### ISSUE TITLE
Qn: What is the best way to shutdown my asp.net core 2.2 app started using dotnet

### ISSUE THREAD

**Issue by saxenark** [dotnet/aspnetcore#10261]
Hi,

I run tests on my server after hosting the .net core 2.2 app using dotnet myapp.dll. After my tests are completed, what is the best way to stop this app and return back to the command prompt. My environment is VS 2017, ASP .NET core 2.2 and Windows Server 2016

Thanks,

**Comment by gfoidl** [comment]
`Ctrl + C` or `SIGTERM`.

`dotnet myapp.dll` should print `Application started. Press Ctrl+C to shut down.` to the command window.
_SIGTERM_ is for use in services (linux, daemon like systemd).

**Comment by anurse** [comment]
Yep, @gfoidl is correct. If you need to "remotely" shut down the app (i.e. when you don't have access to the console) it's up to you to build logic in to your app to do that. You can use the [`IApplicationLifetime`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime?view=aspnetcore-2.2) service in DI to stop the application in response to some event you define.

Putting this in discussions since there isn't actionable work for us. If that changes during the thread, we can re-evaluate.
