### ISSUE TITLE
API Auth via IdentityServer

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#10335]
details TBD but likely just adds IdentityServer & JWT middleware then

**Comment by SidShetye** [comment]
There is a related [ticket open](https://github.com/aspnet/AspNetCore.Docs/issues/11318) on the ASP.NET documentation about API security of an ASP.NET api application using IdentityServer (plus an SPA using said APIs). 

The current VS templates are using the deprecated OAuth2 `implicit flow` instead of the OAuth2 OIDC `PKCE` flow. OAuth 2 is fairly complicated so if the ASP.NET API + authentication templates don't supply a simplified "pre-wired" starting point, it will simply promote bad practices. This "pre-wired" template is especially important because currently identity server 4's documentation is broken against ASP.NET 3.0, adding even more pain.

**Comment by Pilchie** [comment]
Ping on this, since it's currently in Preview7, which doesn't seem likely at this point.

**Comment by Pilchie** [comment]
Moving to backlog since nothing has happened here.

**Comment by HaoK** [comment]
@blowdart is this tracking future work still?

**Comment by blowdart** [comment]
Closing, because the whole thing needs a rethink anyway :)
