### ISSUE TITLE
UseRewriter on Linux/Apache2 gives The page isn’t redirecting properly

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#10543]
As I'm deploying on Ubuntu/Apache2, it works if I use this in Configure method using .NET Core 2.2

`app.UseHttpsRedirection();`

If I use this instead, however, the web server fails to work at all

`app.UseRewriter(new RewriteOptions().AddRedirectToHttpsPermanent());`

The Kestrel service log looks fine, but any request results in

> The page isn’t redirecting properly
> 
> An error occurred during a connection to www.emergenceguardian.com.
> 
>     This problem can sometimes be caused by disabling or refusing to accept cookies

How can I work around this issue?

By the way, whenever I update the application files, do I need to manually restart with 'systemctl restart website.service' every time or is there an easier way?

Here's my website configuration file

```
<VirtualHost *:80>
  ServerName www.emergenceguardian.com
  ServerAlias emergenceguardian.com

  Redirect permanent / https://www.emergenceguardian.com/
</VirtualHost>

<VirtualHost *:443>
  ServerName emergenceguardian.com
  ServerAlias www.emergenceguardian.com
#  DocumentRoot /var/www/emergenceguardian.com
  Documentroot /var/www/spiritualselftransformation.com/
   DirectoryIndex default.aspx index.aspx index.php index.html

  <Directory "/var/www/spiritualselftransformation.com/">
    Require all granted
    AllowOverride All
  </Directory>

  <Location "/blog">
    SetHandler None
  </Location>

  SSLEngine on
  SSLCertificateFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/www_emergenceguardian_com.2017-2019.crt
  SSLCertificateKeyFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/privateKey.key
  SSLCertificateChainFile /etc/ssl/certs/comodo.bundle
  SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
  Protocols h2 http/1.1

  <LocationMatch ".*\.php">
    SetHandler application/x-httpd-php
  </LocationMatch>

  ProxyPreserveHost On
  ProxyPass .ht* !
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/

</VirtualHost>

```

**Comment by anurse** [comment]
Can you post a sample project that reproduces the problem so we can run it and try it out, including your Apache configuration?

**Comment by mysteryx93** [comment]
When I open in Chrome, it tells the error when using redirection middleware: ERR_TOO_MANY_REDIRECTS

Also, with UseHttpsRedirection, I see this in the log

> Jun 01 07:53:42 localhost kestrel-sa[9148]: warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
> Jun 01 07:53:42 localhost kestrel-sa[9148]:       Failed to determine the https port for redirect.
>

**Comment by anurse** [comment]
> Jun 01 07:53:42 localhost kestrel-sa[9148]: Failed to determine the https port for redirect.

This is likely the problem. Can you post a sample project so we can look at the full configuration?

**Comment by mysteryx93** [comment]
I created a new project and all I did was insert the middleware, compiled for Linux and deployed.
[Download the project here.](https://mega.nz/#!7dglkCQb!J1pNGJnA_uVE-eiPXzYYNJcbBkjvBx6RK51ZWaVRnwk)

Here's the Apache2 configuration file

```
<VirtualHost *:80>
  ServerName www.emergenceguardian.com
  ServerAlias emergenceguardian.com
  Redirect permanent / https://www.emergenceguardian.com/
</VirtualHost>

<VirtualHost *:443>
  ServerName www.emergenceguardian.com
  ServerAlias emergenceguardian.com
  Documentroot /var/www/emergenceguardian.com/
  DirectoryIndex index.php index.html

  # .NET
  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/

  # SSL
  SSLEngine on
  SSLCertificateFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/www_emergenceguardian_com.2017-2019.crt
  SSLCertificateKeyFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/privateKey.key
  SSLCertificateChainFile /etc/ssl/certs/comodo.bundle
  SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
  Protocols h2 http/1.1
</VirtualHost>
```

and the SystemD configuration

```
[Unit]
Description=test website

[Service]
WorkingDirectory=/var/www/emergenceguardian.com
ExecStart=/usr/bin/dotnet /var/www/emergenceguardian.com/WebApplication1.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=kestrel-eg
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production 

[Install]
WantedBy=multi-user.target
```

**Comment by anurse** [comment]
> ProxyPass / http://127.0.0.1:5000/

This is the problem, the request is arriving at your ASP.NET Core app as an HTTP request, **not** an HTTPS one. If you're using a proxy like Apache you need to configure the forwarded headers middleware so that the app knows what the front-end (Apache in this case) did, such as terminating SSL. See our [docs on hosting ASP.NET Core apps in Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2#configure-a-proxy-server) for more detail.

**Comment by anurse** [comment]
> Redirect permanent / https://www.emergenceguardian.com/

Given this, I don't see why you need ASP.NET Core to rewrite for you at all. Apache is doing the rewriting for you.

**Comment by mysteryx93** [comment]
> `ProxyPass / http://127.0.0.1:5000/`

So what should it be instead?

There's all kinds of other rewriting rules taking place, such as www to non-www, and renamed pages, etc. I've rewritten them all in the Apache2 config file so my website works, but it would have been a lot simpler to use the redirection middleware.

> Redirect permanent / https://www.emergenceguardian.com/

All this does is the same as UseHttpsRedirection which does work.

**Comment by anurse** [comment]
> All this does is the same as UseHttpsRedirection which does work.

Right, but if you do it in Apache you don't need anything in your ASP.NET Core app. No `UseHttpsRedirection`, no `UseRewrite`. Apache handles it entirely.

> So what should it be instead?

It depends on what you **want** to do. If you want Apache to do the redirection, then let Apache do the redirection and just remove all the rewriting/redirection middleware. 

If you want ASP.NET Core to do the redirection then you need to configure the forwarded headers middleware (as described in the doc I linked above) so that ASP.NET Core **knows** that Apache received an HTTPS request. Otherwise, ASP.NET Core is seeing an HTTP request (from Apache) and thinking it needs to redirect to port `443`, but the user-facing URL is **already** on port `443`, thus causing the loop.

The `UseHttpsRedirection` middleware does **not** just do a redirect like this. It **first** checks if you've configured Kestrel to use HTTPS. If Kestrel isn't using HTTPS it **no-ops**, which may be why it appears to be "working" (since I don't see any HTTPS configuration in your code, unless you're running in Development mode and have the dev-cert installed).

The rewrite rule you configured forcibly redirects to port `443` if the request coming in to ASP.NET Core is non-HTTPS. However, because Apache is terminating SSL (and making an unencrypted HTTP request to ASP.NET Core), it does this redirect even when the request actually already came in on port `443`, thus causing a loop.

**Comment by mysteryx93** [comment]
In that case, would removing the HTTPS redirect from the middleware allow to use the other URL rewriting features?

**Comment by anurse** [comment]
What do you mean? Removing that rule certainly wouldn't preclude using the rewriting features of our middleware. However, I would strongly advise just doing the rewriting in **one place**. Having multiple layers of rewrite/redirect rules can cause lots of confusion, like this.

The key thing to remember is that when you are being proxied, your app thinks it is being access by a **local** client (the proxy, Apache in this case) and the request URL is whatever that proxy used to make the request (`http://127.0.0.1:5000/` from your `ProxyPass` directive in this case). There are special headers (the `X-Forwarded-*` headers) that proxies can put in their requests to **tell** ASP.NET Core that there is a proxy in front of them. These headers include the original hostname (`emergenceguardian.com` in your case), the original protocol (`https`) as well as the original client address (the IP address of the actual browser).

If you are going to use a proxy, you should configure the ForwardedHeaders middleware (again, docs are available in our [hosting ASP.NET Core with Apache doc](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2#configure-a-proxy-server)). This middleware should be right near the top of your pipeline and will "rewrite" the request object to make it look like it came directly from the client. That way all your URL generation will "just work" and you can remove the `ProxyPassReverse` directive in your file (since that is telling Apache to try to rewrite URLs in the **response** as well).

**Comment by mysteryx93** [comment]
This is in 000-default.conf, I believe this sets email forwarding for all domains?

```
<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

```

**Comment by anurse** [comment]
I believe it will, you can easily check by examining the headers in a custom middleware **before** the ForwardedHeaders middleware.
