### ISSUE TITLE
[Discussion]: Breaking changes to Microsoft.JSInterop

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#10810]
In 3.0-preview6, we're migrating Microsoft.JSInterop to use the System.Text.Json based serializer. As part of this transition, there are several breaking changes to the JSInterop library:

* The helper type `Microsoft.JSInterop.Json` is being removed. Users may use a JSON serializer of their choice. We recommend using the `System.Text.Json`-based serializer since Blazor already references it. Here's the code change required to migrate to use `System.Text.Json`:

```C#
// Before
string value = Json.Serialize(...);
MyPoco poco = Json.Deserialize<MyPoco>("...");

// After
using System.Text.Json.Serialization;
...

string value = JsonSerializer.ToString(...);
MyPoco poco = JsonSerializer.Parse<MyPoco>("...");
```

* `DotNetObjectRef` is replaced by a generic `DotNetObjectRef<T>` that is required for both sending and receiving a managed object reference when doing interop with the browser
    
```C#
// Before
IJSRuntime.InvokeAsync("SomeJSMethod", new DotNetObjectRef(someObject));

[JSInvokable]
public static Task SomeDotNetMethod(MyObject myObject)
{
    ...
}

// After
IJSRuntime.InvokeAsync("SomeMethod", DotNetObjectRef.Create(someObject));

[JSInvokable]
public static Task SomeDotNetMethod(DotNetObjectRef<MyObject> myObject)
{
    ...
}
```

* Microsoft.JSInterop will use System.Text.Json to marshal interop data. To customize serialization, you may use serialization primitives such as `JsonPropertyNameAttribute`, `JsonIgnoreAttribute ` etc.

* `IJSRuntime.UntrackObjectRef(DotNetObjectRef);` has been removed. To stop tracking an object reference, dispose the `DotNetObjectRef<T>` instance either on the server or the client.

**Comment by Joelius300** [comment]
I switched from the `System.Text.Json`-based serializer back to json.net following [these ms-docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0). I'm using a server-side blazor project (preview6) and called `AddNewtonsoftJson` on the `IMvcBuilder` I got back from `services.AddRazorPages()` in the `ConfigureServices` method.  

The problem is that it still uses the `System.Text.Json`-based serializer when invoking javascript using `IJSRuntime.InvokeAsync`. I have already opened a [SO question for this issue](https://stackoverflow.com/questions/56915186/ijsruntime-ignores-custom-json-serializer-in-server-side-blazor-project).   

Is the way I change the serializer not correct?   
What do I have to do for `IJSRuntime` to use json.net?
