### ISSUE TITLE
Updating UI for all ASP.NET Core project templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#10883]
Now that we have authentication support for Blazor, it looks pretty odd to have the mixture of styles from the Blazor templates and the default Identity UI. For consistency, we should align the styling of the Blazor templates with the rest of the ASP.NET Core templates, specifically the SPA templates.

**Comment by isaac2004** [comment]
@danroth27 is this for all the blazor templates?

**Comment by danroth27** [comment]
@isaac2004 Thank you for offering to help out! Please hold off for a bit though, as there is some debate how we want to do this.

**Comment by isaac2004** [comment]
@danroth27 sounds good let me know. I have been closing out the open template issues and thoughts this was a high priority one.

**Comment by danobri** [comment]
Any update on this?  Is there a straight forward way to modify the project so all the pages are using the same layout?

**Comment by danobri** [comment]
Also - if you scaffold  any of the Identity pages in order to override the default behavior, you get additional weirdness.  The Blazor layout gets wrapped in the Identity layout.  I was able to fix by removing some of the files that were added in the scaffolding, but figured it was worth mentioning.  Given that I am new Blazor, Razor Pages, and Identity, it's not clear to me why the identity pages aren't using the layout defined in the template.  I would appreciate assistance - trying to get a proof of concept up and running in order to pitch Blazor for an upcoming project.

**Comment by acorrow** [comment]
@danobri Can you detail what you did here? I'm not looking for anything too special, just trying to scaffold the Identity to get around this style, and hitting prob all the same roadblocks you did/are. Any process you had to get a scaffolded Identity working would be great! Thanks!

**Comment by acorrow** [comment]
Also, the stuff @danobri is describing (and what I'm seeing) isn't so much a feature request as a bug in the existing Blazor Identity Scaffolding. I can see the idea of matching the style, but in any case regardless of what you do here, shouldn't "Scoffolding out of the box doesn't work" be a bug as well? I can't see to find it anywhere.

**Comment by danobri** [comment]
@acorrow I ultimately abandoned using Blazor for my project, and am just using Razor Pages instead.  Something to keep in mind is that there is no SPA implementation for the Identity pages, so even if you get the templates playing nicely together, all the identity pages will be standard web pages instead of a SPA like the rest of your application.  The Identity pages are a significant portion of the application I am working on, so it didn't seem worth the headache to integrate with a SPA framework.  Will definitely try Blazor again in the future as it becomes more mature.

**Comment by mkArtakMSFT** [comment]
Closing this as we will be handling any work for 5.0 through targeted issues.
