### ISSUE TITLE
Question: Multiple hubs on 1 server

### ISSUE THREAD

**Issue by captmomo** [dotnet/aspnetcore#11372]
Hi,  
I plan on mapping two hubs to two different routes on my server.  For example:
```

app.UseSignalR(routes =>
{
      routes.MapHub<ReaderHub>("/ReadHub");
      routes.MapHub<WriterHub>("/WriterHub");
});
```

Is this ideal and are there any drawbacks to this method? I plan on allowing a page to connect to only 1 hub at a time.  
The only documentation I could find was for the ASP.NET version  
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#multiplehubs  
  
Thank you.

**Comment by anurse** [comment]
ASP.NET Core SignalR definitely supports multiple hubs per server, but unlike ASP.NET SignalR these hubs **do not share connections**. This means that if you do connect to multiple hubs on the same page, the client will be using multiple connections. There's no inherent problem with that, it just means it takes two separate TCP connections.

In your case, since you only plan to connect to 1 hub at a time, there's absolutely no problem with having multiple hubs. Are you seeing an error or problem?

**Comment by captmomo** [comment]
That's great to hear. As of now, I'm not experiencing any errors related to multiple hubs. Just wanted to ensure I'm aware of any drawbacks.
