### ISSUE TITLE
Xamarin Razor Component Application

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#11471]
It would be nice to run Razor Component Application as Xamarin Application with ability to use Xamarin API
Xamarin has WebView and it is possible to run Razor UI in Xamarin

Similar issue was create https://github.com/xamarin/Xamarin.Forms/issues/5069

**Comment by Eilon** [comment]
If anyone ends up looking into this, I'd like to be involved in the discussion.

**Comment by SteveSandersonMS** [comment]
It's a cool idea! So far, it's not something we've specifically got into any detail thinking about because for the time being, we need to focus entirely on regular web browser scenarios in order to deliver that on time for the 3.0 release.

Technically it should be possible to use the [same technique we've used for Electron](https://github.com/aspnet/AspLabs/tree/master/src/ComponentsElectron) to host a Blazor UI inside a Xamarin app, and have the .NET code run "natively" (per whatever that means for Xamarin, as opposed to on WebAssembly) so you can access all the native APIs directly. However there are probably various extra complications around hooking into the Xamarin build process to make it work with their AOT system, which I've no idea about right now.

**Comment by YordanYanakiev** [comment]
I got some not yet completed idea. Maybe someone will complete it:
-Xamarin to provide a native container (not web view), and Blazor to drop his DLL's, and then render them inside the device as a Forms application (kind of)..
( maybe this will lead to somehow merging XAML with RAZOR - I am not yet sure).

**Comment by mkArtakMSFT** [comment]
Moving into the `5.0.0-preview1` to see how will we be tracking the investigation of this in 5.0 timeframe.

**Comment by Eilon** [comment]
Tune in this Tuesday to see some exciting demos!

https://focus.dotnetconf.net/Agenda

![image](https://user-images.githubusercontent.com/202643/72177796-560c9e80-3396-11ea-9648-6c382e94eb06.png)

**Comment by mkArtakMSFT** [comment]
Closing as this is tracked in an external repo: https://github.com/xamarin/mobileblazorbindings
