### ISSUE TITLE
Identity Cookie expiry not being respected

### ISSUE THREAD

**Issue by siada** [dotnet/aspnetcore#12233]
### Describe the bug
I'm trying to create a long-timeout cookie for Identity that will leave a user logged in for at least 30 days (should refresh after 15 days)

This is the identity+cookie configuration:

```
            services.ConfigureIdentity();

            services.ConfigureApplicationCookie(x =>
            {
                x.SlidingExpiration = true;
                x.ExpireTimeSpan = TimeSpan.FromDays(30);
                x.LoginPath = new PathString("/login");
            });

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(opt =>
                {
                    opt.SlidingExpiration = true;
                    opt.ExpireTimeSpan = TimeSpan.FromDays(30);
                    opt.LoginPath = new PathString("/login");
                    opt.Cookie.SecurePolicy = CookieSecurePolicy.None;
                    opt.Cookie.Expiration = TimeSpan.FromDays(30);
                });
```
What is happening is that a cookie is set with the correct expiry, but after 30 minutes the application explicitly removes the cookie on it's own:

```
Set-Cookie: .AspNetCore.Identity.Application=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
```

### To Reproduce
1. Using this version of ASP.NET Core: 2.2

Using the above samples

### Expected behavior
A cookie that lasts as the very least more than 30 minutes

### Screenshots
![image](https://user-images.githubusercontent.com/177663/61289287-e770ce80-a7c0-11e9-962c-5a01f4c0d0ea.png)

![image](https://user-images.githubusercontent.com/177663/61289343-08392400-a7c1-11e9-9b0c-784aac3b8bf5.png)

**Comment by HaoK** [comment]
That behavior is likely due to the security stamp validation that's looking for a user's security stamp within the cookie, you disable that check if you aren't using the security stamp via its options: https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Core/src/SecurityStampValidatorOptions.cs#L20

**Comment by siada** [comment]
That seems to have done the trick, what's the purpose of this though?

Why do we have the ability to change the cookie expiry if eventually the _actual_ expiration is overridden by the SecurityStamp validator.

I feel like I'm missing part of the point

**Comment by blowdart** [comment]
Security stamps don't expire the cookie, but they invalidate its contents. The stamp is updated when information in the user profile is changed that could affect the UI or authorization (e.g. a new claim is added).

**Comment by siada** [comment]
To the best of my knowledge nothing is being _changed_ during that time period, the only information that gets periodically updated is FullName (not an identity property) and IsDeleted (again, not identity)

So I don't know what is causing the security stamp to be changed, is there any way to track this down?

**Comment by arisliang** [comment]
I also encounter similar issue where security stamp validator affects the cookie expiry time. There is nothing changed in the user, because I set the ValidationInterval to 0 or a few seconds, and every time a simple request would cause the auth cookie expiry time extended.

Keep extending the cookie expiry is a security issue. Disable ValidationInterval would introduce another security issue.

To my understanding of the documentation, when it validates true, it does nothing; if validates false, it signout the user. But why does security stamp validator extend cookie expiry time?
