### ISSUE TITLE
ASP.NET Identity Core 2.2 - Suppress "There are no external services ..." 

### ISSUE THREAD

**Issue by aveer28** [dotnet/aspnetcore#12303]
### Describe the bug
ASP.NET Core 2.2. introduced internal Razor pages that provide default login, register etc. The default login page states:

```
There are no external authentication services configured. See this article for details on setting up this ASP.NET application to support logging in via external services.
```

This is not a production friendly message and there is no way to disable it via API. Please consider removing it as it provides no real value to be displayed to end user

### To Reproduce
1. Using ASP.NET Core 2.2
2. Scaffold an MVC project using `dotnet new mvc -o <name> --auth Individual`
3. Follow the standard setup i.e. add migrations, update database 
4. Visit https://localhost:5001/Identity/Account/Login

### Expected behavior
The above mentioned message should not be displayed. Alternatively it should be possible to turn it off. 

### Screenshot 

![image](https://user-images.githubusercontent.com/50499234/61443409-b2dc4e80-a949-11e9-8378-7b8622269f04.png)

**Comment by aveer28** [comment]
This SO article describes a workaround - https://stackoverflow.com/questions/55496631/asp-net-core-mvc-2-2-login-without-external-login-providers

IMO, this should be unnecessary as it defeats the purpose of the internal razor pages (i.e. reducing complexity and allowing security updates_

**Comment by blowdart** [comment]
@HaoK how hard would an option to suppress this be in 3.1?

**Comment by HaoK** [comment]
This is something where the ability to scaffold a few pages is ideal (only the login page /  manage page) and delete that text from the view.  Thoughts @ajcvickers ?

**Comment by aveer28** [comment]
Yes but if the aim of the Razor Class Library is to support users who dont
need to customize their pages, then this message defeats the purpose. I
cannot think that many (if any) users would want this message displayed.
This message is a developer message and is misleading to end users.

Thus it should be removed by default.

**Comment by blowdart** [comment]
@aveer28 I rather agree with you. Are there other things you'd like hidden in the UI by config rather than scaffolding?

**Comment by aveer28** [comment]
That was all that I came across that could be removed.

However it would be useful if RCL allowed you to disable 2 factor auth from
the GUI if the feature isn't being used.

**Comment by blowdart** [comment]
If you have mfa disabled it shouldn't be appearing in the default UI. Are you saying it is?

**Comment by blowdart** [comment]
We'll look at this after 3.0 releases

**Comment by Webreaper** [comment]
Just coming to this and it seems a major limitation. I'm building an app that's using Identity to handle user accounts. However, since this is all for an intranet-based Blazor Server app, I don't want:
- Profile management/deletion (I have my own admin screen for this)
- 2FA
- External services
- Other stuff which I may not have even stumbled across yet.

In particular, it seems like having support for external services is an extremely '[marmite](https://dictionary.cambridge.org/dictionary/english/marmite)' option; I'd suggest a large proportion of people building apps don't have any interest in their users registering with Google/FB/MSFT/etc. 

Currently, after quite a lot of searching, the only solution to remove all of this is apparently to scaffold some 20+ pages in my app, and then override the functionality to disable them. This means I'm adding code, in order to switch functionality off - which is pretty horrible from a maintenance perspective. It also means that if ASP.Net Identity adds more features/pages in future, I have to a) know about them and b) scaffold / disable them, otherwise I could be risking maintenance hassles (or, worse still, security holes). 

It's even more painful in VS for Mac / VS for Mac 2022 Preview, because the scaffolding UI is very limited, so I'm forced down to the command-line to try and align the runes that make dotnet CLI scaffolding work for a 20-project solution with a bunch of complex DbContext structures.

Feels to me like we need some configuration - something like this: 
```
            services.AddDefaultIdentity<AppIdentityUser>(options => options.IdentityPages = new IdentityPagesOptions
                                                                        {
                                                                            Enable2FA = false,
                                                                            EnableRegster = false,
                                                                            EnableProfileMgmt = false
                                                                        } );
```
so that all this great built-in functionality - which I don't want :) can be disabled trivially. Even better would be if there was an Opt-In pattern available, where everything is disabled unless I explicitly enable it, so perhaps:
```
            services.AddDefaultIdentity<AppIdentityUser>(options => options.EnabledIdentityPages = 
                                                                        new List<IdentityPages> {  Login, LogOut, Register } );
```

**Comment by Webreaper** [comment]
> If you have mfa disabled it shouldn't be appearing in the default UI. Are you saying it is?

I don't have MFA enabled in my app, and I get this on the Account/Manage screen (excuse the formatting, I'm mid-way through re-styling the Identity pages).

<img width="338" alt="Screenshot 2021-08-18 at 09 47 28" src="https://user-images.githubusercontent.com/4901102/129867934-b2127300-1065-4d2f-af7c-ddd5c4432907.png">

<img width="293" alt="Screenshot 2021-08-18 at 09 47 39" src="https://user-images.githubusercontent.com/4901102/129867931-6ae149f4-8dd1-49a3-bca4-9c3b42a13e92.png">

**Comment by HaoK** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/18164
