### ISSUE TITLE
Consider removing ... from TagHelperDescriptor.Name if it is an indexer

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#12380]
E.g, for `@bind-...`,
THD.Name is currently `@bind-...`. It should instead be `@bind-`. The code that displays this descriptor in completions should then special case indexer descriptors and append `...` before showing.

Note: This requires a change from WTE so may not be worth the effort. This isn't affecting any functionality right now and is like a clean up item.

cc @NTaylorMullen

**Comment by rynowak** [comment]
Hmm - what's the impact of doing this change? is it just clean up?

I'd kinda rather not do it if that's the case because using tag helpers to represent components is already a hack - it's a little odd to try and align all of the concepts when they will never really be aligned because they behave differently.

**Comment by ajaybhargavb** [comment]
> Hmm - what's the impact of doing this change? is it just clean up?

Yup
