### ISSUE TITLE
Issue in Data Annotations Localization factory

### ISSUE THREAD

**Issue by Mah3** [dotnet/aspnetcore#12412]
I follow the documentation for DataAnnotation Localizaztion

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#using-one-resource-string-for-multiple-classes

for the below snippet of code

```
public void ConfigureServices(IServiceCollection services)
{
            services.AddMvc()
                    .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                    .AddViewLocalization(options => { options.ResourcesPath = "Globalization"; })
                    .AddDataAnnotationsLocalization(options => options.DataAnnotationLocalizerProvider = (type, factory) =>
                    {
                        return factory.Create(typeof(SharedResources));
                    });
}
```

When put the **SharedResource** in another library, it maintain the sub-path of the configuration of AddViewLocalization ,it dosn't work until i remove ResourcePath for AddViewLocalization or put the SharedResource and its corresponding class on a folder named Globalization.

I think that the options of AddViewLocalization must be for AddViewLocalization  and not affect AddDataAnnotationsLocalization options

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Mah3.
@ryanbrandenburg can you please look into this and see what's causing this behavior? Thanks!

**Comment by Mah3** [comment]
Dears,

I just upgrade my project to core 3.1
and I face something related to this issue, 

```
            services.AddControllersWithViews())
            .AddViewLocalization(options => { options.ResourcesPath = "Resources"; })
            .AddDataAnnotationsLocalization(options => options.DataAnnotationLocalizerProvider = (type, factory) =>
            {
                return factory.Create(typeof(DataAnnotationResource));
            })
            .AddNewtonsoftJson();
```

DataAnnotationsLocalization  dosn't work till I remove `options => { options.ResourcesPath = "Resources"; }`

**Comment by os1r1s110** [comment]
Just faced the same issue as @Mah3, which is partially fixed by removing the `{ options.ResourcesPath = "Resources"; }` part, but in this case, it's the rest of localization that is broken... 

Has there been any fix found for this issue?

**Comment by os1r1s110** [comment]
Seems like this issue is related to #17960, in which @pranavkm has mentioned it's a change in the SDK that causes this issue and was supposedly working on a statement (which I hadn't find yet).

Would it be possible to have more details (here or in the other issue) about the changes? As in my case, I can't make both work (data annotations localization and view localization/string localizer) and I'd like to investigate.

**Comment by os1r1s110** [comment]
After searching more, I also found a link with issue #17269, which seems to point to a problem with VS and not necessarily with asp.net core.

**Comment by os1r1s110** [comment]
Finally after finding [this issue](https://github.com/microsoft/msbuild/issues/4996#issuecomment-581647925), it seems like this is expected behavior (following a desired breaking change, but does not seem documented in the [breaking changes list](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0)).

Hence as recommended in the issue above, I will link the related docs issue here [#16964](https://github.com/dotnet/docs/issues/16964)

**Comment by TanayParikh** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
