### ISSUE TITLE
Background Service to early up and running

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#12501]
following code fails with NullReferenceException

```C#
 protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var path = Path.Combine(AppDomain.CurrentDomain.GetData("WWWBaseDirectory").ToString(),
                "wwwroot\\videos"); ;
```

the reason is (my guess) the pipeline is not configured  
```C#
   public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            AppDomain.CurrentDomain.SetData("WWWBaseDirectory", env.ContentRootPath);
```
Cause
```C#
     services.AddHostedService<VideosWatcher>();
```
runs earlier

**Comment by davidfowl** [comment]
@hannespreishuber Can you provide the actual error and call stack?

**Comment by davidfowl** [comment]
Yes this was an intentional breaking change that was made https://github.com/aspnet/AspNetCore/issues/11437.

A couple of things you can do:
- Inject the `IHostEnvironment` or `IWebHostEnvironment` into the `VideosWatcher`.
- Add the hosted service in `Program.cs` after calling `ConfigureWebHostDefaults`

cc @Tratcher @anurse
