### ISSUE TITLE
Where are ETags stored?

### ISSUE THREAD

**Issue by RPM1984** [dotnet/aspnetcore#12560]
Hi there! 👋 

Just reading about the [Response Cache Middleware](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2), and the relevant [source code](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/ResponseCaching/src/ResponseCachingMiddleware.cs), but i can't see how the ETag is generated.

Can someone please explain how the ETag generation works, and link to the relevant code?

Thanks!

**Comment by Eilon** [comment]
I believe it's comparing the ETag header in the new incoming *request* to the ETag header that was *sent* in the original *cached response*. So, the ETag is always generated by the app itself, using whatever logic it sees fit (e.g. some sort of timestamp or content hash).

**Comment by Tratcher** [comment]
Right, response caching doesn't generate e-tags, it uses the ones provided to it. What are you using to generate the original response?

**Comment by RPM1984** [comment]
Thanks for the quick reply guys! Makes sense..so I just need to set the Etag response header in my controller code. Easy.

One more question: why does the middleware need a cache? We always need to fetch the resource from the underlying store in order to check whether the Etag version is still the same right, and the controller would always send both the Etag and the response...so what is actually being cached and why?

**Comment by Tratcher** [comment]
@JunTaoLuo want to take this one?

**Comment by JunTaoLuo** [comment]
Hmm I'm not sure what the question is.

 The content and etag generated by the controller is stored in the cache. On subsequent requests, the content and etag are retrieved together. Based on the request's etag headers and the etag of the retrieved from the cache, we might send a 304 or send the cached content.

**Comment by RPM1984** [comment]
@JunTaoLuo thanks for jumping in on this. 🙂

> we might send a 304 or send the cached content

This is the part that confuses me. Are you suggesting the middleware might return a 200 with the cached content? Unless I'm totally off (probably am) isn't this outside the scope of how etags should work?

I thought with etags, the server should always check the Etag provided matches what the _current_ version is. So, how would the cache in the middleware know this is the case? What if the response is cached in the MW, then the resource is updated before the cache clears?

**Comment by JunTaoLuo** [comment]
We have a bit more details on how the middleware operates given specific HTTP headers here: https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2#http-headers-used-by-response-caching-middleware

Scenario 1: send 304
1. Client A retrieves a resource with etag `Tag1` from the server
2. Client A sends a request for the same resource with the header `If-None-Match: Tag1`
3. Server sends 304 if the resource is still cached in the response caching middleware since the etag of the cached response matches the `If-None-Match` header.

Scenario 2: send cached content
1. Client A retrieves a resource with etag `Tag1` from the server
2. Client B sends a request for the same resource with the `Cache-Control: no-cache` forcing the cache to be invalidated and a new resource to be generated with etag `Tag2`. The response caching middleware caches the content for etag `Tag2`.
3. Client A sends a request for the same resource with the header `If-None-Match: Tag1`
4. Server sends 200 with the cached content with etag `Tag2` if the content is still cached in the response caching middleware since the etag of the cached response does not match the `If-None-Match` header.

> What if the response is cached in the MW, then the resource is updated before the cache clears?

There's currently no good way on the server to invalidate the cache and we rely on expiration to ensure content doesn't get too stale. The purpose of the cache is to reduce the need for the server to process every request. It does not guarantee that each request gets the latest content and some staleness is expected.

**Comment by JunTaoLuo** [comment]
I'm closing this since it seems like all questions have been answered.
