### ISSUE TITLE
File path IntelliSense adds ~ preceding the directory (for Blazor)

### ISSUE THREAD

**Issue by salmanmkc** [dotnet/aspnetcore#12930]
### Describe the bug
Say if I want to add the source of an image and I rely on IntelliSense to complete the directory for me, it adds a ~ at the beginning of the file path. This will not load the file, and if you remove the ~ it works. I believe this was an issue over a year ago, however it was closed, perhaps it was solved, but IntelliSense itself still adds the ~ to the beginning for users.

### To Reproduce
1. Using this version of .NET Core '3.0.100-preview7-012821'
2. Paste this code in, and have the necessary filename in the directory that is being referenced, retype the filepath but let IntelliSenseautocomplete the directory on the final bit 
![image](https://user-images.githubusercontent.com/32169182/62582356-0b956c00-b8a4-11e9-9f9f-67855b06e9f5.png)
3. You can see that ~ was added preceding the directory
![image](https://user-images.githubusercontent.com/32169182/62582372-13eda700-b8a4-11e9-889b-40bed4b0df8a.png)
4. Try run the web application
5. It wont work
6. Remove the ~
![image](https://user-images.githubusercontent.com/32169182/62582375-1c45e200-b8a4-11e9-8e5a-4d34c60e7071.png)
7. It works

### Expected behavior
That it shouldn't have the ~ added with IntelliSense

### Screenshots
This is what works
![image](https://user-images.githubusercontent.com/32169182/62582337-f8829c00-b8a3-11e9-9f36-ca1cb403f4e0.png)

### Additional context
Sorry if it's already been reported, couldn't find it anywhere

**Comment by salmanmkc** [comment]
This is for Blazor, which I didn't mention in the post

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @salmanmkc.
@jodavis can you please handle this one? The `~/` should be missing for `.razor` files after completion.

**Comment by SteveSandersonMS** [comment]
Example of an expected tag:

    <img src="somedir/file.png" />

Note how the value does *not* start with either `~/` or `/`, since the URLs should be base-relative, not root-relative.

**Comment by jodavis** [comment]
We can take a look at this.

@mkArtakMSFT (or others) - How does Blazor handle URLs in layout pages? The reason we default to app-relative ("~/") URLs is because we can't always predict what the base URL of a file is going to be, especially in a layout page where the base URL changes depending on the page using the layout, or in a routing situation where "localhost/" and "localhost/Index" can refer to the same page.

In a sample app, I see something is setting `<base href="/" />` in the page. Is that configurable, or is it guaranteed to be there in all Blazor apps?

**Comment by SteveSandersonMS** [comment]
> In a sample app, I see something is setting <base href="/" /> in the page. Is that configurable, or is it guaranteed to be there in all Blazor apps?

It is there in the templates, and it's the developer's responsibility to keep it there and/or update it to whatever base URL they are using. Since `.razor` files are primarily for use in SPAs, base-relative routing is standard everywhere in the framework.

**Comment by salmanmkc** [comment]
> Thanks for contacting us, @salmanmkc.
> @jodavis can you please handle this one? The `~/` should be missing for `.razor` files after completion.

No problem! Thanks for getting back so soon ☺

**Comment by jodavis** [comment]
I see it now. I don't know why I didn't find the _Host.cshtml file when I searched earlier.

That makes things a little complicated for the editor. From the context of a component, we don't really know what page the component will be hosted in, so we can't really know what the base URL will be when completing a URL.

We could assume that the base maps to the wwwroot folder, and make URLs relative to that. If the user customizes their base URL, then the editor will start inserting the wrong URLs. Would that be a reasonable compromise? How common do you think it will be for users to customize their base URL?

**Comment by SteveSandersonMS** [comment]
> We could assume that the base maps to the wwwroot folder

👍 That's what to do.

If the user changes their base URL, they reason they will do that is because they are hosting the entire site on some non-root path. And in that case, the wwwroot *still* corresponds to the base URL.

Example: for a site hosted at `http://domain/mydir/`, the base URI would be `/mydir/`, so the file in `wwwroot/a/b/c.gif` would be reachable at the URL `http://domain/mydir/a/b/c/gif`, which as a base-relative URL is still `a/b/c.gif`. So in summary you can ignore what the base URI actually is.

If a user creates a more nonstandard setup where the base URI doesn't match the site's content root, they will have other problems to solve too and the tooling isn't expected to know about that.
