### ISSUE TITLE
Reduce Data Flow

### ISSUE THREAD

**Issue by kevinjhang** [dotnet/aspnetcore#13025]
### Is your feature request related to a problem? Please describe.
I am trying to do reduce data flow

### Describe the solution you'd like
Rename "JS.RenderBatch" to "JS.RB"

### Additional context
![2019-08-10 184143](https://user-images.githubusercontent.com/22629524/62820943-cc666400-bb9e-11e9-8866-aaaee6a53cce.jpg)

**Comment by kevinjhang** [comment]
Maybe rename to "R" is better, It's shorter

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kevinjhang.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by aaronhudon-ts** [comment]
I'd also like to chime in here.  Forgive me if I'm incorrect, but monitoring the websocket messages received, it appears that a large amount of white-space is included in the message payload.  I don't know if IIS optimizes this out or not, but I thought I'd ask for clarification.  
![image](https://user-images.githubusercontent.com/49655238/70821142-3c743900-1d8f-11ea-932e-dee54b4a78e3.png)

**Comment by SteveSandersonMS** [comment]
Blazor Server's renderbatch wire format is already pretty heavily optimized. You can find the implementation at https://github.com/dotnet/aspnetcore/blob/master/src/Components/Server/src/Circuits/RenderBatchWriter.cs.

If you're interested in submitting a PR to optimize this further we'd certainly be interested.

> Rename "JS.RenderBatch" to "JS.RB"

We'd need a stronger, more quantified justification in order to do that. Do you have a reasonable application that returns large renderbatches in which this change would make more than (say) 1% of difference? I'd be surprised if, in large renderbatches which need to be optimized, this change would have any noticeable effect.

Thanks for the suggestion though!

**Comment by kevinjhang** [comment]
[TCPStream-1.txt](https://github.com/dotnet/aspnetcore/files/5382686/TCPStream-1.txt) (32,782 bytes)
[TCPStream-2.txt](https://github.com/dotnet/aspnetcore/files/5382687/TCPStream-2.txt) (31,513 bytes)
TCPStream-2.txt = TCPStream-1.txt.Replace("RenderBatch","RB")
difference(%) = (32782-31513) / 32782 * 100% = 3.871%

**Comment by SteveSandersonMS** [comment]
@kevinjhang Thanks

**Comment by mkArtakMSFT** [comment]
Closing this as https://github.com/dotnet/aspnetcore/issues/35897 is going to give us more benefits and basically obsolete this specific ask.
