### ISSUE TITLE
Kestrel: handling of FIN comming from client

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/aspnetcore#13188]
This issue has been talked about in the archived repo `aspnet/KestrelHttpServer` [SocketTransport: FIN handling](https://github.com/aspnet/KestrelHttpServer/issues/1774) but I'm not sure what the outcome is. I've search for commits mentioned in [issue 1774](https://github.com/aspnet/KestrelHttpServer/issues/1774) in this repo but found nothing.

My problem is that a TCP client is making an HTTP POST request to an ASP.NET Core WebAPI. After getting back an `ACK` the client sends immediately `FIN, ACK`. Subsequently, Kestrel closes the connection so the client does not get the response. Although the corresponding MVC action finishes and returns an `IActionResult`. No error/warning is raised on the server-side.

Lib: Microsoft.AspNetCore.App: 2.2.6
Runtime: netcoreapp2.2
OS: Windows 10 x64
SDK: 2.2.301

You can see the actual behavior in this screenshot of the communication captured with wireshark. Port 51852 is the client initiating the connection. Port 6200 is Kestrel. 

![image](https://user-images.githubusercontent.com/7135790/63166557-0b793700-c02f-11e9-8842-4640a141bb1e.png)

I tested the same a client with a mock service (SoapUI) that provides the expected behavior.

![image](https://user-images.githubusercontent.com/7135790/63166789-b5f15a00-c02f-11e9-8534-826465514b1a.png)

---------------------

By the way: using HttpSys an exception is thrown if my action returns, i.e. both servers have different behavior.

```
 Microsoft.AspNetCore.Server.HttpSys.MessagePump[0]
      ProcessRequestAsync
System.InvalidOperationException: Headers already sent.
   at Microsoft.AspNetCore.Server.HttpSys.Response.CheckResponseStarted()
   at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.ConsiderEnablingResponseCache()
   at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.OnResponseStart()
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)
```

**Comment by halter73** [comment]
Kestrel currently treats the connection as fully aborted as soon as it receives a FIN. That's because thats how most HTTP clients abort connections. If you want to keep the connection open to receive a response, the client must wait to receive the response before sending a FIN.

However, for more generic TCP scenarios, we should look at supporting half-closed connections. @mconnew

**Comment by claudioesposito** [comment]
It looks current Kestrel behaviour correpond more to RST.  FIN should notify to the server that the client has no more information to send but still give a chance to send an answer.
BTW we tried the same scenario using Apache as reverse proxy, and it works "correctly".
In our use case we would not need to use Apache as both client ans server are on the same server.
-Claudio

**Comment by halter73** [comment]
@claudioesposito When I started working on Kestrel, I agreed with you. Kestrel used to support writing a response after the client sent a FIN. After all, why shouldn't you be allowed to continue sending a response if the client just closed its sending half of the TCP connection?

It turns out, that sending a FIN is [the common way for HTTP clients to abort a request](https://github.com/aspnet/KestrelHttpServer/issues/1139#issuecomment-251748845). Sure HTTP clients could abort the request by completely closing the socket which would eventually result in RSTs, but in practice not all HTTP clients do that. Even if the client does do that, the RST won't be observed until the server actually tries to write more data after the client closed the socket.

> My problem is that a TCP client is making an HTTP POST request to an ASP.NET Core WebAPI. After getting back an ACK the client sends immediately FIN, ACK.

You mentioned that you're using a TCP client instead of an HTTP client. I still have not found any HTTP clients that will send a FIN prior to reading the entire response. Last I checked, nginx also immediately aborts the connection upon receiving a FIN. https://github.com/aspnet/KestrelHttpServer/issues/1774#issuecomment-297826280

**Comment by mconnew** [comment]
@halter73, I could imagine a scenario where an HTTP client using pipelining and a connection pool could send the FIN before the response has been returned. For example, on .NET Framework the ServicePoint class (which manages the connection pool to a particular hostname) has a property ConnectionLeaseTimeout which configures how long a connection can exist before it's closed and removed from the pool. I'm not saying this is how .NET Framework works (I'd have to test to see), but I could imagine a scenario where a FIN is sent before the responses are received under the right conditions.  

When using pipelining, the connection needs to be returned to the pool as soon as the request has been sent to enable another request to reuse the connection. When a connection is returned to the pool, a naive/simple approach (depending on your opinion 😄) is to do a half shutdown when the connection is returned to the pool if the ConnectionLeaseTimeout has been reached. All the responses would still be receivable on the socket and when the final response is received, a pending receive is issued on the socket and the FIN from the server would cause a 0 byte receive and initiate close/cleanup. You should always issue a pending receive on a pooled socket so you know if the remote endpoint closed the socket or reset it, otherwise your first socket usage will be an attempt to send another request which then slows down the next request, especially if you have a lot of closed sockets in your pool.  

On .NET Framework, the default ConnectionLeaseTimeout is -1 which means keep the connection indefinitely. If .NET Framework has the behavior I described, it wouldn't be seen by default. It's possible that there are HTTP client implementations which can send a FIN before the response has been received, just not with the default usage. All you can say is the way HTTP clients work by default, they appear to abort the connection with a FIN.

Although there's an interesting detail I think was missed in the referenced issue, and that is that Chrome initially sends a FIN followed by an RST. That sounds to me like it sends a FIN to tell the server it's finished sending the request, and later aborts it. This is similar behavior to HttpWebRequest on .NETFramework in some scenarios. When a response has been closed when there's still data remaining on the response, if the response content length is known and the amount of data left is below a certain threshold, the remaining response is drained so the connection can be reused and put back in the pool (or if pipelining is being used, so you can get the next response). If the content length isn't known (chunked response), it has a cap of how much data can be drained and will attempt to drain up to that amount of data, and if it doesn't reach the end of the response, it aborts the socket. So it sounds like Chrome attempts to cleanly close the connection, but when draining the response it goes over some size or time threshold and aborts it. I read that behavior as Chrome NOT using FIN as an Abort mechanism.

**Comment by halter73** [comment]
> Although there's an interesting detail I think was missed in the referenced issue, and that is that Chrome initially sends a FIN followed by an RST. That sounds to me like it sends a FIN to tell the server it's finished sending the request, and later aborts it. [...] So it sounds like Chrome attempts to cleanly close the connection, but when draining the response it goes over some size or time threshold and aborts it. I read that behavior as Chrome NOT using FIN as an Abort mechanism.

Not quite. The thing that really pushed us over the edge in deciding to treat FINs as abortive for HTTP requests was the EventSource API behavior of Chrome and Firefox.

EventSource is a browser API that is sometimes used by SignalR and other streaming libraries/apps when better alternatives like WebSockets aren't available. This API predates fetch and allows developers to make a GET request and read a specially-crafted chunked response as each chunk/message arrives.

Browsers do NOT send a FIN as soon as they're done sending the request data for the GET request. Instead browsers send a FIN when the client stops reading using the EventSource API. That means that if you have an app that was sending a new chunk to the browser infrequently (e.g. only once every few minutes), the server wouldn't see an RST until the server actually tried to send the next chunk after receiving a FIN. In practice, web developers want the request to be treated as aborted as soon as the client stops reading. In the case of the EventSource API, you know the client stopped reading as soon as you receive a FIN.

I have yet to find a non-toy HTTP client that sends a FIN prior to reading everything it is trying to read.

**Comment by claudioesposito** [comment]
@halter73 
The client experiencing the behaviour is a c++ application managing radio server messages in a national country scale. I promise: it is not a toy :)
As it's a third party system, we do not have at all access to source code and we don't know what http client it is using.

BTW the scenario of a browser using EventSource with Kestrel server pushing is quite uncommon as it's a good practice to add a reverse proxy in the middle. Haven't seen any non-toy application connect a browser directly to Kestrel.

Again: for the moment Apache makes the job, but we would like to avoid as it's a server to server communication.

-Claudio

**Comment by davidfowl** [comment]
> BTW the scenario of a browser using EventSource with Kestrel server pushing is quite uncommon as it's a good practice to add a reverse proxy in the middle. Haven't seen any non-toy application connect a browser directly to Kestrel.

2 years later lots of people using Kestrel "on the edge" 😉

**Comment by Tratcher** [comment]
> y the way: using HttpSys an exception is thrown if my action returns, i.e. both servers have different behavior.
> 
> ```
>  Microsoft.AspNetCore.Server.HttpSys.MessagePump[0]
>       ProcessRequestAsync
> System.InvalidOperationException: Headers already sent.
>    at Microsoft.AspNetCore.Server.HttpSys.Response.CheckResponseStarted()
>    at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.ConsiderEnablingResponseCache()
>    at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.OnResponseStart()
>    at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)
>    at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)
> ```

This is https://github.com/dotnet/aspnetcore/issues/12194, which happens if there's a race between disconnect and the response. That implies Http.Sys and IIS also treat a FIN as a disconnect.

**Comment by halter73** [comment]
This issue hasn't had any external activity in over a year, and I think we're happy with the current behavior.
