### ISSUE TITLE
3.0 Preview restrictive GetFallbackPolicyAsync raises exception

### ISSUE THREAD

**Issue by mrgleba** [dotnet/aspnetcore#13764]
During our migration tryout we've palyed with ```IAuthorizationPolicyProvider.GetFallbackPolicyAsync()```. Our initial guess was to use a restrict-all policy:
```cs
        public Task<AuthorizationPolicy> GetFallbackPolicyAsync()
        {
            var bp = new AuthorizationPolicyBuilder();
            bp.RequireAssertion(_ => false);
            return Task.FromResult(bp.Build());
        }
```

As far as I understand this should return ```401 Unautorized``` for an unmatched link. Instead this code throws:
```
No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions). 
```

What is the propper way to return ```401 Unautorized``` in this case?

**Comment by blowdart** [comment]
@HaoK in case I get this wrong.

Policies either pass or fail. They don't return status codes, or pages. That's down to the authentication services in place, for example JWT will map a failed authorization to a status code, cookies end up doing a redirect to prompt for a login.

So let's turn this around, what are you trying to accomplish?

**Comment by mrgleba** [comment]
The application is generally an API and it's not expected of the client to go to a login page upon 401.
The scenario we've been trying to achieve is to return ```401 Unauthorized``` when someone asks for a nonexistent resource. 

The mentioned code results in a policy that will always fail and it was my expectation that in such case 401 woud be returned. Instead we're getting an exception.

In the meantime we've figured how to return a 404 wchich is acceptable as a solution. Still an exception is a bit unexpected in this case.

**Comment by blowdart** [comment]
So it's up to the authentication piece to decide what's suitable to return, not the authorization pieces. Which authentication method are you using?

As an aside, if you want to ensure everything requires authentication there's an easier way;

```c#
services.AddMvc(config =>
{
    var policy = new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .Build();
    config.Filters.Add(new AuthorizeFilter(policy));
});
```

**Comment by HaoK** [comment]
The error message you are getting is just that you have no default scheme set, so when it tries to issue a challenge (because your policy always fails), it doesn't know what to challenge,  As barry mentions you need to have some authentication scheme that results in a 401 when its challenged, JwtBearer is one such authentication scheme that results in a 401

**Comment by mrgleba** [comment]
@blowdart In this case we're handling nonexistent ulrs, ones that will fall throught MVC to the final 404 handler, so MVC filters won't help.

@HaoK That clarifies the issue, still the provided solution is IMHO far from ideal. Inserting a ```JwtBearerHandler ``` here would lead to a confusing code (any other person reading the code would suppose we're using Jwt). Also ```JwtBearerHandler``` would have to be instantiated to be passed in to the ```AuthorizationPolicyBuilder``` which would result in additional code (the constructror of ```JwtBearerHandler``` requires quite some parameters). All that to achieve an obvious and (I suppose) common "reject-all" policy.

Perhaps the framework should provide either:

- a ```RejectAuthenticationHandler : IAuthenticationHandler``` that simply does
```cs
public Task<AuthenticateResult> AuthenticateAsync() => Task.FromResult(AuthenticateResult.NoResult());
public Task ChallengeAsync(AuthenticationProperties properties)
{
    Context.Response.StatusCode = 401;
    return Task.CompletedTask;
}
```
- a ```AuthorizationPolicyBuilder.RejectAllPolicy``` that does
```cs
var bp = new AuthorizationPolicyBuilder("RejectAuthenticationHandlerSchemeName");
bp.RequireAssertion(_ => false);
return Task.FromResult(bp.Build());
```

**Comment by blowdart** [comment]
I don't agree. Authorization policies evaluate to true or false, that's their single responsibility - does the current user (and optionally the resource) pass the policy. Its up to the authentication pieces to decide how that yes or no gets mapped into an action that is suitable for their type of authentication.

So, like I said, this all comes down to how you're authenticating. Now you also want to mix in URLs that don't map to anything, which further complicates it, because that is another responsibility, that of MVC.

So, again, what authentication method are you using? As you haven't said yet If it's cookies then it's the cookie authentication that is mapping to a redirect, which is the right thing for cookies to do. If you're doing something weird with headers or other non-standard authentication type we don't provide in box then you must write your own handler, which then decides if it's a status code, a redirect, an html response, or whatever else you feel is suitable.

**Comment by mrgleba** [comment]
We are doing some sutom auth using either a session header or a user/pass headers.

I understand your position and reasoning. Perhaps it's something that should go into the docs of ```AuthorizationPolicyBuilder``` that if you construct it without a scheme name then it shoud always succeed lest an exception will be raised. 

We've actually spent quite a few hours trying to figure out why the exception is raised and we'd love for others who stumble upon this problem to be saved from spending time debugging this.

**Comment by blowdart** [comment]
That's fair. @Rick-Anderson for the docs.

I cover writing your own handler at https://github.com/blowdart/AspNetAuthenticationWorkshop

**Comment by Rick-Anderson** [comment]
@mrgleba  Can you create an issue from the doc page this belongs to? That will connect the doc to the issue. Go to the bottom of the doc page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
