### ISSUE TITLE
Should TLS1.3 be on by default?

### ISSUE THREAD

**Issue by mrgleba** [dotnet/aspnetcore#13819]
The 3.0 release introduced TLS1.3. Still the default for the ```SslProtocols``` is ```SslProtocols.Tls12 | SslProtocols.Tls11```. Shouldn't TLS13 be included in the default?

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
Generally we've waited for a year or more until proxies and other devices catch up. Frankly you shouldn't be setting anything with the SslProtocols anyway, because you end up [coding yourself into a corner](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), and leaving things unset has a default of "Whatever the OS gives us"

**Comment by wfurt** [comment]
Besides perhaps better promotion of SslProtocols.None, is there anything left on this issue?
Tls13 should light up as it is available at OS level.
