### ISSUE TITLE
Http Response fails when writing more than 255MB

### ISSUE THREAD

**Issue by davidjward30** [dotnet/aspnetcore#14191]
Reproduction

We have ported an ASP.NET application to ASP.NET Core (2.2.7), converting IHttpHandler to an implementation of IMiddleware.

When writing to the Response Stream, attempting to write a byte array exceeding 255MB fails almost silently. The Status code is 200, but the response is completely truncated. The following appears in the debug log:

Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in Microsoft.AspNetCore.Server.IIS.dll

The innerexception appears to be ArithmeticException 

See attached solution for a full repro. There are various links on the home page that demonstrate the failure modes. Each link attempts to download a response of a specificied size.

Expected behavior:
I should be able to write a byte array much larger that 255MB in 64-bit mode. 
In the attached repro, all links should download a file of the specified size.

[DataLayerServerLargeObjectBugRepro.zip](https://github.com/aspnet/AspNetCore/files/3636490/DataLayerServerLargeObjectBugRepro.zip)

**Comment by Tratcher** [comment]
Exception:
```
Microsoft.AspNetCore.Connections.ConnectionResetException
  HResult=0x80131620
  Message=The client has disconnected
  Source=Microsoft.AspNetCore.Server.IIS
  StackTrace:
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)

Inner Exception 1:
ArithmeticException: Overflow or underflow in the arithmetic operation.
```

**Comment by Tratcher** [comment]
Thanks, we'll investigate.

That said, there are many reasons not to create `byte[]` that large, let alone write them. Why are you working with such single large arrays?

**Comment by davidjward30** [comment]
Yes in hindsight it’s not a good idea to be creating byte arrays that size. They come from blobs in a sql database which we stitch together to form a response. 

When we designed the system 10 years ago the blobs were typically just 1MB. But as computers have become more powerful user data has grown rapidly. 

Clearly we ought to have a bit of a redesign of our code to stream/pipeline the data. 

I thought it might be useful for others caught by the same problem. It has us perplexed for a long time tracking it down in production

**Comment by Tratcher** [comment]
The issue may be around here: https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IIS/src/Core/IO/AsyncWriteOperationBase.cs#L36-L50

**Comment by gfr-g** [comment]
The exception is thrown by the call to native code `http_write_response_bytes` in the ASPNET Core Module for IIS that, in turn, calls `WriteEntityChunks` method on `IHttpResponse`. 

Judging from the [documentation to this method](https://docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/ihttpresponse-writeentitychunks-method), this behavior seems to be by design:

<html><body>
<h2 id="return-value" class="heading-anchor">Return Value</h2>
<p>An <code>HRESULT</code>. Possible values include, but are not limited to, those in the following table.</p>
<div class="has-inner-focus">

Value | Description
-- | --
S_OK | Indicates that the operation was successful.
ERROR_INVALID_PARAMETER | Indicates that the parameter is not valid (for example, the pDataChunks pointer is set to NULL).
ERROR_NOT_ENOUGH_MEMORY | Indicates that there is insufficient memory to perform the operation.
ERROR_ARITHMETIC_OVERFLOW | More than 65535 chunks have been added to the response.

</div>
</body>
</html>

a buffer bigger than 255MB surpass in fact the 65535 chunk limit.

**Comment by Tratcher** [comment]
In this scenario the IIS Asp.Net Core server code should be changed to break up the large write into multiple. If that's impractical, we should throw a specific error message at the start of Write/Async.

**Comment by gfr-g** [comment]
I'll try to explore your proposal and will report back on my findings or in case I need further help with the expected behavior for this part of code.

**Comment by gfr-g** [comment]
I analyzed the possible solutions and it seems to me that the `IISHttpContext.WriteBody` method should be responsible of handling this logic, by slicing the array and feeding the AsyncEngine with data within limits. 
Is it correct or should be a concern of the `AsyncIOEngine`/`AsyncWriteOperation` instead? 

Thank you

**Comment by gfr-g** [comment]
Yes, exactly. I've already implemented it (although I want to see if I can get rid of the hardcoded constants) but I'm out of town so I'll submit a pull request on Monday at the earliest.

**Comment by gfr-g** [comment]
@Tratcher here's one possible solution I'd like to discuss before submitting a pull request because I'd like to know if the trade offs are acceptable. The loop we were talking about would be something like this

```
                    if (!buffer.IsEmpty)
                    {
                        if (buffer.IsSingleSegment)
                        {
                            await AsyncIO!.WriteAsync(buffer);
                        }
                        else
                        {
                            ushort chunksCount = 0;
                            var start = 0;
                            var length = 0;

                            foreach (var chunks in buffer)
                            {
                                chunksCount++;
                                length += chunks.Length;

                                if (chunksCount == MAX_CHUNKS)
                                {
                                    await AsyncIO!.WriteAsync(buffer.Slice(start, length));

                                    chunksCount = 0;
                                    start = length;
                                    length = 0;
                                }
                            }

                            if (chunksCount > 0)
                            {
                                await AsyncIO!.WriteAsync(buffer.Slice(start, length));
                            }
                        }
                    }
```

If we could make assumptions on the segments size (or easily slice to segment's borders) it would be much easier to only apply this logic whenever the buffer is bigger than a certain treshold, but unfortunately that's not possible. 
Unless there's a better way to do it that I'm overlooking, this means almost always iterating over the ReadOnlySequence. It shouldn't be terrible but still something to keep in mind.  

Another thing I don't particularly like, is that we are assuming something on how the AsyncIOEngine will split the ReadOnlySequence in chunks. If this logic changes in the future we might need to change this code as well.  

What do you think?

**Comment by Tratcher** [comment]
That seams ok, and should be easy to test. Feel free to submit a PR.

**Comment by davidfowl** [comment]
@adityamandaleeka Did we mark this for back port to 6.0?
