### ISSUE TITLE
Question: Automatically registering routes for 3.0

### ISSUE THREAD

**Issue by kimbell** [dotnet/aspnetcore#14469]
I build a number of libraries for internal use by multiple services. Some of these register routes. i.e /info for getting various information from a service. 

When building these libraries, we want to make them as easy to use as possible. Today we have based our code on the fact that Controllers are automatically included in the routing table. 

With the changes to routing in 3.0, I would like to investigate if there are better ways of doing this. 

The service will contain code similar to this:
```CS
appBuilder.UseRouting();
appBuilder.UseEndpoints(config =>
{
      config.MapControllers();
});
```

Is there any way of getting routes automatically registered without having each service call config.MapXYZ() for my new routes? 

Ideally I would like routes automatically registered when I add things to the IServiceCollection. i.e. services.AddInformation() should add a route for /info

**Comment by rynowak** [comment]
@kimbell - can you provide any more information about what this is for? 

This kind of thing is theoretically possible to enable - but we made a deliberate choice to make things like this explicit.

> When building these libraries, we want to make them as easy to use as possible.

One of the aspects of this design is that the value returned from `.MapXyz()` is useful for additional configuration. For whatever you library is, would the users ever want to configure auth? CORS? what about specifying the URL pattern or options?

We intentionally made these things visible so that these details would show up in the app and be visible. Sometimes less code does not equal easier to use.

**Comment by kimbell** [comment]
@rynowak We are in the process of converting an existing distributed monolith into a set of micro-services. All services should have certain endpoints for metrics, version information, cache flush, documentation, etc. 

We are developing internal libraries for our use to cover these areas; so we can make a bunch of assumptions that wouldn't hold for ASP.NET Core in general. In many cases they will use third party nuget libraries that are set up for use in our ecosystem. 

We would like to make it as easy for developers to set up these basic things and have them concentrate on business functionality instead. It would be nice if we could get away with a one-liner and let the magic happen. 

We are trying to structure things so that for those cases where the standard setup doesn't work, they have the ability to customize things per service, but that should be the exception rather than the rule.

At the moment we are looking at what options are available in Core 3.0. Previously we used an `IStartupFilter `to register additional endpoints. The most immediate option would be to create a `.MapStandardEndpoints()` that configures things, but it's worth checking what other options we have available.

**Comment by rynowak** [comment]
I'd really strongly suggest doing something like `.MapStandardEndpoints()`.  You might consider making your own `dotnet new` template if the initial setup phase of the project is something you want to want to optimize for.

I'm going to leave this open for more discussion and see if it attracts more feedback. 

---

Thanks for sharing your point of view. I'm not convinced to expose this functionality based on your scenario because it focused on saving line of code in your template. Usually these things have a limit - like any service that can't use the default settings will have to add back that line of code. I'd suggest trying to consistency over minimalism.

**Comment by kimbell** [comment]
@rynowak thanks for the feedback. 

The framework has a lot of extensibility points, and this being a new area, I wanted to find out what possibilities existed.

**Comment by javiercn** [comment]
We haven't received enough feedback for automatically mapping endpoint and we do think that this needs to be an explicit user choice to avoid situations where bringing a package or adding some services lights up some endpoints without user knowledge.
