### ISSUE TITLE
Stateful Background Services in Container Orchestration?

### ISSUE THREAD

**Issue by scalablecory** [dotnet/aspnetcore#14583]
_From @BrandonCookeDev on Friday, September 20, 2019 5:44:30 PM_

# Issue Title

Alternative to Stateful Background Services in Container Orchestration?

# General

Hello, I'm the devops lead for my company. We use .NET Core and are currently running into a complication. Essentially we have code that uses a few background services in ASP.NET (using IHostedService), however it appears those services are stateful in nature. This is problematic because we wish to host this ASP.NET application in a container orchestration environment (AWS ECS). 

Because of the stateful nature, we can't have three different instances of the service running, otherwise data consistency issues or deadlocking issues become introduced. The obvious alternative is to create individual microservice/APIs for these, but given our timetable we are looking for a quicker solution that still may follow a "Best Practice".

I haven't been able to find information elsewhere on others running into this issue. Would you happen to have insight for what to do here? Thank you!

(PS. I think you guys are killing it with .NET Core. Keep up the great work!)

_Copied from original issue: dotnet/core#3410_

**Comment by scalablecory** [comment]
_From @carlossanlop on Saturday, September 21, 2019 12:12:13 AM_

@Pilchie can you help here?

**Comment by Pilchie** [comment]
@anurse ?

**Comment by davidfowl** [comment]
@BrandonCookeDev I'm not 100% sure what's being asked here. 

> otherwise data consistency issues or deadlocking issues become introduced

That's extremely application specific. Can you clarify what you're looking for.

**Comment by anurse** [comment]
Yeah, this looks like an architectural discussion rather than something we can specify in our docs. I don't think there's necessarily anything stateful in `IHostedService` itself, though perhaps @BrandonCookeDev can clarify.

**Comment by BrandonCookeDev** [comment]
Hey guys, thanks for the activity!

So we were handed an ASP.NET application in NETCORE 2.2 that implemented some background services that did things such as sync database information with what was in memory, and other stateful distributed actions.

Now this is fine if one instance of the application is running, as the state the application holds would more or less be in a singleton; however, since we utilize AWS ECS for container orchestration it would be silly to force only one instance of the app to run. Yet, the issue is that if we have two or more instances of the app, up at any given time they could have a different set of stateful data to be synced.

Obviously, the best option is to take the background service and make a FAAS (AWS Lambda, etc) and have that be triggered on a schedule outside of this ASP.NET app; yet due to time restrictions that may not be possible. 

So I guess my question is for the above scenario is there any sort of ASP.NET CORE approach to solve the problem? Let me know if more information is needed. I also understand that it's quite possible that this is not solvable from the app and that the stateful piece will have to be removed altogether and shifted elsewhere, but I figured asking wouldn't hurt :)

Thanks guys

**Comment by davidfowl** [comment]
This isn’t an asp.net core problem. It’s a general issue with having more than one source of truth. I’m. It sure what advice you’re looking for outside of:
- Keep the state external OR
- Make the system tolerate stale data OR
- Detect changes in the data and update the in memory cache

**Comment by BrandonCookeDev** [comment]
> This isn’t an asp.net core problem
For reference I never said it was. I am just looking for potential solutions that coincide with ASP.NET best practices or adhere to ASP.NET design patterns.

**Comment by davidfowl** [comment]
Ah I see, there’s no data syncing primitive to handles these types of scenarios. It sounds like this app was designed with a single instance in mind.

**Comment by BrandonCookeDev** [comment]
Thanks for the feedback guys! 
I assumed this would be the case, but figured I'd ask just in case

**Comment by Rick-Anderson** [comment]
@anurse  can this be closed?

**Comment by anurse** [comment]
Fine with me
