### ISSUE TITLE
Investigate using C# compiler to generate reference assemblies in 5.0

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#14801]
This corresponds to the ProduceReferenceAssembly attribute: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019. Let's investigate using this in 5.0.

**Comment by Pilchie** [comment]
We talked to @ericstj about this, and unfortunately, this isn't suitable for us right now, because of the version requirements of our ref assemblies.

**Comment by ericstj** [comment]
I think the only way to make use of this feature is to do use /refonly instead of /refout and ifdef/conndition the assembly version for that pass.  The benefit of using /refonly is that you can generate it from the same source code that you build the product from, rather than relying on GenAPI.  Since /refonly is a seperate pass you can condition almost anything in the project.

**Comment by Pilchie** [comment]
Oh.  I do like that idea.  Re-opening so that we can consider that.

**Comment by dougbu** [comment]
5266918ed2be
