### ISSUE TITLE
How to config "dotnet watch" stops watching .cshtml file

### ISSUE THREAD

**Issue by mr-xrow** [dotnet/aspnetcore#15018]
i am working with net core 3.0 and "dotnet watch". When I change .cshtml file then "dotnet watch" is restarted. How to "dotnet watch" stops watching cshtml file.

**Comment by pranavkm** [comment]
@mr-xrow see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#opt-in-to-runtime-compilation.

**Comment by mr-xrow** [comment]
Thank @pranavkm 
when I remove AddRazorRuntimeCompilation from ConfigureServices in startup.cs i get error from browser InvalidOperationException: The view '...' was not found. The following locations were searched:...
and "watch" still restarts when I edit .cshtml file. In Version 2.x, watch only restarts when .cs file changes  so I work with cshtml faster

**Comment by ceee** [comment]
You don't have to remove, but **add** `.AddRazorRuntimeCompilation()`, otherwise views will be compiled at build-time, which is the default in ASP.NET Core 3 and is most probably the desired option for production.

Here is an example of my code (I am querying for the watcher in Startup.cs):

```
IMvcBuilder mvc = services.AddControllersWithViews();

// runtime compilation of views for "dotnet watch"
string watcher = Environment.GetEnvironmentVariable("DOTNET_WATCH");
if (watcher != null && watcher == "1")
{
  mvc.AddRazorRuntimeCompilation();
}
```

The environment variable was found in the [command line options](https://github.com/aspnet/AspNetCore/blob/master/src/Tools/dotnet-watch/src/CommandLineOptions.cs) from the watcher.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
