### ISSUE TITLE
Add IConnectionFactory implementation to the socket transport

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#15019]
Today we have all of the pieces in place the server transport but we haven't exposed anything to do client sockets. There's an internal version of the API we want [here](https://github.com/aspnet/AspNetCore/blob/d35b33f29470a51876da5060f6fa46f9794fa941/src/Servers/Kestrel/Transport.Sockets/src/Client/SocketConnectionFactory.cs) so we can start with that as the initial API:

```C#
public class SocketConnectionFactory : IConnectionFactory, IAsyncDisposable
{
    public SocketConnectionFactory(IOptions<SocketTransportOptions> options, ILoggerFactory loggerFactory);
    public async ValueTask<ConnectionContext> ConnectAsync(EndPoint endpoint, CancellationToken cancellationToken = default);
}
```

PS: This will fully enable 

Some observations/questions:
- The `SocketConnectionFactory` is `IAsyncDisposable` because it owns the memory pool. Do we want all connections made by the same factory sharing the pool? If yes then this type should maybe track outstanding connections before disposing the factory.
- As part of these refactorings, we should have a way to construct these types without passing `Options.Create(OptionsType)`. 
- Are there any client options that are different from server options? This [spike](https://github.com/aspnet/AspNetCore/pull/11672) had a shared options base class, and also had client and server options.

**Comment by davidfowl** [comment]
cc @halter73 did you do this?

**Comment by halter73** [comment]
I did start this. We still need to add docs and there are some things that I don't like about it from a client-usage perspective. E.g:

1. The ctor takes `IOptions<SocketTransportOptions>` instead of SocketTransportOptions directly and requires an ILoggerFactory. This means you basically have to use the generic host as demonstrated in the http2cat sample: https://github.com/aspnet/AspNetCore/blob/c7937640a4079465d36441724933eae5a9ca0085/src/Servers/Kestrel/samples/http2cat/Program.cs#L18-L26 https://github.com/aspnet/AspNetCore/blob/c7937640a4079465d36441724933eae5a9ca0085/src/Shared/Http2cat/Http2CatIServiceCollectionExtensions.cs#L13-L19
2. SocketTransportOptions.MemoryPoolFactory is internal as is SlabMemoryPoolFactory.
3. The SocketConnectionFactory uses the same SocketConnection as the server meaning that it retains some behavior expected by the server that might not be ideal for a client. One example of this is that the SocketConnection will immediately close the connection fully upon receiving a fin making it impossible to use in a half-open write-only state.
4. It only supports IPEndPoints at the moment.

**Comment by halter73** [comment]
We have static helpers to create IOptions and ILogger factory so adding new constructors isn't critical. The other stuff like possibly exposing a public memory pool factory option, and supporting other EndPoint types can be done later.
