### ISSUE TITLE
Empty display names resulting in exceptions

### ISSUE THREAD

**Issue by Muchiachio** [dotnet/aspnetcore#15368]
### Issue
We started annotating our projects with nullable reference types while also removing nulls where possible. One of our targets is model property display names, which we localized using [IDisplayMetadataProvider](https://github.com/aspnet/AspNetCore/blob/v3.0.0/src/Mvc/Mvc.Core/src/ModelBinding/Metadata/IDisplayMetadataProvider.cs) implementation similar to this
```C#
public class EmptyDisplayMetadataProvider : IDisplayMetadataProvider
{
    public void CreateDisplayMetadata(DisplayMetadataProviderContext context)
    {
        if (MissingTranslation(context))
            context.DisplayMetadata.DisplayName = () => "";
        else
            context.DisplayMetadata.DisplayName = () => Localize(context); // Might be empty here too
    }
}
```
But it seems like using empty strings on missing translations is not possible today, because display name values are null coalesced in [ModelMetadata](https://github.com/aspnet/AspNetCore/blob/v3.0.0/src/Mvc/Mvc.Abstractions/src/ModelBinding/ModelMetadata.cs#L414) and then passed to [ValidationContext.DisplayName](https://github.com/dotnet/corefx/blob/v3.0.0/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/ValidationContext.cs#L146) which does not allow empty values, thus throwing the exception.

Is this something you would be willing to change or we will have to keep nulling out display names everywhere to be on the safe side?

### To Reproduce
1. Clone [repro](https://github.com/Muchiachio/EmptyDisplay)
2. Run
3. You will get exception on property binding.

### Expected behavior
Action loads without exceptions with empty string display names

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@Muchiachio thanks for contacting us and thanks for providing a project for your scenario.

I think the change you are proposing is reasonable to a degree. I would not simply allow the empty string. But I would be ok if we switched the logic from null coalescing the display name to `!string.IsNullOrEmpty(DisplayName) ? DisplayName : (Name ?? ModelType.Name);`

I think allowing an empty display name by itself is bad, because it can easily lead to broken UIs if you make a mistake.

What I propose I think is a step in the middle, where if you don't have a translation for something it gets the Name instead of an empty string. In that scenario, if you are concerned about missing translations, you can collect a list of all the original terms, run the site on a localized language and search for the unlocalized terms.

Will that be enough?

**Comment by Muchiachio** [comment]
UI is fine with empty strings (nulls), it's just that internal property binding and validations are crashing.
Because if you use null, it correctly falls back to at least a property name.

I agree that changing it to `IsNullOrEmpty` would be reasonable.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
