### ISSUE TITLE
Strange error when component parameter casing does not match

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#16778]
Repro steps:

- Add an `IncrementAmount` parameter of type `int` to the `Counter` component
- Add a `Counter` to the `Index` component with the `IncrementAmount` parameter set, but using the wrong casing: `<Counter incrementamount="10" />`.

Expected result:

```
System.InvalidOperationException: Object of type 'BlazorApp9.Pages.Counter' does not have a property matching the name 'incrementamount'.
```

Actual result:

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
   at Microsoft.AspNetCore.Components.Reflection.MemberAssignment.PropertySetter`2.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, IPropertySetter writer, String parameterName, Object value)
```

**Comment by javiercn** [comment]
@danroth27 thanks for contacting us :).

Component parameters are **case-sensitive** the same way component names are when extending ComponentBase (or more concretely calling `parameterView.SetParameters(this)`

We could provide a diagnostic/warning/information for casing mismatches, but that's it.

**Comment by danroth27** [comment]
@javiercn Yes, I understand that component parameters are case sensitive. This bug isn't about changing that. The error message in this particular case is incorrect. Normally if you provide a component parameter name that is incorrect you get a good error message. In the case of case mismatch you get a weird cast exception.

If we could also provide a design time diagnostic for case mismatches that would be even better.

**Comment by javiercn** [comment]
Actually, I was wrong. Parameter names are case insensitive. I believe this might be a compiler bug, as the parameter with the wrong casing results in the parameter being incorrectly encoded as a string in the generated code (as if it was an attribute) as the parameter is not recognized in visual studio.
```
<Counter initialCount="@(10)" />
```

The generated code for that is
```
protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
{
    __builder.AddMarkupContent(0, "<h1>Hello, world!</h1>\r\n\r\nWelcome to your new app.\r\n\r\n");
    __builder.OpenComponent<BlazorServerApp.Pages.Counter>(1);
    __builder.AddAttribute(2, "initialCount", "10");
    __builder.CloseComponent();
}
```

My visual studio version is `Version 16.5.0 Preview 1.0 [29504.21.master]`

@rynowak leaving the rest to you as the compiler expert.

**Comment by rynowak** [comment]
Passing an arbitrary attribute to a component is not an error - it's allowed, and it's how things like `CaptureUnmatchedAttributes` work.

**Comment by javiercn** [comment]
I don’t agree, that was my first thought and I found tests on the runtime that specifically indicate the opposite.

At the very least there is an inconsistency between what the runtime says and what the compiler does.

**Comment by javiercn** [comment]
Correct casing:
![image](https://user-images.githubusercontent.com/6995051/68226587-2b255900-ffa7-11e9-9588-7d455d57af71.png)

This works fine.

Incorrect casing:
![image](https://user-images.githubusercontent.com/6995051/68226637-3c6e6580-ffa7-11e9-951d-bab444f56d5f.png)

This doesn't work because the compiler emits `builder.AddAttribute("InitialCount", "10");`

Incorrect casing but fixing it with `@`
![image](https://user-images.githubusercontent.com/6995051/68226795-85beb500-ffa7-11e9-95f5-8cf905a6873f.png)

This works because the compiler emits `builder.AddAttribute("InitialCount", 10);` thanks to the `@()`.

Sample code that indicates parameters are case-insensitive and unique.
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Reflection/ComponentProperties.cs#L252-L254

This is a bug because:
1) Component parameters are defined as case-INsensitive by the runtime.
2) Passing a value with the right type works at runtime with no issues.
3) The compiler detects the parameter, but it treats it as case-sensitive and as such, when it finds a case-insensitive parameter it fails to recognize the parameter and defaults to html within the attribute value instead of C# which is what causes the cast failure at runtime.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
