### ISSUE TITLE
UserManager throws exception - Unable to track an entity because primary key property 'Id' is null.

### ISSUE THREAD

**Issue by skoruba** [dotnet/aspnetcore#16866]
### Describe the bug
I've used the implementation of User and Role which are derivated from `IdentityUser`, `IdentityRole`.

If I call the method:
```
var identityResult = await UserManager.CreateAsync(user);
```
I get the error:
```
System.InvalidOperationException: Unable to track an entity of type 'AppUser' because primary key property 'Id' is null.
```
It works perfectly with version of `Microsoft.AspNetCore.Identity.EntityFrameworkCore` - 2.2.0, but after upgrading to 3.0.0 - it doesn't work.

### Further technical details
- ASP.NET Core 3.0.0
- Microsoft.AspNetCore.Identity.EntityFrameworkCore - 3.0.0

**Comment by jeanpoelie** [comment]
I ran into this issue when I migrated from 2.2 to 3.0 as well.
I believe I solved it by adding
```
services.AddIdentity<ApplicationUser, ApplicationRole>()
                    .AddEntityFrameworkStores<dbContext>()
                    .AddRoleManager<RoleManager<ApplicationRole>>()
                    .AddSignInManager<SignInManager<ApplicationUser>>()
                    .AddUserManager<UserManager<ApplicationUser>>()
                    .AddDefaultTokenProviders();
```

To the Startup.cs where it only had 'AddIdentity' before.
I had to explicitly mention all derived classes.

I also had to add the Managers to the Transient.
```
services.AddTransient<UserManager<ApplicationUser>>();
            _logger.LogInformation("Added UserManager<typeof(ApplicationUser)> to services");
            services.AddTransient<SignInManager<ApplicationUser>>();
            _logger.LogInformation("Added SignInManager<typeof(ApplicationUser)> to services");
            services.AddTransient<RoleManager<ApplicationRole>>();
            _logger.LogInformation("Added UserManager<typeof(ApplicationUser)> to services");
            services.AddTransient<dbContext>();
            _logger.LogInformation("Added dbContext to services");
```

**Comment by skoruba** [comment]
Thanks for your tip, but I'm not sure what caused this issue. I get same exception during testing with following UserManager - https://github.com/aspnet/AspNetCore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Identity/test/Shared/MockHelpers.cs#L37

Something has changed, but I don't know - what exactly. Any idea?

**Comment by jeanpoelie** [comment]
Hmm, I have no idea what exactly changed, I remember I had the issue 2-3 weeks ago but can't find exactly why and how I managed to fix it.
Is it possible for you to make a small testable repo?

**Comment by skoruba** [comment]
This exception is probable connected with this breaking change: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#string-and-byte-array-keys-are-not-client-generated-by-default
- I fix this issue on mapping part via Automapper like this:
```
CreateMap<TUserDto, TUser>(MemberList.Source)
.ForMember(dest => dest.Id, opt => opt.Condition(srs => srs.Id != null));
```
If `Id` on UserDto is `null`, then I use default value from `UserIdentity` - which is automatically generated `Guid`.

**Comment by blowdart** [comment]
@ajcvickers

**Comment by ajcvickers** [comment]
@blowdart @HaoK I think I know what might be going on here. Prior to 3.0, string keys were configured to use generated values by default. The value generator would generate a GUID and convert it to a string. However, this was rarely used because:
a) Most people specify string keys explicitly anyway
b) Even if they didn't, the chance they would want a GUID converted to a string seemed low.

Of course, b) doesn't hold true for Identity because of its wonderful string keys that are really GUIDs!

We could:
* Just document the change
* Or change the Identity model to make the keys use value generation again. However, technically then this will be a breaking change between 3.0 and which ever version it happens in.

I would favor just documenting.

@skoruba The [mitigation for this change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#string-and-byte-array-keys-are-not-client-generated-by-default) should work here. Alternately, specify the user ID explicitly.
