### ISSUE TITLE
ServerSide Blazor: Windows authentication not working when enabling windows AND anonymous authentication

### ISSUE THREAD

**Issue by audacity76** [dotnet/aspnetcore#17025]
### Describe the bug
For an internal ServerSide Blazor website I need windows authentication and anonymous access. I enabled both authentication methods in the project properties but the windows authentication does not happen.

### To Reproduce
Configure following component page 

``` C#
@page "/authorized"

@attribute [Authorize]

@inject AuthenticationStateProvider AuthenticationStateProvider

<p>User: @User</p>

@code{
    public string User { get; set; }
    
    protected override async Task OnInitializedAsync()
    {
        var auth = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        User = auth.User.Identity.Name; // null!
    }
}
```

### Further technical details
- ASP.NET Core version 3.0.0
- VS 16.3.8

**Comment by javiercn** [comment]
@audacity76 thanks for contacting us.

@SteveSandersonMS Do you have any thoughts here?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The auth in Blazor server should work very similar with non-Blazor situations. Do you observe similar issue in an MVC app for example?

**Comment by audacity76** [comment]
Just tried it with the latest version 3.1.1 but still the Blazor Server app ignores the [Authorized] attribute. I created a repo so you can compare the behaviors: https://github.com/audacity76/WindowsAuthAspNetCore

**Comment by kempcalalo** [comment]
Experiencing the exact same issue if both windows and anonymous authentication are enabled.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing a repro, @audacity76. Bringing this up for triage tomorrow.

**Comment by EuanKirkhope** [comment]
+1 for this issue,  a major blocker for me, Ive had to go to to a plain old user/ passwords file temporarily. :(

(also) how does one sign in and out of windows authentication say if the user has finished editing a page marked with [authorize], or where the code behind requires login?  This app is more of a industrial visualization app and so is always has a client running, with screens available for all to see.

**Comment by SteveSandersonMS** [comment]
> (also) how does one sign in and out of windows authentication

Users don't sign in or out with Windows Authentication - they are inherently signed in all the time. If you need the ability to sign out without actually logging out from Windows, then you would need to use a different authentication mechanism.

**Comment by christian-ruud** [comment]
+ 1 for this, I am experiencing the exact same problem

**Comment by SeawardToast** [comment]
Is there any movement on this? This is a huge blocker for us as well, wanting to integrate windows authentication within a blazor server side app running on rhels v8.

**Comment by christian-ruud** [comment]
@SeawardToast I made a workaround for my project, as it was a blocker for me too.  

First, we have this extension method:
`
        public static void ChallengeUnauthenticated(this IEndpointConventionBuilder builder)
        {
            builder.Add(SecureEndpoint);

            static void SecureEndpoint(EndpointBuilder builder)
            {
                var d = builder.RequestDelegate;
                builder.RequestDelegate = async context =>
                {
                    if (context.User.Identity.IsAuthenticated)
                        await d(context);

                    else if (authMode == AuthenticationModes.Windows)
                        await context.ChallengeAsync();

                    else if (authMode == AuthenticationModes.AzureAD)
                        await context.ChallengeAsync("AzureADOpenID");

                };
            }
        }
`
And then we add them to the endpoints like this: 
`
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapBlazorHub().ChallengeUnauthenticated();
    endpoints.MapFallbackToPage("/_Host").ChallengeUnauthenticated();
 });
`

Now, authentication works for the UI, and controllers respect the authentication attributes.

**Comment by SteveSandersonMS** [comment]
@audacity76 The way Windows authentication works is that, when each request arrives, you need to decide whether to require auth or not. If you do want to require auth, and the request isn't already authenticated, then you have to respond with a challenge by calling `context.ChallengeAsync()`. The browser will then do whatever auth flow it wants and then retry the request, this time with the necessary authentication headers.

As such, when it comes to Blazor Server, you have to decide whether or not to authenticate the circuit connection *before* the circuit connection is made.

The logic posted by @christian-ruud above is one good example of that. Another example might look like this, which can be added just before `app.UseEndpoints` in `Server.cs`:

```cs
app.Use(async (context, next) =>
{
    if (!context.User.Identity.IsAuthenticated && context.Request.Cookies.ContainsKey("do-auth"))
    {
        await context.ChallengeAsync(IISDefaults.AuthenticationScheme);
    }
    else
    {
        await next();
    }
});
```

This logic will issue the challenge only to people who have a cookie called `do-auth`. Now to set that cookie, consider modifying the `<AuthorizeRouteView>` in your `App.razor` file so that, if a visitor tries to go to a Blazor page with `[Authorize]` and they aren't yet authenticated, redirect them to some new server-side endpoint called `/auth`:

```razor
<AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
    <NotAuthorized>
        @{ NavigationManager.NavigateTo("/auth?redirectUrl=/" + System.Net.WebUtility.UrlEncode(NavigationManager.ToBaseRelativePath(NavigationManager.Uri)), true); }
    </NotAuthorized>
</AuthorizeRouteView>
```

Then implement `Pages/Auth.cshtml` as follows:

```cshtml
@page
@attribute [Microsoft.AspNetCore.Authorization.Authorize]
@functions {
    public LocalRedirectResult OnGet()
    {
        Response.Cookies.Append("do-auth", "true");
        return new LocalRedirectResult(Request.Query["redirectUrl"]);
    }
}
```

This checks if the user can be authenticated via Windows authentication (assuming that's your default auth type), and if so, sets the `do-auth` cookie and returns them back to where they came from. Now the middleware shown above will issue the challenge when the Blazor Server circuit is being established, so now they will be logged in.

cc @javiercn @blowdart for opinions on this flow.

Obviously it will behave strangely if a user gets assigned the `do-auth` cookie because they can be authenticated, but then later loses access to their Windows account, because now until they clear their cookies they'll be stuck in a loop being asked for credentials. If this is a concern you'd need to refine the flow further.
