### ISSUE TITLE
AspNetCore SignalR nuget version mismatch

### ISSUE THREAD

**Issue by zeinali0** [dotnet/aspnetcore#17170]
I gonna create a class library based on SignalR packages but they are not up to date on NuGet and they mismatch each other and i cant use my library in an .net core 3 application.
How should i refrence to Microsoft.AspNetCore.SignalR.Core v3.0.0?

![SignalR-VersionReport](https://user-images.githubusercontent.com/28354390/68994982-f1edc280-089d-11ea-82ad-a8bd4af17346.png)

**Comment by BrennanConroy** [comment]
Could you describe the library you're trying to write and why you need to reference "Microsoft.AspNetCore.SignalR.Core"?

"Microsoft.AspNetCore.SignalR.Core" no longer ships as a NuGet package because it is now in the [shared framework](https://github.com/aspnet/Announcements/issues/325). If you want to write a library that uses it you can add `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to your csproj to let consumers know that they need the shared framework in order to use the library.

**Comment by zeinali0** [comment]
I'm trying to implement [MTProto](https://core.telegram.org/mtproto) by using some part of SignalR.
It has its own handshaking so i'm trying to implement it via `Microsoft.AspNetCore.SignalR.Core`
but it seems in .net core 3 `HubDispatcher` is not public anymore.

**Comment by ffandreassoroko** [comment]
Hi 
we have a similar problem. ( just another lib `Microsoft.AspNetCore.SignalR.StackExchangeRedis` )
we created a lib for some default stuff (own hub base ) and added that lib to our micro services.

**Comment by anurse** [comment]
> in .net core 3 `HubDispatcher` is not public anymore.

Correct. This type was in an `Internal` namespace (meaning it was not supported) and is no longer public in 3.0 as part of cleaning up the `Internal` namespace.

**Comment by zeinali0** [comment]
Almost all core part of SignalR are in `Internal` namespace and they are not open to customize and this make it very risky to use it in an enterprise app.

**Comment by anurse** [comment]
Can you provide more information on what kind of customization you want to do? We have plans to add public _supported_ ways to add more customization in the future.
