### ISSUE TITLE
[Kestrel] Support for custom decoder in headers

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#17400]
Follow up from https://github.com/aspnet/AspNetCore/issues/17399

In 5.0 we want to provide a hook to use a custom decoder for headers. A `System.Text.Encoding.Encoder` is probably not quite sufficient since the codec may want to see the header name in order to make decisions. A strawman API would be something like this:

```csharp
string Decode(string headerName, ReadOnlySpan<byte> headerBytes);
```

**Comment by stephentoub** [comment]
> A strawman API would be something like this

Would it make sense to be more like:
```C#
Encoding GetEncodingForHeader(string header name);
```
?

I'm thinking that would enable:
- more flexibility in the future, given the various APIs on Encoding
- the ability to cache an Encoding to use for a given header, which could in turn enable caching opportunities for a given input sequence
- potential devirtualization opportunities

Just a thought. Not sure if this has progressed since the original strawman.

**Comment by halter73** [comment]
> Would it make sense to be more like:
> ```C#
> Encoding? GetEncodingForHeader(string headerName);
> ```

I think that does make more sense. I assume a null return value tells the server or client to use its default behavior. Do you think an interface for this belongs in System.Net.Http @stephentoub?

**Comment by stephentoub** [comment]
Why would an interface be needed?

**Comment by stephentoub** [comment]
>  I assume a null return value tells the server or client to use its default behavior.

That's my suggestion, as would not providing a delegate/interface at all.

**Comment by halter73** [comment]
> Why would an interface be needed? It could just be a delegate?

It's not, and it could be. I was thinking about having custom decoders be registered via DI, but I understand this doesn't make sense for System.Net.
