### ISSUE TITLE
Handle `isDebugRequest` header in Blazor Middleware

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17444]
When starting the debug process, VS is going to make a request to the `/json` endpoint and pass in a new `isdebugrequest:true` header. Blazor middleware (https://github.com/dotnet/aspnetcore/blob/master/src/Components/Blazor/Server/src/MonoDebugProxy/BlazorMonoDebugProxyAppBuilderExtensions.cs) should handle this and return the CDP websocket endpoint, so VS can use to configure the debugger.

**Comment by mkArtakMSFT** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/17443

**Comment by javiercn** [comment]
We can't do this in preview5 as we can't move to this until VS starts sending the header

**Comment by SteveSandersonMS** [comment]
We're no longer planning to do this at all. The newer VS JS debugger won't use the `/json` endpoint for connection, so it's no longer relevant to change how that works.

I've filed https://github.com/dotnet/aspnetcore/issues/19144 to track future clean-up work on removing the obsolete `/json`-endpoint code. We can't remove it immediately since the replacement isn't in place yet.
