### ISSUE TITLE
Automatically add debug configuration when opening Blazor WASM projects in VSCode

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17549]

**Comment by mkArtakMSFT** [comment]
This is blocked on the JS Debugger team: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1028008

**Comment by NTaylorMullen** [comment]
Launch.json config template:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
 
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against Blazor",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
        }
    ]
}
```

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS @danroth27 @mkArtakMSFT I have a PR out for O#: https://github.com/OmniSharp/omnisharp-vscode/pull/3593 . I haven't been able to test it end-to-end due to issues but the layout of the launch.json is there.

I'm looking for:
1. Verification the launch.json has the correct assumptions
1. A timeline for when I should merge that PR into O# to ensure it doesn't go out before we're ready
