### ISSUE TITLE
Logging STdout filename discrepancy

### ISSUE THREAD

**Issue by awe-source** [dotnet/aspnetcore#17572]
Same app stdout pears to be in different formats

Stdout_pid_yyyyMdhms.log
Stdout_yyyyMMddhhmms_pid.log

Maybe these format strings are not quite right but hompefully you get the idea

 we change this  aspcoremodule <> aspcoremodulev2
And the output file format changes...  and then changes back.

How and why is this even possible.
There does not appear to be any config related to this anywhere  we can find and the doco implies that only the first format is correct pid first...
However ther only related info we could find was the accepted pull for ‘sortable filenames’  https://github.com/aspnet/AspNetCoreModule/pull/130    in 2017? in the archived aspnetcoremodule repo

It would be nice to find info on this easier or if it is configurable info on how to do this.
 
Or if it is related to the V2 then where is the doco for this?!?

**Comment by jkotalik** [comment]
We changed the file name for the stdout log between AspNetCoreModule and AspNetCoreModuleV2. Are you hitting issues with the name change? We could potentially update the documentation here to mention that the log file format changed: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#attributes-of-the-aspnetcore-element

**Comment by awe-source** [comment]
Yes I would suggest that you do add a comment.
I’ll explain what happened here for info.

Log aggreagator was ingesting these files in emergency situations for warning and error only but we could up it for troubleshooting, however because this is not an ideal log sink and doesn’t have time stamps in the file we can only rely on approximate info and we’re using the filename stamp as referenc point for when the file was created as we found the OS file create date not accessible by the aggregator or was to be unreliable in some situations.

When we changed to the new v2 all our time stamps were out of Wack or the aggregator just dropped some files and it took us a long time to join the dots we revisited the doco page you refer to many times wondering if we had missed something subtle and it would have saved us a LOT of effort if there had been a note of this change that wasn’t buried in a change set in an archived repo

**Comment by jkotalik** [comment]
Apologies we didn't document the change. @guardrex want to make a quick doc change to mention that we have changed the file name for the log files to include the pid?

**Comment by guardrex** [comment]
We already have it in ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#log-creation-and-redirection

... but I have the PID there **after** the date, so perhaps the format changed??? :ear:

**Comment by awe-source** [comment]
Yes that’s the issue. All the doco has been updated to reflect the change from stdout-pod-date.log to stdout-date-pid .log...

As referenced in the doco even if you roll back to version 1... in the docs...

There should be a note somewhere easily accessible to all that says we changed the format in the new module

**Comment by guardrex** [comment]
We can't version the ANCM in our topics easily. I don't think it's on the same release schedule as the framework (but they'll let me know if that's not correct). I'll update the doc to put the PID before the date.

**Comment by guardrex** [comment]
@jkotalik I just got a 🎃 *SCARE* 👻 on your change tho ... IIRC, a dev in ancient .NET Core times asked to have the date **_first_** so that the files would sort better by file name. By placing the PID first, the sorting (by file name) isn't going to be so good. They have to use the file modified date at that point. Idk if that's a problem, but I seem to recall that fellow saying at the time that he wanted the file names to sort and that he either couldn't or didn't want to use the file's modified date.

**Comment by jkotalik** [comment]
I need to rereview the ANCM log file formats. I understand the concern though.

**Comment by guardrex** [comment]
I found it ... https://github.com/aspnet/AspNetCoreModule/issues/130

**Comment by guardrex** [comment]
Ah! ... It was in App Service, where I guess you don't even get an opportunity to sort by created/modified file dates. That makes sense.

**Comment by guardrex** [comment]
:smile: I did that actually ... https://github.com/aspnet/AspNetCoreModule/pull/131

**Comment by awe-source** [comment]
Just in case...

To be clear I’m not asking to change the code BACK from that change I was just suggesting a “NOTE: this changed from X To Y in acnm v2 so don’t freak out” to save others the heartache of “discovering” this ... TbH the new date is tonnes easier to parse as it’s fixed width on month day hour etc... just a shock...

**Comment by guardrex** [comment]
I see. I was confused by the ask here. Just confirmed ...

<img width="180" alt="Capture" src="https://user-images.githubusercontent.com/1622880/70330909-13d6c700-1804-11ea-8049-262a19091727.PNG">

... that nothing has changed since the ANCMv2 release.

The document is correct for ANCMv2 (for example, PID has been there for *years* and in the right position in the filename for v2). **_The guidance has been to use the latest version of the ANCM._** We don't document different versions or when ANCM scenarios were rolled out over time.

Are we going to document ANCMv1? If so, I imagine that there's more (maybe even a lot more) content that we'll need to address in the topic. What we'd probably need to do is:

1. Determine the date the ANCMv2 came out.
1. Research back to the state of the topic at that point.
1. Contrast that version of the topic with today's content and add back missing ANCMv1 content. If the timing of the v2 release matches a framework major-minor release, version content using our normal versioning. Otherwise, it might be best to create a new ANCM topic for v1.
1. Understand what was changed for v1 since the release of v2, if anything, and make those updates (i.e., assume that the dev is using the latest release of ANCMv1).

I'll wait for your guidance on how you would like to proceed.

**Comment by jkotalik** [comment]
> Are we going to document ANCMv1 at all? Isn't it unsupported at this point?

There has been talk of backporting ANCMv2 to 2.1 s.t. we can remove ANCMv1 entirely. @shirhatti this is probably a better question for you.

**Comment by awe-source** [comment]
Well... purely selfishly I would support a "this changed" document...

TBH *once we figured out* that this "surprise" was related to ANCM 1/2 we went searching for "whats new" documents on this and all we found was "how to upgrade" which didn't include much detail beyond "change this string in web.config" and "see this doco" (the doco your reference above, which is the mostly same for ASPNET CORE 1..to..3 (on this page at least) you have some more features... but not much about what actually changed...

IF there are blogs or social/forum chatter, we couldn't find anything substantial.

I know "time marches onwards" and 2017 "was so long ago", but we are using a number of tools and libraries that don't work/have bugs/work weirdly between v1 and 2 and so we are sticking with some of these AND using v1 for specific reasons, so it would be nice to have this info "somewhere"...

Having said that I do understand the plight and expense of documentation, so I guess its up to you and how many others you think this will help...
