### ISSUE TITLE
High disk IO volume after upgrading to 3.0 

### ISSUE THREAD

**Issue by nur858** [dotnet/aspnetcore#17843]
We recently upgraded our containerized .net core  app to 3.0. But we started to see high disk write volume in /tmp directory. We took a peek in one of the files and it looked like it was temporarily writing response data in a tmp file  and unlinking after sending response.  Is it by design?  Would it be possible to use memory as temporary storage? 

DotNet version: 3.0
Kestrel Transport: Sockets
Container base: CentOS
cpu cores/container: 2
memory/container: 4GB

```
[pid 2931533] open("/tmp/ASPNETCORE_d297fa6b-4150-4762-a06e-4f31823e2945.tmp", O_RDWR|O_CREAT|O_CLOEXEC, 0666) = 398

[pid 2931533] write(398, "191217 38|191217 39|191217 40|19"..., 1024) = 1024
[pid 2931533] write(398, "137|191217 138|191217 139|191217"..., 1024) = 1024
[pid 2931533] write(398, "30|191217 231|191217 232|191217 "..., 1024) = 1024
[pid 2931533] write(398, "4|191217 325|191217 326|191217 3"..., 1024) = 1024
[pid 2931533] write(398, "|191217 418|191217 419|191217 42"..., 1024) = 1024
[pid 2931533] write(398, "191217 511|191217 512|191217 513"..., 1024) = 1024
[pid 2931533] write(398, "91217 623|191217 624|191217 625|"..., 1024) = 1024
[pid 2931533] write(398, "1217 744|191217 745|191217 746|1"..., 1024) = 1024
[pid 2931533] write(398, "18 786|191218 789|191218 790|191"..., 1024) = 1024
[pid 2931533] write(398, "9 853|191219 854|191219 855|1912"..., 1024) = 1024
[pid 2931533] write(398, " 981|191219 982|191219 983|19121"..., 1024) = 1024
[pid 2931533] write(398, "191218 396|191218 397|191218 398"..., 1024) = 1024
[pid 2931533] write(398, "91218 570|191218 571|191218 590|"..., 1024) = 1024
[pid 2931533] write(398, "191218 74|191218 75|191218 76|19"..., 1024) = 1024
[pid 2931533] write(398, "18 212|191218 213|191218 214|191"..., 1024) = 1024
[pid 2931533] write(398, "8 306|191218 307|191218 308|1912"..., 1024) = 1024
[pid 2931533] write(398, " 449|191218 450|191218 451|19121"..., 16384) = 16384
[pid 2951520] unlink("/tmp/ASPNETCORE_d297fa6b-4150-4762-a06e-4f31823e2945.tmp") = 0
[pid 2951520] close(398)                = 0
```

**Comment by Pilchie** [comment]
@rynowak @richlander

**Comment by Pilchie** [comment]
Oh, 3.0, not 3.1

**Comment by Pilchie** [comment]
Starting with `area-servers`

**Comment by Tratcher** [comment]
Probably the buffering in the legacy MVC response serializes (e.g. Newtonsoft.Json). @pranavkm

**Comment by nur858** [comment]
We tried downgrading to 2.2 and the disk write came down to 0 bytes. And yes we are using Newtonsoft.Json. we used newtonsoft.json with both 2.2 and 3.0

Does this mean that using newtonsoft + 3.0 is likely to result in high disk write volume?

**Comment by rynowak** [comment]
> Does this mean that using newtonsoft + 3.0 is likely to result in high disk write volume?

You can configure this behavior.

```C#
services.AddControllers(options =>
{
    options.SuppressOutputFormatterBuffering = true;
});
```

There's a tradeoff here.

In 2.2 and earlier the newtonsoft.json serializer would do synchronous writes to the output stream. For large payloads this could lead to thread starvation, and otherwise bad throughput performance.

In 3.0 and newer by default the newtonsoft.json serializer will buffer into memory (up to 32kb) and then to disk if the payload is larger than that. You can disable this behavior as shown above.

---

In 3.0 and newer if you use the System.Text.Json serializer, it's fully async, so it will work efficiently for any size payload.

**Comment by Tratcher** [comment]
Disabling SuppressOutputFormatterBuffering will also require enabling AllowSynchronousIO on the server. https://github.com/aspnet/Announcements/issues/342

**Comment by nur858** [comment]
Thanks for the response. 
> In 3.0 and newer by default the newtonsoft.json serializer will buffer into memory (up to 32kb) and then to disk if the payload is larger than that.

is 32kb configurable? any downside in increasing it? response from my service is less than 2MB. 

We were talking about switching to `System.Text.Json`. it requires quite a bit of work but we will get to the new json api.

**Comment by rynowak** [comment]
It's not configurable today - however if we made it configurable it would be a serious [footgun](https://en.wiktionary.org/wiki/footgun). 85kb is the threshold for an object entering the large object heap. If serving a request potentially puts objects in LOH that would be horrid for your app's performance. Since you're talking about 2mb that's well over the critical threshold.

You're probably here because you noticed a performance issue, I'd suggest trying with and without `SuppressOutputFormatterBuffering ` and see which is better for you.

-----

Another option you have would be to rewrite **just that method** to use `System.Text.Json` by serializing the results yourself. This is a smaller effort to unblock what you need without migrating the whole app.

```C#
public async Task MyActionThatReturnsLargeJsonPayload()
{
     HttpContext.Response.ContentType = "application/json;charset=utf-8";
     await JsonSerializer.SerializeAsync(HttpContext.Response.Body, myLargeObject);
}
```

**Comment by rynowak** [comment]
If you *really* wanted to get fancy, you could write an action filter that set `ObjectResult.Formatters` to include just the S.T.J formatter, and then you could progressively migrate that way.

**Comment by rynowak** [comment]
@nur858 - for us to look into this, is there any reason in particular where you're trying to avoid disk writes? Is there something else about your scenario/environment where disk ends up as a scarce resource? Trying to find info so we can investigate effectively.

**Comment by nur858** [comment]
I have a large fleet of containers running in the cloud serving a high traffic service. But large amount of disk writes saturated available IO bandwidth causing kernel panic.The service is a thin layer on top of cache and we were getting consistent response time with .net 2.2  but since we upgraded to 3.0, the response time got very spiky with certain percentage of timeouts. 

Would it be possible to use dedicated memory pool for output buffering when using newtonsoft instead of disk? This is clearly making kestrel a poor choice for high throughput service.

**Comment by davidfowl** [comment]
Thanks for that detail @nur858! We’re working on a workaround for you. There are a bunch but we’re looking for the one with the best tradeoffs. 

> Would it be possible to use dedicated memory pool for output buffering when using newtonsoft instead of disk? This is clearly making kestrel a poor choice for high throughput service.

The issues is that newtonsoft.json does blocking IO (which we disabled in 3.0) and we worked around This with disk buffering. The new JSON serializer is fully asynchronous and doesn’t have this problem but I assume you changed back to newtonsoft because of some missing features, we hope to improve that going forward.

There are some things to improve here regardless. Thanks for your patience!

**Comment by nur858** [comment]
Thanks @davidfowl.  that's very good news. We ran into similar predicament before  with newtonsoft. But we chose to stick to it for couple of reasons:
1. It's popularity and familiarity among developers
2. Reluctance to try a brand new API 
3. it was already being used by other services
 
Async serializer is clearly preferred choice but I am pretty sure there is appetite for using newtonsoft.json with 3.0 considering this is one of the most popular .net package out there. 

Thanks everyone for prompt response!!

**Comment by davidfowl** [comment]
@nur858 Do you have an idea of how big your response sizes are? I'm trying to decide if you're better off with a solution that just bumps up the buffer size.

**Comment by nur858** [comment]
@davidfowl yeah. largest response is ~2MB

**Comment by Systemic33** [comment]
Has there been any progress on this issue?
We’ve likely also run into this issue, as upgrading to .NET Core 3.x came with serious performance hits, and we have a similar setup of large JSON responses (~600kb) and reliance on newtonsoft due to heavy use of jsonconverters helping with deserialising a very hierarchical object system.

We’d love to use STJ, but it doesn’t seem advanced enough to support our use case yet.

Is there any documentation on using a particular serialiser only for serialising you response (without having to manually do it in the controller)?

**Comment by pranavkm** [comment]
@Systemic33 there isn't a built in way in MVC to configure a formatter per controller \ action. The closest would be to use content-types to perform selection. That said, you could write a formatter that delegates to one of the System.Text.Json or Newtonsoft.Json based formatters based on the presence of some metadata on the action descriptor.

**Comment by rynowak** [comment]
> @Systemic33 there isn't a built in way in MVC to configure a formatter per controller \ action. The closest would be to use content-types to perform selection. That said, you could write a formatter that delegates to one of the System.Text.Json or Newtonsoft.Json based formatters based on the presence of some metadata on the action descriptor.

You could use a result filter to manipulate `ObjectResult`. https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ObjectResult.cs#L26

**Comment by javiercn** [comment]
@pranavkm did we do anything in this area for 5.0?

**Comment by davidfowl** [comment]
Seems we missed the output buffering configuration options. I just checked and we only exposed a configurable threshold for the input buffer size 😭. We need to tackle this in 6.0

**Comment by Systemic33** [comment]
That's very unfortunate.

We currently mitigate/workaround this by forcing Kestrel back to synchronised request pipeline together with Newtonsoft JSON. Effectively running as if .NET Core 2.x.
The API only has internal services as users, so we can accept the issues that come with that.

**Comment by bstordrup** [comment]
@Systemic33 , exactly how did you do this? Facing slow serialization performance in a project when returning a 1-2Mb sized response.

**Comment by nur858** [comment]
If the slowness is due to disk IO and you are using newtonSoft.Json then you can try [enabling synchronous IO](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.allowsynchronousio?view=aspnetcore-5.0)
