### ISSUE TITLE
[BLAZOR WASM] Lagging textarea binding with large amount of text

### ISSUE THREAD

**Issue by michuny25** [dotnet/aspnetcore#17951]
I am using textarea in Blazor webassembly (core 3.1) which is binded to a property in the page. I am using bind-value and bind-value:event because when I use only bind="Property" then It does not update as the user is typing which is my use case. I am using this binded value to send requests and save current content of the textarea after the user stops typing.

``` <textarea @bind-value="Note.Content" @bind-value:event="oninput" @onkeyup="@NoteTypingKeyUp"></textarea>```

```razor
@code {
    [Parameter]
    public NoteDetailViewModel Note {get; set;}
    private Timer timer;
    protected override async Task OnInitializedAsync()
    {
        //Initialize timer
        timer = new Timer(300);
        timer.Elapsed += NoteStoppedTyping;
        timer.AutoReset = false;
    }

    private void NoteTypingKeyUp(KeyboardEventArgs e)
    {
        // remove previous one
        timer.Stop();

        // new timer
        timer.Start();
    }

    private void NoteStoppedTyping(Object source, ElapsedEventArgs e)
    {
        if (Note.Id == null)
        {
            if (!string.IsNullOrWhiteSpace(Note.Content))
            {
                InvokeAsync(async () =>
                {
                    await CreateNote();
                    await LoadNotes();
                });
            }
        }
        else
        {
            InvokeAsync(async () =>
            {
                await UpdateNote();
                await LoadNotes();
            });
        }
    }
```

It works fine when the text in the textarea is short. For large amounts it causes UI delays as the user types letters are appearing with a very significant delay.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23375592/71115463-3c7e9980-21d2-11ea-9cf4-3918da781a62.gif)

Is it a known bug and is there some workaround?
Thanks

**Comment by mrpmorris** [comment]
Please show your code for LoadNotes

**Comment by michuny25** [comment]
> Please show your code for LoadNotes

``` 
private async Task LoadNotes()
    {
        Console.WriteLine("Loading list of notes, searchContent: " + searchContent);

        notes = await authHttpClient.AuthGetJsonAsync<List<NoteListViewModel>>($"/api/notes?searchContent={searchContent}");

        StateHasChanged();
    }
```
```
    public class AuthHttpClientHelper
    {
        private readonly ServerAuthenticationStateProvider _authProvider;
        private readonly HttpClient _httpClient;
        private readonly DeviceState _deviceState;

        private string deviceId;

        public AuthHttpClientHelper(ServerAuthenticationStateProvider authProvider, HttpClient httpClient, DeviceState deviceState)
        {
            _authProvider = authProvider;
            _httpClient = httpClient;
            _deviceState = deviceState;
        }

        public async Task<T> AuthGetJsonAsync<T>(string url)
        {
            var authState = await _authProvider.GetAuthenticationStateAsync();

            if (authState.User.Identity.IsAuthenticated)
            {
                return await _httpClient.GetJsonAsync<T>(url);
            }
            else
            {
                if (deviceId == null)
                    deviceId = await _deviceState.GetDeviceId();

                Console.WriteLine("DeviceId: " + deviceId);
                
                if (url.Contains("?"))
                    return await _httpClient.GetJsonAsync<T>($"{url}&deviceId={deviceId}");
                else
                    return await _httpClient.GetJsonAsync<T>($"{url}?deviceId={deviceId}");
            }
        }
    }
```
There you go. But I am pretty convinced this doesn't cause the delay, beause it fires only when the user stops typing, but the lagging is while the user presses keystrokes. Moreover, I tried to commend out the content of the LoadNotes() and the lagging textarea for huge text still persisted.

**Comment by mrpmorris** [comment]
Can you create a new Blazor wasm app that reproduces this?

**Comment by michuny25** [comment]
I have created a sample repo showing this lagging behaviour in the textarea:
https://github.com/michuny25/TextareaBugReproBlazorWasm

Just copy in huge amounts of texts and you will see the lagging letters as you type.

![image](https://user-images.githubusercontent.com/23375592/71321712-ed7c8100-24bd-11ea-993e-9f083464c4e9.png)

**Comment by mrpmorris** [comment]
This is a more minimal reproduction of the problem.

```
@page "/"

<textarea @bind-value="Content" @bind-value:event="oninput" style="height: auto; min-height: 500px; width: 700px;"></textarea>

@code {
  public string Content { get; set; } = new string('x', 18000);
}
```

It seems the lag is when JS invokes Blazor in order to update `Content`

**Comment by michuny25** [comment]
Any update on fixing this?

Also, I noticed another issue with binding the value of a textarea to a property on 'oninput' event:
![image](https://user-images.githubusercontent.com/23375592/71721353-a0cd6a00-2e1c-11ea-971c-d662cba256a4.png)
Every time the user presses a keystroke the whole component is re-rendered which for bigger components means the UI is extremely lagging and is unusable.

Is there some workaround for binding the value of a textarea (in my case representing note) to a property on 'oninput' event without having the whole component to be re-rendered?

**Comment by mrpmorris** [comment]
> Is there some workaround for binding the value of a textarea (in my case representing note) to a property on 'oninput' event without having the whole component to be re-rendered?

```
private int ValueHashCode = 0;
protected override bool ShouldRender()
{
  int lastHashCode = ValueHashCode;
  ValueHashCode = YourValue.GetHashCode();
  return ValueHashCode != lastHashCode;
}
```

**Comment by captainsafia** [comment]
It's expected that Blazor components will trigger a re-render when an event handler is invoked. The solution that @mrpmorris shared above should help with programmatically controlling when re-renders happen.

As for the original performance issue, I profiled this on Edge with the latest version of Blazor WASSM (the RC, at the moment) with a textbox containing 18,000 characters. Each handler takes around 100ms to execute, which is slightly noticeable but not super laggy.

![image](https://user-images.githubusercontent.com/1857993/81442758-0ada8080-9129-11ea-9205-108abce0ccf9.png)

Some follow-ups:
- Can you profile the keypress events so we can get some numbers on performance?
- Are you able to repro the same lag on in more recent versions of Blazor?

**Comment by michuny25** [comment]
> Each handler takes around 100ms to execute, which is slightly noticeable but not super laggy.

That is correct. However, you have to look at context. Who types text in textarea in rate of 1 character/second? The delay obviously stacks, so when you type quickly you get delay of seconds before you see the word in the textarea.

Please use the multiple reproductions posted above to try the real UI experience in context.

**Comment by mrpmorris** [comment]
You could also havr the element change event go to solve javascript and control how often it calls blazor. Say, immediately, but not again for another 50 or 100ms, the typing experience might be better that way.

**Comment by silverx69** [comment]
I am having this problem too, it's very very easy to reproduce, you should not need an example from the community to reproduce this behavior, it's mind numbingly easy. Just bind-value and bind-value:event="oninput" or attach any onkey* event handler on a textarea OR input type="text" and hold a key down or try to type quickly, the words do not appear until you pause typing and let go of keys. This is very confusing to the user because they think it's not working until they stop typing and the text suddenly appears.

The strange part about this, is that I have an input box on another page that has an 'oninput' event handler and does not suffer from the same input lagg even though the event handlers are virtually identical. 

I have tried every single combination of onkeydown, onkeypress, onkeyup, oninput, onchange, etc.. There is no input lagg on the element unitl I attach a blazor binding/event-handler, and it seems to only happen on complex pages during the "onkeyup" phase.

The lowest amount of lagg I had in the elements were when using "onkeyup" as an event handler. If you hold a key down, there was no lagg, but if you tried typing random characters quickly then it would lagg. So my guess is there's something on the "KeyUp" handler internally that's slowing things down when attacked to events. I'm assuming a re-rendering.

**Comment by silverx69** [comment]
I think I might have found a workaround. @captainsafia had mentioned something that gave me an idea.

> It's expected that Blazor components will trigger a re-render when an event handler is invoked.

When an input control or textarea is INSIDE of a larger, more complex Blazor component, the events cause the parent component to re-render it's contents. This is laggy when the Blazor component is large, however!

If you make a NEW component, and ONLY put the input box in that component and then add that component in the same place as the original input box. It's renders MUCH MUCH MUCH faster, and I have virtually no lagg.

So this problem is definitely tied to how complex the input/textarea's parent component is, and you can side skirt this issue by placing the input in a much less complicated container component.
