### ISSUE TITLE
msftbot locks unresolved issues

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/aspnetcore#18110]
Hello everyone, I stumbled upon these three issues and I've noticed all three of them have been locked as resolved by msftbot even though they were not actually resolved nor assigned to a milestone.
https://github.com/aspnet/AspNetCore/issues/8071
https://github.com/aspnet/AspNetCore/issues/10657
https://github.com/aspnet/AspNetCore/issues/11745

Maybe this is the intended behavior but... isn't it a bit too harsh to prevent users from adding their feedback to an ongoing conversation like that?

**Comment by blowdart** [comment]
@anurse

**Comment by Pilchie** [comment]
See https://github.com/aspnet/AspNetCore/blob/master/docs/IssueManagementPolicies.md (specifically the sections on commenting on closed issues and locking closed issues).  The reason to do this is not to stifle feedback, but rather to make sure that it's going to an issue someone will actually look at.

**Comment by anurse** [comment]
Yep, @Pilchie is correct here. It's actually done to make feedback on closed issues ***more visible***. Comments on a closed issue are often lost, since they only notify other participants (who may not be able to handle them right away) and then because they are closed they don't show up in our normal triage process.

The bot locks the issue *precisely* to encourage what you just did @BrightSoul :). Posting a new issue to propose revisiting a discussion that was previously closed.

Note that the use of "Resolution" labels you may have seen elsewhere is a newer practice and many closed issues may pre-date them, so just because an issue doesn't have one doesn't mean the discussion wasn't resolved.

Looking at https://github.com/aspnet/AspNetCore/issues/8071 it looks like it was resolved by @SteveSandersonMS 's [comments](https://github.com/aspnet/AspNetCore/issues/8071#issuecomment-479100722) describing our current planning for Blazor recompilation.

https://github.com/aspnet/AspNetCore/issues/10657 was closed because we believed it to be fixed. If that's not the case, please feel free to file a new bug! In fact, it looks like someone did indicate that the bug may not be fixed but that question was lost and not followed up on (exactly why we discourage commenting on closed issues!).

https://github.com/aspnet/AspNetCore/issues/11745 was closed because the question was answered. Further discussions indicated a request for a feature but no issue was filed to track that.

**Comment by BrightSoul** [comment]
Thank you @anurse and @Pilchie for your detailed replies. I think I understand your point of view on this matter, even though I don't completely agree. Let me clarify, then we can consider this issue closed.

> Looking at #8071 it looks like it was resolved by @SteveSandersonMS 's comments describing our current planning for Blazor recompilation.
Ok, but is this really enough to consider an issue resolved? I think an issue like that, which is clearly a feature request (even if submitted in the shape of a question) should stay open and then marked as resolved only when said feature has been merged to a release branch (or rejected). If anything, it would help us developers/writers/trainers have some visibility into your backlog.

> our current planning for Blazor recompilation.
I admit I couldn't understand what your current plans are for this feature.

- @SteveSandersonMS said it would be restored in the "longer term";
- Then @danroth27 said it would be done for .NET Core 3.0 (which was not);
- No further update was given and no milestone was set.

I think I should just assume it's not been triaged yet or that it won't be released for .NET 5 either. How should people express their interest in this issue now, by opening many other duplicated issues?

I thought I would share my reasoning here since other developers could be puzzled like I was. I mean, @los93sol asked "Did the fix make it in?" and no proper response was given before the issue was locked like that.

Again, thanks for your attention.
Moreno

**Comment by anurse** [comment]
Fair questions, I was just clarifying how our process treats things. Things do sometimes get closed before everyone has reached consensus, which is why the bot has a lag of 30 days of _inactivity_ before locking. Sometimes due to a mistake, different plans for tracking work, etc. If an issue is locked and there are still open questions, it's totally reasonable to open a new one referencing the old one and asking for further clarification. Perhaps it was a mistake or the additional questions were missed? Or perhaps there were other reasons the issue wasn't reopened that could have been made clear. The bot doesn't know _why_ the issue went dormant, it just knows that the issue is closed and dormant and thus further replies are likely to be lost. So it locks the issue in order to encourage further responses via a more visible mechanism (a new issue).

It's up to the Blazor team how they want to handle specific feature requests like this, so I'll leave it to them to discuss the future of this *specific* issue.

**Comment by BrightSoul** [comment]
Thanks for clarification @anurse 👍
