### ISSUE TITLE
Create component dynamically using instance of the component

### ISSUE THREAD

**Issue by sylvainonweb** [dotnet/aspnetcore#18142]
### Is your feature request related to a problem? 
I created a PopupService.Show method which show a component as a popup/modal dialog which can be used like this.

```
  var result = await PopupService.Show(typeof(ForecastEditView), 
            new PopupParameters().Add(nameof(ForecastEditView.Id), forecast.Id));
        if (result.Success)
        {
                // Refresh the user interface (a grid for example)
        }
```

When creating the RenderFragment, the code is like this

```
  public RenderFragment Content
        {
            get
            {
                return new RenderFragment(x =>
                {
                    x.OpenComponent(1, this.ComponentType);

                    int i = 2;
                    foreach (var parameter in this.Parameters)
                    {
                        x.AddAttribute(i, parameter.Key, parameter.Value);
                        i++;
                    }
                    x.CloseComponent();
                });
            }
        }
```
with ComponentType = typeof(ForecastEditView)

Actually, because this method take the type of the component (here ForecastEditView), the parameters are represented as a Dictionary<string, object> so not **typed** parameters.

### Describe the solution you'd like
I would like to be able to do something like this.
```
var view = new ForecastEditView();
view.Id = forecast.Id;
  var result = await PopupService.Show(view);
        if (result.Success)
        {
                // Refresh the user interface (a grid for example)
        }
```

So I would like to be able to pass a instance (and not a type) of the component to the OpenComponent method of the render and let the framework manage the parameter by iterating on the property with [Parameter] attribute to set internaly the parameters.
Of course, I can do it on my own but each time I had to use the OpenComponent method, I add to manage the parameters so...

### Additional context
You can find the PopupService (using Telerik window) here https://github.com/sylvainonweb/blazor-ui/tree/master/common/popup

**Comment by SteveSandersonMS** [comment]
This kind of API is deliberately not part of the Blazor programming model, because the rendering system is meant to be responsible for the component lifecycle. This includes:

 * Instantiating the component
 * Performing dependency injection
 * Calling lifecycle methods
 * Tearing down and disposing

If it was possible to supply your own instance, it's no longer clear which parts of the lifecycle would be handled by the framework and which wouldn't. Also it would be unclear whether certain invariants that exist today could be violated (for example, the same component instance used multiple times in different places, simultaneously or successively).

## Suggested alternative

Consider passing a `RenderFragment` into the `PopupService`. You can dynamically create a `RenderFragment` that describes which component to render and what parameters to pass to it.

**Comment by mrpmorris** [comment]
I would have 
1. A Popup component that you wrap around your content that doesn't render its child content.
2. The component has a `Show` method which executes `IPopopService.Show(ChildContent)`
3. A component in my main layout that subscribes to an `IPopupService` and renders the passed RenderFragment.
