### ISSUE TITLE
Make RequestCookieCollection public

### ISSUE THREAD

**Issue by eduherminio** [dotnet/aspnetcore#18193]
### Use case
Properly mocking `HttpContext.Request.Cookies`.

### Proposed solution
Making `RequestCookieCollection` public, as it was before #11312.

### Additional context
Legacy mock:
`var cookies = new HttpCookieCollection { new HttpCookie("sth", "sthelse") };`

**Comment by anurse** [comment]
Is the interface (`IRequestCookieCollection`) not sufficient for mocking? We made these types `internal` because they were never actually officially supported (because they were in a `.Internal` namespace). We intentionally reserved the ability to make breaking changes to these types, since v1, and making them `internal` makes that clearer.

There's also nothing wrong with you just taking the code and bringing it in to your own tests.

**Comment by eduherminio** [comment]
`IRequestCookieCollection` isn't enough for my scenario due to not knowing how a dependency to interacts with it.
As a worse case scenario I can just copy the implementation code and use it directly, as you suggested, but the possibility of a breaking change being introduced that leaves the copied code out of date prevents me from thinking of it as an ideal situation.
Thanks, anyway!

**Comment by anurse** [comment]
> `IRequestCookieCollection` isn't enough for my scenario due to not knowing how a dependency to interacts with it.

I'm not really clear what you mean here. Do you have a dependency that is expecting specific behavior from `RequestCookieCollection`? If not, you should trust the interface here. It's intended to isolate you from the implementation and support exactly this kind of scenario (allowing components to use a different implementation).

**Comment by eduherminio** [comment]
I guess you're right, mocking `TryGetValue` and indexer should be enough in my case.
