### ISSUE TITLE
Building from source issue: "error : The DateTimeOffset specified cannot be converted into a Zip file timestamp"

### ISSUE THREAD

**Issue by matryosha** [dotnet/aspnetcore#18273]
Trying to build asp net core from source on release/3.1 branch with `build.sh -pack` command,  I'm getting several same errors on some projects:
```
error : The DateTimeOffset specified cannot be converted into a Zip file timestamp. (Parameter 'value')
``` 
[Full Log](https://pastebin.com/BQAfxeKM)

## Steps to reproduce:
1. Clone repo as [BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md) says
3. `cd` to aspnetcore directory
2. Checkout to `release/3.1` branch
3. Run `git clean -xdff`
4. Run `./build.sh -pack`

Also I shoud mention that running `build.sh` without arguments builds fine.

---

OS: ubuntu 19.10 and the same thing with ubuntu 18 LTS

Thanks in advance

**Comment by javiercn** [comment]
@matryosha thanks for contacting us.

@dotnet/aspnet-build can you assist here?

**Comment by dougbu** [comment]
(Odd because I believe our CI builds of 'release/3.1' are currently fine.)

@rrelyea this sounds a bit like the pack determinism issue that cropped up internally in September. Could that behaviour change be present in the 3.1.1-servicing.19576.9 SDK? Could any environment variables (accidentally) re-enable determinism?

**Comment by dougbu** [comment]
See also NuGet/Home#7001.

**Comment by pranavkm** [comment]
Does this still reproduce? I just tried this on Ubuntu 18.04 and `build -pack` works for me.
