### ISSUE TITLE
MarkupString does not consider @onclick

### ISSUE THREAD

**Issue by tossnet** [dotnet/aspnetcore#18301]
### Describe the bug
If I have to build a dynamic  interface from code by using MarkupString  and that I need to add events like @onclick, they don't work

### To Reproduce
``` C#
@page "/"

<div>
    @((MarkupString)sheet)
</div>

<p>Current count: @currentCount</p>

@code{
    private int currentCount = 0;
    string sheet = "";

    protected override async Task OnInitializedAsync()
    {
        sheet = "<div style=\"cursor: pointer;\" @onclick=\"MonthClick\">July</div>";
    }

    private void MonthClick()
    {
        currentCount++;
    }
}
```

is this currently normal or is there a palliative?

**Comment by javiercn** [comment]
@tossnet thanks for contacting us.

That's by design. MarkupString is intended for fragments that will end up as HTML in the browser, not for what you are trying to achieve.

We are not sure what you are trying to accomplish ("dynamic interface" is too generic for us to give you some guidance) but there are two ways you can go about this.

One is to write a component, pass in the parameters to it and handle all the dynamism inside the component by way of writing if-else, etc or by writing the component as a c# class and using the builder APIs.

**Comment by tossnet** [comment]
Yes, it's hard for me to explain. But look at this GIF. I've already made a prototype with Jquery:

![planning](https://user-images.githubusercontent.com/3845786/72258053-62e6f780-360d-11ea-959e-3718de8d7ca4.gif)

According to the clicks of the user, he can redraw the schedule (with DIV), I tried in SVG but I have the same problem : I can't connect events

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by tossnet** [comment]
@mkArtakMSFT I'm truly sorry for the inconvenience. I really thought it was a lack of the MarkupString.
