### ISSUE TITLE
Teach the ContentResultExecutor to honor RespectBrowserAcceptHeader setting

### ISSUE THREAD

**Issue by nulltoken** [dotnet/aspnetcore#18303]
### Is your feature request related to a problem? Please describe.
I'm proxying the result of an external http service and returning it as a `ContentResult` with Content-Type set to `application/json`.

### Describe the solution you'd like
I'd very much like the `ContentResultExecutor` to honor the `RespectBrowserAcceptHeader` and be able to return `Status406NotAcceptable` when the client expected content-type doesn't match what the endpoint is able to return (in the same way than `ObjectResultExecutor` @ https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ObjectResultExecutor.cs#L139-L156)

### Additional context
Would that feature requested be deemed worth of interest, I'd be very glad to work on a Pull Request to make it happen.

**Comment by rynowak** [comment]
We probably would not put something like this in the box, because it's the first time it has come up and it would be a breaking change.

The breaking change is that `ContentResult` currently just responds with whatever status code and content type you give it (always). If we made this change, then `ContentType` would start behaving differently - it's likely to break people's existing applications.

If you want to implement this yourself there are a few options:
1. Make you own action result type - this is attractive for a few reasons
2. Replace `ContentResultExecutor` - this is easy to do with DI

The code you'll need for handling the media type is this branch - https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/DefaultOutputFormatterSelector.cs#L284 - basically you have a known content type, and you need to the if the `Accept` header allows it. Assume `possibleOutputContentTypes.Count == 1`.

Another reason why you might want to write your own result type is that `ContentResult` is not going to be very efficient for what you're doing. Proxying is usually a pretty low-level concern - to use `ContentResult`, I assume your code has to convert the result into a string (allocating a lot of memory) and then convert it back to bytes.

The other problem you may encounter is that `ContentResult` is not generic, it's intended for text. If you need to proxy requests that carry non-text content, you will likely hit an exception in the text encoding system.
