### ISSUE TITLE
LinkGenerator generate url that doesn't exist

### ISSUE THREAD

**Issue by liuliang-wt** [dotnet/aspnetcore#18315]
In .netcore 2.2, LinkGenerator will return null when the controller and action doesn't exist,
but in 3.1, with the UseEndpoints, LinkGenerator will just return a wrong url if I pass a wrong action name.

Is this a bug or by design, if it is by design, is there a way to get the old behavior?

**Comment by rynowak** [comment]
This is by default for endpoints created by `endpoints.MapControllerRoute(...)`. This is the way "MapRoute" used with MVC controllers has always behaved.

We changed the behavior from 2.2->3.1 due to overwhelming feedback that applications depend on this behavior. There's no real way to get the 2.2 behavior back with `MapControllerRoute`. If you use attribute routing, it will behave like it did in 2.2.

**Comment by liuliang-wt** [comment]
Thank you for your answer. 

Is there a way I can force the LinkGenerator to generate url based on attribute routing?
There are both standard mvc controllers and webapi controllers(which use attribute routing) in my project. I have to use endpoints.MapControllerRoute for those standard mvc controllers and LinkGenerator works fine, but for webapi controllers, LinkGenerator will ignore those [Route("api/_[controller]")] attributes and retures a '/controller/action' format url which is wrong....

**Comment by rynowak** [comment]
So is this just about cases where no controller matches the route values? What I expect will happen (conceptually):

1. Link Generation processes attribute routes - no matches found.
2. Link Generation processes conventional routes (`MapControllerRoute`) - this will generate a URL because it doesn't check for the controller to exist

I think this has been the behavior for all released versions of MVC except 2.2 + endpoint routing.

**Comment by liuliang-wt** [comment]
thanks, now I understand.

If I have a action like this:

        [HttpGet("[action]/{id}")]
        public IActionResult CheckLogin(Guid id){...}

and if I only know the controller and action name, I have to do a reflection to check if this action has a parameter id, and then 
lg.GetPathByAction(controller,actionname, new { id = 0 }) to get the correct url.
