### ISSUE TITLE
Support for .NET Standard 2.0 IN Microsoft.AspNetCore.Authentication.JwtBearer 3.1.0

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/aspnetcore#18335]
I'm not seeing any movement on this - so just re-posting for a status update:

Is this issue getting looked at/fixed?
https://github.com/dotnet/aspnetcore/issues/17769

The only dependency is a NET Standard 2.0 compatible library:
Microsoft.IdentityModel.Protocols.OpenIdConnect

**Comment by blowdart** [comment]
No, as we don't consider it a problem.

See aspnet/Announcements#324 for the announcement last year explaining why,

**Comment by OpenSpacesAndPlaces** [comment]
Wouldn't this fall in the same vein as:
https://github.com/dotnet/aspnetcore/issues/17932
?

I bring it up as it would pertain to functionality of:
Microsoft.AspNetCore.Identity

---

From a general standpoint - I get removing libraries that require .NET Standard 2.1 to run, but this has the appearance just of removing 2.0 support just as matter of policy.

**Comment by blowdart** [comment]
Identity has uses outside of asp.net for some people. JWT middleware does not.

**Comment by anurse** [comment]
The JWT middleware is tied to ASP.NET Core, so it does not support .NET Standard 2.0 (since ASP.NET Core does not support .NET Standard 2.0). You can still reference it from a class library if your class library targets .NET Core 3.0 or higher. We have a doc on [using ASP.NET Core APIs from a library](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio) with details.
