### ISSUE TITLE
IHubContextAccessor

### ISSUE THREAD

**Issue by Odonno** [dotnet/aspnetcore#18440]
### Is your feature request related to a problem? Please describe.

That may follow the issue #12535 but I recently got a bug where I do not get the Principal Claim inside my hubs. And that caused me a lot of pain to change my architecture in order to extract the Principal Claim from either the `IHttpContextAccessor` and (somewhere I can set the current Hub Context).

### Describe the solution you'd like

So, the solution I found is a little painful and can lead to some mistakes if not used appropriately.

I would suggest to create something like the `IHttpContextAccessor` for hubs which can be named `IHubContextAccessor` that will provide all the necessary information on the current hub context, meaning the realtime input context.

That way, I can choose to consume either the current HTTP context or the current Hub context.

**Comment by anurse** [comment]
We have intentionally avoided adding `IHubContextAccessor` by design. For `IHttpContextAccessor` it was added because there was common usage of `HttpContext.Current` in ASP.NET 4.x apps. Ambient context like this is generally considered a bad idea since it hides the true dependencies your components have on the "active" hub context.

If you want to do something similar, you can store the active `HubContext` in an [`AsyncLocal`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1) value in a singleton service and build `IHubContextAccessor` yourself, but we don't plan to add this.
