### ISSUE TITLE
OAuthHandler doesn't perform RunClaimActions execution

### ISSUE THREAD

**Issue by olizarevichroman** [dotnet/aspnetcore#18442]
I noticed that CreateTicketAsync method in OAuthHandler doesn't perform RunClaimActions, but we can add ClaimAction to the ClaimActionsCollection when configuring an OAuthOptions. It seems weird cause user expects that data from JSON will exist when JsonKeyClaimAction is added. Also in the same method i see `using (var user = JsonDocument.Parse("{}"))` what means that all data from OAuth server will be skipped. From user side this behaviour is not understandable.

**Comment by anurse** [comment]
The OAuthHandler is very general-purpose and not really usable on it's own since the spec doesn't formalize a way to redeem tokens. You have to add your own logic. The claim actions are an example of this. The options type carries a list for convenience, but it's up to your handler to run them. For example, in the "SocialSample" in our repo, we configure a GitHub-based authentication handler using the OAuth handler and run the claims actions manually: https://github.com/dotnet/aspnetcore/blob/91d17f6c2dfcd4bd296a447faffc0893cdad4e9e/src/Security/Authentication/samples/SocialSample/Startup.cs#L152
