### ISSUE TITLE
Blazor WASM event:preventDefault on Components

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#18460]
This code returns me this error:
````csharp
<NavLink href="@item.NavLink" ActiveClass="selected-border-left" Match="Match" @onclick:preventDefault @onclick="()=>Navigate(item.NavLink)" >
@item.Label
</NavLink>
````

The component parameter 'onclick' is used two or more times for this component. Parameters must be unique (case-insensitive). 
The component parameter 'onclick' is generated by the '@onclick' directive attribute.

So how Can I prevent Navigation when clicking and just have my method fired ?

Thanks.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

@SteveSandersonMS do you have any thoughts here?

**Comment by SteveSandersonMS** [comment]
I'm afraid there isn't a mechanism for passing through arbitrary directive attributes such as `@*:preventDefault` as component parameters, so this isn't expected to work on `NavLink`.

However, you could inherit your own subclass from `NavLink` that adds the "prevent default" behavior. For example, create `NavLinkPreventDefault.razor`, containing this:

```razor
@inherits NavLink
<a @attributes="@AdditionalAttributes" class="@CssClass" @onclick:preventDefault>
    @ChildContent
</a>
```

Now you can use `<NavLinkPreventDefault>` instead of `<NavLink>` to get the behavior you want.

**Comment by JulienM28** [comment]
Thanks for you answer.
I though about something looking that but it was a bit confused in my head about how it will work with inheritance of components as there is no abstract or virtual in NavLink Component.

Thanks.

**Comment by JulienM28** [comment]
Is it possible to add preventDefault in rendertreebuilder ?

**Comment by SteveSandersonMS** [comment]
It's possible that putting the attribute `preventDefault_onclick="true"` onto the `<NavLink>` would actually achieve what you want here, but note that the magic internal attribute name is **not** part of the supported public API and therefore is subject to unannounced breaking changes at any time. The subclassing approach is supported and safe.

**Comment by JulienM28** [comment]
Thanks.
