### ISSUE TITLE
Hot Reload for ASP.NET Core

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18486]
.NET 6.0 is introducing support for Hot Reload during development.

This issue is tracking ASP.NET Core specific changes required to make the developer experience great when code changes are applied via the new Hot Reload feature in .NET 6.0. These code changes are anticipated to be those supported by the runtime's Edit and Continue feature, or new versions of an entire type, in cases where ASP.NET Core could support appropriate remapping to the new type (e.g. a Razor View).

- [ ] [Support Code Hot Reload (EnC) for Razor](https://github.com/dotnet/aspnetcore/issues/18486)

**Comment by EmadKaizen** [comment]
Hi @mkArtakMSFT, Thanks for your great efforts for making Asp.net core more powerful. I was searching for Asp.net Core Hot Reload feature but I have struggled to find any good solution.

We are using [Flutter hot reload](https://flutter.dev/docs/development/tools/hot-reload) and you can't imagine how this feature makes us productive while prototyping and making new apps.

For Asp.net Core we have found [watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1) tool, but it's relay not making us productive because it's not supporting debugging with breakpoints and the state of the server restarts each time we save our changes.

What we expect to be able to set breakpoints in our controllers, start the server, add or modify new methods and codes then click save and see the changes when we hit the controllers again without the need to restarting the asp.net app.

Is that what you are trying to implement?

**Comment by imuller** [comment]
Is there any update on this? This would make is super productive when working on .net core applications.

**Comment by cyq1162** [comment]
a solution to help with this problem : https://www.cnblogs.com/cyq1162/p/14280939.html

**Comment by SvenAelterman** [comment]
@mkArtakMSFT Can you remove the clickbait comment from Jan 15, please?

**Comment by sander1095** [comment]
@mkArtakMSFT 

Hello! I want to ask you the same thing as @EmadBustati . 

If this were implemented, could I change code in my controller (or domain, or any other layer of my application) during development and things would hot reload? Or is only for the API project?

My project does not use razor; it's purely an API that returns JSON; would this be supported?

**Comment by Kevin-Winter-Codes** [comment]
https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload?

**Comment by nphmuller** [comment]
Here's a community solution that implements hot reloading for Razor which you might want to look at for inspiration: https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload

**Comment by hez2010** [comment]
> @mkArtakMSFT
> 
> Hello! I want to ask you the same thing as @EmadBustati .
> 
> If this were implemented, could I change code in my controller (or domain, or any other layer of my application) during development and things would hot reload? Or is only for the API project?
> 
> My project does not use razor; it's purely an API that returns JSON; would this be supported?

According to previous .NET 6 preview release blogs, I think the answer is YES.

**Comment by MaherJendoubi** [comment]
Does this include Hot Reload for ASP.NET Core in docker?

**Comment by PeterHimschoot** [comment]
Hot reload builds my project, and then again, and then again, etc...

Is there a hotfix available? Am I the only one?

**Comment by pranavkm** [comment]
@PeterHimschoot could you please file a separate issue for the bug you're running in to? 

@MaherJendoubi we haven't look at the docker scenario as yet. I filed https://github.com/dotnet/aspnetcore/issues/31908 to investigate what it would take for us to support it.

@sander1095 sorry for the late response, but we expect most .NET 6 workloads to work by the end of 6.0. The way it manifests might be different - for instances Blazor apps can re-render when a hot reload event happens, but a view or an API with swagger would require a browser refresh to see the update, but we expect changes to be applied to apps without needing a rebuild.

**Comment by pranavkm** [comment]
Closing this as the initial set of features have landed in the preview3 and preview4 milestones and soon in VS.
