### ISSUE TITLE
UseEnvironment does not work when using generic host based webhost

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#18499]
Seems like we override the configuration keys as the last entry in the host configuration when `ConfigureWebHostDefaults` is called. This might affect other host setting as well.

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseEnvironment("Staging")
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    // webBuilder.UseEnvironment("Staging"); // This works
                });
```

cc @Tratcher

**Comment by BrennanConroy** [comment]
I'm not sure this is really fixable without either introducing a whole other method for adding config (`ConfigureThisConfigLast(...)`) or adding a method to add configuration to the builder in a different order (`ConfigurationBuilder.AddFront(IConfiguration)`)

The above example could be made to work by just setting the Environment after ConfigureWebHost
```c#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseEnvironment("Staging"); // Works now
```

**Comment by Tratcher** [comment]
Can you share a few links into the code where it breaks down?

**Comment by BrennanConroy** [comment]
`UseEnvironment` calls `ConfigureHostConfiguration`
https://github.com/dotnet/runtime/blob/8953bab5c03c717296dfb57107330b0aff87e16e/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L25
`GenericWebHostBuilder` constructor also calls `ConfigureHostConfiguration`
https://github.com/dotnet/aspnetcore/blob/1be16fb4c9942503477d185cc20e0afbcd4590dc/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L40

The `ConfigureHostConfiguration` method adds the delegate to a list
https://github.com/dotnet/runtime/blob/8953bab5c03c717296dfb57107330b0aff87e16e/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L46
And then iterates over that list when building
https://github.com/dotnet/runtime/blob/8953bab5c03c717296dfb57107330b0aff87e16e/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L141

The order of config is last one wins, so whoever adds config last will override the values from other config providers. Which is why putting `UseEnvironment` after `ConfigureWebHostDefaults` will make `UseEnvironment` work.

**Comment by Tratcher** [comment]
Idea: Don't rely on config, directly modify the environment on the HostBuilder. How? Maybe add a property to HostOptions and make the options available somewhere during the build process? If it's set then don't try to read Environment from config.

Backup: Put something into HostBuilder.Properties that's higher priority than config.

https://github.com/dotnet/runtime/blob/8953bab5c03c717296dfb57107330b0aff87e16e/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L153

**Comment by BrennanConroy** [comment]
Ping @davidfowl

**Comment by Tratcher** [comment]
Closing this as we don't see a good way to fix UseEnvironment without completely replacing it.

**Comment by davidfowl** [comment]
Why not in 6.0?

**Comment by Tratcher** [comment]
Do you think it's worth obsoleting UseEnvironment and replacing it with a new API in 6.0? If so then move this issue to the runtime repo.

My proposal for a new API would be a new HostBuilderOptions with an Environment property that overrides config. This would be passed to a new HostBuilder constructor.

What about CreateDefaultBuilder? Add an overload that also takes HostBuilderOptions, or maybe one that takes a new DefaultBuilderOptions that exposes HostBuilderOptions as well as various opinions like config reload on change:
https://github.com/dotnet/runtime/blob/e94dc2f387117073074f295c573c4d40344749fb/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L74
