### ISSUE TITLE
ReferenceReadStream is not compatible with CryptoStream

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#18503]
### Describe the bug
Very similar to https://github.com/aspnet/KestrelHttpServer/issues/2341 (PR https://github.com/aspnet/KestrelHttpServer/pull/2342) the `ReferenceReadStream` does throw a `NotSupportedException` in its `Flush` method when it should not.

### To Reproduce
```
using(var cs = new CryptoStream(formFile.OpenReadStream(), ...))
{
    throw new Exception("stream has not been read completely and therefore CryptoStream will call Flush");
}
```
This should not trigger a `NotSupportedException`.

### Further technical details
- ASP.NET Core version 2.1.x on .NET Framework 4.7.2

**Comment by anurse** [comment]
Seems reasonable to just no-op in `Flush` instead of throwing.

The simplest workaround you can use for now (and in 2.1, since the change would be in 5.0) would be to build your own wrapper that forwards all calls to the inner stream **except** `Flush` and then wrap that around `ReferenceReadStream`.

**Comment by drauch** [comment]
A pity it's not backported, but I guess the workaround is good enough. Thank you for the quick response.
