### ISSUE TITLE
Using the SVG elements in a page and translating the page using google translator

### ISSUE THREAD

**Issue by Indrajith-Sync** [dotnet/aspnetcore#18517]
I am using the SVG element in a page and when transulating the page to german language i am facing the following script error in console. 

![image](https://user-images.githubusercontent.com/29561170/72927318-f9d55180-3d7b-11ea-9275-764740d1da91.png)

> error: "Uncaught TypeError: a[b].target.className.indexOf is not a function"

have anyone got a solution for this?

**Comment by javiercn** [comment]
Thanks for contacting us <<mention>>.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by javiercn** [comment]
Thanks for contacting us @Indrajith-Sync.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow.

We don't have enough information in this issue to understand what your problem is.
