### ISSUE TITLE
Client Side Blazor seems to hide the message coming back from HTTP request

### ISSUE THREAD

**Issue by americanslon** [dotnet/aspnetcore#18527]
I have an API that, upon failure, returns 500 and "Something went wrong. Please try again later." as body of the message (as well as in the reason phrase just in case). That is confirmed working by running that request with Postman.

The call is called in my Blazor app as follows

`
var response = await Http.DeleteAsync("api/organizations/delete?Id=" + deleteId);
 System.Diagnostics.Debug.WriteLine(response);
`

What I get is 

`
Failed to load resource: the server responded with a status of 500 (Something went wrong. Please try again later.)
blazor.webassembly.js:1 WASM: ﻿StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler+WasmHttpContent, Headers:
blazor.webassembly.js:1 WASM: {
blazor.webassembly.js:1 WASM:   Date: Thu, 23 Jan 2020 00:57:55 GMT
blazor.webassembly.js:1 WASM:   Server: Microsoft-IIS/10.0
blazor.webassembly.js:1 WASM:   Transfer-Encoding: chunked
blazor.webassembly.js:1 WASM:   X-Powered-By: ASP.NET
blazor.webassembly.js:1 WASM: }
`

Nowhere is my custom "Something went wrong. Please try again later." shows up and Blazor replace reason phrase with the generic 500 reason phrase.

Expected behavior or bug?

**Comment by americanslon** [comment]
``

**Comment by pranavkm** [comment]
@americanslon invoking a HTTP Client method does not throw if the request completed - hhttps://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.deleteasync?view=netstandard-2.1. You're free to inspect the response to have it throw: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode?view=netframework-4.8#System_Net_Http_HttpResponseMessage_EnsureSuccessStatusCode. 

This isn't a Blazor specific question though, I'd recommend using StackOverflow if you have further questions on using `HttpClient`.

**Comment by americanslon** [comment]
@pakrym I am not sure we are understanding each other; what does not throw when request is completed? 

Are you saying that HttpClient drops content of the response if the response code is not IsSuccessStatusCode?

**Comment by americanslon** [comment]
Bump

**Comment by pranavkm** [comment]
@americanslon calling `DeleteAsync` will not throw if the request completed with a 500 response. Invoking `EnsureSuccessStatusCode()` on the response should throw an exception. Alternatively, you can inspect the response and choose to make a decision based on the status code:

```C#
var response = await client.DeleteAsync("...");
if (response.StatusCode != 200)
{
  // Do something with an error response
}
else
{
   // Do something with a success response
}
```

**Comment by americanslon** [comment]
@pranavkm Please the original question again......I didn't ask about anything throwing anything. I don't have a problem with not receiving proper status code. 

The issue is that **there is no content coming from API when status code is 500**  (not in the body of the response, not in the reasonphrase) when there should be

**Comment by szmalec** [comment]
I also recently encountered this problem - in my case it appeared when I wanted to use the "Problem Details for HTTP APIs" (see eg. [here](https://codeopinion.com/http-api-problem-details-in-asp-net-core/)) mechanism in my Blazor WASM application.
I asked about this problem on [gitter here](https://gitter.im/aspnet/Blazor?at=5e38814d6f9d3d34981bcace) but I could not get a satisfactory answer.
In my case, it turned out that there is no problem when using `PostJsonAsync`, but problem appears when using `GetJsonAsync`. 
It seems that the way `PostJsonAsync` (uses [SendAsync](https://github.com/dotnet/aspnetcore/blob/v3.1.1/src/Components/Blazor/Http/src/HttpClientJsonExtensions.cs#L99)) and `GetJsonAsync` (uses [GetStringAsync](https://github.com/mono/mono/blob/mono-6.8.0.96/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs#L331)) work seems to be somewhat inconsistent in the context of using "ProblemDetails", doesn't it?
From what I see the following implementation has no problem that I described:
```cs
namespace BlazorApp4.Client
{
    public static class Exts
    {
        public static async Task<T> GetJsonAsync2<T>(this HttpClient httpClient, string requestUri)
        {
            var res = await httpClient.GetAsync(requestUri);
            res.EnsureSuccessStatusCode();
            return JsonSerializer.Deserialize<T>(await res.Content.ReadAsStringAsync(), new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true });
        }
    }
}
```
when I call `GetJsonAsync2` and status code is eg. 400 or 500 then content is also fetched and I can read more details describing reason of failed request.
