### ISSUE TITLE
Consider changing or adding to the MessagePackProtocol options

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#18569]
In MessagePack-CSharp v2 there is a `MessagePackSerializerOptions` class that can be passed to the serializer. Currently we expose a list of `IFormatterResolver`s for the user to configure, but there are other options like compression and `IMessagePackFormatter` that we don't expose.

Options: https://github.com/neuecc/MessagePack-CSharp/blob/8eeb7b8ab71ff7d70f8b2013589423eadbba90b7/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs#L15

Discussion: https://github.com/dotnet/aspnetcore/pull/18133#discussion_r369195152

**Comment by tebeco** [comment]
hello @BrennanConroy 
Sorry to beother you about it again, i remember you wrote a comment ... somewhere ... containing the ApiReview + link to the UnitTest validation custom MessagePack Options/Formater/Resolvers

i can't seem to find your comment here or in my mail or on `aspnet/aspnetcore` ...
As I'm still not sure if i have the background to submit an idea of these new "options", i supposed that having the equivalent of this "lost message" would be nice here

**Comment by tebeco** [comment]
So after trying to understand what could be the various ideas, i'm not sure what/how to change ^^

If i describe what i understand from the "code flow" :

* The current `MessagePackHubProtocolOptions` class from `SignalR` that "kinda wrap" the message pack one [expose an `IList<IFormatterResolver>`](https://github.com/dotnet/aspnetcore/blob/7def10277abbb3086c4ee00e369faf6aa27d676a/src/SignalR/common/Protocols.MessagePack/src/MessagePackHubProtocolOptions.cs#L14)
* `MessagePackOptions` exposes [only a SINGLE `IFormatResovler`](https://github.com/neuecc/MessagePack-CSharp/blob/eed05edcda7e48227aa96689ee644e4450ce6728/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs#L70)

This transition from "Multiple" to a "Single" is done in a call to `SetupResolver` from the `MessagePackHubProtocol constructor`, 
* It checks if the consumer changed the default one (either by count or ref check)
* then uses static method from `MessagePack` : `MessagePackSerializerOptions.Standard.WithResolver(resolver)`

The `Cache<T>` is kinda like "smart `Dictionary<Type, Resolver>` leveraging on the fact that `static ctor` being threadsafe i guess ?

#### Questions :
* Why does `SignalR` exposes an `IList<>`, since at the end it results in a single `FormatterResolver` ?
I suppose that if it's designed like this there's a good reason for that, i'm curious here ^^

* It "could" directly resolves an `IOptions<MessagePackSerializerOptions>`
It would look like the same idea behind `JsonOption` for `Mvc` => 1 Formater, and you just need to properly `.Configure` it as a consumer ?

There's probably other things / way i did not though about ^^

**Comment by tebeco** [comment]
would love @AArnott point of view here, as you probably have a way better insight than me here

**Comment by AArnott** [comment]
Exposing `MessagePackSerializerOptions` will give the app owner more control. They could turn on compression, fiddle with security settings, etc. 

Does aspnetcore require any resolvers to be included in the list, for its own types? If not, then exposing `MessagePackSerializerOptions` to the user and using their exact instance internally makes sense, IMO.
But if aspnetcore needs to ensure that some of its own types can be serialized via some particular resolver, it gets more complicated. You can check out our [`MessagePackFormatter`](https://github.com/microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/MessagePackFormatter.cs) class from StreamJsonRpc as an example where we let the user supply their own `MessagePackSerializerOptions` instance (see the `SetMessagePackSerializerOptions` method), but we then alter it slightly in order to 'wrap' the user-supplied resolvers with our own. We take very special care to only use the user's selected resolvers for user data, and only our own resolvers for our types that tend to 'wrap' that user data.

**Comment by tebeco** [comment]
I forgot to mention that by default the resolvers are :

```
            public static readonly IList<IFormatterResolver> Resolvers = new IFormatterResolver[]
            {
                DynamicEnumAsStringResolver.Instance,
                ContractlessStandardResolver.Instance,
            };
```

**Comment by BrennanConroy** [comment]
> But if aspnetcore needs to ensure that some of its own types can be serialized via some particular resolver

We don't let users customize how the signalr framing is handled, the options are only for their types. So we don't need to set anything on top of the custom settings they provide.

> then exposing `MessagePackSerializerOptions` to the user and using their exact instance internally makes sense

Yes, that would be the ideal situation. It is slightly inconvenient that we currently provide a list as our options, but maybe we can mark it obsolete and provide the new options type.

**Comment by AArnott** [comment]
> We don't let users customize how the signalr framing is handled

@BrennanConroy Does your code ever call into the `MessagePackSerializer`, or are you always working directly with `MessagePackWriter` and `MessagePackReader`?
How do customers get their types serialized? Do they (or you) call directly into the resolver/formatter to serialize them or do customer types go through `MessagePackSerializer`?

I'm curious about how signalr framing relates to the customer types that those frames may carry, as that can impact what you do with their `MessagePackSerializerOptions`.

**Comment by BrennanConroy** [comment]
Customers types go through the serializer, our framing goes through the reader/writer.

**Comment by tebeco** [comment]
> @BrennanConroy Does your code ever call into the MessagePackSerializer

check the screenshoot in the PR description :D
that's a perfect sample (also one VERY RARE place of the code doing a direct call), it's not exposed to the client thought IIRC

**Comment by AArnott** [comment]
OK, sounds good.

**Comment by tebeco** [comment]
@BrennanConroy 
do you mean that the `ctor` of `MessagePackHubProtocol` can be changed from :
`public MessagePackHubProtocol(IOptions<MessagePackHubProtocolOptions> options)`
to 
`public MessagePackHubProtocol(IOptions<MessagePackSerializerOptions> options)` ?

just to be sure

**Comment by tebeco** [comment]
@AArnott do you know any alternatives to the preview points ?
It seems to end up with a "SignalR Options wrapping MessagePack Options again" :s

**Comment by AArnott** [comment]
I'm not too familiar with ASP.NET Core or SignalR's typical patterns here. `IOptions<T>` in particular I don't yet understand. But if `IOptions<T>` puts certain constraints on `T` and `MessagePackSerializerOptions` doesn't fit, I see two options:

1. drop the `IOptions<T>` wrapper and just use `MessagePackSerializerOptions` directly
1. Use `IOptions<MessagePackHubProtocolOptions>` and simply change `MessagePackHubProtocolOptions` to have a `MessagePackSerializerOptions` property instead of the list of resolvers that it took before.

**Comment by tebeco** [comment]
ok so we endup for the same 2 suggestions

**Comment by AArnott** [comment]
If you were hoping I'd recommend one, I appreciate the opportunity, but I just don't know your API design and what customers expect enough to feel I have a well informed opinion.

**Comment by tebeco** [comment]
i just wanted to be sure i did not missed other possible design :)


Regarding `IOptions<T>` in `AspNetCore`,
my choice of word are going to be very very bad, and i hope it's not missleading :
I'll speak for `AddOptions/IOptions`, not for `ISnapshotOptions/IMonitorOptions`
it will register an entry in the `DI container` and this will be instanciated for by the very first time `IOptions<T>.Value` is call
it's like a mix of `Lazy<T> + Singleton` 

so :
* the DI will do the `new` ==> need a ctor
* it will register/wrap the reference of that `T` inside this `IOptions`
* the `IOptions` is also done within the framework

that means :
* need a ctor
* cannot changed the "internal tracked reference"

**Comment by tebeco** [comment]
I think this is the definition of irony ...

![image](https://user-images.githubusercontent.com/2266487/77164446-92ecc400-6ab0-11ea-9b4d-7bf9246b1754.png)

**Comment by AArnott** [comment]
I'm not sure I see the correlation. SignalR doesn't use StreamJsonRpc, does it?

Just FYI, that is an NRE thrown from another process, and JSON-RPC is just the messenger, bringing it back in-proc and informing VS that a failure occurred somewhere else.

**Comment by tebeco** [comment]
This is VisualStudio crashing while opening signalr repo when i tried to work on this issue ;)
And this thread spoke about that lib as an example, this is pure coincidence ^^

**Comment by tebeco** [comment]
@BrennanConroy 

As of today, the code ALWAYS does this :
`_msgPackSerializerOptions = options.WithSecurity(MessagePackSecurity.UntrustedData);`

So if we open `MessagePackSerializerOptions` open to the consumer :

* do we still enforce this ?
* should it log a `Warn` ? (or does `MessagePack` already log a warning if the `serializer` is used for that @AArnott ?)
* do we let the consumers fully responsible of what they do if they customize it ?

**Comment by AArnott** [comment]
No warning is produced when using the default `TrustedData` setting.

I assume you have customers that build web apps for intranets, or for authenticated users where the trust level is higher. There are some small perf gains to be had from using UntrustedData, and some functionality is more likely to work by default (like serializing dictionaries where the key isn't known to be collision resistant). So yes, I think you should allow customers to use TrustedData.

But to help users be on the safe path by default, what you might do is add a `MessagePackHubProtocolOptions.UseUntrustedData` boolean property that is set to `true` by default, and use `options.WithSecurity(MessagePackSecurity.UntrustedData);` when that's set to true. This way it's secure by default, and someone has to explicitly opt out of that protection to get to TrustedData behavior.

**Comment by tebeco** [comment]
with current design + `IOptions` support that scenario :

`MessagePackHubProtocolOptions.cs` : 
```
// pseudo equivalent code (the `setter` is public and defaulted to a secured one) :
public MessagePackSerializerOptions SerializerOptions {get;set;} = MessagePackHubProtocol.CreateDefaultMessagePackSerializerOptions();
...
internal static MessagePackSerializerOptions CreateDefaultMessagePackSerializerOptions() =>
            MessagePackSerializerOptions
                .Standard
                .WithResolver(SignalRResolver.Instance)
                .WithSecurity(MessagePackSecurity.UntrustedData); <===== secured by default
```


`HubProtocol.cs` :
```
        public MessagePackHubProtocol() : this(Options.Create(new MessagePackHubProtocolOptions())) {} // <=== use a the default values of the `Options`
        public MessagePackHubProtocol(IOptions<MessagePackHubProtocolOptions> options) // Will look in the DI if there's a registration for `IOptions<MessagePackHubProtocolOptions>`
```


If a customer want to change it i suppose they would just do :

Either :
```
services
  .AddSignalR()
  .AddMessagePackProtocol(options =>
{
  // Trusting Data :
  options.SerializerOptions = options.SerializerOptions.WithSecurity(MessagePackSecurity.TrustedData);

  // full new options :
  options.SerializerOptions = theirOwnMessagePackSerializer;

  // combining Formatter (looks weird to my eyes)
  options.SerializerOptions = MessagePackSerializerOptions.Standard.WithResolver(CompositeResolver.Create(new CustomFormatter(), options.SerializerOptions.Resolver));
});
```

Or :
```
services
  .AddSignalR()
  .AddMessagePackProtocol()

service.Configure<MessagePackHubProtocolOptions>(otpions => /* Same code block as above */);
// or
service.PostConfigure<MessagePackHubProtocolOptions>(otpions => /* Same code block as above */);
```
