### ISSUE TITLE
Load code section before rendering page 

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#18616]
Hi
I've been having a lot of trouble writing conditions to avoid errors on page rendering due to variable have been not yet instancialized. That's a pretty big annoying thing to do that would be simply solved if Blazor would read the code section first. That would save a lot of unecessary work doing validations like "if variable not null foreach...". Or at least, if he read the variables declaration first, it would also be cool. Because when i declare the variables i call already instanciate them with values from, for example, some static class.
Even in the same degree of importance, when rendering the page, Blazor should ou could not try to put IN the DOM objects that will not be rendered to the page. I don't know if that is feasible. Like those elements inside a tag with visibility:none. Because i can be waiting for values for that section and only later on they will be shown, and when that happens, it as to go all the times through that pageload safeguard verification if a certain variable is null or not,

**Comment by pranavkm** [comment]
@Ricardoaraujo00, we think having the option to begin rendering before values are fully gathered is useful. It enables scenarios such as loading spinners. https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#handle-incomplete-async-actions-at-render has an example of how this works. Instead of putting individual fields behind null-checks, you can use a single flag to indicate your fields are ready.

**Comment by mrpmorris** [comment]
There are lifecycle hooks you can override to initialise data before your component is rendered.
