### ISSUE TITLE
Blazor: Improve VS tooling for CaptureUnmatchedValues 

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#18748]
When using` [Parameter(CaptureUnmatchedValues = true)]` it would be great if  Visual Studio tooling would displays all available attributes like it does for regular elements:

![image](https://user-images.githubusercontent.com/8482283/73653542-ab805680-4689-11ea-8eda-65b521d79c4b.png)

However, the tooling currently is showing this:

![image](https://user-images.githubusercontent.com/8482283/73653609-da96c800-4689-11ea-9d92-1366d2de446f.png)

Is this something you want/can improve?

**Comment by SteveSandersonMS** [comment]
It's an interesting idea, and at some point we might look into putting a feature like this into the tooling.

It will only make sense if we had some way to indicate that a certain component "behaves like" a particular HTML element (in your example, like an `input` element). Otherwise, the tooling would not know which attribute are relevant, or even that HTML attributes are relevant at all. In general, Blazor components don't necessarily use `CaptureUnmatchedValues` to capture HTML attributes - they can use them to capture completely arbitrary data.
