### ISSUE TITLE
TCP Listener not working in Blazor Wasm.

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#18776]
I need to create http server in blazor wasm 
, I am using tcp listener to create web server. I am getting platform not supported error.
How can i get a http web server working on blazor??

**Comment by javiercn** [comment]
@sps014 thanks for contacting us.

We think this will be an issue better suited for the [mono](https://github.com/mono/mono) repository. 

That said, I don't think what you are trying to accomplish here is ever going to work. The set of things that you are able to do in WebAssembly is limited by the set of things you can do in the Browser. A good example of this is HttpClient. While you have full control on .NET code running on a PC, you don't have such control on the Browser when using the equivalent `fetch` API due to security restrictions imposed by the browser.

With that in mind, the browser doesn't expose raw TCP abstractions so it is unlikely this is ever going to be supported unless something changes in the future on WebAssembly to enable it.

**Comment by ayush143** [comment]
Yeah , that seems a mono issue.
Is Serial Communication is supported on wasm ??

**Comment by sps014** [comment]
Yeah Serial com works, don't know how they managed to get it working.
