### ISSUE TITLE
IPageLoader is [Obsolete]

### ISSUE THREAD

**Issue by wangkanai** [dotnet/aspnetcore#18801]
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.RazorPages/src/Infrastructure/IPageLoader.cs

I see that you are obsoleting `IPageLoader`. I did a search and found this issue #8016 and #480.
When are you planning to remove this interface? Its has been 11 months already and 3.1 release is out and now in development for .net 5

Did you forget about it?

**Comment by javiercn** [comment]
@wangkanai thanks for contacting us.

This was marked as obsolete for the 3.0 release, so I imagine we will remove it on 5.0. We normally obsolete if for 1 release and then remove it afterwards, 3.0 and 3.1 were very close together so that's likely why we didn't do it in 3.1.

@mkArtakMSFT I'm moving this to next sprint planning to track the removal as I don't know if we have a separate issue for that.

@pranavkm in case he has any thoughts

**Comment by pranavkm** [comment]
> This was marked as obsolete for the 3.0 release, so I imagine we will remove it on 5.0

I would leave the type there since it's not incorrect to use it, just not preferable. It avoids an unnecessary breaking change.
