### ISSUE TITLE
gRPC cancellation of an in-progress call is broken in Blazor WebAssembly

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#18817]
### Describe the bug
Canceling a gRPC-Web call that has returned headers but has not finished returning a response is broken in Blazor WebAssembly. Cancellation of a `HttpClient` request that has returned headers is done by calling `HttpResponseMessage.Dispose`. This should abort the HTTP request and set ASP.NET Core's `HttpContext.RequestAborted.IsCancellationRequested` to true. It appears that nothing happens currently.

Note that canceling a request that hasn't finished sending response headers (using the `SendAsync(request, ct)` cancellation token) does work.

### To Reproduce
I have a sample that attempts to do Blazor WA server streaming here. Clicking stop will cancel the call with the gRPC client. It calls `HttpResponseMessage.Dispose` internally

Source: https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/blazor-serverstreaming (Blazor sample)

### Further technical details
- Blazor 3.2.0-preview1.20073.1

**Comment by javiercn** [comment]
@SteveSandersonMS @JamesNK I assume one of you will be taking care of this?

**Comment by campersau** [comment]
I think the problem is that the HttpResponseMessage is not subclassed to provide the cancellation on dispose functionally via the AbortController.
https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs#L169

You can try changing the code and can test it like I have described here: https://github.com/mono/mono/pull/18647

**Comment by danroth27** [comment]
This issue was moved to mono/mono#18717
