### ISSUE TITLE
gRPC server streaming is broken in Blazor WebAssembly

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#18813]
### Describe the bug
gRPC server streaming is broken in Blazor WebAssembly because `WasmHttpContent.ReadAsStreamAsync` doesn't return a `Stream` until the response has completed. The .NET gRPC client needs to be able to read messages from the response stream as they are received for server streaming to work.

### To Reproduce
I have a sample that attempts to do Blazor WA server streaming here...

Source: https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/blazor-serverstreaming (Blazor sample)

### Further technical details
- Blazor 3.2.0-preview1.20073.1

**Comment by campersau** [comment]
It might be because streaming is disabled by default here https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs#L37

See https://github.com/mono/mono/pull/17328 for reasons.

You can try set it to `true` via reflection.

**Comment by danroth27** [comment]
This issue was moved to mono/mono#18718
