### ISSUE TITLE
How to prevent javascript injection in Blazor?

### ISSUE THREAD

**Issue by nguyenvanbien95** [dotnet/aspnetcore#18819]
How to prevent injections in Blazor? I have not found anything about this. I can enter some script to field. It is not excute after add but I refresh page and it work as expect. This is not secure. Thank you.

**Comment by javiercn** [comment]
@nguyenvanbien95 thanks for contacting us.

There is documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server?view=aspnetcore-3.1#cross-site-scripting-xss) that explains what Blazor does, but ultimately it is your responsibility to sanitize your input.

We don't have enough information to process this issue, it would help us if you provide a minimal repro project so that we can investigate.

**Comment by nguyenvanbien95** [comment]
I enter `<script> alert(1) </script>` in my InputText. It works and data is added to database. I refresh browser (F5). Data is loaded from database then that script is executed and a message is displayed.
![image](https://user-images.githubusercontent.com/11581483/73843295-f6989600-4850-11ea-8fe7-dab2a3ca5459.png)

**Comment by javiercn** [comment]
@nguyenvanbien95 Can you provide a minimal repro project to help us investigate?

**Comment by nguyenvanbien95** [comment]
Sorry, i have found problem. I use MarkupString for option in selection. This have script value and be execute at runtime.
Thanks for your support!
