### ISSUE TITLE
Close connections periodically

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/aspnetcore#18893]
### Problem

We have multiple VMs with AspNetCore running behind a load balancer. Clients reuse TCP connections as much as possible, and therefore VMs get "pinned" to a subset of clients. We often reach states where one or two VMs are using >90% of CPU resources, whereas most other VMs are <5%. This causes a noticeable degradation and is a recurrent event.

### Proposal

One proposal is provide a setting that tells the maximum number of requests a given TCP connection can deliver.

Another is to allow closing a connection programatically. In this case, the `HttpContext` or other class should expose metrics such as number of requests delivered on that connection, although we can have a good estimate from the request payload itself (i.e. number of requests that a given IP address has performed) or we can simply throw dice and close connections on 0.1% of requests.

In either case, the developer should have ability tell if the closing of a connection will be immediate or graceful. In case of immediate termination of TCP connection, it's fine for ASP.NET to throw exceptions at I/O operations of previously existing requests.

In case of graceful termination, the service must only mark for closing, and stop processing new requests. Requests that exist before close initiated should be satisfied. In `HTTP/11`, the server can automatically return `503` responses for any request that arrives after close is initiated, until the last previously existing request is responded, after which the server can close the TCP socket. The server should also add `Connection: close` header as a hint to clients stop sending new requests. In `HTTP/2` or `HTTP/3`, the server should send a `GOAWAY` frame and ignore new streams, as dictated by the RFC.

### Workaround

The only workaround we know is to restart the AspNetCore application (or entire VM) periodically. However this is cumbersome to implement because we must restart only too-busy nodes, avoid simultaneous restarts of more than one node, and also avoid restarts of two distinct nodes too close to each other. If you have another workaround, please let us know!

Thanks
Fernando Colombo

**Comment by Tratcher** [comment]
Which server are you using in your app? Kestrel, IIS in-proc, IIS out-of-proc, HttpSys? The close the mechanics vary a little. 

> One proposal is provide a setting that tells the maximum number of requests a given TCP connection can deliver.
>  In this case, the HttpContext or other class should expose metrics such as number of requests delivered on that connection,

This kind of setting/information would only be possible on Kestrel. IIS/HttpSys don't expose the connection level semantics to us.

> although we can have a good estimate from the request payload itself

?

> (i.e. number of requests that a given IP address has performed)

A client is free to use multiple concurrent connections. Browsers do that by default. And when you're using a load balancer you don't get a 1:1 mapping between client connections and proxy connections, clients often end up sharing backend connections.

> or we can simply throw dice and close connections on 0.1% of requests.

This is the approach I've seen implemented by customers.

> Another is to allow closing a connection programatically.

This can be done in most places by setting the "Connection: Close" response header. There are a few cases where it's not honored like Kestrel Http/2 or IIS out-of-proc.

> In either case, the developer should have ability tell if the closing of a connection will be immediate or graceful.

All closures are graceful unless you explicitly call the Abort APIs.

> In HTTP/1, the server can automatically return 503 responses for any request that arrives after close is initiated

Http/1 connections only send one request at a time per connection unless you've enabled pipelining which is almost never used outside of benchmarks. A 503 mechanic shouldn't be needed.

> In HTTP/2 or HTTP/3, the server should send a GOAWAY frame and ignore new streams, as dictated by the RFC.

Yes, it would refuse new streams and wait for old ones to drain.

**Comment by msfcolombo** [comment]
Chris, thanks for comments.

We use Kestrel. If you honor `Connection: Close` for Kestrel and `HTTP/1.1`, that fixes part of the problem. How about `HTTP/2` and `HTTP/3`? You mention "Abort APIs". What APIs are these? Can you send link to documentation? Would these APIs work for `HTTP/1.1` as well? Will these APIs cause a "graceful drain" of requests already read from the socket?

Few clarifications: 1) By `HTTP/1` I've meant `HTTP/1.1`, not `HTTP/1.0` - of course the later closes connection after each request; I have edited to make it more explicit. 2) Of course 1:1 mapping is hard to achieve; but we wish to avoid situations like 1:50 or worst for prolonged time. 3) This product is serving REST APIs; while browsers and proxies may use it, it's very uncommon. The common pattern is for clients to send many requests over a prolonged time, which makes "pinning" an often seen situation.

Thanks again!

**Comment by Tratcher** [comment]
Ok, some Kestrel specific details then. Kestrel honors you adding the `Connection: close` response header for Http/1.1. It will gracefully close the connection after the current request.  This has not been implemented yet for HTTP/2 or 3. Kestrel will honor a GoAway but does not expose an API to trigger one.

[HttpContext.Abort](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.abort?view=aspnetcore-3.1)(): For Http/1.1 this forcefully aborts the connection and fails the in-flight request. For Http/2 & 3 it will cancel only the current request. There's a lower level API for Kestrel ([IConnectionLifetimeFeature.Abort](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.connections.features.iconnectionlifetimefeature.abort?view=aspnetcore-3.1)) that kills the connection no matter which protocol you use.

**Comment by msfcolombo** [comment]
Thanks. Please leave it open so we can track when HTTP/2 and HTTP/3 will honor `Connection: close` or provide a similar feature.

Also, there should be away of closing a TCP connection immediately in HTTP/2 and HTTP/3 as well (versus ending just the stream as it's probably doing today).

**Comment by Tratcher** [comment]
> Also, there should be away of closing a TCP connection immediately in HTTP/2 and HTTP/3 as well

That's what IConnectionLifetimeFeature.Abort does.

Yes, I'll mark this as a feature request for Kestrel Http/2 & 3 graceful connection termination.

**Comment by davidni** [comment]
Bumping this for all the reasons originally captured by @msfcolombo and because it has significant pain for us over the past few weeks with YARP due to uncooperating clients doing exactly the same as in Fernando's write-up.

The discussion so far seems to suggest this should be an application concern (e.g. set Connection: Close) on responses. But I'd argue this would make better sense within the server internals (i.e. Kestrel).

Rationale:
* The decision to close or not a connection is scoped to the connection, not to a request that an application is handling
* A reasonable policy might be to start draining a connection after some time (i.e. not number of requests, not amount of data transferred, but wall clock time from connection establishment). ASP .NET Core has no insights into this as far as I'm aware

### Proposal:
* Expose a new setting in Kestrel `TimeSpan? DrainConnectionsAfter { get; set; } = null`. When set, Kestrel would (gracefully) drain connections that are active beyond the specified time. Connections should be drained **even if** they are still active and/or receiving HTTP/2 pings from the client.

Thoughts? @halter73 fyi

**Comment by halter73** [comment]
A server-wide `DrainConnectionsAfter` setting is an interesting proposal. I like it. 👍 I moved this out of the backlog to discuss in the next triage.

> The discussion so far seems to suggest this should be an application concern (e.g. set Connection: Close) on responses.

Right. It had been. Initially I was thinking about an API accessible through an HttpContext feature to start a graceful close of the current connection. The problem with that design is it be very hard to use and reason about. It would affect more than just the current request which is unusual for `HttpContext` APIs, and you couldn't just `await HttpContext.Features...CloseConnectionAsync(CancellationToken)` in middleware because you'd block graceful shutdown. And as I'm sure you're aware, `Connection: Close` doesn't work for HTTP/2 anyway.

`DrainConnectionsAfter` on the other hand is fairly limited, easy-to-understand and addresses a clear issue.

**Comment by Tratcher** [comment]
Naming: KeepAliveLimit to mirror the existing KeepAliveTimeout?

**Comment by BrennanConroy** [comment]
Triage: Might need a second config for DrainTimeout

**Comment by halter73** [comment]
`DrainTimeout` (we a more specific name) would be similar to the existing `ShutdownTimeout` but for this `DrainConnectionsAfter`. IMO `KeepAliveLimit` sounds _too_ similar to `KeepAliveTimeout`.

**Comment by Tratcher** [comment]
Having a drain timeout would kill WebSockets?

**Comment by halter73** [comment]
If we decide we do need it, we would probably default the timeout to infinite.

**Comment by Tratcher** [comment]
Or exclude upgraded connections? Let the application managed those lifetimes.

**Comment by davidfowl** [comment]
The semantics are this setting are to to gracefully shutdown specific connections after some timeout? I'm not sure a setting like this is useful. It's basically a connection  timeout (sort like the request timeout we avoided like the plague). 

Maybe we need to expose a middleware layer for http connections so this can be programmed.

**Comment by Tratcher** [comment]
@davidfowl back up to the original scenario. Load balancer connection fixation has been a consistently reported problem in services and we've done small fixes to address it (e.g. #14522), but nothing consistent across servers.

For HTTP/1.1 an app usually mitigates this by adding `Connection: close` on random percentage of responses.
For HTTP/2 and 3 they they need to be able to trigger a GoAway. #14522 enabled this in HttpSys by converting a `Connection: close` to a GoAway.

@davidni have your issues been with HTTP/1.1, HTTP/2, or both?

**Comment by davidfowl** [comment]
I think the scenario is real I just don't know if the timeout API is right. Does this only affect idle connections? What counts as idle? No data or no requests or both? What about gRPC streams or websockets?

**Comment by halter73** [comment]
> Does this only affect idle connections?

No.

> What about gRPC streams or websockets?

With the default infinite `DrainTimeout`, these would not be closed. If there is a non-infinite `DrainTimeout`, these would be closed after the timeout. Apps and frameworks using gRPC streams or websockets could listen to `IConnectionLifetimeNotificationFeature.ConnectionClosedRequested` to make this more graceful.

**Comment by davidfowl** [comment]
> For HTTP/1.1 an app usually mitigates this by adding Connection: close on random percentage of responses.
For HTTP/2 and 3 they they need to be able to trigger a GoAway. #14522 enabled this in HttpSys by converting a Connection: close to a GoAway.

Feels like we should have a more first class API for this behavior.

> With the default infinite DrainTimeout, these would not be closed.

So this is a connection timeout or a request timeout?

> If there is a non-infinite DrainTimeout, these would be closed after the timeout

Can it be set per-request as well? (Though I guess that might be weird, especially in HTTP/2)

**Comment by halter73** [comment]
> So this is a connection timeout or a request timeout?

Connection timeout. A connection would always start to gracefully shutdown after any connection has been open for over the configured timeout whether it's idle or not. The scenario we care about is periodically closing all connections so clients can get new DNS records.

> Can it be set per-request as well?

I'm not sure how you'd deal with conflicts from multiple requests from the same connection. I guess you could say most-recently-configured timeout wins, but I don't like it. Do you start the timeout from the time it's is set or from the beginning of the connection?

If we were to provide an API that could be used per request, I would want to add something like `IConnectionLifetimeFeature.CloseGracefully()` in addition to `IConnectionLifetimeFeature.Abort()`. Though we'd probably use a new feature interface to avoid breaks. It could be `CloseGracefullyAsync()`, but if you actually awaited the graceful close of the connection in middleware, you'd effectively create an async deadlock. If we really wanted to, we could make `CloseGracefullyAsync()` and have the Task represent flushing the first `GOAWAY` frame for HTTP/2. We'd still have to always return a completed task for HTTP/1.1.

However, I prefer just exposing a global setting instead of a per-request feature for reasons I explain in https://github.com/dotnet/aspnetcore/issues/18893#issuecomment-791074197.

**Comment by halter73** [comment]
My current ranking of preference on how we address this:

1. Server-wide `MaxConnectionLifetime` (was `DrainTimeout`) configuration only that defaults to infinite.
2. `Connection: close` response header triggers graceful connection shutdown
3. ...
4. ...
5. ...
6. `ISomeConnectionFeature.CloseGracefully()`
7. ...
8. ...
9. ...
10. `ISomeConnectionFeature.DrainTimeout`

We definitely need to do something though. This is an important scenario.

**Comment by smflorentino** [comment]
>We definitely need to do something though. This is an important scenario.

Indeed. I work on a service in Azure and we're currently using http.sys. It's imperative that we have the ability to control TCP connection lifetime on the server side. We do this to a control traffic flow from clients. When we update our DNS records via Azure Traffic Manager, clients will not switch to the new endpoint until the TCP connection is reestablished, which, if you have long running clients like us, can take *days.* Today, we detect that TrafficManager routing has changed and automatically add the `Connection: close` header via a Middleware.

I'd like to throw my hat in the ring and recommend (2) to start with - it would be parity with http.sys and give us the ability to tweak connection behavior on demand. Plus, it allows us to treat HTTP/2 and HTTP/1.1 clients the same when it comes to keep-alive.

I'd like to see (2) added first, then (1) after.

**Comment by davidfowl** [comment]
I'm not a fan of interpreting "Connection: close", but I think that is orthogonal from what this feature was asking for. We need a general way to close connection regardless of the HTTP version (though I don't know what this means for QUIC and HTTP/3). That should be an API, not a header. Unlike HTTP.sys, we don't need to ship a new kernel to have consumers use a new API. If we still want to support interpreting connection close, then it should be off by default and services can opt into it. It can be seen as a bridge to customers migrating from HTTP.sys.

We should have 3 issues:
1. A new feature in Kestrel that lets you configure a server wide per-connection timeout (what this issue is about).
2. A first class API to signaling to the server that the connection should be closed gracefully after a request is complete.
3. A new feature in Kestrel, lets call it HTTP.sys compatibility mode, that's off by default, that uses various response headers to signal between the application and the server.

**Comment by davidfowl** [comment]
We had a discussion about this today and as it turns out, we've already expose an API for this in Kestrel that work across HTTP/1, HTTP/2 and HTTP/3. We'll be expanding it to work on HTTP.sys and IIS as well. The [`IConnectionLifetimeNotificationFeature`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.connections.features.iconnectionlifetimenotificationfeature?view=aspnetcore-5.0) which has 0 documentation 😢  can be used to do this today.

Here's a sample:

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            // This is the feature that allows you to trigger a graceful shutdown
            context.Features.Get<IConnectionLifetimeNotificationFeature>().RequestClose();
            await context.Response.WriteAsync("Hello World!");
        });
    });
}
```

It will send connection close on HTTP/1.1 connections, and it'll send a GOAWAY frame on HTTP/2. As part of this issue we're going to do a couple of things:

1. Expose `IConnectionLifetimeNotificationFeature` on HTTP.sys
2. Expose `IConnectionLifetimeNotificationFeature` on IIS
3. Expose a new API on `ConnectionInfo` to allow closing the requesting graceful connection closure.

```diff
namespace Microsoft.AspNetCore.Http
{
    public abstract class ConnectionInfo
    {
+      public virtual void RequestClose();
    }
}
```


```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            context.Connection.RequestClose();
            await context.Response.WriteAsync("Hello World!");
        });
    });
}
```

PS: As a workaround in the meantime, here's a polyfill for HTTP.sys:

```C#
public class ConnectionCloseNotificationLifeTimeFeature : IConnectionLifetimeNotificationFeature
{
    private readonly HttpResponse _httpResponse;

    public ConnectionCloseNotificationLifeTimeFeature(HttpResponse httpResponse)
    {
        _httpResponse = httpResponse;
    }

    public CancellationToken ConnectionClosedRequested { get; set; }

    public void RequestClose()
    {
        // Set the connection close feature if the response hasn't sent headers as yet
        if (!_httpResponse.HasStarted)
        {
            _httpResponse.Headers[HeaderNames.Connection] = "close";
        }
    }
}
```

Usage:

```C#
app.Use(next =>
{
    return context =>
    {
        var feature = context.Features.Get<IConnectionLifetimeNotificationFeature>();
        if (feature == null)
        {
            feature = new ConnectionCloseNotificationLifeTimeFeature(context.Response);
            context.Features.Set(feature);
        }

        return next(context);
    };
});
```

**Comment by Tratcher** [comment]
The docs claim IConnectionLifetimeNotificationFeature has been available since 2.2?

**Comment by davidfowl** [comment]
That's correct

**Comment by Tratcher** [comment]
@Kahbazi will start porting this to HttpSys and IIS.

**Comment by halter73** [comment]
> The IConnectionLifetimeNotificationFeature which has 0 documentation 😢 can be used to do this today.

@Tratcher do we have another issue tracking this?

**Comment by halter73** [comment]
https://github.com/dotnet/aspnetcore/issues/33420

**Comment by msfcolombo** [comment]
Thanks everybody for insuring we have a consistent solution for all HTTP versions. Looking forward to the documentation!
