### ISSUE TITLE
Session is not expired when logout in other tab in Blazor

### ISSUE THREAD

**Issue by nguyenvanbien95** [dotnet/aspnetcore#18901]
I am testing authentication in Blazor.
My problem is blazor app is not expired in 1st tab after logout in 2nd tab.
Please view [repo](https://github.com/nguyenvanbien95/BlazorAuthentication) to repro problem

**Comment by javiercn** [comment]
@nguyenvanbien95 thanks for contacting us.

That is expected to a degree given the fact that Blazor sets up the authentication context when the application starts and doesn't update unless the app does something explicit to enable it.

I believe with Identity you can update the security stamp of the user when you log-out and that should cause the user to be eventually logged out the other tab.

@SteveSandersonMS can you provide more details about this or correct me if I said something wrong :)?

Do we have a sample of this in action?

**Comment by mkArtakMSFT** [comment]
@blowdart what's the best way to change the security stamp for a user?

**Comment by blowdart** [comment]
Yea, this is deliberate, and even if you update the security stamp it's not going to logout until the identity is refreshed, which, by default, is once every 15 minutes. Now whether Blazer reacts to that I have no idea, because it's wired up in the auth pipeline.

`UserManager.UpdateSecurityStampAsync(userId)` is the way to go here.

**Comment by SteveSandersonMS** [comment]
Thanks @blowdart!

@nguyenvanbien95 As per the previous comment, `UserManager.UpdateSecurityStampAsync(userId)` is the way to cause a user's existing logins to be invalidated. You can change how often your application reacts to this by editing the `RevalidatingIdentityAuthenticationStateProvider.cs` file in your project. The default `RevalidationInterval` value has it check for expiry every 30 minutes.

If you're looking for some kind of instantly synchronised sign-out, that's not a feature we have. You could build it yourself by having a singleton DI service that raises events whenever anyone signs out, and have some code running inside each circuit listen to that event and sign the user out if you see the same user signed out in a different circuit. But it gets more complicated if you have multiple servers, since they would have independent state. That's the whole reason why, in the end, we default to using `RevalidatingIdentityAuthenticationStateProvider` with some `RevalidationInterval` to trigger polling the underlying identity database for security stamp changes.

**Comment by nguyenvanbien95** [comment]
Thanks all!
I am clear in this. Instantly synchronised sign-out is more complicated, so I consider other solutions.
