### ISSUE TITLE
Add debugger specific setting to the Blazor project templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18982]

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please share the setting to be added here? Thanks!

**Comment by SteveSandersonMS** [comment]
The launchsettings JSON file should contain this:

```
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
```

I mean it literally like that, with the braces and token names as given there. There would also be a `,` at the end of the line if needed to make the file valid JSON, plus whatever level of indentation applies at the point where it is inserted.

I expect this needs to appear in the file *twice*, since the default launch settings contains two profiles, one called `"IIS Express"` and the other called `"(yourapplicationname)"`, and this setting needs to go into both of those profiles.
