### ISSUE TITLE
Console window is not showing for windows application in visualstudio 2019

### ISSUE THREAD

**Issue by vimala1085** [dotnet/aspnetcore#19002]
Hi,
   If i choose output type "console application" then console window is appears and application working fine.But when i switch output type as "windows application" console windows is not appears and application working fine without any issues.

Can anybody help me ? 
why console window is not appear? or anything else needs to be installed in visualstudio2019?

**Comment by javiercn** [comment]
@vimala1085 thanks for contacting us.

We don't believe this is a question specific to asp.net core. We believe you'll get a better and faster answer by reporting this issue through Visual Studio. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#report-a-problem) for details.

@Pilchie do you know where to route this to?

**Comment by Pilchie** [comment]
This is by design.  It is how Windows works. If you set the subsystem to Windows, the OS doesn't allocate a terminal for it.

You can see things written to Standard Output in the VS output window if you are running under the debugger.  If you want your application to have a console attached, you'll need to set the Subsystem to Console in Project Properties.  You can still do things like show UI if you add the right references.

See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/target-winexe-compiler-option for more information.
