### ISSUE TITLE
Enum.IsDefined throw error with nullable  EnumType properties. 

### ISSUE THREAD

**Issue by varnit03** [dotnet/aspnetcore#19084]
### Describe the bug
Enum.isDefined throw 'Type provided is not Enum' when property is optional

eg.
public NameTypeEnum? Name { get; set; } = null;

// Here is the method for enum validation 

                public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) {
            try {
                if (reader.Value == null && DefaultEnumValue != null)
                    return DefaultEnumValue;

                if (Enum.IsDefined(objectType , reader.Value)) {    // This line throw 'type is not enum' 
                    throw new JsonSerializationException();
                }
                return base.ReadJson(reader, objectType, existingValue, serializer);

            } catch (JsonSerializationException e) {
                throw new JsonSerializationException(e.InnerException.Message, e.InnerException);
            }
        }

### To Reproduce
Send Invalid Enum in json request which is defiend as nullable type.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@varnit03 thanks for contacting us.

In order for us to investigate and help you, can you post a minimal repro project and detaile steps on how to reproduce it?

**Comment by rynowak** [comment]
This seems like a question about dotnet in general...

`Enum.IsDefined` is probably throwing because `objectType` is `Nullable<NameTypeEnum>`.

I suggest reading more about nullable types: https://docs.microsoft.com/en-us/dotnet/api/system.nullable.getunderlyingtype?view=netframework-4.8

You can convert from a nullable type to it's underlying type using https://docs.microsoft.com/en-us/dotnet/api/system.nullable.getunderlyingtype?view=netframework-4.8
