### ISSUE TITLE
TestSSL reports 2 warning and 1 critical warning

### ISSUE THREAD

**Issue by peval27** [dotnet/aspnetcore#19096]
I have an ASP.NET 3.1.101 MVC + Web API running on Windows 10 1909 which uses Kestrel and HTTPS with a self signed certificate. I ran testssl.sh v.3.0 with openssl 1.1.1d from CentOS 7 and it highlighted 3 warnings:

- Secure   Client-Initiated Renegotiation | RED | VULNERABLE (NOT ok), DoS threat
- SWEET32 (CVE-2016-2183, CVE-2016-6329) | yellow | VULNERABLE, uses 64 bit block ciphers
- LUCKY13 (CVE-2013-0169),   experimental | yellow | Potentially VULNERABLE, uses cipher block chaining (CBC) ciphers with   TLS. Check patches

I am not a security expert, so I am struggling to understand the impact. In addition, can those be fixed at web server level (i.e.Kestrel option)?

**Comment by blowdart** [comment]
which OS are you running on?

[Sweet32](https://sweet32.info/) only affects Triple-DES and CBC, modern Windows should have those disabled but you can make sure using [restricting what's available](https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc), although Windows did [patch](https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2016/3155527?redirectedfrom=MSDN) to remove it entirely. Kestrel cannot do this for you.

LUCKY13 is only applicable to Linux and is fixed by ensure your OpenSSL is up to date. Considering that was fixed in [2013](https://www.openssl.org/news/secadv/20160503.txt) it's unlikely you're that far behind.

Secure Client-Initiated Renegotiation is an issue from 2011, and applies to [Windows 7](https://support.microsoft.com/en-sg/help/977377/microsoft-security-advisory-vulnerability-in-tls-ssl-could-allow-spoof) which was patched to disable it by default and OpenSSL was [also updated](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_options.html).

Given the age of these I question the results to be honest. Are you running it locally against a host that's used for development, or against a remote, typically hardened server?

**Comment by peval27** [comment]
Hi Barry @blowdart ,

thanks for your quick and detailed answer. From the look of it, it seems the script has highlighted false positives. If so, I could raise an issue against it. I've replied in line to your questions.

> which OS are you running on?

Software running on Windows 1909 as Windows service, script running from CentOS 7

> [Sweet32](https://sweet32.info/) only affects Triple-DES and CBC, modern Windows should have those disabled but you can make sure using [restricting what's available](https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc), although Windows did [patch](https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2016/3155527?redirectedfrom=MSDN) to remove it entirely. Kestrel cannot do this for you.

scripts is highlighting: 

Triple DES Ciphers / IDEA                     offered
Obsolete: SEED + 128+256 Bit CBC cipher       offered

> LUCKY13 is only applicable to Linux and is fixed by ensure your OpenSSL is up to date. Considering that was fixed in [2013](https://www.openssl.org/news/secadv/20160503.txt) it's unlikely you're that far behind.

OK. this was my understanding. Could it be the script doesn't know the service is running on Windows?
 
> Secure Client-Initiated Renegotiation is an issue from 2011, and applies to [Windows 7](https://support.microsoft.com/en-sg/help/977377/microsoft-security-advisory-vulnerability-in-tls-ssl-could-allow-spoof) which was patched to disable it by default and OpenSSL was [also updated](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_options.html).
> 
> Given the age of these I question the results to be honest. Are you running it locally against a host that's used for development, or against a remote, typically hardened server?

Development. I'm following OWASP guidelines to make sure we're not missing something. But it's very near to what it will be in production.

Many thanks

**Comment by peval27** [comment]
I've updated the issue description with more details (OS, openssl version, testssl version, etc)

**Comment by blowdart** [comment]
Super weird, on Windows these days non of those should be a concern. Maybe try another from https://github.com/ssllabs/research/wiki/Assessment-Tools ?

**Comment by peval27** [comment]
> 
> 
> Super weird, on Windows these days non of those should be a concern. Maybe try another from https://github.com/ssllabs/research/wiki/Assessment-Tools ?

will do soon.

**Comment by peval27** [comment]
Tried with:

-  TestSSLServer which gave me warning WARN[CS006]: Server supports cipher suites with no forward secrecy.
- SSL Audit --> no warnings
- [yawast ](https://github.com/adamcaudill/yawast/releases) no warnings

I will do some more digging in the next few days

**Comment by anurse** [comment]
@peval27 for now I'm going to put this in our Discussions milestone, which means it won't be tracked in Triage, as it doesn't seem like we have actionable work to take here. If something comes out of your investigation, we can adjust this as necessary.
