### ISSUE TITLE
HTTP2 streams returned to pool in uncomplete state

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#19360]
It is possible for a stream to error and be returned to the pool with pipes that are not fully complete

A thrown error will return a stream in a questionable state here - https://github.com/dotnet/aspnetcore/blob/03a9e8ec1c47d3c27902daf586c3ad30b0c40c31/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L976 - will eventually be dequeue and returned to the pool here - https://github.com/dotnet/aspnetcore/blob/03a9e8ec1c47d3c27902daf586c3ad30b0c40c31/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L1063

We shouldn't be holding onto streams in a pool when the pipes are not complete (I noticed this when working to reuse the pipes - calling Reset will throw if the reader and write aren't complete).

Either the return should be moved to a place where we know the stream is safe to return to the pool, or we should keep track of whether the stream is in the right state to return.

@davidfowl @jkotalik @halter73

**Comment by jkotalik** [comment]
I don't think this was an issue before https://github.com/dotnet/aspnetcore/pull/19356 was created. 

In the case where a stream does encounter a Http2StreamErrorException here:
https://github.com/dotnet/aspnetcore/blob/03a9e8ec1c47d3c27902daf586c3ad30b0c40c31/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L976

We will not call Execute() on the Http2Stream. 

https://github.com/dotnet/aspnetcore/blob/03a9e8ec1c47d3c27902daf586c3ad30b0c40c31/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L981

This means the application func isn't called, and from what I can tell, this means none of the state of the RequestBodyPipe and Http2OutputProducer should have been modified.

I have a good idea to verify/assert this. HttpProtocol has an event BeginRequestProcessing; instead of newing up the output producer and request body pipe here: https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L59-L68, can you override BeginRequestProcessing and instantiate them there?

If what I said above is true, then I don't this was a bug before and only affects your current PR. I actually think what I mentioned above where instead we pool in the BeginRequestProcessing https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L425 call would prevent the scenario where we created an output producer which isn't completed.

**Comment by anurse** [comment]
Triage: @JamesNK is looking at this right now. Unassign and ping if that changes and we can re-triage.
