### ISSUE TITLE
[Blazor] wasm runtime state is improperly initialized

### ISSUE THREAD

**Issue by lewing** [dotnet/aspnetcore#19378]
Right now the blazor startup code simply calls `MONO.mono_wasm_rutime_is_ready = true` that isn't enough to signal the debugger that we've initialized sufficiently to make calls into the runtime.  In the reference initialization a call is made to `MONO.mono_wasm_runtime_ready ()` which allows the DebugProxy to detect startup and initialize

**Comment by SteveSandersonMS** [comment]
Thanks for making progress on this, @lewing!

I just tried this out and unfortunately it's quite a problematic change. This causes the debugger to pause the application during the startup process on every single page load, even if you're not debugging. All it takes is having the browser dev tools open, which is a very common workflow, and then you can't reload the page without getting interrupted by the JS debugger.

Is this definitely necessary? Is there some way we can scope it so it only happens when the VS debugger is connected? Is there any way we can call some more minimal API that only does the "detect startup and initialize" thing *without* triggering a `debugger` statement?

**Comment by SteveSandersonMS** [comment]
Also as a more minor point, it logs `MONO-WASM: Runtime is ready.` to the console which ideally it would not.

**Comment by lewing** [comment]
Are you using the js debugger outside the proxy?

**Comment by SteveSandersonMS** [comment]
Not involving the proxy at all. Simply loading a Blazor application while the normal browser dev tools are opened.

**Comment by SteveSandersonMS** [comment]
For example, to see things on the Network or Elements tabs.

**Comment by lewing** [comment]
That makes sense, let me see if I can come up with a work around

**Comment by lewing** [comment]
The fact that the variable MONO.mono_wasm_runtime_is_ready doesn't appear to be set in the release js is at least as big a problem as the `debugger` statement though

**Comment by lewing** [comment]
wait it is actually there, sorry for the noise

**Comment by lewing** [comment]
Ok I think I have potentially workable solution in https://github.com/mono/mono/pull/19056 that would never use the `debugger` solution if the code in #19379 stays as is.  Still thinking through the details.

**Comment by lewing** [comment]
alternate version of the fix using supported apis https://github.com/mono/mono/pull/19057

**Comment by mkArtakMSFT** [comment]
Closing as there is no other fix pending here.
