### ISSUE TITLE
List permission not needed for using keyvault asp.net core integration

### ISSUE THREAD

**Issue by TechWatching** [dotnet/aspnetcore#19392]
### Is your feature request related to a problem? Please describe.
I want to use Azure Key Vault in my ASP.NET Core application to inject secrets in my configuration either by adding it manually with the AddAzureKeyVault method or by using the integration package (Microsoft.AspNetCore.AzureKeyVault.HostingStartup). However the infrastructure team managing my Azure tenant does not want my application to have the "list" permission on the keyvault. It just want it to have the "get" permission and is advising us to use app settings keyvault references. That's not a solution for the development team as it involves keeping the development secrets in our local laptops (secret.json), having to manually retrieve them when they change ... ...

### Describe the solution you'd like
A solution would be to able to have the keyvault integration only use the get permission to retrieve the secrets which does not seem possible today. The solution would be to work a little bit like keyvault configuration provider in ASP.NET (classic). This provider only needs a get permission in Strict Mode and only loads the needed secrets. It prevents the application loading all the secrets of keyvault inlucded secrets it does not need. Okay I know we can implement IKeyVaultSecretManager to target only specific secrets (maybe by doing a logic based on tags) but the list right is needed. There should be a mechanism to allow to load only needed secrets without having to manually retrieve each secret one by one using the sdk.

**Comment by javiercn** [comment]
@TechWatching thanks for contacting us.

@anurse Is there a better label for things like this?

**Comment by anurse** [comment]
@TechWatching the config system requires the ability to list keys since it's a background-load process rather than a "pull-through" process. The provider dumps all the secrets from the KeyVault in the background and atomically pushes them into config in order to avoid blocking processes (except the first load which is blocking). It wouldn't be possible for us to change the design to only use the get permission based on that model.

You could create a custom version (fork the code) of this provider that uses a static list of settings (known at run-time) and then you can just iterate over those settings and "Get" them, thus avoiding the need for listing. That's not something we plan to do in our provider though.

**Comment by TechWatching** [comment]
Okay I understand. Too bad it's not something planned in the provider though as I would rather have it be supported and maintained officially than to do my own custom package. Anyway thanks for the explanation, I was hoping it could be like in asp.net classic but if it's not by design that makes sense.
