### ISSUE TITLE
invoke javascript arrow function from IJSRuntime

### ISSUE THREAD

**Issue by zachneu** [dotnet/aspnetcore#19484]
When creating class library with razor/blazor components and the components need to execute some JavaScript code, you need to add a reference to a JavaScript file in index.html with the functions you need (or in some script tag in the html file).  this will require you to add at least one JavaScript code before you can invoke any JavaScript file.

To solve this problem it would be nice if the IJSRuntime support to call arrow functions. 

Example of this could be: 
SRuntime.InvokeVoidAsync("() => alert('testing'))();");

With this support I can also run an arrow function to dynamically load css or JavaScript files if they are needed by the component.

**Comment by RemiBou** [comment]
You can do this with eval

```cs
SRuntime.InvokeVoidAsync("eval","alert('testing');");
```

**Comment by zachneu** [comment]
Thank you, this solve the problem.

**Comment by RemiBou** [comment]
You can send arrow function in eval as well. 

Even if it was handled by JSInterop it would be an eval, because the way of communicating between Blazor and the browser are done only via string. (https://github.com/dotnet/aspnetcore/blob/e72223eaf58a3ee6660a922064d2449e47b78253/src/Components/Blazor/Mono.WebAssembly.Interop/src/MonoWebAssemblyJSRuntime.cs see InvokeJS) and I don't see how it could work otherwise.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Closing as @RemiBou has answered.
