### ISSUE TITLE
List of any firewall and antivirus software blocking Blazor WebAssembly applications

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#19552]
We've learned about customers who have been seeing issues with their **Blazor WebAssembly applications being blocked by either Firewall or Anti-virus software**.
We're going to use this issue to build up the list of such software which interferes with Blazor WebAssembly so that we can follow up with their providers and try to address those issues.

## ASK
If you have observed (first hand) a situation like the one described above, please comment below the details of the software which has blocked your application in the following format:

```
**Software name**: My custom antivirus
**Version**: 7.7
**Website**: https://MyCustomAntiVirus.com
**Context**: Any relevant information, which is specific to this scenario.
```

## Note
Please note that this issue should not be used for discussions, rather simply a way to build up the list. The discussion issue for this topic is: https://github.com/dotnet/aspnetcore/issues/5477
**Comments, which do not comply with this format will be removed.**

**Comment by mrpmorris** [comment]
We are using a Palo Alto firewall.

The console is filled with errors like this
```
HTTP503: SERVICE UNAVAILABLE - The service is temporarily overloaded
(XHR)GET - http://(redacted).azurewebsites.net/_framework/_bin/(redacted).Components.Dismissable.dll
```

In Firefox 73.0.1 the DLL requests appear in the Network tab with `503` statuses.
In Chrome 80.0.3987.122 the Network response is `ERR_CONNECTION_RESET`.

Using https:// fixes the problem for me, I expect this could be the firewall trusting the content because it knows it hasn't been modified en-route.

**Comment by spottedmahn** [comment]
**Software name**: sophos web protection
**Version**: version of what?  sophos?
**Website**: http://opensilvershowcase.azurewebsites.net
**Context**: 

![image](https://user-images.githubusercontent.com/14079228/76313173-dd995f80-62aa-11ea-907f-0b67688b41e1.png)

http://opensilvershowcase.azurewebsites.net/_framework/_bin/System.ComponentModel.DataAnnotations.dll

**Comment by mihaimyh** [comment]
Hi,

My corporate antivirus blocks all .dll downloaded in Chrome or other browsers:

```
Reputation: Unverified
Media Type: application/executable, application/dotnet-assembly
Rule Set name: Block Access to Site/IP & Alert Notification
Rule name: exe Block By Media Type
generated 2020-04-03 10:33:24 by McAfee Web Gateway
```

**Comment by zeeshanejaz** [comment]
**Software name**: Avast Antivirus
**Version**: 20.1.2397 (build 20.1.5069.562)
**Website**: https://avast.com
**Context**: Blazor webassembly apps are blocked with an error message "We have safely aborted connected with https://website.com because it was infected with DRep". Investigating this error has lead to a "domain reputation" issue. Since my domain is new and is not used by many people, it is considered of low reputation. This means I am unable to user Blazor webassembly for new projects.

**Comment by mkArtakMSFT** [comment]
Thanks everyone.
It seems that the only actual antivirus which is causing a problem is `Avast`. All the other reported cases are firewall specific, which seem to be caused by the fact that Blazor libraries are `.dll` files. We have a resolution to this already in the original thread.
In parallel, we're going to work with Avast antivirus software vendors offline to get this resolved.
Given that there is no more pending action here, I'm closing this issue.

**Comment by spottedmahn** [comment]
>We have a resolution to this already in the original thread

Any chance you can link to that specific comment?  thanks!

**Comment by mrpmorris** [comment]
@spottedmahn some suggestions here https://github.com/dotnet/aspnetcore/issues/5477

**Comment by zeeshanejaz** [comment]
I think it's a good idea to test all popular antivirus AVG, NOD32, MalwareBytes, Avira, Kaspersky, Norton, Macfee, etc.

**Comment by spottedmahn** [comment]
>some suggestions here #5477

Hi @mrpmorris - I know 😉 but the thread is super long.  Very tedious to find the comment(s) w/ the workarounds.  Not very stackoverflow-ish if you will 😊

**Comment by mkArtakMSFT** [comment]
Here is the comment: https://github.com/dotnet/aspnetcore/issues/5477#issuecomment-599148931

**Comment by spottedmahn** [comment]
thanks @mkArtakMSFT! 🤝
