### ISSUE TITLE
Sharing session cookie between Apps

### ISSUE THREAD

**Issue by omer-hatip** [dotnet/aspnetcore#19597]
Hello,
i made two new apps with same code
the first app set the session variable value 
and the other reads that variable value but gets null,

### To Reproduce
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
               .PersistKeysToFileSystem(new System.IO.DirectoryInfo(@"c:\shared-keys\"))
               .SetApplicationName("AppName");

            services.AddDistributedMemoryCache();
            services.AddSession(o =>o.Cookie.IsEssential = true);
            services.AddControllersWithViews();
        }
```

when i use AddDistributedSqlServerCache instead of AddDistributedMemoryCache
it's working and everything ok

```
            services.AddDistributedSqlServerCache(options =>
            {
                options.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MyDbName;Integrated Security=True;";
                options.SchemaName = "dbo";
                options.TableName = "TestCache";
            });

```

Can you help me please to know what's the wrong with AddDistributedMemoryCache
or if i missing something else.
Thanks.

My Project file

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="3.1.2" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.Extensions.Caching.SqlConfig.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

```
### Further technical details
- ASP.NET Core version 3.1.2

**Comment by blowdart** [comment]
Are there any errors in the logs about data protection, or unencrypting the cookie?

**Comment by omer-hatip** [comment]
when i deleting the keys folder then run the first app which sets the value this warnings appear :

1. Source : IIS Express
The directory specified for caching compressed content C:\inetpub\temp\IIS Temporary Compressed Files\WebApplication1 AppPool is invalid.  Static compression is being disabled.

2.  Source : .NET Runtime
Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 35

3. Source : IIS Express AspNetCore Module V2
No XML encryptor configured. Key {dcd42695-d0f8-4b75-81ae-274eedb8598c} may be persisted to storage in unencrypted form.

Category: Microsoft.AspNetCore.Session.SessionMiddleware
EventId: 7
RequestId: 80000004-0002-e700-b63f-84710c7967bb
RequestPath: /
SpanId: |269074c2-4c755379e444b350.
TraceId: 269074c2-4c755379e444b350
ParentId: 

Error unprotecting the session cookie.

Exception: 
System.Security.Cryptography.CryptographicException: The key {3103ef25-99a8-4377-8cdb-d7a6f99ec3ba} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)


and when i run the second program that reads the value 
this warning appears :

The directory specified for caching compressed content C:\inetpub\temp\IIS Temporary Compressed Files\WebApplication1 AppPool is invalid.  Static compression is being disabled.

but all are warning with no errors.

**Comment by omer-hatip** [comment]
And i tried 

```
            services.AddDataProtection()
                .UseCustomCryptographicAlgorithms(
                    new ManagedAuthenticatedEncryptorConfiguration()
                    {
                        // A type that subclasses SymmetricAlgorithm
                        EncryptionAlgorithmType = typeof(Aes),

                        // Specified in bits
                        EncryptionAlgorithmKeySize = 256,

                        // A type that subclasses KeyedHashAlgorithm
                        ValidationAlgorithmType = typeof(HMACSHA256)
                    })
                .SetApplicationName("AppName");
```
with same results and logs.

**Comment by blowdart** [comment]
OK, so you're configuring data protection right with 

```
            services.AddDataProtection()
               .PersistKeysToFileSystem(new System.IO.DirectoryInfo(@"c:\shared-keys\"))
               .SetApplicationName("AppName");
```

But are the sites on the same root domain? e.g. www.contoso.com and app.contoso.com?

**Comment by omer-hatip** [comment]
i tried the two methods
PersistKeysToFileSystem and 
UseCustomCryptographicAlgorithms 

but sure for testing.

i create two new applications using VS to test this issue.

regarding domain : it's localhost as you can see in log files, IIS Express with visual Studio 2019.

**Comment by blowdart** [comment]
You didn't share log files so I couldn't see it was localhost. I assume then they're also using the same scheme, either both HTTPS or both HTTP.

If you open up the browser tools can you see the session cookie going to both sites? Localhost is somewhat special when it comes to same site rules.

**Comment by omer-hatip** [comment]
Yes sure,
both apps use HTTPS 
and yes i can see the cookie in both sites, and when i delete it the app recreates it and appears on both sides,

i tried .net source code stepping and i found that the both app have same SessionKey , but different SessionId, and the first app Session Store contains the key and value  (that i wrote to the session)
but the second has Session Store with count 0 records.

another thing:
when i write a value in the second app , the second app can read it without affecting the value of first app, so i think Session uses MemoryCache but not DistributedMemoryCahe,

**Comment by blowdart** [comment]
That's weird. Ok, it's not data protection so it must be in session. So retagging for someone else

**Comment by omer-hatip** [comment]
i think so,  it's not data protection because it's working when i used 

```
services.AddDistributedSqlServerCache(options =>
            {
                options.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MyDbName;Integrated Security=True;";
                options.SchemaName = "dbo";
                options.TableName = "TestCache";
            });
```

instead of 

`services.AddDistributedMemoryCache();`

**Comment by omer-hatip** [comment]
the test apps
https://github.com/omer-hatip/WebApp1

**Comment by anurse** [comment]
> when i use AddDistributedSqlServerCache instead of AddDistributedMemoryCache
> it's working and everything ok

This is actually expected, `AddDistributedMemoryCache` is a bit of a weird name. Let me explain a bit about how session works.

Session works by storing a unique ID in a cookie and then using that ID to look up data in some kind of data store. ASP.NET Core Session does this using the `IDistributedCache` interface. So we look up the session ID in this distributed cache and read/write session data in there. Data Protection is involved in generating/verifying this Session ID, hence why it was an earlier topic of discussion, but I don't think that's the source of the problem.

The `AddDistributedMemoryCache` method registers an implementation of `IDistributedCache` that is backed by the Memory Cache which is an **in-process memory-based cache**. So two separate applications will get completely separate isolated versions of this and will not share data.

The `AddDistributedSqlServerCache` registers an implementation of `IDistributedCache` that is backed by a SQL Server. As long as both applications share the same SQL Server instance and table name, the data one app writes can be seen by the other and session works.

So essentially: This is the expected behavior. The two apps aren't sharing session because they have complete separate **in-process** caches storing the data.

**Comment by anurse** [comment]
Moving to Discussions since there isn't an actionable bug here based on the initial review. If something else comes up in discussions on this thread, we'll re-triage or file new issues!

**Comment by omer-hatip** [comment]
so we can't achieve this using memory. 
but I think using Sql server database for this is not the ideal solution. because I'm using it to store just keys.

For example 
a user of multi tenant app logs in and selects one of its databases to start .

I store the db Id in the session then start the second app to start working. 

Do we have another solution ?

By the way. I use authentication cookie sharing for these two apps . And every thing is ok.

And I use localization cookie too . And it's working.

So i think i have to make another standalone cookie (like localization cookie) for db id instead of using session cookie

**Comment by omer-hatip** [comment]
> So essentially: This is the expected behavior. The two apps aren't sharing session because they have complete separate **in-process** caches storing the data.

Do you think that if we published the two app to IIS with 
`<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`

Will make any difference?

**Comment by anurse** [comment]
> but I think using Sql server database for this is not the ideal solution. because I'm using it to store just keys.

If you have two separate apps and want to share data between them, there must be *some* kind of shared data store, or you have to round-trip the data back and forth via a Cookie. We provide one implementation of a shared data store based on SQL Server. If you want to use something idfferent, that's fine, you can implement the `IDistributedCache` interface yourself.

> So i think i have to make another standalone cookie (like localization cookie) for db id instead of using session cookie

I'd be very careful doing this yourself. There are major security issues to consider. Remember that a malicious client can forge a cookie, so you'll need to sign or encrypt the value when you issue the cookie and validate the signature each time you receive it. The Session API automatically does this for you (as long as Data Protection is configured appropriately, since each app needs to share encryption/signing keys).

Another option would be to store this in the authentication cookie as a separate claim. How are you doing authentication in your application?

> Do you think that if we published the two app to IIS with
> `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`
> 
> Will make any difference?

No, each app will still be separate processes. Changing to the "in-process" hosting model just means your app runs inside `w3wp.exe` instead of in a separate process. There will still be separate `w3wp.exe` processes for each app.
