### ISSUE TITLE
Unable to redirect to home page in blazor error ui panel

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#19635]
Hello guys, i would like to redirect to my home page when a unhandled execption happen and the div error-ui-panel appear, so i update the code like this
````
<div id="blazor-error-ui">
        Error happen
        <a href="/" class="reload">Reload</a>
        <a class="dismiss"><i class="fas fa-times"></i></a>
    </div>
````
but even with href="/", i stay in the current page
I try also this but same behavior
<a onclick="document.location = '/'" class="reload">Reload</a>

if i write document.location = "/"; in the developer console im correctly redirected

Do you know whats happen ? how I can achieve what i want ?

Thank you !

**Comment by javiercn** [comment]
@julienGrd It is very likely that Blazor is intercepting the link and doing nothing as the app already crashed. Using `document.location = "/"` seems like the right way to go for me.

**Comment by julienGrd** [comment]
Hello @javiercn, unfortunately even this solution not works (<a onclick="document.location = '/'" class="reload">Reload</a>)
Im still on the current page and have no way to come back to the home page (except if the user write directly in the address bar)

thanks for your help !

**Comment by javiercn** [comment]
@julienGrd thanks for trying it out. I gave it a try and you are right, there's something iffy going on here.

**Comment by captainsafia** [comment]
The behavior your are seeing is intentional. The "Reload" link that is included as part of the template is registered to its own click handler ([ref](https://github.com/dotnet/aspnetcore/blob/18cb57aa3271e3e229ef9bdfe1e2b85500c53cb6/src/Components/Web.JS/src/BootErrors.ts#L12)) which triggers the reload and prevents the execution of other handlers or the default href behavior.

To achieve the behavior you are looking for, I would recommend changing the class name on the `Reload` button to prevent the default event handlers from being registered to it then attaching your own event handlers to redirect to the desired route.

Let us know if that does/doesn't work for you.

**Comment by captainsafia** [comment]
@julienGrd I'll close this assuming that the fix works. If not, please re-open the issue.
