### ISSUE TITLE
Can't detect when an Authentication Cookie expires in Blazor (server-side)

### ISSUE THREAD

**Issue by mselinger75** [dotnet/aspnetcore#19645]
See https://github.com/dotnet/aspnetcore/issues/6855 for the reference. The problem mentioned in #6855 still exists. Do you have any suggestions on how to handle this? Thanks!

**Comment by chassq** [comment]
Just a thought for what its worth. Not really knowing the code I would take a guess and say that assuming you are using a Blazor Client Side app. Since the Asp.NET Auth runs server side that each post that goes to the server would make the necessary claim checks and authorize/de-authorize a request accordingly. Since Client Side Blazor requests do not post back to the Server this is why the request is not being invalidated. As stated in #6855 MS has not done any work yet I guess to makes these checks client side? It may be possible to use the AuthenticationStateProvider to check the principal claims locally for existence or a timeout and take action accordingly (e.g. log the user out or prompt them to log in). We do something similar to this with a Blazor Server-side app where by we make some checks on Claims via AuthenticationState.User.Claims. For example (Not a working example. Just notional):


```
using Microsoft.AspNetCore.Components.Authorization;
public class MyService 
{
     private AuthenticationStateProvider _authenticationStateProvider;
     public AuthenticationState AuthenticationState { get; set; }
     public MyService(AuthenticationStateProvider authenticationStateProvider)
     {
          _authenticationStateProvider = authenticationStateProvider;
     }

        public async Task<DateTimeOffset> GetClaimsLastRefreshDate()
        {
            await SetAuthState(); //Get authentication state
            
            //Check claim
            if (!AuthenticationState.User.Claims.Any(c => c.Type.Equals("MyClaim", StringComparison.InvariantCultureIgnoreCase)))
            {
                return default;
            }

            var claimStr = AuthenticationState.User.Claims.FirstOrDefault(c => c.Type.Equals("MyClaim", StringComparison.InvariantCultureIgnoreCase))?.Value;
            DateTimeOffset.TryParse(claimStr, out var lastRefreshDate);

            return lastRefreshDate;
        }

     private async Task SetAuthState()
     {
           if (AuthenticationState == null) AuthenticationState = await _authenticationStateProvider.GetAuthenticationStateAsync();
    }
}
```

**Comment by javiercn** [comment]
@mselinger75 thanks for contacting us.

There is in general no way to know when the cookie expires since Blazor uses a websocket and won't send Http requests to the server. Identity uses session cookies by default, which go away once you close the window and will only set the expiration when the user check the remember me option in the UI.

The best place to know when the cookie will expire is during the initial render of the root component (in the _Host.cshtml page) where you have access to the request and can check the values for the cookie and pass them down to the app as parameters to the root component.
