### ISSUE TITLE
Really poor performance and latency of controls with multiple animations/operations

### ISSUE THREAD

**Issue by hez2010** [dotnet/aspnetcore#19739]
### Problem
Blazor server-side has really poor performance and high latency for controls with multiple animations, especially for dropdown controls with fate-in/out animations.

Some demos:  
https://blazorfabric.azurewebsites.net/dropdownPage
https://www.telerik.com/blazor-ui (demo for Drop Down List)
https://www.matblazor.com/DatePicker
...

You can open browser dev tools to monitor the network activities, and you will see plenty of websocket messages being received during a single `open dropdown` operation, sometimes you even need to wait a few seconds before dropdown list showing up. That's really unacceptable. 

If you use blazor-wasm, all those problems were gone.

### Solution
Bulk operations for blazor server-side rendering.  

I think you can put those `short-time intensive operations` in a single websocket message to reduce pressure and latency for both websocket client and server.

**Comment by Madhust** [comment]
@hez2010  Just now I faced similar issue and asked for clarification in Blazor gitter. My problem is due to distance between the server(Blazor app resides) and client(Browser). When the distance is more the round trip time(RTT) may be little high and you may face delay in UI change. In Blazor WASM there is no such round trip is done hence it worked smoothly for you.

@mrpmorris pointed me to the below link which explains this thing.
https://blazor-university.com/overview/blazor-hosting-models/

I guess this should be documented properly and I request Blazor team to look and provide any solution/workaround to overcome this problem which will help many amazing developers out there.

**Comment by pranavkm** [comment]
Thanks for the link @Madhust. This is also covered as part of Blazor's documentation here: https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1. 

* In the apps that you shared with me, there isn't any noticeable latency for me. This could very well be the result of geo-location of their deployment servers.
* The apps rely on JSInterop to display / animate their components. While this is fine for most purposes, it does mean your UI is going to be bounded by the round-trip-time to the server. 
* In general, network latency is going to be a factor to consider when choosing your hosting models. For a lot of applications, this latency might not be a significant issue, or can be mitigated by other mechanisms (such as taking advantage of Azure SignalR Service's global reach). However, if having low latency apps is critical to your application, going the WebAssembly route might be a more appropriate model to consider for your applications.

**Comment by hez2010** [comment]
Thanks for reply.
However, I think at least JSInterop part can be done at client side to reduce latency. If there's an event listener which is listening to `mouse move` event, it will produce large overhead to server.

**Comment by javiercn** [comment]
We've done a lot of improvements in this area for 5.0 and additionally we recommend following the [performance guide](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-3.1) we created.

If after that, you still have issues, let us know and we'll reevaluate the issue.
