### ISSUE TITLE
Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server please set an example with roles

### ISSUE THREAD

**Issue by carlosalcantara2668** [dotnet/aspnetcore#19769]
In the documentation this section is incomplete "Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server" because it is necessary to make an example with roles

### Additional context
please set an example with roles

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by 4deeptech** [comment]
@carlosalcantara2668 I just went through this trying to hook Blazor WASM up to identity server 4 OIDC.  There won't be an example in the docs for this because it doesn't work out of the box with IdentityServer4 role claims.  Here's why.  In my implementation, I use asp.net identity and have customized it to have multi-tenancy, and within a tenant, there can be roles.  Each role I have defined a set of claims which are permissions for that role.  When a user registers, they get assigned a default set of roles, each having a set of claims.  Note that I said SET of roles, meaning more than 1.  I register an IProfileService implementation that reads the assigned identity roles and claims and adds these to the claims set that ID4 builds and returns in the access token.  The ISSUE here is that it combines them into a single ClaimTypes.Role (type) claim and the string value for this is:  ["role1","role2", "role...n"] format.  **This BLOWS up the blazor client side handling and ends up not matching ANY roles**. To get around this, I ditched the role based checks in lieu of Policy based checks.  When you implement a policy based system you can create your own 'handler' and 'requirement' that allows you to take control of the claim checking process.  I implemented two different ones. One that is purely roles, and the other that is purely permission based. The permission based on is more granular.  Let's say I have a role called 'Accounting' which has 3 different permissions assigned: accounting/read, accounting/write, accounting/remove.  The permission based policy will allow me to use an AuthorizeView to display a 'delete' button/action for only those people that have 'accounting/remove' permission.  That way, if I also have a role called 'Administrator', users assigned to that role would be assigned all permissions which would include 'accounting/remove' and they too would see the buttion/action in the view. **If your auth provider returns the role claims as separate claims in the token, then the built-in stuff would work...Identity Server does not so you have to customize some things on one side or the other to make it work**.  One more thing, if your identity provider has the role claims using a different ClaimType other than the default of ClaimTypes.Role, then in Blazor you should be able to set 'options.UserOptions.RoleClaim' (in the AddOidcAuthentication call) to the claim type of your auth provider so tell it to look for them as a different type. Note that the array of roles as a string issue still applies. In my case, My custom profile service adds the permissions claims as type "permission" and my custom policy then looks at the claims of that type instead.

**Comment by javiercn** [comment]
Closing the loop here, there has been docs and a sample available for some time now. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio#name-and-role-claim-with-api-authorization) for the docs and [here](https://github.com/javiercn/BlazorAuthRoles) for a sample.
