### ISSUE TITLE
Why new Authentication Library targeting .netcoreapp3.1

### ISSUE THREAD

**Issue by ShrenikOne** [dotnet/aspnetcore#19785]
### Is your feature request related to a problem? Please describe.
Currently noticed that JwtToken, Certificate and other Authentication libraries are now started targeting .netcoreapp3.1, is there any rational behind it! Since we have common library same as Microsoft.Identity.Web which utilize different projects including .net4.8 and now this make us not allow to upgrade to latest 3.1.2 version of library.

### Describe the solution you'd like
Can you target Libraries to .NETStandard2.0, since i am able to copy and able to compile with .NETStandard2.0 without any changes.

**Comment by blowdart** [comment]
ASP.NET Core 3.0 and later only runs on .NET Core, not .NET Framework. 

The various packages that are part of it rely on having features in that core 3.x. You cannot pick parts of an application framework and hope it works, it just won't work.

So no, we will not target Net Standard 2.0.

Closing as by design.
