### ISSUE TITLE
[Blazor WASM PWA] AspNet.Core Hosted Failed to find a valid digest in the 'integrity' attribute

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#19828]
I am running a new Blazor-WASM 3.2 Preview 2 AspNetCore hosted inside a Kubernetes cluster and I am experiencing weird errors in a corporate browser:

```
Service worker: Install
Failed to find a valid digest in the 'integrity' attribute for resource 'https://movingpicturesevents.ro/_content/BlazorStrap/css/cromefix.css' with computed SHA-256 integrity 'zcYvqUfYN3GfyOYN7rX7IXuWA4q2tXxgmJzTDxmvYKk='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
Failed to find a valid digest in the 'integrity' attribute for resource 'https://movingpicturesevents.ro/index.html' with computed SHA-256 integrity 'Z/gb0XZMBuENaJIUS5BumSgKN79Icrkj9y4MuGewdhc='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
Failed to find a valid digest in the 'integrity' attribute for resource 'https://movingpicturesevents.ro/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' with computed SHA-256 integrity 'G0POD2J1R26XEDtnl2OT/PoZVgMsdYwohijiCDj36YQ='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://movingpicturesevents.ro/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' with computed SHA-256 integrity 'G0POD2J1R26XEDtnl2OT/PoZVgMsdYwohijiCDj36YQ='. The resource has been blocked.
```
`

You can find the repo [here](https://github.com/mihaimyh/laurkyt) and the live site [here](https://movingpicturesevents.ro/).

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014977 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by SteveSandersonMS** [comment]
The live site you've linked to (https://movingpicturesevents.ro/) doesn't seem to return a Blazor WebAssembly application.

Is it possible you could provide repro steps, or at least a minimal repo showing the issue? We don't normally debug issues that are provided just as a link to a production app repo, because they involve too many other project-specific concerns and we usually can't even run it without taking a lot of time to set up an isolated environment for it to go into.

Thanks!

**Comment by mihaimyh** [comment]
Hi Steve,

Thank you for your answer. The site is a Blazor WASM application, see below:

![image](https://user-images.githubusercontent.com/549272/77186144-18856980-6adb-11ea-8ee3-1591a8044765.png)

I do not know how you can reproduce this issue, I am only seeing this while trying to access this site from work, where I have corporate proxy restrictions.

The source code of the site can be found here https://github.com/mihaimyh/LaurKyt

I hope this helps.
Mihai

**Comment by SteveSandersonMS** [comment]
If the issue is specific to a particular corporate network, it probably has nothing to do with the integrity attribute.

To diagnose this better, can you please try disabling the integrity checking? To do so, add the following into a `<PropertyGroup>` in your Blazor WebAssembly project's `.csproj` file:

```xml
<BlazorCacheBootResources>false</BlazorCacheBootResources>
```

With this setting, there will be no integrity checking so you will probably be able to see the underlying problem.

**Comment by SteveSandersonMS** [comment]
Actually it's not specific to a particular corporate network. When trying your link just now (which seems to point to a different site now), I also see the integrity check failure.

**Comment by SteveSandersonMS** [comment]
I think I see what the issue is. Your web server is returning corrupted responses. Compare these two responses:

 * [Your source code for `index.html`](https://raw.githubusercontent.com/mihaimyh/LaurKyt/master/src/Client/wwwroot/index.html)
 * [Your server's response for `index.html`](view-source:https://movingpicturesevents.ro/index.html)

Notice how the source code contains indentation, but the server's response doesn't. Have you got some kind of HTML minification thing running? Or are you maybe running some kind of HTML minification step during deployment?

If you do, you either need to disable that, or you need to disable the integrity checking (in the way I mentioned above) because your hashes aren't going to match up if your server modifies the responses like this.

**Comment by SteveSandersonMS** [comment]
CC @danroth27 and @mkArtakMSFT for building awareness of these kinds of issues (please see my previous comment).

**Comment by mihaimyh** [comment]
> I think I see what the issue is. Your web server is returning corrupted responses. Compare these two responses:
> 
> * [Your source code for `index.html`](https://raw.githubusercontent.com/mihaimyh/LaurKyt/master/src/Client/wwwroot/index.html)
> * [Your server's response for `index.html`](https://movingpicturesevents.ro/index.html) (note: press ctrl+u to view source)
> 
> Notice how the source code contains indentation, but the server's response doesn't. Have you got some kind of HTML minification thing running? Or are you maybe running some kind of HTML minification step during deployment?
> 
> If you do, you either need to disable that, or you need to disable the integrity checking (in the way I mentioned above) because your hashes aren't going to match up if your server modifies the responses like this.

I am not sure where you see the missing indentation because I am not able to see any differences.

![image](https://user-images.githubusercontent.com/549272/77200547-732abf80-6af3-11ea-9942-df63ed4c01e1.png)

The site is hosted on a kubernetes cluster with a nginx ingress controller in front of it. I am not using any HTML minification, but I will check if this might be related with the ingress controller,

I will also disable integrity checking and let you know how it goes.

**Comment by danroth27** [comment]
@mihaimyh This is what we're seeing:

![image](https://user-images.githubusercontent.com/1874516/77205003-33db7f00-6ab1-11ea-8c1e-aaf3f0f7fc4e.png)

**Comment by SteveSandersonMS** [comment]
Do you have CloudFlare’s HTML minification turned on? https://support.cloudflare.com/hc/en-us/articles/200168196-How-do-I-minify-HTML-CSS-and-JavaScript-to-optimize-my-site-

**Comment by mihaimyh** [comment]
> Do you have CloudFlare’s HTML minification turned on? https://support.cloudflare.com/hc/en-us/articles/200168196-How-do-I-minify-HTML-CSS-and-JavaScript-to-optimize-my-site-

@SteveSandersonMS Yes, this seems to be the issue, I was not aware of this CloudFlare option. 
After turning it off seems to be working now.
Thank you for your support!
