### ISSUE TITLE
VSCode VSOnline C# completions do not work with latest release

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#19899]
With the latest VSOnline release we can no longer get C# completions for whatever reason. We'll need to investigate to find out why.

**Comment by ryanbrandenburg** [comment]
If I do the naive thing and just Create a VSO instance from a fully updated VS+extension completions work. Is there some extra switch or setting I need to set in order to ensure I'm hitting this scenario?
![CompletionInVSO](https://user-images.githubusercontent.com/14987221/79779991-1a1b9a80-82f0-11ea-8bb7-26af666acf38.png)

**Comment by NTaylorMullen** [comment]
> If I do the naive thing and just Create a VSO instance from a fully updated VS+extension completions work. Is there some extra switch or setting I need to set in order to ensure I'm hitting this scenario?

I believe it was C# completions specifically that were the problem

**Comment by ryanbrandenburg** [comment]
Oh man, I apparently need more coffee, it does indeed reproduce for C# completions.

**Comment by ryanbrandenburg** [comment]
Reproduction seemed to be because the clean environment I created didn't have C# extension installed (I thought it installed all my local VSCode extensions by default), once I install the C# extension on the VSOnline instance everything is fine:
![CompletionInVSOCSharp](https://user-images.githubusercontent.com/14987221/79787228-8354db00-82fb-11ea-9bcc-00f7451a04b5.png)

**Comment by ryanbrandenburg** [comment]
Also works in VSOnline in the browser. I'm going to close this out under the assumption that this was fixed by a different change, either on our end or by VSOnline.
