### ISSUE TITLE
Blazor WebAssembly App created as PWA cannot be debugged via Alt+Shift+D (WebSocket disconnected)

### ISSUE THREAD

**Issue by ydyote** [dotnet/aspnetcore#19930]
### Describe the bug
When I create Blazor Webassembly App as PWA I cannot debug via alt+shift+d, when I don't check the PWA checkbox, it works.

The error is shown as: Debugging connection was closed. Reason: WebSocket disconnected Recconect when ready by reopening DevTools

this is the screenshot of the DevTools:
![image](https://user-images.githubusercontent.com/54998537/76894402-5e012700-688e-11ea-86d2-cd37620c81a8.png)

### To Reproduce
1. Create Blazor Webassembly app PWA
2. Run as debug
3. In the opened chrome tab when the app loads, press Alt+Shift+D
4. Follow the instructions on the "Unable to find debuggable browser tab" page for chrome
5. New browser opens, wait for the app to load, press Alt+Shift+D
6. Wait for DevTools to load and see the error as it is on the screenshot

### Further technical details
- I think I used this template: "dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview2.20160.5" Not completely sure though, if you can provide a way to find out the exact version I will do it.

If something is missing, please let me know and I will try to provide more info.

(PS: I was trying to find out whether the blazor-analytics is hooked on the blazor router correctly, because it was not sending requests to my ga account, and also I'm not even sure if I could somehow debug it and find out whether it was hooked to the blazor router correctly)

**Comment by danroth27** [comment]
@SteveSandersonMS Is this a dup of https://github.com/mono/mono/issues/19218?

**Comment by SteveSandersonMS** [comment]
Yes. Closing as external.

@ydyote Sorry for the inconvenience. This is something we're already tracking producing a fix for in the Mono repo.

As a short-term workaround, if you only need the service worker to apply once your app is published (which is true in the default case using the template), you can change index.html so that instead of `navigator.serviceWorker.register('service-worker.js')`, it contains:

```js
if (location.hostname !== 'localhost') {
    navigator.serviceWorker.register('service-worker.js');
}
```

Then at least you can debug when the app is running on localhost. If you make this change, be sure to clear your browser's state (to unregister the existing service worker) from your app when running on localhost.

**Comment by ydyote** [comment]
Oh thanks guys, sorry for the duplicate
