### ISSUE TITLE
UserStore<> FindUserAsync

### ISSUE THREAD

**Issue by SteffenMangold** [dotnet/aspnetcore#19961]
### Describe the bug
Why is the methode `FindUserAsync` of `UserStore<>` marked private and protected?
Because of `public override Task<TUser> FindByIdAsync(string userId` not respect the TKey of user this method is needed to access.

### To Reproduce
Implement a custom UserStore with ´long´ as TKey for user.

``` C#
public class UserStore : UserStore<User, Role, ModelContext, long, UserClaim, UserRole, UserLogin, UserToken, RoleClaim>
{
```

**Comment by blowdart** [comment]
You shouldn't be this far down, there are public apis for finding things by keys. But string is always the key for public apis, your store needs to do the necessary conversion against your user class.

This is by design, because TKey is just yet another layer of generics which frankly didn't work for consumers.

**Comment by SteffenMangold** [comment]
For what property is `FindUserAsync` looking at, the email address? So you mean searching for a user by ID is something to avoid in general?

**Comment by blowdart** [comment]
The user ID and the email field can be different, but our templates by default make them the same. However that's up to you, and you can change it.

**Comment by shyamal890** [comment]
Sorry, I didn't get it, how to utilize `FindByIdAsync` when the user key's is `long`?

**Comment by sunildarji811** [comment]
In my User class I've override key as `Int` now to find it by `FindByIdAsync` ? any one has idea?
