### ISSUE TITLE
TestServer's ResponseBodyWriterStream's Flush should fail if SynchronousIO is not enabled

### ISSUE THREAD

**Issue by Euphoric** [dotnet/aspnetcore#19991]
### Describe the bug
When SyncronousIO is not enabled, [Kestrel's HttpResponseStream's synchronous Flush method](https://github.com/dotnet/aspnetcore/blob/7def10277abbb3086c4ee00e369faf6aa27d676a/src/Servers/Kestrel/Core/src/Internal/Http/HttpResponseStream.cs#L50) fails with an exception. [TestServer's ResponseBodyWriterStream's synchronous Flush](https://github.com/dotnet/aspnetcore/blob/7def10277abbb3086c4ee00e369faf6aa27d676a/src/Hosting/TestHost/src/ResponseBodyWriterStream.cs#L47) does not fail in same conditions. This causes TestServer to produce different behavior from Kestrel's.

This can create false positives in tests using TestServer.

Interestingly, IIS behaves same as TestServer, not Kestrel. Which of these should be correct behavior of synchronous Flush method?

### To Reproduce
Demonstration code : https://github.com/Euphoric/TestServerFlushDemonstration

### Further technical details
- ASP.NET Core version : 3.1.2

**Comment by Tratcher** [comment]
The Flush enforcement is inconsistent across the servers. Many opted not to throw because their Flush implementations don't really do anything, all the work is done in Write/Async.

There are also many components we don't control that call Flush in Dispose, even when they don't really need to. We'll need to figure out how to handle these in Kestrel.

**Comment by shirhatti** [comment]
We'd like for TestServer to mimic Kestrel behavior here and will be accept a contribution if we get it early enough during a release since it might impact other components upstack.
