### ISSUE TITLE
using AutoValidateAntiforgeryTokenAttribute with options.Cookie.Path set post requests fail when Action is not Index ( aspnetcore 3.1)

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#20065]
I've noticed strange behaviour in my app, so having this in Startup.cs:
```
public void ConfigureServices(IServiceCollection services)
{
	services.AddControllersWithViews(o =>
	{
		o.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
	});
	services.AddAntiforgery(options =>
	{
		options.Cookie.Path = "abc"; // without this all works
	});
```
If I launch the app in a new Tab/browser with Private Browsing and the Url is not from an Index action, for example:
```
contr1/Act1
contr1/Act2
```
then all the post actions (with the token present) will fail, 
and I can make them to work by going to the root `/` (Home/Index) and returning back (without closing the private browsing session)

but if I launch the app from an index action like:
```
/
/contr1
```
then post actions will work and I can go the rest of the pages (non index) and they will work as well

and to avoid this problem I need not to set the ` options.Cookie.Path`

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

We are not sure what you are trying to convey here, but from what we understand you are complaining that antiforgery doesn't work when you set a path for the cookie.

I would expect that to be the case since it seems your configuration is not correct and should only work for routes that start with the cookie path ** and that have the same casing as the cookie path**.

We're not exactly sure about what you are implying here, but the way to verify this is very straighforward:
* If you get a matching request token an a cookie token on the post request, you should pass the antiforgery check.
* If you don't get any of the two or they are mismatched, then antiforgery should fail.

I would check that, and if you thing there is a bug here, please include a small repro project and detailed steps on how to reproduce the issue.

**Comment by omuleanu** [comment]
@javiercn I was using similar code in MVC5 without problems,  and after moving to aspnetcore 3.1 I noticed the problem, I'm not sure why `options.Cookie.Path` was being set, so I don't know the proper this should be done.
I thought it's either a bug or I'm doing something wrong, but I couldn't find docs related to `AddAntiforgery` and `Cookie.Path`.

btw, how did you determined that my configuration is not correct ?

**Comment by javiercn** [comment]
@omuleanu I'm guessing because you are setting the path to "abc" so the most logical thing is that any action that is not under "abc" will fail antiforgery validation as the cookie is not there.

That's why we need a repro in case you think this is a bug, because it is not clear to us what you are trying to do, and we can't investigate based on the current information.

For us to move forward with an investigation or a more concrete response, we need a minimal repro project with detailed steps on how to trigger the issue.

**Comment by omuleanu** [comment]
ok, I was looking at the Cookie.Path as if it was name or domain
