### ISSUE TITLE
Consider upgrading reference to StackExchange.Redis

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#20076]
On [the advice of the StackExchange.Redis maintainers](https://github.com/dotnet/aspnetcore/pull/20042#issuecomment-602029515), we have held off on upgrading our version of StackExchange.Redis. We should revisit this later in the 5.0 release.

This applies to SignalR, but also to the Caching Redis extension. We can address them both together (and likely we'll be driving both) so I'll label `area-signalr` for tracking.

**Comment by anurse** [comment]
Suggest revisiting in preview4 milestone.

**Comment by shirhatti** [comment]
Triage note: StackExchange.Redis asked us to hold out for a bit. WE'll revisit in the 5.0 timeframe

**Comment by tebeco** [comment]
this is a very very long shot but I'll try,
@NickCraver @mgravell

I saw the previous version of `StackExchange.Redis` you were testing was rolled back and since then `2.1.28` and `2.1.30` were released.
I'm curious if it's still on hold or should i try to proceed here : https://github.com/dotnet/aspnetcore/issues/20040

**Comment by BrennanConroy** [comment]
@nickcraver 
> We've added more diagnostics and better error messaging (to distinguish between the earlier cases) in the 2.1.23 release (currently on MyGet). We'll get that dogfooded on Stack Overflow this week. It also adds more detection for binding redirect failures (at the pipelines layer) to users are alerted to more failure cases due to that.
>
> I'd say poke me in 1-2 weeks please - we'll have been in prod for a while and get more follow-ups from users testing it. I'd like positive reports on better issue resolution then advise a bump here for all users to benefit.
>
> We're also going to get a hold of the Azure Redis team and sanity check some previous decisions and see if tweaking some defaults makes sense (e.g. we have a theory about Redis instances going to "sleep" we think may be affecting some users...).

Do you have any updates on the newer Redis bits?

**Comment by NickCraver** [comment]
We have a large PR in progress to help the Sentinel bits - the support could be better and we're working through the API now. That's the largest "pending" thing we have - relevant here because it switches the connection strategy to be based on the connection string from the upstream library which makes it more generally usable, e.g. with this reference too. I'll sync with @mgravell tomorrow and get a recommendation here.

**Comment by mgravell** [comment]
There's also the hypothetical "pool" stuff. Pretty huge in terms of impact,
if I can land it.

**Comment by BrennanConroy** [comment]
Friendly ping, were the impactful changes resolved?

**Comment by tebeco** [comment]
hello @mgravell 
As it will probably not be part of `.net5.0`, what wrong could happen if we try to force the transitivity of `StackExchange.Redis` to `2.1.*` to avoid it being resolved to `2.0.*` ?
I suppose as it's just a `minor`, it should be ok.

Also, the question is not specific to `signalr` but generally speaking for all `Msft.Anc` and also [Microsoft.Extensions.Caching.StackExchangeRedis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis)

**Comment by BrennanConroy** [comment]
We generally don't update our 3rd party references unless there is a very good reason such as breaking changes. Consumers can manually reference higher versions of the transitive references if they want updates to the other package. And as long as there are no breaking changes it should work.

**Comment by tebeco** [comment]
thx for the input

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/32239
