### ISSUE TITLE
Add sort options for UseDirectoryBrowser

### ISSUE THREAD

**Issue by xboxeer** [dotnet/aspnetcore#20174]
### Is your feature request related to a problem? Please describe.
Our customer in Stackoverflow is using UseDirectoryBrowser to list the files on his server, he'd like to sort the listed files by created date and modified date, but there is not any places that we can config this, seems UseDirectoryBrowser does not have an option for that

### Describe the solution you'd like
DirectoryBrowserOptions class can have another enum property named SortBy, value of this propery could be CreatedDate, ModifiedDate, or a combination such as CreatedDate|ModifiedDate. In the meantime, UseDirectoryBrowser will check this propery and take the sort options into consideration while rendering the file list in frontend

### Additional context
Original post in stackoverflow as below
https://stackoverflow.com/questions/60850477/asp-net-directorybrowser-feature-how-to-control-sort

**Comment by Tratcher** [comment]
If we were to add such an option to DirectoryBrowserOptions  then the sort would have to happen right before passing the data to the formatter here since there's no way to pass in options to the formatter:
https://github.com/dotnet/aspnetcore/blob/19d2f6124f5d04859e350d1f5a01e994e14ef1ce/src/Middleware/StaticFiles/src/DirectoryBrowserMiddleware.cs#L96

Or maybe add it as an option directly on the HtmlDirectoryFormatter rather than DirectoryBrowserOptions and have you set the Formatter if you wanted to change it?

Your best bet in the short term is to replace DirectoryBrowserOptions.Formatter to customize the view. You can copy HtmlDirectoryFormatter and customize it to your liking.
https://github.com/dotnet/aspnetcore/blob/19d2f6124f5d04859e350d1f5a01e994e14ef1ce/src/Middleware/StaticFiles/src/HtmlDirectoryFormatter.cs#L20

**Comment by shirhatti** [comment]
Triage decision: The directory browser middleware is primarily intended for diagnostic scenarios. Unfortunately, we don't plan to do this. This is a great option to author a good third-party Directory Browser.
