### ISSUE TITLE
AddNewtonsoftJson options should configure newtonsoft settings for entire project and not just the controllers

### ISSUE THREAD

**Issue by tom171296** [dotnet/aspnetcore#20186]
I am trying to configure the options for Json serialization settings via AddNewtonsoftJson but this only configures the settings for data retrieved via a controller. I thought that this functionality would set the settings default settings of newtonsoft.

I would like to see that the AddNewtonsoftJson function should configure the default settings for newtonsoft, so I can use it to configure my json settings for the project. Instead of using the AddNewtonsoftJson function and configuring the other uses of Json serialization via the JsonConvert.DefaultSettings value.

**Comment by javiercn** [comment]
@tom171296 thanks for contacting us.

`AddNewtonsoftJson` only configures the settings for MVC and I don't think it's possible (nor desirable) to globally configure the settings in one place.

The main reasons are that:
1. We can't predict in advance what frameworks are going to be using newtonsoft.json and they would need to opt in to read the "common" options (hence by default options would not be global).
2. In many cases different frameworks need/want different serialization options, so having them in one place can make it so that a change for the serialization in your controllers affects the serialization format somewhere else without you noticing it.
