### ISSUE TITLE
Can somebody please inform the Visual Studio Team of these issues?

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#20235]
### Describe the bug
* On VS16.6P2 can you add a razor component to a project you get to a window "Waiting for Intellisense to finish initializing...You can continue working." which does not go away. If you close that window, do a rebuild, then you can open the new file.

* Trying to log into VS to give feedback results in "We could not refresh the credentials for the account. The method or operation is not implemented".

### To Reproduce
See description

**Comment by javiercn** [comment]
@MarkStega thanks for contacting us.

The best way for you to report this issue is through the visual studio report an issue dialog. See [instructions](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) here.

**Comment by MarkStega** [comment]
@javiercn Normally I would do that, but please look at the second bullet point again. They apparently broken the logon needed to get to the issue dialog.

**Comment by blowdart** [comment]
@timheuer do you know who to direct this to?

**Comment by timheuer** [comment]
@vijayrkn do we know about these ones?  I think the IntelliSense initializing one could be VS core related.  

/cc @madskristensen for comment about not being able to create a devcomm issue and no way to achieve that on the web interface

**Comment by vijayrkn** [comment]
@NTaylorMullen has fixed the first issue and should be available in the next preview. It was a last minute fix and we couldn’t get the fix into preview 2. Sorry about that.

**Comment by Pilchie** [comment]
Also tagging @mariaghiondea for the devcom issue.

**Comment by mariaghiondea** [comment]
It looks like you are facing a sign in issue. Please visit https://www.visualstudio.com/subscriptions/support/ and select “Account, Subscription & Billing Support” under the “Contact Us!” heading. Follow the prompts that will connect you to a support agent who can help troubleshoot this issue with your account. You can set Issue to “Subscription sign in support” for issues signing into the product.
You can’t post from the Developer Community website for VS since we want the diagnostics attached, to make it easier to investigate the issue. We are looking into a way to make this possible though. As a workaround until you get the first one going, you can post from the C++ or .NET space.

**Comment by Pilchie** [comment]
Thanks @mariaghiondea - closing as the first issue is addressed, and the second should move to VS.
