### ISSUE TITLE
[blazor][wasm] VS debug timeout is too low or counted too early

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#20247]
### Is your feature request related to a problem? Please describe.
There appears to be a timeout of 30s before the Web Sockets debug proxy gives up:

![](https://files.gitter.im/aspnet/Blazor/VrGR/image.png)

That sounds like a lot, but the way this seems to work currently is that those 30s count the following aspects:

1. building the solution
1. launching the regular VS debugger
1. launching the browser
1. attaching to a Web Socket

As soon as you have a non-trivial solution that requires a build, the first of those can easily take longer than 30s, thus causing this error message. If you then stop the debugger, and run it again (therefore not requiring another build and significantly reducing overall time), the debugger will be able to launch far more quickly, and hopefully successfully.

### Describe the solution you'd like
If my assumptions are correct: the timeout should start _after_ build.

Even then, I'm not sure 30s is high enough.

**Comment by EricCornelson** [comment]
This makes sense. Normally we're connecting the debugger to the browser which _should_ launch within a second or two. With Blazor-wasm, we're connecting to the Blazor CDP proxy, which is tied to the server application start-up (and thus, build).

We can certainly increase the timeout more as a quick fix, but I do worry that we'll always have some extremely large Blazor project that could take longer than that to build, and it would be nice to balance that with figuring out quickly whether or not the debugger was able to attach.

@SteveSandersonMS any guidance on a good timeout number, or a better way to order the launch? Is it possible to launch the javascript debugger _after_ the .NET build is finished to avoid this race?

**Comment by SteveSandersonMS** [comment]
Thanks for looking into it.

@BillHiebert would be best placed to know if we can do that.

**Comment by BillHiebert** [comment]
@EricCornelson - we don't launch the browser until after the server has started and we can connect to the port. i.e. the webserver has opened the socket.  So the build will have completed before we started the web server. If there is a subsequent delay before the CDP proxy is available that would introduce another race condition. Rather than put a hardcoded delay could you add a retry loop instead?

**Comment by EricCornelson** [comment]
@BillHiebert We do retry in a loop, the timeout value is for when to give up on that loop. It also needn't be hardcoded (we set it through the launch configuration), but it looks like we are currently hard-coding it for Blazor to 30s

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Blazor doesn't control this, so there's nothing for us to investigate.

If our only option is to extend the timeout, perhaps 60s is the next one to try.

Longer term maybe some other UX is applicable, for example a dialog showing a "waiting to connect..." spinner with a "cancel" button so the user can click cancel whenever they get bored of waiting, but besides that never time out (or set it to 10 minutes or something).

**Comment by StevenRasmussen** [comment]
Is there a way to make this configurable?  I'm running into this while trying to debug some startup issues.  Once the error displays, debugging stops and I'm unable to try and troubleshoot this issue.

**Comment by chrisknebel** [comment]
I have yet to successfully launch and use the WASM debugging feature because of this issue. Today, I even created the default application from the WASM template and, without changing a single line of the default code, had the same thing occur on the first debug attempt. Subsequent attempts got past the timeout issue but ran into the issue where "The breakpoint will not currently be hit. Unbound breakpoint" error occurred. For my real application, which is quite large, I've never been able to get past the timeout problem. Running the app without debug launches it within a couple of seconds of completing the build, so there are no inherent launch delays in the application itself. Unless this is addressed, I'm afraid it'll mean a lot of Console.WriteLine statements and a very poor developer experience, or abandoning the WASM configuration for this project.

**Comment by mkArtakMSFT** [comment]
@captainsafia is this being tracked on the tooling side? Should we close this one?

**Comment by captainsafia** [comment]
We've been tracking improving initialization performance overall, not adjusting the timeout.

IMO, tweaking with the timeout is not as valuable as spending time improving underlying performance.

@EricCornelson/@BillHiebert: In VS Code, users can configure the timeout and other options of the JS debugger. Is something similar being considered for VS?

**Comment by captainsafia** [comment]
It looks like VS already provides a way for users to adjust the timeout here. It can be done by editing the registry key using the following command in the VS command prompt.

```
VsRegEdit.exe set "<VSInstallFolder>" HKCU JSDebugger\Options\Debugging "BlazorTimeoutInMilliseconds" dword 60000
```

Where 6000 is the timeout unit in milliseconds.

@guardrex Can we document this in the troubleshooting guide as a way for users to work around the debug proxy taking too long to launch?

**Comment by captainsafia** [comment]
Closing this issue since we've documented how to customize the timeout.
