### ISSUE TITLE
dynamic type as Action method parameter in webapi post method does not give expected result

### ISSUE THREAD

**Issue by babula38** [dotnet/aspnetcore#20269]
### Issue
Trying to use **dynamic** type as request parameter in Aspnetcore web api 3.1. post action method.

### To Reproduce

- Create a webapi project using framework version 3.1.

- Create a Post action method with dynamic type as post parameter. see the code below.

``` C#
            [HttpPost]
        public void Post(dynamic request)
        {
            //json request
            //{
            // "Foo":"Value"
            //}
            var expected = request.Foo;
            //expected should contain the value for Foo.
            //But the object structure is different
        }
```
**Expected:-** Should get the value from the request.Foo.
**Actual:-**  It throws an exception & in the local windows the request contains the below value.
```C#
ValueKind=Object:"{"Foo":"Value"}"
```
### Further technical details
- ASP.NET Core version 3.1

**Comment by javiercn** [comment]
@babula38 thanks for contacting us.

I'm not sure `System.Text.Json` supports dynamic. From what I understand from the sample it is getting deserialized into a JsonElement.

This is not an ASP.NET Core specific issue but a System.Text.Json limitation, you can try using newtonsoft.json for this scenario (not sure if it will work) or file an issue in [dotnet/runtime](https://github.com/dotnet/runtime) so that they add this feature.
