### ISSUE TITLE
Odd UI behaviour with Date Binding on input type="date"

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/aspnetcore#20361]
Hi, 

Hope you're all keeping safe and well!

I have noticed some odd UI behaviour when using an input of type "date". 

I'm in the UK so the date is displaying as dd/mm/yyyy. When you start typing a date in, if on the month you type a "0" parts of the date reset themselves. I suspect it's to do with the fact that Blazor is trying to parse the date from a string and as soon as you type "0" in the month the string becomes an invalid date and the DateTime (DateOffset?) property behind the binding is being reset. 

Similar problems happen with an invalid year or day.

If I want a date of 25/05/2009 then that's what I type "25052009", but the 3rd number causes problems.

My code is very simple:

`<input class="form-control"
       type="date"
       @bind-value="@_bindingValue"
       style="margin-top: 0.2em;" />`

I did try to implement my own "binding" to the "string" value but Blazor "takes over" and doesn't let me get to the raw string value as it expects a datetime or datetimeoffset.

Thanks!

**Comment by javiercn** [comment]
@LaughingJohn thanks for contacting us.

@SteveSandersonMS do you have any ideas of what's going on here?

**Comment by LaughingJohn** [comment]
Thanks for looking. I've tried to create a simplest case, just to make sure it wasn't me. The razor page has this:

`<input class="form-control"
       type="date"
       @bind-value="@DateValue" />`

And the code behind has this:

`        public DateTime DateValue { get; set; }`

I've attached a small video. I'm typing "31032020" into the control. When I press "0" on the month you'll see that the day reverts back to "01".
[2020-03-31_18-36-22.zip](https://github.com/dotnet/aspnetcore/files/4410708/2020-03-31_18-36-22.zip)

**Comment by barahonajm** [comment]
Also if you change the DateValue to be nullable, any invalid value will cause the input to reset to "dd/mm/aaaa", this does not happens on normal html.

**Comment by barahonajm** [comment]
There are a bunch of strange things around the type="date":

1.- The `onchange` event is fired every time the date changes and not when the input loses focus
2.- As stated here https://html.spec.whatwg.org/multipage/input.html#date-state-(type%3Ddate)
> The value sanitization algorithm is as follows: If the value of the element is not a valid date string, then set it to the empty string instead.

for that reason `e.target.value` return an empty string, that is the reason because `EventCallbackFactoryBinderExtensions:525`  thinks the user cleaned up the value so it calls `setter` with  `Default`


**Suggestion**
I believe we need to add the `ValidityState` object to `ChangeEventArgs` (maybe not the whole object), then if the value is empty we also check if the value is valid before call `setter(default)`, that way the date reverts to its previous valid state.

![image](https://user-images.githubusercontent.com/15148088/78461015-db50d800-7693-11ea-95e2-0fb403653ce7.png)

**Comment by SteveSandersonMS** [comment]
I don't see any repro code posted here (just a video) so it's difficult to be sure I know what the issue is.

My guess is that you're trying to bind directly to a .NET `DateTime` value. If so, I'd suggest that's not always a good plan, since a `DateTime` has no way to hold invalid values. If you want to allow the UI to be in the state of displaying an invalid value, then the underlying storage has to be able to hold that invalid value.

This is why the built-in `InputDate` component uses a `string` for the underlying storage, while also exposing the bound data as a `DateTime` value that only changes when the UI receives a valid entry. If you don't do something like this, then you should expect things to be auto-reset when the UI would otherwise get into an invalid state, because two-way binding always tries to keep things in sync.

More generally if you want to build custom input components, I recommend inheriting from the framework's built-in `InputBase` since this not only gives you a pattern for dealing with temporary invalid states, but also hooks into the framework's validation and notifications system: https://chrissainty.com/building-custom-input-components-for-blazor-using-inputbase/

**Comment by LaughingJohn** [comment]
Thanks Steve, the repro code was there, it was just the 2 lines that showed exactly what you said - binding directly to a datetime value.  
I will look at InputDate, I think I looked before and it requires a nullable DateTime - which is a bit of a pain as I'm using an existing model where it isn't. 
Maybe I'm wrong, but I'll figure something out anyway.
