### ISSUE TITLE
[Blazor Wasm] Clearing cache after new deploy

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#20408]
I was searching for a way to force the browser to refresh/clear it's cache whenever I am deploying a new version of a Blazor Wasm app.

Currently, when a new deploy is made the browser still shows the old version of the app until I force reload it using `CTRL+F5`, but on mobile this process can only be done by accessing browser's settings and manually clearing cache there.

You can imagine that all users must manually clear their cache to see an updated version of the app, unless I am doing something wrong here.

Is there a way to simplify this whenever a new version of the app is published?
I am also using Cloudflare, is there a way their cache can be automatically refreshed too with a new app publish?

**Comment by TravisKool** [comment]
I am also interested in something like this.

Client's browser session is caching and not cleared when a new version is available..

**Comment by mihaimyh** [comment]
Any news on this?

**Comment by SteveSandersonMS** [comment]
This is a matter of how your web server is configured, not about Blazor WebAssembly.

As long as your web server returns correct HTTP cache control headers, browsers will know not to re-use cached resources.

For example, if you use the "ASP.NET Core hosted" version of the Blazor WebAssembly template, the server will return `Cache-Control: no-cache` headers which means the browser will always check with the server whether updated content is present (and this uses etags, so the server will return 304 meaning "keep using your cached content" if nothing has changed since the browser last updated its content).

If you use a different web server or service, such as Cloudflare, then it's up to you to configure the web server to return correct caching headers. Blazor WebAssembly can't control or even influence that.

Hope that makes sense!
