### ISSUE TITLE
Razor Class Library static files inaccessible in any ASPNETCORE_ENVIRONMENT other than Development

### ISSUE THREAD

**Issue by idlemind** [dotnet/aspnetcore#20409]
Hi,

I have a Razor Class Library in .NET Core 3.1.0. The RCL has static assets located in wwwroot folder such as js frameworks, css, etc. 

I have a .NET Core 3.1 Web application that references the RCL. When i run the web application the static files within the RCL can be accessed using the path /_content/AreaName/js/...

This works fine when then  ASPNETCORE_ENVIRONMENT is Development. If i change it to anything else, e.g. Local, Staging, the web application returns a 404 (Not found) when trying to access the static files.

Is this an issue/feature?
Is there a workaround?

Any advice is appreciated.

**Comment by javiercn** [comment]
@idlemind thanks for contacting us.

The current behavior is by design. RCL is a development time feature, and doesn't exist when the application is published, hence it's only plugged in by default during development.

If you want to enable it for a different environment you can call `webHostBuilder.UseStaticWebAssets()` to turn it on unconditionally.

**Comment by idlemind** [comment]
Thank you for the prompt response and workaround.
