### ISSUE TITLE
Query String overriding Form Values in Posted Form

### ISSUE THREAD

**Issue by lostatredrock** [dotnet/aspnetcore#20449]
### Issue
We are observing an issue with how model binding is handling scenarios where data exists in both the query string and form in an .Net Core 3.1.3 MVC action.

According to the [documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#sources) model binding should look for data in the following placers in order:

1. Form fields
2. The request body (For controllers that have the [ApiController] attribute.)
3. Route data
4. Query string parameters
5. Uploaded files

What we are observing is that:

- if you submit a query string which contains the same name/value pairs from the form body (ie Val1=FromQS&Val2=FromQs) it will never use it in model binding regardless of it something is in the form values or not
- but if you submit a query string that prefixes the value names with the variable name of the view model input parameter (ie vm.Val1=FromQS&vm.Val2=FromQs) then the model binder pulls exclusively from the query string ignoring any form inputs.

### To Reproduce
The [sample project](https://github.com/lostatredrock/BindingIssueDemo) contains a page /Home/Demo with 3 input forms.

All 3 forms submit input to both properties of the view model using the standard asp-for syntax to setup the input text boxes. They differ in that:
- No QS does not use any query string at all
- Normal QS appends the query string “Val1=FromQS&Val2=FromQs” to the action
- Vm. QS appends the query string “vm.Val1=FromQS&vm.Val2=FromQs” to the action
 
**I would expect them to behave based on the documentation** 
- No QS – should behave like a normal form with only the form values available for binding
- Normal QS – the qeuery string should populate the model only if the form fields are left blank
- Vm. Qs – the query string should have no impact on the model as the parameter names are not correct
 
**What actually happens**
- No QS – behaves as expected
- Normal Qs – never uses the values in the query string regardless of whether the form is filled in or not
- Vm. Qs – the query string overrides all user input in the form

**Comment by pranavkm** [comment]
@lostatredrock the behavior you're seeing is by design. It's [documented](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#complex-types) in passing, but perhaps could do with a more elaborate explanation. 

Consider the following:

```C#
class Person
{
   public string Name { get; set; }

   public int Age { get; set; }
}

// PersonController.cs
[HttpPost]
public IActionResult Post(Person person)
```

Model binding will allow binding `person.Name` as well as `Name`. However, if both are present, only the prefixed value is used. In it's implementation, model binding queries value providers to determine if any have values that start with the `person` prefix. If any value provider returns true, prefixed values are exclusively for binding all values for that model. Non-prefixed values are no longer considered.

If you think this behavior is problematic, here are few ways to address this:

1) You can configure the prefix that generated form fields will have in your view:

```razor
// Index.cshtml
@{ ViewData.TemplateInfo.HtmlFieldPrefix = "person"; }

<input asp-for="Name" /> <!-- this should produce <input name="person.Name" ... /> -->
```

2) You could require an exact prefix to match on the controller:

```C#
public IActionResult Post([Bind(Prefix= "")] Person person)
```

3) You could write a [`ResourceFilter`](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#resource-filters) that removes the query string value provider so query string inputs aren't used.

If you think the documentation could be further improved, we'd be happy to accept a PR.

**Comment by lostatredrock** [comment]
Thanks for the feedback, I had missed this section when reviewing the priority.  Just to confirm my understanding of this is correct I wanted to confirm that decorating the action parameter with the [FromForm] attribute would also override this behavior.  It appears this approach when appropriate gets is the behavior we want.

**Comment by pranavkm** [comment]
@lostatredrock that should work if you do not care about binding from other sources (query string, route, http headers etc)
