### ISSUE TITLE
Client Secret in AddOidcAuthentication

### ISSUE THREAD

**Issue by ferguson-eric** [dotnet/aspnetcore#20452]
### Is your feature request related to a problem? Please describe.
I have a Blazor WASM SPA. It calls an IdP running IdentityServer4 to authenticate interactive users. The SPA can then use the bearer token to call a seperate API.

How do we pass the client secret with the AddOidcAuthentication extension method? The client secret is required for 'authorization_code'.

I can turn off the requirement for the client secret code on the IdP, but I would rather not.

### Describe the solution you'd like
Ideally a way to use a client secret on the client side, which can then be used in the call to the IdP.

### Additional context
I used the following article as a basis: https://docs.microsoft.com/en-gb/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1

cc: @guardrex

**Comment by javiercn** [comment]
@ferguson-eric thanks for contacting us.

Blazor webassembly applications are what is called a 'public application' in oAuth/openid terms. You should not use a client secret with it as the app has no way to securely hold on to that secret and you are not improving the security in any means by having it.

The right thing to do here is to actually disable the requirement for the client secret on the IdP and disable the emission of refresh tokens since they can't also be handled in a secure/safe way.

The recommendation is that you use code+PKCE for public clients, which happens automatically when you set the response_type to code.
