### ISSUE TITLE
SignalR, server side events doesn't work when deployed to IIS without WebSockets and UseResponseCaching is configured

### ISSUE THREAD

**Issue by Hrydberg** [dotnet/aspnetcore#20498]
### Describe the bug
Server side events doesn't work when deployed to IIS without WebSockets and UseResponseCaching is configured and the app is using in-process hosting.
If I use out-of-process hosting or remove UseResponseCaching it works.

### To Reproduce
Create a web application
Call UseResponseCaching in Startup.cs
Use in-process hosting
Deploy to IIS where WebSockets is not installed

This error is logged after 30 second when SignalR tries to connect:
![image](https://user-images.githubusercontent.com/3148297/78363268-c274f380-75bb-11ea-9163-cf8bce76f531.png)

Here is a small Webapplication with the problem.
[WebApplication2.zip](https://github.com/dotnet/aspnetcore/files/4427353/WebApplication2.zip)

### Further technical details
- ASP.NET Core version: 3.1

**Comment by JunTaoLuo** [comment]
@BrennanConroy and I took a look yesterday and it seems like this might be an issue with IIS in-proc and not with signalr or responsecaching. Specifically, we observed the following:
1. The error is likely due to responses not being sent correctly. 
2. The reason response caching causes errors is because it substitutes the response body stream. We can rule out response caching as the root cause since we are able to reproduce the error with a dummy stream that replaces the response body stream.
3. The underlying response body stream that was replaced was a 
4. The error only seems to occur when hosted in IIS inproc and it's likely that it handles response streams differently than out of proc.

Our suspicion is that there's some logic regarding how response body streams and response body writers are interacting in IIS inproc and it may be broken when the stream is substituted. This may mean that response caching is just broken on IIS inproc completely. Maybe @jkotalik would be able to help in this area?
