### ISSUE TITLE
Add additional file-types into service-worker for offline caching 

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#20550]
https://github.com/dotnet/aspnetcore/blob/fd9c7861655f368848ede4661b183098690aabad/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/wwwroot/service-worker.published.js#L11

At the moment I think some important types are missing that should be cached by default.
.svg
.webp
Various font types. Maybe .woff2 is sufficient.

**Comment by MarkusRodler** [comment]
I can make an PR if this feature is helpful for everyone.

**Comment by javiercn** [comment]
@MarkusRodler thanks for contacting us.

The service worker is provided in the template so that you can customize these things. We will take your request into consideration, but our aim is not to try and cover every possible file and instead recommend people that they modify the service worker. That's the main reason it is a file on the template.

**Comment by burakakca** [comment]
How can I edit the service worker, I couldn't find it. Will it be available with the next update?

**Comment by MarkusRodler** [comment]
> How can I edit the service worker, I couldn't find it. Will it be available with the next update?

You can find it in the service-worker.published.js file inside the wwwroot. But only if you installed the PWA Template via the --pwa command-line option
