### ISSUE TITLE
Blazor file input click not working in firefox

### ISSUE THREAD

**Issue by fabianschurz** [dotnet/aspnetcore#20555]
### Describe the bug
Trigger a click event via Javascript on an input element of type file is not working. 
When searching the web for my problem i found [this](https://stackoverflow.com/questions/59838150/blazor-file-input-click-not-working-in-firefox) stackoverflow thread. I already opened an issue here #20228 but it was closed with the reason: "Firefox security issue" which is not right.

### To Reproduce
Create an hidden input file element in a razor component. Then create a button. On the button click call a void, inside the void method call the IJsRuntime invoke method to trigger your js function that clicks the input file element by id.

It's not a firefox security feature. Plain html is working. See here: https://jsfiddle.net/chxnbmqt/

There are many other way's to achieve custom styling of a file input element (already implemented another way). Still i think this may be a bug related to blazor.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

IDE: VS

<TargetFramework>netcoreapp3.1</TargetFramework>

dotnet --info:
.NET Core SDK:
 Version:   3.1.101
 Commit:    b377529961

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@xFirestorm thanks for contacting us.

we'll take another look at this and get back to you.

**Comment by captainsafia** [comment]
Hello @xFirestorm -- I was able to reproduce this issue in Firefox as well and did notice that it works in plain HTML.

From my end, it appears that the click event on the input is indeed working. I verified this by adding a event listener to the `click` event on the input component.

The event dispatched from the JSInterop call and the event dispatched from standard JS example are virtually the same except for one distinction. The `explicitOriginalTarget` property is different for the two. 

For a JSInterop call, the value is `<input id="fileElem" type="file" multiple="" style="display:none">` and for a standard JS invocation it is `<button onclick="elementClick('fileElem')">`.

As it turns out, `explicitOriginalTarget` is a Firefox-specific event property that is used to track events that have been retargetted ([ref](https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget)). I'll admit that I don't have a clear understanding of why this particular property being different would prevent the file browser from showing, but considering the circumstance I suspect it has something to do with it.

From the Blazor side of things, we should probably try to align the way we set the `explicitOriginalTarget` property with the way that Firefox expects it.

I'll track this is a bug for now, albeit relatively low priority considering it's browser specific.

@xFirestorm It seems like you have a workaround for users who want to achieve the same feature (invisible input with file browser triggered via button click). Can you share the alternative here?

**Comment by xFirestorm** [comment]
@captainsafia Thanks for your deep investigation on this.

The workaround is to use plain HTML and JS.

```
<input type="file" id="fileInput" style="display: none;" onchange="YourAfterFileSelectedMethod"/> 
<button onclick="ClickFileInput()">Import</button>

function ClickFileInput() {
    document.getElementById('fileInput').click();
}
```

**Comment by captainsafia** [comment]
@SteveSandersonMS This is the duplicate issue we were discussing during triage today. It occurs on Blazor Server. I assume that the difference I outlined [here](https://github.com/dotnet/aspnetcore/issues/20555#issuecomment-625473590) is a result of the distinction you pointed out about where the JSInterop call was made?

**Comment by SteveSandersonMS** [comment]
@captainsafia Sorry for the slow response. I'm not 100% certain whether this discussion was resolved by us offline, so I'll just reply here now :)

It absolutely might be that `explicitOriginalTarget` relates to something in the browser's internal tracking about whether a given call stack originates in a user action or not. My understanding of the restriction is described in [this blog post](https://mariusschulz.com/blog/programmatically-opening-a-file-dialog-with-javascript). Assuming that blog post is correct, then people shouldn't expect to trigger a file open dialog from a .NET event handler due to the asynchrony, and should instead use the technique of adding a JS event handler like you mentioned in your previous comment.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
