### ISSUE TITLE
[Blazor] Give password reset token as query string

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#20556]
Hi,

I try to make a page named `/reset` and pass the reset token as a query string, by this way:
```
/reset?token=CfDJ8E3Hp0Ox3zRAnTotcZk2BDOWVlgIAl0ru7xNHiiqKd8FUysw9Nc8vxfztXo22VmzElX8JbyHupg+Ojh4mbaAbVKwRL/gO3U4zSXDtzQFutiulv+aL/QKzgiD4Qc+LLe0bIF9MpZv+OeeFqUCY76bl3kLmapuAOH+0K3YTq4zmaNhZR1v6P0sQy8/6NhEuktCIyAaEzJ+h1nekCi5aDqvMx0fYO7kAy/rq4kf79F7iRgi
```

Because there are some slashes in the token the route is not recognized, I had to replace slashes by underscores.

Kind regards

**Comment by GrabYourPitchforks** [comment]
Is it the slash (`'/'`) or the plus sign (`'+'`) that's causing problems? The plus sign has special meaning in query strings, as most frameworks interpret it as a space character rather than a literal plus sign.

Usually the way people work around this is by using _base64url_ encoding rather than standard base64 encoding when generating tokens that will end up in URLs.

**Comment by javiercn** [comment]
@clintnetwork thanks for contacting us.

@GrabYourPitchforks answer is correct

**Comment by clintnetwork** [comment]
Oh yeah it's maybe space

**Comment by javiercn** [comment]
Closing for now since this is not blazor specific

**Comment by clintnetwork** [comment]
No final it's slash for sure, I replace slash with underscore and it works
