### ISSUE TITLE
Silent renew with Oidc and Blazor WebAssembly

### ISSUE THREAD

**Issue by cornem** [dotnet/aspnetcore#20607]
### Is your feature request related to a problem? Please describe.
Typically access tokens provided by the identity provider have a limited lifetime. When the access token expires, the client obtains a new token on behalf of the user.
In browser scenarios it is not recommended to use refresh tokens, which usually have a much longer lifetime, but would need to be stored securely to prevent leaking.

The documentation on authorization with Blazor WebAssembly includes [additional scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1) like saving application state if the access token expires, redirect to the IdP to obtain a new token, restore state from session storage upon return. This is a perfectly valid suggestion, but it adds a lot of overhead as the complexity of the app grows.

### Describe the solution you'd like
IdentityModel's [oidc-client-js](https://github.com/IdentityModel/oidc-client-js) - which is often used in JavaScript-based SPAs - supports silent renew. Essentially, it tracks access token expiration and uses an iframe to round-trip to the IdP for a new set of tokens. This means the SPA itself does not have to redirect (unless for some reason silent renew fails), thus keeping its state intact.

It would be very helpful if the built-in Oidc authentication library in Blazor WebAssembly supported some form of silent token renewal.

**Comment by javiercn** [comment]
@cornem we don't do automatic silent renew, but our API will silently renew the token when you call `provider.RequestAccessToken` the reason we don't do automatic silent renew is because it has some problems, like when people leave the window open for the night (after they leave work) and the token keeps getting renewed overnight.

This is something that is also easy to implement yourself in c#, simply call `RequestAccessToken` and it will return you the token as well as the expiration time. You can then setup a timer and x minutes before expiry you can renew the token yourself.

**Comment by cornem** [comment]
OK, great. Thanks for the suggestion. Using a timer with `RequestAccessToken` should be fine for the app I'm working on.
