### ISSUE TITLE
Blazor WASM jsRuntime.InvokeAsync<System.Drawing.Rectangle> not working in RELEASE build

### ISSUE THREAD

**Issue by Forestbrook** [dotnet/aspnetcore#20716]
I have a strange issue.

I created a JavaScript function getElementPosition which returns { Width, Height, X, Y }, all converted to integers.

I call this function with:
var result = await _jsRuntime.InvokeAsync<System.Drawing.Rectangle>("MyFuncts.getElementPosition", elementReference);

In my debug build I get the correct results.
But in the release build I get an empty Rectangle!

Is there any issue with using a struct (like System.Drawing.Rectangle) for TValue?

I get the correct values in my release build when I replace System.Drawing.Rectangle with something like:

public class ElementRect
        {
            public int Width { get; set; }
            public int Height { get; set; }
            public int X { get; set; }
            public int Y { get; set; }
        }

**Comment by javiercn** [comment]
@Forestbrook thanks for contacting us.

The linker is likely stripping away those fields since it can't tell they are being used. I would suggest you create a custom descriptor to keep the fields. See [this](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file) for details

**Comment by Forestbrook** [comment]
Thanks @javiercn! Problem solved by adding LinkerConfig.xml with content:

<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="netstandard">
    <type fullname="System.Drawing.Rectangle" />
  </assembly>
</linker>
