### ISSUE TITLE
JsonSerializer should round trip AuthenticationProperties

### ISSUE THREAD

**Issue by brockallen** [dotnet/aspnetcore#20722]
`JsonSerializer` doesn't seem to seralize/deseralize the `AuthenticationProperties` class properly.

This test:

```
[Fact]
public void JsonSerializer_should_round_trip_AuthenticationProperties()
{
    var props = new AuthenticationProperties();
    props.Items.Add("foo", "bar");
            
    var json = JsonSerializer.Serialize(props);
    props = JsonSerializer.Deserialize<AuthenticationProperties>(json);

    props.Items.ContainsKey("foo").Should().BeTrue();
    props.Items["foo"].Should().Be("bar");
}
```

Fails with:

```
Message: 
    Expected props.Items.ContainsKey("foo") to be true, but found False.
```

Using ASP.NET Core 3.1.3.

Please advise.

**Comment by pranavkm** [comment]
The properties do not have [public setters](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Authentication.Abstractions/src/AuthenticationProperties.cs#L51-L57). System.Text.Json currently does not have the ability to update a collection property.

**Comment by brockallen** [comment]
For what it's worth, prior to ASP.NET Core 3.1, we used JSON.NET and it worked correctly.

**Comment by anurse** [comment]
The problem here is that Newtonsoft.Json was very aggressive about trying to deserialize the type and would use the dictionary constructor to deserialize it. System.Text.Json does not do that. This is probably best handled by writing a JsonConverter using the new System.Text.Json APIs.

Can you provide more details as to what your scenario is and why you want to deserialize the Auth Properties?

**Comment by brockallen** [comment]
> Can you provide more details as to what your scenario is and why you want to deserialize the Auth Properties?

Because this: https://github.com/dotnet/aspnetcore/blob/75e0115de9ff4ba6ab139777099dc9d951b2a3ff/src/Security/Authentication/OAuth/src/OAuthOptions.cs#L104
