### ISSUE TITLE
Blazer WebAssembly and support for Android

### ISSUE THREAD

**Issue by shahidroofi** [dotnet/aspnetcore#20770]
since webassembly uses mono and shows to be supported on Andriod. While .net core official support does not list Andriod as OS. So how well the blazer client side code on c# will run on andriod phones: https://stackoverflow.com/questions/61173399/webassembly-blazor-andriod-support.

just a question actually i raised on stackoverflow. Please don't mind if i am raising the same on wrong forum.

**Comment by javiercn** [comment]
@shahidroofi thanks for contacting us.

Blazor uses WebAssembly which runs inside the browser. As a result of that, it runs on Android when you run it inside Edge/Chrome.

**Comment by shahidroofi** [comment]
makes good sense. thanks @javiercn 
i assume that .net core support documentation now now need to include Andriod as supported OS in that case. (currently not the case)

**Comment by danroth27** [comment]
Hi @shahidroofi. Blazor WebAssembly apps use a WebAssembly implementation of the Mono IL interpreter instead of .NET Core, so the .NET Core docs are still technically correct. It's a bit confusing right now, because there are multiple different .NET implementations that make up the .NET ecosystem currently. In .NET 5 this should all get cleaned up and unified.

**Comment by shahidroofi** [comment]
thanks @danroth27 
thing is clear now.
