### ISSUE TITLE
Blazor refreshing or navigating to a sub page gives HttpStatusCode: 404

### ISSUE THREAD

**Issue by DanielFawcett** [dotnet/aspnetcore#20788]
### Describe the bug
When refreshing or navigating to a sub page of a hosted website it will give a 404 error.

This is a Single page application with no server and is hosted on azure static sites and is also using a CSN.

### To Reproduce
Publish a site with multiple pages to azure static sites.
Try to navigate a sub page www.domain.co.uk/about
you will get the below error.

The requested content does not exist.
HttpStatusCode: 404
ErrorCode: WebContentNotFound
RequestId : 559bff79-501e-0061-40a1-11c4aa000000
TimeStamp : 2020-04-13T14:43:35.3970428Z
-->

### Further technical details
- Latest version of core and blazor
- Live Website

**Comment by DanielFawcett** [comment]
I can leave the site if you want a live example

**Comment by javiercn** [comment]
@DanielFawcett thanks for contacting us. 

This is likely an issue in the "host" in the set that you need to configure it to serve a default document for any route that doesn't match. I believe there is a way to do that with azure static sites.

/cc @danroth27 who has been doing some work in this area.

**Comment by DanielFawcett** [comment]
But the problem is that that page does exist and it is still giving the does not exist document. Does that make sense.

So you can access the page from the nav menu but then if you Refresh you get the error, is this still a host problem??

**Comment by DanielFawcett** [comment]
@javiercn

**Comment by danroth27** [comment]
Hi @Danielfawcett. Blazor does client-side routing, where it intercepts browser navigations and then renders the correct component based on the route. Obviously this can only work after the Blazor app has been loaded and started from the root of the app. If you navigate the browser directly to a page other than the root, then you need to have something on the server that redirects to the root of the app so that client-side routing can then kick in and handle the request. In ASP.NET Core hosted Blazor apps we handle this for you. With standalone Blazor WebAssembly apps you have to configure the host to do this. With Azure Static Sites I believe the typical way to handle this is to configure the error page to point to your index.html file.

**Comment by DanielFawcett** [comment]
Wonderful, that makes a lot more sense as with my wasam with asp.net server it works fine!! Thank you for you’re help! Keep up the good work all of you, absolutely love blazor.
