### ISSUE TITLE
Razor Syntax Tree MarkupTextLiteral Capturing Content Out of Context

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#20797]
Code Snippet:
![image](https://user-images.githubusercontent.com/14852843/79156128-33b86180-7d87-11ea-90ca-d5cda4b8af4f.png)

Issue: At the cursor position (line 4), the syntax tree interprets being at a `MarkupElement` node with 2 children. 

1. MarkupStartTag (logical)
2. MarkupTextLiteral based on the (unrelated) "closing" > on line 11

![image](https://user-images.githubusercontent.com/14852843/79156291-75e1a300-7d87-11ea-9708-955991f0fb9d.png)

Expected:
Start tag value should be empty (just opening `<` char).

Actual: 
Start tag value is all the text between the opening `<` on line 4 to the "closing" `>` on line 11.

```
SerializedValue [string]:"MarkupStartTag - [63..171) - FullWidth: 108 - [<\rLF    }\rLF}\rLF \rLF@code {\rLF    private bool _collapseNavMenu = true;\rLF \rLF    private string NavMenuCssClass =>] - Gen<Markup> - SpanEditHandler;Accepts:None - [<\rLF    }\rLF}\rLF \rLF@code {\rLF    private bool _collapseNavMenu = true;\rLF \rLF    private string NavMenuCssClass =>]\n    OpenAngle;[<];\n    Text;[<Missing>];\n    MarkupMinimizedAttributeBlock - [64..71) - FullWidth: 7 - [\rLF    }]\n        MarkupTextLiteral - [64..70) - FullWidth: 6 - [\rLF    ] - Gen<Markup> - SpanEditHandler;Accepts:Any\n            NewLine;[\rLF];\n            Whitespace;[    ];\n        MarkupTextLiteral - [70..71) - FullWidth: 1 - [}] - Gen<Markup> - SpanEditHandler;Accepts:Any\n            Text;[}];\n    MarkupMinimizedAttributeBlock - [71..74) - FullWidth: 3 - [\rLF}]\n        MarkupTextLiteral - [71..73) - FullWidth: 2 - [\rLF] - Gen<Markup> - SpanEditHandler;Accepts:Any\n            NewLine;[\rLF];\n        MarkupTextLiteral - [73..74) - FullWidth: 1 - [}] ...
```

Code snippet for repro:
```
@functions{
    public void SomeOtherMethod()
    {
        <
    }
}
 
@code {
    private bool _collapseNavMenu = true;
 
    private string NavMenuCssClass => _collapseNavMenu ? "collapse" : null;
 
    private void ToggleNavMenu()
    {
        _collapseNavMenu = !_collapseNavMenu;
    }
}
```

**Comment by ajaybhargavb** [comment]
This is by design. See [here](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs#L975). We parse the start tag until we see another `>` or `<`. Given that our attribute area can have C# in there, we can't really have other characters be part of the `IsEndOfTag()` condition unless we want to break a lot of other assumptions.

**Comment by TanayParikh** [comment]
So to confirm, we aren't able to add the newline character to `IsEndOfTag()` because of the following (valid?) case?

```
<textarea @code {
var x = foo;
} ></textarea>
```

While the parser recognizes the above case as valid, the following doesn't seem to be allowed:
```
<@code {
    var x = foo;
} textarea></textarea>
 ```

The following isn't a valid HTML `<textarea>` tag either.
```
<
  
textarea></textarea>
```

**Comment by ajaybhargavb** [comment]
Even without C# being involved, we can't use newline as a terminating char because we could have cases like,
```html
<a href="/asdf"
     class="foo"></a>
```

With C# things get even more complicated. I'm sure there could be some cases where we could add some complex logic to detect this doesn't make sense to be a multiline tag but that would add unnecessary complication and make it more bug prone. I am usually wary of touching the parser unless there is a very obvious bug as it is a hot path and could very easily cause a crash.

```html
<
textarea></textarea>
```

In this above case, `textarea` will be considered as an attribute for a tag that has no name (also by design).
