### ISSUE TITLE
Add more using directives in Program.cs in Blazor WebAssembly projects

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#20841]
We should consider adding using directives in Program.cs for Blazor WebAssembly projects that we currently have in Program.cs for ASP.NET Core projects.

Namespaces we should consider adding 

- `Microsoft.Extensions.Configuration`
- `Microsoft.Extensions.Logging`

**Comment by captainsafia** [comment]
The `Microsoft.Extensions.Configuration` namespace has already been added as part of https://github.com/dotnet/aspnetcore/pull/20790/files#diff-660770e26f36d04c0c7b0f7a7162fc9fR10.

As for `Microsoft.Extensions.Logging`, we don't currently do any additional configuration in the Program.cs for logging. This was done to reduce the total size impact of the dependencies that would be pulled in for a new template app and there isn't anything to merit having it in the template, IMO.

I think the docs should be enough to help users learn more about the logging changes and how they configure logging in their apps.

I'll close this based on the notes above but let me know if you think otherwise.

**Comment by captainsafia** [comment]
Re-opening since @danroth27 brought up the point that having the Logging namespace will populate Intellisense with LoggingBuilder extension methods which are more useful.

**Comment by captainsafia** [comment]
Closing for real now that #20869 is merged.
