### ISSUE TITLE
Blazor WASM 3.2 Preview 4 Build

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#20936]
When I do a modification to my solution, if I rebuild, the modification is not applied.

I have to clean my solution before rebuild.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

We had a rogue package that we uploaded by error. We've since corrected the issue. You need to clean the nuget package caches and run restore again. You can do so with `dotnet nuget locals --clear all` (note, this will wipe all the nuget caches from your machine, alternatively you can go to the ~/.nuget\packages and remove the Microsoft.AspNetCore.Components.WebAssembly.Build package and restore again)

**Comment by javiercn** [comment]
If you still have issues after following the guidance, comment on the issue and we'll reevaluate it.
