### ISSUE TITLE
Asp.Net Core SignalR on Blazor Server-Side never calls OnDisconnectedAsync

### ISSUE THREAD

**Issue by francescocristallo** [dotnet/aspnetcore#20932]
### Describe the bug

 OnDisconnectedAsync is never called when using Asp.net Core SignalR with Blazor Server-Side

### To Reproduce

https://github.com/francescocristallo/BlazorAppServerChat

Launch the app, open two tabs, the chat works.
When closing one of the browsers/tab, OnDisconnectedAsync is not called.

The same code calls OnDisconnectedAsync if used with Blazor Webassembly (Client Side)

### Further technical details

ASP.NET Core 3.1 on Visual Studio Professional 2019

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

**Comment by SteveSandersonMS** [comment]
Hub connections are disposable, and you do need to dispose them when you're finished with them. Blazor components get disposed when the user navigates away or terminates their connection. So, to avoid problems you should add code to your `Index.razor` component similar to the following:

```razor
@implements IDisposable

... rest of component code ...

@code {
    public void Dispose()
    {
        _hubConnection.DisposeAsync();
    }
}
```

As you can see, one oddity with this is that currently Blazor doesn’t support `IAsyncDisposable`, so the call to `DisposeAsync` isn't awaited. Adding `IAsyncDisposable` is tracked in #9960

Note that this isn't just for Blazor Server. You also need to dispose your hub connection on Blazor WebAssembly if it lives within a single component like yours does. Otherwise if the user keeps navigating back and forth between `Index.razor` and other components, you'll still be accumulating undisposed hub connections.
