### ISSUE TITLE
Unclear/incomplete instructions in docs on extending claims for a Blazor webassembly 3.2.0 Preview 4 app

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#20970]
I have a Blazor webassembly 3.2.0 Preview 4 app using In-App accounts and I am attempting to follow [this ](https://github.com/dotnet/AspNetCore.Docs/issues/17650) guide to add user's first name to the token and display it as one of the claims on the client app.

1. The guide says 

> Create a class YourAccount that extends the Account class

There is no Account class that I can find. The default project has an ApplicationUser class instead, which I extended like so:
```
public class ApplicationUser : IdentityUser
    {
        public string FirstName { get; set; }
    }
```
2. I migrated these changes to the database, registered a new user, and verified the user record has FirstName populated in AspNetUsers table
3. The guide then suggests:
> Create a class YourUserFactory that extends AccountClaimsPrincipalFactory<YourAccount>

It's not clear what package to reference to get AccountClaimsPrincipalFactory. Instead I found UserClaimsPrincipalFactory, which I have used to create my factory like so:
```
public class MyCustomUserClaimsPrincipalFactory : UserClaimsPrincipalFactory<ApplicationUser>
    {
        public MyCustomUserClaimsPrincipalFactory(
            UserManager<ApplicationUser> userManager,
            IOptions<IdentityOptions> optionsAccessor)
                : base(userManager, optionsAccessor)
        {
        }

        public override async Task<ClaimsPrincipal> CreateAsync(ApplicationUser user)
        {
            var initialUser = await base.CreateAsync(user);
            if (initialUser.Identity.IsAuthenticated)
            {
                ((ClaimsIdentity)initialUser.Identity).AddClaim(new Claim(ClaimTypes.GivenName, user.FirstName));
            }

            return initialUser;
        }
    }
```
4. Finally, the guide suggests to register the factory like this:

> services.AddApiAuthorization<RemoteAuthenticationState, YourAccount>()
>     .AddUserFactory<RemoteAuthenticationState, YourAccount, YourUserFactory>();

I do not find AddApiAuthorization extension method on services collection, and I am not sure what RemoteAuthenticationState is referring to. Instead, what I have in the Startup.cs is this:

`services.AddIdentityServer().AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

and I cannot call AddUserFactory after the AddApiAuthorization, as there is no such extension method.

Kindly provide clear, step by step instructions on how to add a property to a claim and have it be shown on the client web app. Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for bringing these up.
@guardrex can you please make the necessary additions to the docs to avoid the confusion here? Thanks!

**Comment by guardrex** [comment]
Yes, but it's not a doc at this point. It's just on a PR (https://github.com/dotnet/AspNetCore.Docs/pull/17653) right now directly from Javier's notes. I've marked it `DRAFT` until I can add the missing instructions, which I'll work out tomorrow (Saturday) morning.

**Comment by mkArtakMSFT** [comment]
> 
> 
> Yes, but it's not a doc at this point. It's just on a PR ([dotnet/AspNetCore.Docs#17653](https://github.com/dotnet/AspNetCore.Docs/pull/17653)) right now directly from Javier's notes. I've marked it `DRAFT` until I can add the missing instructions, which I'll work out tomorrow (Saturday) morning.

No need to work on Saturday. Keep it for Monday.

**Comment by guardrex** [comment]
*Toooooo late!* 😁 I've worked it out ... Javier made me work for it on that one a bit.

I'll have a fix-up commit for the docs PR shortly.

**Comment by guardrex** [comment]
Well ... it was looking nice there for a sec ...

https://github.com/dotnet/AspNetCore.Docs/pull/17895/files

Namespaces look good, and nothing throws at runtime, **_BUT_** it doesn't seem to be actually running the custom factory in my MSAL-based Azure AD standalone test app. Nothing happens either if I give `AuthenticationMethods` some values or even if I just try to set a claim right on the user ...

```csharp
((ClaimsIdentity)initialUser.Identity).AddClaim(new Claim("testclaim", "testvalue"));
```

The changes to what [@javiercn provided (dotnet/AspNetCore.Docs #17650)](https://github.com/dotnet/AspNetCore.Docs/issues/17650) (in my Azure AD standalone app) are ...

* Add the `Microsoft.AspNetCore.Components.WebAssembly.Authentication` package.
* Base `YourAccount` (I'm calling that `UserAccount` in my app and on the PR) on `RemoteUserAccount` instead of "`Account`," which doesn't seem to be a thing.
* In the factory ...
  * `OidcAccount` becomes `YourAccount` (`UserAccount` in my app and in the PR). I can't find anything called "`OidcAccount` ... and it doesn't make sense given that the `AuthenticationMethods` prop is on (his) `YourAccount`.
  * `CreateUserAsync` returns `initialUser`. `CreateUserAsync` insists on it.

AFAIK, this is a client-side WASM scenario. @bancroftway has angled all of their effort server-side in a hosted setup :point_up:. My intention is to place this in the *Additional Scenarios* topic for Blazor WASM, and this should work in all client-side scenarios. Correct me if I'm headed down the wrong path here ... or if this won't play well with MSAL ... or etc.

**Comment by javiercn** [comment]
@bancroftway look at the code from our tests.

Implement a class like this one:
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/PreferencesUserFactory.cs#L14-L60

(You can use RemoteUserAccount, no need for your own custom account class unless you want to) and then register it on DI https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Program.cs#L20

**All these happen in the Blazor Wasm (client) project** if you are customizing the user from ASP.NET Core identity, you need to follow the guidance from identity and Identity Server to customize the user and flow that data to the client.
