### ISSUE TITLE
DisplayName in core3.0 Compilation fails

### ISSUE THREAD

**Issue by zhaoyingju** [dotnet/aspnetcore#21007]
DisplayNamein core3.0 Compilation fails
![_20200420142048](https://user-images.githubusercontent.com/5696447/79719985-49db9a00-8312-11ea-902d-83112a7d4b4d.png)

**Comment by javiercn** [comment]
@zhaoyingju thanks for contacting us.

Seems like your project might not be correctly setup. I would suggest you check the [migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio) if you are upgrading from an old MVC version or provide a minimal repro project that demonstrates the issue if you are creating a new project, as well as details about your environment so that we can help you out.
