### ISSUE TITLE
[Question] Blazor WASM: IdentityServer4 and gRPC JWT Bearer Tokens

### ISSUE THREAD

**Issue by JeepNL** [dotnet/aspnetcore#21009]
.NET Standard 2.1
.NET SDK 5.0.0 Preview 2
Blazor WebAssembly 3.2.0 Preview 4
Visual Studio Community Edition 16.6.0 Preview 3.0

For my Blazor WASM project I'm using @JamesNK [gRPC Ticketer sample](https://github.com/grpc/grpc-dotnet/tree/master/examples/Ticketer) to protect the server's gRPC services against unauthorized access. The user does not need to login for this, the server responds only to authorized calls originating from the Blazor client.

Now I've added IdentyServer4 to the Blazor WASM project (new Visual Studio Blazor WASM hosted project with individual authentication template*) but I can't get those two to work at the same time. It does work if I implement one of them at the time.

*_New WASM 3.2.0 Preview 4 Template:_ `Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview4.20210.8`

What I want is to protect the servers gRPC services without user authentication, and to use IdentityServer4 for user authentication at the same time. 

I think I've narrowed the problem down to these 2 parts of code in (one) Startup.cs; 1) Ticketer Sample 2) IdentyServer4. 

Any tips/links on how to do this would be very much appreciated. 

1) **Startup.cs** (_Ticketer Sample_)

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
	.AddJwtBearer(options =>
	{
		options.TokenValidationParameters =
			new TokenValidationParameters
			{
				ValidateAudience = false,
				ValidateIssuer = false,
				ValidateActor = false,
				ValidateLifetime = true,
				IssuerSigningKey = SecurityKey
			};
	});
```

2) **Startup.cs** (_IdentityServer4, Blazor WASM Hosted Indentity Template_)

```
services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = false)
	.AddEntityFrameworkStores<ApplicationDbContext>();

services.AddIdentityServer()
	.AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

services.AddAuthorization(options =>
{
	options.AddPolicy(JwtBearerDefaults.AuthenticationScheme, policy =>
	{
		policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme);
		policy.RequireClaim(ClaimTypes.Name);
	});
});

services.AddAuthentication().AddIdentityServerJwt();
```

**Comment by javiercn** [comment]
@JeepNL thanks for contacting us.

I'm not exactly sure I understand all the details of what you are trying to do here and I don't think we can give you an answer with just the details that you posted in this issue. Could you provide a minimal repro project so that we can take a look and help you out?

**Comment by chassq** [comment]
Hopefully not to confuse @JeepNL 's issue but I think we might have the same or similar question. We are running:
VS 2019 Version 16.6.0 Preview 3.0,
Dotnet SDK 3.1.300-preview-015095
Blazor WebAssembly 3.2.0 Preview 3.20168.3
Microsoft.AspNetCore.ApiAuthorization.IdentityServer 3.1.0

We have basically 3 projects:
1) wasm hosted blazor client - From the Hosted wasm template with user accounts configured.
2) wasm client server (host) - From the Hosted wasm template with user accounts configured.
3) Api project - Added to the solution and setup to be the WeatherForecast endpoint much like the wasm client server (host)  project. Configured CORS and etc.

We want to have the blazor client user to be able to hit the API WeatherForecast endpoint and be authorized much like the wasm client server (host) project. We have looked at much of the documentation under https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1 but have not found a configuration that works. Its almost like we want to call var tokenResult = await AuthenticationService.RequestAccessToken(); in FetchData.razor and point it to the API project OR Tell the API project somehow that the wasm hosted project (that creates the bearer token)
[Sample.zip](https://github.com/dotnet/aspnetcore/files/4503384/Sample.zip)
 is a valid authority and should accept tokens from it. See attached code sample set up we are trying to use. The project is not runnable in its current state because we have been toying around with it but it will give you a basic structure.

Any input is welcome! Thank you!

**Comment by JeepNL** [comment]
@javiercn I hope I do better with this post.

I start with a new Visual Studio solution with the default template for a Blazor Web Assembly Hosted App with Authentication/Individual User Accounts (IdentityServer4 v3.0.0.0). The results in 3 projects: WASM Client / Kestrel Hosted Server / Shared. 

This (.NET Core 3.1 default Visual Studio Template) works out of the box. User registration and login, authentication and authorization. Also with .NET 5 preview 2.

Now for database & api access I want to use gRPC services. I'm using code from two sample projects from JamesNK 1: [gRPC Blazor](https://github.com/grpc/grpc-dotnet/tree/master/examples#blazor) and 2: [gRPC Ticketer](https://github.com/grpc/grpc-dotnet/tree/master/examples#ticketer) to use with this Blazor WASM solution.

_About Ticketer:_
> The ticketer shows how to use gRPC with authentication and authorization in ASP.NET Core. This example has a gRPC method marked with an [Authorize] attribute. The client can only call the method if it has been authenticated by the server and passes a valid JWT token with the gRPC call.

So I would like user authentication/authorization (Default VS Hosted WASM Template) and what Ticketer does: gRPC services authentication/authorization. What I'm trying to do is use both in the same Server Project, in the same Startup.cs. On one instance of Kestrel (server).

If I separate the Identity and gRPC auth functionality, make 2 solutions of them, both are working (not with each other at the same time, but as stand alone solutions). When I combine them into one solution I get 'unauthorized' (invalid bearer token) error when accessing the gRPC services.

**Comment by JeepNL** [comment]
I have to close this issue because with "Blazor WebAssembly 3.2.0 Preview 4" I've more problems. It looks like it (_the wasm client_) doesn't get the correct configuration settings from appsettings anymore.

My development server is receiving the production server's data. It suddenly ignores appsettings.Development.json (in client's wwwroot) I think my env. (debug) variable (ASPNETCORE_ENVIRONMENT) is okay. (Development). No, I know it's okay: `#if DEBUG` works. Now, it's is very possible I'm doing something wrong again. I've to look into this as well. People better ignore me, I feel ashamed, and I'm sorry.

But does this still work in Preview 4? (_it took me 2 days to find out, my prod. db is a copy of my dev. db_), I didn't notice it, and because of gRPC authorization error I deleted the [Authorize] attribute in the server's gRPC service. That's why I raised this issue.

[_Blazor WebAssembly 3.2.0 Preview 3_](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/):
> Blazor WebAssembly apps now have built-in support for loading configuration data from appsettings.json and environment specific configuration data from appsettings.{environment}.json.

Furthermore, I'm separating the gRPC services into a dedicated gRPC server, not using the Identity server for those services. (now I don't know if this is necessary anymore but I like it more anyway, _I think_)
