### ISSUE TITLE
Cannot override request-id header

### ISSUE THREAD

**Issue by karlra** [dotnet/aspnetcore#21012]
### Describe the bug
I'm sorry if this message comes across as angry but I've wasted so much time on this, and it was due to behaviour completely out of my control and with zero documentation or common sense behind it.

I have just spent all day trying to get a third party API working.

This API requires each HTTP request to have a GUID sent to it in a header called request-id. It's an old api from a very large company and cannot change under any circumstances.

No matter what I did, it would give me errors saying that my header was not a valid GUID, even though I set it properly, i.e. 

`
var content = new StringContent(request, Encoding.UTF8, "text/xml");
content.Headers.Add("Request-Id", Guid.NewGuid().ToString());
`

After a huge amount of stress, I finally realized I needed to install a local HTTP proxy to understand what was really going on. It was then that I found out that ASP.net Core automatically sends a request-id header which it uses to track requests, presumably for telemetry purposes.

For anyone reading this after pulling their hair for hours and hours like I did, ASP.net core adds a request-id header which looks like this: 

request-id: |4cd8db05-4d8bd2e718e666ed.2.

Now for the big problem. If, in code, if I set the request-id header to a custom value like shown above, it doesn't overwrite. Instead, it becomes:

request-id: |7c98b031-4d1c90b53d1aa587.2., cccf84f1-ddfb-4a6f-aceb-a14b5aa1dad2

(the GUID is my custom header value).

After some googling, I then found @davidfowl answering how to get rid of the header here:
https://github.com/dotnet/aspnetcore/issues/19044

My questions:
1. Why is this header named something so extremely generic like "request-id", and not "ms-tracking-request-id" or similar? This bit me hard, caused a huge amount of confusion, stress and lost time and I can only imagine how many other APIs use the same header name.

2. Why, when I explicitly set the header myself, does it not completely overwrite the header, as you would assume? Is there any other situation when the API behaves this way?

3. How is anyone but an extremely senior dev supposed to debug and find this issue? Anyone who doesn't realize it is possible to use a local proxy would find this completely impossible to solve. Would it even be possible to solve like this had the API been HTTPS?

4. Why is this extremely confusing behaviour NOT DOCUMENTED on HttpClient's manual page?

5. It is my understanding that this would not happen if I did this in a console project. How is it possible that ASP.net takes over the provisioning of HttpClient when I just do var x = new HttpClient();? How does it make any sort of sense that the behaviour of HttpClient changes and that code risks not working depending on what project type it is?

6. In what universe is it OK to post data that I didn't explicitly ask for to a remote location????

**Comment by davidfowl** [comment]
> Why is this header named something so extremely generic like "request-id", and not "ms-tracking-request-id" or similar? This bit me hard, caused a huge amount of confusion, stress and lost time and I can only imagine how many other APIs use the same header name.

This is our bad. The header was defined since .NET Core 2.1 as part of a distributed tracing effort.

> Why, when I explicitly set the header myself, does it not completely overwrite the header, as you would assume? Is there any other situation when the API behaves this way?

Are you saying that when you set the "Request-Id" header on the outgoing HttpRequest (from with an ASP.NET Core project) that it appends to the current header? I wouldn't expect that.

> How is anyone but an extremely senior dev supposed to debug and find this issue? Anyone who doesn't realize it is possible to use a local proxy would find this completely impossible to solve. Would it even be possible to solve like this had the API been HTTPS?

It should be documented. 

> Why is this extremely confusing behaviour NOT DOCUMENTED on HttpClient's manual page?

Agreed... This is the only doc I currently know of:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md

> It is my understanding that this would not happen if I did this in a console project. How is it possible that ASP.net takes over the provisioning of HttpClient when I just do var x = new HttpClient();? How does it make any sort of sense that the behaviour of HttpClient changes and that code risks not working depending on what project type it is?

ASP.NET Core creates an Activity that represents the request by default. This is what tells HttpClient to send an outgoing request id header. You can disable it in a couple of ways:
- By setting the current activity to null before making the request (Activity.Current = null)
- By setting the environment variable `DOTNET_SYSTEM_NET_HTTP_ENABLEACTIVITYPROPAGATION` to "false" or "0".
- By the AppContext switch `System.Net.Http.EnableActivityPropagation` to false

> In what universe is it OK to post data that I didn't explicitly ask for to a remote location????

It's part of an effort to make distributed tracing work by default in ASP.NET Core. It unfortunate the lack of documentation in this area, we'll need to fix that.

cc @noahfalk @shirhatti

**Comment by karlra** [comment]
> Are you saying that when you set the "Request-Id" header on the outgoing HttpRequest (from with an ASP.NET Core project) that it appends to the current header? I wouldn't expect that.

Yes, that's what it is doing.

**Comment by karlra** [comment]
I get that tracing is important but why does this have to result in data being sent to a third party, who knows nothing about the implementation details on the requester's side? It is totally unexpected and the fact that such a basic library changes its behaviour depending on the project type is frankly nuts.

**Comment by karlra** [comment]
Also, your proposed solution of setting Activity.Current to null does work but just looking at code like that makes one wonder if setting a static property like that is thread safe or not. I get that it probably is, since you suggested it, but how is a reviewer or reader of this code supposed to know?

**Comment by davidfowl** [comment]
> I get that tracing is important but why does this have to result in data being sent to a third party, who knows nothing about the implementation details on the requester's side? It is totally unexpected and the fact that such a basic library changes its behaviour depending on the project type is frankly nuts. If this was opt-in then sure, but opt-out......

That's fair, but we went with an opt-out model so that the "it just works when I call my other ASP.NET Core app or backend that supports the new W3C trace context" is on by default. I appreciate the fact that this is poorly documented and that you basically have to now turn it off at all of the places where you don't want it to propagate. 

The behavior is such that when there's a current activity HttpClient will propagate the id to the remote party:
- By default ASP.NET Core creates an activity (this can be disabled)
- You can create an activity on your own.

> Also, your proposed solution of setting Activity.Current to null does work but just looking at code like that makes one wonder if setting a static property like that is thread safe or not. 

It's an async local, so a magical static that only affects the current execution context. 

> I get that it probably is, since you suggested it, but how is a reviewer or reader of this code supposed to know?

With docs, the ones that we need to add 😄 .

**Comment by karlra** [comment]
Ok. I mean, I hear what you're saying, but for the record I think it is a very bad strategy to start relying on "magical statics" instead of having per-request settings. The ability to use general programming knowledge to understand the code's behaviour goes out the window and instead you need detailed understanding of all the platform gotchas.

**Comment by davidfowl** [comment]
> Ok. I mean, I hear what you're saying, but for the record I think it is a very bad strategy to start relying on "magical statics" instead of having per-request settings.

Magical statics are indeed the worst. Unfortunately there is this one thing they are useful for, ambient context that you want to attach to further API calls like fly paper. Of course that's a double edged sword...

**Comment by forik** [comment]
I also faced with Activity/Request-Id related problem. Seems like an established websocket connection preserves a correlation context (not saying Activity intentionally), such as any http call made through typed HttpClient attaches the same Request-Id, eventhough I set Activity.Current = null explicitly. 

Please see [#1797](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1797)
