### ISSUE TITLE
Committing a C# completion in an explicit expression makes it an implicit expression

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21154]
![image](https://i.imgur.com/WgXRATe.gif)

**Comment by ajaybhargavb** [comment]
This is possibly because the completion box opened when `@` was typed and it stayed there while we typed `(` and `Date`. I think this is because they don't consider `(` as a dismiss character https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FCompletion%2FAsyncCompletionCommitManager.cs&version=GBdevelop&line=180&lineEnd=181&lineStartColumn=1&lineEndColumn=1&lineStyle=plain. Not sure how we can control that behavior outside there. We might need a change in that code.

**Comment by NTaylorMullen** [comment]
> I think this is because they don't consider `(` as a dismiss character

Oh super interesting. That's a tough one because technically C# wants to have `(` as a commit character so you can commit method items. Sooo having it as a dismiss character isn't entirely correct either. This is an interesting example where you almost want to programatically decide when `(` should commit or dismiss completion.

In VSCode today this mostly works because C# takes a little bit of time to come back with completion items so by the time they've come back a user has already written `(`. Also I believe O# uses "insertText" instead of TextEdits to apply the completion item so you maintain the parenthesis. 

Assuming we can't change the LSP spec (because that'd be the "right" place to fix this) the best fix for this is probably somewhere inbetween. C# would have `(` as a commit character and by the time the C# completions come back we attempt to re-write TextEdits that would consume the `(` to use `insertText` instead. That's just an idea though. This at the very least probably warrants an MS-LSP discussion since it's a super interesting case.
