### ISSUE TITLE
Blazor Webassembly can not debug with Visual Code

### ISSUE THREAD

**Issue by hieuluong1989** [dotnet/aspnetcore#21166]
I tried to set up debugging of Blazor Webassembly following this document.
https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#visual-studio-code

### Describe the bug
When I press **Debug (Blazor StandAlone)**, it does not handle my break point. My breakpoint was not red, it was circle with grey color.

![image](https://user-images.githubusercontent.com/52130197/80174680-53287780-862e-11ea-8cb3-88c7e13f8726.png)
![image](https://user-images.githubusercontent.com/52130197/80174698-66d3de00-862e-11ea-92fc-faafb7e730e2.png)

### To Reproduce
1. Create new blazor webassembly
2. Open visual code, install extension C# and JavaScript Debugger (Nightly), check checkbox **Use the new in-preview Javascript debuger for Node.js and Chrome**
3. Add the required assets to the app for building and debugging. Select Yes:
4. updated, the launchSettings.json
5. Set breakpoint on razor file
6. Start debug **Blazor StandAlone**, Start debug **Blazor Webassembly in Chrome**

### Further technical details
- dotnet core: 3.1.201
- Microsoft.AspNetCore.Components.WebAssembly.Templates: 3.2.0-preview4.20216.8
- C# extension: 1.21.17 (current)
- JavaScript Debugger (Nightly): 2020.4.2317 (current)
- Chrome: Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please try to debug in browser and see whether that works?

**Comment by SteveSandersonMS** [comment]
Instructions for debugging in the browser are here: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-in-the-browser

**Comment by hieuluong1989** [comment]
It worked with debugging in the browser. This is my dotnet info:
![image](https://user-images.githubusercontent.com/52130197/80561565-df1c1400-8a1f-11ea-99bf-0ba19ad39fb0.png)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen what can we collect to be able to investigate this issue?

**Comment by NTaylorMullen** [comment]
@hieuluong1989 Could you set the setting `trace: true` in the `launch.json`  pwa-chrome configuration. It'll cause the extension to capture verbose logs. The file location will be printed to the debug console, sharing that should shed some light.

**Comment by hieuluong1989** [comment]
@NTaylorMullen: This is the logs of ms-vscode.js-debug-nightly 

[vscode-debugadapter-0.json.txt](https://github.com/dotnet/aspnetcore/files/4584526/vscode-debugadapter-0.json.txt)

**Comment by alderic** [comment]
the same issue, can't load symbols. 
By default in the launch.json "url": "https://localhost:5001" 
In this link indicates [https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/](url) that you can use http and https. 
I change my url to http://localhost:5000 and debug work fine.
mb this is due to the fact that I do not have a certificate on localhost:)

**Comment by mkArtakMSFT** [comment]
@captainsafia reassigning this to you as you've taken this over.

**Comment by captainsafia** [comment]
> the same issue, can't load symbols.
> By default in the launch.json "url": "https://localhost:5001"
> In this link indicates https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/ that you can use http and https.
> I change my url to http://localhost:5000 and debug work fine.
> mb this is due to the fact that I do not have a certificate on localhost:)

Correct. This issue occurs because you haven't trusted your local development certificates yet. [These docs](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems) have more information on how to resolve this problem.

> @NTaylorMullen: This is the logs of ms-vscode.js-debug-nightly

Can you share your `launchj.json`? From these logs, it looks like you might be working on a nested project which requires some additional configuration to map the sourcemaps correctly.
