### ISSUE TITLE
Optional client certificates

### ISSUE THREAD

**Issue by FDonald** [dotnet/aspnetcore#21193]
# Issue Title

404 when set location path security

# General
I am developing a net core 3.1 web application. One of authentication schemes is Certificate, so I want to protect a page with client certificate authentication. This is Web.config IIS configuration (Obviously i set <section name="access" overrideModeDefault="Allow" in solution applicationHostConfig ):

 ```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44300" />
          <environmentVariable name="COMPLUS_ForceENC" value="1" />
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
  </location>
  <location path="certificate/login">
    <system.webServer>
      <security>
        <access sslFlags="Ssl,SslNegotiateCert,SslRequireCert" />
      </security>
    </system.webServer>
  </location>
  <system.webServer>
    <security>
      <access sslFlags="Ssl" />
    </security>
  </system.webServer>
</configuration>
```
Application starts successfully, and when I call localhost://33400/Certificate/login, browser show certificate page handshake correctly, I choose a certificate and ... IIS surprise me with 404 Static File Handler! All others pages work perfectly.
This approach worked well with net Core 2.2.

**Comment by anurse** [comment]
Requiring a certificate for a specific path is not likely to work since certificates are negotiated _per-connection_, so the first request on a connection will negotiate the cert and further requests generally won't be able to change it.

Adding @Tratcher for thoughts.

> This approach worked well with net Core 2.2.

That surprises me. Can you provide a runnable sample that reproduces the problem?

**Comment by FDonald** [comment]
Thanks for your answer.
This is my POC with two project, SampleMVC  target aspnetcore3.1 and SampleMVC2.2, target aspnetcore2.2.
Both of them have a "protected path " with location path security setting in Web.config.
If you navigate at https://localhost:port/home/privacy can check that  SampleMVC2.2 work perfectly and SampleMVC return a 404.
It seem that new IISExpress with netcore3.1 not recognize this configuration, looking at traces try all modules (IsapiFilterModule, ApplicationInitializationModule, WebSocketModule, ConfigurationValidationModule, httpRedirectionModule, ....) but not AspNetCoreModuleV2, so ends with staticFile and 404  
[CertificateTest.zip](https://github.com/dotnet/aspnetcore/files/4556795/CertificateTest.zip)

**Comment by FDonald** [comment]
P.S. You need a valid certificate installed in certificate personal store to try it!

**Comment by Tratcher** [comment]
`<location path="certificate/login">` is setting up a separate virtual directory that's not part of the main application, so the 404 makes sense there. Not sure how 2.2 would behave differently, we'll have to investigate that.

There's a long related discussion on scoping client certs here: https://github.com/dotnet/aspnetcore/issues/18064

**Comment by FDonald** [comment]
Thanks Tratcher. 
I don'r understand why I can`t use this feature, it`s working since Framkework 3.5!
Howecer if isn't possible, how I could authorize a user with a client certificate?
I am working in a gobernment team to develop authorizations system, and this is a must to authorize external citizens for internet managements.
We have several authentication services so, we cannot protect entire site with certificate.
We need browser negotiation in a path, so browser can show local certificates., and after autorization succed, return at original page.

**Comment by Tratcher** [comment]
Honestly I'm not sure how it ever worked in .NET 3.5. Client certificates are a TLS feature, not an HTTP feature, they need to be negotiated at the start of the connection before any HTTP data is available, only the host name (SNI) is known at that point.

There is one alternate mechanic called renegotiation. It allows a client or server to pause a TLS connection and renegotiate the encryption, including providing a client certificate. 
- This is the only mechanic available that might work for the above scenario, but I didn't think IIS exposed this feature.
- Renegotiation can cause deadlocks for POST requests if the TCP window is full.
- Renegotiation has been prohibited for HTTP/2. This may also be part of your issue since HTTP/2 is enabled by default in IIS and many clients now.
- The client cert would then be present for all subsequent requests, there's no way to sign out.

We've been discussing an alternative that uses subdomains rather than paths to set up sections of a site that require client certificates. I haven't put together a working example yet though. Here's the theory:
- You set up bindings for my.domain and clientcert.my.domain on the same site. The base site doesn't require a client cert but the subdomain does.
- If you get to a part of the site that requires a client cert and doesn't have one, you redirect to the same page using the clientcert.my.domain host.
- Since it's a different host name the client will establish a different connection and the client cert will be provided.
- To sign out you redirect back to the my.domain version of the site with a connection: close header to close the old connection behind you.

**Comment by anurse** [comment]
Triage: As @Tratcher indicated, we don't really have action we can take here. Client certificates are negotiated on the connection level and in a situation where there is no path data available (during TLS handshaking). Renegotiation may have worked in the past but is prohibited in HTTP/2 (regardless, that would be an IIS issue, not an ASP.NET Core issue).

Moving to discussions since there's no actionable work at this time.

**Comment by FDonald** [comment]
I will try the @Tratcher proposal, with subdomain. It's this the best way to redirect to subdomain? https://docs.microsoft.com/es-es/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-3.1

**Comment by Tratcher** [comment]
@FDonald that's one option. It could also be done through custom middleware, or maybe even through authentication events.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1

Are you using the 3.1 CertificateAuthentication handler to handle authenticating with the certificate?
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1

**Comment by FDonald** [comment]
Yes @Tratcher I use  the 3.1 CertificateAuthentication handler, in external service that is  protected by certificate client autentication. 
Actually, to move forward, I did a redirect to this service (via browser) to obtain a certificate, parse and return data to main app.
This work, but I prefiere obtain a certificate in Main app, open a back channel to autentication Service via HttpClient, parse data and return to main app.
This approach also allow me to not publish the authentication certificate service outside LAN

**Comment by Tratcher** [comment]
I was going to recommend the cert auth handler events, but it looks like we didn't include a Challenge event for that one because it doesn't normally support challenging. Might need to get more creative.

You could define a custom auth handler that implements challenge to redirect, and configure  the cert auth handler to forward Challenge to it.

**Comment by FDonald** [comment]
Well, my final solution is:

-   Create an indipendent service (may be an Api) to authenticate user via client certificate.

- intercept in router mapping certificate login (Example: certificate/login) and redirect to protected service. This redirect launch browser certificate handshake. 

- Certificate authentication service catch certificate, parse and valide it, and return a post to a main application controller that create a principal user with claims. This may be a security hole, but I protect post data with Dataprotection encryption  and  short duration.

This solution isn't optimal but work. I don't like expose certificate authentication service at internet but I have no other choice.

**Comment by Tratcher** [comment]
@FDonald Glad you got it working. Why did you opt for a separate service vs adding an additional host binding to your existing application? I expect you'd be able to avoid that Post redirect if they were integrated.

**Comment by docmaster2** [comment]
Хорошо я подумаю.07.05.2020, 23:39, "Chris Ross" <notifications@github.com>:
@FDonald Glad you got it working. Why did you opt for a separate service vs adding an additional host binding to your existing application? I expect you'd be able to avoid that Post redirect if they were integrated.

**Comment by FDonald** [comment]
@Tratcher sorry, but I can't see the advantages of subdomain, what's the advantage of using it?
How can I send data or authentication token from subdomain to main application to avoid a post? 
My separate authentication service has same domain with distinct port.

**Comment by Tratcher** [comment]
Triage discussion: Add the Challenge event to the cert auth handler and an in-repo sample (#21484). Vet it with some customers like @brockallen and then write up something for the docs.

**Comment by Tratcher** [comment]
@FDonald using an alternate port accomplishes a similar goal, but ports are something a developer might not have as much control over depending on where they're deployed. Either way the client will use separate TCP+TLS connections for the alternate host+port and you can enforce different client certificate requirements there.

If both hosts are attached to the same application instance then you could do the cert -> user mapping and sign the user in using one step rather than two.

**Comment by treborgero** [comment]
@FDonald I ran into the same issue with the latest .NET Core. 

Please take a look at my web.config. TIP: Make sure you remove the `<location path="." inheritInChildApplications="false">` tag:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<system.webServer>
		<modules runAllManagedModulesForAllRequests="false">
			<remove name="WebDAVModule" />
		</modules>
		<security>
			<requestFiltering>
				<requestLimits maxUrl="8192" maxQueryString="4096" maxAllowedContentLength="512000000" />
			</requestFiltering>
			<authentication>
				<windowsAuthentication enabled="true" />
				<anonymousAuthentication enabled="true" />
			</authentication>
		</security>
		<handlers>
			<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
		</handlers>
		<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess">
			<environmentVariables>
				<environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44397" />
				<environmentVariable name="COMPLUS_ForceENC" value="1" />
				<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
			</environmentVariables>
		</aspNetCore>
	</system.webServer>
	
	
	<!--Security-->
	<location path="api/account/login/pki">
		<system.webServer>
			<security>
				<access sslFlags="Ssl,SslRequireCert,SslNegotiateCert" />
				<authentication>
					<iisClientCertificateMappingAuthentication enabled="true" />
				</authentication>
			</security>
		</system.webServer>
	</location>
	<location path="api/account/register/pki">
		<system.webServer>
			<security>
				<access sslFlags="Ssl,SslRequireCert,SslNegotiateCert" />
				<authentication>
					<iisClientCertificateMappingAuthentication enabled="true" />
				</authentication>
			</security>
		</system.webServer>
	</location>
</configuration>
```
I have no clue what they changed but I got it working this way. Hope this helps!

**Comment by Tratcher** [comment]
@treborgero that doesn't work on HTTP/2 does it? If the first request is to a path other than those listed then you won't get a client cert, and the request to one of those paths would fail because it couldn't renegotiate.

**Comment by treborgero** [comment]
Interesting point. I wonder why it works for me in IIS 10 then? 

Maybe it's an automatic fall back like mentioned here [https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#when-is-http2-not-supported](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#when-is-http2-not-supported)?

This is confusing.

**Comment by Tratcher** [comment]
@treborgero supports both HTTP/1.1 and HTTP/2 via ALPN. You'd have to check the client or server logs to see which was actually used for those requests.

The implication from your "api/" paths is that your clients are programmatic? Are those the same clients accessing the rest of your site or are they different clients? If there's no crossover then it wouldn't be an issue.

**Comment by treborgero** [comment]
Yes. In my case I'm using Angular to programmatically call the certificate authentication path based on conditionals.

For anyone's clarification: I proceed to parse the client certificate in that one call, a claims principal gets temporarily created via a custom handler, and finally a JWT gets created and sent back which is used for further authentication. In conclusion, all further authentication is done via JWT.

Hopefully this helps :)

**Comment by FDonald** [comment]
Thank you very much @treborgero. It work with your suggestion.
Definitively I think is a bug in new Asp.net core config.
Besides the configuration deceive with inheritInChildApplications="false" it's clear that childs inherit.
Well, I will apply your configuration. 
I Attach a simple POC with IIS logs activated to inspect behavior
[SampleMVC.zip](https://github.com/dotnet/aspnetcore/files/4601672/SampleMVC.zip)
