### ISSUE TITLE
Checkbox keep checked, after List Updated and StateHasChanged() method is called

### ISSUE THREAD

**Issue by webebox** [dotnet/aspnetcore#21226]
Hi, I have this code in Blazor :

```
@foreach (var item in list)
{
 <input type="checkbox" @onchange="@(e => HandleCheckChanged(e, item.Name))" checked="@item.IsChecked">
}

private async Task HandleCheckChanged(ChangeEventArgs e, string itemName)
{
   // do something ...
   StateHasChanged();
}
```
if I check a checkbox it calls the HandleCheckChanged and the checkbox is checked
But if I change the list items the previews checked checkbox is still checked and is not updated based on the new list items.

for example suppose that I have a list of ordered numbers {1-20} I follow these steps :
1 : list = GetAll().Where(c => c.Id < 10);
2 : I check the first checkbox (number 1)
3 : list = GetAll().Where(c => c.Id >= 10); (list updated and state has changed)
4 : the problem raises here , checkbox 11 is checked ??? but its value is false
It seems that DOM does not follow the Component's State

**Comment by javiercn** [comment]
@webebox thanks for contacting us.

Several things here, I don't think you need to be calling `StateHasChanged` in your handler. The framework will do that for you automatically. You likely need to use `@key` to have the behavior you want, since otherwise Blazor tries to find the minimal change needed to update the UI and that might not have the effect you expect.

**Comment by webebox** [comment]
Thank you. using @key solved the problem.
