### ISSUE TITLE
Blazor Server, OwningComponentBase with AuthenticationStateProvider 

### ISSUE THREAD

**Issue by kodiex** [dotnet/aspnetcore#21269]
In Blazor Server a OwningComponentBase based Component that requires AuthenticationStateProvider via DI gets an error: "getauthentication state async was called before setauthentication state"

```
public partial class AuthComponent : OwningComponentBase
    {
        
        protected override void OnInitialized()
        {
            SS = (SecurityService)this.ScopedServices.GetService(typeof(SecurityService));
            base.OnInitialized();
        }

[...]

```

```
public class SecurityService
    {
        public SecurityService(AuthenticationStateProvider AuthenticationService)
        {
            this.AuthenticationService = AuthenticationService;
            Console.WriteLine($"** New SecurityService, {Username}");
        }
        private AuthenticationStateProvider AuthenticationService { get; set; }
[...]
```

Standard blazor server project .net Core 3.1 with Individual User Accounts authentication

[BlazorSSAuthTest.zip](https://github.com/dotnet/aspnetcore/files/4542352/BlazorSSAuthTest.zip)

**Comment by javiercn** [comment]
@kodiex thanks for contacting us.

You shouldn't resolve anything that requires the AuthenticationStateProvider within a custom scope, since that will cause a new instance of the AuthenticationStateProvider to be created (which is not correctly initialized).

If you need access to the AuthenticationStateProvider within a service "scoped to a component" I recommend you use [Inject] to get the AuthenticationStateProvider and pass it in to your service within the component as a parameter. That makes sure you get the right instance for each user app instance.

**Comment by kodiex** [comment]
Hi, many thanks for answer. I get it, so is unfeasible to take advantage of DI automatic resolution of dependencies if AuthenticationStateProvider  is one of them, Isn't it?
