### ISSUE TITLE
Move Blazor Server template tests into separate project

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#21293]
The Blazor Server template tests currently rely on Selenium, and as a result cannot be run on Helix. They are currently skipped using the `SkipOnHelix` trait.

Moving these tests into a separate project would allow us to:
- Configure template tests that can run on Helix to only run on Helix and not AzDO
- Isolate the non-Helix tests into a separate project

cc: @HaoK @rynowak

**Comment by HaoK** [comment]
Note: this is sort of a point in time thing too, since I think in the medium term, it's still worth get selenium running properly on helix, I dusted off my old PR and rebased it against master.  See https://github.com/dotnet/aspnetcore/pull/21280 as I don't think its too far away, if you had some cycles to help with the selenium side of things after these have been split off

**Comment by captainsafia** [comment]
Closing this as it has been resolved in #21345
