### ISSUE TITLE
Blazor Webassembly access appsettings from browser url

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#21312]
### Describe the bug
In blazor WebAsembly appsettings is located in wwwroot folder allowing everybody to see it just typing its addres on url bar

### To Reproduce
Just type /appsettings.json on url bar.

![imagen](https://user-images.githubusercontent.com/12015993/80565062-db709900-89ef-11ea-9621-b4b8b4ae97bf.png)

### Further technical details
- Blazor WebAssembly Preview 5.
- Visual Studio 2019 16.6 Preview 4.

**Comment by javiercn** [comment]
@CrahunGit thanks for contacting us.

That's by design, the file needs to be accessible by the browser, like the dlls and everything else on your app. There should be no issue with that as you shouldn't be storing any sort of secret in there (since single page applications can't hold on to secrets safely).
