### ISSUE TITLE
AddOpenIdConnect in ASP.NET Core WebAPI in context auf Angular-SPA ->WebAPI (single domain)

### ISSUE THREAD

**Issue by Tobias-Gr** [dotnet/aspnetcore#21354]
All samples regarding AddOpenIdConnect-middleware seem to target ASP.NET Core MVC. In contrast we have an SPA that accesses a WebAPI. Both are hosted on the same domain. Is it OK to use AddOpenIdConnect-backed cookie authentication on the WebAPI-level in this scenario or what (negative) implications does this have?

Thanks!

**Comment by blowdart** [comment]
If you have a SPA generally we'd recommend JWT tokens rather than cookies, to allow for flexibility and other client types.

However if you know you're never going to write a mobile or desktop app, and you can be sure that all browsers you are going to support have support for SameSite cookies, then yea, you could use cookies if you want, as long as you ensure the cookies are secure (i.e. HTTPS only), http cookies (so you can't access them in a script) and you set the SameSite attribute to be Strict (to avoid CSRF)

**Comment by Tobias-Gr** [comment]
OK, thanks.
