### ISSUE TITLE
Blazor WASM 3.2 preview 5 Timezone file not found

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#21352]
After a release through Azure Devops on our staging environment we get this error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
saas-rc.qualite.xxxxxx.xxxxx/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://saas-rc.qualite..xxxxxx.xxxxx/_framework/wasm/dotnet.timezones.dat' with computed SHA-256 integrity '3B1U2rbsjAD3ATeSdQTk8iLIOV8Qdgtr7s/PqU4IJJ8='. The resource has been blocked.
saas-rc.qualite..xxxxxx.xxxxx/:1 Unknown error occurred while trying to verify integrity.
blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The issue here is that the resource being looked for wasn't found. We will be adjusting the error message to avoid future confusion.

As for the 404, are you saying you are able to publish successfully locally but not when published through Azure DevOps?

Also, can you verify that the timezone file (http://saas-rc.qualite..xxxxxx.xxxxx/_framework/wasm/dotnet.timezones.dat) is on the server?

**Comment by snelgrove** [comment]
I've been having a similar problem, except in my case I get a 500 error (hosted on begin.com, there might be a layer capturing the 404?). I thought this issue might be related to #19796, because I had to make the suggested change to `.gitattributes` to get the correct hash on `blazor.webassembly.*.js`. This fixed the problem for the text (.js) file, but the .dat file remains a problem. I can confirm that dotnet.timezones.dat (and the gz and brotli versions) are present on the server.

I'm using VS 2019 16.6.0 Preview 4 to publish, committing the published app to Github, which is then cloned and deployed on S3 by Begin.com.

**Comment by JulienM28** [comment]
The file is present on the server.
There's is also a gzip and a brotli version of this file.

**Comment by mkArtakMSFT** [comment]
@JulienM28 can you please share more details about how you deploy your app?

**Comment by JulienM28** [comment]
The application is build on a local windows build agent and then deployed on the staging server through a deployment agent. The application is hosted by IIS on a Windows server 2016.

**Comment by pranavkm** [comment]
@JulienM28 is your server configured to support files with the `.dat` extension? The web.config blazor generates [should allow it](https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/Build/src/targets/Standalone.Web.config#L12), but if you were doing something different IIS may disallow the request - https://stackoverflow.com/a/13259953

**Comment by pranavkm** [comment]
@snelgrove have you contacted your hosting provider's support to figure out why a file extension would result in a 500? That seems very unusual.

**Comment by JulienM28** [comment]
Strange, there's no web.config at the root of the hosting directory.
I have a custom one in the project.
It's set on "Content" and "Copy if newer"
But it wasn't published.
I'll try to put it manually on the server.

**Comment by JulienM28** [comment]
It was that.
My web.config was based on an "old" autogenerated web.config and it not contained .dat reference.
It works fine now.

I wonder why the autogenerated web.config is so different of this one : 
https://docs.microsoft.com/fr-fr/aspnet/core/host-and-deploy/blazor/webassembly/_samples/web.config?raw=true&view=aspnetcore-3.1

It's much more complete, use brotli compressed files etc.
