### ISSUE TITLE
Satellite assemblies from shared projects get removed when publishing

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#21406]
This is a degenerate case of https://github.com/dotnet/aspnetcore/issues/19926. 

In a Blazor hosted project, if a shared project has satellite assemblies, they get copied to the the wwwroot, but are removed from the app's publish output.

## Steps to reproduce

1. Create a blazor hosted app
2. Add a Resources.fr.resx to the Shared project
3. Publish the app

Notice that `/publish/wwwroot/_framework/_bin/fr/My.Standalone.resources.dll` exists, but `/publish/fr/My.Standalone.resources.dll` is absent.

**Comment by SteveSandersonMS** [comment]
Glad you suppoted this! I guess it's a bit unusual at least to have the resx be shared between server and client since typically resources relate to a specific bit of UI, and the WebAssembly UI is not the same as the server-executed endpoints.

Do you have a view on whether it's something we can/should try to fix for RTM? Or what workaround we could recommend if not?

**Comment by pranavkm** [comment]
> Do you have a view on whether it's something we can/should try to fix for RTM?

@javiercn would know better, but I believe a non-workaround fix for this needs to come from the RazorSDK. We could fix this in the SDK post 3.2 if we hear a lot of feedback

**Comment by SteveSandersonMS** [comment]
OK. I haven't yet thought of any good (simple) workaround we could suggest to people who hit this as a problem, so let us know if you think of one :)

**Comment by Forestbrook** [comment]
I have my resources in a separate (netstandard2.1) Resource Library project.

Because I want to keep all my translations together, I have bundled them into SharedResource as described in [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization). I understood this is a quite common practice.

I use these resources both in the Api and in the Blazor WebAssembly project.

I would expect that when the Api project references the Resource Library project, the satellite assemblies must be present in the app's publish output. They should ONLY be removed when the Api project does NOT reference the Resource Library project.

**Comment by pranavkm** [comment]
Tried this with the 5.0 SDK and this appears to no longer be an issue. Satellite resources for the shared project appear both in the _framework dir and the publish root directory.
