### ISSUE TITLE
Update Razor generated documents (C#/HTML) with minimal changes

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21407]
Today when we're updating our C#/HTML buffers we replace them wholesale which means our language server pushes the entire buffer down to the client. This is troublesome because it means both C# + HTML need to re-evaluate the entire document. We should be pushing the minimal set of changes down to the client.

**Comment by NTaylorMullen** [comment]
Lets re-evaluate when we want to do this once our dependencies are sorted. @ajaybhargavb lets talk once that happens

**Comment by ajaybhargavb** [comment]
Investigated this. The [Roslyn API](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs#L113) we use to diff our published HTML and C# doesn't actually calculate the true minimal diff and it is by design. I'm looking into if there are other APIs we can use to get the minimal diff. If we don't find anything, we'll need to build our own differ so that we don't send the entire document over the wire on every keystroke.
