### ISSUE TITLE
CORS Header will not send on exception

### ISSUE THREAD

**Issue by grinay** [dotnet/aspnetcore#21450]
Hello. We struggling to understand why application doesn't sen CORS headers in case 500 error. And found that unhandled exception seems to be brakes further pipeline and CORS header will not send. I think no any custom header will not send in response. 

### To Reproduce
My CORS settings is 
            services.AddCors(options => options.AddPolicy("default",
                builder => builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .SetIsOriginAllowed(_ => true)
                    .AllowCredentials()));

Also i have  CustomExceptionFilter : ExceptionFilterAttribute
which handle exceptions which I need. if exception wasn't handle it will pass next to pipe. 

public override void OnException(ExceptionContext context)
{
  if (context.Exception is UserFriendlyException){
     //My handler here
 }
      base.OnException(context);
}

Such a way CORS set correctly. But in case there is any exception that my filter can;t handle, CORS header will not send in response.

**Comment by javiercn** [comment]
@grinay thanks for contacting us.

I'm not sure CORS does anything specific to remove headers from the response specifically, it might be that doesn't get to run before your server/app fails or that something else replaces all custom headers.

That said, there is little value in returning a 500 to the underlying app?

Can you provide more information about your environment? ASP.NET Core version and hopefully a minimal repro project that shows the issue?

**Comment by mjolka** [comment]
@grinay This can be fixed by adding an [exception handler](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-lambda), for example:

    app.UseExceptionHandler(configure =>
    {
        configure.Run(context =>
        {
            context.Response.Clear();
            context.Response.StatusCode = 500;

            return Task.CompletedTask;
        });
    });

I've put together a minimal reproduction of the issue here: https://github.com/mjolka/NoCorsHeadersOnException.

This is sample output from running the example with the exception handler, where the `Access-Control-Allow-Origin` header is present:

```
~$ curl --silent --dump-header - -H 'Origin: http://localhost:4200' -d - http://localhost:5000/weatherforecast/error
HTTP/1.1 500 Internal Server Error
Date: Fri, 08 May 2020 04:34:35 GMT
Server: Kestrel
Content-Length: 0
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Access-Control-Allow-Origin: http://localhost:4200
```

If you remove the calls to `UseDeveloperExceptionPage`/`UseExceptionHandler`, the `Access-Control-Allow-Origin` header won't be present in the response:

```
~$ curl --silent --dump-header - -H 'Origin: http://localhost:4200' -d - http://localhost:5000/weatherforecast/error
HTTP/1.1 500 Internal Server Error
Date: Fri, 08 May 2020 04:37:00 GMT
Server: Kestrel
Content-Length: 0
```

See also: https://github.com/dotnet/aspnetcore/issues/2378
