### ISSUE TITLE
asp-validation-for not working with html tags other than span

### ISSUE THREAD

**Issue by nitishwebgentle** [dotnet/aspnetcore#21462]
I am using model validations in `asp.net core mvc 3.1`. And to display the error message I am using 
`asp-validation-for` attribute.
This attribute works perfectly with the `span` Html tag. But whenever I use some Html tag (like label, small (by bootstrap)) then error message does not work. 
I don't know whether its a bug or a feature request but there should not be any dependency of 
`asp-validation-for` attribute on Html tag. 

### To Reproduce
Suppose I have a model class with a property Title. And I am using _Required_ attribute from _System.ComponentModel.DataAnnotations_.
Then using tag helpers I have an input element for this Title property on view.
If I use span to display error message everything works fine
``` C#
<span asp-validation-for="Title"></span>
```
But if I use small or label etc
``` C#
<small class="text-danger" asp-validation-for="Title"></small>
```
then no message gets displayed on the view.

## Further technical details
- ASP.NET Core 3.1
- The IDE - Visual Studio 2019 professional

**Comment by pranavkm** [comment]
The tag helper specifically targets `span` elements: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.TagHelpers/src/ValidationMessageTagHelper.cs#L17.

**Comment by nitishwebgentle** [comment]
Got it. Then please mark it to feature request as I believe there should not be any dependency like this on html tags.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to provide support for.
You can, however, copy the code and modify it to fit your needs.

**Comment by toddlucas** [comment]
Please consider reopening this and at least applying it to `div` (although `small` would be nice, as it's the default in Bootstrap examples, and thus is likely to be copied a lot--it also makes a sensible alternative to span given the typical use case). I could also see `p` being useful.

The inline nature of this element causes problems with `jquery-validation-unobtrusive` (which is designed specifically to work with this tag helper) since it immediately applies `display: none` to the span with `.field-validation-valid`. This removes any other styles that were applied by sibling classes (like Bootstrap's `.form-text`). In particular, it removes `display: block`. If the `block` display attribute value were intrinsic to the element, we wouldn't have to fight with CSS as much. Thanks!

**Comment by nitishwebgentle** [comment]
I agree with @toddlucas. This should be treated as a priority bug and get fixed.
