### ISSUE TITLE
Kestrel config should be case insensitive

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#21494]
I discovered this issue while working on investigating some of our tests. Essentially Kestrel won't pick up the certificate if the casing doesn't exactly match what it expects. I was observing the issue here

This is the change that I made to our tests:
https://github.com/dotnet/aspnetcore/pull/21493/files#diff-f6ac04d303881c9012a20f9fe4cc2621L73-L75

This is where I think the issue is:
https://github.com/dotnet/aspnetcore/blob/4ebf695a98bcc76343df1f3be76ae583735584e9/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs#L338

This is my reasoning/evidence to argue that this should be case insensitive:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#configuration-keys-and-values

In essence we tell our customers that config is case-insensitive but this piece seems to not be so, so I consider that a bug. The experience is bad because it just doesn't work and you don't get any hint of what's going on.

**Comment by Tratcher** [comment]
Ah, they're stored in a dictionary that is case sensitive by default:
https://github.com/dotnet/aspnetcore/blob/4ebf695a98bcc76343df1f3be76ae583735584e9/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs#L39

**Comment by anurse** [comment]
It would be a breaking change to change the sensitivity, but I do agree with @javiercn here. If we were doing this today (with this new info) we would have made it case-insensitive.

**Comment by Tratcher** [comment]
The config files already are case insensitive, it's only this intermediate lookup table that's sensitive.

**Comment by anurse** [comment]
Yeah, we had some discussion about that in the Triage but I wasn't positive. Given that it should be non-breaking. I'll leave the label on for now as we do the work to make sure we double-check that it's non-breaking.

**Comment by beawolf** [comment]
This will be a breaking change as @anurse said given a scenario for an application using a config like this:

```json
{
  "Kestrel": {
    "Certificates": {
      "MyCertificate": {
        "Path": "<path to .pfx file>",
        "Password": "<certificate password>"
      },
      "mycertificate": {
        "Path": "<path to another .pfx file>",
        "Password": "<certificate password of other certificate>"
      }
    }
  }
}
```

Although I can admit that this scenario is really improbable, but not impossible.

**Comment by javiercn** [comment]
@beawolf every behavior change is a breaking change, but as you mention is way more likely that customers run into the issue described here than it is to fall in the case that you described, and even then, they have an easy fix, which is to use a different config key.

**Comment by wtgodbe** [comment]
@javiercn this seems straightforward enough, but I want to make sure I understand the specifics before I get going - 

https://github.com/dotnet/aspnetcore/blob/b669497be51b3cff683eebdc6abc74098fee4e58/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs#L40-L51

Here we add config entries as defined in the user's config file - presumably the issue is that we don't account for that when comparing against this Dictionary? I see that happening in at least 2 places:

https://github.com/dotnet/aspnetcore/blob/4ebf695a98bcc76343df1f3be76ae583735584e9/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs#L338

https://github.com/dotnet/aspnetcore/blob/4ebf695a98bcc76343df1f3be76ae583735584e9/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs#L365

Do we generally compare against `toLower()`, or do we use another pattern?

I'm also not clear on how the change you linked revealed the bug: https://github.com/dotnet/aspnetcore/pull/21493/files#diff-f6ac04d303881c9012a20f9fe4cc2621L73-L75. Did you make another corresponding change? Is `ASPNETCORE_Kestrel__Certificates__Default__Path` defined somewhere else?

**Comment by Tratcher** [comment]
The Dictionary itself should be created using an OrdinalIgnoreCase comparer.

**Comment by Tratcher** [comment]
Note this was merged into master after branching for preview7. Updating the milestone accordingly.
