### ISSUE TITLE
Extract & encapsulate 'InvokeUnmarshalled' in JSInterop

### ISSUE THREAD

**Issue by majda107** [dotnet/aspnetcore#21492]
After digging deep into these issues:
https://github.com/dotnet/aspnetcore/issues/21426
https://github.com/dotnet/aspnetcore/issues/21444

I've figured out there is a way to invoke unmarshalled js function, making execution many times faster, this comes especially handy if you don't need to encapsulate any objects but only send numeric/string data (like coordinates) speeding up entire thing by so much.

Not something average WebDev may appreciate, but if you need to do something with ~ let's say canvas / js rendering ~ this is a must in order to hit 60fps cap.

**If this gets approved by someone**, I am definitelly **up forking blazor**, doing some nice extraction & encapsulation followed by **submitting merge request**.

You can see **demo usage** of **InvokeUnmarshalled** here...
https://blaze.majdatrpkos.cz/ (multi-selected multiple elements with SHIFT and drag them to test performance)
https://github.com/majda107/blaze-cards

wasn't even able to hit solid 60fps before, and that's only CSS transforms rendering, there are potential ways to hook WebGL bindings and stuff so this may really make sense...

**Comment by pranavkm** [comment]
`InvokeUnmarshalled` is part of Blazor WASM's supported API surface and we recommend using it in specific performance sensitive code paths. It's not entirely clear what it is that you're suggesting here. Related, Mono's JavaScript APIs that allow reading unmarshalled data isn't stable as yet and is likely to change during the 5.0 release. This might affect callsites such as https://github.com/majda107/blaze-cards/blob/3f3f7069100d2d4a6451a3498490eaf45887d150/BlazeCardsCore/wwwroot/blaze-cards/cards.js#L26.

**Comment by legistek** [comment]
> `InvokeUnmarshalled` is part of Blazor WASM's supported API surface and we recommend using it in specific performance sensitive code paths. 

Is there any documentation for how to use it properly? In particular on the Javascript side - such as `BINDING.conv_string`?

And this is probably a noob question, but when we use `InvokeUnmarshalled` and give it, say, an `int[]` or `float[]`, is the Mono runtime still making a copy for JS or is JS getting a direct memory pointer at that point? In other words can we not only avoid JSON serialization/deserialization but also memory copying?

**Comment by pranavkm** [comment]
@legistek there's a small bit of documentation available as part of https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1#use-synchronous-and-unmarshalled-js-interop-apis-where-appropriate. Unfortunately, .NET WebAssembly's JS APIs to consume it aren't fully baked in for this release. You may use it (Blazor does so internally for it's implementation) in performance sensitive areas at the risk of having to rewrite your code if the runtime implementation changes in the future.

> In other words can we not only avoid JSON serialization/deserialization but also memory copying?

The latter, but with caveats. Both JS and WebAssembly share the same memory heap and are are able to read \ write to it. However, a `int[]` or `string` in .NET doesn't have the same representation as a `Uint8` array or a string in JavaScript. Reconstructing these instances over interop might result in additional costs.

**Comment by legistek** [comment]
Thanks @pranavkm! I actually spent a good portion of the weekend doing trial and error and studying the Blazor JS source to figure it out. When I realized that I could just call `Module.setValue` and `Module.getValue` to read and write to shared memory using pointers a whole new world opened up. I quite enjoy it, having cut my teeth on C and Intel Assembly well before .NET existed. :) One has to be meticulous about `struct` layout of course, but I found the way you guys hid the pointer arithmetic inside TypeScript properties quite clever.

I have to say the performance difference is DRAMATIC. I tried building a 10,000-div DOM with a `StringBuilder` and rendering it with `AddMarkupContent` in pure Blazor and it took several seconds  just to do the StringBuilding, then another couple seconds to appear on the browser. I also got a forced, interrupting GC during the render.

As an experiment I tried doing the same thing by sending structured (no strings!) data to JS via `InvokeUnmarshalled`, similar to `RenderTreeFrame`, i.e. commands to tell JS how to manipulate the DOM. The same thing took a fraction of a second and no forced GC.

A few things are therefore clear to me now:
(1) JS-WASM interop isn't inherently slow
(2) JS-WASM interop using large strings is slow and using JSON is ridiculously slow
(3) String building even in pure C# is slow (hopefully will be addressed with AOT)

(2) means that complex DOMs with lots of text, styles, and other attributes are always gonna be slow even with AOT. I think it's worth exploring ways of streamlining the rendering instructions sent from .NET to the JS runtime. For example Instead of building and sending to JS something like `style="position: absolute; width: 500px; height: 200px; left: 50px; top: 50px; border-color: argb(255,128,128,128)"` (100+ characters so 200+ bytes, plus all the string-building required on the C# end, plus the Browser has to parse it anyway) that same information could be distilled down to a data structure of maybe 24 bytes requiring no strings. Then JS could crawl through the structure and build the DOM programmatically like you would do for a custom component.

Even the element name doesn't have to be a string. Blazor could register all element names encountered during the rendering pass and assign them integer values, coordinated with the JS side. Minimize amount of string sharing and parsing. 

Just some thoughts. I think that UI building through .NET and WASM can absolutely work but we might have to be mindful of the metal a lot more than we're all used to in this day and age.
