### ISSUE TITLE
Blazor wasm outputs many empty html comments

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#21526]
Any particular reason blazor wasm outputs so many html comments to the DOM?

![image](https://user-images.githubusercontent.com/1142958/81128310-c1c3da00-8f38-11ea-97db-4f10f743fb08.png)

Or more specifically:
```html
<app><!--!--><!--!--><!--!-->
    <!--!--><!--!-->
            <!--!--><!--!--><!--!--><!--!--><div class="sidebar"><!--!-->
    <!--!--><div class="top-row pl-4 navbar navbar-dark"><!--!-->
    <!--!--><a class="navbar-brand" href="">blazor</a>
    <button class="navbar-toggler"><!--!-->
        <span class="navbar-toggler-icon"></span>
    </button><!--!-->
</div><!--!-->

<div class="collapse"><!--!-->
    <ul class="nav flex-column"><!--!-->
        <li class="nav-item px-3"><!--!-->
            <!--!--><a href="" class="nav-link"><!--!-->
                <span class="oi oi-home" aria-hidden="true"></span> Home
            </a><!--!-->
        </li><!--!-->
        <li class="nav-item px-3"><!--!-->
            <!--!--><a href="counter" class="nav-link"><!--!-->
                <span class="oi oi-plus" aria-hidden="true"></span> Counter
            </a><!--!-->
        </li><!--!-->
        <li class="nav-item px-3"><!--!-->
            <!--!--><a href="fetchdata" class="nav-link active"><!--!-->
                <span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
            </a><!--!-->
        </li><!--!-->
    </ul><!--!-->
</div><!--!-->
</div><!--!-->
```

**Comment by javiercn** [comment]
@benaadams great question!

The reason is because the internal JS algorithm uses them to map the component structure from the Blazor representation to the one in the page.

Comments are needed to avoid introducing artificial elements to delimit the start and end of components.

@SteveSandersonMS can feel free to augment this info or correct me :)

**Comment by SteveSandersonMS** [comment]
Correct. It means the runtime can avoid a lot of work it world otherwise have to do when locating, inserting, and deleting DOM elements. For example, when inserting or deleting a series of sibling nodes between pre-existing siblings, we don’t have to update any indexes relating to the pre-existing siblings since the browser automatically pushes the existing marker nodes along in the list of siblings.
