### ISSUE TITLE
[Blazor] Running Blazor (ASP.NET hosted) app starts browser without extensions

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#21531]
### Describe the bug
When running an ASP.NET Core hosted Blazor WASM app, it launches Chrome in some non-standard mode where extensions are not loaded / passwords are not saved.

### To Reproduce
1: Install a Chrome plugin (Redux DevTools for example)
2: Create an ASP.NET Core hosted Blazor WASM project
3: Run it
4: Start a new instance of Chrome (not just a new tab)
5: Navigate to the same URL
6: Compare the UI of Chrome

Expected: Plugins should be loaded in both
Actual: Plugins are only loaded in the manually started instance

This problem does not exist when creating an ASP.NET Core MVC web app.

### Further technical details
RC1

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

I believe this is because debugging in the browser launches it with a separate profile (and I believe non-debug too). For debugging I believe this is needed/done to avoid polluting your browser profile with test/artificial artifacts.

I don't think we have control over this, since Visual Studio is the one launching the browser, I would suggest you file this issue through the [report a problem option in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) to get a better and faster answer.

I'll leave the issue open in case @SteveSandersonMS who knows more about the debugging area has an idea.

**Comment by mrpmorris** [comment]
@javiercn Done. Reported it through the "Report a bug" option in the latest VS preview.
