### ISSUE TITLE
[blazorwasm] CheckBox-Binding not working, when input is in component

### ISSUE THREAD

**Issue by Knarzi** [dotnet/aspnetcore#21532]
### Describe the bug
I'm trying to create a CheckList component where you load items and automatically create items with checkbox and label. If I put the list with the foreach loop directly on a page, everything works as expected. A click on the button "Select All" sets all checkboxes to checked.

But if I put the same code into a component, nothing happens when I click on the button. The underlying data is changed, but the checkboxes are not set to checked.

rc1 is in use.

### To Reproduce
Pair.cs
```C#
namespace LHHi.AspNetCore.Components.Helpers
{
    public class Pair<T1,T2>
    {
        public T1 FirstValue { get; set; }
        public T2 SecondValue { get; set; }        
    }
}
```
TCheckList.razor
```Razor
<ul class="list-group checked-list-box">
    @foreach (var item in CheckListValues)
    {
        <div @key="item">
            <input type="checkbox" @bind="@item.FirstValue">
        </div>
    }
</ul>

@code
{
    public List<Pair<bool, object>> CheckListValues { get; set; } = new List<Pair<bool, object>>();

    [Parameter]
    public IEnumerable<object> Items 
    {
        set 
        {
            CheckListValues = value.Select(v => new Pair<bool, object> { FirstValue = false, SecondValue = v }).ToList();
        }
    }
}
```
FetchData.razor
```Razor
@page "/fetchdata"
@using ComponentsTest.Shared
@inject HttpClient Http

<h1>Weather forecast</h1>

<p>This component demonstrates fetching data from the server.</p>

@if (forecasts == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <!-- Working-->
    <ul class="list-group checked-list-box">
        @foreach (var item in _checkListValues)
        {
            <div @key="item">
                <input type="checkbox" @bind="@item.FirstValue">
            </div>
        }
    </ul>

    <!-- Not Working-->
    <TCheckList @ref="TCheckList" Items="@forecasts" />

    <button type="button"
            @onclick="@(() => SelectAll())">
            Select All
    </button>
}

@code {

    private List<Pair<bool, WeatherForecast>> _checkListValues = new List<Pair<bool, WeatherForecast>>();

    TCheckList TCheckList { get; set; }

    private WeatherForecast[] forecasts;

    protected override async Task OnInitializedAsync()
    {
        forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");
        _checkListValues = forecasts.Select(f => new Pair<bool, WeatherForecast> { FirstValue = false, SecondValue = f }).ToList();
    }

    public void SelectAll()
    {
        foreach (var item in _checkListValues)
        {
            item.FirstValue = true;
        }
        foreach (var item in TCheckList.CheckListValues)
        {
            item.FirstValue = true;
        }
        StateHasChanged();
    }
}
```
Result:
![image](https://user-images.githubusercontent.com/21334413/81163025-66bcd200-8f8e-11ea-8621-a548879fda71.png)

Expected Result:
![image](https://user-images.githubusercontent.com/21334413/81163123-8b18ae80-8f8e-11ea-9ecc-8e3092036a8c.png)

**Comment by SteveSandersonMS** [comment]
Thanks for getting in touch. I've investigated and determined what's going on.

The problem is that your component is trying to bypass the normal parameter-passing mechanism, and is overwriting its own changes:

 * When `SelectAll` runs, `FetchData` mutates the internal state of the `TChecklist` child component. This is something you should avoid doing, because it's bypassing the normal rendering mechanism, meaning that Blazor can not guarantee to update the affected components. Blazor doesn't know you've done this at all, so it has no way to know which other components to render.
 * However, to make this extra confusing, `TChecklist` has a property setter that on each invocation, generates an entirely new set of instances for the `CheckListValues` collection, defaulting the `FirstValue` (i.e., selection state) of each to `false`.
    * So after `SelectAll` runs and `FetchData` re-renders itself, it re-passes the `Items` to `TChecklist` which the regenerates `CheckListValues` and undoes the mutations that `FetchData` just did.

Fortunately there are simpler ways to do what you're doing here, which don't have these kinds of complications :) There's no need to use `@ref` here. Here's an example of passing the parameters via the normal mechanism: https://gist.github.com/SteveSandersonMS/7c5e80ebf7f238505f1281f550666600

If you're interested in a more advanced way of doing this, which also lets you supply a template for rendering each item and notifying the container component when items are toggled, here's another example: https://gist.github.com/SteveSandersonMS/3b27b3d2ad99997e49cae4d74a225223. This one uses data binding to keep related components in sync.

**Comment by Knarzi** [comment]
Okay, thanks for the information. I was actually hoping that I could put the status of the checkbox directly inside the component, so I would just have to pass the items instead of the checkbox status plus the corresponding item. I wanted to create a generic component that is as self-sufficient as possible, which contains the functions SelectAll, SelectNone etc. directly, so that it is not necessary to store the status of the lists on the page in Pair<bool, T>.
