### ISSUE TITLE
Generic Ok and OkObjectResult

### ISSUE THREAD

**Issue by trejjam** [dotnet/aspnetcore#21535]
### Describe the solution you'd like
The generic parameter of the `ActionResult<T>` is not statically checked when `Ok(object value)` and other helpers from the `ControllerBase` is used.
It will be nice to have `OkObjectResult<T> Ok<T>(T value)` (and others) so the following code will not compile when `_service.Send()` return type changes to a different type.

### Additional context
```cs
[HttpPost]
public async Task<ActionResult<MessageContract>> SendMessage([FromBody] MessageInput message)
{
    // messageContract is MessageContract
    var messageContract = await _service.Send(message);

    return Ok(messageContract);
}
```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by pranavkm** [comment]
It's much more likely we would use https://github.com/dotnet/aspnetcore/issues/8535 to solve this rather than adding generic helper overloads. I'm closing this as a dup of the other.

**Comment by Pilchie** [comment]
Closing resolved issue.

**Comment by Andrew-Webb** [comment]
> It's much more likely we would use #8535 to solve this rather than adding generic helper overloads. I'm closing this as a dup of the other.

The issue you linked to says: "Create and include an analyzer [...]".  Does this mean that getting a warning requires use of `Microsoft.CodeAnalysis.FxCopAnalyzers` in the project?

If so, then given that I'm the only one I know (personally) who actually uses FxCopAnalyzers, I wonder if it might be better to give people the tools they need in the first place - as @trejjam suggests  - to get type safety, rather than produce a warning from a tool that many don't use.

**Comment by pranavkm** [comment]
> Does this mean that getting a warning requires use of Microsoft.CodeAnalysis.FxCopAnalyzers in the project?

No, MVC ships with it's own set of analyzers that are implicitly referenced.

Going back to the initial suggestion, you would have to author these new helpers in very specific ways that don't really gel well with the rest of helpers. For instance, `OkObjectResult<T>` cannot be an instance of `ObjectResult` \ `ActionResult` since this would compile:

```C#
ActionResult<Person> person = new OkObjectResult<NotPerson>(new NotPerson { ..})
```

The analyzer seems to be a much simpler solution than adding a whole new hierarchy of types to support a fairly narrow problem. That said, if you absolutely needed to, you could implement this feature in your own application or library.

**Comment by Andrew-Webb** [comment]
@pranavkm - thanks for the explanation.  Yes, agree: having an MVC analyzer sounds like the best way to go.

>  you could implement this feature in your own application or library

FWIW, since my actions all return `Task<ActionResult<TResult>>` I put this in my abstract base controller class (which sits between `ControllerBase` and the concrete controllers):-

```csharp
        // Generic version of ControllerBase.Ok().
        protected ActionResult<TResult> Ok<TResult>(TResult value)
        {
            return base.Ok(value);
        }
```

This works well.
