### ISSUE TITLE
SignalR: handling Redis connection failures

### ISSUE THREAD

**Issue by Xayton** [dotnet/aspnetcore#21539]
### Describe the bug
When using ASP.NET Core SignalR, I'm having some problems handling Redis connection failures.
The documentations ([link](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.1#redis-server-errors)) says:
> When a Redis server goes down, SignalR throws exceptions that indicate messages won't be delivered.

I could not see or catch in any way those kind of exceptions.
**Question**: How can I handle these exceptions?

### To Reproduce
To simulate a failed connection to Redis, simply put a wrong hostname in the connectionString:
`services.AddSignalR().AddStackExchangeRedis("non-existing-host");`

#### What I expected:
The SignalR connection between the Client and the Server remains active, but messages to and from other servers (via Redis) will be lost. This transparently returns back to normal when the connection with the Redis server is restored.

#### What happens instead:
The SignalR connection between the Client and the Server is interrupted with error "WebSocket closed with status code: 1011".

They only thing the Client can do is try to connect again (it may be configured to do so automatically). The client will connect again, and after a few seconds (depending on how long it takes for the Server to confirm the communication error with Redis) it will be disconnected by the Server. This loop keeps going until Redis comes back or the Client stops trying.

#### Proposal:
Unless this is the desired behaviour, I think it would be better to handle the Redis connection failures transparently. This way the Client would not have to keep reconnecting and we could avoid a lot of useless handshaking.

### Further technical details
- ASP.NET Core version: both 2.2 and 3.1
- Might be related to this other issue: https://github.com/dotnet/aspnetcore/issues/11250

**Comment by BrennanConroy** [comment]
> I could not see or catch in any way those kind of exceptions.
> **Question**: How can I handle these exceptions?

If you try to broadcast, send to a group, send to a user, or send to a connection on a different server (or a connection that doesn't exist) you'll get an exception. For example `await Client.All.SendAsync("method");` will throw if Redis is disconnected.

The current behavior is to fail new connections when Redis is down. You can change this behavior by setting up custom [Redis connect logic](https://docs.microsoft.com/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.1#custom-behavior-for-connection-failures) and returning a successful task instead of failing when Redis is down.

**Comment by Xayton** [comment]
OK, I was able to catch the exceptions when Redis is disconnected.

I was also able to keep the client connections alive when Redis is down: looking the the code you linked I just had to set the `AbortOnConnectFail` to false in the `ConfigurationOptions`.
```
services.AddSignalR().AddStackExchangeRedis("hostname", o => o.Configuration.AbortOnConnectFail = false);
```
The only thing missing is that I would like to send messages to the clients connected to the local server, even if Redis is down. In my case this is still better to broadcast a message to subset of the clients (only those connected to the current server) then not sending it at all.

How can I get send calls to work (only for the clients of the current server) even if Redis is down?

Thank you

**Comment by BrennanConroy** [comment]
If you know what connections are on your server then you can send specifically to the connections with `Clients.Client("id").SendAsync(...);` otherwise we publish the message to Redis and don't try to short-circuit for local connections as that would require extra message de-duping logic (Message from the Redis publish and the same message for the local connection writes).

For your scenario, you want `Clients.All.SendAsync(...);` to work even when Redis is down? You might be able to hack this in by providing a custom IConnectionMultiplexer and custom ISubscriber classes however there is no built-in support for that.

You could also copy the RedisHubLifetimeManager class and add support for that yourself and add your modified class to DI `Services.AddSingleton(typeof(HubLifetimeManager<>), typeof(CustomRedisHubLifetimeManager<>));`

**Comment by Xayton** [comment]
**About sending messages even when Redis is down**
I tried what you suggested, but the class `RedisHubLifetimeManager` depends on other internal classes: to make it work I would need to duplicate almost all the classes in `SignalR.StackExchangeRedis`.
While possible, I don't think this is worth doing and maintaining. OK with this.

**About aborting new connections when Redis is down**
Let's say that I leave `Configuration.AbortOnConnectFail` to the default (true). When Redis goes down:
- Existing connections will be disconnected.
- New connections will be accepted but then disconnected a few seconds later (when `EnsureRedisServerConnection` fails).

**Question**: Is there a way to abort new connections, instead of completing them and then disconnecting a few seconds later?

It seems to me that the connection handshake ([HubConnectionHandler.cs#L113](https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/server/Core/src/HubConnectionHandler.cs#L113)) is completed before the call to `_lifetimeManager.OnConnectedAsync` at line 122 (which will fail with an exception when Redis is down).

The only way would be to check the Redis status before calling `connectionContext.HandshakeAsync()` which would mean copying and customizing not only `SignalR.StackExchangeRedis` but also `Microsoft.AspNetCore.SignalR` classes.
Am I right? If that's the case I consider this issue closed.

Thank you!

**Comment by BrennanConroy** [comment]
> Is there a way to abort new connections, instead of completing them and then disconnecting a few seconds later?

No built in way. If you manage the redis connection yourself via the `ConnectionFactory` then you could write a middleware that intercepts /hub/negotiate requests when Redis is down and stops them before they connect.

> I tried what you suggested, but the class `RedisHubLifetimeManager` depends on other internal classes: to make it work I would need to duplicate almost all the classes

That's true, however, if you want to go down that route you could try to inherit from the `RedisHubLifetimeManager` instead or create an instance inside your custom `HubLifetimeManager` and then just wrap the methods.
