### ISSUE TITLE
WebASM project : HttpClientHandler not supported.

### ISSUE THREAD

**Issue by YordanYanakiev** [dotnet/aspnetcore#21550]
### Describe the bug
I am trying to make a request to a web api from Blazor WebASM project. The server hosting the web api is developer computer with self-signed certificate. I have configured CORS. I am trying with the follow code to bypass the certificate:

```
using( var httpClientHandler = new HttpClientHandler() )
{
    httpClientHandler.ServerCertificateCustomValidationCallback = ( message, cert, chain, errors ) => { return true; };
    using( var client = new HttpClient( httpClientHandler ) )
    {
        // Make your request...
    }
}
```

### To Reproduce
call anywhere in the code:

```
using( var httpClientHandler = new HttpClientHandler() )
{
    httpClientHandler.ServerCertificateCustomValidationCallback = ( message, cert, chain, errors ) => { return true; };
    using( var client = new HttpClient( httpClientHandler ) )
    {
        // Make your request...
    }
}
```

### Further technical details
- ASP.NET Core version : 3.2
- Include the output of `dotnet --info`
- The IDE : VS 2019 / 16.6.0. preview 5.0

**Comment by javiercn** [comment]
@YordanYanakiev thanks for contacting us.

I'm not sure the webassembly message handler has control of the certificate validation process since it's subject to the browser sandbox and that might prevent the request from even happening.

That said, this if anything is an issue in the mono runtime, so I would suggest you file the issue [here](https://github.com/mono/mono) to get a better and faster answer.

**Comment by YordanYanakiev** [comment]
Just to add for everyone having issue with testing against self-signed server.
For Chrome browser - set it with the follow parameters :
>  --incognito --ignore-certificate-errors

This will suppress certificate error.
