### ISSUE TITLE
Dispose() gets called right after OnInitialized() in Server-side Blazor

### ISSUE THREAD

**Issue by leSyndrome** [dotnet/aspnetcore#21571]
I made a Component that is a @page and also implements IDisposable and noticed that Dispose() gets called before initialization (OnInitialized() gets called, then Dispose(), then OnInitialized() again). That doesn't seem right and I need this component to call Dispose() only when it is really removed from the render tree.

Sorry if this is not the right place to post this issue.

Here's a link to a minimalistic repo that recreates the bug:
https://github.com/leSyndrome/DisposeDemo

**Comment by javiercn** [comment]
@leSyndrome thanks for contacting us.

The component is disposed the first time after the prerendering is complete and you see your service as disposed because you are using a singleton service, which is shared across al services. See [the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1) for details.

**Comment by leSyndrome** [comment]
Thanks!
Is there an easy way to determine if the component is being prerendered in the Dispose method?

**Comment by javiercn** [comment]
@leSyndrome You can use a scoped service and a flag that you set before prerendering the component.
