### ISSUE TITLE
[Blazor] warning CS0649 for code behind in partial

### ISSUE THREAD

**Issue by michalczerwinski** [dotnet/aspnetcore#21570]
How to reprodcue?

MyComponent.razor
`<SomeComponent @ref="_someComponentReference/>`

MyComponent.cs
```
public partial class MyComponent: ComponentBase
{
  private SomeComponent _someComponentReference;
} 
```

This will result in warning CS0649.
Since using partial class is now officially supported for Blazor this is a bug, IMHO.

**Comment by javiercn** [comment]
@michalczerwinski thanks for contacting us.

@ajaybhargavb @NTaylorMullen is this something Razor can handle or is this on the C# compiler responsible for this? Meaning, do we need to change how we generate code?

Otherwise, if it's in user code, the only way to solve this is through a pragma. Not 100% sure we can do anything about it.

**Comment by michalczerwinski** [comment]
Some additional info: the issue is due to the way the generated *.razor.g.cs are processed.

The code responsible for setting the reference is inside BuildRenderTree and the very same piece of code moved to regular .cs file is correctly recognized as field initialization.

**Comment by NTaylorMullen** [comment]
Ya sadly this is a quirk in how we do build-time compilation where we discover the available components by doing a "slim parse" of all the Razor components and then we do a real parse based on those discovered components. The problem you're seeing is that during the "slim parse" we remove all bodies of components which means your file starts getting dinged for CS0649.

There are many ways we can fix this.

1. SourceGenerators, this would remove our two step compile
2. Don't publish errors during component discovery. Not sure how easy this is because this error comes directly from Roslyn so we'd need to silence their error publishing.

Either way, we're tracking the fix to this here: https://github.com/dotnet/aspnetcore/issues/20137

Closing as a duplciate for now 😄
