### ISSUE TITLE
[WASM] How do I use Blazor with an alternative Mono distribution?

### ISSUE THREAD

**Issue by LEI-Hongfaan** [dotnet/aspnetcore#21576]
I am trying to mount IDBFS as before but it cannot be done with the recently new versions.

It seems that IDBFS is now an optional component of Emscripten and it is by default not linked into Emscripten.

I think using Blazor with a customized Mono build could be a solution in general. How can I do that? Or is there a way to mount IDBFS?

**Comment by javiercn** [comment]
@LEI-Hongfaan thanks for contacting us.

Using a custom mono runtime is not something that we support nor we plan to support. 

If you wanted to do this you would have to compile your own mono distro and reverse engineer the Blazor build pipeline to modify the outputs of the build process to plug-in your custom built mono runtime, without any guarantee that it would work, since this is not a supported scenario for Blazor.
