### ISSUE TITLE
Blazor dependencies (5.0.0-previewfor Authentication

### ISSUE THREAD

**Issue by Brannos1970** [dotnet/aspnetcore#21619]
I updated Visual Studio 2019 Preview to the latest version. I created a new Blazor App and noticed that the Blazor Client template is missing.

While creating the new app I selected the option to include authentication with Individual User Accounts. The following dependencies were reference but not found:

Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore Version 5.0.0-preview.4.20214.3
Microsoft.AspNetCore.Identity.EntityFrameworkCore Version 5.0.0-preview.4.20214.3
Microsoft.AspNetCore.Identity.UI Version 5.0.0-preview.4.20214.3
Microsoft.EntityFrameworkCore.SqlServer Version 5.0.0-preview.4.20203.1
Microsoft.EntityFrameworkCore.Tools Version 5.0.0-preview.4.20203.1

**Comment by pranavkm** [comment]
We haven't included Blazor WebAssembly in .NET 5 just yet because we're focused on Blazor WebAssembly 3.2 release which is scheduled for May of this year. Blazor WebAssembly 3.2 is based on .NET Core 3.1 and will soon be included in the .NET Core 3.1 SDK. After the May release we'll integrate Blazor WebAssembly with .NET 5.

You can still install the Blazor WebAssembly template and use it with the .NET 5 SDK, but the project template will still only show up as a .NET Core 3.1 base project.

![image](https://user-images.githubusercontent.com/1874516/77103869-55b50300-69d8-11ea-9c7e-e0746ce8114b.png)

I hope this helps!
