### ISSUE TITLE
[Blazor] 404 on _framework/blazor.server.js with nginx reverse proxy

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#21775]
### Describe the bug

I have a server-side blazor application that I want to put behind a reverse proxy with nginx.

I followed [this instruction](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#configure-nginx) to set headers etc, and [this instruction](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1#linux-with-nginx) for SignalR Websockets.

```
server {
        listen 443 ssl http2;

        if ($http_referer ~ ^https://my.host/application/) {
            rewrite ^(.*)$ /application/$1;
        }
        location /application/ {
            proxy_pass http://my.host:8080/;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
}
```

```
http {
    map $http_upgrade $connection_upgrade {
        default Upgrade;
        ''      close;
    }
}
```

I added the rewrite based on referer such that requests to https://my.host/_framework/, https://my.host/css etc are rewritten to the correct path.
```
        if ($http_referer ~ ^https://my.host/application/) {
            rewrite ^(.*)$ /application/$1;
        }
```

The rewrite works for resources such as items in the wwwroot folder, but it doesn't work for `_framework/blazor.server.js`.

### To Reproduce

- Create a new blazor server-side app and configure nginx as above.
- Deploy the app in a docker instance using `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim` as base
- Navigate to https://my.host/application and observe that the network request to `_framework/blazor.server.js` fails.

### Further technical details
- ASP.NET Core version 3.1.4

**Comment by stefanloerwald** [comment]
Here's the devtools output for `_framework/blazor.server.js`:

```
Request URL: https://my.host/_framework/blazor.server.js
Request Method: GET
Status Code: 404 
Remote Address: 192.168.1.60:443
Referrer Policy: no-referrer-when-downgrade
content-length: 0
date: Wed, 13 May 2020 09:04:08 GMT
server: nginx/1.17.10
status: 404
:authority: my.host
:method: GET
:path: /_framework/blazor.server.js
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-CH,de-DE;q=0.9,de;q=0.8,en-US;q=0.7,en;q=0.6
cache-control: no-cache
dnt: 1
pragma: no-cache
referer: https://my.host/application/
sec-fetch-dest: script
sec-fetch-mode: no-cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
```

And here for `css/site.css`:

```
Request URL: https://my.host/css/site.css
Request Method: GET
Status Code: 200 
Remote Address: 192.168.1.60:443
Referrer Policy: no-referrer-when-downgrade
accept-ranges: bytes
cache-control: no-cache
content-length: 3528
content-type: text/css
date: Wed, 13 May 2020 09:04:08 GMT
etag: "1d6277b440a6c48"
last-modified: Mon, 11 May 2020 10:02:23 GMT
server: nginx/1.17.10
status: 200
:authority: my.host
:method: GET
:path: /css/site.css
:scheme: https
accept: text/css,*/*;q=0.1
accept-encoding: gzip, deflate, br
accept-language: de-CH,de-DE;q=0.9,de;q=0.8,en-US;q=0.7,en;q=0.6
cache-control: no-cache
dnt: 1
pragma: no-cache
referer: https://my.host/application/
sec-fetch-dest: style
sec-fetch-mode: no-cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
```

**Comment by javiercn** [comment]
@stefanloerwald thanks for contacting us.

We'll look into this issue and update the status appropriately.

Does the request succeed when running the app on localhost?

**Comment by stefanloerwald** [comment]
Hi @javiercn, the request works if I navigate to the app directly.

**Comment by SteveSandersonMS** [comment]
It looks like your proxy modifies the URL structure (from `/*` to `/application/*`). If that is the case then you must also modify the `<base href>` value in your page correspondingly, otherwise the browser won't know where to fetch related resources. This is not Blazor-specific but rather is just how relative URLs work within browsers.

So your `index.html` probably needs to specify (note the required trailing slash):

```html
<base href="/application/" />
```

See also https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path

**Comment by stefanloerwald** [comment]
Hi @SteveSandersonMS,

yes, I'm modifying the URL structure. However, the proxy rewrite should take care of that, given the http referer, so the application itself should see the requests coming in at the correct URLs, shouldn't it? In fact, it does, for the css resources, just not for the framework javascript file. 

Adding the application path (that only the reverse proxy knows) into the application itself seems like a terribly leaky situation.

**Comment by SteveSandersonMS** [comment]
> However, the proxy rewrite should take care of that, given the http referer, so the application itself should see the requests coming in at the correct URLs, shouldn't it?

No, I don't think that will happen, and we can see from the 404s you're getting that it doesn't happen.

Since your page's base href is hardcoded as `/`, even when the browser thinks it's at https://my.host/application/, the related URLs will be resolved relative to https://my.host/ (e.g., `https://my.host/something.css`). That doesn't have any `/application/` prefix so the rewriter won't get involved and you'll have a 404.

As far as I know, you *would* need to set a correct `<base href>`. Maybe you can somehow transparently rewrite the value inside your Nginx config as the html is served. But either way this isn't really Blazor specific - this is purely about using Nginx and how rewriting URLs affects how webpages fetch related resources.

**Comment by stefanloerwald** [comment]
The rewrite happens based on referer. And again: it works for the css resources, but not for the framework js. The reverse proxy doesn't make that distinction, so it must be a problem of the application, i.e. the blazor app.

**Comment by SteveSandersonMS** [comment]
I'm afraid I'm not in a position to debug what is insufficient about this particular kind of proxying/rewriting, however I think something about it must be insufficient.

Reason: if the proxying/rewriting was updating the request so that, from the application server's perspective, it was no different from a regular direct request, then the application server would not be able to distinguish it from a regular direct request, and hence it must behave the same as a regular direct request, which you have said does work correctly.

Again, I apologise that doesn't directly lead you to a solution.

**Comment by SteveSandersonMS** [comment]
Also I still think you will need to update the base href. Otherwise, Blazor's router will not be able to match up the browser's URLs with the `@page "..."` directives in your application.

For example, if the page URL is `/application/`, the only way this will show the homepage (i.e., the component with `@page "/"`) is if the base href is set to `/application/`.

**Comment by SteveSandersonMS** [comment]
One last thought :) I think there's a much simpler way to achieve what you're doing here.

Since your site at `http://my.host:8080/` is running on ASP.NET Core, you can change the config so that it actually treats `http://my.host:8080/application/` as the PathBase. If you do that, then you no longer have to rewrite URLs from `/x` to `/application/x`, because all the URLs within that site will be within `/application` anyway. Also you don't have to change your `<base href>`, because the `PathBase` automatically becomes part of that. Then all the file serving and Blazor component routing will just work.

For info on how to do this, see https://www.billbogaiv.com/posts/net-core-hosted-on-subdirectories-in-nginx. That post even gives examples on using it with an Nginx reverse proxy 😄

**Comment by stefanloerwald** [comment]
Thanks Steve for your comments. Passing the base path as config is somewhat acceptable, and I get that it's the only way given the routing requirement.

With that, I got it to work, but following the advice for signalr through nginx, it did fall back to non-websocket connection for blazor. I found [another resource](https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-configure-nginx-for-websockets/) that suggested some other settings, and I found it to work with the following setup:

### Application-side
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
   app.UsePathBase(Configuration.GetValue<string>("PATH_BASE"));
   // more app config as usual
}
```
Contrary to what [this instruction says](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#configure-nginx), the following seems to be NOT necessary, Not sure whether that's universally true, or just with my setup:

```
// not required for my scenario:
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});
```

### nginx reverse proxy side

The instruction on [SignalR and reverse proxy](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#configure-nginx) seems wrong, as the browser did not establish a websocket connection with that config.

The config that works for me is
```
location /application/ {
   proxy_pass http://host.docker.internal:1010/application/;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
}
```
The assumption here is that "/application" is the base path used in the app.

The wrong settings seems to be the Connection proxy header, which is set to "keep-alive" in the doc, but seems to only work with "upgrade". The other settings suggested in the doc are not required in my scenario, maybe because I'm staying on the same host.
