### ISSUE TITLE
Investigate PipeWriter.CopyToAsync change in FileBufferingWriteStream resulting in missing bytes

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#21834]
Follow up to https://github.com/dotnet/aspnetcore/pull/21833/files#diff-ce5092f29477d8f4d725de87373a56aaL202. I was unable to reproduce this issue locally, but it was very consistent when running it through benchmarks. Here's the command I used:

```
dotnet run --config https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BenchmarksApps/Mvc/benchmarks.mvcjson.yml --scenario MvcJsonNetOutput2M --application.options.displayOutput true --profile aspnet-physical-lin
```

**Comment by halter73** [comment]
Investigation notes:

When you do a normal CopyToAsync operation with a Stream destination, the full response is still be “written” it would just effectively go to /dev/null. Since the new implementation is checking the FlushResult to see if the transport is still reading, it short circuits to save some cycles when the benchmark client aborts the connection.
 
This isn’t too dissimilar to how StaticFiles stops when RequestAborted fires, the key difference is that [Kestrel checks if RequestAborted has been tripped](https://github.com/dotnet/aspnetcore/blob/b3c6c437896fae08de8f116f24750cb16b5f978a/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L670) before verifying the appropriate number of bytes have been written. Apparently there is a race where Kestrel doesn’t observe ConnectionClosed/RequestAborted firing until after returning a completed FlushResult.
 
The fix is pretty simple. We just trip RequestAborted ourselves when any of Kestrel’s BodyWriters return a completed FlushResult.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/22086

**Comment by davidfowl** [comment]
@pranavkm can you revert the change in MVC and WebUtilities?
