### ISSUE TITLE
Upgrade requests should be keepalive by default

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#21886]
This is breaking Windows Auth with WebSockets in Kestrel.

**Comment by halter73** [comment]
I think I remember what's going on here. If the client tries to establish a WebSocket connection and it gets rejected with a 401 Unauthorized response instead of immediately upgraded, the might want to authenticate with NTLM (which is connection-based) over the same connection, but Kestrel will automatically close the connection after the 401 response because of the connection upgrade request header.

If Kestrel doesn't respond with a 101 Switching Protocols response, there's no need for Kestrel to close the connection. It could treat the upgrade request like any other GET.

**Comment by Pilchie** [comment]
This is in `3.1.x`, but we just merged a fix for 5.0 GA.  Do we need a backport here?  Do we have customers asking for it?

**Comment by halter73** [comment]
I forget how this came up in May, but @vinaykapoor who brought this back to our attention on https://gitter.im/aspnet/SignalR saw this when trying out .NET 5 RC1.

**Comment by halter73** [comment]
I'm okay with closing this if we don't hear more about it from customers. What do you think @Tratcher and @BrennanConroy?

**Comment by BrennanConroy** [comment]
Same, I just wish we put more info when we opened this issue. I have no clue how this was found, and why we put it 3.1 :D

**Comment by Tratcher** [comment]
I don't know how you're going to get shiproom approval without the customer.

**Comment by halter73** [comment]
I'm closing this then. We can reopen later if need be.

**Comment by vinaykapoor** [comment]
I can test it. Please fix this and don’t close

**Comment by vinaykapoor** [comment]
If there is a workaround I can test that as well.

**Comment by vinaykapoor** [comment]
If an issue this prominent exists I don’t see why someone should wait for more complains before fixing it. Unless there is a workaround I am not sure how to proceed.

**Comment by halter73** [comment]
The fix will be in .NET 5 when it ships and should show up in our next [daily build](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md).

#26480 is the PR that fixed it. The only workaround I know of for previous releases is to switch to another server like IIS or HttpSysServer assuming you're running on Windows.

**Comment by vinaykapoor** [comment]
Thank you if it’s fixed in .net 5.0 that would be great!
