### ISSUE TITLE
asp-page TagHelper Not working

### ISSUE THREAD

**Issue by Eragon00721** [dotnet/aspnetcore#21924]
i got problem with asp-page tag helper in asp.net core 3.1 ( web Application ) project

it was working fine before , but today its not working

for example if i write this code :

`<a asp-page="/ShowPage">Click Me</a>
`
and the codes output is here:

`<a href>Click Me</a>`

I've Updated all my nuget packages but it's not working.

i create a new web application razor pages project and tested the tag helpers there but they're not working

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by lgaspari** [comment]
Hi everyone, I'm facing a similar issue with `asp-page` but I think my scenario is quite more complex than @Eragon00721.

I'm rendering a `<form>` tag inside a **Partial View,** called `Logout.cshtml` from the `_Layout.cshtml`. This `form` tag has the attribute `asp-page` the same way as my Register and Login forms does, but it doesn't work as expected. In fact, I have the same output `<form method="post" action="">`

Does anyone else has the same issue?

@mkArtakMSFT do you think I should open a new issue for that?

**Comment by mkArtakMSFT** [comment]
@javiercn any recommendations regarding @lgaspari 's scenario above?
Does the framework output some debug message in case it can't find the action?

**Comment by javiercn** [comment]
I would need a repro to tell.
I would check that endpoints.MapRazorPages() and so on are being called in startup.

**Comment by lgaspari** [comment]
Sure I can build a repro for you @javiercn, but I'm afraid I can't do it today. I'll try to do it tomorrow!

**Comment by lgaspari** [comment]
Hey @javiercn I tried to create a repro project but It won't work because I think I'm trying to do something impossible.

I'm trying to create a **Logout** partial view, that has a Model in the back (to call the `OnPost()` method to sign out) but it does not work since I have to send the model from the `_Layout.cshtml` through the `Logout.cshtml` partial view.

Is it reasonable? Should I take another approach like having a view instead of a partial view? Should I create a **BaseModel** which creates a **LogoutModel**?
