### ISSUE TITLE
[Blazor server side] [Question] Possibility to separate server app and client app in server-side mode ?

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#21938]
Hi guys, This question may appears strange, but i actually migrate a silverlight/wcf app into blazor and trying to keep the same architecture (because i reuse lot of code).

In the actual app, there is no dependency between the client and server app, so some class was shared between the two projects, but compiled in different assembly, with some preprocessor directive inside the code to determine the behavior between the two app (included different property, different constructor, etc)

#if CLIENTSIDE => some code
#elseif SERVERSIDE => other code

To come back to my blazor app, since the beginning i develop it with keep compatibility with webassembly mode and server side mode.  the server at startup read a app settings and execute different piece of code to run in web assembly or server side, and it works well.

Now i want to separate my assembly, for webAssembly it seem OK, i had my answer in this issue https://github.com/dotnet/aspnetcore/issues/21692, it seem work well.

But for server side, i have no idea if its possible. Because at the end everything run on the same executable. for now, if i remove the reference the server side can't run because i have references to app which is in client side project
````
<component type="typeof(App)" render-mode="ServerPrerendered" />
````

So we don't know how to solve this problem, we try to replace our conditionnal symbol architecture with other tricks (partial, extension method, etc) but nothing work as expected, because our assembly are not clearly separate.

So there is a possibility to make it works ? or other tricks i doesn't think to solve my architecture problems ?

thanks !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

Is it because you are compiling the same type into different assemblies with some preprocessor conditional logic applied to it?

**Comment by julienGrd** [comment]
@javiercn yes its exactly the logic of the original App
for example a class classA is on the project Library.Server but also in the project Library.Client (added in this last one as a link)
The server app reference Library.Server
The client app reference Library.Client

If i do that with my blazor app, server app will know classA twice (because server app will know Library.Server but also Library.Client because of the reference to the client)

**Comment by javiercn** [comment]
@julienGrd there is no way to achieve that in server-side blazor.

I think it's pretty complicated. There are ways to do this in C# (see below) but I would recommend against it and instead suggest you use the preprocessor logic to put them in different namespaces.

The only reason client-side Blazor gets away with "total independence" is because there is no memory/code dependency between the server and client app (provided you don't prerender).

In the server-side case, the code runs in the same process, so there is no way of achieving that without the app assemblies being present.

If you still want to do this, I believe you could potentially do this with "global::" https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/namespace-alias-qualifier and https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias but it is likely quite cumbersome and honestly not worth it.

**Comment by julienGrd** [comment]
@javiercn , thanks for your response, it was kind of what i expected. For now i will put this subject aside and maybe we will reconsider to exclude server side from our app (but we have to be sure webassembly version will be improved in term of performance because for now its limited and our server side version is really faster)
