### ISSUE TITLE
Blazor UI invalidation documentation

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#21959]
Is there any documentation how Blazor invalidates the UI?

I know the StateHasChanged method tells Blazor the component should be rendered again, but ...

1) How is the relation between parents and children? Is a parent invalidated when a children is invalidated? and vice versa?
2) What should I invalidate when a component is composed of a hierarchy of components, always the base? always the most specific component?
3) What if I call StateHasChanged is called multiple times? And what if those calls are performed in different components of the hierarchy
4) Are there thinks I should take into account to have good performance?

I appreciate your help to understand how Blazor works.

**Comment by mrpmorris** [comment]
1: Do parents/children render independently?

Simply being in a parent/child relationship will link rendering between parent and child. The parent and child can change independently without forcing a re-render of the other.

The rules are a component will re-render if
1A: One of its [Parameter] property's values change
1B: One of its [CascadingParameter] property's values change
1C: It sets an `EventCallback` of another component, and that component invokes the `EventCallback` (e.g. `<MyChildComponent Clicked=ChildComponentWasClicked/>`)
1D: The component has an `EventCallback` that is set by another component, and the component that sets its `EventCallback` rerendered (no idea why this would be)

2: Sorry, I don't understand the question.

3: It will be flagged to be re-rendered, and then only rendered once on the next render phase.

4: Performance:
4A: Whenver rendering something in a loop (foreach, etc) always assign an `@key` to the element

```
@foreach(Person person in People)
{
  <li @key=person>.....</li>
}
```

4B: If you want strict control over when your component should rerender, override ShouldRender and return `true`/`false`
4C: If you want events raised between components without forcing a rerender, declare a property of type `Action` or `Action<T>` instead of `EventCallback` or `EventCallback<T>`.

**Comment by arivoir** [comment]
Thank you for the comments. I need some time to research more in depth about them.

Regarding 3.

>It will be flagged to be re-rendered, and then only rendered once on the next render phase.

It's not working like that, I just reported the bug https://github.com/dotnet/aspnetcore/issues/22159

**Comment by mkArtakMSFT** [comment]
We will be covering this as part of https://github.com/dotnet/aspnetcore/issues/22576
