### ISSUE TITLE
SignInManager does not check SecurityStamp of 2FA RememberMe cookie allowing 2FA bypass

### ISSUE THREAD

**Issue by sarphiv** [dotnet/aspnetcore#21985]
### Describe the bug
The Identity Core SignInManager has a protected method called SignInOrTwoFactorAsync(...).
https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SignInManager.cs#L786

At the time of writing (2020-05-19) this method is used to sign in a user.
If the user has 2FA enabled, this method will instead prepare for the next step in signing in the user.
If the user has 2FA enabled and the user has said the client should be remembered - 2FA authentication is bypassed and the user is signed in.

A client is marked as "remembered" if it has the "RememberMe" cookie. 
This cookie consists of the user ID and if supported, the security stamp.
https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SignInManager.cs#L744

SignInOrTwoFactorAsync uses the method IsTwoFactorClientRememberedAsync to check if a client is remembered. 
This method, however, only checks if the user ID in the RememberMe cookie matches the user.
https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SignInManager.cs#L412

This causes SignInOrTwoFactorAsync to bypass 2FA even when the security stamp in the RememberMe cookie is invalid.

Is this intentional behavior? It makes "remembered" clients always trusted - but what if the device is stolen? A security stamp reset would not invalidate the stolen device.
Or maybe someone just forgot to check for security stamp support and then call ValidateTwoFactorSecurityStampAsync in IsTwoFactorClientRememberedAsync?
https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SignInManager.cs#L283

### Location
File
src/Identity/Core/src/SignInManager.cs

Commit
4303bbe78650abf0bc6941d81956b02e4357feb5

**Comment by blowdart** [comment]
OK, after some discussion this is "By Design"

SecurityStamps roll for lots of reasons, like role changes or email address changes. So if, for example, you assigned a user a new role they'd now be logged out and have to go through MFA again, which is, to our mind, a little excessive.

If a laptop is stolen the thief is still going to need the account password to get anyway, that cookie does get invalidated when the password changes, and we feel that's the right balance against having to reprompt for 2fa on what could be normal operations.
