### ISSUE TITLE
Blazor Memory Leak

### ISSUE THREAD

**Issue by astevens8182** [dotnet/aspnetcore#21991]
In my server side Blazor app, After launch, I will click on a few pages then go back to the main home page (which has only text) and then just let the app sit for while. When I come back the memory usage has gone up a considerable amount (about 1.mb a min). Any solutions for this issue?

For example after clicking a few pages the memory was about 179MB. When I returned to the app the memory was over 200MB. The app was doing no processing, just sitting idle.

* I can provide minimal code due to the fact that this is not a personal project.

**Comment by astevens8182** [comment]
#18556 had a similar issue

**Comment by javiercn** [comment]
@astevens8182 thanks for filing a separate issue.

I would suggest checking the following:
* Force a GC collection after a few minutes (you can do so with perfview) and see if the memory is freed.
  * If the memory is freed, is not a memory leak, it's just the behavior of the GC collector. It will only release memory when it needs to do so.
* Check the memory traffic of the app:
  * Capture a memory dump when you start the application.
  * Perform several actions.
  * Leave it idle as you mentioned until the memory grows.
  * Capture another memory dump at that point.
  * Compare the two memory dumps in perfview to determine what objects got allocated in that time range and check what their root object is.
  * With that you can determine if the memory growth is caused by your app or the framework.
  * Trigger a GC event and capture another dump.
  * Check what objects are still present after the GC and if they should/shouldn't be there.

**Comment by astevens8182** [comment]
@javiercn  I will give these a try and let you know if it fixes anything. Thanks!

**Comment by astevens8182** [comment]
@javiercn  I forced A GC collection and the memory was not freed.

**Comment by javiercn** [comment]
@astevens8182 can you provide a minimal repro app so that we can take a look? Ideally as a GH repo, and detailed steps on how to trigger the issue?

**Comment by javiercn** [comment]
* Can you also provide more details on what objects/types do you see as the source of this memory growth?
* Are you able to make the memory grow until you reach an Out of memory exception?
* Did you trigger a full GC or just Gen0?
