### ISSUE TITLE
Progressive Web App Not Working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22011]
I found out that progressive web app does not even work.  I do the following steps:
1.  I create new app.
2.  I choose blazor web assembly.
3.  I choose progressive web app
4.  Next, I run it.
5.  I click to install.

After I install, i close out of the app.  The good news is i see the icon on the desktop.  However, when I click on it, it says it refused to connect.  This is just with the starting template with no code changes.

**Comment by jernejk** [comment]
What is the error you're getting?
My app also has broken with the following errors:

```
TypeError: "Response.arrayBuffer: Body has already been consumed."
    m https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
blazor.webassembly.js:1:37761
TypeError: Response.arrayBuffer: Body has already been consumed. blazor.webassembly.js:1:44767
Error: "Failed to start platform. Reason: RuntimeError: index out of bounds"
    v https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
blazor.webassembly.js:1:37761
Error: "Failed to start platform. Reason: RuntimeError: index out of bounds"
    v https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
    u https://dev.cognitivestudio.dev/_framework/blazor.webassembly.js:1
blazor.webassembly.js:1:37761
uncaught exception: Object
```

https://dev.cognitivestudio.dev/
GitHub: https://github.com/jernejk/CognitiveServices.Explorer

It worked on Blazor 3.2 Preview 4 and is broken since Release Candidate.
I hoped that RTM would be fixed but still the same problem.

For each version, I created a new Blazor PWA app and made sure that PWA integration is consistent.

It is possible to make this work with some combination of unregistering worker service and disabling cache but it's inconsistent at best.

If I disable service worker, it works perfectly but I want to have worker service.
I'm thinking about replacing this a manually written worker service without caching, so that I can update production version of the app without breaking it.

**Comment by musictopia2** [comment]
What I get is it says cannot even load the website.

**Comment by captainsafia** [comment]
@jernejk Can you open another issue with the problem that you ran into?

@musictopia2 Can you share some information about the operating system and browser you were using when you encountered this issue?

**Comment by musictopia2** [comment]
I was running on windows 10.   I was using chrome browser.

**Comment by jernejk** [comment]
@mkArtakMSFT, yes, the app seems to be broken and is unrelated to PWA. I thought it was because in RC I fixed it by disabling PWA but now the problem was that I got some cached assemblies from RC and it worked locally before I pushed to production. (for some reason it worked in MS Edge for a bit even after clearing cache before breaking)

New issue: #22116

**Comment by SteveSandersonMS** [comment]
@musictopia2 Offline support is only enabled for published apps, not in development, as described in docs. So your web server needs to remain running all the time in development otherwise the app will not be able to load.

**Comment by musictopia2** [comment]
Where did it mention in the docs?  I could not find where in the docs it was at.

**Comment by SteveSandersonMS** [comment]
Please see https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#offline-support
