### ISSUE TITLE
Debug Blazor WASM breake Google auth with some browser

### ISSUE THREAD

**Issue by fileman** [dotnet/aspnetcore#22045]
Hi,
I've updated to lastest visual studio 16.6, .net core 3.1.300 and all nugets, create new b2c app, but the #20227 wasn't resolved.

I have tried to sign-in with 4 different google account with same settings, but:
Firefox/Opera Ok all account;
Chrome/Edge Fail 3 account, 1 ok;

What can I do to give you better information for this issue?

**Comment by javiercn** [comment]
@fileman thanks for contacting us.

This is indeed an issue. Unfortunately it is not something we can do anything about. The reason for it is that to support debugging we turn on the remote devtools protocol and that in turn enables the `https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver` which Google auth uses to check and prevent logins.

This is something we handle on the browser context we launch (main window) but that we don't handle on popups.

Ultimately we have a tracking issue in chromium to change this behavior, since this is not an automation scenario. See [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1072836) for the associated issue.

Unfortunately, for the time being there is no workaround for this, other than do not use debugging in this situation.

**Comment by javiercn** [comment]
We've talked a bit more about this, and there is actually a workaround you can follow for this:

* Launch the app with debugging enabled.
* **ON THE SAME TAB** navigate to www.google.com and login
* Load the app again on the same tab and you should be able to log in.
