### ISSUE TITLE
Blazor - differ base href in development vs production

### ISSUE THREAD

**Issue by nbarkhina** [dotnet/aspnetcore#22061]
What is the recommendation for using a different base href in development vs production? For example during developing I use the "/" base href since that is what gets served up from the .net core development server. However in production I want to host it in a subfolder url such as https://[mysite]/blazor/ so in this case i would need to make base href "/blazor/". Is there anything built into Blazor to handle this either with syntax or with a parameter passed to dotnet publish, or would I need to handle that on my own either manually or with a build pipeline?

Thanks

**Comment by tn-5** [comment]
This only applies to WebAssembly. I'm having the same issue. Ideal would be if you could do a transform of the index.html during the publish.

For now you have to handle it yourself. From what I can see there are the following options:
1) Different Index.html files for different configs (a hassle since t is only the base href which differs in different files)
2) Use an msbuild extension to replace text in the index.html during publish (I haven't tried this myself, couldn't find one that works properly on all platforms)
3) Use startup javascript to detect base href & update (this is the solution I'm currently using)

Below is the code I'm using now in the index.html

It works well for my specific application. The issue I found is that if the user navigates to a page and then reloads it, the code will set the base href to that subpage (which will then fail). That is why I use the "/q/" after the base href to indicate the "top" of the navigation tree. This is a crude way of ensuring that the code detects the base href correctly (on reload or if the user bookmarks the page from one of the subpages).

```
  <!-- Set in code below, dynamically based on hosting <base href="/" />  -->
    <script>
        // set base href dynamically based on hosting location
        // All route have /q/ prefix to stop this code from failing if a user bookmars "http://server/somepath/q/login" for example
        // Base href only used up to the fixed /q/ prefix (if present)
        var base = document.createElement('base');
        var newBase = `${window.location.pathname}`;
        // Strip if /q/ present
        if (newBase.includes("/q/")) {
            newBase = newBase.substring(1, newBase.indexOf("/q/") + 1);
        }
        // Ensure initial slash present
        newBase = (newBase.startsWith("/") ? "" : "/") + newBase;
        // Ensure trailing slash present
        newBase += (newBase.endsWith("/") ? "" : "/");
        base.href = newBase;
        console.log(`Base href set to ${newBase}`);
        document.getElementsByTagName('head')[0].appendChild(base);

    </script>
```

**Comment by javiercn** [comment]
@nbarkhina thanks for contacting us.

If you are using a standalone app, then you'll have to have an additional processing step to change the entry point at publish time.

If you are using a hosted app, you can replace index.html with a razor page and compute the proper base tag there.
