### ISSUE TITLE
Unable to debug client-side Blazor WebAssembly hosted by ASP.NET Core inside a Docker container

### ISSUE THREAD

**Issue by minameismud** [dotnet/aspnetcore#22092]
Visual Studio 2019 16.6, Blazor 3.2, Edge 81.0.416.77

Starting with a new Blazor WebAssembly App, checking the ASP.NET Core hosted option, verify the debugging steps on [the MSDN Blazor WA debugging page](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1) work (ie. stick a breakpoint on line 14 of Counter.razor, run app, verify breakpoint is hit when the button is clicked). This works for me.

Right click the server project, Add -> Docker Support (Linux OS). Try the debug test again. Breakpoint is not hit. Is this because the remote debugging port isn't being exposed on the container? 

When I hit Shift+Alt+D in my browser, it tries to load `http://127.0.0.1:37557/?url=https%3A%2F%2Flocalhost%3A32770%2F` but fails with `ERR_CONNECTION_REFUSED` in the browser. If I stop and restart debugging, hit Shift+Alt+D again, the port off 127.0.0.1 changes. Is there a setting I can apply to set that remote debugging port to a fixed value so I can expose it in the docker startup?

**Comment by javiercn** [comment]
@minameismud thanks for contacting us.

This is a current limitation we are aware of. The issue is caused due to the fact that the proxy server runs within the asp.net core host inside the container.

We are looking how we can improve the experience in the future, but for the time being we recommend you debug outside the docker container.
