### ISSUE TITLE
[Blazor] Rendering is performed before the initialization finishes

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#22147]
When overriding OnInitializedAsync method it's visible the rendering is not waiting the initialization is complete because the page loads incorrectly.

The steps to reproduce it are

1. Create new page
2. Override OnInitializedAsync method
```
protected override async Task OnInitializedAsync()
{
     await doSomethingAsynchronously(); 
}
```
3. Put a breakpoint before the async method and another after the async method
4. Run the app.
5. You will see the first breakpoint is hit, then press F5.

Observe the page is rendered, then the second breakpoint is hit.

**Comment by mrpmorris** [comment]
This is as designed, so the user isn't kept waiting for potentially long periods of time just looking at nothing.

**Comment by arivoir** [comment]
Makes no sense, if the user want to have that behavior can just call the async method and avoid awaiting it. Actually it wouldn't use the OnInitializedAsync method, it would use OnInitialized instead. What about the other case, the user needing an async method to complete to show the UI?

**Comment by mrpmorris** [comment]
If you don't want anything rendered until after your await you can have a boolean field in your component and wrap your razor markup with `@if (MyField`

Then set it to true after your await completes

**Comment by javiercn** [comment]
I didn't realized this wasn't properly answered, sorry about that.

OnInitializedAsync as well as OnParametersSetAsync will render the UI right after the first asynchronous work happens. That's to support scenarios where you want to display the UI while the data is being loaded. If you don't want this behavior, you can inherit from IComponent directly and have full control of when and how the render happens.

I understand this might not be what you expected to hear, but this is a design decision we made quite a while ago and we don't have plans to change it, since it would be a huge breaking change.

Hope this helps.
