### ISSUE TITLE
code flow with PKCE + client_secret in Blazor webassembly authentication?

### ISSUE THREAD

**Issue by lindespang** [dotnet/aspnetcore#22193]
Hi!

My companys (legacy) ID provider only supports PKCE _together_ with a client_secret from a public client. **I know this is not how it's usually done for public clients and we are shipping a new ID provider later this year that does not require client_secret for public clients**

So what im looking for is if there is any 'hack' or legit way to send back a (not so secret) client secret to our provider after the `authentication/login-callback` (endpoint from example here: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1) and still benefit from the nice features that the webassembly authentication package provides.

There is no property exposed for client_secret (understandably) in the OidcProviderOptions class so im out of luck there https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.oidcprovideroptions?view=aspnetcore-3.1

To wrap it up: Is there any way to provide a client_secret to the provider using the webassembly authentication package? If there is not then I **don't** expect or suggest it to be introduced either, im just trying my luck for a workaround.

Best regards
Victor Lindespång

**Comment by javiercn** [comment]
@lindespang thanks for contacting us.

No, we didn't include that in the first release and don't plan to include it, since we don't have a way of securing the secrets in WebAssembly and can result in people accidentally leaking secrets.

The only way I can think of doing this is by hacking around the JS internals of the authentication service, and that's something I don't recommend since we consider it an implementation detail that might change in the future.

**Comment by lindespang** [comment]
@javiercn Thanks for the reply, I guess I'll stick to Blazor server until we release our new provider.
