### ISSUE TITLE
Fix warning "Atleast for one assembly start time was not obtained due to tag not present or parsing issue"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22241]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens while publishing quarantined test results. Whole warning text:

> ##[warning]Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly
> ##[warning]Atleast for one assembly time tag is not present, total run duration will now be summation of time from all test runs

**Comment by dougbu** [comment]
👀

**Comment by HaoK** [comment]
Meta question, why do we need to run quarantined tests as part of our ci builds at all?  Maybe we could just move this job to the helix quarantined pipeline (and make that the dedicated quarantine run for everything not just helix) and worry about warnings there later (if ever)?

**Comment by HaoK** [comment]
This also has the nice sideffect of getting rid of quarantine test results in our ci runs which is just noise when we see those failures

**Comment by dougbu** [comment]
If the quarantined test pipeline instead ran _every_ test (quarantined or not) without splitting things in two that might be :ok: However, I'd be concerned about the additional resources tied up duplicating work done in the rolling builds.

**Comment by dougbu** [comment]
Simple options we talked about:
- Find a way not to submit Helix jobs that would be empty. This has the nice side effect of reducing our load on Helix queues.
- Add an unconditionally-successful quarantined test to all test assemblies.

In addition, could change our Helix test runner to delete empty test result files -- before the Python stuff tries to submit those results to AzDO.

**Comment by HaoK** [comment]
I thought this issue is just talking about build warnings/logs.  Right now we are running things twice, once in the windows test ci.yml, and again in the helix pipeline

**Comment by HaoK** [comment]
So we could either just stop running the windows tests entirely, or run them both on the helix pipeline if we really want, that's not going to be any worse than what we do today in resources no?

**Comment by HaoK** [comment]
To be precise, we are doing slightly different things.  Helix quarantine pipeline does a helix run of all quarantined tests.  The windows test job does a ci build with RunQuarantinedTests = true, its probably a very similar set, but there might be some slighty differences in test results...  But given that we only look at flaky test data for helix runs...  What's the point of running the windows test job  quarantined tests at all?

**Comment by HaoK** [comment]
Also, this error doesn't exist on helix test jobs, because we don't use the publish test results task, the helix runner scripts directly upload the test results to azdo, so the helix quarantined jobs don't have this warning issue

**Comment by dougbu** [comment]
We have two categories of quarantined tests: Those that run on Helix and those that don't. If the aspnetcore-quarantined-tests pipeline redoes anything that also runs in aspnetcore-ci or aspnetcore-ci-official, I'm fine reducing what aspnetcore-ci and aspnetcore-ci-official are doing and focusing on the reliable tests there.

I would extend this to aspnetcore-helix-matrix too i.e. don't run quarantined tests anywhere but in the aspnetcore-quarantined-tests pipeline.

**But** I don't think it's a good idea to transfer "600+" warnings from one pipeline to another and call that an actual improvement.

**Comment by HaoK** [comment]
Well my main point is that I don't think the non helix quarantined runs are even being looked at, so the win win is to just stop running the non helix quarantined tests completely, the warnings go away, and its not like we are actually looking at those results anyways.

**Comment by dougbu** [comment]
I disagree with no longer running tests that we have _chosen_ to quarantine and not skip. Someone given an issue to unquarantine on of those tests can always check the AzDO test analytics instead of using the (broken) What's Broken application. This is something we'll need to do anyhow 'til What's Broken isn't broken.

**Comment by HaoK** [comment]
I still don't think we are quite talking about the same thing. Most quarantined tests are run twice right now, once in the windows test job, and again in the helix-quarantine-pipeline.  I would guess azdo test analytics should work on both of those pipelines.  So the only tests that would no longer be part of the quarantined runs would be in the handful of test assemblies that aren't running.  Those wouldn't have shown up on what's broken analysis either anyways.  The only point I'm trying to make, is these warnings are generated by mostly redundant work

**Comment by dougbu** [comment]
I may be missing something @HaoK 

The build steps that execute quarantined tests in ci.yml don't exist anywhere else; they handle _only_ tests that don't (yet) run on Helix. If we wrapped those steps into new jobs in quarantined-tests.yml, all we'd be doing is moving the warnings around. This issue is about **fixing** warnings. (As I said above, I'd be fine moving where the non-Helix quarantined tests run but that doesn't fix this issue.)

In any case, does the "Tests: Helix x64" job run quarantined tests on the Helix agents? Does the "Test: Templates - Windows Server 2016 x64" job run quarantined tests (it lacks `/p:SkipHelixReadyTests=true`)?

----

The more I think about it, less sure I am this issue is just about quarantined tests. For example, does `$(p:SkipHelixReadyTests)` cause empty test runs and lead to the warnings?

**Comment by HaoK** [comment]
Ok yeah I think we both were slightly missing things.  So to summarize the state of things to get us on the same starting point:

1. aspnetcore-quarantined-tests is the pipeline for https://github.com/dotnet/aspnetcore/blob/master/.azure/pipelines/quarantined-tests.yml, and today it only runs the helix quarantined tests, and it only runs on the PR queues (not the full matrix)
2. The new helix-matrix does not run any quarantined tests, its only running the non quarantined tests on the full helix queue matrix
3. The ci.yml is only running quarantined tests that are not helix enabled as part of the normal test jobs. 

Number 3 are what's causing warnings due to empy test results xml since 95% of tests are on helix and generate no tests, these are not a problem in the helix quarantine runs because they do not use PublishTestResults at all. 

Given the end goal is to move all tests to helix pipelines, and get rid of the azdo test jobs.  I don't think its all that unreasonable to hide the warnings in the non ci-pipeline, since the warnings will just go away when we finish helixifying the tests, while the other warnings are unlikely to go away as a free sideeffect

**Comment by dougbu** [comment]
Hiding those warnings won't make the warnings go away until and unless _everything_ moves to Helix. Let's make progress here rather than waiting for some of the (large) migrations to complete.

See https://dev.azure.com/dnceng/internal/_build/results?buildId=660310&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=3ef8c84e-db33-5c28-256d-eed52132fc4e&l=12 for example. That's one of these warnings in a regular on-agent test run.

**Comment by dougbu** [comment]
Working on this in #22406. That's not quite ready because I need to play a bit more to get an unquarantined test running in the Blazor templates test assembly. That one has `[assembly: QuarantinedTest(...)]` and trait discovery looks at _all_ applied traits, not just the one(s) closest to the test method.

**Comment by BrennanConroy** [comment]
Only 4 more warnings of this left it looks like.

https://dev.azure.com/dnceng/public/_build/results?buildId=669291&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4523cb61-dcda-536e-8200-61a3fdfb2c8f&l=13

**Comment by dougbu** [comment]
Yeah, we can't do any better because (as I said in #22406) the xUnit console runner doesn't support trait filters. In addition, traits can't be overridden -- just added to. That's why I didn't close this issue.

We probably won't be able to close this issue for realz until and unless we
1. switch to `dotnet test` or `dotnet test` everywhere
2. move the Blazor template tests to Helix
3. remove the `[assembly: QuarantinedTest(...)]` attribute in the Blazor template test assembly

**Comment by dougbu** [comment]
This issue was resolved when #23521 went in. See https://github.com/dotnet/aspnetcore/commit/71e388eab781698fa8e4e8afa5f3df464788f4c1#diff-89fc80cfb8ae7a3a32df121a2bd8c6372be4a38142d8b7639e7eac63100175f0L14

**Comment by dougbu** [comment]
Thanks to @pranavkm for cleaning up the last of this noise
