### ISSUE TITLE
Fix warning "warning : This project has native dependencies which were not built. [F:\workspace_work\1\s\src\SiteExtensions\Runtime\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj]"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22250]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during SiteExtension build. Full warning text below:

> F:\workspace\_work\1\s\eng\targets\ResolveIisReferences.targets(37,5): warning : This project has native dependencies which were not built. Without this, tests may not function correctly. Run `build.cmd -native` to build native projects. Run `build.cmd -managed -native` to build both C# and C++. [F:\workspace\_work\1\s\src\SiteExtensions\Runtime\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj]

**Comment by dougbu** [comment]
Fixed between builds [20200529.9](https://dev.azure.com/dnceng/internal/_build/results?buildId=664608) and [20200529.10](https://dev.azure.com/dnceng/internal/_build/results?buildId=664692) of our official pipeline. The only new commit was dotnet/aspnetcore@14d6b6e28661 My changes in dotnet/aspnetcore#22017 solved this one because all native assets are now created at the start of all Windows jobs on the CI.
