### ISSUE TITLE
How to handle No Internet Connection in Blazor WebAssembly

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#22278]
I am developing Blazor WebAssembly Hosted App.
How do i detect that error is due to no internet connection and retry it automatically as soon as internet become available?

**Comment by SteveSandersonMS** [comment]
In general, it's a bad idea to try to detect "no internet connection" because reality is more complicated than that.

 * Maybe they really do have no internet connection
 * Maybe they have an internet connection, but are stuck behind a captive portal, so the server responses will be incorrect (e.g., 302 to some kind of wifi provider login screen)
 * Maybe they have an internet connection, but it's so slow that responses will take hours to arrive, so it's effectively just as bad as no internet connection

Instead of trying to detect *why* a response failed, it's wiser just to handle failures in a graceful way regardless of the reason.

You cannot know "when an internet connection becomes available" for the same reasons described above. Maybe the device thinks it had an internet connection all along, but some aspect of the server's reachability has changed without the device having any way to know about that. Instead, if a request fails, make sure the user has a way to retry. Consider even auto-retrying at some interval if you want.

BTW some people may suggest using the `navigator.onLine` property. This is an old concept that should be considered obsolete. `navigator.onLine` is not reliable and should not be used for the same reasons I've listed above.

**Comment by nssidhu** [comment]
@SteveSandersonMS  Thanks for the guidance on gracefully handling no connectivity, but unless i know(or can detect) what has gone wrong how do i handle it ?  May be some more clarity like an example might help better understand what you are sugesting.
I am still lost on it.

**Comment by SteveSandersonMS** [comment]
When performing an HttpClient request, wrap it in a `try/catch`. In the `catch`, set some flag that causes the UI to display a message like "There was a problem submitting the request" and offer a button to retry.

**Comment by nssidhu** [comment]
Thanks for the explnation.

I prefer, that if we could let the user know that there is a problem, it gives him an opportunity to take corrective action rather than waiting for things to resolve on its own.

Say for example user is coming out of the flight and has turned on flight mode and if it is detectable and we let user know that give him opportunity to disable the flight mode, or simply letting him know that there is no internet might be good enough.

For another example, say user connected to bad wifi network and if we could let user know that network is unstable or slow, that gives him an opportunity to join different wifi network.

May be user is inside a building where there is poor network and if we let him know that there is no connectivity that may give user an opportunity to go on wifi.

so i am of view that letting the user know that there is connectivity problem gives him an opportunity to correct things rather than leaving the user guessing that an app is buggy.
