### ISSUE TITLE
Some ideas for blazor

### ISSUE THREAD

**Issue by mrhuo** [dotnet/aspnetcore#22270]
### Package all .dll files to one

So many .dll files now

### Just pick the reference class and method only in dlls

This maybe greatly reduce DLL file size, now is too large, download too slow

**_I know it's very difficult to implement these functions. sad for this._**

**Comment by arviedelgado** [comment]
Have you tried the publishing options?
- Produce single file
- Trim unused assemblies

![image](https://user-images.githubusercontent.com/11804514/83018034-392beb80-a057-11ea-9619-378cc9bd8e13.png)

**Comment by mrhuo** [comment]
Thx very much, Trim unused assemblies this options in witch version?

**Comment by mrhuo** [comment]
This publish optional may not be publish Blazor WebAssembly App,

**Comment by javiercn** [comment]
@mrhuo thanks for contacting us.

We've already investigated these directions:
> Package all .dll files to one

This doesn't impact size significantly and has an impact in caching since a change in a single assembly invalidates the entire bundle

> Just pick the reference class and method only in dlls

Not sure what you mean by this. We already do IL linking on the published build output.

**Comment by mrhuo** [comment]
My IDE version is Microsoft Visual Studio Professional 2019  16.6.0，I can't found the publish options your say. I don't know which version will provide this options?

**Comment by mrhuo** [comment]
@javiercn thanks for your comment
