### ISSUE TITLE
Razor Components are not disposed in reverse order of their initialization

### ISSUE THREAD

**Issue by JinShil** [dotnet/aspnetcore#22341]
### Describe the bug
For a list of razor components instantiated in one order, I suggest they should be disposed in the opposite order.  Currently, they are disposed in the same order as they were instantiated.  This poses a problem in more involved scenarios where external entities (in my case, sprites in a scene) should be destroyed in the reverse order from which they were created.

### To Reproduce

Strings.razor
```C#
@page "/strings"

<button @onclick="BindList1">List1</button>

<button @onclick="BindList2">List2</button>

@foreach(var i in _currentList)
{
    <StringView @key="@i" Text="@i" />
}

@code {
    List<string> _list1 = new List<string>()
    {
        "one",
        "two",
        "three"
    };
    List<string> _list2 = new List<string>()
    {
        "four",
        "five",
        "six"
    };

    List<string> _currentList;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        _currentList = _list1;
    }

    void BindList1()
    {
        _currentList = _list1;
    }

    void BindList2()
    {
        _currentList = _list2;
    }
}
```

StringView.razor
```C#
@implements IDisposable

<div>@Text</div>

@code 
{
    [Parameter]
    public string Text { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();

        Console.WriteLine("Initializing StringView: " + Text);
    }

    public void Dispose()
    {
        Console.WriteLine("Disposing StringView: " + Text);
    }
}
```

Console output after pressing "List2" button:
```
﻿Initializing StringView: one
Initializing StringView: two
Initializing StringView: three
Initializing StringView: four
Initializing StringView: five
Initializing StringView: six
Disposing StringView: one
Disposing StringView: two
Disposing StringView: three
```
I believe the last 3 lines should be...
```
Disposing StringView: three
Disposing StringView: two
Disposing StringView: one
```
... in reverse order from which they were initialized.  I would also be nice if `_list1` was disposed before `list2` was created.

**Comment by SteveSandersonMS** [comment]
We've never specified any guarantees about disposal order, so I'd recommend not taking a dependency on this.

You could modify your disposal logic so that it executes in a particular order. For example, instead of `Dispose` actually doing the disposal immediately, change it to notify some service that tracks creation/disposal order and actually disposes everything that is flagged for disposal in the right order.

If there's significant customer demand for changing the built-in logic we could certainly consider doing that in the future, but otherwise I'd recommend handling this in your own application logic. As you can imagine, we have many other highly-prioritised work items that would come ahead of this. Hope that's OK!
