### ISSUE TITLE
Enhance QueryString in blazor

### ISSUE THREAD

**Issue by Thaina** [dotnet/aspnetcore#22388]
I would like blazor to provide better management and handler for querystring of current page url

### [FromQuery] attribute for two way binding

It should allow binding to a field and/or property, so that it would always binded with query string with the same name as the property

```C#
@code {
        [FromQuery]
	int size = 0;
        [FromQuery("queryName")]
	int internalName = 0;
        [FromQuery("date","yyyyMMddHHmmss")] // with format?
	DateTimeOffset internalName = DateTimeOffset.Now;
}
```

### NavigationManager

Should provide API for URI manipulation and history

```C#
public static Uri WithQuery(this Uri uri,string name,string value)
{
    // anything better with the same result?
    var query = HttpUtility.ParseQueryString(uri.Query);
    query[name] = value;
    return new UriBuilder(uri){ Query = query.ToString() }.Uri;
}

void GetAbsoluteUri(this NavigationManager manager) => manager.ToAbsoluteUri(manager.Uri);

// navigateTo(uri.WithQuery())
void SetQuery(this NavigationManager manager,string name,object value);
void SetQuery(this NavigationManager manager,params (string name,object value)[] values);

string GetQuery(this NavigationManager manager,string name);

/////////

// localhost/?q=0 >>> localhost/?q=1
navManager.SetQuery("q",1);
navManager.SetQuery("q",int.Parse(navManager.GetQuery("q")) + 1);
```

Underlyingly should just call `history.pushState` if available

**Comment by TanvirArjel** [comment]
I have created a library called `TanvirArjel.Blazor` which extending the `NavigationManager` to facilitate the query string handling in Blazor and many more. Here is the source code: 

https://github.com/TanvirArjel/TanvirArjel.Blazor/blob/main/src/TanvirArjel.Blazor/Extensions/NavigationManagerExtensions.cs

**Comment by terrajobst** [comment]
I wonder if the `NavigationManager` APIs are needed at all. It seems desirable that when I bind a property to a query string that changing the property can also cause the query string to change. This design also avoids users having to format the values as strings. However, I can see an argument that this behavior should be opt-in. One option is to use a secondary attribute, another is to extend the attribute:

```C#
@code {
    [QueryParameter("q", IsTwoWay=true, ReplaceHistory=true)]
    string Query { get; set; }
 
    [QueryParameter(IsTwoWay=true)]
    int Page { get; set; }
}
```

Now imagine my search form's input is data bound to the `Query` property and is synced on each key stroke. The URL is now updated on every keystroke but the history is replaced instead of getting pushed a new state each time. Neato!

Further imagine I have paging buttons that handle navigating to different pages in my result. Again, just updating the `Page` property will be reflected in the URL but each time I navigate, I get a new state, so back and forward buttons work as you'd expect. Double neato!

**Comment by AmSmart** [comment]
@terrajobst This looks good!

**Comment by Thaina** [comment]
> I wonder if the `NavigationManager` APIs are needed at all. It seems desirable that when I bind a property to a query string parameter that changing the property can also cause the query string to change

Sometimes we might need to have dynamic name of querystring, that was api to allow that

```C#
var jobj = JObject.Parse(@"{ "name0" : "value0","name1" : "value1","name2" : "value2" }"); // actually got from RPC

foreach(var prop in jobj.Properties())
    navManager.SetQuery(prop.Name,prop.Value);
```

**Comment by terrajobst** [comment]
> Sometimes we might need to have dynamic name of querystring, that was api to allow that

That makes sense to. Sadly, it seems the team isn't going to prioritize this 😢

**Comment by Thaina** [comment]
@terrajobst I think they have planned alright. It actually pretty solid so there are not much to talk about but I don't think they missed it

https://github.com/dotnet/aspnetcore/issues/33338#:~:text=Getting/setting%20query%20parameters%20procedurally

**Comment by terrajobst** [comment]
Nice! I just misunderstood the comment from the bot. Please ignore me, I don't know what I'm talking about :-)

**Comment by MackinnonBuck** [comment]
Related querystring work has been completed as tracked in #33338.
