### ISSUE TITLE
[Blazor] Allow inheriting of base pages

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#22411]
There is currently no way to create a base page with any kind of content.

For example, it is possible to create a component that can be used within a page

```
<Card>
  Some content
</Card>
```

But descending a page from `Card` will only display "Some content" and not the content from `Card`

```
@inherits Card
Some content
```

My aim is to have a component that uses IScopeFactory to create its own `IServiceProvider` (like `OwningComponentBase`) that also adds the `IServiceProvider` as a `CascadingValue`.

**Comment by chucker** [comment]
This seems to overlap with the purpose of layouts.

In what order would the inherited content appear? There would probably have to be a special `@InheritedContent` property that’s placed somewhere in the markup?

**Comment by mrpmorris** [comment]
A layout would be shared across multiple pages. If I want to (for example) create a CascadingValue in the base page (which I do, a `IServiceProvider`) then using layouts isn't an option because the IServiceProvider from the layout would be shared across multiple pages.

**Comment by chucker** [comment]
> Perhaps BeforeBuildRenderTree and AfterBuildRenderTree virtual methods on ComponentBase so they can prepend / append some UI via code.

Ah yes. Makes sense to me.

**Comment by SteveSandersonMS** [comment]
Generally we wouldn't recommend inheritance for cases where component composition is the intended mechanism.

The scenario you're describing appears to be a shared component that wraps something around its content. There is a built-in mechanism for that - `ChildContent`, from the normal component composition mechanism.

Strictly speaking, you *can* call `@{ base.BuildRenderTree(__builder); }` from within a component's rendering logic. That's not massively useful because it doesn't offer a way to inject content at a specific place inside the base render output, but again that's exactly the scenario that `ChildContent` is for.

It isn't a goal to make inheritance a suitable way of achieving things that are intended to be achieved through composition.

**Comment by mrpmorris** [comment]
@SteveSandersonMS My goal is to write an `OwningComponent` type component that can be inherited by a page, but adds a `CascadingValue Value=ServiceProvider TValue=IServiceProvider`

How would you recommend achieving this?

**Comment by SteveSandersonMS** [comment]
> My goal is to write an OwningComponent type component that can be inherited by a page, but adds a CascadingValue Value=ServiceProvider TValue=IServiceProvider

It sounds like you just want to make available an `IServiceProvider` to other components. In that case I'd do it through DI. Components can either:

````
@inject IServiceProvider Services;
```

... or if you're trying to put your own semantics on it:

```
@inject YourCustomServiceProvider Services;
```

... where the custom type there has its own special logic around resolving services.

Inheritance is rarely a good fit for cross-cutting concerns like injecting a particular service, since of course you can only have one base class, yet you have many cross-cutting concerns.

**Comment by mrpmorris** [comment]
@SteveSandersonMS yes, I am trying to implement a system of a component that creates an SP, and consuming components that receive the same SP.

Without using a CascadingValue then I see no way of passing the SP down to all components within the content, and I can't automatically add a CascadingValue if my user is creating a page. 

What would you suggest?

**Comment by mrpmorris** [comment]
I don't feel this is resolved. Could it be reopened, please?

My ultimate aim is as follows

1. Create an `InjectScopedAttribute` that can be used instead of `InjectAttribute`
2. Create a descendant of `OwningComponentBase<IServiceProvider>`
3. The class should pass the `IServiceProvider` to a shared static method to fix up any `[InjectScoped]` dependencies on the component.
4. It should also set up a `CascadingValue` so that any components hosted by the component can access the same `IServiceProvider` and use the same shared static method to fix up `[InjectScoped]` dependencies.

I'm not actually trying to introduce content other than a CascadingValue.

The introduction of virtual `BeforeBuildRenderTree` and `AfterBuildRenderTree` methods on ComponentBase would be very useful.

**Comment by SteveSandersonMS** [comment]
Currently we're not planning to implement any feature for this, sorry!

We have a lot of much more highly prioritised items, the suggestion here doesn't seem to fit well within the existing API patterns, and there's already a way of creating a component that exposes a `CascadingValue` (even if it doesn't produce exactly the API shape you're describing):

```razor
<CascadingValue Value="new MyThing()" IsFixed="true">
    @ChildContent
</CascadingValue>

@code {
    [Parameter] public RenderFragment ChildContent { get; set; }
}
```

Hope this is OK. We're focused on more frequently-requested items.

**Comment by mrpmorris** [comment]
Component yes, but this is a request for pages.

I'll have to instruct people to add the same boilerplate code to every page

```
<CascadingValue Value=Service TKey=IServiceProvider>
   .... your page content here
</CascadingValue>
```

Not a huge price to pay, but boilerplate :)
