### ISSUE TITLE
Flaky test CanRenderTextOnlyComponent

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#22442]
https://dnceng.visualstudio.com/internal/_build/results?buildId=664692&view=ms.vss-test-web.build-test-results-tab&runId=20610968&paneView=debug&resultId=100295
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Hello from TextOnlyComponent
Actual:   
          ↑ (pos 0)
```

**Comment by captainsafia** [comment]
This issue is more or less related to the amount of time it takes to display the component. Selenium checks for the element in the UI before it has fully loaded.

One thing we can do to mitigate this is use an `Assert.Wait` check with a timeout to wait a little bit for the element to appear before bailing out. PR incoming.

**Comment by captainsafia** [comment]
Put in a fix for this. We can close it.
