### ISSUE TITLE
Explorer is not opening in the Firefox platform.

### ISSUE THREAD

**Issue by BerlyChristopher** [dotnet/aspnetcore#22540]
Hi Team,

We need to open the file explorer from the external span click by using the JS interop file. This operation is working fine in the Chrome browser and not opening in the Firefox browser. 

Please find the sample from the below link.
**Link:** http://dw.convertfiles.com/files/0704893001591273191/firefox_explore_issue.tar

Anyone help us to resolve the issue?

Regards,
Berly B.C

**Comment by BerlyChristopher** [comment]
Hi Team,

As we mentioned earlier, if we did the functionality for opening the explorer in the external button click in pure javascript, its working fine in the Firefox browser. But, when we do the same functionality in the Blazor platform with the help of JS interop, it's not working. Please find the sample from the below link.

**Sample Link:** https://stackblitz.com/edit/typescript-ldhxq2?file=index.html

Can anyone help us to resolve this issue?

Regards,
Berly B.C

**Comment by JeyanthVictory** [comment]
Hi There,

I am reiterating the issue described above.

In my application, I have a button and an input type of file both are hidden state wrapped with div. I also have a span with `<a>` element which displays Browse text.

When I click the Browse (i.e., `<a>` tag), I am calling the click method of button which inturn calls the click method of input type file in order to show the file explorer window.

Since I could not access DOM, I am using interop to achieve this. That is, I am invoking the interop file in the click handler of `<a>` element.

So my click handler in the interop js file will look like this.

`window.onUploadClick =  () => {
    document.getElementsByClassName('file-wrap')[0].querySelector('button').click();
    document.getElementById("click").addEventListener("click", function (e) {
     document.getElementById('file').click();
    })
}`

Now the problem is , file explorer is opening in chrome but not in Firefox.

Any help or solution would be greatly appreciated.

Thanks,
Jeyanth.

**Comment by BerlyChristopher** [comment]
Hi There,

 

I am reiterating the issue described above.

 

In my application, I have a button and an input type of file both are hidden state wrapped with div. I also have a span with `<a>` element which displays Browse text.

 

When I click the Browse (i.e., `<a>` tag), I am calling the click method of button which inturn calls the click method of input type file in order to show the file explorer window.

 

Since I could not access DOM, I am using interop to achieve this. That is, I am invoking the interop file in the click handler of `<a>` element.

 

So my click handler in the interop js file will look like this.

 

`window.onUploadClick =  () => {
    document.getElementsByClassName('file-wrap')[0].querySelector('button').click();
    document.getElementById("click").addEventListener("click", function (e) {
     document.getElementById('file').click();
    })
}`

 

Now the problem is , file explorer is opening in chrome but not in Firefox.

 

To demonstrate the problem, here I attached a simple project.

 

[FileUpload.zip](https://github.com/dotnet/aspnetcore/files/4994210/FileUpload.zip)

 


Any help or solution would be greatly appreciated.

 

Thanks,
Berly B.C
