### ISSUE TITLE
Forced completion of lambda parameter name as a similar type name

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22754]
![IW2215cvtp](https://user-images.githubusercontent.com/1874516/84213517-bf8ff680-aa75-11ea-8acd-23b07b558f20.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by danroth27** [comment]
For comparison, here's what VS 16.6 does:
![y197maWBUb](https://user-images.githubusercontent.com/1874516/84213760-5c529400-aa76-11ea-911f-c0946a4d1d55.gif)

**Comment by NTaylorMullen** [comment]
This looks to be due to pre-select limitations in completion.

**Comment by dibarbet** [comment]
Not a roslyn issue, but here is the LSP client issue - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1139727

**Comment by NTaylorMullen** [comment]
> Not a roslyn issue, but here is the LSP client issue - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1139727

So given pre-select is working I thought this would be solved but there's actually more going on. So when Dan is typing the completion event has already happened and pre-select has already been indicated in the initial response. So unless Roslyn is saying "isIncomplete: true" for every character in order to indicate that the LSP platform should re-ask for more completions then this wont work as expected. @dibarbet is that what you all plan to do?

**Comment by dibarbet** [comment]
@NTaylorMullen do you mean when the ( is typed and the "Todo" type shows up selected?  So after you type lower-case "t" we want the 'pre-selected' item to be "todos" instead of "Todo"?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you mean when the ( is typed and the "Todo" type shows up selected? So after you type lower-case "t" we want the 'pre-selected' item to be "todos" instead of "Todo"?

No, it's actually here: `@todos.Count(to|`. The expectation is that "nothing" is selected so a user can provide their own lambda argument name; however, `Todo` (the Type) stays selected because the LSP platform filters down to the most relevant item while typing.

**Comment by dibarbet** [comment]
@NTaylorMullen ahh I think we need to be in suggestion mode when inside the lambda.  It looks like we're not right now.  That may just be a bug.

**Comment by dibarbet** [comment]
@NTaylorMullen does this look like how you would expect it?
![suggestion_completion](https://user-images.githubusercontent.com/5749229/91783275-89fe3380-ebb4-11ea-9a83-890e211525ed.gif)

Seems like there is some better sorting that can be done on the client side but otherwise seems to match 16.6 better

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen does this look like how you would expect it?

Yup! I assume at the beginning of the line if you type `programs` (outside of a lambda) it gets auto-selected and is not in "sugestion mode" correct?

**Comment by dibarbet** [comment]
> Yup! I assume at the beginning of the line if you type `programs` (outside of a lambda) it gets auto-selected and is not in "sugestion mode" correct?

Yeah only special occurences (like lambdas) go into suggestion mode.
