### ISSUE TITLE
CSS isolation: CSS parser/rewriter

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#22773]
This is one of the work items needed for https://github.com/dotnet/aspnetcore/issues/10170

Since we need to update CSS selectors, we need a way to parse and rewrite CSS generally.

**Comment by KKacer** [comment]
Hello @SteveSandersonMS 
Pardon me, if you think that I shouldn't add a post here,
I have added this in the **CSS Isolation** topic as well, but mainly because parts of the features below could be related what you have defined specificly here, I decided to re-post it here, which I hope may give and bring some new ideas.

Praise you and thanks for the great work you have done and doing already.
Below is the post:
-------------

Waiting for such features a while, I implemented my own structure, with some hardship.
Though it works now, I afraid after the release of this feature which could be a new standard for achieving the same result I will be forced to change every code and the infrastructure I built.
As a sum up including my earlier mentioned/opened topics.

Here are the related features requested (based on my ideas):

**A. SCSS.**
```
@Scss{
}
```
------------
**B. SCSS imports via libraries (without compilation)**

Better than that, the Scss be able to import other Scss files, even from other assemblies.
Which they could be libraries dedicated to bring their own styles, base styles.

```
@Scss{
// Something not definable yet:
@import External-Assembly1; base/base.scss;
// We can define a new format, or a new routing mechanism to target external assemblies.
@import lib1.scss;
// the styles
// other styles
}
```

Cause of lack of such a feature I wrote MSBuild tools to copy/move/compile my scss files from my base project to every other projects, so in a full solution I may have tens of duplicated scss files in every project, cause the system can't route/find them in other assemblies.

--------------
**C. Styling separation:**

To avoid messing up a component code, it is much better to separate the code and the style in a code-behind way.
So, it will be:

```
Component1.razor
Component1.scss
```
---------------
**D. Styling configuration:**

If we be able to have a type of .config file specifically for the styling section it could be nice, even in my personal opinion file-specific when needed.
For example:

**Component1.scss.config**
```
minification: true;
obfuscation: true;
lazyload: true;
addbrowserspecificcodes: true;
renderindividually: false;
```
---------------
**E. A new custom format like: MCSS**

Not 100% sure, less priority than the previous mentioned parts
but having a new file format like MSCSS (Microsoft SCSS), or BSCSS for (Blazor SCSS)
may help in some scenarios like the extra routing, more customizability, more flexibility, ...
This way you can get the custom parts, the configuration, routing data, ...
and finally you give the duty for the last compilation to the SCSS compiler.

If we have such a format like (MCSS) we will be able to define something like this:
`@import External-Assembly1; base/base.scss;`
when `base/base.scss` be in another assembly named **External-Assembly1**.

----
**I believe number 1,2,3 are a must, 4 and 5 can be great options to have.**
