### ISSUE TITLE
Migrating 2.1 builds to AzDO

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22854]
- Question: Do we have an issue tracking this yet (cards can't be assigned)?
- May also want / need equivalents of the following build configurations:
  - [builds of aspnet-internal-tools](http://aspnetci/viewType.html?buildTypeId=AspNetEf_InternalBuildTools&tab=buildTypeSettings)
  - [builds of aspnet/AspNetCoreLocalFeed](http://aspnetci/viewType.html?buildTypeId=Lite_Infrastructure_AspNetCoreLocalFeed&tab=buildTypeSettings)
  - [builds of aspnet/AspNetWebHooks](http://aspnetci/viewType.html?buildTypeId=AspNetEfOob_AspNetWebHooks_AspNetWebHooks&tab=buildTypeSettings) and [builds of aspnet/AspNetWebHooks-Signed](http://aspnetci/viewType.html?buildTypeId=AspNetEfOob_AspNetWebHooks_AspNetWebHooksSigned&tab=buildTypeSettings)

Believe @pranavkm and @mkArtakMSFT should decide on the legacy WebHooks builds while @joeloff owns aspnet/AspNetCoreLocalFeed. Suggest building aspnet-internal-tools is a requirement only as long as we're signing on TeamCity i.e. not much longer.

**Comment by joeloff** [comment]
The local feed only supported VS2017, and only 1.x. Both 1.0/1.1 are end-of-life. Unless we have an incident that's so severe and requires us to service 1.x I doubt we'd rebuild those installers. Also, depending on the changes to the packages, e.g. if something like ASP.NET rebuilds in 1.x, it actually requires rebuilding things like web tools because it carries the 1.x templates in VS 2017

**Comment by javiercn** [comment]
@dougbu are you saying that if we migrate 2.1 to AzDO we don't need to migrate aspnet-internal-tools? (Providing we do everything for 2.1 within AzDO, including the signing)

I remember from a previous discussion that we already have 2.1 builds running on AzDO (for PRs at least). What would be the remaining work here? Can you T-Shirt estimate it? (Assuming we move 2.1 builds and nothing else).

Would it be reasonable to keep the VMs around but turned off so that we could fallback to teamcity in case we need it? (If we needed for some reason to patch something critical on webhooks or similar)

**Comment by javiercn** [comment]
> The local feed only supported VS2017, and only 1.x. Both 1.0/1.1 are end-of-life. Unless we have an incident that's so severe and requires us to service 1.x I doubt we'd rebuild those installers. Also, depending on the changes to the packages, e.g. if something like ASP.NET rebuilds in 1.x, it actually requires rebuilding things like web tools because it carries the 1.x templates in VS 2017

@joeloff if we had to do this, how big of a risk would be if we had to create this within AzDO, would it be something like 1 day of work or more like 1 week? Would you be confortable having to deal with this in case we had to patch 1.x given how unlikely the situation is?

**Comment by dougbu** [comment]
> are you saying that if we migrate 2.1 to AzDO we don't need to migrate aspnet-internal-tools?

That should be true.

> What would be the remaining work here?

I don't remember exactly but am sure we lack most of the later stages of the TeamCity build process in our AzDO pipelines. That includes at least signing and publication. May also need to store packages on the \\aspnetci share and probably need to make the aspnetcore-ci pipeline reliable enough to remove the need for 
aspnetcore-pr-validation-temp.

The big question here is how complicated this will be without Arcade to help us out. The Arcade SDK is _not_ intended for anything prior to the 3.0 release. Switching ProdCon to run an AzDO pipeline is pretty simple (we do that for dotnet/extensions builds of 2.1). A smaller question is how much we can copy over from the dotnet/extensions AzDO pipeline; dotnet/aspnetcore is a more complicated beast but we might get lucky.

> Can you T-Shirt estimate it? (Assuming we move 2.1 builds and nothing else).

I'm not sure except to say it's not likely small.

> Would it be reasonable to keep the VMs around but turned off so that we could fallback to teamcity in case we need it? (If we needed for some reason to patch something critical on webhooks or similar)

I don't think this would be reasonable or necessary for dotnet/aspnetcore builds.

But we may need a way to build aspnet/aspnetwebhooks and aspnet/aspnetwebhooks-signed i.e. legacy WebHooks. I defer to @mkArtakMSFT and @danroth27 on whether we'd **ever** build those repos again.

**Comment by dougbu** [comment]
Forgot to mention: The test matrix on TeamCity may also be larger than what we have in either existing 2.1 AzDO pipeline.

**Comment by dougbu** [comment]
@wtgodbe what work remains here❔

**Comment by wtgodbe** [comment]
> @wtgodbe what work remains here❔

None, the build succeeded yesterday, so we can close this!
