### ISSUE TITLE
Static fields in classes doesn't reset by RazorPage 

### ISSUE THREAD

**Issue by gfbahadir** [dotnet/aspnetcore#22874]
This is not actually a bug or feature but we were using a class that has a static field which is set once by a class that inherits RazorPage<T> in our project.
Basically what we wanted was a really short time memory storage that holds a simple value and returns it multiple times in a View without multiple redis cache queries...
And in this we didn't had any problems at .net core 2.2 which we were using for 11 months. The static field was set null right after the definition and it became null every time we requested a view.
After we upgraded to 3.1 we started to get some strange errors and what i have found is that static field is not set to null on every view render, it is set once after starting the project and does not get released after the view is rendered.
So something has changed in either RazorPage class or in the way that statics work in 3.1 and i just wanted to let you know since i did not see anything about this on "What's New" page for 3.1.
(Btw i fixed the issue by adding a constructor without parameters and setting that static field to null in it. So the class new constructor works but fields are not released from ram.)

**Comment by javiercn** [comment]
@gfbahadir thanks for contacting us.

I don't think there has been any behavior change in this area. Using static fields with RazorPages or Views is something that we discourage since it is not threadsafe and can lead to security issues like information leaks.

Given that this is the only report that we had from this and that it is a pattern we discourage, I'm going to close this issue since we don't plan to take action on it.

/cc: @pranavkm in case you want to add something else.
