### ISSUE TITLE
[Blazor WASM] Choosing cache location regardless of path

### ISSUE THREAD

**Issue by NateKomodo** [dotnet/aspnetcore#22937]
### Is your feature request related to a problem? Please describe.
When loading blazor from different paths (i.e. user was directly linked to /login instead of /), blazor creates a new cache for that path (see image below)
![image](https://user-images.githubusercontent.com/31631620/84598141-71f20000-ae60-11ea-8a1a-4301f58d79da.png)

### Describe the solution you'd like
A way (i.e. within Blazor.start) that allows you to specify a specific name for the cache store

**Comment by javiercn** [comment]
@NateKomodo thanks for contacting us.

Is the BaseUri on the document the same or different? If its different it is expected, since you can have different apps hosted within different base URIs on the url space. If the Base URI for the document is the host in all cases, then we might have an issue here.

/cc: @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
The cache name is computed from the base href, so I think this is behaving correctly already:

https://github.com/dotnet/aspnetcore/blob/74857c3e352755fa4c924d73c615b3e9113ea1a8/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L172-L173

@NateKomodo If you have more information to imply there's a bug, please let us know, otherwise this appears to be working as intended and it looks like there's an issue in your code.

**Comment by NateKomodo** [comment]
Its the same app but loaded from different base hrefs, so loading the site with the path of / or the path of /login (To load a specific page within the SPA after it loads), this creates a cache for both / and /login despite it being the same application. I'm requesting an option to override the name for cases like this where it is loaded from different paths but all the files are the same. Yes, that code is working as intended, but it doesnt handle cases where the same app is loaded with different relative paths.

**Comment by javiercn** [comment]
@NateKomodo you can disable the built-in caching and handle caching yourself by setting `BlazorCacheBootResources` to false within your project and using a custom resourcebootloader

**Comment by NateKomodo** [comment]
Guess i'll finally get around to writing a service worker then. It would still have been nice to see this as a feature though.
