### ISSUE TITLE
Model binding infinite loop (sample provided)

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#23154]
I'm trying to use a custom model binder within a loop. However it seems to get stuck in an infinite loop. The error I'm getting back is:

> InvalidOperationException: Collection bound to 'Images' exceeded MvcOptions.MaxModelBindingCollectionSize (1024). This limit is a safeguard against incorrect model binders and models. Address issues in 'WebApplication1.Controllers.ImageViewModel'. For example, this type may have a property with a model binder that always succeeds. See the MvcOptions.MaxModelBindingCollectionSize documentation for more information.

I think my issue is related to the one [here](https://github.com/dotnet/aspnetcore/issues/4939). However I have tried saying the following within my model binder but it didn't help:

```
bindingContext.BindingSource = BindingSource.Form;
```

I have attached a very basic example to illustrate the issue. Please run the app and submit the form and you should see the problem.

I'd really appreciate any help on this as I have already wasted too much time trying to figure this out. Thanks

[WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/4804908/WebApplication1.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
@pranavkm FYI

**Comment by pranavkm** [comment]
@nfplee `Images` is a collection property that uses the collection binder. `ImageViewModel` is a complex type that uses the complex type binder. The interaction of collection and complex type model binder needs to be precise otherwise you may run in to issues like the one you're seeing.

Collection binder continues binding as long as it's elements can be bound. Complex type binder will succeed as long as at least one of it's properties is bound using values from the request. `Base64EncodedFormFile` is bound from the request and always succeeds. This would result in the complex type always succeeding and the collection type continually producing new items until it hits the configured limit. I'll recommend looking at the implementation for https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/FormFileModelBinder.cs to see how to terminate your binding when no more values are available.

**Comment by nfplee** [comment]
@pranavkm thanks. I'll add some temporary code to make sure a value is sent (before saying it succeeded) with a note pointing to this issue to review it in the future. I'm not quite sure how this plays out with nullable files , but I'll deal with that when I come to it.

**Comment by icesasoftcorp** [comment]
hi,
I have the same problem any solution, i am sending 2860 rows and 9 columns.

**Comment by nfplee** [comment]
@icesasoftcorp I ended up having to say:

```
var valueResult = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);

if (valueResult == ValueProviderResult.None)
    return Task.CompletedTask;
```
