### ISSUE TITLE
Blazor Server: JS function with large return value called with JS Interop causes connection to disconnect, method to not continue executing

### ISSUE THREAD

**Issue by Merlin04** [dotnet/aspnetcore#23179]
### Describe the bug
In a Blazor Server app, when a JS function that has a large return value is called by `JSRuntime.InvokeAsync`, the connection disconnects and the method containing the call to `InvokeAsync` appears to either exit with no exception or take an incredibly long time to get to the next line of code (I used the debugger but couldn't tell). 

### To Reproduce

https://github.com/Merlin04/invokeasync-issue

### Exceptions (if any)

I don't get any exceptions but I do get this error in the browser console: `Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.`
In addition, when this code is an async method, I get this exception:
```c#
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
```

### Further technical details
- ASP.NET Core version: 3.1.200
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Not sure why it says I'm on Ubuntu 18.04, I'm on 20.04
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: JetBrains Rider 2020.2 EAP3

**Comment by javiercn** [comment]
@Merlin04 thanks for contacting us.

This is caused because you are trying to send a message that is over the underlying default signalr limits, which are around 32K.

You can do two things to make this scenario work:

* Increase the message size limit for SignalR.
  * This is easy, but I would avoid doing so as it has attached security implications.
* Break the result in multiple smaller chunks.
  * Instead of returning the value at once, break it into multiple parts.
  * Send each part individually.
  * Assemble the result when you've received the last part.
