### ISSUE TITLE
[Blazor] StateNotChanged not refreshing view when triggered from Observer pattern

### ISSUE THREAD

**Issue by puppetSpace** [dotnet/aspnetcore#23198]
### Describe the bug
I want to change the data for a component, A, from another component, B. For that I use some kind of Observer pattern where component A  implements an interface and subscribes himself for notifications to a broker. Component B uses this broker to notify a change.
In component A the change is done and a call to StateHasChanged is done. The view does not refresh.
If I do the same thing with events, it all works. 

### To Reproduce
I have a repo here: [https://github.com/puppetSpace/StateHasChangedRepo]()
Shared/MainLayout is Component A. 
Pages/Counter is the Component B. this triggers the changes

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.4.20258.7\

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20251.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`VS 16.6.2`

**Comment by SteveSandersonMS** [comment]
@puppetSpace Your `StateHasChanged` call is inside the layout, not the page whose state you're saying has changed (and want to re-render).

The reason it works for events is because `EventCallback` is a special concept within the system that knows how to re-render the component that contains the callback. You don't have anything like that for your observer mechanism so that's why it doesn't re-render in that case.

To fix this, you need to have the page listening for notifications call its own `StateHasChanged` when the notification arrives.

**Comment by puppetSpace** [comment]
> @puppetSpace Your `StateHasChanged` call is inside the layout, not the page whose state you're saying has changed (and want to re-render). So it's not really having any effect.
> 
> The reason it works for events is because `EventCallback` is a special concept within the system that knows how to re-render the component that contains the callback. You don't have anything like that for your observer mechanism so that's why it doesn't re-render in that case.
> 
> To fix this, you need to have the page listening for notifications call its own `StateHasChanged` when the notification arrives.

Oh. But I'm calling the `StateHasChanged` on the component that needs to refresh:
```
		public void Handle(CounterUpdateNotificationMessage value)
		{
			InvokeAsync(() =>
			{
				AmountOfClicks++;
				StateHasChanged();
			});
		}
```
`Handle` gets called from the other component (the one that triggers the change).

Or are you saying that by using the observer mechanism, the `StateHasChanged` is called on the component that triggers the change because it's still in the "context" of the triggering component?

**Comment by SteveSandersonMS** [comment]
@puppetSpace Your only call to `StateHasChanged` is on this line:

https://github.com/puppetSpace/StateHasChangedRepo/blob/557da44db5821991394e6cd72b1ef7e150800a8c/StateHasChangedNotRefreshing/Shared/MainLayout.razor.cs#L41

...which is inside `MainLayout.razor`. So you're not calling it on the component that needs to change; you're calling it on `MainLayout`.

> Handle gets triggered from the other component.

Yes, but it's not a question of what's higher up in the call stack :) The method you're calling is a method on `MainLayout`.

**Comment by puppetSpace** [comment]
Maybe my example is not so evident, but `MainLayout` is the one that needs to change. `Counter` (are only the buttons) is the one that triggers the change for `MainLayout`.
So `Counter` makes use of the observer mechanism to update the counter on `MainLayout`

**Comment by SteveSandersonMS** [comment]
Oh I see, thanks for clarifying that. In that case then your problem is inside `EventBroker`'s `Subscribe` logic.

For some reason you're only allowing a single subscription for each subscriber type, and are ignoring subsequent attempts to add more subscriptions. That will cause you problems because:

1. If you have more than one user, only the first one will be able to subscribe, plus events triggered by subsequent users will show up in the UI for the first user, since you're registering the services as singletons instead of scoped.
2. The "first user" is actually the prerendering process, so when your circuit connects interactively, it's not able to add any subsequent subscriptions, so they get ignored.

**Comment by puppetSpace** [comment]
It's a simplified version of what I actually have, just to show the issue. For this, only one subscription is needed. Just to show that when `StateHasChanged` is called, nothing gets refreshed, because the code gets called. `StateHasChanged` gets called, but the view does not refresh.
So it's not an issue of the observer mechanism not executing the `StateHasChanged`

**Comment by SteveSandersonMS** [comment]
> So it's not an issue of the observer mechanism not executing the StateHasChanged

In your repro, the component that gets refreshed is the prerendering instance of `MainLayout`, not the interactive instance. This is because `EventBroker` only allows one subscriber.

If I changed it to disable prerendering (by changing `_Host.cshtml` to use `render-mode="Server"` instead of `ServerPrendered`) then the UI *does* update when triggering the broker.

**Comment by puppetSpace** [comment]
Ok. Now I get it. Didn't know it gets called twice if prerendering is enabled. 
Thank you very much. I'm gonna do some reading about prerendering
