### ISSUE TITLE
Identity Core React SPA app not working in Internet Explorer 11

### ISSUE THREAD

**Issue by ps-tb** [dotnet/aspnetcore#23299]
### Describe the bug
To start, I am embarrassed to ask this question; please don't judge me. 

I created a React SPA app in 3.1 with Identity and it's lovely and it works as expected in all browsers but Internet Explorer 11 because to start, Promises aren't supported. The organization for whom this was built has a use case for using Internet Explorer much to my chagrin. Before expending the effort to even try, would it even be possible to use Babel to polyfill the code so it can be run in IE 11? I ask because I'm not an expert in this area. It seems to me that even if I could polyfill the `api-authentication` files, there's still the `oidc-client` library that is imported into these files that would not work in IE 11. Thank you for your input.

### To Reproduce

Create an Identity Core project, navigate to it in IE 11, and watch it laugh at you.

### Exceptions (if any)

`SCRIPT5009: 'Promise' is undefined`
### Further technical details
- ASP.NET Core version: 3.1

**Comment by javiercn** [comment]
@ps-tb thanks for contacting us.

We've personally haven't tried this out, but you could potentially make it work with appropriate polyfills. Looking at the docs for CRA [here](https://create-react-app.dev/docs/supported-browsers-features/) it says that IE11 is supported with appropriate polyfills, and for oidc-client.js I believe you should be able to make it work with appropriate polyfills, but I can't guarantee it, since that's not something we support, so we haven't tried it out.

**Comment by blowdart** [comment]
As this really is a question about react, closing
