### ISSUE TITLE
DataProtection Protected Payload length

### ISSUE THREAD

**Issue by taranlabana** [dotnet/aspnetcore#23399]
I am trying to implement a module to protect/unprotect the data using [ASP.Net Core's DataProtection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection?view=azure-dotnet). I want to store the payload which is generated by [Protect(protector, string)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectioncommonextensions.protect?view=aspnetcore-3.1#Microsoft_AspNetCore_DataProtection_DataProtectionCommonExtensions_Protect_Microsoft_AspNetCore_DataProtection_IDataProtector_System_String_) method in a SQL Table. 
So I was wondering what length should I set for the Table Column (e.g. Varchar(256)). 
Or if there is a way to limit the length for the payload to be generated.

Can someone please help me out? 

Thanks in appreciation.
Taran

**Comment by blowdart** [comment]
It depends on the data to be honest, and the algorithm configured. Are you indexing on it? If not, just nvarchar(max) and be done with it.

**Comment by GrabYourPitchforks** [comment]
Two things to note.

First, since you mentioned database storage... the data protection layer is intended to create _ephemeral_ data, not persisted data. By ephemeral data we mean data that you wouldn't mind losing. Authentication cookies are an example of this, as if you "lose" your authentication cookie you can simply log in again. It's not recommended to use the data protection APIs to create data that you intend to keep around in perpetuity. If you intend long-term storage of cryptographically protected data, you may have data retention and retrieval requirements, so another mechanism (such as something backed by a proper X.509 certificate) might be more appropriate.

So let's say you decide using data protection + a database is appropriate for your scenario. If you do this, remember that the data protection layer operates on _bytes_, not _chars_. Once you have a `byte[]` that represents a protected payload, remember to call `Convert.ToBase64String` to convert it to a `string` before storing it in your database. The column type should be `nvarchar(max)`, as Barry said.
