### ISSUE TITLE
UI controls pack for Blazor

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#23559]
The ready availability of rich UI controls has been a major strength of Microsoft frameworks (WinForms to UWP). Can we have a Microsoft authored pack of UI controls in Blazor? Currently, we have to rely on third parties, each offering a non-standard experience. A standard, open-source, readily available pack of UI controls will go a long way in fast web development using Blazor.

**Comment by daniel-p-tech** [comment]
I tend to agree - I raised a similar concern when Blazor was first announced and the guidance at that time was to wait until 3rd party vendors implement their own solutions. Well, I have been following one of the major vendors for a year and to this day they still don't have a functional library that would let me and the team embark on a new large scale project (although I have been assured by the vendor that things will move much faster this year, I'm somewhat skeptical at this point).

I think there is a value in Microsoft providing open-source high quality components implemented using best-practices that the community can then contribute to (or completely take over).

**Comment by danroth27** [comment]
Thanks for this suggestion! We don't have any plans to produce a library of UI components for Blazor. Instead we look to the community to provide these components. This frees up the Blazor team to focus on the core framework and creates space for the community to innovate.

You can find Blazor UI component libraries from various vendors:

- [Telerik](https://www.telerik.com/blazor-ui)
- [DevExpress](https://www.devexpress.com/blazor-razor-components/)
- [Syncfusion](https://www.syncfusion.com/aspnet-core-blazor-components)
- [Radzen](https://blazor.radzen.com/)
- [Infragistics](https://www.infragistics.com/products/ignite-ui-blazor)
- [GrapeCity](https://www.grapecity.com/componentone/blazor-ui-controls)

There are also various open source component libraries already being maintained by the Blazor community:

- [Blazored](https://github.com/Blazored)
- [MatBlazor](https://www.matblazor.com/)
- [BlazorStrap](https://blazorstrap.io/)
- [Blazorise](https://blazorise.com/)
- [Ant Design Blazor](https://ant-design-blazor.gitee.io/)

You can find additional open source libraries and projects from the community at https://aka.ms/awesomeblazor.

Another option is to leverage standards based Web Components in your Blazor app. [FAST](https://fast.design) is a good example, and comes from some folks at Microsoft.

Since we don't have any plans to build and ship our own library, I'm going to go ahead and close this issue.

**Comment by mayur-ekbote** [comment]
So nothing to counter Flutter? I hope this decision is reconsidered later. Thanks!
