### ISSUE TITLE
Blazor Refreshing Component without ChildContent

### ISSUE THREAD

**Issue by jontavakoli** [dotnet/aspnetcore#23556]
I have a Container component that simply loops through a list of integers and renders them as li tags.

```
<ul>
    @foreach (var item in Items)
    {
        <li>@item</li>
    }
</ul>

@code {

    [Parameter]
    public RenderFragment ChildContent { get; set; }

    [Parameter]
    public List<int> Items { get; set; } = new List<int>();

}
```
This component does not trigger a view update unless an unrendered ChildContent is added to it.

In the following example everything works just fine. However, once the `<i />` tag is removed the code stops working. I have no idea what would causes such behavior, however i prefer not to render a useless tag if it can be avoided.

```
@page "/"

<Container @ref="container">
    <i />
</Container>

<button @onclick="Add">Add</button>

@code{

    private Container container;

    void Add()
    {
        container.Items.Add(container.Items.Count);
    }

}
```

**Comment by javiercn** [comment]
@jontavakoli thanks for contacting us.

Blazor has no way to know that the state of the container has changed. What you should be doing is pass the list as a parameter to the container and that will cause the container to re-render automatically.

A component can re-render because of two reasons:
* It received new parameters.
* The component itself calls StateHasChanged in response to something.

The right way for a parent to notify a child component that new data is available, is through parameters, not by using the child-api component directly.

**Comment by jontavakoli** [comment]
@javiercn i understand that, but why does adding a child content alerts the behavior to where you don't need to pass the list as a parameter over and over. Rather changing the list data automatically causes a rerender of the component?

**Comment by javiercn** [comment]
@jontavakoli Blazor doesn't examine your track the component state in order to trigger re-renders automatically, the model it follows requires makes the component responsible for notifying the framework when the state has changed. Blazor only keeps track of the UI state to determine how to update it appropriately in response to a the component being rendered again.

If you want to trigger changes based on model changes you can make your model trigger some sort of notification and subscribe to it to trigger new renders, but that is not the philosophy that Blazor uses by default. The idiomatic way of doing things in Blazor is to be explicit and pass the state you want as parameters, trigger notifications within each component in response to events and for the framework to take care of reconciling the old UI state with the new UI state.

**Comment by jontavakoli** [comment]
@javiercn I understand everything you are saying. But my question still remains the same. Why does having a ChildContent defined on a component alters the way re-rending happens.
I would expect the re-rendering not to occur when i add a new item to the list that is literally added using the code. **However adding the ChildContent to the Container will make it so that it re-renders even though the ChildContent is not altered at all.**

Can you explain why having a ChildContent assigned to the component the behavior changes?
