### ISSUE TITLE
CVE-2020-10878 on Docker image

### ISSUE THREAD

**Issue by peterjgrainger** [dotnet/aspnetcore#23652]
### Describe the bug
Docker image mcr.microsoft.com/dotnet/core/aspnet:3.1 has vulnerability https://security-tracker.debian.org/tracker/CVE-2020-10878

**Comment by javiercn** [comment]
@peterjgrainger thanks for contacting us.

We'll asses the impact of the reported problem and decide what actions we need to take if any are needed.

Please note for future security issues a github issue is not the best place to report them. Please consider using our [coordinated disclosure route](https://github.com/dotnet/aspnetcore/security/policy), as highlighted when you created issues. Security issues reported through secure@microsoft.com are eligible for our bug bounty program. Github issues are not eligible.

**Comment by blowdart** [comment]
In this case, because we don't use perl during runtime it's not going to affect anything hosted in the container.

We relay on the upstream image to fix it anyway. Until Debian update Buster there's no fix available for us.

While https://github.com/dotnet/dotnet-docker/issues would be the github repo, as @javiercn points out Github issues are not the venue for security bug reports.
