### ISSUE TITLE
Can't launch Blazor WASM debug session from VS Code

### ISSUE THREAD

**Issue by alpinedelight** [dotnet/aspnetcore#23675]
**Description**
I have followed the setup [outlined in docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1), installed respective extensions, enabled preview features, and verified config in launchsettings.json.
Every time I want to launch a new debug session from my Blazor WASM I get the following message:

> Unable to launch browser: "Unable to find a Chrome installation on your system. Try installing it, or providing an absolute path to the browser in the "runtimeExecutable" in your launch.json.

I have tried adding absolute path to edge to no avail using runtimeExecutable under launch.json.
Re-installed extensions etc. All no luck.
I can launch and access the app normally (not in debugging mode) via VS Code
However, debugging does work from visual studio 2019.

**Versions**
VS Code 1.46.1
Debugger for Microsoft Edge v1.0.15
JavaScript Debugger v2020.7.317 > Preview 
C# v1.22.1
Edge v83

**Steps to Reproduce**
VS Code, 

1. Open VS code
2. Create new folder anywhere
3. dotnet new blazorwasm -o testproj
4. Open folder
5. f5 > BlazorWebAssemblyDebug
6. Error

**Comment by captainsafia** [comment]
@alpinedelight It looks like you want to launch a debugging session using Edge instead of Chrome. We default to Chrome but you can modify this by setting the `browser` property in your `launch.json` to edge. Like so.

```
{
  "type": "blazorwasm",
  "request": "launch",
  "name": "Launch and Debug",
  "browser": "edge"
}
```

The options are documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#launch-configuration-options).

Let me know if that doesn't work for you.

**Comment by alpinedelight** [comment]
Thanks for the quick response Safia - rather obvious now that you point it out 😅
Documentation denial of service. Thanks again.
