### ISSUE TITLE
Blazor server side. Input date has problem.

### ISSUE THREAD

**Issue by duloveme** [dotnet/aspnetcore#23686]
### Describe the bug
I wrote a blazor server side project with reference https://github.com/Daddoon/Blazor.Polyfill.
In IE11, An error occurs when input date loses focus.
Error : Invalid element type 'text'
![error1](https://user-images.githubusercontent.com/1410552/86546072-cecb6c80-bf6d-11ea-8f72-8f616f6f90d5.png)
![error2](https://user-images.githubusercontent.com/1410552/86546074-cf640300-bf6d-11ea-9333-e32e71bc0a55.png)

<input type="date @bind="fromDate" />
@code {
    private DateTime fromDate = DateTime.Today;
}

### To Reproduce
This is my test project for the error.
https://github.com/duloveme/BlazorApp6

### Exceptions (if any)
SCRIPT5022: Invalid element type 'text'.
blazor.server.js (8,53420)

### Further technical details
- ASP.NET Core version : 3.1
- The IDE (VS / VS Code/ VS4Mac) : Visual Studio 2019 16.6.3

**Comment by javiercn** [comment]
@duloveme thanks for contacting us.

This can be due to an issue on the polyfill you are using or something to do with IE11 support for `input type=date`. In general, if it works on Edge/Chrome/Firefox/Safari I don't think this is a Blazor issue but an issue with either the polyfill or the limited IE11 support for some browser input types.

**Comment by mkArtakMSFT** [comment]
After further investigation, this looks like a browser issue, rather than an issue with Blazor.

**Comment by SteveSandersonMS** [comment]
IE11 doesn't support `<input type=date>`, so I'm afraid `InputDate` can't work on that browser.
