### ISSUE TITLE
Unnecessary file in the default template

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23731]
1. Create a new ASP.NET Core 3.1 MVC app with Individual User Accounts.
2. *Areas\Identity\Pages\_ViewStart.cshtml* seems unnecessary. I've deleted it and the app is still working.

I think it should be generated after identity scaffold only.

**Comment by javiercn** [comment]
@Youssef1313 thanks for contacting us.

That file is there to override the layout that Identity uses in favor of the layout from the application. The reason you don't see any difference is because the default layout in the template matches the one provided by Identity UI, but the moment you start customizing the layout from the application there will be differences.

By default we setup the layout in Identity UI to use the layout from your app so that you can keep a consistent layout between Identity UI and your app

**Comment by Youssef1313** [comment]
@javiercn Thanks for the very fast response :)
I think in most cases, developers will keep consistency. So, having the default template less noisy seems better in my opinion (and less confusing to developers). And in the few cases where the developer needs a different layout, he can get this file scaffolded.

But if you prefer the current behavior, that's okay. Feel free to close the issue.
