### ISSUE TITLE
Add support for sending exceptions to renderer

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#23763]
For scenarios like the `OnNavigateAsync` callback in the router, we need to be able to send unhandled exceptions to the renderer instead of dropping them.

Ref: https://github.com/dotnet/aspnetcore/pull/23290/files#r450915496

**Comment by SteveSandersonMS** [comment]
Another scenario that might benefit from this is using `@bind` with a property whose setter wants to do something asynchronous. 

Today there's no way to do that without treating the async task as fire-and-forget (discarding any possible exceptions), so it would be nice if there was a proper, safe way to do it.

**Comment by javiercn** [comment]
In this case, I'm wondering how this exception bubbles when the location changes.

https://github.com/dotnet/aspnetcore/pull/23290/files#diff-c9e6808455b40dcab1c29363164978afR162-R166

Isn't it kind of similar?

**Comment by javiercn** [comment]
One way for us to flow the exception data in this case could be to simply trigger a render and rethrow the exception at that point.

**Comment by SteveSandersonMS** [comment]
> In this case, I'm wondering how this exception bubbles when the location changes.
> https://github.com/dotnet/aspnetcore/pull/23290/files#diff-c9e6808455b40dcab1c29363164978afR162-R166

That link's not working for me (GitHub doesn't highlight any specific file).

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/Routing/Router.cs#L126-L130

**Comment by SteveSandersonMS** [comment]
That's a synchronous exception so it would bubble up to wherever the navigation event first reached .NET. Async exceptions are a bit harder to deal with because `NavigationManager`'s `LocationChanged` event only deals with invoking synchronous code.

**Comment by javiercn** [comment]
@SteveSandersonMS that's fair, in that case it surfaces as a JS interop error.

We could however; for the router case surface the exception through the Render method, since I don't think it would make the callback hard to understand. The way I see it, is "There was an exception that prevents this component from successfully rendering"

Just trying to think out of the box here on ways to avoid new concepts/public API.

**Comment by SteveSandersonMS** [comment]
Another more generalised way to describe one of the scenarios would be "Any time a developer wants to handle an `event` and do something asynchronous". This is (arguably) a problem with C# events in general, which were designed long before `async`/`await`. However it's a real issue because in UI programming it's common to use events to flow notifications throughout the application.

In an event handler, you have nowhere to return a `Task`, so it would be helpful if there was some provided way that a component could dispatch a task such that any failures would be handled like async lifecycle method failures.

**Comment by captainsafia** [comment]
I opened a PR for this in #23947. I kept the implementation fairly conservative and explicit in the interest making the release. But I'm happy to play around with getting something working for scenarios beyond exceptions thrown during `OnNavigateAsync`.
