### ISSUE TITLE
isSvgElement is slow

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/aspnetcore#23807]
### Describe the bug
I am rendering a table with, let's say 500 items. Upon clicking a button, I'm modifying each item in a foreach loop, which causes a re-rendering of the whole table.

With the Google Chrome profiler, I noticed that around 47% of the time it takes to re-render the table (2 seconds) is spent in the `isSvgElement` method:
![2020-07-09 15_04_03-IKON_2_0 - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/67917640/87043573-82925d80-c1f5-11ea-98c2-45c886e0543d.png)

Since I'm not using Svg elements in my rendering, I am not sure this is warranted.
### To Reproduce
Render a huge table from a list of complex items. Then iterate over said list and change properties to cause the list to re-render.

### Further technical details
- ASP.NET Core version:  3.1 / 5.0 respectively.

<details>
<summary>Output of  dotnet --info</summary>
dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014977 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 Version 16.7.0 Preview 3.1

**Comment by javiercn** [comment]
@dantronik-markus thanks for contacting us.

We are aware of this issue. @SteveSandersonMS has some ideas around it.

**Comment by SteveSandersonMS** [comment]
@dantronik-markus I'm glad you're looking into quantifying the performance. Please continue letting us know if you spot things that look like opportunities for optimization.

I'm also doing a lot of perf investigations as part of https://github.com/dotnet/aspnetcore/issues/22432. One of the main things I've found through investigations is that the numbers given by Chromium's profiler don't match up with reality at all, at least when measuring intensive rendering scenarios. Perhaps the overhead of profile capturing greatly distorts the timings, or perhaps it's for some other reason, I don't know for sure. But this has led me to implement some more lightweight profiling mechanisms in #23510 to capture more accurate data.

For example, when profiling the [grid benchmarks](https://github.com/dotnet/aspnetcore/blob/master/src/Components/benchmarkapps/Wasm.Performance/TestApp/Pages/GridRendering.razor) (which sounds a lot like your scenario), I also see Chromium's profiler claim that a huge proportion of the time is spent in `isSvgElement`. So you might think that by replacing the method body of `isSvgElement` with `return false` would greatly improve the benchmark results. But it doesn't.

Here's the FastGrid benchmark based on the current `master` branch:

![image](https://user-images.githubusercontent.com/1101362/87059538-511f8f00-c201-11ea-997e-e57746b17c8d.png)

... and here's the same after replacing `isSvgElement`'s logic with `return false`:

![image](https://user-images.githubusercontent.com/1101362/87059581-60064180-c201-11ea-9f87-04c12b718535.png)

So it does look like it *is* fractionally improved, but not by the 50% or so that Chromium's profiler would suggest. I do think that a few % gain is a good enough justification for trying to optimize `isSvgElement`, but it's not the silver bullet we might have hoped for based on Chromium's profile data.

If you're interested in doing further perf investigations, I'd recommend trying out changes in the framework sources to see what practical effect it has on the benchmark results. Be sure to run them with the browser's dev tools **closed**! Simply having dev tools open causes the browser to run in a far less optimized mode, typically adding ~ 50% to the time taken for rendering.

**Comment by dantronik-markus** [comment]
> If you're interested in doing further perf investigations, I'd recommend trying out changes in the framework sources to see what practical effect it has on the benchmark results. Be sure to run them with the browser's dev tools **closed**! Simply having dev tools open causes the browser to run in a far less optimized mode, typically adding ~ 50% to the time taken for rendering.

Hey, could you be more specific about this? Are we talking about me testing existing changes in the Asp.NET Core framework in order to quantify what effect this has on performance, or rather me trying to find ways to make the framework source more performant?

In any case, are there nightly builds available and what's the process of switching from the latest preview of AspDotNet to the latest nightly?

**Comment by SteveSandersonMS** [comment]
@dantronik-markus I meant that if you're interested in trying to figure out optimizations and test whether they work, or perhaps just to try identifying which parts of the framework are expensive in particular cases, then I'd recommend working from the framework sources so you can make changes and observe the effects.

There's info about working with the framework sources at https://github.com/dotnet/aspnetcore#how-to-engage-contribute-and-give-feedback

**Comment by mkArtakMSFT** [comment]
Closing as the performance characteristics will be a lot different in 5.0.
