### ISSUE TITLE
When using AddControllersAsServices and AddSingleton, ControllerContext is shared between different requests

### ISSUE THREAD

**Issue by TalAloni** [dotnet/aspnetcore#23817]
I have created a minimal repro demonstrating the issue [here](https://github.com/TalAloni/AspNetCoreSingletonControllerHttpContext).

When the following conditions are met:
1. AddControllersAsServices is used.
2. AddSingleton is used to add the controller
3. Multiple requests are issued to the web application at the same time

The ControllerContext  (and as a result the HttpContext) are shared between different requests.

I have confirmed this issue occurs in ASP.NET Core MVC 2.0, 2.1 and 2.2 (I haven't tested newer versions).

Note: Response headers may leak to different responses than the ones intended - this has security implications!

**Comment by javiercn** [comment]
@TalAloni thanks for contacting us.

Please note for future security issues a github issue is not the best place to report them. Please consider using our coordinated disclosure route, as highlighted when you created issues. Security issues reported through secure@microsoft.com are eligible for our bug bounty program. Github issues are not eligible.

This is a user error with security implications, not a security issue in the framework, the same way as if you use `Html.Raw` with untrusted input. We've prescribed since (old ASP.NET times) that components need to be registered as transient services when using a DI container.

**Comment by TalAloni** [comment]
Javier, thank you for the quick reply, I will update my web application accordingly.
