### ISSUE TITLE
[Blazor] [WASM-3.2] AccountClaimsPrincipalFactory not deserializing arrays correctly

### ISSUE THREAD

**Issue by cradle77** [dotnet/aspnetcore#23895]
### Describe the bug
When a claim in a JWT token is an array of values, the expected deserialization in a ClaimsPrincipal is having multiple Claim objects - one per each value - with the same type.
E.g.
a token such as
```
{
  ...,
  "role": [ 
    "user", 
    "superUser"
  ]
}
```
should generate 2 `Role` claims in the ClaimsPrincipal, with the 2 values `user` and `superUser`.

This is how ASP.NET Core behaves.

In Blazor WASM, however, `AccountClaimsPrincipalFactory` generates only one `Role` Claim, with a string value which is the JSON serialization of the array.

This breaks several functionalities, like `ClaimsPrincipal.IsInRole()` or `[Authorize(Roles = "user")]`

### To Reproduce
I have created a unit test project which reproduces the issue:
https://github.com/cradle77/AccountClaimsPrincipalFactory

The project also includes a proposed implementation for AccountClaimsPrincipalFactory which fixes the issue by explicitly handling arrays

### Further technical details
- Blazor WASM 3.2

**Comment by javiercn** [comment]
@cradle77 thanks for contacting us.

AccountClaimsPrincipal does not try to be smart about the payload representation. When a single role is returned a single string claim is added. When multiple roles are present it will represent them as an serialized json array of values.

You can extend accountclaimsprincipalfactory like [here](https://github.com/javiercn/BlazorAuthRoles/blob/master/Client/RolesClaimsPrincipalFactory.cs) to transform the roles array into a list of claims.

**Comment by cradle77** [comment]
Hello @javiercn,

I would suggest to reconsider this design choice, because it seems wrong that the same token generates a different ClaimsPrincipal in Blazor than in ASP.NET Core Web API / MVC. 
Plus, as I said, it breaks various other components like policies, AuthorizeAttribute or IsInRole.

Anyway, I'll use a custom implementation for the time being.

Thanks for your time.

**Comment by javiercn** [comment]
@cradle77 The original implementation had that trait (it will coalesce arrays into lists of claims) but if you think about it, it is kind of weird to bake that behavior in, and it is better to just "be dumb" about it and let people control the deserialization. 

Ultimately it is a contract between the AccountClaimsPrincipalFactory you are using and the underlying JS interop library. That's why we switched it to have extensibility there, so that you can tweak it to suit your needs. I understand that it makes it a bit harder to work with roles, and that's something we might be willing to tweak in future versions, but we need to discuss this within the team first, to see if it is something we want to consider.
