### ISSUE TITLE
TagHelper/Component end-tag completion fails at the end of the document

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23907]
Repro:
- Go to the very end of `Index.razor`.
- Type `<App>`

Expected:
`<App></App>`

Actual:
`<App>`

**Comment by NTaylorMullen** [comment]
This onlny reproduces for TagHelpers

**Comment by TanayParikh** [comment]
Investigated. This is because the end of a document doesn't have a classified span associated with it. Ex. `>` is at `absoluteIndex` of 129 but the last span has an `absoluteIndex` of 118 with a length of 6 (`end` = 124).

Consequently [projection fails](https://github.com/dotnet/aspnetcore-tooling/blob/4c4a85ab84a925d813904cae0d19f838f13caa40/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs#L81-L84) with a [null response](https://github.com/dotnet/aspnetcore-tooling/blob/4c4a85ab84a925d813904cae0d19f838f13caa40/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs#L70) (as the mapping service returns [`Razor` instead of `HTML` as the language](https://github.com/dotnet/aspnetcore-tooling/blob/4c4a85ab84a925d813904cae0d19f838f13caa40/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs#L253)).

I believe the underlying issue of missing classified spans at the end of a document may be known, and there was a reason we hadn't addressed it. cc/ @NTaylorMullen / @ajaybhargavb do you have more context on this? I could be mistaken and this could just be a bug for us to resolve now.

**Comment by NTaylorMullen** [comment]
Ah interesting. I think it's an implementation detail of the parser weaving different languages together and the default is always 'Razor'. Meaning, at the end of the document the parser trys to go back to its default state.

I don't think this is something we should change at the parser layer. Instead lets change our mapping logic to special case the end of the document.
