### ISSUE TITLE
Add extension methods to IJSRuntime for getter/setter

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#23952]
### Is your feature request related to a problem? Please describe.

I find myself writing the following code
```cs
//IJSRuntime js;
var value = await js.InvokeAsync<string>("eval", "foo");
await js.InvokeVoidAsync("eval", $"foo = '{value}'");
```

This works as expected: it gets/sets the value of the variable `foo` in the javascript context.

### Describe the solution you'd like

I suggest to add an API for getting/setting:

```cs
ValueTask<T> GetAsync<T>(this IJSRuntime js, string identifier);
ValueTask SetAsync<T>(this IJSRuntime js, string identifier, T value);
```

This would allow a much more intuitive usage:

```cs
//IJSRuntime js;
var value = await js.GetAsync<string>("foo");
await js.SetAsync("foo", value);
```

NB: The API can be implemented with eval, as above (might need some specialization for the setter). I don't know if there is an eval-free approach to this (which probably would be better in terms of performance?).

**Comment by javiercn** [comment]
@stefanloerwald thanks for contacting us.

I'm not sure what you scenario is, but in general we discourage being chatty over JS interop, so this is not an API that we are likely to add. (You can create extension methods for it yourself if you choose to do so) since that can easily be misused and lead to bad performance in your application.

**Comment by stefanloerwald** [comment]
Hi @javiercn,

I agree that it's best to avoid JS interop altogether, but sadly it's not (yet) avoidable everywhere. I already use such extension methods but thought more people might want to have them.

Assignments to variables in JS are for example necessary in the HTML canvas API (e.g. https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle), which translates to https://github.com/excubo-ag/Blazor.Canvas/blob/68751361c10b884c6179b84b887c348d052afd1c/Canvas/Contexts/Context2D_FillAndStrokeStyles.cs#L14 in a [C# API wrapper](https://github.com/excubo-ag/Blazor.Canvas). I'm sure there are many more libraries/APIs where setting values is simply unavoidable.

**Comment by javiercn** [comment]
@stefanloerwald I understand what you mean, but I would say the example you provided is the type of API we want to avoid having/writing.

I understand that it is incredibly straightforward and convenient to write an API in that way given that it pretty much maps 1:1 to the underlying JS API, but it will perform terribly in server-side scenarios since a roundtrip will be required for changing each property.

This is very similar to what we do to deal with the DOM updates. We could have built an API like that but as you can guess it would have very bad performance characteristics. Instead what we do is we collect all the updates and send a "RenderBatch" to the client to handle the changes.

For an API like the one you are showing, it makes sense to do something similar. I understand that this is way more involved that what you are doing, but it is what we would recommend and what would give you the best performance.

One way you could do so is by creating a list of function calls in a data structure with their arguments, and sending that payload to the JS side instead for it to be applied in one go.

Something like:
```charp
@code {
    private Canvas helper_canvas;
    private ElementReference normal_canvas;
    protected override async Task OnAfterRenderAsync(bool first_render)
    {
        if (first_render)
        {
            await using (var ctx1 = await helper_canvas.GetContext2DAsync())
            {
                ctx1.Font("48px solid");
                ctx1.FillText("Hello", 0, 150);
                await ctx1.ApplyChanges();
            }
        }
    }
}
```
That would produce a payload like the following:
```json
[
  "font": [ "48 px solid" ],
  "fillText": ["Hello", 0, 150]
]
```

And that you could map on the JS side to the context members.

This is the type of API we would promote over something that does a 1:1 map over granular js methods, and for that reason we don't think that having those APIs in the framework is desirable, since it can easily lead to writing components and libraries that perform poorly.

I hope that helps clarify things.

**Comment by stefanloerwald** [comment]
Thanks @javiercn for the clarification. I haven't seen bad performance with the canvas API in either server-side or client-side, but of course the API you describe can be an advantage in situations where there are simply too many calls to be made.
