### ISSUE TITLE
Erroneous Error Highlighting on Statements in OnInitializedAsync

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#24018]
The screenshots below show errors being flagged on statements within the override OnInitializedAsync method in a layout Blazor component immediately after a successful re-build that didn't show any errors.  These flagged errors disappeared after I added a statement to the method and did a re-build.  Don't know what I did that led up to the error situation in the first place.

![Screenshot (8)](https://user-images.githubusercontent.com/18602722/87694010-a573c300-c75b-11ea-9c7a-277c1df79f69.png)
![Screenshot (9)](https://user-images.githubusercontent.com/18602722/87694011-a60c5980-c75b-11ea-9c84-02f0d0a04ae6.png)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
