### ISSUE TITLE
Erroneous Error Highlighting

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#24057]
The screenshot below show errors being flagged in component markup immediately after a successful re-build that didn't show any errors and a subsequent execution that worked.  This is similar to this issue (https://github.com/dotnet/aspnetcore/issues/24018) except for the context of the erroneous error highlighting. The suggested using is in the root _imports.razor file.  Closing and re-opening the solution made the highlighting go away.

I just noticed that this situation cropped up when I renamed a component file and then manually renamed references to it in other components (such references were not automatically changed by the rename as would have been appropriate).

![Erroneous Markup Highlighting](https://user-images.githubusercontent.com/18602722/87791752-cfd38800-c810-11ea-9834-2c405c4202bf.png)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
