### ISSUE TITLE
UserManager.ConfirmEmailAsync method not calling UpdateSecurityStampInternal method internally

### ISSUE THREAD

**Issue by mgupta0710** [dotnet/aspnetcore#24056]
### Describe the bug
Same Email confirmation link doesn't become redeemed/invalid upon using second time. 

### To Reproduce
I am using `GenerateEmailConfirmationTokenAsync` to generate the token for email confirmation link and using `ConfirmEmailAsync` to validate the link. It is working fine.

**Problem** - Link should work only once. If user using same link second time link should be redeemed/invalid. When I debug the code, I found each time `ConfirmEmailAsync` result as succeeded. I was expecting `VerifyUserTokenAsync` should return false second time but it is also returning true.

### Further technical details
- ASP.NET Core version 3.1

**Comment by blowdart** [comment]
This is by design - if we rotate the security stamp the user will be logged out everywhere.

@HaoK is there a way to make an email confirmation single use only?

**Comment by huysentruitw** [comment]
Letting `VerifyUserTokenAsync` or `ConfirmEmailAsync` invalidate the token would be an unexpected side-effect of calling these methods.

**Comment by HaoK** [comment]
This is dependent on the token provider implementation, the default one is a time sensitive data protection based one I believe, that's salted with the security stamp.  What @blowdart said is correct, confirming the email doesn't update the security stamp since that will log you out everywhere, ChangeEmail does do this and hence the tokens will only work once.  We don't store the tokens anywhere so there's no way to invalidate them after use, you would have to implement this logic and switch to using your custom token provider to add this

**Comment by mgupta0710** [comment]
Thanks a lot for suggestion. I agreed with @HaoK that we would have to implement this logic with custom token provider.
