### ISSUE TITLE
Bind the cookie to ITlsTokenBindingFeature

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2406]
_From @Tratcher on Friday, April 29, 2016 1:19:33 PM_

If the cookie is marked as Secure (https://github.com/aspnet/Session/issues/106), bind it to the TLS token (https://github.com/aspnet/Security/issues/773, https://github.com/aspnet/IISIntegration/issues/31)

_Copied from original issue: aspnet/Session#110_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, September 21, 2016 4:16:38 PM_

@muratg this should be backlogged, the underlying infrastructure from IIS, WebListener, and Kestrel.Https isn't ready.

**Comment by brockallen** [comment]
I know this has mainly fizzled due to chrome, but if/when this is enabled, you will need to keep in mind that the Katana cookie and data protection integration will also need to do the same to ensure cookies issued by ASP.NET Core with the binding can be consumed by the Katana cookie handler (and vice versa).  // @blowdart @Tratcher

**Comment by Tratcher** [comment]
@blowdart also closing this one as indefinitely blocked.
