### ISSUE TITLE
Customize RemoteAuthenticatorView so that it opens within app window

### ISSUE THREAD

**Issue by jmacCity** [dotnet/aspnetcore#24089]
Hi there, 

I recently followed the [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1) tutorial.

The RemoteAuthenticatorView opens a separate window to authenticate against Azure B2C. I would like this authentication dialog to open within the Blazor application itself to provide a more uniform experience (like a pop-up or dedicated authentication page). Is this something configurable or does it require additional changes to the template itself?

![auth](https://user-images.githubusercontent.com/17515360/87857458-cc193180-c8f4-11ea-9576-9b00a632ecb1.PNG)

The tutorial mentioned above specifies the use of a Web platform redirect URI; however, it looks like there is the new SPA platform (seen below) that offers auth flow with PKCE. Is it necessary to migrate MSAL versions/platforms before getting the desired functionality I mentioned above?

![client registration](https://user-images.githubusercontent.com/17515360/87857308-cbcc6680-c8f3-11ea-8eee-ae2a749062b4.png)

Sorry if I am missing the obvious on any of this. 

Regards,
Jordan

**Comment by mkArtakMSFT** [comment]
@javiercn FYI

**Comment by javiercn** [comment]
This is not something that can be achieved through OAuth/OIDC.

You either get a pop-up or a redirect to the login page, but the login dialog must be handled by the identity provider (Azure ADB2C) on their origin so that they can ensure the safety of the login attempts.

The default logic is popup and fallback to redirect, and in preview8 we added an option to avoid the popup completely and use the redirect directly.
