### ISSUE TITLE
Blazor components cannot access any thing useful

### ISSUE THREAD

**Issue by Banyc** [dotnet/aspnetcore#24154]
### Is your feature request related to a problem? Please describe.

Blazor has no HttpContext, which provides a ton of useful information.

I can not even access cookies even if Signalr connection instantiated inside a razor component that needs cookie as authentication.

I have wasted my whole day to find out solution but NOTHING is achieved.

WHY BLAZOR COMPONENTS ARE SO HARD TO MANAGE?

A simple act, like getting cookies from HttpContext, will be a disaster for blazor components.

Then I have tried out this:

```cshtml
<app>    
    <component type="typeof(App)" render-mode="ServerPrerendered" TheCookies="Model.Cookies"/>
</app>
```

...But the property here:

```csharp
[Parameter]
    public System.Net.Cookie TheCookies { get; set; }
```

... is always being NULL!

To develop a blazor component, you will waste MOST OF TIME on absurd problems like that.

### Describe the solution you'd like

Why not make it simpler to use? Without cookies, the hub of signalr cannot impose any authorization check!

### Additional context

Frustrated.

**Comment by captainsafia** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by javiercn** [comment]
@Banyc thanks for contacting us.

The HttpContext is normally not available for Blazor applications. That is because Blazor applications don't run in the context of a request and response. The context can be available under some circumstances through IHttpContextAccessor, but we discourage its usage. See the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-3.1#blazor-and-shared-state).

The recommended way to pass data from the request to a Blazor application is to do so as parameters during the initial component render.

We understand your frustration, but Blazor applications don't use a request/response model and HTTP concepts don't apply to them.

**Comment by Banyc** [comment]
> The recommended way to pass data from the request to a Blazor application is to do so as parameters during the initial component render.

This is exactly why I so frustrated. What I need is a concrete solution. I have tried many times to guess what it means by “to do so as parameter”. I have already given an example above to show a false attempt which also “to do so as parameter”. 

I have wasted most of the time to guess those “Useful instructions.”

**Comment by Banyc** [comment]
> Status: Resolved

Interesting
