### ISSUE TITLE
[Request Feature] NavigationManager Add Overload to NavigateTo to open in a new window

### ISSUE THREAD

**Issue by AhmedAbuelnour** [dotnet/aspnetcore#24357]
NavigationManager Add Overload to NavigateTo to open in a new window

**Comment by javiercn** [comment]
@AhmedAbuelnour thanks for contacting us.

The goal of using navigation manager is to perform client-side navigation. I would be hesitant to add options for all possible scenarios since many of them don't commonly get used.

You can achieve your scenario through JS interop by calling `await JS.InvokeVoidAsync("window.open", url);`

**Comment by AhmedAbuelnour** [comment]
Thanks i didn't know that 😅
