### ISSUE TITLE
Warning about dev cert even when a certificate manually supplied

### ISSUE THREAD

**Issue by bencyoung** [dotnet/aspnetcore#24361]
### Describe the bug

Manually setting some Kestrel configuration and overriding the certificate explicitly gives a warning about not being able to find the dev certificate

### To Reproduce
We have our own centralised way of finding certificates though a CertificateFinder class. We also want to allow users to configure Kestrel in the standard way. We have code like:

```
                        kestrelOptions.Configure(config.GetSection("Kestrel"));

                        if (configuration.TryGetValue("Certificate", out var certName))
                        {
                            var cert = CertificateFinder.FindCertificateFromConfiguration(startup.Configuration, certName);
                            kestrelOptions.ConfigureHttpsDefaults(https => https.ServerCertificate = cert);
                        }
```

Howver this gives the warning:

`Failed to locate the development https certificate at 'NULL'.`

on startup. Ideally it would only warn if it actually had to use the dev cert, which it doesn't in this case. The other option would be to be able to disable the dev cert entirely.

Any workarounds welcome!

**Comment by bencyoung** [comment]
Note in this case the config is actually empty

**Comment by javiercn** [comment]
@bencyoung thanks for contacting us.

I'm not sure what you are trying to accomplish. Are you explicitly setting the configuration to use a certificate and that certificate is null?

AFAIK, we will warn you if we can't find the development certificate if you didn't specify an HTTPS cert and didn't explicitly configure the listening urls.

We don't really know if you tried to specify a certificate (specially if you assign it to null) and we will warn you in that case since we will try to find the default development certificate and won't be able to do so.

For workarounds, the best thing you can probably raise the logging level for the given scope to error, but that might skip other warnings/errors within the config processing.

**Comment by bencyoung** [comment]
The issue is in the config reading code in Kestrel:

```
            if (configReader.Certificates.TryGetValue("Default", out var defaultCertConfig))
            {
                var defaultCert = LoadCertificate(defaultCertConfig, "Default");
                if (defaultCert != null)
                {
                    DefaultCertificateConfig = defaultCertConfig;
                    Options.DefaultCertificate = defaultCert;
                }
            }
            else
            {
                var logger = Options.ApplicationServices.GetRequiredService<ILogger<KestrelServer>>();
                var (certificate, certificateConfig) = FindDeveloperCertificateFile(configReader, logger);
                if (certificate != null)
                {
                    logger.LocatedDevelopmentCertificate(certificate);
                    DefaultCertificateConfig = certificateConfig;
                    Options.DefaultCertificate = certificate;
                }
            }
```

In this case:
1) We've asked it to read config but not actually supplied any (as the defaults are fine and we're using "urls" to pass the hosting paths
2) I don't have a dev certificate installed
3) We manually override the default certificate later

Ideally the warning would only come later if one isn't supplied. 

However in Core 3.1 it looks like this warning is suppressed if the cert path is null so I'll close this...
