### ISSUE TITLE
Unable to serve Blazor WASM 

### ISSUE THREAD

**Issue by john-cullen** [dotnet/aspnetcore#24397]
### Describe the bug
I have a Blazor WASM project that works when I run it directly, but when referenced in my server project (which also includes a signalr hub and a handful of API controllers) none of the Blazor content is served, not even `_framework` URLS.

The project files for the server and client projects and other relevant files are included in the following gist:

https://gist.github.com/john-cullen/f1bc278287928b9924aecc9c865af538

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: latest Visual Studio 2019 Professional

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.1.805 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@john-cullen thanks for contacting us.

Unfortunately the information that you provided is not enough for us to help you troubleshoot the issue. Could you produce a minimal repro project (Zip or GH repo) and include the necessary steps to reproduce the issue?

There are small details that can easily be missed otherwise and prevent us from reproducing the problem.

**Comment by john-cullen** [comment]
@javiercn https://github.com/john-cullen/Blazor-Reproduction

`dotnet run --project Server.csproj`

Try to open `http://localhost:8082`

**Comment by john-cullen** [comment]
If I change the project SDK type to `Microsoft.NET.Sdk.Web` and add a `launchSettings.json` file it works *IF* the `ASPNETCORE_ENVIRONMENT": "Development"` environment variable is set.

The project I based on the example set already as the environment variable above in a `launchSettings.json` file, but I guess it isn't reading it if the project SDK is `Microsoft.NET.Sdk` despite the project file having `<FrameworkReference Include="Microsoft.AspNetCore.App" />` set.

Can I retain the SDK type as `Microsoft.NET.Sdk` yet trigger whatever the behaviour difference is? 

If not is there documentation on what the differences are between the project types? I can think of some things that would need to be changed in our project to work with the Web SDK type but there may be more. For example, https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview does not mention the different value that `AppContext.BaseDirectory` has.

**Comment by pranavkm** [comment]
Thanks for the issue repo @john-cullen. Blazor WebAssembly relies on the static web assets feature to be able to serve it's contents when it's referenced. As you discovered, it's only available by the Web SDK. Static web assets adds special behavior during Development that is only introduced by the presence of the `Development`. 

For web apps, we generally recommend targeting the WebSDK since there are other features like this that are only enabled by that SDK reference. 

> If not is there documentation on what the differences are between the project types? 

Unfortunately there isn't. However, the Web SDK is a super set of `Microsoft.NET.Sdk`. It should largely be very compatible with the ,NET SDK.

> does not mention the different value that AppContext.BaseDirectory has.

I'm not familiar with this. There shouldn't be a difference to this value based on the SDK you're targeting.
