### ISSUE TITLE
Changing UserName desyncs with Normalized

### ISSUE THREAD

**Issue by hgGeorg** [dotnet/aspnetcore#24400]
### Describe the bug
`UserName` and `NormalizedUserName` desync when setting `UserName` to an already existing value using `UserManager`. Eg. 

1. there are two users: johndoe1 and johndoe2
2. their respective `NormalizedUserName` are JOHNDOE1 and JOHNDOE2
3. using `UserManager<IdentityUser>.SetUserName` change johndoe1 to johndoe2
4. now we have two johndoe2 but with different `NormalizedUserName`

This is kinda confusing since it's **not** possible to **create** users with duplicate usernames. Same thing happens with `Email`

### To Reproduce
https://github.com/hgGeorg/UserNameDesyncDemo

`UserController.Demontrate` should contain enough to reproduce. InMemory database is used, but the issue can be reproduced with SqlServer.

### Further technical details
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by blowdart** [comment]
Email is expected, unless you configure for unique emails.

@HaoK is the usermanager supposed to enforce this, or is it up to an external check first?

**Comment by HaoK** [comment]
Well we enforce it to the best that we can, the username uniqueness check is done at the UserValidator level, but if the user poco is manipulated directly and it gets saved to the database via some other mechanism, its possible they get out of sync.   

The validation we do is only done as part of the UpdateAsync call in user manager which is generally how we save the user.

Safer approach is to just modify the user poco directly, and call Update rather than SetUserName/Email methods

**Comment by HaoK** [comment]
Then update will fail if there's a duplicate

**Comment by hgGeorg** [comment]
> Email is expected, unless you configure for unique emails.

Email is setup as unique in my sample.

> but if the user poco is manipulated directly and it gets saved to the database via some other mechanism, its possible they get out of sync.

I'm only using UserManager to manipulate the user, but UserName/NormalizedUserName still get out of sync.

> Safer approach is to just modify the user poco directly, and call Update rather than SetUserName/Email methods

Modifying poco directly, then calling UserManager.UpdateAsync still desyncs UserName and NormalizedUserName, unless I manually set NormalizedUserName myself. I can work with that but is this expected behaviour?

**Comment by HaoK** [comment]
What do you mean by desyncs exactly?  The expectation is that the poco won't be saved into the database until its validated which means username is unique.  I'm not sure what the semantics of in memory database is, but its likely this won't be possible, so that's not a valid database to test against.  With the sql database, the state of the POCO is irrelevant, its what data is in the database record.  Are you saying the row actually gets out of sync or are you just looking that the user instance in code.

**Comment by hgGeorg** [comment]
Sorry, I looked at the wrong data in my last test. Your first comment does solve my problem.
