### ISSUE TITLE
IHttpContextAccessor.HttpContext always null

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/aspnetcore#24416]
### Describe the bug
`IHttpContextAccessor.HttpContext` always returns null when testing an external service.
The actual need of the `HttpContext` is its `IFeatureCollection` or more precisely, its `IHttpAuthenticationFeature`, so that the service can obtain the authentication claims in the current session.

I believe this is by design, but there should at least be a way to inject fake controllers to a web-api, so we're able to test surrounding services, like [this](https://bit.ly/313Mxwy) example.

### To Reproduce

- Create an ASP.NET Core API project
- Add `AddHttpContextAccessor` to its service registration in _Startup.cs_
- Add a test project and add a test utilizing `WebApplicationFactory<Startup>.Services` to acquire the accessor
- Its `HttpContext` property will be null

Full repro project [here](https://bit.ly/2P68Ps5).

### Further technical details
- ASP.NET Core version 3/5
- VS 16.6

**Comment by javiercn** [comment]
@weitzhandler thanks for contacting us.

I think that is expected. The HttpContext will only be available within the scope of the request. When you call it through `WebApplicationFactory<Startup>.Services` it has not been set.

If you rend a request and put a breakpoint on the service is it not set? If that's the case, it can be because test server doesn't set it. You could correct that by injecting a middleware with an IStartupServicesFilter to correct it.

You could also completely replace IHttpContextAccessor with your own mock to provide whatever value you want.

Unfortunately, I can't load the links you provided, so I can't give you a more detailed answer, since it's not clear to me what exactly the scenario is.

**Comment by weitzhandler** [comment]
Hey @javiercn and thanks for your quick and detailed answer.

> If you rend a request and put a breakpoint on the service is it not set? If that's the case, it can be because test server doesn't set it. You could correct that by injecting a middleware with an IStartupServicesFilter to correct it.

The `HttpContext` works well during a request.

> You could also completely replace IHttpContextAccessor with your own mock to provide whatever value you want.

I want to test that my bearer authentication is properly intercepted by the ASP.NET Core runtime. A mock is not a solution here, it's an integration test.

> Unfortunately, I can't load the links you provided, so I can't give you a more detailed answer, since it's not clear to me what exactly the scenario is.

1. I posted a repro project on GH (weitzhandler/NullHttpContextRepro)
2. I tried to circumvent this test by creating a mock controller (this would be the ultimate solution), which is not recognized by the runtime. I'll add another test for this scenario.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by weitzhandler** [comment]
[Self reference](https://github.com/dotnet/AspNetCore.Docs/issues/19358#issuecomment-667701927), that was the solution to the problem, mocking the controller instead of trying to obtain the `IHttpContextAccessor`.
