### ISSUE TITLE
Add support for .webmanifest file extension

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2442]
_From @madskristensen on Friday, October 27, 2017 3:57:16 PM_

This is used in Progressive Web Apps (PWAs) for the manifest JSON file. 

The content type should be `application/manifest+json`

_Copied from original issue: aspnet/StaticFiles#219_

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, October 27, 2017 4:00:02 PM_

cc @glennc

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, October 27, 2017 4:13:03 PM_

Is there a spec reference?

**Comment by aspnet-hello** [comment]
_From @madskristensen on Friday, October 27, 2017 4:24:22 PM_

<https://w3c.github.io/manifest/#media-type-registration> shows the content type `application/manifest+json` and a little further down in the same chapter the `.webmanifest` file extension.

Sorry, I should have added this when I opened the bug

**Comment by aspnet-hello** [comment]
_From @RehanSaeed on Monday, October 30, 2017 2:59:39 AM_

Just saw this issue, I already raised https://github.com/aspnet/StaticFiles/pull/221 to fix this.

**Comment by muratg** [comment]
Backlogging this.

cc @glennc FYI.

**Comment by willdean** [comment]
There's an additional imperative for this now, because the usual work-around of adding the required mapping to a `StaticFilesOptions` object and passing it to `UseStaticFiles`  then prevents (for reasons I don't properly understand) Blazor Server from initialising its static file service properly.   So you can serve static .webmanifest files, or you can have Blazor Server, but you can't easily do both.

This seems to be because if you pass `StaticFileOptions` to `UseStaticFiles`, the framework stops calling `ConfigureStaticFilesOptions`, which then means that Blazor Server doesn't work (because blazor.server.js isn't served).   

Could we please just have the mapping entry?  Someone even filed a one-line PR for this over two years ago #221 - if just seemed to get lost somehow.

**Comment by Tratcher** [comment]
@danroth27 @anurse We're getting more hits on this. See the linked PR #7664.

**Comment by Tratcher** [comment]
It's documented by w3c, but not registered with IANA.
https://w3c.github.io/manifest/#media-type-registration
https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by danroth27** [comment]
@SteveSandersonMS How are we handling the manifest media type currently in the new PWA support for Blazor WebAssembly?

**Comment by SteveSandersonMS** [comment]
@danroth27 We call it manifest.json so it uses the default JSON media type. We can switch it to be a .webmanifest file in the future when ASP.NET Core understands that by default. 

In the short term it should make no difference: https://stackoverflow.com/questions/52129281/manifest-json-vs-manifest-webmanifest

**Comment by madskristensen** [comment]
Previously closed dupes: #3613 and #2440

**Comment by anurse** [comment]
> There's an additional imperative for this now, because the usual work-around of adding the required mapping to a `StaticFilesOptions` object and passing it to `UseStaticFiles` then prevents (for reasons I don't properly understand) Blazor Server from initialising its static file service properly.

This seems like a Blazor problem worth investigating (@SteveSandersonMS @danroth27 ).

I'm sending a PR to add the content type mapping.

**Comment by willdean** [comment]
@anurse Please see #19578 which I filed after adding my comment here.
