### ISSUE TITLE
List.Count does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24479]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1131683/listcount-does-not-work.html)._

---
Create a standard Blazor WASM project.
Change the code of the counter Page to the below code
Run it, watch it just completely crash when trying to load the page.
See attachments

```
@page "/counter"

@try
{
	@for (int i = 0; i < NumberBiggerThanListSize; i++)
	{
		@if (Strings.Count < i)
		{
			<div>@Strings[i]</div>
		}
		else
		{
			<div>@i is outside the bounds </div>
		}
	}
}
catch (Exception ex)
{
	<div>@ex. ToString()</div>
}

@code {
	private List<string> Strings = new List<string> { "String one", "String 2" };
	private int NumberBiggerThanListSize = 5;
}
```

---
#### Feedback Bot on 7/30/2020, 07:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mrpmorris** [comment]
Your check is wrong. It should be `if (i < Strings.Count)`

Otherwise for the third iteration of your loop (i = 2) you'll see that 2 < 5 and your code will try to access index 2 of your list, which doesn't exist because indexes are zero based.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by kevonh** [comment]
Wow, just... wow.  I reported the issue using the built in tools in Visual Studio. It opened an issue from developer community.  It sat there for days with no comment, in the meantime, it ALSO got posted here with **no indication** from the other location indicating that it has been moved here. Then after 4 days waiting for some kind of response, I get notified that it was a duplicate and a solution was added.  I popped on over to the community forum to see the link over HERE, and then saw that **NONE OF MY CLARIFYING STATEMENTS MADE IT HERE**. and that it was closed as "_Your question is stupid, try stack overflow_". 

IF you're going to build in tools to report issues, at least have them go to the right place where we, the users, can see your comments and can then follow up for clarification.

As it stands... I **KNOW** the check is "backward" and I put in additional clarification that the issue was that the catch was never reached.  I **WANTED** to throw an index out of bounds error, and for it to be **caught**. 

So, how do we appropriately fill a bug report? It certainly does not seem that using the built in Visual Studio tools is the correct way.

Please re-open this so we can have a dialog on the nature of the problem.

**Comment by mrpmorris** [comment]
Hi @kevonh 

I would recommend ignoring this ticket and posting a new one yourself. Please try to make the repro as simple as possible, comments inline with the code are useful to draw attention to caveats (for example). Also, I don't think anyone thought your question was stupid 👍
