### ISSUE TITLE
[Question] What's the recommended way to implement login functionality without Identity

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#24616]
I have a legacy SQL Server database which already have its own `User` table. What's the recommended way to implement login functionality?

**Comment by blowdart** [comment]
Without identity Javier :p

We don't have any recommendations. What we do have is documentation on how to use the [cookie authentication middleware without identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1), which gives you tamper proof cookies. Beyond that we can't comment on how to go about it.

**Comment by Youssef1313** [comment]
@blowdart Thanks. Are there any security considerations you have in mind when not using identity?

**Comment by blowdart** [comment]
This now becomes opinion, and personal opinion, rather than Microsoft recommends

- You need to be careful when validating your usernames and passwords, especially password comparisons which have to be time consistent.
- You probably want to normalize user names to stop impersonation via unicode characters
- You want to consider your lockout policies, and ways to stop password stuffing, and also figure out a way that you can't lock out admins by sending bad passwords.
- And of course MFA implementations :)

**Comment by Youssef1313** [comment]
I'll look into these. That was very useful. Thanks.
I'll close this as things are clear now.
