### ISSUE TITLE
Blazor hasDebuggingEnabled set when "Start without debugging" in VS

### ISSUE THREAD

**Issue by lewing** [dotnet/aspnetcore#24623]
When blazor is started from inside VS with `Start without debugging` hasDebuggingEnabled is true and load_runtime is passed non zero debug level.  This disables most interpreter optimizations (because they would break debugging) leading to substantially slower execution speed (https://github.com/dotnet/runtime/issues/40428).  Is this the intended behavior?  If not can it be fixed, and if so can it be documented?

https://github.com/dotnet/AspNetCore/blob/master/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L367

**Comment by captainsafia** [comment]
> Is this the intended behavior? 

Nope.

> If not can it be fixed, 

We can try to fix it. We had briefly discussed this class of issues (passing configurations from the IDE down to the debugger, such as start without debugging) but hadn't talked about the specifics.

The JS debugger sets a `noDebug` flag in the config. We might be able to figure out a way to read that from the client and configure the MonoProxy correctly.

> and if so can it be documented?

@guardrex Let's add a note in the debugging section to let users know that "Start without debugging" doesn't work with Blazor WASM on VS.

@mkArtakMSFT This issue would be a good candidate for RC1 as a perf improvement.

**Comment by captainsafia** [comment]
It looks like our best option here is to implement a middleware in the debug proxy that checks to see if there is a chrome process with the `remote-debugging-port` set. I landed on this solution after spiking into a couple of different approaches:

* We can't rely on any client-side checks, including checking `navigator.webdriver`, because pretty soon that will not be set when debugging is enabled ([ref](https://bugs.chromium.org/p/chromium/issues/detail?id=1072836)).
* You can figure out if a Chrome browser is running with debugging enabled by checking the command line arguments listed at chrome://version. Of course, there is no way to check this from the JavaScript on a webpage.
* We can try sending a request to `http://localhost:9222/json/version` and seeing if we get a response. However, there's no way for us to know ahead of time what debugging port (e.g. 9222) is being used by Chrome/Edge, especially if Chrome is launched with any available port (e.g. `remote-debugging-port=0`).
* We could set a flag from the IDE (VS/VS Code) when `Start without debugging` is used. However, this change is a little bit more high cost than the timeline we have here. Also, it makes the change less portable across different scenarios.

So, debug proxy + PID scan strikes the balance between being the most portable and requiring us to know the least ahead of time (e.g. what debugging port is used).

**Comment by captainsafia** [comment]
Orrrrrrrrrrr....alternatively as discussed during today's Blazor engineering sync we can have the user explicitly set whether or not they want to debug via a query parameter.

1. User starts debugging.
2. User navigates to`https://localhost:5001?debug=true`.
3. We parse the query params and set the flag accordingly.

VS Code and VS will need to update the launch URL of the application accordingly.

**Comment by captainsafia** [comment]
We reverted this change and will put in a more robust fix for 6.0 so re-opening.

**Comment by guardrex** [comment]
@captainsafia ... Should I close the docs issue :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/19545?

**Comment by captainsafia** [comment]
@guardrex Yes.

**Comment by pranavkm** [comment]
@lewing given this is a dev scenario and fixing it seems tedious at best, I'm going to mark this as won't fix. Let me know if you feel very strongly about fixing it.
