### ISSUE TITLE
Alternative to <base href="/" /> to specify the root of a Blazor app

### ISSUE THREAD

**Issue by jeremycook** [dotnet/aspnetcore#24631]
### Is your feature request related to a problem? Please describe.

I am trying out integrating Blazor Server Side into an existing ASP.NET Core MVC 3.1 web application. I am using the `<component type="typeof(..)"./>` TagHelper and everything is working nicely, but one glaring issue is that developers and content authors alike will not be able to use relative URLs (`<a href="../path-to/other-page/relative-to-current-page.html">Other Page</a>`).

Not the end of the world but it would be nice to benefit from Blazor without taking on this sometimes awkward convention--a convention that makes sense for Blazor only SPAs, but can conflict with other assumptions/pre-existing conditions when embedding Blazor into an existing or multi-paradigm web application.

I looked through [open issues related to blazor base href](https://github.com/dotnet/aspnetcore/search?q=blazor+base+href&state=open&type=Issues) and found nothing that addresses my issue directly. I found quite a few issues that demonstrate that the current convention creates challenges. It also seems to be surprising since using paths like "~/whatever" is a standard convention when it is necessary to reference a resource relative to the root of an ASP.NET Core web application.

### Describe the solution you'd like

Please provide an alternative to `<base href="/" />` to specify the root of a Blazor app.

An alternative could look like this in a static context:

```html
<meta name="blazor-base-href" content="/" />
```

or like so in an ASP.NET Core context:

```html
<meta name="blazor-base-href" content="@Url.Content("~/")" />
```

Setting this through configuration in Startup.cs or maybe _Imports.razor are other alternatives.

**Comment by javiercn** [comment]
@jeremycook thanks for contacting us.

> Not the end of the world but it would be nice to benefit from Blazor without taking on this sometimes awkward convention--a convention that makes sense for Blazor only SPAs

All blazor applications are SPAs since navigations happen client-side when you have a router

> I found quite a few issues that demonstrate that the current convention creates challenges

`<base href="<<something>>" />` is the standard way to make this work on the web. Without it any document relative url doesn't work. From what I understand on your proposal, you want some sort of `base href` that selectively applies to Blazor. This is not a direction we are planning to pursue, introducing an alternative and selective way of doing this will introduce a different set of problems that will affect a broader set of customers.

If we were to have different ways of specifying the base path, there would be ambiguity about which one wins or worse, different definitions will apply depending on the context. Some urls on the document would be interpreted based on the "base" tag and some others would be based on the meta tag. That's not an experience we are confortable having. AFAWK no other UI framework has this concept or has needed it, so I don't think Blazor is any different. 

Blazor applications are SPAs, they are initialized with the url from the browser, not the url on an HTTP request, and the navigation context relates to the current url on the browser, not the original request that rendered the page. For that reason, things like `~/` don't make sense in the context of a blazor app, since there is no "virtual/base path context` and that is why the only `base` concept that it exists is the one that HTML specifies and that dictates how document relative urls behave.

I understand that this might not match your expectations, and I agree that this is a confusing area and requires a bit of learning to successfully deal with how urls are interpreted and so on, but the reality is that this is the mechanism HTML provides to deal with urls on a document and that is not something we are willing or capable to change.

**Comment by jeremycook** [comment]
Thanks for clarifying @javiercn 

`<base href>` is an elegant way to handle this in SPAs and I see your point that Blazor is always a SPA. Its behavior when I use `<component>` and blazor.server.js confirms that. I guess I am still a little surprised the routing system has no concept of a base path (beyond what the browser transparently provides) and there is no desire to introduce such a system. I will keep this in mind when deciding if Blazor is a good fit. Thanks again for your time and the thorough response.
