### ISSUE TITLE
Cached name persists after re-naming file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24665]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1135857/cached-name-persists-after-re-naming-file.html)._

---
Working in Blazor WASM.  I created a component "MyComponent".  Then, I copied/pasted the file in the same folder so that the component's name was "MyComponent - Copy".  Then I re-named the file as "MySecondComponent".

Next, I tried to add "MySecondComponent" to a page, but it was not being recognized as a valid component. I DID see "MyComponent - Copy" as an option, even though that didn't exist anymore.

I closed Visual studio, re-launched the same solution and the issue disappeared.

---
#### Feedback Bot on 8/5/2020, 00:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
