### ISSUE TITLE
Capture reference to blazor components with nullability enabled always gives warning on net5.0 preview 7

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#24794]
When project nullability is enabled there is no way to capture a reference to a blazor component without generating a compiler warning.

### Steps to reproduce
* Create template project: `dotnet new blazorwasm`
* Edit project file, add `<nullable>enable</nullable>`
* Build -> observe there are some nullable warnings, ignore these they can all be fixed by updating the code
* In `Index.razor` add the following:
```
@code {
   SurveyPrompt p;

}
```
* In `Index.razor` update the component line to read: `<SurveyPrompt @ref=p Title="How is Blazor working for you?" />`
* Build the project again -> observe warning line #7 `CS8618: Non-nullable field 'p' is uninitialized'`
* Change declaration to: `SurveyPrompt? p;`
* Build again -> observe warning line #7`CS8600: Converting null literal or possible null value to non-nullable type`

<b>There seems to be no way to get rid of this warning. If it was somewhere in c# code one could have added a pragma around the specific line, but since the warning is in the razor part of the file it cannot be disabled for that specific line only</b>

**Comment by pranavkm** [comment]
> There seems to be no way to get rid of this warning:

How about:

```
@code {
   SurveyPrompt p = default!;
}
```

**Comment by tn-5** [comment]
```
@code {
   SurveyPrompt p = default!;
}
```

results in 

`warning CS8601: Possible null reference assignment`

changing the ref to: `  @ref=p! ` results in:
```
error CS8598: The suppression operator is not allowed in this context
```

**Comment by SteveSandersonMS** [comment]
I had a quick look into this just to understand it, since it was surprising. Possibly the issue is here:

https://github.com/dotnet/aspnetcore/blob/40869f8969dbbf24b7668f0284c6abbf40ce093c/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L589

The callback is typed as `Action<object?>`, which means the following generated code:

```cs
        __builder.AddComponentReferenceCapture(3, (__value) =>
        {
#nullable restore
#line 7 "C:\Users\stevesa\Desktop\BlazorP8StandupDemo\ServerApp\Pages\Index.razor"
            myInstance = (ServerApp.Shared.SurveyPrompt)__value;

#line default
#line hidden
#nullable disable
        }
```

... produces a warning because `__value` is `object?` and we're casting to a non-nullable type.

I suspect it would be correct to change the callback type to `Action<object?>` because we know the framework will only pass nonnull values to it.

**Comment by egil** [comment]
That was my conclusion as well @SteveSandersonMS.
