### ISSUE TITLE
Different response headers for GET/HEAD when using response compression middleware

### ISSUE THREAD

**Issue by akashsax14** [dotnet/aspnetcore#24844]
### Describe the bug
When response compression middleware is used and a GET/HEAD request is made with Accept-Encoding header set as "gzip", the response to GET request contains the Content-Encoding header with value "gzip" and no Content-Length header but the response to HEAD request contains no Content-Encoding header with Content-Length header value as the uncompressed content length.

### To Reproduce
[Git repo](https://github.com/akashsax14/dotnet_response_comp_bug) for reproducer
1. Run the ASP.NET Core application using ResponseCompBug launch profile
2. Open postman or similar api testing application and make the following requests with Accept-Encoding header as gzip
     - GET https://localhost:5001/api/values
     - HEAD https://localhost:5001/api/values
3. Expect to get same headers for GET and HEAD but are not

### Further technical details
- ASP.NET Core version : 2.2
- Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Tratcher** [comment]
Side note: 2.2 is out of support, please update to 3.1.

Fair point. In the RFC this is listed as a best effort requirement ("SHOULD").
https://tools.ietf.org/html/rfc7231#section-4.3.2
"The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted."

Note that Content-Length and Transfer-Encoding are considered payload headers and are optional for HEAD responses.

The current behavior is because the response compression middleware only reacts to writes on the response body.
https://github.com/dotnet/aspnetcore/blob/ff4db3627f974573d3eb24c3436f56dbce1964f7/src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs#L234-L236

A well written app component won't write to the response body for a HEAD request, so the middleware doesn't trigger.

We could probably add a special check for HEAD requests in FinishCompressionAsync that's called at the end of the request.
https://github.com/dotnet/aspnetcore/blob/ff4db3627f974573d3eb24c3436f56dbce1964f7/src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs#L43

**Comment by alefranz** [comment]
I've sent a PR #28464
Hopefully no one was already working on it as it is only marked as nice to have.
