### ISSUE TITLE
Blazor - class conflict with non-existing files after moving class files into a subfolder

### ISSUE THREAD

**Issue by arc488** [dotnet/aspnetcore#24933]
So, I had my Razor component is a folder 

> MyApp.App -> Components

, and everything was working just fine. but then I moved the files to 

> MyApp.App -> Components -> Subfolder

Now I get errors such as:

`Error	CS0104	'AddUnitAssetDialog' is an ambiguous reference between 'myapp.App.Components.Subfolder.MyComponent' and 'myapp.App.Components.MyComponent
`

Even tho the files in the main folder no longer exist in the project tree or when browsed in explorer.

Furthermore, my component C# and Razor file (which are connected like this "MyComponent.razor" and "MyComponent.razor.cs") don't see each other after I move them as described above, using @inherits doesn't help either. Even tho, they worked perfectly before I moved them.

The only workaround right now is for me to create a new file under a different name, and copy my code from broken files into the new files. As you can imagine, this is very frustrating.
`

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
