### ISSUE TITLE
[Blazor] Events and Dispose guidelines

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#24989]
Hi,

Is it necessary to implement ```IDisposable``` to remove event handlers? The documentation suggests so, but is this really a good practice? This is not something that I would typically do using other .NET UI frameworks.

 https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1

Here's a trivial example:

```
        protected override void OnInitialized()
        {
            OnShow += Settings_OnShowAsync;
        }
```

```
        private async void Settings_OnShowAsync()
        {
        ....
        }
```

```
        public override void Dispose()
        {
            base.Dispose();
            OnShow -= Settings_OnShowAsync;
        }
```

Is it OK to omit ```Dispose``` method?

Thanks.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

The guidance is correct. You should remove any event handlers you set during dispose to avoid memory leaks. I'm not sure about other UI frameworks, but forgetting to remove event handlers is a common cause on memory leaks, and I'm pretty certain it affects other frameworks too since this is just C# and there is no magic behind it.

If you attach an event handler to an event that outlives the component/handler type, then even though the framework might not be referencing it, the fact that you didn't unregister the event handler will mean that the object instance containing the handler will be kept alive longer than expected.

Additionally, if you then re-render that component again, it is likely you'll attach another event handler instance to the same event and the problem will grow bigger and bigger over time.

So in practice, the guidance there only reflects the C# general guidance. After you are done with an object, you should unregister any event handler it has set to avoid the object being kept alive and the memory leaking as a result.
