### ISSUE TITLE
Remove design time helper members from C# completion list

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#25091]
We should look at the code we generate and remove any Razor design time helpers from C#'s completion list. For instance one example is to remove the `__o` variable. Makes sense to do this in VS & VSCode

**Comment by AmadeusW** [comment]
Currently the design time helper is preselected, which means that typing `@{` results in committing this item, and user gets `@__o{`
![image](https://user-images.githubusercontent.com/1673956/90823939-7ec12300-e2eb-11ea-8ca8-4181a6618ecf.png)

**Comment by ryanbrandenburg** [comment]
Is there a way to know programmatically if something is design-time only? I assume maintaining a list is not possible because someone can have a variable in their page named `__o` if they want.

**Comment by NTaylorMullen** [comment]
> Is there a way to know programmatically if something is design-time only? I assume maintaining a list is not possible because someone can have a variable in their page named `__o` if they want.

Not really. We have a list of known "Razor" included monikers such as __o __RazorDirectiveTokenHelpers__ etc.

**Comment by ryanbrandenburg** [comment]
I suppose if we changed the code-gen to always prepend `generated.` to the variable gen, but then that probably makes CodeActions, Hovers, and other places a mess. You're right, it's probably not worth it to do a bunch of work to make it 100% correct just in the unlikely case that someone names their variable `__o`.

**Comment by NTaylorMullen** [comment]
If someone named their variable __o we'd explode anyhow 😄

**Comment by TanayParikh** [comment]
Also applies for:
- `__builder`
- `__RazorDirectiveTokenHelpers__`

**Comment by allisonchou** [comment]
After experimenting with the proposed solution of "if the current identifier that's being targeted actually starts with a double underscore identifier, don't trim them out; otherwise do" (creds to Taylor), I've run into an interesting case with the solution I'm not sure how to address:

Say the user defines the variables "\_1 and "\_\_2". If the user types "\_1", then backspaces to "_", and finally types one more underscore to make the text "__", the same initial completion session will active, and therefore we will not get "__2" in the completion list.

The same issue also applies when typing "\_", manually invoking completion, and then typing another "_".

@NTaylorMullen, @TanayParikh, @ryanbrandenburg - do any of you perhaps have thoughts on this? I'm not sure if there's a workaround here (at least on the Razor side), since I believe the Editor is the one determining the life cycle of a completion session.

**Comment by ryanbrandenburg** [comment]
Hmm, that's unfortunate but it is an edge-case (backtyping `_`) of an edge-case (naming variables  `__`). I'd be OK to waiting to hear feedback on that before we do anything complicated to make it work unless someone has a simple solution.

**Comment by NTaylorMullen** [comment]
I think that's an OK limitation to have. Worse case the user dismisses completion then re-invokes. Once isIncomplete is supported it may also give us additional options to support that edge case if we want to

**Comment by allisonchou** [comment]
This has been addressed in https://github.com/dotnet/aspnetcore-tooling/pull/2994.
