### ISSUE TITLE
Title component causes a warning in VS if it doesn't have a separate closing tag

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25149]
Visual Studio things our new `Title` component is a normal HTML `title` tag. It adds a warning if you don't close the Title component with a separate closing tag. 

![image](https://user-images.githubusercontent.com/1874516/90951747-613aa900-e412-11ea-851c-c1130100beb7.png)

The completions on the Title tag are also pretty noisy:

![image](https://user-images.githubusercontent.com/1874516/90951770-8c24fd00-e412-11ea-974e-8e850dab1622.png)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

**Comment by NTaylorMullen** [comment]
Oh and @danroth27 and this kind fellow wrote this article that you should super check out if you haven't: https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/

He's the best
