### ISSUE TITLE
Why InputText,ValidationMessage ? why not doing it like  asp-for , asp-validation-for

### ISSUE THREAD

**Issue by Hanisafa** [dotnet/aspnetcore#25302]
Hi , 
i was porting asp razor page website to blazor , i got this question why blazor is using <ValidationMessage> and <InputText>
can you make like asp tag helper ? tag helper make me feel that i have more control over the elemnt , its just a pane HTML markup

this is asp razor page code 

div class="form-group"
                label asp-for="School.Phone" class="control-label"></label>
               input asp-for="School.Phone" class="form-control" />
                span asp-validation-for="School.Phone" class="text-danger"></span>
/div

this is how i port it

` <div class="form-group">
                <label>Phone</label>
                <InputText @bind-Value="CurrentSchool.Phone" class="form-control" />
                <ValidationMessage For="(() => CurrentSchool.Phone)" class="text-danger" />
            </div>`

**Comment by SteveSandersonMS** [comment]
Maybe at some point in the future we might have a taghelper-like way of instantiating components, however it's quite difficult to see how a design would work well for that in an end-to-end way, for example composing together multiple unrelated magic attributes. It's quite different to the whole architecture of the framework. That's why we haven't done it yet.

Blazor is a component-oriented framework, so it makes sense that things like rich input controls are provided as components.
