### ISSUE TITLE
 Microsoft.AspNetCore.SignalR.Client package does not indicate that it needs Microsoft.AspNetCore.Http v3.1

### ISSUE THREAD

**Issue by TehWardy** [dotnet/aspnetcore#25305]
It would be nice if the system could detect when I depend on 2 different things that in turn share a dependency but different versions.
I'm constantly told by Microsoft devs that I need to add a reference I don't directly depend on as a result of lengthy support processes, having the system determine this for me would save me and Microsoft a ton of time.

Classic example ...
Create a new Azure functions App, add SignalR to it, ensure you reference the latest of both dependencies.
This is the feedback I got ...

>For some reason it seems that the build calculates Microsoft.AspNetCore.Http.dll should be 2.1, but it seems that something in SignalR depends on types in the 3.1 version. Since this is such a rare scenario I likely won't investigate too deeply unless it becomes a bigger problem.

... after a week or so of witch hunting.

There should be a way to force consistency and have the system figure this stuff out unless I have explicitly forced a conflict in to the project tree.

**Comment by TehWardy** [comment]
The issue is not that the reference is right or wrong here. 
The point of raising this ticket was to request that some means to show / crawl / detect what's going on in a complex solutions dependency tree from within VS.

For example ... 
What if I could right click on a project and select an option like "analyse dependency tree" or something and it brings up a new tab showing the crawl of all the references, the common things they depend on and when they are different "suggest" a means to resolve (e.g. reference a set version of the dep of that dep).

In the example shown ...
Azure functions wants one version of a dependency and SignalR wants another version.
Those are my direct dependencies but it's not clear how the build process will resolve the "in-direct" dependencies I have.

**Comment by dsplaisted** [comment]
This looks like an issue with Azure Functions to me.

**Comment by davkean** [comment]
@TehWardy We already detect conflicts of indirect dependencies via restore/build. However, this requires that packages declare their correct dependencies. One of these packages is not.

@dsplaisted How did you come to the conclusion? I don't really understand the packages or pieces in play here.

**Comment by dsplaisted** [comment]
> How did you come to the conclusion? I don't really understand the packages or pieces in play here.

I think I have seen issues in the past specific to Azure functions caused by things they were doing like pinning to a specific version of NewtonSoft.Json, or customizing how assemblies are loaded.  I don't remember the details.  It's also possible that this could be an incorrectly authored package, but to me it felt like it might be something specific to Azure Functions.

**Comment by TehWardy** [comment]
You may be right you can see from the ticket above that my work with @brettsam has resulted in us coming to a conclusion that there is a reproducable problem that does appear to be an only Azure Functions problem (i even provided a repro project and pushed it to git.

I raised this ticket because I'd like some tooling on my client that lets me identify when packages that I depend on have conflicting dependencies between them as it's not always obvious / a trivial fix.
This may be a simple case of having to force that a particular version be used of the conflicting dependency but it's one of those areas that I suffer most with .Net in general.

I was hoping the VS project system could be built to provide some insight in to whats going here so that when I log a ticket like this it's not handed around as much and the team involved with fixing it get targeted informationwithout me having to build an application project to show the complex hole I got lost in.

**Comment by davkean** [comment]
This command is that context for issues:

```
msbuild [project] /binlog:Bug.binlog
```

This produces a file that can be opened in: https://msbuildlog.com/. That is the first thing I did with your repro and helped me understand the packages and their dependencies.

We do have features to catch incompatibilities but it does require that packages to correctly specify their dependencies. TBH, I don't understand the problem well enough to know what other actionable features we can help to catch this issue. I'm hoping that SignalR folks can tell me that, hence moved the bug here.

**Comment by TehWardy** [comment]
Can we get that info in to VS as a project context menu option ?

**Comment by davkean** [comment]
This is an extension that provides it: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools. But we are thinking about providing it the box.

**Comment by TehWardy** [comment]
neat i'll give it a whirl :)

**Comment by BrennanConroy** [comment]
Can you share your project.assets.json from the built project (in your bin folder)

**Comment by davkean** [comment]
This is from the Azure functions project:

[project.assets.json.txt](https://github.com/dotnet/aspnetcore/files/5153002/project.assets.json.txt)

**Comment by TehWardy** [comment]
did you compile against .Net Core 2 or am I just seeing a lot of packages that have .Net Core 2 framework refs?

The most core of them at a glance appears to be this ...

```
      "Microsoft.CSharp/4.5.0": {
        "type": "package",
        "compile": {
          "ref/netcoreapp2.0/_._": {}
        },
        "runtime": {
          "lib/netcoreapp2.0/_._": {}
        }
      },
```

Most of aspnet core seems to have pulled 2.x dependencies.

**Comment by BrennanConroy** [comment]
Can someone summarize the issue here? It's not clear what is wrong and what sort of action we're supposed to be taking.

Also, that project.assets.json file has 4 different netcoreapp references (2.0, 2.1, 3.0, and 3.1), we generally recommend you only have 1 of those referenced as there is no guarantee that they will work together.

**Comment by davkean** [comment]
> Also, that project.assets.json file has 4 different netcoreapp references (2.0, 2.1, 3.0, and 3.1), we generally recommend you only have 1 of those referenced as there is no guarantee that they will work together.

As a consumer of this, how do I figure that out the support policy? Why don't we prevent this from building by using capping the references on these packages so the user can get build enforcement of this?

**Comment by dsplaisted** [comment]
> Can someone summarize the issue here? It's not clear what is wrong and what sort of action we're supposed to be taking.
> 
> Also, that project.assets.json file has 4 different netcoreapp references (2.0, 2.1, 3.0, and 3.1), we generally recommend you only have 1 of those referenced as there is no guarantee that they will work together.

What do you even mean by having 4 different netcoreapp references?  I don't see that in the assets file.

**Comment by TehWardy** [comment]
I'm summarising here but I think this is what @davkean is pointing at ...

@BrennanConroy The issue is that an Azure Function / Build Process is resolving the wrong version of a dependency that aspnet core has internally when consuming the SignalR package at this point.
It's part of a bigger issue in "generally" getting a complete working stack that involves some Roslyn calls, ultimately dynamically loading and working with "everyhting in the app domain".

There's a mix of things going on but one "culprit" suggested by the Functions Team is that the SignalR package is "reporting the wrong dependency version" when complied against the latest version of .Net Core (3.1, i'm excluding the .Net 5 previews).

Given a standard build with a stack of .Net Core 3.1 packages that I depend on (including SignalR) I should not "indirectly" be seeing the Build process resolve .Net Core 2.x dependencies at all.

How do consumers of SignalR ensure the correct dependency tree is resolved by the Build process?

**Comment by BrennanConroy** [comment]
> the SignalR package is "reporting the wrong dependency version"

I find that extremely hard to believe. Can you provide any evidence that that's the case? A repro app etc?

> Given a standard build with a stack of .Net Core 3.1 packages that I depend on (including SignalR) I should not "indirectly" be seeing the Build process resolve .Net Core 2.x dependencies at all.

The assets.json provided above and the csproj you provided in the linked issue shows a reference to Microsoft.NET.Sdk.Functions 3.0.x which is bringing in 2.1 references of AspNetCore assemblies.

**Comment by davkean** [comment]
@dsplaisted In the targeting pack world, how does SignalR.Client indicate that it needs 3.x equivalent of .NETCoreApp references? The problem here is that SignalR.Client can be installed into a project that has 2.x dependencies and the build does not complain, or promote the references to 3.x.

The expectation can't be that the user has to implicitly know that SignalR.Client needs 3.x equivalent of .NETCoreApp, we should not let the projects construct dependency graphs that will not work.

**Comment by dsplaisted** [comment]
> @dsplaisted In the targeting pack world, how does SignalR.Client indicate that it needs 3.x equivalent of .NETCoreApp references? The problem here is that SignalR.Client can be installed into a project that has 2.x dependencies and the build does not complain, or promote the references to 3.x.

I looked at this a bit more and I think I have a bit of a better understanding of what's going on.  If the app depended on the ASP.NET Core shared framework, then the 2.x references would get promoted to 3.x (the 2.x assets would still be in the assets file but the `ResolvePackageFileConflicts` task would choose the 3.x assets from the targeting pack).

It sounds like the issue is that `GetExportedTypes` is failing.  It would be helpful to see the actual error message / stack trace that is happening.

It looks like SignalR.Client is not supposed to require ASP.NET Core.  This is why it targets .NET Standard 2.0, allowing it to run on full Framework, or Xamarin, etc.

Perhaps the issue is that it includes types that only can load when running in ASP.NET Core, but normally those types wouldn't be loaded if ASP.NET Core wasn't loaded.  The GetExportedTypes() call forces them to load anyway, causing the error.

That's just an educated guess, like I said it would help to see more information about how GetExportedTypes is failing.

**Comment by BrennanConroy** [comment]
Please provide a repro app that shows an issue with AspNetCore, otherwise we're keeping this in discussion until some action is found.

**Comment by TehWardy** [comment]
The original ticket that this is linked to has this project ...
https://github.com/TehWardy/ScrapHeap

It's basically a minimum required to reproduce the issue I am having and it goes bang on the GetExportedTypes call mentioned by @dsplaisted above.

If the issue is in SignalR a build of that project should show you what you are asking.

**Comment by BrennanConroy** [comment]
Can you provide repro steps? It's more complicated than just pressing F5 in VS.

**Comment by TehWardy** [comment]
My understanding is that you need to compile with the verbose option on and it should be in the output window what dependencies are resolved.

As @davkean  showed here https://github.com/dotnet/aspnetcore/issues/25305#issuecomment-684085654 though it's all detailed in the project.assets.json.txt file.
I'm guessing this is generated by some tooling somewhere, you guys are now in territory i'm not familiar with.

**Comment by TehWardy** [comment]
ping
