### ISSUE TITLE
NavigationManager.Validate System.ArgumentException: The URI 'https://localhost:5001/BlazorHost/BlazorAppRealTime' is not contained by the base URI 'https://127.0.0.1.xip.io:5001/BlazorHost/BlazorAppRealTime/'.

### ISSUE THREAD

**Issue by ghstahl** [dotnet/aspnetcore#25328]
I have a working Blazor WASM that I serve via asp.net core 3.1. 

```
 <base href="/BlazorHost/BlazorAppRealTime/" />
```
where my server url is ```https://localhost:5001```.  
Given the same app I did an experiment by changing the above to the following;
```
<base href="https://127.0.0.1.xip.io:5001/BlazorHost/BlazorAppRealTime/" />
```
After I got my CORS stuff sorted, all the blazor files came down and now I am getting the following error;  
```
blazor.webassembly.js:1 ﻿System.ArgumentException: The URI 'https://localhost:5001/BlazorHost/BlazorAppRealTime' is not contained by the base URI 'https://127.0.0.1.xip.io:5001/BlazorHost/BlazorAppRealTime/'.
at Microsoft.AspNetCore.Components.NavigationManager.Validate (System.Uri baseUri, System.String uri) <0x2b300c0 + 0x0004c> in <filename unknown>:0 
```
<img width="1285" alt="Annotation 2020-08-27 143837" src="https://user-images.githubusercontent.com/201257/91497938-b132c900-e873-11ea-80f2-18f515ddea93.png">
 

The idea is to allow different teams to host their own blazor app and backends independent of the main website.  Ultimately I would like to wrap a blazor wasm in a webcomponent.

Should I be able to pull my blazor app from a different domain then what my main website is?  The current NavigationManager code is gating me clientside.

**Comment by Krzyrok** [comment]
You can check workaround described here: https://github.com/dotnet/aspnetcore/issues/22220#issuecomment-683783971

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `base href` should not contain domain and port.
Also, we currently only support hosting multiple blazor apps on the same page via iframe-s.

**Comment by Krzyrok** [comment]
Technically, `base href` could have full URL (with domain) as in the examples in the MDN https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#Examples . I understand that it is not handled currently by Blazor but any plan for handling it? Or maybe better way to handle loading app from different domain (in addition to iframe).

**Comment by Krzyrok** [comment]
BTW there is another problem with local development of Blazor WebAssembly app when `base href` is specified (even as relative path). I followed https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path 
All of the files are hosted correctly, at subpath (also `_framework/blazor.boot.json`). But request for `_framework/blazor.boot.json` does not take into account this subpath: it tries to load `blazor.boot.json` from the root and I've got 404.
```dotnet --version: 3.1.302```
In this way, `base href` is useless for me (still one file is loaded without subpath). 

It can be connected with https://github.com/dotnet/aspnetcore/issues/22220 but this issue is marked as feature/enhancement (this what I mentioned is a bug, I believe). Should I create separate issue for this? Or maybe I'm missing something?
