### ISSUE TITLE
Blazor CascadingParameter design has multiple flaws

### ISSUE THREAD

**Issue by velocitytoo** [dotnet/aspnetcore#25366]
The Blazor CascadingParameter design has multiple flaws:

A child component has to know that its parameter will be used in a cascading manner and has to decorate the parameter with [CascadingParameter]. Why not just come up with a design so that a child component does not have to know whether or not it will be used in a cascading manner? This would be a much better SOC design; only the parent should have to know how the child's parameters will be used. For children, properties should simply use [Parameter] everywhere, and a proper cascading design should allow for cascading usage/specification (or not) at the parent (higher) level only.

The [CascadingParameter] attribute uses a string to identify the parameter to cascade! This is a horrible design pattern. We have all the type-safety, compile-time checks, and reflection of .NET at our disposal now, and someone chose to use a string value to represent the identifier of the parameter. Why? a) What if I want to change the string identifier of the parameter (answer: I have to do a fuzzy search through all the code to try to make the change, which puts us right back to the Javascript world, ugh). b) What if I have two different types of child components that for some reason decided to use the same identifiers for their cascading parameters? Such a poor design choice.

Can we please come up with a better design choice for cascading parameters in Blazor?

**Comment by javiercn** [comment]
@velocitytoo thanks for contacting us.

It is unlikely that we will change the design of cascading parameters. That would be a massive breaking change, but let me answer some of your comments to hopefully explain our rationale.

A child component has to know that its parameter will be used in a cascading manner and has to decorate the parameter with [CascadingParameter]. Why not just come up with a design so that a child component does not have to know whether or not it will be used in a cascading manner?

This is done for performance and correctness reasons, cascading parameters are explicitly declared to avoid having to check for the presence of cascading values for each parameter and to avoid any ambiguity between regular parameters and cascading parameters being passed to a component (if the same parameter is a cascading parameter and a direct parameter we need to decide which one wins) as well as having to check if there was a previous cascading parameter being passed-in and adjust the change notifications.

The current design is explicit, straightforward and more performant than the alternatives we considered.

> The [CascadingParameter] attribute uses a string to identify the parameter to cascade! This is a horrible design pattern. We have all the type-safety, compile-time checks, and reflection of .NET at our disposal now, and someone chose to use a string value to represent the identifier of the parameter. Why? a) What if I want to change the string identifier of the parameter (answer: I have to do a fuzzy search through all the code to try to make the change, which puts us right back to the Javascript world, ugh). b) What if I have two different types of child components that for some reason decided to use the same identifiers for their cascading parameters? Such a poor design choice.

You can use a type, in fact that's what we recommend and use on our templates. (For example, you can use `[CascadingParameter] public EditContext Context { get; set; }` on your input components as well as `[CascadingParameter] public Task<AuthenticationState> AuthenticationState { get; set; }` as examples of cascading parameters used within the framework.

There is a string overload that can be used to disambiguate when you have multiple cascading parameters of the same type, but it is a somewhat more advanced scenario. Even in that case, you are not forced to rely on strings. You can define a constant in a class and use that across all the references to that cascading parameter in your codebase and you won't have to deal with strings at all.

I hope this brings a bit more clarity into the design trade-offs and capabilities of CascadingParameter
