### ISSUE TITLE
WsFed viable for hosted Blazor WASM?

### ISSUE THREAD

**Issue by ngboardway** [dotnet/aspnetcore#25499]
Researching auth for a work project- Is Ws-Federation a viable option for authenticating a hosted Blazor WASM application?

**Comment by blowdart** [comment]
Not really no, because WS-Fed tokens are huge and won't fit in any api auth scenario. If you just wanted login, and no authenticated web services then you could use identity server to convert the WS-Fed login to a JWT issued by identity server, but that's outside the scope of our templates and takes you deep into identity server configuration.

**Comment by Eyeb0lt** [comment]
@blowdart does this include systems where there is a supporting backend server? We have used WS-fed for other SPA frameworks making use of a hosted remote backend server.

**Comment by blowdart** [comment]
@Eyeb0lt it would depend what the back end server does. If it's handling logins, and changing them into a spa suitable format, like identity server would do, then yes. But we don't provide that, you'd have to check out identity server and see if it works for you. 

And at that point it's not Blazor doing the authentication, it's Identity Server, so being pedantic the answer to the original question is still no.
