### ISSUE TITLE
Support variable for Blazor @page directive declaration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25589]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1057305/support-variable-for-blazor.html)._

---
hello, for example:

```
@inherits ListBase
@{
    string pagePath = $"/Offer/List/{{{nameof(SelectedID)}}}";
}
@page  @pagePath
```

or by string interpolation directly:
`@page $"/Offer/List/{{{nameof(SelectedID)}}}"`

current Error is: The 'page' directive expects a string surrounded by double quotes.

regards

---
#### Feedback Bot on 6/1/2020, 02:51 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
Thanks for contacting us.

This is not something we can do since the page directive gets compiled down to an attribute and has the same restrictions as C# attributes.

You can use the `@attribute` with the `[Route]` attribute and use string concatenation instead of string interpolation to define a constant for the route, since that's what the C# compiler supports. For example: `@attribute [Route("/" + nameof(Index))]`
