### ISSUE TITLE
WorkerService Dockerfile is wrong

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#25584]
When generating a Dockerfile for a worker service using latest net5-preview8 from Visual Studio Version 16.8.0 Preview 2.0 the runtime image is wrong.

The fix is using `mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim`.

```
- FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim AS base
+ FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
```
Using `mcr.microsoft.com/dotnet/runtime:5.0-buster-slim` will result in the following error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0-preview.8.20414.8' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0-preview.8.20414.8&arch=x64&rid=debian.10-x64

```

**Comment by blowdart** [comment]
@richlander Where should this go?

**Comment by BrennanConroy** [comment]
@MichaelSimons Could you move this issue to dotnet-docker?

**Comment by MichaelSimons** [comment]
This doesn't belong in https://github.com/dotnet/dotnet-docker from the looks of it.  It looks like an issue for https://github.com/microsoft/dockertools instead.  @pratiksanglikar do you agree?

**Comment by pratiksanglikar** [comment]
@MichaelSimons , Yes, I would say it belongs to [https://github.com/microsoft/dockertools](https://github.com/microsoft/dockertools).

@mihaimyh it is expected since it is a preview version of .NET5, please use nightly version of .NET5 to get around this issue.
Please change images to `mcr.microsoft.com/dotnet/nightly/aspnet:5.0` and `mcr.microsoft.com/dotnet/nightly/sdk:5.0` in the dockerfile.

The images are correctly scaffolded for projects using released bits of .NET.

**Comment by Pilchie** [comment]
This issue was moved to microsoft/DockerTools#271
