### ISSUE TITLE
Document how to configure HttpClient base address in Blazor Server using IHttpClientFactory

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#25758]
I am trying to configure `HttpClient`'s base address in a Blazor Server using `IHttpClientFactory` but I am getting a runtime exception:

    services.AddHttpClient("ApiClient", (provider, client) =>
    {
        var uriHelper = provider.GetRequiredService<NavigationManager>();
        client.BaseAddress = new Uri(uriHelper.BaseUri);
    });

Create an instance of this HttpClient using IHttpClientFactory and the following exception will be thrown:

`_httpClient = httpClientFactory.CreateClient("ApiClient");`

`System.InvalidOperationException: 'Cannot resolve scoped service 'Microsoft.AspNetCore.Components.NavigationManager' from root provider.'`

![image](https://user-images.githubusercontent.com/549272/92745245-dd2d6e80-f38a-11ea-8f6e-e0cb6d787506.png)

```
NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Anyone knows what might be the issue here?

**Comment by mihaimyh** [comment]
Tested it with both 3.1 and 5.0-preview8, same result.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will investigate how this can be resolved in the future.

**Comment by aredfox** [comment]
Is there a workaround, or other solution meanwhile that can be promoted whilst it is in process of enhancement @SteveSandersonMS / @mkArtakMSFT? Thanks!

**Comment by mihaimyh** [comment]
Can you try it like this?

```
            services.AddHttpClient("ApiClient", (provider, client) =>
            {
                var uriHelper = provider.GetRequiredService<NavigationManager>();
                client.BaseAddress = new Uri(uriHelper.BaseUri);
            });

```

**Comment by arivera12** [comment]
I would just simply use the default http client factory `services.AddHttpClient();`

I did this kind of overriding the base http client address and it was a bad idea once when I started with blazor wasm and server.

I falled back to just include the `HttpClient `using it's default base root address where the web server is running. 

What happens if you want to get a resource which is on the `wwwroot` of your blazor server/wasm application?

You will lose this main address in your http client...

If you are on native application then this would make sense at all to do it.

I would suggest to change approach and make a HttpClientService per specific API controllers instead and inside set up you base http client address.

I know this doesn't answer the asked question but it's my experience based on this when I did this approach before this should not be done at all.

I even think it should be considered a bad practice at all.

**Comment by agilenut** [comment]
I would also like to see this addressed. I need to be able to add a user's access token to a named HTTP client. But I'm getting the same exception when I try to resolve the AuthenticationStateProvider to figure who the user is. This should be a supported scenario.

**Comment by SteveSandersonMS** [comment]
When fixing this, verify that it also fixes https://github.com/dotnet/aspnetcore/issues/25758
