### ISSUE TITLE
Support :root on css isolation at least on MainLayout

### ISSUE THREAD

**Issue by barahonajm** [dotnet/aspnetcore#25796]
### Desciption
As stated in the MDN docs `:root` is used to hold global css variables but since it is scoped it gets converted to something like this `:root[scopeid]` which make the selector invalid, declaring global css variables into a `MainLayout` could open the possibility to have a couple of `layouts` that define different values for the variables so we can have different themes (dark, white, and others)

### Describe the solution you'd like
I believe ignoring `:root` in the css isolation process would do the work

**Comment by javiercn** [comment]
@barahonajm thanks for contacting us. 

Does `:root ::deep` not do the trick?

In general this is not something I'm supportive off, since it can introduce non-scoped rules within the scoped css and that'll cause things like bundling to become unreliable.

All rules in scoped css files should be scoped and not leak over, for things like that it's simple enough to define a regular css file and use the "link" tag on the component (for example)

**Comment by barahonajm** [comment]
`:root ::deep` it does not, but I understand the point, I am using a regular link as you said and its working fine so I believe if this makes more problems than it solves, it's fine to not support it, Thank you!
