### ISSUE TITLE
Combobox performance

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#25904]
Comparing the Angular to Blazor Combox Box Telerik controls you see a notable difference when opening it.  Looking at the below gifs it does not seem much of difference (still you clearly can observe it) but when doing it live it feels very clumsy. Is this just network latency and something customers have to live with when using Blazor Server?  ( i.e. when using Blazor WASM one can expect same performance as with the Angular controls?)

Blazor:

![blazor_combox_telerik](https://user-images.githubusercontent.com/8482283/93215622-f0638400-f766-11ea-8df3-d01b220ca66f.gif)

Angular:

![angular_combox_telerik](https://user-images.githubusercontent.com/8482283/93215634-f5c0ce80-f766-11ea-95c7-6056b3199274.gif)

**Comment by Postlagerkarte** [comment]
Here is another example , where you can clearly see that there is a notable lag. Notice how cursor and red square are unified when using the Angular control and are out of sync with the Blazor control:

Blazor:

![blazor_calendar_select_telerik](https://user-images.githubusercontent.com/8482283/93224303-3f161b80-f771-11ea-9190-99559e2f441c.gif)

Angular:

![angular_calendar_select_telerik](https://user-images.githubusercontent.com/8482283/93224330-450bfc80-f771-11ea-8a0e-1e728ba43799.gif)

**Comment by danroth27** [comment]
Hi @Postlagerkarte. Blazor Server is subject to network latency. All of the UI interactions are sent to the server over a WebSocket connection, where they are handled by your components on the server. The UI updates are then sent back to the browser and applied to the DOM. The impact of network latency on a Blazor Server app can be compounded when dealing with high frequency events. You can minimize the impact of the network latency by locating servers as close as possible to the client. See https://docs.microsoft.com/aspnet/core/blazor/hosting-models#ui-latency for additional details.

Blazor WebAssembly doesn't have the same network latency problems as Blazor Server because the UI code executes client-side in the browser using a WebAssembly based .NET runtime.
