### ISSUE TITLE
[Blazor] PWA not working off-line

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#25902]
### Describe the bug
.NET 5 PWA installed on desktop (PC or phone) will not work without a network connection.

### To Reproduce
https://theperiodictablegame.z19.web.core.windows.net/

1: Create a new Blazor WebAssembly PWA app
2: Deploy it
3: Visit it in Chrome
4: Click the (+) to install it
5: Disconnect from your network
6: Double-click the icon on your desktop

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
@mrpmorris This doesn't repro for me with the default project template. It appears to work fine out of the box.

I think there is some problem with how you've deployed your app:

 1. You don't have any compression enabled. I know this won't break it on its own, but means the site is a rather terrifying 14 MB to download.
 2. There's an integrity check failure in your `app.css` file:

![image](https://user-images.githubusercontent.com/1101362/93338031-cd49da80-f821-11ea-89c7-150b466fa1c4.png)

The integrity check failure suggests that you or something on your server has modified the file in between when it was published and when it got delivered to the browser. This might be because you actually deliberately edited it manually, or it might be something more subtle like Git's EOL conversions, depending on how you deployed it.

The result of the integrity check failure is that the service worker isn't installed at all, so there isn't any (+) button to click:

![image](https://user-images.githubusercontent.com/1101362/93338196-008c6980-f822-11ea-9d87-718933feaf6a.png)

So I don't quite understand how the (+) button appeared for you when you wrote your repro steps. Maybe this `app.css` problem occurred later and there is some other underlying issue, but this is all I can tell for now.

If you think there is some underlying framework problem, could you please correct your repro steps and let us know? Thanks!

**Comment by mrpmorris** [comment]
Hi @SteveSandersonMS 

I'm sorry about that. I didn't realise I am not able to update the css file on its own. I have now rectified that.

I don't know why it isn't compressing properly, I am right-clicking on the Wasm project and doing a Release mode publish to folder and then uploading via Azure Storage Explorer.

As for the steps, I just retried and the behaviour I see is not the same as last night.

1: Visit site
2: Install PWA
3: Close PWA
4: Switch on Airplane mode
5: Right-click the page and select Reload

From that point onwards the app gets stuck on the index.html page

**Comment by SteveSandersonMS** [comment]
@mrpmorris Since you fixed your `app.css` issue, it works for me now, including offline.

If it's still not working for you then try clearing your browser's storage for your site using the "Clear site data" button:

![image](https://user-images.githubusercontent.com/1101362/93352268-93350480-f832-11ea-931c-f765e69b6a93.png)

**Comment by SteveSandersonMS** [comment]
Compression is still off though, so the site is massive. I'm not sure if some additional steps are needed to enable it with your particular deployment mechanism.

**Comment by mrpmorris** [comment]
Strange things are happining. Your suggestion didn't work at least 3 times, but on the 4th time it did. Now I can load and also refresh the page even when offline. Very odd, but I think it must be down to Chrome weirdness rather than Blazor.

I'm going to close this. I already have a ticket regarding the size here: https://github.com/dotnet/aspnetcore/issues/25926

Thanks!
