### ISSUE TITLE
Blazor Virtualize 22-25 items 

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#25915]
extended Weatherservice to 500 records, added a ID property named Counter (incremented)
Changed fetchdata.razor

```
 <Virtualize Items="forecasts" Context="forecast">
                <ItemContent>
                    <tr @key="forecast.Counter">
                        <td>@forecast.Counter</td>
                        <td>@forecast.Date.ToShortDateString()</td>
                        <td>@forecast.TemperatureC</td>
                        <td>@forecast.TemperatureF</td>
                        <td>@forecast.Summary</td>
                    </tr>
                </ItemContent>
                <Placeholder>
                    <tr>
                        <td>Loading...</td>
                    </tr>
                </Placeholder>
            </Virtualize>
```

shows only 22-25 rows in Browser 

- ASP.NET Core version 5 5.0.100-rc.1.20452.10

- Version 16.8.0 Preview 3.0

**Comment by GarettCooper** [comment]
I'm experiencing a similar issue. My chat log consistenly shows the last 24 messages, removing older messages when new ones are added to the virtualized items. I can make the number of messages change when I resize the div, but that sometimes results in elements overlapping each other and not appearing in the correct positions. I haven't tried implementing my own ItemsProvider to resolve the issue.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/22463490/93255553-150c2b80-f768-11ea-8b0b-4bc814a77de9.png)


![image](https://user-images.githubusercontent.com/22463490/93255772-5ac8f400-f768-11ea-9fd1-18239fa655e4.png)

</details>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by hannespreishuber** [comment]
no rocket science.- but https://github.com/hannespreishuber/Blazor5App

**Comment by SteveSandersonMS** [comment]
@GarettCooper I think your issue is different and may be due to some unwanted interactions between CSS and `<Virtualize>`. If you could file a new issue with minimal repro steps we can take a look.

**Comment by SteveSandersonMS** [comment]
@hannespreishuber Thanks for the repro information. I was able to observe this issue and have tracked down the underlying cause.

The issue happens when `<Virtualize>` recomputes its estimate for the item height, and it happens to be so similar to the default value that it thinks no re-rendering is needed. Then it doesn't refresh while the user is scrolling because it's no longer listening for events.

### Workaround

If you want to work around this in your own code, it's reasonably easy. You just need to pass an accurate `ItemHeight` parameter to the `<Virtualize>` component so it will use your value instead of its default initial value of 50px. When I ran your code, I used the browser dev tools to see that the actual item height is 48.89 pixels:

![image](https://user-images.githubusercontent.com/1101362/94129870-d3f4d500-fe53-11ea-9eb2-9fdb85ca5a08.png)

So then I supplied this information to `<Virtualize>`:

```razor
<Virtualize Items="forecasts" Context="forecast" ItemSize="48.89f">
    <tr @key="forecast.Counter">
        ... etc ...
    </tr>
</Virtualize>
```

... and now it behaves correctly and doesn't get stuck.

If you don't like relying on arbitrary-seeming values like 48.89, then it's probably best to use CSS to force the items to be a specific known height. For example in your `.css` file you could set `.my-table td { height: 50px; }` or similar, and then you know to pass `ItemSize="50"`.

### Fixing it in the framework

I have prepared a fix for `<Virtualize>` that lets it detect when a refresh is needed purely due to changes in the item size estimate. However I don't know yet whether we will include this fix in the 5.0 release because the bar for including changes now is quite high and this issue has an easy workaround. I'll post an update here later when we have a decision about that.

**Comment by hannespreishuber** [comment]
> If you don't like relying on arbitrary-seeming values like 48.89, then it's probably best to use CSS to force the items to be a specific known height. For example in your .css file you could set .my-table td { height: 50px; } or similar, and then you know to pass ItemSize="50".

Thanks - I can live with that workaround, as I want to support blazor to reach the best tool, missing size is unexpected behavior. Needs a remark in docu and/or a warning in Visual Studio of missing size attribute on compile.

**Comment by GarettCooper** [comment]
@SteveSandersonMS Thanks for letting me know, the height issue did occur to me but I couldn't find any documentation confirming or denying that Virtualize only supported items with consistent heights. When I saw Virtualize in the blog post I was hoping for a silver bullet, but I guess I'll have to look in to writing my own solution.
