### ISSUE TITLE
Blazor WASM 3.2 EOL work

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25923]
* [x] Remove code \ or mark as nonshipping the wasm code from 3.1 branch
* [x] Remove the template from the 3.1 installer
* [x] Remove the 3.1 template from the 5.0 installer

**Comment by danroth27** [comment]
@pranavkm @HaoK @mkArtakMSFT  Let's chat about this a bit more. It's not clear to me that we should be removing the older Blazor WebAssembly templates from these SDKs.

**Comment by HaoK** [comment]
From initial discussions it sounds like we are all agreed that we want to remove the 3.1 templates from 5.0 and master installers.  But we need to come to a consensus on the first 2 bullet points (what to do about the code in the 3.1 branches).  I'm assuming older shipped builds are always available, so is it sufficient for people who want to use the existing 3.1 templates to use 3.1 sdk installers that contain the templates, but we will remove it from future 3.1 releases.

**Comment by danroth27** [comment]
> it sounds like we are all agreed that we want to remove the 3.1 templates from 5.0 and master installers.

Actually, I'm not sure we should do that either. Let's chat about it.

**Comment by Pilchie** [comment]
I suggest following up with the SDK team for how they approach these things.

**Comment by HaoK** [comment]
We followed up with Dan offline and I think he was mulling it over some more, but he was leaning towards being okay with the current plan, @danroth27 how are you feeling today? :)  Either way, we need to stop producing updated 3.2 template bits in our 3.1 builds since we don't want to ship new versions of it, so I was just doing that work that is required regardless of whether we decide to stop shipping the templates or not going forward.

**Comment by danroth27** [comment]
We met with @KathleenDollard to discuss options yesterday. The goal here is to help prevent users from unintentionally using Blazor WebAssembly 3.2 once it goes out of support. There isn't a way to really remove the Blazor WebAssembly 3.2 template once it has been installed, but we can remove it from new installations. She also pointed us to @vijayrkn to discuss how to remove the template from VS. We also discussed options to somehow generate a warning in Blazor WebAssembly 3.2 projects to let users know that they are using an unsupported version and need to update. Maybe obsoleting the old packages is a sufficient way to do this?

**Comment by Pilchie** [comment]
I believe VS has various bits of yellow-bar warnings that could here, either:

1. In the new project dialog if an unsupported version is picked (probably should do this ASAP) to discourage new projects.
2. On project open (probably want to wait a bit for this one to give people a chance to migrate).

**Comment by danroth27** [comment]
Here's the current state of the user experience when deprecating a package: https://docs.microsoft.com/nuget/nuget-org/deprecate-packages. It doesn't look like you get any sort of warning on restore/build.

**Comment by HaoK** [comment]
Add a link to @pranavkm information on the deprecation progress, @SteveSandersonMS wanted to make sure @danroth27 is aware that the custom message for deprecation is only visible if the user clicks on the glyph to expand details

https://github.com/aspnet/specs/issues/518

**Comment by SteveSandersonMS** [comment]
@danroth27 The reason I'm raising this point is that NuGet.org is going to say, on the 3.2.x package pages, *This package is deprecated because it is legacy*. People might misinterpret that as meaning "`Microsoft.AspNetCore.Components.WebAssembly` is legacy and deprecated".

Since it will only say that on the pages for the 3.2.x versions of the packages (not the 5+ versions) it's probably not such a big deal.

**Comment by HaoK** [comment]
@vijayrkn is there any work we need to do to ensure that the 3.2 templates are no longer available options on the VS side in the march time frame to align with the plan to remove them from the 3.1 sdk installer?

**Comment by mkArtakMSFT** [comment]
@HaoK I believe this can close now, correct?
