### ISSUE TITLE
porting tool to move webforms to cshtml

### ISSUE THREAD

**Issue by bfreezer99** [dotnet/aspnetcore#26018]
One user has created a porting tool to help to decommissioning Webforms.

https://github.com/dotnet/aspnetcore/issues/1961#issuecomment-452650308_

Microsoft should be releasing similar tooling.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
/cc @danroth27

**Comment by danroth27** [comment]
Thanks for the suggestion!

Because the gap between ASP.NET Web Forms and ASP.NET Core is pretty large we don't think there is a good way to provide generic tooling for this sort of conversion. There just too many variables to consider for the tool to be generally useful without devoting a lot of resources to developing it, which then wouldn't be available to further improvements in the platform.

Since we don't have plans to pursue this, I'm going to go ahead and close this issue.
