### ISSUE TITLE
[Blazor] Brotli compression code is ignored in PWA apps

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#26096]
### Describe the bug
Standard static hosted apps use *.br files when the following compression advice is used
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#compression (except you cannot use the decode.min.js file, you must use decode.js)

However, when the project is a PWA the DLLs are downloaded

### To Reproduce
Create a new WASM PWA app (not ASP.NET Hosted)

Download decode.js and add it to your app
https://github.com/google/brotli/tree/master/js

Alter index.html as directed in the documentation above
```
<script src="decode.min.js"></script>
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      if (type !== 'dotnetjs' && location.hostname !== 'localhost') {
        return (async function () {
          const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });
          if (!response.ok) {
            throw new Error(response.statusText);
          }
          const originalResponseBuffer = await response.arrayBuffer();
          const originalResponseArray = new Int8Array(originalResponseBuffer);
          const decompressedResponseArray = BrotliDecode(originalResponseArray);
          const contentType = type === 
            'dotnetwasm' ? 'application/wasm' : 'application/octet-stream';
          return new Response(decompressedResponseArray, 
            { headers: { 'content-type': contentType } });
        })();
      }
    }
  });
</script>
```

Now publish the app and visit the page. The app downloads `.dll` files instead of `.dll.br` files.

### Further technical details
- ASP.NET 5 RC1

**Comment by SteveSandersonMS** [comment]
This is as expected. When you implement a service worker or use the project template to get the default `service-worker.published.js`, you get to control exactly the logic that fetches the static resources. The service worker cannot use your `loadBootResource` logic directly because it runs in a completely different context to your `index.html` page and cannot see that logic. So, if you goal is to have similar custom logic for fetching `.br` files in your service worker, then it's up to you to put that logic in your server worker.

**Comment by SteveSandersonMS** [comment]
Also to clarify: normally the best system for serving the `.br` (etc) files is via server-side, not client-side logic. This is what happens by default with the "Hosted on ASP.NET Core" templates, and with Azure Static Web Apps. In these cases, there's no need to write any `loadBootResource` logic or to change your service worker, because by requesting `SomeFile.dll`, the server will automatically return the precompressed `SomeFile.dll.br` file when present on disk.

So the extra complication of having to customize your service worker only applies if you are trying to make the compression work based on client-side logic. Unfortunately service worker logic does run in a difference context from the host HTML page, so you should expect the implementation to be independent.
