### ISSUE TITLE
Adding to SignalR groups using Context.UserIdentifier rather than Context.ConnectionId

### ISSUE THREAD

**Issue by Roy19** [dotnet/aspnetcore#26133]
### Description

I was wondering why can't we add to SignalR groups using ```Context.UserIdentifier``` rather than using ```Context.ConnectionId```? Is it mostly an architectural issue? If so what might be the recommended approach for getting this behaviour?
Current behaviour: ```await Groups.AddToGroupsAsync(Context.ConnectionId, groupName)```.
Required behaviour: ```await Groups.AddToGroupsAsync(Context.UserIdentifier, groupName)```.

### Configuration

.NET Core version: 3.1.
SignalR server version: 3.1.0.
IDE: Visual Studio 2019

**Comment by BrennanConroy** [comment]
> If so what might be the recommended approach for getting this behaviour?

You would need to store a mapping of user id to groups and every time someone connects you would check their user id against that mapping and add them to the groups the user is in.

This is a major feature that we are unlikely to add.

**Comment by Roy19** [comment]
> This is a major feature that we are unlikely to add.

Could you please explain as to why this feature is unlikely to be added. What I want is to understand the reason behind doing so. Is it some architectural design decision or something else?

**Comment by davidfowl** [comment]
Adding a connection to a group has a well defined lifetime as connection come and go. Users on the other hand are made up of multiple connections and need to be explicitly managed. 

For example if you add a user to a group, you're implicitly adding all current and future connections to that group. This will persist until an explicit call to remove that user from the group. When would you remove a user from the group? How would we express that in a way that avoid leaks? Does it need to timeout? Where do we store that mapping information so that every new connection on any replica/instance of the server knows what users are in what group?

Those are some of the challenges.

With when adding connections to groups, we can store that locally on the the connection itself (since it only exists in a single place).
