### ISSUE TITLE
Add unmarshalled invocation of .Net methods from JS

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#26287]
Blazor JSInterop has a special JSRuntime that lets me call JS functions from .Net without any marshalling for max performance in a webassembly scenario: [WebAssemblyJSRuntime Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.webassembly.webassemblyjsruntime?view=aspnetcore-3.1)

There doesn't appear to be an equivalent functionality when making a call from JS into .Net without marshalling? This would be good when wrapping JS libs in Blazor.

**Comment by SteveSandersonMS** [comment]
If you're just passing a few primitive-values parameters (e.g., a few strings or ints) then there's little to no overhead from the JSON marshalling, so you can use the normal marshalled interop.

If you need to pass larger data structures, then you would have to use marshalled interop because WebAssembly in general (and .NET specifically in this case) has no way to read directly from the JavaScript memory space. It's not meaningful to talk about pointers to JavaScript memory, so there couldn't be any equivalent to unmarshalled data transfer in this direction.

If you have a more specific requirement (for example passing a `byte[]` from JS to .NET) then please let us know about your scenario and we might be able to make suggestions that work in your particular case.

Hope that sounds reasonable!

**Comment by user72356** [comment]
Thank you, my requirements aren't very specific at the moment, as I'm still learning to use the JS interop when dealing with external JS libs. As much as I hate JS, there are some excellent libs which can't be ported to Blazor 100% due to webassembly not having access to the DOM (would be a killer feature!!).

A common scenario is calling a .Net method within a JS callback raised by a JS lib. In this callback I have to call a .Net method and pass it a JS event object, which can be quite complex depending on the lib. Including references and circular references. At present I have to create a purpose-made intermediary object in JS and .Net, and include each field one by one. This can be tedious.

Ideally I would just forward the JS event object straight to the .Net and automatically map the fields to a .Net object. This would make wrapping a JS lib so much easier.

Sometimes the events are generated a few times per second, for example of mouse move, so I was thinking of ways to keep the calls as fast as native.

**Comment by SteveSandersonMS** [comment]
> Sometimes the events are generated a few times per second, for example mouse move/touch events, so I was thinking of ways to keep the calls as fast as native JS.

It's not really meaningful to think about the JS data getting into .NET without some kind of marshalling or conversion. For example, JavaScript strings are not .NET strings, so even something as simple as passing a single string involves conversion. Of course we do want to make it as fast as possible though :)

> Ideally I would just forward the JS event object straight to the .Net and automatically map the fields to a .Net object. This would make wrapping a JS lib so much easier.

In a sense that's literally what the JSON-based marshalling already does (automatically maps fields). If you have more details about what you're looking for that's different, please let us know!
