### ISSUE TITLE
Make CreateStaticFilesOptions API public

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#26544]
### Is your feature request related to a problem? Please describe.

I serve up blazor spa apps and have some logic at runtime to decide which app to serve up from where, and part of that is serving up the "blazor _framework "files.

In order to serve those _framework files, the options for the static files middleware need to be configured appropriately.
At the moment, you can see that logic in this private method here:

https://github.com/dotnet/aspnetcore/blob/89c3d6bf23974b35ac896df92e9c588288599107/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L69

Currently there is no way to get at this directly (without reflection) because its a private method, and the only way to leverage it is to also use the framework provided middleware: `UseBlazorFrameworkFiles` https://github.com/dotnet/aspnetcore/blob/89c3d6bf23974b35ac896df92e9c588288599107/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L31

I don't want to use `UseBlazorFrameworkFiles` because I have some additional logic around how requests should be mapped, as well as additional headers I'd like to include (i.e not just Environment) which I can express with my own middleware. The problem comes with the fact that I still need to ultimately serve the static files, and that means creating sensbile StaticFileOptions for _framework content. As this method is private, I have had to keep a copy of this logic in my application in order to create the options in the same way. For example ".blat" and ".dat" files are now new to the _framework, so I have had to update my copy of the method appropriately: https://github.com/dotnet/aspnetcore/pull/25954

Please would you consider making this method public? It would be very useful in situations such as mine, where I'd like to be in control over the middleware aspect, whilst still being able to create appropriate options to serve _framework content using static files middleware without having to duplicate this logic into my application, or use reflection.

### Describe the solution you'd like
As above

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

Before we expose a new API, I would like to understand what are you trying to achieve so that requires such level of customization. We normally don't expose new APIs unless we have a good reason/scenario for it, since it limits our ability to change things in the future.

**Comment by dazinator** [comment]
I'd like to create a generic server, where a blazor spa app can be uploaded by a user and then configured to be served on a particular url.

In other words, someone can zip up there blazor spa app static files / published output, then upload it to my website, which will place the content in a particular folder on disk for that user, as well as set up a file provider to serve that content up. Its that last part that is not easily accessible today without copying logic..

**Comment by LaughingJohn** [comment]
Sorry to jump on to this, but rather than start another issue I thought I'd add my use case.
I have a custom AuthenticationHandler and I don't want any static files, especially Blazor client DLLs to be downloaded unless the user has been fully authenticated. 

I can achieve this with static files by doing a check for IsAuthenticated in the OnPrepareResponse of StaticFileOptions 

```
            app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = ctx =>
                {
                    if (!ctx.Context.User.Identity.IsAuthenticated)
                    {
                        // respond HTTP 401 Unauthorized.
                        ctx.Context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                        ctx.Context.Response.ContentLength = 0;
                        ctx.Context.Response.Body = Stream.Null;
                    }
                }
            });
```

This works for static files, however I can still download DLLs from the _framework folder. There doesn't seem to be any clear way of doing this with the Blazor static files as UseBlazorFrameworkFiles doesn't take StaticFileOptions parameter and as @dazinator points out we can't get at it because it is private. I think our only option is also to copy the code!?

It seems to me like a security no-brainer that the we would protect our code from unauthorized access even if (we hope) the code should not help an attacker.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
