### ISSUE TITLE
bundler & minifier View Page

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/aspnetcore#26584]
Hello!
How to force bundler & minifier (HTML, CSS, JavaScript) into view body?

**Comment by javiercn** [comment]
@EvgenyPrikhodko thanks for contacting us.

This is not a feature we have.

The HTML produced in Razor views is sent "verbatim" since minifying it can introduce styling bugs due to significant whitespace. For CSS and JS, the razor compiler would have to understand how to parse and interpret those languages (which currently doesn't and we don't plan to) so they don't get minified either.

If you want to minify CSS and JS I would recommend you put them on a separate file and use a bundler/minifier tool on them. You could then inline the contents within a razor view.

**Comment by EvgenyPrikhodko** [comment]
> @EvgenyPrikhodko thanks for contacting us.
> 
> This is not a feature we have.
> 
> The HTML produced in Razor views is sent "verbatim" since minifying it can introduce styling bugs due to significant whitespace. For CSS and JS, the razor compiler would have to understand how to parse and interpret those languages (which currently doesn't and we don't plan to) so they don't get minified either.
> 
> If you want to minify CSS and JS I would recommend you put them on a separate file and use a bundler/minifier tool on them. You could then inline the contents within a razor view.
Can come up with some kind of partial file minifier?
We don't want to create separate static files
