### ISSUE TITLE
Virtual machine (or some other means) of making it easy for the community to build from source

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#26661]
I've attempted to build from various versions of source and have failed. Despite wanting to contribute something on numerous occasions I have therefore never been able.

I'd like an easy way to download something (VM or other) that I can then just open up a copy of VS and build + run tests + run the sample apps against the source.

The current method seems to be time consuming and (for me at least) difficult to get started with.

**Comment by richbryant** [comment]
oh god so much this

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

The main issue here is that running some tests requires full windows. I created a dockerfile a while ago, but it's GBs worth of memory.

**Comment by SQL-MisterMagoo** [comment]
I wonder if there could at least be some way to use Tags to indicate "this commit right here is likely to build because all the tests ran ok"

I'm bringing this up because if you look at the testing history, a lot of commits that hit master don't have clean 100% testing and it feels like if you just randomly pull master down and try to use it you might have one of those experiences where nothing seems to work.

I have sometimes deliberately chosen a Tagged release as the codebase - maybe incorrectly - assuming that is most likely to build and run successful tests

**Comment by mrpmorris** [comment]
@javiercn I'd download gigs

**Comment by MariovanZeist** [comment]
The problem is that the solution needs a lot of prerequisites to build. Those prerequisites will in my opinion make it so that it is nearly impossible to simply download the repo, and immediately start developing. 
A lot of Blazor tests for example use Selenium to automate browser tests. Some tooling needs the Java JDK, and others again need NodeJS to be installed.
Additionally, the code itself might be based on prerelease builds of part of the dotnet ecosystem and must be installed to run tests properly.

In my experience, it was that whenever the solution didn't build, (I had one time in where browser based tests wouldn't run because of some Selenium issue, that magically got resolved after a few reboots ) some prerequisites weren't met. 
The problem was finding out which. 

It might be worth figuring out if we can reinforce the build.cmd to make sure all prerequisites are met, and if not either automatically correct it (By setting the proper variables, or install it), or let the developer know what to do. I know it already does this to some extent, but it might be worth investigating if more issues could be identified.

**Comment by stefanloerwald** [comment]
Would it be possible to isolate the not normally installed dependencies into containers? Seems like most dependencies that cause installation trouble are used for tests and tests benefit from a consistent environment anyway, which containers would offer.

**Comment by dougbu** [comment]
For Linux, we already have a couple of Docker files that should grab the dependencies in the [`eng/docker/`](https://github.com/dotnet/aspnetcore/tree/master/eng/docker) folder and a [`./dockerbuild.sh`](https://github.com/dotnet/aspnetcore/blob/master/dockerbuild.sh) script to build using them. Suggest extending the available Docker files and mentioning the script in our docs/BuildFromSource.md. Because Selenium is Windows-only AFAIK, this won't support building and testing everything.

For Windows, might be able to do some similar container scripting (though I don't know the details there) or create a container that can be made available to all contributors.

Not sure what works on macOS.

**Comment by SQL-MisterMagoo** [comment]
As this is still open, I guess I can add to the discussion.

I was working on a script to install all the pre-requisites and build the repo in Windows Sandbox, and everything was going swimmingly until I hit a hurdle with installing Visual Studio, specifically the Windows 10 SDK - which just hangs. I realise this is likely a Windows 11 Sandbox issue rather than a repo issue, but the question it raised is - why do I need Visual Studio / the Windows 10 SDK when a Linux/MAC user can build without it?

Are there specific parts of the SDK that are required and not others?
 - I would love to be able to grab individual installers for just the required packages, then maybe I could complete this task - as this is the last hurdle.

**Comment by wtgodbe** [comment]
As we haven't heard anything on this for a while, I'm going to close this. Our dev experience has improved over time - https://learn.microsoft.com/en-us/dotnet/core/docker/container-images may be of interest.
