### ISSUE TITLE
Possible mishandling of TargetFramework vs TargetFrameworkMoniker

### ISSUE THREAD

**Issue by sfoslund** [dotnet/aspnetcore#26709]
In GenerateSharedFrameworkDepsFile on line https://github.com/dotnet/aspnetcore/blob/master/src/Framework/App.Runtime/src/Microsoft.AspNetCore.App.Runtime.csproj#L246, the `TargetFrameworkMoniker` is used instead of the `TargetFramework`. This value is used to initialize a TargetInfo object, but[ in the SDK](https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L379) we populate this object with the value of the `TargetFramework` (not the `TargetFrameworkMoniker` as we see here). 

@dsplaisted should this universally be the `TargetFramework` or was the SDK a special case?

**Comment by javiercn** [comment]
@sfoslund thanks for the report.

@dotnet/aspnet-build any ideas?

/cc: @Pilchie

**Comment by dougbu** [comment]
The result of this custom task is a runtimes/{platform}/lib/net5.0/Microsoft.AspNetCore.App.deps.json file containing
``` json
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v5.0/win-x64",
    "signature": ""
  }
```
That looks exactly like the `*.deps.json` files I see the SDK generate.

But, I don't see Microsoft.NETCore.App.deps.json (or Microsoft.NETCore.App.runtimeconfig.json) in Microsoft.NETCore.App.Runtime packages. Do we need `Microsoft.AspNetCore.App.*` files at all❔

**Comment by sfoslund** [comment]
It's very possible that this is the right behavior and the SDK needed to be a special case to account for platform information. @dsplaisted do you know if this is correct?

**Comment by dsplaisted** [comment]
We actually normally [populate this value](https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L90) with the TargetFrameworkMoniker.  We only populate it with TargetFramework in the special case where we don't have an assets file because we're building a C++/CLI project.  See here: https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L129-L136

So the ASP.NET handling looks to be correct here.

**Comment by dougbu** [comment]
Closing per @dsplaisted's [comment](https://github.com/dotnet/aspnetcore/issues/26709#issuecomment-706305068)
