### ISSUE TITLE
Blazor Default RenderFragment

### ISSUE THREAD

**Issue by ahazelwood** [dotnet/aspnetcore#26746]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
It would be useful to mark a RenderFragment as the default for a Razor Component that may contain multiple RenderFragments.

### Describe the solution you'd like
For Razor components that emulate layout features, it would be useful to allow any contained content to flow into a default RenderFragment unless a specific name is matched.

For example, imagine a layout like:

```
<Control>
 <Header>
   <b>My Header content</b>
 </Header>
 <div class="content">
   My content
 </div>
</Control>
```

The class definition could look something like:

```
[Parameter]
RenderFragment Header { get; set; }

[Parameter(CaptureUnmatched = true)]
RenderFragment Content { get; set; }
```

### Additional context
Think of something like a dialog window where you might define a header, a footer, and then anything else could go into the content.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. This is basically what the `<ChildContent>` parameter already is. If you're only passing that one parameter to a component, there's no need to wrap it in `<ChildContent>` because it's treated as the default:

```razor
<Control>
 <div class="content">
   My content
 </div>
</Control>
```

... but if you are passing multiple parameters, you do need to wrap it:

```razor
<Control>
 <Header>
   <b>My Header content</b>
 </Header>
 <ChildContent>
   <div class="content">
     My content
   </div>
  </ChildContent>
</Control>
```

We don't want to allow passing multiple parameters *and* omit the `<ChildContent>` wrapper because it would be too ambiguous. Consider this example:

```razor
<Control>
 <h1>Here is some HTML</h1>
 Very good!
 <Header>
   <b>My Header content</b>
 </Header>
 <div class="content">
   My content
 </div>
</Control>
```

In this case there's no way to know whether `<Header>` is part of the markup being passed in the middle of `<ChildContent>`, or whether `<Header>` is a separate parameter from `<ChildContent>`.
