### ISSUE TITLE
Allow Blazor wasm in vscode webview from extension

### ISSUE THREAD

**Issue by scabana** [dotnet/aspnetcore#26790]
### Feature request

I am trying to get Blazor wasm to load from a vscode extension in a webview. I'm getting the following error: 

![image](https://user-images.githubusercontent.com/8278735/95678037-b768d480-0b97-11eb-9a4e-c9ab17f9ebbd.png)

Blazor currently validates that the current url matches the base url in the page (https://github.com/dotnet/aspnetcore/blob/724c2e75a7415e67f9f5ad33fc72bf55507b8d59/src/Components/Components/src/NavigationManager.cs#L262-L266) but the vscode webview has a scheme (vscode-webview) for the initial page and a scheme(vscode-webview-resource) for additional files provided by an extension.

### Solution I'd like
Would be nice to be able to use Blazor wasm from a vscode extension. Have some kind of a way to disable the validation. Other solutions: 
- Add logic for those schemes in the validation (which is not generic, thus not good)
- Allow Blazor without a NavigationManager (haven't got there, but I don't think navigation should happen in a vscode webview hosted app)

I tried (but didn't work): 
- Navigating to a file in vscode-webview-resource scheme
- Loading a serviceworker (to try to rewrite the outgoing requests to the right scheme)

I tried and worked (hacky): 
Replaced ```getLocationHref:function(){return location.href}``` with ```getLocationHref:function(){return document.baseURI}``` in the blazor.webassembly.js file. The application loaded just fine.

**Comment by danroth27** [comment]
We're getting more internal asks for this, so we should consider if we need to do something here for .NET 8. We should also investigate whether the extensions should use Blazor WebAssembly or Blazor Hybrid.

**Comment by rrelyea** [comment]
Once launched in a vscode webview, navigation isn't functional (all links appear to navigate to a new browser window). I'd imagine that problem would need to be fixed as part of this work.

**Comment by MackinnonBuck** [comment]
I'm guessing that this error is happening because the HTML being loaded in the WebView sets a base href with an origin that's different from the document's location. This is probably done so that static assets can be loaded using relative paths, since VSCode uses a [different origin](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content) for loading local content.

Blazor makes the assumption in multiple places (either explicitly or implicitly) that these two origins must be the same. Even if we were to disable the `NavigationManager` check mentioned in this issue's original comment, there are going to be problems when attempting to perform navigations. For example, clicking an `<a>` element with a relative `href` will cause a navigation to an external, invalid URI (since the base href has an external origin).

I would suggest not changing the base href and instead using absolute URIs for static assets. If you get an error saying that `blazor.boot.json` couldn't be loaded, you can customize the boot configuration by following [this example](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0#load-boot-resources).

**Comment by MackinnonBuck** [comment]
Closing this out since this isn't a change we're going to make. See https://github.com/rrelyea/vscode-webview-blazor/pull/1 for an example of how to make Blazor WebAssembly work in a VSCode WebView and support navigation. https://github.com/dotnet/aspnetcore/issues/44510 will track adding more customization options to `WebAssemblyHostBuilder` for scenarios like this, where a valid approach might be disabling navigation altogether.
