### ISSUE TITLE
Host all Blazor WASM required files on one official CDN

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#26800]
We need **ONE** official place for all framework files (*.blat, *.dat, *.js, *.wasm, *.dll and compressed versions). I'm sure I don't have to explain why.

**Comment by mrpmorris** [comment]
Aren't those assemblies modified at compile time (Release) to strip out classes that aren't used by the app?

**Comment by Andrzej-W** [comment]
Stripping is of course good, but I think CDN with full versions is probably better. Blazor WASM is not used for public websites yet, but in version 5.0 we will get a lot of missing pieces, for example we can modify title and other metadata in `head` section, we have official support for prerendering, etc. It is always better to download for example 2-3 MB than 5-6 MB but on the other hand it is better to download 6 MB once than 3 MB hundreds of times - hopefully in the near future Blazor will be as popular as some JS libraries, like Bootstrap 😃

**Comment by SteveSandersonMS** [comment]
Unfortunately CDNs aren't as useful as they used to be :) Modern browsers no longer share cache entries across origins, so just because you downloaded a file onto site A from a CDN does *not* mean it's treated as already cached if site B tries to reference the same file on that same CDN. For more details, see https://www.jefftk.com/p/shared-cache-is-going-away So the suggested advantage of doing this isn't really true any more.

However, the drawback of doing this (not being able to strip any code from the DLLs), *is* very much true, so it would be strictly worse overall to get unstripped files from a CDN than to get stripped ones from your own application domain, no matter how many different sites are referencing the CDN.

With this in mind, for these reasons we don't have any plans to set up or recommend a CDN. However if you do want to set one up for whatever reason, you absolutely can. We provide an extensibility point that lets you control how files are loaded, so if you want to load them from your own choice of CDN you are free to do so: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#custom-boot-resource-loading

**Comment by Andrzej-W** [comment]
Thank you @SteveSandersonMS for the clarification. I haven't heard about security problems with shared cache. I'm old and I still have to learn new things 😩
