### ISSUE TITLE
Blazor - Get Child or Parent Component

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#26826]
### Is your feature request related to a problem? 

It would be helpful to have a built in way to take a component reference and get a child or parent component of a certain type. When passing around component references, a parent component could be passed and then you automatically have access to its children. 

### This would be one way to do it

```
\\ MyComponentRef populated via `@ref`
var MyComponentRef2 = MyComponentRef.GetChildOfType(“MyComponent2”);
```

### Additional context

Getting a child or parent component is a common JavaScript activity, so making it native to Blazor would support the mission.

**Comment by SteveSandersonMS** [comment]
This is deliberately not part of the programming model as it leads developers into writing very problematic code. We've seen this historically with frameworks like Windows Forms and ASP.NET WebForms which expose an explicit control tree - code ends up with lots of assumptions about controls only working when nested in specific patterns and errors otherwise.

More modern frameworks like Blazor (or similarly React or Vue) use a different model whereby you can explicitly capture references to children via `ref`, or you can implement code that has children invoke methods on parents (e.g., via CascadingParameter) to register themselves for further callbacks. Although these approaches take a little more time to think about, they leads to much better encapsulation of components.

If an individual developer is truly determined they want an explicit component hierarchy they can walk through, it is possible. You would need to declare a common component base class that contains logic in its "OnInitialized" method to register itself with its parent, so you can build your own component tree. But I strongly recommend you don't do that and instead use `@ref` and `CascadingParameter` to communicate in a more decoupled manner.
