### ISSUE TITLE
Blazor Server application disconnects if starting "chromium-browser" process from the app itself on Linux

### ISSUE THREAD

**Issue by KyryloAntoshyn** [dotnet/aspnetcore#26864]
### Bug
Hi! I have the problem with my Blazor server application. I run it on Raspberry Pi 3 (Linux). When the application is started ("ApplicationStarted" is triggered) I start bash "chromium-browser" process and pass app's URL. The problem is that the app opens, everything goes fine, but one time per 30 seconds error occurs: **"Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'."** If I start chromium browser manually (comment "ApplicationStarted" handler) after my server is started and navigate to the server URL everything works fine.

### To Reproduce
All the logic is into Startup.cs. Also, I created linux-arm Release.
[bug.zip](https://github.com/dotnet/aspnetcore/files/5373989/bug.zip)

### Exceptions
There are no exceptions actually. I've only observed the error via Chromium console (shared above).

### Further technical details
I use ASP.NET Core Runtime 3.1.8 on RPi 3. For development I use .NET Core SDK 3.1.4.
Moreover, I use VS Code IDE for development, but not on RPi. I develop the app on my Windows machine.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@BrennanConroy any recommendation how this can be diagnosed?

**Comment by BrennanConroy** [comment]
I'm assuming launching the "chromium-browser" and waiting for the process will block until the browser is closed. Because you're doing this in the `ApplicationStarted` registration you end up blocking anyone else who is using `ApplicationStarted`, in this case SignalR is using that token to start the heartbeat thread which is what sends ping messages. Because that never runs (since you blocked it), you never get ping messages from the server and your client will close with an error.

An easy test for this would be to change your code to `_ = Task.Run(() => ExecuteBashCommand("chromium-browser http://localhost:5000"));`

**Comment by KyryloAntoshyn** [comment]
Thanks, @BrennanConroy! Tomorrow I will test it and respond you with results!

**Comment by KyryloAntoshyn** [comment]
If we start process in another thread it works! Thanks @BrennanConroy and @mkArtakMSFT!
