### ISSUE TITLE
Error in Counter.razor when the project is being translated in Chrome

### ISSUE THREAD

**Issue by rfinorf** [dotnet/aspnetcore#26945]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/try
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

invalidOperationException: TypeError: Cannot read property 'removeChild' of null.

I think one of the causes is page translation.
I'm sorry if it has already been reported.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue. We will see whether there is a way to slightly change the template to avoid this issue.

**Comment by captainsafia** [comment]
It appears that this is an issue affecting other frameworks as well. There's a lengthy thread discussing this over on the react repo at https://github.com/facebook/react/issues/11538.

The issue seems to be related to the way that the Google Translate extension replaces text nodes on a page with `<font>` tags to facilitate translation. The React team did not pursue a fix because any fixes in the framework would've impacted perf/reliability as documented in https://github.com/facebook/react/issues/11538#issuecomment-417504600.

There's an open issue on Chrome to address this behavior that is documented here: https://bugs.chromium.org/p/chromium/issues/detail?id=872770. It looks like there's a bit of activity on that thread and plans to address this sometime next year.

I'll close this as external to Blazor for now. It's probably not worth it to invest in workarounds in Blazor that would be rendered moot by a more reliable fix in Chrome/Google Translate.
