### ISSUE TITLE
VS2019 16.7.6 Image not showing in Blazor serverside. In 16.7.5 was working fine

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26970]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1220509/vs2019-1676-image-not-showing-in-blazor-serverside.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:2019 16.7.5]
In VS2019 version 16.7.6 <img> control is not showing the source image.
Blazor Serverside. 
In version 16.7.5 was working fine

---
#### Feedback Bot on 10/14/2020, 11:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
To be able to use static assets (an image in your case) from your app, they have to be located in the `wwwroot` folder . In your situation, it looks like the image is located in the root of the project directory.
I'm not sure how it would work being in the root directory before your update, but the behavior you experience currently is correct.
If you can reproduce the behavior you've experienced earlier, share a small project with us and we would like to investigate it further.

**Comment by homeconstructor** [comment]
Sorry, but I tried to store the image in every possible folder but never show the image...also tried to show an image stored in other internet address but not showing it too....In version 16.7.5 was working fine...
This happens when I run the App from VS2019...But, when I run the App under IIS work fine
I have some Blazor ServerSide Proyects that stop showing images after an update to 16.7.6

![from IIS](https://user-images.githubusercontent.com/31412149/97052831-ff1d3200-1581-11eb-8fc4-71f60ea8a5b6.png)
![from VS2019](https://user-images.githubusercontent.com/31412149/97052834-ffb5c880-1581-11eb-9157-0f45bbd6fd82.png)

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details, @homeconstructor.
In order for us to investigate this we need a small repro project. Can you please share one so we can move forward with this. Also, in the related feedback ticket you've mentioned that you've recorded a video showing the experience. Can you also link it here? Thanks1
