### ISSUE TITLE
Investigate behavior of Blazor Server on mobile when switching apps

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#26985]
Folks at [ThePostage](https://thepostage.com) reported that they often see connection loss issues on mobile devices when switching apps. The said the problem seemed worse or iOS. We should take a look at the experience and see if there's anything we can do to improve it.

**Comment by konradbartecki** [comment]
This is most likely due to circuit being recycled on the server after some time. 
Then when mobile browser is resuming after a long time it shows the "connection lost, retryiing..." dialog for 3 seconds (default), then tries to reconnect, but this attempt is immediately rejected and results in `Could not reconnect to the server. Reload the page to restore functionality` message.

See #32113

**Comment by mkArtakMSFT** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/32113
