### ISSUE TITLE
Visual Studio Intellisense for Web Component (custom-element.json) [Blazor]

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/aspnetcore#27054]
Hello aspnetcore Team,

I wanted to ask if there is intellisense support for html web compontents in Visual Studio (non code)

We are working with some designers who build us a design system with html web components, the same which are
used in FAST in this Community Standup:
https://www.youtube.com/watch?v=sYTH_xYH3iA&list=PL1rZQsJPBU2St9-Mz1Kaa7rofciyrwWVx&index=2

The components work excellent, even with Blazor data binding.

Now I found that in Visual Studio Code supports this using the html.customData setting
https://code.visualstudio.com/blogs/2020/02/24/custom-data-format
https://stackoverflow.com/questions/62312996/visual-studio-intellisense-for-custom-web-components
and they suggested it to the w3c: https://github.com/w3c/webcomponents/issues/776

Is there also some support in Visual Studio planned/existing for custom-elements.json? Especially for blazor.
We are currently using lit-elements for creating web components.

Thank you very much
Greetings
Michael

**Comment by javiercn** [comment]
@MichaelPeter thanks for contacting us.

This is not something that our team directly works on. I would suggest that you file this issue through the [Visual Studio suggest a feature dialog](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) as it will be routed to the right team and placed in the right channels so that other users can show interest and you'll get a better and faster response.
