### ISSUE TITLE
Scaffold tool to extract views (cshtml files) from Razor class libraries

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/aspnetcore#27110]
### Is your feature request related to a problem? Please describe.

When you add `Identity` to your ASP.NET Core applications, you can **scaffold** its Razor pages.

[![enter image description here][1]][1]

I am looking for a way to **extract** my views **from a referenced RCL** just like `Identity`.

I mean, I want to create `Area` and related files (cshtml) to help developers to customize it (not a specific UI as you see in the above pic).

  [1]: https://i.stack.imgur.com/xetU5.png
  [2]: https://i.stack.imgur.com/oNmqA.png

### Describe the solution you'd like

I think global `dotnet` tools can help us to extract `cshtml` files into the current project.

I checked inside of a Razor class library with `dotpeek` there is no HTML resource, everything is class.

[![enter image description here][2]][2]

I am not sure the idea is possible now to achieve.

### Additional context

Without any tools, I think as a developer I should add my `cshtml` files to Nuget package as **file contents**, so whenever a user adds the package access to all files below `Area/Library` folder.

**Comment by javiercn** [comment]
@HamedFathi thanks for contacting us.

Unfortunately that is not a feature we support nor plan to. Razor files are compiled to C# at build time and only the assembly is packaged with them. It is up to library authors to bundle the original Razor files within their packages and there would need to be a standard convention for "extracting them".

Bear in mind that even if there were to be a convention to pack the files in a "standard" location, normally the views you scaffold are not same that you include in your compiled output, specially if you have to deal with generics and other aspects that add complexity to building class libraries.

That said, you can create your own convention and tool for this if you choose to do so, simply pack the Razor files in your nuget package at a convenient location and create a tool to unzip the package, and dump the files into your project.

As I said, this is not a direction we plan to go for the time being, since there's a way for users to achieve this through current extensibility and we haven't received enough feedback about it.

We understand this might not be what you expected to hear, but we hope that at least the reasons above help explain why we are unlikely to take action in this area.

**Comment by HamedFathi** [comment]
@javiercn 

 Thank you so much,  no problem at all.

Just for curiosity, How do you this scaffolding feature for Identity? 

How do you get cshtml files for it?

**Comment by javiercn** [comment]
We maintain a separate set of views and scaffolding logic [here](https://github.com/dotnet/Scaffolding/tree/master/src/VS.Web.CG.Mvc)

**Comment by HamedFathi** [comment]
Thanks
