### ISSUE TITLE
Completion - typing closing HTML bracket deletes prior characters

### ISSUE THREAD

**Issue by allisonchou** [dotnet/aspnetcore#27152]
Typing out `</p>` manually will delete prior characters in the tag:

![CompletionDeletion](https://user-images.githubusercontent.com/16968319/96942338-b1bd9980-1489-11eb-91ec-43cee00c813f.gif)

**Comment by NTaylorMullen** [comment]
Investigated and the reason why this is happening is because the filtering logic done by the core editor doesn't include the `</` as part of the potential filter list because it's not a valid identifier. Therefore, `p` ends up having a direct match in the completion list so it gets selected. Unfortunately that p ends up deleting the `</` text edit range.

There's many solutions that can be approached here so i'm marking this for the time being as being blocked externally until we can talk more with the WebTools folks on the right approach

**Comment by NTaylorMullen** [comment]
This is mostly fixed now; however, there's a separate issue where the start tag completion item takes precedence over the end tag one which is being tracked here: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1267847

For now closing this out as the root issue was resolved.
