### ISSUE TITLE
Incorrect CSS style completion in Razor component after hyphen

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27150]
Version 16.9.0 Preview 2.0 [30621.305.main]
New Razor editor

After a hyphen in a CSS property name, it looks like the completion list resets to only look at text after the hyphen:

![image](https://user-images.githubusercontent.com/1874516/96941979-a61da300-1488-11eb-873b-061c2ad17eb0.png)

Here's the expected completion:

![image](https://user-images.githubusercontent.com/1874516/96942049-e4b35d80-1488-11eb-8147-fad4d5f05847.png)

**Comment by jimmylewis** [comment]
I don't think we had noticed that yet, but I repro'd and we're sending back everything in the LSP response.  Maybe the client-side completion filtering is chucking out the goods?  @AmadeusW do you know offhand what the client logic is to reset/filter the completion session?  I see it close and reset after I type the `-` which kind of sucks for a kebab-cased language like CSS:

![razor-css-completionReset](https://user-images.githubusercontent.com/3976973/98751821-b59c5780-2375-11eb-8aaa-1a4dcab222c5.gif)

**Comment by NTaylorMullen** [comment]
> I see it close and reset after I type the `-` which kind of sucks for a kebab-cased language like CSS:

That's because it's a commit character no?

**Comment by jimmylewis** [comment]
> > I see it close and reset after I type the `-` which kind of sucks for a kebab-cased language like CSS:
> 
> That's because it's a commit character no?

Did you guys make it one?  It's not for our servers, because that would be silly. 😜  Seriously though... looks like [it is for Razor contained languages](https://github.com/dotnet/aspnetcore-tooling/blob/c8f395524c8976c3cdeacba01b67ee8c5fccacf8/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs#L22) though we don't do that in the HTML delegation server (for us it's a trigger character but not a completion character).

I've opened DevDiv bug 1245576 to track this on our side.  If we specified the completion characters on each completion item it would not fallback to the incorrect server default setting.

**Comment by NTaylorMullen** [comment]
@allisonchou I'd imagine when the platform supports embedded language-configuration.json's word patterns that this would be "fixed" because CSS would be detected and its word pattern would be used resulting in the appropriate completion experience

**Comment by NTaylorMullen** [comment]
This is fixed in 17.0-Preview3
