### ISSUE TITLE
Utilize DebuggerDisplayAttribute for improving debugging in ASP.NET apps

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27279]
Debug views on HTTPRequest like ToString on HttpRequestMessage so that you can make sense of things easier. Make the watch window more usable. Debug attribute for how to show this when debugging.

**Comment by captainsafia** [comment]
During today's meeting, we also discussed doing an audit of our codebase to identify places in our codebase where we would benefit from adding DebuggerAttributes.

**Comment by captainsafia** [comment]
@adityamandaleeka We've had the `help wanted` issue on this for a while so I'm inclined to close it. It's also not clear to me that adding these attributes on the particular types would provide a benefit to users. I assume that's why we haven't gotten much contributor traction either.

If you agree, feel free to close!

**Comment by adityamandaleeka** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/48205
