### ISSUE TITLE
Request Cookie Key is truncated if contains @ (at character)

### ISSUE THREAD

**Issue by Domon87** [dotnet/aspnetcore#27311]
# Issue Title

Request Cookie Key is truncated if contains @ (at character)

# General

In Request.Cookies i get all the cookies but the key is truncated if contains @ character.
For example, **MDL_testcookie@default.it** cookie name is truncated in **default.it** .

My workaround for this issue is for now to access the Cookie list using Request.Headers["Cookie"] and check the cookie string manually.

.NET Core framework version is 3.1

**Comment by Tratcher** [comment]
That's because `@` isn't allowed in cookie names, no symbols are.

https://tools.ietf.org/html/rfc6265#section-4.1.1
       cookie-name = token
https://tools.ietf.org/html/rfc2616#section-2.2
       token = 1*<any CHAR except CTLs or separators>
       separators = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT

You'll need to encode (%40) or remove the `@`.

The failure in this case is somewhat novel. The parser tries to read a `token`, reaches the first separator `@`, decides `MDL_testcookie` isn't a valid cookie because it doesn't have an `=` after it, discards the invalid cookie and keeps going with `default.it=value` which is valid.
