### ISSUE TITLE
Blazor wasm lazy loading is not working

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#27331]
### Describe the bug
Using [lazy loading of assemblies](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0) fails when a service extension method is used.

### Additional context
A blazor wasm [project](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/tree/master/BlazorWasmLazyLoading) is configured to use lazy loading for a [class library project](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/tree/master/BlazorWasmLazyLoading/MyComponents) that has some [dependencies](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/blob/171e24ba8046ad48809893d6ff25e658882c8fc2/BlazorWasmLazyLoading/MyComponents/MyComponents.csproj#L13-L16). The app is inspired by the [example from Dan Roth](https://github.com/danroth27/BlazorNet5Samples/blob/3ad3f531330d10754fe7cce3ad063b7f6b86da63/Client/BlazorNet5Samples.Client.csproj#L22) and the [MyComponents](https://github.com/danroth27/BlazorNet5Samples/tree/master/MyComponents) lib.

The problem occurs when a [service extension method](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/blob/171e24ba8046ad48809893d6ff25e658882c8fc2/BlazorWasmLazyLoading/BlazorWasmLazyLoading/Client/Program.cs#L25) is used, which is [empty](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/blob/171e24ba8046ad48809893d6ff25e658882c8fc2/BlazorWasmLazyLoading/MyComponents/ServiceExtensions/ServiceCollectionExtensions.cs#L7-L10). [Not using this method](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/blob/171e24ba8046ad48809893d6ff25e658882c8fc2/BlazorWasmLazyLoading/BlazorWasmLazyLoading/Client/Program.cs#L20-L22) works as expected and no errors are thrown.

### To Reproduce
1. Clone https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue
2. Set the [server project](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/tree/master/BlazorWasmLazyLoading/BlazorWasmLazyLoading/Server) as a startup project
3. Run the app by pressing `Ctrl + F5`

#### Expected
The dependency assemblies are loaded without errors.

#### Actual
An exception is thrown and the app crashes. The actual component that triggers lazy loading is in the [Counter.razor file](https://github.com/Stamo-Gochev/blazor-wasm-lazy-loading-issue/blob/master/BlazorWasmLazyLoading/BlazorWasmLazyLoading/Client/Pages/Counter.razor#L7).

### Exceptions (if any)
AN exception is thrown in the console
> System.IO.FileNotFoundException: Could not load file or assembly 'MyComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### Further technical details
- ASP.NET Core version 5.0 RC2
- Include the output of `dotnet --info` 
- The IDE (VS / VS Code/ VS4Mac) latest

**Comment by captainsafia** [comment]
Thanks for opening this issue, @Stamo-Gochev!

The scenario that you're describing isn't supported by the lazy-loading features in Blazor. The `AddMyComponent` method from `MyComponent1` is used in the initialization logic before the app has been launched and the `OnNavigateAsync` code path is invoked.

We designed the lazy-loading feature to support lazy-loading on a per-route basis. Since the `AddMyComponent` method needs to be used when the application first launches, it's reasonable to lazy loaded. For your scenario, I'd recommend splitting up the parts of your package that you do want lazily-loaded (the components) from the things you want to use during initialization (the `AddMyComponent` API).

Let me know if you have any follow-up questions.

**Comment by Stamo-Gochev** [comment]
@captainsafia A follow-up question - as splitting a package into multiple packages in order to support lazy loading is not always possible (e.g. in order to be backward compatible), is there any chance for the current limitation to be fixed in the future or have some type of a workaround? As the service injection is not working, another approach might be to define the injected service as a variable and mark it with some attribute to signal the variable is dependent on the lazy loading feature (note that currently this fails with the same error as described above):
```csharp
@code {
        [LazyLoaded]
        public MyCustomComponentClass CustomClass { get; set; } = new MyCustomComponentClass();
}
```

**Comment by captainsafia** [comment]
@Stamo-Gochev Thanks for the feedback! That's definitely a valid scenario that we had considered in the design but opted out of since we didn't consider it to be a common scenario.

Would you be interested in opening an issue with this feature request so we can gauge how many folks would find this helpful?

**Comment by Stamo-Gochev** [comment]
@captainsafia I will log an issue, but is the service injection possible at all as it works on per app level (`services.AddSingleton<SomeService>`) or are you rather referring to the "workaround" suggestion with an attribute?

**Comment by captainsafia** [comment]
>  are you rather referring to the "workaround" suggestion with an attribute (the exact implementation can be something else like a configuration)?

I was referring to the second scenario with the workaround. It's reasonable to assume that people might not want to split out their components into a separate RCL to get them to work with lazy-loading.

With regard to the service injection, the scenario you provided doesn't work with lazy-loading since the lazy-loaded service is used before the app has been initialized at all.

**Comment by Stamo-Gochev** [comment]
@captainsafia I've logged the issue in https://github.com/dotnet/aspnetcore/issues/27811, feel free to update it accordingly.

**Comment by ChristianWeyer** [comment]
> @Stamo-Gochev Thanks for the feedback! That's definitely a valid scenario that we had considered in the design but opted out of since we didn't consider it to be a common scenario.
> 
> Would you be interested in opening an issue with this feature request so we can gauge how many folks would find this helpful?

Hi @captainsafia :-) I can confirm that this a is very common and indeed much-needed scenario for splitting out functional modules that can be lazy-loaded.
Thanks!
