### ISSUE TITLE
Improve dev-experience when working with containers

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27350]
## Summary
We should treat containers as a first class citizens when we build features. For example:
- blazor web assembly debugging doesn't work when you try to debug in a container
- when running on containers, tests should also be run in a container.
- the certificate we generate doesn't work on linux. This was a bug in OpenSSL which should already be fixed.
- Certificate and security problems in container to container communications Integration of the certificate issuance in docker/kubernetes
- HTTP forwarding headers by default inside containers

### People with more context
@javiercn, @blowdart

**Comment by jkotalik** [comment]
I think there is also some work we can consider with improving dotnet's integration with containers natively aka a lot of the work we did in tye. cc @glennc @amarie401

**Comment by javiercn** [comment]
* the certificate we generate doesn't work on linux. This was a bug in OpenSSL which should already be fixed.
* Certificate and security problems in container to container communications Integration of the certificate issuance in docker/kubernetes

These two we have solutions for

**Comment by javiercn** [comment]
I'm wondering for _Certificate and security problems in container to container communications Integration of the certificate issuance in docker/kubernetes_ if we can go a bit further and update our docker files to handle trusting the certificate as part of the build process for the image.

So something along the lines of:
* Check if there is a crt file on disk during docker build and copy it to the proper location in the runtime image.
* On the runtime image, run update-ca-certificates to make the cert trusted in that container

**Comment by peterbozso** [comment]
@mkArtakMSFT does the sentence "blazor web assembly debugging doesn't work when you try to debug in a container" mean that when debugging a Blazor WASM app inside a container, in VS2022 the breakpoints don't work with the error message "The breakpoint will not currently hit. No symbols have been loaded for this document."?

I am asking because I was following these issues: #27766 and #22587 to see when it's fixed, but from there I get the idea that it's already solved with the release of .NET 6. But I still face the same problem, trying to debug with VS2022 a Blazor WASM app running in a container, targeting .NET 6.

**Comment by mkArtakMSFT** [comment]
Closing as this is too high level and we have (couldn't find it yet, but it's there) a blazor-specific issue to make development better in containers.
