### ISSUE TITLE
Invalid Confirmation Email Code Resource is missing in IdentityErrorDescriber

### ISSUE THREAD

**Issue by isalo** [dotnet/aspnetcore#27416]
Invalid Confirmation Email Code Resource is missing in IdentityErrorDescriber

```
var result = await _userManager.ConfirmEmailAsync(user, code);

if (result.Succeeded)
{
  return Ok($"Вашу електронну пошту {user.Email} було підтверджено");
}
else
{
  return BadRequest(result.Errors);
}
```

result.Errors contains error - `Invalid confirmation URL. Please try again.`

And there is no way to localize it using `IdentityErrorDescriber`

**Comment by HaoK** [comment]
Generally we use InvalidToken as the error today, we don't have a specific error for each of the various methods that do token validation, you can override the UserManager method and customize this if you want a specific error message due to failures in each of the various token validation methods.

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Identity/Extensions.Core/src/UserManager.cs#L1497
