### ISSUE TITLE
Add an `HttpVersion` property to `JwtBearerOptions`

### ISSUE THREAD

**Issue by ghominejad** [dotnet/aspnetcore#27426]
### My identity provider only supports `Http2` protocol.
But it seems there is no a simple option to specify the http version in  `AddJwtBearer `

### Solution
Add `AuthorityHttpVersion`  in `configureOptions`

```CSHARP
services.AddAuthentication(
...
).AddJwtBearer(options =>
            {
                options.Authority = authorityUrl;
                options.AuthorityHttpVersion = HttpVersion.Http2;
                ...
            });
```

### More info
Currently I have to implement a `HttpMessageHandler` to force using `http2`

```CSHARP
services.AddAuthentication(
...
).AddJwtBearer(options =>
            {
                options.Authority = authorityUrl;
                options.BackchannelHttpHandler = new ForceHttp2Handler(new SocketsHttpHandler());
                ...
            });


```

**Comment by Tratcher** [comment]
We address this in the other providers by letting you set the `RemoteAuthenticationOptions.Backchannel` [HttpClient](https://github.com/dotnet/aspnetcore/blob/584e06fcedc7f26f59d19305b68207ec982bd11a/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L78) and its [DefaultRequestVersion](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=netcore-3.1). If the client is not provided then we build it from the other properties. 
https://github.com/dotnet/aspnetcore/blob/3fdbc2e90d9762324ef3809098c9ca25b0cb3284/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L67-L73

It looks like we overlooked this for JwtBearerOptions because it doesn't derive from RemoteAuthenticationOptions, but it should be easy to add there too.
https://github.com/dotnet/aspnetcore/blob/3fdbc2e90d9762324ef3809098c9ca25b0cb3284/src/Security/Authentication/JwtBearer/src/JwtBearerPostConfigureOptions.cs#L53-L55

Does that approach work for you @ghominejad?

**Comment by ghominejad** [comment]
Thank you for your consideration.
Yes, of course, but I think It worth it having a simple option to achieve this also.

**Comment by Tratcher** [comment]
I think we already have too many separate configuration options for the HttpClient as is. Long term we'd like to replace a lot of this with the IHttpClientFactory.

**Comment by ghominejad** [comment]
Am I allowed to make a PR about the issue you mentioned?

**Comment by Tratcher** [comment]
JwtBearerOptions intentionally does not derive from RemoteAuthenticationOptions, RemoteAuthenticationOptions is designed for redirect style authentication like OAuth, OpenIdConnect, WsFed, etc., many of the other properties wouldn't apply.

The recommended fix here is to add an `HttpClient Backchannel` property to JwtBearerOptions like the one RemoteAuthenticationOptions has, and update JwtBearerPostConfigureOptions accordingly. Please do give that a try.
