### ISSUE TITLE
Refactor NavigationManager by concept area

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27456]
**Note:** Edited by captainsafia on 11/2/2020.

The `NavigationManager` class currently implements several different concepts in one:

- Methods for doing the actual navigation (e.g. `NavigateTo` and `SetLocation`)
- Methods for handling the navigation lifecycle (e.g. `OnLocationChanged`)
- Methods for getting and validating the current URL

We should explore splitting up this implementation into 2 or more distinct interfaces for .NET 6.

By default, this change will be a breaking binary change but we can explore options for this if we want to pursue the work.

**Comment by BenjaminCharlton** [comment]
May I add an idea here?

It would be good if the `NavigationManager `implemented an interface outside of ASP .NET Core (such as `INavigationManager`) that could be shared by a different type of `NavigationManager` for Xamarin (and potentially others).

That way, those of us that follow the MVVM pattern can inject an implementation of the `INavigationManager` interface in the constructor of our ViewModels so that the ViewModels remain ignorant of whether they are being by a Xamarin app or Blazor app or something else entirely.

If you end up splitting `NavigationManager` into different classes in .NET 6 like you suggest here, then this feature request still applies but for each of the new classes.

Hope it's clear what I mean and thanks for your consideration and hard work (I love .NET 5 and Blazor).
