### ISSUE TITLE
Blazor Webassembly AAD and AAD B2C support improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#27549]
Here are some of the things we don't support we have received feedback about, and we could consider doing on the 6.0 timeframe.

- [ ] Support for reset password flow in Azure AD B2C.
- [ ] Login with Identity Providers (option to skip silent token acquisition/login)
- [ ] Support for incremental consent.
  * Enable requesting scopes incrementally when the app needs them instead of requesting all during startup.
- [ ] Support for login hint
- [ ] Support for prompt options
- [ ] Silent sign on
- [ ] Support for conditional access

**Comment by AlbertoPa** [comment]
Any chance the password reset workflow is addressed for 5.x? 
In the current status, for Blazor Webassembly, there isn't a clean approach to have this basic functionality without writing a good amount of user code.

**Comment by chrislangston** [comment]
> Any chance the password reset workflow is addressed for 5.x?
> In the current status, for Blazor Webassembly, there isn't a clean approach to have this basic functionality without writing a good amount of user code.

We also face issue with being able to use Blazor Web Assembly with AD B2C for our clients since we have not been able to figure out how to handle the redirect back to the client after they have selected the option that they have forgotten their password.

Seeing an example of how we can intercept this error in the query string and then handle the redirect approprately would be helpful.

https://localhost:5001/authentication/login-callback#error=access_denied&error_description=AADB2C90118%3a+The+user+has+forgotten+their+password.%0d%0aCorrelation+ID%3a+6e6935b7-b602-4228-b658-1c3e942fcc57%0d%0aTimestamp%3a+2020-11-25+18%3a56%3a40Z%0d%0a&state={SOME STATE VALUE}

**Comment by AlbertoPa** [comment]
In reference to my comment above, password reset is not managed with the self-sevice password reset process, directly through AD B2C, which works fine. 

However, profile editing and other user's flows available by default in AD B2C do not have support, so it would be nice to have those supported out of the box (a way to capture the callback in Blazor would be needed).

Thanks!

**Comment by AlbertoPa** [comment]
In reference to my comment above, password reset is not managed with the self-service password reset process, directly through AD B2C, which works fine. 

However, user's profile editing and other user's flows available by default in AD B2C do not have support, so it would be nice to have those supported out of the box (a way to capture the callback in Blazor would be needed).

**Comment by TestLearningUser** [comment]
almost two years and nothing about incremental consent, good job microsoft

**Comment by javiercn** [comment]
All these are covered by https://github.com/dotnet/aspnetcore/issues/42580
