### ISSUE TITLE
Light bulb refactorings can break C# semantic colorization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27593]
In a Blazor app in Codespaces open up Counter.razor and add:

```
@code {
    class Test : IDisposable
    {
    }
}
```

Invoke the light bulb to implement the dispose pattern for IDisposable and see colorization break (ignore the double light bulbs, that's another issue but this happens even without htat):

![ZH9VLkgiuO](https://user-images.githubusercontent.com/2008729/98414909-10117d00-2031-11eb-9217-e1277e7d84b8.gif)

I wasn't able to reproduce this in a pure C# file so I'm imagining it has something to do with Razor. Also it doesn't seem to reproduce locally. @gundermanc I imagine this is a LiveShare sync issue? I would have imagined that it would have been "eventually" correct but it never corrects

**Comment by NTaylorMullen** [comment]
Hmm, something odd may have been happening because I can't reproduce anymore but also looking at the gif I attached there were also multiple light bulbs for the same thing

**Comment by gundermanc** [comment]
>I would have imagined that it would have been "eventually" correct but it never corrects

Unfortunately no, once we're out of sync, the only way we can detect the error condition at the moment is by getting semantic tokens edits from the server that place tokens at positions that don't exist. Until that happens, we exist in a corrupt state because there's ATM no standardized checksum for the post-edit buffer state in LSP protocol standard. :(

Hints as to what's going on:

- _Some_ .NET lightbulbs can trigger server-side changes, which are violation of the LSP protocol's assumption that all edits happen on the via `workspace/applyEdit`. Issue on Roslyn here: https://github.com/dotnet/roslyn/issues/48991.
- I saw at least one case where the colors would get mis-aligned with lightbulbs that didn't seem to be doing any server edits, so it's possible there's a race condition bug in application of edits in `workspace/applyEdit` in the IDE's LSP client too.

We should fix both of these by 16.9 GA. Both of these seem to be covered by my work on IDE's LSP message + text synchronization and remoting story. 

@NTaylorMullen do you have a set of lightbulb actions that are known to consistently cause this issue? Doing so will help me prioritize which end needs fixed first.

**Comment by TanayParikh** [comment]
+1

![image](https://user-images.githubusercontent.com/14852843/98420011-27556800-203b-11eb-908e-52da21a60127.png)

**Comment by gundermanc** [comment]
FYI: I have filed a proposed user story to harden the LSP client's portion of these scenarios: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1243527.

The intent is that if possible, we support server-side edits and have a 'gating' mechanism where we don't actually inform the LSP server about the edit until it has been acknowledged by the client.

I don't have any more details yet, this will probably require some prototyping and possibly a change to the in-proc Roslyn bits.

**Comment by NTaylorMullen** [comment]
Verified on latest and no longer repros with other light bulbs.

**Comment by TanayParikh** [comment]
Hmm still seeing this:
![image](https://user-images.githubusercontent.com/14852843/112937102-ea6a3a80-90db-11eb-9dbf-fdda698ca182.png)

**Comment by NTaylorMullen** [comment]
@TanayParikh ya that seems quite messed up from semantic tokens perspective? @ryanbrandenburg would this fall under the larger semantic token issue we saw yesterday in triage that you were planning to run by Christian?

**Comment by gundermanc** [comment]
>would this fall under the larger semantic token issue we saw yesterday in triage that you were planning to run by Christian?

That sounds like the issue fixed by this PR: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/313631

**Comment by TanayParikh** [comment]
Seeing this as well, not sure if it's related?

![ColorizationIssues](https://user-images.githubusercontent.com/14852843/113335220-7bf2cb80-92d9-11eb-8e9d-04ed970d47f3.gif)

**Comment by NTaylorMullen** [comment]
I believe so. Don't know if the LSP platform PR has been fixed yet. Now that being said, the way semantic token ranges are growing like that are a little concerning and may be something @gundermanc may want to look at in general 😄. Aka, semantic ranges shouldn't grow to include whitespace, they should stop at word boundaries

**Comment by ryanbrandenburg** [comment]
Yeah, that behavior looks like VS trying to "guess" at how it should colorize while it waits for Semantic or Syntactic tokens, but @gundermanc would know more.

**Comment by gundermanc** [comment]
>Aka, semantic ranges shouldn't grow to include whitespace, they should stop at word boundaries

This is a known issue with semantic tokens at the moment. The issue is that we're mapping from the data edits you give us right into buffer tags and tracking in reverse lets tags get out of order on deletions, so they currently all track forward. I haven't yet looked at a fix.

The part that worries me is the extra segment highlighting the 'h' after the edit is applied. That looks like a token wasn't removed properly.

**Comment by TanayParikh** [comment]
Should I re-open this issue to track?

**Comment by gundermanc** [comment]
>Should I re-open this issue to track?

Can you verify:

- This repros on lightbulb application.
- It goes away when the document is closed and reopened

**Comment by TanayParikh** [comment]
> > Should I re-open this issue to track?
> 
> Can you verify:
> 
> * This repros on lightbulb application.
> * It goes away when the document is closed and reopened

Created: https://github.com/dotnet/aspnetcore/issues/31566

This specific example does not require light bulbs at all. Just type in the above text and then add a <kbd>TAB</kbd> and <kbd>SPACE</kbd> char to the front of the line.

The issue is resolved on document reopen.
