### ISSUE TITLE
Windows Emoji + Blazor *.razor file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27664]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Windows-Emoji--Blazor-razor-file/1242561?preview=true)._

---
[severity:It bothers me. A fix would be nice]
Any use of emojis from the Windows OS emoji picker pasted/added to *.razor file in Blazor project (VS19) results in a instant crash.

---
#### Feedback Bot on 11/4/2020, 01:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue is fixed in the latest Visual Studio 2022. If you'd like to try this tooling out you can download the latest VS 2022 and re-try your scenario.

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
