### ISSUE TITLE
Huge delay between code change and error reporting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27665]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Huge-delay-between-code-change-and-error/1244499?preview=true)._

---
[severity:It's more difficult to complete my work]
An ASP.NET Core 3.1 Web API with VS 16.7.7

When I change some code that should be in error, there's a huge delay between the change and VS reporting the error in Error list.  Same thing happens if I fix the error, the error reported takes too much time to disappear.  I saw similar problem discussion however it was closed for not being able to reproduce.  This should be addressed whatever you can or not reproduce.  I consider this a major issue for us.

I provide a video to show the issue.

---
#### Feedback Bot on 11/4/2020, 06:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Goal here is to see if this is us or not.

**Comment by GearTheWorld** [comment]
If that can help, since my VS didn't change since at least 2 years at most and have zero extension, I saw the progression of lag as new version was coming in.  More lag was introduced during this past 5 months.  It would be fair to think that the charge of VS to inspect the code real time has been overwhelmed somehow.  Another area where I see that is when opening a JS file which formatting takes a very long time.  So long in fact that if I try to **Collapse to definition** during formatting, it'll never format and I have to restart VS and wait again.  Again all this was perfectly smooth and fast at least 1 year before.

**Comment by NTaylorMullen** [comment]
> Another area where I see that is when opening a JS file which formatting takes a very long time. So long in fact that if I try to **Collapse to definition** during formatting, it'll never format and I have to restart VS and wait again. Again all this was perfectly smooth and fast at least 1 year before.

@uniqueiniquity This a known thing?

**Comment by GearTheWorld** [comment]
Probably related

**Comment by uniqueiniquity** [comment]
Not a known issue.
@GearTheWorld, I see that your recording involves the error list responding to a C# change.
I think it would be beneficial to investigate the C# and JS issues separately.

Would you be willing to file another feedback ticket with a recording of the JS issue you described?
I'd love to investigate further.

**Comment by GearTheWorld** [comment]
@uniqueiniquity Sure,  I'll get back to you as soon as possible with a recording.

**Comment by uniqueiniquity** [comment]
Thanks! Using the Report A Problem feature in VS and attaching repro steps (as you did with your first ticket) would be best.

**Comment by GearTheWorld** [comment]
Hi,
Here's the link : [](https://developercommunity2.visualstudio.com/t/Opening-a-JS-file-is-not-formatted/1262240)

**Comment by GearTheWorld** [comment]
Hi,
Here's the link : [https://developercommunity2.visualstudio.com/t/Opening-a-JS-file-is-not-formatted/1262240](url)

**Comment by NTaylorMullen** [comment]
@GearTheWorld for the "error reporting" issue initially reported here do you see the same thing happen in Visual STudio 2022?

**Comment by GearTheWorld** [comment]
@NTaylorMullen To date, I've not been able to see that issue in VS 2022 which is right now at Preview 3.1 for me.  This doesn't mean it's not there.

**Comment by NTaylorMullen** [comment]
Ah quite interesting. Do you happen to have a repro project or steps that we could play around with to investigate further?

**Comment by GearTheWorld** [comment]
You may just start a new project since this isn't dependent on a particular project I have on hand.  Start a new ASP.NET MVC web app and import one of your .JS file which is big enough already and then once the project is created, restart VS and see what happen to a .JS already opened.  

That means before closing your solution, make sure your .JS is opened so VS opens it at startup.  Then try to interreact when the .JS is loaded but formatting isn't applied yet since it'll take several seconds before the .JS is formatted completely.

**Comment by NTaylorMullen** [comment]
> That means before closing your solution, make sure your .JS is opened so VS opens it at startup. Then try to interreact when the .JS is loaded but formatting isn't applied yet since it'll take several seconds before the .JS is formatted completely.

Ahhh that's in a JavaScript file not in a Razor file right?

**Comment by GearTheWorld** [comment]
Exactly

**Comment by NTaylorMullen** [comment]
@GearTheWorld would you mind logging an issue in VS via Report a Problem in the top right hand corner? Unfortunately a different team owns the JavaScript editor.

For now going to close this issue. If you link the VS issue here we can make sure it gets routed to the right folsk though
