### ISSUE TITLE
Adding .cs files causes intellisense to break down

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27660]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Adding-cs-files-causes-intellisense-to-/1233107?preview=true)._

---
[severity:It's more difficult to complete my work]
VS 16.8.0 Preview 4 (and a few versions prior to this) have an issue when adding a .cs file. When added, intellisense fails to work. The only way to activate intellisense is to quit VS and delete all bin, obj and .vs folders. This seems to happen most frequently with .razor.cs Blazor backing files, where I am unable ever to add a file without having to perform this reset manoeuvre.

---
#### Feedback Bot on 10/26/2020, 11:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
