### ISSUE TITLE
ApiExplorer does not correctly populate parameters for IApiDescriptionGroupCollectionProvider when modelbinding is used

### ISSUE THREAD

**Issue by statler** [dotnet/aspnetcore#27671]
[ApiDescriptionProblem (2).zip](https://github.com/dotnet/aspnetcore/files/5514600/ApiDescriptionProblem.2.zip)
### Describe the bug
When using [modelbinder] attribute, the ApiExplorer does not correctly populate for parameters of a controller method

### To Reproduce
Populate the API Explorer for a parameter that uses [modelbinder]. Instead of the parameterDescriptions being enumerated in the ApiDescription as happened in .Net Core 2.2, the ApiDescription contains only the name of the parameter.

In the attached project, run it and put a breakpoint in the constructor of SampleDataController. The property group contains 2 items. The first uses modelbinding and has one parameter whereas the second directly maps to the bound model and has the expected 21.

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version VS 19 (16.7.7)

**Comment by pranavkm** [comment]
@statler this is likely a dup of #4825. Model binding as opposed to input formatting uses a wire format that is tied to how MVC functions. It's a bit difficult to map that to a swagger spec. Custom binders make it more complex since the author of the binder has to describe the wire format to MVC.

For APIs, we would generally recommend using JSON as the wire format to get a reasonable Swagger experience. We'll continue using the linked issue to track further work here.
