### ISSUE TITLE
dotnet watch run infinite loop not honoring exclude/remove config

### ISSUE THREAD

**Issue by johan-v-r** [dotnet/aspnetcore#27775]
### Describe the bug

2 issues that seem related:

1. Exclude/Remove watched files (configured in `csproj`) not honored.
1. Saving `scss` files in different folders cause the watch to rebuild infinitely.

It looks like the build creates the `css` file, which is then _watched_ and the cycle continues.

### To Reproduce

Repro project available here: https://github.com/johan-v-r/Blazor-Wasm-Watch-Repro

### Further technical details

VS 2019 16.8.0 with .NET 5.0.100

Able to replicate on 3 different Windows 10 machines, and just with CLI & notepad

**Comment by dwerner80** [comment]
Any updates on this? I'd love to use `dotnet watch` with component-scoped .scss files but this bug makes it impossible because I can't include `**/*/*.scss` files and exclude `**/*/*.css` files from the watcher.

I have a similar scenario as OP, but I'm using a `gulp` pipeline using `gulp-sass` that runs during build and generates .css files, and I don't want those generated files picked up by the watcher. Currently, they get picked up, so I end up in this same infinite loop.

**Comment by zaneclaes** [comment]
This is affecting more users than it may appear. The problem is not constrained to `*.scss` files. I use two entirely different code-gen tools for my GraphQL client and server, respectively. Both of them are sufficient to trigger this bug, i.e., cause `dotnet watch` to be unusable due to infinite restart loops.

**Comment by leolin16** [comment]
Please forgive me that I'm still a newbie to the dotnet world, but I've been able to reproduce this issue in several use cases here(currently found in one Blazor project & one MVC API project both via dotnet version `6.0.0-preview.3.21201.13`):
- when I wanted to generate pictures under **wwwroot** of a REST API project during `dotnet watch run`, `<Watch Exclude...` and `<Watch Remove...` in csproj didn't have effects and infinite build loop introduced.
-  when I wanted to use scss and put the scss-to-css generation task in the pre-build event,  the generated/re-generated `*.css.map` has caused `dotnet watch build` or `dotnet watch run` to fail into infinite building loop, although `<Watch Exclude...` and `<Watch Remove...` in csproj has been tried.

It seems that two **stackoverflow** links are related to this.
1. [https://stackoverflow.com/questions/65376352/how-to-exclude-certain-file-types-from-dotnet-watch-run](https://stackoverflow.com/questions/65376352/how-to-exclude-certain-file-types-from-dotnet-watch-run)
2. [https://stackoverflow.com/questions/65775540/net-watch-exclude-files-does-not-compile](https://stackoverflow.com/questions/65775540/net-watch-exclude-files-does-not-compile)

May I ask is there any further update regarding whether in the next milestone this issue will be fixed? or any possibility prediction for this issue to be fixed in the up-coming official release of dotnet 6 on November this year(2021) if not earlier?
Thanks team, if possible investigation/evaluation/consideration could be provided.

**Comment by Cowlephant** [comment]
This is happening with a simple implementation of `rollup.js` and makes `dotnet watch run` unusable as it keeps detecting the main.bundle.js file being output and an Exclude for its location in wwwroot doesn't work.

**Comment by McNerdius** [comment]
this did the job for me: https://github.com/dotnet/aspnetcore/issues/31141#issuecomment-805229841

**Comment by GravlLift** [comment]
None of the suggestions here helped me, but I was able to figure out what's causing my css files to be included despite my protests using `dotnet watch --list`. With a bit of experimenting, I was able to conclude that all of the files from the `None` build group were being watched, and I was able to finally ignore them for good with:

```xml
  <ItemGroup>
    <None Update="**/*.razor.css" Watch="false" />
  </ItemGroup>
```

Apparently dotnet includes a lot of groups of files in the watch by default.

**Comment by johan-v-r** [comment]
Thanks @GravlLift this did the trick! My config to watch `scss` and exclude `css` is now:

```xml
<ItemGroup>
	<!-- extends watching group to include *.scss files & remove *.css -->
	<Watch Include="**/*.scss" />
	<None Update="**/*.css" Watch="false" />		
</ItemGroup>
```
