### ISSUE TITLE
Add route constraint for strings, example: [HttpPost("{url:string}")]

### ISSUE THREAD

**Issue by Zerotask** [dotnet/aspnetcore#27847]
Add a route constraint for strings (regardless of its length).

**Docs:**
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#route-constraint-reference](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#route-constraint-reference)

### Is your feature request related to a problem? Please describe.
I want to define a parameter as a string with a variable length, for example `test123`. At the moment I have to use `minlength(1)`

**Example**
-  `[HttpPost("{url:minlength(1)}")] // Current; alternative regex`
-  `[HttpPost("{url:string}")] // Suggestion`

### Describe the solution you'd like
I would like to have a regular `string` type, since there are already other data types like `int`, `bool` or `float`. This would make the code more readable and would fit to the current options.

**Comment by javiercn** [comment]
@Zerotask thanks for contacting us.

Routing constraints are for disambiguating routes, not for validation. In this case it doesn't make sense to have a string constraint because any route parameter is already a string.

Constraints like `bool`, `int` or `float` only check that the value assigned to the parameter is a well formed integer, float or boolean value respectively, but don't do any type of conversion nor validation.

Since parameters are already strings, we don't think we need to add such constraint, since it wouldn't make any difference.
