### ISSUE TITLE
Blazor server side html markup issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27891]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-server-side-html-markup-issue/1238258?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio]
In Blazor component html is formatted like this (problem area is **bold**):
            <div class="row">
                @if (viewModel.SearchTswPro)
                {
                    **<p><h4>TSW Pro Next</h4></p>**
                    <TableWrapper @ref=TswProTableWrapper OnSelectRequested="TswProSelectedRow"
                        HeaderStyle="background-color: #cccf1;" Table="viewModel.TswProOwnerTable">
                    </TableWrapper>
                }

Assuming "viewModel.SearchTswPro" is True, in Chrome and Edge, the rendered output is this :
<div class="row">
                    **<p></p>**<h4>TSW Pro Next</h4>**<p></p>**
                    
<div style="bottom: 50%;overflow:auto;position: relative ;right: 0px ;top: 0px ">
<table> _(this is the rest of the <TableWrapper> component)_

I cannot get Blazor to render the HTML like this:

<p><h4>TSW Pro Next</4></p>

Even without the <h4> tags it renders like <p></p>TSW Pro Next<p></p>

I don't think the developers and web designers will be able to use the editor - which they'll have to use as the razor component has to be rendered to an intermediate. This is why every single web designer that I've ever met hated . ASPX files because they didn't have control over what rendered. 

I'm sure it's an easy fix and love how much control I currently have, but I have to convince others of Blazor's awesomeness.

I'm not sure if the problem was caused by my recent VS upgrade but it could have.

---
#### Feedback Bot on 10/30/2020, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Dana Reed solved on 10/29/2020, 11:21 AM, 0 votes: 

<p>[Workaround]<br>
Moved display of the &lt;h4&gt; tag from parent component to child  component as a [Parameter]. Displays the header properly</p>
<h3>TableWrapper.razor</h3>
<p>@using AuditSearch.Client.ViewModel</p>
<p>&lt;/h4&gt;<br>
<strong>&lt;p&gt;&lt;/p&gt;&lt;h4&gt;@TitleCaption&lt;/h4&gt;</strong></p>

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT, I investigated this a little. I can reproduce it but I am not sure if this is a bug or by design.

Here is what I found,
`<p><span>Hello</span></p>` renders as is

but 
`<p><div>Hello</div></p>` renders as
`<p></p><div>Hello</div><p></p>`.

Given that it is invalid to put block elements inside `p` element, I suspect this might be an intentional Blazor behavior.

@SteveSandersonMS, do you know if this is intentional?

**Comment by ajaybhargavb** [comment]
Note: This is not a parser issue because the generated document looks as expected,

```C#
 __builder.AddMarkupContent(4, "<p><div>Hello</div></p>");
```

**Comment by ajaybhargavb** [comment]
Actually I think this is just the browser parsing it differently because the source from "Inspect Element" and "View page source" look different.

Inspect Element:
![image](https://user-images.githubusercontent.com/1579269/99306525-2aeea900-280a-11eb-9f6d-b9509399d0d5.png)

View page source:
![image](https://user-images.githubusercontent.com/1579269/99306590-3cd04c00-280a-11eb-91c7-7ad6b29a501d.png)

Given this, I believe this is out of our control and by design. I'll wait for @SteveSandersonMS to confirm though.

**Comment by SteveSandersonMS** [comment]
Yes, this is just the way HTML works and is not about Blazor. Thanks for investigating, @ajaybhargavb!
