### ISSUE TITLE
Blazor/WASM - CSS changes do not apply without hard refresh (Ctrl+F5, etc.) 

### ISSUE THREAD

**Issue by tstuts** [dotnet/aspnetcore#28107]
### Describe the bug
If I change app.css, I have to hard refresh (Ctrl+F5, etc.) to see those changes

### To Reproduce
I just created a brand new .NET 5 WASM app with this error. Will submit repro if necessary.

### Exceptions (if any)
None

### Further technical details
.NET 5

**Comment by tstuts** [comment]
I found https://github.com/dotnet/aspnetcore/issues/23505, which is what gave the suggested hard refresh, but this cannot be an actual solution. I very gladly submit my many years of engineering experience to find a true solution. With some cultural/platform guidance, I would be more than happy to help in finding a permanent solution.

**Comment by javiercn** [comment]
@tstuts thanks for contacting us.

This is something that should work, we're not sure why it's not working in your case. Could you provide a minimal repro project that showcases the issue and detailed repro steps?

It would also be helpful if you capture the network traffic in the Dev tools as a har file so that we can inspect the headers, but I would start by checking why the browser is not issuing a second request.

**Comment by tstuts** [comment]
@javiercn, thanks for your attention. I've been trying to create a reliable repro, but unfortunately I'm getting inconsistent results. I thought I had narrowed it down, but now it's happening sometimes when I think it shouldn't and it's not happening when I think it should. I'll keep trying.
