### ISSUE TITLE
Add DisplayName support for InputText and InputTextArea

### ISSUE THREAD

**Issue by ErikApption** [dotnet/aspnetcore#28118]
### Is your feature request related to a problem? Please describe.
Validation errors for InputText and InputTextArea should support DisplayName to customize required field validation messages.

### Describe the solution you'd like
DisplayName for InputDate<TValue>,InputNumber<TValue>,InputSelect<TValue> solves this issue but it is not applicable to InputText or InputTextArea

### Additional context
This is necessary for localization and other cases were variables do not follow a friendly naming convention.

**Comment by javiercn** [comment]
@ErikApption thanks for contacting us.

We believe the validation errors come from data annotations not from the Blazor form components, so its up to data annotations whether the display name is honored or not.

Could you provide a GH repo with a repro project that we can use to better understand what problem you seem to be facing?

**Comment by ErikApption** [comment]
Here we go https://github.com/ErikApption/BlazorFormRequiredBug
This sample shows that DisplayName is not supported by the InputText and Required annotation. Btw, I'm happy to dig more and look into the source code.

**Comment by SteveSandersonMS** [comment]
The `Required` attribute causes DataAnnotations to generate validation error messages when the field is empty. The error message doesn't come from Blazor in this case, so attributes passed to `<InputText>` don't have any way of influencing the error messages that DataAnnotations produces.

The intended way to influence the error messages produces by DataAnnotations is to use DataAnnotations attributes on your model properties. For example:

```cs
    [Required, Display(Name = "e-mail address")]
    public string UserEmail { get; set; }
```

or

```cs
    [Required(ErrorMessage = "Don't forget to enter your e-mail address!")]
    public string UserEmail { get; set; }
```

The reason that `InputNumber` has a separate `DisplayName` attribute is because, unlike `InputText`, it has to deal with parsing the user's entered value *before* it can even populate the .NET models, and hence before DataAnnotations can see it. When the parsing fails, because the user entered a string that doesn't represent a number, Blazor itself needs to generate a valdiation error message, which is why we've made that controllable.

I know it's a bit confusing that there are two different stages of validation like that (one before parsing, one after parsing) but it's an unavoidable consequence of having a true strongly typed runtime. Hopefully this explains why it's relevant for InputNumber to do some extra validation on top of what InputText would do.

**Comment by ErikApption** [comment]
@SteveSandersonMS Thanks - yes did not realize the Data Annotation were handled by a different stack. My main reason for using the DisplayName was to handle localization. Would be nice to have something better than the resx files that can integrate across all components. I see there is as option to localize the data annotations as well but need to make sure it can work with my 3rd party localization library. Question - is there any way to manually handle the validation only for the required attributes using the validation overriding?
