### ISSUE TITLE
SignalR Stream is will throw when combined with ToObservable from IX.net, and the stream completes.

### ISSUE THREAD

**Issue by arontsang** [dotnet/aspnetcore#28241]
```
public class FooHub : Hub
{
    public IAsyncEnumerable<int> Foo()
    {
        return AsyncEnumerable.Empty<int>();
    }
}

public static class Program
{
    public async Task Main()
    {
         await new HubConnectionBuilder()
              .WithUrl(....)
             .Build()
             .StreamAsync(nameof(FooHub.Foo))
             .ToObservable()
            .Do(x => Console.WriteLine(x))
            .ToTask();
    }
}

```
This will throw an exception of CancellationTokenSource ObjectDisposedException.

**Comment by BrennanConroy** [comment]
Is there a typo in that code or have you not started the connection yet?

**Comment by arontsang** [comment]
Typo. The exceptions happens on OnComplete, as IX tries to dispose the
AsyncEnumerable after the AsyncEnumerable has disposed itself already.

**Comment by BrennanConroy** [comment]
Can you provide a more complete example please? Yours doesn't compile as the operators don't mix like you posted them (unless there is some extension somewhere that you need to add).

Also, a stack trace of the exception is generally useful to provide.

**Comment by arontsang** [comment]
See https://github.com/arontsang/signalr-bug

**Comment by BrennanConroy** [comment]
Minimal repro without IX.net
```c#
var asyncEnumerable = connection.StreamAsyncCore<int>("Stream", new object[] { streamTo });
using var cts = new CancellationTokenSource();
await using var e = asyncEnumerable.GetAsyncEnumerator(cts.Token);
while (await e.MoveNextAsync())
{
}
cts.Cancel();
```

The issue is that we dispose an internal cts when the server sends a stream completion
https://github.com/dotnet/aspnetcore/blob/b4f8e0f587c064b67b99e7ee5f1562fc61ba9242/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L579

Then, if the user cancels a token passed into `GetAsyncEnumerator` before the enumerator is disposed we will try to cancel the disposed cts from earlier https://github.com/dotnet/aspnetcore/blob/b4f8e0f587c064b67b99e7ee5f1562fc61ba9242/src/SignalR/common/Shared/AsyncEnumerableAdapters.cs#L69
