### ISSUE TITLE
.NET Core SDK 3.1.111 ASP.NET Core targeting pack files are newer in .exe installer than .zip package

### ISSUE THREAD

**Issue by dagood** [dotnet/aspnetcore#28331]
> [@NicoleWang001 <https://github.com/dotnet/runtime/issues/3756#issuecomment-665550211>]
> With SDK 3.1.107 and 3.1.401, ref files (files on .\packs\Microsoft.AspNetCore.App.Ref\3.1.3\ref\netcoreapp3.1\) on .exe installer is more recent than .zip installer.
> ![image](https://user-images.githubusercontent.com/1578239/88782816-9ad81580-d1c0-11ea-9991-3d1039096a5c.png)

> [@vdanche <https://github.com/dotnet/runtime/issues/3756#issuecomment-733582948>]
> [...] Still repro on SDK 3.1.111, ref files (files on .\packs\microsoft.aspnetcore.app.ref\3.1.10\ref\netcoreapp3.1) on .exe installer is more recent than .zip installer.
> ![image](https://user-images.githubusercontent.com/65637796/100207518-a3f4ab80-2f42-11eb-9054-221099c8e894.png)

---

Transfered from from https://github.com/dotnet/runtime/issues/3756.

**Comment by marcpopMSFT** [comment]
It appears the contents of the msi and nupkg for the targeting pack are different which they shouldn't be.

**Comment by javiercn** [comment]
@dagood thanks for the report.

@dotnet/aspnet-build do you have any thoughts?

**Comment by wtgodbe** [comment]
Huh, interesting - I'll take a look

**Comment by wtgodbe** [comment]
The reason, at least for us, is that the .nupkg input files are from the various project output directories, while the .zip input files are from a centralized location where we copy all of those project output files to create a layout. So, it's the same set of files, but the ones in the .zip have been copied one extra time.

**Comment by wtgodbe** [comment]
@dagood does this still sound like an issue, given the above?

**Comment by dagood** [comment]
I'm not sure what the issue is, I just moved it here from a thread in dotnet/runtime. 😄
@NicoleWang001 and @vdanche may be able to provide more context.

**Comment by vdanche** [comment]
@dagood The issue is that .NET SDK installers have different contents as the zip archives, e.g. With SDK 3.1.405, ref files (files on .\packs\Microsoft.AspNetCore.App.Ref\3.1.10\ref\netcoreapp3.1) on .zip installer is more recent than .exe installer.

Repro steps:
1. Installing the .NET Core SDK 3.1.405(Use release/3.1.4XX branch from https://github.com/dotnet/core-sdk)
2. Downloading and extracting the zip archive of the .NET Core SDK
3. Running a folder diff on the extracted SDK and the install folder
Tool WinDiff : \bvtsrv2\Team\v-yunwei\Docshare\windiff

Expected Result:
The installers include identical contents as the zip archives

Actual Result:
.NET SDK installers have different contents as the zip archives, ref files (files on .\packs\Microsoft.AspNetCore.App.Ref\3.1.10\ref\netcoreapp3.1) on .zip installer is more recent than .exe installer.
![image](https://user-images.githubusercontent.com/65637796/101458884-7102dc80-3972-11eb-8f51-a3d6199345e1.png)
![image](https://user-images.githubusercontent.com/65637796/101459601-68f76c80-3973-11eb-8ef4-1d98e60c23c8.png)

**Comment by wtgodbe** [comment]
This is not an issue - the files are the same, the reason that the last-modified stamp is different is because the files in the .zip were copied from their original location to a layout folder. @NicoleWang001 was this caught by a CTI validation scenario? If so, can we modify that validation scenario so that we check for FileVersion rather than for the last modified date?

**Comment by vdanche** [comment]
@wtgodbe Got it! We'll make note in our test scenario. Thanks much!
