### ISSUE TITLE
RazorTagHelper - DOTNET_HOST_PATH is not set

### ISSUE THREAD

**Issue by celoko-cintra** [dotnet/aspnetcore#28333]
After updating VS 2019 16.8.0  I'm facing this error on compilation on any project:

**Web C# .net core 2.2**

Erro	MSB4018	Falha inesperada da tarefa "RazorTagHelper".
System.InvalidOperationException: DOTNET_HOST_PATH is not set
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.get_DotNetPath()
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.GenerateFullPathToTool()
   em Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
   em Microsoft.Build.Utilities.ToolTask.Execute()
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.Execute()
   em Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   em Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	QRPlus	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	79	

Anyone knows whats is going on?

**Comment by hungxp** [comment]
> I did 3 steps to get it to build AND to get the ( ~/ ) variable to work.
> 
> 1. Open cmd and write this: **setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"**
> 2. Open **C:\Program Files\dotnet\sdk** in here delete the folder: **NuGetFallbackFolder**
> 3. Restart your pc!

Thanks!

**Comment by psnehi** [comment]
> Added the following environment variable to my user environment to make it build again:
> DOTNET_HOST_PATH
> %ProgramFiles%\dotnet\dotnet.exe

My issue resolved. Thanks.

**Comment by Ahad726** [comment]
It worked for me after I added this Nuget package:
Microsoft.NET.Sdk.Razor
Since I added the Net.SDK.Razor package, it builds successfully. I had also added Microsoft.AspNetCore.Razor.Design.

**Comment by ship-store** [comment]
> Adding this line in project file works or install razor package:
> `<PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0"></PackageReference>`
> 
> **reference:**
> 
> [https://stackoverflow.com/questions/64827539/msb4018the-razorgenerate-task-failed-unexpectedly](url)

Worked like a Charm !!

**Comment by pranavkm** [comment]
Thank you for the issue report. We inadvertently broke support for ASP.NET Core 2.2 as part of the 5.0 SDK which is why you're seeing this error. We're addressing this in 5.0.2 which is set to be released early next month. In the meanwhile there are a few workaround:

a) Use a global.json and pin the .NET SDK to a 3.1 version. Here are samples for creating and modifying a global.json file: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#examples

b) Some people have had success referencing the 2.2 Razor SDK from their project:

```xml
<PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0" />
```

c) You could consider setting an environment variable for DOTNET_HOST_PATH globally. The value is likely `%ProgramFiles%\dotnet\dotnet.exe`

I would like to add that .NET Core 2.2 has been [out of support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for some time now and is no longer receiving any updates (including security fixes). You should consider migrating to a supported releases (2.1, 3.1 or 5.0) to continue to be supported.

**Comment by uandersonmbc** [comment]
This was resolved in macOS Catalina. Version 10.15.7

For those who have not yet managed to define the environment variable, enter this site that will help a lot. To resolve the `DOTNET_HOST_PATH is not set` problem. After hours and hours looking for solutions, I found this site.

http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/

**Comment by oshinyil** [comment]
> I got the same issue and had to manually set the `DOTNET_HOST_PATH`
> environment variable as described by @olivermue above
> 
> ```
> setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"
> ```

This works for me. Thanks a lot!

**Comment by ankitmori14** [comment]
> Added the following environment variable to my user environment to make it build again:
> DOTNET_HOST_PATH
> %ProgramFiles%\dotnet\dotnet.exe

Working fine for me
