### ISSUE TITLE
Using HttpClientFactory without dependency injection

### ISSUE THREAD

**Issue by poke** [dotnet/aspnetcore#28385]
Is there any way to consume the `HttpClientFactory` without using dependency injection, or more precisely without using M.E.DI?

I am creating a client library for which I want to make use of HttpClientFactory but I am going to use this library also in a legacy project that does not not have a M.E.DI-compatible DI.

Ideally, I would just new up a `DefaultHttpClientFactory` and consume that directly but since the factory itself is internal, this is not possible.

Why is the `HttpClientFactory` internal and is there _any_ way to consume it explicitly without using DI?

**Comment by bugproof** [comment]
`HttpClient` is the most confusing class of all. I still don't know if I'm using it correctly in my console apps. Every time when I have to deal with it I have 1000 voices in my head screaming I could be doing something wrong. I can't count the times I googled how to correctly use it. It's impossible to learn. I guess the safest option now is just adding DI to your console apps and be done with it. I'm not even sure what should I derive from anymore if I want to make my own HttpClientHandler correctly.

**Comment by yanxiaodi** [comment]
This issue should not be closed. I don't see the proper solution after 2 years.

**Comment by silkfire** [comment]
There's a great library that solves this problem, also available on NuGet: https://github.com/myarichuk/Simple.HttpClientFactory

**Comment by Gladskih** [comment]
That WebRequest-HttpRequest / HttpClient problem makes me think I've chosen wrong platform to learn and work with 10 years ago and all my life gone wrong.

**Comment by Jehoel** [comment]
@rynowak please re-open this issue, @msftbot closed this when it shouldn't have.

**Comment by mary-perret-1986** [comment]
@bugproof 
@yanxiaodi 
@silkfire 
@Gladskih 
@Jehoel 

According to the official Microsoft Docs, [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#alternatives-to-ihttpclientfactory): 

> # Alternatives to IHttpClientFactory
> Using `IHttpClientFactory` in a DI-enabled app avoids:
> - Resource exhaustion problems by pooling `HttpMessageHandler` instances.
> - Stale DNS problems by cycling `HttpMessageHandler` instances at regular intervals.
> 
> There are alternative ways to solve the preceding problems using a long-lived [SocketsHttpHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler) instance.
> - Create an instance of `SocketsHttpHandler `when the app starts and use it for the life of the app.
> - Configure [PooledConnectionLifetime](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime#System_Net_Http_SocketsHttpHandler_PooledConnectionLifetime) to an appropriate value based on DNS refresh times.
> - Create `HttpClient` instances using `new HttpClient(handler, disposeHandler: false)` as needed.
> 
> The preceding approaches solve the resource management problems that `IHttpClientFactory` solves in a similar way.
> - The `SocketsHttpHandler` shares connections across `HttpClient` instances. This sharing prevents socket exhaustion.
> - The `SocketsHttpHandler` cycles connections according to `PooledConnectionLifetime` to avoid stale DNS problems.

You can use `HttpClient` without relying on HttpClientFactory and DI, by using `IHttpClientFactory`:

```csharp
// Used throughout your application (i.e. app lifetime)
using var httpSocketHandler = new SocketsHttpHandler();
using var httpClient = new HttpClient(httpSocketHandler);
using var response = await httpClient.GetAsync("https://www.google.com");
```

**Comment by ericsampson** [comment]
@mary-perret-1986 that code snippet would need to be tweaked slightly to achieve the stated goal.

**Comment by mary-perret-1986** [comment]
> @mary-perret-1986 that code snippet would need to be tweaked slightly to achieve the stated goal.

@ericsampson Would you mind elaborating on this?

**Comment by Jehoel** [comment]
@mary-perret-1986 `SocketsHttpHandler` is not available in .NET Standard. If we're making redistributable libraries that use `HttpClient` then that makes things difficult - or if we're targeting .NET Framework. What solution would you suggest in that case?

**Comment by silkfire** [comment]
@mary-perret-1986 Doesn't it make more sense to make the default empty constructor of `SocketsHttpHandler` either private or internal and the only way to access the class for consumers be through a static `SocketsHttpHandler.Instance`? This would make sure that only one instance is ever created through the lifetime of your app.

**Comment by bugproof** [comment]
> > @mary-perret-1986 that code snippet would need to be tweaked slightly to achieve the stated goal.
> 
> @ericsampson Would you mind elaborating on this?

See? There's always something about `HttpClient` that will surprise you. You can't just use it with confidence. There should be only 1 instance of `HttpClient` in your app but then what's the point of `BaseAddress`?. It's badly designed to be used as a singleton. `HttpClientFactory` solves these problems for you but it only works with DI because it's `internal`. It took me a while to realize that I wasn't using it correctly: https://github.com/bugproof/PinSharper/blob/master/PinSharper/PinterestAPI.cs#L25

Ideally, the constructor of `HttpClient` should be `internal` or `private` so people will never ever instantiate it directly but through `HttpClientFactory` to promote good design.

**Comment by Jehoel** [comment]
@bugproof 

> There should be only 1 instance of `HttpClient` in your app but then what's the point of BaseAddress? 

No-one is saying that `HttpClient` should be an _application-wide_ singleton. I think you're misinterpreting @rynowak's advice (repeated below; the bold-for-relevance is mine)

> * If you are on .NET Core - you should **use a single `HttpClient` directly** and set `SocketsHttpHandler.PooledConnectionTimeout` here to an appropriate value.  
> * If you are on .NET Framework - you should **use a single `HttpClient`** and use `ServicePoint` to configure the similar settings.

My understanding is Ryan meant _each separate consumer_ of a `HttpClient` should have _its own_ single instance - not that there should be an application-wide singleton. This makes sense given that `HttpClient` is mutable, and _generally speaking_ instances of mutable classes should not be shared by unrelated consumers.

**Comment by silkfire** [comment]
@Jehoel This [article ](https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core) mentions that `SocketsHttpHandler` handles connection cycling and lifetime management automatically just like `DefaultHttpClientFactory` does, but having peeked at the source code I can't see anything static residing on the class itself. So two instances wouldn't be sharing data between each other.

Sigh, I just wish Microsoft could make the `DefaultHttpClientFactory` API public.

**Comment by davidfowl** [comment]
I don't understand why you think you need it. Are you managing different settings per handler? If not then you don't need it.

**Comment by silkfire** [comment]
I would believe that creating multiple HttpClients - one for every consuming service - would each use their own instance of  `SocketsHttpHandler`, possibly leading to socket exhaustion. They would use their own respective pool, if I've understood this correctly. What I'm trying to say is I don't want apps to always have keep track of a singleton `SocketsHttpHandler`.

**Comment by davidfowl** [comment]
Then use the same singleton instance?

**Comment by silkfire** [comment]
If this is how how `SocketsHttpHandler` is to be used I'd rather it be a static instance than a singleton...

**Comment by davidfowl** [comment]
Sure store it in your own static. There are obviously much more advanced use cases but the default should be a single instance used by your app until further notice

**Comment by JohnNilsson** [comment]
Just storing a singleton SocketsHttpHandler would mean a shared cookie container by default no? 

Which is the kind of foot gun that leads to security issues when sessions are shared between clients unexpectedly.

**Comment by davidfowl** [comment]
I believe cookies is off by default, so you would be opting into that footgun. Also I hope your API are using bearer tokens (though that's a separate discussion).

**Comment by silkfire** [comment]
So cookies are shared between different HttpClients if they use the same message handler?

**Comment by davidfowl** [comment]
The cookie container is per handler instance. Like I said before, if you need to vary settings or state per handler then you need to manage multiple http clients. Otherwise use a single one

**Comment by ericsampson** [comment]
> 
> 
> > @mary-perret-1986 that code snippet would need to be tweaked slightly to achieve the stated goal.
> 
> @ericsampson Would you mind elaborating on this?

The `SocketsHttpHandler` has a default connection lifetime of [infinite](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime?view=net-5.0#property-value), so you need to specify an explicit shorter lifetime if you want to achieve the goals that you mentioned of respecting callee DNS changes. This is mentioned in the text that you quoted : )
This also might be useful for you @silkfire , because it's only handled 'automatically' by `SocketsHttpHandler` if you configure it correctly.

The default value for this param can't be changed unfortunately, due to backwards compatiblity requirements.

```
// Used throughout your application (i.e. app lifetime)
using var httpSocketHandler = new **SocketsHttpHandler(){ **PooledConnectionLifetime = TimeSpan.FromMinutes(3) }**;
using var httpClient = new HttpClient(httpSocketHandler);
using var response = await httpClient.GetAsync(@"https://www.google.com");
```

**Comment by silkfire** [comment]
> The cookie container is per handler instance. Like I said before, if you need to vary settings or state per handler then you need to manage multiple http clients. Otherwise use a single one

And if I have varying settings on the handler? Would having multiple `SocketsHttpHandler` instances prevent me from gaining the benefits of any 'global' connection lifetime management then I presume?

**Comment by davidfowl** [comment]
> @davidfowl And if I have varying settings on the handler? Would having multiple SocketsHttpHandler instances prevent me from gaining the benefits of any 'global' connection lifetime management then I presume?

The connection management is coupled to the `SocketsHttpHandler` instance, so many instances means you'll end up with connection management spread across each instance. I think there are only a couple of settings that would force the creation of multiple handlers (that and a couple of scenarios). I suspect this is a more the advanced use-case.

**Comment by Jehoel** [comment]
So if I understand things correctly...

## Example 1:  `using`-wrapped short-lived `HttpClient` from default constructor for a single request:

```
async Task MakeSingleRequestAsync()
{
    using( HttpClient httpClient = new HttpClient() )
    {
        using( HttpResponseMessage response = await httpClient.GetAsync( "https://www.example.com" ) )
        {
            // Do stuff
        }
    }
}
```

###  Example scenarios:
  * Probably _everyone_ that has ever used `HttpClient` before reading _that_ 2016 blog article.

### API Advantages and Disadvantages:
* Simple and straightforward.
* The fact that `HttpClient` is `IDisposable` is a very strong hint that `using()` should be used.
* You can easily mutate the `HttpClient`, such as setting `DefaultRequestHeaders`.

### Platform-specific guidance:

* .NET Framework: **Don't do this** - you'll have Socket Exhaustion.
  * `HttpClient.Dispose()` will dispose its private `HttpClientHandler`. This is the original issue described in [You're using HttpClient wrong](https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).
* * .NET Core 5: **Don't do this** - you'll have Socket Exhaustion.
  * `HttpClient.Dispose()` will dispose its private `HttpClientHandler`, which wraps its own private instance of `SocketsHttpHandler`, which owns its own `HttpConnectionPoolManager`, which is not shared between `HttpClient` instances.
* .NET Standard: **Don't do this** - you don't know what the host platform will do.

## Example 2:  Static or singleton long-life'd instance of `HttpClient` from default constructor, for many requests:

```
public static class Program
{
    private static readonly HttpClient httpClient = new HttpClient();
    
    public static async Task Main( String[] args )
    {
        using( HttpResponseMessage response = await httpClient.GetAsync( "https://www.example.com" ) )
        {
            // Do stuff
        }

        using( HttpResponseMessage response = await httpClient.GetAsync( "https://www.github.com" ) )
        {
            // Do stuff
        }
    }
}
```

### API Advantages and Disadvantages:
* As the `HttpClient` is `static` it cannot (or rather: _shouldn't_) be mutated for any request-specific reason.
  * So _don't_ set `DefaultRequestHeaders`, for example.
  * In order to customize requests (cookies, etc!) you need to manually create your own `HttpRequestMessage` instances: you won't be able to use `GetAsync` or `PostAsync`. This is bad for usability!

### Example scenarios:
  * Windows Service that makes periodic HTTP requests.
  * Long-lived background service object in ASP.NET 4.x via `System.Web.Hosting.HostingEnvironment.RegisterObject( IRegisteredObject )`.
  * Long-lived infinite-loop method invoked via `System.Web.Hosting.HostingEnvironment.QueueBackgroundWorkItem)`.
  * `IHostedService` in ASP.NET Core or .NET Core.

### Platform-specific guidance:
* .NET Framework: **Don't do this without the `ServicePoint` workaround** - your cached DNS results will go stale.
  * http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html
  * The workaround is to run this code below **but for each distinct combination** of `Uri.Scheme, Uri.DnsSafeHost, Uri.Port` that you make requests for - but _you only need to do this once_.
  
    ```
    ServicePointManager.FindServicePoint( httpRequestMessage.RequestUri ).ConnectionLeaseTimeout = // Typically 1 minute. YMMV.
    ```

* .NET Core 1.0 through 2.0: **Don't do this** - your cached DNS results will go stale.
  * Unfortunately `ServicePointManager` does not exist in .NET Core 1.0 through 2.1:
    * https://github.com/dotnet/runtime/issues/18348 "Singleton HttpClient doesn't respect DNS changes"
  * The only real solution is to update to .NET Core 2.1 or later so you can use `SocketsHttpHandler`.

* .NET Core 2.1, 3.0, 3.1, 5.0: **This is _fine_**.
  * ...assuming you didn't force-enable `WinHttpHandler` then `HttpClient` will use `SocketsHttpHandler` (via `HttpClientHandler._underlyingHandler`).

* .NET Standard: **Don't do this** - you don't know what the host platform will do.

## Example 3:  Static or singleton long-life'd instance of `HttpClientHandler` or `SocketsHttpHandler`, for many requests, with a short-lived `HttpClient` with `disposeHandler: false`:

```
public static class Program
{
    private static readonly HttpClientHandler _httpClientHandler = CreateHttpClientHandler();
    private static readonly SocketsHttpHandler _httpClientHandler = CreateSocketsHttpHandler();
    
    public static async Task Main( String[] args )
    {
        using( HttpClient httpClient = new HttpClient( _httpClientHandler, disposeHandler: false ) )
        {
            httpClient.DefaultRequestHeaders.
            using( HttpResponseMessage response = await httpClient.GetAsync( "https://www.example.com" ) )
            {
                // Do stuff
            }
        }

        using( HttpClient httpClient = new HttpClient( _httpClientHandler, disposeHandler: false ) )
        using( HttpResponseMessage response = await httpClient.GetAsync( "https://www.github.com" ) )
        {
            // Do stuff
        }
    }
}
```

### API Advantages and Disadvantages:
* As the `HttpClientHandler` is exposed we can set `CookieContainer`, `AutomaticDecompression`, and `AllowAutoRedirect` which we normally cannot do.
    * But when doing so we have to be careful not to share the `HttpClientHandler`.
        * But if we don't share the `HttpClientHandler` we'll end up creating excessive connections and may encounter socket exhaustion, even in .NET Core 5 because `SocketsHttpHandler` doesn't share its connection pool.
* This has the advantage of letting you mutate `HttpClient` provided the `HttpClient` is not shared by other types or methods that have preconditions on the contents of `DefaultRequestHeaders` etc.

### Example scenarios:
* Same as Example 2.

### Platform-specific guidance:
* Same as Example 2.

## Example 4:  You're creating a redistributable web-service client library class:

```
public class SilkRoadClient : ISilkRoadClient
{
    // TODO: Should this class own its own HttpClientHandler?
    // TODO: Should this class own its own SocketsHttpHandler? What if it's .NET Framework or .NET Standard where it's unavailable?
    // TODO: Should this class own its own HttpClient? Who should be responsible for creating it? Should it be mutable?
    // TODO: Should this type be disposable if it owns/implements any of the above?
    // TODO: What should the lifetime semantics of this type be? Transient? Long-lived? "Medium-lived" (e.g. end-user session length)? What if it's a singleton?

    public SilkRoadClient( /* what goes here? */ )
    {

    }

    public async Task<SubstancesInvoice> BuyMoreAdderallOnTheDarkWebSoICanPutUpWithEverIncreasingHttpClientRevelationsAsync( Int32 qty, Int32 strengthMG, String bitcoinPrivateKey )
    {
        // * Should this method create its own HttpClient?
        // * Should this method dispose its own HttpClient?
        // 
    }
}
```

Welcome to _heck_. Figuring out how to handle `HttpClient` when you don't own the entrypoint or host program that will run your code is very difficult.

I've added comments to the above code that point out all of the unanswered questions I still have regarding using `HttpClient` in a redistributable library where `IHttpClientFactory` isn't available - this is the current _void_ in the documentation and guidance for `HttpClient`.

I note that the simplest approach is still to just take a dependency on `IHttpClientFactory` - but that comes with the _massive cost_ of getting complaints from your users who now have no way to quickly and easily fire-up an instance of your client class.

**Comment by ericsampson** [comment]
@Jehoel, FWIW if you want to see how someone has handled these issues, you can take a look at the Azure SDK. IIRC they've dealt with this.

I'm definitely not saying that it shouldn't be easier OOTB, but at least as a reference…
