### ISSUE TITLE
RZ9997	Unrecognized attribute 'Roles' on child content element 'Authorized'.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28491]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/RZ9997	Unrecognized-attribute-Roles-on/1275880)._

---
[severity:I'm unable to use this version]
For no apparent reason, I started getting this error and it won't go away.  I am using a standard <AuthorizeView Roles="Administrator"> construct.  It worked fine earlier today.

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ9997	Unrecognized attribute 'Roles' on child content element 'Authorized'.	BlazorApp	C:\Users\super\source\repos\AuthorizationDemo\BlazorApp\RAZORGENERATE	1

---
#### Feedback Bot on 12/2/2020, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
