### ISSUE TITLE
@Forelse directive Blazor

### ISSUE THREAD

**Issue by nijenhof** [dotnet/aspnetcore#28507]
### The issue
Whenever I'm loading a list in Blazor, I need to add a null check if the list is not null and check if the item is count is greater than 0. If I would like to display a placeholder for an empty list, I would need to do an additional check on the item count.

### Describe the solution you'd like
When I did some things with Laravel I noticed they have a solution for that: the forelse. Would it be possible to implement something like this? So you can do:
```
@forelse(var item in list)
{
    <p>item.property</p>
}
else
{
    <p>This list is empty</p>
}
```

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us!

It's a cool idea, but would need to be implemented in C# itself rather than Blazor. This is because Razor syntax is purely using the C# language and we neither add to it nor remove from it, we don't even have the ability to do so, since the compiler literally is the C# compiler.

If you're interested in suggesting a C# language feature, the repo is at https://github.com/dotnet/csharplang.
