### ISSUE TITLE
Navigation Lifecycle events

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/aspnetcore#28527]
## Summary

We would like to implement a Navigation lifecycle event, that should be called BEFORE navigation is performed, with the ability to cancel that navigation.

## Motivation and goals

The main reason for this lifecycle event is that currently, we have no way of canceling a navigation event, which is useful if for example the user has made some changes in a form, but navigates away from that page before those changes could be stored.

For reference, some work has already been done in https://github.com/dotnet/aspnetcore/pull/24417 , 
One of the problems we face in that PR is that we want the event to be asynchronous. So using an EventHandler is out of the question. Also the location on where to place this event (Navigationmanager, Router) is under discussion.

## In scope

Canceling navigation Lifecycle events.

## Risks / unknowns

The performance issue I can think of is that every navigation event (clicking a href for example) in Serverside Blazor would incur an additional client/server callback, even when no one is listening. This can be mitigated by only calling the lifecycle event when a listener is actually supplied. (This has been addressed in the PR)

## Examples

```cs

//Set to true when Data has been modified that has not yet been stored
bool PageIsDirty { get; set;}

//Function that is called when a navigation event occurs (returns true when navigation should be canceled)
ValueTask<bool> LocationChanging(string uri, NavigationOptions options)
{
  if (PageIsDirty)
  {
    var result = await ShowDialog($"Changes have not been saved. Are you sure you want to navigate to:{uri}", Buttons.YesNo);
    return result != Button.Yes; 
  }
  return false;
}
```

**Comment by MariovanZeist** [comment]
@captainsafia I hope you still want to co-author this design proposal with me. Feel free to modify it.

**Comment by ShaunCurtis** [comment]
Hi,

I know I'm one of many (countless many), but my approach to this has changed since  I first registered an interest a year ago.  At that point i thought this was a must, but as my "knowledge" increased I realised there are more more than x ways to skin a cat (x++ to play on a pun). I no  longer use my "alternative" router to get around the problem.  See [Inline Dialog](https://www.codeproject.com/script/Articles/ArticleVersion.aspx?waid=4247448&aid=5297432) for one of  my current solutions.

So maybe the solution is "Education" rather than what is proposed. Would help in any shape or form if asked - I'm bored silly in COVID lockdown in the UK.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @MariovanZeist! Closing this in favor of https://github.com/dotnet/aspnetcore/issues/14962 until there is capacity to flesh out the design for this. We'll use this issue and the PR as a basis for that then.
