### ISSUE TITLE
Razor text editor code highlight

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28553]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Razor-text-editor-code-highlight/1252869?preview=true)._

---
Hi Guys,

First off, thank you for the great work you have been doing with VS in supporting Blazor. 

Was wondering why razor linter on the text editor highlights code section? Personally, it would be great if they just looked like regular code rather than highlighting them with a light gray color. Highlighting code on a razor page makes it feel like they don't belong there.

---
### Original Comments
(no comments)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
