### ISSUE TITLE
Blazor Wasm Azure AppService ASPNETCORE_ENVIRONMENT ignored

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#28573]
Using the latest .Net 5.0.1 and Blazor Wasm in Azure AppService, the ASPNETCORE_ENVIRONMENT variable is not honored.
https://github.com/dotnet/aspnetcore/issues/25152
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0

So, we are trying to place a static environmentConfig.json file in each slot that defines the Environment:  (Development, Staging or Production if non existent).

This works so far, but how do we change the WebAssmblyHostBuilder.Environment in Program.Main.cs?

**Comment by roysurles** [comment]
- Yes.  The 3 files (appSettings.json, appSettings.Staging.json & appSettings.Development.json) exist in the development slot.
- Yes.  ASPNETCORE_ENVIRONMENT is set to Development in the development slot
- No.  I do not see a response header Blazor-Environment for blazor.boot.json.
- aooSettings.json is requested by the browser instead of appSettings.Development.json

**Comment by mkArtakMSFT** [comment]
Thanks for the details. @roysurles can you try to change the casing of the `appSettings.json` files to all be lowercase and see whether that fixes the issue?

**Comment by roysurles** [comment]
All 3 appsettings files are already lowercase.

**Comment by joer33304** [comment]
I have the same issue. This WORKED in the prior version and after upgrading to 5 it does not anymore .
I do have the header "blazor-environment: Development".

**Comment by aicreed** [comment]
Anyone have any updates on this? I have the same issue, I however do not have the ""blazor-environment" header.

**Comment by pvervaet** [comment]
Seems to me this is a major oversight.
Right now there is no way to specify the environment in a release pipeline (build once, deploy many)...
Any update on this?

**Comment by ViRuSTriNiTy** [comment]
This needs to be fixed asap as all serious apps are developed in different stages / environments!

**Comment by KolyaNET** [comment]
I have the same issue

**Comment by Krangth** [comment]
i can't believe this isn't fixed yet.

**Comment by PerBlomqvist** [comment]
Need this as well for deployment to QA and Production via Azure DevOps pipeline to Azure App Service.

**Comment by joer33304** [comment]
There is an easy we got get this working. If you host the assebly in a server app, all what is need is to set the ASPNETCORE_ENVIRONMENT to the environment. In azure you can add this to the app settings.

For plain webassebly, the ASPNETCORE_ENVIRONMENT  is in the launchsettngs.json file. Add that file and the environemtn and it will pick up the correct one

**Comment by Tailslide** [comment]
Is there a workaround for webassemblies?? The solution proposed by @joer33304 is a little light on details.  I'd like to be able to swap my app service slots between staging and production and this kind of makes that impossible.

**Comment by joer33304** [comment]
> Is there a workaround for webassemblies?? The solution proposed by @joer33304 is a little light on details. I'd like to be able to swap my app service slots between staging and production and this kind of makes that impossible.

I explained that in my post. For webassemblies NOT hosted by an server app, you set the ASPNETCORE_ENVIRONMENT in the launchsettngs.json file. So just deploy different launchsettngs.json files per environment

**Comment by Tailslide** [comment]
@joer33304 do you have an example of this?

**Comment by StigHausberg** [comment]
CHiming in here, this is quite important, building an WASM with OIDC login needs different appsettings environments in the client. Have not found a working workaround as of yet

**Comment by Tailslide** [comment]
FWIW, I hacked something temporary together by checking the domain to see if I was running in staging or production.  It at least let me promote directly between the two systems without having to republish.  Would still like a better workaround though.

**Comment by buzzluck68** [comment]
From the multiple issues opened about this problem that I have read, the only solutions seem to be focused around manual deployment from VS to the Azure slots. For us though, we are using Azure DevOps CI/CD pipelines to deploy to the various slots, which does not allow us to do the special build and publish routines that have been suggested.

And the suggestion within this thread to modify the launchsettings.json file for each slot would require multiple PRs to get created and approved, as that file would need to be modified and pushed for deployment for each slot.

Microsoft needs to figure out a way to either have Blazor read the environment variable from the slot configuration, or allow for modifying the required files during the DevOps release pipeline.

**Comment by ViRuSTriNiTy** [comment]
One possible solution in deployments is to use a `web.{Environment}.config` file to set `blazor-environment` header for the app based on the name of release pipeline stage.

These are the steps:

- add a `web.{Environment}.config` file per existing environment to your project root
  - for example `web.Staging.config` and `web.Production.config`
  - the file content should look something like this
  ```
	<?xml version="1.0"?>
	<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
	  <system.webServer xdt:Transform="Insert">
		<httpProtocol>
		  <customHeaders>
			<add name="blazor-environment" value="Testing" />
			<add name="Cache-Control" value="no-cache, must-revalidate" />
		  </customHeaders>
		</httpProtocol>
	  </system.webServer>
	</configuration>
  ```
	> See https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-5.0#set-the-environment-via-header for additional info about the file content.
- either include the files in your project so that it is copied to the output folder on build or add the following task to your pipeline
  ```
    - task: CopyFiles@2
      inputs:
        Contents: |
          {YourProject}/web.Staging.config
          {YourProject}/web.Production.config
        TargetFolder: ...
        flattenFolders: true
  ```
- enable [XML transformation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#xml-transformation) in your release pipeline stage

Now the deployed app will run with a transformed `web.config` that sets the `blazor-environment` header.

Hope this helps.

**Comment by sturlath** [comment]
I just could not get @ViRuSTriNiTy proposed solution to work for me but then I found [this complete guide](https://abpioazuredevopsblazor.azurewebsites.net/part9) setting up Blazor project within Azure DevOps that solved it for me. Thought I let you future reader know

**Comment by buzzluck68** [comment]
When I tried adding a web.{environment}.config file to the blazor wasm project (per @ViRuSTriNiTy), it would no longer load when run.  It would just forever stay on the loading progress stage.  So that is not a solution that I think will work.  I am looking at the link provided by @sturlath to see if it will work, but the documentation seems to be specifically for the blazor server side project, and not a wasm project.

**Comment by javiercn** [comment]
Hey folks, I gave this a try and created a small "guide" to see if that can help people troubleshoot this in their apps.

https://gist.github.com/javiercn/05314f8fc6d347c438484aee840ef001#file-instructions-md

@guardrex can you add something to the docs based on the gist above?

**Comment by buzzluck68** [comment]
@javiercn I am not sure why you decided to close this issue, as even you state that this is not a fix for Blazor Webassembly standalone apps.  This issue was created for a Blazor Webassembly standalone app, not an aspnetcore hosted one. We need a fix for the standalone version of Blazor to be implemented please.
