### ISSUE TITLE
Bug with controller action which has a parameter named "index" and an IEnumerable parameter

### ISSUE THREAD

**Issue by Hayko-1** [dotnet/aspnetcore#28603]
### Example

```C#
    [ApiController]
    [Route("[controller]")]
    public class MyController : ControllerBase
    {
        [HttpGet]
        public bool Get([FromQuery] string index, [FromQuery] IEnumerable<int> test)
        {
            return test != null && test.Any();
        }
    }
```

### Actual Result
requesting http://localhost:18351/my (with no params) returns **false**
requesting http://localhost:18351/my?index=123 (with index param) returns **true**

### Expected Result
requesting http://localhost:18351/my?index=123 (with index param) should return **false**

Tested on .NET Core 3.1

**Comment by brunolins16** [comment]
@Hayko-1 the current behavior, described here https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections, is using the `index` querystring/form to bind the collection. What can potentially be improved here is if the **_Controller Action_** has an `index` parameter explicitly defined we skip the usage of the `index` query/form during the collection binding. 

@pranavkm what do you think about that?

**Comment by brunolins16** [comment]
I have discussed with @pranavkm and changing the behavior could add an unnecessary complexity, since this is a scenario easily fixed changing the **Action parameter name** to something other than `index` and should be our recommendation here.

I will update the docs (https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections) to include this recommendation avoiding users to use the `index` parameter when binding `collections`.
