### ISSUE TITLE
Editing same blazor component in two different windows makes visual studio extremely slow.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28645]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Editing-same-blazor-component-in-two-dif/1282952)._

---
[severity:It bothers me. A fix would be nice]
When I open same blazor file in two different windows. Visual studio become slower than usual.
! [image.png] (https://aka.ms/dc/image?name=Bdf1dcd88b3574d04add190cb47d89a0e637431210329715630_20201209-173031-image.png&tid=df1dcd88b3574d04add190cb47d89a0e637431210329715630)

---
#### Feedback Bot on 12/9/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
