### ISSUE TITLE
RazorCompileOnBuild not working

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#28657]
I hope to see the `Pages` folder, `RazorCompileOnPublish` works fine, but `RazorCompileOnBuild` not working.
![image](https://user-images.githubusercontent.com/12094247/102173450-f851d200-3ed5-11eb-8760-040a9434f357.png)

**Comment by pranavkm** [comment]
Setting `RazorCompileOnPublish=true` suppresses copying files to the publish directory, which is why you would see these files being copied to the publish directory when the feature is disabled. However, Razor files are typically not copied to the build directory. You can choose to copy them by configuring `CopyToOutputDirectory=PreserveNewest`:

```xml
<ItemGroup>
   <Content Update="...\*.razor" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```

That said, why are you disabling build time compilation? You don't need to disable it to use runtime compilation.

**Comment by ahdung** [comment]
I know the `CopyToOutputDirectory` way, but this is not elegant. Allowed to disable but not automatically copy `Pages` to the output directory, it's strange. This will cause you to be unable to access any cshtml pages after running the exe in the output directory directly. `Disable` and `copy`, it should be an atomic operation, like `RazorCompileOnPublish` does.

**Comment by pranavkm** [comment]
@ahdung thanks for the feedback. Given there's a fairly straightforward way to achieve what you're trying to do, we're unlikely to change this behavior.
