### ISSUE TITLE
Modifying Blazor WebAssembly Individual User Accounts authentication

### ISSUE THREAD

**Issue by frankabbruzzese** [dotnet/aspnetcore#28784]
### Is your feature request related to a problem? Please describe.
At moment when a Blazor WebAssembly project is scaffolded choosing "Asp.net Core hosted", and  "Individual User Accounts" in order to authenticate the user must leave the Single Page Application to perform a cookie based authentication. Then, Blazor uses the cookie to get the needed bearer tokens.

Since leaving the SPA and reloading di SPA costs a lot of time and clears the SPA application state it would be better to force the user to authenticate with cookie before he enters the SPA.

### Describe the solution you'd like

I studied the a little bit the code of the Identity Server Extensions defined to put in place the whole authentication protocol, and tried the code below to force the user to logs in before entering the SPA:

```
endpoints.MapFallbackToFile("index.html")
                .RequireAuthorization(new AuthorizeAttribute() 
                { AuthenticationSchemes = IdentityConstants.ApplicationScheme }) ;

```

Substantially, I added `RequireAuthorization` to force logging before entering into the the SPA. 
After this modification, when the application starts, the user is correctly redirected to the login-page, 
but then, he continues to be redirected to the same login-page also after a successful login.

Meaning the `IdentityConstants.ApplicationScheme` scheme  furnishes the correct login page, but strangely enough is not able to authorize the page.

If I remove  `AuthenticationSchemes = IdentityConstants.ApplicationScheme` the user stops being redirected to the login page and the browser receives a 401 code. This makes sense to me, since outside of the "/Identity" path the default schema is the bearer token schema.

Is there something I can do to solve the issue without rewriting from the scratch the whole identity server based authentication logic?

**Comment by sportfisketavling** [comment]
It doesn't make sense to me either that you create a Blazor WebAssembly App thats supposed to be SPA. But as soon as you choose to have authentication it isnt SPA. Since you have to leave the application for authentication, registration and managing your account.

Is it possible to use blazor components on the client side for handling such scenarios or at least embedd the pages in the SPA application?

Not only the problem with leaving the application. But the UI/UX is problematic. I mean, when you are redirected to the "Manage my account"-page, how are you supposed to get back? I want the same menus, footers, mainlayout as my blazor application but thats impossible.

**Comment by frankabbruzzese** [comment]
@sportfisketavling ,
Actually, it makes sense but can be improved. The whole Blazor authentication framework has been designed to be compatible with OAuth, that is with external providers, and OAuth requires the browser to move to other URLs. There is no SPA version of OAuth because of security problems.

However, one can force the user to authenticate before entering the SPA. This way the application remains compatible with OAuth, and the user is not forced to leave the SPA once entered. 

The other option is to give up OAuth and to implement a pure Jwt based authentication. However, also this approach has its disadvantages:

1. You can't add external providers to your SPA. This means you can't access services offered by third-party WEB-APIs.
2. You are forced to issue long-life bearer tokens and possibly to store them in local storage. Both choices are not safe. 

You can mitigate point 2, by using the long-life Jwt only to get short life and task-specific Jwt. However, this complicates Jwt handling each time you need to call the server.

There is no way to overcome point 1.

Here the actual problems are the application load time and saving the apllication state more than exiting the SPA. You can serialize the Blazor application state, and save it in local storage before leaving the application, but the high Blazor application load time at moment is difficult to overcome. One should be able to cache the whole app and not only the framework code.

In my opinion, at moment, the best option is authenticating with all needed providers before entering the application.

**Comment by javiercn** [comment]
@frankabbruzzese Thanks for contacting us.

The reason why it doesn't work is because Identity Server handles the **authorization** of the SPA application by delegating to ASP.NET Identity for the **authentication** process.

The best solution I could think of would be to add an additional redirect url, perform the same CODE+PKCE from the server to get the authentication state setup in the same way and to enable the app to login silently upon start on the browser. That said, I have my doubts about whether it will work and it is likely it stops working in the future all-together in the general case due to incoming browser restrictions on cookies and third-party domains.
