### ISSUE TITLE
Debug Blazor wasm hosted in ASP.NET Core: Hosting environment is always Production

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#28797]
Hi, i have the same issue reported here: https://github.com/dotnet/aspnetcore/issues/26999

I use ASP.NET Core 3.1 and blazor WASM.

The hosting environment is set to `Production` but i'm in debug and in launchsettings.json is specified `"ASPNETCORE_ENVIRONMENT": "Development"`:

```
"ARTCreditService.Server": {
      "commandName": "Project",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

debugging the startup.cs in Configure method, the result of `env.IsDevelopment()` is `true` but in the console it show "`Production`":

![image](https://user-images.githubusercontent.com/13186600/102867482-2042b780-4439-11eb-8cb1-7c02112af510.png)

What's wrong?

Thanks

**Comment by captainsafia** [comment]
Thanks for opening this issue, @Gambero81! It looks like you've identified the hosting environment for the Blazor debugging proxy server. This is independent of your application server's hosting environment.

Since the `env.IsDevelopment()` call is returning true, it appears that your application server has the correct hosting environment set. Can you verify this in the console output for that server?

The hosting environment for the debugging proxy shouldn't affect anything in your app.

**Comment by Gambero81** [comment]
Thanks @captainsafia, i checked the output console of a new blazor wasm project and it show 2 rows for hosting environment, the first with `Developement` and the last with `Production`, instead in my project it show only one row with `Production` so i was confused:  

![image](https://user-images.githubusercontent.com/13186600/103875628-f644f280-50d2-11eb-8e02-a9f2c2e2c06a.png)

Why in my project i dont see the first 5 console rows on info? there is a setting i have missed?

Even if the `Production` specified in console does not affect any in the app, why the console show it?

Thanks

**Comment by captainsafia** [comment]
> Why in my project i dont see the first 5 console rows on info? there is a setting i have missed?

Perhaps you might've configured logging differently on your project?

> Even if the Production specified in console does not affect any in the app, why the console show it?

It's the output from the debugging proxy. We pipe it to stdout because it can be helpful for diagnosing debugging issues.

Since this isn't a bug, I'll close the issue for now. If you have any more bug reports, please open a new issue.
