### ISSUE TITLE
runtimelist.xml file not included in runtime archive

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#29092]
This is a reoccurrence of https://github.com/dotnet/aspnetcore/issues/27670.

The issue is that there is not parity between the ASP.NET files contained in the SDK archive vs the standalone ASP.NET runtime archive.  The runtime archive does not contain a runtimelist.xml file.

https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.21054.2/dotnet-sdk-6.0.100-alpha.1.21054.2-win-x64.zip: Contains shared/microsoft.aspnetcore.app/6.0.0-alpha.1.20629.3/runtimelist.xml

https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.0-alpha.1.20629.3/aspnetcore-runtime-6.0.0-alpha.1.20629.3-win-x64.zip: Does not contain shared/microsoft.aspnetcore.app/6.0.0-alpha.1.20629.3/runtimelist.xml

cc @wtgodbe

**Comment by wtgodbe** [comment]
Darn, I'll take a look

**Comment by wtgodbe** [comment]
Ah, I remember this now - I closed the last issue because the same is true for WindowsDesktop and Runtime - that is, none of the sharedFx zips anywhere in the stack carry a runtimeList.xml. The dotnet/installer repo gets these files from somewhere else - I believe it's the .nupkg? @wli3 @sfoslund @dsplaisted could you confirm?

**Comment by dsplaisted** [comment]
We use the runtime archive, and it looks like at least until recently it had the RuntimeList.xml file in it: https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/6.0.0-alpha.1.20617.3/aspnetcore-runtime-internal-6.0.0-alpha.1.20617.3-win-x64.zip

The RuntimeList.xml file doesn't need to be in the shared framework, it only needs to be in the runtime pack.  My understanding is that it was included in the ASP.NET runtime archive more or less incidentally.

If it has been removed from the runtime archive, I would expect for it to stop showing up in the SDK once the dependency flows through to the installer repo.

**Comment by wtgodbe** [comment]
runtimeList.xml is present in `aspnetcore-runtime-internal.zip` but not `aspnetcore-runtime.zip`. This has been true since at least 5.0.0-preview1.

As for dotnet/runtime, `runtimelist.xml` isn't present in either `dotnet-runtime.zip` or `dotnet-runtime-internal.zip`, which has also been true since at least 5.0.0-preview1. How do you get the file from runtime?

**Comment by wtgodbe** [comment]
Also @mmitche how does this intersect with https://github.com/dotnet/aspnetcore/issues/27687? I thought dotnet/runtime had already gotten rid of their `-internal` zip, but I still see it in the latest 6.0.0-preview blobs in dotnetcli. Did https://github.com/dotnet/runtime/pull/38457 just get rid of the `-internal` .nupkg? CC @jkoritzinsky

**Comment by dsplaisted** [comment]
> How do you get the file from runtime?

We don't.  It's not in the .NET SDK layout.  It is part of the runtime pack when those get downloaded, but we don't produce those in dotnet/installer.

**Comment by wtgodbe** [comment]
Ah, I see - the SDK zip doesn't have runtimelist.xml files for WindowsDesktop or Runtime, but it does have one from aspnetcore. This is because we include the file in our `-internal` .zip, while the other repos don't. So we should remove it from our .zip, but keep it in our .nupkg - does that sound right @dsplaisted?

@mmitche my other question still stands - is https://github.com/dotnet/aspnetcore/issues/27687 about getting rid of the `.nupkg` or the `.zip`? It sounds like dotnet/installer still explicitly relies on the `.zip` for constructing the SDK archive

**Comment by jkoritzinsky** [comment]
dotnet/runtime still produces the -internal archives. I wasn't sure when dotnet/installer wasn't using them, so I didn't stop producing them.

**Comment by dsplaisted** [comment]
> So we should remove it from our .zip, but keep it in our .nupkg - does that sound right @dsplaisted?

Yes, that sounds right.

**Comment by mthalman** [comment]
@wtgodbe - So should https://github.com/dotnet/aspnetcore/issues/27670 be re-opened since this isn't fixed in 5.0?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/29109

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/29109
