### ISSUE TITLE
blazor inputcheckbox bool? 

### ISSUE THREAD

**Issue by DanielSeara** [dotnet/aspnetcore#29135]
The `InputCheckbox` doesn't support `bool?` because `null` cannot be represented in an HTML checkbox element.

_Originally posted by @mkArtakMSFT in https://github.com/dotnet/aspnetcore/issues/14500#issuecomment-536007662_

Right, but if my model needs a bool? property, the component MUST manage it. In this case, if it !HasValue it will be displayed unchecked. :) Otherwise I'll have to:
- Define strange properties out of my model,  just to accomplish the component limitation
- Forced my model, and my database and my business not to use null values if required.

**Comment by Regenhardt** [comment]
A checkbox does after all have two states - checked and unchecked. null might imply there is no checkbox, or that it should decide for itself what its default value is (which depends on your use case).  
Since you need your component to carry a `bool?`, you could wrap the checkbox in `@if(model.HasValue)` and bind the checkbox to `model.Value`, or gotta make something else to make your view decide what it means when there is no value at all.

**Comment by DanielSeara** [comment]
So, instead od simplify things, it needs to be complicated in a VERY COMMON case. I think it is a bad design, but, I know: you'll not change it, even consider the usual case. Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Regenhardt.
This is indeed not something we plan to change. There should already be many third-party components doing that so you can consume one of those.
