### ISSUE TITLE
mkArtakMSFT closing issues that are not resolved

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#29158]
Getting pretty sick of you closing issues with no discussion or further information, it's lazy and completely against the point of github issues. #29154 is very much still open as you have not provided any information on resolution. Calling js interop in the way described in my issue is in line with your docs (https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0) which you would know had you not instantly closed the issue. 5th time you've done it now... @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Thanks for raising your concern, @ScottKane.
I'm sorry that my responses came along that way. There is definitely nothing personal here. In fact, I don't even remember any other issues you've filed. Of course I can query for these, but that's not the point. What I want to emphasize is that we don't differentiate our customers and all of them, including you are very valuable to us.

Being a small team we can't afford spending much time on issues which are caused by customer code and help everyone out. As much as we would like to do that, we just can't: that would result in us spending more than half of the team time on these investigations and reduce the innovations and bug fixes we make. To address this, we've had decided to redirect all customers who file similar issues to [StackOverflow](https://stackoverflow.com), as they can get faster responses there. This process is well detailed in our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) document.

Speaking about the referenced issue, it was closed because you have an error in your code. What's happening there, is the method `JsInterop.SetGridDataAsync` is static, and it relies on at least one `JsInterop` type instance to be created to operate successfully. Because you never call into DI to instantiate that type, the constructor is never called, hence the static method fails as the value of `_js` is null. An easy way to confirm this yourself would be to add a breakpoint in the constructor of the `JsRuntime` and see that it's not being called. Hope this helps.
