### ISSUE TITLE
Not able to debug webassembly after publishing it to iis 

### ISSUE THREAD

**Issue by KulwantK** [dotnet/aspnetcore#29208]
Hi,
i have created a blazor webassembly project and publishing it to IIS (local).

![image](https://user-images.githubusercontent.com/43417143/104315984-c433f600-5501-11eb-88e1-8cf5c8e0f8d3.png)

everything works fine except debugging part. 

whenever tries to debug it always says "the break point will not currently be hit. no symbols have been downloaded". 

any help would be appreciated

Thanks.

**Comment by javiercn** [comment]
@KulwantK thanks for contacting us.

Are you publishing the symbols? Also is it a standalone or a hosted project?

The debugger needs a proxy to be running in order to debug from the editor. Otherwise you can always debug through the browser developer tools.

**Comment by KulwantK** [comment]
Thanks for responding.

Are you publishing the symbols? **not much idea how we do it, are you asking about Debug->Options->Debugging->Symbols**

is it a standalone or a hosted project? **Yes its standalone** 

Otherwise you can always debug through the browser developer tools. **is this possible once you have published it to iis, i dont think so, have tried it but with no luck.**

**Comment by captainsafia** [comment]
@KulwantK You'll also want to make sure that the environment is set to `Development` in the app that you'd like to debug. Assuming the following conditions are met:

- App environment is set to `Development`
- Debugging using either Chrome or Chromium edge
- Don't have any proxies or firewalls on the machine you're debugging in
- Confirmed that PDBs are generated in the app output

After that, you should be able to debug by following the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser).

Note: you'll probably want to publish and run locally instead of doing this on a production deployment.

**Comment by KulwantK** [comment]
thanks seems it issue is resolved so closing this issue
