### ISSUE TITLE
Validating model of type ContentType fails in aspnet core 5 when name field is missing

### ISSUE THREAD

**Issue by Codecamv** [dotnet/aspnetcore#29343]
### Describe the bug
Validation of ContentType objects have changed from .net core 3 to 5. It seems like the type "ContentType" must always include the name field in order to validate (for instance when using TryValidateModel). In .net core 3 and lower the lack of name field has not given us validation errors. Inspecting the ContentType class the name property is allowed to be null, but the framework seems to think otherwise. This is a critical issue for us as we offer api endpoints having input models with ContentType properties (cloudevent objects).

As seen in attached screenshot running the code in aspnet core 5 we see that a ContentType object without name set does not validate, while a ContentType with the name property set does validate. We are in the understanding that the name property should not be required. 

![image (41)](https://user-images.githubusercontent.com/823495/104713183-cbd2e500-5723-11eb-9888-87b8b517fba9.png)

Same code, but now with aspnet core 3 produces successful validation on both objects (attached below)

![netcore3](https://user-images.githubusercontent.com/823495/104713914-cf1aa080-5724-11eb-9fff-b0004e738665.png)

Please check the supplied link to github for the test project illustrating the issue.

### To Reproduce
https://github.com/Ianril/dotnetcore5issue (code is in the weatherforecastcontroller)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is the expected behavior. You can read more about it [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#required-attribute) as well as learn how to work around this.

In general, we recommend not binding to types that you don't own / have control of, since the shape can change and that can cause errors and cause security issues.
