### ISSUE TITLE
Why DI method of 'AddOAuth'  must need type of CallbackPath is 'PathString'?

### ISSUE THREAD

**Issue by BruceQiu1996** [dotnet/aspnetcore#29388]
I am using assembly 'Microsoft.AspNetCore.Authentication.OAuth' to access three-party authentication,but three-party callback of auth2.0 is an absolute path to their site.but the AddOAuth method need parameter of 'CallbackPath' is PathString.
So the design here can only use the path of my own site?
Now I get httpstatus code is 500 and the three-party give me 'Invalid redirect_uri'
Now i want know did I use it wrong or say this design is safer and more reasonable or another way can fulfill my needs.thx

**Comment by blowdart** [comment]
The call-back path is where the oauth flow returns to on your site, after login has been completed on the 3rd party oauth server. 

You should not have oauth starting from site A returning to site C, it won't work, because sites are supposed to check if they initiated the request, and site C will know it didn't start the request and will reject it. 

Your logs will have more details about the 500 if it's on your site. If it's the oauth server saying the uri is invalid then your app registration on that site is incorrect, it needs to be in the form of your full domain and the callback path.
