### ISSUE TITLE
Blazor: multiple @page directives not working

### ISSUE THREAD

**Issue by WouterrV** [dotnet/aspnetcore#29406]
Blazor supports multiple routes per component, according to the docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0

But IME this works a bit buggy. If you make a Razor component with multiple @page directives, then those routes work, but if you then arrive at the target URL and press F5, the page 404's.

How to reproduce: 

1. make a new blazor server project (.NET 5.0)
2. add `@page "/counter.html"` to `Counter.razor`
2. add `<a href="/counter.html">Go to counter</a>` to `Index.razor`
4. click on the link you just created, the page should load
5. press F5, the page 404's.

Now, if you go to /counter (using the default menu on the left), F5 does work strangely enough. Can someone look into this? Many thanks!

**Comment by javiercn** [comment]
@WouterrV thanks for contacting us.

This is likely not a Blazor routing issue but an issue on how you have setup the routes on the hosting server. It is likely that your server doesn't have a fallback route configured to render the entry page (index.html or _Host.cshtml) when no other route is applicable and as a result when you F5 into `/counter` the server responds with 404 instead of serving the root document.

Check that you have `endpoints.MapFallbackToFile("index.html")` in your Startup.cs or `endpoints.MapFallbackToPage("_Host.cshtml")`

**Comment by WouterrV** [comment]
Sorry I don't understand you. Why would I need a fallback route?

> when no other route is applicable

But other routes are applicable, see the steps I posted, it's defined there. And it works, just not in all contexts.

> configured to render the entry page

What sense does it make to render the entry page if I want to retrieve `/counter` ?

**Comment by javiercn** [comment]
@WouterrV There are two routing systems involved when you are dealing with Blazor applications (or any SPA for that matter).

* Server-side routing: Happens when you navigate to a page for the first time (for example, type the url in the browser or press F5 in an existing page)
* Client-side routing: Can happen after the first navigation has occurred and the document has been loaded into the browser. In this type of navigation, code running in the browser programmatically changes the url, but the document that was loaded remains the same (hence single page applications), just new content is displayed via JavaScript.

Routes in *.razor files are client routes. The server knows nothing about them so it doesn't know which document it has to serve (hence the 404).

Given that the server can't know all the routes it needs to handle (since it doesn't know about routes in the .razor files) the normal setup is to configure a "fallback route" (with one of the methods described above depending on your use case) and to serve the document that represents the entry point of your app `(index.html, _Host.cshtml)`.

Then when the application starts in the browser, the client-side routing mechanism will kick in and render the appropriate page.

**Comment by WouterrV** [comment]
Okay thanks for the extra explanation. I just checked for a fallback route, I used the default Blazor project and the fallback route is already defined there.

So this doesn't solve the problem, there's still an inconsistency, because `/counter` works with F5, and `/counter.html` doesn't which doesn't seem like the intended behavior, with server-side routing only one works, with client-side routing they both work.

**Comment by javiercn** [comment]
@WouterrV we might be missing some context.

Could you provide a minimal repro project that illustrates the issue so that we can try and determine what's going on?

**Comment by WouterrV** [comment]
Absolutely: https://github.com/WouterrV/MultipleRouteTemplates

**Comment by javiercn** [comment]
@WouterrV thanks for the additional details.

The issue is that the second route contains a file extension `.html` and the default fallback route will automatically ignore paths with an extension. There is an overload you can call that allows you to specify the pattern explicitly. `MapFallbackToPage("<<pattern>>", "<<page>>")`
