### ISSUE TITLE
HTTP/3: Add multiplexed connection support to UseConnectionLogging()

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#29436]
With HTTP/3 each stream is its own `TransportConnection`. Verify that connection logging works with this way of managing connections and streams.

**Comment by JamesNK** [comment]
Tested and connection logging doesn't work.

**Comment by JamesNK** [comment]
It seems like there is a different path for multiplexed connections:

https://github.com/dotnet/aspnetcore/blob/45867e0be114d5a214c573eab705dc0cf8ef222a/src/Servers/Kestrel/Core/src/ListenOptions.cs#L135-L139

https://github.com/dotnet/aspnetcore/blob/45867e0be114d5a214c573eab705dc0cf8ef222a/src/Servers/Kestrel/Core/src/ListenOptions.cs#L161-L175

Has thought been put into making connection middleware work with both? Or should something like `ConnectionLogging` add middleware to both standard connections and multiplexed connections in its `UseConnectionLogging` method?

@jkotalik @halter73 @tratcher @davidfowl

**Comment by halter73** [comment]
I figured we'd just create a MultplexedConnectionLoggingMiddleware similar to https://github.com/dotnet/aspnetcore/blob/88226213a3dcef969310de1fb7510f40bdfb2ab2/src/Servers/Kestrel/Core/src/Middleware/LoggingConnectionMiddleware.cs but multiplexed. That makes it sound slightly more trivial than it is since we'll need to decorate the MultiplexedConnectionContext so we can intercept Accept/ConnectAsync, but that doesn't seem too bad.

Then we have UseConnectionLogging() add both the normal and multiplexed middleware.

**Comment by jkotalik** [comment]
But don't you want to have UseConnectionLogging() per stream for QUIC/HTTP/3? Would the MultplexedConnectionLoggingMiddleware add logging per stream as well?

**Comment by halter73** [comment]
> Would the MultplexedConnectionLoggingMiddleware add logging per stream as well?

Yes. That's why the MultplexedConnectionLoggingMiddleware would need to decorate the MultiplexedConnectionContext and intercept the calls to Accept/ConnectAsync.
