### ISSUE TITLE
I want to capture the Browser keypress event and perform certain action [Hot key functionality in Blazor]

### ISSUE THREAD

**Issue by Akmo790** [dotnet/aspnetcore#29443]
I want something like if I press F5 then I want to capture this key event and perform certain action In Blazor e.g. want user to directly navigate to certain component on different KeyPress event like F5, Ctrl+shift+F5 etc.

**Comment by javiercn** [comment]
@Akmo790 thanks for contacting us.

There shouldn't be anything special about this in Blazor, you could achieve this by subscribing to `@onkeydown` in an element on the document root or by using javascript to attach an event handler within the window with `addEventListener`

**Comment by En3Tho** [comment]
I think F5 case is not so simple. SO gives some JS answers with disabling F5 first. I think user might just add those as script to index.html. Or is there an option to do it via Blazor?

**Comment by javiercn** [comment]
@En3Tho I'm not sure you can capture F5, but It's not something you can do in Blazor if it can't be done in the browser.

**Comment by Akmo790** [comment]
Actually i wanted something like, when my application is running in a browser and I click F5 or F10, I should be able to capture the response and perform certain action in blazor server side application for. E.g open s specific page .If it can be javscript can you give a samlle code.

**Comment by javiercn** [comment]
@Akmo790 I'm not sure how to do it nor if it's possible to do so in the browser. 

While we do our best to try and answer every question, this question is not about Blazor anymore and about web programming. 

This issue tracker is focused on product issues, since we don't have the resources to handle these types of questions, I would suggest you try asking how to do this in JavaScript in Stackoverflow or a similar forum and then apply it to Blazor through the use of JS interop.

That said, I think that this is likely not possible to do in the context of a browser (for some key bindings like F5 at least)

**Comment by Akmo790** [comment]
Ok
