### ISSUE TITLE
We should colorize "string" TagHelper attributes as normal HTML attributes

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#29471]
Otherwise you get this:
![image](https://user-images.githubusercontent.com/2008729/105227127-c277bd00-5b15-11eb-9a73-9df5111df940.png)

**Comment by ryanbrandenburg** [comment]
Nice catch, I see what happened here now. Firstly I usually use Dark-mode, for which the html attribute value color is white, as is the text literal value, so I didn't notice this difference. For why it was wrong, the problem is that I needed to override VisitMarkupTagHelperAttributeValue, otherwise it steps down into the child (MarkupTextLiteral). Fix incoming.
