### ISSUE TITLE
Different routing behavior between .NET 5 and .NET Core 3.1

### ISSUE THREAD

**Issue by JasonXtreme** [dotnet/aspnetcore#29594]
### Describe the bug
As far as we managed to gather, .NET 5 has either different behavior to .NET Core 3.1 or there is a bug in route priority assignment.

Mapping two endpoints, one pointing to a Home controller and a second, catch-all endpoint, in .NET 5, the catch-all endpoint always takes precedence. In short:

Action: make a GET call to https://localhost:5001/home

Behavior:
.NET Core 3.1: Calls the Home controller once and the catch-all once (favicon.ico).
.NET 5: Calls the catch-all endpoint twice, regardless of other mapped routes.

Where it goes wrong:
The router first assigns precedence to both routes, giving the home controller route 1 and the catch-all route 5 (hard-coded for catch-alls). It then assigns scores to both, giving the home route a score of 1 and catch-all a score of 0. It orders the routes by score ascending and returns the first route (in this case, the catch-all). We suspect the score assignment logic is faulty.

### To Reproduce
See attached project. Compile, then run the .NET Core 3.1 version and the .NET 5 version, respectively. Trigger https://localhost:5001/home on both, observe console output or set breakpoints in home controller and catch-all route.

### Exceptions (if any)
No exceptions.

### Further technical details
.NET Core 3.1: SDK 3.1.405
.NET 5: SDK 5.0.102

### Reproducible sample
[RoutingIssueSample.zip](https://github.com/dotnet/aspnetcore/files/5867773/RoutingIssueSample.zip)

**Comment by javiercn** [comment]
@JasonXtreme thanks for contacting us.

You are likely running into [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference we)

There was a bug in asp.net core 3.1 that we fix with a compatibility switch. In 5.0 we made the correct behavior the default.

**Comment by JasonXtreme** [comment]
@javiercn Thank you for the quick reply. I am not entirely sure we are talking about the same thing here. Am I to understand that the controller route

`endpoints.MapControllerRoute(
    name: "default",
    pattern: "home",
    defaults: new { controller = "Home", action = "Index" });` 

is now as a rule considered less defined than a catch-all route and gets a lower precedence accordingly? This implies that once a catch-all route is introduced, all controller routes become irrelevant.

Interestingly enough,

`endpoints.MapGet("home", async (t) =>
    {
	System.Console.WriteLine("Home called");
	await Task.CompletedTask;
    });`

works as expected.

**Comment by javiercn** [comment]
@JasonXtreme thanks for the additional details.

I looked more in depth and I can conclude that the behavior you are seeing is by design and caused by the fix we did in 5.0 to the routing bug we had in 3.1

Routes have order and precedence and order wins over precedence.

Conventional routes have an Order=1 (so that they are less specific than attribute routes and don't interfere with them when combined).

The second endpoint you are mapping doesn't have an order, so the order is 0.

The conventional route has more precedence than the catch-all route, but order is evaluated over the precedence.

That's why the route with the catch-all wins over the conventional route.

Conventional routes have a starting order of 1 and the order increases with each definition (to reflect the same behavior as classic mvc).

**Comment by koma-tompit** [comment]
Thank you for the clarification. This still raises a question; in an application like ours, which combines several types of routes, how would one register a pipeline so that it follows routes from most to least defined (in precedence), with one catch-all route that only picks up requests that no other route matches? The application relies heavily on dynamically generated routes, for which we used the catch-all as described above until now.

**Comment by javiercn** [comment]
@koma-tompit You can specify the order of a route with a convention by downcasting the endpoint to `RouteEndpoint`. It will have an order property you can set. You can then just give it a large value (like 1000) and that should make it the last option).

If you routes are dynamic but handled by controllers I suggest you look into MapDynamicControllerRoute route and similar functionality. Those allow you to participate in the matching process by defining your own mapping between your route values and the controller and action to target and already incorporate order implicitly on the same way that conventional routes do.
(Meaning you have control over how the route maps to a controller/action and the same definition order that conventional routes have)

**Comment by koma-tompit** [comment]
Hello again, @javiercn. Your quick response times are much appreciated. We tried casting an endpoint to a RouteEndpoint, but the Order property is readonly. Would you be so kind as to provide a short code sample?

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/blob/c272436a9e5dd42662d5f7eb5451c0eb0fc805c9/src/Http/Routing/src/Builder/FallbackEndpointRouteBuilderExtensions.cs#L75-L98

**Comment by koma-tompit** [comment]
@javiercn You are a saint! If you're ever in Slovenia, there's a glass of fine Cognac here with your name on it. Thank you.
