### ISSUE TITLE
The new Razor editor doesn't honor setting a background color for code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29601]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The-new-Razor-editor-doesnt-honor-setti/1316258)._

---
[severity:Other]
The new Razor editor doesn't set a background for code blocks, which is fine, but it also doesn't honor the background color for code blocks if someone sets it. We should have a way to specify that you want the background color.

---
#### Feedback Bot on 1/20/2021, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
@NTaylorMullen I saw you labeled this as a compiler issue earlier but it seems like a tooling bug. Let me know if there is some context I'm missing here!

**Comment by ryanbrandenburg** [comment]
@captainsafia you're right, definitely a tooling issue. We just don't currently emit the tokens for code blocks.

**Comment by ryanbrandenburg** [comment]
This is actually a bit more nuanced than I had first thought. Our survey's show the community preference is to have no background coloring, but we'd like to give people the option to set it if they prefer. My plan WAS going to be to start returning the background code token and set the Alpha channel of the background color classification to 00 ("totally clear") in the default themes, then users could override that color to get their preferred result.

The problem is that the VS Fonts and Colors menu doesn't currently offer users a way to set the Alpha channel, so it's impossible for them to make this token visible. We're currently discussing options.

**Comment by ryanbrandenburg** [comment]
We talked it over and the decision for now, given the platform limitations here, is to omit the Razor Code Background token from LSP Razor Semantic Token emission. This won't affect the old editor.
