### ISSUE TITLE
Start experimenting with draft AoT support in runtime

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#29630]
- [ ] Try to get this working end to end (basic blazor app)
- [ ] measure app size and perf

**Comment by SteveSandersonMS** [comment]
I have been exploring the AOT capabilities since we got a first drop of it yesterday, but see that @pranavkm has also been doing so, and in fact has already produced some measurements of app size and perf.

@pranavkm I don't want to get in your way here! It looks like you're dealing with this. Should we assign this issue to you, or even just close it since the things listed above are done? Likewise, let's discuss whether we should both be working on aspects of this, or whether this is a one-person thing and you want to just own it.

**Comment by SteveSandersonMS** [comment]
As described above, I think this issue no longer serves any purpose so I'm closing it.

@pranavkm Looking to you for info about anything that still needs to be done - but isn't yet planned - for getting an MVP in Preview 2.
