### ISSUE TITLE
Blazor Intellisense support for light bulbs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29644]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-Intellisense-support/1309085)._

---
I'm using Blazor serverside project using .NET 5. In my razor page, I have the following code but it doesn't have any support to add references. I.e. "using statements". For e.g. CultureInfo as seen below. Other frameworks like Aurelia,Vue,React already have the ability to right click the property and add the reference(For e.g. @using System.Globalization;) to top of page. It'd be beneficial for Microsoft to add these features if they want users to switch to Blazor. 

```
@page "/"
<p>Created time : @createdTime</p>
@code {
    private static string DateTimeFormatExpected = "yyyyMMddHHmmzzz";
    private static string createdTime = "202101131107-0800";

private DateTime documentCreatedTime = DateTime.ParseExact(
                        createdTime,
                        DateTimeFormatExpected, CultureInfo.InvariantCulture);
```

---
#### Feedback Bot on 1/13/2021, 10:40 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue is fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
