### ISSUE TITLE
Make some lines un-aligned in "FetchData.razor" file in Bazor Server project, select the lines and select "Format Selection", the format is not correct.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#29645]
REGRESSION: Worked in: Dev16.8.4
REPRO CONFIGURATION: Win Server 2019 19h2(1909)+Dev16.9 Preview3 VSE

.NET Core SDK (CLI) Version: 5.0.200-preview.20614.14
Latest .NET Core runtime Version: 5.0.1

TESTCASES AFFECTED:
AspNetCoreBlazorRazorEditing

INSTALL STEP

1. Clean machine: Win Server 201919h2(1909)

2. Install Dev16.9 Preview 3.0+
Select Web workload +  .NET Desktop workload
Check additional project template(previous version)
Unchck .NET Core 3.0/2.2 runtime under IC tab
REPRO STEPS
1. File >New Project>Blazor Server App~.NET 5.0(Current).
2. Open [FetchData.razor](https://github.com/dotnet/aspnetcore/blob/f0fc56dc58fd06b26a897ab68b7dae0ef12f3117/src/Components/Samples/BlazorServerApp/Pages/FetchData.razor) under Pages folder.
3. Make some lines un-aligned like below.
    
   ![image](https://user-images.githubusercontent.com/1408396/106674046-73934400-6567-11eb-9475-061ceb3105f5.png)

4. Select lines(19~22)  and Edit->Advanced->Format Selection

### Expected result

![image](https://user-images.githubusercontent.com/1408396/106674123-8dcd2200-6567-11eb-84c1-568e14df7fd8.png)

### Actual result

![image](https://user-images.githubusercontent.com/1408396/106674137-9291d600-6567-11eb-9f41-54ff81fa1caa.png)

See original VSTS issue for images: 
AB#1265978

**Comment by sharwell** [comment]
This issue is caused by the following code:

https://github.com/dotnet/aspnetcore-tooling/blob/ddbe099e78585e03c7c62ac07dcc6a66472f8b8a/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs#L336-L338

In scenarios where the HTML formatter only formatted a portion of the code, the formatting is correct in a _relative_ sense and not an _absolute_ sense. In this case, `effectiveDesiredIndentation` should be equal to `razorDesiredIndentation` and not be adjusted to account for `effectiveCSharpDesiredIndentation`. We only want to adjust for `effectiveCSharpDesiredIndentation` if the formatted span includes one or more leading whitespace characters on the first line of the HTML block. For this case, the starting position needs to be at or before the `$$` in the following:

```
   $$ <table class=""table"">
```
```

**Comment by davidwengier** [comment]
Also reported here: https://developercommunity.visualstudio.com/t/Formatting-doesnt-work-in-VS-2022-previ/1517712
