### ISSUE TITLE
CertificateManager.ListCertificates impacting ASP.NET startup

### ISSUE THREAD

**Issue by stephentoub** [dotnet/aspnetcore#29650]
In an app created from the Blazor server template, CertificateManager.ListCertificates is consuming ~5% of startup time.  Within ListCertificates, a significant portion of normal processing time is spent opening the certificate stores and enumerating/validating every certificate.  However, in the typical developer use case, an ASP.NET certificate will be found in the user store (since that's where it's generally added), but we still open and enumerate the local machine store, anyway.  It could be beneficial to first check the user store and only look at the local machine store if a valid cert can't be found in the user store.

cc: @halter73

**Comment by blowdart** [comment]
_However, in the typical use case, an ASP.NET certificate will be found in the user store (since that's where it's generally added)_

Are we sure about that? 

For IIS the typical approach was to put it into local machine so all app pools could see it, and ACL appropriately there. 
Service Fabric also uses the machine store, including in their [kestrel instructions](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint).

The dotnet cert tooling installs the self signed cert into the user store, because it's a testing cert. I'm not sure you can say that the typical, real life use case does the same.

**Comment by stephentoub** [comment]
Test cert is "real life use case" when focused on developer inner loop performance.

And,  regardless,  it didn't really matter.  Today both costs are paid up-front. We may as well just do one,  and only do the other of necessary.

**Comment by MCCshreyas** [comment]
If a certificate gets found in the current user store location, should we skip the call to find certificates from the local machine store? Or vice versa?

@stephentoub

**Comment by stephentoub** [comment]
> If a certificate gets found in the current user store location, should we skip the call to find certificates from the local machine store

That is what I was suggesting.

**Comment by stephentoub** [comment]
After the changes made to CertificateManager, ListCertificates has dropped to only ~2% of startup.  On top of that, the path Kestrel takes already only checks the local machine if the user store doesn't have the test cert.
https://github.com/dotnet/aspnetcore/blob/dfe625fbd122557cc4dda0f3d6f3dc5c7afc8c8e/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs#L176
It's not clear why https://github.com/dotnet/aspnetcore/blob/277cc564ce5a76c6613f29dd92c0168e06b41b1c/src/Shared/CertificateGeneration/CertificateManager.cs#L166 does something different, but it appears that's used by dotnet-dev-certs rather than by Kestrel, and so isn't an issue for ASP.NET startup.

So, we can close this, unless someone would like to keep it open for tracking improvements to dotnet-dev-certs.
