### ISSUE TITLE
Microsoft.AspNetCore.Identity 3.1 is not part of the ASP.NET Core shared framework

### ISSUE THREAD

**Issue by triplegav** [dotnet/aspnetcore#29659]
We have a need to create a class library that will implement custom SignInManager and UserManager classes.  These classes will be referenced by a number of different core web apps.

The last version of Microsoft.AspNetCore.Identity on nuget is 2.2.  Due to a breaking issue with the SignInManager constructor, we are unable to use this:

https://github.com/dotnet/aspnetcore/issues/21612

I was hoping the Identity classes would be included in the Microsoft.AspNetCore.App , but alas this is not the case.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio

Is there a plan to enable these Identity classes from Microsoft.AspNetCore.Identity 3.x to be available to a class library project in the future?

Thanks

**Comment by javiercn** [comment]
@triplegav thanks for contacting us.

Microsoft.AspNetCore.Identity is part of the shared framework. You need to add a framework reference to your class library in order to reference elements of the shared framework, but identity is part of it, you can find it at `shared\Microsoft.AspNetCore.App\3.1.11\Microsoft.AspNetCore.Identity.dll` within your dotnet install location.

If you are unsure how to get it to work, create a razor class library with support for MVC views and pages and that should create a csproj with all you need to reference the types, if you want to then make it a regular class library, remove the content and switch the sdk to microsoft.net.sdk

**Comment by triplegav** [comment]
Thanks @javiercn that worked!
