### ISSUE TITLE
blazor = native browser caching features

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#29676]
Providing solutions for caching data in the browser natively or by some component, such as localstorage, sessionstorage and indexeddb.

We already have some solutions made by the community for local and session, but indexeddb the solutions that exist still leave a lot to be desired. And it would be interesting to have extra features, like TTL, encrypt data, etc.

**Comment by javiercn** [comment]
@drma-dev You can already do this with one line of code.

We don't intend to provide a shim for all Browser APIs since that implies a high maintenance cost for our team that we can't afford, and we prefer that the community comes up with their own packages to do these types of things.

Some of this APIs are callable directly from JS interop without need for a wrapper library, but if you prefer it, building a wrapper is trivial. For example, localStorage can be directly called through JSInterop by doing `var data = await JS.InvokeAsync("localStorage.get", "key")` similar with other functions as well as for session storage.
