### ISSUE TITLE
Remove Blazor CascadingParameter binding by type

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#29817]
It just doesn't make any sense, makes the code unexpected, and introduces confusion and extra learning curve. Binding should be (like anything else in the world of IT) by name

**Comment by javiercn** [comment]
@MhAllan thanks for contacting us.

We appreciate the feedback, however this is not something we plan to change as this is not a common opinion from the community and removing a functionality like this would be a big breaking change.

Developers are not forced to use binding by type and can always leverage binding by name.

**Comment by mrpmorris** [comment]
Type is a very useful way for a parent to pass a reference of itself to children.

It's far better for a child to expect a cascading value if type Parent than it is to have both parent and child agree on a string ID. Passing by type will result in a compiler error if wrong, passing by string using the wrong ID will result in a null.

**Comment by MhAllan** [comment]
Do you see the daily conflicts that will happen just because things will bind behind your back? I am totally against it

**Comment by mrpmorris** [comment]
Sorry, I don't understand.  What conflicts?

**Comment by javiercn** [comment]
@MhAllan we appreciate the feedback, but we are not planning on removing existing functionality from the framework since it will be problematic for other users.

We haven't received significant feedback that binding by type is problematic and doing what you propose would be costly and a painful breaking change that we don't plan to do as it will unnecessarily cause pain to the vast majority of users that haven't complain about this.

I hope this helps clarify our motivations.
