### ISSUE TITLE
How to refresh my authentication cookie without redirecting to cshtml page in Blazor Server application

### ISSUE THREAD

**Issue by tahaAttique** [dotnet/aspnetcore#29819]
![Untitled](https://user-images.githubusercontent.com/47359465/106460492-3e2e1e00-64b5-11eb-870c-ab72b6a24835.png)

I am using Blazor Server. The screenshot mentioned above is a razor page. After Inactivity of sometime the app opens the above mentioned pop-up. On clicking Logout the app logouts. On clicking the Stay Login the pop-up/Modal disappears and should refresh the user cookie ticket.

For refreshing the cookie ticket/Token I am using SignInManager.RefreshSignInAsync(). 
![image](https://user-images.githubusercontent.com/47359465/106460585-6289fa80-64b5-11eb-94ea-09bee0465e16.png)

When I use SignInManager.RefreshSignInAsync() on the razor page I get exception saying "response headers cannot be modified because the response has already started."

![image](https://user-images.githubusercontent.com/47359465/106460663-7d5c6f00-64b5-11eb-9237-161def071671.png)

To resolve this I made a separate cshtml file and it works fine there. But the problem is that we have to redirect to that cshtml page to refresh user cookie ticket which loses the unsaved data(data in the inputs etc).

![image](https://user-images.githubusercontent.com/47359465/106460689-88170400-64b5-11eb-9f42-40d51bcca03d.png)

I am looking for a better solution to refresh user cookie ticket using which I will not lose the unsaved data and the app will continue the same. Waiting for your answers.

**Comment by javiercn** [comment]
@tahaAttique thanks for contacting us.

I'm going to assume that when you say razor page you are referring to a Blazor component (with a .razor extension) using the `@page` directive.

It is not possible to use the signin/signout capabilities from identity within server-side blazor since they rely on HTTP primitives (request/response) that are not available on the context of a Blazor application.

The only way to renew the cookie is to trigger a new request from within the browser so that the server can update the cookie within the response. The solution that you found seems appropriate, but in addition to it you might be able to do it without a navigation if you for example render a hidden iframe within the Blazor application or issue an ajax request through JS interop.

I'm not 100% convinced of all the security implications to do this safely, you might want to protect the endpoint against CSRF just in case, but it would require some analysis.

As mentioned above, Blazor applications don't run in the context of an HTTP request, so they don't have the ability to modify cookies.

/cc: @blowdart and @SteveSandersonMS in case they have further thoughts on alternatives/additional security considerations.

**Comment by tahaAttique** [comment]
Thanks a lot @javiercn, It was quite helpful.  Can you help me with Refreshing Authentication cookie using ajax request through JS interop?

**Comment by javiercn** [comment]
It's the same thing that you are doing, but you can use a controller instead and return "OK" from it. From the Blazor perspective doing something like `JS.InvokeAsync("fetch", "cookie-refresh")` will trigger an http request starting from the browser and that's all you should need.

Keep in mind that there might be security implications that you might need to deal with and that I can't analyze ad-hoc within an issue, so consider this suggestion as a starting point and determine if there are other things worth doing to secure the refresh endpoint.

**Comment by tahaAttique** [comment]
Thanks a lot ! It worked
