### ISSUE TITLE
New properties for ElementReference

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#29823]
I really like how FocusAsync was added.  Here are some other parts that would be great if it can be part of ElementReference.

1.  SelectAllAsync
This would highlight all the text if any.  I know it can currently be done with javascript interop.  However, I would guess having it built in would have better performance.

2.  GetBoundingRectangleAsync.
This would get the rectangle of the element which would include Height, Width, Top, and Left.

Even though its easy to get via javascript, however, if it was built into the framework, then that would improve performance.
Because instead of a person having to create calls into javascript and having performance problems, they would use that function which the framework would know the most efficient way to get the data.  Plus would allow more things to be done with the framework instead of reaching into javascript.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While we don't plan to add the proposed APIs to the ElementReference. However, we will expose the IJSRuntime instance from the ElementReference so that developers can easily add their preferred APIs in the future. That work will be tracked as part of https://github.com/dotnet/aspnetcore/issues/29826
