### ISSUE TITLE
Blazor server dispose of javascript addEventListener does not work on page refresh

### ISSUE THREAD

**Issue by ScottyBlazor** [dotnet/aspnetcore#29886]
This is referring to a closed issue that was not resolved
https://github.com/dotnet/aspnetcore/issues/29747
I have logged a new issue when I didn't get a reply there and following the instructions in the "Issue Management Policies"

Hi Javier thanks for the quick reply

I have been doing a lot of reading on IAsyncDisposable but am still experiencing some issues mainly the "A task was canceled" error is still being thrown.

1. I have implemented the IAsyncDisposable and moved the javascript dispose call to it
```
@implements IAsyncDisposable;  
async ValueTask IAsyncDisposable.DisposeAsync()
{
   await JSRuntime.InvokeVoidAsync("RemoveInputKeyboardEventHandler", this.ID);
}
```
the IAsyncDisposable is called but it still throws "System.Threading.Tasks.TaskCanceledException A task was canceled" once the garbage collector fires.
If I put break points before and after the javascript call the code never reaches the break point after it.
also any console.log calls in the javascript RemoveInputKeyboardEventHandler are never printed to the browser console (might be cleared because of the page refresh), I added one to the start of the javascript method to try and confirm it is actually being called correctly and one after it.
If I navigate to a new page all my break points are hit correctly, and all my javascript console.log are printed, but when refreshing the page this is not the case.

2. I also have some local references in my component that need disposing, but implementing both the IDisposable and IAsyncDisposable stops the IDisposable.Dispose being called, even after removing the async keyword from it as you recommended.
I could add these synchronous disposes to the IAsyncDisposable but this page seems to suggest both should work
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync
"Implement both dispose and async dispose patterns"
 
3. Should I be adding the GC.SuppressFinalize(this); to my IAsyncDisposable.DisposeAsync and IDisposable.Dispose
My understanding of this is to let the garbage collector know we have manually cleaned up the object so it doesn't need to (but not quite sure). I have seen code samples where some people call it and some don't.

4. bit of a async noob question here. 
as my javascript RemoveInputKeyboardEventHandler does not return a value should I be awaiting it when calling InvokeVoidAsync.
or should I make it return a value or something just so it can be awaited correctly?

5. does my javascript code in RemoveInputKeyboardEventHandler need to be async, ie "async function RemoveInputKeyboardEventHandler(p_ControlID)"

Sorry to bombard you with questions, I just want to make my code work correctly without memory leaks and I find understanding the documentation is a little tricky in some of these areas.

_Originally posted by @ScottyBlazor in https://github.com/dotnet/aspnetcore/issues/29747#issuecomment-771275593_

**Comment by javiercn** [comment]
@ScottyBlazor I apologize if we missed your follow up comment.

I didn't realize this was happening within the page refresh. 

I don't think there is anything you can do in that case, since by the time disposeasync is called on the component, the connection to the server is already cut and it's likely that the server is just shutting down at that point.

I would recommend you wrap the call within a try..catch and swallow the task cancelled exception in that situation.


> 1. I also have some local references in my component that need disposing, but implementing both the IDisposable and IAsyncDisposable stops the IDisposable.Dispose being called, even after removing the async keyword from it as you recommended.
>    I could add these synchronous disposes to the IAsyncDisposable but this page seems to suggest both should work
>    https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync
>    "Implement both dispose and async dispose patterns"

We only call DisposeAsync when the component implements both IDisposable and IAsyncDisposable. The guidance you are receiving is general purpose guidance based on not the lack of knowledge about the context where the type is being used. In Blazor, we recommend you implement IAsyncDisposable moving forward.

> 2\. Should I be adding the GC.SuppressFinalize(this); to my IAsyncDisposable.DisposeAsync and IDisposable.Dispose
>     My understanding of this is to let the garbage collector know we have manually cleaned up the object so it doesn't need to (but not quite sure). I have seen code samples where some people call it and some don't.

I don't remember the details about it, but it doesn't hurt, I believe that will inform the GC it doesn't have to run any finalizer, but it's very likely you don't have one anyways.

> 3\. bit of a async noob question here.
>     as my javascript RemoveInputKeyboardEventHandler does not return a value should I be awaiting it when calling InvokeVoidAsync.
>     or should I make it return a value or something just so it can be awaited correctly?

You can 'fire and forget' the call by not awaiting it, but you need to make sure no exceptions bubble up.

> 4\. does my javascript code in RemoveInputKeyboardEventHandler need to be async, ie "async function RemoveInputKeyboardEventHandler(p_ControlID)"

Your api can be synchronous but the call will be asynchronous since it's blazor server and has to go over the network.

**Comment by javiercn** [comment]
You shouldn't need to do anything within on page refresh since the page is going away and all the state on the page will be discarded.

**Comment by ScottyBlazor** [comment]
Hi Javier, Thanks for the reply

so it sounds like in blazor there is no good way to clean up your javascript references if the user refreshes the page, is this correct?

I am already catching the TaskCanceledException exception in my custom javascript dispose method "RemoveInputKeyboardEventHandler"
but I often leave the "break on all errors" exception setting on in visual studio to make debugging issues easier, so this is a little annoying as it still breaks on these errors before they are trapped.
and to make things worse we use identity on our web page, so every time i need to do an identity login, etc I will get these (as it has to break out to MVC as described here https://chrissainty.com/securing-your-blazor-apps-introduction-to-authentication-with-blazor/  I asked a question in the comments there " Scott • 5 months ago"

also in my full code sample (not posted here) when I add a javascript addEventListener I am also passing in a DotNetObjectReference to my component, and storing it in an expando property on the DOM control, so after checking the key pressed I can use it to call back to my blazor code
I clean this up in my javascript dispose method also (that is not working on page refresh).


I read that in modern browsers if you do not call the removeEventListener then the browser will eventually clean them up using something like a garbage collector
but what about my DotNetObjectReference stored in an expando property

is it safe to assume the browser will automatically clean up any javascript objects and I will not end up with memory leaks?


it seems it would be nice if there was a way to clean them up manually
especially because when navigating to a new page this can be achieved correctly using the IAsyncDisposable implementation.

short of having a good way to do this in blazor, do you know of a way I could add another event listener through javascript that will fire in the case of a page refresh in time to clean up the javascript references

**Comment by javiercn** [comment]
@ScottyBlazor let me add some more details.

The browser is connected to JavaScript via a websocket. When the user performs a full navigation (to Identity, or just F5) it will get rid of all the state on the page, so there is no need for you to cleanup any JavaScript state.

Any state you have on the client (handles you setup, dotnet object references, etc.) will go away at that point.

When the user performs a full navigation it will disconnect the websocket. Blazor server will remain unaware of this for a few seconds, and then enter a "disconected" state. At this point blazor doesn't know if the connection went down because you were inside a tunnel or because the user decided to terminate it.

When a few minutes have passed an the user hasn't come back, Blazor will decide to terminate the current circuit, at which time it will dispose all the components on the page. By the time that happens, the connection to the browser is long gone, so you can't perform any javascript interop.

You don't need to clean any state in the browser at that point because the browser has already done it when it navigated away and there is no connection to communicate back to the browser. The only thing left for you is to cleanup any state on the server you'll be holding on to; that is, existing components that get disposed, dotnet object references that you were holding on to on the server and so on.

Even if you didn't clean any of them up, it's very likely all of them can be garbage collected, since they are no longer referenced by any memory on the server.

There are no events that run reliably on page unload, you could try to use the `unload` event but that doesn't always fire in most browsers or use the `onbeforeunload` but nothing guarantees you that there isn't another handler that will prevent the page from actually unloading. There are new events in the browser like `pageHide` and similar that might also be of use here.

Hope this helps clarify things.

**Comment by ScottyBlazor** [comment]
Hi Javier, thank you very much for explaining this in detail, it is much appreciated
