### ISSUE TITLE
Request Throttling for ASP.NET Core

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#29933]
## Summary

1-2 sentences. Say what this is about.

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by Kahbazi** [comment]
@davidfowl Do you accept PR for this? 😅 https://github.com/Kahbazi/ThrottlR

**Comment by davidfowl** [comment]
@Kahbazi based on the name alone, yes! But no, there's a bunch of design work that needs to happen. I'm sure the ideas are very similar though so maybe once I write down what has been done thus far the stars will align.

**Comment by halter73** [comment]
I hope this will subsume/replace [Microsoft.AspNetCore.ConcurrencyLimiter](https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/). See https://github.com/dotnet/aspnetcore/issues/10702 for the original epic.

**Comment by davidfowl** [comment]
I think if the abstraction is done right it might be able to replace the concurrency limiter

**Comment by halter73** [comment]
I closed https://github.com/dotnet/aspnetcore/issues/19823 which asks for action-based (or endpoint routing based) concurrency limit support. I think this design should cover that by allowing for the implementation of hard concurrency limits and per-endpoint configuration.

**Comment by msschl** [comment]
@davidfowl Any news on this? Is it still on track for 6.0?

Will there be an IP based request throttling variant?

**Comment by compgumby** [comment]
I would love throttling on the Blazor virtualizer. The ItemsProvider is called with no regard for latency in that call. In my scenario, the items provider issues a database call which takes some time. Not a lot... but long enough such that a user could keep scrolling. As they do, the ItemsProvider calls just stack up. What I would prefer is all but the most recent data requests be discarded while a current fetch is underway. When the user finally stops scrolling, the most recent data request could then become the final request. 

Obviously, it has to be configurable because different data sources behave differently - but right now, if a user gets impatient and continues to scroll, that ItemsProvider function gets hammered and the SQL calls just stack up. Because I'm returning the right items count for the universe of results, they can also drag the scroll bar into a position that seems "right", but there's a myriad of calls that get stacked up while they're doing it. It would be nice if we could simply ignore scroll events until they're done for .5 seconds (or something like that.)

**Comment by wtgodbe** [comment]
Closing as done: https://github.com/dotnet/aspnetcore/tree/main/src/Middleware/RateLimiting

**Comment by compgumby** [comment]
@wtgodbe and @Tratcher - Thank you! I will give this a spin shortly. :)
