### ISSUE TITLE
Move Blazor Webassembly to Solution-Subfolder ensures that component-css files are not found

### ISSUE THREAD

**Issue by UrielMhezzek** [dotnet/aspnetcore#29958]
### Describe the bug
I create a subfolder in my solution and create a webass

### To Reproduce
1. Create a blank solution
2. Create a Subfolder named Frontend in Solution
3. Create a Blazor App (Blazor Webassembly App with HTTPS and  PWA) in Frontend folder
4. Migrate Project to .net 5 with this step by step guide https://docs.microsoft.com/de-de/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio example
5. Run the project 
6. See the missing css styles

**Comment by nurbat** [comment]
screenshot you solution dir and files in directory

**Comment by javiercn** [comment]
@UrielMhezzek thanks for contacting us.

Could you please validate the following?
* Remove your bin, obj folders and trigger a clean build.
* Create a 5.0 project. Move the webassembly bits to a subfolder and check for differences with your migration.
* If none of that works, could you provide a minimal repro project so that we can try to further help?
