### ISSUE TITLE
Ability to turn off CascadingParameter binding by type

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#29953]
We favour explicit coding in our organization. So we don't want parameters to bind by type magically as that could lead to unintentional binding. We want to be able to turn off binding by type CascadingParameter

**Comment by javiercn** [comment]
@MhAllan thanks for contacting us.

We don’t plan to offer this option, since it is a breaking behavior change with the current implementation and forces component authors to handle the case where this feature is not enabled and will require all component authors to update existing components to support this.

If binding by type does not work for your organization, it’s fine for you to avoid it in your own components, but it’s not something we plan to force component library authors or other users to deal with.

We understand that this is likely not what you’d like to hear, but this is something that we haven’t received significant feedback for, complicates our implementation and forces unnecessary complexity into other customers and library authors.

**Comment by MhAllan** [comment]
yeah, I was thinking of compiler options to ignore it, but then how libraries will do? I see.
