### ISSUE TITLE
Allow any component to contribute Cascading Values

### ISSUE THREAD

**Issue by david-driscoll** [dotnet/aspnetcore#30021]
## Summary

Today in Blazor there is only one limited way to provide values for child components down stream, using `<CascadingValue />`.  However if your component needs to provide many values or the values need to vary greatly, it becomes cumbersome and error prone to manage.

## Motivation and goals

The motivation is to allow developers to create components that can contribute Cascading Values.  To expose multiple cascading components today requires deep nesting `<CascadingValue />` in your template or some frustrating [RenderTree logic](https://github.com/david-driscoll/blazorify/blob/36d476a534f453ef089e99ae185826b1319abbb4/RazorClassLibrary1/ReactiveObjectComponent.cs#L34).  The goal here is to allow developers the freedom to provide any value to downstream components that they want to, and simplify some of the more advanced scenarios.

## In scope

* Externalize the ability to provide CascadingValues
* Allow multiple values to be provided by a given component

## Out of scope

* No changes to how cascading parameters are consumed
* No breaking changes

## Risks / unknowns

* Providing many cascading values could cause a performance issues
  * Is this better or worse  than creating a tree 10 `<CascadingValue />`s deep?
* With great power comes great responsibility, this feature will likely be more advanced, and developers could implement it incorrectly.

## Examples
Using #29971 as a reference, and omitting some data types for brevity.  I'm ignoring the subscription logic as that will be a talking point I think.

### Example 1 - A router that provides previous and next routes
This example is if there was a router that wanted to be able to provide location history for the previous and next routes. If for example you're in the middle of the history stack, you would have a "next" value.

```csharp
class Router : ComponentBase, ICascadingValueComponent
{
    public bool HasValue(Type valueType, string valueName)
    {
        return valueType == typeof(RouteData);
    }

    public object GetValue(Type valueType, string valueName)
    {
        if (valueType != typeof(RouteData)) return null;
        return valueName switch {
            "PreviousRoute" => _previousRoute,
            "NextRoute" => _nextRoute,
            _ => _currentRoute,
        };
    }
    public bool IsFixed { get; } = false;
    public void Subscribe(IComponentState subscriber) => ...;
    public void Unsubscribe(IComponentState subscriber) => ...;
}
```

### Example 2 - Themeable Components
This is modeled after [Vuetify](https://vuetifyjs.com/) where one component can change influence it's children, such that one section might be dark mode, and another not.

```csharp
class Card : ComponentBase, ICascadingValueComponent
{
    public bool HasValue(Type valueType, string valueName)
    {
        return valueType == typeof(ThemeData) && _theme != null; // allows for chaining up to other parents.
    }

    public object GetValue(Type valueType, string valueName)
    {
        if (valueType != typeof(ThemeData) || _theme == null) return null;
        return _theme;
    }
    public bool IsFixed { get; } = false;
    public void Subscribe(IComponentState subscriber) => ...;
    public void Unsubscribe(IComponentState subscriber) => ...;
}
```

There are other scenarios like using a DI container or dictionary to provide cascading values dynamically.

# Detailed design
TBD -- see #29971 for a prototype (not final design!)

# References
* [Vue.js provide / inject](https://vuejs.org/v2/api/#provide-inject)

**Comment by javiercn** [comment]
@david-driscoll thanks for adding a design proposal.

Here are some of my thoughts, I used quotes where appropriate to make it easier to correlate to different parts of the proposal.

It seems to me that the main motivation is to make it easier to provide multiple cascading values at once, am I correct?

> The motivation is to allow developers to create components that can contribute Cascading Values.

I think this is already possible today and that nothing we do changes this. Devs can do this today using the existing `CascadingValue` component.

> To expose multiple cascading components today requires deep nesting <CascadingValue /> in your template or some frustrating RenderTree logic. 

This might be true, however I wonder how common this scenario is in applications. Do the majority of your components need to share multiple cascading values downstream or is it more likely a minority of components in your app?

> The goal here is to allow developers the freedom to provide any value to downstream components that they want to, and simplify some of the more advanced scenarios.

I think that this is the case already, nothing prevents a component from using the existing `CascadingValue` primitive one or more times to provide as many values as it wants.

WRT to simplifying more advanced scenarios, I'm not sure that it's the right goal to optimize for. Advanced scenarios are "rare" by definition and we shouldn't optimize a design for them at the cost of adding complexity or new concepts that everyone needs to understand.

I share the concerns over the risks you point out in the risk section:

> * Providing many cascading values could cause a performance issues
          Is this better or worse than creating a tree 10 <CascadingValue />s deep?

* I don't think this will necessarily have a negative impact on perf, based on the fact that 1, I don't expect this to be common in an application.
* The number of cascading values when passing multiple components won't likely be huge.

> * With great power comes great responsibility, this feature will likely be more advanced, and developers could implement it incorrectly.

This is the part that worries me the most. What happens when things go wrong:
* How easy/hard is to get the implementation right on your own component.
* Is it easier/harder than relying on `CascadingValue` to do it?
* How can a bad implementation affect the performance of the application.

I'm worried about this leading to some libraries not implementing this in a performant way and as they become popular, negatively impact the perception on folks about the performance characteristics of Blazor.

Finally, I would add a couple more questions:
* Are the scenarios achievable with the existing framework primitives?
* Are there alternative ways of achieving the same goals?

**Comment by SteveSandersonMS** [comment]
+1 to @javier's points, and thanks @david-driscoll for writing up the proposal. This really does help clarify what you're suggesting and gives us a good context to discuss the pros/cons/necessity/alternatives.

As a point about the overall feature area, it's worth thinking about pub/sub systems in general. Overall, pub/sub systems can be arbitrarily sophisticated and include arbitrary scenario-specific features and behaviors. There are whole large libraries dedicated to pub/sub management. Cascading values aren't meant to expand to cover all possible pub/sub requirements, but rather are intended as a specific low-level ancestor->descendant flow that you can build application-specific behaviors on.

For example, if you want to vary dynamically the things that are provided from a certain component, you could do that today on cascading values by cascading a "publisher" object from your own pub/sub system, and then recipients could use your own APIs to subscribe to notifications about whatever things your own pub/sub system can supply. This lets you implement any messaging semantics that you want.

We have always expected to one day extend `CascadingValue` so that it can supply multiple items (hence no need to nest them), but even then a viable alternative is just to wrap up the set of things you want to supply into a single container object and supply that. I'm not suggesting this makes it irrelevant to want to supply multiple items, just explaining why we haven't prioritised it above other features.

**Comment by david-driscoll** [comment]
So I've created this example to demonstrate the issue I've personally run into (and why I joined in on the conversation in #18743)

https://github.com/david-driscoll/blazor-cascading-value-example

Basically if you have a CascadingValue that is optional, in order to render properly you have to create two different component trees.  One with the CascadingValue and one without.  
This either leads to a component tree that feels really clunky:
https://github.com/david-driscoll/blazor-cascading-value-example/blob/master/Shared/CustomParent.razor#L1-L19

In addition if you want to share this behavior you have to ensure that every each component executes the same root render method before rending it's content as well.


https://github.com/david-driscoll/blazor-cascading-value-example/blob/master/Shared/CustomParent.razor#L1-L19

**Comment by david-driscoll** [comment]
So I've created this example to demonstrate the issue I've personally run into (and why I joined in on the conversation in #18743)

https://github.com/david-driscoll/blazor-cascading-value-example

Basically if you have a CascadingValue that is optional, in order to render properly you have to create two different component trees.  One with the CascadingValue and one without.  

This either leads to a razor file that feels really clunky:
https://github.com/david-driscoll/blazor-cascading-value-example/blob/master/Shared/CustomParent.razor#L1-L19

Or down the render tree rabbit hole:
https://github.com/david-driscoll/blazor-cascading-value-example/blob/master/Shared/Themeable.cs#L14-L25

In addition if you want to share this behavior you have to ensure that every each component executes the same root render method before rending it's content as well, which leads to a lot of code duplication, which would be wonderful to avoid if possible.

https://github.com/david-driscoll/blazor-cascading-value-example/blob/master/Shared/CustomParent.razor#L1-L19

**Comment by david-driscoll** [comment]
@SteveSandersonMS I don't think that a full pub/sub system is needed, I understand that today ICascadingComponent uses a pub/sub implementation.  Ideally for this feature we could hide that behind an abstraction and give the consumer a simpler way to trigger changes.

Ideas:
```
bool HasChanges();
```
The method will reset it's underlying value when called -- this puts the work on the consumer.

```
void InitializeCascadingValues(IComponentState state);
```
This method gets called once when the component is instantiated, and then behind the scenes the subscriptions gets managed.  Then the consumer only has to keep a reference to `IComponentState` and call it when changes happen.

**Comment by javiercn** [comment]
@david-driscoll I'm not sure I understand what you are doing things that way within your code.

Here is an alternate implementation for a multi cascading value component (modulo bugs, design, etc.) which is what I would do if I had to implement something like this:

```csharp
    public class MultiValueCascadingComponent : IComponent
    {
        private RenderHandle _handle;

        public void Attach(RenderHandle renderHandle)
        {
            _handle = renderHandle;
        }

        public Task SetParametersAsync(ParameterView parameters)
        {
            _handle.Render(RenderCascadingComponents(parameters));
            return Task.CompletedTask;
        }

        private RenderFragment RenderCascadingComponents(ParameterView parameters)
        {
            var rest = ToList(parameters, out var childContent);
            return builder =>
            {
                RenderCascadingValue(builder, childContent, rest, 0);
            };

            List<ParameterValue> ToList(ParameterView parameters, out RenderFragment childContent)
            {
                var result = new List<ParameterValue>();
                childContent = null;
                foreach (var parameter in parameters)
                {
                    if (parameter.Cascading)
                    {
                        continue;
                    }
                    if (parameter.Name == "ChildContent")
                    {
                        childContent = (RenderFragment)parameter.Value;
                        continue;
                    }
                    result.Add(parameter);
                }

                return result;
            }

            void RenderCascadingValue(RenderTreeBuilder builder, RenderFragment childContent, List<ParameterValue> parameters, int listIndex, int currentIndex = 0)
            {
                if (listIndex >= parameters.Count)
                {
                    return;
                }

                var parameter = parameters[listIndex];
                var value = (ICascadingValueEntry)parameter.Value;
                builder.OpenComponent(currentIndex++, value.CascadingValueType);
                builder.AddAttribute(currentIndex++, nameof(CascadingValue<object>.Value), value.EntryValue);

                RenderFragment next = listIndex == parameters.Count - 1 ? childContent :
                    fragment => RenderCascadingValue(fragment, childContent, parameters, listIndex + 1, currentIndex + 2);

                builder.AddAttribute(currentIndex++, nameof(CascadingValue<object>.ChildContent), next);
                builder.CloseComponent();
            }
        }
    }

    internal interface ICascadingValueEntry
    {
        Type CascadingValueType { get; }
        object EntryValue { get; }
    }

    public abstract record CascadingValueEntry { }

    public record CascadingValueEntry<T>(T Value) : CascadingValueEntry, ICascadingValueEntry
    {
        Type ICascadingValueEntry.CascadingValueType => typeof(CascadingValue<T>);
        object ICascadingValueEntry.EntryValue => Value;
    }
```

And here is it in use:
```razor
<MultiValueCascadingComponent @attributes="_parameters">   
    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</MultiValueCascadingComponent>

@code{
    Dictionary<string, object> _parameters = new()
    {
        ["Parameter1"] = new CascadingValueEntry<bool>(true),
        ["Parameter2"] = new CascadingValueEntry<string>("Javier")
    };
}
```

Would something like this not work?

**Comment by SteveSandersonMS** [comment]
For an optional cascading value, would it suffice to define some component like the following?

```razor
'@* OptionalCascadingValue.razor *@

@if (Value == null)
{
    @ChildContent
}
else
{
    <CascadingValue IsFixed="@IsFixed" Value="@Value">@ChildContent</CascadingValue>
}

@code {
    [Parameter] public object Value { get; set; }
    [Parameter] public bool IsFixed { get; set; }
    [Parameter] public RenderFragment ChildContent { get; set; }
}
```

Then you can use `<OptionalCascadingValue>` anywhere that you'd have used `<CascadingValue>` before.

I haven't actually tried this BTW so it's quite possible there are some typos or mistakes in this code!

**Comment by david-driscoll** [comment]
All these are possible, it would be great if blazor provided this natively, so it doesn't have to be rebuilt by others.

Using an optional cascading value component would force a re-render of the entire tree?  So if a value swapped near the top of the application, that would essentially redraw everything? Or is the re-render logic more isolated to each individual component than I'm aware.

**Comment by javiercn** [comment]
> All these are possible, it would be great if blazor provided this natively, so it doesn't have to be rebuilt by others.

Why can't this be part of a library that someone on the community builds that the community can consume instead?  

We can always put features in the framework, there is no doubt about it, but each feature we build comes with an initial development cost (design, coding, test, API review, docs) and an associated maintenance cost (GH issues for the feature, maintaining tests over time, etc.)

Using an optional cascading value component would force a re-render of the entire tree? So if a value swapped near the top of the application, that would essentially redraw everything? Or is the re-render logic more isolated to each individual component than I'm aware.

It depends on a case by case basis. Short answer, if you change values at the top, it trigger a re-render that trickles down to components below. That said, there is a diffing algorithm that determines when the parameters for a component haven't changed and avoids re-rendering those components.

**Comment by SteveSandersonMS** [comment]
> Using an optional cascading value component would force a re-render of the entire tree? So if a value swapped near the top of the application, that would essentially redraw everything? Or is the re-render logic more isolated to each individual component than I'm aware.

Cascading values in general only cause re-rendering of their *immediate* children, plus any deeper descendants that specifically subscribe to their value. That is unchanged with `OptionalCascadingValue`.

**Comment by craigajohnson** [comment]
While the above solutions would be useful in certain situations I prefer to explicitly define what I am passing down from parent node to child node, including knowledge of the parent itself

I currently have a ChildComponent<TParent> that inherits from BaseComponent and then a small hack to automatically supply the TParent instance to the Child.

It would be much better to remove the hack and gain access to TParent through the front door - perhaps a [Parent] attribute on a property in the Child since I assume just supplying a Parent property in ComponentBase is a breaking change.

From there I can do whatever I want since I can converse with the parent and not have to wire up pub/sub, callbacks, etc. (though we do that in many cases but if it's just parent->child I can now do a lot with TParent in an easy, strongly-typed way)

And yes I can do a Parent="this" param but I would prefer not to
