### ISSUE TITLE
[blazor] @bind:event="oninput" on input type="number" make it unable to input minus character

### ISSUE THREAD

**Issue by Thaina** [dotnet/aspnetcore#30033]
### To Reproduce

```html
<input type="number" min="-1" max="1" step="0.01" @bind="someFloat" @bind:event="oninput" />


@code {
    public float someFloat = 0;
}
```

Then try to remove value or input minus by select all character will reset value to 0. It seem blazor try to bind value on every change and reset every invalid value instantly

But try to start by minus sign `-` or dot `.` or clearing the field should consider valid for input number. Can we fix this?

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   5.0.102     
 Commit:    71365b4d42  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19042
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\
```

vscode 1.53.0

**Comment by SteveSandersonMS** [comment]
If you use `@bind:event="oninput"` then you're asking the binding system to bind on every keystroke. This inherently supposes that every state along the way will be valid and representable in the type you're binding to.

Since in your case you want to allow for intermediate invalid/incomplete states, I recommend binding to a `string` and not to a `float`. This way you can put in your own arbitrary logic to determine which incomplete/invalid states to ignore and which ones to revert. For example, if you only want to react to parseable inputs, you could do this:

```razor
<input type="number" min="-1" max="1" step="0.01" @bind="TypedValue" @bind:event="oninput" />

<p>Value: @someFloat</p>

@code {
    float someFloat = 0;

    string typedValue;
    string TypedValue
    {
        get => typedValue;
        set
        {
            typedValue = value;

            // Implement any logic you want for deciding which strings to accept
            if (float.TryParse(typedValue, out var parsedValue))
            {
                someFloat = parsedValue;
            }
            else if (string.IsNullOrEmpty(typedValue))
            {
                someFloat = 0;
            }
        }
    }
}
```

**Comment by Thaina** [comment]
@SteveSandersonMS Thank you for your response. Still I think the behaviour I describe might be used in many places. Is it possible to extend custom binding type? Maybe I would made `@bind:event="onvalidinput"` or something similar

**Comment by SteveSandersonMS** [comment]
If it becomes a common request we can certainly consider it. So far it hasn’t been requested often. Thanks for reporting it though!
