### ISSUE TITLE
Memory Leak in Blazor project

### ISSUE THREAD

**Issue by Suriya-Murugan** [dotnet/aspnetcore#30064]
Hi Team,

We are facing when using C#(ASP.NET Core) library in blazor project. Trying to read text file, using stream reader. 

We have attached sample for reference.

- Try running the sample.
- We have used StreamReader which load text file.
- For each iteration(looping), Memory gets increased and not released.

Please check this and share the details.

[BlazorProject.zip](https://github.com/dotnet/aspnetcore/files/5957526/BlazorProject.zip)

Screenshot:

![image](https://user-images.githubusercontent.com/43063728/107499494-044acf00-6bbb-11eb-930f-5449d0b5b6e6.png)

**Comment by javiercn** [comment]
@Suriya-Murugan thanks for contacting us.

This is not a memory leak.

Seems like you have the debugger attached and its likely a debug build.

In addition to that, it seems that you are still holding a reference in the stack to the stream you seem to want to collect. Finally, the call to GC.Collect you have in your code is not effective because you are reading a large document into a string which is going to be allocated on the Large Object Heap.

Regular collections won't free space in the LOH, to force that you need to do something like `GC.Collect(2, GCCollectionMode.Forced);`

If you null out the reference to the stream and trigger a full collection you'll observe the memory go down and become stable.

Hope this helps
