### ISSUE TITLE
Improvements To Css Isolation To Make It Like Javascript Isolation

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#30081]
I would like a way eventually to have css isolation that works like javascript isolation where the library can do the linking.  That way when others use the library that has css in it, they don't have to link up.  The way it works in javascript isolation works perfectly.
Currently in css isolation, it only isolates for a component.  However, if several components needs the styles.
Or if you want to share the styles so you don't have to rewrite them or have to include them in the html each time, that would be great.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

Can you clarify what the ask here is maybe with an example?

**Comment by musictopia2** [comment]
An example is you create a razor class library.  Maybe even create some class where you manually specify the path to the css which can be used in all projects.  In this case, then the user does not have to specify the path to the css because the razor class library already did it.  Just like in javascript isolation, you can create a javascript class and in there, specify the javascript to use.  In that case, then any user it would just work without having to link any javascript files because the class library already handled that part.

**Comment by javiercn** [comment]
@musictopia2 thanks for the additional details.

From what we understand you want the ability to automatically import CSS files from your razor class library into an application. 

That is not something we plan to do since it essentially makes Blazor into a package manager and forces us to deal with all the concerns a package manager deals with like injection order, conflicting dependencies, etc.

We are able to offer some isolation in the form of JS isolation because the language provides support for it, and we are able to do it for scoped CSS files because by definition they are scoped to the file they target so there is no chance of version conflicts or file order causing problems, however, there is no such thing fo CSS files in general.
