### ISSUE TITLE
Indentation problem in Razor View on VS2019 Preview 4.0

### ISSUE THREAD

**Issue by yannick-vachon-reseautage** [dotnet/aspnetcore#30080]
Since the latest update to VS2019 Preview 4.0 today, the indentation in my Razor Views is broken. Actually, while searching for an answer, I found that the problem existed a few years ago as explained here: #4997

The problem I see is the same one as this. I have confirmed with the same views on a different computer that is running the latest non-preview version of VS2019 and it works as expected. It also worked fine on Preview 3.0.

To reproduce, I only use the Format document under the Edit - Advanced menu.

I'm on ASP.Net Core 5.0.

Here is a picture I have on my side after doing the Format.

![indent](https://user-images.githubusercontent.com/70272218/107577315-47f40780-6bc0-11eb-9107-1af308a6a646.png)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue is fixed in the latest Visual Studio 2022. If you'd like to try this tooling out you can download the latest VS 2022 and re-try your scenario.

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
