### ISSUE TITLE
blazor + parameter + array of Enum

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#30097]
```
[Parameter] public Enum Value { get; set; }
[Parameter] public IReadOnlyList<Enum> Values { get; set; }
```
![image](https://user-images.githubusercontent.com/12803050/107646434-bc7a8500-6c58-11eb-994f-b9f49ebc301f.png)

When I pass an enum by parameter, it works normally.
But when I try to pass an array of enum (or any type of collection) it is giving error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'System.Collections.Generic.IReadOnlyList<VerusDate.Shared.Enum.Intent>' to 'System.Collections.Generic.IReadOnlyList<System.Enum>'	VerusDate.Web	...	Active
```

**Comment by javiercn** [comment]
@drma-dev thanks for contacting us.

This is by design and is a behavior of the runtime `Intent` is a subclass `Enum`, but `System.Collections.Generic.IReadOnlyList<VerusDate.Shared.Enum.Intent>` is not a subclass of `System.Collections.Generic.IReadOnlyList<System.Enum>`

**Comment by drma-dev** [comment]
I know. But the question is: why does the parameter convert when it is alone and not in a collection?

**Comment by javiercn** [comment]
@drma-dev I'm not sure I follow.

That's just how C# works. We don't convert anything, you pass in an enum of type Intent and asign it to a variable of type Enum. You can do the same thing in C#.

```csharp
public enum Intent { 
     SomeValue
}
Enum variable;
variable = Intent.SomeValue;
```

You can't do that with lists because they are not covariant, and that's why it's failing. The runtime happily upcasts Intent to Enum, but can't do the same thing with the list.
