### ISSUE TITLE
Ability to Disable TypeCheck (Maybe as an argument to ParameterAttribute)

### ISSUE THREAD

**Issue by legistek** [dotnet/aspnetcore#30110]
### Is your feature request related to a problem? Please describe.
I'm working on an MVVM system with data-binding for Blazor. In my Razor markup I would like to be able to set bindings interchangeably with direct values, for example:

```
public class MVVMButton : MVVMComponentBase {
     [Parameter(TypeCheck=false)]  // see below
     public ICommand { get; set; }
     ...
}
```

then in a consuming page:

`<MVVMButton Command=@this.WhateverCommand>`

where `WhateverCommand` is just a member of type `ICommand` that won't change.

OR

`<MVVMButton Command=@(Bind(source: someINPCobject, path: "PropertyPath"))>` 

where `Bind` returns a `Binding` instance,

What I would do is override `SetParametersAsync` in `MVVMComponentBase` and if the value is of the `Binding` type then I would perform the binding operation (subscribing to INPC `PropertyChanged` and all that), or if not just assign the value directly.

My _problem_ is that I'm being thwarted by `Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck` being injected into the `razor.g.cs` files, which I am powerless to stop, and so it won't compile.

### Describe the solution you'd like
I think a simple solution would be to add a `bool TypeCheck` property to the `Parameter` attribute, which would default to `true`, but which I could set to `false` to disable the type check for any parameters that I want the option of assigning a `Binding` (or anything else) to.

Notably if I remove the `Parameter` attribute entirely, and override `SetParametersAsync`, things work the way I would like, except that I lose Intellisense for those properties. So that's really not a viable workaround. 

I also tried making all the bindable properties `dynamic`, and it does work, but `dynamic` is so evil, I might as well just use Javascript at that point.

### Additional context
It looks like there have periodically been other issues that have come up with `TypeCheck`, so it might be worth implementing this anyway just as a workaround for potential future issues.

**Comment by javiercn** [comment]
@legistek thanks for contacting us.

We don't think this is something we want to add to the framework. It adds a concept for all users to know about and we haven't received significant feedback about it to think the demand outweighs the added complexity. 

Razor markup is meant to represent code, and in this case you seem to want a feature that "build a language" on top of the language, in a similar fashion to XAML.

If you still want to persist this avenue, I would suggest trying out to get it to work within the languages. Maybe an implicit conversion operator might help you coerce your binding into a common type that you can use in both cases.

**Comment by legistek** [comment]
> Maybe an implicit conversion operator might help you coerce your binding into a common type that you can use in both cases.

Heh well actually I had been doing that. I made a `BindableValue<T>` structure from which either `T` or `Binding` could both be implicitly cast and my components' bindable properties were all of that type. The drawback is that we then have tens of thousands of superfluous objects being instantiated at run time and taking up memory which serve no purpose other than as a workaround to a restriction that you put into the language. If we were talking about natively compiled apps that would be no issue, but performance is borderline with interpreted WASM as it is.

As for the demand, perhaps no one has requested this specific change, but, I'm sure you will find that there is widespread interest in making Blazor MVVM friendly. This unfortunately is a blocker to that.

**Comment by legistek** [comment]
Well I devised a workaround to get what I want. It's a total hack. Frankly it's revolting. But it works. And I'm not gonna tell you guys what it is, because I genuinely fear you'll try to prevent me from doing it in a future release.

To the point "you seem to want a feature that "build a language" on top of the language, in a similar fashion to XAML.", you're right. I think keeping Razor so rigid is a mistake. The team has added built in directives like @bind and such here and there when they deem fit, but you should give the consumers the ability to do the same. The _framework_ allows things to be very flexible, but not the language. XAML's flexibility is what made it so successful. Razor's rigidity is a weakness. Just my thoughts.

**Comment by javiercn** [comment]
> As for the demand, perhaps no one has requested this specific change, but, I'm sure you will find that there is widespread interest in making Blazor MVVM friendly. This unfortunately is a blocker to that and unfortunately it seems that this team has been consistently resistant to ANY Blazor changes that would make it more MVVM friendly or help facilitate cross-platform development generally (i.e. web <> desktop <> mobile). Actually not just this team, but the entire Microsoft enterprise. It's been baffling for years and remains so.

We definitely want to make Blazor friendly and accessible for as many types of programming models as we can, but not at any cost. There are already plenty of MVVM implementations for Blazor out there and they all seem to work without requiring extra features from the runtime/compiler.

I can tell you that our goal is to help as many people as possible, however we need to balance the needs of all our customers when we add features to the framework, and do so carefully, since in many cases we can't change them/take them back if we make a mistake, so we tend to be conservative about it.

In this case, the request includes an addition in a public API change that every developer will now have to reason about in their code whether or not they are using an MVVM framework that requires it and that includes a non trivial change in the compiler that increases its complexity even further and that will add to the maintenance cost of the component going forward. 

If this were a blocker for the majority of users we would consider alternatives, but we don't have data to claim that, and based on that we don't have a good reason to prioritize this request over others, that said, if that changes, we'll definitely reconsider.

> Well I devised a workaround to get what I want. It's a total hack. Frankly it's revolting. But it works. And I'm not gonna tell you guys what it is, because I genuinely fear you'll try to prevent me from doing it in a future release.

We don't have any intention to block anything that you want to do in your own code unless we determine there are security risks associated with it, in which case, we generally at most advise against it. 

It's fine if you want to keep your solution to yourself, however, keep in mind that we might not consider it hacky as you think it is, you might be missing on helping other customers in your same position, and we might change the behavior and unknowingly break it in the future if we don't know about it.

> To the point "you seem to want a feature that "build a language" on top of the language, in a similar fashion to XAML.", you're right. I think keeping Razor so rigid is a mistake. The team has added built in directives like @Bind and such here and there when they deem fit, but you should give the consumers the ability to do the same. The _framework_ allows things to be very flexible, but not the language. XAML's flexibility is what made it so successful. Razor's rigidity is a weakness. Just my thoughts.

There is a fundamental difference in philosophy here. Directives like `@bind` in Blazor are just syntactic sugar to what you can achieve with code, in this sample the equivalent is an attribute and an onchange handler.

Blazor and XAML are different languages with different characteristics, each one with their own strong points and weaknesses. We don't mind if you want to borrow concepts and primitives from XAML and use them in your Blazor app if that's what you are most familiar with. However, at the same time, is not our goal to bring over features from XAML to converge the two languages into one.

If we think there's a useful feature to be had in Blazor we will consider adding it, but if there is already an alternative way of achieving the same goal, it is unlikely that we add a second or third way of doing so.

While in the end we might have different opinions I hope you understand that we are not trying to block you in any way and that if we think that there's something reasonable we can do to help, we will. At the same time I hope you understand we must balance the tradeoffs of adding new features to the framework across all of our customers, which might not share your same opinions, and prioritize requests accordingly.

**Comment by legistek** [comment]
Hey man, I promise I'm not going to be one of those obnoxious people who goes on a tirade whenever a suggestion of theirs isn't adopted. I'm one of the biggest Microsoft fans out there; we were in Bizspark, then Startups, and now use Azure exclusively. So understand this is coming from a place of love.

_That having been said,_ I have to call out bad decisions when I see them. And I don't mean saying no to this particular ask. it's that across the entire Microsoft enterprise there is, at best, ambivalence, and at worst, resistance, to the idea of sharing code between web and other platforms, or any feature request that pushes in that direction.

I wish I could find it, but very early when Blazor was announced, one of the main guys said something to the effect of porting or reusing code between Blazor and other frontend platforms like WPF or UWP was not what Blazor was meant for. 

Similarly there was this recent issue:
https://github.com/dotnet/aspnetcore/issues/26677

> There is a large MVVM WPF application which needs to move to the web

The response:

> This ask is not aligned with our vision

And then on the other side of the building, you have MAUI, where dozens of commenting devs (which probably equate to hundreds or thousands out there) have been vocal about wanting MAUI to support web via Blazor. And the response from Microsoft? Total silence.

https://github.com/dotnet/maui/discussions/62

So you say, well we can do this ourselves because the framework is flexible. And until I hit this blocker, I thought that was true. 

> There are already plenty of MVVM implementations for Blazor out there and they all seem to work without requiring extra features from the runtime/compiler.

I have seen MVVM frameworks that do some binding within the component definition itself, but they require you to re-render your entire component (with `StateHasChanged`) every time the viewmodel fires `PropertyChanged`. Blazor WASM does not have sufficient performance to support that.

For MVVM to work the way it was intended you have to be able to bind component _parameters_ directly to C# property paths. The only place this can be done is during the parameter setting phase, because that's the only time you have an actual instance of the component. But I can't even get to that point because of `TypeCheck` (without ugly hacks at least). Can you point me to an MVVM implementation for Blazor that allows you to bind to component parameters?

So that is the blocker.

Why do I fear you'd break my workaround on this issue if you knew what my hack was (and please trust me, it's UGLY)? Not out of cruelty. But you might consider it to be exploiting a weakness, and even though it's necessary to accomplish what I want to do (i.e. share code across web and other platforms), you guys don't seem to consider that something you want to support, so you might go ahead and make the change which would then break my framework.

Anyway thanks for being responsive. Never mind this particular issue, but I hope you'll take these broader issues about code sharing to heart.

**Comment by legistek** [comment]
You know what? I'm closing this and will just make a XAML -> Blazor compiler based on Portable.Xaml which I should have done from the beginning. Thanks again for listening.
