### ISSUE TITLE
Property value "get" returns 0 even though there's a value

### ISSUE THREAD

**Issue by danypellerin** [dotnet/aspnetcore#30147]
![issue-blazor wasm](https://user-images.githubusercontent.com/5531265/107792268-edbf8780-6d22-11eb-83f1-35414f68aadd.png)

This happens on the WASM in a blazor project. When in debug and hovering on c.Id you can see there is a value, but when you assign it to a variable it assigns the value 0. This causes the ToDictionary function to fail because of duplicate keys (0) while there is no Id with a value of 0 in the collection.

When I am in debug mode and I hover over c.Id, it shows the id, when I assign it to a variable and I hover over that variable it shows 0. How is that even possible?

Here's the simplified version of the code that fails
`private void CollectionToDictionary<T>(List<T> collection)
            where T : IUniqueResource
{
       var dictionary = collection.ToDictionary(t => t.Id, t => t);
       return dictionary;
}`

Here's the simplified code of the class implementing : IUniqueResource
`
    public interface IUniqueResource
    {
        public long Id { get; }
    }  

    public class BaseDealerLocation :  IUniqueResource
    {
            public long Id { get; set; }
    }

    public class DealerLocation : BaseDealerLocation
    {}

    public class GameTable : DealerLocation
    {}
`

Here's a simplified sample of what the data being passed to the method looks like:
`var gameTables = new List<GameTable> { 
                new GameTable { Id = 1 },
                new GameTable { Id = 2 },
                new GameTable { Id = 3 },
                new GameTable { Id = 4 },
                new GameTable { Id = 5 },
};`

**Comment by javiercn** [comment]
@danypellerin thanks for contacting us.

Can you debug the code in the browser dev tools and see if the issue also happens there?

/cc: @captainsafia

**Comment by danypellerin** [comment]
It sure does. The problem isn't only happening while debugging, I assigned the value to a variable only because I wanted to understand why the Dictionary was complaining about duplicate 0s when I knew there was no Id with a value of 0 in that list. When I checked the values in the immediate window it left me dumbfounded.

**Comment by javiercn** [comment]
@danypellerin thanks for the additional details.

I thought this was just about debugging, but it seems that it is about the actual code that is running.

Can you provide a minimal repro project that illustrates the issue and detailed steps on how to reproduce it? We need a minimal repro project, otherwise its very likely we miss something and are not able to reproduce it.

**Comment by danypellerin** [comment]
Exactly yes.

I can easily reproduce it at will in my current project, it's not a timing or concurrency issue. It would be easy to demonstrate, but I understand you need a repro project. 

I'm not exactly sure what preconditions are needed for it to happen. I'm currently working under tight deadlines so I'm not exactly sure when I can provide a repro project.

I'll try to see if I can come up with something by the end of this week.

**Comment by mkArtakMSFT** [comment]
Thanks @danypellerin.
We'll wait for you to share a small repro project so that we can move forward with this.

**Comment by danypellerin** [comment]
I was able to figure out what was causing the issue and create a small repro:
https://github.com/danypellerin/issue-repro-30147

Steps to reproduce:
- Click on menu item "Issue demo"
- Click on "Convert to dictionary" button

I found out the issue happens because the class hides inherited members from the base class. I fixed that in my code so the issue is gone. I still think this is an issue as I would never suspect that kind of error to happen under those circumstances.

**Comment by javiercn** [comment]
@danypellerin thanks for the additional details.

I believe this is the expected behavior. You are likely seeing a warning in the console about Item.Id hiding BaseItem.Id and a recomendation to use new on the property definition.

What's happening here is that you are deserializing the data into a list of `Item` and the serializer is setting `Item.Id` instead of `BaseItem.Id` (which is expected since Item is hiding BaseItem.Id on its definition).

Then your service requires a T that implements IUniqueResource, which is done by BaseItem, and that's why you can do `.Id` on the ToDictionary and why `BaseItem.Id` is picked up instead of `Item.Id`.

In essence, if you cracked open the class with ILSpy or similar you'd see it has two field for two Id properties, the issue is that the serializer is deserializing into one, and your code is trying to access the other.

**Comment by danypellerin** [comment]
In my original project the data does not come from deserializing but I get your point.

How do you explain when you are in debug mode and you evaluate the Id in the immediate window or by hovering you get the proper value, but when you try to assign it to a variable it assigns 0? This is very misleading, to say the least. I'd expect to get either 0 in both cases, which would have been fine, or the value in both cases.

That said I did get a warning, but I'd expect to get an error if it's going to be causing bugs such as that.

**Comment by danypellerin** [comment]
I did a quick read of this article (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier#:~:text=When%20used%20as%20a%20declaration,you%20get%20a%20compiler%20warning) where it says: "When you hide an inherited member, the derived version of the member replaces the base class version".

What was being passed to the method was the derived class so in that case I would expect to get the value from the derived class since it "replaces" the base class version. At least that's what normally happens with polymorphism.

After reading that article in the official documentation, I highly doubt this is the expected behavior. It's a fairly problematic side effect.

**Comment by javiercn** [comment]
> How do you explain when you are in debug mode and you evaluate the Id in the immediate window or by hovering you get the proper value, but when you try to assign it to a variable it assigns 0?

That might be a bug in the debugger/inmediate window where it's showing the field on the base class instead of the value the runtime produces (that's why the differences happen, but TBH this is a C# question, so don't take me as an authoritative source :))

> That said I did get a warning, but I'd expect to get an error if it's going to be causing bugs such as that.

This has been historically the C# behavior. WarningsAsErrors is always an option here. In general it's discouraged to hide members unless you truly know what you are doing.

> What was being passed to the method was the derived class so in that case I would expect to get the value from the derived class since it "replaces" the base class version. At least that's what normally happens with polymorphism.

That's not how hiding works. Your property is not virtual, and the binding to `get_Id()` is done at compile time based on the compile time type. Your generic method is calling IUniqueResource.Id which is implemented by BaseType

**Comment by danypellerin** [comment]
Well today I did improve my understanding of hiding members. (I didn't do that on purpose in my project, I just forgot to remove the properties after creating the base class).

I do get a better understanding of how hiding works. In that case I would just need to have the interface on the base class and the derived class. It's a little confusing, but it makes sense. 

Thanks for your help.
