### ISSUE TITLE
Blazor WASM(Core Hosted) Application hosted in azure does not retrieve data when an api request is made to the server.

### ISSUE THREAD

**Issue by SevvandhiN** [dotnet/aspnetcore#30169]
**Describe the bug**

When publishing a Blazor WASM ASP.NET Core hosted application to azure, it does not fetch the data when an api request is made to the server.  The mentioned issue occurs only on the azure site and does not occur when running the application locally. The same scenario works as expected in the server application.

**To Reproduce**

Local sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/BlazorApp-931563409-1741557075

Azure hosted link: https://blazorappserver20210209215632.azurewebsites.net/

1. Open and run the attached sample
2. You could see that the web api controller fetched the data. Hence the data displayed in the control of the dropdown.
3. The data will not be retrieved when the open azure hosted link. 

Any help would be helpful.

**Comment by javiercn** [comment]
@SevvandhiN thanks for contacting us.

We don't think there is a Blazor issue here and we believe there is an error in your app. 
![image](https://user-images.githubusercontent.com/6995051/107941190-2f784a00-6f3e-11eb-854e-edcfa9095499.png)

Unfortunately we can't help with those requests since they fall out of the scope of this issue tracker. We recommend you post a question on stackoverflow to get a better and faster answer. 

If you can clearly determine that this is a Blazor issue and produce a minimal repro project that demonstrates it, we will be happy to take a look.
