### ISSUE TITLE
Need to document that stopPropagation refers to Blazor's delegated events, not native DOM events

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#30199]
Hi,

I am designing a custom ComboBox component and have run into an issue which I believe is a bug. Please refer to the code snippet below.

Although I set ``@onclick:stopPropagation`` directive on ``<a>`` element, the click event still bubbles up to ``window`` object and `` newComponent.onWindowClick`` event is being triggered. Expected behavior is to suppress the click event from bubbling up the DOM hierarchy. This concept seems to be working if a parent Blazor component handles the click event - but in this case, I need to attach the event handler to the ``window`` object so that I can close the dropdown if user clicked outside of it.

Is this a bug? If not, how do I implement closing of the dropdown?

Thanks!

```razor
<div ...>
...
        <div @ref="m_divDropdownMenu">
            @if (IsDropdownMenuVisible)
            {
                <ul class="dropdown-menu d-block p-0" style="@DropdownStyle">
                    @foreach (var item in Items)
                    {
                        <li>
                            <a class="dropdown-item @GetItemCssClass(item)" href="#"
                                @onclick="() => OnItemClick(item)"
                                @onclick:preventDefault
                                @onclick:stopPropagation>@GetItemText(item)
                            </a>
                        </li>
                    }
                </ul>
            }
        </div>
</div>
```

```csharp
protected override async Task OnItemClick(TItem item)
{
    IsDropdownMenuVisible = false;
    await base.OnItemClick(item);
}
```

```javascript
export function register(componentDotNetRef, componentGuid, inptDropdown, btnDropdownToggle, divDropdownMenu) {
    let newComponent = lib.registerComponent(componentDotNetRef, componentGuid, 'BlzComboBox');

    ...

    // handle window click event
    newComponent.onWindowClick = function (event) {
        // check if dropdown can be closed
        let canClose = componentDotNetRef.invokeMethod("CanClose");
        if (canClose === true)
        {
            componentDotNetRef.invokeMethod("Close");
        }
    };

    window.addEventListener("click", newComponent.onWindowClick, false);
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `stopPropagation` directive attribute is used to stop propagation of events only within Blazor scope, not HTML DOM.
This is because Blazor uses event delegation internally, and events have to propagate to the root before Blazor deals with them.
We will look into updating our documentation on this topic to clarify this: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#stop-event-propagation

**Comment by daniel-p-tech** [comment]
Thank you for your response.

Is this something that will be addressed in the future or is it inherent to how Blazor works? I basically have no way to truly suppress propagation of an event triggered by a Blazor component.

**Comment by daniel-p-tech** [comment]
@SteveSandersonMS can you suggest how to get around this problem? Thanks.

**Comment by SteveSandersonMS** [comment]
@daniel-p-tech I'd recomment not using any kind of "stop propagation" mechanism for this, since that could interfere with entirely unrelated parts of your UI that are interested in observing click events.

Instead, I'd recommend modifying your JavaScript code so that it checks [the event object's `composedPath()` function](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) to see the bubbling path that the click event has followed. If any of the elements within the composed path have the CSS class name `dropdown-menu`, then you would not call `componentDotNetRef.invokeMethod("Close")`, because you know it was a click somewhere inside the dropdown.
