### ISSUE TITLE
[BlazozWebAssembly] NavLink not work isolated css

### ISSUE THREAD

**Issue by nurbat** [dotnet/aspnetcore#30207]
HTML RESULT BROWSER
![изображение](https://user-images.githubusercontent.com/5789051/108032621-7009bd80-703b-11eb-8574-0e6fbc695711.png)

HTML IN RAZOR
![изображение](https://user-images.githubusercontent.com/5789051/108032645-79932580-703b-11eb-90f4-84742a74ffae.png)

CSS IN RAZOR
![изображение](https://user-images.githubusercontent.com/5789051/108032706-916aa980-703b-11eb-8227-21faa7b79364.png)

**Comment by javiercn** [comment]
@nurbat thanks for contacting us.

CSS isolation only applies to HTML elements on a given file, not to components used in that file. If the scope were to be applied to those components, it would break their own CSS isolation.

It's not clear to us what you are suggesting doesn't work. If you are talking about the scope attribute not being applied to the `a` element is because that comes from the NavLink and can't be styled from outside.

We suspect your issue is that you are missing the `::deep` pseudo selector within your CSS rules. See https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support for details
