### ISSUE TITLE
Blazor server app having memory leak

### ISSUE THREAD

**Issue by PiramanayagamR** [dotnet/aspnetcore#30210]
### Describe the bug
I have faced the memory leak issue in Blazor server side application. 
By default, the memory consumed (Ex: 76.7 MB) in empty Blazor application. If we open the application in new tabs then memory has been increased gradually (77.6 MB, 78.7 MB etc). But while closing the browser tabs is not cleared.

### To Reproduce

1. Create a new Blazor Server-Side application.
2. Run the application.
3. See the Diagnostic tools process memory tab. (Ex: 76.7 MB)
4. Open this application with different tabs.
5. See the Diagnostic tools process memory tab. (Ex: 77.6 MB, 78.7 MB etc)
6. Now close these tabs.
7. See the Diagnostic tools process memory tab. (Ex: 77.6 MB, 78.7 MB etc)
8. **Output**: Memory is not cleared for closing tabs.

### Exceptions (if any)
![Capture](https://user-images.githubusercontent.com/61314814/108067131-5772c500-7086-11eb-8d17-f6c1bc1e8189.PNG)

### Further technical details

- Blazor server APP 5.0
- VS 2019

**Comment by javiercn** [comment]
@PiramanayagamR thanks for contacting us.

That is not a memory leak. No garbage collection seem to have happened in your "experiment". In server GC mode (the default for asp.net core apps) no garbage collection will be triggered unless the system is running low on memory.

In addition to that, Blazor doesn't immediately clear the memory when a client closes a tab/window, since it many cases it can't differentiate a transient network loss from a session ending.

Blazor keeps a limited number of circuits in memory for up to 3 minutes (by default) to enable applications to reconnect to the same session in the event that there is an intermittent network connection.

What you are seeing is perfectly normal and not a memory leak. If you want to validate this yourself, I suggest you capture two memory dumps. One at the beginning and one 10 minutes after you've closed your last tab and after triggering a forced generation 2 garbage collection with GC.Collect(2, Forced) and you'll observe that the memory is roughly the same as in the beginning of your experiment.

**Comment by PiramanayagamR** [comment]
Hi @javiercn ,

Thanks for the quick answer.

I have checked memory after 10 to 20 minutes closing tabs. Still memory is not released. Please refer to the below images. 
**20 min Before**
![LI-before](https://user-images.githubusercontent.com/61314814/108179488-ae7ea580-712b-11eb-9b86-2163cccd875e.PNG)
**20 min After**
![LI-after](https://user-images.githubusercontent.com/61314814/108179657-dec64400-712b-11eb-9e98-34702d039a56.PNG)

I have used component with 500 MB memory utilization. If I opened in large number of tabs (performance testing like large number of user testing), then it increases the memory gradually. Let say an example if I host this application and 100 number of user open this application then memory reached at maximum. It throws index out of memory. It causes big problem.

Could you please provide the any solution or suggestion to resolve this issue?

For your reference, I have attached demo sample with some element rendering.
[BlazorApp.zip](https://github.com/dotnet/aspnetcore/files/5994444/BlazorApp.zip)

**Comment by javiercn** [comment]
@PiramanayagamR In your sample no garbage collection has happened. Memory won't be released until a garbage collection happens.

WRT to allocating 500 MB per user, that is not a memory leak, in your case, all the memory is being used for up to 3 minutes after a tab has been closed. This is no different than if you allocate 500 MB per request and send 1000 concurrent requests.

A memory leak happens when memory is allocated and can't be freed up by a garbage collection. 
* In the image, it doesn't show you are triggering a garbage collection, so memory won't decrease.
* In your sample code, the memory is actually being used up to 3 minutes after the circuit is no longer present and it's your component the one performing an incredibly expensive set of allocations. A memory leak is a way to cause an OutOfMemoryException but it is not the only reason for it, in your case is an expensive allocation.

I **strongly suggest** you follow the guidance provided above and call GC.Collect(2, CollectMode.Forced) to force a GC to happen explicitly after 10 minutes and you'll see how the allocated memory goes away.

**Comment by javiercn** [comment]
I suggest you check out [this repo](https://github.com/sebastienros/memoryleak) for best practices when analyzing memory in .NET applications

**Comment by davidfowl** [comment]
FYI @Maoni0
