### ISSUE TITLE
Add support for TagHelper element/attribute completion tooltip classifications in Visual Studio

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30226]
Old editor:
![image](https://user-images.githubusercontent.com/2008729/108139166-5769c980-7074-11eb-91d4-0cfd230a611b.png)
(Jinu / UrlResolutionTagHelper shouldn't be there)
![image](https://user-images.githubusercontent.com/2008729/108139149-4d47cb00-7074-11eb-8169-8da21e728e27.png)

New editor:
![image](https://user-images.githubusercontent.com/2008729/108139062-1bceff80-7074-11eb-885f-36488b9b9531.png)
(UrlResolutionTagHelper shouldn't be there, addressed by: https://github.com/dotnet/aspnetcore/issues/23243)
![image](https://user-images.githubusercontent.com/2008729/108139045-12de2e00-7074-11eb-9159-76533da219fd.png)

**Comment by allisonchou** [comment]
@NTaylorMullen I've been looking into this issue, but one thing I'm unsure about is which part of the CompletionItem we're supposed to put the classifications in. Since component completions are part of the Razor LS, we're using the OmniSharp version of CompletionItem. However, the O# version of CompletionItem doesn't include the [Description property](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FLanguageServer.Protocol.Extensions%2FVSCompletionItem.cs&version=GBdevelop&line=31&lineEnd=32&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) like VSCompletionItem does. The Description property is how C# gets classification in completion tooltips to show up today. Is there something equivalent in O# CompletionItem we can use?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I've been looking into this issue, but one thing I'm unsure about is which part of the CompletionItem we're supposed to put the classifications in. Since component completions are part of the Razor LS, we're using the OmniSharp version of CompletionItem. However, the O# version of CompletionItem doesn't include the [Description property](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FLanguageServer.Protocol.Extensions%2FVSCompletionItem.cs&version=GBdevelop&line=31&lineEnd=32&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) like VSCompletionItem does. The Description property is how C# gets classification in completion tooltips to show up today. Is there something equivalent in O# CompletionItem we can use?

There's not one today, you'll need to create a VSCompletionItem that derives from it to expand the capabilities

**Comment by allisonchou** [comment]
Addressed by https://github.com/dotnet/aspnetcore-tooling/pull/3509.
