### ISSUE TITLE
Better byte[] serialization in JS interop

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#30288]
Split out from https://github.com/dotnet/aspnetcore/issues/27885

@javiercn Can you please add details about what you think we should be doing here?

**Comment by javiercn** [comment]
We currently Base64 encode binary data between .NET and JS.

This is inefficient when dealing with large enough payloads. For example, for 1GB file we send more than extra 300MB of data over the network (which are all 0's) for Blazor server. Compression is not an option here due to CRIME and BREACH security concerns.

For WebAssembly Base64 encoding and copying large amounts of memory between JavaScript and .NET Core via our JS interop is also problematic as it drastically degrades performance, which affects a wide range of multimedia applications. We want to find a better way of enabling WebAssembly to access native JS memory (ArrayBuffer, etc.) minimizing the copy and maximizing the efficiency.

We can special-case binary data within our serialization and deserialization schemes to promote efficiency across blazor server and webassembly.

**Comment by SteveSandersonMS** [comment]
OK, thanks for clarifying. I think we already have an issue for that: https://github.com/dotnet/aspnetcore/issues/21877

Can we close this one as a dupe? Or close the other one as a dupe, assuming you agree it's the same thing.

**Comment by SteveSandersonMS** [comment]
Since this does appear to be a duplicate of #21877, I'll close it for clarity. But if I'm wrong, please let me know and/or reopen with details.
