### ISSUE TITLE
net5.0 Blazor not loading .css with multiple startup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30306]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/net50-Blazor-not-loading-css-with-mult/1337333)._

---
[severity:Other]
blazor 
one startup:
! [devenv_Y6i1mUcsiM.png] (https://aka.ms/dc/image?name=B25b791ff58784172a91eb873087b2dd0637486577987281862_devenv_Y6i1mUcsiM.png&tid=25b791ff58784172a91eb873087b2dd0637486577987281862)
! [vivaldi_J8qstPx8od.png] (https://aka.ms/dc/file?name=B6d320aab33444641818d424d33e9c8e3637486578213166408_vivaldi_J8qstPx8od.png&tid=6d320aab33444641818d424d33e9c8e3637486578213166408)

multiple startup:

! [devenv_CXFY9q75FT.png] (https://aka.ms/dc/file?name=B1d96fcd0424a440b9d76479830e43ee5637486579325114652_devenv_CXFY9q75FT.png&tid=1d96fcd0424a440b9d76479830e43ee5637486579325114652)
! [vivaldi_G4s8is0kcG.png] (https://aka.ms/dc/file?name=Bbb6b2eb7d4bc4a1597575c6f8ad565ad637486579447592306_vivaldi_G4s8is0kcG.png&tid=bb6b2eb7d4bc4a1597575c6f8ad565ad637486579447592306)

---
#### Feedback Bot on 2/13/2021, 04:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Dr9vik** [comment]
SDK 5.0.103
vs2019 16.5.8
standart project server blazor
https://github.com/Dr9vik/blazor-server

replace: 
`webBuilder.UseStartup<Startup>();`
V
`webBuilder.UseStartup(typeof(Startup).GetTypeInfo().Assembly.FullName);`

build project
browser console:
Failed to load resource: the server responded with a status of 404 ()          {PROJECT}.styles.css:1

**Comment by javiercn** [comment]
@Dr9vik thanks for the additional details.

Seems like you are configuring startup to a value that doesn't follow the default convention (what's your motivation to do so if we may ask) and as a result static web assets are not correctly configured.

Given that you are not following the framework conventions you need to specify the key for static web assets manually so that they can find the right file. To do that, you call UseSetting and pass in `WebHostDefaults.StaticWebAssetsKey` the absolute path to the *<appName>>.StaticWebAssets.xml` file in your build output.

**Comment by Dr9vik** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0#environment-based-startup-class-and-methods
I want to create StartupDevelopment and StartupProduction class
