### ISSUE TITLE
File aspnetcorev2_inprocess.dll not working

### ISSUE THREAD

**Issue by dmumladze** [dotnet/aspnetcore#30363]
I'm trying to get a self-contained .NET core web API up and running without installing a AspNetCoreModuleV2 module onto the server. I noticed there's aspnetcorev2_inprocess.dll in my bin folder now so I was hoping that would eliminate the need of installing the module, but I may be wrong... Haven't been able to find much documentation about this new file either.

How doe aspnetcorev2_inprocess.dll work and why is it there? Do I still need to install the AspNetCoreModuleV2 from SDK MSI?

This is a Windows 2016 server.

Thank you.

**Comment by Tratcher** [comment]
A self-contained deployment includes the runtime and a plugin for the module to load (`aspnetcorev2_inprocess.dll`), but the IIS module still needs to be installed in order to start the loading process. `aspnetcorev2_inprocess.dll` contains runtime loading code that may version with each release, vs the module which contains only minimal startup code and interops with all version.
