### ISSUE TITLE
Blazor AsyncDisposable fails when using Task.Yield

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#30396]
### Describe the bug

I am contributing to a Blazor component library that makes use of a JS framework (Material). Every component needs to be initialized, and should also be destroyed. Simplifying the code makes it look like this:

```js
// javascript
function init(el) {
    console.log("Initializing", el);
}
function destroy(el) {
    console.log("Destroying", el);
}
```

```cs
// in Blazor component
<h3 @ref="element">Component</h3>
This component has some async disposal to do.
@implements IAsyncDisposable
@inject IJSRuntime js
@code { 
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await js.InvokeVoidAsync("init", element);
        }
        await base.OnAfterRenderAsync(firstRender);
    }
    public async ValueTask DisposeAsync()
    {
        await js.InvokeVoidAsync("destroy", element);
    }
}
```

This works just as expected and displays logs such as
```log
Initializing <h3 _bl_abc>...</h3>
Destroying <h3 _bl_abc>...</h3>
```

In the component library, we want to batch calls to `js.InvokeVoidAsync`, as too many calls can be performance-degrading on Blazor Server. This introduces a slight delay, which has a bad side-effect: the DOM element is destroyed before the JS call takes place. The code can be reduced to this:

```cs
    public async ValueTask DisposeAsync()
    {
        await Task.Yield(); // any delay is equivalent
        await js.InvokeVoidAsync("destroy", element);
    }
```

As soon as the `await Task.Yield();` is added, the log changes to 
```log
Initializing <h3 _bl_abc>...</h3>
Destroying null
```

This of course causes problems, because now we want to destroy a null object. Ouch.

### To Reproduce

Here's a repo containing the full code: https://github.com/stefanloerwald/AsyncDisposable
Relevant files are:
- wwwroot/code.js: JS code
- Pages/AsyncDisposing.razor: the component that implements IAsyncDisposable
- Pages/Index.razor: the component displaying the AsyncDisposing component. Click the button twice to trigger the DisposeAsync method

### Further technical details
- ASP.NET Core version: net5.0 (latest)

**Comment by javiercn** [comment]
@stefanloerwald thanks for contacting us.

I don't necessarily think this is a bug. We don't make any guarantees about the state of UI within DisposeAsync and developers must account for that. For example, the circuit might be disconnected when DisposeAsync is invoked or the element might be gone from the page since another batch happened.

If I were to do this, I would instead setup something on the JS element during init so that cleanup happens when it gets removed without the need to use a JS interop call from the server.

**Comment by captainsafia** [comment]
@SteveSandersonMS The triagers are wondering if you have any additional thoughts on this.

**Comment by SteveSandersonMS** [comment]
I agree with @javiercn's point. We have to clean up the DOM immediately on disposal - we can't wait until after the `DisposeAsync` task completes, because that could take arbitrarily long. We would have to block *all* UI updates until this arbitrary-duration task has completed, at that would would make a really bad UX.

Javier's suggestion of managing this on the JS side sounds much easier. Presumably using a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

**Comment by stefanloerwald** [comment]
Thanks so much for the clarification! It makes perfect sense for Blazor not to wait for any user-code before changing the DOM. We're looking into alternatives, one being MutationObserver, the other simply omitting the "destroy" code, as it might be superfluous anyway.
