### ISSUE TITLE
System.NullReferenceException in AspNetCore pipeline

### ISSUE THREAD

**Issue by VamseeInala** [dotnet/aspnetcore#30426]
[{"parsedStack":[{"assembly":"Microsoft.AspNetCore.Http, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Http.DefaultHttpRequest.set_RouteValues","level":0,"line":0},{"assembly":"Microsoft.AspNetCore.Routing, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync","level":1,"line":0},{"assembly":"Microsoft.AspNetCore.Routing, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Routing.Matching.DfaMatcher+<SelectEndpointWithPoliciesAsync>d__12.MoveNext","level":2,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":3,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":4,"line":0},{"assembly":"Microsoft.AspNetCore.Routing, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware+<<Invoke>g__AwaitMatch|8_1>d.MoveNext","level":5,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":6,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":7,"line":0},{"assembly":"******", Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"********.ExceptionMiddleware+<Invoke>d__6.MoveNext","level":8,"line":68,"fileName":"D:\\a\\1\\s\\Service\\Service\\ExceptionHandlers\\ExceptionMiddleware.cs"}],"outerId":"0","message":"Object reference not set to an instance of an object.","type":"System.NullReferenceException","id":"16182211"}]

Can someone please help me fix this issue?

**Comment by javiercn** [comment]
@VamseeInala thanks for contacting us.

Unfortunately we don't have enough information to troubleshoot this issue. Could you provide us with a minimal repro project and detailed steps to cause the issue to manifest so that we can try and help out?

**Comment by VamseeInala** [comment]
Hello,

Unfortunately this issue isn't occurring consistently to reproduce :( Is
there a scope for you to check from the stack trace?

**Comment by javiercn** [comment]
@VamseeInala There can be lots of reasons why this is happening. For example if you have code that interacts with the routing system and returns bad data and so on. It's impossible for us to determine what's going on unless we get a minimal repro with instructions on how to trigger the issue. The call stack is not enough indication that the issue is in our codebase.

**Comment by Tratcher** [comment]
To null ref at `DefaultHttpRequest.set_RouteValues` would require more than bad request data. Issues like this are usually caused by bad multi-threading code. HttpContext is not thread safe so trying to access it from multiple threads can cause this. The usual suspect is a Task that's missing an `await`. or an explicit Task.Run.

For this this to happen in routing, the cause would likely be earlier in the middleware pipeline. The only non-framework code I see in the callstack is `Microsoft.Recruiting.Integrations.SubscriptionService` so I'd start there.
