### ISSUE TITLE
Move from TSLint to ESLint

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#30440]
TSLint is deprecated, we should look into moving to ESLint https://www.npmjs.com/package/tslint

As part of that we should make sure to add the `"requires '_'"` rule for private members to help with name mangling.
https://github.com/dotnet/aspnetcore/pull/30320/commits/7844c64d37b253feb9863cae023be6ec9eff62e4#diff-887211f12c122673d436221142a9cd6cb0c7355385261e595742116180e7754a
```
"naming-convention": [
            true,
            {"type": "member", "modifiers": "private", "leadingUnderscore": "require"}
          ]
```

**Comment by joaopgrassi** [comment]
I think I could take this one :). Probably will need some guidance later on, but the idea then is to move everything here: https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/clients/ts to ESlint? And also the `_` on private members + the new rule. That summarizes it well?

**Comment by BrennanConroy** [comment]
Yeah, we'd also like to try and preserve the rules from [our tslint config](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/tslint.json) (if they aren't already on by default)

**Comment by joaopgrassi** [comment]
Ok  I started doing some work on this.. I looked into what was included in the `recommended` for TSLint and there's quite a few things different. 

Not sure what is the path to proceed. https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#configuration recommends using the built-in ESlint rules + their own recommendations, which is what I started with now.

But for example, things like `variable-name` in TSLint: https://github.com/palantir/tslint/blob/285fc1db18d1fd24680d6a2282c6445abf1566ee/src/configs/recommended.ts#L90 is on by default, but I didn't find it in any of the recommended ones for ESlint, meaning it's off. 

There are a lot more like this.. I started trying to map them in a spreadsheet but soon it became too much. Do you think it make sense to find all that was ON in TSLint but it's OFF in ESLint and enable them? 

Another thing I found is that there's a lot of `any` in code, and by default now it complains due to `"@typescript-eslint/no-explicit-any". Should I disable rules like this in order to make the existing code compile, or do we want to fix these all now?

**Comment by BrennanConroy** [comment]
> Do you think it make sense to find all that was ON in TSLint but it's OFF in ESLint and enable them?

Yeah, I think we should grab the TSLint rules that are on and enable them in ESLint, as well as have the ESLint recommended. Then we can try to clean it up once we can see the whole list.

> For the `tests` folder. Do we want to keep the same rules there, or have it more relaxed?

Ideally we should have the same global rules so we don't need to maintain different lists. If it's a lot of work, we can relax the test folder for now.

**Comment by BrennanConroy** [comment]
Friendly ping @joaopgrassi, was wondering how your testing went?

**Comment by joaopgrassi** [comment]
Hey @BrennanConroy sorry, I got caught up at work with some stuff didn't have much time :( Hopefully in the coming week I'll be able to get back to it.

**Comment by BrennanConroy** [comment]
No worries, just wanted to see if you had hit any snags 😃

**Comment by joaopgrassi** [comment]
haha I think it was going quite well, was just lack of time really. Probably the most time consuming part will be checking what rules were on by default on TSLint that aren't on by default on ESLint. 

What I have on my branch is ESLint running with the recommended set of rules + the ones we had before on the `signalr` package. It passes the build fine :). The next step would be to fix the ESLint errors for its tests. Then I can maybe apply the same to the `signalr-protocol-msgpack` package.

**Comment by joaopgrassi** [comment]
Hi @BrennanConroy! So, I finally did most of the work. Just an overview:

- Checked all the default rules from TSLint: https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts
- Checked all the default rules from ESLint/TS ESLint:
  https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.ts
  https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js
  
- Added the ones that were ON by default in TSLint but not in ESLint/TS ESLint. 

I believe the only thing missing is adding the rule you mentioned to enfore `_` on private fields. I'll work on it next.
