### ISSUE TITLE
Blazor PreventDefault and StopPropagation

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#30460]
.Net 5.0.103 SDK x64

I have an EditForm.
In this form thers is a component which contains an input:
```
<input type="text" class="@cssclasse" id="@Id" value="@_value" @oninput="SetValue" @onkeydown:stopPropagation @onkeydown="KeyDownHandler" autocomplete="@Autocomplete" />
```

KeyDownHandler method is:

```csharp
 private void KeyDownHandler(KeyboardEventArgs e)
        {
            Console.WriteLine(e.Key);
            if (e.Key == "Enter")
            {
                if (!string.IsNullOrEmpty(_value) || !_invalid)
                {
                    Add(_value);
                    _value = string.Empty;
                }
            }
        }
```

When enter key is hit, the form is submitted.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What you're looking for is the `preventDefault` directive instead: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#prevent-default-actions

**Comment by SteveSandersonMS** [comment]
I don't think you mean to use `stopPropagation`. If your goal is to prevent the default form submission behavior, then you should use `preventDefault` instead. Note that `stopPropagation` is unrelated to this.

However, since you actually want a *conditional* `preventDefault` (where the condition is "the key being pressed is 'enter'"), it's a little more complicated.

The two simplest solutions are:

1. Simply don't have an HTML submit button within the `<form>`. That is, remove any `<input type=submit>` or `<button type=submit>` and have a plain `<button>` instead, wired up to some .NET event handler logic. Then the enter button won't trigger a submit (assuming there's more than one input in the form). See details at https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that
2. Or, use a JavaScript event handler to do a conditional preventDefault. It's easy to do this in Blazor - just use `onkeydown` instead of `@onkeydown`. Just add the following attribute `onkeydown="return event.keyCode !== 13"`. You can add this either to the `<form>` (or `<EditForm>`) or to the `<input>` elements within it.
