### ISSUE TITLE
Blazor Server website always displays connection redirecting UI after page load

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#30483]
### Describe the bug
https://themesof.net/ always displays the connection reconnecting UI after page load. It is displayed for a couple of seconds and then disappears.

Is Blazor Server being too aggressive with assuming a lost connection?

### To Reproduce
1. Visit https://themesof.net/
2. "Reconnecting attempt 1 of 8" displayed for a couple of seconds
3. Website then works normally

### Further technical details
Website source: https://github.com/terrajobst/themesof.net

@terrajobst

**Comment by JamesNK** [comment]
Screen capture:

![themesofnet](https://user-images.githubusercontent.com/303201/109244123-ffd11800-7842-11eb-93db-2e9eb0702677.gif)

**Comment by benaadams** [comment]
I end up with multiple connects; one per new node (fresh data) opened

https://user-images.githubusercontent.com/1142958/109253845-8efd1200-77e8-11eb-95e1-639bae3bcbe7.mp4

**Comment by terrajobst** [comment]
Do you think that’s indicative of a bug in my site or in Blazor infrastructure? I’ll try to sieve though the exception log to see if the server has an unhandled error somewhere.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by benaadams** [comment]
Ignoring the disconnects it is working ok (e.g. loading the nodes etc)

It does send some chonk messages 
![image](https://user-images.githubusercontent.com/1142958/109257785-d091bb00-77f0-11eb-906e-549fbfe6f99a.png)

Looking at that might be busting the 32kB limit

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/SignalR/common/Http.Connections/src/HttpConnectionDispatcherOptions.cs#L14-L29

Looking at https://github.com/dotnet/aspnetcore/issues/5623#issuecomment-434781675; you may need to up these limits in Configure

```csharp
app.UseSignalR(route => route.MapHub<BlazorHub>(BlazorHub.DefaultPath, o =>
{
    o.ApplicationMaxBufferSize = 131072; // larger size
    o.TransportMaxBufferSize = 131072; // larger size
}));
app.UseBlazor<App.Startup>();
```

**Comment by benaadams** [comment]
Testing with https://github.com/terrajobst/themesof.net/pull/16

**Comment by benaadams** [comment]
Specifically In `ConfigureServices`
```csharp
            services.AddServerSideBlazor()
                .AddHubOptions(options =>
                {
                    // Increase the limits to 256 kB
                    options.MaximumReceiveMessageSize = 262144;
                });
```
and in `Configure`
```csharp
                endpoints.MapBlazorHub(options => 
                {
                    // Increase the limits to 256 kB
                    options.ApplicationMaxBufferSize = 262144;
                    options.TransportMaxBufferSize = 262144;
                });
```

**Comment by javiercn** [comment]
This is likely the message going up exceeding the underlying max message size as @benaadams image shows. 
Sending messages to the client doesn't have a limit I believe.

Do we know what's causing such a big message to be sent?

**Comment by benaadams** [comment]
The list of open nodes [ThemesOfDotNet/Pages/Index.razor.cs#L572-L579](https://github.com/terrajobst/themesof.net/blob/701a1ef4e0ffbe04380ea7e87d0cbc57462d8dd4/src/ThemesOfDotNet/Pages/Index.razor.cs#L572-L579)

![image](https://user-images.githubusercontent.com/1142958/109317906-21330380-7845-11eb-823b-51fa0951cfed.png)

With all the nodes closed there isn't a big post from the client
![image](https://user-images.githubusercontent.com/1142958/109318445-b6ce9300-7845-11eb-9f14-d05219373e6d.png)

With all of them open there is a 33.9kB post (followed by a 468 kB response with the data for the open nodes)

![image](https://user-images.githubusercontent.com/1142958/109318735-090fb400-7846-11eb-9724-320eab29f9cc.png)

> Sending messages to the client doesn't have a limit I believe.

For the first large message on startup it does look like `render-mode="ServerPrerendered"` still sends the full data on the first message rather than using the Prerendered state?

![image](https://user-images.githubusercontent.com/1142958/109319044-5ab83e80-7846-11eb-9b10-937e54bce33f.png)

**Comment by mkArtakMSFT** [comment]
@javiercn moved this to the `Discussions`. Please include any pending work from here in your `Blazor Server Improvements` issues so that we can track those.
