### ISSUE TITLE
Razor transition in template expressions are not colorized in new Editor

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30555]
The `@` should be colorized

![image](https://user-images.githubusercontent.com/2008729/109575792-5c347180-7aa7-11eb-84af-41165319b537.png)

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen do you happen to remember the larger context here? I'm not seeing this replicate in what I assume the context would have been:
![image](https://user-images.githubusercontent.com/14987221/113039676-c8f56700-914c-11eb-93e9-ef5c80c7158c.png)
We've made some changes in SemanticTokens since then, though I can't think of any in particular which would have fixed this instance?
