### ISSUE TITLE
Replace msgpack5 with WebAssembly implementation (performace)

### ISSUE THREAD

**Issue by JiriZidek** [dotnet/aspnetcore#30566]
## Summary

Option to replace JS library msgpack5 with WebAssembly module within SignalR browser side. This would bring even better performance on client side.

## Motivation and goals

Since there are various existing C# implementations, it should be easy to port them and compile as WebAssembly module (being it MSFT one or neuecc), and to keep the same interface as msgpack5.

## In scope

Any modern browser support WA now. Using within Blazor would be useful as well.

**Comment by javiercn** [comment]
Removing Blazor since the question seems to be about SignalR.

WRT to Blazor we don't currently have performance concerns about our current implementation and we can't validate that there would be a significant performance improvement to justify the change.

WRT to SignalR it's likely that we don't want to do that either, since a Webassembly implementation would be much bigger in size than the current JS implementation.

That said, I'll let the SignalR folks have final say.

**Comment by BrennanConroy** [comment]
> WRT to SignalR it's likely that we don't want to do that either, since a Webassembly implementation would be much bigger in size than the current JS implementation.

Yeah, this isn't something we will add to the built in library. You're free to provide your own message pack protocol implementation and pass it in when creating the hub connection, https://docs.microsoft.com/javascript/api/@microsoft/signalr/hubconnectionbuilder?view=signalr-js-latest#withhubprotocol-ihubprotocol-

**Comment by JiriZidek** [comment]
Thx for explanation and clear opinion.
