### ISSUE TITLE
Razor @inject directive should allow an init lambda

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#30591]
I'm injecting my app's options into each of my pages through `_ViewImports.cshtml` like so:

```
@inject Microsoft.Extensions.Options.IOptions<MyApp.WebAppOptions> AppOptions
```

Because this is an `IOptions` though, I have to access the options in my views through the somewhat-clunky `.Value` property in my pages with:

```
@if (!AppOptions.Value.DisableClientValidation) {
    [...]
}
```

I'd like to be able to initialize the value injected into the AppOptions variable through my own code, as I'd do in the constructor when using a class's constructor injection, maybe in a lambda along the lines of:

```
@inject Microsoft.Extensions.Options.IOptions<MyApp.WebAppOptions> AppOptions = (iopt) => iopt.Value

[...]

@if (!AppOptions.DisableClientValidation) {
    [...]
}
```

The actual type of `AppOptions` would then be inferred from the return type of the lambda.

I'd imagine this functionality would have quite a few other applications too.

**Comment by javiercn** [comment]
@jez9999 thanks for contacting us.

This is not something that we plan to implement in the near future. We don't include any additional behavior for services injected via `@inject` with respect to regular resolution using DI and we don't plan to deviate from it, since it adds a new knob developers need to be aware when using DI in the context of Blazor and that's a non-goal for us.

You can achieve this in several ways using the standard DI mechanisms:
* Inject IOptions<TOptions> and add a property for accessing the value directly.
* I believe you might be able to inject TOptions directly, but I might be wrong.
* You can alternatively register TOptions in DI and use a factory to resolve it.

/cc: @HaoK in case he has more ideas

**Comment by jez9999** [comment]
@javiercn How do you add a property for accessing the value directly?  Do you mean an extension method for IOptions or something?

**Comment by javiercn** [comment]
```
@inject IOptions<TOptions> RawOptions

@code{
  public TOptions AppOptions => RawOptions.Value;
}
```

**Comment by HaoK** [comment]
The property pattern is generally the most common and the typical use case, the other options @javiercn mentioned would work fine too.

**Comment by jez9999** [comment]
> ```
> @inject IOptions<TOptions> RawOptions
> 
> @code{
>   public TOptions AppOptions => RawOptions.Value;
> }
> ```

That doesn't seem to work in `_ViewImports.cshtml`, unfortunately, which is where I'm injecting the options.
