### ISSUE TITLE
Blazor feature request : inherit components from interface and inject them

### ISSUE THREAD

**Issue by navidzehi** [dotnet/aspnetcore#30640]
It would be very useful if we could inherit components from interfaces :

```
public interface ITextboxField {
      string Text { get; set;}
} 

```

**BootstrapTextbox.razor** :

```
@inherit ITextboxField 

...

@code{
   [Parameter] public string Text { get; set;}
}

```

**MyPage.razor :**

```
@inject ITextboxField MyTextboxField

<MyTextboxField  Text="something" />
```

**startup :**
```

services.UseBootstrapComponents();
or 

services.UseMaterialDesignComponents();


```
**Bootstrap extension method :**
```
services.AddScoped<ITextboxField,BootstrapTextbox>();
...
// other controls

```

**Comment by javiercn** [comment]
@navidzehi thanks for contacting us.

The part about "Inheriting" threw me off a bit, but I think I know what you are asking about.

It might be possible for you to do this today in two ways:
* Writing and registering your own IComponentActivator, which allows you to have the indirection you are looking for. There might be things that get in your way, like the compiler or other things I can't foresee.
* You might do this in a slightly different way by using a named using `@using Some.Type = MyName` but I'm not sure if the compiler respects that.
  * If that were to be the case, you can just put a bunch of usings like that within a _ViewImports.razor file and should have the effect you are looking for.

In general we are not in favor of features like this because they add quite a good amount of overhead to the rendering process (every component needs to be resolved) and this problem can be solved in different ways, like providing different versions of a library and so on.

It is not a common requirement to be able to switch CSS frameworks and so on and so it is expected that it requires a bit of work

**Comment by navidzehi** [comment]
@javiercn thank you for your answer. As you mentioned the _ViewImports.razor can do the job.
