### ISSUE TITLE
Server-side Blazor should use WebSocket compression

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#30745]
Dependent on https://github.com/dotnet/runtime/pull/49304

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@blowdart are there any security concerns with this? Can we do this at all?

**Comment by blowdart** [comment]
I have absolutely no idea, nor do I have any idea how to evaluate it. It's probably ok, because you're not holding the TLS keys in memory, that has already happened. so the specifics of breach and crime, but it's still concerning because of the lack of analysis by industry.

So, if you do it, it should be off by default IMO. 

@GrabYourPitchforks any thoughts here?

**Comment by mkArtakMSFT** [comment]
Thanks @blowdart.
After some more discussion we've decided not to do this work as the risk involved is quite high.

**Comment by SteveSandersonMS** [comment]
It's also worth noting that Blazor Server already deduplicates strings if we know for sure that they came from compile-time constants, and hence don't vary by user input. So it's already a kind of compression for the things we know are safe.

**Comment by benaadams** [comment]
Using https://themesof.net/ as an example server-side Blazor app; its still very chonky 

94.2 kB is the reload of server-side render (as it resends the starting state vs WebSocket); which is 7 kB when compressed

482 kB is clicking the open nodes button; which is super chonk

![image](https://user-images.githubusercontent.com/1142958/110388509-21a87700-805b-11eb-94af-99bd67c60bfc.png)

**Comment by SteveSandersonMS** [comment]
I'd personally be open to enabling an option for this if it became a common customer request. In this *specific* example with themesof.net, I don't *think* the compression oracle attacks would be a viable attack vector, since there's very limited scope for an attacker inserting their own data into the stream. Though maybe the attacker could be someone with write access to issue titles/labels.

Generally the problem with having these kinds of options is that developers may turn them on because they understand the benefits but don't understand the risks. The risk level of compression oracle attacks is really hard to estimate or communicate.
