### ISSUE TITLE
Update the CookiePrefix value in the CookieAuthenticationDefaults

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#30802]
Update the CookiePrefix value in the CookieAuthenticationDefaults class to "__Host-AspNetCore."

".AspNetCore."=> "__Host-AspNetCore."

https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationDefaults.cs#L21

This would improve security to only allow same domain cookies for browsers which support this. If users would like to share cookies between sub domains etc, then the user must actively change this to allow it.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes

I could do a PR for this is you find it good.

Greetings Damien

**Comment by blowdart** [comment]
Hah. That prefix "feature" has caused security vulnerabilities in itself. Given that it's just another way of indicating either the secure flag or the host flag I'm not convinced this adds anything except confusion and pain, because it's not clear that the name of the cookie should affect where it's sent, or the protocol it goes over.

**Comment by damienbod** [comment]
@blowdart thanks for the feedback, will close this then.

Greetings Damien

**Comment by blowdart** [comment]
I do appreciate the thought though!
