### ISSUE TITLE
OnAuthenticationFailed never fires when certificate validation fails

### ISSUE THREAD

**Issue by TheNephalim** [dotnet/aspnetcore#30819]
### Description

I have a rooted certificate (created a CA and generated a test user certificate from this CA).  When attempting to present this certificate, I fully expected the certificate validation to fail because it cannot check a CRL.  This failure is desired.  However, the handler associated with the OnAuthenticationFailed event never fires.

I stepped through the code in the CertificateAuthenticationHandler.cs and found that the certificate validation fails as expected, but reaches line 140 where the code states:

                return AuthenticateResult.Fail("Client certificate failed validation.");

and the AuthenticationFailed event and its associated event handler are never fired.

I changed the options.RevocationMode to X509RevocationMode.NoCheck.  As expected, the validation of the certificate succeeds and reaches line 149 where the code states:

            await Events.CertificateValidated(certificateValidatedContext);

and the CertificateValidated event and associated handler are fired.

### Configuration

.NET Core 3.1
Windows 10 Professional
x64 architecture

### Regression?

I don't know if this is a regression.

### Other information

N/A

**Comment by blowdart** [comment]
That's not what `OnAuthenticationFailed` is for I'm afraid. That method is for when the handler fails, due to exceptions during processing.

We updated the comments in the other middlewares, e.g. [Jwt](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Security/Authentication/JwtBearer/src/JwtBearerEvents.cs) but it looks like it never made it to Certificate.

@JunTaoLuo / @HaoK could one of you update the xml doc comments to match the ones in JWT to remove the confusion?

**Comment by TheNephalim** [comment]
Ok.  Thank you for the information, but I'm a little perplexed, because when the validation of the certificate fails, the request still proceeds forward rather than preventing the request from moving forward unless this is by design.

Based upon the example(s) in the docs, the OnCertificateValidation seems to be designed for adding additional claims to the identity, checking the certificate against a database, etc.   My application will most likely run in an environment where it cannot use the internet to check CRLs and will not have access to offline CRLs either, so setting the revocation mode to NoCheck is probably going to be the way to go anyway. 

One thing I also noticed is that the checks seem to be occurring twice, is this because it runs before and after the request?

**Comment by blowdart** [comment]
Validation failures are acceptable, because you can have multiple authentication handlers, and when one fails another may succeed, Auth failure doesn't stop the pipeline. 

If no authentication handlers end up running there's no identity produced, and any authorization will fail.

@Tratcher if we look at JWT it's inconsistent with the actual code comments. What's the expected behaviour here?

**Comment by blowdart** [comment]
OK we've talked about this internally, we don't have base events, so we have inconsistency. 

JWT is does it, because the JWT validator isn't our code, they throw exceptions, we catch and then pass up to fail. OIDC is the same as JWT. Cookie doesn't have validation really. So, we'll change certificate for 6.0 and pass the failures up, to match JWT, and we'll fix the code comments everywhere.

**Comment by TheNephalim** [comment]
Thank you very much for reviewing this and your consideration.

**Comment by blowdart** [comment]
You're welcome.
