### ISSUE TITLE
Merge #28698 to branch 5.*

### ISSUE THREAD

**Issue by Karql** [dotnet/aspnetcore#30862]
## Description

In 5.0 some logging updates were made that accidentally swapped the argument parameters for a log.

## Customer Impact

Customers consuming structured logging might depend on the types of the structured data, swapping the arguments can break them [as seen above](https://github.com/dotnet/aspnetcore/issues/30862#issuecomment-797311567), also the log reads incorrectly.

## Regression?
- [x] Yes
- [ ] No

Regressed from 3.1 to 5.0 (fixed in 6.0 already)

## Risk
- [ ] High
- [ ] Medium
- [x] Low

The change is a logging change only, just switching the parameter order.

## Verification
- [ ] Manual (required)
- [x] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A

------

Hi!

It is possible to merge fix from #28698 to branch 5.*?

Best regards,
Mateusz

**Comment by Tratcher** [comment]
The log is a bit confusing, but is there any more impact to you? An issue like this wouldn't normally qualify for a patch.

**Comment by Karql** [comment]
The problem affects our central logging system (EFK stack).

![image](https://user-images.githubusercontent.com/173098/110910649-eedbd880-8311-11eb-9845-b3921de3c141.png)

We have several apps with diffrent .Net Core version 3.*, 5.* etc.

In version 3.* there was no bug: https://github.com/dotnet/aspnetcore/blob/v3.1.13/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs#L50

Bug exists in 5.*: https://github.com/dotnet/aspnetcore/blob/v5.0.4/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs#L51

So there is diffrent format for one field when logs are pushed to the elastic.

**Comment by davidfowl** [comment]
This seems like reasonable thing to backport. It's super low risk but I'll let @Pilchie decide.

**Comment by BrennanConroy** [comment]
Triage: we're in favor of patching. This is a regression from 3.1 to 5.0.

We could technically provide a private reflection workaround, but this should be patch worthy.

**Comment by BrennanConroy** [comment]
## Description

In 5.0 some logging updates were made that accidentally swapped the argument parameters for a log.

## Customer Impact

Customers consuming structured logging might depend on the types of the structured data, swapping the arguments can break them [as seen above](https://github.com/dotnet/aspnetcore/issues/30862#issuecomment-797311567), also the log reads incorrectly.

## Regression?
- [x] Yes
- [ ] No

Regressed from 3.1 to 5.0 (fixed in 6.0 already)

## Risk
- [ ] High
- [ ] Medium
- [x] Low

The change is a logging change only, just switching the parameter order.

## Verification
- [ ] Manual (required)
- [x] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A

**Comment by BrennanConroy** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/31080
