### ISSUE TITLE
Blazor Hosted WebAssembly template why RazorPages?

### ISSUE THREAD

**Issue by Jimmys20** [dotnet/aspnetcore#30901]
Hello, I don't understand why the blazor wasm hosted template uses a Razor page to implement the /error endpoint. Why not just use an exception handler like in this example [https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#exception-handler](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#exception-handler). Most of the time the Server project is used to implement the API endpoints (WeatherForecastController) for the Client project to consume (via HttpClient). I think it's more appropriate to return a ProblemDetails payload instead of an html page when an exception occurs. And then `services.AddRazorPages();` and `endpoints.MapRazorPages();` will no longer be needed in the template.

Related issue: [https://github.com/dotnet/aspnetcore/issues/20791](https://github.com/dotnet/aspnetcore/issues/20791)

Edit: I guess it is necessary for when authentication is enabled on the template. Then the Server is not simply implementing a web api but also has the Identity UI for authentication/authorization and managing users.

**Comment by javiercn** [comment]
@Jimmys20 thanks for contacting us.

We try to be consistent across our templates and follow the same patterns where possible, this is one of those cases. There are multiple ways to deal with errors in an ASP.NET Core application, the option we provide on the template is one of many which users are free to change to suit their needs or preferences.

We try to setup our templates so that they are flexible and make easier implementing common scenarios (like the one you suggested) but ultimately our templates are only one way of doing things and we encourage people to change them to suit their needs.

**Comment by Jimmys20** [comment]
Thanks for your reply @javiercn, it makes sense.
