### ISSUE TITLE
Any way get service in blazor?

### ISSUE THREAD

**Issue by j4587698** [dotnet/aspnetcore#31187]
### Is your feature request related to a problem? Please describe.

I am try to get service in blazor using HttpContext.RequestServices.GetService(). 
But the service is different from inject.

### Describe the solution you'd like

Provide a method to get the same service as inject.
Like HttpContext.RequestServices.GetService().

**Comment by javiercn** [comment]
@j4587698 thanks for contacting us.

HttpContext is not available within Blazor. You can use `@inject Service Property` to inject a service into a component that is available via the property.

**Comment by meziantou** [comment]
If you need to _dynamically_ inject services, you can use the `IServiceProvider` service:

````
@using Microsoft.Extensions.DependencyInjection
@inject IServiceProvider ServiceProvider

<button @onclick="OnClick">test</button>

@code{
    void OnClick()
    {
        var service = ServiceProvider.GetRequiredService<MyService>();
    }
}
````

**Comment by j4587698** [comment]
@javiercn Thank you for your reply. I want to use it in reflection, and I don't want to pass in service as a parameter. I want to have an approximate static method to get service in a method that can't inject.

**Comment by javiercn** [comment]
@j4587698 thanks for the additional details.

We don't offer any static method to get a hold to the IServiceProvider since is not a recommended pattern (and there are multiple scopes in Blazor Server applications, which makes it even harder).

You can either inject the service or inject the service provider, we don't offer an alternative out of the box
