### ISSUE TITLE
ArgumentOutOfRangeException in ViewBufferTextWriter with latest servicing release

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#31299]
This line 
https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/Buffers/ViewBufferTextWriter.cs#L113

throws when invoked with `index: 0, count: 0` which is the case when using the new html encoder `TextWriterExtensions`
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/src/System/IO/TextWriterExtensions.cs#L33

when invoking this method with a string that starts with a chars that needs to be encoded:
https://github.com/dotnet/runtime/blob/1a35f1db908f96f2bddd9d23c780c515d14f16e0/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/TextEncoder.cs#L204

I have multiple reports of Orchard users with applications on Azure that stopped working when the release was pushed.
https://github.com/OrchardCMS/OrchardCore/issues/8887

**Comment by pranavkm** [comment]
FYI @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
I'm aware. Looks like our March servicing release exposed this latent bug in MVC. Will spin up a conversation with shiproom about how we should address this.

**Comment by GrabYourPitchforks** [comment]
BTW, I suggest that when you fix this, you also audit your existing `TextWriter` and `Stream` subclasses. The default implementation of virtual methods like `Write(ROS<>)` might not be as efficient as you'd expect. By overriding these methods and providing optimized implementations, you may realize a small perf boost.

**Comment by Lizzy-Gallagher** [comment]
@TanayParikh @mkArtakMSFT - Is there an estimate of when this fix will go out?

Some context:
- the System.Text.Encodings.Web versions 4.5.1 and 5.0.1 were flagged as fixing a [critical vulnerability] (https://github.com/dotnet/announcements/issues/178).
- this bug is making it hard for our applications with Portugese users to update, since that language starts questions with ¿ which is a character that requires encoding (triggering this error).

We have spot fixes to unblock updates, but would be very excited to have this reliably fixed.

**Comment by TanayParikh** [comment]
This was fixed via https://github.com/dotnet/aspnetcore/pull/32277 & will be part of the .net 6 Preview 5 release.

**Comment by sebastienros** [comment]
@Lizzy-Gallagher this is scheduled for 6.0. Can you provide some code that shows how you are hitting this issue? Orchard is using a custom view engine, and we couldn't find a way to trigger the behavior otherwise.

**Comment by Lizzy-Gallagher** [comment]
Thanks for the quick response @sebastienros  and @TanayParikh, I have put together a minimal repro in .NET Core 3.1:
https://github.com/Lizzy-Gallagher/ViewBufferTextWriterBugRepro

Steps:
1. Clone the repro
2. In VS, use the ViewBufferTextWriterBugRepro launch profile
3. Click the "Fail" link to see the ArgumentOutOfRangeException

Gif of the repro:
![repro](https://user-images.githubusercontent.com/7842023/117221313-05b11f80-add7-11eb-884d-a52e46d134ed.gif)

To be honest, I am not positive of the link between this error and System.Text.Encodings.Web update we did. This is mostly because I don't completely understand how this .NET Core 3.1 app gets its copy of these classes. Our apps hitting this in production get it from installed NuGet packages as they are .NET Framework. Perhaps this is what you meant by this being a "latent bug in MVC"?

**Comment by sebastienros** [comment]
Here is the interesting part

```c#
public void CreateRepro(IHtmlContent text)
{
	// In production code, we are doing something more complicated with this
	// ViewContext.Writer and would like to continue using it if possible.
	var writer = this._htmlHelper.ViewContext.Writer;
	
	var headerTextDiv = new TagBuilder("div");
	writer.Write(headerTextDiv.RenderStartTag());
	
	headerTextDiv.InnerHtml.AppendHtml(text);
	headerTextDiv.WriteTo(writer, HtmlEncoder.Default);

	writer.Write(headerTextDiv.RenderEndTag());

	// NOTE: This issue is only present when the text is inside
	// a TagBuilder. The following does not throw the ArgumentOutOfRangeException:
	// writer.Write(text);
}
```

Thanks. As a mitigation you can deploy the previous .NET version as self-contained to prevent the system from using a more recent version, until this is fixed, probably in next service release (though I don't want to promise anything).

**Comment by sebastienros** [comment]
Another mitigation that I haven't tried must might just work as well is to use a zero-width space (http://www.unicode-symbol.com/u/200B.html) as the first char, since the issue only occurs when the first char needs to be encoded, hoping it doesn't have to.
