### ISSUE TITLE
Add a GetAllUsersAsync<TUser> method to IUserStore<TUser> to ease implementation of custom user stores

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/aspnetcore#31316]
I'm working on a custom user store for ASP.NET Core Identity. I implemented almost all the interfaces such as `IUserStore<TUser>`, `IUserClaimsStore<TUser>` and so on. It was all so easy and straightforward up until this point.

Now, since I also need a way to fetch all users, I tried to implement `IQueryableUserStore<TUser>` but I've really been struggling with this one and I'm giving up soon.
I'm not using EFCore and I certainly don't want to implement a full LINQ provider. What I really need is just one simple method such as `GetAllUsersAsync<TUser>` that can asynchronously fetch all users, just like `GetUsersForClaimAsync` can fetch users having a specific claim.

I know there are workarounds to this but it feels like the `IUserStore<TUser>` interface is incomplete without a `GetAllUsersAsync<TUser>` method.

If this can't be added to `IUserStore<TUser>` for back compatibility reasons, then a new interface would do as well.

**Comment by blowdart** [comment]
We've never implemented this, because we don't implement any manage all users UI. What's your actual scenario here for wanting all users? Once you get to any appreciable size of user base that method will cause all sorts of memory pressure.

**Comment by BrightSoul** [comment]
Hey @blowdart, thanks for your reply.
> What's your actual scenario here for wanting all users?

A small application with maybe a 20-30 users (employees) that has to show all of them on a page. Customer doesn't want to rely on EFCore.

> Once you get to any appreciable size of user base that method will cause all sorts of memory pressure.
Yes, well... even the `GetUsersForClaimAsync` method could lead to the same problem. Suppose I have 300k users living in the US in my database and I run this line of code:
```
var users = await userManager.GetUsersForClaimAsync(new Claim(ClaimTypes.Country, "USA"));
```
Or, even worse:
```
var users = userManager.Users.ToList();
```
These examples are just as harmful. I think the developer should be ultimately responsible for performance issues caused by improper use of public APIs.

> We've never implemented this
Please realize I'm unable to complete a feature in a straightforward and simple way because you thought I would do myself harm. But I don't need this kind of babysitting.

**Comment by blowdart** [comment]
The problem here is GetAllUsers() works for a 20 user database, not so much for a 20,000 user database, and certainly not for 200,000. For it to be useful we'd have to work out a paging mechanism that works across all supported platforms. Identity isn't really targeting this sort of API. I'm not entirely sure why we have GetUsersForClaim to be honest. @HaoK can you remember why that came in?

**Comment by HaoK** [comment]
We probably added it forever ago (pre core), when we were possibly going to support the webadmin scenarios.  We definitely abandoned adding any more APIs like that since these indeed cause the db to lock and create tons of performance issues.  So I agree that we definitely do not want to add anything like GetAllUsers to identity API
