### ISSUE TITLE
Can SlidingExpiration property of ConfigureApplicationCookie refresh the cookie on the basis of action instead of Navigation. ASP.Net Core Blazor Server

### ISSUE THREAD

**Issue by tahaAttique** [dotnet/aspnetcore#31346]
I am developing a Blazor Server ASP.net core app. It has Cookie based authentication using RevalidatingIdentityAuthenticationStateProvider. When I login I find '.AspNetCore.Identity.Application' Cookie in my browser.

I wanted to extend the login Expiry session for more than 30 min so I used the SlidingExpiration Property.

**The problem I am facing is that I want SlidingExpiration to issue the new cookie on any action (like filling a form) instead of just navigation.**

Consider the scenario that  SlidingExpiration= true;  and the sessionExpiry is at 30 min. What if the user keeps filling a form for 30 min and does not navigate anywhere. If SlidingExpiration only works on the basis of Navigation then the Session will expiry after 30 min in which the user was filling a form . 

Help will be appreciated !

**Comment by blowdart** [comment]
The cookie refresh doesn't happen on every request by design, it'll happen a little before it's due to expire. If a user isn't sending a request, for example by filling out a form for 30 minutes and there's no request happening it's just not going to refresh.

**Comment by tahaAttique** [comment]
@blowdart  Thanks a lot for the response.

 What do think?  what's the better solution to the problem ?

**Comment by blowdart** [comment]
@javiercn Anything you can do in blazor around it?

**Comment by SteveSandersonMS** [comment]
It's difficult for programming models like Blazor Server or SignalR generally to participate in the cookie reissuance, since cookies are only issued with HTTP responses, and Blazor Server / SignalR isn't making HTTP requests and so there are no HTTP responses.

It sounds like we'd need to issue some artificial "heartbeat"-type requests intermittently just for the purpose of refreshing cookies. Perhaps we'd need some rule like "only emit the heartbeat if we've seen signs of user activity recently" to avoid keeping it going forever. I'm not sure whether this is something the SignalR team is interested in handling at the SignalR level, or whether it should be a Blazor Server feature, or whether it's something we would expect application developers to put in themselves based on their own rules about frequency and detecting idleness.
