### ISSUE TITLE
FetchData.razor in the Blazor Server Template is supposed to show a loading text, but doesn't

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31486]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FetchDatarazor-in-the-Blazor-Server-Tem/1377388)._

---
[severity:It bothers me. A fix would be nice]
Expected behavior:
The 'forecasts' variable is set after the page is loaded, and a "Loading..." message is shown while the data is being populated and sent to 

Current behavior:
The 'forecasts' variable is set before the page is loaded, so the "Loading..." message is never shown. The service call is blocking, while I am assuming the template wants to show off loading the list async through SignalR.

Suggested fix:
Change from using OnInitializedAsync to OnAfterRenderAsync with this. StateHasChanged() in the template file.

---
#### Feedback Bot on 3/22/2021, 02:03 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
Thanks for contacting us.

This is not the case, the reason is twofold:
* Prerendering waits for the component/page to load completely before producing the rendered HTML, so in that case `Loading...` is irrelevant.
* On non-prerendered scenarios the data is produced synchronously which avoids the "Loading" state altogether.

The template exposes the pattern for consistency with the WebAssembly template, however we have no intention to change it for what you suggest nor to add a `Task.Delay` to the weatherforecastservice which would be the right way to expose this behavior in a more realistic way.
