### ISSUE TITLE
Blazor App doesn't add reference to working class library

### ISSUE THREAD

**Issue by IonutDaniel98** [dotnet/aspnetcore#31505]
Hello. I made a blazor app server side application. Ai added to the solution a new class library where I define my entities and connect to the DB but on the blazor project when i try to add the reference doesn't work. If i try manually to add it it says that it can't find my class library even if 

![image](https://user-images.githubusercontent.com/33718521/113477266-54426580-9489-11eb-8de9-9c887bd80173.png)

**Comment by javiercn** [comment]
@IonutDaniel98 thanks for contacting us.

Blazor server applications are no different to any other .NET Core applications in this regard. I believe this is likely a tooling issue rather than an SDK/framework issue. I suggest you do the following:
* Open your csproj file.
* Add a `<ProjectReference Include="..RelativePathToPeopleLibrary" />` inside an `ItemGroup` element.
* Save the project file
* Restore packages for the solution or run `dotnet restore` from the command-line.
* Perform a build and check the errors tab or run `dotnet build` from the command-line to spot any possible error.
* Check the target framework for the class library to ensure it's compatible with .NET Core (make sure is not full .NET framework).

**Comment by IonutDaniel98** [comment]
@javiercn 
I am not sure if I did it right because it is still not working. This is how my csproj file for the class library looks:
![image](https://user-images.githubusercontent.com/33718521/113685621-1fbfeb00-96cf-11eb-919a-9f36c5bcd961.png)


I am not sure how to take the correct relative path to the class library. I tried this way:
![image](https://user-images.githubusercontent.com/33718521/113686804-56e2cc00-96d0-11eb-881b-d6e9cf1def1c.png)



What I am doing wrong?
![image](https://user-images.githubusercontent.com/33718521/113687007-8e517880-96d0-11eb-923a-ca36bce0007f.png)

**Comment by javiercn** [comment]
@IonutDaniel98 thanks for the additional details.

There is likely a `.csproj` file inside that `PeopleLibrary` folder. You need to include that in the project reference.

So ` ContactListBlazorApp\PeopleLibrary\PeopleLibrary.csproj`

Another way to do it is via Visual Studio right click in the dependencies node within the project and clicking "Add project reference"
![image](https://user-images.githubusercontent.com/6995051/113689031-b912e100-967e-11eb-83f8-e247d62031ee.png)

**Comment by IonutDaniel98** [comment]
@javiercn  Thank you a lot. Now it is working fine.
