### ISSUE TITLE
dotnet run or dotnet watch run hangs after file change

### ISSUE THREAD

**Issue by ppiresdias** [dotnet/aspnetcore#31531]
Hello,

I installed .Net Core SDK version 3.1.407 and scaffolded an mvc web app template using `dotnet new mvc --auth Individual -o website`. If I run `dotnet run` or `dotnet watch run` without making any changes it works fine, but if I make a change to a file and try to rerun either of those two commands, it just hangs. I checked if any process is running on port 5001 while running the command(s) and there are none. I'm on macOS 10.15. 

Any help is greatly appreciated, thank you!

**Comment by ppiresdias** [comment]
It seems that when I `Control + C` to leave the process, it runs ok when I do `dotnet run` or `dotnet watch run` even with file changes. Before I was doing `Control + Z`. Perhaps, Control + Z leaves certain things running in the background that is supposed to be stopped or removed when the app exits?

**Comment by pranavkm** [comment]
Using `Control + C` would be the right way to go about exiting a dotnet process. For dotnet-watch, you shouldn't need to kill the process between file changes (since watch is responsible for rebuilding the app once it's detects changes). For more details on how to use watch, see https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-6.0

**Comment by ppiresdias** [comment]
Thank you. I'm having no issues running the application now.
