### ISSUE TITLE
Add a way to prevent re-rendering after processing an `EventCallback` in Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#31549]
## Summary

Provide a mechanism that allows user to determine when re-rendering should not occur after an `EventCallback` has been processed on a component.

## Motivations and Goals

In a previous iteration of this design doc, the goal was to make it easier for developers to avoid re-rendering for events that are triggered frequently. The main motivation was to reduce the perf impact for customer scenarios. I played around with the following customer reported customer scenarios:

* Large tables with `OnScroll` event handlers. 
* Large tables with an `OnClick` handler in an element outside the table that modifies a single element. 
* Component with event handler that does not modify state.

From this, I came to the following conclusions.

* For some  scenarios, the problem can be resolved by implementing better component best practices. For example, writing components that take primitive values to take advantage of the diffing logic.
* For scenarios like the `OnScroll` and `OnMouseMove` event handlers, the solution would be better addressed via https://github.com/dotnet/aspnetcore/issues/10522.
* The workarounds under "Current Approaches" are sufficient for most of the scenarios covered.
* In a few of the scenarios, perf impact can be reduced by leveraging new features like Virutalization and AoT.

With that in mind, I believe the goal should be to make it easier to.

* Users should be able to determine whether or not a re-render occurs for all events on a component.
  * So far, I haven't seen any scenarios where a single component has two events where it makes sense to not render for one but for the other. 
* The implementation should not require any modifications to the Razor syntax.
* The API should be easier to use than existing appraoches. Easier here means fewer lines of code and less juggling of state.
* Users want to be able to re-render if the parameters provided to a component change but not if event handlers on it are called.

## Current Approaches

The following approaches currently exist for solving the problem of "preventing render on event callbacks"

**Use Action parameter for event handler**

```
<button @onclick="@Handler">Click me</button>

@code {
  [Parameter]
   Action<MouseEventArgs> Handler;
}
```

**Custom implementation of IHandleEvent**

```
@implements IHandleEvent

<button @onclick="@HandleClick">Click me</button>

@code {
    private void HandleClick() {
        System.Console.WriteLine("Clicked...");
    }

    Task IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, object arg)
    	=> callback.InvokeAsync(arg);
}
```

**Provide an override for ShouldRender**

Developers can implement a `ShouldRender` override that returns false when required for their event handler.

```
<input @keydown="ProcessKeydown">

@code {
  private bool shouldReload = true;
  
  private void ProcessKeydown() {
  	shouldReload = false;	
  };
  
  protected override void ShouldRender() {
    if (shouldReload) {
      return true;
    }
    return false;
  }
}
```

## In Scope

* Avoid changing too much of the existing event handling logic in `ComponentBase`
* Avoid requiring users to roll out their implementations of native primitives (`ComponentBase`, `IHandleEvent`)

## Out of Scope

* Allow users to specify which event handlers should not trigger a re-render

## Risks/Unknowns

* **Risk:** There might be some confusion around the existence of both a `ShouldRender` and `ShouldRenderForEvent`.
* **Risk:** We want to avoid users using this feature as an escape hatch for best practices (e.g. using `Virtualization`).

## Examples

In the example below, a re-render will be triggered in the `MyEventCoponent` if the provided `Text` parameter changes but not if the `MyEventHandler` is invoked.

```
<h1>MyEventComponent</h1>

<p>@Text</p>

<button @onclick="MyEventHandler">Click me</button>

@code {
    [Parameters]
    public string Text { get; set; }
    
    protected override bool ShouldRenderAfterEvent() {
    	return false;
    }

    private void MyEventHandler() {
    	System.Console.WriteLine("Event handler that does not change state.")
    }
}
```

## Detailed Design

With this in mind, I think the idea of adding a `ShouldRenderAfterEvent` method to `ComponentBase` is the most promising.

```diff
public abstract class ComponentBase {
+	protected virtual bool ShouldRenderAfterEvent()
}
```

#### Considered Alternatives

**event:preventRender event handler**

<details>
<summary>Expand this for the original proposed design for this issue</summary>
## Summary

Provide a mechanism for producing pure event handlers that do not trigger a render during event handling.

## Motivation and goals

Currently, the `ComponentBase` classes implementation of `IHandleEvent.InvokeEventAsync` will call `StateHasChanged` which triggers the re-render of the component ([ref](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs#L310)). This is generally the desired behavior but there are some scenarios where developers need to implement event handlers that _do not_ re-render by default.

This is especially helpful for scenarios where:

- Re-rendering a component with a complex child tree can have a noticeable perf impact
- Developers want to avoid re-rendering on components where events are triggered frequently (e.g. `keydown` on large text inputs)

## In scope

- Allow users to specify which event handlers should not trigger a re-render

## Out of scope

- Supporting disabling re-rendering after event processing globally
- Avoid changing too much of the existing event handling logic in `ComponentBase`

## Risks / unknowns

* **Mitigated risk:** This behavior will be disabled by default and needs to be explicitly enabled by the user by setting `event:preventRender="true"` so the risk of confusing new developers who are used to the existing behavior is minimal.
* **Risk:** It's possible that users might assume that the `preventRender` attribute on a single event-handler
* **Risk:** The changes required to add support for the `preventRender` flag in the compiler and propagate it through to the `EventCallback` do add complexity to the `EventCallback` feature.
* **Risk:** Users need to be careful to only use `preventRender="true"` when intended or they run the risk of unexpected behavior (e.g. state inconsistent with UI) when their application is running.

## Examples

In the example below, the `preventRender` attribute is used to disable re-render on the component when #event-with-prevent-render is clicked.

Both buttons invoke `IncrementCount` which does not modify component state. #event-with-render will still re-render even though no state is changed.

```csharp
@page "/counter"

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount" @onclick:preventRender="true" id="event-with-prevent-render">Click me but don't render</button>

<button class="btn btn-primary" @onclick="IncrementCount" id="event-with-render">Click me and render</button>

@code {
    private int currentCount = 0;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender) {
            System.Console.WriteLine("First render...");
        } else {
            // Should not happen when #event-with-prevent-render is called
            System.Console.WriteLine("Rendering again...");
        }
    }

    private void IncrementCount() {}
}
```

## Detailed design

The implementation for this feature will be a two-step process with a change in the compiler and a change in the Blazor runtime.

To support this feature, the Razor compiler needs to be updated to produce the following generated code when a  `preventRender` attribute is included in a particular event handler.

```
<button  class="btn btn-primary"  @onclick="IncrementCount"  @onclick:preventRender="true"  id="event-with-prevent-render">Click me but don't render</button>
```

...will produce...

```csharp
__builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.PureEventCallbackFactory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, IncrementCount));
```

💡 : Note: this change needs to be populated to the Razor SDK for the future to fully light up.

The code above will utilize a new `PureEventCallbackFactory` that produces `EventCallback` s with their `PreventRender` attribute set to `true`.

Adjacent to this, we introduce a new internal property on the `EventCallback` that is set via a new constructor.

```csharp
public class EventCallback {
  + internal readonly bool PreventRender = false;
  + public  EventCallback(IHandleEvent? receiver, MulticastDelegate? @delegate, bool  preventRender) {}
}
```

Inside `EventCallback.InvokeAsync`, we use `PreventRender` to determine whether we want to call `HandlePureEventAsync` or `HandleEventAsync` on the receiver.

```csharp
return  PreventRender ?
	Receiver.HandlePureEventAsync(new  EventCallbackWorkItem(Delegate), arg)
	Receiver.HandleEventAsync(new  EventCallbackWorkItem(Delegate), arg);
```

The `HandlePureEventAsync` method is a new method on the `IHandleEvent` interface.

```csharp
public interface IHandleEvent {
  + Task  HandlePureEventAsync(EventCallbackWorkItem  item, object? arg);
}
```

In `ComponentBase` , we implement this `HandlePureEventAsync` method that does not invoke `StateHasChanged` after processing the event handler.

```csharp
 Task IHandleEvent.HandlePureEventAsync(EventCallbackWorkItem callback, object? arg)
 {
	 ...
 
     -    StateHasChanged();

     ...
 }
```
</details>

**PreventRender in EventArg**

In the framework:

```csharp
public class ComponentEventArgs : EventArgs
{
    public bool PreventRender { get; set; }
}

// And now our built-in EventArgs types are changed to inherit from it, plus custom EventArgs types can optionally inherit from it:
public class MouseEventArgs : ComponentEventArgs
{
   // ... same properties as before ...
}
```

In the component:

```csharp
private void HandleSomeEvent(MouseEventArgs eventArgs)
{
    eventArgs.PreventRender = true;

    // ... and now the rest of your event logic ...
}
```

**Comment by SteveSandersonMS** [comment]
Looks like a great start! I'll give more detailed feedback later, but the first thing I wonder is - instead of adding the new `HandlePureEventAsync` method, did you consider adding some `ShouldRender` bool flag to the existing `EventCallbackWorkItem` struct so the info is available to the existing `HandleEventAsync`? Or does that not work out for some reason?

**Comment by captainsafia** [comment]
> Looks like a great start! I'll give more detailed feedback later, but the first thing I wonder is - instead of adding the new HandlePureEventAsync method, did you consider adding some PreventRender bool flag to the existing EventCallbackWorkItem struct so the info is available to the existing HandleEventAsync? Or does that not work out for some reason?

With regard to avoiding adding a new method on the `IHandleEvent` interface, I did approach adding a new `preventRender` parameter to the `HandleEventAsync` method and tried that out here: https://github.com/dotnet/aspnetcore/blob/09062d994dcc98f5cc961663c62eb757f4d49944/src/Components/Components/src/ComponentBase.cs#L301

but I was a little wary of the boolean trap I used here. Obviously, that's not the only way to pass this property to the method and I considered adding the flag on the `EventCallbackWorkItem`, but my intuition was telling me that it wasn't totally necessary to pass down the `PreventRender` attribute from the `EventCallback` to the `EventCallbackWorkItem` ([ref](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/EventCallback.cs#L61)) if we could just conditionally call the correct method on the `IHandleEvent` inside `EventCallback.InvokeAsync`.

Is there a benefit to propagating the flag to the `EventCallbackWorkItem` that I am missing?

**Comment by SteveSandersonMS** [comment]
> Is there a benefit to propagating the flag to the EventCallbackWorkItem that I am missing?

Mainly just to simplify things for people implementing `IHandleEvent`. If there are two methods, then:

 * It's tricky for people with existing implementations to know what's going to happen. Presumably we'd use a default interface implementation to make `HandlePureEventAsync` call `HandleEventAsync`, but it's hard for people to know that.
 * The complexity could keep growing. Maybe we want to add further flags or parameters in the future - we could end up with a lot of variations on these methods.
 * Naming is tricky. It's not clear what a "pure" event is, for anyone who doesn't already know, and even then it's a bit of a dubious name since presumably the event must have some side-effects otherwise there would be no point raising it.

If it's possible to add a `PreventRender` flag on `EventCallbackWorkItem`, that seems to avoid all three problems but perhaps there's more to it than I've considered. Let me know what you think!

**Comment by SteveSandersonMS** [comment]
As a separate sub-discussion, would it be possible to add the following alternative "design considered" - which you're absolutely welcome to reject in the end, but I think we should at least consider it.

Given that the re-rendering behavior is purely a behavior of `ComponentBase`, we could argue that the only thing we need to do is provide a way to change that default behavior on `ComponentBase`. Rather than needing any new Razor syntax, we could just add a new `virtual` method on `ComponentBase`:

```cs
protected virtual bool ShouldRenderAfterEvent() => true;
```

Developers who want to call `StateHasChanged` manually after an event on a specific component would override this to return `false`, somewhat like how they can do a similar thing for `ShouldRender`. The `ComponentBase` logic would call this method as part of its event-handling logic and use the return value to decide whether or not to call its own `StateHasChanged` after handling the event (including asynchronously).

The main differences from the original design here are:

 * Cons: It can't be controlled on a per-event basis - it's all-or-nothing for any given component. This is inconvenient if you're adding a new event to an existing component, because you'd have to go through the other event handlers on the same component and put in `StateHasChanged` calls.
 * Pros: It's cheaper for us to implement, as there's no new Razor syntax, no different rendering APIs, no need to thread any state through the `EventCallback` objects etc. It's conceptually simpler as it's clearly just an aspect of `ComponentBase` and not a wider framework feature. It does support a "global default"-type pattern, as you could put the `ShouldRenderAfterEvent` override into a common component base class.

As for whether the "con" here makes it unacceptable - I can totally believe that problem is too bad and makes this simplification unfeasible - but it would be great to determine one way or the other based on the original customer requests. Do we have evidence that enough people want to do this that a more integrated/expensive solution is justified? Or is the sense from people asking from this that they just want to set a global/semiglobal default, in which case the simplification is actually better for them?

**Comment by javiercn** [comment]
I went through the issue to read through:
* Is the scenario what we want to optimize for? 
  * (A "side-channel" for getting updates instead of as a result from an action/event")
  * That doesn't feel a common scenario nor something we want to enforce.
    * More details would be needed here.

The conversation seems to turn into "perf" at some point:
* Is perf the problem we are trying to solve?
* If so, is this the right approach?
  * What are our perf goals (let's say stay under 100ms per interaction as per the RAIL model) 
    * See here for details: https://web.dev/rail/#focus-on-the-user
  * What's a concrete scenario where those goals are not being met.
    * How many customers are impacted by it.
    * What solutions can those customers implement (alternatives).
    * How hard is to implement each of those solutions.

My take so far is:
* I don't think we have enough evidence to justify introducing a "per handler" render behavior.
  * We already provide mechanisms to control "when/how often" a component should render.
  * We don't have a concrete scenario where we can say we aren't meeting our perf goals.
    * We should start by defining the scenarios we care about.
    * We should stablish a concrete perf goal.
    * We should assess whether we are meeting that goal.
    * We should brainstorm solutions for that scenario.

* It seems to me that we are jumping into solutions without a clear scenario in or a perf goal in mind.

If this is a common problem, then a solution like this will force everybody to constantly add this attribute to their markup which will be cumbersome.
If this is not a common scenario, why does it need a "first class" solution?

As per the design/implementation I think its fine for the most part provided this is something we want to do. The main piece that I'm having issues with
is the introduction of a language feature that relies on ComponentBase for its implementation. Coupling the language feature with an implementation is not
something we want to do, it forces every component to account for that behavior and there's no guarantee it is respected unless you are using ComponentBase.

**Comment by SteveSandersonMS** [comment]
> What are our perf goals (let's say stay under 100ms per interaction as per the RAIL model
> We should assess whether we are meeting that goal.

That's a tricky criterion to use as we can't know how expensive any given rendering event will be - it depends on the whole component subtree and all the user code in it.

One scenario where people have raised concerns is with things like `@onmousemove` - it *feels* wasteful to be re-rendering the whole subtree on every mouse movement, whether or not the machine can handle it. I know we'd like some kind of throttling for that kind of frequent event, but even then, developers may want to combine both throttling and "don't re-render the subtree every time" to provide an ideal experience. So I can sympathise with developers' wish to have a feature like this even when quantifying the payoff is complicated.

> I don't think we have enough evidence to justify introducing a "per handler" render behavior.

That seems like the biggest design pivot point right now, so will be interested to get @captainsafia's perspectives on it based on the community reports and requests.

**Comment by captainsafia** [comment]
With regard to the perf criterion, we've had a few users come in with scenarios for this. The one scenario were we do have stats is the "typing in a large input box" scenarios that is reported by a user in https://github.com/dotnet/aspnetcore/issues/17951. 

When I was investigating it last year, I observed that the handling for each event was getting a little close to the 100ms for a single scenario (https://github.com/dotnet/aspnetcore/issues/17951#issuecomment-625985945).

> I don't think we have enough evidence to justify introducing a "per handler" render behavior.

Yep. So the "global option on the component" was something that I actually considered out-of-scope based on my investigation with the problem. Users were already able to disable the re-render behavior by having cleverness in their `ShouldRender` that would disable rendering from an event handler. However, users were complaining about having to implement this complex logic to get a desired result. ([ref](https://github.com/dotnet/aspnetcore/issues/17951#issuecomment-570587871), [ref](https://github.com/dotnet/aspnetcore/issues/18919#issuecomment-675485982)). The general impression I got was that it was important for users to want to react to a particular handler instead of all of them by default.

> Coupling the language feature with an implementation is not
something we want to do, it forces every component to account for that behavior and there's no guarantee it is respected unless you are using ComponentBase.

Thanks for calling this out! This actually wasn't a philosophy that I accounted for in my design and now that you and Steve have mentioned it -- I can definitely see why it is problematic.

My new thoughts on this:

- I do think this is a problem worth solving, especially with regard to perf, based on the problems that customers have approached us with. We can craft benchmarks/scenarios as part of this work but prior experience tells me this is a problem.
- I do think it's important to make it easy for users to disable/enable this on a per handler/event basis.
- I agree that it is important to not introduce new Razor syntax for this. It also has the side-effect of making this feature a lot easier to ship (e.g. no need to wait for things to flow to the SDK).

> protected virtual bool ShouldRenderAfterEvent() => true;

This inspired me. What if we tweak this a bit so that it looks something like this:

```csharp
protected virtual bool ShouldRenderAfterEvent(SomeTypeHere val);
```

Wherein `SomeTypeHere` is a object that contains information about the event type of the invoked handler (I'll have to look into if that is possible). Then users can do something like this:

```csharp
protected override bool ShouldRenderAfterEvent(SomeTypeHere val)
{
   if (val.EventType == "onmouse")
   {
      return false;
    }
}
```

💡 I put `SomeTypeHere` because I'm not sure if an existing type (e.g. `EventCallbackWorkItem`) would suffice to use here.

If that seems compelling, I can play around with this idea and update the design doc with something more concrete.

**Comment by rogihee** [comment]
I'm not sure I agree that re-rendering on every event should be the desired default behavior. 

An event does not always equals a state change, which is now assumed. 

IMHO an event _may_ trigger a state change, but should not by default.

**Comment by SteveSandersonMS** [comment]
```cs
protected virtual bool ShouldRenderAfterEvent(SomeTypeHere val);
```

I'm not sure about this. If a component has more than one event handler of a particular type, it doesn't seem like we could communicate which of them we're talking about, so this seems like a half-solution. I know there are *some* cases where it would happen to be sufficient, but would be extra confusing in the cases where it isn't. 

TBH I'd be more comfortable with it just being an all-or-nothing choice you make per-component. That would be much easier to understand - people would just have to call `StateHasChanged` explicitly within all events on that component, without having to reason about *which* of the event handlers need this. It would also be more satisfying for developers who have the following kind of preference:

> I'm not sure I agree that re-rendering on every event should be the desired default behavior ... IMHO an event may trigger a state change, but should not by default.

... since the "no re-rendering by default" could be achieved project-wide via a single override on a base class.

### One other possibility, if we really want to do this on a per-handler basis:

This is probably nonsense, but I'll raise it for consideration anyway :) Inspired by JavaScript's `preventDefault`-type APIs, imagine something like this:

```cs
private void HandleSomeEvent(MouseEventArgs eventArgs)
{
    eventArgs.PreventRender = true;

    // ... and now the rest of your event logic ...
}
```

It could be something like this:

```cs
public class ComponentEventArgs : EventArgs
{
    public bool PreventRender { get; set; }
}

// And now our built-in EventArgs types are changed to inherit from it, plus custom EventArgs types can optionally inherit from it:
public class MouseEventArgs : ComponentEventArgs
{
   // ... same properties as before ...
}
```

The logic in `ComponentBase` can simply check whether the `EventArgs` type is a `ComponentEventArgs`, and if so whether its `PreventRender` flag was mutated after the initial synchronous call to the event handler.

Drawbacks:

* Not certain whether it might be breaking to anyone to add an extra layer of base class between our `EventArgs` subclasses and `EventArgs` itself. I guess it would be breaking for anyone who has a subclass that already has a `PreventRender` member on it (which is probably nobody yet since 5.0 doesn't support custom event args).
* It doesn't provide any nice way to set a component-wide or project-wide "don't re-render" default, which the `ShouldRenderAfterEvent` method would do

...so I'd still strongly recommend trying to work out what the primary customer scenarios are here and how we're going to cover the concrete requirements we see. I'm kind of suspicious of this whole `ComponentEventArgs` idea because it somehow feels too fancy. But maybe you have other ideas or designs!

**Comment by javiercn** [comment]
@SteveSandersonMS that's not a bad idea.

**Comment by mrpmorris** [comment]
Why include ="true" at all? Just event:preventRender would be enough. If the coder wants to conditionally render in the event that can call StateHasChanged

**Comment by mrpmorris** [comment]
I like the option of being able to disable auto render from events on a per component basis and having to call StateHasChanged.

But when there are lots of events and we only want to prevent one from rendering then disabling per event would be good.... @onclick:NoRender

**Comment by mrpmorris** [comment]
Added to 6.0-Preview4, but closed due to lack of duscussion @mkArtakMSFT

**Comment by ChristianWeyer** [comment]
Do you have a link to docs or a sample @mrpmorris ? Thanks.

**Comment by javiercn** [comment]
@mrpmorris This somehow fell out the cracks.

We decided to not do anything here for the time being:
* We are not planning to add language features that depend on more opinionated layers of the framework (like component base).
* We are not planning to change the implementation in component base to support something different that what we currently support.
* We believe it only takes a few lines of code to implement whatever behavior you want within a given class and that it can be shared at the project level via a common base class or even in a nuget package.

We understand that this might not match your expectations, however we think that the framework already provides an out of the box behavior that is reasonable for the vast majority of scenarios, that we offer enough extensibility points for developers to implement their own semantics/opinions and that the added complexity and maintenance cost doesn't justify the additions in this area.

Hope this helps.
