### ISSUE TITLE
Why remove libuv support

### ISSUE THREAD

**Issue by jackletter** [dotnet/aspnetcore#31700]
## Why remove libuv support?

When I upload a test file, when more than 200 30KB files are uploaded simultaneously, kestral is stuck, and libuv is very smooth！

## My Test Code
```csharp
[HttpPost]
public string Upload()
{
    var files = Request.Form.Files;
    if (files == null || files.Count == 0) return "error";
    var requestId = Guid.NewGuid().ToString();
    return requestId;
}
```

My Test Server is Window Server 2019,Asp.net core 3.1;

**Comment by davidfowl** [comment]
> Why remove libuv support

https://github.com/aspnet/Announcements/issues/424

> When I upload a test file, when more than 200 30KB files are uploaded simultaneously, kestral is stuck, and libuv is very smooth！

It's because of your code, not the libuv transport. Using Request.Form is blocking and likely causing you performance problems. There are a bunch of ways to improve this:
- Accept an IFormFile directly in the method argument. MVC will read the files using the appropriate APIs (and call your method)
- Use [`Request.ReadFormAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.requestformreaderextensions.readformasync?view=aspnetcore-5.0) to get the list of files
- Use the more efficient API and avoid buffering the entire request https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#upload-large-files-with-streaming

Hope that helps. If you have some performance profiles showing Kestrel being faster with Libuv, we'd love to take a look.
