### ISSUE TITLE
Currently blazor can't use system.security api when configured for .net core 5 in visual studio

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#31701]
For mordern applications, the ability to use encryption plays a crucial part in its logic. Since there is no support currently for system.security, should we update our Microsoft.AspNetCore.Components.WebAssembly or wait for further releases of blazor, what's the suggestion?

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

It's not immediately obvious what you are trying to do here. Can you clarify what is not available that you need?

**Comment by javiercn** [comment]
Likely a dupe of https://github.com/dotnet/runtime/issues/44996#issuecomment-817350693

**Comment by Xyncgas** [comment]
I found a suggestion here :https://github.com/dotnet/runtime/issues/40074
to use web crypto api for replacement.
My issue was immediately that I saw options for blazor projects to be using .net 5, but discovering that it doesn't support the system.cryptography was an urgent issue at hand and the microsoft document ( https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly ) is saying there isn't a work around.
Right after I saw the thread I understand why you are doing it.
So a bit suggestion is it would be nice if we can call web crypto api in blazor apps using c#, maybe through some nuget packages, making it easier since we can not use system.cryptography anymore

**Comment by javiercn** [comment]
@Xyncgas thanks for the additional details.

As far as I know the original issue is tracking the fix inside the runtime for 6.0. We don't plan to offer a package specifically in Blazor since that would require library authors to take a dependency on it and would fork the ecosystem when it comes to cryptography in .net based on whether a project is targeting Blazor or not.

The runtime is the place to get support for this via webcrypto and I believe it's planned for 6.0, so this will be fixed by the runtime at that point. If you can't wait, you can write a JS interop library to use webcrypto directly, however that's not something we plan to invest resources on from the Blazor side.
