### ISSUE TITLE
The name 'fromAccount' does not exist in the current context [BankProgram]csharp(CS0103)

### ISSUE THREAD

**Issue by kdodan** [dotnet/aspnetcore#31796]
Hi guys,
I am new to C# and got this error while doing one of my tasks. 

Here is my TransferTransction class file. 
<img width="545" alt="Screen Shot 2021-04-14 at 7 43 27 pm" src="https://user-images.githubusercontent.com/82506978/114693720-3c0df880-9d5d-11eb-8447-ea4fa0bf11ac.png">

And here's my Program class file, where I get the error message. 
<img width="970" alt="Screen Shot 2021-04-14 at 7 44 03 pm" src="https://user-images.githubusercontent.com/82506978/114693546-0ec14a80-9d5d-11eb-983e-3504e682dce1.png">

Can anyone please help me to find what I have done wrong..??

**Comment by javiercn** [comment]
@kdodan thanks for contacting us.

The problem in your code is that you are passing values as parameters to the constructor but you are not creating an instance of those parameters first. You would have to do something like

```csharp
Account fromAccount = new Account();
Account toAccount = new Account();
...
TransferTransaction transferTransaction = new TransferTransaction(fromAccount, toAccount, ammount);
```

Note that you are receiving an account as a parameter already, I don't know the semantics of the code you are writing so I can't advise you on that. However I imagine that  the semantics are along the lines of `sourceAccount.DoTransfer(destination)` or similar and in that case it would be something like this

```csharp
Account fromAccount = new Account();
Account toAccount = new Account();
...
TransferTransaction transferTransaction = new TransferTransaction(this, account, amount);
```

Hope that helps.

**Disclaimer**: Please keep in mind that this issue tracker is meant for product issues and not as a general place to answer general questions regarding C# or programming questions. We recommend you post this question in https://stackoverflow.com to get a better and faster answer since we don't have the resources to deal with these types of questions here. For that reason we will be closing this issue
