### ISSUE TITLE
Remove dotnet new --uninstall workaround from the template 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31807]
SDK issue: dotnet/templating#3041

Commit to undo: https://github.com/dotnet/aspnetcore/pull/31748/commits/360f7054a59317bc5d9f00761a95e9aef838ed1c (a small part of #31748)

**Comment by dougbu** [comment]
To clarify: It's likely not possible to revert https://github.com/dotnet/aspnetcore/pull/31748/commits/360f7054a59317bc5d9f00761a95e9aef838ed1c in the normal way because that commit was squashed into @cede6c4fbb3a along w/ the rest of #31748. But, we should undo that part of the PR when dotnet/templating#3041 is fixed.

@pranavkm will we need to react in other ways once dotnet/templating#3041 is fixed❔

**Comment by BrennanConroy** [comment]
Was this resolved as part of https://github.com/dotnet/aspnetcore/commit/90137b0336616a30b28a9de80ca6a9a0671e94d7?

If so, I'll close this when that change gets to main.

**Comment by dougbu** [comment]
> Was this resolved as part of 90137b033661

Yes and @halter73 cherry-picked that from #32054 but the merge from preview4 got into 'main' first. I'll close #32054, with thanks to @DavidKarlas.

> If so, I'll close this when that change gets to main.

It has 😀
