### ISSUE TITLE
ResolveServiceProviderFactory should work with Minimal Hosting

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#31861]
Tools like EF migration rely on `Program.CreateDefaultBuilder()` at build-time to build the service container and resolve services (like DbContext). 

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs

**Comment by javiercn** [comment]
@shirhatti also Microsoft.AspNetCore.Mvc.Testing depends on that

**Comment by DamianEdwards** [comment]
I'm wondering if we could use a startup hook to enable this somehow, rather than boilerplate code that must be in the app for it to work. Alternatively, could we use a source generator that's enabled by the invoking tool (e.g. `dotnet ef`) to generate the required pattern or hook somehow.

**Comment by davidfowl** [comment]
I had an idea that we could use a diagnostic source for this but that won't work since this pattern basically wants a public API that is callable.

EF - https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs#L49-L59
Testing - https://github.com/dotnet/aspnetcore/blob/fdd687bae97ab2719f20d04fcea13fa5e31a5249/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L339-L347

These rely on a callable entrypoint

**Comment by davidfowl** [comment]
Actually we might still be able to do this.

**Comment by davidfowl** [comment]
This is fixed by
- https://github.com/dotnet/runtime/pull/53757
- https://github.com/dotnet/runtime/pull/54052
- https://github.com/dotnet/runtime/pull/54090

WebApplicationFactory support
- https://github.com/dotnet/aspnetcore/pull/33462
