### ISSUE TITLE
Unhandled exception rendering component in blazor server side, not able to found issue

### ISSUE THREAD

**Issue by SyedAunHaider** [dotnet/aspnetcore#31931]
Hi all,
 
 I'm facing unhandled exception and its happening randomly. not able to found the root cause of the issue have debugged code again and again but no success.
 
 [WRN] Unhandled exception rendering component: TypeError: Cannot read property 'removeChild' of null
System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
2021-04-18 21:07:28.171 +02:00 [ERR] Unhandled exception in circuit 'H0A-alngg7peorGBonCDrncy9uCjmTEQvKewU72tjgk'.
System.AggregateException: One or more errors occurred. (TypeError: Cannot read property 'removeChild' of null)
 ---> System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by SyedAunHaider** [comment]
I can share code via any file , because we can reproduce error only on production , if we try to load page 100 times , then maybe 3 times it will fail. How I can provide the minimalistic code for it.
this is website URL (https://betapakke.dao.as/nyPakke)
also have attached the 2 pages code which are causing issue

[Pages.zip](https://github.com/dotnet/aspnetcore/files/6342334/Pages.zip)

**Comment by SyedAunHaider** [comment]
This is the component of header which is used in pages and have logic in it

[Header.zip](https://github.com/dotnet/aspnetcore/files/6342379/Header.zip)

**Comment by mkArtakMSFT** [comment]
Thanks @SyedAunHaider.
We can't access `.zip` files per our policy. Can you please share those as publicly hosted GitHub repos instead?

**Comment by SyedAunHaider** [comment]
Hi Artak,
Due to some company policy , i'm unable to upload code. only thing that will help us 
did in blazor we can catch render tree exception at global level or any other way. We have already did logging on all blazor event  methods line onIntialize , onRender and every function , but not able to catch exception anywhere. Any way to catch this exception and reload the page

**Comment by SteveSandersonMS** [comment]
I tried loading your page at https://betapakke.dao.as/nyPakke about 50 times and the error mentioned never appeared, so unfortunately this is quite difficult to provide a diagnosis. Without simpler repro code, I'm afraid I can't proceed with any investigation.

What I suspect is likely happening is that some of your other JavaScript code that mutates the DOM may be interfering with Blazor's rendered output. We have guidance about this [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#use-of-javascript-libraries-that-render-ui-dom-elements). In particular, you need to make sure that the DOM managed by Blazor doesn't get modified by external code:

> Blazor's diffing system relies on having control over the tree of DOM elements and runs into errors if some external code mutates the DOM tree and invalidates its mechanism for applying diffs. This isn't a Blazor-specific limitation. The same challenge occurs with any diff-based UI framework.

To try to track down which code paths are causing your issue, approaches you could try include:

 * Incrementally removing or commenting out more and more sections of functionality until the error stops occurring
 * Or, use the browser's JS debugger to set a breakpoint on all the lines in `blazor.server.js` that call `removeChild`, and have the breakpoint be conditional so that it only fires if the parent is `null` or `undefined`. Then you might be able to infer from the context which part of the document has become unreachable.

Since the issue isn't reproducing when I try it, this isn't something I can help with further unfortunately!
