### ISSUE TITLE
HttpLoggingMiddleware + Websockets/Upgrade

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31962]
We need to verify that we either log the response correctly or disable request and response logging for websocket upgrades.

**Comment by Tratcher** [comment]
We should be able to log upgrade requests normally (Request.Body is not used for upgrades).

For upgrade responses we'll have to wrap the upgrade feature in order to get a timely notification of the upgrade and log headers. Otherwise the default logging will happen when the middleware eventually exits. No special handling is required for the body, Response.Body is not used for upgrades.

**Comment by gfr-g** [comment]
Hello, I would like to take a look at this issue but it's my first time working with this codebase and I'd appreciate some direction.

From my initial investigation, the issue seems to lie in the way AcceptWebSocketAsync() sends the response to the upgrade request, by "temporarily bypassing" the middleware pipeline.  This appears to be as designed, since also the documentation mentions the fact that the middleware pipeline should be kept running, although I'm curious to know why it was designed this way. 

From a pure speculative point of view, what I expected to happen is something like: 

- AcceptWebSocketAsync() should accept a delegate that handle the messages inside the WebSocket that will eventually be established

- The 101 response is sent using the usual way, by short circuiting the middleware pipeline

- The WebSocket "upgrades" the connection and is tied to it (so it should not be disposed or reused) and not to the request through the HttpContext.  

I'd like to hear your thoughts about this. I surely have missed a lot of nuances, and I'm also curious to know if there is a easier way to handle this as @Tratcher mentioned that a possible solution is to "wrap the upgrade feature". 

Thank you

**Comment by Tratcher** [comment]
@gfr-g we tried that design in prior stacks like ASP.NET 4.x and Microsoft.Owin, it had its own tradeoffs. Regardless, that's not a design point we can change at this point without breaking all the current users.

And yes, it should be possible to wrap the `IHttpUpgradeFeature` similar to how logging wraps the response body today. When UpgradeAsync is called that would trigger the same response header logging as writing to the response body does. We would not want to capture any of the actual websocket traffic.
https://github.com/dotnet/aspnetcore/blob/f08285d0b6918fbb2b485d97f4e411dc9ea9a94f/src/Http/Http.Features/src/IHttpUpgradeFeature.cs#L9

**Comment by gfr-g** [comment]
@Tratcher thank you very much for your answer but, unfortunately, I think I'm missing something very obvious because I wasn't able to figure out exactly what you mean. 

This part: "And yes, it should be possible to wrap the IHttpUpgradeFeature similar to how logging wraps the response body today. When UpgradeAsync is called that **would trigger the same response header logging as writing to the response body does**." makes me believe there's an actual system in place that immediately logs the response headers when the response body is written to. I failed to find this wrapping mechanism in the source code and I also failed to make it work with a simple example like this that I believe should show what I think you meant with the sentence above

```
[...]

app.UseHttpLogging();
app.Use(async (context, next) =>
{
	await next();
	await Task.Delay(10000);
});

app.Run(async (context) =>
{
        // not really necessary 
	context.Response.StatusCode = 200;
	context.Response.Headers.ContentType = "text/html; charset=UTF-8";

        // write to the body
	await context.Response.WriteAsync("test");
});

[...]

```

I'm not able to see any response headers being logged (I used the console provider and the event source provider) while the middleware pipeline is waiting for the ten seconds delay.

Would you mind to please elaborate further your proposal?

**Comment by Tratcher** [comment]
See here:
https://github.com/dotnet/aspnetcore/blob/999d3d0af1194a8d59fd4d0a56db036a3bc7e7f2/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L138-L151
https://github.com/dotnet/aspnetcore/blob/999d3d0af1194a8d59fd4d0a56db036a3bc7e7f2/src/Middleware/HttpLogging/src/ResponseBufferingStream.cs#L123-L133

It looks like this is only triggered when response body logging is enabled. Otherwise it logs after `next()`:
https://github.com/dotnet/aspnetcore/blob/999d3d0af1194a8d59fd4d0a56db036a3bc7e7f2/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L162-L166

For WebSockets you'd add a wrapper for `IHttpUpgradeFeature.UpgradeAsync` kindof like how `IHttpResponseBodyFeature` is wrapped here.

**Comment by gfr-g** [comment]
Thank you, understood. I'll work on it.
