### ISSUE TITLE
How to allow `.config` file download?

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#31973]
I hope all files in a specified folder can be download, so I did this:
```c#
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".config"] = "application/octet-stream";

app.UseStaticFiles(new StaticFileOptions()
{
    FileProvider          = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "xxx")),
    RequestPath           = "/xxx",
    ServeUnknownFileTypes = true,
    DefaultContentType    = "application/octet-stream",
    ContentTypeProvider   = provider,
});
```
it work well for `.exe|.dll`, except `.config`, got this:
![image](https://user-images.githubusercontent.com/12094247/115372601-a90e0c00-a1fd-11eb-8db7-c02e0984af7d.png)

Please help.

**Comment by blowdart** [comment]
IIS by default will block .config urls, which frankly is a good thing. If you must allow it, and I strongly recommend you do not allow it because for older asp.net versions config files contain secrets you can try [this](https://forums.iis.net/t/1150046.aspx). However, I repeat this is a bad idea from a security perspective.

**Comment by ahdung** [comment]
@blowdart Thank you for your link, it's worked:
```xml
<system.webServer>
  <security>
    <requestFiltering>
      <fileExtensions>
        <remove fileExtension=".config" />
      </fileExtensions>
    </requestFiltering>
  </security>
</system.webServer>
```
Regard security, I know what I do.
