### ISSUE TITLE
Improve RoleManager documentation

### ISSUE THREAD

**Issue by Sc7-git** [dotnet/aspnetcore#32005]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

### Additional context

Dear senior, Hello:
I have never been in contact with asp net identity, how to learn asp net core identity systematically?
I read security/authentication and security/authorization/ under the asp net core document, I have practiced all my examples, except for examples such as spa, Azure, and third-party authentication.
But I still don’t understand how asp net core identity works, such as:
1. How does jwt work in identity, how to issue tokens to users, and how to verify users' tokens.
2. There is no detailed introduction to RoleManager, UserManager, and SignInManager in the document, especially RoleManager at all. Although I know that these auxiliary classes are to operate identity
For the database, since there is no specific document or demo, I still don't know what scenarios these functions are used in.
3. https://docs.microsoft.com/en-us/learn/modules/secure-aspnet-core-identity/ There are only simple cases.
5. Is there a step-by-step document, or recommend some information.
There is an urgent need to master this part of knowledge, and I hope my predecessors will advise. 
Poor English, please understand.

**Comment by blowdart** [comment]
JWT is not part of identity at all, if you need that you need to look at [Identity Server](https://codewithmukesh.com/blog/identityserver4-in-aspnet-core/), or [OpenIddict](https://documentation.openiddict.com/guide/index.html)

RoleManager is horribly undocumented, so we'll need to do that @HaoK 

The simple cases are what identity is aimed at, so I'd be interested to discover what extra you want on top of it. We don't have any step-by-step, because the simple cases generally cover the use cases, so knowing what you think the steps should be would help guide future documentation.

**Comment by adityamandaleeka** [comment]
> RoleManager is horribly undocumented, so we'll need to do that @HaoK

Re-titling this issue since it sounds like that's the actionable part.

**Comment by adityamandaleeka** [comment]
@HaoK That sounds good, RoleManager is covered by that issue already. Yea, let's prioritize getting that done soon.

**Comment by HaoK** [comment]
amusingly enough we duped the docs version of this issue already against this too https://github.com/dotnet/AspNetCore.Docs/issues/22096
