### ISSUE TITLE
Try out new .NET 6 logging generator

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#32087]
.NET 6 has a feature to generate logging classes from attributes. Could reduce the amount of boilerplate in our logging types while also validating log event IDs aren't duplicated.

See https://github.com/dotnet/runtime/issues/36022

We should try replacing some small static Log types with the new feature.

* [x] HttpAbstractions
* [x] Kestrel
* [x] Middleware
* [ ] HttpSys
* [ ] Mvc
* [ ] Components
* [ ] SignalR

**Comment by davidfowl** [comment]
I asked @maryamariyan to give it a try. I think there are some issues that will prevent full adoption but we should I aim to move. 

cc @gfoidl

**Comment by gfoidl** [comment]
If @maryamariyan's try succeedes I'd like to broaden that usage here (this generator seems really cool).
Further it's a good opportunity to detect some potential flaws and improve that generator before shipping .NET 6.

**Comment by gfoidl** [comment]
I made a quick test with the logging generator and it looks very promising, so I believe we can use that for some logging that needs to written new or to be rewritten (like the Kestrel trace).

**Comment by alefranz** [comment]
Looking forward for this. Let me know if you are looking for help.

**Comment by gfoidl** [comment]
ATM there are two (?) points that should get addressed before we can use the logging generator:

* allow nested classes https://github.com/dotnet/runtime/issues/52301
* allow skipEnabledCheck https://github.com/dotnet/runtime/issues/51927

**Comment by maryamariyan** [comment]
Opened this issue https://github.com/dotnet/runtime/issues/52549 to list up logging generator related issues. Not all need to be addressed right away.

@gfoidl I think https://github.com/dotnet/runtime/issues/51927 depends on how we end up with the API review on https://github.com/dotnet/runtime/issues/50913

**Comment by gfoidl** [comment]
IMO https://github.com/dotnet/runtime/issues/51927 is quite independent from https://github.com/dotnet/runtime/issues/50913. The logging generator can skip the IsEnabled-check if there's a LoggerMessage.Define overload, otherwise (in the fallback case) ignore that "hint" which is merely an optimization.

I know that https://github.com/dotnet/runtime/issues/51927 needs to be reviewed too, but when touching the logging for Kestrel, etc. it would be nice that it can be done once and use the goodness from the new logging generator.
It looks very promising, just some tiny pieces are missing (linked issues / also your list).

**Comment by adityamandaleeka** [comment]
Thanks @pranavkm for making a bunch of progress here. Moving to .NET 7 milestone to cover the remainder.
