### ISSUE TITLE
Consider using signed HTTP exchanges as a way to download ICU data on browsers that support it

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#32110]
ICU data is invariant of the app and is ripe for being distributed over a CDN. We could benefit from distributing the icu shards from a CDN in browsers that support [signed HTTP exchanges](https://tools.ietf.org/id/draft-yasskin-http-origin-signed-responses-02.html). It's supported on chrome 73 and newer - https://www.caniuse.com/sxg so that's a reasonable chunk of users which makes it worthwhile to pursue.

**Comment by javiercn** [comment]
@pranavkm I believe its a bit trickier than that, however I would point out that all files would benefit from this. Including doing this for the unlinked BCL

**Comment by SteveSandersonMS** [comment]
> I would point out that all files would benefit from this. Including doing this for the unlinked BCL

Could you clarify how the unlinked BCL could get involved here? I would have thoughts that, since no normal site is going to be unlinked in production, there's never going to be a case where an end user gets told to download the unlinked files.

Is your idea something like "*after starting up the app using the linked BCL, also in the background download the unlinked BCL, just for the benefit of speeding up loading 3rd-party sites*"? If so, I'd be surprised if anybody is willing to let their site be the sacrificial one that triggers this large download at no benefit to themselves (even though it's not from their server, an end user may still notice the heavy data usage caused when visiting the site).

I would have thought that the only files that could benefit are the ones that will naturally be identical across sites, of which the only large ones are ICU files.

> It also doesn't "help" as much since contents are deleted by chrome every 7 days.

That is a serious drawback which I hadn't fully realised before. Thanks for pointing that out.

Unfortunately it would be difficult to make a precise argument for this feature having a very beneficial impact, since (1) it would only apply to a smallish subset of the payload, and (2) it would only take effect once the user has visited a different but same-framework-version Blazor WebAssembly app in the last week. We couldn't use this to claim that Blazor WebAssembly apps are becoming lighter, since it would only be an edge case where it takes effect.

Given the cost side of it (us setting up a process to publish ICU data to some kind of CDN with each release, keeping that working, potentially dealing with new kinds of support issues from hosting a live service, measuring stats on usage), I'm less enthusiastic now about prioritising this. As a smaller step, we could try to make sure our existing mechanism for customizing the loader can work with SXGs on custom CDNs.

**Comment by javiercn** [comment]
> Could you clarify how the unlinked BCL could get involved here? I would have thoughts that, since no normal site is going to be unlinked in production, there's never going to be a case where an end user gets told to download the unlinked files.

This might be beneficial if your company ships many apps since it might make greatly diminish the cost of making an update (since the BCL is cached) or might have been already been cached by another app if there is a "shared CDN" serving all these assets.

Same for the runtime files like `dotnet.js` and `dotnet.wasm` since those are not linked either. My main concern here is that this is a lot of work involving setting up PKI infrastructure to deal and maintain the signed copies of things.

Another thing to point out is that while the cache might live for 7 days, the app might be able to cache the payload in their local caches, which could make them expire at a later point?

**Comment by SteveSandersonMS** [comment]
> might have been already been cached by another app if there is a "shared CDN" serving all these assets.

Only if that other app has chosen to fetch the entire unlinked BCL, which doesn't seem like something many people would want to do. Not saying it's completely impossible that someone might choose to do that, just that it's very much a minor edge case rather than what we'd expect from most apps.

> Same for the runtime files like dotnet.js and dotnet.wasm since those are not linked either. My main concern here is that this is a lot of work involving setting up PKI infrastructure to deal and maintain the signed copies of things.

True for `dotnet.js`, but whether it's true for `dotnet.wasm` today depends on whether you have an AOT build or not. Also part of the .NET 6 plan includes relinking `dotnet.wasm` if you have the Emscripten toolchain available (regardless of whether you're doing AOT) since we get to trim another 10-20% off it based on your feature usage, so in that case it would not be constant across sites.

I share your concerns about the cost.

> Another thing to point out is that while the cache might live for 7 days, the app might be able to cache the payload in their local caches, which could make them expire at a later point?

Yes, we already use application storage to hold per-site caches indefinitely, but does that somehow extend the lifetime of the SXG? If there's some way of proactively pushing content into the SXG cache (not just when it's fetched, like with a traditional CDN cache) then maybe that is possible, but I'm not sure that is how it works.

**Comment by mkArtakMSFT** [comment]
Closing as this is not something we plan to do.
