### ISSUE TITLE
Lazy loading at page level

### ISSUE THREAD

**Issue by fayewong6198** [dotnet/aspnetcore#32133]
As long as I researched, Blazor WASM only allowed to lazy loading as project level. Basically if I want to lazy load a component I have to create new WASM project and move the component to that project. May be I was wrong but right now I don't know to implement lazy loading to all my pages in my project efficiency. I means easy to implement just like React and Angular.

Does my understand is correct ? If not what is the correct way to implement lazy loading for an enterprise app ?

**Comment by javiercn** [comment]
@fayewong6198 thanks for contacting us.

In general the unit of deployment in .NET is the assembly, that's why lazy loading is supported at the assembly level. To support lazy loading at the page level every page should be on its own assembly, since pages are compiled to C# Types and those must live within an assembly, which is what the .NET runtime knows how to load and run.

**Comment by fayewong6198** [comment]
@javiercn So in theory it is impossible for blazor-wasm or it will be added in the future?

**Comment by javiercn** [comment]
@fayewong6198 It's not possible today and it is not something we plan to pursue in the foreseeable future.
