### ISSUE TITLE
Suppress cookie sliding

### ISSUE THREAD

**Issue by brockallen** [dotnet/aspnetcore#32269]
It would be nice to have an event to suppress cookie sliding. I know there's already an event for the ValidatePrincipal, but I'm also looking for one where the normal sliding logic executes (and that runs regardless if there's an OnValidatePrincipal).

**Comment by blowdart** [comment]
What's the thinking behind this? When would you want to suppress it?

**Comment by brockallen** [comment]
For example, you have JS that wants to ping the server at a well known endpoint to see if the cookie is still alive and/or has changed. On this endpoint we'd not want the cookie to slide.

**Comment by Tratcher** [comment]
So in the event you'd get the Endpoint from the HttpContext and use information from that to decide if the refresh logic should be skipped? Or are you planning to match the path?

**Comment by brockallen** [comment]
I don't know what an endpoint is (so don't don't suggest something like metadata on endpoint) :P

But imagine in the event you'd look at the path, yes. But who knows, perhaps the criteria is different (e.g. a query param).

**Comment by brockallen** [comment]
Also, having this as one event might be nice. Now there are two places this can slide. Once in OnValidatePrincipal. This is what I have to do now for the OnValidatePrincipal:

https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/SessionManagement/PostConfigureApplicationValidatePrincipal.cs

But the other is just the normal ReadTicket workflow, I can sort of work around it if there is a ITicketStore registered, but that might always be the case:

https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/SessionManagement/PostConfigureApplicationCookieTicketStore.cs

and

https://github.com/DuendeSoftware/BFF/blob/596e9f0d22e7beffd0440f3bd9c88afa552ef565/src/Duende.Bff/SessionManagement/TicketStoreShim.cs

**Comment by Tratcher** [comment]
We should check the opposite scenario while we're at it as the mechanism may overlap. People have complained that the current sliding refresh behavior doesn't refresh often enough. It will only refresh if the window is more than 50% elapsed. 
https://github.com/dotnet/aspnetcore/issues/21949

Should we support people opting into refreshes early as well?

**Comment by brockallen** [comment]
> Should we support people opting into refreshes early as well?

Sure. Tho, I doubt you were asking me :)

**Comment by Rinsen** [comment]
Sleeping tabs is making this a requirement for us also. 

If a tab is sleeping any timer that will warn a user for session expiration will be paused and when the user reactivate the tab again the browser will notify the user with the wrong session timeout time. 

We would like to solve this with a backend call to check the expiration of the HttpOnly cookie but this call must not refresh the lifetime of the cookie because users must be logged out when they are inactive. If not this background feature could keep sessions alive for ever.

**Comment by Tratcher** [comment]
Design notes:
OnValidatePrincipal's CookieValidatePrincipalContext.ShouldRenew handles the opposite case. It's false by default and can be set to true to force a refresh. We could recomend this to people that don't like the default 50% refresh interval.

ShouldRenew does not indicate if an automatic refresh is scheduled. Could it? Even if we could, current implementations of OnValidatePrincipal would likely be setting the value to false most of the time and would break sliding refresh. Looks like we do need a separate event. The new event wouldn't change anything about OnValidatePrincipal since that's a manual renewal request.
