### ISSUE TITLE
Blazor Server Multiple _Host.cshtml Not Working

### ISSUE THREAD

**Issue by sudip7139** [dotnet/aspnetcore#32333]
Here I have blazor server app, in app I have two _Host.cshtml, one for website which is default _Host.cshtml and another for admin panel that is _HostAdmin.cshtml. Both of them have separate css and js file. I too have separate layout, for website I have Mainlayout.razor which should use _Host.cshtml and for admin panel I have AdminLayout.razor which should use _HostAdmin.cshtml .
Now, the problem is that when I add new razor component and use AdminLayout.razor layout the view doesnot use css and js of _HostAdmin.cshtml.

In my _HostAdmin.cshtml

1. Create a separate razor page and set the route to "/Admin"
2. Set the base tag href to "~/Admin/"

In my Startup.cs  I have

app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
                endpoints.MapFallbackToPage("~/Admin/{*clientroutes:nonfile}", "/_HostAdmin");
            });

![Img1](https://user-images.githubusercontent.com/21105059/116812483-ac46b780-ab6e-11eb-8cc4-a3420246304f.png)

**Comment by javiercn** [comment]
@sudip7139 thanks for contacting us.

You have two conflicting routes there in your mapfallback, since the `endpoints.MapFallbackToPage("/_Host");` is essentially `"{*path:nonfile}"` and will map routes hadnled by `/Admin/{*clientroutes:nonfile}`.

To disambiguate you need to explicitly set the order for the Admin route to be lower so that it takes precedence. The way to do it is:
```csharp
    endpoints.MapFallbackToPage("~/Admin/{*clientroutes:nonfile}", "/_HostAdmin")
        .Add(b => ((RouteEndpointBuilder)b).Order = int.MaxValue - 1);
```
