### ISSUE TITLE
Dictionary query parameter behaves differently when it's used or not

### ISSUE THREAD

**Issue by Rudde** [dotnet/aspnetcore#32489]
Given the following API
```
        [HttpGet]
        public object Get(
            [FromQuery] string search,
            [FromQuery] Dictionary<string, string> keyVal)
        {
            var ct = HttpContext.Request;
            return new {};
        }
```
Using the given API with only search `/api?search=exampleSearchText` will populate both the variable search with `exampleSearchText` and keyVal with an element where the Key is `search` and value `exampleSearchText`, however if I use the api as follows `/api?search=exampleSearchText&keyVal[exKey]=exvalue`. `keyVal` will now be populated with only one element where key is `exKey` and `exvalue` is value. the including of search which makes no sense in the first place is just omitted now, and it work as I would expect it to.

```
C:\Users\Rudde> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14
```

I am using visual studio community 2019 version 16.9.4, the problem is the same regardless if I host it directly or via IIS Express.

**Comment by pranavkm** [comment]
Thanks for the issue report. This is by design and documented here - https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#prefix--parameter-name. Model binding will look for values that  start with `keyVal` and when it does not find any, it'll fall back to an empty prefix. 

You can configure an explicit prefix to require `keyVal` must be specified: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#custom-prefix
