### ISSUE TITLE
[Blazor] OnParametersSetAsync being invoked multiple times (3) when parameter is a ref type

### ISSUE THREAD

**Issue by ghostinside** [dotnet/aspnetcore#32531]
WASM i dont know why this issue was closed [https://github.com/dotnet/aspnetcore/issues/21348](https://github.com/dotnet/aspnetcore/issues/21348)

but i ran into the same issue: 

`[Parameter]
 public int ProductId { get; set; }
 [Parameter]
 public string SubmissionsToCopy { get; set; }`

if SubmissionsToCopy  is List<int> or int[] or boxed into object Oblect{int[] SubmissionsToCopy  get;set;}
method protected override async Task OnParametersSetAsync() will be executed 3 times, just passing the list as string helps

**Comment by ghostinside** [comment]
@javiercn  did I get you right that the suggestion is to use some local variable to detect whether it is the first set to parameters or not? 
& if the problem is in the ref types being passed as a parameter, why don't you create a wrapper structure for them to get what you are missing to handle it properly?

**Comment by javiercn** [comment]
@ghostinside You are talking about reference types, like `public class Something`.

Blazor has a conservative change detection algorithm and will consider reference types to have changed even when they point to the same instance, with the exception of strings.

The default logic for OnParametersSetAsync is to call `StateHasChanged` which triggers a render. Instead of that, you can override `SetParametersAsync` and perform the comparison between the current parameters in your component and the incoming parameters and make the decission yourself.

```csharp
public override Task SetParametersAsync(ParameterView newParameters)
{
  if(AreSame(newParameters))
  {
      return Task.CompletedTask;
  }
  
  return base.SetParametersAsync(newParameters);
}
```
