### ISSUE TITLE
Blazor Camera Image Upload

### ISSUE THREAD

**Issue by JohnFasc** [dotnet/aspnetcore#32543]
I have the problem, that our customer want's to capture an image and store it in our blazor application. We would upload the image directly to our blob storage, we already take this approach with our default file upload.  

The best and clean solution in my opinion would be, to extend the "InputFile", to open the camera from there. To use less javascript we want to prevent the Interop services for a clean code.

**Comment by javiercn** [comment]
@JohnFasc thanks for contacting us.

We don't plan to provide specific DOM APIs within the framework itself and we expect people that want to leverage the browser capabilities to either use a third-party library from the ecosystem or to write JS interop code for it.

That said, we are working on making JS interop better around these types of scenarios so that you don't have to implement your own "InputFile" and can leverage something we provide for the interop.
