### ISSUE TITLE
[Mvc] CSS isolation fails with some HTML constructs

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#32542]
For the provided markup:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tmp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="tmp.styles.css" />
</head>
```

We produce:

```html
<!DOCTYPE html>
 b-0pr8yvohll<html b-0pr8yvohll lang="en">
<head>
    <meta b-0pr8yvohll charset="utf-8" />
    <meta b-0pr8yvohll name="viewport" content="width=device-width, initial-scale=1.0" />
    <title b-0pr8yvohll>Home Page - tmp</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />

    <link b-0pr8yvohll rel="stylesheet" href="tmp.styles.css" />
</head>
```

* We should fix adding the scope after the doctype declaration
* We should stay away from applying the scope to meta, title, and other tags that appear only within the HEAD

**Comment by javiercn** [comment]
Motivating issue [here](https://github.com/dotnet/aspnetcore/issues/32491)

**Comment by mkArtakMSFT** [comment]
@captainsafia do you think this is something you've already addressed?

**Comment by captainsafia** [comment]
> We should fix adding the scope after the doctype declaration

This part was fixed in https://github.com/dotnet/aspnetcore/pull/31257. I haven't been able to repro the original issue on preview5 ([ref](https://github.com/captainsafia/MvcCSSTest/blob/main/obj/Debug/net6.0/generated/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/_Views_Home_Index_cshtml.cs#L80))

> We should stay away from applying the scope to meta, title, and other tags that appear only within the HEAD

Yep, this makes sense. I believe this happens at a different pass in the compiler so we'll have to track that down and adjust it.

@mkArtakMSFT It should be doable for preview5.

**Comment by captainsafia** [comment]
> Yep, this makes sense. I believe this happens at a different pass in the compiler so we'll have to track that down and adjust it.

Moving this to preview5 milestone since I put out a PR with a fix.
