### ISSUE TITLE
Razor Development: AutoComplete Tag Takes Seconds to Complete

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32558]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-Development:-AutoComplete-Tag-Take/1416599)._

---
[severity:It's more difficult to complete my work]
This may be related to [this issue here,](https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587) but wanted to make sure it is captured in case it is indeed another issue, as there were several similar issues reported in that thread.

Whereas the main thread mentioned above reports an issue whereby a simple press of a key will throttle for many seconds at a time, in this case there is simply excessive churn when attempting to complete the simplest task.

As an example, please see the attached.  The IDE gets in such a funk that it takes up to 5 seconds for a razor tag to auto-complete/close.

In the recording, I type several times:
`<Evaluate>`

And await for it to auto-complete to:
`<Evaluate></Evaluate>`

Each time, it takes several seconds to complete, taking up to 5 seconds in some cases.

---
#### Feedback Bot on 5/9/2021, 07:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Mike-E-angelo** [comment]
Hey all... good news here.  Looks like this was addressed somewhere with `16.11-preview1`:

![](https://i.imgur.com/gyeSliU.gif)

I will need to do some actual development to verify for sure, but preliminary testing looks promising. 👍

**Comment by NTaylorMullen** [comment]
We have code in the works to further improve speeds by over 3x as well 😄

**Comment by Mike-E-angelo** [comment]
Unfortunately @NTaylorMullen this has returned to my IDE, which is incredibly perplexing to me:

![https://i.imgur.com/5M1Q0kc.gif](https://i.imgur.com/5M1Q0kc.gif)

I tried deleting the  `.vs` folder of the SLN (which I haven't opened since the last animated capture I submitted above on May 25th), but alas that did not do anything and the delay persists.

So on May 25th when `16.11-preview1` was released, my autocomplete was wicked fast as denoted by my previous comment.  But now as I try it today, it is no longer wicked fast as denoted by the GIF above.  So confused. 😅😭

I even went through and disabled all my extensions and the problem still persists (R# is of course disabled in both cases).  Perhaps this is a settings issue?  I am open to any further suggestions on how this could have been "fixed" but has recurred after some time.

**Comment by Mike-E-angelo** [comment]
OK after some exploration, I see there's an `Enable experimental Razor editor (requires restart)` setting under `Preview Features`:

![](https://i.imgur.com/FRTAcRR.png)

When it is _unchecked_ autocomplete is May 25th fast.  When I check it and restart, it is June 11th slow.  The interesting thing is that I have never modified this setting, so I am thinking something weird happened with loading my settings on May 25th where the new/experimental editor was not loaded properly (even though it was enabled), leading to an inaccurate reporting of having been addressed/fixed.

So it would seem that this issue is still present when the Experimental Razor editor is enabled in 16.11.  However, if you feel you have addressed it for `17.0-preview2` @NTaylorMullen, then we can keep this issue closed.  I can keep the experimental editor off until I can try `17.0-preview2`+.

Glad we got that figured out. :P

**Comment by Mike-E-angelo** [comment]
Literally me in my IDE for the past 6 months or so. :p

![](https://i.makeagif.com/media/8-27-2015/lyJwvj.gif)

**Comment by NTaylorMullen** [comment]
We're definitely doing our best to resolve this and we think we have a pretty good idea on what's going (and since fixed in 17.0-P2). But just to be absolutely certain would you mind doing the "Report a Problem" in VS and using the VS' "record and capture" tools to ensure we can get an ETL trace to validate what's going on?

**Comment by Mike-E-angelo** [comment]
Ah thank you @NTaylorMullen you read my mind. 😁  I was actually going to suggest creating another issue but was not sure if that was going to be necessary or not.  I very much appreciate you being thorough and making sure the issue is addressed here.  

I have created your requested recording and it can be found here:
https://developercommunity.visualstudio.com/t/delay-in-tag-completion-when-enable-experimental-r/1448703

**Comment by NTaylorMullen** [comment]
Thank you @Mike-E-angelo! Exactly what we thought it was 😉, really appreciate the time and effort!
