### ISSUE TITLE
Component tag helper render-mode attribute value doesn't get committed from intellisense in Razor editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32557]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Component-tag-helper-render-mode-attribu/1416363)._

---
In my Blazor WebAssembly app, if I update the render-mode attribute on my component tag helper from WebAssembly to WebAssemblyPrerendered using the completion list, the selected value doesn't get committed to the editor when I hit enter or click on the completion list item.

Clicking the completion list multiple times sometimes resolves the issue.

---
#### Feedback Bot on 5/9/2021, 08:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
