### ISSUE TITLE
JsonPatch without Newtonsoft

### ISSUE THREAD

**Issue by grosch** [dotnet/aspnetcore#32628]
So people have been asking for years now to allow JsonPatch without requiring Newtonsoft. I've completely moved away from Newtonsoft (as Microsoft has for pretty much everything else) and don't want yet another dependency in my project, so now I'm faced with the decision of including Newtonsoft and potentially having other developers accidentally use that library vs. having to implement my own version of JsonPatch.

There are so many requests for this, is there any chance of it finally happening in .NET 6?

**Comment by javiercn** [comment]
@grosch thanks for contacting us.

Unfortunately that's not something we have planned for .NET 6.0 and its not a small work item for us to tackle. Something like that has a lots of potential to break existing JSON patch customers (in fact, just changing the library will break their deps and libraries) and we want to make sure those customers don't get disrupted by switching libraries.

If you are concerned about the usage of JSON.NET types in other projects/assemblies, it should be doable to write an analyzer to prevent such usage in other areas/parts of your product and include it by default in a `Directory.Build.Props` so that it gets automatically applied to new projects. That would effectively make it impossible to reference a type in Newtonsoft.Json by accident.
