### ISSUE TITLE
Re-enable Win7 tests once dotnet restore hangs are resolved

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#32683]
Win7 builds on helix are currently failing internally due to an issue with dotnet restore hanging.

https://dev.azure.com/dnceng/public/_build/results?buildId=1136832&view=ms.vss-test-web.build-test-results-tab

We should re-enable these once we figure out why .NET restore is hanging on Win7.

**Comment by sebastienros** [comment]
@HaoK You made a change (https://github.com/dotnet/aspnetcore/pull/32774/files) and created `runtests.cmd`, which seems to be related to the failure, since the log displays `neq was unexpected at this time` which is an error while interpreting the batch file. From a quick google search it looks like there could be a syntax error here. Can you double check this syntax is fine on Win7?

**Comment by HaoK** [comment]
Oops yeah my bad, I usually try the full matrix but I forgot to on this change, I'll look into it

**Comment by sebastienros** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/32965

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/blob/a3da3e1da05117ea0d2ae3d0b8477851727b1451/eng/targets/Helix.Common.props#L31

??

**Comment by sebastienros** [comment]
:/

**Comment by sebastienros** [comment]
@HaoK you agree we can re-enable this step now?

**Comment by HaoK** [comment]
Gonna defer to @dougbu who is keeping the restore issue separate from the runtests fix which I merged: https://github.com/dotnet/aspnetcore/pull/32965#issuecomment-847537536

**Comment by adityamandaleeka** [comment]
Triage: we don't run this queue anymore. Closing issue.
