### ISSUE TITLE
Missing partial modifier on declaration of type 'Counter'; another partial declaration of this type exists

### ISSUE THREAD

**Issue by khanakia** [dotnet/aspnetcore#32749]
I am using basic blazor tutorial https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#partial-class-support and trying to split the Razor component with C# Classes but Visual Studio auto generating some class file for the razor file which is conflicting with partial class check the screenshot

![Screenshot 2021-05-16 172013](https://user-images.githubusercontent.com/2174170/118395998-082f3700-b66b-11eb-894e-507f0c0d8be4.png)

![Screenshot 2021-05-16 172203](https://user-images.githubusercontent.com/2174170/118396056-46c4f180-b66b-11eb-84ef-00c58a3a7067.png)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
