### ISSUE TITLE
Does Blazor attribute splatting supports EventCallback parameters?

### ISSUE THREAD

**Issue by danleydmello** [dotnet/aspnetcore#32786]
When i try I get InvalidCast exception

**Comment by javiercn** [comment]
@danleydmello thanks for contacting us.

Can you provide a concrete example (as a public GH repo or similar) that illustrates what you mean?

If you are passing a lambda as a component attribute and there's no explicit event associated with it. It likely means the compiler  doesn't have the necessary information to generate an EventCallback and will likely generate an `Action` or similar. 

If you then try to cast that parameter to an EventCallback its going to fail since the compiler won't have created it and you'll be dealing with an Action.
