### ISSUE TITLE
Blazor virtualize component causes scoped services to never be disposed

### ISSUE THREAD

**Issue by cristian-recoseanu** [dotnet/aspnetcore#32808]
### Describe the bug
Virtualize component prevents scoped injected services from being disposed.

### To Reproduce
Here is a sample repo:
[BlazorVirtualizeServiceDisposeTest](https://github.com/cristian-recoseanu/BlazorVirtualizeServiceDisposeTest)

The `VirtualizePage` renders multiple `TestComponent` components which depend on the scoped service `ScopedServiceTest`.

Using the `Virtualize` component to render them causes the scoped service to never be disposed when refreshing/closing the page.

![image](https://user-images.githubusercontent.com/15727528/118624450-155e3a00-b7c1-11eb-99cb-aeb261b2fced.png)

Uncommenting the section using the `Virtualize` component and using a foreach works as indented. The scoped service is created and always disposed correctly.

![image](https://user-images.githubusercontent.com/15727528/118624704-48a0c900-b7c1-11eb-999d-b89e6b63f8ee.png)

### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21180.15
 Commit:    19ce2535ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 16.9.5

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please look into this? If turns out to be true, we can bring this in for preview5 potentially.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this, @cristian-recoseanu! From investigations, it looks to me like those scoped services *will* eventually be disposed, but a problematic aspect of the implementation means it will take 1 minute before that happens.

### Investigation

Looks like a real issue, which comes down to two things:

1. The `IAsyncDisposable` implementation inside `Renderer` relies on the wholesome idea that all components will complete their disposal quickly: https://github.com/dotnet/aspnetcore/blob/659e492495884d37cde5a567f3c73b0550c561e5/src/Components/Components/src/RenderTree/Renderer.cs#L913-L914
    While it might be OK to let components take a long time to dispose while the circuit remains active, as soon as the circuit is being shut down, we shouldn't let them take as long as they want and pin resources in memory until they eventually finish (or maybe never eventually finish).
2. The behavior of `RemoteJSRuntime` when a circuit is disconnected isn't great. Any subsequent async JS interop calls will be issued as if the circuit was still there, but of course there will never be a reply, so they just hang until they finally time out (default: 1 minute).
 
Since `<Virtualize>` tries to clean things up on the JS side when being disposed, those two things above combine to make it take 1 minute to complete its `IAsyncDisposable` task, and the DI container remains undisposed until then.

I don't think this is a defect in `<Virtualize>`. In general we should expect components to try doing JS interop calls as part of async disposal. Instead, I think we need to make sure that either (1) JS interop calls fails immediately if/when the circuit is disconnected, or (2) that the `Renderer's` async disposal path doesn't actually wait for components' async disposal paths. Maybe we should even do both of these, since each of them alone still seems to leave open edge cases where things would be left hanging longer than you want.

@dotnet/aspnet-blazor-eng - opinions on whether it's either, both, or something else?

**Comment by SteveSandersonMS** [comment]
I'm don't think `AsyncServiceScope` will change this. The renderer disposal process hangs *before* we ask the DI scope to be disposed, because the component hierarchy disposal runs first and doesn't complete.

The question we need to answer first is whether there should be an exception if you try to do JS interop calls during `IAsyncDispose` after the circuit is gone. On one hand it should be an exception because the call couldn't complete, and you told us to await it. On the other hand, this will *always* happen whenever the user closes a tab, so this is very noisy in server logs. 

But even then we still have a problem either way. Given that you have code like `await JS.InvokeAsync("someCleanupLogic")`, we can't continue with the rest of your disposal logic after this, whether or not it throws. So JS interop during async disposal might leave other things undisposed. We would have to recommend that all use of JS interop during disposal be fire-and-forget (e.g., `_ = JS.InvokeVoidAsync("someCleanupLogic")` - this will still log an exception but won't prevent other disposal logic from running.

**Comment by SteveSandersonMS** [comment]
I suppose the right answer is that `JS.InvokeAsync` should throw as noisily as possible if the browser already disconnected. Yes, that will be noisy in logs, which is precisely what might help developers discover they need to do something about it (e.g., try/catch for the specific JS exception that occurs).

**Comment by cristian-recoseanu** [comment]
Thanks for looking at this @SteveSandersonMS! It hadn't crossed my mind to wait for a timeout. Empirical evidence pointed at the Virtualize component being the culprit but as your investigation points out this is a much more deeper issue in the framework.

> 
> 
> I suppose the right answer is that `JS.InvokeAsync` should throw as noisily as possible if the browser already disconnected. Yes, that will be noisy in logs, which is precisely what might help developers discover they need to do something about it (e.g., try/catch for the specific JS exception that occurs).

I think this is a good approach which increases visibility of the problems so developers can cater for them in their implementations.
