### ISSUE TITLE
Error 404 with default-value template after dot

### ISSUE THREAD

**Issue by bernd5** [dotnet/aspnetcore#32815]
### Describe the bug
I replaced the working template pattern:
`"{file}.{extension?}/{xyz}"`

with 

`"{file}.{extension=something}/{xyz}"`

and got Error 404.

It even does not work with a simpler template like: `{something}.{extension=foo}`.
But without the default value it works: `{something}.{extension?}`

### To Reproduce
[Link to controller](https://github.com/bernd5/aspnet_default_value_sample/blob/master/SampleWebApp/Controllers/WeatherForecastController.cs)

### Exceptions (if any)
return code: 404

### Further technical details
- ASP.NET Core version: 5.0.5

**Comment by webczat** [comment]
Hello,
I have actually investigated it and it seems to me that the cause is complex segment handling. I mean there is some special case for the last part being optional, and it seems it was specifically done to support this use case, except no support for extension being defaulted.
That invoked a question, why it's required complex segments are parsed like that, right to left, instead of left to right? It would make it possible to support optional/default parts in a more general purpose way maybe... although the problem may be more complex than how I view it.
Of course just adding a default support to the last part matching could be considered, I think.
What would you say?

**Comment by webczat** [comment]
Relevant code seems to reside in https://github.com/dotnet/aspnetcore/blob/v5.0.5/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs (the `MatchRouteSegment` method).

**Comment by javiercn** [comment]
Default values are not supported for individual parameters in complex segments, only the last parameter after the separator (currently the only one is `.`) can be optional

**Comment by javiercn** [comment]
We don't plan to add more behavior to complex segments

**Comment by webczat** [comment]
Does that mean it would be actively rejected or just that there is no plan to give this any priority? I remember that when this was reported I was thinking about contributing the change, the only problem was to figure out what the acceptable change in this case would be.
