### ISSUE TITLE
TagHelper's bang-escape operator is not colored correctly

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#32821]
**Actual:**
![image](https://user-images.githubusercontent.com/2008729/118705436-14cba080-b7cd-11eb-8175-043ac88cdfda.png)

**Expected:**
![image](https://user-images.githubusercontent.com/2008729/118705459-1bf2ae80-b7cd-11eb-8ef7-d418064bbaba.png)

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen that's because we're explicitly calling it a [MarkupElement](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs#L81). Seems like you're saying it ought to be classified as a `RazorTransition` (same as `@`)?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen that's because we're explicitly calling it a [MarkupElement](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs#L81). Seems like you're saying it ought to be classified as a `RazorTransition` (same as `@`)?

Yes
