### ISSUE TITLE
Js interlope for blazor through javascript definition supported by c# syntax

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#32943]
Much like emscripten's EM_JS, if we can write javascript functions in the same place where we call it, maybe inline maybe a seperate function in the same file, it would looks like calling just another c# function except the stuff is javascript, I am not even asking for intellisense but can I please get the support for writing javascript inside .cs/.razor files.

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is not something we plan to do. The component model Blazor uses doesn't lend itself well to writing JS code inline since removing a script tag from the page has no effect once it has been added. We recommend keeping your JS separate and use `import` statements to load JS and leverage functionality.
