### ISSUE TITLE
CLI: dotnet user-secrets should support a 'get storage location' command

### ISSUE THREAD

**Issue by Plasma** [dotnet/aspnetcore#33099]
### Is your feature request related to a problem? Please describe.
I am trying to find the stored secrets file on my computer (to move between computers) for a project.

I figured out its location, but because it can be different between projects, it would have been helpful to have a command tell me where it was.

### Describe the solution you'd like
I'd like to type `dotnet user-secrets get-storage-location` (or something) to print the on-disk path to the file or pipe its output to open in an editor like `vscode`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by sebastienros** [comment]
~~Using DevKit, there is no easy way to manage secrets (opening the secrets file in vscode)~~ so I was looking for way to open it from command line instead of adding secrets one by one. Would be nice IMO. Or at least a command to get the id of the current project so we can build the file path from it. We could extract it from the csproj but it's harder to do that using a custom command.

Update: I was clicking in the standard explorer, it's actually integrated in DevKit
