### ISSUE TITLE
Razor @foreach should be null-tolerant

### ISSUE THREAD

**Issue by glatzert** [dotnet/aspnetcore#33110]
Since Blazor is a (really nice) thing now, frontends will be written in razor.
Comming from JS Frontends (Angular et al.) Razor sometimes seems "verbose" and I there's one thing where it could be improved easily:

Consider making `@foreach` null-aware.

If there are nullable enumerables, we currently end up writing
```
@if(myNullable != null) {
    @foreach(var myvar in myNullable) { 
        <razorcode>
    }
}
```

Which could automatically be handled in a manner this would suffice:
```
@foreach(var myVar in myNullable) { ... }
```

This probably could be a compiler-opt-in / opt-out?

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion, but `foreach` is a C# language feature, not a Razor feature. To make it reasonable for people to understand what Razor does, we don't interfere with the behavior of C# language features. It would be extremely strange if some language constructs had different edge-case behaviors in `.razor` files versus `.cs` files.

Technically speaking we couldn't even if we wanted to, at least not without completely rewriting the Razor compiler, since the Razor compiler doesn't see the inside of C# expressions and is only aware of them as opaque blocks of source code text.

**Comment by mrpmorris** [comment]
Write an extension method on `IEnumerable<T>` that returns `Array.Empty<T>` when the value is null

**Comment by glatzert** [comment]
> Thanks for the suggestion, but `foreach` is a C# language feature, not a Razor feature. To make it reasonable for people to understand what Razor does, we don't interfere with the behavior of C# language features. It would be extremely strange if some language constructs had different edge-case behaviors in `.razor` files versus `.cs` files.
> 
> Technically speaking we couldn't even if we wanted to, at least not without completely rewriting the Razor compiler, since the Razor compiler doesn't see the inside of C# expressions and is only aware of them as opaque blocks of source code text.

Thanks for explaining - I had the assumption Razor was something like a DSL and could be adjusted in behaviour of the code blocks.
