### ISSUE TITLE
Change internal ICascadingValueComponent interface to public or add possibility to get ParentComponent from RenderHandle

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#33244]
Now, to provide cascading value to child components we should wrap render fragments into CascadingValue<T> component.
In many cases it's very expensive. 
For example building large lists or tables, we add some RowComponent for each row and wrap it with CascadingValue (if using context is not enough).
If ICascadingValue will public interface, we could implement this interface to our  RowComponent, sow this RowComponent will provide cascading value by itself and we reduce one component for each row.

**Comment by javiercn** [comment]
@kefyru thanks for contacting us.

We are not planning on making `ICascadingValueComponent` public since it is tight tied with the rendering implementation details of the framework and doing so will greatly limit us in the future to further optimize the rendering process.

If you can give a more concrete example of what you are trying to achieve and what the problems you are running into are, we might be able to suggest alternative implementations.
