### ISSUE TITLE
Blazor: Add support html dom api like Element.setAttribute()

### ISSUE THREAD

**Issue by alijam93** [dotnet/aspnetcore#33321]
### Is your feature request related to a problem? Please describe.
I'm trying to create dark mode switcher with c# in blazor ... I searched but couldn't find  any solution with pure c#  

### Describe the solution you'd like
With js we do this:

1. Add this in .css
```css
[data-theme="dark"] {
  --background-color: #3F3F3F;
  --text-color: #fff;
}
```
2. In js side use: 
``` js
// Wait for document to load
  document.addEventListener("DOMContentLoaded", function(event) {
    document.documentElement.setAttribute("data-theme", "dark");
  // The rest of the code
  });
```

After refresh in index.html the dark mode will be applied:
``` html
<!DOCTYPE html>
<html data-theme="dark">
<!-- The rest of the code -->
```

In RenderTreeBuilder  we only have `AddAttribute` method not `GetAttribute` like **document.documentElement.setAttribute("data-theme", "dark")** in js.

My suggestion is support build-in  dom api within Blazor.

### Additional context
https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us, @alijam93.

We're not planning to add a complete clone of the DOM APIs in .NET code, at least not baked into Blazor itself, for a couple of reasons:

 1. It would be a moving target - there would always be parts of the DOM API surface recently added that wouldn't be in the shipping .NET libraries. We'd be constantly chasing.
 2. It would encourage people to use inefficient coding patterns. For example, instead of using Blazor's diff-based low-allocation rendering system, people would start mutating the DOM directly. Worse still, this would lead to undefined behavior since the diffing system would no longer match up with what's in the DOM.

It's totally fine if somebody in the community wants to create a NuGet package that uses JS interop to wrap all the DOM APIs, but it's not on the Blazor team's backlog for these reasons.

However the good news is that you can already use JS interop to achieve what you want very easily. At the top of a `.razor` file, you can add `@inject IJSRuntime JS`, and then somewhere in your `@code` block:

```cs
await JS.InvokeVoidAsync("document.documentElement.setAttribute", "dark-theme", "dark");
```

That's all there is to it - no need to add any `.js` file, and you can trigger this at any point in the .NET application code.
