### ISSUE TITLE
Add a test to validate native dependency usage in Blazor WebAssembly

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#33367]
To make sure that this scenario works, we need to add a new sample app to the repo, which has a native dependency and have some tests utilizing that sample.

**Comment by SteveSandersonMS** [comment]
I'm not convinced we actually do want to do this in our repo here. Doing so implies that we need the `wasm-tools` workload installed in order to build and test, *and* means we have to go through the `dotnet.wasm` relinking step which currently means publishing, and that's > 10 mins likely.

Since this is a runtime feature, I'd expect it to be tested in the runtime codebase. There isn't anything Blazor-specific about this feature. We *would* add an E2E test for it here for clarity and completeness if it wasn't for the drawbacks on build/test time, but those drawbacks are nontrivial.

@lewing @radical Are you happy that the native dependency feature, and its interactions with build/publish, are adequately tested in the runtime repo anyway?

**Comment by SteveSandersonMS** [comment]
We've decided that the existing CTI coverage is satisfactory as far as Blazor scenarios. It's up to @lewing etc whether the runtime test coverage is already good.

**Comment by lewing** [comment]
Other points aside, relinking shouldn't nearly that much time right now.
