### ISSUE TITLE
Unable to find a solution to implement Blazor virtualize for scrolling bottom up.

### ISSUE THREAD

**Issue by ut786** [dotnet/aspnetcore#33426]
I have been working on a project on Blazor Server. I have got struck on a chat-box feature in my application which I need to be implement with Lazy-Loading by using the virtualize component.
I have used virtualize for my tables using ItemsProvider action but not finding an accurate way to do so for a chat-box, which need to be scrolled from bottom to upwards, as it is a standard for a chat-box functionality.

Can I get some help on my problem?

**Comment by SteveSandersonMS** [comment]
If sounds like what you'd want is:

 1. To add new chat messages dynamically as they arrive (which you can already do by updating the underlying data source and calling the "data has changed" method on `Virtualize`)
 2. To auto-scroll to the end each time.

Item 2 can't be done purely from .NET code until we implement https://github.com/dotnet/aspnetcore/issues/26943. However you can technically do it via JS interop, since you can set the `scrollTop` property of the corresponding DOM element.
