### ISSUE TITLE
Change ReactDevelopmentServer to be generic 

### ISSUE THREAD

**Issue by keithn** [dotnet/aspnetcore#33466]
The code in :-
https://github.com/dotnet/aspnetcore/tree/main/src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer

is nearly generic for running any console based web thing.    Other than the unnecessary text that refers to "react", the main thing that is a blocker is that it can't be configured to detect when the console has started the server and ties it to one specific environment,  which is in ReactDevelopmentServerMiddleware.cs   

```await scriptRunner.StdOut.WaitForMatch(                        new Regex("Starting the development server", RegexOptions.None, RegexMatchTimeout));```

That needs something that can be injectable.  I have seen some people make their system artificially emit this string just so they can use this middleware, but I think it would be better if you just made this generic since it is 95% there already.

In my case I want to run Vite with Vue, but Vite can also run React, and this would block that as well

I suggest simply changing this to 

DevelopmentServerMiddleWare

Remove all the textual references to react / npm / yarn  etc   and then have a "React" set of preconfigured settings that you can then pass to to this middleware, and that way others will be free to create their own settings for other environment like  Vite with Vue or React or any other system,  but could equally be used with a rust server, go, or any other console based system.

**Comment by keithn** [comment]
huh, interesting ,that was how I was doing it, but not sure that is better, proxying to razor pages from the spa is now going to be more interesting.

**Comment by javiercn** [comment]
> huh, interesting ,that was how I was doing it, but not sure that is better, proxying to razor pages from the spa is now going to be more interesting.

We find that is better for several reasons:
1. It is inline with the SPA frameworks guidance in these cases.
2. It uses the same battle-tested proxy as all other backends. Our proxy though it does the job, has nuances that are specific to it and ends up getting in the way in some cases.
3. Its easier to find solutions/docs about how to solve specific development time problems since there's a wider community around it. If you have a problem you need to solve at development time, its likely the solution applies whether you use ASP.NET Core as the backend or any other framework.
4. At publish time, all the SPA output becomes content served from the wwwroot folder ("its just files on disk") within the backend project and the only thing at runtime you see is `MapFallbackToFile("index.html")` to deal with client routes.

In 6.0 we still launch the proxy automatically for you when you run `dotnet run`, but you can disable that and launch the proxy manually by navigating to the `ClientApp` folder and running `npm start`. Doing it manually might be more work, but I personally think its better for two reasons:
1. You can keep the proxy up and running and you only pay a slow start the first time.
2. You don't need to restart the server when you make changes to the client files, and if you restart the server you don't have to restart the proxy either.
