### ISSUE TITLE
Asp.net core routing, Add react spa & blazor server

### ISSUE THREAD

**Issue by fleischman718** [dotnet/aspnetcore#33461]
I'm trying to add blazor (Server side) to an existing project, that already serves a react spa app & web api.

My issue is that if i add `endpoints.MapFallbackToPage("/_Host"); `everything is being routed to blazor instead of react spa.

I would like to route a request to blazor if it starts with "/test/*", i tried changing the fallback rule to `endpoints.MapFallbackToPage("test/*", "/_Host");` but this has two issues:

1. The root ("/") still routes to blazor (which i don't understand why this matches the rule "tets/*" to begin with.)
2. This only routes /test to blazor but not sub-routes, example: test/test/123.

**Comment by javiercn** [comment]
@fleischman718 thanks for contacting us.

`endpoints.MapFallbackToPage("test/*", "/_Host");` should work.

> 1\. The root ("/") still routes to blazor (which i don't understand why this matches the rule "tets/*" to begin with.)`. 

This is because host has a page directive like `@page "/"` so it matches that in addition of anything under "test/*". If you have a prefix under which all your SPA routes will be served, then you can just use `@page "prefix/{*rest}"` to handle fallbacks.

> 2\. This only routes /test to blazor but not sub-routes, example: test/test/123.

The patter you have there is incorrect. It should be something like "test/{*slug}"

**Comment by fleischman718** [comment]
@javiercn Thank you so much for your help! 

it's working now as expected!
