### ISSUE TITLE
OpenApi generator fails with space in path

### ISSUE THREAD

**Issue by johan-v-r** [dotnet/aspnetcore#33463]
### Describe the bug

Building a project with a configured `<OpenApiReference>` task from a file path that contains a space fails.

Looks like the path in `openapi2csclient /input:` arg would require some quotes or something...?

### To Reproduce
```
mkdir "src with-space"
cd '.\src with-space\'
dotnet new classlib
dotnet openapi add url https://petstore.swagger.io/v2/swagger.json
dotnet build
```

Repro project: https://github.com/johan-v-r/OpenApi-Generator-Path-Repro

Same thing when configuring the OpenAPI Connected Service through VS.

### Exceptions (if any)

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\SourceCode\OpenApi-Generator-Path-Repro\src'.

### Further technical details
- ASP.NET Core version
  - .NET 5
- Include the output of `dotnet --info`
  - > Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\
Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
  - .NET CLI and VS 2019

**Comment by captainsafia** [comment]
This issue here is external to ASP.NET Core and will likely need to be fixed in the NSwag code generator Particularly, here:

https://github.com/RicoSuter/NSwag/blob/4f345e1adc9c49d8498d4018250760aa69dd8dd2/src/NSwag.Commands/Commands/OutputCommandBase.cs#L45-L54

The reason being is that this issue occurs when the `GenerateNSwagCSharp` task is executed via MSBuild. The task passes the `FullPath` of the `OpenApiReference` item which contains spaces and is unescaped in MSBuild. The filepath flows all the way to the file read logic above without being escaped.

**Comment by johan-v-r** [comment]
Thanks Safia - Actually looks like it's already solved in the latest version of [NSwag.ApiDescription.Client](https://www.nuget.org/packages/NSwag.ApiDescription.Client/)
