### ISSUE TITLE
Add source index build step

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#33534]
See https://github.com/dotnet/runtime/pull/46823 for more details.

cc @alexperovich 
cc @dougbu

**Comment by dougbu** [comment]
I thought source indexing was something covered automatically (along w/ SDL checks) in our release pipeline❔

Separately, I'm curious how source indexing relates to rich navigation. Please explain.

@jepetty set up rich navigation for us in https://github.com/dotnet/aspnetcore/blob/main/.azure/pipelines/richnav.yml but I can't find the actual pipeline (@jepetty❔).

/cc @dotnet/aspnet-build

**Comment by davidfowl** [comment]
This is for https://source.dot.net/ I think but I dunno how the 2 are related.

**Comment by dougbu** [comment]
Thanks @davidfowl for this and the mention in the internal conversation. Makes much more sense now❕ 

I added this to the dashboard we (the build v-team) use to track work. Seems pretty simple&hellip;

/fyi @Pilchie

**Comment by alexperovich** [comment]
To simplify this change, if the repo uses eng/common/templates/jobs/jobs.yml, you can just set the "enableSourceIndex" parameter there. If the code to be indexed gets built by default with eng/common/build.ps1, then you can stop there. Otherwise the sourceIndexBuildCommand value in the sourceIndexParams parameter will need to be set to the command that will produce a binlog containing builds of all the projects to be indexed.

**Comment by dougbu** [comment]
@alexperovich can we use `enableSourceIndex` at a lower level e.g. in a single job that already produces a source index❔

Separately (kinda) we build multiple times to handle native assets and avoid desktop `msbuild` otherwise. Our builds therefore produce a minimum of three binary logs where binlogs are enabled (and we don't enable them often -- too big). Does the source index need just the binary log for building our C# code❔ Is it possible to tell your stuff which binlog to use❔

**Comment by alexperovich** [comment]
it only needs to be in one job, and that job can only build C#, or whatever you need. The only requirement is that it produce a binlog in the normal place that contains all the csc commands for the code that should show up on source.dot.net

**Comment by alexperovich** [comment]
it will actually read all the binlogs, so if it produces multiple that is fine, but one is faster.

**Comment by KirillOsenkov** [comment]
How do we get this in? I'm getting complaints that these assemblies aren't on https://source.dot.net

**Comment by dougbu** [comment]
>  I'm getting complaints that these assemblies aren't on https://source.dot.net

We (a) missed the urgency in this issue -- everything was quiet since June and (b) only just learned the simple approach.

----

The next question is which Eng channels contain Arcade bit containing `enableSourceIndex`. The corresponding dotnet/aspnetcore branches are where we'd fix things in the next few days.

Separately, is this also an issue for dotnet/efcore code❔

**Comment by alexperovich** [comment]
Its just a part of the arcade sdk, the source index bits are delivered with the eng/common folder and the sdk.

**Comment by dougbu** [comment]
> Its just a part of the arcade sdk, the source index bits are delivered with the eng/common folder and the sdk.

@alexperovich I understand that part. What I'm not sure is whether, say, the '.NET 3 Eng' bits include the feature.

**Comment by alexperovich** [comment]
I doubt they do, I added the code to arcade/main, and there is only one source-index so it should be done on main. Release branches don't need anything.

**Comment by dougbu** [comment]
Turns out we **cannot** just use `enableSourceIndex` because we instead use the eng/common/templates/job/job.yml template and e.g. use the eng/common/templates/post-build/post-build.yml template directly in our main pipeline.

That said, the eng/common/templates/job/source-index-stage1.yml looks easy enough to use.

> It will actually read all the binlogs

 No, it doesn't. I'll need to change the `binlogPath` to pick up our .binlog because we only build the Release configuration and, where we create .binlog files, we usually name them something unique. Working&hellip;

**Comment by alexperovich** [comment]
O yes, thats right. The actual source-indexer exe will read all the binlogs when the repo is built as part of the index build. This method will only read the specified one.

**Comment by dougbu** [comment]
I have been running internal builds to validate my work. Not done yet but last run (https://dev.azure.com/dnceng/internal/_build/results?buildId=1386785&view=results) was successful; https://source.dot.net contains ASP.NET Core sources 🎉

**Comment by davidfowl** [comment]
It's missing some still. https://source.dot.net/#q=WebApplicationBuilder

**Comment by dougbu** [comment]
> It's missing some still. https://source.dot.net/#q=WebApplicationBuilder

I agree and suspect problems in the indexing infrastructure somewhere though not in my draft PR. See https://dev.azure.com/dnceng/internal/_build/results?buildId=1386785&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=89d21b4d-9e97-5d1e-92db-12e44f8ee3f8&l=3972:

``` text
Adding D:/a/_work/1/s/.source-index/stage1output\src\src\DefaultBuilder\src\WebApplication.cs as src/src/DefaultBuilder/src/WebApplication.cs
```

@alexperovich❔

**Comment by dougbu** [comment]
Oops, next line:

``` text
Adding D:/a/_work/1/s/.source-index/stage1output\src\src\DefaultBuilder\src\WebApplicationBuilder.cs as src/src/DefaultBuilder/src/WebApplicationBuilder.cs
```

**Comment by alexperovich** [comment]
I need to update the main source index build to use the output of this step. Is it running currently? I can update things now if the stuff has been uploaded to storage.

**Comment by alexperovich** [comment]
okay, I see the stuff in storage. Build running now.

**Comment by dougbu** [comment]
> Things are working now

Excellent @alexperovich. Just need to get #37028 working&hellip;

**Comment by davidfowl** [comment]
Clicking on the "open in GitHub link" doesn't work

**Comment by davidfowl** [comment]
It took me here https://github.com/dotnet/aspnetcore/tree/a579e0a3d717d1916c1b3ac43a20998dcdb465bc/src/DefaultBuilder/src/WebApplicationBuilder.cs

**Comment by dougbu** [comment]
> https://github.com/dotnet/aspnetcore/tree/a579e0a3d717d1916c1b3ac43a20998dcdb465bc/src/DefaultBuilder/src/WebApplicationBuilder.cs

I bet this happened because my commit was only in the internal AzDO repo. That is, links shouldn't be busted once an official build of 'main' happens after I get #37028 in. Agreed @alexperovich❔

**Comment by alexperovich** [comment]
Yup, it bakes in the commit hash of whatever was built, so if thats not on github it won't be a valid link.
