### ISSUE TITLE
ComplexObjectModelBinder sealed and setProperty internal

### ISSUE THREAD

**Issue by msmolka** [dotnet/aspnetcore#33545]
## Summary

I'm using in ASP .NET Core 3.1 custom ComplexTypeModelBinder which overrides default one. My implementation is used to automatically trim incoming string properly. 

## Motivation and goals

ComplexTypeModelBinder is now obsolete, and I cannot easily replace implementation of ComplexObjectModelBinder. Copy everything is pretty useless, because then handling bug and fixes and the class would be a nightmare.

**Comment by pranavkm** [comment]
@msmolka we had intentionally avoided making the new binder public since it makes it difficult for us to evolve the type. There's a couple of options you could consider:

a) Continue using the `ComplexTypeModelBinder`. The obsoletion is to indicate the type isn't used by the framework, but we're going to leave it as-is.
b) Copy the `ComplexObjectModelBinder`. We believe this is the best option if you do all of the features that the type supports but firewalls library / user code from changes to the type.
c) You could use the `ComplexObjectModelBinderFactory` to get an instance of the type and wrap it instead of deriving from it.

**Comment by msmolka** [comment]
Copying whole class is a bit pain, to handle changes/fixes that are not relevant for me.
Decorating ComplexObjectModelBinder would work for if SetProperty would be public instead of internal. If you don't like to make it overridable, at least do not use internal methods, so I then would be able to wrap and decorate it.

**Comment by msmolka** [comment]
@pranavkm 
I've tried to copy use option:

> b) Copy the ComplexObjectModelBinder. We believe this is the best option if you do all of the features that the type supports but firewalls library / user code from changes to the type.

Hover ComplexObjectModelBinder is using few internal things:
a) `PlaceholderBinder` - this is small class I can copy it over
b) logger extensions - can be copied - no problem
c) and big problem:
`modelMetadata.BoundProperties` which I cannot reuse
