### ISSUE TITLE
Question regarding Blazor & Threads

### ISSUE THREAD

**Issue by gingters** [dotnet/aspnetcore#33583]
This is sort of a follow-up to issue/question #19004

That question was whether to use `.ConfigureAwait(false)` in Blazor components, and @SteveSandersonMS answered no, because Blazor is a UI Framework and so the code needs to run on the synchronization context.

Now for me that rises more questions than what it answers:

1. Blazor WASM only has a single thread, and the JavaScript runtime also has a single thread (if it's not even the very same thread), and so in the JS part only a single thread is available to update the actual UI. So here it doesn't really matter, as anything is run on the same thread anyways.

2. Blazor Server runs on the server, and the representation of the UI is 'streamed' to the client. So there shouldn't be a difference in what thread calls a method on the SignalR hub to send the UI-update / diff down the connection to the browser - where the single JS thread will receive that message and update the UI.

3. The new SignalR is part of ASP.NET Core, and .NET Core / .NET 5 and ASP.NET Core doesn't even have a synchronization context to which a continuation could be pinned.

So the actual question is, why does Blazor introduce this requirement artificially by introducing a new synchronization context? Why is it needed in the first place? The UI updates are synchronized anyways in JS.

**Comment by SteveSandersonMS** [comment]
Blazor Server runs in a truly multithreaded environment. If we didn't impose any controls, you could write multithreaded .NET code that invokes a single renderer multiple times concurrently (e.g., `Thread.Start`, and then in each thread, do something that calls `StateHasChanged` on components), and then one of the following would have to be true:

 1. We'd have to block some of those threads, which is very bad for server performance
 2. Or, we'd have to make everything in the rendering pipeline thread-safe for concurrent execution, which would not really be practical because it would leak out into the public API. For example, in every component, developers would have to do locking or similar in every event handler that mutates any state. It would be extremely difficult to reason about things like "how many times does this render" because it could be rendering multiple times concurrently.

As for WebAssembly, although it's currently single-threaded, that's not going to be the case forever. We don't know how soon multithreading will be supported by browsers (it depends on when they fully re-enable `SharedArrayBuffer`) but we want people's apps to be ready to turn on multithreading without having to rewrite from scratch because they are based around assumptions of single-threadedness.
