### ISSUE TITLE
[Question]: CSRF prevention using EditForm in Blazor Server-Side

### ISSUE THREAD

**Issue by dmoncada** [dotnet/aspnetcore#33620]
[My apologies if the question is missing some detail, I'm still learning the in's & out's of CRSF attacks.]

**Context:**
I'm investigating how to add CSRF protection to a Blazor Server-Side project using ASP.NET's antiforgery features, I'm been familiarizing myself with these features and trying out the functionality, particularly what's shown in [this article][aspnet-antiforge] from the MS docs. The article mentions (as does [this other one][razor-antiforge]) that antiforgery tokens are injected into HTML `form` elements in Razor files via the `FormTagHelper`.

It is unclear to me, however, if tokens are also injected into Blazor components using either `form` elements or `EditForm` components. I wrote a very simple Server-Side PoC with a single controller decorated with `ValidateAntiForgeryToken`. While this protected the controller when I attempted a simulated CSRF attack, I was unfortunately not able to hit the controller by submitting an `EditForm` from within the app.

I should also mention that, I read [a comment from a couple years back][no-csrf] that says Blazor Server apps are not vulnerable to CSRF attacks. However, when I removed the `ValidateToken` attribute from the controller I was able to trigger a simulated CSRF attack, by triggering the controller externally using a regular `form` in an HTML, so not sure if I'm misinterpreting the comment?

In the end I was able to protect the controller by adding back token validation -and- hit it from within the app by injecting the antiforgery token into the Blazor component with the `EditForm` using DI (by following the method described in [this article][pass-token], also from the docs.) The method is a bit convoluted in that you need to touch a few files, which is what leads me to ask...

**Question:**
Is there an out-of-the-box way to inject antiforgery tokens into `EditForm` (or `form`) components, inside Blazor components? Or, is there a way to make the [Form Tag Helper][tag-helper] modify `EditForm`s inside Blazor components?

[aspnet-antiforge]: https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-5.0#aspnet-core-antiforgery-configuration
[razor-antiforge]: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio#xsrfcsrf-and-razor-pages
[no-csrf]: https://github.com/dotnet/aspnetcore/issues/11787#issuecomment-508000446
[pass-token]: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app
[tag-helper]: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-5.0#the-form-tag-helper

**Comment by javiercn** [comment]
@dmoncada thanks for contacting us.

CSRF is a vulnerability on your controller. The comment from @SteveSandersonMS is correct in the context of Blazor, since in Blazor the common way to render and react to a form submit is in the context of a websocket, where the submit event is handled by an event handler on the server and processed there, where there is no way for an external domain/page to trigger it.

If you have a controller that can accept input from a form, then you need to use Antiforgery or SameSite cookies (or both) to protect it. That is independent of whether you are using Blazor Server, Webassembly, Razor, or any other rendering technology.

On a CSRF attack, the vector is your controller receiving a request from a form input post coming from a separate origin, so you should protect it accordingly.

The comment mentions that Blazor Server is not vulnerable to CSRF because all the input is handled through a websocket and not through standard HTML mechanisms. And using traditional form posts is not something we recommend in the context of a Blazor server app, since it triggers a server side navigation, which neglects all the benefits of the SPA experience.
