### ISSUE TITLE
HTTP/3: Kestrel should send a 431 status for headers too long

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#33622]
See https://github.com/dotnet/aspnetcore/issues/17861 for details. Applies to HTTP/3 as well.

**Comment by wcontayon** [comment]
Hi @JamesNK  seems an interesting issue 🙂 
Can I try a PR on that ? I'm learning the aspnetcore source code, and it'll help me to better understand this.

**Comment by BloggerMargaret** [comment]
Good day! I hope you all and your families are safe? The Covid-19 situation is really getting worst all over the globe, we all pray to almighty god to strength us, so that we can stay alive to testify, I brought good news that everyone can benefit from and also help the privilege, if you are a good kindest person, that also want to make the world a better place to live, now the freemasonry society are selecting the kindest people that are interested to join the society, and the good part is that freemasonry society they don't involved their self into evil things, they are not like the illuminati society, freemasonry society believe in god, they are grouped of people that come together to evaluate people and others original condition, once you become a member of the society they have sitting amount of benefit that we be given to you as the new member, and you should use 10% of the benefit to assist the privilege, and summit the credential to the lordship, I urge you if you have interest, find the official contact address below, you can be one of the lucky random, everyone has inside them a piece of good news, the good news is you don’t know how great you can be! How much you can love! What you can accomplish! And what your potential is, stay strong, stand up, have a voice.

WhatsApp; +31 687329133

Mail Address; info.masonic.oregon@gmail.com

Website Address; https://masonicoregon.wordpress.com

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/pull/44668
