### ISSUE TITLE
WebApplicationFactory.Client should fail with DisposedException but does not.

### ISSUE THREAD

**Issue by Rubenisme** [dotnet/aspnetcore#33645]
@javiercn thanks, but I did know this and had already fixed this in the real code before raising this issue. It’s why I wrote this in the first message:

> How can I test that properly? The purpose of this test is to pretty much test the whole thing (of course excluding some mocks (not shown) that we have set up and tested elsewhere).
> 
> Of course I just fixed the mistake, but I would have liked to see this fail before finding out somewhere else.

The problem I have is that the test succeeds and didn’t find this error.

_Originally posted by @Rubenisme in https://github.com/dotnet/aspnetcore/issues/33601#issuecomment-863415398_

This is just the continuation of the previous since it was closed by the bot and not resolved.

**Comment by javiercn** [comment]
@Rubenisme thanks for contacting us.

It seems we closed the other issue ahead of time, sorry about that. Some times we mark them as answered early and our bot closes them before we can re-evaluate them.

Seems like we would need to implement IDisposable [here](https://github.com/dotnet/aspnetcore/blob/a9a6831a1a0aa2fc21c276e1f28b86a2b1cdbb28/src/Hosting/TestHost/src/ClientHandler.cs)

@Tratcher are you ok with this change? It would help people catch errors when the HttpClient instance gets disposed before you are done with it.

**Comment by Tratcher** [comment]
So the HttpRequestMessage and the HttpContent are disposed mid call but that doesn't cause an exception in the test server? For reference, what kind of HttpContent is it?

First, this looks like a race condition. The using block that disposes the request/content doesn't exit until the http operation becomes async. A normal http client might have to resolve dns, open a connection, serialize the headers, etc., lots of async work before sending the request. The in-memory one bypasses all of that overhead and can start reading the content almost immediately. I think this is happening before we even start reading the headers:
https://github.com/dotnet/aspnetcore/blob/a9a6831a1a0aa2fc21c276e1f28b86a2b1cdbb28/src/Hosting/TestHost/src/ClientHandler.cs#L71-L97

The in-memory flow does force server side processing off onto another thread, but not until later:
https://github.com/dotnet/aspnetcore/blob/a9a6831a1a0aa2fc21c276e1f28b86a2b1cdbb28/src/Hosting/TestHost/src/HttpContextBuilder.cs#L94-L99

A fix for this would require delaying the call to the SendRequestStream callback until after the thread hop in HttpContextBuilder.SendAsync. Arguably that's when it should happen anyways since it's weird to read the request body before 'sending' the headers.

cc: @JamesNK who last refactored that code path.

**Comment by Rubenisme** [comment]
Thanks so much @javiercn and @Tratcher, that makes sense that it happens so quickly in the test. I actually tried to add some middleware in the test later to delay the connection to see if that might be the cause but couldn’t get that working as hoped. Still had somehow excepted some check of disposal. Thanks for looking into this, this is one of those things that you’d like the test to reveal.

**Comment by Rubenisme** [comment]
> For reference, what kind of HttpContent is it?

@Tratcher or @JamesNK, just so you are aware, there is a [GH repo](https://github.com/Rubenisme/reproduce-request-disposed) mentioned in the first issue for easy testing of this.

I understand the focus this summer on the coming release, though hope it can be picked up quickly afterwards.

**Comment by javiercn** [comment]
@Rubenisme If @Tratcher is ok with it and you want to try and send us a PR I think we would accept one. I'm ok with it at the very least, however @Tratcher is the expert here, so I delegate to him.

**Comment by Tratcher** [comment]
It should be possible to delay the SendRequestStream callback until RunRequestAsync, I just don't know what affect it will have on existing tests. Feel free to try it.

**Comment by Rubenisme** [comment]
Yes, that’d be great. I tried to look at it and had it reproduced in a unit test in the hosting tests project but didn’t see an immediate solution. I haven’t given it more priority since, but have thought about it recently again, glad you are having some time for this.
