### ISSUE TITLE
Blazor JavaScript Canvas Switching Doesn't Work

### ISSUE THREAD

**Issue by skunkmonkey** [dotnet/aspnetcore#33649]
### Describe the bug
If you try to use JS to draw to one canvas, and then later change to draw to a different canvas the JavaScript will still draw to the old canvas instead of the new one. If you enter the JS commands directly into the developer tools in Chrome (F12) it will draw to the correct canvas, but making the JS calls through Blazor will draw to the old canvas instead.
This is a serious issue for us since we allow our users to switch tabs (which unloads the canvas from the DOM) and then when they switch back to the drawing tab it recreates a new canvas to draw on, but due to this bug drawing no longer works.

### To Reproduce
1. Download the master branch of this repo: https://github.com/skunkmonkey/BlazorCanvasBug.git
2. Run the application
3. Click the View1 button (it will draw a diagonal line in the top canvas)
3. Click the View2 button (it **should** draw a vertical line in the bottom canvas, but it will draw the line in the top canvas)
4. To prove that it's a problem with Blazor instead of a coding error, simply enter the drawing commands from SketchPad::SwitchToView2() directly into the developer tools console in Chrome (F12), and you will see it correctly draws to the bottom canvas.

### Further technical details
**IDE**
Microsoft Visual Studio Professional 2019 - Version 16.10.2

**'dotnet --info' results**
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.108 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SteveSandersonMS** [comment]
This happens because, for performance, JS interop caches the lookups from "identifier string" to "JS function instance". You call to:

```cs
JS.InvokeVoid("CanvasContext2D._context.moveTo", new object[] { 100, 100 });
```

... effectively caches the `CanvasContext2D._context` object, so on subsequent calls it will continue to use that object even if you've changed the global one.

I understand the caching behavior leads to a surprise in this case, but it is valuable to ensure good performance of JS interop. Generally it doesn't cause people problems. The reason it causes a problem here is that you're using and mutating JS global objects as a way of tracking application state, which is not a recommended pattern.

There are several ways you could fix this, but what I'd recommend is something like changing your `CanvasContext2D.init` function to return a JS object reference. Then you will be able to issue further calls on it from .NET code without having to pollute global state. For documentation about using JS object reference, see https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-isolation-in-javascript-modules or https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-javascript-isolation-and-object-references
