### ISSUE TITLE
[Blazor] Can't add breakpoint to razor while running

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33652]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Cant-add-breakpoint-to-razor-w/1450470)._

---
[severity:It's more difficult to complete my work]
VS Version: 16.9.5

Trying to break on a line of C# inside a razor file, which is perfectly fine while the program isn't running, doesn't work when it is running.
Breakpoint will just appear on line 1 of the file every time.

---
#### Feedback Bot on 6/16/2021, 01:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Goal here is to see if this is fixed by lspification

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue is fixed in the latest Visual Studio 2022. If you'd like to try this tooling out you can download the latest VS 2022 and re-try your scenario.

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
