### ISSUE TITLE
Until we have dynamic override support typing `=` should not auto-insert ""

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#33677]
Right now in Blazor if you type `=` we will auto insert the `""` for you which then requires you to not overtype the ending `"`. Once we have language-configuration.json to make this work we should re-enable this feature.

**Comment by allisonchou** [comment]
@NTaylorMullen Now that this issue is closed, can this line be uncommented? I tried and looks like there's still something funky going on though:
https://github.com/dotnet/aspnetcore-tooling/blob/4fa070530856a8db07cee9a480c37d1e9b5ee20a/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs#L206

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Now that this issue is closed, can this line be uncommented? I tried and looks like there's still something funky going on though:

Ya I think you're right it definitely can. We aren't going to bring back that support until we bring back the full `st|` => `style="|"` completion experience.
