### ISSUE TITLE
Blazor Debugging not working

### ISSUE THREAD

**Issue by bfmsoft** [dotnet/aspnetcore#33731]
I have a project that I can't get debugging working.  I have tried [all items from this page](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio).  I can get a New Project to work fine.  But something is stopping it from working on my project.  I have been using Console.WriteLine until I can get it to work.  It is really slowing things down.

Whenever I try to set a breakpoint when the application is started I get empty red circle with "The breakpoint will not currently be hit.  Unbound breakpoint".

If I set breakpoints it will set them (the red circle is solid).  But, the code doesn't stop.

In console window I see:
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-285047492998C23D12B37860BF67612B:::1052 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32602,
        "message": "No target with given id found"
      } ]

launchsettings.json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:43571",
      "sslPort": 44365
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "BfmGames": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

**Comment by bfmsoft** [comment]
Also get this message sometimes:

fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-E010D94B54F8C68AAD5A4E394F53AB89:::1052 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32602,
        "message": "No target with given id found"
      } ]

**Comment by bfmsoft** [comment]
Just got this again this morning:

fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-5FDC6B8FF29CBF373E761A3D68F4E1A1:::1020 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32000,
        "message": "Debugger agent is not enabled"
      } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-5FDC6B8FF29CBF373E761A3D68F4E1A1:::1021 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32000,
        "message": "Debugger agent is not enabled"
      } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-DB791F9EBC80116960EA5F6EC21C5985:::1052 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32602,
        "message": "No target with given id found"
      } ]

**Comment by captainsafia** [comment]
@bfmsoft You mentioned that debugging works on a new project but not the one under debug. Have you tried a process of elimination to identify any code changes that might be causing the issue? For example, we recently resolved an issue where having enum attributes would break debugging.

Some other things I would check:

- Do you have script debugging enabled in VS?
- Are you able to repro on the latest .NET 6 preview?

**Comment by bfmsoft** [comment]
@captainsafia It is a pretty big project that will take a while to do that but, what I am going to do next.  Is there any kind of log that can clue me into what is breaking?  I been looking for this for a couple weeks, trying things.

**Comment by captainsafia** [comment]
@bfmsoft There should be a `%TEMP%/visualstudio-js-debugger.txt` file that contains some helpful info.

**Comment by bfmsoft** [comment]
Here is my log file.  I don't see any errors of note.

[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/6696026/visualstudio-js-debugger.txt)

**Comment by captainsafia** [comment]
Hm, this caught my eye.

![image](https://user-images.githubusercontent.com/1857993/123027409-a3b27680-d392-11eb-9e28-43775d44ec9e.png)

Do you happen to be debugging an app with embedded PDBs or one that is in a Release configuration?

But despite that, it looks like at least one of your breakpoints registered as set.

![image](https://user-images.githubusercontent.com/1857993/123027493-c5abf900-d392-11eb-9c9c-d2f425b26976.png)

Are you unable to hit the breakpoint place in the file referenced above?

**Comment by bfmsoft** [comment]
I see that breakpoint when I run it states "The breakpoint will not currently be hit.  Unbound breakpoint."

**Comment by bfmsoft** [comment]
I just reworked everything.  Deleted the debug file and restarted.  The is a fresh file.

[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/6698662/visualstudio-js-debugger.txt)

**Comment by bfmsoft** [comment]
Sorry missed your questions.  No, this doesnt contain and pdfs and no not a release build.

Can u tell me the reasons it would set debugging as disabled?  Is there something I should have set?  I have tried to follow docs closely.

Thanks,
Brett

On Jun 22, 2021, at 10:48 PM, Safia Abdalla ***@***.***> wrote:

﻿

Hm, this caught my eye.

[image]<https://user-images.githubusercontent.com/1857993/123027409-a3b27680-d392-11eb-9e28-43775d44ec9e.png>

Do you happen to be debugging an app with embedded PDBs or one that is in a Release configuration?

But despite that, it looks like at least one of your breakpoints registered as set.

[image]<https://user-images.githubusercontent.com/1857993/123027493-c5abf900-d392-11eb-9c9c-d2f425b26976.png>

Are you unable to hit the breakpoint place in the file referenced above?

**Comment by bfmsoft** [comment]
When I try to debug in Shift-Alt-D in the browser I get:

On the browser it states: "Debugging connection was closed. Reason WebSocket disconnected

Then in the console window:

fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-958DAFA0F1D78D83664B65F5E6B374D7:::1023 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-958DAFA0F1D78D83664B65F5E6B374D7:::1024 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-958DAFA0F1D78D83664B65F5E6B374D7:::1025 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
got exception System.Net.WebSockets.WebSocketException (997): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()

**Comment by bfmsoft** [comment]
So, I found the issue.  I literally spent all day trying to eliminate a working project to a none working project.  It turns out that it had nothing to do with the project!

I have a Directory.Build.Props file.  That contains 
<DebugType>full</DebugType>

That breaks debugging.  Comment it out and it works.  Boy was that hard to find!

**Comment by pranavkm** [comment]
@lewing is this something the proxy could handle? Produce a reasonable error if the DebugType isn't portable?

**Comment by lewing** [comment]
cc @thaystg

**Comment by brice-fromentin** [comment]
I have the same issue, here is my steps :
 - Create Blazor App
 - Create .NET 6 Class Library Project
 - Create a class within the class library
 - In program.cs of blazor add : builder.Services.AddSingleton<MyClass>();
 - In MainLayout.razor add : @inject MyClass myClass

If I create MyClass in blazor project It works fine.

**Comment by thaystg** [comment]
@brice-fromentin which version of dotnet are you using?

**Comment by brice-fromentin** [comment]
@thaystg  I use latest preview of NET 6.0 (6.0.100-preview.7.21379.14).

**Comment by thaystg** [comment]
@brice-fromentin just to check if I'm reproducing the same thing that you are having. 
You are trying to add the breakpoint in a method in MyClass or somewhere else?
If you remove and add the breakpoint after the app is already running the breakpoint works?

**Comment by brice-fromentin** [comment]
In fact, I put a breakpoint on the constructor. The bug happens when I inject the singleton.
________________________________
De : Thays Grazia ***@***.***>
Envoyé : Tuesday, September 14, 2021 5:42:55 PM
À : dotnet/aspnetcore ***@***.***>
Cc : brice-fromentin ***@***.***>; Mention ***@***.***>
Objet : Re: [dotnet/aspnetcore] Blazor Debugging not working (#33731)


@brice-fromentin<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrice-fromentin&data=04%7C01%7C%7Cf4dbd85722ef4b6a4f8c08d9779652df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672309777032962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9MsyR8gQra%2BPffG9%2B%2FFsF3mFteYTTpJwJWjhOsepPM0%3D&reserved=0> just to check if I'm reproducing the same thing that you are having.
You are trying to add the breakpoint in a method in MyClass or somewhere else?
If you remove and add the breakpoint after the app is already running the breakpoint works?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Faspnetcore%2Fissues%2F33731%23issuecomment-919274187&data=04%7C01%7C%7Cf4dbd85722ef4b6a4f8c08d9779652df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672309777032962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LMFXAianDYWKulgPDPWlNszzdYZciNRfi8ZoDqMOulw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFA7Q5WB5S2SUTTF7QNUYS3UB5UP7ANCNFSM47CQSWBA&data=04%7C01%7C%7Cf4dbd85722ef4b6a4f8c08d9779652df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672309777042917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hzin2QcyvED%2FTxbx6qb4rnOGsAyal%2Bxc34jzlDgxZZ0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf4dbd85722ef4b6a4f8c08d9779652df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672309777042917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=chUFHyva58U49e%2Feg5wpEHjYBVUYf2E%2Fm7yy6M9iq3k%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf4dbd85722ef4b6a4f8c08d9779652df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672309777042917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nApvKC3smwCP4lSo4jfKpJBl6MBDwIVCxx1LuKOTbQA%3D&reserved=0>.

**Comment by dpozimski** [comment]
In my case - enabling `Tools/Options/Debugging/’Enable JavaScript debugging for ASP.NET (Chrome, Edge and IE)` fixed the problem

**Comment by boukenka** [comment]
Hello. In the Options dialogue box, enabling Javascript debugging does not solve the problem.

![image](https://user-images.githubusercontent.com/16502423/134763358-1853f062-81b7-4801-b805-17048d8cafc7.png)

**Comment by thaystg** [comment]
This was fixed in this PR https://github.com/microsoft/vscode-js-debug/commit/aed1287598f581c7d8ae24ef8cabeff74761a3a2, I'm checking when it will be on VS and will let you know when I have this information.

**Comment by brice-fromentin** [comment]
Thanks you
________________________________
De : Thays Grazia ***@***.***>
Envoyé : Monday, September 27, 2021 3:31:38 PM
À : dotnet/aspnetcore ***@***.***>
Cc : brice-fromentin ***@***.***>; Mention ***@***.***>
Objet : Re: [dotnet/aspnetcore] Blazor Debugging not working (#33731)


This was fixed in this PR ***@***.***<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-js-debug%2Fcommit%2Faed1287598f581c7d8ae24ef8cabeff74761a3a2&data=04%7C01%7C%7C8faad89b65ab4520e19308d981bb22d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637683463004066434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A7krnSF7PYk5HUJXQDxygQQg2Omir2Jyp%2FAjnz6ve2A%3D&reserved=0>, I'm checking when it will be on VS and will let you know when I have this information.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Faspnetcore%2Fissues%2F33731%23issuecomment-927878784&data=04%7C01%7C%7C8faad89b65ab4520e19308d981bb22d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637683463004076387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1HDFEQwbb9V%2FurNnkU4W9Jl%2F00KZfdG3q3ympICDo%2Bc%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFA7Q5QL443DZIEZFUGZVT3UEBW3VANCNFSM47CQSWBA&data=04%7C01%7C%7C8faad89b65ab4520e19308d981bb22d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637683463004076387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X7qkuORRWfowjvls48As60Kw5NJM2eleAQIp24ZDV2g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8faad89b65ab4520e19308d981bb22d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637683463004086354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kpnb5UOOvZ3yBmk7w%2BtKGbGb4ACAoBMEEqW1%2F82Kl5k%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8faad89b65ab4520e19308d981bb22d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637683463004096306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w5zNny%2FRkJx0WdmvZDql1A2QsJoGputpFatMxieHnHs%3D&reserved=0>.
