### ISSUE TITLE
WebApplicationBuilder.Services should fail if accessed after Build()

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#33812]
WebApplicationBuilder.Services does nothing after the application has already been built, so anything trying to modify it is likely buggy. I suppose it possible to want to access this just to read the service descriptors but that feels unlikely.

In addition to throwing InvalidOperationExceptions from the WebApplicationBuilder.Services getter and the various methods on IServiceCollection, we could also consider writing an analyzer similar to the UseAuthorizationAnalyzer to fail at build time if WebApplicationBuilder.Services is obviously incorrectly accessed after build.

**Comment by LadyNaggaga** [comment]
Related issue 
### Scenario

**What are you trying to do**: get a list of to-do items from the in-memory database and writes a JSON representation to the HTTP response.


```cs
app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync());
```
Data model

``` cs
class TodoItem
{ 
    public int Id { get; set; }
    public string Item { get; set; }
    public bool IsComplete { get; set; }
}
```

DbContext 

```cs 
{
    public TodoDb(DbContextOptions options) : base(options) { }
    public DbSet<TodoItem> Todos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("Todos");
   
```
Runs app and navigates to `/todos`
Error message: InvalidOperationException: Unable to read the request as JSON because the request content type '' is not a known JSON content type. 
![image](https://user-images.githubusercontent.com/2546640/124786650-e4bf9480-df15-11eb-89c2-11623f696831.png)

Problem
-  TodoDb isn't registered as a service the error message is confusing \
`builder.Services.AddDbContext<TodoDb>(options => options.UseInMemoryDatabase("items"));`

Proposed solution 

Better error message handling 
![image](https://user-images.githubusercontent.com/2546640/124788901-cce91000-df17-11eb-8734-f948510790a0.png)
