### ISSUE TITLE
Downloading a file with unicode characters in file name creates wrong Content-Disposition header

### ISSUE THREAD

**Issue by mathijsco** [dotnet/aspnetcore#33912]
### Describe the bug
Downloading files from a .net core ASP webserver is creating wrong file names in the fileNameStar field in the Content-Disposition header.
When a file name is used with a smiley, e.g. "File 🤩 name.txt", the header that is generated is wrong.

The following value is returned in the Content-Disposition header: 
`attachment; filename="File __ name.txt"; filename*=UTF-8''File%20%EF%BF%BD%EF%BF%BD%20name.txt`

However, it should be:
`attachment; filename="File __ name.txt"; filename*=UTF-8''File%20%f0%9f%a4%a9%20name.txt`
(This last one matches the header of OneDrive).

### To Reproduce
```cs
var header = new Microsoft.Net.Http.Headers.ContentDispositionHeaderValue("attachment");
header.SetHttpFileName("File 🤩 name.txt");
header.ToString().Dump();
```

### Further technical details
- ASP.NET Core version 3.1.16
- .NET SDK (reflecting any global.json):
   Version:   5.0.301
   Commit:    ef17233f86
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19043
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\5.0.301\
  
  Host (useful for support):
    Version: 5.0.7
    Commit:  556582d964
  
  .NET SDKs installed:
    2.2.207 [C:\Program Files\dotnet\sdk]
    5.0.100 [C:\Program Files\dotnet\sdk]
    5.0.301 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
  Visual Studio Professional 2019 (16.10.1)

**Comment by Tratcher** [comment]
EF BF BD is the utf-8 replacement character `�`. https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD, it couldn't correctly encode the emoji.

`🤩` is actually two characters or code points combine as a [surrogate pair](https://docs.microsoft.com/en-us/globalization/encoding/surrogate-pairs), 0xD83E and 0xDD29. Encoding.UTF8 called on the whole string would generate the expected 0xF0, 0x9F, 0xA4, 0xA9.

There's a bug in ContentDispositionHeaderValue's encoding where it does not handle surrogate pairs because it calls Encoding.UTF8 on individual characters, and surrogate pairs are not valid when split up.
https://github.com/dotnet/aspnetcore/blob/86ea8e019eb315dd6b68bd7fcc796a0fcb6a67c9/src/Http/Headers/src/ContentDispositionHeaderValue.cs#L613-L620

This encoding is inefficient anyways and would benefit from a re-write.

**Comment by adityamandaleeka** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/34071
