### ISSUE TITLE
Adding a new Razor component does not get picked up as a valid component until edit

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#33957]
Repro:
1. Create a new component (do not edit it)
2. Try and reference it in another file

**Expected:** Colorization/completion in said file
**Actual:** Nothing

if you then go and edit the created component it'll become available.

**Comment by NTaylorMullen** [comment]
Happens in multi-project scenarios, specifically I did it in the Blazor WASM project here: https://github.com/NTaylorMullen/ASPNetProjects

**Comment by mayur-ekbote** [comment]
I guess it's also related to #33914 . It is happening in every VS version including in 2022.

**Comment by ryanbrandenburg** [comment]
This doesn't reproduce as described on latest internal builds, likely it was fixed by https://github.com/dotnet/aspnetcore-tooling/pull/3995.

I DO see that completion is not initially offered to the referencing file, but if you type the name out by hand it colorizes and after that point you're able to get it as a completion option.
