### ISSUE TITLE
Feature Request: Blazor: Handling of ambiguous routes

### ISSUE THREAD

**Issue by Phloog** [dotnet/aspnetcore#33963]
Dear *,

it would be very helpful if we could handle ambibuous routes gracefully in Blazor, by either

- make routes defined in a Blazor application take precedence over identical routes defined in an RCL (specified by "AdditionalAssemblies" on the Router)
- or give the Router-Component an event we can react/subscribe to that is raised on ambigous routes and allows us to write code to decide which route to take

What do you think?

**Comment by javiercn** [comment]
@Phloog thanks for contacting us.

We don't have short term plans to offer a way to disambiguate between routes in Blazor. 
We already disambiguate based on route precedence (similarly to how its done in ASP.NET Core) and if we were to do this, we would not implement it in a different way than how it is done in ASP.NET Core today, which is using the route order.

**Comment by Phloog** [comment]
@javiercn thanks for your insights - may I ask you to elaborate on

> We already disambiguate based on route precedence (similarly to how its done in ASP.NET Core) 

because this doesn't apply to identical routes, right? "Only" routes with common paths up to a certain hop. If an RCL defines a certain path (e.g.  "/my/page") and a blazor app referencing this RCL defines the same path ("/my/page"), an exception is thrown on app startup. This is what I hoped could be made a bit more graceful.

**Comment by javiercn** [comment]
@Phloog no, it doesn't it applies to routes with at least a different segment type, for example `/a/{b}` and `a/c` both match the path `a/c`, however the second route `a/c` is picked since it has higher precedence over `a/{b}`.

In general it's not super common to have conflicting routes in Blazor apps since in the majority of cases routes are defined with literals and those tend to be unique across the routing space. In addition to that, the developer is normally in control of all the routes in the app, so it's reasonable to resolve the conflict by changing one of the routes.

If we see more requests for it, we might consider doing something here, however it would most likely just mean adding an optional Order property to the routes in the same way ASP.NET core does.

**Comment by Phloog** [comment]
I understand. Would it then maybe be possible to subclass the Router component and implement the disambiguation myself?

**Comment by gingters** [comment]
> In addition to that, the developer is normally in control of all the routes in the app, so it's reasonable to resolve the conflict by changing one of the routes.

I tend to disagree with that. Components can (and should) be provided by different teams and that makes it extremely (and in my opinion unnecessarily) difficult to structure a project that re-uses components as you have to derive all components just to add a project-specific route, because the component developer can't know at what route where the component will be used in different projects he provides the components, pages or even complete application submodules for. Different projects re-use the same pages and submodules at different routes. That clutters the project and makes it near to impossible to provide a clean and simple structure.

To be really usable and flexible and allow for re-using of components the routing system needs a way to completely define the routes outside of components to be able to compose an application (i.e. like in Angular, where you configure the routes for the components at a place where you also configure your DI).

This would also allow @phloog to use re-components from a library and override the predefined routes so that it matches his specific application.
