### ISSUE TITLE
Preview 6 NoHttps issues with react template

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#33979]
With 6/29 preview 6 builds (see https://github.com/aspnet/AspNetCore-ManualTests/issues/719) for exact builds used

React templates with No https selected have issues:

- No auth, with no https is completely broken, the project does not seem to get created at all, no files are dropped, no error is raised, it just silently fails with an empty soln created (@phenning what's the best way for me to see the errors in this situation from VS/project creation?)

- Individual auth with no https, creates the project, builds, npm install/test work, and launches but there are failures at runtime:

```
Unhandled Rejection (Error): Could not load settings for 'ReactP6IndAuth'
AuthorizeService.ensureUserManagerInitialized
C:/Users/haok/source/repos/ReactP6IndAuth/ReactP6IndAuth/ClientApp/src/components/api-authorization/AuthorizeService.js:184
  181 | 
  182 |        let response = await fetch(ApplicationPaths.ApiAuthorizationClientConfigurationUrl);
  183 |        if (!response.ok) {
> 184 |            throw new Error(`Could not load settings for '${ApplicationName}'`);
      | ^  185 |        }
  186 | 
  187 |        let settings = await response.json();
View compiled
async AuthorizeService.getUser
C:/Users/haok/source/repos/ReactP6IndAuth/ReactP6IndAuth/ClientApp/src/components/api-authorization/AuthorizeService.js:24
  21 |            return this._user.profile;
  22 |        }
  23 | 
> 24 |        await this.ensureUserManagerInitialized();
     | ^  25 |        const user = await this.userManager.getUser();
  26 |        return user && user.profile;
  27 |    }
View compiled
async AuthorizeService.isAuthenticated
C:/Users/haok/source/repos/ReactP6IndAuth/ReactP6IndAuth/ClientApp/src/components/api-authorization/AuthorizeService.js:15
  12 |    _popUpDisabled = true;
  13 | 
  14 |    async isAuthenticated() {
> 15 |        const user = await this.getUser();
     | ^  16 |        return !!user;
  17 |    }
  18 | 
View compiled
async LoginMenu.populateState
C:/Users/haok/source/repos/ReactP6IndAuth/ReactP6IndAuth/ClientApp/src/components/api-authorization/LoginMenu.js:27
  24 |    }
  25 | 
  26 |    async populateState() {
> 27 |        const [isAuthenticated, user] = await Promise.all([authService.isAuthenticated(), authService.getUser()])
     | ^  28 |        this.setState({
  29 |            isAuthenticated,
  30 |            userName: user && user.name
```

**Comment by phenning** [comment]
It looks like this is happening in Visual Studio because of the env.development file contains:

```
PORT=5002
//#if(RequiresHttps)
HTTPS=true
//#endif
```

Visual Studio 2022 Preview 2 and earlier still use a version of the template engine which is not preocessing .development files properly, instead when instantiating the template, the template engine reposts the following to host, which we do not surface to the user in any meaningful way.

```
Error while processing file /React-CSharp/ClientApp/.env.development
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: srcOffset
at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
at Microsoft.TemplateEngine.Core.Util.ProcessorState.AdvanceBuffer(Int32 bufferPosition)
at Microsoft.TemplateEngine.Core.Util.ProcessorState.Run()
at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target)
at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)
```

This does not happen on the command line because obviously template engine itself in the NET 6 SDK does not have this problem. @vlada-shubina  can confirm, but I believe this extension is handled properly in NET 6.

This will be resolved in Visual Studio 2022 Preview 3 will resolve this as we are updating the template engine binaries to the NET 6 template engine. 

@vlada-shubina is there a way we can update the template so that the 3.0 template engine which is in Visual Studio Preview 2 can process this file properly, in case we need to make this work as is for Preview 7?

**Comment by vlada-shubina** [comment]
Likely to be https://github.com/dotnet/templating/issues/2913. 
Reordering statements so that condition is not last statement in the file may help.

**Comment by phenning** [comment]
@HaoK I just tested out the suggestion by adding a single additional line at the end of the file and it creates fine then in preview 2. Seems like a low risk fix to take to the template.
