### ISSUE TITLE
RCL + Libman: Restored files don't get packed / published at the correct location in final app.

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#34039]
### Describe the bug
Files that are restored with the Microsoft.Web.LibraryManager.Build (LibMan) inside a Razor Class Library (RCL) are not deployed to the correct location in the final consuming app (e.g. Blazor Server App).
Instead of being deployed to:
`wwwroot/_content/<RCL Package Name>/`
they are deployed to 
`wwwroot/`

This happens only if the files are not yet restored when you pack / publish the app. Once the files are restore they are correctly deployed in subsequent builds.

dotnet version:
 5.0.300
environments:
dotnet cli (e.g. dotnet pack)
Visual Studio (pack context menu)

### Solution
I found out that the ResolveCurrentProjectStaticWebAssetsInputs target takes content files as its input. The LibraryManagerRestore on the other hand doesn't produce content items. If you apply the following workaround, the issue disappears:

```xml 
...
  <PropertyGroup>

<ResolveCurrentProjectStaticWebAssetsInputsDependsOn>LibraryManagerRestore;FixLibManRestore;$(ResolveCurrentProjectStaticWebAssetsInputsDependsOn)</ResolveCurrentProjectStaticWebAssetsInputsDependsOn>

  </PropertyGroup>
  
  <Target Name="FixLibManRestore" AfterTargets="LibraryManagerRestore">
  <ItemGroup>
            <Content  Include="%(FilesForPackagingFromProject.Identity)" Exclude="@(Content)">
            </Content>
        </ItemGroup>
		
  </Target>

...

```

**Comment by javiercn** [comment]
@TFTomSun thanks for contacting us.

The solution you came up with is not a workaround, it's the correct way to achieve this scenario. We only look at content items and its up to other components to expose things as Content at the right time for them to be picked up by static web assets.

I would suggest you file an issue on the Libman repo for this, since this is not something Libman needs to add in their targets to support integration with RCLs
