### ISSUE TITLE
Source generators from M.E.Logging.Abstractions conflict with source generators in the transport package

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#34048]
Two copies get added

* microsoft.aspnetcore.internal.transport\6.0.0-preview.7.21352.2\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll
* microsoft.extensions.logging.abstractions\6.0.0-preview.7.21352.2\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll

which results in conflicts.

**Comment by dougbu** [comment]
@ViktorHofer (in @ericstj's absence) as I mentioned in #34033, we should now have worked around this duplication. But, is this an issue that should be transferred to (and fixed in) dotnet/runtime❔

**Comment by dougbu** [comment]
/ping @ViktorHofer @ericstj I believe this issue can be closed as I haven't heard recent noise about it. Please confirm.

**Comment by pranavkm** [comment]
@dougbu should we remove the workaround: https://github.com/dotnet/aspnetcore/blob/main/eng/Workarounds.targets#L51-L57?

**Comment by dougbu** [comment]
> @dougbu should we remove the workaround?
> https://github.com/dotnet/aspnetcore/blob/main/eng/Workarounds.targets#L51-L57

Yes, as long as the underlying issue is gone. If not, we should just live with it and consider those lines a "fix".

**Comment by ericstj** [comment]
When the version is the same as in the above we rely on conflict resolution to prefer the framework copy.  In the actual product we do this with the `PackageConflictPreferredPackages` property.  See https://github.com/dotnet/sdk/issues/19834#issuecomment-901363082

In your case you need to treat the transport package like it's the framework package (since you're constructing the framework).  I think you do so by adding that to `PackageConflictPreferredPackages`, though it still needs a target since the SDK will overwrite the value with what the framework says:
https://github.com/dotnet/sdk/blob/22c4860dcb2cf6b123dd641cc4a87a50380759d5/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L366

**Comment by dougbu** [comment]
@ericstj anything wrong w/ us using the current workaround and closing this issue❔ Guess I'm asking about the upsides of your recommendation.

**Comment by ericstj** [comment]
The current workaround always prefers the transport package, regardless of version.  You're unlikely to ever mismatch versions so that's probably OK.  The other thing about your current workaround is that it would require updates if/when we add generators to other package.  You could avoid that by saying to conflict resolution to always prefer the transport package.

**Comment by dougbu** [comment]
> You could avoid that by saying to conflict resolution to always prefer the transport package.

That makes sense but we only use the transport package for ref/ assemblies and analyzers or code generators. We don't want the transport package used for implementation assemblies. Can `PackageConflictPreferredPackages` handle that nuance❔

Another option would be to remove the implementation assemblies from the transport package and _then_ switch to using `PackageConflictPreferredPackages`.

**Comment by ericstj** [comment]
Just let us know what you want to do for implementation assemblies and we'll make it happen.  Test it out to see what the behavior is.  Presumably you're working around it already?

**Comment by wtgodbe** [comment]
Ok, we'll give `PackageConflictPreferredPackages` a shot as-is to see if it already works - if not we'll follow up with you about what we want to do with the implementation assemblies in the transport package.

**Comment by wtgodbe** [comment]
Opened https://github.com/dotnet/aspnetcore/pull/40216. I don't think there are any implementation assembly conflicts being resolved in favor of the transport pack after this PR, if there were any such conflicts they'd have been present before it as well - but given that we don't use those implementation assemblies anyways, could they be removed @ericstj?

**Comment by wtgodbe** [comment]
The `PackageConflictPreferredPackages` workaround caused more problems than it solved, so we'll stick with what we already have.
