### ISSUE TITLE
Setting custom FieldCssClassProvider globally.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#34099]
Currently, to override the Blazor's default `FieldCssClassProvider ` we need to add our custom `FieldCssClassProvider ` on every EditContext as follows:

```C#
var editContext = new EditContext(model);
editContext.SetFieldCssClassProvider(new BootstrapValidationClassProvider());
```

There is no option to set it globally for all `EditContext`. Actually, there should be an option to set it globally for all `EditContext.`

Thank you.

**Comment by pranavkm** [comment]
We think the best way to do this is to use a helper function that does this. Blazor generally does not have ways to global defaults for components.

**Comment by TanvirArjel** [comment]
@pranavkm Really, there is no way to override this for all components at once?https://github.com/dotnet/aspnetcore/blob/8d46b3a64ea784c95dddeb9d421c7cda6de993a2/src/Components/Web/src/Forms/EditContextFieldClassExtensions.cs#L26-L43

However, what about changing the Blazor default CSS validation classes to `is-valid` and `is-invalid` in  `FieldCssClass` to map to the popular bootstrap framework. Most importantly ASP.NET Core Blazor default templates are using bootstrap then why its validation classes did not map to the bootstrap validation classes?

**Comment by pranavkm** [comment]
Unfortunately at this point changing the defaults would be a breaking change.

**Comment by TanvirArjel** [comment]
@pranavkm Sometimes breaking changes are needed for the evolution of a library, framework, or software, isn't it?

**Comment by SteveSandersonMS** [comment]
@TanvirArjel Yes, absolutely. But nonetheless, backcompat is something we take very seriously, so a breaking change requires very careful consideration. For example:

 * If it's the sort of thing that can be detected at compile time, we're more open to doing it because developers will be forced to update their code to adapt.
 * But for a change like this, there would simply be a change of behavior at runtime with no warning to the developer, which we tend to do only in the most extreme cases (e.g., if it was fixing a security issue).

I know that, since you want this change, it may seem like a win if it happened. But there have probably been dozens of other breaking changes that other people have requested which, if we had done them, would have broken your applications (even if they did evolve the framework). We need to balance these interests and make sure all developers are empowered to get the results they want, without having to debug unexpected changes of behavior when upgrading to newer frameworks.

The existing extensibility we've provided (`FieldCssClassProvider`) means you can get the behavior you want, and you can use it throughout your whole app just by wrapping your calls to `new EditContext()` inside some custom wrapper that returns an edit context configured however you wish. If this seems impractical, it would be great if you could clarify why, as we may be able to suggest ways to do it more conveniently. I hope this seems reasonable!

**Comment by TanvirArjel** [comment]
@SteveSandersonMS Yes! Your explanation seems right. I have accepted it. But why overriding the following `FieldCssClass` class from a central place is not possible?

https://github.com/dotnet/aspnetcore/blob/8d46b3a64ea784c95dddeb9d421c7cda6de993a2/src/Components/Web/src/Forms/EditContextFieldClassExtensions.cs#L26-L43

**Comment by SteveSandersonMS** [comment]
It’s because global defaults don’t work when you have a component library ecosystem. Each library may have different opinions about the defaults, and may break if you change them. The only way to have a reliable ecosystem is for the developer to control the options used at each usage site. 

This is the same reason that System.Text.Json doesn’t have configurable default serialisation options.

**Comment by TanvirArjel** [comment]
@SteveSandersonMS Got it! Thank you for your clarification.
