### ISSUE TITLE
Consider moving Content includes for cshtml and razor files from RazorSDK -> NETSdk

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#34188]
Based on an offline conversation, it appears not having .cshtml / .razor files as Content items causes LSP-based Razor tooling to not function. We've seen a few incidents of users referencing the .NET SDK instead of Razor / Web SDK which results in no tooling. Moving the content includes in to the .NET SDK at the same place where the Compile Include default is configured would be one way to remedy the issue.

**Comment by NTaylorMullen** [comment]
@pranavkm if we were to make these tooling interactions work for older SDKs is there an item group that contains all of the Razor files in a similar form to `Content` that we can ask the project system team to understand?

**Comment by Eilon** [comment]
Just talked to @NTaylorMullen and I have a somewhat related case for .NET MAUI. In .NET MAUI we have a workaround that involves removing `*.razor` from the Content ItemGroup into the RazorComponent ItemGroup. Because the Razor files are no longer in Content, something to do with Roslyn/RazorEditor no longer sees the files for Intellisense/highlighting/whatever purposes and you lose out on the compilation of those items at _design time_ (regular build works fine).

@NTaylorMullen showed me a workaround for this, which was to do my Content-->RazorComponent mapping only when NOT in DesiginTimeBuild:

```csproj
  <ItemGroup Condition="'$(DesignTimeBuild)' != 'true'"> <-- this Condition was added to work around the issue -->
    <Content Remove="**\*.razor" />
    <RazorComponent Include="**\*.razor" />
  </ItemGroup>
```

**Comment by Eilon** [comment]
Related .NET MAUI issues that are fixed by adding the DesignTimeBuild condition:

* [Bug] IntelliSense does not work in .razor file in .NET MAUI Blazor App. https://github.com/dotnet/maui/issues/1623
* [Bug] Partial class for Razor Component does not work. https://github.com/dotnet/maui/issues/1516

**Comment by davidwengier** [comment]
Given that we already have two 1st party project types that have different item types for Razor files, I think this request is probably not the way to go, as it would only make the MAUI workaround permanent.

I can think of a couple of other possibilities:

1. Consider all `.cshtml` and `.razor` files to be dynamic files (and hence associated with Roslyn as such) regardless of item type
	* This would require confirmation from the .NET Project System (@tmeschter @jjmew) to see if it's possible as I'm not sure there is an "All item types" concept they can hook into
2. A property to control which item types are considered dynamic files
	* This still needs work on the project system side to read the property, so still needs a feasability check there
	* Presumably then MAUI would set `<DynamicFileItemType>RazorComponent</DynamicFileItemType>` in their SDK, the Web SDK can set `<DynamicFileItemType>Content</DynamicFileItemType>` and the default value in the base SDK can be `<DynamicFileItemType>None</DynamicFileItemType>`

**Comment by Eilon** [comment]
What I would love is that if all Razor stuff had some particular MSBuild ItemGroup and then everyone could reason about that item group, but that would probably be a huge breaking change for all the various MSBuild targets/props in the world that assume they're always Content.

So, while admitting I'm not an expert in this and all the implications, I think having various SDKs specify what they consider to be "dynamic" for Roslyn purposes seems reasonable, because I _think_ each SDK has a sensible idea of what to specify.

Though, I'd like to add that one of the problems that led me down this path to begin with is that each SDK couldn't agree with each other on who "owns" what files/item groups, and if you use more than 1 SDK (which is increasingly common), you end up with conflicts. So giving SDKs perhaps more "power" over these things is not a decision to take lightly.

**Comment by tmeschter** [comment]
If a project uses more than one SDK, is it possible that some .razor files in the project will need to go through process `A`, some through process `B`, and some through both? (I'm being vague and hand-wavy here but I don't know anything about how these files are actually handled.)

**Comment by davidwengier** [comment]
@tmeschter The files are picked up by the [`DynamicItemHandler`](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs) in the project system. Proposal number 2 would be specifically to resolve [this value](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs#L31) from evaluation rather than hardcoding `Content.SchemaName`.

**Comment by tmeschter** [comment]
Right, but could there be situations where we need to handle multiple item types? E.g. you're using more than one SDK and each expects a different item type to be dynamic?

**Comment by davidwengier** [comment]
At the moment the only supported way for the Razor editor to work is to put items in `Content`, and we're only suggesting changes because it seems like we can turn a common enough scenario (that is, people opt-ing out of the web sdk) into a pit of success. There is no requirement that I've seen for us to go further and allow full customization of things to the extent of needing to allow for multiple item types. At the same time, if its something that is easier to consider up front, from a project system point of view, then I don't think anyone would object. They just might not ever use it.

**Comment by Eilon** [comment]
@tmeschter said:

> If a project uses more than one SDK, is it possible that some .razor files in the project will need to go through process `A`, some through process `B`, and some through both? (I'm being vague and hand-wavy here but I don't know anything about how these files are actually handled.)

From my understanding, all .razor files in any "normal" scenario would always go through the same process: get processed by Razor (a source generated), converted to C#, and compiled into a DLL. The Razor owners would have to confirm this.

**Comment by mkArtakMSFT** [comment]
@davidwengier do you plan to handle it? Just saw it assigned to you.

**Comment by mkArtakMSFT** [comment]
Talked to @davidwengier and he will be handling this work.

**Comment by davidwengier** [comment]
Tracking this work in https://github.com/dotnet/project-system/issues/7411

At this point in time I don't think this will need any work outside of the project system repo, but will leave this issue open for tracking.
