### ISSUE TITLE
Verify that Razor compiler honors global usings when generating code for .cshtml & .razor files

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#34217]
With C# 10 introducing support for global usings declarations and the SDK now implicitly adding global usings for projects targeting .NET 6 we need to verify that the Razor compiler honors any global usings (whether set via the SDK or in the project) in the code it generates.

We expect this will "just work" so this issue is to ensure we verify that.

Assuming this is verified we can update the project templates to not explicitly add usings in .cshtml/.razor files if they're already added by the SDK.

@captainsafia @pranavkm

**Comment by captainsafia** [comment]
At the moment, the set of imports that we include via the SDK:

```
// <autogenerated />
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

Mostly overlaps with the set that we include by default in the generated Razor code.

https://github.com/dotnet/aspnetcore/blob/19f1321aa92911d6e1f66090313f2db9a543021f/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentImportProjectFeature.cs#L17-L21

So we can already remove those imports.

Razor currently uses the `_Imports.razor` file to define global usings. Moving the `usings` from `Imports.razor` to a global usings file doesn't seem to work for a Blazor WASM app.

```
global using BlazorWasmApp.Shared;
```

will fail to compile due to issues resolving types in the Shared namespace.

```
/Users/captainsafia/Verifications/GlobalUsings/App.razor(1,1): warning RZ10012: Found markup element with unexpected name 'Router'. If this is intended to be a component, add a @using directive for its namespace. [/Users/captainsafia/Verifications/GlobalUsings/GlobalUsings.csproj]
/Users/captainsafia/Verifications/GlobalUsings/App.razor(2,5): warning RZ10012: Found markup element with unexpected name 'Found'. If this is intended to be a component, add a @using directive for its namespace. [/Users/captainsafia/Verifications/GlobalUsings/GlobalUsings.csproj]
/Users/captainsafia/Verifications/GlobalUsings/App.razor(4,9): warning RZ10012: Found markup element with unexpected name 'FocusOnNavigate'. If this is intended to be a component, add a @using directive for its namespace. [/Users/captainsafia/Verifications/GlobalUsings/GlobalUsings.csproj]
/Users/captainsafia/Verifications/GlobalUsings/App.razor(6,5): warning RZ10012: Found markup element with unexpected name 'NotFound'. If this is intended to be a component, add a @using directive for its namespace. [/Users/captainsafia/Verifications/GlobalUsings/GlobalUsings.csproj]
```

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/34719.
