### ISSUE TITLE
MapControllerRoute does not support link generation for conventional routes

### ISSUE THREAD

**Issue by ctbhavius** [dotnet/aspnetcore#34283]
### Describe the bug

ControllerEndpointRouteBuilderExtensions.cs in Microsoft.AspNetCore.Builder methods for MapAreaControllerRoute and MapControllerRoute do not support link generation for creating endpoint routes by convention.   They create endpoints with SuppressLinkGeneration: True

and there is no readily available "open access" to modifying classes and methods because too many of them are marked "internal" and not easily modifiable.  For example, why should AddConventionalLinkGenerationRoute() be hidden, and thus more or less unusable, by marking the class ActionEndpointFactory "internal"?

### To Reproduce

Conventional route mapping methods unavailable because too many are marked "internal" or otherwise have properties that are readonly or gettable only, and cannot be modified as settable properties.  Why?  Will methods for supporting conventional routing be maintained?   Or must conventional routing be abandoned in favor of attribute routing?

### Exceptions (if any)

MapControllerRoute generates endpoints with SuppressLinkGeneration: True  and  SuppressMatching: True

Developers should have greater control of managing the properties of MVC routes that are mapped to endpoints via conventional routing approaches with MapControllerRoute and MapAreaControllerRoute

### Further technical details
Net 6 preview 5
6.0.100-preview.5.21302.13

**Comment by javiercn** [comment]
@ctbhavius thanks for contacting us.

When a conventional route is mapped, we expand the pattern to apply it to the list of discovered action and create specific endpoints for matching those controllers as we are able to dramatically optimize the system that way.

In addition to that, we add a separate link generation endpoint for the conventional route mapped.

It's not clear what your issue is specifically about, if you can point out what was working with you before that now doesn't work, that will help us.

**Comment by ctbhavius** [comment]
None of the calls in our code libraries to MapControllerRoute or MapAreaControllerRoute generate any endpoints that support link generation.  So link generation does not work for us with our conventional MVC routes.  If you are now asserting that calls to MapControllerRoute generate endpoints that do support link generation, can you please provide the references to the demos and tests that show and prove how MapControllerRoute can and does generate endpoints which support link generation?  Can you also please explain why developers should NOT have access to and control of various methods and classses such AddConventionalLinkGenerationRoute and the class ActionEndpointFactory?  Why must they remain hidden and unaccessible for use by developers?   And if you wish to argue that such and such is necessary for "purposes of optimization", then why is it not switchable on and off so that you do NOT create the unintended side-effect of jeopardizing flexibility and convenience of access and use of methods and classes by developers?

**Comment by ctbhavius** [comment]
And why do you declare this issue answered and resolved when it has not been either addressed or resolved?

**Comment by javiercn** [comment]
> If you are now asserting that calls to MapControllerRoute generate endpoints that do support link generation, can you please provide the references to the demos and tests that show and prove how MapControllerRoute can and does generate endpoints which support link generation?

Can you provide a sample demo/sample that they do not?

This is basic functionality that we are confident its not broken both because we have tests and because we would have heard from virtually every ASP.NET Customer in existence. We must not be understanding what you are asking if you think is broken, so if you provide a repro app, that would help us get on the same page.

> Can you also please explain why developers should NOT have access to and control of various methods and classses such AddConventionalLinkGenerationRoute and the class ActionEndpointFactory? Why must they remain hidden and unaccessible for use by developers?

The question we normally ask ourselves is the opposite, why would a developer need access to those types? If we can't find a concrete scenario that has many customer requests and that require that type to be public, we won't make it public. In general our goal is to minimize the public API surface area, otherwise it limits our ability to freely evolve the implementation over time.
