### ISSUE TITLE
net461 Invalid option '10.0' for /langversion. Use '/langversion:?' to list supported values.

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#34292]
Since the recent SDK update and the langversion being changed to 10, projects targeting net461 no longer compile in VS 2019 16.11.0p2.
```
Error	CS1617	Invalid option '10.0' for /langversion. Use '/langversion:?' to list supported values.	Microsoft.Extensions.Features (net461)	D:\github\AspNetCore\src\Http\Features\src\CSC
```

Should we make the langversion conditional?

**Comment by pranavkm** [comment]
We should remove this: https://github.com/dotnet/aspnetcore/blob/15949fa899e1b64b0b5142b0d753be87a5d24215/eng/targets/CSharp.Common.props#L4 and let the SDK decide the version.

**Comment by Tratcher** [comment]
I don't know if that's viable. Without it we get two types of errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8630	Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.	Microsoft.AspNetCore.DataProtection.Abstractions (net461)	D:\github\AspNetCore\src\DataProtection\Abstractions\src\CSC	1	N/A
Error	CS8652	The feature 'global using directive' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.	Microsoft.AspNetCore.Cryptography.Internal (net461)	D:\github\AspNetCore\artifacts\obj\Microsoft.AspNetCore.Cryptography.Internal\Debug\net6.0\Microsoft.AspNetCore.Cryptography.Internal.ImplicitNamespaceImports.cs	2	N/A
```

**Comment by JunTaoLuo** [comment]
How feasible is it to fix those errors by adding LangVersion properties in whatever projects/areas that needs those fixes?

I like leaving the default up to the SDK and only specify it for projects where it's needed.

**Comment by davidfowl** [comment]
@jaredpar this is a PITA 😢

**Comment by jaredpar** [comment]
> Since the recent SDK update and the langversion being changed to 10, projects targeting net461 no longer compile in VS 2019 16.11.0p2

Can you be more specific here? Can't tell if you mean:

1. When you hit Build in Visual Studio the project fails to compile 
2. When you are editting in Visual Studio the error list contains an error about unsupported language versions

Guessing you mean (2). If you mean (1) then you likely have bigger issues because it means there is a mismatch between the compiler you believe you are using (one from .NET 6 SDK P6) and the one you are actually using (likely .NET 5 SDK) 

> We should remove this ... and let the SDK decide the version

The TF being used here is `net461` hence letting the SDK decide means it will choose 7.3. Given the setup here you are likely better just using `<LangVersion>preview</LangVersion>`

> this is a PITA

I understand it's frustrating but you're using the SDK in several unsupported configurations here. 

- The .NET 6 P6 SDK is only validated in 16.10 for the purpose of building `net5` projects
- Language versions above `7.3` are tied to TF

This is going to have rough edges in your current setup and you have to thread the needle here on how to use it.

**Comment by Eilon** [comment]
I'm seeing lots of `The using directive for `System` appeared previously in this namespace` and similar:

![image](https://user-images.githubusercontent.com/202643/125538860-6b5e6f05-197f-4c4a-864f-c5d8833700d3.png)

![image](https://user-images.githubusercontent.com/202643/125538880-17d6ee46-528a-4907-86ca-8d789a906b62.png)

**Comment by davidfowl** [comment]
@Eilon I'm gonna send a PR for that

**Comment by davidfowl** [comment]
@Tratcher where do those errors come from?

**Comment by Tratcher** [comment]
> Can you be more specific here? Can't tell if you mean:
> 
> 1. When you hit Build in Visual Studio the project fails to compile
> 2. When you are editting in Visual Studio the error list contains an error about unsupported language versions
> 
> Guessing you mean (2). If you mean (1) then you likely have bigger issues because it means there is a mismatch between the compiler you believe you are using (one from .NET 6 SDK P6) and the one you are actually using (likely .NET 5 SDK)

It's 1, the build fails in VS:
```
========== Build: 0 succeeded, 100 failed, 0 up-to-date, 0 skipped ==========
```

> @Tratcher where do those errors come from?

I'm building `src\Middleware\Middleware.slnf`.

Switching langversion to `preview` avoids the langversion errors and we're left with the duplicate usings error. Adding `<NoWarn>$(NoWarn);0105</NoWarn>` to the root Directory.Build.Props gets us to a clean build (#34324).

**Comment by jaredpar** [comment]
> It's 1, the build fails in VS:
> Since the recent SDK update and the langversion being changed to 10, projects targeting net461 no longer compile in VS 2019 16.11.0p2.

These two statements don't make sense together. The SDK update should not change how the langversion for this scenario. It only changed how langversion is calculated when targeting `net6.0`. 


> We should remove this:
> aspnetcore/eng/targets/CSharp.Common.props
> <LangVersion>10.0</LangVersion> 
> and let the SDK decide the version.

This seems like the problem. You all have essentially hard coded `<LangVersion>10.0</LangVersion>` into the build files. That will only be supported when using a compiler that is .NET 6 P6 or higher. Yet it appears based on the data here that you are using an earlier compiler that doesn't support that language version. 

The easiest way to determine what compiler you are using is to insert the following into your code and build. 

```c#
#error version
```

**Comment by Tratcher** [comment]
> These two statements don't make sense together in terms of cause / effect. The SDK update should not change how the langversion for this scenario. It only changed how langversion is calculated when targeting `net6.0`.

To clarify, updating the SDK and setting the langversion to 10 were two distinct steps that happened as part of the global usings feature.

> The easiest way to determine what compiler you are using is to insert the following into your code and build.

CS8304	Compiler version: '3.11.0-2.21301.11 (757770cf)'. Language version: preview.	Microsoft.Net.Http.Headers

**Comment by jaredpar** [comment]
> CS8304 Compiler version: '3.11.0-2.21301.11 (757770cf)'. Language version: preview.

Yeah that is the compiler from 16.11 / .NET 5.400X which is which is essentially the stock compiler that comes with 16.11. That means you're going to be limited to the features we shipped in .NET 6 P5. That excludes file scoped namsepaces and the change to langversion 10.0.

To get the new features in 16.11 you need to install the .NET 6 P6 SDK + have VS use that. Even then you still want to use `langversion:preview` because VS isn't going to understand 10.0. This is squarely in the unsupported territory I listed above but you can make it work if you put in some effort. 

Overall though the path of least resistance is move to Dev17 😄
