### ISSUE TITLE
Support extensionKind = "workspace" for Blazor WASM Companion Extension

### ISSUE THREAD

**Issue by mdgilene** [dotnet/aspnetcore#34413]
### Is your feature request related to a problem? Please describe.

Currently the extensionKind is "ui" which means this extension cannot be used for remote development (ssh/container/etc.)

### Describe the solution you'd like
Support extensionKind "workspace" so that the extension can run on the remote host as well.

**Comment by javiercn** [comment]
@mdgilene thanks for contacting us.

Can you clarify the extension you are talking about?

**Comment by mdgilene** [comment]
Hi yes, I am referencing this extension specifically.

https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion

**Comment by captainsafia** [comment]
@mdgilene It is by design that the companion extension only supports being run on the local host. It's sole purpose is to launch a debugging proxy between the browser (running on the local machine) and the application server (running on the remote machine) and it needs to run on the local host to support this.
