### ISSUE TITLE
Try contributing to aspnetcore with Codespaces

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#34436]
To make it easier for developers to contribute to the aspnetcore repo, we're experimenting with enabling GitHub Codespaces in the aspnetcore repo.

**What is GitHub Codespaces?**
Codespaces is a cloud-based development environment based on VS Code. Instead of installing an editor and dependencies locally, you can access a cloud-based development environment that contains all the tools needed to be productive with the repo. You can learn more about Codespaces at https://docs.github.com/en/codespaces/about-codespaces.

**How do I get access to Codespaces?**
You'll have to sign up for the Codespaces beta at https://github.com/features/codespaces/signup.

**How do I use Codespaces in the aspnetcore repo?**
Navigate to the `dotnet/aspnetcore` repo on GitHub and select the "Open with Codespaces" option under the "Code" dropdown.

![image](https://user-images.githubusercontent.com/1857993/126005542-cb664704-5931-49b9-baf5-1c9d306f4ad8.png)

A new window will open with a web-based VS Code session containing the cloned code for the repo. It might take a few minutes for the initialization steps to complete. Once that is done, you can follow the [build instructions](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#step-3-build-the-repo) to build the repo.

**Share your feedback on GitHub codespaces in the comments below! ⬇️**

**Comment by martincostello** [comment]
I had a quick try of this just now to just clone, build and run some tests for MVC. These are the things I experienced that I thought were of note:

1. The `onCreateCommand` part of the terminal that runs when the Codespace starts seems to take a _very_ long time to run.
2. Related to the above, after 5-10 minutes (I forgot to note the exact time) I got a high CPU warning (see screenshot below), presumably because of something the above command was doing.

![code-spaces-high-cpu](https://user-images.githubusercontent.com/1439341/126331669-b77e4761-1c67-46fc-90c5-e0106a9c45b6.png)

3. I ran `./src/Mvc/build.sh -test` and got a single test failure. However, consuming that failure wasn't particularly friendly as it was embedded in an HTML file that I had to open in the editor, so I got the raw render of the failed test, rather than something easy to read (see screenshot below). Maybe there's a better way to deal with viewing HTML files within a Codespace (I've not really used it before) that I'm unaware of, but as a newbie it wasn't obvious to me how to get something better to consume like if I was developing locally.

![code-spaces-failed-tests](https://user-images.githubusercontent.com/1439341/126331949-9390ba74-aa06-4581-bae0-0b61f40dccd6.png)

**Comment by captainsafia** [comment]
@martincostello Thanks for the feedback! I'll see if I can route some of this to the appropriate channels.

> The onCreateCommand part of the terminal that runs when the Codespace starts seems to take a very long time to run.

Do things work fine if you just close the `onCreateCommand` Window and go about with your dev work?

**Comment by martincostello** [comment]
Yeah it seemed fine, though at first I assumed it needed to finish before I could start. After a few minutes of it running I just figured maybe not and then started doing stuff.

It felt like something that was maybe important though, so I left it to do it's thing in the background rather than cancel it.

**Comment by captainsafia** [comment]
> The onCreateCommand part of the terminal that runs when the Codespace starts seems to take a very long time to run.

OK. I fixed this in https://github.com/dotnet/aspnetcore/pull/34945. Turns out the script was running and exiting fine. Just needed to exit at the end.

**Comment by captainsafia** [comment]
> Maybe there's a better way to deal with viewing HTML files within a Codespace (I've not really used it before) that I'm unaware of, but as a newbie it wasn't obvious to me how to get something better to consume like if I was developing locally.

I think our best bet is some time of HTML previewer extension for the VS Code instance.

Typically, you'd view these HTML files using a web browser on your local machine. However, I don't think it's possible at the moment to open HTML files inside the Codespace without some HTTP server running.

An extension like https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer might help but it is not very discoverable. We'll see if there is something else...

**Comment by captainsafia** [comment]
Bad bot! Let's keep this open.

**Comment by captainsafia** [comment]
Robot, you are rude.
