### ISSUE TITLE
Request that Blazor Webassembly .js nw, 2000, and electronics.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34502]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Webassembly가-nwjs-및-electron-에서도/1466988)._

---
Running a web page created with Blazor WebAssembly .js or electronic will cause an error like the one shown below.

! [Capture444. PNG](https://aka.ms/dc/image?name=B648a7b3b2e6e4f7d98be8b38a733332a637608400951112484_%EC%BA%A1%EC%B2%98444.PNG&tid=648a7b3b2e6e4f7d98be8b38a733332a637608400951112484)

This seems .js nw, or .js has both a node, a web environment, and a web environment.

If you specify __dirname as shown in the photo below, the error will not occur.

! [Capture445. PNG](https://aka.ms/dc/image?name=Bc662c157a94c498abb852d6db6e02071637608402343037014_%EC%BA%A1%EC%B2%98445.PNG&tid=c662c157a94c498abb852d6db6e02071637608402343037014)

If the Blazor Webassembly-driven script recognizes .js as a node,, but also the web environment,

__dirname want to set the value of the __dirname to location.origin, instead of specifying the part that sets the path.

---
#### Feedback Bot on 7/4/2021, 07:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by danroth27** [comment]
Thanks for contacting us. Instead of using Blazor WebAssembly in a native app, we've been pursuing a different approach where the Blazor components are executed locally in a .NET process that communicates with an embedded web view or browser through a local interop channel. For .NET 6 we are shipping support for running Blazor in .NET MAUI, WPF, and Win Forms apps. The model can be extended to other app frameworks as well (see https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebView for an example).  We recommend pursuing a similar approach.
