### ISSUE TITLE
Suspend Razor.BackgroundDocumentGenerator during solution close

### ISSUE THREAD

**Issue by sharwell** [dotnet/aspnetcore#34603]
This is similar to dotnet/roslyn#47408. BackgroundDocumentGenerator allocates large amounts of data, which can indirectly delay solution close.

**Comment by davkean** [comment]
@NTaylorMullen I've opened https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1370125 to represent this. GitHub bugs are not getting caught in the queries the division are tracking because none of the dashboards respect them.

This is impact is huge, in the trace called out, its allocating 3.2 GB during solution close.
