### ISSUE TITLE
[Question] How to validate SignalR request?

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#34676]
I was expecting something like ModelState of the controller for the Hub and use validation attributes the same way we do with action models, but I didn't find it. how should I validate the request models properties?

**Comment by davidfowl** [comment]
SignalR has no validation built in, and there's no model state. You can use something like fluent validation to perform validation or manually invoke data annotations to invoke valiation.

**Comment by MhAllan** [comment]
thanks @davidfowl, any plans to make a hub act like a controller and for this validation and also have middleware pipeline?

**Comment by davidfowl** [comment]
Validation won't ever be built into SignalR no, you can write a IHubFilter that does this though.

**Comment by MhAllan** [comment]
@davidfowl do you mind to explain why? just curious

**Comment by davidfowl** [comment]
Validation is expensive and not everyone wants to have it be automatic when they're doing RPC. Signalr is used in many different ways not just as an mvc replacement over websockets. We'd also need to think about client side validation as well since rpc is bidirectional and I haven't seen many requests for that. 

We'd also need to introduce a validation abstraction so differ frameworks can plug in (like fluent validation). In the end it's much easier if it's all opt in and manual and with filters you can do that if you really care.
