### ISSUE TITLE
Blazor webassembly: In the browser, navigating to a shared project's files displays raw information

### ISSUE THREAD

**Issue by wheat32** [dotnet/aspnetcore#34687]
### Describe the bug
On the default Blazor wasm project that is ASP.NET Core hosted, raw JSON data can be seen if you start debugging and navigate to a page sharing the name of a file in the Shared project. This seems like it has the potential to be a security issue, or at the very least can make the website look unprofessional.

### To Reproduce
1. Launch Visual Studio
2. Create a Blazor WebAssembly App (make sure ASP.NET Core Hosted was checked)
3. Do not modify the code
4. Start debugging
5. In the browser, navigate to WeatherForecast
6. Note the raw JSON printed to the screen

I found this when I created a razor component with the same name as a file in the Shared project and refreshing the browser would only show the raw information and not load Blazor.

### Further technical details
- ASP.NET Core version: 6.0-preview 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022 Preview 2

![Capture](https://user-images.githubusercontent.com/5769329/126883585-317b05da-9f69-4038-b1b5-d35227dc8c5e.PNG)

**Comment by javiercn** [comment]
@wheat32 thanks for contacting us.

That's expected and by design. The json endpoint is not secured and for that reason is accessible from any client (including the browser).

What's happening here is that you have an endpoint (in this case a file) that is in a conflicting path with a client route. Server routes always take precedence over client routes (which are mapped as a fallback). This is simply how the system works.

I would suggest that 1, you avoid creating ambiguous endpoints, and 2, you take into consideration how the system works and plan your app endpoints accordingly.

**Comment by wheat32** [comment]
Thanks for the response! Hopefully this isn't a stupid question, but is there a way around that? On the Blazor template project for example, if I navigated to WeatherForecast in the browser, is there a way I can hide that, redirect the user, or give them a 404 message?
