### ISSUE TITLE
Razor view engine renders wrong result for boolean value

### ISSUE THREAD

**Issue by mkorsukov** [dotnet/aspnetcore#34718]
### Describe the bug

The Razor view has a checkbox input defined by:

```
<input type="checkbox" name="@(nameof(Model.UpdateProfitEstimator))" value="@(Model.UpdateProfitEstimator)"  />
```

where the `UpdateProfitEstimator` is a boolean property. And the final HTML looks like:

```
<input type="checkbox" name="UpdateProfitEstimator" value="value">
```

The "value" is incorrect here. It should be "True / False" value instead. I have multiple lines of code with such syntax and most of the time the HTML output gets correct "True / False" values. I can't find the reason why the "value" value is coming from the Razor.

So I have to use this fix for now:

```
... value="@(Model.UpdateProfitEstimator.ToString())" />
```

### Further technical details
dotnet --info:
```
NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [/usr/share/dotnet/sdk]
  5.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

IDE:
```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-63-generic snap
```

**Comment by campersau** [comment]
I guess that this is by design as boolean values are special and are used to toggle element attributes which is useful for `checked` / `disabled` / `readonly` etc.

Is it intentional you are setting the `value` of a `checkbox`? Most times you just need the `checked` attribute which works with booleans.

Here are some references:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Mvc/Mvc.ViewFeatures/src/RazorComponents/HtmlRenderer.cs#L232-L237

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Components/Shared/src/RenderBatchWriter.cs#L153-L162

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L360-L371

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L674-L678

**Comment by mkorsukov** [comment]
@campersau Thank you for detailed response! The reason I use `value` is to actually submit the value (true or false) to the backend. In some other cases the value can be an ID (from user list, for instance). If no `value` attribute present on the input, the browser submits the `on` value, which is not bindable as is.

I need to mention, there is a single `input` tag per property in my case to keep the final HTML clean.

I know, that Razor helper (Html.CheckBoxFor) will generate a pair of tags:
```
<input id="Data_IsPurchaseAgreementUploaded" name="Data.IsPurchaseAgreementUploaded" type="checkbox" value="true">
<input name="Data.IsPurchaseAgreementUploaded" type="hidden" value="false">
```

**Comment by mkorsukov** [comment]
@campersau I'm sorry, maybe something wrong with my environment...

- Few days ago I was forced to use `value="@(Model.Data.IsStandardAddendumsUploaded.ToString())"` as value was `value`.
- Today I'm trying to use `value="@(Model.Data.IsStandardAddendumsUploaded)"` and it works fine. The value = `True / False`.

**Comment by mkorsukov** [comment]
I'm closing the issue now.
