### ISSUE TITLE
WebHostBuilderExtensions.UseSolutionRelativeContentRoot doesn't find the project path

### ISSUE THREAD

**Issue by lioror** [dotnet/aspnetcore#34793]
after the function traverses to parent folder until it finds the folder of the sln file.
then it simply concatenates the project folder name to the path after the solution.
in case there is some folders on the way it will fail, for example: <Sln Folder Path>\src\<project path>.
you should either search for this directory recursively or pass the correct relative to solution path.

**Comment by martincostello** [comment]
The argument is called `solutionRelativePath`, so you just need to give it the relative path so it is found.

```csharp
UseSolutionRelativeContentRoot(Path.Combine("src", "MyProject"))
```

**Comment by lioror** [comment]
It is called internally

**Comment by martincostello** [comment]
But `\src<project path>` doesn't have a slash in the middle (at least from what's in the issue description), so would come out as `srcMyProject`, which is why the call to `Path.Combine()` here isn't working for you:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Hosting/TestHost/src/WebHostBuilderExtensions.cs#L181

**Comment by lioror** [comment]
Using this method directly with the right relative path worked, thanks.
