### ISSUE TITLE
Blazor Validation: Private fields, methods, and properties in EditContext should be accessible. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34800]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Validation:-Private-fields-metho/1478770)._

---
Although a new validator class is simple to create, there appears to be no way to get at private members of the EditContext class, although the Blazor Component itself should be permitted to reach into its own context (via reflection). This is currently poses a major obstacle as to the usability of Blazor validation.

---
#### Feedback Bot on 7/19/2021, 08:07 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please provide more details about the scenario you're working on and you're unable to. Also, it would help to share a small repro app showing the code that is failing for you.

**Comment by HansGuckInDieLuft** [comment]
Comment and Closure of that issue happened at my annual leave. So, I had no chance to react. And I do so now with some irony: 
Actually, when caring just about functionality, who would ever need private class members, if public ones already work. Then, we could even simplify things down to the basics: who would ever need classes, when simple dynamic objects would suffice?
So, to make it even simpler: I'd propose to carry on with Angular instead of Blazor.
