### ISSUE TITLE
Blazor component performance differences in service-mode and wasm mode

### ISSUE THREAD

**Issue by neozhu** [dotnet/aspnetcore#34878]
I found that the same code is very slow to render the page in the wasm environment. I can be sure that the performance is much slower than vue, angular, and react,
why is it?
Anyone have encountered a similar situation ?

https://user-images.githubusercontent.com/1549611/127604579-9a710bb7-848e-4e9a-b613-1ff2cb020982.mp4

following code:
````
@page "/"
@using MudBlazor

<MudTable 
          Height="calc(100vh - 290px)" 
          FixedHeader="true" 
          FixedFooter="true"
          Items="@Elements" 
          MultiSelection="true" 
          @bind-SelectedItems="SelectItems"
          Hover="@hover">
    <HeaderContent>
        <MudTh>Nr</MudTh>
        
    </HeaderContent>
    <RowTemplate>
        <MudTd DataLabel="Nr">@context</MudTd>
       
    </RowTemplate>
    <PagerContent>
        <MudTablePager PageSizeOptions="new int[]{50, 500,1000,2000}" />
    </PagerContent>
    <FooterContent>
        <MudTd colspan="5">Select All @SelectItems.Count</MudTd>
    </FooterContent>
</MudTable> 
@code {
    private bool hover = true;
   

    private List<int> Elements = new();
    private HashSet<int> SelectItems=new();

    protected override async Task OnInitializedAsync()
    {
        Elements = await Task.FromResult(Enumerable.Range(0,6500).Select(e=>e).ToList());
    } 
}
````

**Comment by javiercn** [comment]
@neozhu thanks for contacting us.

Blazor webassembly runs IL code via an interpreter compared to blazor server that JITs the IL into native code and runs it. If you want to get more similar performance in webassembly, we recommend you Ahead of Time (AoT) compile the application.

That produces webassembly code that the browser is able to execute directly. You should see much less performance difference in that mode compared to blazor server.

That said, despite all that, we recommend you try and limit what you are rendering to what fits on the viewport. Rendering elements that don't fit in the viewport is wasteful because the user doesn't see them immediately and still consume resources. We have a `virtualization` component specifically designed to deal with large list of data that can help here.

**Comment by neozhu** [comment]
Thank you for having responded, I will try it right away

**Comment by neozhu** [comment]
now, it's ok.
I found no performance issues after deploying to the IIS server.
http://wasm.i247365.net/
http://aot.i247365.net/
I'm relieved for the moment
thank you again.
