### ISSUE TITLE
Quarantine Components.E2E tests failing due to Selenium not launching page

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#34941]
## Failing Test(s)

- CanRenderSvgWithLink
- Router_RequireRole_NotAuthorized
- CachesResourcesAfterFirstLoad
- CanAddAndRemoveChildComponentsDynamically

## Build

- https://dev.azure.com/dnceng/public/_build/results?buildId=1269884

**Comment by SteveSandersonMS** [comment]
Closing because since all the work to make E2E tests more reliable, they are now extremely reliable (100% pass rate as far back as the stats go, and yes [they are still able to report failures](https://github.com/dotnet/aspnetcore/pull/38115)).

I verified that the four specific tests listed above are all running and are part of that pass rate.
