### ISSUE TITLE
Different behavior when using Authorize attribute on SignalR Hub Class vs. Method

### ISSUE THREAD

**Issue by oriches** [dotnet/aspnetcore#34977]
**Is this a bug or by design?**

When using the Authorize attribute on a SignalR Hub implementation I  am getting different result/response in the client application depending on where the attribute is placed:

Class Level - I recieve an expected 403 (forbidden) in the client when attempting to connect.

    [Authorize(Policy = "MyPolicy")]
    public class ExampleHub : Hub
    {
        public Task Register()
        {
            return Task.CompletedTask;
        }
    }

Method Level (Hub endpoint) - I am not recieving anything in the client, there is no fault in the execution.

    public class ExampleHub : Hub
    {
        [Authorize(Policy = "MyPolicy")]
        public Task Register()
        {
            return Task.CompletedTask;
        }
    }

I would expect to recieve a 403 error from the Hub endpoint (even after successful connection).

**Sever**
ASP.Net Core version 5.0,
Hosted in Kestrel  in a .Net 5.0 console app.

**Client**
.Net framework 4.6.1,
WPF application,

VS 2019 (16.10.3)

**Comment by BrennanConroy** [comment]
This is by design. If you connect to the hub you're now connected. There can't be a 403 after the fact, that'd be like making an HTTP request, getting a 200, then later getting a 403 somehow.

If you try to invoke a method you're not allowed to invoke, you will
a) get a log on the server side
b) if you did InvokeAsync or StreamAsync on the client side you will receive an error saying you aren't authorized to call that hub method. If you used SendAsync there is no invocation id the server can send an error back on, so the client wont receive anything.

If you do want to close the connection if it tries to call a method it isn't allowed to, you can use an authorization handler and call Abort on the `resource.Context` https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#use-authorization-handlers-to-customize-hub-method-authorization

**Comment by oriches** [comment]
Thanks for detailed answer.
