### ISSUE TITLE
Failing Test `HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#34982]
## Failing Test(s)

- Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange

## Error Message

```text
Assert.Equal() Failure
↓ (pos 0)
Expected: Message two

Actual:

↑ (pos 0)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange() in /_/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs:line 386
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[xUnit.net 00:00:02.26]     Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange [FAIL]
[xUnit.net 00:00:02.26]       Assert.Equal() Failure
[xUnit.net 00:00:02.26]                 â†“ (pos 0)
[xUnit.net 00:00:02.26]       Expected: Message two\n
[xUnit.net 00:00:02.26]       Actual:   
[xUnit.net 00:00:02.26]                 â†‘ (pos 0)
[xUnit.net 00:00:02.26]       Stack Trace:
[xUnit.net 00:00:02.26]         /_/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs(386,0): at Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange()
[xUnit.net 00:00:02.26]         --- End of stack trace from previous location ---
[xUnit.net 00:00:03.08]   Finished:    Microsoft.AspNetCore.HttpLogging.Tests

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1272695&view=ms.vss-test-web.build-test-results-tab&runId=37642180&resultId=108945&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by wtgodbe** [comment]
This is firing for me locally when the test fails:

https://github.com/dotnet/aspnetcore/blob/405567fde1dc8108691f258916b7a5fca9848abf/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L197-L200

Which returns before the current message is written. Still digging.

**Comment by wtgodbe** [comment]
Oh, I think I know what's happening. I wait for the file to exist, then dispose - but that dispose could happen between the file getting created here:

https://github.com/dotnet/aspnetcore/blob/405567fde1dc8108691f258916b7a5fca9848abf/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L184

And the CancellationToken check here:

https://github.com/dotnet/aspnetcore/blob/405567fde1dc8108691f258916b7a5fca9848abf/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L197

So I should really be waiting for the file to exist & have content, rather than just waiting for it to exist. I'll update the tests then do another batched run locally to confirm they stop failing.
