### ISSUE TITLE
Update razor page item template to react to changes with implicit usings, etc.

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#35073]
- [ ] Remove `using` statements from the `PageModel` class file that aren't required to compile the content in the file
- [ ] Use block-scoped namespace declarations

**Comment by Ponant** [comment]
@DamianEdwards , why  Use block-scoped namespace declarations? I thought the idea is to use file-scoped namespace and Rc1 currently uses block-scoped namespaces (that was not the case in preview 7).

**Comment by DamianEdwards** [comment]
@Ponant it's due to current limitations with detecting the current project's language version and user preferences when item templates are executed. Using block-scoped in the item template will mean it works for all projects, regardless of the language version. If the project/solution the item is being added to has an editor config file that configures a preference for file-scoped namespace declarations, then Visual Studio will apply that on file creation for .cs files.

**Comment by Ponant** [comment]
Thanks @DamianEdwards , how can i instruct VS to use file scoped namespace, if that is even possible now?

**Comment by DamianEdwards** [comment]
I'm trying it out now and can't make it work so I'm tracking down what's what.

In the meantime, there is a code-fix-up already available in VS 2022 though:
![image](https://user-images.githubusercontent.com/249088/133499114-581d4ddb-56fd-4efd-bff6-ed22f57cd136.png)

**Comment by Ponant** [comment]
Thank you @DamianEdwards , I forgot this fix. I filled an issue in roslyn as I believe it belongs there
https://github.com/dotnet/roslyn/issues/56410.
Have a good day

**Comment by mkArtakMSFT** [comment]
@phenning do you plan to handle this?

**Comment by phenning** [comment]
We decided in the my PR to use block scoped namespace in this template. 
https://github.com/dotnet/aspnetcore/pull/34598#issuecomment-895388843

This issue was never updated as a result of that discussion. I'll defer to @DamianEdwards  if you want to make additional changes here. We have most of the support we need in Visual Studio to enable this. The main issue was with the fact that with NET 6 AND NET 5 installed that there was no way for command line creation to get the NET 5 version of the template since item creation can't inspect the project, and there was not a desire to put additional parameters on the template.

**Comment by DamianEdwards** [comment]
Yep I think we're done with this then, thanks!
