### ISSUE TITLE
HTTP/3: alt-svc port and proxies

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#35150]
What happens if a server is behind a proxy and the end-user port is different from the configured listener port?

i.e. website is behind TLS terminating proxy and has port 80, while public port is 443.

**Comment by Tratcher** [comment]
YARP blocks proxying the alt-svc header for this reason. The proxy would need to add its own header.

Since h3's advantages are mainly on the edge, h3 and alt-svc are less likely to be used between the proxy and server.

If the alt-svc header does get through, the connectivity test will fail and the client will continue using the other protocols.
