### ISSUE TITLE
RazorSourceLineCollection - internal abstract method

### ISSUE THREAD

**Issue by softwaretirol** [dotnet/aspnetcore#35218]
### Describe the bug
The class "RazorSourceLineCollection" is an abstract class but has declared a internal abstract method.
For that reason it is not possible to derive from this class because the method can not be overwritten?

Is there any reason for this?

### To Reproduce
Just derive from this class and try to overwrite it :-).

**Comment by javiercn** [comment]
@softwaretirol thanks for contacting us.

I'm not sure what might be going on there, likely a programming mistake from one of our developers. It doesn't matter since these APIs are not consumed outside of the context of the Razor compiler. These APIs are not meant to be used by third-parties so there is nothing we plan to do to address these issues unless we have to due to changes in requirements.
