### ISSUE TITLE
Unexpected behavior with docker and environment variables

### ISSUE THREAD

**Issue by HarelM** [dotnet/aspnetcore#35362]
### Describe the bug
Setting environment variables for a public facing kestrel server does not behave as expected.
Details:
We have a web server that runs on `https://israelhiking.osm.org.il/` the backend is a kestrel server that also does the https encryption. It runs inside a docker container.
The code can be found here:
https://github.com/IsraelHikingMap/Site/blob/7b2afd9dca83eae40f6dab1e7f32afd6847a949f/IsraelHiking.Web/Program.cs#L22
and here:
https://github.com/IsraelHikingMap/Site/blob/7b2afd9dca83eae40f6dab1e7f32afd6847a949f/IsraelHiking.Web/Startup.cs#L147
The story is a bit long, but try to bear with me:
We have a tile server that returns vector tiles, it seems that it has a problem with returning valid headers for http2 so we turn off the http2 by the following env variables:
```
ASPNETCORE_Kestrel__Endpoints__HttpsDefaultCert__URL: https://israelhiking.osm.org.il
ASPNETCORE_Kestrel__Endpoints__HttpsDefaultCert__Protocols: Http1
```
We also added the following env variables to support both https and http on default ports:
`ASPNETCORE_URLS: http://+;https://+`
We Also added these variables to support https:
```
ASPNETCORE_Kestrel__Certificates__Default__Path: some-path
ASPNETCORE_Kestrel__Certificates__Default__Password: some-pass
```
We were happy that we though everything is working as expected until we noticed the following warning in the log file:
``` 
Overriding address(es) 'http://+:80, https://+:443'. Binding to endpoints defined in UseKestrel() instead.
...
Hosting environment: Production
Now listening on: https://[::]:443
```
Weird, there's no place where we override these settings to only expose 443 and not 80...
We added the following line to the code:
`PreferHostingUrls(true)` in `program.cs` and it removed the overriding warning but also re-enable http2.

This seems like very odd behavior which I can't reconcile... seems to me like there are some bugs here which are colliding...

### To Reproduce
I don't have a minimal reproduction code unfortunately.

### Exceptions (if any)
None, just incorrect and unexpected behavior

### Further technical details
See docker file here:
https://github.com/IsraelHikingMap/Site/blob/7b2afd9dca83eae40f6dab1e7f32afd6847a949f/Dockerfile#L18

**Comment by halter73** [comment]
Kestrel allows you to define endpoints two ways:
1. Via "hosting" which most commonly means the `ASPNETCORE_URLS` environment variable, `--urls` command line flag or `.UseUrls()`. These all work with HttpSysServer as well.
2. Via Kestrel-specific APIs (like calling one of the `.Listen()` API in a `UseKestrel()`) or via the `Kestrel:Endpoints` section of configuration (typically this is in `appsettings.json` but `ASPNETCORE_Kestrel__Endpoints__*` does effectively the same thing). This gives more control over the specified endpoint like configuring certs.

Kestrel does not let you merge "hosting" URLs with endpoints specifically defined just for Kestrel. Normally, Kestrel will bind just to the endpoints defined specifically for Kestrel. This is what the `Overriding address(es) 'http://+:80, https://+:443'. Binding to endpoints defined in UseKestrel() instead.` warning log is about.

When `PreferHostingUrls(true)` is configured, the opposite happens and "https://israelhiking.osm.org.il" (which is inferred to be port 443 because of the "https" in the URL) is used and whatever is defined via the `ASPNETCORE_Kestrel__Endpoints__*` environment variables is ignored. 

Starting in 6.0, we'll have updated this log to say `Overriding address(es) 'http://+:80, https://+:443'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.` See #29618.

Triage, are we happy with the new log message? I wonder if it would be better as `Binding to endpoints defined in Kestrel "Endpoints" configuration and/or UseKestrel() instead.` since it points out the overrides are coming from the "Endpoints" section and `IConfiguration` is getting pretty deep into implementation details.

I'm also wondering if we should backport this log message fix. We could go all the way back to 2.1.x with this.

**Comment by HarelM** [comment]
Thanks for the super detailed and fast respond!
This makes a lot of sense in terms of why this is not behaving "reasonably" (for me).
I would say that `UseKestrel()` in the warning did not point me to the right direction in terms of what was happening and what was wrong.
The details provided in this issue is allowing me to better understand this.
I would recommend creating a KT article that better explains this, as I couldn't find anything in the documentation that explain this and details the difference and the fact that these aren't being "merged".
After creating such kind of KT article simply link to it in the warning like you are doing for other issues, I think this will allow developers like me to see the warning, go to the KT article and better understand how to solve this issue.
I will move all the configuration to the appsetting.json file and hopefully it will solve my problems.
Thanks again!

**Comment by adityamandaleeka** [comment]
Triage: closing this since we have the improved message in .NET 6.
