### ISSUE TITLE
Use bound parameters in authorization?

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#35371]
We have authorization policies which use "context" to decide whether a user is allowed to access a resource. Some of them should now use the action's parameters to decide whether the user is allowed to access the resource, e.g.:

```
[HttpPost]
public IActionResult MyAction ([FromQuery] Guid myId, [FromQuery] Guid myId2, MyModel model)
{
    doSomethingWith(myId, myId2, model.MyId3);
}
```

At first we thought to just look at all the query parameters, however, that would allow an attack to specify a third query parameter `MyId3=AllowedValue` in the query to trick the auth system, when in reality, the controller aciton uses MyId3 from the form data model.

How to implement this in a clean way with ASP.NET 5? Maybe there is a clean way to get the bound values from the IParameterBinder at the time of authorization? Can we obtain the parameter values from the action descriptor somehow?

Best regards,
D.R.

**Comment by abdusco** [comment]
Authorization middleware runs before Endpoint middleware, and therefore authorization policies (and handlers) are evaluated before MVC performs model binding. That means you won't be able to access `MyModel` instance declaratively. (You can always call `_authorizationService.AuthorizeAsync(User, model, "my_policy")` imperatively)

You can, however, read the post body inside an authorization handler and bind the value yourself, which might be an acceptable workaround. I've written [an answer here]().

If there's a way to call model binder manually, that would be an even better solution.

**Comment by blowdart** [comment]
This was a deliberate design choice, model binding happens after auth because model binding can have side effects. Despite best practice being view models folks do bind to entity framework classes, or other classes which have side effects. The safe way to do it is via [imperative auth](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-5.0#use-imperative-authorization), rather than declarative.
