### ISSUE TITLE
LSP platform can flood Razor tooling with semantic token requests.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#35396]
When debugging through some larger apps I found that the platform's flow is:

- Range x12
- Full
- Rangex5
- Edit

Which Razor translates into:

- Full x18
- Edit

Ultimately this has huge perf implications where we're not only spamming C# with a ton of CPU bound work but we're also clogging our request queues.

We could potentially address this on the Razor front but ideally the platform would behave better and not flood us (marking this as external because of that).

**Comment by gundermanc** [comment]
> ideally the platform would behave better and not flood us

This is by design behavior in the LSP specification.

When I originally wrote the VS IDE version of the LSP client in May 2020, Dirk shared this clarification via email:

> The only request that is mandatory to make semantic coloring work is the full request. This ensure flicker free scrolling and coloring of the minimap. Everything else (range based and delta) is necessary for optimizations either on the wire or when opening a file.

> Range request: This request is an optimization for when the user opens a file to only compute the tokens for the given viewport to reduce the time necessary to color the viewport correctly. 

If your provider indicates that it supports the _range_ provider, you are telling the platform that you can compute ranges faster than the whole document.. and by extension.. that you are capable of parsing subsets of the document text independently of the full document parse. We use this 'knowledge' to request ranges for the viewport while waiting for the first full request to complete.

The advantage of supporting range requests is that it can enable you to more quickly colorize the viewport, particularly in cases like Go to definition, where the user might jump to the middle of a huge file, only glance at the viewport a moment, and then jump somewhere else.

Since your parser seems to parse the full document, even for range requests, I'd recommend just dropping range requests since they aren't really giving you any benefit.

In the future, if you want to support range requests, you could do so via lexical colorization (colorize tokens in the visible lines instead of full semantic colorization of the document in context via parsing).

That said, I agree this behavior is non-obvious (hence the email thread :D), perhaps it's worth filing an issue on the LSP repo to add a clarification to the spec.

**Comment by gundermanc** [comment]
FWIW, InitializeAsync() in the LSP client seems like a pretty concise explanation: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FTagger%2FSemanticTokensHybridClassificationTagger.cs&version=GBdevelop&line=193&lineEnd=228&lineStartColumn=1&lineEndColumn=10&lineStyle=plain&_a=contents

**Comment by ryanbrandenburg** [comment]
Testing this locally the gains for a small app were relatively small, it was ~8.5 seconds with range requests and ~8.25 seconds without the range request.

However for a LARGE app (and a LARGE document) not using range requests took our Time-To-Full-Color from 1-2 minutes to 35-39 seconds. Obviously ~30 seconds is still too long, but knocking 30seconds-1.5minutes off is a great win that we can take for mostly no cost.
