### ISSUE TITLE
Is Blazor Server an Option in MAUI Project ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#35440]
The current Template in VS 2022 Preview 3 for MAUI Blazor only has Option to create **Blazor Web Assembly**.

Will there be Options to use **Blazor Server** or even **Blazor Hosted WebAssembly** with MAUI Projects ?

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Short answer no, it's not something we plan to ship or have explicit support for. 

Slightly longer answer, you can run anything you want in a WebView, so you can connect to a page that renders a blazor server app or a blazor webassembly app from within a WebView2 control and that should work.

**Comment by Eilon** [comment]
Hi @nssidhu , Blazor Desktop is a separate concept from Blazor Web Assembly and Blazor Server and not directly related to either one. I did a video called [How does Blazor Desktop run your app's code?](https://www.youtube.com/watch?v=oNxUfPoAXac) that explains how it runs.

As such, there won't be an option for Server vs. WebAssembly vs. Hosted WebAssembly in Blazor Desktop because neither of them are ever used.
