### ISSUE TITLE
Add BatchSize to W3CLoggerOptions

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#35545]
## Background and Motivation
`Logging.AzureAppServices` has the same behavior and has a option for `BatchSize` for writing to file. 
https://github.com/dotnet/aspnetcore/blob/d2421adbc9b7472df187ffdc71374cd4b253508e/src/Logging.AzureAppServices/src/BatchingLoggerProvider.cs#L88-L94

Is the same option also useful for W3C Log?
https://github.com/dotnet/aspnetcore/blob/d2421adbc9b7472df187ffdc71374cd4b253508e/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L123-L126

## Proposed API
```diff
namespace Microsoft.AspNetCore.HttpLogging
{
    public sealed class W3CLoggerOptions
    {
+       public int? BatchSize { get; set; }
    }
}
```

**Comment by Kahbazi** [comment]
This issue didn't get any area label! pinging @Pilchie @javiercn so the issue won't get lost. :slightly_smiling_face:

**Comment by Pilchie** [comment]
Thanks for pinging me - added the tag.

**Comment by javiercn** [comment]
I sometimes have bugs 😄

**Comment by wtgodbe** [comment]
We decided not to use `BatchSize` for W3C since it would be trying to solve the problem of request/response pairs coming in faster than we could log them, which seemed unlikely (CC @halter73 who I remember having an opinion on this during design review). Closing this for now as I don't think there's any action to take.

**Comment by halter73** [comment]
I agree this makes sense to close. If a BatchSize ends up being important for some scenario we could consider hard-coding one. For it to a problem not to have one, logs would have to be generated faster than they can be taken from a blocking collection and appended to a list. Even in thread-starved scenarios this seems unlikely to happen for long, especially since the blocking collection should prevent the source of logs from growing too large when the async file writing or flush interval.
