### ISSUE TITLE
Uint8Array created by byte[] deserialization in javascript has incorrect buffer property byteLength

### ISSUE THREAD

**Issue by LostBeard** [dotnet/aspnetcore#35597]
### Describe the bug
- When passing byte arrays from Blazor to Javascript the resulting Uint8Array's buffer property (an ArrayBuffer) has an incorrect ,and MUCH larger, byte length. The Uint8Array has a correct byteLength.

- A Blazor byte[2], byte[10], byte[100], or even byte[1000] results in a Uint8Array.buffer.byteLength == 62128128. 
- A byte[62128128] results in Uint8Array.buffer.byteLength == 118358016. 

### To Reproduce
- Call the below Javascript function from Blazor with a valid byte[] as the first argument.

function uint8arrayTest(arg0) {
    console.log('Uint8Array.byteLength', arg0.byteLength);
    console.log('Uint8Array.buffer.byteLength', arg0.buffer.byteLength);
    console.log('Uint8Array.byteLength == Uint8Array.buffer.byteLength', arg0.byteLength == arg0.buffer.byteLength);
}

### Example using above
- In Blazor (js is IJSRuntime):
js.InvokeVoidAsync("uint8arrayTest", new byte[] { 1, 3, 5  });

- Browser console output:
Uint8Array.byteLength 3
Uint8Array.buffer.byteLength 62128128
Uint8Array.byteLength == Uint8Array.buffer.byteLength false

### Exceptions (if any)
None

### Further technical details

- ASP.NET Core version
6.0.0-preview.7.21377.19

- Include the output of `dotnet --info`

Microsoft Windows [Version 10.0.19042.1110]
(c) Microsoft Corporation. All rights reserved.

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1

Edit: Uploaded simple example project repo. 
[https://github.com/LostBeard/Uint8ArrayCheck](https://github.com/LostBeard/Uint8ArrayCheck)

**Comment by TanayParikh** [comment]
After investigating this, I'm labeling this as "expected behavior" / by design due to the way the framework & underlying `Uint8Array`/`ArrayBuffer`s work in JS. 

# Investigation
> Notes for those who may be interested in this subject matter:

This behavior presents itself in both Blazor Server & WASM. The `buffer.byteLength` is `32` in server in comparison to `62128128` mentioned for WASM.

The discrepancy between `Uint8Array.byteLength` and `Uint8Array.buffer.byteLength` is a result of how `Uint8Array`/`ArrayBuffer`s work. Generally we get the final `Uint8Array` by taking a "subarray" from the `ArrayBuffer` source. In other words the `Uint8Array` and `Uint8Array.buffer` represent two different logical buffers, and hence their `byteLength`s are appropriately different. The `ArrayBuffer` source differs from Server & WASM and hence the discrepancy between the two `buffer.byteLength`s. 

## Blazor Server
- Messages are received via SignalR.
- The `32` bytes we see as the `byteLength` represents the underlying array buffer used to represent the whole message (that we receive [here](https://github.com/dotnet/aspnetcore/blob/f6452bf1f7750da319f2eccdc911ee481f7e15c7/src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts#L72-L94)). This is in turn decoded [here](https://github.com/dotnet/aspnetcore/blob/f6452bf1f7750da319f2eccdc911ee481f7e15c7/src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts#L125). From that we have the invocation properties (like method name `JS.ReceiveByteArray`, params, and other metadata which allows the framework to function appropriately). 
- Looking at the `byteOffset` we can see it matches the expected params with relation to the underlying SignalR message buffer:

![image](https://user-images.githubusercontent.com/14852843/130684445-283841b6-1574-47a9-9a36-a389660a376d.png)

## Blazor WASM
- We receive the byte array via marshalled interop from the heap (not SignalR). This is done [here](https://github.com/dotnet/aspnetcore/blob/f6452bf1f7750da319f2eccdc911ee481f7e15c7/src/Components/Web.JS/src/Boot.WebAssembly.ts#L181).
- We then get the `Uint8Array` (sub)-array from the heap [using mono](https://github.com/dotnet/aspnetcore/blob/f6452bf1f7750da319f2eccdc911ee481f7e15c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68-L74)
- Hence the `62128128` represents the mono total heap `ArrayBuffer`
![image](https://user-images.githubusercontent.com/14852843/130685750-49e093b5-5075-4722-a4bd-d13beb7783ac.png)
- Like we did for Blazor server, we can see the `Uint8Array.byteOffset` matches the expected params.
![image](https://user-images.githubusercontent.com/14852843/130685072-3e9f80f7-cf90-4db7-bc0b-f0a5b9e09e8c.png)
![image](https://user-images.githubusercontent.com/14852843/130685029-5024bc72-f02e-47e9-99e5-5f48a5c6795c.png)

**Comment by LostBeard** [comment]
Those incorrectly formed Uint8Arrays created by Blazor WASM cannot be [Transferred](https://developer.mozilla.org/en-US/docs/Web/API/Transferable)  to WebWorkers. That is how I found the problem in the first place. Trying to transfer a byte[] to a WebWorker. My custom implementation of byte[] serialization/deserialization works. Yours does not. If not working is expected behavior than close it I guess.  :/

**Comment by LostBeard** [comment]
Simple fix. Change:

starting at line 179 in Boot.WebAssembly.ts

function receiveByteArray(id: System_Int, data: System_Array<System_Byte>): void {
const idLong = id as any as number;
&nbsp;&nbsp;const dataByteArray = monoPlatform.toUint8Array(data);
&nbsp;&nbsp;DotNet.jsCallDispatcher.receiveByteArray(idLong, dataByteArray);
}

To:

function receiveByteArray(id: System_Int, data: System_Array<System_Byte>): void {
&nbsp;&nbsp;const idLong = id as any as number;
&nbsp;&nbsp;const dataByteArray = new Uint8Array(monoPlatform.toUint8Array(data));
&nbsp;&nbsp;DotNet.jsCallDispatcher.receiveByteArray(idLong, dataByteArray);
}

**Comment by LostBeard** [comment]
Without this fix anyone trying to call postMessage to a WebWorker (ServiceWorker, Worker, etc) and transfer a Uint8Array will fail. Or they will have to add their own javascript to fix Blazor Uint8Arrays before passing them on via postMessage.

**Comment by TanayParikh** [comment]
> wrap it in a "new Uint8Array()".

That is essentially performing a full clone of the underlying buffer data within the `Uint8Array`. Doing this by default every-time we're doing interop would be very costly and should be avoided if at all possible. If your use case demands `Uint8Array.byteLength == Uint8Array.buffer.byteLength` then that may be a potential solution (alongside `slice`). 

![image](https://user-images.githubusercontent.com/14852843/130698963-83dafc05-4697-4455-8132-ed425a52f83c.png)

**Comment by LostBeard** [comment]
That all makes sense. Thank you for taking the time to explain that all and including the links. 

According to your link in [MonoPlatform.ts](https://github.com/dotnet/aspnetcore/blob/f6452bf1f7750da319f2eccdc911ee481f7e15c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68), toUint8Array is using "new Uint8Array(length)" which creates a new ArrayBuffer of size length and then uint8Array.set(Module.HEAPU8.subarray(...)) which copies the data off of the heap and into the newly created uint8array... So we shouldn't be recieving a Uint8Array with an underlying ArrayBuffer tied to the mono heap. And the Uint8Array byteLength would match the buffer.byteLength. Am I missing something?

toUint8Array: function toUint8Array(array: System_Array<any>): Uint8Array {
&nbsp;const dataPtr = getArrayDataPointer(array);
&nbsp;const length = getValueI32(dataPtr);
&nbsp;const uint8Array = new Uint8Array(length);
&nbsp;uint8Array.set(Module.HEAPU8.subarray(dataPtr + 4, dataPtr + 4 + length));
&nbsp;return uint8Array;
},

This is the code that I think is actually running in .Net 6 preview 7. This code below would explain why the underlying buffer is the way it is. 

toUint8Array: function toUint8Array(array: System_Array<any>): Uint8Array {
&nbsp;const dataPtr = getArrayDataPointer(array);
&nbsp;const length = getValueI32(dataPtr);
&nbsp;return Module.HEAPU8.subarray(dataPtr + 4, dataPtr + 4 + length);
},

**Comment by LostBeard** [comment]
Looks like it has already been fixed. That explains my confusion on the linked code. Mono will create a new Uint8Array and copy the data off the heap into it which will fix my issue. [The commit was July 22](https://github.com/dotnet/aspnetcore/commit/0610031dc58512bd71f55bcbdd1f06656b753929#diff-a5167572a221c4bbe4fa36e4e110b39011b6e8f547ce0ab8bdd204f55201f1c0). 


Any idea if it will make it into .Net 6 final?

**Comment by TanayParikh** [comment]
Yes it'll be in the next release .NET 6 RC1

**Comment by LostBeard** [comment]
Thank you for your help.
