### ISSUE TITLE
Send FLoC opt-out header by default

### ISSUE THREAD

**Issue by ArthurHNL** [dotnet/aspnetcore#35921]
### Is your feature request related to a problem? Please describe.
Google is developing and pushing out a new standard for web tracking called FLoC with the intent to replace third-party cookies. TLDR: it allows a profile based on the web history of the user to be retrieved using a Javascript API in the frontend of web-applications. If you do not want your website to be included in this tracking profile, you have to include the following HTTP response header inside all of your HTTP responses:

```txt
Permissions-Policy: interest-cohort=()
```

### Describe the solution you'd like
Since tracking should always be opt-in, especially when you have to make that choice for your users and you probably do not have your users consent to be tracked at the first web request of the user, I would like ASP.NET Core applications to send the opt-out header by default.

### Additional context
The FLoC spec can be found here: https://github.com/WICG/floc#opting-out-of-computation. The EFF has an article where it expresses concern about this standard here: https://www.eff.org/nl/deeplinks/2021/03/googles-floc-terrible-idea. Google is already trying this out in the field.

I would like to see this feature in all supported versions of ASP.NET core and enabled by default, since ASP.NET core applications never tracked users by default and thus not including this header would introduce a breaking change in the sense that users of applications that previously did not track them will now start to get tracked.

**Comment by davidfowl** [comment]
The bar for anything being a default header is extremely high and this doesn’t meet the bar. Maybe it’s something that could be in the razor pages/mvc template (like cookie policy was) but even then, this feels like a stretch.

just my 2c

**Comment by blowdart** [comment]
As @davidfowl says. It's the same reason we don't add CSP or X-Frame-Options or anything else of that ilk. While you may feel that floc opt-out is a more secure option, others with disagree, and as a framework we're not talking a stance on this. Nor will we add headers for a trial feature that may change often.

As an aside google [rolled back the idea of floc for now](https://blog.google/products/chrome/updated-timeline-privacy-sandbox-milestones/), due to the wider industry reaction.
