### ISSUE TITLE
How to use Html.DisplayFor correctly ?

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/aspnetcore#35991]
```
Exception thrown: 'System.NullReferenceException' in Microsoft.AspNetCore.Mvc.ViewFeatures.dll
Object reference not set to an instance of an object.
```

code: 
```
....
@foreach (var item in Model)
{
<td>
@Html.DisplayFor(modelItem => item.Employee.Name) <-- is Null 
</td>
...
```

Asp core 3.1

**Comment by javiercn** [comment]
@EvgenyPrikhodko thanks for contacting us.

I don't think DisplayFor and other helpers will noop when there is a null value. However in this case its likely that a null-reference exception happens when we try to evaluate the expression. I would suggest you try with the null conditional operator `?.` or that you check for null before calling DisplayFor

....
@foreach (var item in Model)
{
<td>
@Html.DisplayFor(modelItem => item.Employee.Name) <-- is Null 
</td>
...

**Comment by EvgenyPrikhodko** [comment]
![image](https://user-images.githubusercontent.com/25795145/131683012-000a4617-60e6-4251-9add-9ed1dedee453.png)

**Comment by javiercn** [comment]
@EvgenyPrikhodko then you need to check for null outside of the `Html.DisplayFor`

**Comment by EvgenyPrikhodko** [comment]
Why can't you use "?"

**Comment by javiercn** [comment]
@EvgenyPrikhodko likely a C# limitation since DisplayFor uses `System.Linq.Expressions` and the C# compiler might not be able to translate the expression

**Comment by EvgenyPrikhodko** [comment]
Can register a wish?

**Comment by javiercn** [comment]
@EvgenyPrikhodko it's not something we control in this repo, I think you'll have to go to `dotnet/roslyn` for that.

It's likely that there is an issue for it already, I'm sure the team has already considered this, however its likely very hard to do due to the fact that it requires adding new types/nodes to the runtime likely makes it hard.
