### ISSUE TITLE
Blazor webassembly AuthorizeView component is very slow on page loading

### ISSUE THREAD

**Issue by bsweb** [dotnet/aspnetcore#36139]
We are finding that the AuthorizeView is very slow on page load. It adds 2-3 seconds of a blank page to the loading.

If we just load the same razor view without authentication then it is almost instant.

![image](https://user-images.githubusercontent.com/4737211/132000802-1b977f0c-c9da-4280-be97-0b24fdb012d9.png)

Using Azure AD B2C and .Net 5

I believe these are similar issues that have been reported:
https://github.com/dotnet/aspnetcore/issues/22633
https://github.com/dotnet/aspnetcore/issues/31926

**Comment by javiercn** [comment]
@bsweb the authorization component needs to do several network calls to retrieve configuration and check the authentication state for the user, including DNS resolution and TLS negotiation. Those normally can take up to several seconds each depending on your network configuration.

You can try to speed these up by using link tags on the head of the document to preload and preconnect to some of those origins. Otherwise there's not really much we can do about it.

Moving this to the backlog in case we want to try and see if there is any optimization we can make in the future.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
