### ISSUE TITLE
Blazor - RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#36135]
This issue is related to #35530. Basically I implemented what's suggested in the link you mentioned @pranavkm. See the logs for the error. My expectations are to make the browser download the file independently from the app. Right now the app is frozen until streaming is completed. [localhost-1630644851435.log](https://github.com/dotnet/aspnetcore/files/7103407/localhost-1630644851435.log)

I'm using .NET 6 Preview 7, since base64 encoding is no longer required when calling JSInterop.

### API
```<!-- language: c# -->
public async Task<ActionResult> GetFileData([FromBody] Foo dto)
{
    // some logic here

    _ = new FileExtensionContentTypeProvider().TryGetContentType(dto.FileFullName, out string contentType);
    Response.Headers.ContentType = contentType ?? MediaTypeNames.Application.Octet;
    return File(result, contentType ?? MediaTypeNames.Application.Octet, xfRequest.FileFullName);
}
```
### Component.razor
```
    var content = await responseMessage.Content.ReadAsByteArrayAsync();
    await JS.InvokeVoidAsync("download", fileName, content, "text/plain");
```
### index.js
```
function download(fileName, data, blobType) {
    var blob = new Blob([data], { type: blobType });
    var url = URL.createObjectURL(blob);

    var link = document.createElement('a');
    link.download = fileName ?? '';
    link.href = url;
    link.target = "_top";
    document.body.appendChild(link); // Needed for Firefox
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
```

**Comment by SteveSandersonMS** [comment]
While what you're doing here will work, it's pretty inefficient to load the whole file from JS memory (as the `fetch` reponse) into .NET memory (when you call `ReadAsByteArrayAsync`) only to then transfer it back into JS memory. For large enough files, that will make the browser hang for a while.

Two approaches I would recommend instead:

 * (Simplest) Instead of loading the data using `HttpClient` on the .NET side, you could more directly use `fetch` to get the data inside your JS function `download`, for example by passing it the URL from .NET instead of the file contents. Then it can directly construct the blob from the response.
 * (More sophisticated) If you do want to load it via .NET, you could avoid using `ReadAsByteArrayAsync`, and instead keep it purely as a `Stream` on the .NET side. That is, on the .NET side, wrap the `responseMessage.Content` in `new DotNetStreamReference(...)`, and then pass the `DotNetStreamReference` instance to JS code. This will let the JS-side code receive it as a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) which you can then use without allocating any large buffers on the .NET side.

**Comment by ylr-research** [comment]
@SteveSandersonMS where does `DotNetStreamReference` class live? I cannot find it anywhere.

**Comment by SteveSandersonMS** [comment]
https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop/src/DotNetStreamReference.cs

**Comment by SteveSandersonMS** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript

**Comment by ylr-research** [comment]
Thanks @SteveSandersonMS
