### ISSUE TITLE
InstallVisualStudio.ps1 pulls wrong Windows SDK version

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#36165]
I believe the `InstallVisualStudio.ps1` file is supposed to bring all required components to be able to build the solution.
However when I tried to run the quarantined tests it failed with a missing Windows SDK, and wanted `10.0.18362.0` whereas the script installed `10.0.17134.0`.

I ran `& ./eng/build.ps1 -CI -nobl -all -pack -NoBuildJava` to get the error

**Comment by AraHaan** [comment]
I would rather have ASP.NET Core depend on 10.0.22000.0 where that is that latest version of the Windows SDK.

Why? Because developers like me install and use only the very latest version of the Windows SDKs and uninstall the older ones to make room for other stuff (since they are about 2~3 GB each.

It could also help out on InstallVisualStudio.ps1 as well.

What do you think @mkArtakMSFT?

**Comment by AraHaan** [comment]
Alright going to open pull request to try to close this issue (Note: For dev16 and dev17 it will require the 10.0.22000.0 windows sdk).

If that SDK is not available on the dev16 feeds, you should still be able to access it from Dev17 at least to install it. Besides I think Dev17 at this point is required for the main branch anyway (or at least I use it with that).

**Comment by AraHaan** [comment]
Sad news, the CI on the Windows x86/x64/arm64 and the Windows Server images seems to not have 10.0.22000.0 installed on the Windows SDK so the change (that should hopefully resolve this issue) is currently blocked.
