### ISSUE TITLE
Access Modifiers

### ISSUE THREAD

**Issue by dartemage** [dotnet/aspnetcore#36196]
I would like to know why there are so many internal / private classes in an open source project. 

Let's say I want to affect rendering in Blazor, but in order to do it painlessly (through reflection), I need to compile the entire solution myself, just to change a couple of lines of code. Is there a chance that you will get rid of this approach in your code?

**Comment by davidfowl** [comment]
Because we ship public API as the product. Public API needs to be supported and we avoid making breaking changes where possible. As a result, we're [intentional](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md) about *every single piece of public API* we ship. We don't make things public without a thorough review of the APIs and extensibility around them.
