### ISSUE TITLE
AuthenticationMiddleware should probably try all Schemes not just the default one.

### ISSUE THREAD

**Issue by EraYaN** [dotnet/aspnetcore#36278]
### Is your feature request related to a problem? Please describe.

I am trying to access the `HttpContext.User` item in the Middleware pipeline after the `AuthenticationMiddleware`, and the behavior is different depending on the scheme used (so for us on the issuer of the JWT token). Which seems like a weird design choice. Especially since one would expect if one uses say two calls to `AddMicrosoftIdentityWebApi` with unique scheme names to add both Azure AD from one tenant and Azure AD B2C for another, that either token source would populate the User in the `HttpContext`.

### Describe the solution you'd like

So for now we added a Middleware right after the default authentication middleware that has this in it's invoke Method. But this is a work-around, we were wondering mostly as to WHY it only tries the default. To me it seems like unexpected behavior.I'd like to see this kind of behavior in the default middleware.

```cs
// If the default one already worked we don't need to try anything.
if (context.User.Identity?.IsAuthenticated != true)
{
    foreach (var scheme in await Schemes.GetAllSchemesAsync())
    {
        var result = await context.AuthenticateAsync(scheme.Name);
        if (result?.Principal != null)
        {
            context.User = result.Principal;
            if (context.User.Identity?.IsAuthenticated == true)
            {
                break; // bail on first one that works.
            }
        }
    }
}

await _next(context);
```

### Additional context
This was mostly so I could properly authenticate a SwaggerGen endpoint (the actual swagger.json or .yaml) since all of that happens before the Routing Middlewares and thus before Authorization.

**Comment by blowdart** [comment]
Because that's what the default is there for. It runs on everything. There are ways to switch it out, or add additional schemes in policy or attributes. 

Auth can have side effects, by only running the default one, we hopefully control unexpected surprises from other auth schemes/types. Heck, some folks have custom auth that just checks IP addresses for some reason, and that's their default, and they don't even build a user from it.

So, because it's safer in terms of side effects and expectations. It would be a huge breaking change to try everything, and it's not one we'd be willing to make, given you can change the default policy yourself to do it.

**Comment by EraYaN** [comment]
Aah right, thing is just changing the default doesn't really work for us, because we use multiple at the same time. We will continue running a secondary middleware. Thanks for the quick response.

**Comment by Kahbazi** [comment]
@EraYaN I guess you could add a default scheme which its handler will check all other scheme and return the first success authentication ticket. This way you won't need the secondary middleware.
