### ISSUE TITLE
couldn`t compile asp.net core 6.0 rc1

### ISSUE THREAD

**Issue by RoyalForeverBest** [dotnet/aspnetcore#36432]
I can`t  compile asp.net core, it report an error:

```
Failed to install dotnet from public location.
E:\NetSourceCode\aspnetcore\eng\build.ps1 : The variable '$LASTEXITCODE' cannot be retrieved because it has not been se
t.
At line:1 char:126
+ ... ulture = '';& 'E:\NetSourceCode\aspnetcore\\eng\build.ps1' -all -nobu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (LASTEXITCODE:String) [build.ps1], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,build.ps1

source code version: release/6.0-rc1
```

**Comment by RoyalForeverBest** [comment]
my environment is Visual Studio 2022 community

**Comment by dougbu** [comment]
The release/6.0-rc1 branch no longer exists but we do have occasional issues missing .version files which the installation scripts use to find stable-versioned installers. The problem should have been resolved since you opened this issue. Please reopen this if you are still having trouble, especially with current branches such as release/6.0 or main,
