### ISSUE TITLE
SupplyParameterFromQueryAttribute is long-winded and verbose

### ISSUE THREAD

**Issue by conficient** [dotnet/aspnetcore#36494]
## Background and Motivation

The new `SupplyParameterFromQueryAttribute` in .NET 6 is a very long and overly-descriptive name for an attribute. 
```c#
[SupplyParameterFromQuery] public Foo { get; set; }
```
The API should err toward a terser syntax where practical, as eases code reading and makes it easier for non-English-speaking coders to scan and understand as well.

Looking at similar attributes in Razor components we find `[Parameter]` and `[CascadingParameter]`. If we were to follow the same convention we could argue that `[Parameter]` should be `[SupplyParameterFromParentComponent]`! 

The "Supply" part is implied by the nature of it being a parameter, and the "From" is redundant.

## Proposed API

Not sure why it wasn't selected but a plain `[QueryParameter]` seems to be much simpler and equally valid alternative. It has two elements: `Parameter` tells us this is a parameter property, and `Query` tells us it comes from the query string.
```c#
[QueryParameter] public string Foo { get; set; }
```

## Usage Examples

```C#
  // url is "/customer?find=x&type=ltd&active=true
 [QueryParameter] public string Find { get; set; }
 [QueryParameter] public CustomerTypes Type { get; set; }
 [QueryParameter] public bool Active { get; set; }
```

## Alternative Designs

The origin of the name appears to be https://github.com/dotnet/aspnetcore/issues/34115 and there seems to have been no discussion of the name proposed originally, and it was picked 'by default'.

## Risks

This would be a breaking change unless a second attribute with the alternative name is added.

**Comment by pranavkm** [comment]
Thank you for your API suggestion. Unfortunately we're well past the point of making API changes for 6.0 and any changes here for 7.0 would be considered a breaking change as you noted in your Risks. It's also unlikely that we would consider a different attribute simply because the first one is verbose.

A fairly trivial workaround would be to add an alias to this in your `_Imports.razor ` (where it only applies to .razor files) or to your `Program.cs` where it applies to every file in your project.

```C#
// Program.cs
global using QueryParameter = Microsoft.AspNetCore.Components.SupplyParameterFromQueryAttribute;
```

**Comment by conficient** [comment]
Nice suggestion, @pranavkm  - thanks
