### ISSUE TITLE
NET 6 RC1 Blazor Wasm SignalR WebSockets authentication fails.

### ISSUE THREAD

**Issue by gdar91** [dotnet/aspnetcore#36541]
After updating to NET6 RC1, WebSockets protocol can no longer be used for SignalR in BlazorWasm projects, that require JWT authentication. An error appears in the console, saying:

_WebSocket connection to 'wss://localhost:7133/my-hub?id=p6I2kK4zlOd5kQOeSsPoTA&access_token=***' failed: HTTP Authentication failed; no valid credentials available
dotnet.6.0.0-rc.1.21451.13.js:1_

Then it falls back to long polling.

To reproduce, just create a new blazor-wasm hosted project with individual authentication. Add SignalR and a hub with authorization attribute in the server project. Add SignalR client and set an AccessTokenProvider using the IAccessTokenProvider.

**Comment by BrennanConroy** [comment]
> After updating to NET6 RC1, WebSockets protocol can no longer be used for SignalR in BlazorWasm projects, that require JWT authentication.

I'm not sure what you mean here, the behavior isn't different between 5.0 and 6.0. Your issue is likely because you aren't grabbing the access token out of the query string which is where it will be when using websockets from the browser. Look at the docs for info on how to do it.
https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#identity-server-jwt-authentication
