### ISSUE TITLE
Default editor colors let TextMate shine through

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#36614]
Looks like there's a few locations in which C# and us don't provide semantic classifications for the document (it relies on the default editor colors); this ends up showing TextMate colors in unexpected locations. For instance:
![image](https://user-images.githubusercontent.com/2008729/133671790-1c7be7ae-4a5b-4786-8618-96bc97b5e783.png)

`@RequestsMenuItems`, `@(ShowRequests`, `.Vertical` etc. are miss colored.

We may need to re-lobotimize our TextMate theming for attributes 😢

**Comment by ryanbrandenburg** [comment]
Good catch. This is because Roslyn [does not define a color for `property name`](https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2019.xml#L64-L65) and a few other classifications. They default to the standard color for the Theme, which is "black" for the Light Theme. BUT because the classification didn't apply anything the HTML Classification value is allowed to shine through.

There are two possible solutions here:
1. LSP Tagger respects "Classifications without Coloration" and lets them set the default text value for the theme in that case.
2. Roslyn populates those values. I THINK they could still achieve their current behavior (defaulting to the theme default) using `Type="CT_SYSCOLOR" Source="00000008"`, but I think there's also an argument to be made fore explicitly setting the value to black since end-users have no way of knowing what classifications will just default due to empty classifications.

**Comment by ryanbrandenburg** [comment]
Talked with @gundermanc offline, we both think that 2 is the preferable fix here. @JoeRobich is that acceptable to Roslyn?

**Comment by JoeRobich** [comment]
Roslyn [lists the Identifier classification as the BaseDefinition](https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/Implementation/Classification/ClassificationTypeDefinitions.cs#L153) for our more specific identifier classifications. This allows a single change to the Identifier color to be reflected in all the classifications that do not have special colorization. By setting the foreground for all of our specific Identifier classifications it would be harder for users to configure and would certainly break existing user themes.

**Comment by ryanbrandenburg** [comment]
Here's what the offending area looks like under Carnation:
![image](https://user-images.githubusercontent.com/14987221/134071820-8995a38f-951c-44d7-8fdc-8965ca4177a0.png)
The pure "Plain Text" scenario lists no classification at all.
