### ISSUE TITLE
Race condition with component using @ref for cascading value to another component ?

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#36693]
I'm not sure if this is a bug or I'm doing something inherently bad.

I have a page with 2 sections, one with Tab component (basically links with some content) and another component that gets updated with the content of tab when a user click on them.
Normally this components are one inside the other, but for structural/html reasons, I need to have them separated so in my first try I passed the component via `[Parameter]` and to DRY I switched to `CascadingParameter` so I can define it once and all tabs get's the same "parent".

```
@code {
    public TabPlaceholder? tabPlaceholder { get; set; }
}
@if (tabPlaceholder is not null)
{
	<CascadingValue Value="@tabPlaceholder">
	    <Tab Text="Text 1">Something 1</Tab>
	    <Tab Text="Text 2">Something 2</Tab>
	    <Tab Text="Text 3">Something 3</Tab>
	    <Tab Text="Text 4">Something 4</Tab>
	</CascadingValue>
}
<div>
    <TabPlaceholder @ref="tabPlaceholder" />
</div>
```

Tab.razor:
```
[CascadingParameter] public TabPlaceholder? TabPlaceholder { get; set; }
[Parameter] public string? TabText { get; set; }
protected override void OnInitialized()
{
	if (TabPlaceholder is null)
	{
		throw new ArgumentException(nameof(TabPlaceholder));
	}
	TabPlaceholder.AddTab(this);
}
```

The issue I'm getting is a race condition where sometimes the component is not render (and tabPlaceholder is null).
Tried using `if not null` without success.

Is this by design? and if it is, what would be the proper way to make it work ?
Tried to call `StateHasChanged` on lifecycle events but I cannot get it to work as expected (to always render)

Since the error happends as what it looks like as a race condition, is not reproducible 100% of the times. [I can put a repo showcasing the problem if needed]

**Comment by javiercn** [comment]
@Bartmax thanks for contacting us.

I think what you are doing is `inherently` wrong and won't produce the results you expect. You should only rely on the values captured by `@ref` within `OnAfterRenderAsync` in any other situation, the value might not be correct. In your case:

Within on first render, tabPlaceholder will be null until (aproximately) `<TabPlaceholder @ref="tabPlaceholder" />` has executed. On subsequent renders, `@if (tabPlaceholder is not null)` at that point it will hold the value for the previous render.

All we do with Razor syntax is "transform" existing code, and as part of that, it has to respect the order in which the instructions were originally emitted, otherwise you would end with really hard to debug bugs.

The way I would approach this would be to introduce a separate model object that gets initialized in the beginning and passed down to the tabs and the content. Tabs register themselves in this model, and the content uses the results from that. That way you don't have to wait for the `ref` to be captured and overall things are "simpler"
