### ISSUE TITLE
Azure stdoutLogFile default value causes startup failure 500.31 ANCM Failed to Find Native Dependencies

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/aspnetcore#36749]
This issue was reported in May 2020 and closed as fixed (https://github.com/dotnet/aspnetcore/issues/21498 ) but I'm still seeing it today.

Is that fix not live yet? How will we be able to tell when it's live?

And how do we control what path ends up in the deployed web.config file? In some of our app services it is set to the correct value (`"\\?\%home%\LogFiles\stdout"`) and in others it is still the value that gets set locally (".\logs\stdout")

**Comment by BrennanConroy** [comment]
> Is that fix not live yet? How will we be able to tell when it's live?

It's an Azure App Service issue and they don't track released fixes like we do, if you want to try and get a specific date you can ask on https://github.com/projectkudu/kudu or try going through Azure support.

> And how do we control what path ends up in the deployed web.config file? In some of our app services it is set to the correct value (`"\\?\%home%\LogFiles\stdout"`) and in others it is still the value that gets set locally (".\logs\stdout")

If you have a web.config in your publish output then that's the path that will be used, otherwise the default will be used when we generate a web.config for you.
