### ISSUE TITLE
Blazor "datetime-local", cannot input value into the browser.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36767]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-datetime-local-cannot-input-va/1521964)._

---
[severity:It's more difficult to complete my work]
Unable to input any value into the browser when the value of and html input of type "datetime-local" is bound.
I.e.
`<input type="datetime-local" @bind-value="@Model.FromDate"/>`

Other date/datetime inputs work Ok.

Have tried it in two browsers. Brave and Edge. Both exhibiting the exact same problem.

---
#### Feedback Bot on 9/5/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're unable to reproduce the issue. Please share a minimal repro project hosted in GitHub, so that we can investigate this.
Also, please clarify what are you referring to by "unable to input"? What are the specific actions that you're taking in the browser that do not work as expected?
