### ISSUE TITLE
SupplyParameterFromQuery doesn't work in non-routable components

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#36966]
### Describe the bug
I was expecting parameters marked with the `SupplyParameterFromQuery` attribute would work regardless of whether they were routable components or not. However, if I add the attribute to a component and add that to a page that receives the query string, the parameters on the child component are not set. 

### To Reproduce
Using the stardard Blazor WebAssembly template, update the Index.razor file to the following code:

```razor
@page "/"
@inject NavigationManager NavManager

<PageTitle>Index</PageTitle>

<SurveyPrompt />

<button @onclick="Navigate">Click me</button>

@code {
    private void Navigate()
    {
        var uriWithQuerystring = NavManager.GetUriWithQueryParameter(nameof(SurveyPrompt.Testing), "foo");

        NavManager.NavigateTo(uriWithQuerystring);
    }
}
```

Then update the SurveyPrompt.razor to the following code:

```razor
<div class="alert alert-secondary mt-4">
    @Testing
</div>

@code {
    [Parameter, SupplyParameterFromQuery]
    public string? Testing { get; set; }

    protected override void OnParametersSet()
    {
        Console.WriteLine($"The value of Testing is {Testing}");
    }
}
```

Notice when clicking the button on the Index component, the value is never rendered in the SurveyPrompt component. When checking the console, the OnParametersSet method isn't being called as no additional messages are written to the console.

### Exceptions (if any)
Any component can have it's parameters hydrated from a query string when using the SupplyParameterFromQuery attribute.

### Further technical details
- ASP.NET Core version: .NET 6 RC 1

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this, @chrissainty! This is currently by design, but I understand why it might feel less convenient in certain scenarios. I'll give some background for reference.

The reason we didn’t originally do this is that it subverts the top-down information flow and makes it unclear what order things will happen in. While it seems conceptually simple to do it at first glance, it would create more ordering confusion than cascading parameters already do.

When the URL changes, a deeply-nested component may then receive new parameters both through its immediate parent and through a direct subscription to the query parameter. This may or may not mean multiple re-renderings and in a hard-to-reason-about order depending on exactly how the ancestor components pass through the info. This might manifest as subtle bugs in application logic that assumes things happen in a single specific order.

Limiting it to passing directly to routed components avoids this because there’s only one component receiving a notification, and it remains in control over if/how to pass this to its descendants, either directly or indirectly by defining custom cascading parameters. Things are simplest to reason about if the info is only passed via regular parameters, not cascading ones, but of course developers are free to create cascading parameters and it might be straightforward in particular scenarios.

We're certainly open to changing this in the future if there's strong customer feedback, but it's not free of drawbacks.

**Comment by chrissainty** [comment]
Thanks for the background to the design decision, @SteveSandersonMS. This now makes perfact sense and I agree, it could cause more problems than it solves, attempting to do it the way I expected. 

I'm going to close this now as I think the current implementation makes the most sense.
