### ISSUE TITLE
The PageTitle component doesn't update the title when navigating directly to a page

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#36967]
### Describe the bug
When applying the `PageTitle` component to pages, the title is only updated when navigating from another page in the application, not when loading a page directly.

### To Reproduce
Using the standard Blazor WebAssembly template, load the application as normal and navigate from the Index page to the Counter page. Observe that the title is updated from the application name to "Counter" in the browser tab. 

Now open a new tab and load the counter page directly. Observe that the title in the browser tab is not updated to "Counter" but remains the name of the application.

### Further technical details
- ASP.NET Core version: .NET 6 RC 1

**Comment by SteveSandersonMS** [comment]
I wasn't able to repro this with 6.0 RC2. Navigating to `/counter` directly in a new browser tab does produce the expected behavior for me, i.e.,

 * Page title is `<ApplicationName>` before the WebAssembly app starts running (e.g., for 0.5 seconds)
 * Then it immediately changes to `Counter`

@chrissainty Are you still able to repro this on a current build? For example, try the RC2 or RTM daily builds at https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries. Thanks for reporting it!

**Comment by chrissainty** [comment]
I've installed .NET 6 RC2 (6.0.100-rc.2.21501.10) and everything works as expected! I've checked a new application as well as an existing one. Both work correctly.
