### ISSUE TITLE
Examine password hashing best practices and update as needed

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#37032]

**Comment by HaoK** [comment]
Moving to preview1 so we do this at the start of 7.0

**Comment by brockallen** [comment]
Anything of interest here?

**Comment by blowdart** [comment]
Lol define interest 😀

This will end up being re-examining identity's hashing and upping the hash count or maybe swapping out the function if we have something more modern.

**Comment by blowdart** [comment]
Unless Argon is in the CLR now we can't use it. We can't use 3rd party libraries, and we can't write our own.

**Comment by GrabYourPitchforks** [comment]
SDL bar check:

PBKDF2 is allowed with 100k+ rounds and HMACSHA512. (HMACSHA256 is allowed but discouraged.)
Argon2 / bcrypt / scrypt are allowed as long as you call a trusted implementation.

Since we're discussing server-side code, you want to be sensitive to the amount of work you're performing while processing login requests, since the expectation is that such requests will be frequent. Whether a 1-second delay (for instance) is acceptable would depend on the application type and the expected concurrent request load.

**Comment by slaneyrw** [comment]
> Unless Argon is in the CLR now we can't use it. We can't use 3rd party libraries, and we can't write our own.

Microsoft may not be able to use Argon2, but everyone else can.... except we have to wrap the Task calls because the PasswordHasher is synchronous.

We ended up replacing ALL the password invocations at the UserManager level with an async PasswordHasher version ( and yes we had to re-implement the **private** UpdatePasswordHash ).

**Comment by slaneyrw** [comment]
> SDL bar check:
> 
> PBKDF2 is allowed with 100k+ rounds and HMACSHA512. (HMACSHA256 is allowed but discouraged.) Argon2 / bcrypt / scrypt are allowed as long as you call a trusted implementation.
> 
> Since we're discussing server-side code, you want to be sensitive to the amount of work you're performing while processing login requests, since the expectation is that such requests will be frequent. Whether a 1-second delay (for instance) is acceptable would depend on the application type and the expected concurrent request load.

So are you going to add a "V4" password hasher to the Microsoft.AspNetCore.Identity library using HMACSHA512 ?

**Comment by GrabYourPitchforks** [comment]
Pinging on this. Because it has potential perf impact, it would be good to front-load this work.

From an internal email thead: there's no need to introduce a V4 format. The V3 format should be sufficient to cover this. You'd need to change the logic to say "if the app requested \<algorithm\> but the db contained \<weaker-algorithm\>, re-hash the password." This would be an additional check to the existing "if the stored hash iteration count is too small, re-hash" logic.
