### ISSUE TITLE
Blazor does not free up memory

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#37066]
This issue is related to #30210

As @javiercn mentioned there ASP.NET Core does not call garbage collection by default unless it runs out of memory. Now I have the following razor code:

```
@page "/Example1"
@using MemoryDiagnosis.Data

<a href="/Example1" target="_blank">Open Example 1 in new Tab</a>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>FirstName</th>
			<th>LastName</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in _data)
		{
			<tr>
				<td>@item.FirstName</td>
				<td>@item.LastName</td>
			</tr>
		}
	</tbody>
</table>

@code {

	private List<Example1Model> _data = new List<Example1Model>();

	protected override void OnInitialized()
	{
		for (var i = 0; i < 30; i++)
		{
			_data.Add(new());
		}
	}
}
```

The class Example1Model is defined as:
```
public class Example1Model
    {
        public string FirstName { get; set; } 
        public string LastName {  get; set; }

        public Example1Model()
        {
            FirstName = RandomString(10);   
            LastName = RandomString(20);
        }

        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
```

As you can see I'm creating 30 instances of this model and add it to a list in my component. Now I repeat reloading until I hit 200MB of RAM usage. I switch the page and wait around 3 minutes and manually then I manually call GC.Collect(2, Forced) as @javiercn mentioned in the mentioned issue. However, the memory will still be freezed and is only growing when I do any more actions within the app.

It keeps growing and growing. In another proejct with larger objects this results in our app is using over 25GB after 2 days of usage. I created a small video which shows what I mean.
https://www.youtube.com/watch?v=zQwkk45oA-M

I also uploaded the code to this repo: https://github.com/MarvinKlein1508/MemoryDiagnosis

Could you clarify what's going on @javiercn ?

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

In general we require more specific data for us to start a memory leak investigation. The reason is that often the methodology used is not appropriate or the issue is in the way the app is setup.

For us to continue making progress we need to see evidence that the framework is holding on to objects when it shouldn't and preventing the memory from being freed.

**Comment by MarvinKlein1508** [comment]
@javiercn check out the repo above. It is a default blazor template in .NET 6 just with an added page and model. You can reload the page as many times as you want. Every reload adds ~ 3MB memory. According to VS 2022 the memory keeps growing and will not shrink at any time. Even if I trigger a GC.Collect(2, Force); after 3 and 10 minutes.

When will the memory usage of the app shrink again, when the data is clearly no longer needed? I also tried to fill up my memory to maximum using Testlimmit64.exe from Sysinternals.

It's really frustrating to not know what's going on here. I would really appreciate a comment from you @javiercn  which tells me how the repo will shrink again to it's initial 100MB of memory usage.

**Comment by javiercn** [comment]
@MarvinKlein1508 I understand your frustration, at the same time, I would hope you understand that we don't have the resources to investigate every claim that a user makes in these kind of issues. 

We've done rigorous performance and stress testing on these areas as part of the release and we haven't found issues like the one you describe.

It's very hard and time consuming for us to be explaining why your results don't match your expectations. In the majority of the cases the cause is normally a defect in the app itself or in the methodology used to perform the measurements.

It is for that reason that we ask for concrete evidence of the issue and the methodology used to produce the results. For example:
* Is the app running in Release configuration?
* Is the debugger attached to the app?
* Are you able to force the framework (not your app) to consume enough memory to create an OutOfMemoryException?

Without a detailed report that demonstrates the configuration, methodology and specific evidence of an issue, it's impossible for us to conclusively determine there is an issue and its very expensive for us to repeat this process for every issue that gets filed. 

On the opposite side, we've done enough stress testing as part of the release that we think its very unlikely that there is an issue in this area.

In the end, I hope you understand that this is a cost/risk analysis. We don't have the resources to investigate every potential customer report in this area as the cost of doing so is very high and we have taken steps to validate these scenarios ahead of each release to minimize the risk of these types of issues being present.

**Comment by MarvinKlein1508** [comment]
Hi @javiercn 

yes I totally understand that it is really time consuming to figure this kind of stuff out. 

I allresdy spent a few days trying to understand what‘s going on. I also believe this isn‘t an issue within the Framework. But I see many posts on either StackOverFlow or on the AspNetCore repo from people who are wondering the same thing.


My main question is why I never see the memory shrinking within a Blazor app. Every action I just allocates more memory but it never shrinks within the Visual Stuido tools. As you can see in my provided repo, I just used the default blazor app and even here I never see the allocated memory shrinking. When I‘m running low on memory then I can see in VS that Blazor run a Garbage Collection but the allocated amount still shows 200MB and does not fall.

I think Blazor does something different because I don‘t run into this kind of issue within any other .NET platform.

I think you‘ll will notice immediately what I mean and are able to provide a solution for this. All you‘ll need to do is clone the repo, run it in Debug, navigate to /example1 hit F5 as many times as you want and see the allocation grow. Wait a few minutes and try a manual GC which doesn‘t affect anything at all.

**Comment by javiercn** [comment]
@MarvinKlein1508 You need to run under Release mode and without the debugger attached as a starting point. Those things will affect what you are observing.

**Comment by MarvinKlein1508** [comment]
@javiercn I ran the App now in release mode without a debugger attached to it. Also I updated my Model to generate 1GB of data everytime. The memory will be free'd now now I 'm running low on memory. For example:

I put 22GB of data via Testlitit64.exe into memory and startet my project. The app consumes more GB everytime I reload my test page. When it run's low the Blazor app will free around 1GB automatically to get enough space to load the data for the next reload. However, the app still uses around 4GB although it should only require 1.1GB to load everything into memory.

The page itself now generates 1.000.000 objects of Example1Model

```
@page "/Example1"
@using MemoryDiagnosis.Data

<a href="/Example1" target="_blank">Open Example 1 in new Tab</a>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>FirstName</th>
			<th>LastName</th>
		</tr>
	</thead>
	<tbody>
		<Virtualize Items="_data" Context="item">
			<tr>
				<td>@item.FirstName</td>
				<td>@item.LastName</td>
			</tr>
		</Virtualize>
	</tbody>
</table>

@code {

	private List<Example1Model> _data = new List<Example1Model>();

	protected override void OnInitialized()
	{
		for (var i = 0; i < 1000000; i++)
		{
			_data.Add(new());
		}
	}
}

```

I also added a few more property to the model itself to allocate the memory faster.
```
public class Example1Model
    {
        public string FirstName { get; set; } 
        public string LastName {  get; set; }
        public long Age { get; set; }
        public int Test { get; set; }
        public int Test2 { get; set; }
        public int Test4 { get; set; }

        public Example1Model()
        {
            FirstName = RandomString(10);   
            LastName = RandomString(20);
            Age = 10;
        }

        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
```

The main issue about this is that we cannot start our Hyper-V machines when the IIS is holding so much GB of trash in memory.

I think it has something todo with the List itself because I still see it within the memory profiler of VS.
Also it doesnt make any sence at all. Why is VS displaying that the Heap is only 6390,56KB large when the process memory is over 5GB. Where are all my other private bytes allocated? Take a look:
![grafik](https://user-images.githubusercontent.com/32510006/135170110-f9b5bd20-4142-47e3-957c-f4e4e4153ce2.png)

**Comment by davidfowl** [comment]
FYI @Maoni0
