### ISSUE TITLE
Blazor enable dynamic root components / Error: Dynamic root components have not been enabled in this application

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#37075]
Found this issue on Twitter / Stack overflow. Looks like an area which would either benefit from more documentation or updated registration lifecycle to prevent it altogether.

> Blazor enable dynamic root components / Error: Dynamic root components have not been enabled in this application

> https://stackoverflow.com/questions/69319216/blazor-enable-dynamic-root-components-error-dynamic-root-components-have-not?stw=2

**Comment by TanayParikh** [comment]
Error source: https://github.com/dotnet/aspnetcore/blob/24ea7ef4b753e1d1d56d13ffa4791af242bcefd0/src/Components/Web.JS/src/Rendering/JSRootComponents.ts#L144

**Comment by Swimburger** [comment]
The solution mentioned in StackOverflow works fine. A simpler version of it works in fact:
```html
    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        Blazor
            .start()
            .then(() => {
                const containerElement = document.querySelector('#app')
                return Blazor.rootComponents.add(containerElement, 'app', {});
            })
            .catch((error) => console.error(error));
    </script>
```
By setting `autostart="false"` you can prevent Blazor from starting, and then manually start it.
When the promise resolves you can safely run `Blazor.rootComponents.add` in my experience.

I do think it could be helpful to add an event that we can hook into instead of having to start Blazor ourselves.
I requested such an event in #37074.

**Comment by TanayParikh** [comment]
Thanks @Swimburger. Closing this out as dup against #37074
