### ISSUE TITLE
UseTokenLifeTime behavior clarification after testing

### ISSUE THREAD

**Issue by Ponant** [dotnet/aspnetcore#37087]
Consider the OIDC options:

````csharp
options.UseTokenLifetime = true;
````
which are used in an Azure B2C app using the `Microsoft.Identity.Web` with SignInSignUp built-in user flow for a Razor WebApp (cookies, implicit flow).

This option allows the cookie lifetime to somehow follow that of the access & id-tokens. It is the "somehow" which I would like to clarify.

The arguments hereafter have been tested but the mechanism described may not be accurate because testing is painful given the 15 minutes lower bound imposed for the session timeout in the portal.

Assume the following, configured in the portal:

* Access & ID token lifetimes is set to 5 minutes
* Web app session lifetime to 15
* Web app session timeout to `Absolute`
* Single sign-on configuration `Tenant` (anything but `Suppressed`)

and for the webapp in program.cs

* Application has a session cookie `mycookie`

#### Question

How long a user will stay signed in before being required to enter credentials anew?

#### Answer

The lifetime for reauthentication rule seems to be the following:

* The tokens lifetime being 5 minutes means that, if the user hits a page requiring authorization (e.g. with an `Authorize` attribute) at time `t0`, the new lifetime beyond which he will be required to sign in again with credentials is `15` only if `t0 < 10`. If the user clicks at `t0 > 10` then the new lifetime is `t0 + 5 > 15`. For example, by clicking a page with an authorize attribute at `t0 = 14`, the new lifetime becomes `t = 14 + 5 = 19`. Any subsequent visit at time `t1` within the next 5 minutes on a page requiring authorization will reset the time to `t1 + 5`. If the user waits for 5 minutes and later visits a page requiring authorization, the user will be prompted to enter the credential again. This means that the user can remain indefinitely logged in as long as he gets new Access & ID tokens by visiting pages requiring authorization within the 5 minutes set by the tokens lifetimes.

The same behavior occurs if we set the `ExpireTimeSpan` instead of session in the application cookie to, say, 1 minute.

However, if the application cookie has a `MaxAge` of 1 minute, then after the 15 minutes the new time before being forced to login is determined by the cookie (1 minute), so that the user will be required to be logged in at most after `15 + 1 = 16 minutes`.
In this sense the name `UseTokenLifetime` is somewhat confusing.

Any feedback is greatly appreciated because the Azure B2C docs really are not great and the information on `UseTokenLifeTime` is as vague as its name.

cc @amanmcse

**Comment by Tratcher** [comment]
> Web app session lifetime to 15

Which specific API are you setting here? [Session](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0) and auth are unrelated.

**Comment by Ponant** [comment]
@Tratcher https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy
and for the tokens https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens?pivots=b2c-custom-policy
The rest is something along

````csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
              .AddMicrosoftIdentityWebApp(options =>
              {
                  options.UseTokenLifetime = true;
                  //rest of code
              });
````

**Comment by Ponant** [comment]
Portal Azure B2C (I work on custom policies, but the behavior is observed also in built-in policies, such as the Susi pictures below)
![Capture1b](https://user-images.githubusercontent.com/19961806/135360901-f300f9c6-5c51-431b-bd2a-db5a9d4a116f.PNG)
![Capture2](https://user-images.githubusercontent.com/19961806/135360912-e8fc83ef-b53b-4766-82e4-ead9d43e1517.PNG)

**Comment by Tratcher** [comment]
So all UseTokenLifetime does is pin the auth ticket / cookie expiration to match the id token.
https://github.com/dotnet/aspnetcore/blob/3d7a624cc7bfbfeec1843efb8c00b4832e7c5675/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1270-L1283

What you're describing sounds more like the refresh token flow, which I believe is something implemented by AddMicrosoftIdentityWebApp. Is that right @jennyf19?

**Comment by Ponant** [comment]
I did not test beyond the 1 day minimum of refresh tokens!
But what is not so expected is the possibility to exceed the session time out limit (15 min in the example) even with an `Absolute` session type. The docs above say

"Absolute - Indicates that the user is forced to re-authenticate after the time period specified."

What is also not expected is the role of MaxAge on the application cookie.

**Comment by jennyf19** [comment]
@Tratcher there is no refresh token unless this is included `.EnableTokenAcquisitionToCallDownstreamApi()`, which will use a cache and the refresh token.
Do you want me to include someone from B2C?

**Comment by Ponant** [comment]
I am not using downstream apis. This is a single isolated web app (tested on the template from VS) which only wires up `AddMicrosoftIdentityWebApp`.

**Comment by HarmanDhunna** [comment]
Hi @Ponant,

I think your understanding of B2C is correct but I would like to summarize in case I miss read any part of the discussion.

**Access & ID token lifetimes (minutes)**: the lifetime of the access token that is issued for your application. This does not get used by B2C for subsequent requests. 

**Refresh token lifetime**: the lifetime of the rt(refresh token), basically the time period in which the client can obtain ATs(access tokens) or ITs(id tokens).

**Refresh token sliding window lifetime**: This really varies on the type of app, but basically do we extend the RT time. Spa apps are limited to one day max no matter what.

**Lifetime length (days)**: Max value of anything and everything.

**Web app session lifetime (minutes)**: Lifetime of the session cookie (If presented with KMSI, this gets overridden by the KMSI value and the cookies are set to be persistent instead of session).

**Web app session timeout**: how the extension should be of the session. 



From what I understand from the discussion above with @Tratcher, `UseTokenLifetime ` will set the cookies lifetime to match that of the token. Which token? I am not sure. Let's presume there is only one type of toke requested and returned. Both the cookie and the token would expire at the same time. 

Example: AT was requested, and at t0 AT with a lifetime of 15 mins is returned, then the client is able to use that AT till t0+15mins to your application, and they do not have any means of silent getting another AT and the client should force the user to sign in interactively.


Resources:
* [Token lifetime behavior](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens?pivots=b2c-custom-policy#token-lifetime-behavior)
* [Configure session behavior in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy)
