### ISSUE TITLE
Blazor PointerEventArgs.Button always -1 with svg

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/aspnetcore#37213]
HI, 

```PointerEventArgs.Button``` is always -1 in an svg with Blazor .NET 6 RC1 even when left/right mouse buttons pressed.

Workaround is to use ```PointerEventArgs.Buttons```.

Repro below:

```
@page "/"

<svg width=300 height=300 style="background-color:green"
				 @onpointermove="@OnPointerMove"
				 @onpointermove:stopPropagation="true"
				 @onpointermove:preventDefault="true"
				 				
></svg>

@code {

    void OnPointerMove(PointerEventArgs e)
	{
		Console.WriteLine($"e.Button = {e.Button}, e.Buttons = {e.Buttons}");  // e.Button always -1
	}
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Did you check whether the browser returns something different when you access that in JS?

**Comment by KristofferStrube** [comment]
This is the intended behavior.
`onpointermove` is *fired when a pointer changes coordinates.*
The `Button` attribute is `-1` if *Neither buttons nor touch/pen contact changed since last event.*
So this is not a bug.
Source: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

This small HTML/JS example showcases the same behavior:
```html
<html>
    <body>
        <svg id="svg" width=300 height=300 style="background-color:green">
        </svg>
        <script>
            var svg = document.getElementById("svg");
            svg.addEventListener("pointermove", (e) => {
                console.log(`pointermove: e.button: = ${e.button}, e.buttons = ${e.buttons}`);
            });
        </script>
    </body>
</html>
```
