### ISSUE TITLE
[Blazor] Bundling all resources into a single file

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#37310]
Hi,

Is there a way to bundle all JS modules, CSS files and images into a single file and then load these resources from the browser cache? I suspect you are doing something similar in Blazor MAUI.

Imagine a simple web app that has dozens of resources but all combined totaling a relatively small size < 100 KB. Rather than loading them dynamically across the network in various parts of the app I'd like to load them as a single file on the initial download. Besides potential performance improvement, main benefit is that the resources will not fail to load on unreliable mobile network as user navigates through the app. I've run into instances when a JS module is not loaded on something like a simple dropdown component and I'm not sure what is the recommended way to attempt to reload the module besides user refreshing the page (which has its own problems).

Thanks!

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

We don't have such feature, you can use Webpack or similar tooling to bundle your assets if you want to, there's nothing we provide out of the box. That said, you don't get that many benefits from bundling with HTTP/2 compared to HTTP/1.1 since bundling is primarily implemented as a way to get around the limited number of connections browsers use when communicating over HTTP/1.1.

As for Blazor desktop, it works fundamentally different than Blazor webassembly, so those concepts don't apply.
