### ISSUE TITLE
Can't start debugging Blazor WebAssembly with Hot Reload disabled in VS

### ISSUE THREAD

**Issue by centreboard** [dotnet/aspnetcore#37357]
### Describe the bug
Can't start debugging Blazor WebAssembly with Hot Reload disabled in VS.

### To Reproduce
In Visual Studio have Auto build and refresh option: None
![image](https://user-images.githubusercontent.com/10487726/136415265-315bd07f-15cf-420b-b687-b0ce78c0b16e.png)

Create a new Blazor Webassembly project. Start debugging it.
"An unhandled error has occurred."

Changing the option to `Refresh browser after build` allows debugging again.

### Exceptions (if any)
```
System.AggregateException: One or more errors occurred. (Failed to fetch dynamically imported module: https://localhost:7100/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7100/_framework/blazor-hotreload.js)
 ---> Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7100/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7100/_framework/blazor-hotreload.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.InitializeAsync()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken, WebAssemblyCultureProvider cultureProvider)
   at Program.<Main>$(String[] args) in C:\Hackday\ThinkingTOAD\BlazorApp\BlazorApp\Client\Program.cs:line 11
   --- End of inner exception stack trace ---
   ```

### Further technical details
- ASP.NET Core version: 6 rc1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 17.0.0 Preview 4.1
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

```

</details>

**Comment by pranavkm** [comment]
Implementation notes self since this has a few moving parts:

On startup, Blazor WASM attempts to re-apply any deltas from a before the browser was refreshed by invoking a JS module. Currently this is gated on `MetadataUpdater.IsSupported` which is true when debugger is attached. While we wire up other things in the framework based on this condition, this is the first incidence of doing something pro-active when the feature switch is present. This poses a problem since `IsSupported` does not indicate `IsEnabled` which is what's happening in the user's case.

For this particular case, we can infer the presence of the `blazor-hotreload` endpoint as a proxy to hot reload being enabled. To do this,

a) The browser refresh middleware binary will configure an environment variable that says it is indeed injected.
b) Components.WebAssembly.Server will read this env variable and configure an additional HTTP response header when sending blazor.boot.json
c) The client script will configure a env variable in WASM based on the presence of this HTTP header.
d) WebAssemblyHost will only attempt to download the module if both `MetadataUpdater.IsSupported` and this environment variable are present.
