### ISSUE TITLE
Blazor - A question related to the 15547 issue

### ISSUE THREAD

**Issue by outsidergiant** [dotnet/aspnetcore#37477]
Hi,

In a closed [15547 issue](https://github.com/dotnet/aspnetcore/issues/15547), Steve Sanderson mentioned the following:
>We're not planning to bake in INotifyPropertyChanged as a required pattern within Blazor, because various other patterns are also used and considered preferable depending on your overall architecture.

What other patterns are used by Blazor out-of-the-box, and which ones are more preferable than INotifyPropertyChanged support?

**Comment by outsidergiant** [comment]
I didn't get any response..what activity do you expect from me?

**Comment by SteveSandersonMS** [comment]
> I didn't get any response..what activity do you expect from me?

Sorry, the bot's message wasn't well suited to this situation.

> What other patterns are used by Blazor out-of-the-box, and which ones are more preferable than INotifyPropertyChanged support?

The out-of-box pattern in Blazor is simply:

 * A: when an event occurs, the component receiving the event will re-render
 * B: when a component re-renders, its children will re-render if any of their parameters may have changed (that is, if they receive a primitive-typed parameter whose value has changed, or if they receive any non-primitive-typed parameters since they may have mutated)

Part B continues recursively down the hierarchy, stopping whenever a descendant definitely isn't getting any changed parameters. This simple pattern turns out to be sufficient for the vast majority of cases and doesn't require the developer to write any code to control the reactivity, so is a good starting point.

However you always have the power to call `StateHasChanged` on any component yourself, and therefore to wire up any other reactivity source of your choosing. If you like implementing `INotifyPropertyChanged`, you can do so and call `StateHasChanged` when you see a property has changed. If you like a different approach such as observables (like in Rx or MobX or Knockout) then you can have domain models structured in those terms and write code that handles change notifications by calling `StateHasChanged` to trigger re-rendering.

It's not that any one approach is objectively more preferable than another. It's about allowing simple code when possible, and allowing detailed power and control when required. Hope that makes sense!
