### ISSUE TITLE
Consider supporting IJSInProcessRuntime in Blazor Desktop

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#37647]
The `IJSInProcessRuntime` service exists to offer improved performance and behavior when Blazor code (e.g. app code) is running with a "locally available" JS runtime, such as in Blazor WebAssembly scenarios. This should also presumably be the case in Blazor Desktop scenarios, where there is also a locally available JS runtime in the WebView.

I'm not sure if it would have any real perf improvements or implications because everything is running locally anyway (maybe less marshalling/serialization?), but it could make it easier to have Blazor components work in Blazor Desktop if they require support for `IJSInProcessRuntime`.

Example from SkiaSharp: https://github.com/mono/SkiaSharp/issues/1834

@SteveSandersonMS / @javiercn - thoughts on this? Any reason we couldn't or shouldn't?

**Comment by javiercn** [comment]
@Eilon isn't the WebWindow interop channel async? That's the main limitation for the InProcess one. If we can't guarantee that across implementations, we should avoid it, or just implement it where supported.

**Comment by javiercn** [comment]
> but it could make it easier to have Blazor components work in Blazor Desktop if they require support for `IJSInProcessRuntime`

Components should **not require** support for `IJSInProcessRuntime` we should be very clear that this is always an opt-in optimization.

**Comment by javiercn** [comment]
@Eilon @SteveSandersonMS I propose we don't even consider this, since as a general rule, we can't guarantee the availability of sync interop across desktop platform implementations (which AFAIK none supports today) and if we were to implement it on some of them and not others, it would produce an inconsistent experience for Blazor Desktop developers. So I think the right call here is to resort to the common denominator for all desktop platforms.

IMO there can be two outcomes:
* Providing sync interop doesn't yield significant perf benefits, in which case, there's not much benefit on enabling it.
* Providing sync interop yields significant perf benefits, in which case, we end up with an inconsistent platform that offers different perf characteristics across platforms. I don't think we want to promote apps/frameworks that work well in one platform and don't in another.

**Comment by Eilon** [comment]
@javiercn - all good points, thank you.

I think that either way on these, there is no way to implement this right now anyway, and I don't think this is important enough right now to try to push all (or even _any_) of the browser vendors to support this, plus the relevant interop APIs. As such, I think there is little value in keeping this issue open because it doesn't have any reasonable path forward.
