### ISSUE TITLE
New SpaProxyManager requires port to be hit before starting dev server

### ISSUE THREAD

**Issue by steveoh** [dotnet/aspnetcore#37661]
On the dotnet community stand up, a spa proxy manager class was released that could be used in dotnet 5 to start up the front end development server (which would ultimately end up in dotnet 6). I've converted to dotnet 6rc2 and have noticed some changes from the shim that seem problematic. 

Because this feature has no documentation, some of my assumptions could be wrong so please correct me if that is the case. My only insight is to look at how the template is created.

With the old shim, the presence of a `spa.proxy.json` file was basically enough to start the front end dev server when you ran `dotnet run`. The front end server would start and the dotnet server would start next. With 6rc2 it seems that the `spa.proxy.json` was moved into the `.csproj`. 

There is the presence of some magic port numbers that start the front end dev server and redirect you. From the react template that is `7004` and `5220`. So, if I have my website up and running on the front end dev port of 3000, and I restart the api, 3000 is not started until I browse to 7004 again. This is a poor development loop.

The change from 5000 and 5001 to 7004 and 5220 also requires any configured OpenID callback urls to be changed. The port change seems unnecessary. Can this feature be changed to keep the 5000 and 5001 urls and start the front end server when a cli command is run rather than when a url is hit?

**Comment by javiercn** [comment]
@steveoh thanks for contacting us.

We made some changes over the following previews to better align the IDE experience. Let me try to address some of your comments feedback:

> The change from 5000 and 5001 to 7004 and 5220 also requires any configured OpenID callback urls to be changed. The port change seems unnecessary. Can this feature be changed to keep the 5000 and 5001 urls and start the front end server when a cli command is run rather than when a url is hit?

The port change is something that happened across the entire ASP.NET Core templates as we switched from IIS Express to Kestrel as the primary development experience.

> There is the presence of some magic port numbers that start the front end dev server and redirect you. From the react template that is 7004 and 5220. So, if I have my website up and running on the front end dev port of 3000, and I restart the api, 3000 is not started until I browse to 7004 again. This is a poor development loop.

The ports are not "magic", they are randomized during project creation (in the same way they were for IIS Express) so once the project is created they stay the same until you change them. The frontend should not be affected by what you are describing, since the backend won't change ports after project creation. If you can provide a concrete set of steps where this happens we would consider that a bug and something we would try to address.

The current is that the backend API is always launched first, when the C# backend is launched, it contains logic to detect whether the proxy is already running or whether it needs to launch a new instance. While the new SPA proxy instance is booting, the server redirects to a temporary page with a link to the front-end proxy and when it detects that the proxy is up and running it redirects there. If you start the proxy manually from a separate command line, we redirect to the proxy URL without waiting.

> With the old shim, the presence of a spa.proxy.json file was basically enough to start the front end dev server when you ran dotnet run. The front end server would start and the dotnet server would start next. With 6rc2 it seems that the spa.proxy.json was moved into the .csproj.

This hasn't changed, and spa.proxy.json was never something sitting in your project, but something that got generated at build time automatically, this is still the same today. This is not an area where we've made changes between previews.

Hope this helps clarify some of the reasons for the changes.
