### ISSUE TITLE
Base grid component

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37908]
Consider shipping a basic architecture for a Blazor grid component. This would only include the core functionality of rendering rows very efficiently (virtualized), sorting, being wired up to data sources like `IQueryable`, and being extensible.

People who want more sophisticated functionality like drag-drop column reordering, row grouping/nesting/selection, etc. would build this on top of the base grid or use a 3rd-party component that may do so.

**Comment by cirrusone** [comment]
There has already been feedback requested in the WinUI community since 2019 relating to a new DataGrid component - [Discussion: Modern WinUI DataGrid - Input Needed](https://github.com/microsoft/microsoft-ui-xaml/issues/1500)

It would be useful if the DataGrid for Blazor/WinUI aligned functionality.

Also, I think the lack of decent DataGrid in Blazor and WinUI is one of the key decisions on whether that technology will be used by many businesses. We can't always get the budget or approval for many 3rd party libraries.

**Comment by Liero** [comment]
Funny, I made a similar attempt to create a extensible base grid component using css grid: 

https://github.com/Liero/vNext.BlazorComponents/tree/main/BlazorComponents/Grid

I have successfully used it in production, but I have learnt that the base grid should not attempt directly support IQueryable or Sorting or System.Linq.Expression (Property selectors..), but rather provide callbacks, e.g. `ItemsProvider` callback for querying, `HeaderClicked` callback for sorting etc, or OnCellContextMenu (since it is untrivial to do in a performant way).

Also the column definitions should be extensible POCO classes, that could be wrapped in Components in the extended datagrid.

I found the ag-grid's approach using it's `GridApi` best solution for extensible base grid component and I have tried many grids from various providers on various platforms.

**Comment by silentdevnull** [comment]
This would be a great item to add. I 100% agree with @cirrusone that a lot of times there isn't the buget for third part times. Most of them are eight hundred plus to which is a lot if all you need is one page with a sortable grid.

Please add this to dotnet 7.

**Comment by Postlagerkarte** [comment]
In of his last talks Steve indicated that this is going to be in .NET 7 -  *HURRAY!* 😃 

The performance of QuickGrid is just mind blowing! It might even be able to compete with AG-Grid.

Having a fast but simple base grid component is great to quickly showcase something to customers (having a high performance grid view is a key factor for enterprise customers in insurance and banking) and it hopefully enables 3rd Party Vendors to finally deliver feature rich and performant version of their current (pretty lame) grids.

**Comment by SteveSandersonMS** [comment]
Update for people watching this: for .NET 7 we're shipping an experimental data grid package, and have published a whole samples site about it: https://aspnet.github.io/quickgridsamples/

You can read more there about the feature set and how we aim to evolve this in the future. If you're interested, please try it out and give us your feedback!
