### ISSUE TITLE
EntityFrameworkCoreXmlRepository Seems Suboptimal?

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/aspnetcore#37985]
I notice that EntityFrameworkCoreXmlRepository never removes DataProtectionKeys entries from the database, and returns them in insertion order - since the XML has an expirationDate only two months in the future, doesn't this mean after say 3 years of running, it would have to check 18 invalid keys on each application start before finding the valid key - and that it would only get slower and slower over time?

Is there a reason it needs to keep expired keys, and is there a reason it doesn't return them in the reverse of the order they were inserted?

Edit: I see now that it's actually 3 months (90 days) not 2 months, and that we need to keep the expired keys in order to possibly decrypt data that was encrypted with the now-expired key. So I think I will just increase the default lifetime to something above 90 days

**Comment by blowdart** [comment]
We intentionally do not remove keys because some developers store protected data in databases. If we purged keys that data would be lost, never to be recovered. It's just like certificates in the certificate store, expired ones never get deleted so data encrypted with them can still be decrypted. 

When data protection refreshes the keyring it loads _every key_, expired and unexpired, so the only performance hit is on startup and refresh, and the refresh isn't that often. 

If you have an actual significant slowdown and you're not storing protected data you can of course purge on your own, but that's your decision and not one we can make with any degree of accuracy or no risk of data loss, so we simply won't do it.
