### ISSUE TITLE
Blazor wasm size reduction

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#38071]
In .net 6 https://github.com/dotnet/aspnetcore/issues/27668 was removed, It was marked cut and very little commitment was made to overall size reduction.
Size reduction is crucial for wide adaptation of Blazor wasm.  
For .net 7 please consider reopening the issue and giving some priority to Size reduction. If not in .net 7 then it's gonna be too late.

@samsp-msft @mkArtakMSFT

**Comment by javiercn** [comment]
@sps014 thanks for contacting us.

The issue you referenced contains a list of potential improvements without a clear indicator of the benefits/improvements to size reduction each one of the proposed changes aims to provide.

We've done a significant amount of work to reduce the application size in .NET 6.0, with things like re-linking and low level changes to reduce the size of trimmed applications. We think there are better opportunities for improvement in other areas before we try to tackle some of the items in that list.

There are some other reasons to tackle some of the items in that list, and we will plan for those accordingly. Please note that with regards to performance (in this case, size reduction), we don't make "speculative" changes and we need to have evidence of the gains before we tackle on the work.

The size reduction for many of the remaining improvements won't be significant and won't likely be relevant for most applications since, at best, we would need to avoid reflection in all code paths for the linker to be able to trim reflection code paths.

Even if we were to take on this massive amount of work, it would all be for nothing the moment someone brought in a library that uses reflection.

Our main motivation to remove reflection code-paths is speed and linkability. For example, we have a prototype for ` Parameter assigmment (ComponentProperties.cs, MemberAssignment.cs, CascadingParameterState.cs, PropertySetter.cs), to find the properties on a type with ParameterAttribute and to write supplied values to them` as there are reasonable performance benefits for using it.

For other items like ` BlazorPack (SequenceOfT.cs), to check whether a type is a value type via typeof(T).GetTypeInfo().IsValueType` this doesn't even apply to webassembly, so there's no motivation for us to pursue it.

I hope this helps clarify our approach to size reduction and bring some light into why some of the remaining items are not a priority for us. 

I'm closing this issue as we are handling the remaining items of that list that we deem worthy in separate issues.
