### ISSUE TITLE
VS 2022 Preview 7, Asp.net 6, New Blazor Server Project with Periods in Project Name Fails to Build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38074]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Preview-7-Aspnet-6-New-Blazor/1565042)._

---
[regression] [worked-in:16.11]
All,

I just created a new project, I immediately tried to build and it is having errors. See attached. 

I think the periods in the namespace have something to do with it. I named it GC. BlazorComponents.UI. And the errors state:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0426	The type name 'BlazorComponents' does not exist in the type 'GC'	GC. BlazorComponents.UI	C:\Users\kgates\source\repos\GC. BlazorComponents\GC. BlazorComponents.UI\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Error_cshtml.g.cs	158	Active

```

---
#### Feedback Bot on 10/28/2021, 00:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
I don't think `.` is the reason here, rather the space (` `) in the project path.

**Comment by kevingates** [comment]
@mkArtakMSFT I think that space is added in the error, because I created the project. There wasn't a space. Heck, I don't even think VS will let you create a namespace *with* a space. The repo is private one, but I looked at the original commits. The solution, nor project file, nor namespace have a space. All are `GC.BlazorComponents`

For insance, is the default code from the templated JS Interop:

```C#

using Microsoft.JSInterop;

namespace GC.BlazorComponents
{
    // This class provides an example of how JavaScript functionality can be wrapped
    // in a .NET class for easy consumption. The associated JavaScript module is
    // loaded on demand when first needed.
    //
    // This class can be registered as scoped DI service and then injected into Blazor
    // components for use.

    public class ExampleJsInterop : IAsyncDisposable
    {
        private readonly Lazy<Task<IJSObjectReference>> moduleTask;

        public ExampleJsInterop(IJSRuntime jsRuntime)
        {
            moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>(
               "import", "./_content/GC.BlazorComponents/exampleJsInterop.js").AsTask());
        }

        public async ValueTask<string> Prompt(string message)
        {
            var module = await moduleTask.Value;
            return await module.InvokeAsync<string>("showPrompt", message);
        }

        public async ValueTask DisposeAsync()
        {
            if (moduleTask.IsValueCreated)
            {
                var module = await moduleTask.Value;
                await module.DisposeAsync();
            }
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for clarifying this, @kevingates.
The issue here is due to a naming conflict in your namespace. Specifically, `GC` is a known type and the compiler gets confused.
You can try to remove the `ImplicitUsings` property from your project file and see whether that helps. It will, initially, cause a lot of errors that you'll need to address.
If not, renaming the namespace would be your best bet.
