### ISSUE TITLE
Blazor Server OnInitialized called after setting variable when run under VS2022 but not in VS2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38130]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Server-OnInitialized-called-after/1572117)._

---
[severity:I'm unable to use this version]
I have a Blazor Server project that was created in VS2019 using .NET 5.   I have a page with a button that has a click event handler.  In the handler method I set a variable that is scoped to the page.  The variable is displayed in a div element on the page.   When run under VS2019 everything works as expected.  The variable is set in the onclick event of the button and the div element displays the contents of the variable.  However when I open the exact same project under VS2022 and run it, setting the variable causes the OnInitialized method to be called again, so the page is reloading.   Nothing is different other than the IDE.

---
#### Feedback Bot on 11/4/2021, 08:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ttosello** [comment]
[BRS.Test2.zip](https://github.com/dotnet/aspnetcore/files/7499980/BRS.Test2.zip)

I have attached a project that is a standard Blazor Server template based on .NET 5 and I created it in VS2019.  I modified the Index.razor page only.

The issue is related to the HtmlAgilityPack library and not setting a plain variable as first thought.  In VS2019 when you call the Save method of the HtmlDocument object, the document saves and the page does not reload.   If you open in VS2022 and run the same project, the Save method causes the page to reload.

In VS2019 the Counter should be 5 after clicking the button and it is. However, in VS2022 the Counter resets to 10 because the page is reloaded.

**Comment by JonathanMagnan** [comment]
The issue is not related with `HtmlAgilityPack` but with the `Flush` method from the `StreamWriter`.

The same issue can be reproduced used this code inside the project of @ttosello provided.

```csharp
private void DoSomething()
{
	var path = Path.Combine(Env.WebRootPath, "test.html");

	StreamWriter sw = new StreamWriter(path, false, System.Text.Encoding.UTF8);
	sw.Write("test");
	sw.Flush();
	
	c = 5;
}
```

**Comment by mkArtakMSFT** [comment]
@ttosello please share the repro project as a publicly hosted repo on GitHub. We can't open zip files due to policies.

**Comment by ttosello** [comment]
Sorry, here is the repro:  https://github.com/ttosello/BRS.Test2

**Comment by javiercn** [comment]
@ttosello does the issue reproduce if you run the project from the command-line?

It can be that you have hot-reload enabled in VS2022 and that is triggering a reload or something similar, causing the code to re-execute

**Comment by ttosello** [comment]
Yes, running from command line produces the expected behavior.   I have tried disabling Hot Reload (setting shown in image) but it has no effect.  

![image](https://user-images.githubusercontent.com/6826475/141008294-cbc2d983-2c1a-4e6e-b78f-851290c339bc.png)

**Comment by javiercn** [comment]
@ttosello what's likely happening here is that we are refreshing the browser on save

**Comment by ttosello** [comment]
I have tried changing this setting, but it doesn't help:

![image](https://user-images.githubusercontent.com/6826475/141009109-3ec03088-2ac0-49b1-99cf-bfb6d178c8df.png)

**Comment by javiercn** [comment]
@ttosello It seems to be VS specific, so I would report it through the report a problem dialog in Visual Studio.

@pranavkm and @BillHiebert might have some ideas.

**Comment by ttosello** [comment]
I did report it there and it was moved here.

**Comment by javiercn** [comment]
@ttosello You are right, let me ping other folks and see if they have some ideas.

**Comment by pranavkm** [comment]
Ok, looks like the component is writing out an html file to the webroot. This is likely to cause VS to think a html file change and do a rebuild. I was under the impression that the setting that you have configured to None should turn off this behavior. Let's move this conversation back to the VS feedback issue so that we can route this to the right VS feature crew.
