### ISSUE TITLE
Builder.WebHost.UseUrls does not seem to override default url

### ISSUE THREAD

**Issue by Buildstarted** [dotnet/aspnetcore#38185]
Previously mentioned: #36245

### Describe the bug
`Builder.WebHost.UseUrls()` fails to use the port/url provided

### To Reproduce
```
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseUrls("http://*:8080");
var app = builder.Build();
app.Run();
```

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.208 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21460.8 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by Tratcher** [comment]
@halter73

**Comment by halter73** [comment]
This is a bug.

Certain `IWebHostBuilder` extension methods are unsupported and throw when they're called (e.g. `builder.WebHost.UseEnvironment("{EnvironmentName}")`) because it's too late to reload all the config at this point. However, we have [WebApplicationOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplicationoptions?view=aspnetcore-6.0) which can be passed to `CreateBuilder(WebApplicationOptions options)` to make up for that.

Server urls are bound late enough that this should work as is. Unfortunately there's a bug where stale hosting config is incorrectly overriding the urls configured with `UseUrls(params string[] urls)`. This is what `Configuration` looks like [on this line](https://github.com/dotnet/aspnetcore/blob/3e354f3591a854b498a90097bae6d6207871c4a9/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L72).

![image](https://user-images.githubusercontent.com/54385/140811732-204ef860-59d3-4a47-8a33-9cf0014b8b41.png)

There are a number of workarounds depending on your requirements. The easiest is likely passing in the `url` argument to `WebApplication.Run(string? url = null)`.

```c#
app.Run("http://*:8080");
```

**Comment by davidfowl** [comment]
I think we should also patch this in 6.0.x

**Comment by halter73** [comment]
I agree it should be patched. I almost milestoned it myself, but figured we could discuss in triage.

**Comment by tetious** [comment]
For me, trying to override the URL in Run results in the following `Changing the URL is not supported because no valid IServerAddressesFeature was found.` when using `WebApplicationFactory` for testing. I'm uncertain if this is a mistake in my configuration/usage or a separate bug...

Setting `ENV ASPNETCORE_URLS=http://+:5050` within the runtime image section in our Dockerfile worked, however, and doesn't break testing.

**Comment by tehmufifnman** [comment]
> For me, trying to override the URL in Run results in the following `Changing the URL is not supported because no valid IServerAddressesFeature was found.` when using `WebApplicationFactory` for testing. I'm uncertain if this is a mistake in my configuration/usage or a separate bug...
> 
> Setting `ENV ASPNETCORE_URLS=http://+:5050` within the runtime image section in our Dockerfile worked, however, and doesn't break testing.

Do you have a code snippet to share?
