### ISSUE TITLE
Visual Studio 2022 Blazor project builds and runs successfully but publish fails with System.ArgumentException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38186]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Blazor-project-builds/1573407)._

---
Visual Studio 2022 Blazor project builds and runs successfully but publish fails with the following error

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.GroupExistingStaticWebAssets(Dictionary`2 assemblyAssets, Dictionary`2 nativeAssets, Dictionary`2 satelliteAssemblyAssets, Dictionary`2 symbolAssets, Dictionary`2 compressedRepresentations)
   at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.Execute()	Client		0	

The attached solution (bug.7z) contains the necessary solution and project files to reproduce the error. Just unzip and set Client as the startup project. It should build and run successfully but when you try and publish the Client project it will give the error. If this turns out not to be a Visual Studio error, please improve the error message in order to make the debug process easier.

---
#### Feedback Bot on 11/7/2021, 07:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Could you make the minimal repro project available as a public github repository?

@pranavkm possible dupe of https://github.com/dotnet/aspnetcore/issues/37574

**Comment by budcribar** [comment]
I have a github repo at https://github.com/budcribar/PublishBug. See the readme to reproduce. thanks,
bud

**Comment by javiercn** [comment]
@budcribar thanks for the additional details.

Based on https://github.com/budcribar/PublishBug/blob/master/Components/Components.csproj#L80-L91 it seems like the same issue as https://github.com/dotnet/aspnetcore/issues/37574

**Comment by budcribar** [comment]
It sounds like #37574 is a run time error. My app works fine at run-time but the error occurs during Publish. I also tried referencing ..\HPI.FrameworkAbstractions.dll etc from the main level project and the publish still fails. Regardless, the error message could be improved :)

**Comment by javiercn** [comment]
@budcribar I believe you are correct.

It seems that you have a `.config` file for a dll. That it is potentially causing the issue.
![image](https://user-images.githubusercontent.com/6995051/141480470-a8ff213a-b237-41cc-b763-962c90458217.png)

The reason is the original item spec is set to the .dll and that is causing the gzip task to create duplicates

**Comment by javiercn** [comment]
I believe this issue is the same as https://github.com/dotnet/sdk/pull/22470 hence addressed there.

**Comment by javiercn** [comment]
The config item shows the same issue WRT the original item spec, so the fix is the same
https://github.com/dotnet/sdk/pull/22470/files#diff-576ff8fae44da14d0ffe3820de926dbe0f8df13c8881dc5fd98bd851101c4180R131-R138

**Comment by budcribar** [comment]
@javiercn Thanks for checking into this further. Is there a daily build that I can use to verify or should I wait for next release?

**Comment by javiercn** [comment]
@budcribar If you need to workaround the issue, you might be able to avoid it by removing the config file of the .Interfaces project (not sure what that is being used for).

As for nightly builds, you can grab it from github.com/dotnet/installers. A 7.0 nightly SDK build should have the fix, but it might not be able to build 6.0 RTM projects yet (this is just because 6.0 got released recently and some dependencies might need to still flow through the system in the 7.0 branches).

**Comment by budcribar** [comment]
@javiercn Thank you it works!! Not sure what the config file of the .Interfaces project was used for either ;) Just picked it up from another developer.

**Comment by MKI-Miro** [comment]
I am getting same error during publish process, but I really dont undersand how to find where the problem is

C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): Error : System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.GroupExistingStaticWebAssets(Dictionary`2 assemblyAssets, Dictionary`2 nativeAssets, Dictionary`2 satelliteAssemblyAssets, Dictionary`2 symbolAssets, Dictionary`2 compressedRepresentations)
   at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.Execute()

**Comment by AlexIvanRBC** [comment]
Same error here... builds fine, publish works on .NET5, but after upgrading to .NET6, same error...

**Comment by mkArtakMSFT** [comment]
We believe this is already resolved. If you still face similar issues please file a new issue.
