### ISSUE TITLE
navigator.clipboard.writeText blocked in Safari (MacOS and iOS)

### ISSUE THREAD

**Issue by jonheslop** [dotnet/aspnetcore#38211]
Blazor components using `@onclick` which then run `JsRuntime.InvokeVoidAsync("clipboardCopy.copyText")` fails in Safari because (I think) the onclick event is detached enough from the blazor server invoked `navigator.clipboard.writeText('text')` function that Safari thinks the copy function hasn’t been triggered explicitly by the user.

Our copy functionality uses the exact code in this example - https://chrissainty.com/copy-to-clipboard-in-blazor/

It works fine in Chrome/Firefox but is blocked in Safari (MacOS and iOS) with the error.

```
[2021-11-09T14:17:55.015Z] Error: Microsoft.JSInterop.JSException: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
writeText@[native code]
```

I’ve made a simple example app with the Blazor tutorial app - https://github.com/jonheslop/SafariCopyIssue/

![Screenshot showing error in Safari](https://user-images.githubusercontent.com/440503/140947637-49454555-ec77-4eb8-8c3a-5f48da3ecc81.png)

**Comment by rorymalcolm** [comment]
Blocker for us too, if any community member has a workaround it'd be much appreciated!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is caused by browser behavior, which we don't control. So you'll need to implement this on your own by writing an event handler in JavaScript, capturing whatever data you need and passing it into the .NET application using either a [custom event](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0#custom-event-argumentsv) or a [JS Invokable method](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0).
