### ISSUE TITLE
Why is aspnetcore looking for deps.json in production env?

### ISSUE THREAD

**Issue by geetmenon** [dotnet/aspnetcore#38275]
I have explicitly turned of deps.json generation in my aspnetcore (.Net 5) web project via the following setting :
`<GenerateDependencyFile>false</GenerateDependencyFile>`
So my publish does not generate deps.json.

I am able to run being up my web app successfully in my dev environment.  However in my production server, I get the error "HTTP Error 500.30 - ASP.NET Core app failed to start". On checking event viewer logs, I see the error  "Could not find file  deps.json". 

My understanding is that deps.json is not really required in production env. So why is it looking for deps.json in my production env?

**Comment by davidfowl** [comment]
> My understanding is that deps.json is not really required in production env. So why is it looking for deps.json in my production env?

Your understanding from where?

**Comment by geetmenon** [comment]
I read somewhere that deps.json contains all dev dependencies, and we can turn if off by setting GenerateDependencyFile to false in web proj file
`<GenerateDependencyFile>false</GenerateDependencyFile>`

If this is not correct, 
a) do we need to generate and deploy deps.json in production always, or is there a scenario when we can do  away with deps.json?
b) what is the scenario where we can/should set  GenerateDependencyFile to false?

**Comment by davidfowl** [comment]
That's not correct, AFAIK you need the deps file to run. Where did you read that you don't need a deps file?

**Comment by geetmenon** [comment]
Not exactly sure. Our team had looked at several articles, stackoverflow, github in the past few weeks. Based on what we read, for our console based solution, we set GenerateDependencyFile to false in our main proj file. Deps.json did not generated (and therefore was not published). We have been able to successfully run this console based solution in production (without deps.json) for the past few weeks now. Was hoping for the same with our aspnetcore solution as well.
		
If deps.json is always required,
  a) how come we are able to successfully run my console based solution in production, without deps.json ( i.e. using a build generated with GenerateDependencyFile set to false)?
  b) what is the scenario where we can/should set GenerateDependencyFile to false? What this is property for?

**Comment by davidfowl** [comment]
I just tried this and it does work when using Kestrel so this might be specific to how the IIS hosting works. We might need to make explicit changes to make it work without a deps file. I didn't realize that we supported this in the host now.

cc @vitek-karas

**Comment by vitek-karas** [comment]
The host can start the app without `.deps.json` but it's generally not recommended. I personally don't know why SDK has the property to disable `.deps.json` generation, but I would recommend against using it.

For normal console apps, the `.deps.json` should only contain information necessary for running the app, no "Dev dependencies". ASP.NET did include the "dev dependencies" but it doesn't anymore in .NET 6: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/preservecompilationcontext-not-set-by-default

You can ask the SDK to remove the "dev dependencies" by setting `PreserveCompilationContext=false`. Either way, these are not used in any way to run the app (unless the app/ASP.NET is looking for them specifically).

Not having `.deps.json` will mean the host will blindly enumerate all `.dll` files in the application directory and use those as the "entire app". This typically means:
* Portable apps may not work (building with no RID specified will produce a portable app)
* If your app carries the same assembly as the framework, it's kind of a toss up which one will be used (the `.deps.json` carries version information for these files, but if it's not there the host will pick one without looking at the version) - could break the app.
* In .NET 6 this might actually have slightly negative impact on startup performance (since we have to enumerate the files on disk, which the .NET 6 host doesn't do if there's a `.deps.json))

The error you mention probably comes form the ASP.NET IIS Module - so if this were to be supported the change would probably have to happen there.

**Comment by geetmenon** [comment]
Thanks for the clarifications @davidfowl  and @vitek-karas! Will reset GenerateDependencyFile back to true in both our console solution as well as in our aspnetcore solution.
