### ISSUE TITLE
.NET inside browsers

### ISSUE THREAD

**Issue by AlwaysHC** [dotnet/aspnetcore#38278]
The .NET 6 efforts to make Blazor WASM small is great but even for a small app there are KBs or MBs to download. And the runtime is compressed and the warm start up on smartphones is really slow. the demo app needs more than 10 seconds to start on my phone (a redmi note 8T).
I think the only solution is to collaborate with Mozilla, Google, Opera, and the other browser producers and integrate the .NET runtime on the browser! The same that already happens for JavaScript.

**Comment by ShreyasJejurkar** [comment]
I don't think so that will happen! If .NET gets integrated with browser, then other languages will ask for same for example rust, Java, Python and browser will be bloated with this tech, and it will loose fundamental use of browsing internet!

WASM is new technology and not everyone using it extensively. 
The new proposals like WASM-GC, can really help .NET to trim its runtime size. Because with WASM-GC, the GC will be provided by browser WASM itself, and individual languages or runtime don't have to pack their GC with application.

The WASM-GC proposal - https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md

**Comment by javiercn** [comment]
@AlwaysHC thanks for contacting us.

This is not an approach we plan to take. Browser vendors won't ship a collection of third-party runtimes within their products and we don't plan to create a broken experience with different performance characteristics depending on the browser used.
