### ISSUE TITLE
Access token exhaustion when using client credentials flow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38297]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Access-token-exhaustion-when-using-clien/1578544)._

---
[severity:Other]
Hi, I am working on a .NET REST API project which can be accessed via the client credentials flow. Every time a client application invokes our API, it has to request for an access token first. 

My concern with this is that if there are thousands of API requests there will be thousands of access tokens as well. What is the best practice for this? Should the client application store an access token in a cache and only request for a new one once it has expired? Or is there a more practical solution?

---
#### Feedback Bot on 11/10/2021, 06:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
We'll need a lot more information first here.

What is your oauth setup? What's the server? AAD, Identity Server? Something else?
What are you doing for token acquisition? How is the client configured?
What's the expiry date on the tokens you're getting?

Generally we'd expect the typical oauth flow to be "Sign-in, get a long lasting token and a refresh token, cache both, use token, and use refresh token to get a new token as needed". Refresh tends to happen on failure because the contents of the token are opaque to your app (yes, JWT is a well known format, but a server may not issue you a jwt)

**Comment by josh-monreal** [comment]
Hi blowdart, here are my answers to your questions.

1. What is your oauth setup? What's the server? We are using Azure Active Directory
2. What are you doing for token acquisition? The client API sends the client Id, client secret, scope, and grant type.
3. What's the expiry date on the tokens you're getting? 1 hour, as the default expiration of an access token in Microsoft's oauth server.

Refresh tokens are not provided by Microsoft if the grant type is client credentials. Also, I am asking this question irrespective of the identity provider. I just want to ask if the best practice is to cache the access token or if there is a better approach.

**Comment by blowdart** [comment]
If you're using Azure AD might I suggest using [Identity.Web ](https://github.com/AzureAD/microsoft-identity-web) on your client apps rather than doing it manually, as it does everything you need for you, including caching (so yes, caching is the best practice here. If you want to persist it between app runs then you can look at the Windows Credential store, or Mac keychain as a place to keep it safely. Linux is, well, linux, so it's drop it in the home directory and hope!)

**Comment by josh-monreal** [comment]
Thanks!
