### ISSUE TITLE
::deep Not Working in Blazor .NET 6

### ISSUE THREAD

**Issue by bearsystems** [dotnet/aspnetcore#38339]
I have read extensively about using ::deep in order to apply CSS styles to child elements in Blazor apps.  I was using .NET 5 and then I installed VS 2022 along with .NET 6, upgrade the project to 6 and I still get an error that "::deep" is not a valid element".

None of the styles that I attempt to apply to child elements is working - I am simply modifying the MainLayout.razor.css stylesheet with the following entry:

```
.deviceWrapper, ::deep .deviceWrapper {
    border-radius: 5px;
    height: 100px;
    width: 400px;
    background-color: #f6f6f6;
    display: flex;
    justify-content: center;
    align-items: center;
    box-shadow: 0 1px 5px 0 rgba(0, 0, 0, 0.26), 0 2px 2px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.08);
}
```

And attempting to apply that to the following:

```
<div class="target-wrapper" style="width:400px">
                <div class="deviceWrapper">
                    <div class="@targetName" style="text-align:right;">
                        <span class="material-icons-outlined md-light">menu</span>
                    </div>
                </div>
</div>
```

**Comment by javiercn** [comment]
@bearsystems thanks for contacting us.

The error you are observing is likely due to Visual Studio not "knowing" about the `::deep` selector, which is specific to CSS Isolation in ASP.NET Core.

The way this works is as follows (You can see this also in the generated bundle CSS if you need to troubleshoot things).

`.deviceWrapper, ::deep .deviceWrapper` should get transformed to `.deviceWrapper[b-asdf1234], .deviceWrapper[b-asdf1234]`. I don't believe you need to use `::deep` at the top level since you aren't selecting an element.

If you hit view source, you should see something like `<div b-asdf1234 class="target-wrapper" style="width:400px">`. 

Deep is only necessary when you have descendant selectors and want to target an element within that is not the last element. For example `div ::deep p` would get transformed to `div[b-asdf1234] p`

As a next step, we would recommend you check the generated bundle file for the actual styles being generated as well as the markup generated in your app.

It is also fundamental to understand that CSS isolation works at the file level, and applies to HTML elements, so it won't apply to things like components or tag helpers.

**Comment by bearsystems** [comment]
Thank you for your response!  As it turns out, CSS Isolation does not work on popup menus, apparently even though the "popup" is presented on the same razor page - https://docs.telerik.com/blazor-ui/knowledge-base/common-css-isolation

I ended up nesting script tags directly in the Telerik control and that fixed the issue.
