### ISSUE TITLE
Virtualize scrolling is broken when using display:grid on panel and display:content on rows

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#38439]
### Describe the bug

Following code worked fine in .NET 5, but is broken in .NET 6

```css
.grid {
    display: grid;
    grid-template-columns: 1fr;
}
.grid-row {
    display: contents;
}
```

```razor
<div class="grid" style="height: 800px; overflow: auto">
    <Virtualize TItem="Item" ItemsProvider="GetItemsAsync">
        <div class="grid-row" @key="context">
            <div class="grid-cell">
                @context
            </div>
        </div>
    </Virtualize>
</div>
```
Notice that as I scroll down, I get pages in rows in wrong order: 13**, then 14** then 13**.

![screen](https://user-images.githubusercontent.com/3494407/142031284-5b7c0413-9d84-4c58-ac60-11c1dc48770a.gif)

This only happens when the item have style `display: contents;`.

### To Reproduce
1. Go to: https://blazorrepl.telerik.com/QllPPqbK57ftwhga22
2. Scroll down 50%;
3. Try to scroll slowly. You will see flickering and incorrect order or rendered items.

### Further technical details
- ASP.NET Core version 6:00

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

</details>

**Comment by Liero** [comment]
The issue seems to be deeper.

In Blazor Server Side, I often get to endless loop where placeholders are being added and removed. It happens also with display:block, not just css grid

![screen](https://user-images.githubusercontent.com/3494407/142420580-c801dfa6-71a6-4776-ab7c-fd91b0a75f3c.gif)

Repo: https://1drv.ms/u/s!An7wnk66a6RRlqg-wDpwOXehcTwARA?e=fhCxPs

I have even tried to copy sources of Virtualize component from .NET 5 branch and use in ASP.NET 6 app, but I got the same behavior.

**Comment by SteveSandersonMS** [comment]
@Liero Thanks for reporting this.

In the first case, using `display: contents` isn't something that `Virtualize` has ever supported. Doing this causes your elements to be displayed as if they aren't inside the scroll region at all. I suspect you were trying to do this because you thought of `Virtualize` as an HTML element, but it isn't - Blazor components don't create wrapper HTML elements. You can just not use `display:contents` in this case.

For the second repro, I was able to repro this when using `Overscan="0"`, but that's a rather dangerous setting as it forces the component to refresh at the exact instant that the user scrolls to its visible edge. If they leave the browser scrolled close enough to the edge, the intersection observer will continue to fire, leading to constant thrashing in the DOM. When removing the `Overscan="0"` parameter, the problem didn't occur for me. Do you have a case where the problem occurs when omitting this parameter, or using the kind of value we intended, like 5 or above?

**Comment by Liero** [comment]
@SteveSandersonMS:
the second repo and oversize count: the stone fell from my heart, I almost want to say I love you 😄 


----------------------------
Now back to `display: contents`:

The same code is working in .NET 5, so it was kind of "supported" and it is a breaking change. (I know that Virtualize does not create and an wrapper html element - aside from spacers).

You basically measure the space between spacers divs and  item wrapper element with `display:contents` should not affect the space.

I did dome debugging and the problem is, that ItemSize is not calculated correctly. 

I suspect this line gives incorrect value:
https://github.com/dotnet/aspnetcore/blob/ad46e0355613b8cfca9d401a44d9eba7004a175b/src/Components/Web.JS/src/Virtualize.ts#L87

Let me check some other ways of measuring the distance between spacers tomorrow.

**Comment by Liero** [comment]
@SteveSandersonMS: Here are my findings:

1. Workaround - wrap placeholder in display:contents element:
   ```razor
   <Placeholder>
      <div class="grid-row" @key="context">
          <div class="grid-cell" style="grid-column: 1 / -1">
             Placeholder @context.Index; Height: @context.Size
          </div>
      </div>
   </Placeholder>
   ```

2. Possible fix:

replace  ~~`const spacerSeparation = rangeBetweenSpacers.getBoundingClientRect().height; `~~

with

```javascript
const spacerSeparation = spacerAfter.getBoundingClientRect().top - spacerBefore.getBoundingClientRect().bottom;
```

Why? I have no idea, but it seems that rangeBetweenSpacers does not work as expected

**Comment by Liero** [comment]
Hi @SteveSandersonMS:

I have investigated the issue a bit more and find out that `Range.getBoundingClientRect()` is a buggy API and inconsistent across browsers (Chrome gives invalid result, Firefox always return 0).

```javascript
const rangeBetweenSpacers = document.createRange();
rangeBetweenSpacers.setStartAfter(spacerBefore);
rangeBetweenSpacers.setEndBefore(spacerAfter);
// this gives invalid results
const spacerSeparation = rangeBetweenSpacers.getBoundingClientRect().height; 

// this just works
const spacerSeparation = spacerAfter.getBoundingClientRect().top - spacerBefore.getBoundingClientRect().bottom; work
```

Is there any reason why you prefer `Range.getBoundingClientRect()`. instead of `HTMLElement.getBoundingClientRect()`?

Should I create PR that fixes this?

**Comment by SteveSandersonMS** [comment]
@Liero Unfortunately we used to use the approach you're suggesting (`spacerAfter.getBoundingClientRect().top - spacerBefore.getBoundingClientRect().bottom`), but it lead to bugs due to floating point inaccuracies when performing the subtraction. Please see https://github.com/dotnet/aspnetcore/pull/37585/files#diff-db6a898fab2100f6f6edf10fed7f4cf5861c2deb79d28f0c44ca19b7acd3d96fR82-R84.

I'm not certain what is the scenario where the new approach (`Range`) doesn't work. I understand your non-Blazor repro of a problem, but could you give a minimal Blazor `<Virtualize>` example that has a problem with this? Thanks!

**Comment by Liero** [comment]
> could you give a minimal Blazor `<Virtualize>` example that has a problem with this? 

Sure, see the REPL from my original post: https://blazorrepl.telerik.com/QllPPqbK57ftwhga22

or this even simpler REPL: https://blazorrepl.telerik.com/cmaFvYlS59Ca2dy456

**Comment by SteveSandersonMS** [comment]
Those repros seem to use `display:content`. Do you have a repro that doesn't?

I'm not sure we're going to be able to add support for `display:content` because if it requires using `spacerAfter.getBoundingClientRect().top - spacerBefore.getBoundingClientRect().bottom`, that would still break in more general cases due to floating point inaccuracies.

**Comment by Akinzekeel** [comment]
I went through a major refactoring of my grid component in an effort to make it work without the need for a `display: contents` row wrapper. Unfortunately it's still broken and I found that it's due to using popper tooltips inside the grid as well as `position: sticky` on the column headers.

**Comment by SteveSandersonMS** [comment]
There's an example of a grid at https://github.com/SteveSandersonMS/BlazeOrbital/tree/main/BlazeOrbital/QuickGrid that uses virtualization and `position: sticky` on headers ([here](https://github.com/SteveSandersonMS/BlazeOrbital/blob/main/BlazeOrbital/QuickGrid/Grid.razor.css#L7)). Not sure whether that will help.

I know it's tricky to make all this stuff work together, which I why I think the framework should include a base implementation people can build on: https://github.com/dotnet/aspnetcore/issues/37908

**Comment by Akinzekeel** [comment]
Thanks for sharing but that is a table, not a grid. Since the Virtualize component creates div elements to simulate the height and because table elements only allow some very specific child nodes, your example will technically produce invalid markup. This is ultimately the reason why I (and presumably others) used a CSS grid to begin with.

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying what you're looking for! I meant it's a grid in the sense that people call this kind of UX a grid, not in the sense of the HTML elements being used.

As far as I'm aware there's nothing specific to the approach in QuickGrid that necessitates the use of `<table>` etc, as a set of `<div>` elements with `display:table` etc would produce the same result. It's normally considered preferable to use real `<table>` (etc) elements for the purpose of guiding accessibility technologies, even if in this case we also put some invisible `<div>` elements in there (which are actually styled as `display:table-row` so it's equivalent as far as the layout engine is concerned).

You might be able to adapt the approach in QuickGrid to be structured as you want but I can't promise that for sure.

**Comment by Liero** [comment]
@Akinzekeel: Can you provide minimal codepen for your issue using `position: static`, simmilar to [mine](https://codepen.io/Lieroo/pen/XWeeVYW)? I'm about to report bug to chromium.
