### ISSUE TITLE
Core-React not started API(Server Side)

### ISSUE THREAD

**Issue by devncore-james** [dotnet/aspnetcore#38463]
I tried this step.
```
1. dotnet new react -o my-new-app
2. cd my-new-app/ClientApp
3. npm install
4. npm start in cmd
    // Api server(controller) is not listening.
    // Only started react client.
```
When running through the **Visual Studio** (IIS Express or npm), the API server also operates normally.

I want to operate from **vscode** to the server through **npm start**

**Comment by javiercn** [comment]
@devncore-james thanks for contacting us.

That's the expected behavior. You have two modes of operation (I'm assuming you are using .NET 6.0):
* You can start both things with `dotnet run` (the ASP.NET Core App will start the SPA frontend in the same way VS does)
* You can start the proxy manually with `npm run start` and start the app separately with `dotnet run`. (If we detect a running proxy we won't start a new instance)

**Comment by devncore-james** [comment]
@javiercn Thank you !!! 

```
dotnet run
```
