### ISSUE TITLE
Razor runtime view compilation via environment variable not working in .NET 6

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/aspnetcore#38465]
Runtime view compilation appears to not be working in .NET 6 Razor Pages projects when using the environment variable to specify this behavior as described here:

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio#conditionally-enable-runtime-compilation-in-an-existing-project

If I manually add `AddRazorRuntimeCompilation()` in ConfigureServices it does work though.

I'm including v6.0.0 of the assembly package:
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />`

And my launch profile has the following section:
```
"environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      }
```

Worked as expected in .NET 5 on the same project.

**Comment by davidfowl** [comment]
cc @halter73 (might be a hosting problem)

**Comment by javiercn** [comment]
@AndrewTriesToCode thanks for contacting us.

@pranavkm do you have any thoughts?

**Comment by pranavkm** [comment]
This was introduced as a result of my attempt to refactor the way action descriptors are registered for Razor. Runtime compilation requires adding a matcher policy and a different ADP, which is currently contingent on the default one being already registered: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor.RuntimeCompilation/src/DependencyInjection/RazorRuntimeCompilationMvcCoreBuilderExtensions.cs#L88-L99. This unfortunately does not happen with the env variable since the hosting startup runs before `ConfigureServices`. My guess is one way to fix it would be to reduce the check to only remove the ADP on Line 90, and do everything else all the time. 

That said, for 6.0, we intentionally removed the option of conditionally enabling runtime compilation from our project templates because we believe hot reload is a better dev time alternative. Particularly for .cshtml files, you get really high fidelity for the kinds of edits that are supported, so there generally shouldn't be a reason to require this feature.

**Comment by AndrewTriesToCode** [comment]
Thanks for the details. My experience on Mac has been that hot reload only works on non-debug runs, causes an error, and is disabled for the rest of the session. It might be due to the fact that I use Rider so I’ll try it in VS code.

**Comment by SteveSandersonMS** [comment]
@pranavkm Should this go on the backlog then? I'm putting it there but please feel free to move it if you disagree.

**Comment by solrevdev** [comment]
Can I just add that I am having the same issue except that razor runtime view compilation does not work at all for me. 

Even if I manually add `AddRazorRuntimeCompilation()` changes to cshtml files do nothing. I have to ctrl-c; dotnet run; f5;

https://github.com/dotnet/AspNetCore.Docs/issues/24111

Is there a workaround as this is such a horrible development experience?

**Comment by knoepdan** [comment]
In our Single Page App scenarios/setups, this is a crucial feature and hot reload does not replace it properly. 
I get an error: "{"ErrorCode":5000,"Message":"Error in path , ex: InvalidOperationException\r\n   System.InvalidOperationException: Cannot find compilation library location for package " when activating razor compilation in .Net 6 via Code  " services.AddControllersWithViews().AddRazorRuntimeCompilation()" not via environment variable. It's working in .Net 5. 

No matter what I tried, it just doesn't work in .Net 6. In my opinion, the extension method "AddRazorRuntimeCompilation" should either be fixed or completly removed.

**Comment by DanielRBowen** [comment]
I have a project that I have yet to update to .Net 6 because of this problem. Hot reload isn't working either. Is it because I am [debugging on IIS with VS](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2022#:~:text=Publish%20in%20Debug%20Mode%20Using%20the%20File%20System,from%20the%20dropdown.%207%20Select%20Save.%20See%20More.) that hot reload isn't working properly? If that is the case then I would like either for Hot Reload to work with when debugging with IIS or fix ```AddRazorRuntimeCompilation()```
