### ISSUE TITLE
Idea: .NET 6 Minimal Api - Set dynamic generated access modifier for "Program" class as a "public" not "internal"

### ISSUE THREAD

**Issue by djfoxer** [dotnet/aspnetcore#38474]
### Is your feature request related to a problem? Please describe.
It's only idea. It will be much easier if generated `Program` class for minimal API in .NET 6 will have `public` access modifier than `internal` (as it is now). Especially for testing with WebApplicationFactory as an inherited class (with `InternalsVisibleTo`):

```csharp
public class MyWebApplicationFactory : WebApplicationFactory<Program>
{
//
}
```

currently solution above throws error:
```
CS0060	Inconsistent accessibility: base class 'WebApplicationFactory<Program>' is less accessible than class 'MyWebApplicationFactory'
```

### Describe the solution you'd like
Generate dynamic `Program` class with `public` access modifier.

### Additional context
Current solution, add code to minimal API to change access modifier:

```csharp
#pragma warning disable CA1050 // Declare types in namespaces
public partial class Program { }
#pragma warning restore CA1050 // Declare types in namespaces
```

**Comment by davidfowl** [comment]
This is a language feature ask with ASP.NET Core minimal APIs as a motivating scenario. FWIW we discussed this and agreed that it would be internal by default and using internals visible to is the better approach. Is there a reason `MyWebApplicationFactory` can't be internal?

cc @jaredpar

**Comment by djfoxer** [comment]
Thank you for your answer. I understand your point.

> Is there a reason `MyWebApplicationFactory` can't be internal?

I used to create `CustomWebApplicationFactory` (`MyWebApplicationFactory` in this case ) as a shared context between tests in xUnit:

```csharp

public MyTests : IClassFixture<MyWebApplicationFactory>
{
    MyWebApplicationFactoryFixture fixture;

    public MyTests (MyWebApplicationFactoryfixture)
    {
        this.fixture = fixture;
    }
   //tests
}
```

In this particular scenario `MyWebApplicationFactory` can't be internal.

**Comment by davidfowl** [comment]
I see, because your test class is public, got it.

**Comment by halter73** [comment]
I know there were concerns about making the `Program` class generated for top-level statements public by default because of type conflicts when multiple assemblies with top-level statements are loaded. I imagine this would even be harder to change now. However, manually making `Program` public for testing is pretty ugly if you want to suppress `CA1050`.

```C#
#pragma warning disable CA1050 // Declare types in namespaces
public partial class Program { }
#pragma warning restore CA1050 // Declare types in namespaces
```

@AlekseyTs @jaredpar @cston Would it be reasonable to suppress `CA1050` warnings by default for `partial class Program` declarations?

**Comment by jaredpar** [comment]
That is actually an analyzer warning, not a compiler one. @mavasani, @jmarolf

**Comment by jmarolf** [comment]
In .NET 5 we shipped CA1050 as `info` and we haven't changed the default since then: https://github.com/dotnet/roslyn-analyzers/blob/6ae50529e7b88493b2591fb533ceebadc8425e1d/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md.

@halter73 can you file a separate issue on https://github.com/dotnet/roslyn-analyzers by default you should not be seeing this as a warning unless you elevated it to be that. In general I am open to having some logic introduced to making this pattern better for those that need to make their `Program` type public. modulo bugs that @halter73 may be seeing we could may make a change to disable this analyzer for types that contain entry points.

**Comment by halter73** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/5800 makes it so that the workaround of adding `public partial class Program { }` no longer requires suppressions for CA1050 with the .NET 7 SDK. I don't think there's anything left to do in ASP.NET Core.
