### ISSUE TITLE
Blazor httpcontext is renewed upon refreshing the page

### ISSUE THREAD

**Issue by yogigrantz** [dotnet/aspnetcore#38475]
### Blazor httpcontext is renewed upon refreshing the page
Using .net core 6 / Blazor application, when I refresh the page, the httpcontext is renewed. This causes losing the claims, user identity, cookies, and sessions. Current workaround is to use Blazorized.LocalStorage 

### To Reproduce

https://github.com/yogigrantz/BlazorApp1

download the solution and open in VS2022 and run it.

1. Login with demo / demo -> it would take you to the weather page. 
2. Click on Login link on the menu -> It would say that you are authorized. That's good.
3. Go back to weather page, it still say that you are authorized. That's good
4. Set a breakpoint in FetchData code (OnInitializedAsync) before line 15
5. Refresh the page 
6. Step into line 15 to authorize the httpcontext, and it could not authorize because the claims are gone

Since the claims are gone, this statement: 

if (httpContextAccessor.HttpContext.User.Claims.Any(x => x.Type == "role" && x.Value == role))

would not find any claims

### Further technical details
- ASP.NET Core version: 6
- The IDE : VS 2022 on PC
- Dependency injection: HttpContextAccessor

**Comment by javiercn** [comment]
@yogigrantz thanks for contacting us.

That's by design. Blazor sessions are tied to the current session, so if you refresh or navigate away from the page, the session is lost, a new Http request is initiated and that request might not contain what you expect.

Also it is discouraged to use HttpContextAccessor within Blazor. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#blazor-and-shared-state for details
