### ISSUE TITLE
Multiple jwt authentication schemes are not working

### ISSUE THREAD

**Issue by zhangpengchen** [dotnet/aspnetcore#38498]
**Describe the bug**
When multiple JWT authentication schemes are used, except for the bearer scheme, the rest always fall into 401.

**To Reproduce**
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(ConfigureJwtBearer.CreateJwtBearer(env, settings, "authority 1"))
    .AddJwtBearer("Bearer2", ConfigureJwtBearer.CreateJwtBearer(env, settings, "authority 2"))
    .AddJwtBearer("Bearer3", ConfigureJwtBearer.CreateJwtBearer(env, settings, "authority 3"));

**Further technical details**
https://github.com/dotnet/aspnetcore/blob/f993b272df3187500f5afef52dc9a726118cfbc0/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L81 The bearer scheme is being considered, but not the one that was defined. such as Bearer2, Bearer3.

Related issue: https://github.com/dotnet/aspnetcore/issues/26002

**Comment by blowdart** [comment]
Rather than have 3 middlewares like this what happens if you have a single instance of jwtbearer but set the [token validation parameters](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters?view=azure-dotnet) to have multiple allowed issuers through the ValidIssuers property? Or do they have different keys etc?

If they're all on different keys you could use a [policy scheme](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/policyschemes). You'd use the forwardselector inside the default auth scheme to switch to one of the others based on issuer, but this does mean parsing the jwt without validation to yank the issuer out. This isn't so bad because whatever scheme it ends up in will perform full validation anyway.
