### ISSUE TITLE
Restore and build only for specific feature areas

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#38533]
For example, don't need to build ANCM if we aren't going to run on IIS

**Comment by dougbu** [comment]
I missed part of the meeting this morning and would like to understand this issue a bit better. For one thing, `-restore` is already selective e.g. `.\eng\build.cmd -Projects .\eng\tools\BaselineGenerator\BaselineGenerator.csproj` does the usual .NET installations, builds `RepoTasks` (which is almost-always required), builds native projects, then builds `BaselineGenerator`. But, it doesn't restore anything else and the first two parts of the process can be disabled w/ `-noBuildRepoTasks` (which is dangerous) or `-noBuildNative` (which is usually safe unless you need ANCM).

If the issue is the `dotnet-install` checks after the initial downloads, there's nothing for us to do here. The build is split into 3 phases i.e. _cannot_ be done in fewer phases (without always building using desktop `msbuild` on Windows, slowing things down) and Arcade insists on checking for newer runtimes in all of those. Fortunately, the checks are pretty quick w/ most hardware.

If the issue is the native build, would it suffice to do one or all of the following❔

1. Highlight `-noBuildJava`, `-noBuildNative`, and similar eng/build.* options more in our documentation
2. Add `-noBuildNative` to a bunch of our src/**/build.* scripts
3. Ensure Microsoft.AspNetCore.App.Runtime.csproj builds fine on Windows x64 w/o a preceding native build (this may already be the case)

**Comment by Tratcher** [comment]
More project specific builds could enable `-noBuildJava -noBuildNative` by default since almost no projects depend on those. E.g. https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/build.cmd doesn't need native IIS or Java.

**Comment by wtgodbe** [comment]
It looks like area-specific `build.cmd` scripts like the one @Tratcher linked above _already_ don't build java/native projects by default, by virtue of passing `-Projects` to `eng\build.cmd` (which would include native/Java projects in the default case of being called without that arg, but defers to the explicit list of projects passed in when available) - so I'm not sure there's more to do here. @dougbu thoughts?

**Comment by dougbu** [comment]
If build.cmd files where the desktop `msbuild` sub-step causes frustration all use `-projects`, we should be good. The opposite unfortunately isn't true and we may need to add `eng\build.cmd -buildNative` commands in e.g. src/Servers/build.cmd and src/Servers/IIS/build.cmd.

Note adding `-buildNative` to commands containing `-projects` changes the `-projects` interpretation, basically assuming the specified project is a `*.vcxproj` and (usually) disabling the managed build.

**Comment by mkArtakMSFT** [comment]
@dougbu , @wtgodbe what is the state of this issue? Should it be closed or moved forward to .NET 8 planning / .NET 7 RC2 ?

**Comment by wtgodbe** [comment]
I did a brief audit of these back in February and didn't see any that needed to be updated - I'll do another pass in the RC1 time frame to make sure we're still good.

**Comment by wtgodbe** [comment]
I believe we're good here.
