### ISSUE TITLE
Model validation for non-nullable array elements

### ISSUE THREAD

**Issue by pmaga** [dotnet/aspnetcore#38548]
Non-nullable reference types get implicit [Required] attribute, but this attribute does not work with array elements.

In [ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#non-nullable-reference-types-and-required-attribute) we see this statement:
`The validation system treats non-nullable parameters or bound properties as if they had a [Required(AllowEmptyStrings = true)] attribute. By enabling Nullable contexts, MVC implicitly starts validating non-nullable properties or parameters as if they had been attributed with the [Required(AllowEmptyStrings = true)] attribute.`

It's awesome, but it's not enough to guarantee valid state in a nullable context.

### To Reproduce
`<nullable>enabled</nullable>`
`SuppressImplicitRequiredAttributeForNonNullableReferenceTypes` flag is disabled by default:
`services.AddControllers(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = false);`

Let's take the following example:

```
public class Request
{
    public List<string> Strings { get; set; }
}
```

```
[HttpPost("test")]
public IActionResult Test(Request command)
{
    var isValid = ModelState.IsValid; // returns true
    return Ok();
}
```

Payload:
```
{
  "Strings": [
    null
  ]
}
```

In result, there is no validation error, response status is 200 OK, and we have a null item in the array of not-nullable elements.

### Further technical details
- ASP.NET Core version: 6.0.0

It's very nice that there is such a default behavior, but since it is enabled by default, I would like to trust with full confidence that it will work in any case. 
Do you have a plan to improve this validation? This is the typical entry point to an application and it is strange that there is such a flaw in this simple use case.

**Comment by captainsafia** [comment]
So, as mentioned in the referenced doc, support for the nullability context works by adding the `Required` attribute to types that are marked as non-optional via their nullability annotations. The `Required` value only checks on the top-level property to ensure that it is not null or empty (aka the List of strings) and not the items with it. If you wanted this behavior, you can achieve it by writing your own attribute like so:

```csharp
public class ContainsNull : ValidationAttribute
{
  public override bool IsValid(object val)
  {
     return val.Count(i => i is null) == 0;
  }
}
```

@pranavkm Thoughts on this? It feels like we don't need to add support in the framework for this.

**Comment by pranavkm** [comment]
One of the reasons we'd initially punted on this was because there isn't a way in C# to annotate generic type parameters i.e. you couldn't have expressed that items in the array or collection are required using attributes. That said, not enforcing that collection items are required does mean user code is now prone to null reference exceptions:

```C#
public IActionResult Post(List<Product> products)
{
  foreach (var product in products)
  {
    // The compiler will tell me product is guaranteed to be non-null here
    // But if we went product.ToString(), it's possible to null ref.
   } 
}
```

It would certainly be nice if we could try and address it, for e.g. by synthesizing the `ContainsNill` validation attribute and adding it as part of creating ModelMetadata.

**Comment by captainsafia** [comment]
So, I took a stab at implementing this in the linked PR above and we had a lengthy discussion about how to implement these feature fully. Here's a summary of what was covered.

**Supporting interface implementations**
For this feature to work in meaningful scenarios, we'll wan to support scenarios where as user leverages a collection type directly in a model.

```csharp
public class MyModel
{
  public List<string> Foo;
}
```

And where the user references an interface implementation, like so:

```csharp
public class MyCollection : IList<string> { }
public class MyModel
{
  public MyCollection Foo;
}
```

**What collection types are supported**
For this feature, we'll want to consider what collection types are supported (`ICollection`, `IList`, `IEnumerable`). Depending on how expansive the support is, we might run into tricky issues with the implementation (e.g. for all `IEnumerable` types).

**Opt-in vs. opt-out behavior**
This behavior might be surprising to users, particularly those who are using collection types with nullability enabled that are defined in a separate assemblies. To that end, we should have an option to opt-in or opt-out of the behavior. During our conversations, we leaned towards opt-in but this results in a weird misalignment with the opt-out behavior for the `Required` attribute.

Because there's a lot of subtleties to the implementation and because there isn't a lot of user interest in the issue at the moment, we are punting to the backlog.

**Comment by captainsafia** [comment]
Per a conversation with @rafikiassumani-msft, to be disciplined with our backlog I'm going to close this issue as there is (a) not a ton of community interaction (b) a viable workaround and (c) notes and a partial implementation for our future selves.

In the event that this issue crops up more seriously in the future, we can use it then.
