### ISSUE TITLE
Razor component wrong format.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38603]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-component-wrong-format/1592281)._

---
[severity:It bothers me. A fix would be nice]
I created a new Blazor server app using . NET6.

On one page i use a `<InputDate>`... component (see picture below).
When i try to format the date as format="yyyy-mm-dd" an exception occurs.

When i use the `<input>`.. instead it works correct. 

![image.png](https://aka.ms/dc/image?name=Bbb8a553428494d6b9d4ae6af8e612a32637731898262943120_20211122-155705-image.png&tid=bb8a553428494d6b9d4ae6af8e612a32637731898262943120)

![image.png](https://aka.ms/dc/image?name=Bf738bda63a2b46e0b8a38887e669071f637731914465411257_20211122-162404-image.png&tid=f738bda63a2b46e0b8a38887e669071f637731914465411257)

---
#### Feedback Bot on 11/22/2021, 03:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SteveSandersonMS** [comment]
The issue here is that an `<InputDate>` component maps to an HTML `<input type=date>`. This is a standard HTML element type that does *not* support choosing a custom date format. Instead, the browser picks whatever is the normal date format in your user's locale.

This isn't something Blazor can control, since we don't control how HTML's `<input type=date>` works. If you need to implement something different, please continue use a plain `<InputText>` or `<input type=text>` and handle the formatting and parsing in your own code.
