### ISSUE TITLE
Ability to cache pages with antiforgery forms?

### ISSUE THREAD

**Issue by aloksharma1** [dotnet/aspnetcore#38642]
hey guys,
I have an issue with anti forgery forms and response caching, basically I have a front facing site with **newsletter subscriber form** on all pages (using component view). Now due to anti forgery token I get error warning that page cannot be cached; is there any way to bypass it. If I load this common newsletter form from ajax or do a caching on it will it go away?

what's the best way or alternative approaches in these scenarios; with less coding efforts to apply on whole lot of pages.

**`The 'Cache-Control' and 'Pragma' headers have been overridden and set to 'no-cache, no-store' and 'no-cache' respectively to prevent caching of this response. Any response that uses antiforgery should not be cached.`**

i am using net 5

**Comment by javiercn** [comment]
@aloksharma1 thanks for contacting us.

It's not advisable that you mix antiforgery with caching. Otherwise your request token is trivially guessable and you effectively open yourself to CSRF attacks (all that provided that you set the cookie on each request to prevent antiforgery to fail)

You might be better off using a small amount of JS to trigger the form submit in this case to an API that only accepts JSON to avoid having to deal with antiforgery.

**Comment by aloksharma1** [comment]
> You might be better off using a small amount of JS to trigger the form submit in this case to an API that only accepts JSON to avoid having to deal with antiforgery.

can you give me a basic example of this? also what if I don't want to loose csrf protection is there no way to partially cache these pages for performance?
