### ISSUE TITLE
Clarification on AuthenticateResult.NoResult vs AuthenticateResult.Failure

### ISSUE THREAD

**Issue by chrischu** [dotnet/aspnetcore#38685]
I have a question about the different types of `AuthenticateResult`, especially when to use which result. It makes sense to use `Success` when authentication is successful and `Failure` when it is not, but what is best in the following cases?

The context: I have a web application that has some tenanted routes that need authentication (those routes contain the tenant ID) and some who are untenanted (and therefore need no authentication). The authentication handler is triggered on both routes, for the first case (tenanted routes), but what result should I return if the handler encounters an untenanted route? Instinctually I would say `AuthenicateResult.NoResult` seems reasonable, but I'm not 100% sure.

And also there's another case I'm not 100% sure on: when on an tenanted route and I cannot find any credentials, would it be best to return `Failure` or `NoResult`? Here I would instinctually say `Failure` but maybe that should only be used when someone actually supplied credentials?

Maybe a more general question: what is the behavior when returning `NoResult`?

Thanks in advance!

**Comment by blowdart** [comment]
The reason there is both a `Failure` and a `NoResult` is because multiple authentication handlers can parse a requirement. `NoResult` indicates "I can't fulfill the requirement, so let someone else have a go". 

For example, if I have a "CanEnterBuilding" requirement there could be multiple ways to validate that, the user might be an employee, the user might be a guest, the user might have a day pass and so on. Each of those ways to fulfill the requirement can be different handlers, each one returning `NoResult` so the other handlers might check. If a single handler returns `Success` then the requirement is fulfilled. 

`Failure` on the other hand denies other handlers from having a chance to fulfill the requirement (they'll still run, because folks like to log stuff or have other side effects in their requirements, but even if they succeed the handler that returns `Failure` is going to win out). So for my building example the building might have a status check someone of "IsBuildingOnFire". A handler checks if the building is on fire, and returns `Failure` to stop anything else letting someone in.
