### ISSUE TITLE
blazor will auto add tag in img or css but with it added in JS it will not?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38709]
In blazor webassembly if I write a css:
```
.amap-icon img
    width: 33px;
    height: 33px;
}
```
it will auto add the tag to the `img`
`.amap-icon[b-sj224auzm2]`
but if the `img` is added in `js` it will not have the `tag` so can not use the css

how to do it?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Scoped CSS isn't supported for dynamic components.
We'lll park this feedback in backlog for now to accumulate more feedback about this and see whether there is enough evidence to warrant more thinking in this area.

**Comment by mcguu** [comment]
@mkArtakMSFT  then there is a solution for this?
I think I have to add a [filter] to do it.
`.amap-icon[*]` then it will work.

but it is not a good code.

**Comment by mcguu** [comment]
@mkArtakMSFT  you say it is not supported for dynamic components .

what about not compoents？ 

I am a newbie and I find that If I want to add a page I have to add component right?

**Comment by mkArtakMSFT** [comment]
Sorry for not getting back to you on this earlier - I have too many notifications on GitHub and am unable to keep up with all of them. My response at this point is probably not relevant any more since so much time have passed.
Anyway, by `dynamic component` in this particular case I was referring to the `img` tag added via JavaScript code (dynamically).
You could have moved the logic from JavaScript to Blazor and condition rendering the image based on some boolean field, which could have been set via JS-interop, if necessary. That way, the image tag would get the appropriate styles from scoped CSS file.

At this point, given that we've received no similar feedback and engagement from the community, I'm closing this issue.
