### ISSUE TITLE
asp.net .net 6: Unauthorized access returns 403 instead of 401

### ISSUE THREAD

**Issue by Maurik77** [dotnet/aspnetcore#38718]
### Unauthorized access returns 403 instead 401
After the migration to .net 6, our unit tests have identified that the unauthorized access, using the AuthorizationAttribute and identity role claims, returns the http status 403 (forbidden) instead of 401 (unauthorized)  as with .net 5.
It’s a breaking change, because many clients could not manage the unexpected result, and it seems **undocumented**.

### To Reproduce
- The repro project is attached as a `.zip` file. [WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/7626046/WebApplication1.zip)
  -  Just changing the target framework, from 5 to 6 and vice versa, the http result code changes. 

### Further technical details
- ASP.NET Core version

**Comment by adityamandaleeka** [comment]
@HaoK Can you please take a look at this repro?

**Comment by HaoK** [comment]
@Maurik77 can you upload your repro app to a github repo, we generally don't open zip files

**Comment by Maurik77** [comment]
> @Maurik77 can you upload your repro app to a github repo, we generally don't open zip files

Of course, but I suggest you to change the instructions that appear when you open an issue

**Comment by HaoK** [comment]
Thanks for the repo, could you provide some concrete steps to demonstrate the difference 403/401 with this app on 5.0 vs 6.0

**Comment by Maurik77** [comment]
Hi @HaoK ,
Fist step:

1. After downloading the repo the project is set to **net6.0** (RepoBugs\WebApplication1.csproj)
2. Run the project
3. Execute: curl https://localhost:5001/weatherforecast -v
4. You can verify that the app replies with  http status **403** (Forbidden)
5. Change the target framework to **net5.0**
6. Run again the project
7. Execute: curl https://localhost:5001/weatherforecast -v
8. You can verify that the app replies with  http status **401** (Unauthorized)

**Comment by HaoK** [comment]
Thanks, I do see what you are seeing, its strange that this was a 401 in 5.0, as the correct behavior is 403 and we have a unit test that's been there since 5.0 too https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Security/Authorization/test/AuthorizationMiddlewareTests.cs#L372

I'll try to see where the difference is

**Comment by HaoK** [comment]
Okay I see the issue, in your auth handler, you are creating an identity that is not considered authenticated since you don't specify an authentication type, this is line: https://github.com/Maurik77/RepoBugs/blob/main/HermodrAuthenticationHandler.cs#L29

You can verify this by checking identity.IsAuthenticated, you can pass in anything like `new ClaimsIdentity("foo");` which will make the behavior be a 403 as expected.  

I'll try to track down what side effects might have changed to cause this minor difference in behavior

**Comment by Maurik77** [comment]
Okay, thank you for the analysis, the problem ca be fixed, but anyway I suggest to describe the different behaviour in the
[Api Diff Doc](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/api-diff/rc1/README.md) or some other official documentation because the upgrade can lead to an unexpected result.

**Comment by HaoK** [comment]
Okay, I think I found the introduction of this behavior/breaking change, as this was the only change that seems related to IsAuthenticated, was this change which now does some caching around the default authenticate result based on whether the user identity is authenticated:

https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L77

cc @Tratcher @blowdart @BrennanConroy 

clearing milestone so this is visible in triage

**Comment by HaoK** [comment]
Discussed this in triage, since the subtle change of behavior is in a scenario which isn't really useable in practice (auth handlers that return principals that are IsAuthenticated, since they won't be useable otherwise).  We don't plan on fixing this.  The workaround for anyone that hits this, is to always set the authenticationType on their claims identities so IsAuthenticated will be true.
