### ISSUE TITLE
Consent cookies in Blazor Web assembly throwing errors

### ISSUE THREAD

**Issue by Lingala-Joshna** [dotnet/aspnetcore#38723]
### Describe the bug
When we add consent cookies in Blazor web assembly application in .net6, throws console errors

### To Reproduce
1. Download the sample
2. Unzip the downloaded file
3. Run the sample
4. Open console in the browser, the error can be found

[BlazorWebAssembly.zip](https://github.com/dotnet/aspnetcore/files/7626538/BlazorWebAssembly.zip)

### Further technical details
- ASP.NET Core version: net6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022

**Comment by pranavkm** [comment]
Could you share a repro as a GitHub repo instead of a zip file? Thanks!

**Comment by Lingala-Joshna** [comment]
Hi Pranav,

Please find my GitHub repo 

https://github.com/Lingala-Joshna/BlazorWasmConsentCookies

Regards,
Joshna

**Comment by pranavkm** [comment]
Thanks for sharing the repro app. Blazor WebAssembly is running in the browser and as such cannot ASP.NET Core features such as the HttpContext / IHttpConextAccessor. Consider directly setting a cookie rather than using the consent feature.

Also note that ASP.NET Core 2.2 has been out of support for some time now. Using the 2.2 packages in your application is not recommended.
