### ISSUE TITLE
[AspNetCore.Identity] CreateAsync without validation

### ISSUE THREAD

**Issue by zgid123** [dotnet/aspnetcore#38791]
### Is your feature request related to a problem? Please describe.
I am trying to create a user record whose data are invalid with default configuration. I wonder there is a solution to save this data without validation or not.

```cs
await userManager.CreateAsync(user, builder.Configuration.GetValue<string>("Config:AdminPassword"));
```

Say, my default validation for password is: `PasswordRequiresNonAlphanumeric;PasswordRequiresLower;PasswordRequiresUpper`

But I wanna create some accounts with password that is not followed to those rules. But it seems currently I cannot do it with `UserManager.CreateAsync` (this is only example, I wanna create some special accounts without following the validation rules)

### Describe the solution you'd like
I think we can have a parameter called `validate` (default true), if we set false, when creating a record, we skip the validation.

```cs
await userManager.CreateAsync(user, builder.Configuration.GetValue<string>("Config:AdminPassword"), validate: false);
```

### Additional context
I am using `AspNetCore.Identity.EntityFrameworkCore 6.0`, if there is a solution for this, please tell me that

**Comment by HaoK** [comment]
There's no way to bypass validation on a call by call basis using the userManager.Create apis, that's by design, as its contract is that all users will be 'valid' as defined by the IUserValidators registered in DI.  If you want to bypass this selectively, you could directly insert users using the UserStore apis, but you will need to mimic the behavior inside of Create, so you could derive your own userManager.CreateWithoutValidation and do this if you wish, but this isn't something that we will add to the framework
