### ISSUE TITLE
CSS isolation does not work when Razor runtime compilation is enabled

### ISSUE THREAD

**Issue by safarviktor** [dotnet/aspnetcore#38889]
### Describe the bug
CSS isolation's unique HTML attributes are not added to the HTML elements *during build time* when Razor runtime compilation is enabled.

Note, this is different to #33446 although it is mentioned at the bottom for net6-preview.

### To Reproduce

1. new Web App with MVC
2. add `Index.cshtml.css` to the `Home/Index.cshml`
3. add a piece of css, eg. `h1 { color: red; }`
4. ensure `Views/Shared/_Layout.cshtml` contains `<link rel="stylesheet" href="~/{assembly name}.styles.css" />`
5. run the app
6. the Welcome title is rendered in red, the H1 element contains the "unique" attribute
7. stop the app, install `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`
8. in `Program.cs` append `AddRazorRuntimeCompilation()` to `builder.Services.AddControllersWithViews()`
9. run the app
10. the Welcome title is not rendered in red, as the H1 element is missing the "unique" attribute

PoC on Github: https://github.com/safarviktor/CssIsolationTest

### Further technical details
- ASP.NET Core version: 6.0.100 x64 SDK
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 v17.0.1
- Include the output of `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
I suspect that we don't capture the necessary information for this to happen (if at all), since the CSS scope is computed as part of the initial compilation.

There are a couple of things to consider here:
* Changes to existing views with existing scoped CSS files, this could potentially work since we have all the information available.
* Adding a brand new view with an associated scoped CSS file. This won't work since the MSBuild pipeline is not involved in the build.
* Adding a scoped CSS file to an existing view. Same comment as for the point above.

In general I don't think we will make this work. Doing so involves a lot of work and we don't think the effort or the maintenance cost are worth it. During development we think HotReload is a much better approach for this scenario. In production, we wouldn't recommend using runtime compilation (even though some folks have done it in the past).

In general, for runtime compilation the expectation is that no MSBuild based feature will work since that would force us to replicate the MSBuild pipeline at runtime, which is not something we plan to do.

/cc: @pranavkm in case you have thoughts.
