### ISSUE TITLE
The purpose to add `app.UseAuthorization()` middleware when using a default template to create a none-Authentication application

### ISSUE THREAD

**Issue by Dillion132** [dotnet/aspnetcore#38887]
### Describe the bug

As we all known, Authentication Middleware (UseAuthentication) attempts to authenticate the user before they're allowed access to secure resources. And the Authorization Middleware (UseAuthorization) authorizes a user to access secure resources. When we enable the authorization, we should add `app.UseAuthentication()` and `app.UseAuthorization()` middleware, and should keep the order. 

But for the default template, if we select the None Authentication Type, why it will auto add the `app.UseAuthorization()` middleware in the startup.cs file? Can anyone tell me the purpose to add this middleware when using the default template and non-authentication?

### To Reproduce

For example, using the Asp.net core Web App (Model-View-Controller) creates a new application and selects the None Authentication Type,

![image](https://user-images.githubusercontent.com/16394302/145165517-dae456f9-fd21-4743-b3e1-bcf7d8fc1c5b.png)

Then in the startup.cs file, we can see it already add the `app.UseAuthorization();` middleware:

![image](https://user-images.githubusercontent.com/16394302/145165897-f4798a4c-5256-460f-aada-83ecdf294781.png)

### Further technical details
- ASP.NET Core version: Asp.net core 3.1, Asp.net 5, Asp.net 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019, VS 2022
</details>

**Comment by pranavkm** [comment]
Starting in 3.1, endpoint routing replaced a few MVC constructs including replacing auth filters with the AuthorizationMiddleware. So you would need the middleware any time you happen to be using MVC. Particularly because you could have authorization rules that do not require a user to be authenticated. For instance, `RequireHttpsAttribute` is an auth filter that requires a resource is only allowed over a TLS connection. You could conceive of other auth requirements that are based on the HTTP request characteristics rather than the logged in user.
