### ISSUE TITLE
Better way to detect "Failed to start the HttpConnection before stop() was called."

### ISSUE THREAD

**Issue by angelaki** [dotnet/aspnetcore#38893]
I'm using some client side SignalR-Services that get disposed, as soon as the component utilizing it gets destroyed.

Right now my code looks like this:

```
this.hubConnection.start().then(_ => {
    this.initializeConnection();
    this.isConnected$.next(true);
}, e => {
    if (e.message !== 'Failed to start the HttpConnection before stop() was called.') { throw e; }
});
```

This default catch-behavior is pretty unclean - but I quite common case I'm not interested in. It would be nice if this error could be detected _cleaner_ somehow.

**Comment by halter73** [comment]
@angelaki Is the complaint that you have to compare against the error message determine if `stop()` being called was the reason for the `start()` failure? Or is it consuming the promise with `.then()` that's annoying?

If it's comparing against the error message that's the problem, I agree that seems fragile. We could update the message at any point. We should probably consider making it an [AborttError](https://docs.microsoft.com/en-us/javascript/api/@microsoft/signalr/aborterror?view=signalr-js-latest) instead of a generic error so you can do an `instanceof` check.

In the meantime, could you check some other state to see if you already called `stop()` on the connection without looking at the error message?

```js
this.hubConnection.start().then(_ => {
    this.initializeConnection();
    this.isConnected$.next(true);
}, e => {
    if (!this.wasStopped) { throw e; }
});
```

I'm hesitant to define a bunch of different Error types to assist managing control flow based on the type of exception thrown. To me, this feels analogous 

If it's the `.then()`, could you switch to this being async?

```js
(async function() {
    try {
        await this.hubConnection.start();
        this.initializeConnection();
        this.isConnected$.next(true);
    } catch (e) {
        if (e.message !== 'Failed to start the HttpConnection before stop() was called.') {
            throw e;
        }
    }
})();
```

**Comment by angelaki** [comment]
@halter73 Thank you for even mentioning both possible complaints! Since I come from rxjs the `.then()` method is absolutely ok for me. Could even wrap it in an observable, but that feels redundant and probably is less performant.

Yeah, it was about the error just being a string and so can possibly change at any time. Your work-around looks quite nice for me. But yes, why not using concrete error classes? Do you mind the client-size? What sure is a valid argument! Guess it's an 
individual opinion to use or not to use them. But imho a `FailedToStartBeforeStoppedError` (inheriting from AbortError?) without message is smaller and somehow _handier_. Not more beautiful for sure - one has to die one death.

**Comment by halter73** [comment]
I'm not sure I want to add more error types like `FailedToStartBeforeStoppedError`. Is there any other way to abort `start()` other than calling `stop()`? `start()` doesn't take anything like a CancellationToken, so I don't think so. If not, let's just change it from `Error` to `AbortError`.

@angelaki Would you be interested in submitting a PR with this change? There are a few async operations during `start()` that could be canceled by `stop()`.

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L250

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L401-L405

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L142-L149

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L150-L155

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L299

I think that covers it. I don't think you can test all these conditions since some of them depend on the order multiple awaiters to the `_startInternalPromise` run in which is hard to control. But it should be possible to use `TestHttpClient` and `TestTransport` to delay the completion of negotiation and transport selection until after you call stop() in [HttpConnection.test.ts](https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/tests/HttpConnection.test.ts) and delay completion of the hub handshake with a `TestProtocol` in [HubConnection.test.ts](https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/tests/HubConnection.test.ts).

There are already some tests that do this without checking the error type thrown from `start()`.

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/tests/HttpConnection.test.ts#L164-L166

https://github.com/dotnet/aspnetcore/blob/73db5e40bbdeb4f04e5e05b9090f253760d1e1ee/src/SignalR/clients/ts/signalr/tests/HubConnection.test.ts#L391-L394

**Comment by angelaki** [comment]
Yeah sure, I can check this. But ... If I'm not mistaken it's only replacing the `Error` by your specific `AbortError`? Since you already mentioned all the occurrences, wouldn't it be easiert to already create that PR? Guess I'm mistaken 😉

**Comment by halter73** [comment]
@angelaki Don't feel obligated. There's a little more work to make sure we're testing all the abort scenarios we can, and it's always nice to have another pair of eyes making sure all the places we abort start() with stop() are covered. The notes I left are for whoever ends up taking it. It may be me 😄
