### ISSUE TITLE
Adding new MediaType to NewtonsoftJsonInputFormatter doesn't work

### ISSUE THREAD

**Issue by NCC1701M** [dotnet/aspnetcore#38911]
### Describe the bug
I'd like to add a new MediaType to the `MvcOptions` input formatter in .Net 5 

When I do the following
```csharp
services.AddControllers();

services.Configure<Microsoft.AspNetCore.Mvc.MvcOptions>(options =>
{
	options.InputFormatters
 .OfType<Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter>()
 .First()
 .SupportedMediaTypes
 .Add(new Microsoft.Net.Http.Headers.MediaTypeHeaderValue("application/csp-report"));
});
```

everything works fine. But I want to use Newtonsoft.Json instead of the default Json-Serializer so I changed my code to

```csharp
services.AddControllers()
		  .AddNewtonsoftJson();

services.Configure<Microsoft.AspNetCore.Mvc.MvcOptions>(options =>
{
	options.InputFormatters
 .OfType<Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter>()
 .First()
 .SupportedMediaTypes
 .Add(new Microsoft.Net.Http.Headers.MediaTypeHeaderValue("application/csp-report"));
});
```

But now every time a `application/csp-report` is send to the controller I get a 415 Status code.

### Further technical details
- ASP.NET Core version: 5.0.12 (running in a devcontainer)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VSCode 1.62.3
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

</details>

**Comment by brunolins16** [comment]
@NCC1701M, the `AddNewtonsoftJson` method will add two input formatters (`NewtonsoftJsonInputFormatter` and `NewtonsoftJsonPatchInputFormatter`) and when you are calling the `OfType<NewtonsoftJsonInputFormatter>` both are returning, but because you are selecting the first one, that will be always `NewtonsoftJsonPatchInputFormatter` that ended up being configured with your new media type not the `NewtonsoftJsonInputFormatter` that you expected.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.newtonsoftjsoninputformatter?view=aspnetcore-6.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.newtonsoftjsonpatchinputformatter?view=aspnetcore-6.0

**Comment by NCC1701M** [comment]
@brunolins16 Thanks, thats the solution
