### ISSUE TITLE
[.NET 6 Blazor server] 'Exceeded the maximum byte array transfer limit for a call' when transfer byte array from js to c#

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#38941]
Hello guys, i juste migrate my blazor server app from .NET 5 to .NET 6.

Now i try to profit of the improvement and i face problem on the way we can transfer byte array from js to c#.

from c# to js i don't have many problems (i use stream) but from the other way i have a fatal exception

this is the stack
````
blazor.server.js:1 [2021-12-10T12:30:11.816Z] Error: System.ArgumentOutOfRangeException: Exceeded the maximum byte array transfer limit for a call. (Parameter 'data')
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.ReceiveByteArray(Int32 id, Byte[] data)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ReceiveByteArray(JSRuntime jsRuntime, Int32 id, Byte[] data)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass44_0.<ReceiveByteArray>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.ReceiveByteArray(Int32 id, Byte[] data)
````

i already change the MaximumReceiveMessageSize parameter at startup
````
.AddHubOptions(o =>
                {
                    o.MaximumReceiveMessageSize = 100 * 1024 * 1024; // 100MB;/
                });
````

with the 64based string representation , i don't have this problem (the document i transfer is not more than 1Mb)

i send on this manner
`myComponent.invokeMethodAsync("OnDocumentSigned", lSignedDocByteArray);`
and receive
```
[JSInvokable]
        public async Task OnDocumentSigned(byte[] pDocumentSigned)
```

You have an idea on this ?

thanks !

**Comment by TanayParikh** [comment]
Hello, thanks for contacting us, this appears to be due to https://github.com/dotnet/aspnetcore/issues/38205. 

> i already change the MaximumReceiveMessageSize parameter at startup

This is **highly discouraged**. Having the `MaximumReceiveMessageSize` this large (100MB) can create security issues.

cc/ @BrennanConroy should we add a note to https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#configure-server-options discouraging (very) large `MaximumReceiveMessageSize`?

The recommended technique is just to use streaming for your JS to .NET calls. Please see https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#stream-from-javascript-to-net for more information.
