### ISSUE TITLE
SignalR connection failed when not on localhost

### ISSUE THREAD

**Issue by 3DSX** [dotnet/aspnetcore#38976]
Using Blazor as the client. NET 6 on both client and server.

I've already been trying any possible workaround for hours to this and I'm stuck.
The clientside and serverside are on the same server (wasm backed) but the thing It doesn't work when it tries to connect to the server through a remote domain, not localhost, which worked on the development stage.

I've been wondering about CORS but I have my CORS properly set and still the same, even if I call the AddAuthentication method. Also, I have tried to enable the Websocket service in additional features at IIS. Note I'm running this on the server with dotnet publish.

**Client-side console:**
[![enter image description here][1]][1]

**Client-side websocket details:**
[![enter image description here][2]][2]

Relevant server-side settings on server that may affect this:

In appsettings.json:

        {
      "Kestrel": {
        "EndPoints": {
          "Http": {
            "Url": "https://0.0.0.0:443"
          }
        }
      },

In Startup/Program

    // CORS (before SignalR)
    builder.Services.AddCors(options =>
        options.AddDefaultPolicy(builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
    
    //Add SignalR
    builder.Services.AddSignalR(opt => { opt.EnableDetailedErrors = true; opt.HandshakeTimeout = TimeSpan.FromSeconds(120); }); ;
    builder.Services.AddResponseCompression(opt =>
        {
            opt.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] { "application/octet-stream" });
        });

    // SignalR response compression
    app.UseResponseCompression();
    
    // log requests statuses in console
    
    if (true)
    {
        app.Use(async (context, next) =>
        {
            await next.Invoke();
            Console.WriteLine(
                $"{DateTime.Now.Hour} : {DateTime.Now.Minute} : {DateTime.Now.Second} - response: {context.Response.StatusCode}");
        });
    }
    
    // Handles exceptions and generates a custom response body
    app.UseExceptionHandler("/errors/500");
    
    
    // Handles non-success status codes with empty body
    app.UseStatusCodePagesWithReExecute("/errors/{0}");
    
    app.UseHttpsRedirection();
    
    app.UseBlazorFrameworkFiles();
    app.UseStaticFiles();
    
    // CORS
    app.UseCors();
    
    app.UseRouting();
    
    app.UseAuthentication();
    app.UseAuthorization();
    
    app.MapControllers();
    
    // Blazor
    app.MapFallbackToFile("index.html");
    
    // Map SignalR Hubs
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapHub<SmsHub>("/smshub");
    });

Multiple 204 status codes logged on the server (because of this), which should not be happening:
[![enter image description here][3]][3]

**IMPORTANT NOTE:** as you can notice, in some instance, the Hub's OnConnectedAsync is called and logged with the info user provides. Maybe in some of the different methods that are attempted to connect to the socket, but closing the browser window will not end that connection until it times out. Finally, I want to add this live-server example is using the Cloudflare proxy, but it's nothing related to it.

  [1]: https://i.stack.imgur.com/xGp1R.png
  [2]: https://i.stack.imgur.com/BxHIb.png
  [3]: https://i.stack.imgur.com/jO6n6.png

**Comment by halter73** [comment]
> Also, I have tried to enable the Websocket service in additional features at IIS. Note I'm running this on the server with dotnet publish.

I think we're going to need more logs to get to the bottom of the weboscket issue. Can you grab a network trace using wireshark on the client side?

The chrome network logs make it look like long polling is working based on the 1.5 minute 200 responses, but it indicates the clients probably aren't receiving any messages. I don't see anything indicating the reason for the websocket request failing though.

It might help to get debug-level logs on the server side too. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

Are you hosting this in your own VM? Is there anything between the VM and the Cloudflare proxy that could be interfering with the websocket connection?

> Multiple 204 status codes logged on the server (because of this), which should not be happening:

I'm pretty sure, 204 responses are normal for [CORS preflight requests](https://github.com/dotnet/aspnetcore/blob/0114538e41c4358064f32d4e27c3ec39a2008d43/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L204-L213). CORS doesn't apply to websocket requests regardless. You might need CORS for the initial negotiate request, but that would explain the websocket request failing.

> Maybe in some of the different methods that are attempted to connect to the socket, but closing the browser window will not end that connection until it times out.

This could be because clients are falling back to long polling since WebSockets isn't working. Since long polling connections involve multiple requests, the server doesn't know whether or not there is going to be another poll after the previous one completes unless the client does an explicit action to indicates this. SignalR clients send a `DELETE` request when `stop()` is called on a long polling client connected for this purpose, but you have to manually call `stop()` in `window.onbeforeunload` or something like that. Websockets and server-sent events don't need this because a connection going away is enough to know the client is permanently disconnected with those transports.
