### ISSUE TITLE
UseSpa UseReactDevelopmentServer logging incorrect

### ISSUE THREAD

**Issue by oobles** [dotnet/aspnetcore#39147]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Output from UseSpa UseReactDevelopmentServer is only logged as "fail:" rather than "info:". Is there a way to change the logging level?

```
info: Microsoft.AspNetCore.SpaServices[0]
      Starting the development server...
      
fail: Microsoft.AspNetCore.SpaServices[0]
      <i> [webpack-dev-server] Project is running at:
```

### Expected Behavior

Logging output from node is logged at info rather than fail.

### .NET Version

5.0.400

**Comment by tarwn** [comment]
This will likely get closed out as "won't do", since SpaServices has been deprecated. 

The underlying issue is that WebPack is outputting infrastructure messages to stderr by default, which the SpaServices code picks up and logs as errors (there are no options we can change to alter this and a lot of the code is marked as internal, which is a shame because it would also be nice to change the "localhost" hardcoded host value to fix the ipv6 2s latency issue without messing with the webpack config too). 

If you're using an explicit webpack config (not Create-React-App), you may be able to fix this from the webpack side of things (I think it may also be webpack 5+).

Webpack 5 has a config to set the `stream` option in `infrastructureLogging`: https://webpack.js.org/configuration/other-options/#stream

If this is available for you, then you could:

1. Webpack config: Configure `infrastructureLogging.stream` to `process.stdout` 
2. appsettings.Development.json: Add a line in "Logging"/"LogLevel": `"Microsoft.AspNetCore.SpaServices": "Information"`

Example from my webpack file:
```
module.exports = {
  ...
  infrastructureLogging: {
    stream: process.stdout,
    colors: false,
    level: "info"
  }
};
```
_(`colors` and `level` may be unnecessary, I'm pasting it as is from an example config I'm working on)_

appsettings.Development.json:
```
{
  "DetailedErrors": true,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.AspNetCore.SpaServices": "Information"
    }
  }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
