### ISSUE TITLE
Very high memory consumption in Blazor app 

### ISSUE THREAD

**Issue by pcarret** [dotnet/aspnetcore#39156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have started a Blazor (server-side) svg-editor ambitious project and I'm facing **very very** high memory consumption (more than 500 Mb for some svg)

So I decided to investigate why the memory was getting very high and firstly when user was simply moving the mouse in <svg> area

When mouse moves or when wheel moves, some maths computations are done with mouse-coordinates + svg-matrix whenever the mouse is moved to compute coordinates in svg space
And memory climbs 1Mb after 1Mb to raise rapidly > 100 MB when displaying one single rectangle and memory never goes down. For one user it's not perceptible , but I can't imagine what it can be with 100 users on a server. The server would just die before user can finish their work

So I decided to find now the reason why memory was climbing so much and I isolated one code part that **seems** responsible of part of this memory issue
Then to share with the community, I made one console app and 3 Blazor projects with similar code but targeting different .net version.
  
The Blazor samples are doing exactly same operation.. 1 million of simple math matrix mulplications then a call to `GC.Collect();`
The Console app is just to have simpliest code ever.

 

### Expected Behavior

Depending on .NetCore version, memory can raise up to 203 Mb and it never goes back to its initial state although the objects are not referenced anywhere else. Why memory is not released down to its initial value. Is it a memory strategy to allocate enough memory for near future supposed use ?
On console app it raise from 8Mb to 19Mb so it climbs 11Mb. Why is there a so big difference in size allocation ?

I know after all my readings about this memory subject that memory in general and GC in particular is a whole Universe...but this issue is so big that I'm wondering on stopping this project now before crashing myself on the memory-wall 

It's easy to call GC.Collect() after 1 million of operation
How can I achieve a clean-up startegy when mouse is moving on client browser ?

### Steps To Reproduce

github repos are there :

- [console app](https://github.com/pcarret/MemoryTest)
- [blazor template with .NetCore 3.1](https://github.com/pcarret/MemoryIssue31)
- [blazor template with .Net 5.0](https://github.com/pcarret/MemoryIssue50)
- [blazor template with .Net 6.0](https://github.com/pcarret/MemoryIssue60)

![pca](https://user-images.githubusercontent.com/7167627/147130234-f83d0b6f-f68a-4896-9589-b4a533ff667a.png)

### Anything else?

I am using VS2022 Version 17.0.2 under Windows 10

**Comment by TanayParikh** [comment]
Hello @pcarret, thanks for contacting us. 

When running inside Visual Studio, potentially with the debugger attached, and/or using a debug build, the GC behaves differently. Consequently, these results are likely not representative of how Blazor behaves in a production environment. 

If you want to capture an accurate trace of your program we suggest you follow some of the guidance provided [here](https://docs.microsoft.com/aspnet/core/performance/memory) to accurately measure the memory usage in your app.

**Comment by pcarret** [comment]
> Hello @pcarret, thanks for contacting us.
> 
> When running inside Visual Studio, potentially with the debugger attached, and/or using a debug build, the GC behaves differently. Consequently, these results are likely not representative of how Blazor behaves in a production environment.
> 
> If you want to capture an accurate trace of your program we suggest you follow some of the guidance provided [here](https://docs.microsoft.com/aspnet/core/performance/memory) to accurately measure the memory usage in your app.

I have checked the guidance provided.
What can we conclude if Task Manager show that the exe memory increase like VS already shown. 
I am not sure it's Visual Studio is hiding something and it seems something bad about memory is happening for no obvious reason. Do I need to consider this as an individual and localized issue having no interest to the community ?
I my end app the memory rasie from 88 Mo to 190 in one minute while user does simply zooming / unzooming operation where the math computation is done and call to js interop as well

I could throw away the interest and months  I spent already in Blazor if only  20 users can use one server at same time

**Comment by MariovanZeist** [comment]
Hello @pcarret, I tried cloning your repos but they are not accessible, could you add them again?

**Comment by pcarret** [comment]
Hi @MariovanZeist,


Thanks for asking. I have re-created all 4 repos using VS2022
I deleted all 4 repos after this post was closed by **msftbot**
They are a simplistic version of the issue I am encountering. 
I hope they can fix the issue I have on my much bigger Blazor solution

**Comment by pcarret** [comment]
> Hello @pcarret, I tried cloning your repos but they are not accessible, could you add them again?
Hi @MariovanZeist,

I have pushed the 4 repos using VS2022 So they are available again
Hope this will help

**Comment by MariovanZeist** [comment]
I finally had some time looking at your issue:

Determining the memory usage of an application can be difficult If you don't know exactly what you are looking at. Judging by the numbers you provided, you have looked at the memory consumption inside VS, and in TaskManager.

Sadly both of them will not give you an accurate number, and especially the Visual Studio memory will be vastly inflated because it needs a lot of memory for debugging purposes. 
If you are interested in some better numbers, don't look at the ``Process Memory (MB)``, but select the ``Memory Usage`` tab below it, press ``Take Snapshot`` and there you can see the amount and types of memory allocated.

Even in TaskManager, your application will have allocated more memory, because of the need to display the console window, and other things.

If you are serious about checking for memory, you should follow up on the link @TanayParikh provided, as it has really good info about this issue.

But If I look at your code, I see nothing to worry about. for example the console application is just using around 64k of memory when idle, and will rise to 2MB when running the ``bigloop``. Even if you run it 1.000.000 times the memory won't go a lot higher than that.

The ASPNet core application does use a bit more memory, but that's for all the ASP net Core stuff, running the bigloop there will again not increase the memory by more than 2MB even if you press the counter 1.000.000 times.

There is some good documentation on how c# allocates (and releases) memory here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals

And you don't need to worry about Blazor Server in this case. Even if you had 1000 browsers attached. (Granted, each client will add a bit of memory to the overall application use)
And on these 1000 browsers users would click the counter button 1000 times, the memory will not increase by a lot. 

Although I am a little concerned about performance as you mention you are doing actions on a ``MouseMove``. this might not be a good fit for Blazor Server, but would be better if you run on Blazor Wasm.

You might infer that if one browser increases the memory usage by 2MB, 1000 browsers will increase it by 2GB (1000 *2MB) but this is simply not the case, and not how memory allocation in C# works.

As I cannot 100% rule out that you have a memory leak in your application (As I haven't seen the code) I am fairly confident that what you are seeing is normal c# behavior.

**Comment by pcarret** [comment]
Hi @MariovanZeist,

Thanks **very much** for taking your time to have a look and answer so deeply.

I do not understand why I need to call GC.Collect() in the 4 repos to force memory to go down
So as far as I understand from you notes, with snapshot, taking the heap size is the prefered approach and looking after its changes by taking multiple snapshots and compare them is accurate while looking in VS tool where memory clim up to 200Mb is not. because of VS internal consumption to add debugging info

To answer about your question on Blazor style (server-side vs WASM) I decided to use server-side to avoid reverse engineering since I saw WASM can be decompiled and by using Reflection, code can be sniffed. 
My concern is about performance since the program is an SVG Editor reacting to every mouse move (zooming, panning, moving objects). I did not have yet the chance to test on a real server. Debugging WASM versions is very painful compared to server-side which can be itself not so easy when exception are coming from a place you ignore. It's much harder than classical C# 

I am able to share with you the simpliest version of this editor where it shows the memory climbing at each mouse wheel action. I can make a new public repo for that
I made a [video ](https://user-images.githubusercontent.com/7167627/147741744-eeed225a-a3c3-4b1e-a12c-9dc947b7f904.mp4)to show what I'm wondering about. On video the VS memory tool goes very high when zooming (starts at 0:19 sec. VS goes from 177Mb to 185Mb) while the snapshot show 8Mb of usage

**Comment by MariovanZeist** [comment]
The reason why you shouldn't call ``GC.Collect`` in your code explicitly is that .NET will do it automatically for you when needed (and it does this in a smart way), If you call it yourself you will probably (almost certainly) hurt the performance of your application. And it's really not needed. I just found this blog: https://devblogs.microsoft.com/dotnet/garbage-collection-at-food-courts/ which tries to explain a bit how it works. 

Watching your video, I again see nothing special. there are 2 things to look for,
1. The number of yellow checkmarks in the Process Memory (MB) is low. Every checkmark would indicate that .NET thinks it needs to do a ``GC.Collect``. Seeing only 1 checkmark during the entire time tells me there is not a lot of changes in memory usage.
2. The 2 snapshots you created differ less than 1 MB in memory which is not much, even .NET doesn't think it needs to do a ``GC.Collect`` (Or if you go by the food court analogy, .NET doesn't think its dirty enough to start cleaning)

So remember, it's not that every client you add will take 6-7MB. You can simply test this by starting your application, and open 10 browser windows and connecting to your application. Take a snapshot, and start zooming in all the browser windows and see what the difference is after taking another snapshot.

**Comment by pcarret** [comment]
garbage-collection-at-food-courts is an execllent ref article. Thx, Comparison is always a great help to educate people

I still do not know if Blazor is the right choice for an online svg drawing software either with server-side downside (performance) and WASM (reverse-engineerable)

Anyway many thx @MariovanZeist, for your helpful and detailed answers

**Comment by mkArtakMSFT** [comment]
Thank you for helping out with this, @MariovanZeist ! Much appreciated!
