### ISSUE TITLE
(Blazor) Why is onchange event default for <input>?

### ISSUE THREAD

**Issue by bugproof** [dotnet/aspnetcore#39197]
One thing I've noticed that is different from frameworks like Vue and Svelte is that they use `oninput` for bindings by default instead of `onchange`. Any reason why it's `onchange` in Blazor? Fortunately you can change it with `@bind:event="oninput"` . Is there a way to change it to use `oninput` by default?

Are there any other valid values you can use for `@bind:event` other than "oninput" and "onchange"?

**Comment by pranavkm** [comment]
> Is there a way to change it to use oninput by default?

There isn't. If these are for components, you could consider building a set of components deriving from InputBase that subscribes to `oninput` rather than `onchange`. e.g. https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputText.cs#L38

> Are there any other valid values you can use for @bind:event other than "oninput" and "onchange"?

Those are the only two events that are currently supported.
