### ISSUE TITLE
(Blazor) Default type for @typeparam

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnetcore#39191]
This feature is first requested 2 years ago by #13619 and it is marked as "won't fix".

Now two years past, can you consider this feature again?

This feature is really helpful because razor syntax doesn't allow multiple generic types with the same name, such as `MyComponent<T>` and `MyComponent<T1, T2>`.

As we know, .net6 uses source generator and can have type parameters inferred by parent component. I think this feature can be implemented by a similar technique.

**Comment by pranavkm** [comment]
We have another issue that covers adding better type inference for generic components: https://github.com/dotnet/aspnetcore/issues/37569. In general, we want Razor to be a subset / equivalent set of C#. Adding a default type for a generic type parameter isn't a C# feature which is likely why the other issue is marked as won't fix. I'll close this since we already have the other issue tracking further improvements in this area.

**Comment by anranruye** [comment]
@pranavkm  thanks for the explanation

**Comment by anranruye** [comment]
@pranavkm But are you sure the issue you post is disscuss the same thing as this issue? And you are right, we want a razor feature rather than a C# feature.
