### ISSUE TITLE
HttpLoggingMiddleware could allow custom code to decide whether to log or not

### ISSUE THREAD

**Issue by hugoqribeiro** [dotnet/aspnetcore#39200]
## Background and Motivation

The `HttpLoggingMiddleware` added recently works based on configuration options in `HttpLoggingOptions`.

The currently implementation is basically all or nothing. You either add the middleware or not. Even if you can decide what is redacted or not and if request/response bodies are included.

It would be nice if `HttpLoggingOptions` included a delegate to let the application (custom code) decide whether to log or not for a specific request.

## Proposed API

```diff
namespace Microsoft.AspNetCore.HttpLogging
{
    public sealed class HttpLoggingOptions
    {
+       public Func<HttpContext, bool> Selector { get; set; } = context => true;
    }
}
```

## Usage Examples

- Log only failed requests.
- Log request body only for specific endpoints.

## Alternative Designs

You can implement your own middleware but that beats the whole purpose of implementing this feature in the framework.
An alternative would be to make `HttpLoggingMiddleware` public and add some kind of extensibility to it. At least one could implement that custom middleware but reuse the framework implementation (e.g. request buffering).

## Risks

The risk is that performance of HTTP logging would depend on the custom code implemented in the delegate.

**Comment by pranavkm** [comment]
Couldn't you wrap `UseHttpLogging` in a `app.MapWhen` to achieve this?

**Comment by hugoqribeiro** [comment]
`UseWhen` would problably be better for most use cases.
Although I still think the proposal would be clearer and more powerful. With very little effort on the part of the framework.

**Comment by BrennanConroy** [comment]
Similar to https://github.com/dotnet/aspnetcore/issues/31844

**Comment by Tratcher** [comment]
Rather than on/off, you'd want something more granular like HttpLoggingFields (and return None for off).
```diff
namespace Microsoft.AspNetCore.HttpLogging
{
    public sealed class HttpLoggingOptions
    {
+       public Func<HttpContext, HttpLoggingFields>? FieldSelector { get; set; } 
    }
}
```

This is similar to the proposed endpoint attribute in https://github.com/dotnet/aspnetcore/issues/43222.

**Comment by halter73** [comment]
API Review Notes:

- Would the `FieldSelector` be called at the beginning of the request? Yes.
  - Wouldn't this be too early to "log only failed requests"? Yes.
  - Are we okay with this? Sounds like yes. We could possibly add an option to delay logs and also the call to the `FieldSelector` until after the response is produced at a later date.
- Should we register a service rather than add a settable `Func` to options? This would make it a little easier to resolve services and maintain. It's possible to resolve services using the options pattern, so this is a matter of style.
- What does the example usage look like?

```csharp
builder.Services.AddHttpLogging(options =>
{
    //options.LoggingFields = FieldSelector.RequestPropertiesAndHeaders;

    options.FieldSelector = context =>
    {
          if (<some condition that means the request should not be logged>)
          {
               return FieldSelector.None;
          }

          return null;
    };
});
```

- How do we combine it with `HttpLoggingOptions.LoggingFields`? Does it override it always? Should we make the return type nullable if we want the default behavior? Let's do that.
- Do we want to support multiple `FieldSelector`s? We think manually chaining the funcs is sufficient for this.

API Approved with nullable return type!

```diff
namespace Microsoft.AspNetCore.HttpLogging
{
    public sealed class HttpLoggingOptions
    {
+       public Func<HttpContext, HttpLoggingFields?>? FieldSelector { get; set; } 
    }
}
```

**Comment by BrennanConroy** [comment]
I was thinking about whether the `Func` should include the current field options, it would be easy to do that with WAB:
```csharp
builder.Services.AddHttpLogging(options =>
{
    var defaultOptions = HttpLoggingFields.RequestPropertiesAndHeaders;
    options.LoggingFields = defaultOptions;

    options.FieldSelector = context =>
    {
          if (<some condition to remove request headers>)
          {
               return defaultOptions & ~HttpLoggingFields.RequestHeaders;
          }

          return null;
    };
});
```
But, not everyone uses WAB, and we are using `IOptionsMonitor<HttpLoggingOptions>` which means the default could change at any time. It seems like we should add the current options then:
```diff
+       public Func<HttpContext, HttpLoggingFields, HttpLoggingFields?>? FieldSelector { get; set; } 
```

Also, thinking about
> We could possibly add an option to delay logs and also the call to the `FieldSelector` until after the response is produced at a later date.

It seems like we would need a way of expressing this in the `FieldSelector` call, so users would know that this was called after the response or not.
e.g.
```diff
+       public Func<HttpContext, bool, HttpLoggingFields, HttpLoggingFields?>? FieldSelector { get; set; }
```
And optionally adding a delegate so that the parameters can be named.
```diff
+       public FieldSelectorDelegate? FieldSelector { get; set; }
+       public delegate HttpLoggingFields? FieldSelectorDelegate(HttpContext context, bool afterResponse, HttpLoggingFields currentFields);
```
Or, adding a context object like we do in other middleware, in case we want to add more settings in the future, such as changing the response/request body log limits.

**Comment by Tratcher** [comment]
> It seems like we would need a way of expressing this in the `FieldSelector` call, so users would know that this was called after the response or not.

You'd also need a separate option to enable the delayed call. Or even a two stage flow where you call it once, it says what to preserve, and then you call it again with the results and it decides if the logs should happen. This seems more complicated than we want to pursue right now.

And by the time you have this many parameters you should be passing a context object.

**Comment by BrennanConroy** [comment]
> You'd also need a separate option to enable the delayed call.

Yes, I was assuming that since it was already called out by Stephen.

> And by the time you have this many parameters you should be passing a context object.

Yes, that's what I said at the end of my comment.

> This seems more complicated than we want to pursue right now.

I'm not saying we should add the delayed call right now. But we should design for potential future changes.

**Comment by BrennanConroy** [comment]
Notes:
* We would like feature parity with the attributes in https://github.com/dotnet/aspnetcore/issues/43222, meaning request/response size limits should be settable
* Adding a context object makes this more future proof
* Media type options would be a pain to pass in and allow setting per endpoint
* Similar with request/response headers, would need to copy every time
* Just keep it simple with Fields and body size limits for now, it's a context so we can add things easily in the future!
* **Calling into question why we even need this** if you can fairly easily write a middleware to do the same thing (now that the attribute apis are approved)
  - caveat, if this was called after response, it would be more useful (hard to do in middleware) since we would be buffering request/response and not logging until you made a decision

API needs feedback still

```diff
namespace Microsoft.AspNetCore.HttpLogging;

+public sealed class HttpLoggingContext
+{
+    public HttpLoggingContext();

+    public HttpContext HttpContext { get; set; }

+    public HttpLoggingFields LoggingFields { get; set; }

+    public int? RequestBodyLogLimit { get; }

+    public int? ResponseBodyLogLimit { get; }
+}

namespace Microsoft.AspNetCore.HttpLogging;

public sealed class HttpLoggingOptions
{
+    public Action<HttpLoggingContext>? HttpLoggingSelector { get; set; }
}
```

**Comment by adityamandaleeka** [comment]
Triage: it would be interesting to think about how you could do this in ILogger instead of here. 

cc @JamesNK who is working on other logging things that may be related.

**Comment by Tratcher** [comment]
ILogger seems too late. Collecting these fields from the HttpContext and creating the log message, especially with the request body, is expensive.

**Comment by BrennanConroy** [comment]
I think this is replaced by https://github.com/dotnet/aspnetcore/issues/31844#issuecomment-1603418570
Which allows the user more granular control over what gets logged.
