### ISSUE TITLE
Performance of .Net 6 vs .Net Core 2.2 on big html pages

### ISSUE THREAD

**Issue by mshayesteh301** [dotnet/aspnetcore#39237]
I am trying to migrate to dotnet 6 from dotnetcore 2.2. Using West Wind WebSurge, I tested performance of home page of my site (Controller with .cshtml razor views) to see difference in both frameworks. In spite of turning off runtime compilation, performance of dotnet 2.2 is considerably better according to the following snapshots:

dotnet 2.2 test result:
![dotnet2-2](https://user-images.githubusercontent.com/8945396/147665021-8553b4bc-ecb3-412d-98fe-193e05b9d0da.png)

dotnet 6 test result:
![MPOdd](https://user-images.githubusercontent.com/8945396/147659385-35e57e3c-8eda-4b56-b35e-257cf744a81e.png)

It is worth to note that:

The only code in controller is return View() and in razor I have pasted rendered html code (generated by browser) to ignore effect of other things in razor page.
By reducing lines of html to half of current size, performance becomes almost equal.
Is there any special config or tips to improve performance in dotnet 6?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is too high level to be able to make a statement, given many parameters at play. We will need to have a repro projects highlighting the scenario for which the performance has regressed so that we can investigate it further. Would you mind creating a minimal repro project and host it as a public GitHub repo to showcase the issue? Thanks!

**Comment by davidfowl** [comment]
If you can give us a sample application, that would be great!
