### ISSUE TITLE
[Question]: OnAfterRender gets triggered again, while click on button

### ISSUE THREAD

**Issue by aravindravi94** [dotnet/aspnetcore#39244]
**Describe the bug:**
We have created a button and added a click event for that element. In the click event of the button, we have shown an alert box. When we click on the button element, the click event gets triggered and an alert box gets opened. Once click the ok button on the alert box,  the component OnAfterRender event gets triggered again. Is this is nature of blazor ???

**Version used:**
Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 3.0

**To reproduce:**
1. Click on the button
2. Alert box gets opened.
3. Now, click on the **ok** button in the alert box.
4. See the onAfterRender gets triggered again

**Expected behavior:**
We thought the OnAfterRender gets triggered only once and does not want to trigger while clicking on the button.

**Actual behavior:**

**Additional context:**

Code Snippet is added below

```razor
@inject IJSRuntime JsRuntime
<div>
    <input type="button" value="Button" @onclick="@Click" />
</div>

@code {

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine("Hit");
    }

    private async void Click()
    {
        await JsRuntime.InvokeVoidAsync("alert", "Warning!"); // Alert
    }
}
```

**Comment by pranavkm** [comment]
Delegate event handlers automatically trigger a UI render. See https://docs.microsoft.com/us/aspnet/core/blazor/components/event-handling for more about event handlers and component lifecycle methods. 

The only odd part is that the `OnAfterRender` is invoked after the `window.alert` is dismissed. This is because alerts are modal and blocks until the `window.alert` completes, preventing Blazor from receiving an ACK from the app that the render was completed.
