### ISSUE TITLE
Double Page Declaration Causes Object Reference Not Set Error

### ISSUE THREAD

**Issue by CheetahChrome** [dotnet/aspnetcore#39270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a user accidently adds an extra page declaration such as

#### Razor Page Duplication

    @page "/additionalinfo"
    @page "/additionalinfo" 
    @using BPG.Model
   ...
   
   A runtime exception is thrown.

----

#### Exception on Page
> NullReferenceException: Object reference not set to an instance of an object.

#### StackTrace

    BlazorProvingGroundServerApp.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml
    -
    @namespace BlazorProvingGroundServerApp.Pages
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
    @{
        Layout = "_Layout";
    }
    <component type="typeof(App)" render-mode="ServerPrerendered" />

### Expected Behavior

(*This falls into a user doing a *Garbage in, garbage out* scenario...*) But, this should be caught, if at runtime, then a more robust error describing multiple page declarations found. Or if at compile time, at least as a warning, or better an error. 

### Steps To Reproduce

1. Create a component page.
2. Duplicate the @page line.

### Exceptions (if any)

> NullReferenceException: Object reference not set to an instance of an object.
> Microsoft.AspNetCore.Components.Routing.Router.Refresh(bool isNavigationIntercepted)

### .NET Version

.Net 6

**Comment by geogreg1** [comment]
Here is what appears to be a variation of the same issue: duplicate page in the RCL causes an an exception to be thrown when router code is modified even though the duplicate page is _not_ being consumed.  https://stackoverflow.com/questions/72310618/adding-an-additional-assembly-to-app-razor-router-in-blazor-causes-host-cshtml

**Comment by jlchavez** [comment]
I consider that the issue #39228 is not a duplicate, because one thing is the code generation for the razor page or having an error in the editor because of having duplicate route values for the same component, that migh be a viable error for not making an error that breaks things because of having multiple pages with the same route in the same assembly, but having two different components one in the application and another in an RCL with the same path, that with routing the one in the application should take priority.

I just got the issue blocking on delivering shared pages in an RCL and I don't want to create another Issue like #39238 and being ignored as it was done with that one. 

You would have to consider three scenarios:

- Error or Warning on duplicate routes that are the same in a component
- Error or Warning on duplicate routes that are the same in multiple components in the same assembly
- Prioirity on Routes in the hosting app over the RCL's

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that having different page attributes works. Having duplicate page attributes is just not a scenario that we support, and we don't plan to spend resources to improve the experience with duplicate page attributes.
