### ISSUE TITLE
Using SSR (Angular) in .NET 6

### ISSUE THREAD

**Issue by omikolaj** [dotnet/aspnetcore#39295]
I've realized that traditional support for SSR in .NET 6 has been deprecated. I am seeking clarification that hopefully will also be beneficial to others.

When asked about Server Side Rendering /Angular Universal in the following [issue](https://github.com/dotnet/aspnetcore/issues/27887), an [answer was given](https://github.com/dotnet/aspnetcore/issues/27887#issuecomment-912106128) 

"As we've had [announced earlier](https://github.com/aspnet/Announcements/issues/379), we will be relying on SPA frameworks to provide server side rendering functionality."

_Originally posted by @mkArtakMSFT in https://github.com/dotnet/aspnetcore/issues/27887#issuecomment-912106128_

Stand alone application of Angular allows users to perform SSR and Prerendering via Nodejs install via few npm packages added to the project in local development. 

When the answer was given that "... we will be relying SPA frameworks to provide server side rendering functionality" is this talking about this very functionality or is this something completely different? I am asking because I'm curious if this means my .NET 6 server will be able to run script 'npm: serve:ssr'  and use Nodejs installed by Angular to render and serve HTML?

I guess what I am trying to figure out is if I can serve Angular application and achieve SSR from .NET 6 or if I have to look at other places to host the front end app that allow SSR to achieve desired result.

**Comment by muzyka-viacheslav** [comment]
Hey guys
I do seek as well of hearing that .NET will start support natively SSR, and I believe this native support is crucial for almost all devs amongst those who are working with project stack .NET + Web (Angular/React/Vue/etc.)

**Comment by PieterjanDeClippel** [comment]
Hi, I forked the code here: https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices.Routing

The package is on nuget.org

**Comment by omikolaj** [comment]
I appreciate that, but such packages are bound to become outdated because they are not updated with the frequent .NET updates. I'd rather not have a dependency that can go out of date in 3-5 years. It will be a headache in the future

**Comment by cbernth** [comment]
I'm surprised that MS hasn't provided a clear migration path for this issue.

Any modern website relies on SSR to provide meta data to e.g. Google, Bing as well as SoMe integration. Without SSR the site content will never be picked up by search engines nor will we be able to share links with previews on SoMe.

I would assume MS want to promote running existing and new .NET solutions on Azure (and even choose .NET as the foundation for new solutions) so there is a huge documentation gap on how to enable SSR in .NET.

Part of the deal is, that the "proper way" promoted by MS (which includes running the SPA as the UI front and proxying/rewriting API requests to the .NET) isn't documented.

What we need is a recommended practices / getting started guide specifying:
- How to set up the Azure IIS configuration to run the Angular app on Azure Web App, **_AND_**
- How to set up the Azure IIS configuration to also run the .NET API on the same Azure Web App, **_AND_**
- How to configure the proxying/url rewrite/whatever is required to have the two seamlessly integrated, **_AND_**
- How to integrate the above steps into a CI-CD build step

Without the above, the natural approach is to seek away from IIS (Azure) or seek away from .NET API, both of which I assume is not in the interest of MS.

To every developer: Running (Angular) SSR + .NET 6 API in such a way that MS proposed by discontinuing .UseSpaPrerendering is to **_not_** have the .NET app route some HTTP request to the NodeJs app and subsequently return the rendered result (and others being handled internally as API calls to), but instead delegate the roles so each part of the app serves it's own portion of the HTTP requests. 

_The utterly disappointing aspect of that grand plan that MS came up with, is that they never bothered specifying what is needed to achieve that on e.g. Azure IIS._

Thanks,
Claus

**Comment by nmocruz** [comment]
Microsoft as many times likes to give some goodies to please people searching for innovative ways to do some stuff, and then after some time that just move to other trend leaving everyone behind.
I was really bad luck, first I learned WPF and Silverlight, then I start to develop with spa and knockout, and last one I start to use dotnet core spa services. I think that they are just waiting to see if I learn blazor to wait 1-2 years and then say, sorry guys we are not supporting more blazor, we found a better place to invest resources.

**Comment by leeyates5000** [comment]
We have a thriving business running an SSR Vue app - quite frustrating to have the upgrade path completely blocked now as we can't easily migrate. If I'm pushed to implement the SSR using node, what do you think are the chances of me staying with Microsoft in the long run? Speaking as a user of .NET since 1.0.

**Comment by leeyates5000** [comment]
There seems to be some doubt on Microsoft's part as to whether there's any value in supporting this. I can't speak for the numbers adopting the SSR library, only MS can make this evaluation. 

However, I can say this....

The SSR library has allowed me to reuse a domain model, serving an API and Views which inject .NET objects and render Vue pages ultimately. This has proven to be very efficient and allowed me to reuse code extremely well.

If I now need to serve this data from nodejs how would that work? I'd need to mirror libraries in node in order to render server side. **That is not an option** with a code base of 2,500 files, the code is neat but will be a huge effort - for what?

However, if there is no native SSR in .NET then my I will be pretty much forced to implement in a way that achieve this without code duplication. That means there's no choice but to move technologies. I haven't looked at Java type options yet but it could be moved to node. 

There would be no coming back to Microsoft on this one. How many developers are moving back to Microsoft after moving out to open source technologies. I'm one of the few remainers - the open source converts are not screaming for MS tech.

**Comment by JoshClose** [comment]
Please open back up.

**Comment by jitterbox** [comment]
@mkArtakMSFT @danroth27 The popular Angular (/Vue/React) + ASP.NET stack continues to suffer mightily due to this gap. Microsoft made clear that it can't maintain the burden of SPA prerendering/SSR functionality for the disparate JavaScript SPA frameworks - that's fine. But please dedicate a few resources to working with the Angular team to produce guidance [as requested above](https://github.com/dotnet/aspnetcore/issues/39295#issuecomment-1101357336) for setting up projects with **Microsoft Visual Studio tooling** and hosting them in **Microsoft Azure** with the current .NET LTS version. It should cover the recommended steps to debug and run these solutions in development and production, build them through DevOps, and publish them to Azure.

Google and the community have not picked up the ball on this - it remains where you left it. Please include this in your plans.
