### ISSUE TITLE
Repeatedly reloading of .NET 6 Blazor wasm page in Firefox causes out of memory

### ISSUE THREAD

**Issue by andersfrantz** [dotnet/aspnetcore#39305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There seems to be some kind of memory leakage when reloading _.NET 6 Blazor Wasm_ in _Firefox 95.0.2 (64-bit) on Windows_ 10. We found that our product built on Blazor caused out of memory error after 3 reloads when published with **AOT** and after about 12 times **without AOT**. This has not been seen before upgrading to .NET 6 when the application was built with .NET 5. After this error has occurred it's game over and the browser needs to be restarted.
_The following was logged:_
_info_: Streaming compilation failed. Falling back to ArrayBuffer instantiation.  out of memory blazor.webassembly.js:1:36697

_err_: TypeError: Response.arrayBuffer: Body has already been consumed. blazor.webassembly.js:1:35461
        printErr https://localhost/pg2/_framework/blazor.webassembly.js:1
        Module https://localhost/pg2/_framework/blazor.webassembly.js:1

_err_: Uncaught (in promise) TypeError: Response.arrayBuffer: Body has already been consumed.
       n https://localhost/pg2/_framework/blazor.webassembly.js:1

**This is also reproducible when running the out-of-the-box VS 2022 "template" Blazor application (published with AOT)**. After several reloads, (in this case 32) the following warning and error is logged:

_warn_: WebAssembly module validated with warning: failed to allocate executable memory for module

_err_: Uncaught (in promise) TypeError: Response.arrayBuffer: Body has already been consumed.
    n https://localhost:5001/_framework/blazor.webassembly.js:1

Firefox memory in task manager has at this point grown to about 4 GB.
Below is an excerpt from _about:memory_ (Force GC by pressing the 'Minimize memory usage' button makes no noticeable difference):

**Explicit Allocations**

20,118.30 MB (100.0%) -- explicit
├──20,068.68 MB (99.75%) -- window-objects/top(https://localhost:5001/, id=37)
│  ├──20,053.02 MB (99.68%) -- active/window(https://localhost:5001/)
│  │  ├──20,049.23 MB (99.66%) -- js-realm(https://localhost:5001/)
│  │  │  ├──20,042.39 MB (99.62%) -- classes
│  │  │  │  ├──16,385.64 MB (81.45%) -- class(ArrayBuffer)/objects
│  │  │  │  │  ├──16,384.00 MB (81.44%) ── non-heap/elements/wasm [**32**]
│  │  │  │  │  └───────1.64 MB (00.01%) ++ (2 tiny)
│  │  │  │  ├───3,638.22 MB (18.08%) -- class(WebAssembly.Instance)/objects
│  │  │  │  │   ├──1,966.21 MB (09.77%) ── malloc-heap/misc [32]
│  │  │  │  │   ├──1,672.00 MB (08.31%) ── non-heap/code/wasm [32]
│  │  │  │  │   └──────0.00 MB (00.00%) ── gc-heap [32]
│  │  │  │  └──────18.53 MB (00.09%) ++ (6 tiny)
│  │  │  └───────6.84 MB (00.03%) ++ (2 tiny)
│  │  └───────3.79 MB (00.02%) ++ (3 tiny)
│  └──────15.66 MB (00.08%) ++ (32 tiny)
└──────49.61 MB (00.25%) ++ (24 tiny)

**Other Measurements**

134,217,727.94 MB (100.0%) -- address-space
├──131,915,122.37 MB (98.28%) ── free(segments=202)
├────2,282,128.48 MB (01.70%) -- reserved
│    ├──2,097,096.57 MB (01.56%) ── mapped(segments=13)
│    └────185,031.91 MB (00.14%) ── private(segments=1331)
└───────20,477.09 MB (00.02%) ++ commit

5.87 MB (100.0%) -- decommitted
└──5.87 MB (100.0%) ── js-non-window/gc-heap/decommitted-pages

81 (100.0%) -- event-counts
└──81 (100.0%) -- window-objects/top(https://localhost:5001/, id=37)/active/window(https://localhost:5001/)/dom
   ├──77 (95.06%) ── event-listeners [32]
   └───4 (04.94%) ── event-targets

### Expected Behavior

There should be no memory consumption/leakage causing the application to crash after reloading the page.

### Steps To Reproduce

See description above. The problem is reproducible with the out-of-the-box sample Blazor application project in VS 2022

### Exceptions (if any)

TypeError: Response.arrayBuffer: Body has already been consumed. blazor.webassembly.js:1:35461
        printErr https://localhost/pg2/_framework/blazor.webassembly.js:1
        Module https://localhost/pg2/_framework/blazor.webassembly.js:1

Uncaught (in promise) TypeError: Response.arrayBuffer: Body has already been consumed.
       n https://localhost/pg2/_framework/blazor.webassembly.js:1

### .NET Version

6.0.100

**Comment by TanayParikh** [comment]
Hello @andersfrantz, thanks for reporting. Is this issue specific to Firefox, or are you seeing it in other browsers as well. 

cc/ @radical have you seen this before?

**Comment by radical** [comment]
@kg @radekdoulik @lewing wasm memory growth causing this? Does that get reset when reloading a page?

**Comment by kg** [comment]
A page reload should clear everything, so this is either a bug in Firefox or something related to Blazor's persistent service worker. I'm not sure how Blazor's service worker could cause this, though. It looks like a Firefox bug, so it should probably be filed over at their bugzilla (https://bugzilla.mozilla.org/home). If the reporter needs help filing it I can probably assist.

**Comment by andersfrantz** [comment]
> Hello @andersfrantz, thanks for reporting. Is this issue specific to Firefox, or are you seeing it in other browsers as well?
> 
> cc/ @radical have you seen this before?

It doesn't seem to be the same problem in Chrome and we didn't see the problem in Firefox before upgrading from .NET 5 so thought it might anyway be related to some change in .NET 6 Blazor.

**Comment by grahamstaf** [comment]
I have also seem memory issues with Chrome when using the **Published** Blazor code. 

Chrome Task Manager shows memory usage increasing 5 times that of the Release or Debug code.

You can easily see this by using the Dev Studio default Blazor project template and running the release code and published code versions. Then look at Task Manager for Google Chrome to compare memory usage.

Refreshing (F5) does not reduce memory usage.

**Comment by mkArtakMSFT** [comment]
@grahamstaf thanks for sharing your observations. It looks though that what you are seeing is different from what the issue author brought up initially. Feel free to file a separate issue and provide us with a repro project so that we can look into it separately.

**Comment by kg** [comment]
Agreed with Artak that your issue in Chrome is likely a separate bug so it should be filed separately. To provide some clarity so it's easier to understand:

Any memory usage or similar issue that persists across a page reload (hitting the reload button in the browser) is at least in part a browser bug. In this case as you only started seeing it once upgrading to .NET 6, that means likely a change in Blazor or the underlying .NET platform *caused you to hit the bug*, but it is a browser bug. By design nothing should persist across a page load (with the exception of things like data stored in indexed DB), so things like increases in browser memory usage or the browser running out of memory are definitely browser bugs and only the browser vendor can fix them. Once the browser vendor has information available on the nature of the bug, we can potentially identify a workaround to help you and your affected customers in the interim.

From the Firefox memory report, it looks like it may be an issue in their management of compiled wasm code and wasm heap objects, as it is normally not possible for a tab to even allocate 18gb of memory (wasm on paper tops out at 4GB of memory due to being a 32-bit architecture, and often will stop below 4GB) and there appears to be nearly 2GB of compiled wasm code sitting in RAM as well. I can imagine potential workarounds to make this less severe, but if the memory is sticking around after you reload or close the tab, we can't fix that for you.

As always, feel free to communicate with us by filing github issues when you believe you've hit a problem, and we will be happy to investigate. Just in this specific case it does appear to be a browser bug, so we can only do so much to help.
