### ISSUE TITLE
Implement <NavLink> for MVC/Razor Pages

### ISSUE THREAD

**Issue by Ducki** [dotnet/aspnetcore#39316]
Blazor components got a [NavLink](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Routing/NavLink.cs) which automatically sets an `isActive` if the current route matches the link.
It is unfortunate, that MVC and Razor Pages never got this feature builtin.

Please [reconsider](https://github.com/dotnet/aspnetcore/issues/7049), since this is an essential helper that literally every other framework in the world has.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Unfortunately, this doesn't meet the priority bar for us to do this at the moment.
Looks like we've closed the original ask because of no community interest. I assume there won't be much interest this time around either, but I'm willing to give this another chance. Feel free to send us a PR with the proposed fix.
