### ISSUE TITLE
Blazor wasm - ability to independently prerender only HeadOutlet component

### ISSUE THREAD

**Issue by CoryKoehler** [dotnet/aspnetcore#39333]
### Is your feature request related to a problem? Please describe.
I am trying to remove prerendering from my site and have only the element that requires it be prerendered

Others have opened issues where documentation was not clear on the way to change title and meta content 
e.g https://github.com/dotnet/aspnetcore/issues/37293

### Describe the solution you'd like
I think it would be ideal if we could choose to only prerender the HeadOutlet and not the entire app.

**Comment by SteveSandersonMS** [comment]
@CoryKoehler You can prerender whichever subset of your root components you wish.

Inside the `_Host.cshtml` and `_Layout.cshtml` files in your server project, you'll find `<component>` tag helpers that prerender things. If you want the `App` component *not* to be prerendered, consider changing this:

```razor
<component type="typeof(App)" render-mode="WebAssemblyPrerendered" />
```

... to this:

```razor
<component type="typeof(App)" render-mode="WebAssembly" />
```

This will leave the `HeadOutlet` unaffected, and hence still prerendered.

However, bear in mind that the page title is determined by the `Router`, which in turn is inside the `App` component by default. If you're not prerendering that, then it hasn't run on the server, and hence the server doesn't know the page title, and hence `HeadOutlet` prerendering can't populate itself with a title. There isn't really any other way this could work, because the router can do anything it wants to select a page, and those pages can do anything they want to select a title. If none of that is happening during server-side execution, there's no way to define the page title.

**Comment by CoryKoehler** [comment]
@SteveSandersonMS Can I prerender the Router so that I can get the behavior I want from HeadOutlet and still keep the App from prerendering?

**Comment by SteveSandersonMS** [comment]
> Can I prerender the Router so that I can get the behavior I want from HeadOutlet and still keep the App from prerendering?

The page title is determined by the page that gets selected, and it can even change the title dynamically (e.g., using data from a DB query). So if you really want to prerender the true page title, you really do have to run the entire component hierarchy so that all of this logic runs.

> However, bear in mind that the page title is determined by the Router

Sorry, it was misleading when I said that. The router chooses the page to render, and then the page determines the page title.
