### ISSUE TITLE
blazor-devserversettings.json

### ISSUE THREAD

**Issue by ysiivan** [dotnet/aspnetcore#39449]
The only mention, that I can find, of this file is [here](https://github.com/dotnet/aspnetcore/issues/28237). Google draws blank. I can't find anywhere any specs. 
Is there a documentation (perhaps not reachable by the search engines) for it?

**Comment by SteveSandersonMS** [comment]
It's exactly the same as an `appsettings.json` file (identical format and capabilities, [as documented](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)), simply renamed to `blazor-devserversettings.json`.

We haven't been explicit about it in docs because there are almost no scenarios where you would need to configure this. It's more of an escape hatch in case a reason to configure it emerges.

Remember that this *only* configures the dev server, so has no impact on your app in production.
