### ISSUE TITLE
signalr.min.js Uglify error

### ISSUE THREAD

**Issue by rvicoqbi** [dotnet/aspnetcore#39515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When building an angular SPA and using Uglify to obfuscate the code, compiler is throwing an error indicating the next message: Unexpected token punc «{», expected punc «(».
We found that there is a catch block wrong typed (column 15999). Catch is typed without () before {}.

### Expected Behavior

Compiler should end succesfully

### Steps To Reproduce

Compile an angular SPA using Uglify with PROD environment configuration.

### Exceptions (if any)

ERROR in scripts.98d04603e1669c1a8f0f.js from UglifyJs
Unexpected token punc «{», expected punc «(» [node_modules/@microsoft/signalr/dist/browser/signalr.min.js:1,15999][scripts.98d04603e1669c1a8f0f.js:20847,16005]

### Anything else?

You can test it copying @microsoft/signalr/dist/browser/signalr.min.js in https://skalman.github.io/UglifyJS-online/

**Comment by BrennanConroy** [comment]
Uglify-js doesn't support ES6+ which we use in this project, additionally if you fix the error you're seeing, you don't get any size wins from uglify because we already used terser (a fork of uglify-es) to uglify the code.

We have no plans to stop using ES6+ in this repo so wont fix this.

For completeness, the error you're seeing comes from https://github.com/dotnet/aspnetcore/blob/465f9294d0b9f5403ab1a25c42ca9cf75e3cdeae/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L655

**Comment by rvicoqbi** [comment]
Thanks for the explanation @BrennanConroy. Yeah, I saw the file is already minified, so there is no size win at all with that code. Just wanted to clarify the error.
Best.
