### ISSUE TITLE
Blazor Application 404 error after command line execution 

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/aspnetcore#39550]
Whenever I start my BlazorServer App manually everything works 
but when I open command line and use `start BlazorApp.exe` i get 404 errors

```css
GET https://localhost:5001/css/bootstrap/bootstrap.min.css [HTTP/2 404 Not Found 2ms]
GET https://localhost:5001/css/site.css [HTTP/2 404 Not Found 2ms]
``` 

is there anything I can do? I want to start the blazor app by sending a command.

**Comment by javiercn** [comment]
@HeroinGyrl thanks for contacting us.

Are you trying to execute the .exe file inside bin/Debug/net6.0? (for example) if that's the case, that won't work because you haven't setup the environment in the same way that `dotnet run` does.

if you want to run the application you need to publish it first using `dotnet publish` and then run the .exe from the `publish` folder. `dotnet publish` is the only command that will produce a valid executable application.

**Comment by HeroinGyrl** [comment]
> @HeroinGyrl thanks for contacting us.
> 
> Are you trying to execute the .exe file inside bin/Debug/net6.0? (for example) if that's the case, that won't work because you haven't setup the environment in the same way that `dotnet run` does.
> 
> if you want to run the application you need to publish it first using `dotnet publish` and then run the .exe from the `publish` folder. `dotnet publish` is the only command that will produce a valid executable application.

I published the file and everything and used `start BlazorApp.exe` on the release file.
but then I figured out that I had to add the content root path and urls. now it works. regarding!
