### ISSUE TITLE
How does SignalR work with Blazor Server when everything is rendered server-side?

### ISSUE THREAD

**Issue by rysep2** [dotnet/aspnetcore#39573]
I understand that Server Blazor doesn't run client-side, instead every frontend rendering is done by the server and updated to the browser over SignalR in the background. So what happens when I create a "second" SignalR hub/client like explained in [this Microsoft Docs page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor)? The SignalR hub is server-side but the SignalR client in the .razor file is server-side too. Does that mean that in this case the SignalR library just forces a rerender of the page server-side and then it is pushed to the browser over the existing Blazor Server SignalR connection? Or is there somehow a second websocket connection?

I'm sorry if this was asked before. I couldn't find any information on this.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24620

**Comment by javiercn** [comment]
@rysep2 thanks for contacting us.

Blazor server applications run on the server, so in this case, having a SignalR connection to another hub (if you are using the C# client) also runs on the server, similar to what happens if from a controller you send an HTTP request to the address where your page is hosted.
