### ISSUE TITLE
Blazor Virtualize - Calls ItemsProvider with request.Count = 0 when not visible

### ISSUE THREAD

**Issue by hakenr** [dotnet/aspnetcore#39723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Let's have a page with Virtualize component.
If you minimize/switch browser window during initial page load (there might be explicit `RefreshDataAsync()` call), Virtualize calls the `ItemsProvider` with `ItemsProviderRequest.Count` set to `0`.

### Expected Behavior

1. The `ItemsProvider` should be first called when the initial count requested is known,
2. or, if it is necessary to call the `ItemsProvider` before that, the `Count` should be set to  `2 * OverscanCount` (the current value of `0` ignores the `OverscanCount` completely).

### .NET Version

6.0.1

### Anything else?

The `Count` is calculated in `CalcualteItemDistribution` method: `https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/Web/src/Virtualization/Virtualize.cs#L302

It seems, that the `CalcualteItemDistribution` method is called only from JS-callback, but the `ItemsProvider` gets called before any such callback happens and thus uses the `_visibleItemCapacity` default value (`0`).

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. As it stands, this is consistent with the intended design for `Virtualize`. Since you're getting the value zero, your code can easily no-op the process and not incur any extra costs.

However, if we continue to get more feedback from the community that this is causing problems, we'll definitely consider changing the design in the future. Hope that's OK!
