### ISSUE TITLE
Razor Pages - ModelBinder Improperly Fills Dictionary with Form Values

### ISSUE THREAD

**Issue by ctorx** [dotnet/aspnetcore#39767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a Razor Page Model has a bound property of type Dictionary<string, string>, if values are posted for the property it is bound correctly, but if values are NOT posted for the property (they are omitted from the form post), the dictionary gets filled with Key Value Pairs from the form itself which is unexpected behavior.

### Expected Behavior

The model binder should NOT fill the dictionary with values from the form, but rather, produce an empty dictionary.

### Steps To Reproduce

I have created an example proof of concept at this repo:
https://github.com/ctorx/ModelBinderDictionaryIssue

### .NET Version

5.0

**Comment by pranavkm** [comment]
Thanks for the issue report. This is by design and documented here - https://docs.microsoft.com/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#prefix--parameter-name. Model binding will look for values that start with `KVPs` and when it does not find any, it'll fall back to an empty prefix. 

You can configure an explicit prefix so that only keys with the `KVPs` prefix are bound: https://docs.microsoft.com/aspnet/core/mvc/models/model-binding#custom-prefix

**Comment by ctorx** [comment]
Thank you, that's what I needed.
