### ISSUE TITLE
Non bubbled event from custom element doesn't reach the Blazor handler

### ISSUE THREAD

**Issue by artzfly** [dotnet/aspnetcore#39831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was trying to add event handler for an @onclosed as below,
![image](https://user-images.githubusercontent.com/60744754/151544769-415733b0-dac7-4317-9222-7b29ae3f3e8c.png)

I have `bubbles` set to `false` for the event triggered from the custom element,
![image](https://user-images.githubusercontent.com/60744754/151545026-c82f6bc3-f729-4253-a834-cf03f9f9a8bd.png)

the Blazor event handler doesn't trigger. I could see this in the documentation.
![image](https://user-images.githubusercontent.com/60744754/151544370-afaf1a9e-631e-48ec-b516-94862584f834.png)

As I am using common custom element code across SPA frameworks I may not be able to enable bubbles only for Blazor.

### Expected Behavior

I should be able to handle non-bubbled events triggered by custom elements inline using Blazor EventHandler.

### Steps To Reproduce

You can reproduce this using https://github.com/msbasanth/BlazorFeatureTester by making bubbles false @/BlazorTesterApp/Client/wwwroot/css/bootstrap/lit-button.js

### .NET Version

.NET 6

### Anything else?

VS 2022 Preview 4

**Comment by SteveSandersonMS** [comment]
Yes, this is by design because Blazor uses event delegation to receive the events. This is performance and is common in other SPA frameworks too.

> As I am using common custom element code across SPA frameworks I may not be able to enable bubbles only for Blazor.

I think you'll have the same issue if you want to support React - see [this](https://www.freecodecamp.org/news/event-propagation-event-bubbling-event-catching-beginners-guide/) and [this](https://stackoverflow.com/questions/43098550/react-js-broke-dispatchevent).

**Comment by artzfly** [comment]
Thanks for the clarification.
