### ISSUE TITLE
.NET 6 Blazor byte[] issue

### ISSUE THREAD

**Issue by DouglasRiddle** [dotnet/aspnetcore#39843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to load a `byte[]` of a plain text document using the .NET 6 `Uint8Array` it appears to be adding unexpected characters to the resulting output.

Actual text
`–€À³JS.ReceiveByteArray’ÄPlain Text String`

Expected
`Plain Text String`

The output returns to normal if I use `new Uint8Array(bytes)` within my javascript

### Expected Behavior

Expect to see just the plain text of the document without using `new Uint8Array(bytes)`

### Steps To Reproduce

Download and run [ByteExampleProject](https://github.com/DouglasRiddle/ByteExampleProject) and select the "Open Plain Text File" button.

To see the expected output, uncomment [this line](https://github.com/DouglasRiddle/ByteExampleProject/blob/master/ByteExampleProject/wwwroot/js/inputfile.js#L15)

### .NET Version

.NET 6

**Comment by javiercn** [comment]
@DouglasRiddle thanks for contacting us.

I believe you should be using the [textencoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) APIs to do the conversion to text on the JS side.

A

**Comment by javiercn** [comment]
Also, I would check the following docs on how to achieve what you are trying to do https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0

**Comment by TanayParikh** [comment]
Thanks @DouglasRiddle for reaching out. You need to update line 19 to use the `Uint8Array` provided as the arg, and NOT the underlying buffer:

```
            var blob = new Blob([bytes.buffer], { type: definedContentType });
```

needs to be changed to:

```
            var blob = new Blob([bytes], { type: definedContentType });
```

as Javier mentioned, https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0 provides more guidance on downloading files with Blazor.

As a side note, you can also use `await js.InvokeVoidAsync` instead of `js.InvokeAsync<object>`. The former has some internal optimizations that are helpful in certain scenarios.

**Comment by DouglasRiddle** [comment]
@TanayParikh I can confirm your resolution works with my existing code.

Thank you both for the provided info and optimization guidance.
