### ISSUE TITLE
Duplicated client assemblies after publish

### ISSUE THREAD

**Issue by Fabster1993** [dotnet/aspnetcore#39884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If i publish a ASP.NET Core hosted web assembly blazor app (using the provided template), then client  assemblies are duplicated in publish folder. Once in wwwroot/_framework folder (with i assume is the right behavior) and once in the publish root folder next to all server assemblies.

### Expected Behavior

All client assemblies occuring only once in wwwroot/_framework folder after publish.

### Steps To Reproduce

- Create a new ASP.NET Core hosted web assembly blazor app (using the template)
- dotnet publish ./Server.csproj
- Navigate to publish output

### .NET Version

6.0.101

**Comment by javiercn** [comment]
@Fabster1993 thanks for contacting us.

That's expected and by design. Assemblies in `wwwroot/_framework` are trimmed and meant for consumption on the browser, while assemblies on the publish folder are meant for consumption by the server app, for example, when prerendering the app.

Hope this helps.

**Comment by Fabster1993** [comment]
@javiercn Oh, that makes sense. Thank you for the answer!
