### ISSUE TITLE
cachedFunction of JSInterop causes memory leaks 

### ISSUE THREAD

**Issue by Inkeliz** [dotnet/aspnetcore#39918]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Using .NET 6 with `JSInterop.InvokeVoidAsync`, may cause memory leak, since the cacheFunction maps (on JS-side of JSInterop) isn't covered by garbage-collector. 

_I don't use C# nor .NET 6. I'm just exploring how C# runtime calls JS functions._

------------

The function documentation describes:

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/JSInterop/Microsoft.JSInterop/src/JSRuntimeExtensions.cs#L15-L21

Given that `"someScope.someFunction"` is a valid function. We can also consider that `someScope` could be one map (such as `new Map()`), in that case each index the internal `cacheFunction` will also cached:

https://github.com/dotnet/aspnetcore/blob/6969db9c0d1f5a1fa61e34cfa1ae01b0066ba306/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L21-L34

### Expected Behavior

It should not cause memory leak, and not implicit cache, or must be covered by GC somehow.

Or, otherwise, that behavior must be documented. It must inform that `JsRuntime.InvokeVoidAsync` caches the argument values, and that isn't suppose to be used for accessing mutable methods and maps (or anything that implements `get` directly). _Consider the code below as example, since it acts like a "function-table" that always return a valid value. That code is valid and a valid JS, and works. It also works currently, but causes memory leaks due to .NET 6 implementation. 

### Steps To Reproduce

If we consider such function in Javascript:

```
window.keyToFunc = new Proxy([], {
    get: function (_, k, _) {
        return function () { /* no-op example */};
    },
    has: function (_, _) {
        return true;
    }
})
```

If we call it using the following C# code:

```
Random rnd = new Random();
byte[] b = new byte[32 * 1024];

for (int i = 0; i < 10_000; i++) {
    rnd.NextBytes(b);
    await JsRuntime.InvokeVoidAsync("keyToFunc." + Convert.ToBase64String(b));
}
```

It would cause a huge memory leak on JS-side of JSInterop. Since it would cache each ` Convert.ToBase64String(b)` value into the `_cachedFunctions`. The values from  `_cachedFunctions` is never cleared by .NET/C#.

### .NET Version

6.0.101

### Anything else?

<details>
  <summary>dotnet --info</summary>

```
SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
  
</details>

**Comment by javiercn** [comment]
@Inkeliz thanks for contacting us.

We cache functions for performance, the number of cached functions is based on the application code, and while you can create schemes like the one you mentioned below, it's your own code creating that situation.

We don't protect you against those things in the same way we don't protect you against infinite recursion. On the expected usage, the amount of JS interop calls an application makes is relatively small and caching doesn't significantly contribute to the memory footprint of the application.

**Comment by Inkeliz** [comment]
> it's your own code creating that situation.

Every memory leak is caused my one specific code, or I'm missing something here?

The code as example is a valid JS and a valid C#.

It's not documented. There's nothing mentioning the cache nor suggesting to not use it for map access (which also works). How someone would know that the example code would "creating that situation"?

Another alternative is enforcing that the value provided isn't a map or ignore cache if the "parent" is a map.

**Comment by javiercn** [comment]
> Every memory leak is caused my one specific code, or I'm missing something here?
The code as example is a valid JS and a valid C#.
It's not documented. There's nothing mentioning the cache nor suggesting to not use it for map access (which also works). How someone would know that the example code would "creating that situation"?

The same way you would do with every other piece of code, if you realize you have a problem you use a profiler to understand where the problem is. It's uncommon to document the performance characteristics of methods outside of collection types.

When we detect that one of our implementations has a problem in a scenario that people regularly run into, we first try to address it, and if not possible we document the pitfalls. We don't document things like cache usage and other implementation details for two reasons:
* Generally it doesn't matter. In the concrete case that you are bringing up, its not a pattern that we've seen applications historically use or a problem we've seen applications run into.
* Code changes all the time, and it consumes a lot of resources to document implementation details and keep them up to date with little return on investment if its not a problem.

In our current JS interop implementation we optimize for a bounded amount of JS interop functions with a cache to speed up the look-ups. This works well for the scenarios we care about and we haven't seen problems with its usage. 
* Does it have trade-offs and edge cases? 
  * Absolutely, like every other algorithm.
* Does it matter?
  * Not much, since we haven't seen people run into issues as its not a pattern people employ in their apps.
* Are there reasonable alternatives available?
  * Yes, you can have a single function and perform your own dispatching within it.
