### ISSUE TITLE
Blazor-server sign in option.

### ISSUE THREAD

**Issue by mrjrdg** [dotnet/aspnetcore#39928]
Hi everyone sorry I posted this issue in the wrong section i'm new on github and i don't know where to ask this question.

So my team and I have built a blazor-server web application and everything went well everything is finish. We started the authentication part 3 day ago and we still can't figute out how to handle that. (SignInManager and UserManager don't work)

In the offical documentation they mention .cshtml and normal old way asp.net authentication but there is no way we will dot that. I mean the goal of having an spa is completely remove if we do that.

So i would like to know if someone have an idea of how we can handle the authentication problem. We though about jwt token. But does the blazor-server mechanism will recognize everything like blazor-wasm do if we do that ? I'm out of idea honestly.

P.S to Microsft team  : Seriously your framework is great but how could you forget something so important (in every enterprise application we need a authentication mechanism) ?

**Comment by TanayParikh** [comment]
Hello @mrjrdg, thanks for reaching out. I'd recommend checking out these documentation pages if you haven't already as they delve into authentication within Blazor. 

- https://docs.microsoft.com/aspnet/core/blazor/security/server/?view=aspnetcore-6.0&tabs=visual-studio
- https://docs.microsoft.com/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0

**Comment by mrjrdg** [comment]
Hi @TanayParikh thank you for your answer. Unfortunately, i already read these article. As i said it mention using .cstml. But we need blazor component for our page not plain .cshtml we don't want to use the old asp.net web app way with redirect() and localredirect() method.  It look on the web that a lot of people are having the same issue that i have with no solution.

**Comment by sholman** [comment]
I would have to agree that having to drop out the Blazor app to go to Razor pages to Authenticate and then go back to Blazor is very, very inconvenient. It means having to manage two different UI's amongst other issues. It would be significantly easier if ASP.NET Identity could be worked into Blazor.

**Comment by javiercn** [comment]
@mrjrdg thanks for contacting us.

While it might be interesting to have the authentication parts of the application implemented using Blazor, there are fundamental challenges in doing so. ASP.NET Core Identity provides the UI layer using Razor Pages and it is designed to work in the context of a Request/Response, contrary to Blazor which works in a stateful model over a websocket. 

SignInManager, UserManager and other Identity abstractions expect an HTTP Request and Response to be available to work. Things like cookies can't be set over a websocket, which is a fundamental challenge to performing authentication in Blazor. In addition to that, there is a good amount of through put into the design and validation of the authentication process that Identity implements, which is why we consider its a much better option to reuse the component altogether instead of creating a new implementation and a new authentication process that we need to design and validate over an existing process that has already gone through those steps.

I understand that it might be "inconvenient" to have a separate UI stack for part of your application or that it might be desirable to perform authentication without leaving the Blazor application, but the reality is that the majority of the SPA frameworks leave the app to perform the authentication process by redirecting to a separate provider and coming back to the app, and in this case, Blazor Server is similar to that.

This is to say that our position is that, even if we implemented UI within Blazor itself and designed and validated a protocol for safely performing the authentication process, we would still end up in a worse position that if we reuse the existing tried and tested processes that we already provide.

I hope this helps clarify that this is not something that we forgot but a deliberate design choice we made. I understand that this causes some friction as its "desirable" to have a "SPA style" authentication where you don't leave the app and that it is inconvenient to use Razor Pages to manage the SPA UI, however we think that reusing the same tried and tested UI and authentication process is a much better trade-off than implementing a separate system that requires design and validation.
