### ISSUE TITLE
Web Component - Virtualization - API Modification proposal - ItemsProviderRequest

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#40031]
## Background and Motivation

Following the [ASP.NET CORE 6 - Blazor - Infer the component type for child components from a method](https://github.com/dotnet/aspnetcore/issues/39217) issue, I am currently using the option C. This means using the delegate below:

```C#
public delegate ValueTask<ItemsProviderResult<TItem>> ItemsProviderDelegate<TItem>(ItemsProviderRequest request);
```

This method has the parameter: ```ItemsProviderRequest```. However, this parameter does not contain any sorting information.

## Proposed API

The goal would be to add sorting information to the ```ItemsProviderRequest``` parameter.

```diff
namespace Microsoft.AspNetCore.Components.Web.Virtualization;
{
    public readonly struct ItemsProviderRequest
    {
+       public List<SortRequirement> SortRequirements { get; }
...
         public ItemsProviderRequest(int startIndex, int count, CancellationToken cancellationToken, 
+               List<SortRequirement> sortRequirements = default!)
        {
            StartIndex = startIndex;
            Count = count;
+           SortRequirements = sortRequirements;
            CancellationToken = cancellationToken;
         }
    }
}
```

```C#
public readonly struct SortRequirement
{
    public int Order { get; }
    public string FieldName { get; }
    public SortDirection Direction { get; }

    public SortRequirement(int order, string fieldName, SortDirection direction)
    {
        Order = order;
        FieldName = fieldName;
        Direction = direction;
    }
}

public enum SortDirection
{
    ASC,
    DESC
}
```

## Usage Examples

When calling a remote provider, the sort requirement can be added. This will give for example the possibility to apply the sorting directly when querying the database. This will be very useful when using a pager. The number of rows that are returned is limited and a previous sort will already be applied. The typical use is a table/grid where there is a multiple sort option.

![image](https://user-images.githubusercontent.com/16502423/152795268-fdd2da3d-ec5d-4386-85ed-89b1529f5a74.png)

## Risks

None. Because the ```SortRequirements``` parameter is optional. There will be no breaking change for the current API.

**Comment by SteveSandersonMS** [comment]
@boukenka Thanks for your suggestions.

We wouldn't add `SortRequirement` to `ItemsProviderRequest` because:

1. That's outside the design for what `ItemsProviderRequest` is meant to represent. Sorting is an application concern, along with filtering or any other way of modifying a query. The expected pattern for getting a virtualized component to use sorting/filtering/etc is simply by storing the desired information on some other field or property and using it in the `ItemsProviderRequest` callback.
2. In general, sorting can be much more complex than the model proposed here. For example it could be multi-column sorting, or involve other special collation rules.

Hope that makes sense!
