### ISSUE TITLE
[Migration] Support sharing auth state with "backend" System.Web app

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40083]
As part of https://github.com/dotnet/aspnetcore/issues/40078, we'll need to determine a way to share auth state between the front end .NET Core, and backend System.Web app. Prelimnary work here is to determine the list of authorization providers (cookie, token etc) that we need to support based on how frequently they appear in user apps.

**Comment by Tratcher** [comment]
Possible kinds of auth (not necessarily the ones people need):
- JWT/Bearer/Basic/Digest/API - Easy, implement in both apps separately.
- Cookie/Forms/Owin - Requires shared formats and encryption
- Identity - Depends on cookie auth, requires a shared database
- OAuth, OpenIdConnect, AzureAd - Depends on Cookie Auth, and where you want to put the login page.
- Windows/Negotiate/NTLM/Kerberos - Would need to be handled by the front end, doesn't proxy well. Could be converted to something else like JWT for the backend. We do something more complex for IIS out-of-proc, (duplicate handles) but I think that only works because IIS started the other process.

**Comment by Tratcher** [comment]
So far I've seen reports from potential migration customers that are currently using:
- JWT
- OWIN Cookies & OpenIdConnect
- B2C

**Comment by adityamandaleeka** [comment]
Closing since this is done as part of https://devblogs.microsoft.com/dotnet/incremental-asp-net-migration-tooling-preview-2/

Further requests in this area can be filed over on https://github.com/dotnet/systemweb-adapters/
