### ISSUE TITLE
Could we have Async validation in Blazor?

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#40244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to run asynchronous validations, but Blazor only supports synchronous ones.

For example, contacting a server to see if a username is already in use.

### Describe the solution you'd like

Support Async validation

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

Do you mean as part of forms and validation or as part of `@bind`

**Comment by oiBio** [comment]
Too bad this is not going to happen soon :-( this would have been pretty handy for us

**Comment by SteveSandersonMS** [comment]
The validation system was originally designed so that:

 * People can implement async validation logic manually
 * In the future, the framework could have additional helpers for async validation to simplify that

For .NET 7 the work plan is already pretty full and we don't expect to schedule anything new around async validation. But there are reasonable patterns for doing it already in your own code.

In fact there are many possible ways of doing it, depending on exactly what kind of UX you want to appear (e.g., whether things should be disabled while async checks are taking place, and whether to keep the async messages on screen until a particular field is edited again, etc.). Here's one fairly arbitrary example:

```razor
@page "/"
@using System.ComponentModel.DataAnnotations
@inject NavigationManager NavManager

<EditForm EditContext="@editContext" OnValidSubmit="TryRegister">
    <DataAnnotationsValidator />
    <p>
        Username: <InputText @bind-Value="@user.Username" />
        <ValidationMessage For="@(() => user.Username)" />
        @if (checkingUsername) { <span>Checking...</span> }
    </p>
    <button type="submit" disabled="@checkingUsername">Register</button>
</EditForm>

@code {
    private User user = new();
    private EditContext editContext = default!;
    private ValidationMessageStore extraValidationMessages = default!;
    private bool checkingUsername;

    protected override void OnInitialized()
    {
        editContext = new (user);
        extraValidationMessages = new (editContext);
        editContext.OnFieldChanged += (_, _) => extraValidationMessages.Clear();
    }

    async Task TryRegister()
    {
        checkingUsername = true;
        try
        {
            if (await IsUsernameAvailable(user.Username!))
            {
                // Success - proceed with saving or whatever you need
                NavManager.NavigateTo("done");
            }
            else
            {
                extraValidationMessages.Add(() => user.Username!, "Sorry, this name is already taken. Pick another.");
            }
        }
        finally
        {
            checkingUsername = false;
        }
    }

    async Task<bool> IsUsernameAvailable(string username)
    {
        await Task.Delay(1000); // Simulate calling some remote endpoint or querying a DB
        return username.Length > 5;
    }

    class User
    {
        [Required]
        public string? Username { get; set; }
    }
}
```

I know this is quite a lot of code, but it does show how you have a lot of control over how exactly the UX flow goes.
