### ISSUE TITLE
Blazor WASM caching persists even with 'no-cache' header (nginx)

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#40249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am unable to clear the cache automatically when I publish a new version in blazor, I have checked online and most solution are either:
- enable 'no-cache' (doesn't have any effect)
- clear content using JS if a new version is available (complex to implement)

so I am asking in the official blazor repository to know what are the possible ways to enable smart caching (load the new version if the files have changed, but keep the app within cache) since the framework was designed here

This is the following config in nginx for my `location /`
```
add_header 'Cache-Control' 'no-cache' always;
root /home/[user]/apps/blazorapp/wwwroot/;
try_files $uri $uri/ /index.html =404;
```

### Expected Behavior

When I go to the app, it should use the new files if they have been updated

### .NET Version

6.0.102

**Comment by javiercn** [comment]
@ctigrisht thanks for contacting us.

Not sure about what exactly do you mean by this. If what you are seeing is that the dlls are not requested on a subsequent reload of the page, that's expected as blazor locally caches them in the browser storage.

You can use `<BlazorCacheBootResources>false</BlazorCacheBootResources>` to disable this behavior. Other than that, if you open your network tab and see the response header applied, everything is working "as expected" and out of Blazor control, its the browser that is ignoring the header. If you don't see the header then something in between your server and the browser is changing it (a CDN might be for example).

**Comment by ctigrisht** [comment]
@javiercn Thanks for the reply
if I set `<BlazorCacheBootResources>false</BlazorCacheBootResources>`, will it disable caching completely and I will have to download the dll's again everytime right

**Comment by javiercn** [comment]
@ctigrisht that's correct, but as I mention, it's not clear what level of caching you are referring to.

That's the additional caching Blazor adds on top of the browser caching. If that's not the caching you are referring to, then it's not clear to us what might be happening in your app. Does the `no-cache` header show up in the responses in the network tab when you run an incognito session? Do you happen to be using a PWA application?

**Comment by ctigrisht** [comment]
@javiercn The `no-cache` header is present and I am indeed using `PWA`.

The caching that I am referring to is the dll's and views, they don't seem to update, it will stay on old versions of the C# code and old razor pages if I don't clear the storage data

Also what I did not understand from your first reply:
`dlls are not requested on a subsequent reload of the page, that's expected`
the above contradicts this: `out of Blazor control, its the browser that is ignoring the header.`

Which is it? is cache within blazor control or out of blazor control?
 
So assuming `no-cache` will not make blazor request the new dll's, how do I cache those dll's but check for a new version from the server? I don't want to disable caching I only want my application to update if I put new files on the server
Do you have any solution for this? Thanks

**Comment by javiercn** [comment]
> I am indeed using PWA.

This is why. The PWA caches the application in the service worker. Check [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-6.0&tabs=visual-studio#offline-support) for details.

There are in general multiple layers of cache involved:
* Blazor caching -> automatic and happens by default unless explicitly disabled.
* Service worker caching -> When you use a PWA, which needs to cache all dlls. By default with a PWA you won't get an updated version until a new version of the service worker gets installed (that's why you see the dlls not being downloaded).
* Browser caching which is what `no-cache` is for.

In your case what I suspect that's happening is that you are updating your app, a version of the service worker gets installed and then when you update the app the next time and visit it on the browser, the service worker serves the installed version of the app while it installs the new version on the background.

You can likely see the installation on the browser dev tools. If you refresh the page after the installation has completed successfully you should see the new version. Similarly, if you use an in-private browser window you should get the new version right away.

That is not specific to Blazor, but an artifact of how PWAs work (specifically service workers) you can see more details [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
