### ISSUE TITLE
SignInManager.GetTwoFactorAuthenticationUserAsync() returns null if called after a long wait after calling PasswordSignInAsync()

### ISSUE THREAD

**Issue by programatix** [dotnet/aspnetcore#40240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm created a project with ASP Core with Identity and enabled 2FA. When a user signed in and immediately enter the 2FA code, it works properly. But if the user signed in, and then keep the LoginWith2fa page open and only enter the 2FA code after a long wait, all calls to SignInManager.GetTwoFactorAuthenticationUserAsync() returns null.

I tried to trace the source code and found that the User is stored somewhere for 2FA purpose. I think the issue is due to the data stored expired.

### Expected Behavior

If it is by design, a better flow should be designed to allow user to re-login, instead of crashing with exception.

### Steps To Reproduce

1. Create new ASP Core with Identity project
2. Run
3. Create a new user
4. Enable 2FA for the user
5. Log off
6. Log in
7. On Two-factor authentication page, wait for a few minutes
8. Proceed to enter 2FA code
9. InvalidOperationException exception will be thrown by OnPostAsync() in LoginWith2fa.cshtml.cs. It is because _signInManager.GetTwoFactorAuthenticationUserAsync() returned null.

### Exceptions (if any)

InvalidOperationException

### .NET Version

6

**Comment by HaoK** [comment]
This is indeed by design, there's a cookie that will expire if you wait too long, you can customize this flow if its important to you by scaffolding Identity UI and changing the logic when the user is null, generally as a best practice for login security we don't disclose reasons for why authentication fails.

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/LoginWith2fa.cshtml.cs#L118
