### ISSUE TITLE
Can't pass headers from browser (typescript) to hub (.NET Core 6)

### ISSUE THREAD

**Issue by felzend** [dotnet/aspnetcore#40307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently using Angular with @microsoft/signalr^6.2.0, and backend with .NET Core 6.0.

I'm trying to pass authentication headers, but I don't receive any.

Won't work with a custom HttpClient neither "headers" attribute.

I'm using LongPolling, since it won't work with WebSockets.

![image](https://user-images.githubusercontent.com/10427954/154755781-c4ba4945-e094-44f6-abda-bb13b7cddd98.png)

![image](https://user-images.githubusercontent.com/10427954/154755914-780d4e43-b506-4e33-8eb4-f2c861772670.png)

![image](https://user-images.githubusercontent.com/10427954/154755816-df714416-4094-47ad-9f7d-f77c122a7d90.png)

**Received headers on debug.**

![image](https://user-images.githubusercontent.com/10427954/154755655-13cffe52-963b-401d-8e36-3b825ed14984.png)

### Expected Behavior

The headers should be received on the backend.

### Steps To Reproduce

The prints above showed the whole process, a simple code.

### Exceptions (if any)

No exceptions, I just received no headers in the backend.

### .NET Version

6.0.100

**Comment by dgrafael** [comment]
According my analysis the issue isn't in the c# backend but the client library who only pass the custom header  in Node Platform as we can see in this source https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts 
   As we can see in the print.
![image](https://user-images.githubusercontent.com/3328658/154979599-73aaba32-0cf9-4ec6-a2a9-1d4949aef21f.png)

**Comment by felzend** [comment]
Yes, the problem is related to the Node library, since I can pass the headers using the Flutter library.

**Comment by BrennanConroy** [comment]
The problem is that browsers do not allow setting headers on WebSocket connections. There is nothing we can do to fix that.
And we mention that WebSockets wont work in the doc comments:
https://github.com/dotnet/aspnetcore/blob/651493c39e14f3b9337d562f0ae67c9dc78ab202/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L12

**Comment by davidfowl** [comment]
> There is nothing we can do to fix that.

You can complain about that here https://github.com/whatwg/html/issues/3062

**Comment by felzend** [comment]
> The problem is that browsers do not allow setting headers on WebSocket connections. There is nothing we can do to fix that. And we mention that WebSockets wont work in the doc comments:
> 
> https://github.com/dotnet/aspnetcore/blob/651493c39e14f3b9337d562f0ae67c9dc78ab202/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L12

Also I mentioned I'm using LongPolling instead WebSockets.

Why won't it work?

On Flutter it works also on browser.

**Comment by davidfowl** [comment]
Long polling will work just fine, we're talking specifically about websockets. 

> On Flutter lib it works also on browser.

Not sure what you mean, but if it's using websockets, it doesn't work with headers.

**Comment by felzend** [comment]
> Long polling will work just fine, we're talking specifically about websockets.
> 
> > On Flutter lib it works also on browser.
> 
> Not sure what you mean, but if it's using websockets, it doesn't work with headers.

Well, but didn't you see I just mentioned I'm currently using LongPolling mode and that won't work anyway?

That's the problem I'm reporting, looks like a bug or a misconfiguration.

**Comment by BrennanConroy** [comment]
Oh I see, your original report wasn't super clear that LongPolling wasn't working as expected.

> I'm using LongPolling, since it won't work with WebSockets.

This makes it sound like you switched to LongPolling to make headers work (which is true) and that your issue was about WebSockets headers not working.

You're hitting this line of code:
https://github.com/dotnet/aspnetcore/blob/5760f2864016081a142642b417db17e5340a1d67/src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts#L114-L116
Which is removing the authorization header when the accessTokenFactory either doesn't exist or returns null. We might want to make it only remove the header when the `accessTokenFactory` is defined by the user.

**Comment by felzend** [comment]
Wow! Indeed....

But anyway, it's good to know the real reason.

Since it's a bug and my middleware is total customized, I'll use a different header name for a while :)
