### ISSUE TITLE
BLAZOR WASM - ADFS - OIDC - Documentation

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#40331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Below is the list of scenarios for [securing ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-6.0). But there is no scenario for **Hosted with ADFS** via OIDC (unless I'm wrong). Could it be added? Or could you provide some guidance for its implementation?

![image](https://user-images.githubusercontent.com/16502423/154951116-900c36af-5186-4c85-85de-c88f081672fe.png)

### Describe the solution you'd like

Documentation for implementing ASP.NET Core Blazor WebAssembly security with ADFS (OIDC) for a hosted solution.

**Comment by javiercn** [comment]
@boukenka thanks for contacting us.

That's not an scenario that we support out of the box. We would recommend that you check the AAD documentation on how to achieve this, it might be that our MSAL package works in this case, but otherwise you would need to build your own support for it. I would recommend you check the implementation of the MSAL package in the repo to get an idea on how to do this, as its not something we currently plan to cover.

**Comment by boukenka** [comment]
@javiercn Ok. Thank you for the answer.
