### ISSUE TITLE
Unable to add test-specific Middleware when writing integration tests with WebApplicationFactory<T>: InvalidOperationException: Unable to build IHost

### ISSUE THREAD

**Issue by Chris-Thompson-bnsf** [dotnet/aspnetcore#40361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using a derived Startup/Program file with the WebApplicationFactory<T> will throw when trying to construct the host. Additionally, using a non-derived Startup file (which uses a private field of the 'base' Startup class) also throws in the same way.

The goal is to be able to provide a test-specific Middleware class, by overriding Startup.Configure(). In this case, I need to be able to specify a 'dummy' IP address for the HttpContext.

This happens both when running the test, and when debugging the test.

### Expected Behavior

WebApplicationFactory<DerivedStartup> should create the host without issue, or throw an exception with more details to identify what the problem is.

### Steps To Reproduce

Background: ASP.NET 6 app, using Startup not minimal API.

ProgramBuilder.cs
```csharp
internal static class ProgramBuilder
{
	internal static IHostBuilder CreateHostBuilder<T>(params string[] args)
		where T : Startup
	{
		return Host.CreateDefaultBuilder(args)
			.ConfigureWebHostDefaults(defaults => defaults.UseStartup<T>());
	}
}
```

Startup.cs
```csharp
public class Startup
{
	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public IConfiguration Configuration { get; }

	public virtual void Configure(IApplicationBuilder app, IWebHostEnvironment env) { }

	public virtual void ConfigureServices(IServiceCollection services) { }
}
```

Program.cs
```csharp
public class Program
{
	public static void Main(string[] args)
	{
		var host = ProgramBuilder.CreateHostBuilder<Startup>(args).Build();

		host.Run();
	}
}
```

IntegrationTestStartup.cs
```csharp
public class IntegrationTestStartup : Startup
{
	/// <inheritdoc />
	public IntegrationTestStartup(IConfiguration configuration) : base(configuration)
	{
	}

	/// <inheritdoc />
	public override void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		base.Configure(app, env);

		app.UseMiddleware<FakeRemoteIpAddressMiddleware>();
	}
}

/// <summary>
/// Sets a dummy IP address on the HTTP connection.
/// </summary>
/// <remarks>See the <see href="https://stackoverflow.com/a/49244494/5038805"/>original SO source</remarks>
public class FakeRemoteIpAddressMiddleware
{
	private readonly RequestDelegate _next;
	private readonly IPAddress _fakeIpAddress = IPAddress.Parse("192.168.0.1");

	public FakeRemoteIpAddressMiddleware(RequestDelegate next)
	{
		_next = next;
	}

	public async Task Invoke(HttpContext httpContext)
	{
		httpContext.Connection.RemoteIpAddress = _fakeIpAddress;

		await _next(httpContext);
	}
}
```

IntegrationTestProgram.cs
```csharp
public static void Main(string[] args)
{
	var host = ProgramBuilder.CreateHostBuilder<IntegrationTestStartup>(args).Build();

	host.Run();
}
```

IntegrationTest.cs
```csharp
public class IntegrationTest
{
	[Fact]
	public async Task Foo()
	{
	    var client = new WebApplicationFactory<Program>().CreateClient();

	    var response = await client.GetAsync("/some/route/here");
	}
}
```

### Exceptions (if any)

System.InvalidOperationException
Unable to build IHost
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.get_Services()

### .NET Version

6.0.200

### Anything else?

Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Visual Studio 2022 17.1.0
XUnit test project:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
	<ItemGroup>
		<PackageReference Include="ApprovalTests" Version="5.4.7" />
		<PackageReference Include="AutoMapper.Extensions.EnumMapping" Version="1.0.0" />
		<PackageReference Include="Extend.XUnit" Version="1.0.0" />
		<PackageReference Include="AutoMapper" Version="10.0.0" />
		<PackageReference Include="EntityFramework" Version="6.4.0" />
		<PackageReference Include="ImpromptuInterface" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="Verify.Xunit" Version="15.2.1" />
	</ItemGroup>
</Project>
```

.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Chris-Thompson-bnsf** [comment]
A workaround for this issue - albeit not a good workaround - is to have a config value, which the real Startup.cs class uses to determine whether or not the 'Test' middleware should be added to the pipeline.

This approach is not ideal, because it means test code is included in the production code, as opposed to being hidden away in the test project.

**Comment by halter73** [comment]
Can you update your Microsoft.AspNetCore.Mvc.Testing package reference to 6.0.2? While you're at it, it probably makes sense to upgrade EF to 6.4.4 and any other packages that don't have the latest patch. It's possible you're hitting a timeout that was increased in a patch (see https://github.com/dotnet/runtime/pull/61688). At the very least, you should get a better exception message than "Unable to build IHost".

The old way `WebApplicationFactory` used to work was by looking for a `public static IHostBuilder CreateHostBuilder(string[] args)` in `Program` (or whatever class contains the entry point). This still works, so you might be able to work around this issue by just adding a `Program.CreateHostBuilder` method.

Starting in 6.0, `WebApplicationFactory` gained the ability to invoke the entry point and wait for a call to `HostBuilder.Build()` to capture the `IHostBuilder`.  This allows it to support minimal projects where the `Program.CreateHostBuilder` method doesn't exist. This can run into problems if `HostBuilder.Build()` is never called or is called too late. That's why `WebApplicationFactory` still prefers calling `Program.CreateHostBuilder` over the entry point if it exists.

**Comment by Chris-Thompson-bnsf** [comment]
> Can you update your Microsoft.AspNetCore.Mvc.Testing package reference to 6.0.2? While you're at it, it probably makes sense to upgrade EF to 6.4.4 and any other packages that don't have the latest patch.

I'll give this a shot, thanks for the suggestion.

Quick question regarding this package's versioning - is it going to be kept in-line with the other dotnet core packages? Meaning, if there exists a `Microsoft.AspNetCore 6.0.x`, there will always be a `Microsoft.AspNetCore.Mvc.Testing 6.0.x` (for a given x)?

Asking because I already have a `<DotnetCoreVersion>6.0.0</DotnetCoreVersion>` property defined in our Directory.Build.props file in the repo, and I was wondering if it would be safe to use that same property for this package version, as is being done for some of the other packages, such as Microsoft.Extensions.DependencyInjection (in the library projects).

> The old way `WebApplicationFactory` used to work was by looking for a `public static IHostBuilder CreateHostBuilder(string[] args)` in `Program` (or whatever class contains the entry point). This still works, so you might be able to work around this issue by just adding a `Program.CreateHostBuilder` method.
> 
> Starting in 6.0, `WebApplicationFactory` gained the ability to invoke the entry point and wait for a call to `HostBuilder.Build()` to capture the `IHostBuilder`. This allows it to support minimal projects where the `Program.CreateHostBuilder` method doesn't exist. This can run into problems if `HostBuilder.Build()` is never called or is called too late. That's why `WebApplicationFactory` still prefers calling `Program.CreateHostBuilder` over the entry point if it exists.

Interesting. I omitted it from the original post - because Main() was not calling that method - but I do have the `Program.CreateHostBuilder` method still, though I did update it to take in `params string[] args`, not just `string[] args` - I assume that wouldn't matter even on 6.0.0?

**Comment by halter73** [comment]
> Quick question regarding this package's versioning - is it going to be kept in-line with the other dotnet core packages? Meaning, if there exists a Microsoft.AspNetCore 6.0.x, there will always be a Microsoft.AspNetCore.Mvc.Testing 6.0.x (for a given x)?

NuGet packages shipped out of this repo (dotnet/aspnetcore) like Microsoft.AspNetCore.Mvc.Testing and Microsoft.Extensions.Features get a new release every time we patch the shared runtime even if the package itself hasn't changed other than the version. This keeps package versions and AssemblyInformationVersions aligned with the shared runtime version. Packages shipped out of the dotnet/runtime repo only get pushed if they've been serviced in that particular patch. When they are serviced, the AssemblyInformationVersion but not the package version is aligned with the shared runtime.

![shared framework dlls](https://user-images.githubusercontent.com/54385/155815704-a732255a-cd3d-4e13-950f-0847dfad540e.png)

For example, the Microsoft.Extensions.Caching.Memory.dll in the screenshot above with the 6.0.2+... AssemblyInformationVersion is shipped as part of the 6.0.1 package even though the 6.0.1 runtime shipped with the 6.0.0 dll. You can [see for yourself here](https://nuget.info/packages/Microsoft.Extensions.Caching.Memory/6.0.1).

I'm not sure there's a good way to reference these misaligned package versions with a single `<DotnetCoreVersion>` property defined in your Directory.Build.props file outside of an ASP.NET Core app assuming you don't want to float patch versions. However, since you are targeting Microsoft.NET.Sdk.Web, you shouldn't need the Microsoft.Extensions.Logging package references because those are included as part of the Microsoft.AspNetCore.App framework reference. I think this is true for most packages shipped out of the runtime repo, so maybe you can just remove those references and continue using `<DotnetCoreVersion>` for just the packages shipped out of the aspnetcore repo.

The more general solution might be having the package versions baked into each csproj and running a bot that applies a `nuget update` and submits a PR on some interval. Wildcarding patch versions might also be an option, but I certainly understand not wanting to do that.

@dotnet/runtime-infrastructure Do any of you have any better suggestions for how to easily keep `Microsoft.Exntensions.*` packages up to date using a single msbuild property without floating patch versions? It does seem like the aspnetcore way of servicing packages is easier for customers to understand and deal with.

Either way, it'd probably be better if we were consistent with how we handled this between repos. Is the way we version patches documented anywhere?

**Comment by Chris-Thompson-bnsf** [comment]
I got around to re-testing this today with the suggested change of using 6.0.2, and I did get past the IHost building error.

To do this, I had to use an arguably less intuitive workaround than my initial workaround, because of a CS0017 (multiple entry points) build error when trying to define a Program class in an XUnit test project. [This article](https://andrewlock.net/fixing-the-error-program-has-more-than-one-entry-point-defined-for-console-apps-containing-xunit-tests/) has a good explanation of the reasoning behind it, but the solution it poses isn't really applicable in my use case.

To get around this issue while keeping the test code out of the production code entirely, I resorted to creating another project to house the derived Startup class, and its own Program class (which made use of the derived Startup class). The existing XUnit test project then references these types via `WebApplicationFactory<IntegrationTestProgram>`.

So, while I am able to get past the original exception that was described, I still think this is an area that could do with some improvement, as something this simple seems to not be particularly easy to support.

Granted, the only reason I even needed this type of functionality was because of a dependency on the IP address of a request while using `WebApplicationFactory<Program>` (which leaves it as null).

In an ideal world, I could set something up on the client/request to populate that, rather than requiring this test middleware at all.

**Comment by halter73** [comment]
@Chris-Thompson-bnsf Did you consider adding an `IStartupFilter` to the `WebApplicationFactory<Program>` via `WithWebHostBuilder` and `ConfigureTestServices`? This should allow you to add middleware for testing without having to define an `IntegrationTestProgram`.

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#inject-mock-services
