### ISSUE TITLE
UseCorrectCatchAllBehavior breaks optional parameter behavior

### ISSUE THREAD

**Issue by tokrqui** [dotnet/aspnetcore#40389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to use the catch-all option for dynamic routing. Dynamic route with parttern "{**path}" must handle invalid paths in requests. 

For catch-all route to work correctly, I have to enable switch "Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior". 

But with this switch enabled, the route "foo" stops processing the path /foo. Request with /foo fall into the last dynamic route with the pattern "{path?} instead "foo" route.

### Expected Behavior

Routes are tried in order of adding or according to their priority and specificity.

### Steps To Reproduce

Here is demo project https://github.com/tokrqui/DynamicCatchAllRouteDemo

To reproduce the issue, run project and open in browser 
http://localhost:5000/foo

You will see text"optional path".

If you comment line
AppContext.SetSwitch("Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior", true);
in Program.cs, then request 
http://localhost:5000/foo will respond with text "foo", as expected.

### .NET Version

3.1.0

**Comment by javiercn** [comment]
@tokrqui thanks for contacting us.

The behavior you are observing is correct, and by design, although a bit "weird" and something we changed in 5.0.

If you look at the routes

```
endpoints.MapDynamicControllerRoute<CatchAllRouteValueTransformer>("{**path}"); // Order = 0
endpoints.MapControllerRoute("foo", "foo", new { Controller = "Foo", Action = "Index" });
endpoints.MapGet("bar", async context => { await context.Response.WriteAsync("bar"); });
endpoints.MapDynamicControllerRoute<OptionalPathRouteValueTransformer>("{path?}"); // Order = 0
```

The ones with a transformer have Order = 0.

While `endpoints.MapControllerRoute("foo", "foo", new { Controller = "Foo", Action = "Index" });` is a conventional route an has Order 1.

It's for that reason that you see optional path winning over foo in that case.

In 5.0 and onwards we did a breaking/behavior change to align this with how conventional routes where the order is based on the definition order, with better reflects what people expect. In 5.0 and onwards all dynamic routes and conventional routes share the same match order which starts at 1 and increments with every route. So with your sample, the order in 5.0 is:

```
endpoints.MapDynamicControllerRoute<CatchAllRouteValueTransformer>("{**path}"); // Order = 1
endpoints.MapControllerRoute("foo", "foo", new { Controller = "Foo", Action = "Index" }); // Order = 2
endpoints.MapGet("bar", async context => { await context.Response.WriteAsync("bar"); }); // Order = 3
endpoints.MapDynamicControllerRoute<OptionalPathRouteValueTransformer>("{path?}"); // Order = 4
```
