### ISSUE TITLE
OnConnectedAsync intermittently not called

### ISSUE THREAD

**Issue by nuteman1** [dotnet/aspnetcore#40465]
Not sharing the same Azure SignalR Service instance between two hubs resolved the issue.

_Originally posted by @Arash-Sabet in https://github.com/dotnet/aspnetcore/issues/6448#issuecomment-463206526_

**Comment by nuteman1** [comment]
Hi,

So in https://github.com/dotnet/aspnetcore/issues/6448#issuecomment-463206526, Arash-Sabet said that he solved the issue by not having more than one app server instance (though he called them "hub") connecting to the same Azure SignalR Service.
I do have multiple app server instances connecting to the same Azure SignalR Service, as I believe Microsoft recommends here https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-6.0.

In my case I have a log message being written at the very top of the OnConnectedAsync:

**_logger.LogInformation("In PanelsHub.OnConnectedAsync, Connection ID = {connectionid}", Context.ConnectionId);**

When I don't get the messages on the client, I check the logs for all the instances. None of them have the message for that connection ID. When all goes well, one of them has the corresponding log message.

The problem is intermittent - most of the time OK, sometimes the problem.

The client is JavaScript client, version 5.0.14 (very recent release). The server is microsoft.azure.signalr, version1.15.2.

As Aresh-Sabet said, there doesn't appear to any error logged from the SignalR components (client or server) - it just doesn't invoke the OnConnectedAsync.

Any insight?

**Comment by nuteman1** [comment]
Might this be related to the problem?:

![image](https://user-images.githubusercontent.com/47330400/156169533-23623294-26c0-4e30-98eb-cac55ae9de02.png)

**Comment by vicancy** [comment]
Yes, it is possible when the service is under Classic mode.

It is also possible when you have multiple different app servers connected to the same service, and the client was actually routed to another app server that you were not monitoring.

You can enable your diagnostic log to see what happened as described here: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-diagnostic-logs, or you can try this live trace tool if you can easily repro the issue: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-live-trace

If it is caused by "Classic" mode, you can see some client connections "enter serverless mode".

You can aslo email me `lianwei(at)microsoft` the timestamp when the client connected  however no connected event was triggered, as well as **the URL** client used to connect, and I can check the service log to see what happened to the connection.

**Comment by nuteman1** [comment]
My bad: We had an instance deployed from years ago that was running outdated code that I wasn't aware of, The clients that happened to connect to that instance were experiencing the problem (as in the old OnConnectedAsync the association of connection ID to group was not happening according to the new/updated approach). And it was intermittent as it only happened for those client connecting to the old instance. When I deleted that instance, all was good.
Thanks!
