### ISSUE TITLE
Azure webapps rewriting backslash to slash

### ISSUE THREAD

**Issue by ioantoader** [dotnet/aspnetcore#40532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Here is my controller sample code:

```
using Microsoft.AspNetCore.Mvc;

namespace TestRoute.Controllers
{
[Route("api/[controller]")]
[ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
[ApiController]
public class TestRouteController : ControllerBase
{
[HttpGet("{*documentId}", Name = "Get")]
public IActionResult Get([FromRoute] string documentId)
{
return Ok(new { documentId });
}

}
}

```

when I enter for the documentId **abc\xyz** (https://testrouteit1.azurewebsites.net/api/TestRoute/abc%5Cxyz) the method return **abc/xyz** value

### Expected Behavior

To return abc\xyz

### .NET Version

5.0.14

**Comment by javiercn** [comment]
@ioantoader thanks for contacting us.

@Tratcher I believe the host might be doing this, even before getting into kestrel.

**Comment by ioantoader** [comment]
If I tested on my PC with kestrel or IIS is working fine

**Comment by adityamandaleeka** [comment]
This is by design. If you want to get the exact value, you can try reading the `X-WAWS-Unencoded-URL` header.

**Comment by bradygaster** [comment]
After corresponding with the service team, I learned that this is By Design: IIS FE's URL parse the request URL during proxying, so the URI will be modified (canonicalized and normalized).

The work around is for the app to use the `HTTP_X_WAWS_UNENCODED_URL` server variable (a.k.a. `X-WAWS-Unencoded-URL`: header).  This header contains the *exact* bytes as they were received from the wire.
