### ISSUE TITLE
"body stream already read" error due to broken blazor wasm fallback

### ISSUE THREAD

**Issue by kg** [dotnet/aspnetcore#40547]
Right now if a streaming compile of the blazor wasm binary fails, we fall into a fallback path that won't actually work. It produces this error:

```TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read```

This is because the first compile attempt already consumed the body of the response, and it can't be consumed a second time. The fix is to issue a second fetch before attempting to compile again. We would want to do that in the fallback path above here:

https://github.com/dotnet/aspnetcore/blob/98641b09c16d2d6843495fb4d4e391586add56bd/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L646

We also currently just try to do a streaming compile, but the most common failure case is detectable without trying to compile - if the content-type of the response is not ```application/wasm``` the streaming compile will always fail, so we should probe for that (via ```response.headers.get("Content-Type")```) and if it doesn't match we should just immediately jump to the fallback. This would eliminate the need for a 2nd fetch.

(The second fetch shouldn't be a performance issue anyway, it should hit the browser cache.)

cc @radical

**Comment by radical** [comment]
An issue where this manifested - https://github.com/dotnet/aspnetcore/issues/40528

**Comment by radical** [comment]
cc @pranavkm

**Comment by javiercn** [comment]
Seems that the underlying issue is the OOM happening.

I'm closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/40547

**Comment by CoryKoehler** [comment]
@danroth27 @SteveSandersonMS 
Hello, I put in an issue similar and closed it since this one seems to be the one where everything is tracked regarding this.
I don't think this can be pushed to .Net7. I am having customers complain currently on this. Depending on device (both Android and IOS are affected)

This to me seems huge and would make my clients rethink any investment in Blazor. 
An existing production site that is blazor wasm hosted that is having this issue is boatsforsale.com and replicate this issue with enough attempts on smaller devices. The site will display just a loading spinner forever and in the console you'll see
![image](https://user-images.githubusercontent.com/5295679/160139181-f0655f38-9697-40ee-806b-896ba592d259.png)

Is there any way this could be looked into for an earlier release than next nov?

**Comment by SteveSandersonMS** [comment]
@CoryKoehler I suspect this issue isn't your actual problem, and that https://github.com/dotnet/aspnetcore/issues/40548 is. We have an ongoing discussion with the runtime team and will post updates there.

**Comment by TanayParikh** [comment]
I'm going to close this out in favor of https://github.com/dotnet/aspnetcore/issues/42055.
