### ISSUE TITLE
React SignalR - customHeader

### ISSUE THREAD

**Issue by pamav** [dotnet/aspnetcore#40659]
Hi,

I found little problem with custom Header:
MyCode:
```typescript
const options: IHttpConnectionOptions = {
    headers: { app: 'test' },
}

const connect = new HubConnectionBuilder()
    .withUrl(`${baseUrl}${connTypeParams[0]}`, options)
    .withAutomaticReconnect()
    .build()
```

but on server side with .Net 6
```csharp
public class CustomHub : Hub<ICustomAction>
{
    public override Task OnConnectedAsync()
    {
        var x = Context.GetHttpContext().Request.Headers["app"];
        return base.OnConnectedAsync();
    }
}
```

varible x is always empty.
If I check in browser developerTools only first request from clietn with url negotiate?negotiateVersion=1 has Header param app.

What is wrong?

Thank you

**Comment by BrennanConroy** [comment]
This is the expected behavior when using WebSockets in the browser.
https://github.com/dotnet/aspnetcore/blob/38865d0415e8196bbd4a0a9b218203ae129495c6/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L12-L13

Browsers do not support adding headers to WebSocket requests. You can try to push for that feature here: https://github.com/whatwg/websockets/issues/16
