### ISSUE TITLE
RAM problems when downloading files

### ISSUE THREAD

**Issue by onimor** [dotnet/aspnetcore#40658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to download and upload files using the minimal api. I did it as described in the documentation. 
Blazor WASM acts as a client. 
When I get a stream file from the api and call JS to download, then ~1.3 gigabytes of RAM is consumed for a 400mb file and is not released. When downloading again, the amount of memory consumed only increases. Thus, uploading and downloading files becomes problematic.

### Expected Behavior

In the console , WinForm and other projects, it consumes ~ 18 MB, I expect about this, not 1.3 gigabytes

### Steps To Reproduce

[https://github.com/onimor/FileUploadDownloadBlazorWasm
](https://github.com/onimor/FileUploadDownloadBlazorWasm
)
Place your file to be downloaded in the folder "FileUploadDownloadBlazorWasm.minimalapi/Resources/Testfile", after deleting what is there.
I used a 400 MB file. run the project "FileUploadDownloadBlazorWasm.MinimalApi" and click the download button, see how much RAM was used. Click again to download the file again, compare before and after. It is always growing and never released.

### .NET Version

6.0.200

### Anything else?

Microsoft Visual Studio Enterprise 2022 (64) - Preview
Версия 17.1.0 Preview 6.0

**Comment by javiercn** [comment]
@onimor thanks for contacting us.

This is an artifact of several things:
* HttpClient will create a buffer to contain the response, so that's 400MB there.
* In addition to that, there are the buffers used to transfer the file from .NET to JS
* Finally, CreateObjectUrl will create an additional buffer.

My suggestions would be:
* Forcefully trigger a GC and see if the memory is freed.
  * You might not observe anything depending on how you are measuring because having free memory in .NET doesn't mean it returns it to the underlying host.
  * It might also be the case that while webassembly can grow memory, it might not be able to shrink it.
* It might be that chrome doesn't free the memory immediately either as it holds on to it in case it wants to reuse it. Normally, while you have available RAM on your system, processes will keep allocating and keeping the memory as it saves costly OS syscalls.
* You can test the limits with your app and see if you get into a situation where the app crashes after downloading X GB of files (not that I mean downloading multiple files, not a gigantic file) or if the memory gets released/reused at some point.
* Finally, if you are downloading very large files, I would skip .NET all together and do this directly via JS interop and fetch. Using HTTP client in this scenario is not buying you a lot.

**Comment by onimor** [comment]
@javiercn I found a solution that is to use a direct link to stream
`await JS.InvokeVoidAsync("triggerFileDownload", "/api/TestFile",fileName);`
Now everything is fine with this way of downloading the file. We can say that there are no expenses.
But the problem with uploading files back to the server remains.
The method described in the documentation spends a lot of memory.
```
private async Task OnInputFileChange(InputFileChangeEventArgs e)
    {  
        var upload = false;

        using var content = new MultipartFormDataContent();

        foreach (var file in e.GetMultipleFiles(3))
        { 
                try
                {
                    var fileContent = new StreamContent(file.OpenReadStream(file.Size));

                    fileContent.Headers.ContentType = 
                        new MediaTypeHeaderValue(file.ContentType); 
                    content.Add(
                        content: fileContent,
                        name: "\"files\"",
                        fileName: file.Name);

                    upload = true;
                }
                catch (Exception ex)
                {
                    
                } 
        }

        if (upload)
        {
            var response = await httpClient.PostAsync("/api/TestFile", content); 
        } 
    }
```

**Comment by onimor** [comment]
`await JS.InvokeVoidAsync("triggerFileDownload", "/api/TestFile",fileName);`
this is a bad option, because if you use authorization, the file will not be downloaded. And if you do as I wrote above (following the example of the documentation), then the memory goes away and is not released, when you download it again, it is spent again, and not reused. what to do about it?

**Comment by sane1998k** [comment]
Yeah, i've the same problem!

**Comment by javiercn** [comment]
By design as per https://github.com/dotnet/aspnetcore/issues/40658#issuecomment-1065025283
