### ISSUE TITLE
Add ElementReference to InputRadioGroup & InputRadio

### ISSUE THREAD

**Issue by rfabro** [dotnet/aspnetcore#40804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The InputRadioGroup & InputRadio doesn't have the `ElementReference` unlike the other Blazor form components. I'm trying to set focus on these controls and since they don't have `ElementReference` I wasn't able to call the `FocusAsync` extension method.

### Describe the solution you'd like

Add ElementReference to InputRadioGroup & InputRadio so I can set focus on these components without using the JS interop.

**Comment by javiercn** [comment]
@rfabro thanks for contacting us.

@MackinnonBuck I vaguely remember you did the original PR to add these components (InputRadioGroup and InputRadio) and also the PR for adding ElementReference to the original InputBase element.

Could you spend 30 minutes to propose a concrete design so that it can be implemented by someone on the community as an enhancement if they choose to do so? I imagine the implementation will be very similar/identical to the existing InputBase implementation, but I'm not familiar with all the details in this area.

**Comment by campersau** [comment]
Original PR for reference: https://github.com/dotnet/aspnetcore/pull/29555
