### ISSUE TITLE
Allow For Inheritance with RouteAttribute

### ISSUE THREAD

**Issue by zhurst31** [dotnet/aspnetcore#40825]
## Background and Motivation
Currently, the ```RouteAttribute``` is marked as sealed [see here](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/Components/src/RouteAttribute.cs#L10).

It would be nice if we could inherit off of the ```RouteAttribute``` to allow for convention based routes.

## Proposed API
```diff
namespace Microsoft.AspNetCore.Components;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
- public sealed class RouteAttribute : Attribute
+ public class RouteAttribute : Attribute
```
## Usage Examples
Area based routing
``` C#
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public class AdminRoute : RouteAttribute
{
    public AdminRoute(string template) : base($"/Admin/{template}")
    {
    }
}

[AdminRoute("Setup")] /* this would evaluate to /Admin/Setup */
public partial class ApplicationSetup : ComponentBase
{
}
```

Multi-Tenant based routing
``` C#
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public class MultiTenantRoute : RouteAttribute
{
    public MultiTenantRoute(string template) : base($"/{{Tenant}}/{template}")
    {
    }
}

public class MultiTenantComponentBase : ComponentBase
{
    [Parameter]
    public string Tenant { get; set; }
}

[MultiTenantRoute("Settings")] /* this would all for /XYZ/Settings where XYZ is the Tenant */
public partial class Settings : MultiTenantComponentBase
{
}
```
## Alternative Designs
None

## Risks
None

**Comment by zhurst31** [comment]
@mkArtakMSFT Saw the labels added. Not sure if this should also be filed under [area-blazor](https://github.com/dotnet/aspnetcore/labels/area-blazor). I forgot to specify in the issue description but I found this issue / limitation using Blazor WebAssembly.

**Comment by javiercn** [comment]
@zhurst31 thanks for contacting us.

WRT to routing in ASP.NET Core, the attributes are not meant to be extended. They all implement interfaces and people can create their own attributes based on that.

WRT to attributes in Blazor, there's no point in overriding them since they are applied through the `@page` directive and you don't get control of the metadata we emit from the compiler.

If we were to do something in this area, it would be something in the same vein as ASP.NET Core routing, where we would offer an interface that people could implement in their own attributes.

That said, we haven't received significant feedback on this area, so I'm going to put it in the backlog to collect more data points and then we can re-evaluate.

**Comment by MackinnonBuck** [comment]
Closing this out since there hasn't been any community activity in a while.
