### ISSUE TITLE
W3CLogger tests pass despite using DateTime.Now instead of DateTime.UtcNow

### ISSUE THREAD

**Issue by gfr-g** [dotnet/aspnetcore#40844]
## Failing Test(s)

- `Microsoft.AspNetCore.HttpLogging.W3CLoggerTests.WritesDateTime`
- `Microsoft.AspNetCore.HttpLogging.W3CLoggingMiddlewareTests.DefaultDoesNotLogOptionalFields`
- `Microsoft.AspNetCore.HttpLogging.W3CLoggingMiddlewareTests.TimeTakenIsInMilliseconds`

## Error Message

All tests share the same assertion fail 

```text
Assert.True() Failure
Expected: True
Actual:   False
```

## Problem

The problem seems to be caused by an incorrect use of `DateTime.Now` in the tests. 

```
var now = DateTime.Now;
[...]
var startDate = DateTime.Parse(lines[1].Substring(13), CultureInfo.InvariantCulture);
// Assert that the log was written in the last 10 seconds
Assert.True(now.Subtract(startDate).TotalSeconds < 10);

```

But the `W3CLoggerProcessor` uses `DateTime.UtcNow` when writing the date (which is then parsed to `startDate` in the code above). 

`await WriteMessageAsync("#Start-Date: " + DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture), streamWriter, cancellationToken);`

## Resolution

The fix should be as simple as changing 

`var now = DateTime.Now;`

to

`var now = DateTime.UtcNow;`

in all affected tests.

**Comment by wtgodbe** [comment]
Good catch, thanks for the report - https://github.com/dotnet/aspnetcore/pull/40881 should resolve the issue

**Comment by wtgodbe** [comment]
It was because the check was for the delta being less than 10 seconds - in time zones that are behind UTC, the delta would be a negative number, so the tests still passed. They'd fail in time zones ahead of UTC. https://github.com/dotnet/aspnetcore/pull/40922 should fix the logic (though centralizing on `UTCNow` already prevents this failure class, correcting the logic is still good).
