### ISSUE TITLE
Use IEquatable for Blazor object parameters to optimize rendering by default

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#40867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

After working with Blazor for quite a few hours I notice these two things:

1. You want to pass objects or list of objects as parameters quite frequently to build real world components. Apart from the most simple low level inputs or "grain" level components you usually build components against a class hierarchy (Person, Address, Order etc). Thus the most convenient way to build "app-level" components is to pass class instances around as parameters. 
2. Playing mind games when running / debugging: "will it re-render". Simple type parameters are diff checked, but if there is any object parameter the component is re-rendered regardless if the state of that object has changed or not. I also notice this as a frequently overlooked "default" of Blazor by novice developers.

Reducing the number of re-renders can greatly improve performance of a Blazor application.

Right now, we have the following options to tweak this (per https://docs.microsoft.com/en-us/aspnet/core/blazor/performance):
1. Use exclusively primitive immutable types. This can become quite laborious if you render say 5+ properties of an object, and you have to break it down into primite types. E.g.: Address object with Street, 
2. Override ShouldRender. This places the burden of "when does my object change" inside the component. 

I propose a third option

### Describe the solution you'd like

Improve the Blazor re-rendering logic by checking if an object Parameter implements `IEquatable` and then skip StateHasChanged automatically if the object has not changed:
https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2022

This could be built-in or opt-in using an attribute to not break existing applications:
```[Parameter, Equatable] public MyObjectThatImplementsIEquatable { get;set; }```

**Comment by javiercn** [comment]
@rogihee thanks for contacting us.

This has come up several times. While it sounds like a good idea, we are worried of a few things with this approach which is why we haven't taken this route. Blazor diffing algorithm is very conservative and is limited to well-known value types as well as a few well-known immutable types. 

The reason for this is that we can't in general detect if an object/reference type has been mutated, and the consequences of failing to effectively do this are bad, as they result in rendering bugs that are incredibly hard to diagnose. For example, some part of your page might not update after a change.

Supporting IEquatable implementation and using that in the diffing algorithm also has another drawback which is that it makes the performance of the system non predictable, since we don't have control of the performance of the IEquatable implementations, the consequences are that a poorly performant implementation only manifest as "my app/the framework is slow" when the cause is the implementation of the interface used during comparison.

We've talked about how we could improve this for certain patterns like `records`, etc. However in general the problem is that implementing IEquatable in an object doesn't guarantee that it implements `deep structural equality`, for example when an object has a reference to another object its out of the class with the reference to control whether the other object is equal to another instance (for example if that object class is in a separate assembly).

We want to continue handling the diffing logic as much as possible to ensure that we can offer a consistent performance experience and that users don't need to look into these types of optimizations to make their app perform well. Our goal is that even with our current diffing logic apps should perform well.

In general, we want to be very conservative and always re-render when in doubt, as that will always lead to the correct behavior. In addition to that, while it's not ideal you can already have control over this process on a per-component basis by overriding `SetParametersAsync` and returning early if you deem the parameters you are comparing are equal.

Our diffing strategy only controls whether a component receives a new call to `SetParametersAsync` and the component is ultimately responsible for deciding whether to re-render or not.

In addition to that, I would also caution that there is another drawback to doing this with general objects, which is that those graphs can get very large very quick and result in a performance degradation due to additional number of comparisons to perform, while with the current approach, you "pay for what you render" vs how big your model is.

I understand that this might not match your expectations, but I hope it at least provides some insight into our reasoning about why we went with the current design/trade-offs and why we think it is important to be conservative in this area.

We would be open to considering other proposals that respect the current properties that we care about, like having predictable performance and keeping control of how the diff happens while expanding the set of types that we can detect we can correctly compare for structural equality.

**Comment by rogihee** [comment]
@javiercn Thanks a lof for this *very* detailed answer and reasoning, this is greatly appreciated. Thinking about this with your information, I think your reasoning is more correct. Again, thank you for taking the time to answer.
