### ISSUE TITLE
UsePathBase regex

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#40959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to add a regex in ``UsePathBase``, I want to culture the entire URL

### Describe the solution you'd like
I am using blazor server side.

I currently have something like this:
```
            app.UsePathBase("/pl");
            app.UsePathBase("/pl-pl");
            app.UsePathBase("/en");
            app.UsePathBase("/en-us");
            app.UsePathBase("/de");
            app.UsePathBase("/it");
```
Need:
```
app.UsePathBase("/{culture:regex(^[a-zA-Z]{{2}}(-[a-zA-Z+]{{2}})?$)}");
```

This creates many problems but solves the one I care about. Thanks to this, we can have a culture in each URL. e.g:
``domain.com/en-us/register``

```cs

                endpoints.MapGet("/{culture:regex(^[a-zA-Z]{{2}}(-[a-zA-Z+]{{2}})?$)=pl}/{**rest}", async context =>
                {
                    var culture = context.Request.RouteValues["culture"] ?? _website.Culture;
                    var rest = context.Request.RouteValues["rest"];

                    var option = new CookieOptions
                    {
                        Expires = DateTime.Now.AddYears(1)
                    };
                    context.Response.Cookies.Append("Culture", culture.ToString() ?? "", option);
                    await Task.CompletedTask;
                });
```

Unfortunately, when we use ``PathBase``, this request will not be performed and it will not save the cookie culture. Do you have an idea how to do it?

The effect I want to get is written here:
https://github.com/dotnet/aspnetcore/issues/38584#issuecomment-976637332

The problem of using ``app.UsePathBase`` is that a value is added to ``<base href = "~ /" />``, so we need to change to ``<base href = "/" />``

### Additional context

Let me know what you think, in short I need to be able to prefix in the url. I need to support the culture as in the example in the link above.

**Comment by adityamandaleeka** [comment]
@Alerinos we won't implement a feature for this (as you described, it creates many problems :) ) but you can implement this behavior yourself in middleware.

You'll want to do something like this: https://source.dot.net/#Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs,49

**Comment by rjgotten** [comment]
@Alerinos 
FWIW; keep in mind that using `PathBase` when you also need to support generating links to switch between different cultures/locales/languages is a bit of a pain. You need to use the signatures for link generator where you explicitly pass the `pathBase` parameter; can't pass it as a route value. And that also means pain when you have an application using e.g. `asp-*` tag helpers.

Moreover; consider that `PathBase` is added to each and every generated link. You may not want that when generating links to resources that are not localized at all, e.g. CSS or JavaScript assets.

The proper solution would be to wrangle the endpoint routing system to add the culture to the route.
But, because of how the system for merging ambient and current route values works, it will still delete the ambient culture even though it would be 'more to the left' - i.e. higher up the path hierarchy - than action/controller or other route values. Meaning you need to pass the culture to use on _all_ your link generation. 
... Or you hack the system and author and register into the `IServiceCollection` an implementation of `LinkGenerator` which decorates `DefaultLinkGenerator` and which forcibly reintroduces the ambient `culture` routeValue as a current `culture` routeValue before passing on to the default generator's `GetPathByAddress` and `GetUriByAddress` methods.

That gives you your cake _and_ allows you to eat it.

**Comment by blowdart** [comment]
As an aside if you're going to do this yourself *please* put a timeout on the regex, otherwise you may end up with catastrophic backtracking DoS attacks depending on your expression.
