### ISSUE TITLE
Nesting AuthorizeView and Authorized components with various roles

### ISSUE THREAD

**Issue by aterbo** [dotnet/aspnetcore#41011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to have a section of a NavBar component wrapped in an `<AuthorizeView>` tag to limit access to only authorized users, but then use nested `<AuthorizeView Roles="admin, user, etc">` within to show/hide various options within the list, if shown. However, I can't use two `<AuthorizeView>` tags due to context conflicts.

This is similar to issue #20294 which was closed.

### Describe the solution you'd like

Be able to nest `<AuthorizeView>` tags with more restrictive roles in the inner tags to allow for showing/hiding content and subcontent

**Comment by MariovanZeist** [comment]
Hi @aterbo 
You can nest ``<AuthorizeView>``  tags if you want, but you will have to rename the Context

Like in this example:

```razor
<AuthorizeView Policy="MyPolicy">
    Show when MyPolicy is valid
    @context.User
    <AuthorizeView Policy="MySecondPolicy" Context=SomeOtherName>     @*Here I renamed the Context to SomeOthername  *@
        Show only when MySecondPolicy is valid
        @SomeOtherName.User
    </AuthorizeView>
</AuthorizeView>
```

This is because the ``ChildContent``  of an ``<AuthorizeView>`` component is of type ``RenderFragment<AuthenticationState>`` 
For these generic Renderfragments, Blazor will generate a  variable named ``context`` that you can use to access that ``AuthenticationState``
If you have nesting components that each have generic render fragments (Like in the example above) you get into a problem that the variable in the nested component is also named ``context``, and that would give a compile error as you can't use 2 different variables with the same name.

That's why to get it to work you will have to rename the Context to something else, and you can access that variable using that name (as I did above)

**Comment by aterbo** [comment]
Well, that's simple..... Thank you for your help, @MariovanZeist that worked perfectly.

This may be room for improvement on the docs. They discuss accessing `context` for various reasons, but not nesting components. Although, that may be repetitive, because had I thought through the `ChildContent` aspect more, it should be treated like any other component where you need to rename context.

I'm happy to close the issue if this type of documentation change isn't needed.

**Comment by javiercn** [comment]
@aterbo thanks for contacting us.

@MariovanZeist answer is correct here.
