### ISSUE TITLE
Suggest to add npm client package management template

### ISSUE THREAD

**Issue by sgalcheung** [dotnet/aspnetcore#41018]
Create the default template lib contains some client packages. It seems a bit awkward to submit these in git version management. Can you provide an NPM version template

**Comment by javiercn** [comment]
@sgalcheung thanks for contacting us.

It's not clear what you are asking for here. Could you clarify what your ask is?

**Comment by sgalcheung** [comment]
When I created an MVC project, it was not the NPM management mode I wanted, but used lib's package directly, which made it impossible for me to continue working directly on the default template

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion, @sgalcheung! We don't currently plan to do this because it leads to a lot of open-ended problems that we can't necessarily make work for all projects. However if your requirements are limited to the use of Bootstrap, you can probably add your own `package.json` and set up something that copies the relevant `.css` files to your `wwwroot` during the build.
