### ISSUE TITLE
How to display a image in local?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#41022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to displa a image in local

`<img src="which from my device.png" />`

but I do not have to upload it to server

but It is not supported to read the image.

### Describe the solution you'd like

pick  an image then auto in` <img src="the  image.png" />`

**Comment by TanayParikh** [comment]
Hi @mcguu, thanks for reaching out. It's not immediately clear what you're attempting here. Is this for a Blazor Hybrid / MAUI application? Or are you trying to embed the image as part of your blazor webassembly assets?

**Comment by mcguu** [comment]
@TanayParikh  thank you. what I want to do is to display an image which is in my computer to the website but do not upload to server.

I am trying to embed the image as part of my blazor webassembly assets but the image is in my computer and I can change it.
with a `<input type="file" />`

which means I only have a static website of blazor webassembly but want to embed the image which is in a user's computer.

**Comment by javiercn** [comment]
@mcguu thanks for contacting us.

This is not specific to Blazor. You can achieve this by creating an object url for the file as described [here](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) via JS interop and assign the result to the src attribute of the img element.

If you still run into issues, I would suggest you check some other resources like stackoverflow in order to do this.
