### ISSUE TITLE
Blazor Server MainLayout not always disposed with long polling

### ISSUE THREAD

**Issue by larthallor** [dotnet/aspnetcore#41056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Long Polling with Blazor Server on .NET 6, MainLayout components that implement IDisposable do not always get disposed under load.

### Expected Behavior

MainLayout components that implement IDisposable should always get disposed when no longer in use.

### Steps To Reproduce

1. Create a new Blazor Sever project with dotnet new blazorserver
2. Configure the Blazor Hub to use Long Polling
3. Add code to MainLayout.cs to log disposal (see attached patch files for example code)
4. Run the project in VS 2022

Normal, slow operations correctly dispose MainLayout instances.  However, spamming the reload button for 8-10 seconds leave multiple instances not disposed. This also occurs using a 2nd browser instance and closing that browser does not cause the "orphans" to dispose.

### Exceptions (if any)

This does not appear to be an issue when using Web Sockets, which eventually timeout and dispose.

### .NET Version

6.0.201

### Anything else?

[MainLayout.cs.patch.txt](https://github.com/dotnet/aspnetcore/files/8422155/MainLayout.cs.patch.txt)
[Program.cs.patch.txt](https://github.com/dotnet/aspnetcore/files/8422156/Program.cs.patch.txt)

**Comment by javiercn** [comment]
@larthallor thanks for contacting us.

Blazor keeps the circuit alive for a predefined (and configurable) amount of time after a client has disconnected in case the client reconnects back to the application. You won't see components dispose until after 2 (or 3) minutes after the server considers the circuit to be disconnected.

Blazor server considers the client disconnected when SignalR deems the client to be disconnected which I think can take longer if you are using long polling. In general, we highly recommend using websockets with Blazor Server since if offers a much better experience.

You should be able to see in the logs (you might need to turn debug logging on) when the circuits are marked as disconnected and when they get disposed (disposing all components as part of it)

**Comment by larthallor** [comment]
Thank you for responding.

2 or 3 minutes is the kind of timeout value one might expect to allow for reconnection. However, these objects appear to remain undisposed indefinitely. 

Below is output from a slightly modified version of the code I submitted. The code has been updated to show how long each object has gone undisposed. This output shows that spamming refresh on a single tab for 8-10 seconds has resulted in 4 instances of MainLayout objects that have gone undisposed for 45 minutes and counting.

```
LongPollingMainLayoutDisposalDemo.Shared.MainLayout: Warning: Layout 16240319 has been alive 00:45:04.8262178.
LongPollingMainLayoutDisposalDemo.Shared.MainLayout: Warning: Layout 12506874 has been alive 00:45:09.9697009.
LongPollingMainLayoutDisposalDemo.Shared.MainLayout: Warning: Layout 52390226 has been alive 00:45:10.6280417.
LongPollingMainLayoutDisposalDemo.Shared.MainLayout: Warning: Layout 6084834 has been alive 00:45:05.4326899.

```

**Comment by larthallor** [comment]
Publishing to a folder and running from a command line did fix this. It did not matter whether I published under a Release or Debug profile: both versions eventually disposed all but the one, running instance as expected with 2 or 3 minutes.

Do you have any insight or links to share as to why this is an issue within VS?
