### ISSUE TITLE
In ASP.NET Core, why are Session and User not accessible from services instead of members of HttpContext?

### ISSUE THREAD

**Issue by wessleym** [dotnet/aspnetcore#41065]
## Summary

In ASP.NET Core, why are Session and User not accessible from services instead of members of HttpContext?

## Motivation and goals

In ASP.NET Core, not all sites use sessions, user authentication, or WebSockets.  So why are `Session`, `User`, and `WebSockets` members of `HttpContext`?  Why wouldn't these have been made available through some kind of per-request `ServiceLifetime.Transient` service (e.g., `AuthenticatedUserService.User`)?

Is it included on `HttpContext` just for convenience since so many sites do use `Session` and `User`?  Or is it to maintain some resemblance of .NET Framework's ASP.NET?  I'm trying to understand Microsoft's logic in how they decided what should be accessible from a service and what should be included as a member of `HttpContext`.  I've searched through the documentation, and I can't find a statement of how Microsoft made this determination.

(I was sent here from AspNetCore.Docs, so I hope I'm now in the right place.  https://github.com/dotnet/AspNetCore.Docs/issues/25536)

## In scope

I guess this scope is `HttpContext`, but this is really just a question.

## Out of scope

Actual changes would likely be out of scope.  I'm just looking for an answer.

## Risks / unknowns

N/A

## Examples

Instead of `HttpContext.User`, why not `AuthenticatedUserService.User`?

**Comment by halter73** [comment]
HttpContext isn't thread safe and don't have a SynchronizationConext in ASP.NET Core so exposing the HttpContext via an async local or similar is dangerous. It is possible with [IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor), but you have to be careful not to reference it from parallel operations. Your better bet in most cases is to pass the HttpContext as an explicit parameter to your services that need it.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0

We also have an issue to improve that HttpContext document at https://github.com/dotnet/AspNetCore.Docs/issues/7721

**Comment by wessleym** [comment]
@halter73, thank you.  Are you saying this lack of thread-safe-ness is the reason why `User`, `Session`, and `WebSockets` couldn't be split into services?  They had to be part of `HttpContext` since they rely on the data of the `HttpContext` and would have to use `IHttpContextAccessor` to get the `HttpContext`?

**Comment by wessleym** [comment]
@davidfowl and @Pilchie, I noticed you're participants on this issue.  Do you have anything to add?  I would like an answer to my original question in light of halter73's answer.  Thank you for your time.

**Comment by halter73** [comment]
@wessleym Sorry I didn't see your earlier reply until now. I think you understood my answer pretty well.

The lack of thread-safety is one reason we don't want to expose request state via "ambient state" (i.e. [AsyncLocal](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=net-6.0)) which is what `IHttpContextAccessor` does. You're right that `User`, `Session`, and `WebSockets` services would need to rely on  `IHttpContextAccessor` or something very similar to it to work.

Reasons not to use it are listed in the `IHttpContextAccessor` API docs. Testability and performance are also a concern.

**Comment by halter73** [comment]
> I can imagine `HttpContext` being retrieved by relying on such a middleware-service combination, but I'm guessing the .NET people decided that was not a good option for some reason and instead chose to make something like `IHttpContextAccessor`.

I'm glad you managed to do this yourself. If you're only using the `HttpContext` from scoped services, this is probably slightly better than using the `IHttpContextAccessor` because it avoids the `AsyncLocal`. There is some cost to recreating the scoped service for each request, but I figure it's relatively small by comparison. By default, ASP.NET Core avoids the cost of either option.

The main reason we decided against a scoped service exposing the `HttpContext` is because `IHttpContextAccessor` already exists and can also be used from singleton services. Providing too many options could be confusing. As much as we recommend against it, sometimes a singleton service is implementing an interface it cannot change, so adding parameters for the `HttpContext` or `HttpContext`-derived data isn't possible.

Custom `ILoggerProvider`s are a common example of this. It's somewhat risky, because who's to say someone didn't capture the request's execution context and log in the background, but similar things could happen if someone used a scoped service in the background. And as long as nothing actually does capture the request's execution context and log in the background, it should be alright. The framework itself should avoid capturing the execution context on background threads it logs from.
