### ISSUE TITLE
MapFallback catch all requests to API controller when ConsumeAttribute added

### ISSUE THREAD

**Issue by Brainman643** [dotnet/aspnetcore#41060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello.
In .net 6 behavior of MapFallback broke when ConsumesAttribute was added. MapFallback catch all requests to API controller.
In .net 6 index.html file always returns on requests to API controller but if I remove endpoints.MapFallbackToFile or delete ConsumesAttribute filter then everything works as I expected.
**In .net 5 the example works correctly.**

ConsumesAttribute was added for the correct generation of swagger.json by Swashbuckle in order not to add it to every action or controller.

### Expected Behavior

Requests to controllers must not be catched by MapFallback.

### Steps To Reproduce

```c#
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(options => options.Filters.Add(new ConsumesAttribute("application/json")));
        }
        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("index.html");
            });
        }
    }
```

### .NET Version

6.0.200

**Comment by javiercn** [comment]
@Brainman643 thanks for contacting us.

Here is what is happening.

I believe this is a side-effect of moving the Consumes to be evaluated earlier (as part of route matching via a matcher policy) during the request processing pipeline.

On .NET 5.0 there wasn't any accept policy, so any endpoint with [Consumes] attribute would match even if the content-type from the header was incompatible with the endpoint. Later on, the Consumes filter would take effect and generate the expected 415 response.

On .NET 6.0 we added and registered an AcceptsMatcherPolicy by default to evaluate this during routing for minimal APIs. As a result of this, evaluating the compatibility with the content type has moved earlier in the request pipeline
and the endpoint is being discarded. Since the endpoint is being discarded, the fallback endpoint added for SPAs and Blazor Webassembly now gets selected instead.

You should be able to add this to your map fallback to file call to avoid the fallback from being matched in these situations
```cs
    endpoints.MapFallbackToFile("index.html").WithMetadata(new HttpMethodMetadata(new[] { "GET" }))
```

**Comment by tnlthanzeel** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Hello. In .net 6 behavior of MapFallback broke when ConsumesAttribute was added. MapFallback catch all requests to API controller. In .net 6 index.html file always returns on requests to API controller but if I remove endpoints.MapFallbackToFile or delete ConsumesAttribute filter then everything works as I expected. **In .net 5 the example works correctly.**
> 
> ConsumesAttribute was added for the correct generation of swagger.json by Swashbuckle in order not to add it to every action or controller.
> 
> ### Expected Behavior
> Requests to controllers must not be catched by MapFallback.
> 
> ### Steps To Reproduce
> ```cs
>     public class Startup
>     {
>         public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddControllers(options => options.Filters.Add(new ConsumesAttribute("application/json")));
>         }
>         public void Configure(IApplicationBuilder app)
>         {
>             app.UseRouting();
>             app.UseEndpoints(endpoints =>
>             {
>                 endpoints.MapControllers();
>                 endpoints.MapFallbackToFile("index.html");
>             });
>         }
>     }
> ```
> 
> ### Exceptions (if any)
> _No response_
> 
> ### .NET Version
> 6.0.200
> 
> ### Anything else?
> _No response_

same issue for me too, is there a solution?

**Comment by javiercn** [comment]
@Brainman643 can you explain what is not working for you in a separate issue?

(Include please a minimal repro project as a public gh repo).

**Comment by MackinnonBuck** [comment]
Done in #43984

**Comment by davidfowl** [comment]
Does this regress anything else? Is it a breaking change?

**Comment by javiercn** [comment]
@davidfowl **very theoretically** if you were requesting a SPA with a POST, PUT, etc. request, but that's not something that would affect any production scenario. The main scenario for this is to serve index.html in SPAs and Blazor.

We can add a small announcement for it, but I highly doubt it's a problem.

**Comment by javiercn** [comment]
We should keep the issue open, though

**Comment by javiercn** [comment]
Note for triage:
* The remaining work here is to find a solution for the behavior change that we introduced when Consumes became a matcher policy instead of a filter.

**Comment by davidfowl** [comment]
Can we add the announcement and mark it as a breaking change?

**Comment by javiercn** [comment]
@davidfowl absolutely.

@MackinnonBuck can you take care of it?

**Comment by MackinnonBuck** [comment]
https://github.com/aspnet/Announcements/issues/495

**Comment by tnlthanzeel** [comment]
is this fixed?

**Comment by omarceloribeiro** [comment]
I got this issue in blazor web assembly .net core hosted. I created a api folder in controllers, then create my api controllers.
so when I hit the url /api/products the .net core fallback to index.html resulting the a blazor web page respone "Sorry, there's nothing at this address." 

oddly, when I open in anonymous tab, or if I press control F5 the .net core works correctly and returns my api.
also, if I access via HttClient (RestClient) it works in google chrome, but doesnt work in Firefox. the response is empty in firefox.

**Comment by martinlingstuyl** [comment]
I'm on .net 8 and same issue for me...

**Comment by EndOfTheSpline** [comment]
I've spent the last three days trying to track down why using `FallbackPolicy` was not behaving like documented (e.g. ignoring `AllowAnonymous`/`[Authorize]`), why my policies were not receiving endpoints for evaluation, why my endpoints seem to disappear/be ignored by the `DfaMatcher`, and after I tracked it down to `MapFallbackToFile` and some more searching, I finally found this issue - which details my use case exactly.

Since this appears to still be an issue (with GET endpoints at least) with .NET 9, and .NET 10 is around the corner, I guess this is going to persist for a longer while?

Is there any working workaround that would make `MapFallback` "safer" to use (e.g. with less side effects in unexpected places)? It seems like the presence of a (globally?) registered `IAcceptsMetadata` triggers this behaviour already (at least: copying `ConsumeAttribute` and removing that one interface lets the API load again), so working around this (and other similar issues) might be tricky.

Not entirely relevant, but I would like more control over the fallbacks in general - if I could e.g. scope them to disable the fallbacks entirely for requests going towards `/api/`, then the issue wouldn't really affect me either. From a rough testing point, it seems like this piece of code might do the trick, although it's not strictly speaking a "fallback" anymore and definitely not using the endpoints/routing system:

```cs
app.MapWhen(
    ctx => Path.GetExtension(ctx.Request.Path.Value) == "" && !ctx.Request.Path.StartsWithSegments("/api"),
    fallback =>
    {
        fallback.Use(next => context =>
        {
            context.Request.Path = "/index.html";
            context.SetEndpoint(null);

            return next(context);
        });

        fallback.UseStaticFiles();
    }
);
```

It should work as long as whatever is controlled/called by the normal endpoints, and whatever the fallbacks should handle, are completely distinct paths, which would be enough in my case. Still, having an unified solution would be preferable.
