### ISSUE TITLE
SignalR client should send keepalive ping immediately when connected

### ISSUE THREAD

**Issue by zackliu** [dotnet/aspnetcore#41081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, SignalR client will send a keepalive ping 15s after connected. In some cases, the client connection terminates unexpectedly and the TCP become half-open before the first ping and the hub server will think the client won't send ping as it's an old version client. Thus, the server will close the connection after TCP timeout, and it's a very long time.

https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L638

### Expected Behavior

The client send ping immediately after connected to void such race condition.

### Steps To Reproduce

The half open TCP is not easy to reproduce. But, it's easy to see the first client ping happens around 15s after connected.

### Anything else?

signalr js client: microsoft/signalr: 6.0.3

**Comment by halter73** [comment]
Kestrel and IIS don't support half-open TCP connections, so I don't see how that could come into play. It's hard to imagine a proxy or frontend timing out a request backing a SignalR connection just because the client didn't send more data immediately after completing a SignalR handshake.

If this is happening for some strange reason in your case, you could invoke a no-op server hub method right after the client connects yourself. This would be functionally equivalent to a keep alive.

We would likely need a network trace or repro app with both the client and server to figure out what's really going on in your case but sending a keep alive immediately after connecting seems wasteful.

**Comment by zackliu** [comment]
The ping from client is the key to start checking timeout in Server side. If client dies before the first ping, the server side never knows whether the client has dead or use a version without ping.

https://github.com/dotnet/aspnetcore/blob/70d7f5f9e02c84084daec2f6666decd343e56b46/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L162

**Comment by halter73** [comment]
I see. It's SignalR itself timing out the connection too slowly. I thought it was some proxy timing out the connection for a lack of keep alive. It does make sense to expect some payload over the transport from newer clients to start the connection. We're tracking this with #23794.
