### ISSUE TITLE
“dotnet watch run” encountered an error: Too many changes at once in directory:

### ISSUE THREAD

**Issue by wmunlai** [dotnet/aspnetcore#4109]
When I run "dotnet watch run", it keeps reporting "too many changes at once in directory" when I did not change anything. And then it exits and start again. Wonder if anyone has encountered similar problem.

I am using dotnet version 2.1.401

watch : The file watcher observing 'C:\munlai\websitepractice\EpdAsset\' encountered an error: Too many changes at once in directory:C:\munlai\websitepractice\EpdAsset\.
watch : Exited with error code 1
watch : File changed: C:\munlai\websitepractice\EpdAsset\EpdAsset.csproj
watch : Started
watch : The file watcher observing 'C:\munlai\websitepractice\EpdAsset\' encountered an error: Too many changes at once in directory:C:\munlai\websitepractice\EpdAsset\.
watch : Exited with error code 1
watch : File changed: C:\munlai\websitepractice\EpdAsset\EpdAsset.csproj
watch : Started
...............

It just keeps exiting and starting. After a few minutes wait, the starting will suddenly be successful.

**Comment by klick-barakgall** [comment]
This is still an issue. Any news on this? I have a sneaking suspicion that some file that is being built or an intermediate file of the build is triggering a watch rebuild in some cases, but because it gives NO information it's impossible to determine what files might be impacting this process. Is there a verbose mode that will list each file change that it does detect before it becomes overloaded?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
