### ISSUE TITLE
Support watching multiple projects from command-line

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4110]
Make it possible to watch multiple csproj files that may not be connected in the P2P graph without having to create a "watch.proj" file.

Usage: add `-p|--project` that takes multiple files.
```
dotnet watch -p Web/web.csproj -p Test/test.csproj
```

**Comment by pfeigl** [comment]
@smerrell Did you make any further progress on this after natemcmaster's feedback? This feature would be so nice to have natively without starting multiple projects at once.

Common usecases are probably situations where an API and a MVC application are hosted next to each other, or also when i.e. IdentityServer is hosted as it's own project.

**Comment by dharmaturtle** [comment]
Are there currently any workarounds for this? @natemcmaster mentioned creating a `watch.proj`, what does that look like or involve? Thanks!

**Comment by smerrell** [comment]
Hey there. Life got in the way and I wasn't able to make a ton of progress on this. What I got stuck on was that I couldn't pass multiple projects to msbuild like Nate suggested. What ended up happening is that msbuild would complain that the `;` was an invalid character. I searched as much as I could and found I could escape the semi-colon. Once I did that, instead of getting a list of projects, I got the whole string as a single item. I tried seeing if there were some clever ways I could break the string up inside the targets file but didn't have much luck there. Hopefully this helps move things along.

**Comment by natemcmaster** [comment]
I'm no longer working for Microsoft. @Pilchie / @glennc are the right people to reach out to if you need more help on this one.

**Comment by Pilchie** [comment]
Tagging @nguerrera and @rainersigwald for ideas on how to do this in msbuild logic.

**Comment by jkotalik** [comment]
As an FYI, this is currently supported in [tye](https://github.com/dotnet/tye) if you'd like to watch multiple projects.

**Comment by MichelJansson** [comment]
> As an FYI, this is currently supported in [tye](https://github.com/dotnet/tye) if you'd like to watch multiple projects.

Although tye allows me to watch and **run** multiple projects as individual services, I can't seem to get it to watch and build multiple projects but only **run one**.
Basically what I would like to do is:
- Watch a list of projects and rebuild those on changes
- Run one project, that is also rebuilt and restarted when any of the above projects are rebuilt.

**Comment by pranavkm** [comment]
Closing this as we have no plans to support this feature.
