### ISSUE TITLE
Blazor app.razor NotFound not authorizing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41113]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-apprazor-NotFound-not-authorizin/1700826)._

---
Within Blazor, the NotFound-routing is not authorized. This allows an unauthorized attacker to detect existing and non-existing items from a rest-based Blazor instance by the HTTP return values 403 and 404.

I would expect that a Blazor-internal 404-return would be filtered by the authorize condition, or that in app.razor the NotFound-element can be added an AuthorizeRouteView element beneath, or at least that the OnRender-event for app.razor can be given an authorizing code.
(I was not able to do so.)

---
#### Feedback Bot on 3/24/2022, 07:32 AM: 

(private comment, text removed)

**Comment by javiercn** [comment]
Thanks for contacting us.

It's not super clear what the issue you are mentioning seems to be. You shouldn't base the security of your app on your client-side rules. It's imperative there is always server validation and if you are lacking that on the server the issue is there.

However, I would like to point out that there is a way to report potential security issues confidentially and that we offer a reward for those if we asses they are indeed security issues. I would suggest that next time you follow the guidance from our .NET bounty program https://www.microsoft.com/en-us/msrc/bounty-dot-net-core to opt for a reward.

**Comment by HansGuckInDieLuft** [comment]
> _This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-apprazor-NotFound-not-authorizin/1700826)._
> 
> Within Blazor, the NotFound-routing is not authorized. This allows an unauthorized attacker to detect existing and non-existing items from a rest-based Blazor instance by the HTTP return values 403 and 404.
> 
> I would expect that a Blazor-internal 404-return would be filtered by the authorize condition, or that in app.razor the NotFound-element can be added an AuthorizeRouteView element beneath, or at least that the OnRender-event for app.razor can be given an authorizing code. (I was not able to do so.)
> 
> ### Original Comments
> #### Feedback Bot on 3/24/2022, 07:32 AM:
> (private comment, text removed)
This request has sadly been closed too early. It is *not* resolved, and the response to prefer server-sided authorization is *not* correct: this is simply not working: Even though restricting access to a user group in a Blazor server app, an unauthorized user may still call inro the app with a query string, bypassing the authorization, when not found. So, it is an issue. Please try out yourself before assuming its result.

**Comment by javiercn** [comment]
@HansGuckInDieLuft thanks for the additional details.

From the information provided, we don't have enough information to determine there is a security issue in the framework.

If you think you've found a security issue, please report it through the mechanism provided above with a minimal repro project as well as clear repro steps and a detailed description on the issue found so that we can evaluate whether there is an actual vulnerability or not and take appropriate steps.
