### ISSUE TITLE
The front end text boxes width is minimized after running them this is happening for next 2 weeks 

### ISSUE THREAD

**Issue by NameIsShubham** [dotnet/aspnetcore#41147]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

In our dot net project we have used bootstrap for styling the front end but now when we open it the width of text boxes are shorter and the whole front end has been looking strange this is happening 2nd time in a week . We even try to run it on older version but the same problem is seen their . we even try to build new module but this thing is still happening .we dont want to change the front end can you clear the problem 

### Expected Behavior

We expect that our front end with bootstrap should run as before there should be no compromise with our frontend . the text boxes should be seen as they should be unexpected behavior should be excluded.

### .NET Version

4.7

### Anything else?

bootstrap

**Comment by javiercn** [comment]
Thanks for contacting us @NameIsShubham .

It looks like this is a question about how to use Bootstrap. We can't tell there is any framework specific issue with ASP.NET Core here. We would suggest you post on Stackoverflow or a similar site to get a better and faster answer to your problem.

If you still think this is an issue with ASP.NET Core, provide a minimal repro project with detailed steps on how to reproduce the issue, the concrete behavior you are observing and the expected behavior. Otherwise, we are unable to make progress on this issue with the current information.

**Comment by TanayParikh** [comment]
Hello @NameIsShubham, thanks for contacting us. It appears you're using .NET Framework 4.7. Please note, this repo is specifically for ASP.NET Core. If you believe this is an issue with .NET Framework, please report it within the Visual Studio `Report a Problem` dialogue so it may be directed to the appropriate team.
