### ISSUE TITLE
Call  to builder.WebHost.UseUrls breaks Blazor Server app in  VS17.1.4

### ISSUE THREAD

**Issue by ttosello** [dotnet/aspnetcore#41165]
After updating to VS17.1.4 from 17.1.3, my Blazor Server app no longer launched the browser or ran any razor components.  When I comment out the call to builder.WebHost.UseUrls the app runs fine.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ttosello** [comment]
Repro here:  GitHub - ttosello/1714<https://github.com/ttosello/1714>

Line 34 in Program.cs prevents the browser from launching in v17.1.4 (and beyond).  Worked fine in 17.1.3 and below.


Trevor Tosello
Senior Software Architect

T: 1.416-706-7340
E: ***@***.******@***.***>
U: http://www.blackriversc.com

**Comment by javiercn** [comment]
@ttosello thanks for the additional details.

The issue here is that Visual Studio is setting up the ASPNETCORE_HTTPS_PORT environment variable when launched.

![image](https://user-images.githubusercontent.com/6995051/163801942-1446be38-2233-4e52-bfd6-31a821e9c3fb.png)

What's happening is that the `HttpsRedirection` middleware is picking that up and redirecting to https://localhost:7180

It might be the case that this has changed from 17.1.3 to 17.1.4, however I would be surprised if that's the case.

There might be a good reason for this behavior, so I would suggest to change the urls within launchSettings.json too to match what you use in your UseUrls call.

From my point of view, the framework is behaving as 3expected, but it is being fed incorrect information from within the launching process in VS.

**Comment by javiercn** [comment]
@ttosello I'm going to close this issue since it is Visual Studio related and I've already forwarded the relevant information to the VS team, so they'll take it from here.

If you want to keep tabs on the issue, I would suggest you file it through the Visual Studio report a problem dialog in VS and link this issue along with the details mentioned here.

**Comment by ttosello** [comment]
Hi, I did report this through VS but they marked it as duplicate and pointed to this thread instead.

**Comment by javiercn** [comment]
@ttosello thanks for the additional details. From what I spoke to the VS folks, this hasn't changed in a long time (the environment variable was always set) so it is not clear to me how this ever worked for you in a previous version of VS. 

I'm going to hand off the VS ticket directly to the VS folks to help you here.

**Comment by javiercn** [comment]
@ttosello I've reactivated the original VS issue and looped in the right folks to take a look at it. I'm going to close this issue to avoid confusion and we will handle updates in the user voice ticket directly.
