### ISSUE TITLE
Can't configure SSL certificate when TLS1.2 is enabled

### ISSUE THREAD

**Issue by alons1** [dotnet/aspnetcore#41175]
Hello 

I get in Chrome: ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY
Unless I specifically set in my program.cs file:
`
serverOptions.Listen(IPAddress.Any, 5001, listenOptions =>
{                            
       listenOptions.UseHttps(System.Security.Cryptography.X509Certificates.StoreName.Root, "IS02LTB18SLH2.domain.local", true);
        listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1;
});`

I'm on Win10 21H1 where TLS1.2 is supported.
My certificate properties when accessing via IE is: **TLS 1.2, AES with 256 bit encryption (High); RSA with 2048 bit exchange**
Why do I have to set HttpProtocols to Http1 then?

Using ASP.NET core 5.0.12

**Comment by blowdart** [comment]
The problem lies in Windows, while it supports HTTP/2 it doesn't exclude the weak ciphers that it shouldn't offer up. 

On Windows10 you can disable HTTP2 for serving

```reg
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters]
"EnableHttp2Tls"=dword:00000000
"EnableHttp2Cleartext"=dword:00000000
```

or tell kestrel just to use http 1.* in app settings

```json
"Kestrel": {
"EndpointDefaults": {
  "Protocols": "Http1"
}
}
```

If you really want you can start disabling the insecure ciphers, which involves messing with the registry or group policy or [using powershell](https://docs.microsoft.com/en-us/powershell/module/tls/disable-tlsciphersuite?view=windowsserver2022-ps) and disabling everything that is marked as [not supported in TLS1.2](https://www.rfc-editor.org/rfc/rfc7540#appendix-A)

**Comment by alons1** [comment]
TLS1.2 is required by our organization's security department.
As long as non-weak ciphers are enabled on my machine, why is there a problem? Who is trying to use the weak onces?

**Comment by blowdart** [comment]
Windows 10 is, unfortunately. Does it work on a server OS?

**Comment by blowdart** [comment]
`Get-TlsCipherSuite | ft name` in powershell will give you a list of currently enabled ciphers. On my Win10 client machine it includes a bunch of things no-one would want in a server. Problem is are you sure nothing on your machine is using them?

You can pick things off one by one, and aim to get to just the following, which should then work with Chrome.

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
