### ISSUE TITLE
Poor performance resolving tilde paths in Razor tags

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/aspnetcore#41234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The code like this:

```
<a href="~/path/to/something">link</a>
```

Performs 20X slower than the code like this:

```
<a href="@Url.Content("~/path/to/something")">link</a>
```

### Expected Behavior

Should be close. I would expect Razor parser to use `Url.Content` internally, apparently it does not.

### Steps To Reproduce

Test "benchmark" razor view

```
@{
    System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
    sw.Start();
    for (int i = 0; i < 10000; i++)
    {
        <a href="@Url.Content("~/path/to/" + i)">aa</a>
    }
    sw.Stop();

    @sw.ElapsedMilliseconds

    sw.Restart();
    for (int i = 0; i < 10000; i++)
    {
        <a href="~/path/to/@i">ss</a>
    }
    sw.Stop();

    @sw.ElapsedMilliseconds
}
```

The first test takes 2 (two) milliseconds. **The second takes 42 milliseconds** which is 20 times slower.

### .NET Version

.NET 6 (MVC)

### Anything else?

I've disabled all taghelpers in my `_ViewImports.cshtml` hoping it would help. It didn't

After changing `@Url.Content` calls to built-in Razor paths I noticed CPU load on our server go up from 5% to 15%. Took me a while to discover why.

**Comment by javiercn** [comment]
@alex-jitbit thanks for contacting us.

This is expected and by design.

In the second example, `<a href="~/path/to/@i">ss</a>` is using a TagHelper to resolve the actual URL which has more overhead than directly passing the Url using `Url.Content` and that's why you are seeing a difference in performance.

> I've disabled all taghelpers in my _ViewImports.cshtml hoping it would help. It didn't

I wouldn't expect this to be the case. I would check that you've truly disabled the tag helper on the page, as well as double check the results on the measuring process.

If you want to measure the performance difference between using the tag helper and Url.Content I would strongly recommend using something like Benchmark.net to do so.

> After changing @Url.Content calls to built-in Razor paths I noticed CPU load on our server go up from 5% to 15%. Took me a while to discover why.

I'm assuming this statement is with the tag helpers being enabled.

It's important to note that the Razor compiler knows nothing about Urls or virtual paths, which is why it doesn't transform `~/...` to anything like `Url.Content` and that it is a TagHelper the one that does that work at runtime. 

It's also important to note that we can't just change this behavior to use Url.Content as we would be breaking pretty much every app out there that is transforming links in any way.

We don't think there is a performance issue in this area based on the data provided so far. It is obvious that one approach is slower than the other, but this is expected as each feature comes at a cost and the performance for each approach fall within acceptable bounds/goals. While (as you pointed out) there are faster alternatives, we don't think this makes a significant difference in the vast majority of the apps.

If it happens to make a difference for your app/site, then we recommend using `Url.Content` directly as you did for improved performance.

**Comment by alex-jitbit** [comment]
@javiercn please elaborate how is this "by design" and what extra work does TagHelper need to do to calculate the tilde path?

Tilde path is deterministic and resolves to Web application root, always. Isn't that always the case?

**Comment by javiercn** [comment]
@alex-jitbit using a tag helper involves more work because it needs to get instantiated, find the attribute to apply to and update the content at runtime, compared to `Url.Content` whose only job is to "take a string and produce another string".

The code you are looking for is https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor/src/TagHelpers/UrlResolutionTagHelper.cs
