### ISSUE TITLE
Blazor WebAssembly: conflict between parameters and event callback prevents rendering

### ISSUE THREAD

**Issue by JBBianchi** [dotnet/aspnetcore#41282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was trying to make a simple modal in my Blazor WebAssembly project that would be open when the user navigates to a page, would ask for some inputs, and closes on submit.

To do so, I created a new Razor component with 3 parameters:
- `Active`: used to define if the modal should be displayed or not
- `Model`: the data to input/edit
- `OnSaveModel`: an event callback called when the form is submitted

In the modal, I added a form to which I bound an handler for `@OnSubmit` that invokes the event callback and closes the modal (set `Active` to `false`).

See [Modal.razor](https://github.com/JBBianchi/ConflictingParameterAndEventCallback/blob/main/ConflictingParameterAndEventCallback/Pages/Modal.razor)

When I tried to code, I noticed my event callback was invoked but my modal was still displayed.

 I checked and the `Active` property was actually set to `false`.

Even after adding few `StateHasChanged()` calls, either in `Modal.OnSubmitAsync` or `Index.OnSaveModel`, the modal stayed visible.

But if I click the close button on the top corner, the modal does disappear.

### Expected Behavior

The modal to disappear after clicking on submit.

### Steps To Reproduce

- Clone and run https://github.com/JBBianchi/ConflictingParameterAndEventCallback
- Visit the index, fill in the name and click submit

### .NET Version

6.0.202

**Comment by MariovanZeist** [comment]
@JBBianchi 
I wanted to look at your issue, but couldn't clone your repo. 
Did you manage to fix your issue?

**Comment by JBBianchi** [comment]
@MariovanZeist sorry, I didn't notice the repo was private, I turned it public, you should be able to clone it. Can you confirm please ?

**Comment by javiercn** [comment]
@JBBianchi thanks for contacting us.

The issue happens because you are using the Parameter `Active` as a Parameter and to hold the state for the component, which we don't recommend because it impacts subsequent renders.

If you have some piece of state, you should store it separately from your parameter, for example if you change your sample to use a private field _isCurrentlyActive and you set the value from Active within OnInitialize, you'll see that things start working.

**Comment by JBBianchi** [comment]
@javiercn thanks for your feedback. Could you point me some piece of code or explantations about how the subsequent renders work? I'm quite curious to see how it works. I find it strange that flipping the Active prop-state works outside the event call back but doesn't when the event callback is called (even if the value is actually updated, and even after calling StateHasChanged()).

**Comment by javiercn** [comment]
@JBBianchi there are general docs in the following locations:

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0

As to what happens specifically in your case, its a bit complicated to explain (and my explanation might not be completely accurate) and I recommend debugging through the code to get a better understanding of what's going on.

What I suspect happens is that the event callback triggers the parent component to re-render and that causes the Modal component to update, since it gets new parameters (blazor is very conservative on detecting parameters and consider reference types different even if they are the same instance).

My recommendation would be that you override SetParameters on the components to setup breakpoints as well as set some breakpoint over the render logic in the components as a way to visualize when they are rendering and the values at those points, that will give you a good idea about how the code is interleaved.
