### ISSUE TITLE
Add integration library for easy auth

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#4128]
App Service has first class support for 3rd party authentication providers:

![image](https://user-images.githubusercontent.com/95136/39965188-5ea147b6-5649-11e8-9123-88ac0ef108c9.png)

Data flows to the application in various headers. We should support this in a more first class way that interoperates with our authentication system.

/cc @HaoK @Tratcher

**Comment by shibayan** [comment]
We already have similar codes written and handled by each:

https://stackoverflow.com/questions/41501612/trouble-getting-claimsprincipal-populated-when-using-easyauth-to-authenticate-ag

I have any idea. Use HostingStartup to injection New EasyAuth middleware. Install from siteextension

Since easyauth implementation should be similar to cookie implementation, it should be relatively easy.

This is an important part that is also involved in Azure Functions.

**Comment by muratg** [comment]
Backlogging this for now.

**Comment by muratg** [comment]
Removing from backlog so that it's back in triage.  cc @Eilon

**Comment by markhobson** [comment]
May I suggest updating the [Azure documentation](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) with the following points:

* Azure App Service authentication is also known as 'Easy Auth'
* ASP.NET Core does not currently support populating the current user when using Easy Auth

It took me a lot searching and reading to find this issue! Thanks.

**Comment by Tratcher** [comment]
@markhobson you can leave feedback directly on that linked doc.

**Comment by davidfowl** [comment]
We may also want to link to 3rd party implementations https://blog.maximerouiller.com/post/using-easyauth-appservice-authentication-with-aspnet-core/.

We should really have something here.

cc @blowdart

**Comment by blowdart** [comment]
Yes, and we've been talking to azure about owning that. Don't reinvent the wheel *again*. Azure says they want to do it, let them. That way they can keep it up to date with their plans.

**Comment by Tratcher** [comment]
Demand has been surprisingly low.

**Comment by blowdart** [comment]
With internal discussions Azure are to implement this themselves. Closing.
