### ISSUE TITLE
Blazor Server events generate a lots of network traffic in Edge DevTools

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#41294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
<div class="card shadow-sm d-flex flex-row bg-white p-1 mt-1 w-100 overflow-hidden" style="box-shadow: .125rem .25rem rgba(34,34,34,0.15)" @onmouseenter="(x) => this.Owner.ActiveItem = context" @onmouseleave="(x) => this.Owner.ActiveItem = null">
```

When moving with mouse over a button or some divs that have events attached, they generate a lot of traffic.

just moved with mouse 4 or 5 seconds generated 294 requests already
![blazor requests](https://user-images.githubusercontent.com/7447285/164411611-c9aa1878-1842-4e03-b899-4409aea587cc.PNG)

Depending on how many events are attached this could easily generate 1000+ requests and 1MB+ of data in a few seconds.
When hosting this on Azure with many users this could cause an unwanted increase of costs.

Is this a bug or not?

### Expected Behavior

not so many network traffic requests on events.

### Steps To Reproduce

use some events in Blazor Server side

```
<div class="card shadow-sm d-flex flex-row bg-white p-1 mt-1 w-100 overflow-hidden" style="box-shadow: .125rem .25rem rgba(34,34,34,0.15)" @onmouseenter="(x) => this.Owner.ActiveItem = context" @onmouseleave="(x) => this.Owner.ActiveItem = null">
```

### .NET Version

.net 5

### Anything else?

I'm not sure if this is the same or not: https://github.com/dotnet/aspnetcore/issues/15728 

Not even sure if this is expected behavior or if i'm doing something wrong with events...?

**Comment by javiercn** [comment]
@wstaelens thanks for contacting us.

From what I can tell you seem to be using long polling instead of websockets. SignalR uses requests to ping the server regularly as part of long polling to ensure the connection is alive.

We would suggest you switch to websockets and should see those requests disappear.

That said, I want to set expectations here: Blazor Server is a "connected" protocol, so it is expected that you see traffic going through the connection at regular intervals as well as when a render happens on the server or when a user triggers an event.

**Comment by javiercn** [comment]
@wstaelens thanks for contacting us.

From what we can tell you seem to be using long polling instead of websockets. SignalR uses regular requests to the server using long polling to ensure the connection is alive. If you turn on websockets you should see the requests go away.

That said, I want to set expectations here: Blazor server is a "connected" protocol and as such, it regularly maintains traffic with the server when an event is triggered as well as when a render happens on the server, so you shouldn't expect the traffic to go away, but to be done through the websocket.

**Comment by wstaelens** [comment]
2. --> Point of Blazor is also to avoid Javascript ;-)
