### ISSUE TITLE
SignalR JavaScript client: Updating query parameters during active connection

### ISSUE THREAD

**Issue by willhopkins44** [dotnet/aspnetcore#41405]
For authentication and authorization, the suggestion is to use Bearer token as discussed [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#bearer-token-authentication).

In our implementation, we did not want to use a bearer token. Instead, we generate a ticket for a specific user with an expiration time.

The client first fetches a ticket from our service. Then, a SignalR connection is established with our service, with the ticket provided under the query parameter “ticket” as shown below:
```
let connection = new signalR.HubConnectionBuilder()
    .withUrl("{endpoint}:{port}/{hubName}?ticket={generatedTicket}")
    .build();
```

On the service, a [hub filter](https://docs.microsoft.com/en-us/aspnet/core/signalr/hub-filters?view=aspnetcore-6.0) intercepts and validates the ticket against the connected user:
```
public async ValueTask<object> InvokeMethodAsync(HubInvocationContext invocationContext, Func<HubInvocationContext, ValueTask<object>> next)
{
    var httpCtx = invocationContext.Context.GetHttpContext();
    var ticketId = httpCtx.Request.Query["ticket"].ToString();
    try
    {
        await ValidateTicketAgainstUser(ticketId, invocationContext.Context.UserIdentifier);
    }
    catch (SomeException ex)
    {
        throw new HubException("exception message");
    }
    return await next(invocationContext);
}
```

All this works fine as long as the ticket does not expire. 

In the client code, we want to periodically renew the ticket. Once renewed, we want to update the existing SignalR connection with this newly generated ticket so that subsequent hub method invocations over the _same_ connection starts sending the new ticket.

As mentioned, we have explored the JavaScript client's accessTokenFactory, but this works only if we are sending a bearer token or expecting the hard-coded query parameter "access_token".

Does a callback exist that would let us set the renewed ticket into a custom query parameter, similar to how the value is being set for “access_token”?

**Comment by rashmy-git** [comment]
Thank you for the reply. This is helpful.

When the ticket has expired, we don't want to abort the connection since the client will have to subscribe to all the SignalR Groups again. Instead we want to inform the client to re-generate the ticket since the client was previously authenticated with this ticket. As we are building a new feature, we are leaning towards passing the ticket as a parameter on every hub method. We also wanted to allow the client to pass a requestId on every hub method call so that it can be used for tracing in our logs. 

Hence we are leaning towards the following pattern -
1. Before opening SignalR connection, client will request a ticket from the server. The ticket is generated specifically for the requesting client and user.
2. Next, open the SignalR connection and send ticket in the query parameter (http://myhost.com/hub?ticket=1234).
    - Server will verify the ticket is valid and has not expired
3. When the client wants to invoke a hub method, send two parameters in the Hub
   ```
    hubConnection.invoke("SendMessage", hubOptions, hubPayload)
    
    where:
    hubOptions = {
        ticket = "1234"
        requestId = "client1-1234"
    }

    hubPayload = {
       channel = "devops"
       message = "Feature A ready for deploy"
    }
    ```
4. Every hub method call passes through a HubFilter called AuthenticateHubFilter. In the HubFilter, do the following
    - Read the hubOptions.ticket
    - Verify the ticket has not expired.
    - If ticket expired, send error indicating ticket has expired
    - If ticket has not expired, pass to next HubFilter

Do you see any issues for the future if we walk down the path of sending ticket, first as query parameter and then as input to hub method?

**Comment by rashmy-git** [comment]
One more request -

I'd like to explore further on your suggestion to use AccessTokenFactory to integrate my auth checks. Could you please point me to the documentation on performing auth checks in the server with the auth middleware?

Thank you!

**Comment by BrennanConroy** [comment]
> Do you see any issues for the future if we walk down the path of sending ticket, first as query parameter and then as input to hub method?

Nope, seems fine. The SignalR library shouldn't do anything in the future to break that.

> 1. Could you please point me to the documentation on performing auth checks in the server with the auth middleware?

There are lots of docs around auth, you could start with the SignalR specific ones that give a high level overview: https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0

Then there are the main auth docs starting at https://docs.microsoft.com/aspnet/core/security/authentication/?view=aspnetcore-6.0

> 2\. What is the difference between doing authorization checks in the HubFilter vs the [authorization handler](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#use-authorization-handlers-to-customize-hub-method-authorization)

It's more declarative, so some hub methods could use auth while others don't, to do this in a hub filter you would need to check against the hub method name which might be uglier/less maintainable depending on your code base. It also calls into the auth pipeline which might be cleaner to declare all your auth in startup/main. Depends on how you want to layer things, but it should be very similar to handling auth in the filter instead.

**Comment by rashmy-git** [comment]
Thanks again for all replies!

Also, I now understand the need for authorization handler :)
