### ISSUE TITLE
Blazor css-isolation and js-isolation via rendertreebuilder

### ISSUE THREAD

**Issue by sawapont** [dotnet/aspnetcore#41450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blazor css-isolation and js-isolation don`t work via rendertreebuilder

https://github.com/sawapont/CssIsolationViaRenderTreeBuilder

### Describe the solution you'd like

Blazor css-isolation and js-isolation work via rendertreebuilder

**Comment by javiercn** [comment]
@sawapont thanks for contacting us.

That's expected and by design. CSS isolation is a feature of the Razor Compiler, if you aren't using Razor to compile the component, scoped CSS is not going to play a role. We don't have any plans to make this scenario work since scoped CSS is a build time feature.

**Comment by sawapont** [comment]
> @sawapont thanks for contacting us.
> 
> That's expected and by design. CSS isolation is a feature of the Razor Compiler, if you aren't using Razor to compile the component, scoped CSS is not going to play a role. We don't have any plans to make this scenario work since scoped CSS is a build time feature.

Thank you for your answer! I looked for a possibbility of creation of a component with a dynamic tag. In a Razor file there is no such possibbility. So, can't I use a dynamic tag with a css-isolation?
