### ISSUE TITLE
Plz include solution for #37323 also in .Net 6

### ISSUE THREAD

**Issue by DaveLaa** [dotnet/aspnetcore#41471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

See #37323

### Describe the solution you'd like

It would be a great help to implement it also in .Net 6 in the next version of the Microsoft.AspNetCore.Mvc.NewtonsoftJson package, if this is possible
Thx

**Comment by captainsafia** [comment]
Triage: We propose to take this as a backport because there is (a) no applicable workaround and (b) the delta is limited to to the JSON parsing and designed to fix a defect in the API.

**Comment by halter73** [comment]
I was about to start the servicing process for this, but I reconsidered. This is something that never worked before, and it's not exactly zero risk.

It's possible someone is setting the `Handled` flag for usage in one of their other error handlers and still expects MVC to reject the request. I don't think it's very likely, which is why I'm fine with the change .NET 7 without a breaking change announcement. But there's enough of a possibility that I don't want to change it in a patch release. Especially considering this never worked before and you *could* deserialize the message body yourself if you really want to.

**Comment by BrennanConroy** [comment]
We decided not to service this in 6.0.

**Comment by DaveLaa** [comment]
It is sad to hear this.
I was migrating from .Net Framework to .Net 5 and then up to .Net 6 and this is the only breaking change in the core framework that prevents my project to run. My frontend developers have to work through milions of lines of code just to fix problems that not have been there in .Net Framework before, just because the NewtonsoftJsonInputFormatter is not error tollerant like the old mechanism was.
But ok.
Can you plz tell me how i can "deserialize the message body" myself then? I mean I dont want to rewrite the complete Microsoft.AspNetCore.Mvc.NewtonsoftJson project just to add this one line of code... Is there a simple way to just override the NewtonsoftJsonInputFormatter with my own implementation?
