### ISSUE TITLE
WebApi: adding ApiVersioning removes numbers from end of controller name

### ISSUE THREAD

**Issue by simple-nathan** [dotnet/aspnetcore#41502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```[ApiController]
[Route("[controller]")]
public class WeatherForecast2022Controller : ControllerBase
```
With versioning added in the Startup class, the `2022` gets removed from the controller name in the generated swagger documentation and when you attempt to call from Postman. Has to be called as `weatherforecast`

### Expected Behavior

I would expect to see this controller be called `WeatherForecast2022` in swagger and for calling the route from Postman.

This section from the docs implies that numerals can be added to the end of a controller name.
[Docs link](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#token-replacement-in-route-templates-controller-action-area-1)

Before adding versioning
![image](https://user-images.githubusercontent.com/93679016/166585520-b2f7dc84-3f89-46ca-8b30-6f779db66e0e.png)

After adding versioning
![image](https://user-images.githubusercontent.com/93679016/166585546-21688e3e-8f82-4976-9822-65699439a135.png)

### Steps To Reproduce

[https://github.com/simple-nathan/controller-name-testing](https://github.com/simple-nathan/controller-name-testing)

### Exceptions (if any)

None

### .NET Version

6.0.202

### Anything else?

```
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by BrennanConroy** [comment]
@commonsensesoftware is this issue better suited in https://github.com/dotnet/aspnet-api-versioning?

Is there a fix already for this in the 6.0 previews? Also, where can you find the nupkgs for the 6.0 preview bits?

**Comment by commonsensesoftware** [comment]
@BrennanConroy yes - this type of question/issue is better suited for the API Versioning repo directly.

To answer your question, this behavior isn't completely new. This is essentially how it's always behaved. Just like MVC always trims off the `Controller` suffix, so too, API Versioning trims of trailing numbers. This is to deal with naming conflicts in the same namespace; for example, `WeatherForecast1Controller` and `WeatherForecast2Controller`, should both have the name `WeatherForecast`. This behavior is not well-documented by me (#bad-developer #no-donut). The controller name is, unfortunately, important. It's the only logical way to group different controller types together. It's not really possible to infer semantic or grouping relationships from the URL; primarily because URLs do not convey hierarchy or relationship, despite what human beings might think they see. Not using this convention would produce an equal number of unexpected results, but in the opposite direction.

During the `5.0` release, I noticed that this normalization was happening in two places. In an attempt to optimize and reduce duplication, I accidently introduced a change that broke certain scenarios - like this one. No test caught that because it wasn't a scenario I thought of. I would have assumed someone would have rather applied an API version such as `2020-01-01` or something. Regardless, this should not have happened.

`5.1` and `6.0+` introduces the following interface to deal with this:

```c#
public interface IControllerNameConvention
{
    string NormalizeName( string controllerName );
    string GroupName( string controllerName );
}
```

There are 3 built-in flavors:
- `ControllerNameConvention.Default` - currrent, default behavior
- `ControllerNameConvention.Group` - only the name used for grouping is normalized (e.g your controller name is unchanged)
- `ControllerNameConvention.Original` - _as is_; no normalization. some things _might_ break

in `5.1`, it is set with `ApiVersioningOptions.ControllerNameConvention`. in `6.0+`, it will be a replaceable `IControllerNameConvention` service in the DI container.

in `5.0` there is a **workaround**. if your controller is decorated with `[ControllerName("WeatherForecast2022")]`, then it is used verbatim without any modification. Technically, there are other ways that it can be changed, but this is by far the simplest.

The `6.0` previews are out. _Preview 3_ is quite close. Note that the name package identifiers are `Asp.Versioning.*` for `6.0+`. If you want to know the _why_ and history, please see the [announcement](https://github.com/dotnet/aspnet-api-versioning/discussions/807). A great many things have changed in `6.0`. You likely want the `Asp.Versioning.Mvc` package.

**Comment by simple-nathan** [comment]
@commonsensesoftware thank you sir! As ever, super helpful and very much appreciated. I guess I should close this issue as it's turned out to be a "feature not a bug"?

**Comment by commonsensesoftware** [comment]
FYI, I realized the last time this was called out that _I like donuts_ 😋, so I added the description of this behavior to the wiki. That can be found [here](https://github.com/dotnet/aspnet-api-versioning/wiki/Controller-Conventions#naming). Hopefully, that _should_ help. I've been stalled on code signing. That is preventing the official release and updating the documentation with relevant code changes/configuration. Once that happens, I'll expand upon the documentation. We're ever closer.
