### ISSUE TITLE
CSS isolation support in ASP.NET Core 6.0 for img tag

### ISSUE THREAD

**Issue by kryszek** [dotnet/aspnetcore#41507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

According to documentation:
Introduction to Razor Pages in ASP.NET Core, section CSS isolation
(https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio#css-isolation)
css file:
`h1 {
    color: red;
}`
For h1 tag:
`<h1>My header</h1>`
Resulting correctly with:
`<h1 b-c3zvocbsns>My header</h1>`

However, css file:
`img {
    width: 110px;
    height: 44px
}`
for img tag:
`<img src="/images/logo.png" alt="logo" />`
Resulting with no changes:
`<img src="/images/logo.png" alt="logo" />`

### Describe the solution you'd like

Could the result be something like:
`<img b-c3zvocbsns src="/images/logo.png" alt="logo" />`

Or even using class in .css file:
.logo {
    width: 110px;
    height: 44px
}
Could the result be something like:
`<img class="b-c3zvocbsns" src="/images/logo.png" alt="logo" />`

**Comment by javiercn** [comment]
@kryszek thanks for contacting us.

What's happening there is that a tag helper is acting over the img tag and that results in the tag not being treated as an HTML tag. CSS isolation only applies to HTML tags, so that's why it's not being applied in this case (since it's not just a tag).

CSS isolation only applies to HTML tags within the document, otherwise it would potentially break the isolation boundary of other tags or components.

We do have an issue opened on making possible for other components and tag helpers to opt-in into receiving the CSS scope from a call/use point, which would result in what you are looking for. I would suggest you upvote this issue instead https://github.com/dotnet/aspnetcore/issues/30213

As a workaround, we would suggest you wrap the tag inside another element like a div, and update your CSS rule to account for it.
