### ISSUE TITLE
Potential memory leak with Blazor Webassembly when using an iframe in a razor component

### ISSUE THREAD

**Issue by LouHendricks** [dotnet/aspnetcore#41537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use a javascript library that displays a pdf on the web page using an iframe in my blazor webassembly application.  I am having issues with memory usage climbing and never dropping and also with the browser crashing while testing it.  While troubleshooting I have isolated the behavior that any razor component with an iframe (even an empty one) will allocate memory and never return it even after garbage collection.

### Expected Behavior

Updated: I would expect that Blazor would not allocate memory forever every time a component with an empty iframe is visited.  This behavior does not occur with an empty frame.

Original submitted: I would think that the allocated memory would be returned after the component is navigated away from and after garbage collection takes place.

### Steps To Reproduce

- Create a new Blazor Webassembly ASP.Net Core Hosted application from the template using the latest Visual Studio 2022 and .Net Core 6.
- Edit counter.razor and add <iframe style='width:10px;height:10px'></iframe> on the page.
- Launch the application in debug mode using IIS express
- Click back and forth on any of the three home pages and see memory allocation climb every time Counter is clicked on.
- Repeat process until garbage collection occurs.  I saw GC indicator at 830 MB and at 1.1 GB memory allocation.  Strangely after the second GC memory allocation jumped from 1.1 to 1.4 GB.

### .NET Version

6

**Comment by javiercn** [comment]
@LouHendricks thanks for contacting us.

Webassembly applications can't return the memory unless the app is stopped and restarted. Otherwise, that would violate the memory safety guarantees offered by webassembly.

**Comment by LouHendricks** [comment]
Maybe I should have made my expected behavior be - Blazor should not allocate additional memory repeatedly every time a page containing an iframe is visited.

**Comment by LouHendricks** [comment]
Editing my test project and putting in a frame instead of an iframe does not allocate any additional memory every time the page is visited.  This seems to be an iframe only behavior.

**Comment by javiercn** [comment]
@LouHendricks I missed some of the details in your initial comment.

Let me provide some more context:
* You can't measure memory in Debug configurations and with the Debugger attached. That changes the behavior of the runtime.
* As for the memory, webassembly applications can grow memory but once that memory grows it can not shrink. What this means is that if you allocate a big object in .NET, the garbage collector will be able to reuse the memory when the object is collected, "but the runtime can't return the memory to the OS" (because the webassembly memory can't shrink).

As to for the repro you are suggesting, it's not clear what the scenario is or what's going on, but essentially if your program consumes a lot of memory that's not a memory leak. If the hardware you are running on or the limits the browser imposes are not big enough, the program will eventually crash.

As for what's concretely going on, I would advise against taking any measurement in Debug configurations or with a debugger attached as those factors spoil the measurements.

**Comment by LouHendricks** [comment]
@javiercn Thank you for responding again.  My actual scenario is using the pdf-lib js library wrapped in a component to provide pdf viewing and manipulation in my blazor application.  I'm having application crashed using my component right now so I'm deconstructing it and testing it one element at a time to see if I can identify my issue.

During this process I came across the behavior of iframe allocating additonal memory every time the component containing it is accessed which does not seem to happen for any other element that I add to a razor page.

The memory allocation does seem to hit a cap eventually (it hit 1.4 GB then finally stopped on my first test attempt) without crashing my application.  I feel like allocating that much memory just by repeatedly navigating to a page containing an iframe is undesirable but maybe it is unavoidable.  Based on what you have said I am going to try to see if I can see what the memory allocation is like when not in debug mode.
