### ISSUE TITLE
Duplicate registration in ServicesCollection on AspNetCore.

### ISSUE THREAD

**Issue by GFlisch** [dotnet/aspnetcore#41530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On ASPNETCORE .NET 6 when I request the instances for ILogger<T> and IConfiguration I receive for each of them 2 instances instead of one like in ASPNET CORE 3.1 and 5.
For ILogger this is 2 instances of the same type.
For IConfiguration this is 2 instances: One of type ConfigurationManager and ConfigurationRoot.

### Expected Behavior

Receive one instance like in .NET Core 3.1 and 5.0.

### Steps To Reproduce

On Visual Studio 2022.
Create a WebApi project in .NET 6 and another in .NET 5

For .NET 5, in statup.cs
```
public class Startup
    {
        ...
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            var configurations = app.ApplicationServices.GetServices<IConfiguration>();
            var configuration = app.ApplicationServices.GetService<IConfiguration>();
```
=> One instance will be in configurations. Same for ILogger...

For .NET 6
```
var app = builder.Build();
var configurations = app.Services.GetServices<IConfiguration>();
var configuration = app.Services.GetService<IConfiguration>();
```
2 instances in configurations, and 2 for a ILogger<T>...

### .NET Version

6.0.300-preview.22204.3

### Anything else?

We can see in the .NET 6 framework code that 2 collections of services are built with on each one a declaration of ILogger and IConfiguration.

When you merge the 2 collections we have the issue of having 2 registrations for ILogger<T> and IConfiguration

**Comment by davidfowl** [comment]
How is it affecting you?

**Comment by GFlisch** [comment]
Hi @davidfowl, this in in fact a valuable remark. I have take time to answer.

I am working in a European utility company located in Belgium and Germany.  

They are building line of business applications used to serve the community by providing applications to maintain the balance between production and consumption of electricity.

We are using my open source framework available here: https://github.com/GFlisch/Arc4u.

If you have a look at this class, https://github.com/GFlisch/Arc4u/blob/master/src/Arc4u.Standard.Dependency.ComponentModel/ComponentModelContainer.cs (net5.0) you will see that I have added a capability to resolve (getService equivalent) a serviceType by name or not (something that is possible with System.Composition and not on the standard net core DI)..

When a developer Resolves a type, I am checking that only one instance exists otherwise I throw a MultipleRegistrationException. I do this because I don't want that when we expect to have one instance that 2 or more exist. If this is the case it means that more than one implementation exist and are registered. By having no error we don't know which one is used and there is a risk regarding the behavior of the application.

In the case of the assumption that only the latest registration is resolved it means that this will depend on the order of the registration. Imagine we develop an application and run it without any issues. By updating the application on a different part of the code, we can change the order of the registration and the behavior will be different in a business part that we don't have changed and may be not tested with a code coverage enough to detect this. 
This is the main reason why I check this to ensure that when we expect one instance only one registration is done and this is why when I have updated the framework to net6.0 and used it in an ASP.NET core service I was able to detect this immediately...

I hope this was clear.

**Comment by halter73** [comment]
Thanks for taking the time to explain your use case.

> In the case of the assumption that only the latest registration is resolved it means that this will depend on the order of the registration. Imagine we develop an application and run it without any issues. By updating the application on a different part of the code, we can change the order of the registration and the behavior will be different in a business part that we don't have changed and may be not tested with a code coverage enough to detect this.

Order of registration allowing you to override services in ASP.NET Core. This is documented at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#service-registration-methods.

> Any of the above service registration methods can be used to register multiple service instances of the same service type. In the following example, `AddSingleton` is called twice with `IMyDependency` as the service type. The second call to `AddSingleton` overrides the previous one when resolved as `IMyDependency` and adds to the previous one when multiple services are resolved via `IEnumerable<IMyDependency>`. Services appear in the order they were registered when resolved via `IEnumerable<{SERVICE}>`.

While it would be possible for extension methods replacing services to remove any pre-existing service descriptors for the same service type, it would make these methods more complicated and inefficient. In any case, that's not what existing IServiceCollection extension methods do to replace services, and I don't expect this to change any time soon.

I do see the appeal to being more explicit when replacing a single service vs adding to a list of services. If replacing services worked differently, even ASP.NET Core itself could throw something like a `MultipleRegistrationException` when you tried to resolve a service registered multiple times without `IEnumerable<{SERVICE}>`, but the existence of all the existing methods in the ecosystem that assume this is the way you replace services means you're going to be fighting an uphill battle.

All that said, `WebApplicationBuilder` does not need to have two `IConfiguration` services by default. It's just confusing and wasteful. Fortunately, this is one of the many small issues we fixed in .NET 7 with https://github.com/dotnet/aspnetcore/pull/40459. Can you confirm that the latest .NET 7 preview resolves this issue for you? This was a very large change across multiple assemblies and repos, so it's not something we would backport to .NET 6.

**Comment by GFlisch** [comment]
I will do the test on .NET 7 but later.
