### ISSUE TITLE
Microsoft.JSInterop can't build Release on Version 6.0.4

### ISSUE THREAD

**Issue by Inco90** [dotnet/aspnetcore#41581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to 6.0.4 I can no longer publish or build my solution (Blazor Server Webapp) with the Release preset. 
I received the following error message on several machines:

_Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3021	Unable to copy file "C:\Users\UserName\.nuget\packages\microsoft.jsinterop\6.0.4\lib\net6.0\Microsoft.JSInterop.dll" to "bin\x64\Release\net6.0\Microsoft.JSInterop.dll". Access to the path 'bin\x64\Release\net6.0\Microsoft.JSInterop.dll' is denied.	SolutionName	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4808_	

### Expected Behavior

Build and publishes my solution with the same preset as Version 6.0.3 could without the error message above.

### Exceptions (if any)

Debug config works fine

### .NET Version

6.0.202

### Anything else?

VS Enterprise 17.1.6

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@Inco90 thanks for contacting us.

This problem seems to be specific to something on your environment. Can you try a few things to see if we get more info?
* Check if some program is somehow blocking the dll on the target path (if you want to be sure, you can reboot the computer).
  * You can use the sysinternal tools (process explorer -> ctrl+shif+F) to determine what processes are holding a handle to a file.
* Clean the bin and obj folders and try to build again
* Make sure that the app from the project is not running.
