### ISSUE TITLE
Target html and body tags in css isolated files

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#41580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I originally posted on [StackOverflow](https://stackoverflow.com/q/72161251/9971404).

### Describe the bug

I'm using "css isolation" with RazorPages.

I have a `_Layout.cshtml` and `_Layout.cshtml.css`. I want to apply a background color to the body. So I tried `html body { background-color: red }`.

But that generates css with an isolation attribute, e.g. `html body[b-d29f2jaemq] { background-color: red); }`. The `html` and `body` tags don't have such attributes.

Can the html and body tags be targetted in a css isolation file? Is this a bug or by design?

### Expected Behavior

`html body { background-color: red); }`

### Steps To Reproduce

As above

### .NET Version

6.0.202

### Anything else?

vscode and o# plugin

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

This is likely because there is a tag helper applying to the body tag (likely BodyTagHelper) which means this is no longer a plain HTML element, hence why it doesn't apply the attribute.

You can validate this by using @removeTagHelper Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper, Microsoft.AspNetCore.Mvc.Razor.

Note that some other functionality might break if you do this. We would recommend that you base your styles on some element that is not being considered a tag helper (you can see this because the scoped css attribute only gets applied to elements)

We have designs to improve this area to allow the scope to be selectively applied to tag helpers. If you care about this scenario, I suggest you upvote this issue instead https://github.com/dotnet/aspnetcore/issues/30213
