### ISSUE TITLE
TraceIdentifier performance is inconsistent

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/aspnetcore#41651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## My situation：
TraceIdentifier performance is inconsistent

***Local environment*** (kestrel)：TraceIdentifier  like `0HMHJP0IGCO99:00000002`
***Production environment (IIS)***：TraceIdentifier like `80000cca-0000-d600-b63f-84710c7967bb`

### Expected Behavior

TraceIdentifier performance is consistent

TraceIdentifier  like `0HMHJP0IGCO99:00000002`

### .NET Version

net 6

**Comment by davidfowl** [comment]
Performance? What does that mean?

**Comment by SpringHgui** [comment]
HttpContext.TraceIdentifier Value has  different format
kestrel：`0HMHJP0IGCO99:00000002` 
IIS：`80000cca-0000-d600-b63f-84710c7967bb`

**Comment by davidfowl** [comment]
Yes, that's by design. On IIS it comes from HTTP.sys (the kernel driver) and it is exposed to the application so that the you can trace the ID from the kernel to the application and back to the kernel. With Kestrel it's a different format. They're not going to made the same because that would mean it needs to all look like IIS.

**Comment by SpringHgui** [comment]
when deploy by IIS，Is it possible to make it same to kestrel format style ,like  `0HMHJP0IGCO99:00000002`

**Comment by davidfowl** [comment]
No. The formats are different on different servers for the reasons mentioned.
