### ISSUE TITLE
Undocumented breaking changes .NET 5 => .NET 6

### ISSUE THREAD

**Issue by Socolin** [dotnet/aspnetcore#41679]
Hello,

I just wanted to notify that this commit did break things in our project:

https://github.com/dotnet/aspnetcore/commit/bd4d9657e92bdded675980a6d9fcff6300e2a894

We were using 

```cs
public ActionResult<Model> Get() {
    Response.StatusCode = (int) HttpStatusCode.Created;
    return new Model()
}
```

and the status code is now overwritten with no way of configuring it (we have to use) so it break things by returning 200 instead of 201.

I was not able to find any reference to this breaking changes in the migration doc
https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio

**Comment by brunolins16** [comment]
@Socolin sorry for breaking you project, however, the assumption is that we will always return `200` for your scenario (since 3.1 https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#actionresultt-type). the change you mentioned is just fixing the code to make the implementation in sync with the expected behavior.

Probably you already fixed it but some suggestions to your scenario are:

``` c#
public ActionResult<Model> Get()
{
    return Created("somelocation", new Model());
}
```

``` c#
public ActionResult<Model> Get()
{
    return StatusCode(StatusCodes.Status201Created, new Model());
}
```

**Comment by brunolins16** [comment]
However, I will add a breaking change to document it just to make it easier to discover since it might cause some Filters issues as well, since they might be expecting a `null` status code.

**Comment by brunolins16** [comment]
> However, I will add a breaking change to document it just to make it easier to discover since it might cause some Filters issues as well, since they might be expecting a `null` status code.

@Socolin I just published the breaking change https://github.com/aspnet/Announcements/issues/485. Thanks for reporting the undocumented change.
