### ISSUE TITLE
[Blazor] pass custom class parameter to page

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#41828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently parameters are well defined for Blazor components but not for Blazor pages. They only support what can be passed via URL - string/int etc.

### Describe the solution you'd like

An API e.g. `NavigationManager` method which would allow to pass object as parameter to the page just as if it was a Blazor component.

**Comment by javiercn** [comment]
@janseris thanks for contacting us.

I imagine this is similar to `history.push(state)` in JS but without the serialization. Did I get this right?

**Comment by janseris** [comment]
@javiercn 
Hi,
I am not very familiar with JS API but yes without serialization.

Scenario (artificial but to simulate more than one parameter).

Page:
```
@page "/animalSummary"

@* This page displays animal with its photo as a confirmation before it is added to the system (DB Insert) *@

_XML markup showing the data_

[Parameter] Animal Animal {get;set;}
[Parameter] AnimalPhoto Photo {get;set;} //contains byte[] and some additional info like description, format, dimensions etc.

```
Navigating to this page:

`NavigationManager.NavigateTo("/animalSummary", new Dictionary<string, object>{"Animal" = variable1, "AnimalPhoto" = variable2});`

If the parameter names would be accessible via Intellisense and detected during compilation, that would be better, but I think that this is the current API for Blazor components in BlazorWebView (I might be remembering it wrong).

The solution might be that each page would have 1 parameter which is AnimalSummaryPageData and then its members could then be strongly typed because it would be initialized like `new AnimalSummaryPageData{Animal = variable1, AnimalPhoto = variable2 };`

Maybe this data type could be automatically generated in the Blazor page partial class (.razor.cs)?

**Comment by SteveSandersonMS** [comment]
It's an interesting idea, but I think these objectives are best achieved using a different API than NavigationManager. The reason is that NavigationManager is exclusively intended as a way of interacting with the browser's URL-based history API. If it were to start holding state that is separate from the URL, then you could no longer deep-link to arbitrary parts of your application or generally perform navigation using `<a>` tags.

Instead I think you should look at using one of the various other techniques that allow for transferring data independently of the URL. For example:

* The most mainstream technique would be to use the URL to pass the ID of some object (as a string or number), and have the recipient then look up the data from that ID. This is then compatible with normal URL-based navigation and bookmarking.
* Alternatively you could use a framework feature like CascadingValue to set the instance being passed at a high level in the component hierarchy and have it be received as a CascadingParameter deeper inside the component hierarchy
* Finally, you could create an entirely custom way of communicating values as your own DI service
