### ISSUE TITLE
Add in-library support for DisplayFormat Attribute on Blazor model properties 

### ISSUE THREAD

**Issue by deafcomedian** [dotnet/aspnetcore#41840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'd like to be able to use the MVC strategy using DisplayFormat attributes to format my model properties in Blazor apps. 

Currently, the only native way to achieve this is to always apply `.ToString(_format_)` wherever the property is referenced in a Blazor page.

From 2019, it sounds like this is a known missing feature: [Comment in Issue 5523](https://github.com/dotnet/aspnetcore/issues/5523#issuecomment-533628206)

Currently:

Model.cs
```
public decimal MyDecimal { get; set; }
```

Page.razor
```
<div>
    @(${Model.MyDecimal:0.##})
</div>

OR with predefined formats like:

<div>
    @Model.MyDecimal.toString("N2")
</div>
```

### Describe the solution you'd like

I'd like references to model properties decorated with the DisplayFormat attribute tag to reflect in Blazor pages.

Ideally, this just displays with the format string applied.

Model.cs
```
[DisplayFormat(DataFormatString = "{0:##}"
public decimal MyDecimal { get; set; }
```

Page.razor
```
<div>
    @Model.MyDecimal
</div>
```

Thanks!

**Comment by SteveSandersonMS** [comment]
@deafcomedian Thanks for the suggestion.

We don't plan to make something like this happen by default whenever there's an `@someExpression` because it would be very breaking to existing code, plus even for new code there would be lots of cases where you *don't* want this to happen.

We'd recommend that you create some utility method that you can call, e.g., `@MyFormatter(() => someExpression)`, which in turn can look up the formatting you want to apply. If the method is declared as accepting a `Expression<Func<T>>` then it's technically possible to determine the property attributes.
