### ISSUE TITLE
Image from url (http) not show in Blazorwebview in wpf app

### ISSUE THREAD

**Issue by tespheakdeyesoftix** [dotnet/aspnetcore#41912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor server application running in Blazorwebview in wpf application and everything work fine except display image from http url. Display image from https url is working fine.
Is there any way I can fix this problem?

Thank,

### .NET Version

6.0.300

**Comment by javiercn** [comment]
@tespheakdeyesoftix thanks for contacting us.

That's likely a mixed content issue within your app. The solution would be to access the image over HTTPS or otherwise, download the image on the .NET side and rendering on the browser as an object url.

We do have plans to make this easier in the future. See https://github.com/dotnet/aspnetcore/issues/25274
