### ISSUE TITLE
IHostingEnvironment.WebRootPath is not nullable but can be null

### ISSUE THREAD

**Issue by Socolin** [dotnet/aspnetcore#41929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

It seems `IHostingEnvironment.WebRootPath` can be null.

![image](https://user-images.githubusercontent.com/539620/171041449-c3522282-0aaa-49ed-8271-1cd9da627d29.png)

Can you add `?` to this declaration ?

### .NET Version

6.0.202

**Comment by adityamandaleeka** [comment]
@Socolin can you share your repro steps? We'd like to understand how you got to that state.

**Comment by Socolin** [comment]
https://github.com/Socolin/ReproBugAspnetCoreWebHostEnv/blob/main/ReproBug/TestMiddleware.cs#L20

**Comment by halter73** [comment]
I looked at this and confirmed `WebRootPath` is indeed `null`. And when you stop to really think about it, it makes sense because there is no `wwwroot` directory in the project. If you add one, it [becomes non-null](https://github.com/Socolin/ReproBugAspnetCoreWebHostEnv/compare/main...halter73:main).

Thanks for the report and the repo @Socolin. We should make both the `IHostingEnvironment.WebRootPath` and more importantly the non-obsoleted `IWebHostEnvironment.WebRootPath`.

The `WebRootFileProvider` properties are set to the `NullFileProvider` instance which makes sense too, so their nullability doesn't need to change.

**Comment by adityamandaleeka** [comment]
Triage: we should probably start an issue for tracking nullability changes in 7 and include this in there (along with other stuff we've changed). For example, this is what we did in 6: https://github.com/aspnet/Announcements/issues/444

**Comment by adityamandaleeka** [comment]
Triage: Creating the nullability changes announcement at this point seems low-value and we haven't heard any requests for it. We can re-evaluate if we hear more feedback about this.
