### ISSUE TITLE
Provide a more intelligent routing fallback for Blazor apps that only falls back if the route matches a routable component

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#42003]
The Blazor fallback logic always falls back to the specified route even if the original route doesn't match any routable components. This can be problematic in some cases, like in ASP.NET to ASP.NET Core app migration scenarios where you want to allow any unhandled requests to be proxied elsewhere. The [Cocoon](https://github.com/VisualReCode/Cocoon) project currently uses some custom logic to identify all of the routable components and then only falls back for the component routes. We'll need something similar to support migrating to Blazor in our own incremental migration support based on YARP. We could provide some helpers that make this logic easier.

**Comment by SteveSandersonMS** [comment]
Sounds fine.

Implementation note: this would need to be an option, not a new default fallback behavior, because in general developers aren't required to use the built-in routing system and they might have a custom one of their own. We wouldn't be able to detect which URLs are matched by a custom router.

**Comment by SteveSandersonMS** [comment]
We have this now.

@javiercn Do you feel the current implementation is sufficient for this to count as "done"? If so we can close it.
