### ISSUE TITLE
Razor Contextual Components

### ISSUE THREAD

**Issue by eyalalonn** [dotnet/aspnetcore#42126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm creating a UI library that is built on top of Blazor and I have two main issues with it and are as followed:

1. A Razor component needs to be unique to avoid naming conflicts so if you have a `DataGrid` and you like to have the following structure as far as I know atm you can't because the components names are derived by the name of the file.
```html
<DataGrid>
    <Header>
        <Column DataField="FirstName" Caption="First Name" />
        <Column DataField="LastName" Caption="Last Name" />
        <Column DataField="Age" Caption="Age" />
    </Header>
    <Content>
        <Row>
            <Column>Eyal</Column>
            <Column>Alon</Column>
            <Column>40</Column>
        </Row>
    </Content>
</DataGrid>
```
But this naming issue doesn't just exist in a single component it exists across components as well so in practice you have to use a very long names or prefixing the child components with at least the name of the parent component so for the  example above we might name the child components as `DataGridHeaderColumn` and `DataGridRowColumn` respectively to avoid the naming conflict.

2. A `ChildContent` can't be restricted, you can literally put anything but in a `DataGrid` or any other complex component you may want to define what can go there.

### Describe the solution you'd like

Say that the file name of the `DataGrid` component is `CompanyDataGrid.razor` so atm the consumer have to access the component through `CompanyDataGrid` to solve the naming problem I'm proposing to add a `tag` directive to components that would like this this:
```
@tag DataGrid
```
This could be an attribute at the class level like so `ComponentTagNameAttribute("DataGrid")`.

Now to solve the problem with `ChildContent` this is somewhat related because we want to have two different types of columns for our `DataGrid` but with the same name depending on the context and this is the reason it's part of the same issue so the `DataGrid` component might look like this:
```html
@tag "DataGrid"
@typeparam TItem

<table>
    <thead>
        <tr>@Header</tr>
    </thead>
    <tbody>
        @Content
    </tbody>
</table>

@code {
    [Parameter]
    [ChildType(typeof(DataGridHeaderColumn))]
    public RenderFragment? Header { get; set; }
    
    [Parameter]
    [ChildType(typeof(DataGridRow))]
    public RenderFragment? Content { get; set; }

    [Parameter]
    public IReadOnlyList<TItem> DataSource { get; set; }
}
```
Now both `DataGridHeaderColumn` and `DataGridRowColumn` can have the exact same tag name using the `@tag "Column"` but differ in the type.

Similar to `DataGridHeaderColumn` and `DataGridRowColumn` the component `DataGridRow` uses `@tag "Row"`.

It may be a good idea to add a property to `ChildTypeAttribute` to control whether many instances or a single instance of the component can appear inside the content, in the example above I haven't specify any properties because I don't know what should be the default but I conveniently assumed many.

I hope it's crystal clear.

**Comment by eyalalonn** [comment]
@javiercn 

> With regards to the component name, you could use the fully qualified type name. You only have to use it when you are using two different components with the same name.

Unfortunately, this leads to unpleasant user experience, really.

> It will prevent "functional" components like "virtualize" from being used in such components (or you would have to manually indicate that those components are ok

In my opinion the author of the component should decide what goes where and why not the framework and that wouldn't restrict it from being used as the author can choose to add a child component with a `public RenderFragment? Content { get; set; }` without the attribute to restrict it and there the consumer can have whatever he/she wants.

> The content for that component can contain a mix of control flow statements or might come from a render fragment.

Again, same as above.

> For the other one, we would not necessarily allow you to specify a tag name (same issue as with two very general class names) 

Well that's a shame really. 

I'm not sure what the comment about "same issue as with two very general class names" because it's not! they are two different types that under a specific context have the same tag name it's exactly the same as having two different classes that have the exact same property name that return two different types, why not?

> but would support something like either using https://github.com/dotnet/razor-compiler/issues/257 or allowing to specify the component using a partial class name like ParentNs.Component in cases there is ambiguity.

You provided solutions that don't solve the problem and then marked the issue as a duplicate but with all due respect I'm not asking for an `alias` nor I'm asking a way to do `ParentNs.Component` I'm asking to have two different types with the ability to specify the same tag name in different context and make child components more discoverable which would lead to a much better user experience so I'm not sure why you tagged it a duplicate.

**Comment by javiercn** [comment]
@eyalalonn Thanks for the additional details.

It is not exactly the same, but it is not too far off. Some of the samples made me interpret things in a different way. Let me break things down a little:
* MyDataGrid -> DataGrid: This is what I was mentioning when I referred to using an alias.
* `[ChildType(typeof(DataGridHeaderColumn))]` my understanding is that you don't want to "restrict" the content, but to "alias" what `Column` means within the content.
  * This is in general not solvable but for trivial cases. Using your component definition from above, you would not be able to do things like this when consuming your component:
  ```
  <DataGrid>
    <Header>
        @headers
    </Header>
    ...
  </DataGrid>
  ```
  * There is no way for us to know what's in the RenderFragment at compile time.
  * There is no way for us to know that we need to generate different code because it is being used at a concrete call-site.

We don't plan to do these kinds of "bindings" at runtime because that would be very expensive.
We don't think that in general, having the same tag mean different components based on the context is something desirable. (If I am understanding correctly that in your sample Column in Header and Column inside DataGridRow mean different types).

I understand that this issue is not the "exact" same issue as the one I pointed out, but it is on the same "theme" of "controlling what goes inside a renderfragment and how it is interpreted" hence why I lumped it together with it. In general, if we decide to take action on this area, we will use that issue as reference and take input from all related issues like this.

I hope this helps clarify our reasoning and shed some light into the challenges in this area.

**Comment by eyalalonn** [comment]
> If I am understanding correctly that in your sample Column in Header and Column inside DataGridRow mean different types

Yes, they are different types that under different context of the `DataGrid` I'd like them to have the same html tag name in this case "Column".

Really the problem atm is you have to use long names like `CompanyDataGridHeaderColumn` and `CompanyDataGridRowColumn` to differentiate between components and yes you could *abuse* namespaces but obviously this fails the moment you have to mix components together that share the same name, for application developers that author specific components this might work but for developers that develop general UI libraries this is a challenge, the experience could be a lot better both for developers that author components and consumers alike.

@javiercn Thank you very much.
