### ISSUE TITLE
Cannot resolve ApiController in unit tests of the IoC container

### ISSUE THREAD

**Issue by emanuelefirmani** [dotnet/aspnetcore#42153]
## Summary
I want to test the resolution via IoC of each single entry point, i.e. each controller.

## Motivation and goals
Controllers may have several dependencies. I need to be sure that all the dependencies are correctly registered.
I cannot rely on integration tests, because mockups are used as dependencies.

## In scope
Using `services.AddControllers()` does not register the `ApiControllers` as dependencies, therefore they cannot be resolved.
I would suggest that `ApiControllers` should be part of the IoC scope.

## Examples
See https://github.com/emanuelefirmani/IocResolutionOfControllers.git
The repo contains two branches:
- main contains the API and a single test that fails
- bad_resolution contains the solution I came with, but I consider it as a poor implementation

**Comment by arialdomartini** [comment]
The test

```csharp
application.Services.GetRequiredService<WeatherForecastController>().Should().NotBeNull();
```

fails with an error that clearly says:

```csharp
No service for type 'IocResolutionOfControllers.Controllers.WeatherForecastController' has been registered.
```

I tried also adding 

```csharp
services.AddMvc().AddControllersAsServices();
```

as suggested in [ASP.NET Core Resolve Controller and call Action by name](https://stackoverflow.com/questions/68927861/asp-net-core-resolve-controller-and-call-action-by-name) by it did not help.

**Comment by brunolins16** [comment]
@arialdomartini @emanuelefirmani Probably the problem is not the `AddControllersAsServices` but the fact that the `AddMvc` is not discovering the application parts because it depends on the `applicationName` as described here https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-6.0#discovery-in-application-parts.

You could try to change this line https://github.com/emanuelefirmani/IocResolutionOfControllers/blob/db40f90eebfe5c87c38be345b9e57b3a071f48f5/IocResolutionOfControllers.Test/UnitTest1.cs#L13 to something like:

``` c#
var builder = WebApplication.CreateBuilder(new WebApplicationOptions() 
  { 
      ApplicationName = "IocResolutionOfControllers"
  });
```
Or add a call to [`AddApplicationPart`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvccoremvcbuilderextensions.addapplicationpart?view=aspnetcore-6.0) to include the API assembly to the Builder created during the test.

In both cases you probably will need to add a call to `AddControllersAsServices()` as mentioned by @arialdomartini.
I hope this helps you.

**Comment by emanuelefirmani** [comment]
The proposed solution works. You can find it here: https://github.com/emanuelefirmani/IocResolutionOfControllers/blob/suggested_resolution/IocResolutionOfControllers/IocResolutionOfControllers/Startup.cs

I'm not very happy of invoking `AddMvc` in a REST API project, but it's needed.

I'm wondering how dotnet resolves `Controllers` during the handling of a request: is this resolution not managed by IoC?

**Comment by emanuelefirmani** [comment]
I took another look and found:
```csharp
public static IMvcBuilder AddMvc(this IServiceCollection services)
{
    if (services == null)
    {
        throw new ArgumentNullException(nameof(services));
    }

    services.AddControllersWithViews();
    return services.AddRazorPages();
}
```
I tried adding `services.AddControllersWithViews()` and `services.AddRazorPages()` to my code, but the test is still red.

It's the call to `IMvcBuilder.AddControllersAsServices()` what makes the trick:
```csharp
foreach (var controller in feature.Controllers.Select(c => c.AsType()))
{
    builder.Services.TryAddTransient(controller, controller);
}

builder.Services.Replace(ServiceDescriptor.Transient<IControllerActivator, ServiceBasedControllerActivator>());
```

Why is `AddControllersWithViews` a method available only to `IMvcBuilder`, but only to `IServiceCollection`?
