### ISSUE TITLE
Microsoft.AspNetCore.ClientAssets - An improvement proposal

### ISSUE THREAD

**Issue by lscorcia** [dotnet/aspnetcore#42220]
Hi,
I just discovered @javiercn blog post at https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/ and I have to say I am impressed by the idea and the functionality provided by the `Microsoft.AspNetCore.ClientAssets` experimental package.

I'd like to propose a small change that could make it adaptable to more scenarios. In my case (Razor Class Library for an ASP.net Core Web project), I had three additional requirements:

a) I need to access the output path in more than one build command;
b) My npm commands are somewhat more complex than just invoking webpack and require moving some files around after packing;
c) My npm commands need to be cross-platform.

The current code at

https://github.com/aspnet/AspLabs/blob/d193d1660e54f4c65f86a9938ffa1a424b37b3a6/src/ClientAssets/Microsoft.AspNetCore.ClientAssets/build/netstandard2.0/Microsoft.AspNetCore.ClientAssets.targets#L35

invokes `npm run build` as follows:

`npm run build:Debug -- --output-path C:\mypath\obj\Debug\net6.0\clientassets`

This is fine if `build:Debug` resolves to a single `webpack` call, or any other single command that takes a command line parameter, but AFAIK it's not enough if you need to do more complex stuff (in my case, I have to copy some additional files to the output path after webpack is done).

My solution is to modify slightly the above line to use environment vars instead of hardcoding the parameter reference. Just change that line with:

`<Exec Command="$(ClientAssetsBuildCommand) $(ClientAssetsBuildOutputParameter)=$(_ClientAssetsOutputFullPath)" WorkingDirectory="$(ClientAssetsDirectory)" />`

This passes the parameter to `npm` instead of passing it directly to the running script. `npm` automatically makes all parameters available as environment variables as `$npm_config_paramname` / `%npm_config_paramname%`, therefore it becomes really easy to pass this additional parameter to webpack, or to whatever command you may need, by directly specifying it in the `package.json` file, for example:

```
"scripts": {
    "webpack:Debug": "cross-env-shell webpack build --no-color --mode=development --output-path $npm_config_output_path",
    "webpack:Release": "cross-env-shell webpack build --no-color --mode=production --output-path $npm_config_output_path",
    "devextreme-bundler": "devextreme-bundler ./devextreme-custom.bundle.config.js && cross-env-shell shx mv ./devextreme-custom.bundle.js ./devextreme-custom.bundle.debug.js $npm_config_output_path",
    "build:Debug": "npm run webpack:Debug && npm run devextreme-bundler",
    "build:Release": "npm run webpack:Release && npm run devextreme-bundler"
}
```

If you could apply this suggestion to the experimental package, it would add a lot more flexibility in how the client assets are packaged.

Please let me know if you find this suggestion useful or if you have any other comments!

**Comment by javiercn** [comment]
@lscorcia thanks for contacting us.

We appreciate the feedback, and we are looking to do some improvements as we plan to productionize this in .NET 7.0.

With regards to the improvements suggested, some of them are already possible today.
> a) I need to access the output path in more than one build command.

Instead of invoking webpack in your `package.json`, create a js file and invoke node `your-file.js` and there you can invoke as many tools as you need. You can also chain the commands with && on the npm scripts section.

The key point here is that we are going to invoke `npm run build:Debug` and `npm run build:Release` at the correct times and we are going to collect the results and make them available as if they were part of the wwwroot folder. Whatever you do within `build:Debug` and `build:Release` is up to your imagination :).

> b) My npm commands are somewhat more complex than just invoking webpack and require moving some files around after packing;

Using a script should do the trick here.

> c) My npm commands need to be cross-platform.

You can use something like `run-script-os` for that. We will pass the path in a format appropriate for the platform, but making npm commands cross-platform is out of our scope. That said, it might be easily achievable when we productionize this just based on how we decide to model the MSBuild code, but its currently not a goal.

That said, I think it is trivial to us to change how this works and your approach looks like a net improvement, so we'll take that into account as we take the next steps on this journey.

Thanks again for providing feedback, this is very valuable for us as we decide how we move forward.

**Comment by lscorcia** [comment]
Thank you @javiercn for the additional details!
In the end I followed your suggestion and created a js script that runs my commands - something like this:

package.json
```js
"scripts": {
    "build:Debug": "node builder.js --mode=development",
    "build:Release": "node builder.js --mode=production"
}
```

builder.js
```js
const yargs = require('yargs');
const { execSync } = require('child_process');

const argv = yargs
    .option('output-path', { alias: 'o', demandOption: true })
    .option('mode', { alias: 'm', demandOption: true })
    .argv;

console.log(argv.outputPath);
execSync("webpack build --no-color --mode=" + argv.mode + " --output-path=" + argv.outputPath + "/dist", { stdio: 'inherit' });
execSync("devextreme-bundler ./devextreme-custom.bundle.config.js && npm exec cross-env-shell shx mv ./devextreme-custom.bundle.js ./devextreme-custom.bundle.debug.js " + argv.outputPath + "/dist", { stdio: 'inherit' });
```

I will sure improve on this as I learn node/npm better.

Another (small) suggestion. For Release builds, we'd like to use `npm ci` instead of `npm install` to get repeatable builds. While it is easily doable in the csproj, you could maybe consider this as the default behavior:

`<ClientAssetsRestoreCommand Condition="'$(Configuration)' == 'Release'">npm ci</ClientAssetsRestoreCommand>`

One last thing - I noticed that builds are triggered quite often - I'd say every time the project is built in VS. Shouldn't it trigger a build only when the package.json / package-lock.json are changed from the last build? Am I missing something?
