### ISSUE TITLE
About Virtualization in blazor vs large collection

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#42518]
Currently Virtualize component let user scroll the window then display the part of data that's visible.
There's a few question I have :
1) Do users scroll endlessly if there is a million items, or is it better to let user scroll further only if they've reached the end of scrollable area and new items were fetched (instead requesting more data when your fake padding comes into view, request more data when the **last visible element** comes into view and no more fake paddings)
2) If I am loading chat messages, one usually start scrolling bottom to top nowadays, so maybe it would be nice to have options for scrolling from top / bottom? Maybe we can ask for ```StartIndex = 0``` to be the case for meaning to be the last item in your database, or if a hint made available for the total item count in the DB we can just jump right to the bottom of the scrolling too (that's assume we are 'virtualizing' all the items into scrollable area instead of dynamically increasing the scrollable area)
3) If the remote database updated and has new items, if indexing (StartIndex) starts from the bottom I can just call RefreshDataAsync and if user is already at the bottom (or top, if there's a new option) of the scrollable area then StartIndex 0 will now get them the newest items (chat messages are usually newest at the bottom right, where as emails are usually newest at the top) obviously, but if indexing start from the top then can I ask politely for the component to scroll to the bottom for me or expose a method for me to do so instead of me calling javascript myself via interop which in my opinion decreases the Out-Of-The-Box experience for blazor as a .NET & Microsoft product, otherwise the component can also correctly recognize the current virtualized window's position is unchanged and is indeed at the bottom therefore displays the items it needs and are the newest as well
4) If user are scrolling very fast maybe the Virtualize component should use its CancellationToken to notify cancelation of all previous requests
5) Would it be awesome if we are using the approach where request are made using element coming into view detection instead of padding coming into view detection therefore enabling components rendered by Virtualize to have different dimensions as instead of the restriction now to expect same dimension

**Comment by SteveSandersonMS** [comment]
Thanks for your questions.

> Do users scroll endlessly if there is a million items

It sounds like you're talking about the difference between **virtualization** and **infinite scroll**:

 * The Virtualize component follows the UI virtualization pattern, where it looks as if all of the items are in the UI at once, and the user can scroll to any point they want
 * The "infinite scroll" UI pattern is where you only add new items to the document once the user nears the end of the current scroll range, and then you extend the scroll range (like a Facebook news feed). If you want this pattern, you'll need to implement it yourself because that's not what Virtualize is for.

> If I am loading chat messages, one usually start scrolling bottom to top nowadays, so maybe it would be nice to have options for scrolling from top / bottom

That sounds equivalent to asking for a "scroll to specific row" API, which is covered by [this issue](https://github.com/dotnet/aspnetcore/issues/26943) which also provides an example of how you can already do it using a JS interop call. You can therefore set the initial position to the end of the list. The Virtualize component will then fetch the older chat items if the user scrolls upwards.

> If user are scrolling very fast maybe the Virtualize component should use its CancellationToken to notify cancelation of all previous requests

It does do that already.

> Would it be awesome if we are using the approach where request are made using element coming into view detection instead of padding coming into view detection therefore enabling components rendered by Virtualize to have different dimensions as instead of the restriction now to expect same dimension

That sounds like asking for variable-height items, which is covered by https://github.com/dotnet/aspnetcore/issues/25058

There isn't a way of making this work in complete generality, as a user may move the scrollbar instantly to an arbitrary point in the list, and there would be no way of knowing which items would be displayed without fetching and rendering everything in between the old and new positions, which could be tens of thousands of items and be impractical.

The way you're talking about this working sounds more like an infinite-scroll UI pattern which you can already do and doesn't have any dependency on things being a fixed height. It's just not what the Virtualize component is for. We did originally consider making Virtualize cover infinite-scroll scenarios as well, but during implementation, we found that there wasn't really much commonality between what's needed for virtualization and what's needed for infinite-scroll.

Hope this helps!
