### ISSUE TITLE
[Razor] IHtmlHelper.ActionLink/RouteLink add Exception on invalid route

### ISSUE THREAD

**Issue by Timka654** [dotnet/aspnetcore#42556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

.NET 6.0

Have a code in my Razor page
`
@Html.ActionLink("Delete", "Delete", new { item.CaseId, item.QualityId, item.ItemId, item.RarityId })
`
in `linkText, actionName, routeValues` implementation

CaseId have int type
QualityId have byte type
ItemId have int type
RarityId have byte type

Have a Delete page "GetAsync" method
`
public async Task<IActionResult> OnGetAsync(int caseId, byte qualityId, int itemId, byte rarityId)
`

As result i'm have 
`<a href="">Delete</a> `

but other routing have normal results, why?
Open link http://localhost:5174/CaseItems/delete?caseId=1&qualityId=1&itemId=1&rarityId=1 have normal page result

This problem actual always be how asp.net have ActionLink/RouteLink

### Describe the solution you'd like

Add to methods RouteLink/ActionLink

throw NotFoundRoutingException on page cannot be found

throw InvalidArgumentException on parameter have invalid type or not found parameter for sended

Maybe add this for optional using and add this in default application blank - for dont destroy exists projects

### Additional context

`<a asp-page="./Delete" asp-route-caseId="@item.CaseId" asp-route-qualityId="@item.QualityId" asp-route-itemId="@item.ItemId" asp-route-rarityId="@item.RarityId">Delete</a>`
normal working, in ActionLink have parameter "action" - not a "page", this fix my problem, but global problem - "empty link on invalid routing" actual

**Comment by javiercn** [comment]
@Timka654 thanks for contacting us.

I can't fully follow your example, but based on what I see, this is a well-known routing behavior. The issue is likely that you are missing some value to generate the link correctly. You can turn on logging to Debug level and that might give you a hint of what is going on.

In essence, routing will produce an empty link if it can't generate a valid one. The reason for this behavior is that links are generated at runtime, which means:
* You don't see an issue until the link is generated.
* Runtime configuration might affect the way you generate links.

Because of those two reasons, we never throw an exception, as it will result in the page being completely broken compared to a small piece of the page not working correctly as you expect, which is a much more benevolent behavior.

What we would suggest in this case is to make sure the behavior is covered by tests in your app to ensure that things work as expected.

**Comment by Timka654** [comment]
@javiercn thanks for response, my problem solvered in `Additional context` in question... But it's problems have any time in many people, my question have - we can add Exception in generate link if cannot found? if you search "ActionLink href empty" in google/stackoverflow - you found many questions, people cannot visible problem - for search thay have only "my href is empty"
