### ISSUE TITLE
Throw `Exception` if JSInterop calls are made without Blazor Synchronization Context

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#42616]
Add an exception detecting calling JSInterop from the incorrect thread, like we do within the renderer.

https://github.com/dotnet/aspnetcore/blob/a1431a0c70610967eeb37dec57c44e6e4eddec0c/src/Components/Components/src/Rendering/RendererSynchronizationContextDispatcher.cs#L19

Related: https://github.com/dotnet/maui/issues/7865

**Comment by javiercn** [comment]
The issue here is that JS interop is not designed to be multithreaded. We don't want to pay the price of adding synchronization locks to it because Blazor already runs in a synchronization context that only allows a single thread to run at a time.

The renderer checks that it is in the right context when a render is triggered and throws. Unfortunately, we currently don't do the same for JS interop. The consequences of this are that, if you do something like

Task.Run(() => StateHasChanged()) within your component, it will throw an exception (as expected). However if you do something like
Task.Run(() => JS.InvokeAsync(...)) we will not throw an exception and any continuation that occurs within the `Task.Run` will not run inside the synchronization context, which might lead to multiple continuations running in parallel and creating issues.

The enhancement here is what @TanayParikh described, which involves validating that we are running inside the sync context and throwing if not.

**Comment by mkArtakMSFT** [comment]
Closing this as we're planning to cover this by making it explicit in the docs that these APIs are not thread safe.
