### ISSUE TITLE
Provide access to configuring the SecurityStampValidator from IdentityBuilder

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#42749]
It should be easier to discover and configure the `SecurityStampValidatorOptions` that affect the `SecurityStampValidator<TUser>` added by Identity (or indeed completely replace with another implementation of `ISecurityStampValidtor`).

Consider the simple case of wanting to change the interval that the security stamp is validated for changes. Currently, the developer has to know to configure the options manually via the standard options configuration APIs, e.g.:

``` c#
builder.Services.AddIdentity<AppUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

// Force Identity authn cookie security stamp to be validated every minute
builder.Services.Configure<SecurityStampValidatorOptions>(o => o.ValidationInterval = TimeSpan.FromMinutes(1));
```

We should make this easier to configure the security stamp validator via the `IdentityBuilder` e.g.:

```c#
builder.Services.AddIdentity<AppUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders()
    .AddSecurityStampValidator(options => options.ValidationInterval = TimeSpan.FromMinutes(1));
```

Or if a custom implementation of `ISecurityStampValidator` is being used:

```c#
builder.Services.AddIdentity<AppUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders()
    .AddSecurityStampValidator<MyCustomSecurityStampValidator>(options => options.ValidationInterval = TimeSpan.FromMinutes(1));
```

## Proposed API

```diff
namespace Microsoft.AspNetCore.Identity

public class IdentityBuilder
{
+    public IdentityBuilder AddSecurityStampValidator(Action<SecurityStampValidatorOptions> configure);
+    public IdentityBuilder AddSecurityStampValidator<TValidator>() where TValidator : ISecurityStampValidator;
+    public IdentityBuilder AddSecurityStampValidator<TValidator>(Action<SecurityStampValidatorOptions> configure) where TValidator : ISecurityStampValidator;
}
```

@rafikiassumani-msft @HaoK @Tratcher @davidfowl @jcjiang

**Comment by DamianEdwards** [comment]
Do folks think this is ready to take for API review as-is?

**Comment by HaoK** [comment]
Well, we need to be a bit careful here, this really kind of belongs under the identity cookie builders, https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityCookiesBuilderExtensions.cs

as AddIdentity is the original API, we wanted people to move to AddIdentityCore() (for non auth stuff), and configure the cookies separately, which is a bit in the other direction of where minimal is going, but more like: 

```
        services.AddIdentityCore<ApplicationUser>()
            .AddRoles<IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddSignInManager()
            .AddDefaultTokenProviders();

        services.AddAuthentication(o =>
        {
            o.DefaultScheme = IdentityConstants.ApplicationScheme;
            o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
        })
        .AddIdentityCookies(o => { });
```

The security stamp validator is really a cookie concern as opposed to something the core identity/database side of things is the nuance here.

**Comment by DamianEdwards** [comment]
The idea of simply having something like `IdentityBuilder.SetSecurityStampValidatorInterval(TimeSpan interval)` seems OK.

That said, we also saw feedback about scenarios where folks might want to force validation on a per-resource basis (e.g. by inspecting current endpoint metadata), so that they can force validation when particularly sensitive services are being accessed. Would that be best done via a custom `ISecurityStampValidator` or some other mechanism?

**Comment by HaoK** [comment]
> IdentityBuilder.SetSecurityStampValidatorInterval(TimeSpan interval) seems OK, although why not just allow configuration of the options type at that point

Well you can already do that via `services.Configure<SecurityStampValidatiorOptions>(o => ...)`, this is sorta of related to your section question about validation, forcing validation is going to be different depending on your auth, tokens vs cookies for example, which is why I tried to point out that nuance in my previous reply.  Identity is mostly concerned about user data storage (membership) as well as generating a claims principal representing the user.  Authentication is responsible for doing things with that principal (which would encompass the security invalidation scenario).  SignInManager is identity + cookie auth which is why it is tightly coupled to cookie auth.  And why SecurityStampValidation isn't really a core identity thing, its more of a Identity + Authentication thing.  

So to spitball `force validation when particularly sensitive services`, I think you want to do this via Authorization with an imperative call to authorization and make sure to have current claims (as opposed to potentially stale claims in the cookie), `authService.AuthorizeAsync(ForceFetchUserClaims(User), contextOrResource, "SuperSecretPolicy")`.  For performance you really don't want to hit the database on every request to check if your cookie is stale, but for super important things, performance isn't as critical as not letting a bad actor do something he wasn't supposed to do, so I'd argue doing it in the cookie events is not the most robust way to do this kind of super secure security check

**Comment by DamianEdwards** [comment]
>Well you can already do that via services.Configure<SecurityStampValidatiorOptions>(o => ...)

Right but I think the challenge with that is discoverability. Once you know it, it's fine, but we keep seeing feedback that folks struggle to find this kind of detail (most recently from @rafikiassumani-msft). But perhaps this would never have come up if the scenario (forcing revalidation after underlying data changes) were documented in the Identity docs (it currently only shows up in an article specifically about using cookie Authn **without** Identity).

RE doing an imperative call each time, that's fine, but I think we'd generally be promoting more composable solutions, e.g. custom metadata on endpoints that indicate a the principal/claims should be revalidated, and then perhaps a custom middleware that uses that metadata to perform the aforementioned forced sign-in/claims check.

**Comment by DamianEdwards** [comment]
Recommend we close this one out or push to backlog.
