### ISSUE TITLE
blazor: using open/close region vs passing int sequence numbers to component creator method

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#42870]
I see that generic components in `razor.g.cs` files are rendered using generated internal methods like `TypeInference.CreateMyComp_1` and for these methods `int`  sequence numbers (`int seq, int __seq0`) are being passed to be used for the `builder`.

Would it be the same if I use an open/close region inside this TypeInference CreateComp method, so I don't have to pass sequence numbers ?
Are there any downsides to using open region so that's why sequence numbers are being passed as parameters ?

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

I don't remember being a major difference, other than the fact that the "sequence" doesn't work how many folks think. There might be a small improvement for the diffing logic, but I can't remember the details of if and why.

@SteveSandersonMS might have the details.

**Comment by SteveSandersonMS** [comment]
> Are there any downsides to using open region so that's why sequence numbers are being passed as parameters ?

I think the only reason why the generated code does this is for the extremely small performance gain of not having to call `OpenRegion` and `CloseRegion` (which are super cheap, but a method call still uses some instructions). We only bother with such a minor optimization because it's generated code and therefore no humans have to use up their brain cycles writing it.

If you're writing your own code, I would definitely not try to recreate this tiny optimization unless you are in some surprising case where it somehow makes a noticeable difference.
