### ISSUE TITLE
Web Hosting bundle exits with return code 232

### ISSUE THREAD

**Issue by ShaikhMohdRafique** [dotnet/aspnetcore#42988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am installing the dotnet-hosting bundle on servers, using the chef cookbook to silently install it. The installer exits with return code 232 and causing the installation to fail. The cookbook expects return types 0, 42, and 127 as success exit codes (These are default values). If looked in server only .NETCore runtime is installed and it skipped the installation of AspNetCore. On re-running the installation the exit code is 0 as it was already run once. If I manually run the same installer and repair, it installs the skipped AspNetCore runtime.

Dotnet-hosting: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.5-windows-hosting-bundle-installer  
.NET version: 6.0.5 (using an older version as 6.0.7 has parsing error).

In the local and in test servers the installation runs fine.

I have looked at all places to understand all the return codes the executables return. Can you please point me to the correct location?

Another suggestion I read so far is to stop the IIS before installing it and then start the IIS after. Can you please validate?
 

### Expected Behavior

The dotnet-hosting bundle should install both AspNetCore and .NETCore

### Steps To Reproduce

Not sure if this can be reproduced on all servers, I received only live servers.

### .NET Version

6.0.5

**Comment by adityamandaleeka** [comment]
@wtgodbe @joeloff Is installing on a live server this way supposed to work?

**Comment by joeloff** [comment]
Those exit codes are not standard Windows success codes. Standard success exit codes on Windows for installers are 0, 3010 (Reboot required) and 1641 (Reboot initiated). There is no [error code 42](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) defined and 127 on Windows means `ERROR_PROC_NOT_FOUND` - I'm guessing these are from Chef. Assuming the 232 is not something that's being remapped by your deployment software, that seems like a pipe error. I have seen A/V software close named pipes before during installs. If this is caused by A/V software your best bet usually is to reach out to the provider so that they can update their signatures or see whether they have some sort of exclusion list.

The engine will usually map its return values to HRESULT values, for example, if a downgrade is detected you will return `0x80070666` (which comes from error code 1638 (0x666))

You would need to restart IIS if it is actively using the ANCM module or you have an application pool that's using any of the runtime files being updated. Ultimately, the decision is deferred to the Windows Restart Manager that may decide to stop processes and potentially restart them.

Can you provide the install logs?

**Comment by adityamandaleeka** [comment]
@ShaikhMohdRafique Our normal suggestion for something like this, given that we don't promise zero-downtime upgrades on live servers, would be to do something like load balance to another server while the upgrade is being performed.

**Comment by ShaikhMohdRafique** [comment]
Thank you @adityamandaleeka for the suggestion. Yes, Our servers are load balanced and we did a rolling deployment to avoid the outage.
