### ISSUE TITLE
[Blazor] Setting options for event handlers

### ISSUE THREAD

**Issue by msynk** [dotnet/aspnetcore#43014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to set the `options` for an event handler (such as capture, once, passive) as described here:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

but currently, no feature is available in Blazor to allow me to achieve it. the only solution, for now, is to fall back to javascript, which is not suitable for every scenario.

### Describe the solution you'd like

I think providing other directives like preventDefault/stopPropagation for this request would be awesome, for example:

```razor
<input @onkeypress:capture:once />
```

**Comment by ysmoradi** [comment]
+1

**Comment by javiercn** [comment]
@msynk thanks for contacting us.

Blazor uses event delegation so this is something that is not possible, since it would affect all the events. We don't have plans at the moment to change the way Blazor handles events as that has big implications. We might reconsider this in the future if that changes.
