### ISSUE TITLE
JwtBearerHandler logs are uninformative

### ISSUE THREAD

**Issue by blastrock** [dotnet/aspnetcore#43066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `AddAuthentication` and `AddJwtBearer`, even when setting `options.IncludeErrorDetails = true`, the logs lacks all the details necessary to debug the issue.

For example, if the JWT issuer host is down and its `.well-known` can't be accessed, the error looks like

```
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: Failed to validate the token.

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
```

And all other kinds of errors look like this, with these placeholders types instead of the values, this makes it very hard to understand what is the problem and debug client (or server) code.

### Expected Behavior

The error should contain the actual values instead of placeholders like `System.String` etc.

Moreover, for this particular example, the framework should explain why it couldn't match the key from the JWT. I expect to see something like `Connection refused` somewhere.

### .NET Version

6.0.302

**Comment by khellang** [comment]
Versions of Microsoft.IdentityModel.Logging before v6.15.0 [only logged the type name](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/63e430fcc500479291e79f285e0470cf97a1f28f/src/Microsoft.IdentityModel.Logging/LogHelper.cs#L353) if the argumentwasn't marked as "non-PII" in order to not accidentally log PII.

Newer versions (v6.15.0 and up) [should format the arguments using a special PII string](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/81d938c51f7df5d85b9fdcac830bb57e632552db/src/Microsoft.IdentityModel.Logging/LogHelper.cs#L374) to make this clearer:

> [PII of type '{0}' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]

**Comment by blastrock** [comment]
Thanks a lot, `ShowPII` is exactly what I needed!

I am using IdentityModel 6.10.0 so I didn't get the new formatting. Anyway, users of the new version shouldn't have this problem with that message, I'm closing this.
