### ISSUE TITLE
Custom ModelBinder and complex objects deserialization

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/aspnetcore#43095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Trying to use the official [custom **ModelBinder** solution](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0#polymorphic-model-binding) I am able to correctly deserialize polymorphic objects but not complex objects. That is, polymorphic objects containing collection of other, even non-polymorphic objects do not get deserialized properly. Deserialized vehicle in my example (attached) is missing `RepairHistory` records in the `Create()` method.  

I am not certain if this a know limitation, a bug or, perhaps, just more code to handle complex objects is needed.  
If the root problem is specified ModelBinder gets applied not only to the parent object but to child objects as well, then I believe it is a bug.

```C#
public abstract class Vehicle
{
    public abstract string Kind { get; set; }
    public string Make { get; set; }
    public RepairRecord[]? RepairHistory { get; set; }
    // public RepairRecord RepairRecord { get; set; }
}
public class Car : Vehicle
{
    public override string Kind { get; set; } = nameof(Car);
    public int CylinderCount { get; set; }
}
public class Bicycle : Vehicle
{
    public override string Kind { get; set; } = nameof(Bicycle);
    public bool HasStand { get; set; }
}
public class RepairRecord
{
    public DateTime DateTime { get; set; }
    public string Description { get; set; }
}
[HttpPut]
public IActionResult Create([ModelBinder(typeof(VehicleModelBinder))] Vehicle vehicle)
{
    return new OkResult();
}
```
Complete solution: [TestWebAPI.zip](https://github.com/dotnet/aspnetcore/files/9267523/TestWebAPI.zip)

### Describe the solution you'd like

`IModelBinder`/`IModelBinderProvider` architecture seems to be too difficult to use. Instead, I suggest approach much easier to apply: `ModelBinderAttibute` accepting object exposing simple `IJsonTypeSelector` interface, e.g. defined as below.
```C#
public interface IJsonTypeSelector
{
    public Type SelectType(JsonDocument document);    
}
```
### Additional context

The problem is described [here](https://stackoverflow.com/questions/73238046/json-deserialization-of-polymorphic-and-complex-objects-in-asp-net-core-without) as well.

**Comment by rafikiassumani-msft** [comment]
@tdjastrzebski Can you provide a payload example to help us investigate this issue?

**Comment by tdjastrzebski** [comment]
Two sample payloads tested below - depending on `Vehicle` class version - see [TestWebAPI.zip](https://github.com/dotnet/aspnetcore/files/9261244/TestWebAPI.zip)
In both cases `RepairRecord` object (simple property or an array) does not get deserialized.
```JSON
{
    "kind": "Car",
    "make": "Honda",
    "cylinderCount": 4,
    "repairHistory": [
        {
            "dateTime": "2022-08-04T23:38:17.848Z",
            "description": "engine check"
        }
    ]
}
```
```JSON
{
    "kind": "Car",
    "make": "Honda",
    "cylinderCount": 4,
    "repairRecord": {
        "dateTime": "2022-08-04T23:45:35.193Z",
        "description": "engine check"
    }
}
```

**Comment by brunolins16** [comment]
@tdjastrzebski Thanks for contacting us.

I am checking your app and problaby you are already aware of this but the custom `ModelBinder` example uses the `ValueProvider` (in your case `Route` or `QueryString` ) to obtain your `Vehicle.Kind` value and because you are creating the derived types without a `BindingInfo` it will use the `ComplexObjectModelBinder` that will bind your model using the `ValueProviderst` as well. 

It is not a problem at all, but I would like to make sure that you know that the `json` example that you share is not used, since your app is expecting a query string.

If you send a request with the following query string it will bind correctly: 

`?kind=Car&make=Honda&cylinderCount=4&repairHistory[0].dateTime=2022-08-04T23:38:17.848Z&repairHistory[0].description=engine`

You are probably using the `json` payload shared in Swagger UI, that creates a wrong query string:

`?kind=Car&make=Honda&cylinderCount=4&repairHistory[dateTime]=2022-08-04T23:38:17.848Z&repairHistory[description]=engine`

The correct syntax is described here: [Model Binding in ASP.NET Core - Collections](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=main&view=aspnetcore-6.0#collections-1)

**Comment by brunolins16** [comment]
If you want to read the content from body, you can try change your `ModelBinderProvider` to include a `BindingInfo` when you call the `CreateBinder` method.

```csharp
var bindingInfo = BindingInfo.GetBindingInfo(new[] { new FromBodyAttribute() }, modelMetadata );
binders[type] = (modelMetadata, context.CreateBinder(modelMetadata, bindingInfo));
```



With that, you will still have the `Kind` querystring but all the other information will be bound from the body.

**Comment by tdjastrzebski** [comment]
@brunolins16, thanks for your response. What I understand is that there is an unfortunate coincidence of two things going on here:
1. [Polymorphic model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0#polymorphic-model-binding) changes the default `FromBody` binding to `FromQuery` binding.
1. Swagger does not correctly convert complex object json to a query string.

Is that correct? I have tried modifying the [polymorphic model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0#polymorphic-model-binding) the way the whole payload (including `Kind` property) is accepted as a body but I was not successful. Is it actually possible?

**Comment by brunolins16** [comment]
@tdjastrzebski 

> Swagger does not correctly convert complex object json to a query string.

Exactly

> [Polymorphic model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0#polymorphic-model-binding) changes the default FromBody binding to FromQuery binding.

Not exactly, the `ModelBinderAttribute` sets the `BindingSource` to `Custom` and the Swashbuckle will render it as `Query`. In your case, since you have a `IModelBinderProvider` you don't need to specify the attribute and in this case, it will infer `FromBody`. 

![image](https://user-images.githubusercontent.com/12376385/183978342-df2da87d-c4f8-4aa2-9c13-be011a8656cb.png)

So, at least you will have it FromBody in swagger UI but you will miss the `Kind` parameter, but you can fix it adding it your your controller action route or a querystring, eg.: [HttpPut("{kind}")]

**Comment by brunolins16** [comment]
> Is that correct? I have tried modifying the [polymorphic model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0#polymorphic-model-binding) the way the whole payload (including Kind property) is accepted as a body but I was not successful. Is it actually possible?

I tried locally with your sample app, the changes I mentioned above and adding to the VehicleModelBinderProvider.cs (line 18):

`var bindingInfo = BindingInfo.GetBindingInfo(new[] { new FromBodyAttribute() }, modelMetadata );`

**Comment by tdjastrzebski** [comment]
@brunolins16 Thanks four your help and advice although I cannot get it working.  
Entire payload should be sent as a body.  
Is there any known and easy solution to fix Swagger's incorrect assumptions? I mean, to tell it Custom means `FromBody`, not `FromQuery`?  
After applying the fix you described all I get is response 400 - bad request.
```JSON
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-531b3701c6a4ca8dbb38a3cb37bcf9a5-1ae2c81ecb5c9b00-00",
    "errors": {
        "vehicle": [
            "The vehicle field is required."
        ]
    }
}
```

**Comment by tdjastrzebski** [comment]
@brunolins16 please reopen

**Comment by brunolins16** [comment]
@tdjastrzebski Can you share the updated source code? Thanks

**Comment by tdjastrzebski** [comment]
Updated code attached.
[TestWebAPI-2.zip](https://github.com/dotnet/aspnetcore/files/9434505/TestWebAPI-2.zip)

**Comment by brunolins16** [comment]
@tdjastrzebski  I just tested your code and you need to:

* Remove the ModelBinder attribute, since your are using the IModelBinderProvider.

``` diff
-public async Task<ActionResult> Create([ModelBinder(typeof(VehicleModelBinder))] Vehicle vehicle)
+public async Task<ActionResult> Create(Vehicle vehicle)
```

* Since your binder logic decided which type to bind based on the `Kind` i think make sense if you add the `Kind` route parameter or querystring in your action.

``` diff
-[HttpPost()]
+[HttpPost("{kind}")]
```

* To make the JSON object simpler when submitting the payload, maybe you could include the `JsonIgnore` attribute to the `Kind` property.

``` diff
-    public abstract string Kind { get; set; }
+    [JsonIgnore]
+    public abstract string Kind { get; set; }
```

With these changes you must have what you are looking for:

![image](https://user-images.githubusercontent.com/12376385/186950300-3d3eecef-1082-4423-8e67-2d563c0eec72.png)

**Comment by tdjastrzebski** [comment]
@brunolins16 Thank you but **the entire payload** (must be posted as json document, no extra query params. It is a hard requirement. If non-standard hybrid (body/query) payload is required for this solution to work with complex object, I think someone should revisit the current concept/architecture/implementation since using it already seems more complicated that simply accepting JsonElement as a param and starting custom object creation from there.

**Comment by brunolins16** [comment]
@tdjastrzebski The problem is your custom binder gets the `Kind` to decided which model should be used. If this value is coming from the JSON payload you will need to read the entire payload before serializing, that does not seem to be a good option.

I am not sure if it is an option for you, but .NET 7 introduces [System.Text.Json Polymorphism](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/#polymorphism) that simplifies your scenario. In this case you won't need a custom binder and instead just update your base class to include the `JsonDerivedType`, eg.:

``` c#
[JsonDerivedType(typeof(Car), nameof(Car))]
[JsonDerivedType(typeof(Bicycle), nameof(Bicycle))]
public abstract class Vehicle {}
```

With this you can achieve what you are looking for, adding the discriminator to the JSON payload eg.: ` "$type" : "Car"`

**Comment by brunolins16** [comment]
> Do I correctly understand that use of `[ModelBinder]` attribute and `IModelBinderProvider` is mutually exclusive?
> Declarative fashion (`ModelBinder`) is more preferred.

Short answer: YES.
Long answer: The `ModelBinderAttribute` is evaluated by `BinderTypeModelBinderProvider` that will create an instead of `BinderTypeModelBinder` that will call the `binder` provided. This provider is the first one registered by default, however, usually when registering a custom `IModelBinderProvider` we insert it at the index `0`, in order to have it executed first avoiding any built-in binder provider. That means, once you call `options.ModelBinderProviders.Insert(0, new VehicleModelBinderProvider());` the original `BinderTypeModelBinderProvider` will not be executed for your specific request since the `VehicleModelBinderProvider` will be able to provide a `binder` already making it useless in this case. 

However, the `ModelBinderAttribute` also affects the OpenAPI metadata, since when it is present it will be always set as `Custom` source.

**Comment by brunolins16** [comment]
> I am not sure if it is an option for you, but .NET 7 introduces [System.Text.Json Polymorphism](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/#polymorphism) that simplifies your scenario. In this case you won't need a custom binder and instead just update your base class to include the `JsonDerivedType`, eg.:

Another option is a custom JSON Converter as described here: [Support polymorphic deserialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0#support-polymorphic-deserialization)

**Comment by tdjastrzebski** [comment]
> If this value is coming from the JSON payload you will need to read the entire payload before serializing, that does not seem to be a good option.

That's right, but only if top performance, rather than code readability/maintainability is your priority.  
Thanks, for now I use `JsonElement` param and will look into `[JsonDerivedType]` when .Net 7 is GA.
