### ISSUE TITLE
[Blazor Server] Warn developer if the <base/> tag is missing from the root layout

### ISSUE THREAD

**Issue by SparkyTD** [dotnet/aspnetcore#43146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I just wasted an entire day's worth of productivity trying to fix an obscure bug relating to Blazor's SPA navigator. I got to learn the hard way that specifying `<base href="~/"/>` in the root layout's `<head>` section is absolutely crucial for SPA to work as intended. Omitting this tag will cause navigation links in lower-level routes to break completely as SPA navigators, and act as regular anchor tags instead, causing a full page refresh when the user clicks on them.

For example, navigation between root-level pages (e..g `/Index`, `/Counter`, etc...) still works fine without the `<base/>` tag, but nav links pointing from lower-level pages (more than one '/' in the path, e.g. `/Users/View`) to higher level pages will not work as intended, causing the behavior described above.

### Describe the solution you'd like

Since the presence of this tag is mandatory in order for SPA to work as intended, and there is pretty much no use case (that I can think of) where one would intentionally omit it from the layout, it would be incredibly useful if the Blazor Framework would generate some sort of error/warning log message in the server's console, in case this tag is not present during page render.

### Additional context

This issue can happen in two cases: When a user is just starting out with Blazor, and doesn't yet know about this requirement; or when using a custom HTML template not originally made for Blazor, that doesn't have the tag by default. In my case, it was the combination of both, and I paid the price.

This was an incredibly hard bug to find, especially with no prior experience with Blazor, and the suggested warning message might save the next developer from falling into the same trap.

**Comment by javiercn** [comment]
@SparkyTD thanks for contacting us.

Unfortunately, this is highly contextual, and scenario based, so we can't realistically produce a warning because doing so would require us at the very least to scan every document on every request, which we do not plan to do.

This is in the end standard browser/web behavior which is behavior we don't plan to replicate on the server. We document this requirement https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path and I believe NavigationManager will produce a visible error in the console under some circumstances.
