### ISSUE TITLE
Severe blazor server memory leak

### ISSUE THREAD

**Issue by m4rt1nd** [dotnet/aspnetcore#43221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor server constantly allocates memory on every page refresh and does not return it. Garbage collection does not reduce memory usage at all as if there was a severe memory leak.

### Expected Behavior

My Blazor server app should not balloon up to using 50GB of RAM within a few days of internal use. Garbage collection should keep it down to a manageable number.

### Steps To Reproduce

1. Create a brand new template Blazor Server Project and run it
2. Refresh any page several times
3. Watch in the Diagnostic Tools tab that opens as the Process Memory continually goes up without coming down, even if a garbage collector comes through
![image](https://user-images.githubusercontent.com/107061667/184237997-bdc1143c-91d4-4b07-a2b3-721770d9e9ff.png)

In this case, each refresh nets about .5MB, but on my own project, this issue causes each refresh to increase the amount of allocated memory by up to 200MB.

### Exceptions (if any)

None, other than an out of memory exception when my computer invariably runs out of memory

### .NET Version

6.0

**Comment by TanayParikh** [comment]
Hello @m4rt1nd, thanks for contacting us. 

When running inside Visual Studio, potentially with the debugger attached, and/or using a debug build, the GC behaves differently. Consequently, these results are likely not representative of how Blazor behaves in a production environment. 

If you want to capture an accurate trace of your program we suggest you follow some of the guidance provided [here](https://docs.microsoft.com/aspnet/core/performance/memory) to accurately measure the memory usage in your app.

**Comment by davidfowl** [comment]
> My Blazor server app should not balloon up to using 50GB of RAM within a few days of internal use. Garbage collection should keep it down to a manageable number.

Does it ballon to 50GB of RAM? What have you seen in practice?

> None, other than an out of memory exception when my computer invariably runs out of memory

Have you observed this? Have you collected a memory dump of a problematic application? (one that you deem using too much memory?)

How many concurrent users does this application typically have or how many does it have when you observe these problems?

**Comment by javiercn** [comment]
@m4rt1nd thanks for contacting us.

Blazor server creates a new circuit per user session. Each user session corresponds to a single document being rendered in the browser, for example, multiple tabs create multiple sessions.

Blazor server maintains a constant connection to the browser that initiated the session (circuit from now on). When the connection is lost for some reason (user loses network connectivity, or abruptly closes the browser), Blazor has a recovery mechanism that places a limited number of circuits in a "disconnected" pool, giving clients a limited amount of time (by default 3 minutes) to reconnect and re-establish the session.

After that time, Blazor will release the circuit and discard the session. From that point on, the circuit is eligible to be garbage collected and it will be claimed when a collection for the generation it is in, is triggered. One important aspect to understand is that circuits have a long lifetime, which means that most of the objects rooted by the circuit will reach Gen 2, and as a result, you might not see those objects being released until a Gen 2 collection happens.

## Understanding how to measure memory usage in general

There are a few prerequisites that we need to understand:
* The app needs to be set to Release. Debug measurements are not relevant as the generated code is not representative of the code that will be used in production.
* The app needs to run without a debugger attached (Run without debugging or CTRL+F5) as this might also affect the behavior of the app and spoil the results.
* You need to understand the different types of memory to understand how much memory it is actually in use by .NET. Generally people look at the Task manager, which typically offers an upper bound of the actual memory in use. There are several helpful articles about this:
  * https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md
    * Specially interesting is the section on [memory fundamentals](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#Memory-Fundamentals)
  * https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-0/
  * https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-1/
  * https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-2/

## Memory usage applied to Blazor

We compute the memory used by blazor as follows:
* Active circuits * PerCircuitMemory + DisconnectedCircuits * PerCircuitMemory

The ammount of memory a circuit uses is largely dependent on how the app is written, and it is an app concern. The number is the number of concurrent clients that have an active session, so you can think of MaxMemory / PerCircuitMemory = MaxActiveCircuits.

For a memory leak to happen in Blazor, the following things need to be true:
* The memory must be allocated by the framework, not the app (if you allocate a 1GB array in your app, it is your apps problem).
* The memory must not be actively being used (if you have MaxActiveCircuits running, it is a scale issue, not a memory leak) which means the circuit is not active and has been evicted from the disconnected circuits cache.
* A garbage collection for the generation the circuit is in has run but has not been able to claim the circuit.
  * And the reason it has not been able to is because another object in the framework is holding a strong reference to it.

In any other cases, there is no memory leak. If the circuit is active (connected or disconnected) is still in use.
If a GC for the generation the circuit is in does not run, the memory won't be released (the GC does not need it).
If a GC for that generation runs and frees the circuit, you need to validate the memory against the GC stats, not the process, as .NET might decide to keep the virtual memory around.
If the memory is not freed, you need to find a circuit that is not either active or disconnected and that is being rooted by another object in the framework. In any other case, it is an app issue.

## Things that you can do to reduce memory usage
* Reduce the number of disconnected circuits.
* Reduce the time a circuit is allowed to be in the disconnected state.
* Trigger a GC manually to perform a collection on downtime periods.
* Configure the GC in workstation mode instead of server (this will more aggressively collect).

**Comment by m4rt1nd** [comment]
Yes, I have seen it use 50GB in task manager and had to restart the server. The circuits are not being garbage collected at any time. I'm not sure if it actually reached an Out of Memory exception, but it did use up all the memory on the machine and become unresponsive as a result. But I have other servers on this machine that may need to use that memory before it is completely maxed out. How can I force the circuits to be garbage collected before it maxes out my machine?

**Comment by javiercn** [comment]
@m4rt1nd you can trigger a collection manually using `GC.Collect` you'll have to check the options

**Comment by javiercn** [comment]
@m4rt1nd if you had an OutOfMemory exception your app would have crashed. Very likely the fact that you have other apps running on the host has an impact. 

I would suggest that you capture an event trace to get more details when you are in that situation, but likely what might be happening is that there are frequent GCs (0) and maybe (1) happening when the machine becomes irresponsive due to the memory usage but for some reason GC (2)s are not being triggered (which is what you would need).

With that in mind, you can force a GC yourself with `GC.Collect(2, force: true)` but keep in mind that this will block the runtime while it is happening, so I recommend caution on when you do it. (Maybe do it at night when you don't have users).

**Comment by m4rt1nd** [comment]
it seems like calling GC.Collect(2) only works minimally; I need to call it several times for it to meaningfully reduce the amount of allocated memory, which seems very strange to me.
It is also still a little concerning that this does not happen with the garbage collector automatically. Is there a way to manage this, a setting for example, that is recommended in production? Setting a maximum memory allocation, for instance?
Also, what sort of data is stored in circuits that they hold this much memory?? I'm able to bring my application up to 5GB of allocated memory in the first 60 seconds of loading and reloading pages

**Comment by javiercn** [comment]
@m4rt1nd You would need to capture a memory dump and analyze the memory to see where the allocations are happening.

I do not know how you are calling GC.Collect, if you load a bunch of pages and call it right away, the circuits are going to be disconnected.

Here are the docs with the [GC settings](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector)

**Comment by vgb1993** [comment]
Memory consumption is my only real concern with Blazor server. 

I did some tests with Telerik components and I was able to see cirquits get closed and memory decreased.

@m4rt1nd could you please tell us what component library / vendor / features are you using in your app? 

Do you have features of your own that implement IDisposable?

How many connections do you manage?

**Comment by davidfowl** [comment]
You’re saying the blazor sever application has a 50GB working set? What are these machine specs?

**Comment by javiercn** [comment]
@vgb1993 if you want some concrete data on Blazor server scalability, it is a bit out of date, but you can check https://devblogs.microsoft.com/dotnet/blazor-server-in-net-core-3-0-scenarios-and-performance/#using-blazor-server-at-scale

**Comment by m4rt1nd** [comment]
@vgb1993 the main component library I'm using is Radzen and a few very small custom components. None implement IDisposable, I do not see how they would. The site probably has around 10 concurrent connections at any given time. 
@davidfowl the server the website runs on has 84GB of RAM
@javiercn the circuit settings do not seem to change the memory issue and I cannot find where in a standard blazor server application you would specify the GC settings, could you elaborate on that?

**Comment by davidfowl** [comment]
@m4rt1nd are you running on IIS? How many cores do you have on this server?

**Comment by m4rt1nd** [comment]
it is running on IIS, 10 cores

**Comment by davidfowl** [comment]
Do you know how long the 50GB process was running? IIS restarts the app pool recycles ever 29 hours. So an occasional 10 concurrent users and 50GB doesn't add up. A memory dump or a gc trace that collect allocations might give more insight into what the "leak" might be.

**Comment by m4rt1nd** [comment]
I'm not sure how long it was running, but I know about 24 hours earlier it was at 34GB. This doesn't seem too crazy to me, as I'm able to get it to 10GB in a few minutes just running it locally jumping between pages. What is the best tool to investigate a memory dump? I tried running it in Visual Studio but wasn't able to glean very much.

**Comment by TanayParikh** [comment]
> I'm able to get it to 10GB in a few minutes just running it locally jumping between pages

Just to confirm, are you running it in `Release` mode, without a debugger attached?

**Comment by m4rt1nd** [comment]
yes, ran it with CTRL+F5 and it still gained allocated memory at the same speed as I tracked the exe through task manager

**Comment by TanayParikh** [comment]
> with CTRL+F5

That launches without the debugger attached, however, by default that's still in `Debug` mode. You'll also have to change the launch configuration to `Release` mode if you haven't already.

**Comment by vgb1993** [comment]
> @vgb1993 if you want some concrete data on Blazor server scalability, it is a bit out of date, but you can check https://devblogs.microsoft.com/dotnet/blazor-server-in-net-core-3-0-scenarios-and-performance/#using-blazor-server-at-scale

Yes I was aware of those metrics, but as the article says:

> That will depend in large part on how much additional memory your app requires per user

So I decided to run my own tests with Telerik components to see memory consumption and concluded it is suitable for our use case. Never the less, it's something we will have to keep monitoring very rigorously with our clients. 

My test was 50 tabs open with a page containing a grid, with a dbContext. Then I closed some tabs and 30min later the memory decreased (when GC triggered). This is not a production test, but it allowed me to see how much memory a single cirquit was consuming, and also the proper release of this memory.
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/10832876/184457408-a462fb2d-92ed-4354-9cff-b8f457c8da3e.png)

So I agree with @davidfowl something doesen't add up.

I would suggest looking at the dump and also search for some IDisposable not beeing disposed, like a dbContext or so.
 
Hope you can find the cause.

**Comment by davidfowl** [comment]
This is something you should be able to do on your server where the problem happens https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#how-to-collect-top-level-gc-metrics.

**Comment by m4rt1nd** [comment]
@TanayParikh I have set the configuration in Build > Configuration Manager to "Release" and ran it through the performance profiler tracking memory usage, and there was no change in memory usage.

**Comment by TanayParikh** [comment]
Please try David's suggestion above.

**Comment by TanayParikh** [comment]
To confirm, were you able to collect the top level GC metrics per David's suggestion above?

**Comment by m4rt1nd** [comment]
I'm not sure how to use the perfview command, when I put it into the Command Window in visual studio while my application is running, it just says command not valid. Where should I be running this?

**Comment by javiercn** [comment]
@m4rt1nd perfview is a standalone tool that you can get from [microsoft/perfview](https://github.com/microsoft/perfview):

The documentation that I referenced above goes into detail on how to use it to troubleshoot problems:

https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md
Specially interesting is the section on [memory fundamentals](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#Memory-Fundamentals)
https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-0/
https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-1/
https://devblogs.microsoft.com/dotnet/work-flow-of-diagnosing-memory-performance-issues-part-2/

**Comment by m4rt1nd** [comment]
okay, I've collected the top level GC metrics with perfview, but I'm not sure what the information I've gathered means. It seems like virtual memory usage is the issue and garbage collection did not significantly reduce that number, but I'm not quite sure. What should I be looking at?

**Comment by davidfowl** [comment]
Did you collect a profile from your production machine where the problems shows up?

**Comment by m4rt1nd** [comment]
Yes, I've collected top level GC stats on my production machine and I'm not gleaning anything from it other than the virtual memory being used by this process is far too high

**Comment by javiercn** [comment]
@m4rt1nd thanks for the additional details.

You'll have to capture a memory dump and look at the heap and try and identify 2 things:
* Whether you have one or more object graphs that are consuming much memory.
* Whether you have allocated a huge number of instances of a given type.

**Comment by m4rt1nd** [comment]
there are hundreds of instances of RenderTree.RenderTreeFrame[], System.Byte[], and System.String[] in the range of 1-10MB, and about a dozen RenderTree.RenderTreeEdit[] at 1.5MB. There is nothing else in the Large Object Heap larger than 1MB, it is exclusively these four array types. What is a good way to determine where they came from?
Looking a bit further into it, it looks like Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[] is the cause of about 50% of the entire memory use. This does not seem right to me.

**Comment by javiercn** [comment]
@m4rt1nd that very likely means that you are generating a large UI (in terms of elements) are you for example rendering long tables of data and similar?

**Comment by m4rt1nd** [comment]
Yes I am, the entire website is just displaying data tables. How can I make this use less memory, or at least collect the unused memory instead of permanently increasing every time I (re)load a page?

**Comment by javiercn** [comment]
@m4rt1nd Use the VirtualizeComponent to limit the amount of data rendered to what is actually visible on the screen https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0

Check https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-6.0 for other performance recommendations.

**Comment by davidfowl** [comment]
@m4rt1nd I'd be interested in looking at the dump and traces you collected. My email is david dot fowler at microsoft.com.

**Comment by m4rt1nd** [comment]
I've sent an email to @davidfowl
I'm working on the virtualization, but so far it doesn't seem to work with the data table component I'm using, it just doesn't display any thing at all

**Comment by TanayParikh** [comment]
@m4rt1nd @davidfowl did you happen to come to a resolution for this issue? Should this be kept open?
