### ISSUE TITLE
Cannot use JSON source generator with (HttpValidation)ProblemDetails

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#43236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the JSON source generator is enabled for the default JSON serializer options and an application uses the `Results.Problem()` or `Results.ValidationProblem()` methods, it is not possible to make the two work together.

If the `HttpValidationProblemDetails` or `ProblemDetails` is not registered with the `JsonSerializerContext`, then an exception is thrown at runtime:

```
NotSupportedException: Metadata for type 'Microsoft.AspNetCore.Mvc.ProblemDetails' was not provided by TypeInfoResolver of type 'ApplicationJsonSerializerContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
```

If a developer attempts to add either type using `[JsonSerializable]`, then the application fails to compile:

```
Project\Repro\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ApplicationJsonSerializerContext.ProblemDetails.g.cs(24,120): error CS0122: 'ProblemDetailsJsonConverter' is inaccessible due to its protection level
```

### Expected Behavior

An application is successfully able to use `Results.Problem()` or `Results.ValidationProblem()` with JSON source generators and Minimal APIs.

### Steps To Reproduce

A full repro project is available at [martincostello/problemdetails-json-source-generator-repro](https://github.com/martincostello/problemdetails-json-source-generator-repro).

To reproduce, clone the project and run `dotnet build`.

### .NET Version

7.0.100-preview.7.22377.5

### Anything else?

I think something somewhere in the JSON source generator has become more strict beginning in .NET 7 preview 7, which is what brought this to my attention.

Previously I think the source generator would just fallback to using runtime serialization so things would "just work" without you needing to add the `[JsonSerializable]` attribute.

It seems like it would be fairly trivial to fix this use case by making [`HttpValidationProblemDetailsJsonConverter`](https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/Shared/ProblemDetails/HttpValidationProblemDetailsJsonConverter.cs#L10) and [`ProblemDetailsJsonConverter`](https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/Shared/ProblemDetails/ProblemDetailsJsonConverter.cs#L11) public instead of internal, but as they're shared source that might cause other complications with multiple public types with the same name and namespace in different assemblies.

**Comment by brunolins16** [comment]
@martincostello I worked with the JSON source generation for problem details when developing the `ProblemDetailsService` and just to let you know that probably you will face another problem when it is fixed  because,  by default,  it will not fallback to reflection-based the `Extensions` property fail to serialize. 

https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L54

Unless if you knowo all types that will be there at runtime and added then to your context. 

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation?pivots=dotnet-6-0#source-generation-support-in-aspnet-core

**Comment by captainsafia** [comment]
> I think something somewhere in the JSON source generator has become more strict beginning in .NET 7 preview 7, which is what brought this to my attention.

Did this issue not occur prior to preview7?

**Comment by martincostello** [comment]
In the context of where it was occurring where I found it, no.

I have a bit of custom code in an example app that's used to generate examples for the OpenAPI docs with Swashbuckle.AspNetCore that was using the default JSON serializer which had a serializer context associated with it. Since updating to preview 7, that started to throw.

To "fix" it, I had to reconfigure the filter to use the copy-constructor to create a separate options and unassociate the context: https://github.com/martincostello/api/pull/808/commits/6d3778553d7fb633288c805a7766024bf641821c

**Comment by BrennanConroy** [comment]
@dotnet/area-system-text-json do you know what might be going on here? Did something change in preview7 to cause this problem when using the source generator?

https://github.com/dotnet/aspnetcore/blob/846f0fd3cc4217582c00da10ad590704288190af/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L69-L70

https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/Shared/ProblemDetails/ProblemDetailsJsonConverter.cs#L11

**Comment by eiriktsarpalis** [comment]
> If the HttpValidationProblemDetails or ProblemDetails is not registered with the JsonSerializerContext, then an exception is thrown at runtime:

This seems related to an intentional breaking change we made in Preview 7. See https://github.com/dotnet/runtime/issues/71714 for more details and a workaround.

> If a developer attempts to add either type using [JsonSerializable], then the application fails to compile:

The error message appears related to a bug fixed recently in https://github.com/dotnet/runtime/issues/71714, cc @krwq.

**Comment by martincostello** [comment]
Thanks for the pointer at the workaround @eiriktsarpalis - I got this back to working how it was in preview 6 with this change: https://github.com/martincostello/api/pull/808/commits/b43a46cb41e970d566d3c15aa37d78f2e37ec12a

**Comment by pinkfloydx33** [comment]
I just struggled through the same exact issue with `ValidationProblemDetails`/`ProblemDetails` for my MVC-based API. I tried adding the types to my `JsonSerializerContext` but couldn't due to the `internal` converters. I eventually came to the same work-around using the `TypeInfoResolver`. but I'm trying to figure out if there's any downside to **not** using `AddContext<>` as that is [what the docs say to use](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation?pivots=dotnet-6-0#source-generation-support-in-aspnet-core).  

I [started a discussion](https://github.com/dotnet/runtime/discussions/74359) over in dotnet/runtime asking about the implications. It would be nice to have a way around this without needing to fallback to the reflection resolver. Though... perhaps it won't be an issue once Problem Details service is in the mix

**Comment by eiriktsarpalis** [comment]
FWIW I should say that adding reflection-based fallback defeats the purpose of using source generators. It seems unfortunate that we need to rely on reflection (accidentally in .NET 6, explicitly starting with .NET 7) to add serialization support for the validation models. It sounds to me like MVC might want to expose a `JsonSerializerContext` for common model types so that users can add them to the mix without relying on reflection:
```C#
builder.Services.ConfigureRouteHandlerJsonOptions((options) =>
{
    options.TypeInfoResolver = JsonTypeInfoResolver.Combine(ApplicationJsonSerializerContext.Default, ValidationContext.Default);
});
```
cc @davidfowl

**Comment by pinkfloydx33** [comment]
Those of us migrating from @khellang's ProblemDetails Middleware will be stuck with the reflection approach, assuming we want to keep our output _as is_. That Middleware [adds a `traceId` extension](https://github.com/khellang/Middleware/blob/2c41d08ca65c2ac62b47e5420f9be083033f430e/src/ProblemDetails/ProblemDetailsOptions.cs#L282-L297) which would immediately disqualify us from source gen and force us into reflection mode anyways. Even with a context exposed for "combining" we'd still be SOL. 

The options would be:
- stop outputting `traceId`
- somehow replace the converter

As the converters are specified as class-level attributes the second option doesn't seem possible. If it were, we'd likely need (or at least _want_) to subclass the current `internal` converters to add our well-known extension data, though the current code path would still exclude source gen due to the extension length check.

It seems like our only options are to either remove the property or be at peace with the fact that we need the reflection fallback just to cover this case. That may be alright, but it could cause other types to slip through the cracks if we accidentally miss annotating them as we'd no longer receive the source-gen errors that we get with the latest previews.

**Comment by khellang** [comment]
Adding the `traceId` extension was merely a mirroring of ASP.NET's default behavior:

https://github.com/dotnet/aspnetcore/blob/f6362e06e8228588fe3d82bd03b7e16a7bd91bf0/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L95-L99

**Comment by pinkfloydx33** [comment]
> Adding the traceId extension was merely a mirroring of ASP.NET's default behavior:

In that case, wouldn't it cause all `ProblemDetails` (or at least those coming from _controllers_) to have the `traceId` extension and thus forced into reflection-mode? I can't tell if the new services are limited to minimal-APIs or apply to MVC as well so perhaps it not a... _problem_.

For what it's worth, the new services uses [`ProblemDetailsDefaults.Apply`](https://github.com/dotnet/aspnetcore/blob/f6362e06e8228588fe3d82bd03b7e16a7bd91bf0/src/Shared/ProblemDetails/ProblemDetailsDefaults.cs#L73) and it looks like minimal API `IResult`-based results use [`HttpResultsHelper.ApplyProblemDetailsDefaults`](https://github.com/dotnet/aspnetcore/blob/f73497c33244ba0a42b084885645ff155541e8af/src/Http/Http.Results/src/HttpResultsHelper.cs#L126) to "set up" the `ProblemDetails`. Neither of these set any of the extensions, so it seems limited to the factory/MVC-based production.

> For my middleware, it's easily excluded by setting GetTraceId and returning null 😄

I don't want to remove it; I'd like to keep it =)

**Comment by khellang** [comment]
Then what hits this code path? 🤔 

https://github.com/dotnet/aspnetcore/blob/f6362e06e8228588fe3d82bd03b7e16a7bd91bf0/src/Mvc/Mvc.Core/src/Infrastructure/DefaultApiProblemDetailsWriter.cs#L54-L70

**Comment by pinkfloydx33** [comment]
> Then what hits this code path? 🤔

Early morning coffee-less code interpreters

**Comment by halter73** [comment]
Triage question: Is there anything we can or should do to help with `(HttpValidation)ProblemDetails` serialization with the source generator in aspnetcore for .NET 7?

> ```cs
> builder.Services.ConfigureRouteHandlerJsonOptions((options) =>
> {
>     options.TypeInfoResolver = JsonTypeInfoResolver.Combine(ApplicationJsonSerializerContext.Default, ValidationContext.Default);
> });
> ```
> 
> cc @davidfowl

Are you suggesting that we add a new public `ValidationContext.Default`? So we have to define our own `IJsonTypeInfoResolver`? How complicated is that? Should we add it by default Does this affect more than just `(HttpValidation)ProblemDetails`?

Would it be okay to just call `ProblemDetailsJsonConverter.Write` directly from our default `ProblemDetailsService`? Would that also fix this source gen issue?

https://github.com/dotnet/aspnetcore/blob/f1353bd0de37a817f9f6acf22451ccd2d5c6a462/src/Shared/ProblemDetails/ProblemDetailsJsonConverter.cs#L43-L48

**Comment by eiriktsarpalis** [comment]
> So we have to define our own IJsonTypeInfoResolver? How complicated is that?

JsonSerializerContext already implements that interface via the source generator, so it really just boils down to defining your own source generated context for the required types.

**Comment by pinkfloydx33** [comment]
> Would that also fix this source gen issue?

The problem (at least in my case) is that I'm using source-gen with my MVC API. By default `HttpValidation/Validation/ProblemDetails` all cause serialization to fail since they've not been defined on the `JsonSerializerContext` I've bound to Mvc's `JsonOptions`.

The work-around is to enable the reflection-fallback but that seems like it defeats the purpose. If aspnet exposed a `JsonSerializerContext` for the `*ProblemDetails` types we can combine *that* with our own context without needing to enable the reflection-fallback mode.

**Comment by davidfowl** [comment]
Are you using source generators for performance reasons?

**Comment by pinkfloydx33** [comment]
Sort of. Prior to source-gen we had custom converters for all of our types after a couple of my colleagues did some extensive profiling and saw enough improvement that it was felt to be warranted. From there we saw minor improvements with fast-path source-gen serialization, not enough to justify it on its own, but the cost of not needing to maintain custom converters is what caused the switch.

Going forward, we are starting to look at getting our apps trimmable. We aren't there yet, but are trying to avoid adding anything new that could bring trimmer warnings.

**Comment by brunolins16** [comment]
> JsonSerializerContext already implements that interface via the source generator, so it really just boils down to defining your own source generated context for the required types.

@eiriktsarpalis So basically, what you are saying is we could make something like this public (probably including `(Http)ValidationProblemDetails` as well), right?

https://github.com/dotnet/aspnetcore/blob/846f0fd3cc4217582c00da10ad590704288190af/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L69-L70

As I mentioned before, the `ProblemDetails.Extensions` is a `Dictionary<string, object?>`, and if I understood correctly, we need to declare all expected runtime types (even very common types like `string`, `int`, etc.) in `JsonSerializerContext` that is very annoying. Is there anything that we can do to avoid it? Also, should some of them be declared in the `ProblemDetailsContext`?

**Comment by eiriktsarpalis** [comment]
> if I understood correctly, we need to declare all expected runtime types (even very common types like string, int, etc.) in JsonSerializerContext that is very annoying. Is there anything that we can do to avoid it?

Unfortunately, no. Relevant issue: https://github.com/dotnet/runtime/issues/58134. Even if we do address it for common primitives, fundamentally the experience won't change: any runtime types will need to be explicitly opted in.

**Comment by brunolins16** [comment]
> Unfortunately, no.

😟 So, since MVC adds the `traceId` we'll probably need to add, at least, `string` to the public context (to make the user experience a little bit smoother).

https://github.com/dotnet/aspnetcore/blob/f6362e06e8228588fe3d82bd03b7e16a7bd91bf0/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L95-L99

**Comment by brunolins16** [comment]
@martincostello https://github.com/dotnet/aspnetcore/issues/44132 is completed and you should be able from .NET 8 Preview 2 source-gen a problemdetails, if needed
