### ISSUE TITLE
Maui App after update Microsoft.AspNetCore.SignalR.Client to 6.0.8 release build crash without error message

### ISSUE THREAD

**Issue by AHComp** [dotnet/aspnetcore#43304]
### Description

I have a simple maui chat app with asp.net core backend.
The android debug version runs very well after update but not the release.
I changed nothing in the code only upgrade from .net 6.0.7 to 6.0.8.
So it's only in release version and i have no idear how i can provide logs or something !

### Reproduction Steps

Nuget update to Microsoft.AspNetCore.SignalR.Client to 6.0.8 
Change back to 6.0.7 and it works

### Expected behavior

Should run also with 6.0.8

### Actual behavior

android Release version crashs after upgrade to 6.0.8

### Configuration

VisualStudio 2022 17.4.0 Preview 1 and 17.3.0 latest same failure.

**Comment by BrennanConroy** [comment]
Nothing changed in SignalR between 6.0.7 and 6.0.8.

You're going to need to provide the error that's occurring if we want to make any progress.

Either try enabling logs in the client https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#net-client-logging or add exception handling and log yourself.

**Comment by AHComp** [comment]
I implement a try

![image](https://user-images.githubusercontent.com/35998144/184723658-2b05f7ac-d708-4330-843e-f89663a06a72.png)

But not reached !!!

**Comment by BrennanConroy** [comment]
@Eilon would you be able to provide guidance on how to debug a release build of a maui app on android?

**Comment by AHComp** [comment]
Sorry you don't understand If I configure the Debugger for the release version the failure gone. So then it works.
It's only in the release version without debugging.
So I need a chance to see the crash log but don't know how.

**Comment by BrennanConroy** [comment]
Looks like Eilon is out, maybe @mattleibow can help?

**Comment by mattleibow** [comment]
Logcat is probably your friend.

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by AHComp** [comment]
No entry in logcat on error

**Comment by brunolins16** [comment]
@AHComp I have been trying to repro this issue and I was not able to repro the 6.0.7 -> 6.0.8 behavior that you mentioned, however a very simple Maui App + SignalR failed (for both versions) when AOT is enabled. In this situation I got the following error message in the logcat:

```
09-26 16:16:39.487 17818 17818 E         : * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:3678, condition `is_ok (error)' not met, function:decode_patch, module 'MauiApp1.dll.so' is unusable (GUID of dependent assembly Microsoft.AspNetCore.SignalR.Client doesn't match (expected 'B6A7FF42-B0A3-4AFE-BE79-CE4D59FF39EF', got '7AE22FDA-D7CF-4D19-8CA9-0EC7D6774940')).
```

Since AOT is **ON** by default for Maui (release mode), have you tried to disable it? If not, can you try to see if it is something related similar to what I got in my repro.

You can disable it adding the following to your project:

```xml
<RunAOTCompilation>false</RunAOTCompilation>
```

**Comment by brunolins16** [comment]
@AHComp I was able to make it work after manually clean (delete the `obj` folder) and rebuild. Looks like some build cache was causing the issue in my scenario. I am not sure what is your scenario, but since you are upgrading the package, it might be something similar.

I have a very simple app where it is working with `6.0.8` (https://github.com/brunolins16/simple-maui-chat)
