### ISSUE TITLE
Blazor Component doesn't re-render after unhandled exception in event handler

### ISSUE THREAD

**Issue by PeterDraex** [dotnet/aspnetcore#43433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following component represent a very very common pattern I use when developing apps with Blazor:
```csharp
@code {
    bool isLoading;

    async Task HandleClick(MouseEventArgs args)
    {
        isLoading = true;

        try
        {
            await Http.GetFromJsonAsync<object>("/api/do-something");
        }
        finally
        {
            isLoading = false;
        }
    }
}

@if(isLoading) {
    <span>Loading ...</span>
} else {
    <button @onclick="HandleClick">Do Something</button>
}
```

The user can trigger a request to the server. While the action is being performed, the user sees a loading indicator. We assume that the request to server goes through well. Adding specific logic to handle the exception is unnecessary. Handling exception the within the component is not desirable. It's sufficient to hide the loading indicator so the user wouldn't keep waiting indefinitely.

The issue is that the code above doesn't actually work in case of an exception. The finally block is executed, but since the exception wasn't handled, the component doesn't re-render. The user can't attempt the action again. The loading indicator is shown indefinitely. A workaround is to call `StateHasChanged()` at the end of the finally block, but that just feels silly.

### Expected Behavior

`StateHasChanged()` is called automatically after handling an event, even in the case of unhandled exception. It can be assumed that the component state has changed and the UI should be updated accordingly.

### .NET Version

6.0.4

### Anything else?

If this behavior is considered a feature and not a bug (I hope not), it should be described in the documentation. The [When to call StateHasChanged](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-5.0#when-to-call-statehaschanged-1) section seems appropriate.

**Comment by TanayParikh** [comment]
I believe this behavior is by design, an unhandled exception, by its nature is unhandled and consequently usually fatal to an application. I recommend reviewing the [Blazor error handling documentation](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0), and in particular [error boundaries](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#error-boundaries) which may allow you to achieve the behavior you desire.

**Comment by PeterDraex** [comment]
Thanks for the link to the documentation. I've read it again, but it doesn't seem to be what I am looking for. The framework currently lets the user decide whether the exception is fatal or not (hence the inobtrusive error bar with options to "Reload" or close the bar). I like this as the default handler of exceptions. If continued use of the app is one of the options, it seems appropriate that the UI should reflect the current state.

**Comment by javiercn** [comment]
@PeterDraex thanks for contacting us.

That's not actually the case. In Blazor Server or Desktop an unhandled exception will terminate the user session or the app respectively.

We do not call `StateHasChanged` automatically when the handler fails because we do not know what state the app is left in or whether doing so will obscure the original cause of the problem.

This is a behavior implemented in ComponentBase, and it is not something that we plan to change. You can implement your own component base class if you choose to do so, but we would recommend you use the ErrorBoundary component to deal with the error or that you call StateHasChanged yourself.
