### ISSUE TITLE
Blazor: get currently focused element

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#43541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there a way to get currently focused element in Blazor ?

### Describe the solution you'd like

So we could do something like this:
```
<input @ref="txtSearch" />
@if (!txtSearch.isFocused()) 
// or
@if(txtSearch != currentFocusElement)
{
    <div>hi</div>
}
```

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

There is no such thing in Blazor, however you can do this with some JS interop by passing an ElementReference to the element and comparing against `document.activeElement`. For example `await JS.InvokeAsync<boo>("hasFocus", txtSearch)` where hasFocus is just `return txtSearch === document.activeElement`

**Comment by omuleanu** [comment]
@javiercn you can, except you have to call this after Render and either handle (show/hide div) it in js or call another render (StateHasChanged)

**Comment by javiercn** [comment]
@omuleanu You can't know during rendering because rendering is synchronous the best you can do is compute the value ahead of time either inside OnAfterRender or within SetParametersAsync or HandleEvent (or any external way in which you might trigger a render for the component)

The alternative can also be to just render both elements and use CSS to display the appropriate element.

**Comment by omuleanu** [comment]
@javiercn In my case I did it with a js func called on `firstRender` in `OnAfterRender`
