### ISSUE TITLE
Continue to support UseProxyToSpaDevelopmentServer

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#43702]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It looks like with .NET 6, the `UseProxyToSpaDevelopmentServer` style of proxying through to a SPA server behind the ASP.NET development server has been deprecated.

### Describe the solution you'd like

I would like to see this method stay actively supported as one option for doing ASP.NET SPA websites.

### Additional context

I'm sure there are some sites out there that were developed with this style of SPA site in mind from the .NET 5 SPA templates, and I personally prefer it to having a Webpack/Vite server in front of the ASP.NET server (how are you meant to host multiple SPA apps inside one ASP.NET site?  That was a major design goal of `UseProxyToSpaDevelopmentServer`).

I also don't understand the description of the new approach in .NET 6 as being "SPA framework-agnostic".  `UseProxyToSpaDevelopmentServer` is also framework-agnostic - it's just proxying data to another server.  There's nothing specific about that to a SPA framework or a particular development web server.

**Comment by Tratcher** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/43662

**Comment by javiercn** [comment]
@jez9999 thanks for contacting us.

Unfortunately, this is not a direction we plan to move on in the future. Proxying to the SPA development server from .NET is a unique approach that we took at the time that makes our integration problematic in several aspects:
* We need to have our own proxy (which currently does not use YARP).
  * This has been the source of many integration issues in the past. (It would still be the case even if we used YARP).
* We have to keep up to date with the evolution of every SPA framework we support.
  * It requires us to validate or do work to catch up on new features developed by the frameworks.
* We have to deal with integration issues that are unique to our approach.
* We have to develop our own approach to support certain scenarios, instead of being able to leverage solutions from the community.
* We have to test against multiple versions of the SPA frameworks we currently support to ensure that our codebase works for all of them. Otherwise, we prevent people from updating their existing apps.

For these and other reasons we switched to use the canonical approach promoted by the SPA frontends. We do not plan to continue investing in our own proxy story for SPA development and instead we will continue focusing on making sure that we integrate with the latest versions of the SPA frameworks available.

You can still use the current .NET proxying approach if that works for you, although we might obsolete it in a future version. If there are bugs with enough interest from customers that are easy to address, we will likely take PRs for them. However, we do not plan to make big changes in this area in the future, add new features to it or update it to react to changes in the SPA frontend development experience.

We understand that this might not match your expectations, however, in our view we believe this enables us to focus on delivering updates templates rather than having to focus on addressing integration issues caused by our unique approach.

Hope this helps clarify our motives.

**Comment by danroth27** [comment]
> It looks like with .NET 6, the UseProxyToSpaDevelopmentServer style of proxying through to a SPA server behind the ASP.NET development server has been deprecated.

Please note that `UseProxyToSpaDevelopmentServer` is part of Microsoft.AspNetCore.SpaServices.Extensions, which is still supported and has not been obsoleted. If at some future point we do decide to obsolete this API we would also provide guidance on how to migrate existing apps to the new model.

**Comment by jez9999** [comment]
@javiercn Most of the issues you list, I suspect, come from the fact that you did indeed try to support specific frameworks.  However, why don't you just continue to support `UseProxyToSpaDevelopmentServer` and tell users that when using this approach, they need to start the SPA development server themselves and configure `UseProxyToSpaDevelopmentServer` to point to the appropriate port?  I get that maintaining stuff like `UseReactDevelopmentServer` requires you to maintain framework-specific stuff so I can understand why you'd drop that, but my suggested approach above is much more generic. 
 The 'technologies' being used here are HTTP and websockets, which seem unlikely to change going forward, so I'm not sure why this approach would cause integration issues.  You need your own proxy, yes, but you already have it and it's frankly not too hard to maintain.

**Comment by javiercn** [comment]
> The 'technologies' being used here are HTTP and websockets, which seem unlikely to change going forward, so I'm not sure why this approach would cause integration issues. You need your own proxy, yes, but you already have it and it's frankly not too hard to maintain.

There are a lot of small tweaks that the dev proxies do to support things like hot reload. The issue is not with HTTP or Websockets, it is with the development features the SPA frameworks offer to support their experiences. We used to have to continuously play catch-up with those as well as dealing with the integration between proxying to the dev proxies.

In many cases, there were problems in the way our proxy interacted with the SPA proxies that were unique to our integration just because there were bugs in the way the proxy handled the requests .NET sent (as the proxy is more tested against the browser). 

Chasing those down is expensive and we do not have the resources to do so. It puts us in a position where we are continuously fighting against those types of issues instead of improving other areas of our support.

If there are concrete things that you don't like about the current approach, we are open to consider improvements to the experience, (I think I recall you mentioning in one case the middleware not being explicit something that you did not like).

Our goal is to focus our energy on improving the templates contents and keeping them consistent with the rest of the JS community approaches to this scenario.

**Comment by jez9999** [comment]
Fair enough.  Yeah, as you mentioned, having an explicit pipeline defined in my site's code would be good to maintain.
