### ISSUE TITLE
Blazor custom elements shouldn't require explicit script reference to BlazorCustomElements.js

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#43710]
It looks like I still have to add an explicit script reference to BlazorCustomElements.js to use Blazor custom elements. But I believe we said we wanted to use a JS initializer to remove this additional manual step.

@MackinnonBuck @javiercn

**Comment by MackinnonBuck** [comment]
We decided to keep it as an external script to not bloat the blazor.*.js files.

cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
> We decided to keep it as an external script to not bloat the blazor.*.js files.

Yes, having it as an external file does sound right to me, but it might be that we can auto-load it using a JS initializer like Dan suggests (so it's not necessary to add any `<script>` tag manually except for the `blazor.*.js` one).

We didn't do that in the original custom elements prototype because I think our JS initializers feature either didn't exist then, or was too new for us to integrate with.

**Comment by javiercn** [comment]
We should do this in .NET 7.0, it should be simple enough and will avoid future breaking changes.

**Comment by MackinnonBuck** [comment]
Fixed in #43809
