### ISSUE TITLE
`FromFormAttribute.Name` not respected by `ApiParameterDescription.Name`

### ISSUE THREAD

**Issue by ascott18** [dotnet/aspnetcore#43815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For a parameter with `[FromForm(Name = "SomeName")]`, the provided Name is not included in the `ApiParameterDescription.Name` produced for that parameter.

### Expected Behavior

I would expect the circled parameters in the screenshot below (for the code in the repro steps) to be named `childItem.Id` and `childItem.Name`, since this is the name they must be (or other valid nested naming scheme like `childItem[Id]`) in the form data POST body in order to be bound.
![image](https://user-images.githubusercontent.com/5017521/189001735-79b5a23b-942a-4d59-a680-42b81a3b725d.png)

### Steps To Reproduce

Look at the ApiDescription for the following action:

``` c#
[Route("test")]
public class MyController : Controller
{
    [HttpPost]
    public virtual IActionResult AddChildItem(
        [FromForm(Name = "id")] int id,
        [FromForm(Name = "childItem")] Item childItem
    )
    {
        return Ok(new
        {
            id,
            ChildId = childItem.Id
        });
    }

    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

### .NET Version

6.0.303

### Anything else?

This is breaking Swashbuckle - I have also reported this at https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2495, because I'm not sure if its intentional and consumers like Swashbuckle are expected to compensate for it themselves, or if it is expected that aspnetcore be the one accounting for this behavior.

**Comment by captainsafia** [comment]
During triage, I had assumed this bug was related to the fact that we were originally not respecting the `Name` property on `FromX` attributes applied to a parameter. After looking at the issue description further, it looks like this is actually related to the way the `ApiParameterDescription.Name` is generated for parameters that have DTOs. In particular, the ApiExplorer is set up to ignore the parameter name to account for scenarios where composite model binding is used:

```csharp
public class Account
{
  public string UserId { get; set; }
  [FromBody]
  public User UserToAdd { get; set; }
}
```

In the case above, the desired goal is to ignore the parameter name/DTO name altogether and use the property names for `ApiParameterDesscription.Name` -- this is what causes the particular bug here.

Now, as mentioned, the dynamics of `FromForm` attributes are a little different so we could probably add some logic to handle the concatenation for form parameters to support constructing the parameter name correctly.

**Comment by captainsafia** [comment]
@ascott18 In the meantime, you can use this workaround to correct the naming using a RequestBodyFilter in SB.

```csharp
builder.Services.AddSwaggerGen(c => {
    c.RequestBodyFilter<FormNameFilter>();
});

...

public class FormNameFilter : IRequestBodyFilter
{
    public void Apply(OpenApiRequestBody body, RequestBodyFilterContext context)
    {
        foreach (var param in context.FormParameterDescriptions)
        {
            if (param.ModelMetadata.PropertyName is not null)
            {
                var props = body.Content["multipart/form-data"].Schema.Properties;
                if (props.ContainsKey(param.Name))
                {
                    var element = props[param.Name];
                    props.Remove(param.Name);
                    props[$"{param.ParameterDescriptor.Name}.{param.Name}"] = element;
                }
            }
            
        }
    }
}
```

**Comment by captainsafia** [comment]
Marking this as answered for now and using the other issue to track a fix in Swashbuckle.

**Comment by ascott18** [comment]
@captainsafia Thanks so much for the investigation and workaround!
