### ISSUE TITLE
Deployments Destroy All Circuits

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#43873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is in regards to issue #30344 where I inquired about a potentially related issue.

I asked here: https://github.com/dotnet/aspnetcore/issues/30344#issuecomment-1196496742

Here: https://github.com/dotnet/aspnetcore/issues/30344#issuecomment-1217809917

And here: https://github.com/dotnet/aspnetcore/issues/30344#issuecomment-1239601065

But did not hear back so creating a new issue here to ensure it is captured.

Problem: Upon deployment of Azure AppService, all circuits are wiped and every connection's state is reset.

### Expected Behavior

When a server is restarted, the connection/circuit session state is preserved and reloaded appropriately, maintaining user state.

### Steps To Reproduce

Deploy a Blazor server-side application to an Azure AppService while an existing/previous version is already deployed and running.

### Anything else?

Thank you for any consideration and/or assistance in addressing this issue. 🙏

**Comment by javiercn** [comment]
@Mike-E-angelo thanks for contacting us.

Apologies if I missed your comment on the other issue. Short answer is yes, our intention is that Pause and resume supports this scenario, with three core ideas:
* The same mechanism used to preserve state during prerendering is used here so you do not have to write special code.
  * This will never be an automatic process as it would imply serializing the process state, which is not something we are going to do. But hopefully, the state you want/need to preserve in a regular session is not that much (typically limited to the page) and you can choose to not store the state, but a "reference" to it that you can use to restore it (for example, instead of storing collections of data you are showing, store the query and reissue it on resumption).
* Libraries can author "providers" for storing the state, so that you can use whatever storage backend (redis, azure, sql, etc) without having to implement it yourself.
* Component libraries can support this on their components so that you do not have to implement anything yourself in your app. (Think for example of a form that automatically preserves its state).
  * In addition to this, we will likely support storing the state in the browser when possible (compressed and data protected) so that there is no need to have a storage backend when dealing with scenarios where the client is connected.
* The app will have mechanisms to trigger the process so that people can build workflows around it.

That said, this is a big work item (hence why we have not tackled yet) but it is something that is on our radar. /cc: @danroth27

**Comment by Mike-E-angelo** [comment]
Works for me, @javiercn!  Thank you for the quick reply here and all your work over there.  My primary intention here is to make sure it's at least known/captured so I can cross it off my list.  Your time and detailed response here is appreciated. 👍
