### ISSUE TITLE
ComponentBase.BuildRenderTree cannot be overriden

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43883]
It seems that a component when compiled, generates code that overrides `BuildRenderTree`. But that override implementation _never calls the base implementation_ so if we derive our component from a some class _we_ create (that derives from `ComponentBase`) overriding `BuildRenderTree` in our created base class, the method is never called.

This is confusing since there are numerous blog posts that talk about deriving from `ComponentBase` and overriding `BuildRenderTree`.

e.g.

[Blazor BuildRenderTree](https://www.webassemblyman.com/blazor/blazorbuildrendertree.html)

[Building Components Manually via RenderTreeBuilder](https://chrissainty.com/building-components-via-rendertreebuilder/)

[Reuse and Customize Components](https://docs.devexpress.com/Blazor/401753/common-concepts/customize-and-reuse-components)

So, is this a bug? I'm doing this in Blazor Server, perhaps it works differently in Blazor WebAssembly? Perhaps it once could be overridden in the past but no longer can be?

**Comment by javiercn** [comment]
@Korporal thanks for contacting us.

No, this is not a bug, it is a by design behavior. Generated code from `.razor` files overrides `BuildRenderTree` and does not call base.

We generally discourage people from using the RenderTreeBuilder APIs directly, as those are meant for compiler generated code and might break in the future.
