### ISSUE TITLE
How to properly destroy javascript component and avoid JSDisconnectedException

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#44180]
My blazor component wraps existing javascript component that needs some javascript cleaning when removed from DOM.

I call `jsObjectRef.InvokeVoidAsync("destroy")` when disposing blazor component, but it throws unhandled exception:

 >     Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

The logs are then bloated with this exception

```csharp
    public class RichTextEditor : InputTextArea, IAsyncDisposable
    {
        ElementReference? _elementRef;
        IJSObjectReference? _jsObjectRef;

        [Inject] IJSRuntime Js { get; set; } = default!;

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                _jsObjectRef = await Js.InvokeAsync<IJSObjectReference>("CKEditorInterop.init", _elementRef;
            }
            await base.OnAfterRenderAsync(firstRender);
        }

        public async ValueTask DisposeAsync()
        {
            if (_jsObjectRef != null)
            {
                await _jsObjectRef.InvokeVoidAsync("destroy"); //this throws JSDisconnectedException when browser is reloaded  or closed or disconnected
                await _jsObjectRef.DisposeAsync();
            }
        }
    }
````

Is it possible to avoid this exception?

---
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27094

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear why do you expect to do manual cleanup after the circuit is being closed?
What you're observing is actually by design - and that exception is valid, as the circuit doesn't exist anymore.
Your code is expected to catch that exception and ignore.

**Comment by Liero** [comment]
@mkArtakMSFT: sorry for not being clear.

> It's not clear why do you expect to do manual cleanup after the circuit is being closed?
I don't. I require cleanup only when my component is disposed and the circuit is open. For example, when use navigates to another page within blazor app.

**Comment by MackinnonBuck** [comment]
Thanks for getting back to us, @Liero.

Is there a problem with the solution we proposed (adding a try/catch)? If so, would you please clarify what that is?

Thanks.

**Comment by Liero** [comment]
@MackinnonBuck 
I've tried the try/catch again and the exception was not logged indeed.

**Comment by guardrex** [comment]
@MackinnonBuck @mkArtakMSFT ... This seems like an edge case, but do you want the approach of catching `JSDisconnectedException` to avoid the logged exception in general coverage?

**Comment by Liero** [comment]
It's not exactly edge case, because in Blazor Server it happens all the time. 

it's basically inevitable on every page with IJSObjectReference  in every user session. Every session must end once, which will cause the exception if there is an IJSObjectReference somewhere.

Please note, that `IJSObjectReference.DisposeAsync();` also throws JSDisconnectedException.

I would ideally want to check, whether the circuit is open or being closed.

**Comment by guardrex** [comment]
I said "seems like" an edge case because so many PU engineers over the years ... including Steve, Pranav, and Ryan ... have provided text and code for interop and disposal scenarios without addressing it. I assume that they intend for devs to generally avoid coding their component disposal that way for the purpose of merely avoiding logging. Besides, anyone can trap anything anywhere for that purpose. We don't generally advise trapping to avoid logging across every conceivable scenario, including this one. I was more concerned about potentially more serious issues (e.g., security, arbitrary component behavior, etc. ... anything that might 💥).

It's up the PU to determine if this rises to the level of providing general guidance on it. We could end up with anything from just a quick remark in the component disposal section of the components *Overview* topic to a full section in the JS interop *Overview* topic ... and even modifications to examples in articles that perform disposal.

**Comment by Liero** [comment]
feedback

**Comment by javiercn** [comment]
The recommendation is to wrap the call in a try..catch. Alternatively, you can implement this without JS interop by using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

**Comment by Liero** [comment]
@javiercn: please note, that `IJSObjectReference.DisposeAsync();` also throws an exception. I guess it must be disponsed on the server too, doesn't it?

**Comment by javiercn** [comment]
@Liero What is happening here is by design.

When the server gets disconnected it can't make JS Interop calls, and that can happen during circuit disposal. You can either account for it in a `try..catch` or you can avoid the call to JS during disposal altogether by setting up an alternative cleanup mechanism directly on the JS side (for example, using the MutationObserver). At that point you would simply not perform a JS call during Dispose on either direction. You would simply perform the cleanup in the MutationObserver callback.

**Comment by Liero** [comment]
@javiercn : Thanks, I believe I understand that. 
But given that I perform JS side cleaning, I still have the `IJSObjectReference` on the server. Should I dispose it (and thus wrap in try...catch, since it call JS), or JS side cleaning is enough?

So for example, in a Blazor Server app a blazor session expires, I can just forget about the IJSObjectReference? It is not documented anywhere

**Comment by guardrex** [comment]
> It is not documented anywhere

It's documented at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-isolation-in-javascript-modules

... and in Steve's Mapbox example at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-libraries-that-render-ui

**Comment by Liero** [comment]
@guardrex: 
1.  The docs doesn't mention JSDisconnectedException at all
2.  The docs does not handle case, when browser is refreshed (circuit disconnected) in Blazor Server app - it throws unhandled exception when disposing - should it be handled or ignored? See my next code sanple
3. I still don't know whether IJSObjectReference should be disposed in Blazor, when I dispose it manually in JavaScript as @javiercn suggested


In the Mapbox sample, the mapModule stays undisposed:

```csharp
    private IJSObjectReference? mapModule;
    private IJSObjectReference? mapInstance;

    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (mapInstance is not null)
        {
            await mapInstance.DisposeAsync(); //this throws JSDisconnectedException
        }

        if (mapModule is not null)
        {
            await mapModule.DisposeAsync(); //this stays undisposed. Is this memory leak on the server?
        }
    }
```

That docs says that we should

 > Dispose the IJSObjectReference for garbage collection in IAsyncDisposable.DisposeAsync.

So, according to the docs, the code above causes memory leak on the server since the IJSObjectReference  won't be garbage collected

**Comment by guardrex** [comment]
I don't think the PU wants further discussion here, @Liero. I'm going to respond on the docs issue. I'll ping u over there.
