### ISSUE TITLE
Blazor Wasm ( Hosted )Template project issue with Authentication

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#44262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor WASM Template with Hosting needs an update.
If you choose Use individual account it cause this add to server program.cs

```csharp
builder.Services.AddAuthentication()
    .AddIdentityServerJwt();
```

This enable the regular way for openid well-known endpoint which conflicts with

```csharp
builder.Services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
```
declared just above.

```csharp
builder.Services.AddAuthentication()
    .AddIdentityServerJwt();
```
needs to be removed to get things working.

### .NET Version

.Net 7 RC1

**Comment by Julien-Marpault** [comment]
@TanayParikh There's the same issue with the .Net 6 version of the template

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear what is the concern here? Is something not working when you go with Individual User accounts option? And if so, what is the error that you're getting?
If you believe this is a real issue with the framework, please share a minimal repro project hosted as a public GitHub repo so that we can investigate this.

**Comment by TanayParikh** [comment]
This issue has been closed because it has been marked as requiring author feedback but has not had any activity for **7 days**. Feel free to comment when you are able to provide the additional information and we will re-investigate.
