### ISSUE TITLE
Dynamic blazor

### ISSUE THREAD

**Issue by thanhnntq** [dotnet/aspnetcore#44375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to render a fragment from a markup string, it's contains event but not work.

```razor

@((MarkupString)content)
@code {
    string content = "<div @onclick=Go>Go Go</div>";
    void Go(){  content = "new content"; StateHasChanged(); }
}
```

Content rendered correct but event didn't work.

### Describe the solution you'd like

Dynamic component to render markupstring with event callback.

**Comment by javiercn** [comment]
@thanhnntq thanks for contacting us.

That won't work. The compiler runs at build time, what you are looking for would require the compiler to run at runtime and it is not something we plan to support.

**Comment by thanhnntq** [comment]
It's very cute future, why not plan to support it? It can make blazor more flexible.

**Comment by javiercn** [comment]
@thanhnntq Running the compiler at runtime and generating the necessary code is an incredibly big effort. We know this because we do it in MVC/Razor pages with the Runtime Compilation feature. We simply do not think that the future is worth the cost and we rather focus our resources in other areas that can benefit more people.
