### ISSUE TITLE
Blazor: Skip the initial validation for dynamically added form content 

### ISSUE THREAD

**Issue by IonutArhire** [dotnet/aspnetcore#44433]
I've been trying to skip the initial validation for dynamically added content but to no avail. 

**The problem**

I have a form model object with a list of children objects. Whenever I add another child in the list during runtime, the child gets validatated even though the child's fields were not even touched by the user. I would like for the newly added child to not be subject to validation right after creation. In other words, I want to skip the initial validation for such children.

**Reproducing the problem (simplified example)**

Index.razor html
```html
<EditForm EditContext="EditContext" OnValidSubmit="@HandleValidSubmit">
        <ObjectGraphDataAnnotationsValidator />

        <div>
            <section>
                <label>
                    Name
                    <InputText @bind-Value="Model.Name" />
                    <ValidationMessage For="() => Model.Name" />
                </label>
            </section>

            @foreach (var item in Model.Items)
            {
                <section>
                    <label>
                        Name
                        <InputText @bind-Value="item.Name" />
                        <ValidationMessage For="() => item.Name" />
                    </label>
                </section>
            }
        </div>

        <section>
            <button @onclick="AddItem">Add Item</button>
            <button type="submit" disabled="@(!IsFormValid)">Create</button>
        </section>
</EditForm>
```
Index.razor code
```csharp

...

protected override void OnInitialized()
{
    EditContext = new(Model);
    EditContext.OnFieldChanged += HandleFieldChanged;
    EditContext.OnValidationRequested += HandleValidationRequested;
    MessageStore = new(EditContext);
}

...

private void AddItem()
{
    Model.Items.Add(new ItemModel());
}
```

Any ideas?

**More info**
- framework: .NET 6
- project type: .NET Maui Blazor

**Comment by danroth27** [comment]
@SteveSandersonMS Thoughts on this?

**Comment by IonutArhire** [comment]
Hi! Any update? Please tell me if more information is needed on my part.

**Comment by IonutArhire** [comment]
I just realized this happened because I was calling Validate in the OnFieldChanged event callback.

I think this issue should be closed.

**Comment by SteveSandersonMS** [comment]
@Nick-Stanton For when you investigate this, I suspect what's going on is that even though the new fields are unmodified, that doesn't stop them from being invalid.

A simpler scenario is if you had a form with a single required field on it - if you leave the whole thing untouched and blank, then as soon as you try to submit the editform, we show that field as invalid because it is (and if it wasn't, it would be unclear why the form submission was not being accepted).

In this case, a validation is being triggered perhaps at the same time as adding a new object? If so, assuming the new object is added before the validation cycle runs, we wouldn't have a way to know not to validate that thing - for one thing, we don't know that it's new. And in any case, the whole form is *not* valid since it's missing a required field. I'm not 100% certain what the sequence of UX interactions is and why it would be possible and sensible to skip validating one thing even though we're validating other things.

**Comment by surayya-MS** [comment]
@IonutArhire , thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.

**Comment by IonutArhire** [comment]
Been away from github and my pet project for quite some time but today I had a look once more.

Turns out the described behaviour was due to my own code where I overwrote a validation lifecycle event.

Sorry for the mistake. This issue can be closed.
