### ISSUE TITLE
Curious what is the drawback of removing the reference of _framework/blazor.server.js from my blazor server project?

### ISSUE THREAD

**Issue by neetutanwar** [dotnet/aspnetcore#44444]
Hi,

I have created a blazer server application, that has a dynamic header dependent on an external JS file (for handling the nav click, change in layout on window resize, capturing the telemetry, etc.), and it has a couple of other pages communicating to an external API for data fetching on "OninitializeAsync" method of Blazor component.

I noticed one thing when I have the _**framework/blazor.server.js** referred to in the _layouts.cshtml then the user experiences it a bit weird, it causes the page to flicker, renders the page twice (even thrice sometimes), and also doesn't trigger the header nav clicks.

But when I remove the **_framework/blazor.server.js** reference, everything works smoothly. 

So I am curious what will happen if I remove this Js reference from the layout? Will it cause any issues?

**Comment by javiercn** [comment]
@neetutanwar thanks for contacting us.

If you remove `_framework/blazor.server.js` from the page, the app will not be interactive.

> I noticed one thing when I have the _framework/blazor.server.js referred to in the _layouts.cshtml then the user experiences it a bit weird, it causes the page to flicker, renders the page twice (even thrice sometimes), and also doesn't trigger the header nav clicks.

This is a result of prerendering. What is happening is that you are prerendering the page on the server (for which we will wait until all the content is loaded) and when blazor loads on the client it will re-render the page "interactively" and at that point it typically does not wait for the content to be loaded to render (to display a loading prompt or similar) and when the content is loaded it re-renders again (with the actual content) which I suspect is the flicker that you are seeing.

We have a feature to preserve the prerendered state so that you can re-render the page synchronously when the app starts interactively and avoid the flicker.

See https://learn.microsoft.com/sk-sk/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-6.0&viewFallbackFrom=aspnetcore-2.2 for details.
