### ISSUE TITLE
[NETE2ESDK]With NET 7.0.0 windows server hosting installed, the hyperlink for "here" on installer UI is 6.0 link not 7.0 link.

### ISSUE THREAD

**Issue by v-jiexu1** [dotnet/aspnetcore#44615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With NET 7.0.0 windows server hosting installed, the hyperlink for "here" on installer UI is 6.0 link not 7.0 link.

### Expected Behavior

The hyperlink for "here" should be 7.0 link.

### Steps To Reproduce

Double-click on NET 7.0.0 dotne-hosting installer .exe on EN OS
On installation UI, Click the link for "here"
Actual Result:
<img width="350" alt="Screenshot 2022-10-18 152634" src="https://user-images.githubusercontent.com/113498399/196364468-60bbc9ee-ed89-4bd2-926c-61a8fbdd76f5.png">
here:https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0

**Comment by dougbu** [comment]
Suggest closing this in favour of #44616. That mentions this problem as well as non-localization of the hyperlinks.

**Comment by dougbu** [comment]
Reopening because the problem now exists in our 6.0.x installers.

@mkArtakMSFT this is another `fwlink` issue I think. The <https://go.microsoft.com/fwlink/?LinkId=798277> URI is used in the 6.0.x and 7.0.x windows hosting installers and should not be. That link currently goes to <https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/?view=aspnetcore-7.0> or <https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-7.0> (see #44613).  Need a new `...?view=aspnetcore-6.0` forwarding link.

**Comment by mkArtakMSFT** [comment]
Here are two new links for you to use:
- 6.0: https://aka.ms/aspnet/6.0/host-and-deploy-with-iis
- 7.0: https://aka.ms/aspnet/7.0/host-and-deploy-with-iis

I know you've asked for just one, I wanted them to look alike.

**Comment by dougbu** [comment]
@mkArtakMSFT could we add another link for 8.0 please❔

**Comment by dougbu** [comment]
- [ ] 2.1.x / release/2.1
- [ ] 6.0.x / release/6.0
- [ ] 7.0.x / release/7.0
- [ ] 8.0.x / main

**Comment by dougbu** [comment]
Verified this fix. I didn't check the latest 2.1.x installer but the 6.0.x, 7.0.x, and 8.0.x ones all go to the correct version-specific pages about IIS.

/cc @wtgodbe @mkArtakMSFT
