### ISSUE TITLE
Blazor Server app display different between F5 and Ctrl+F5

### ISSUE THREAD

**Issue by hjy1210** [dotnet/aspnetcore#44632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Server sample app (https://github.com/hjy1210/BlazorCKEditorMathJax), the display result is different among executing by F5(Debug) and Ctrl+F5.

1. In the Index page, before press the "Typeset" button, the display is:
![before-typeset](https://user-images.githubusercontent.com/7498709/196585307-76e55cb8-e651-4c2c-8fa0-f0e658ed6a30.jpg)
2. In the Index page, after press the "Typeset" button, the display is:
    * In case start app by F5
![after-typeset](https://user-images.githubusercontent.com/7498709/196585522-a1233143-99d0-4296-aa42-faa7024f98b0.jpg)
    * In case start app by Ctrl+F5
![ctrl-F5-after-typeset](https://user-images.githubusercontent.com/7498709/196585664-2c0641dd-ccb5-4f47-9c1f-1c131a2ab776.jpg)

**Why the display result is different among executing by F5(Debug) and Ctrl+F5?** The Ctrl+F5 result is what I exapected.

### Expected Behavior

**I expect the display results are the same among executing by F5(Debug) and Ctrl+F5.**
**The Ctrl+F5 result is what I exapected.**

### Steps To Reproduce

https://github.com/hjy1210/BlazorCKEditorMathJax

### .NET Version

.net 6.0.401

### Anything else?

Microsoft Visual Studio Community 2022(64 bit) Version 17.3.4
ASP.NET and Web Tools - 17.3.376.3011

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What is the behavior when you run the app from command line?

**Comment by hjy1210** [comment]
@ mkArtakMSFT
If execute from command line with "dotnet run", after press "Typeset" button the result is(the same as Ctrl+F5):
![dotnet-after-typeset](https://user-images.githubusercontent.com/7498709/197149051-dc7f8e70-0809-45fa-b11a-cbcf7c7673aa.jpg)

I guess this is a race issue: Both MathJax and Blazor manipulate the DOM, how to let MathJax manipulate last?

**Comment by SteveSandersonMS** [comment]
@hjy1210 My guess is you're using MathJax to mutate the DOM directly, even when Blazor is trying to render it. This is explicitly not supported and can lead to arbitrary errors.

There is a supported way to use external JS logic to render UI within your Blazor-rendered UI, documented at https://learn.microsoft.com/en-gb/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-libraries-that-render-ui. I recommend you follow that approach, i.e., make JS interop calls to instruct MathJax to render UI into specific empty elements, rather than letting MathJax mutate arbitrary parts of the page.
