### ISSUE TITLE
.NET6 Blazor Server - using 'ProcessStartInfo.UseShellExecute = false' forces UI Component to Reinitialize?

### ISSUE THREAD

**Issue by faciendum** [dotnet/aspnetcore#44658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi community,

I have noticed a behavior and I am puzzled about it. 
In a Blazor server application, when calling a process via ProcessStartInfo, setting the UseShellExecute property to false, the entire Blazor environment is reloaded. (Protected override void OnInitialized() on the components is called again). In my case, this has the disadvantage that UI elements like modal views disappear because of the reload. 

Regardless of whether the call is in a background task or not.
I am unsure if this is supposed to be a bug or normal behavior. 

### Expected Behavior

Starting applications via ProcessStartInfo in the background should not cause Razor UI elements to be reinitialized.

### Steps To Reproduce

- Create a normal Blazor Server sample project
- Write a small method where an application is opened, e.g. Notepad:
```
ProcessStartInfo _processStartInfo = new ProcessStartInfo();
_processStartInfo.UseShellExecute = false;
_processStartInfo.WorkingDirectory = @"C:\Program Files";
_processStartInfo.FileName = @"Notepad.exe";
_processStartInfo.Arguments = "test.txt";
Process myProcess = Process.Start(processStartInfo);
```
- Breakpoint on a Razor component on protected override void OnInitialized()
`UseShellExecute = false` notepad starts, OnInitialized() is called again - UI is reloaded
`UseShellExecute = true`, notepad starts, OnInitialized() is NOT called again - UI is NOT reloaded

### .NET Version

6.0
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.6

**Comment by javiercn** [comment]
@faciendum thanks for contacting us.

We do not have enough details to understand what you are doing. We would need a minimal repro project as a public github repository so that we can make progress.

With that in mind, from what I can infer. I am going to assume that you are either running with dotnet-watch or that you are running from VS. If that is the case, it is very likely that HotReload is detecting your change and restarting the project.

If you want to be sure, publish the app to the file system and run the published app directly to see if the behavior reproduces there.
