### ISSUE TITLE
More flexibility in Blazor's navigation system regarding browser history to support multi-page browsing

### ISSUE THREAD

**Issue by jtheisen** [dotnet/aspnetcore#44699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blazor 7 adds the ability to add history entry state on navigating when using `NavigationManager.NavigateTo`. This helps a lot with a unique user interface I like to implement in my application, but I still have to hack around a lot.

What I want to implement is what I call "historical navigation" which is a web application that displays the previous visited page along with the current one (when navigating internally). This animation shows what I mean:

![blazor-historical-navigation-screencast](https://user-images.githubusercontent.com/1516294/197361930-8be77df7-9777-4cbf-b0c1-5ef60fa0f8c7.gif)

I got this working on Blazor 7 and put [the repo](https://github.com/jtheisen/blazor-historical-navigation-demo) up.

However, the implementation is hacky and I'm filing this ticket to raise awareness to this kind of UI and point to possible solutions so that it could be implemented less hacky on a future version of Blazor.

### Describe the solution you'd like

The current version intercepts all anchor clicks the same way Blazor already does internally. In fact I copied the code to do so largely from the Blazor sources. When an anchor click is deemed internal navigation by the same rules Blazor uses, it's snatched away from the Blazor handlers and instead the event is delegated to a new .NET handler:

```js
event.preventDefault();
event.cancelBubble = true;

const replace = shouldUseReplaceForAnchor(anchorTarget);

navDelegator.invokeMethodAsync("Navigate", absoluteHref, replace);
```

This `Navigate` function is on a new scoped service that then calls the `NavigationManager` to do the navigation server-side:

```c#
[JSInvokable]
public void Navigate(String url, Boolean replace)
{
    var i = CurrentHistoryIndex;

    var options = new NavigationOptions
    {
        HistoryEntryState = (replace ? i : i + 1).ToString(),
        ReplaceHistoryEntry = replace
    };
    navigationManager.NavigateTo(url, options);
}
```

Whether a link should use `replace` is know to the Javascript side as that information is given in a css variable set on the parent container that represents a "page". The container representing the "previous page" has the variable set and all links therein thus navigate with `replace` being set to true.

That works pretty well in both Blazor Server and Blazor WebAssembly.

However, it's less than ideal that I need to replace all anchor-click logic in Blazor's Javascript side by snatching away the event handling.

There are two reasons why this is necessary, both of which would have to be addressed by Blazor to make this easier:

1. *A newly visited page needs to have a custom state set.*
  In the demo, this is just an integer and the actual route data is stored in the circuit (the route data for the previous page needs to be held somewhere), but one could also put the route data in the state. 
2. *There needs to be a way to make some anchors cause a replacement.*
  The demo uses the mentioned css variable to regulate that.

I've been thinking a bit about what changes to Blazor would make this less hacky and I think the current `RegisterLocationChangingHandler` would need to be augmented or some similar new callback  registration added.

The new version would have to have the ability to set the next history entry state.

It would also need to pass on information about the clicked anchor: The demo uses at least the `replace` boolean. Perhaps it could pass something set on a special `CascadingValue`.

This would do away with the need to snatch click events away from Blazor's Javascript.

**Comment by javiercn** [comment]
@jtheisen thanks for contacting us.

I am not sure that relying on the navigation state is the right tool for what you are trying to accomplish. I believe you would be better off implementing your own router to support this functionality. If you create your own router you can deal with events in the page however you see fit. Blazor will not intercept navigations if you are not using our built-in router.

The changes that you are proposing add a lot of complexity to the navigation manager and is not something we are inclined to tackle unless we see a clear need for it, especially since there are alternatives to it.

**Comment by jtheisen** [comment]
On a quick glance it seems that the Router is married to the entire logic about routes in general, ie. `RouteTable`, `RouteKey`, `RouteEntry`, etc. Those are internal classes.

I agree with you that Blazor shouldn't add complexity for an exotic use case, but it should provide the flexibility to allow adding exotic use cases on top.

It seems I'd have to replace a major part of Blazor's internals for something that would only require a little customization of what is already there.

If I'm wrong and I can do this while not replacing everything else in regards to routing, I'm all ears.

**Comment by SteveSandersonMS** [comment]
> I agree with you that Blazor shouldn't add complexity for an exotic use case, but it should provide the flexibility to allow adding exotic use cases on top.

There are always tradeoffs about how much extensiblity to add, given that each extensibility point (or any public API) becomes a thing that has to be supported permanently, and hence can block the framework from evolving in the long run. For routing, we've so far chosen to keep it largely decoupled from the core of the framework so that people can plug in entirely separate routers they create, which hopefully reduces the requirement to make the default router massively open for extension and hence locked to specific design choices forever.

What you've done with pre-intercepting the link clicks on the JS side and raising custom events is a pretty good way to get the behaviors you want. If we got evidence that this became a common thing to do for many developers, we'd certainly look at streamlining this and perhaps having built-in APIs for it. However I don't recall hearing of others doing this so it would likely be premature to make it an official feature.

> I got this working on Blazor 7 and put [the repo](https://github.com/jtheisen/blazor-historical-navigation-demo) up.

It's cool you made it work! It's neat how you were able to use `RouteView` to make it display like you wanted. If you think this kind of custom routing system may be useful to others, please consider publishing it as a NuGet package. That would also help with gathering evidence that it's a broadly demanded feature (if it turns out that lots of people do go on to use it).

**Comment by jtheisen** [comment]
You're right, I have a way of doing this and it should be low on Blazor's priorities.

However, maybe it would be beneficial to make the routing stuff more modular in general. I've had some trouble with other routing related things:

- uri escaped slashes are still interpreted as slashes, that's even documented but surprising and sometimes very undesirable
- routing never matches if the last path fragment contains a dot (that's likely because it's considered a file then, not sure where this gets decided though)

Both is a bit annoying because that means I can't have path fragments be arbitrary names without implementing my own escaping scheme.

I just throw this out here, I have workarounds for those things too.

Feel free to close this then.
