### ISSUE TITLE
dotnet new web profiles should list HTTPS profile before HTTP

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#44722]
According to [this GitHub comment](https://github.com/OmniSharp/omnisharp-vscode/issues/5417#issuecomment-1289747617)
> the right fix would be to have `dotnet new` only generate the https endpoint in launchSettings.json.

To reproduce the problem:

Follow the instructions at the [Microsoft Web API tutorial-Create a web project](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio-code#create-a-web-project-1)

```
dotnet new webapi -o TodoApi
cd TodoApi
code -r ../TodoApi
```

^F5 and it launches a browser to `http:localhost::<port>` not  `HTTPS` from `launchSettings.json`

***NOTE:*** This problem applies to all the web apps, minimal, MVC, Razor Pages

VSC says this is a https://github.com/OmniSharp/omnisharp-vscode/issues, OmniSharp says this is a `dotnet new` issue

See https://github.com/OmniSharp/omnisharp-vscode/issues/5417

**Comment by DamianEdwards** [comment]
These [changes were made intentionally in .NET 7](https://github.com/dotnet/aspnetcore/issues/41990) due to feedback about the experience issues that HTTPS can create when not properly configured. Visual Studio (& VS for Mac) was updated to prefer the HTTPS profile listed in `launchSettings.json` as VS contains extra logic that on project launch checks the status of the self-signed ASP.NET Core development certificate and prompts the user to install and trust it before the app is started, avoiding the vast majority of the issues.

For .NET CLI users (which includes VS Code) the default experience now is to not launch with HTTPS enabled in the project. An HTTPS launch profile will still be created by default, but as it is not listed first in `launchSettings.json`, `dotnet run` will not choose it by default. It can be specified at the command line using the `--launch-profile` or `-lp` options, e.g. `dotnet run -lp https`

**Comment by Rick-Anderson** [comment]
If anyone runs into this issue, VSC does the right thing now. See https://github.com/OmniSharp/omnisharp-vscode/issues/5417
