### ISSUE TITLE
Extra config not available in IHosting startup classes

### ISSUE THREAD

**Issue by specimen151** [dotnet/aspnetcore#44847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the new WebApplication in `Program.cs`,
Adding some extra config to the builder:
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile("extra_appsettings.json");
var app = builder.Build();
```

However these extra configs are not available to me in `public void Configure(IWebHostBuilder builder)` in `IHostingStartup`.

Seems to me (using the debugger) that IHostingStartup is called before we get the chance to call `AddJsonFile()`. Is it supposed to work like this, or is it a bug?

### Expected Behavior

I'd expect the (added) config to be available to the IHostingStartup implementations.

### .NET Version

6.0.300

**Comment by adityamandaleeka** [comment]
@specimen151 This is the current expected behavior. The `IHostingStartup` is initialized during `CreateBuilder` (during which all your configured callbacks will run). 

Do you need to be able to access the config you added at this point? If so, you could switch to using the Generic Host (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0).
