### ISSUE TITLE
[API Proposal]: Introduce IResettable to streamline object pool usage

### ISSUE THREAD

**Issue by geeknoid** [dotnet/aspnetcore#44901]
### Background and motivation

We use a lot of object pools in our environment and its clumsy to have to implement dedicated policy types when we generally want a single behavior applied to a large variety of object types. We adopted a solution of having all these objects declare themselves as IResettable and then a single policy suffices to deal with these objects

### API Proposal

```csharp
namespace Microsoft.Extensions.ObjectPool;

/// <summary>
/// Defines a method to reset an object to its initial state.
/// </summary>
public interface IResettable
{
    /// <summary>
    /// Reset the object to a neutral state, semantically similar to when the object was first constructed.
    /// </summary>
    /// <remarks>
    /// In general, this method is not expected to be thread-safe.
    /// </remarks>
    void Reset();
}

/// <summary>
/// An object pool policy for resettable objects.
/// </summary>
public sealed class ResettablePooledObjectPolicy<T> : PooledObjectPolicy<T>
    where T : notnull, IResettable, new()
{
    public static ResettablePooledObjectPolicy<T> Instance { get; } = new();

    private ResettablePooledObjectPolicy()
    {
    }

    public override T Create() => new();

    public override bool Return(T obj)
    {
        obj.Reset();
        return true;
    }
}
```

### API Usage

```csharp
// a resettable object is one that logically can come back to its initial state
internal class MyState : IResettable
{
    private readonly List<int> _data = new();
    public void Add(int value) { _data.Add(value); }
    public void Reset() { _data.Clear(); }
}

var pool = ObjectPool.Create<MyState>(ResettableObjectPoolPolicy<MyState>.Instance);

// or alternatively, there could be a new method on ObjectPool, which requires less typing...
var pool = ObjectPool.CreateResettable<MyState>();
```

**Comment by joperezr** [comment]
cc: @Tratcher

**Comment by xiaoyuvax** [comment]
I also met similar challenge to use instances returned from the object pool, cos they contain old property values and references to other objects, which may lead to problems, if not intialized.
but the `IResettable `solution requires implementing `Reset()` method for each object, it's a lot of labor if u've got a lot of types, cos u have to initialize each member of a type, some of which may be of reference to other types, as is complicated.

So far my solution is an extenstion method which cleans(resets).
```
 public static T Clean<T>(this T obj, bool keepRef = false)  // where T: IResetable    <-- U can limit it to certain interface
        {
            foreach (var p in obj.GetType().GetProperties().Where(i => i.CanWrite))
            {
                if (p.PropertyType.IsClass && keepRef) continue; 
                else if (...)  ...
                else p.SetValue(obj, default);
            }
            return obj;
        }
```

**Comment by halter73** [comment]
Could the default policy call `IResettable.Reset()` on return if the object happens to implement the interface? Since this is a new interface, this should be non breaking.

@JamesNK asks if Reset() should return a boolean to indicate success? Like TryReset? Could be useful for things like CancellationTokenSource.

Another option is to keep the ResettablePooledObjectPolicy type, and add a public `ResettablePooledObjectPolicy(Func<T, bool> tryReset)`. This way it could work for types you don't own. We might even be able to replat the StringBuilder policy on it and get rid of the interface.

**Comment by xiaoyuvax** [comment]
ah, this "default policy call `IResettable.Reset() ` " if detected, is preferable, so that those objects don't need resetting can be spared from being reset, for sorta performance optimiazaiton, at least in my case.

**Comment by geeknoid** [comment]
Having the default policy call Reset would require adding a type test in the existing paths, which would slow things down a teeny bit.

Having the Reset function return a boolean is a reasonable idea, although it seems fairly niche. Nevertheless the semantics would be clear. If Reset returns false, then the object is dropped on the floor and not added to the pool.

**Comment by geeknoid** [comment]
Having the default policy conditionally invoke IResettable.Reset doesn't require a type test on every call. The type test can be done in the constructor for the policy and then just a boolean test can be used in the Return method. So this sounds like a good idea as it avoids introducing another public policy type.

**Comment by Tratcher** [comment]
Is the current proposal:
```c#
public interface IResettable
{
    bool Reset();
}
```

And a type check in PooledObjectPolicy.Return?

**Comment by geeknoid** [comment]
> Is the current proposal:
> 
> ```cs
> public interface IResettable
> {
>     bool Reset();
> }
> ```
> 
> And a type check in PooledObjectPolicy.Return?

Yes, I think so.

**Comment by halter73** [comment]
API Review Notes:

- We're a fan of the bool return value because it allows for objects to enter a non-resettable state.
- Can we get away with only updating the `DefaultPooledObjectPolicy<T>`? `StringBuilderPooledObjectPolicy` exists, but `StringBuilder` is sealed.
- Is there anything analogous for object creation? No.
- Do we expect custom policies to respect this? No. If you are unsure what the `PooledPolicy<T>` will be, don't rely on this.
- By removing the ResettablePooledObjectPolicy, we lose the generic type constraint. However, given a plain old `ObjectPool<T>` that you didn't construct, you can never know if it will call `IResettable.Reset()`.
- The alternative is always calling reset yourself before returning. The upside of this proposal is that if you construct the ObjectPool and define the type yourself, you know you won't accidentally not reset. Or have others forget. This is already possible with custom polices, but it's more verbose.

API Approved!

```csharp
namespace Microsoft.Extensions.ObjectPool;

public interface IResettable
{
    bool Reset();
}
```

**Comment by Tratcher** [comment]
@halter73 that should have been TryReset.

**Comment by halter73** [comment]
Yeah. We should have discussed that. I figured we were trying to match `PooledObjectPolicy<T>.Return(T)` which also returns a book for similar reasons without "Try", but I think the "Try" is more clear. It aligns with `CancellationTokenSourece.TryReset()`.

@Tratcher can you send an email? I don't think it will be controversial, but it's good for visibility.

**Comment by Tratcher** [comment]
We did discuss it, and even agree to it, it just didn't make it into the notes.

**Comment by halter73** [comment]
I had to recheck the meeting video but @geeknoid did mention that "TryReset" was the new boolean-returning API name while I was distracted trying to copy the "current proposal. I never wrote it out or confirmed that we were all satisfied the name, but that's on me. I'll update the approval and make a note of it in the wrap up email.

**Comment by CodeBlanch** [comment]
I'm just going to throw this out there. I do agree basic usage of the ObjectPool requires too much ceremony. But I don't think IResettable really helps with that, it is also a lot of ceremony. I had this proposal a while back to introduce a simple helper extension which you can pass a delegate to for doing reset (if needed): https://github.com/dotnet/aspnetcore/issues/36586

I think it accomplishes the goal with less 🤷

[It got viciously tossed because this public API is not for public usage? Dub-tee-eff? I'm not bitter about that at all 🤣]

**Comment by xiaoyuvax** [comment]
After experimenting similar resetting mechanism in my project, i found it a big performance disaster to generally reset every instance, especially if a Type owns too many properties, and if most of its properties r to be overwritten later.

Now i've removed all experimental resetting implementations and adopted a more performance-friendly solution: 
Use different, dedicated DefaultObjectPools for different object Reuse Cases (in accordance with object life-cycle) of the same type, so that the same group of properties r always overwritten exactly in reusing code (i.e. avoid messing up reuse-cases), thus to avoid resetting. and wherein u don't have to use Reset() or custom ObjectPoolPolicy while assuring performance.

The only problem here is how to manage different reuse-cases, better with code, as to make it more readable and managable. 
i have contemplated some solutions:

1) Group up properties of Reuse Cases by Component Interfaces:
`public class MyObject : IReuseCase1, IReuseCase2`

2) allow immediate evaluation(if needed) upon callling a new Get<T,I>(Func<T,I>) method with Component Interfaces, as to make property evaluation more concentratedly visible, as to improve readbility and manageability (if business logic allows). 
 ```
    /// <summary>
    /// This is the method suggest to be added or just extended to DefaultObjectPool<T>
    /// </summary>
    /// <typeparam name="T">The type which may has multiple Reuse Cases</typeparam>
    /// <typeparam name="I">One of the component interfaces for T</typeparam>
    /// <param name="case1"></param>
    /// <param name="eval">Delegate to evaluate underlying properties immediately, if u don't want to do it immediately, u can simply use Get<I>() on the ObjectPool</param>
    /// <returns></returns>
public static T Get<T, I>(this DefaultObjectPool<I> case1, Func<I, I> eval = null) 
   where T: I
   where I : class
    {
        I objI = case1.Get();
        objI = eval?.Invoke(objI) ?? objI;   //note: if the delegate returns null, objI would not be changed.
        return objI is T objT ? objT : default;
    }
```
I made a more complete demo here (we need a DefaultObjectPoolPolicy4ReuseCases<T, I>  class) :
[](https://github.com/xiaoyuvax/ObjectPoolReuseCaseDemo)

3) above solution could manage Reuse-Case Consistency already, but i would also expect certain analyzer/compiler help, such as simple warnings, if reuse-case consistency is violated.

What do u guys think?
