### ISSUE TITLE
X-Requested-With header is incorrect in FetchHttpClient

### ISSUE THREAD

**Issue by val1984** [dotnet/aspnetcore#44933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`FetchHttpClient.ts` sets `X-Requested-With` header to `XMLHttpRequest` which makes it harder than needed to know which HTTP client was used by `@microsoft/signalr` JS library.

### Expected Behavior

`X-Requested-With` header should be set to `Fetch` as it was in [the initial implementation](https://github.com/dotnet/aspnetcore/blame/2be0ffae194c320472235173b8a18ab6c6ef78d0/src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts#L39).

### Steps To Reproduce

Make use of `@microsoft/signalr` JS library and check the headers sent by the lib when calling the negotiate route.

### Anything else?

`@microsoft/signalr`: ^6.0.9

**Comment by BrennanConroy** [comment]
This header is set so that Cookie authentication will avoid redirecting to a login page, if it actually did the redirect, it would result in an ugly, hard to diagnose error on the client side.
https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L94-L96
https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L105-L108

This behavior is customizable by setting the header yourself when creating the connection.
```
new signalR.HubConnectionBuilder()
    .withUrl("/chathub", { headers: { "X-Requested-With": "Fetch" } })
    .build();
```

**Comment by val1984** [comment]
What is the point of it if it's always set to "XMLHttpRequest", even when the FetchHttpClient is used?

**Comment by BrennanConroy** [comment]
> which HTTP client was used by @microsoft/signalr JS library

Why do you need to know this information?

> This behavior is customizable by setting the header yourself when creating the connection.

Is this customization not usable for your scenario?

> Shouldn't [CookieAuthenticationEvents.cs](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L105-L108) be modified to also accept "Fetch"?

No. Using "Fetch" as the header value is not a common pattern, whereas `XMLHttpRequest` is a very well known pattern that has been used for years across multiple technology stacks.
