### ISSUE TITLE
Long delay for request to start while debugging and another request is waiting

### ISSUE THREAD

**Issue by madelson** [dotnet/aspnetcore#44940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am debugging an application (no breakpoints set) and one request is doing a long asynchronous operation. I then kick off another request to the same endpoint and that request hangs for 10-15s before actually executing the new request.

Here is my app:
```
using System.Diagnostics;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
using SemaphoreSlim semaphore = new(1, 1);
app.MapGet("/wait", async () =>
{
    var requestStart = DateTimeOffset.Now;

    Stopwatch stopwatch = Stopwatch.StartNew();
    if (await semaphore.WaitAsync(TimeSpan.FromSeconds(5)))
    {
        await Task.Delay(TimeSpan.FromSeconds(500));
        semaphore.Release();
    }
    return $"Started at {requestStart}, waited for {stopwatch.ElapsedMilliseconds}ms";
});
```

Here are my steps:
1. Visit localhost:xyz/wait -> spins for a long time (expected)
2. Visit localhost:xyz/wait in another tab -> spins for about 20s, then returns with something like `Started at <date>, waited for 5001ms`;

I'm confused about where the extra time is going.

This does not happen when I run the app _without_ the debugger attached. In that mode request 2 completes in ~5s.

### Expected Behavior

The requests should behave about the same whether or not a debugger is attached.

### Steps To Reproduce

See bug description.

### Exceptions (if any)

n/a

### .NET Version

7.0.100-preview.7.22377.5 (originally reported by another user who is on 6)

**Comment by BrennanConroy** [comment]
This has something to do with HTTP/2. If you use a separate browser (instead of a separate tab) to force a new connection from the browser, you'll see the request finishes in 5 seconds. Additionally, if you use HTTP instead of HTTPS which forces HTTP/1 you also see requests finish in 5 seconds.

Looking at the logs shows that the second request doesn't even reach the server for many seconds. I think it's actually a chromium specific issue. Using just Firefox for the long blocking request and the second request shows the second request taking 5 seconds, but using Chrome or Edge shows the second request taking many seconds before even initiating the second request.

This chromium issue looks suspiciously similar to what is being observed: https://bugs.chromium.org/p/chromium/issues/detail?id=1074705&q=component%3AInternals%3ENetwork%3EHTTP2%20delay&can=2
