### ISSUE TITLE
[Blazor] new bind suffixes (after,get,set) fail to compile with .Net 7 

### ISSUE THREAD

**Issue by crmeadowcroft** [dotnet/aspnetcore#44952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documented sample code for @bind:after (and @bind:set) in Blazor apps does not compile. Problem in the code generator?

### Expected Behavior

The above sample code should compile without error (and do nothing when run).

### Steps To Reproduce

Create a new empty Web Assembly project. Place the code:

```@page "/"

<h1>Hello, world!</h1>
<input @bind="_text" @bind:after="PerformSearch" />

@code {
    private string _text = "";

    private async Task PerformSearch()
    {
        await Task.CompletedTask;
    }
}
```

in Index.razor. Attempt to compile. Error appears: Error CS1503 Argument 3: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<string>' to 'System.Action<string?>'

### .NET Version

7.0.100

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Unfortunately, we've discovered late in the release that a dependent change for this feature didn't make it in time due to an internal error. We've documented this as a [known issue](https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md#aspnet-core) for the .NET 7 release and have the fix pending for the upcoming 7.0 patch release.
