### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OAuth still using Newtonsoft

### ISSUE THREAD

**Issue by DominicSaladin** [dotnet/aspnetcore#45060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not quite sure if this fits the purpose here, but I found nothing on the internet about it, so...
I'm currently working on a custom OAuthHandler and tried to download the Package Microsoft.AspNetCore.Authentication.OAuth for this, but this package has not been updated for so long and still uses the Newtonsoft objects.

Is there an updated version of this package and I just didn't find it? I would like to implement the OAuthHandler just like the MS Handler here https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountHandler.cs

### Expected Behavior

The package Microsoft.AspNetCore.Authentication.OAuth should be updated or the [documentation ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.oauth.oauthcreatingticketcontext?view=aspnetcore-6.0)should tell which package I have to use.

### .NET Version

6.0.11

**Comment by martincostello** [comment]
You should use a FrameworkReference instead of a PackageReference now to get the latest version of the OAuth assembly to compile against: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore

That's why there's no newer packages in NuGet. It's not that it hasn't been updated, it just doesn't ship as its own dedicated package anymore.

This is how we build all the custom OAuth handlers in https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers

For example: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/c7f504404db35fbd9a3eda18e690e4e472fb3d4d/src/AspNet.Security.OAuth.GitHub/AspNet.Security.OAuth.GitHub.csproj#L14

**Comment by DominicSaladin** [comment]
Oh wow, I did not know that, thank you @martincostello that totally works!
