### ISSUE TITLE
Blazor lazy loading percentage 

### ISSUE THREAD

**Issue by mottaghipour** [dotnet/aspnetcore#45164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We can use css variables like `--blazor-load-percentage` for make better loading screen and design html elemnts. It's perfect but `--blazor-load-percentage` does not updated on lazy loading assemblies.

### Describe the solution you'd like

If `--blazor-load-percentage` variable update on lazy loading process we can use this percentage on all loading components.

### Additional context

![Screenshot from 2022-11-18 11-54-39](https://user-images.githubusercontent.com/98211450/202655358-03041b40-b389-4324-a9f7-b5340a467fa1.png)

**Comment by javiercn** [comment]
@mottaghipour thanks for contacting us.

I do not think we want to go in that direction. The values provided by these variables represent the percentage during the boot process. We do not want to include anything that is loaded afterwards. Since lazy loaded assemblies are loaded explicitly, you can create your own CSS custom property to work out how many of them have been loaded and use some `calc` to compute the value you are looking for.

**Comment by mottaghipour** [comment]
how to get percentage of downloaded assemblies with c# code?
``` c#
    private List<Assembly> lazyLoadedAssemblies = new();

    private async Task OnNavigateAsync(NavigationContext args)
    {
        try
        {
            if (args.Path == "lazy")
            {
                var assemblies = await AssemblyLoader.LoadAssembliesAsync(
                    new[] { "Lazy.dll" });
                lazyLoadedAssemblies.AddRange(assemblies);
            }
        }
        catch (Exception ex)
        {
            Logger.LogError("Error: {Message}", ex.Message);
        }
    }
```

**Comment by javiercn** [comment]
@mottaghipour that is for your application to track.

You mark assemblies as lazy, so you know the total. And you can increment the count every time you load one.

**Comment by mottaghipour** [comment]
Ok. Thank you. Better close this issue :)
