### ISSUE TITLE
Make QuickGrid more inheritance friendly

### ISSUE THREAD

**Issue by wolfgangschneider** [dotnet/aspnetcore#45182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to do greate my own Grid including selection using Inheritance  but the most of the usable fields are privat 
e.g (but not all)
  // Caches of method->delegate conversions
    private readonly RenderFragment _renderColumnHeaders;
    private readonly RenderFragment _renderNonVirtualizedRows;

If this this fields are protected it gives me the possibility to create my own RenderNonVirtualizedRows function.

### Describe the solution you'd like

  protected readonly RenderFragment _renderColumnHeaders;
  protected readonly RenderFragment _renderNonVirtualizedRows;

and much more

### Additional context

Why I prefer inheritance in case of change original code:
When a new Quick grid nuget package will release I can use all new features / bux fixes without compare my modified code with new one.

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us, @wolfgangschneider.

I appreciate your objectives, however we have to strike a balance. In general it's crucial for the framework to have a clearly defined API surface and strongly encapsulate its implementation details. The more parts of the implementation we make public, the less we're able to evolve the framework in the future because the implementation has become a public contract we can't break. As such we don't just change things to public/protected without having a clear design for exactly how it would be used and why we would never want to change those implementations details in the future.

In this specific case it would be helpful if you could describe what you're trying to achieve (as in, what user-facing functionality you're trying to produce), and why you believe the only reasonable way to achieve it involves accessing internal state/methods. We may be able to come up with a design for how to make QuickGrid more extensible.

**Comment by wolfgangschneider** [comment]
@SteveSandersonMS 

I want to create a derived QuickGrid  that supports single row selection.

My solution:
crate an inhereted class EBQuickGrid  razor and cs file.

EBQuickGrid.razor

`base.BuildRenderTree(__builder);
`

EBQuickGrid.cs
```
 public EBQuickGrid() : base()
    {
      
        _renderNonVirtualizedRows = RenderNonVirtualizedRowsWitchOnClick;
    }
```
to do this, the _renderNonVirtualizedRows  Access Modifier has to change

*  I create my own _renderNonVirtualizedRows  function

```
 private void RenderNonVirtualizedRowsWitchOnClick(RenderTreeBuilder __builder)
    {
        var initialRowIndex = 2; // aria-rowindex is 1-based, plus the first row is the header
        var rowIndex = initialRowIndex;
        foreach (var item in _currentNonVirtualizedViewItems)
        {
            RenderRow(__builder, rowIndex++, item);

        }

        // When pagination is enabled, by default ensure we render the exact number of expected rows per page,
        // even if there aren't enough data items. This avoids the layout jumping on the last page.
        // Consider making this optional.
        if (Pagination is not null)
        {
            while (rowIndex++ < initialRowIndex + Pagination.ItemsPerPage)
            {
                <tr></tr>
            }
        }
    }
```
To do this, the currentNonVirtualizedViewItems Access Modifier has to change

* create my own RenderRow function

```
  protected new void RenderRow(RenderTreeBuilder __builder, int rowIndex, TGridItem item)
    {
    
        string selected = string.Empty;

        if( whatever)
            selected = "cssRrowselectedClass" 
  
        <tr @key="@(ItemKey(item))" class="@selected  @GetRowCSS(item)" @onclick="() => OnClickAsync(item!,rowIndex)" aria-rowindex="@rowIndex">
            @foreach (var col in _columns)
            {
                <td class="@ColumnClass(col)" @key="@col">
                    @{
                        col.CellContent(__builder, item);
                    }
                </td>
            }
        </tr>
    }
```

To do this, the _columns and CellContent Access Modifier has to change (CellContent to public)

Maybe I used a wrong way to extend the QuickGrid

**Comment by wolfgangschneider** [comment]
I added feedback. How to reopen it?
