### ISSUE TITLE
Unable to set request body format to binary in minimal api

### ISSUE THREAD

**Issue by FranklinWhale** [dotnet/aspnetcore#45265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`requestBody` in `swagger.json` of the code below

```cs
app.MapPut("/file", Created (HttpRequest request) => {
    return TypedResults.Created("https://example.org");
})
.Accepts<byte[]>("application/zip")
.Produces(StatusCodes.Status415UnsupportedMediaType)
```

is

``` json
"requestBody": {
  "content": {
    "application/zip": {
      "schema": {
        "type": "string",
        "format": "byte"
      }
    }
  }
}
```

while `.Accepts<Stream>("application/zip")`

leads to

```json
"requestBody": {
  "content": {
    "application/zip": {
      "schema": {
        "$ref": "#/components/schemas/Stream"
      }
    }
  }
}
```

When I want to override `requestBody` by adding

```cs
.WithOpenApi(o => {
    o.RequestBody = new OpenApiRequestBody {
        Content = new Dictionary<string, OpenApiMediaType>() {
            {
                "application/zip",
                new OpenApiMediaType {
                    Schema = new OpenApiSchema {
                        Type = "string",
                        Format = "binary"
                    }
                }
            }
        }
    };
    return o;
});
```

I find that it has no effect.

How to set format to `binary`?

### .NET Version

7.0.100

**Comment by captainsafia** [comment]
Triage: This behavior occurs because the moment schema generation for types in OpenAPI is facilitated by Swashbuckle. Even if you set a schema specifically using `WithOpenApi`, it gets overridden in Swashbuckle's schema generator. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2521 for more info. By default, the correct scheme isn't set here.

For now, you might want to consider using an `OperationFilter` in Swashbuckle to set the types whenever the return type is a stream. It would look something like this:

```csharp
builder.Services.AddSwaggerGen(c =>
{
    c.OperationFilter<StreamParameterOperationFilter>();
});

public class AuthorizeOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
      var acceptsMetadata = context.ApiDescription.ActionDescriptor.EndpointMetadata.OfType<IAcceptsMetadata>();
      if (acceptsMetadata.RequestType == typeof(Stream)
      {
         // modify operation here
      }
    }
```
