### ISSUE TITLE
Virtualize does not respond to items change after call RefreshDataAsync but when scrolling page

### ISSUE THREAD

**Issue by rmoergeli** [dotnet/aspnetcore#45694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor server app .NET 7.0, Virtualized table is not deleting item after it has been deleted from database and RefreshDataAsync(). But when I scroll one page done and up again it's updating. But LoadTestData() reloaded the data correctly before.

https://github.com/rmoergeli/VirtualizeTest

```
            <Virtualize @ref="@TestVirtualViewModel.TestContainer" ItemsProvider="@TestVirtualViewModel.LoadTestData" Context="forecast" OverscanCount="5">
                <ItemContent>
                <tr>
                    <td>@forecast.Id</td>
                    <td>@forecast.Date.ToShortDateString()</td>
                    <td>@forecast.TemperatureC</td>
                    <td>@forecast.TemperatureF</td>
                    <td>@forecast.Summary</td>
                    <td>
                        <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#modaldelete1" @onclick="@(() => TestVirtualViewModel.OnSelectedId(forecast.Id))">
                            Delete
                        </a>
                    </td>
                </tr>
                </ItemContent>
                <Placeholder>
                    <p>Bitte warten.</p>
                </Placeholder>
            </Virtualize>
```

### Expected Behavior

Virtualized table should reflect the change without additional StateHasChanged().

### Steps To Reproduce

[](https://github.com/rmoergeli/VirtualizeTest)

**Comment by Nick-Stanton** [comment]
Hi @rmoergeli,
It seems that your issue is caused by calling `TestContainer?.RefreshDataAsync()` from inside your ViewModel. Since `RefreshDataAsync()` is usually called from a Blazor event handler or component lifecycle method, a render is not automatically triggered. I would suggest moving some portion of your deletion logic to your `TestVirtual.Razor` component so that the component can be notified of a state change (e.g. `StateHasChanged()`, which can't be called from inside your ViewModel).

For more information, please see the [doc page](https://learn.microsoft.com/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#item-provider-delegate) about Razor Component virtualization. Please keep in mind that the examples in the doc page are oriented towards handling virtual components within the `@code { }` block of your Razor component.

**Comment by rmoergeli** [comment]
Indeed that works. I thought I could move more of the Razor Component into the ViewModel.

Many thanks!
