### ISSUE TITLE
Run on Mac OS 13.0 in Helix

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In https://github.com/dotnet/aspnetcore/pull/45737, when I added Mac OS 13.0 to Helix, the job hung.

### Expected Behavior

Helix runs on the latest Mac OS version (13.0+) successfully.

### Steps To Reproduce

Run on 13.0:
```xml
<HelixAvailableTargetQueue Include="OSX.13.Amd64.Open" Platform="OSX" />
```

**Comment by dougbu** [comment]
So far, it seems problems here may be on the Core-Eng side. The target queue we're trying here may have no (physical) agents behind it yet. @ilyas1974 will follow up on Monday w/ more information.

**Comment by dougbu** [comment]
The issue was the `OSX.13.Amd64.Open` queue was empty when we initially tried to test there. Thanks to @ilyas1974's work w/ DDFUN, the queue now has 10 (physical) machines in it. Second run of #45855 (a draft PR I'll leave open to remind me) was successful😁  See [build #20230112.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=135454&view=results).

We're not ready to add this queue to our `aspnetcore-helix-matrix` runs yet because it doesn't contain enough machines for regular use. We should track the information in [this Power BI dashboard](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8b49a89c-7aea-4fdb-95d5-547a9fe5d734/ReportSectione6503c9317531cbfd377?experience=power-bi) for (a) the addition of a `osx.13.amd64.open` row and (b) more than ~45 machines on that row. Can add testing on OSX 13 to the scheduled `aspnetcore-helix-matrix` once that all happens.

----

@ilyas1974 I see multiple rows for some queues e.g. `osx.1200.amd64.open`. Is that about moves from one hardware type to another❔

**Comment by dougbu** [comment]
Marked this as a `task` and removed the `investigate` label.

@mkArtakMSFT do we have a label for tracking status elsewhere❔ For example, would marking this as `External` be appropriate❔

(This repo contains far too many labels. Choosing between them or even finding something that fits is becoming difficult.)

**Comment by dougbu** [comment]
> ... We should track the information in [this Power BI dashboard](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8b49a89c-7aea-4fdb-95d5-547a9fe5d734/ReportSectione6503c9317531cbfd377?experience=power-bi) for (a) the addition of a `osx.13.amd64.open` row and (b) more than ~45 machines on that row. Can add testing on OSX 13 to the scheduled `aspnetcore-helix-matrix` once that all happens.
> 
> @ilyas1974 I see multiple rows for some queues e.g. `osx.1200.amd64.open`. Is that about moves from one hardware type to another❔

/ping @ilyas1974

In addition, the [Power BI dashboard](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8b49a89c-7aea-4fdb-95d5-547a9fe5d734/ReportSectione6503c9317531cbfd377?experience=power-bi) still doesn't show the `osx.13.amd64.open` queue (unless I'm missing something). Why not❔
