### ISSUE TITLE
Microsoft.Extensions.Caching.SqlServer AddDistributedSqlServerCache add IServiceProvider support

### ISSUE THREAD

**Issue by kzhui125** [dotnet/aspnetcore#45762]
for AddSingleton or AddScoped, I can use IServiceProvider.GetRequiredService to config the instance.

I want to use IServiceProvider in AddDistributedSqlServerCache, because my ConnectionString is from another service.

Thanks!

**Comment by kzhui125** [comment]
Is there a workaround now?

**Comment by pinkfloydx33** [comment]
Have you tried a custom `IConfigureOptions<SqlServerCacheOptions>` to configure the options? That's the typical pattern when you need to use constructed services for option configuration. 

You'd still have to pass a dummy callback to `AddDistributedSqlServerCache` since it doesn't allow the argument to be null.

**Comment by kzhui125** [comment]
Thanks @pinkfloydx33 , I think this code is OK?:

```cs
services.AddSingleton<IDistributedCache, SqlServerCache>();
services.AddOptions<SqlServerCacheOptions>()
    .Configure<SomeService>((o, someService) =>
    {
        o.ConnectionString = someService.ConnectionString;
        o.SchemaName = "dbo";
        o.TableName = "TempCache";
    });
```
