### ISSUE TITLE
obsolete EnableDataAnnotationsValidation, requires IServiceProvider now 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#45783]
regarding this change https://github.com/dotnet/aspnetcore/pull/39737

I just noticed that `EnableDataAnnotationsValidation()` is obsolete now (.net 7),
I'm not going to need the `IServiceProvider` in my validation attributes, 
if you remove the obsolete method (without ISP), I'll have to inject the ISP everywhere `EnableDataAnnotationsValidation` gets called, even though I don't need it.

For now, if the method gets removed think I'll create a dummy class and pass it:
```
    public class MyISP : IServiceProvider
    {
        public object GetService(Type serviceType)
        {
            return null;
        }
    }
...
EditContext.EnableDataAnnotationsValidation(new MyISP())
```
unless there's a `static` service locator so I could create an extension for `EditContext` , so I could call
`EditContext.EnableDataAnnotationsValidation(ServiceLocator.Resolve<IServiceProvider>)`

`async` calls can't be used in Validation Attributes/IValidatableObject method (https://github.com/dotnet/aspnetcore/issues/7573),

so I do my DB/Service requiring validation at the start of my `Save` methods.

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

Where are you calling `EnableDataAnnotationsValidation` directly? This is typically called within a component, like the `DataAnnotationsValidator` that injects the service provider.

It's not clear what your ask here is.

**Comment by omuleanu** [comment]
@javiercn I'm calling it inside a Create and Edit method of a state object of my Custom Component which in this case it is used to edit multiple items at the same time, something like:
```
var itemState = new EditItemState<T>()
{
    ...
    EditContext = new EditContext(model),
};

itemState.EditContext.EnableDataAnnotationsValidation();            

editStates.Add(itemState.Key, itemState);
```
---
I'm asking to remove the requirement to pass the `IServiceProvider` to the `EnableDataAnnotationsValidation`
I also noted that if you'll use the `IServiceProvider` in your `IValidatableObject.Validate`  you won't be able to use `async` anyway, so it will be more efficient to do call this validation from your `Save` method.

**Comment by javiercn** [comment]
@omuleanu what is the problem with injecting the IServiceProvider in your custom component?

I suspect the logic behind this change was that we want to guarantee validation rules can take advantage of the service provider if needed.

As for the comment regarding async, it is completely orthogonal to this.

Based on this I do not think we want to reconsider this decision and we would recommend you update your code in one of these two ways:
* Inject the service provider in your custom component and pass it to the existing overload.
* Pass in your own provider.

Both options are pretty straightforward.

**Comment by omuleanu** [comment]
> @omuleanu what is the problem with injecting the IServiceProvider in your custom component?
@javiercn I suppose it feels wrong to inject something just for the purpose of passing it along.

Also the edit feature of my component is only going to be used probably 5% of the time, but I have to inject it just for it be available for this method.

The code that needs it should be the one that will resolve it.
here's an example: 
```
public class DinnerInput : IValidatableObject
{
...
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        var cxf = validationContext.GetService<IDbContextFactory<MyContext>>();
    }
}
```
think the code that created this `ValidationContext`, should be the one that will resolve the `IServiceProvider`.

**Comment by javiercn** [comment]
> @javiercn I suppose it feels wrong to inject something just for the purpose of passing it along.

I am not sure I agree with this statement. Plenty of software passes data/services around. In this case, you are providing context via the `EnableDataAnnotationsValidation` call.

If your concern is performance, I do not think this will be appreciable.

I would be concerned if this change resulted in apps having to update dozens of call sites to do this, but from experience, the change is limited to custom form validation components which most apps do not have.

> think the code that created this `ValidationContext`, should be the one that will resolve the `IServiceProvider`.

There is a tradeoff here. We would not be having this conversation if `EditContextDataAnnotationsExtensions` were internal/private members of the DataAnnotationsValidator component.

The only reason they are likely public static methods is because we likely wanted you to be able to add data annotations without forcing you to use our component. There are other ways to do this, but I do not think one way or the other is significantly better or even important for the vast majority of use cases.

So, I do not think there is a strong reason for us not to continue with this change, and the suggestion above is what we would recommend you do.

Hope that helps clarify our reasoning.
