### ISSUE TITLE
BL0007 "Component parameters should be auto property" too broad

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#45793]
looking at https://github.com/dotnet/aspnetcore/issues/26230, seems that having some code in the Parameter `get` is not a problem at  all, 
and having code in the Parameter `set` will be an issue **if we trigger rerenders**.

So as long as we don't do things like: `SomeEvent.InvokeAsync(), ValueChanged.InvokeAsync(value),  ` in the `set` we can ignore this warning, right ?

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

You are correct. However, this is a trade-off between the complexity of the rule and its applicability. You can have a full property parameter and do some things inside the get or set without necessarily having problems. 

However, the list of ways in which things can go wrong is big and it is easier and better to provide a clear rule that everybody can understand and a clear way to achieve a concrete goal in those situations rather than having to list or detect all the potential pitfall cases.

With this, what I am trying to say is that, like with every warning, you can choose to suppress it at your own risk, but at that point it's up to you to ensure that the behavior of the app matches your expectations.
