### ISSUE TITLE
Investigate interaction between `UseProxyToSpaDevelopmentServer` and `UseEndpoints`

### ISSUE THREAD

**Issue by rafaelfgx** [dotnet/aspnetcore#45903]

**Comment by mkArtakMSFT** [comment]
@captainsafia, @JamesNK do you know if is this a newly added analyzer suggesting this change and is the proposed change truly equivalent to the original code?

**Comment by brunolins16** [comment]
@rafaelfgx I have tested without `app.UseRouting` and `app.UseEndpoints`, as mentioned, and it should work. Can you share a repro?

**Comment by halter73** [comment]
@brunolins16 Did you try with `UseRouting` but not `UseEndpoints`? That should also work.

**Comment by HarelM** [comment]
I've stumbled across this issue as well I believe as can be read in my comment here: https://github.com/dotnet/aspnetcore/pull/42937#issuecomment-1383081751
For some reason the commit is not in the post, the following is the relevant commit I did in order to revert back to a working state:
https://github.com/IsraelHikingMap/Site/commit/419b98bdadd6e384cc161fef94fbe1619ee8962f
I did some workarounds as can be seen in the following commits:
https://github.com/IsraelHikingMap/Site/commit/788a961d7d3e6bdca04ba3a40ea8db265e440161
to bypass this but I believe the docs should mention the need to remove `UseRouting` as well so that developers will fix the warning properly without breaking the entire app like I did.
After the removal of `UseRouting` I believe the app is working as expected (although I'm not very confident it does as I have done some changes I don't fully understand)...

**Comment by HarelM** [comment]
Nope, I was celebrating too soon...
One of my controllers that doesn't require authentication is not called in my latest code: https://github.com/IsraelHikingMap/Site/tree/32146b91931e6fd3a392413063be3e091685f5ae
Generally speaking, this analyzer brought more damage than good from my point of view, unfortunately... :-(

**Comment by rafaelfgx** [comment]
@javiercn and @brunolins16

Guys, thanks for replying and for trying to help.

I'm not using minimal hosting.

I've tried calling MapControllers directly, but it doesn't work at runtime.

![image](https://user-images.githubusercontent.com/7357119/213185833-0db27256-61c0-46f6-9d47-cf2b0d8eb9b0.png)

My repo: https://github.com/rafaelfgx/Architecture

Thanks again in advance.

**Comment by captainsafia** [comment]
OK, while looking into this, I observed one buggy behavior with the analyzer which is that it will warn on code like:

```csharp
app.UseEndpoints(e => {});
```

Which is not desirable since the user might want to be explicitly invoking `UseEndpoints` with a certain ordering.

> I'm not using minimal hosting. I'm using top-level statements in program.cs class.

Minimal hosting refers to the use of the `WebApplicationBuilder` and `WebApplication` constructs here. You can read more about them [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0).

> I've tried calling MapControllers directly, but it doesn't work at runtime. Angular does not identify the controller endpoint and returns 404.

I'm not a total expert on the SPA templates here but I suspect it might have something to do with the order of the other middlewares in your application. Top-level invocations are working in the [built-in Angular templates](https://github.com/dotnet/spa-templates/blob/b88ebff70c461ded8aa7d101875cc2375a4476fb/src/content/Angular-CSharp/Program.cs).

**Comment by brunolins16** [comment]
> I'm not a total expert on the SPA templates here but I suspect it might have something to do with the order of the other middlewares in your application. Top-level invocations are working in the [built-in Angular templates](https://github.com/dotnet/spa-templates/blob/b88ebff70c461ded8aa7d101875cc2375a4476fb/src/content/Angular-CSharp/Program.cs).

I believe you are right. I am not expert as well but the call to `UseAngularCliServer` will configures the `UseProxyToSpaDevelopmentServer` that will proxy all request to SPA and I believe in this case `MapControllers` need to be called with `UseEndpoints`.

Could be related to this discussion: https://github.com/dotnet/aspnetcore/issues/44244

@javiercn @mkArtakMSFT maybe you could confirm this information.

**Comment by rafaelfgx** [comment]
Thank you very much, guys!

**Comment by captainsafia** [comment]
> Nope, I was celebrating too soon... One of my controllers that doesn't require authentication is not called in my latest code: https://github.com/IsraelHikingMap/Site/tree/32146b91931e6fd3a392413063be3e091685f5ae Generally speaking, this analyzer brought more damage than good from my point of view, unfortunately... :-(

@HarelM Do you mind opening another issue for your dilemma so we can track if there is a similar problem there? I don't want it to get lost between the comment on the PR and this issue.

**Comment by captainsafia** [comment]
I split up the analyzer problem into a separate bug.

Moving this to the Blazor area to resolve why the SPA setup used in user code is causing issues with `MapControllers`.

cc: @mkArtakMSFT

**Comment by Nick-Stanton** [comment]
@SteveSandersonMS when convenient could you please check this out?

**Comment by HarelM** [comment]
@captainsafia I'm not sure what the other bug should say if I need to open a new one, the bottom line of this bug describes my problem.
The obsolete message was confusing and somewhat incorrect from my point of view.
I needed a few changes to happen for it to work properly.
I had a middleware after the controllers which causes issues and keeping the `useRouting` also caused issues.
Hope this helps you guys narrow down the issue. Good luck! :-)

**Comment by SteveSandersonMS** [comment]
I've looked into it, and it appears to match with what @JamesNK says in https://github.com/dotnet/aspnetcore/issues/44244. That is, `UseSpa` is terminal middleware, so if you want other middleware to run for certain URLs, you have to register that other middleware earlier in the pipeline. Calling `application.MapControllers()` directly (outside `UseEndpoints`) registers the controller middleware too late, so it isn't compatible with `UseSpa`. This is not a breaking change - it's always been the case as far as I can tell (verified back to .NET 6 anyway).

@captainsafia Do any problems occur if people call `application.UseEndpoints(endpoints => endpoints.MapControllers())`? That's compatible with `UseSpa` but I don't know if it has any drawbacks besides triggering the Roslyn suggestion.

@HarelM You might already be aware, but `UseSpa` is from `Microsoft.AspNetCore.SpaServices.Extensions` which is not the latest and recommended way to host a SPA inside ASP.NET Core. As of .NET 6, this was replaced with the [`Microsoft.AspNetCore.SpaProxy`](https://www.nuget.org/packages/microsoft.aspnetcore.spaproxy) package - read more at https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-7.0#improved-single-page-app-spa-templates. We're not actively working on the older `Microsoft.AspNetCore.SpaServices.Extensions` package so if possible you'd be better off upgrading, which will implicitly fix the issue you're facing here.
