### ISSUE TITLE
Generating code for an OpenAPI Service Reference fails if the path to the swagger file has spaces in it.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#45926]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generating-code-for-an-OpenAPI-Service-R/10244904)._

---
[severity:It's more difficult to complete my work]
If you attempt to generate an OpenAPI Service Reference when the path to the swagger.json has spaces in it, it will fail to generate the C# code. This is because the path to the swagger.json file is not escaped, so if you have a swagger.json file at "C:\path with spaces\swagger.json", this will run the command `"path\to\nswag.exe" /input:C:\path with spaces\swagger.json /output:obj/swagger.cs`, which will be interpreted by NSwag as `/input:C:\path`.  Manually copying the command and running it with quotation marks around the input command allows the build to succeed.

---
#### Feedback Bot on 1/4/2023, 07:54 PM: 

(private comment, text removed)

---
#### Levi Willrich solved on 1/4/2023, 09:27 AM, 0 votes: 

<p>It is possible to manually generate the code file by copying the command from the error list into a text editor, which gives you something like this</p>
<pre><code>Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\lwillrich\.nuget\packages\nswag.msbuild\13.0.5\build\../tools/Win/NSwag.exe" openapi2csclient /className:WebApi /namespace:<span class="hljs-tag">&lt;<span class="hljs-name">Namespace</span>&gt;</span> /input:E:\Repos\Windows Applications\<span class="hljs-tag">&lt;<span class="hljs-name">solution</span>&gt;</span>\<span class="hljs-tag">&lt;<span class="hljs-name">project</span>&gt;</span>\OpenAPIs\swagger.json /output:obj\swaggerClient.cs " exited with code -1.	<span class="hljs-tag">&lt;<span class="hljs-name">Solution</span>&gt;</span>	C:\Users\lwillrich\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets	28	
  
</code></pre>
<p>From there you can add quotes around the path after /input, copy out the actual command into the command line, and run it.</p>

**Comment by mitchdenny** [comment]
Looks like this might be an issue with the handling of the `<OpenApiReference ... />` by the `NSwag.ApiDescription.Client` package that we depend on. Looking at the specific version of the targets file that is bombing out it seems like the `/input:` argument is not being correctly quoted:

```xml
<Command>%(Command) /input:%(FullPath) /output:%(OutputPath) %(Options)</Command>
```

The version of `NSwag.ApiDescription.Client` that we are picking up here is `13.0.5`. If I bump to the latest version of `NSwag.ApiDescription.Client`  (`13.18.2`) and `Microsoft.Extensions.ApiDescription.Client` (`7.0.2`) it seems to work. So I'd say the bug has been fixed in the underlying tooling we depend on. Just need to figure out why we are using those older versions and what it'll take to do a bump.

Thanks for reporting!

**Comment by mitchdenny** [comment]
Update: I've reached out to the folks within the Visual Studio team that own the parts of VS that control versions that are injected here. Hopefully they can pick up a newer version of the packages.

**Comment by mitchdenny** [comment]
The VS team has responded and they will look into fixing this on their side. For now the workaround is manually updating the package versions in your `*.csproj` file and then rebuilding. I'll go ahead and close this issue now since this isn't actually an ASP.NET issue.
