### ISSUE TITLE
PreventDefault as a method on Blazor event arguments

### ISSUE THREAD

**Issue by stsrki** [dotnet/aspnetcore#45949]
We already have a way of preventing events in Blazor, but the problem is that it is very limited. The prevention only works after the event handler is over and the component rendering cycle is finished. This way it is really hard to do any advanced handling on input, like input masking for example. The existing behavior can be seen in the next example.

**Existing API**

```razor
<input value="@name" type="text" @onkeydown="@onKeydown" @onkeydown:preventDefault="@isPreventKey" />

@code {
    private string name { get; set; }

    private bool isPreventKey { get; set; }

    private void onKeydown( KeyboardEventArgs args )
    {
        this.isPreventKey = args.Key == "a";
    }
}
```

I am aware that we can do the JavaScript-type event handlers, eg. `<input onkeydown="do some stuff here" />`, but that way, we cannot access any code from C# without additional interop calls.

---

My proposal is to add the `PreventDefault()` method on existing event argument classes, eg `KeyboardEventArgs`, `MouseEventArgs`, and others. Blazor will somehow internally keep track of the event argument state, and if `.PreventDefault();` was invoked the event would be canceled.

**Proposed API**

```razor
<input value="@name" type="text" @onkeydown="@onKeydown" />

@code {
    private string name { get; set; }

    private void onKeydown( KeyboardEventArgs args )
    {
        if ( args.Key == "a"  )
        {
            args.PreventDefault();
        }
    }
}
```

---

As far as am aware, we have a similar API to the proposed one already on the navigation. So the use case would be similar.

eg.

```diff
private ValueTask OnLocationChanging(LocationChangingContext context)
{
    if (context.TargetLocation == "/counter")
    {
+        context.PreventNavigation();
    }

    return ValueTask.CompletedTask;
}
```

**Comment by javiercn** [comment]
@stsrki thanks for contacting us.

I am not sure I follow. `preventDefault` is about preventing the event on JavaScript from applying the default behavior. 

By the time the event reaches .NET the event has already happened, that's why we have a declarative API to express what you want ahead of time.

If your intent is that `args.PreventDefault()` works within JS, that's not something we can do (we can't travel back in time (yet)), and if your intent is to avoid doing anything on the handler, I believe you can thow a taskcancelledexception and that will stop any further processing.

**Comment by stsrki** [comment]
> If your intent is that `args.PreventDefault()` works within JS

That was my idea originally, yes.

In the meantime, I discovered that in JavaScript, `preventDefault()` cannot work with async code, which in turn makes it unusable with Blazor too.

My next question is. Is there any way in Blazor, currently or a planned feature for the future, to cancel the event conditionally so it doesn't get through? Without throwing an exception.

**Comment by javiercn** [comment]
> In the meantime, I discovered that in JavaScript, `preventDefault()` cannot work with async code, which in turn makes it unusable with Blazor too.

This is exactly the reason why we use a declarative model; you need to "preempt" what the behavior is based on the state at the time of rendering.

> My next question is. Is there any way in Blazor, currently or a planned feature for the future, to cancel the event conditionally so it doesn't get through? Without throwing an exception.

I took another look at the code and realized that throwing a `TaskCanceledException` won't work here if your goal is to prevent a re-render based on the cancelation.

I am not sure we would add a way to achieve this. We have not received many requests for it, and it does not come for free. It would require us to pass in a cancellation token to the `EventCallback` which will create an explosion of overloads and it will also require to create a CTS on each event, which can add a lot to the cost.

Otherwise, we would have to introduce a breaking change as we would need to create a separate event base type different than EventArgs to add a property with the CTS to cancel the event.

I think, if we were to do something, it would be to unconditionally avoid triggering a re-render if the task gets canceled synchronously as a result of some code throwing a `TaskCanceledException` sychronously inside component base. It would become an optinion of ComponentBase rather than a general framework behavior.

I'll put this in the backlog to collect more feedback with the additional context and constraints we have to deal with.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
