### ISSUE TITLE
Blazor WASM PWA app published to github pages - PWA not working, errors in console, cannot access .json file

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#46027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I published my Blazor WASM app to the github pages. Everything is working in localhost (no errors in console, lottie animation is displayed correctly, PWA can be installed ...) but when its published its not working as expected. I try to find some tutorials but no luck so it seems that I am doing something wrong. Could you please check if its me doing something wrong or there is issue on your side?

### Steps To Reproduce

1. Create new Blazor WASM PWA (optional: add lottie animation)
2. Publish app to github pages

Github repo:
https://github.com/Laftek/BlazorWASMPWAStaticPublish.git
Site:
https://laftek.github.io/BlazorWASMPWAStaticPublish/

### .NET Version

7.0.100

### Anything else?

![Screenshot_20230111_010506](https://user-images.githubusercontent.com/98880933/211802171-9d6a2f83-b128-4508-9c88-994e11242ffb.png)

**Comment by Nick-Stanton** [comment]
On first look, I am noticing that [your publish workflow](https://github.com/Laftek/BlazorWASMPWAStaticPublish/blob/main/.github/workflows/main.yml) uses `actions/checkout@v2` and `actions/setup-dotnet@v1`, both of which currently have v3 versions. An added benefit is that these run on Node16 instead of Node12 which went out of support in April 2022. For more information about the Node12 deprecation, please see [this blog post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

I am continuing to investigate just in case there's a problem elsewhere, but I am also marking this as requiring author action to see if the version upgrade helps.

**Comment by Laftek** [comment]
Hey Nick thanks for help! Unfortunately I am still getting the same error like before :/
