### ISSUE TITLE
Unexpected parent component rerendering

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#46044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While playing around with some code I noticed a behaviour I wasn't expecting. Here is the code in question:

### Parent Component

```razor
@page "/"

<button @onclick="ShowPrompt">Click me</button>

@if (_showPrompt)
{
    <SurveyPrompt Title="Testing" OnClose="Close" />
}

@code {
    private bool _showPrompt;

    private void ShowPrompt() => _showPrompt = true;
    private void Close() => _showPrompt = false;
}
```

### Child Component

```razor
<div class="alert alert-secondary mt-4">
    <strong>@Title</strong>
    <button @onclick="OnClose">Close</button>
</div>

@code {
    [Parameter] public string? Title { get; set; }
    [Parameter] public Action OnClose { get; set; }
}
```

When clicking the Close button in the child component, the child component causes a re-render in the parent component and is hidden. This is unexpected as that should only occur when either the child components parameter type is `EventCallback` or the handler in the parent calls `StateHasChanged`. 

Changing the child components code to this results in the expected behaviour and the child component isn't hidden.

```razor
<div class="alert alert-secondary mt-4">
    <strong>@Title</strong>
    <button @onclick="() => OnClose()">Close</button>
</div>

@code {
    [Parameter] public string? Title { get; set; }
    [Parameter] public Action OnClose { get; set; }
}
```

I don't know if this is a bug or not but it's not what I was expecting and I can't work it out. 

### Expected Behavior

Child components shouldn't cause re-renders of parents without defining parameters of type `EventCallback` or parent handlers calling `StateHasChanged`

### Steps To Reproduce

Update the `Index` component in a new Blazor project to the following code:

```razor
@page "/"

<button @onclick="ShowPrompt">Click me</button>

@if (_showPrompt)
{
    <SurveyPrompt Title="Testing" OnClose="Close" />
}

@code {
    private bool _showPrompt;

    private void ShowPrompt() => _showPrompt = true;
    private void Close() => _showPrompt = false;
}
```

Update the code for the `SurveyPrompt` component to the following:

```razor
<div class="alert alert-secondary mt-4">
    <strong>@Title</strong>
    <button @onclick="OnClose">Close</button>
</div>

@code {
    [Parameter] public string? Title { get; set; }
    [Parameter] public Action OnClose { get; set; }
}
```

Clicking the button in the index component shows the survey prompt. Clicking the Close button in the SurveyPrompt hides the Survey prompt. However, no StateHasChanged call has been issues.

### .NET Version

7.0.101

**Comment by javiercn** [comment]
Thanks for bringing this up @chrissainty.

This is an existing and rather obscure Blazor behavior. We try really hard to detect when the target of a delegate is a component that implements IHandleEvent.

What's happening is that the delegate you pass to `OnClose` is being pass-through to an event handler `@onclick` in the component.

As a result, we are constructing an EventCallback with `OnClose` as the target delegate. Since the event callback detects that `Delegate.Target` implements `IHandleEvent`, it routes the event through it, and since the parent component extends ComponentBase it triggers a render on the parent.

This is by design as we do not have a way to know, and the recommendation in this scenario is to do what you did to achieve your expected behavior, which is to call the parameter within a lambda.

In general, this is not a problem because most people desire the parent component to re-render (which is why it is the default behavior) and why in most cases the event is raised inside another method on the child component instead of being passed through directly.

I hope this helps clarify things.

**Comment by chrissainty** [comment]
This makes sense. Thanks for the explaination @javiercn 👍
