### ISSUE TITLE
RequireLocalPort extension for IEndpointConventionBuilder

### ISSUE THREAD

**Issue by goncalo-oliveira** [dotnet/aspnetcore#46057]
## Background and Motivation

I've found myself in a situation where I needed endpoints responding on different ports. Mainly one for public requests and another for internal requests (health checks for example). To do this I resorted to the `.RequireHost` extension method and did something similar to this

```dotnet
app.MapHealthChecks( "/healthz" )
    .RequireHost( "*:9001" )
    .AllowAnonymous();

app.MapGet( "/", () =>
{
   // ...
} )
.RequireHost( "*:8080" );
```

Locally things work properly and so I was surprised when deployed behind a reverse proxy I wasn't able to reach the public endpoint, but was able to reach the health check (internally).

Turns out that `RequireHost` uses the Host header, which behind a reverse proxy that may be the public host/port and not the one we're listening to. It took me a while to figure this out and it also took me quite a while to figure out how to create a filter to look at the `HttpContext.Connection.LocalPort` instead.

## Proposed API

In addition to better documentation on `RequireHost`, to clarify whoever is using it, I'd suggest having a `RequireLocalPort` extension. If I'm not mistaken, previous versions of `UseHealthChecks` had an optional `port` argument.

```csharp
namespace Microsoft.AspNetCore.Builder;

public static class EndpointConventionBuilderLocalExtensions
{
    public static IEndpointConventionBuilder RequireLocalPort( this IEndpointConventionBuilder builder, int port )
        => builder.AddEndpointFilter( async ( context, next ) =>
        {
            if ( context.HttpContext.Connection.LocalPort != port )
            {
                return Results.NotFound();
            }

            return await next( context );
        } );
}
```

## Usage Examples

The code above would be replaced with

```dotnet
app.MapHealthChecks( "/healthz" )
    .RequireLocalPort( 9001 )
    .AllowAnonymous();

app.MapGet( "/", () =>
{
   // ...
} )
.RequireLocalPort( 8080 );
```

**Comment by Tratcher** [comment]
Would be useful for YARP https://github.com/microsoft/reverse-proxy/issues/1240

**Comment by halter73** [comment]
Nice suggestion. In many cases the host matching is sufficient, but I can see proxies making that difficult. We'll want to make this a MatcherPolicy rather than an endpoint filter so endpoints with different port requirements don't conflict. For now, another workaround might be to continue using `.RequireHost("*:9001"), but add middleware before UseRouting() that sets `HttpContext.Request.Host` based on the local port.

I wonder if there's a more general feature here. What if you want to discriminate based on the IP address of thenetwork interface the connection came in on? Or named pipe? Maybe the metadata could contain the `System.Net.Endpoint` that should match the listen socket. That wouldn't work for requests arriving over any interface on a given local port though. If the metadata provided a predicate for the Endpoint, it could work, but that's not very declarative. Do you have thoughts on this @JamesNK?

**Comment by JamesNK** [comment]
Setting the host header seems like a simple solution.

I don't have any more thoughts off the top of my head. It's been a long time since I wrote host matcher 😄
