### ISSUE TITLE
Blazor Hotrelopad generic

### ISSUE THREAD

**Issue by timeshift92** [dotnet/aspnetcore#46100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

hello hotreload current doesn't  work with generic  for example
```razor

<MudTextField Label="First name" HelperText="Max. 8 characters"
                              @bind-Value="model.Username" For="@(() => model.Username)"/>
```
if i remove this code i need to relaod full project

### Describe the solution you'd like

i don't know =(

**Comment by javiercn** [comment]
@timeshift92 thanks for contacting us.

> if i remove this code i need to relaod full project

Do you mean that hot-reload breaks and you have to reload the project manually or just that it automatically reloads the whole page instead of just the component.

Could you provide a minimal repro project as a public github repository so that we can take a look at the concrete problem you are running into?

@tmat can you take a look?

**Comment by timeshift92** [comment]
yes one moment
![image](https://user-images.githubusercontent.com/13614530/212713429-ece24dc7-e5b3-4b08-82c1-ed6f566a5eda.png)

**Comment by timeshift92** [comment]
[BlazorMud.zip](https://github.com/dotnet/aspnetcore/files/10427100/BlazorMud.zip)

**Comment by timeshift92** [comment]
@javiercn 
https://github.com/timeshift92/hotreload-generic-error

**Comment by tmat** [comment]
Thanks for the repro.

The edit is blocked because it updates a *generated) generic method, which is not supported on .NET 7:

![image](https://user-images.githubusercontent.com/41759/212989797-4ab01f8e-eac9-4da2-83cf-78d739d2ca9e.png)

I have filed https://github.com/dotnet/runtime/issues/80749 on the runtime to add support.

@danroth27  @mkArtakMSFT @tommcdon @maddymontaquila 
 FYI

**Comment by danroth27** [comment]
Closing as hot reload support for generics is being tracked by https://github.com/dotnet/runtime/issues/80749.
