### ISSUE TITLE
Please find a way to put .net and other popular components in the CDN for wasm

### ISSUE THREAD

**Issue by aminsharifi** [dotnet/aspnetcore#46119]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

massive Blazor WASM size

### Describe the solution you'd like

Please find a way to put .net and other popular components in the CDN for decreasing Blazor WASM size
Applications must contain only the source code for themselves.

**Comment by javiercn** [comment]
@aminsharifi thanks for contacting us.

You have full control over the loading process of Blazor applications, and can, if you choose to do so, put your app dlls in a CDN. 

However, this is not going to yield the results you expect, since IL Linking will strip parts of the code and will create unique dlls tailored for each app, meaning that they won't be generally reusable.

As for us hosting the .NET dlls in a public CDN, we do not have plans to do so, as we've moved away from this practice even for other assets that we ship like our JS libraries.

**Comment by aminsharifi** [comment]
Like other .net solutions, it is expected from blazor that if .net was uploaded from one app and it was available in the browser cache, there is no need to load .net in another program.

**Comment by javiercn** [comment]
@aminsharifi thanks for the additional details.

> Like other .net solutions, it is expected from blazor that if .net was uploaded from one app and it was available in the browser cache, there is no need to load .net in another program.

Blazor use IL linking to reduce the size of the application, so the generated dlls are unique to your app and can't be reliably reused.

You can disable linking at the cost of a bigger initial download, and configure your Blazor application to load the framework dlls from a central location that you can reuse across applications and configure your server to make sure the browser caches those.

However, neither this nor hosting the unlinked dlls in our own CDN is something we plan to do.
