### ISSUE TITLE
Blazor .NET 7 CustomElements two-way binding/calls not working

### ISSUE THREAD

**Issue by marcus905** [dotnet/aspnetcore#46111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the .NET 7 release CustomElements nuget package, against a Blazor WASM or Server application, there is no way to use any kind of binding either to properties, or to callbacks/event receivers.

If I generate a MarkupString and include it in a blazor page, and in there I use a custom registered component, I can only set via Javascript some parameters therein, not read back its state and not even cause a callback to the main code.

### Expected Behavior

I expected the binding of methods and properties to behave in the same way as a standard blazor component.

### Steps To Reproduce

https://github.com/marcus905/TWBindingMinimalPoC

The sample fails in three ways:

- the custom text input does not render at all, see console, for lack of two-way binding
- the custom file input does not call the onchange event listener
- the button does not even appear in the render tree

### Exceptions (if any)

(web browser console)
Loaded 9.53 MB resources from cache
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Microsoft.AspNetCore.Components.Forms.InputText requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.
System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputText requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

### .NET Version

7.0.101

### Anything else?

.NET Core 7.0.2
VS Community 2022

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by javiercn** [comment]
@marcus905 thanks for contacting us.

We do not think your sample is complete.

**Comment by marcus905** [comment]
> @marcus905 thanks for contacting us.
> 
> We do not think your sample is complete.

Hi, what do you mean by that? The sample is complete as far as I can tell

**Comment by javiercn** [comment]
@marcus905 It seems that there is a missing commit. 

Where are the components that you are describing?

**Comment by marcus905** [comment]
> @marcus905 It seems that there is a missing commit.
> 
> Where are the components that you are describing?

https://github.com/marcus905/TWBindingMinimalPoC/blob/8fe6507d884b1c7e7411d9b2d8203c5a46b0d5ea/TWBindingMinimalPoC/Client/Program.cs#L10
https://github.com/marcus905/TWBindingMinimalPoC/blob/8fe6507d884b1c7e7411d9b2d8203c5a46b0d5ea/TWBindingMinimalPoC/Client/Program.cs#L11

For simplicity's sake I used builtin components and registered them in the client blazor app. The same happens with completely custom ones, though.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @marcus905.

This isn't a direction we plan to take. Blazor's custom elements functionality is limited by the capabilities that the custom elements Web API provides. For example, a two-way binding implementation requires information about how to mutate the bound variable and react to changes to its value. An HTML element attribute could provide a string representing the name of the variable to mutate (as shown in the repro you provided), but this isn't enough information for a two-way binding implementation.

That said, two-way binding can be simulated if you're willing to set the component's parameters as properties on the custom element, as is shown in [the docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#pass-parameters).

For example, since you can set `EventCallback` parameters on custom elements using the JavaScript property approach, it's possible to simulate a two-way binding:

_HTML_
```html
<button type="button" onclick="setCount(0);">Reset counter</button>

<my-counter></my-counter>

<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
    const counter = document.querySelector("my-counter");
    const setCount = (count) => counter.count = count;

    Blazor.start().then(() => {
        counter.countChanged = setCount;
    });
</script>
```

_Counter.razor_ (registered as the `my-counter` custom element)

```razor
<button type="button" @onclick="IncrementAsync">Current count: @Count</button>

@code {
    [Parameter] public int Count { get; set; }

    [Parameter] public EventCallback<int> CountChanged { get; set; }

    async Task IncrementAsync()
    {
        await CountChanged.InvokeAsync(Count + 1);
    }
}
```

Keep in mind that not all Blazor components will work as custom elements. If a component has parameter values that aren't JSON-serializable, or if it depends on some other unavailable state (cascading values, etc.), then it probably won't work as a custom element, especially if those parameters are required (which is the case for `InputFile` and `InputText`, as you saw in your repro). This limitation is by-design, since JSON serialization is the mechanism that we use to move data between the JS and .NET layers of an app.

Hope this helps!
