### ISSUE TITLE
Allow `NameClaimType`/`RoleClaimType` to be configured with the authentication configuration provider

### ISSUE THREAD

**Issue by glen-84** [dotnet/aspnetcore#46221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to set the `NameClaimType` using the `Authentication` section in configuration, but it doesn't appear to be supported.

### Describe the solution you'd like

Allow `NameClaimType`/`RoleClaimType` to be configured with the authentication configuration provider.

### Additional context

Workaround (configure in code):

```cs
builder.Services
    .AddAuthentication()
    .AddJwtBearer(
        "FusionAuth",
        options => options.TokenValidationParameters.NameClaimType = "preferred_username");
```

**Comment by captainsafia** [comment]
@glen-84 Thanks for reporting this issue (and other ones in the auth space)!

We were pretty intentionally about only binding certain properties when it comes to automatically resolving authentication options from config in .NET 7. The `TokenValidationParmaters` type has quite a few properties and we wanted to be intentional about what values we supported binding from. So for the moment, the workaround you showcased is the best approach for this.
