### ISSUE TITLE
Bad build Performance of project dependency chain with many StaticWebAssets

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#46272]
There is an issue with the static web asset handling within razor class libraries and blazor apps. When you add many web assets the build time that is consumed by processing them sums up for every project within the dependency chain. I've created a sample project with 1400 web assets. The project itself takes about4 seconds to build (which is already bad), but when I try to build the blazor app which has that project as a dependency on the 4th level of hierarchy, the build takes more than 12 seconds. 

here's a small repo that demonstrates the issue:
https://github.com/TFTomSun/RazorClassLibraryBuildPerformanceIssue

I think its a general AspNetCore StaticWebAsset handling issue, but I am not 100% sure.

**Comment by TFTomSun** [comment]
@javiercn As you can see especially in the incremental build is that the total build time is 2.6 seconds which is much more than the sum of the executed tasks. The point here is, that the evaluation phase takes super long and increases by each project that you put in between the dependency chain.

**Comment by javiercn** [comment]
> So basically there's nothing to do in an incremental build, but that nothing still costs 2.6 seconds.

I do not know if there is something going on here, but what I can think I can tell for sure (after taking another look) is that this is not related to static web assets.

From what I can tell at the evaluation phase a significant amount of time is spent inside the .NET SDK targets/props. My analysis might have gaps, but from what I see in the profile evaluation, this is not related to static web assets.

![image](https://user-images.githubusercontent.com/6995051/218087979-cd77d483-0ac5-4632-a61c-1676faaadf67.png)

The other issue that references this one mentions `**\*` patterns, and there is definitely a `wwwroot\**\*` pattern inside razor class libraries and web projects, but I can't not see how that would impact anything outside of the project with many assets.

To further confirm this, I have disabled static web assets from a build and it still has long evaluation times, so I believe this is due to the large amount of files present, which is not something we control.

If you want to check this out yourself, I suggest you build the `RazorClassLibrary1\DirectConsumerClassLibrary.csproj` with `dotnet build /p:StaticWebAssetsEnabled=false /bl:noassets.binlog /profileevaluation` and you'll see that there are similar timings.

As to what is happening here, I do not know if this is a bug or simply the fact that systems can't scale indefinitely. I would suggest you rise this up with the MSBuild folks as at they are going to be in the best position to help you.
