### ISSUE TITLE
Identity schema versioning design / infrastructure

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#46274]
## Background and Motivation

We haven't changed the identity database schema in many years, the motivation is to make this easier and have the infrastructure to do this regularly.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Identity;

public class IdentityStoreOptions
{
      // The schema version for the store, the default is 0.0 which leaves it up to the store to determine what version should be used.
+    public Version SchemaVersion { get; set; } = IdentityVersions.Default;
}

+ public static class IdentityVersions
{
      // Today's version
+    public static readonly Version Version1 = new Version(1, 0);
  
     // New net8 schema version
+   public static readonly Version Version2 = new Version(2, 0);}

      // Default up to stores to interpret
+    public static readonly Version Default = new Version(0, 0);

}

namespace Microsoft.AspNetCore.Identity.EntityFrameworkCore;

// User only dbcontext base
public class IdentityUserContext<...> : DbContext 
{
+    public Version SchemaVersion { get; } // Sugar for returning StoreOptions.SchemaVersion
}

```

## Usage Examples

```csharp

            .AddIdentity<IdentityUser, IdentityRole>(o =>
            {
                // Select the new net8 schema
                o.Stores.SchemaVersion = IdentityVersions.Version2;

                // Set an arbitrary version that their store understands
                o.Stores.SchemaVersion = new Version(3, 0);
            })
```

## Alternative Designs

Could add feature flags to opt into more granular schema changes instead of trying to coordinate versions, i.e. enableTokenSupport but this seems like it would lead to an explosion of flags over time and harder to manage in the long run..

**Comment by halter73** [comment]
I like the IdentityStoreOptions and IdentityVersions, but maybe an enum similar to [PasswordHasherCompatibilityMode](https://github.com/dotnet/aspnetcore/blob/2cd5873673d6c9858625baf80730507e428a6bad/src/Identity/Extensions.Core/src/PasswordHasherCompatibilityMode.cs#L6-L20) like you suggested would make more sense than using than a `Version`. Or does it make sense to do `>=` and similar checks? Will there be any kind of backward or forward compatibility?

I'm also not sure about the IdentityUserContext changes. Isn't the important thing just to expose the current schema version? Could this better be achieved by adding a non-virtual protected getter?

```diff
public class IdentityUserContext<...> : DbContext 
{
+    protected SchemaVersion SchemaVersion { get; }
}
```

And then instead of overriding `OnModelCreatingVersion1` and `OnModelCreatingVersion2`, you just check the `SchemaVersion` in the existing `OnModelCreating` overrides if you care.

```csharp
    protected virtual void OnModelCreating(ModelBuilder builder)
    {
		base.OnModelCreating(builder);

        if (SchemaVersion == SchemaVersion.Version2)
        {
            // Schema 2 follow up
        }
        else
        {
            // Schema 1 follow up
        }
    }
```

@dotnet/efteam Do you have any thoughts on the actual schema changes?

**Comment by halter73** [comment]
API Review Notes:

- We need to be able to do comparison like `>=` with the version, so we don't want an enum. Should it be an `int` instead of a `Version` though? If we want to do a minor version for fixing something in servicing, the minor version will be helpful.
- Do we care about allocating the static default versions at startup? Everyone using identity would pay this cost at startup. It's super small though, and we don't micro-optimize at that level.
- Do we like `Version(0, 0)` instead of `null` as the default value? Sure.
- Should it be `IdentityVersions` or `IdentityVersion` or `IdentityConstants`?  `IdentitySchemaVersions`? We have `HttpVersion` and `HttpProtocols`. Let's do `IdentitySchemaVersions`.

API Approved!

```diff
namespace Microsoft.AspNetCore.Identity;

public class IdentityStoreOptions
{
     // The schema version for the store, the default is 0.0 which leaves it up to the store to determine what version should be used.
+    public Version SchemaVersion { get; set; } = IdentityVersions.Default;
}

+ public static class IdentitySchemaVersions
+ {
+    // Today's version
+    public static readonly Version Version1 = new Version(1, 0);
+    // New net8 schema version
+    public static readonly Version Version2 = new Version(2, 0);}
+    // Default up to stores to interpret
+    public static readonly Version Default = new Version(0, 0);
+ }

namespace Microsoft.AspNetCore.Identity.EntityFrameworkCore;

// User only dbcontext base
public class IdentityUserContext<...> : DbContext 
{
+    public Version SchemaVersion { get; } // Sugar for returning StoreOptions.SchemaVersion
}
```
