### ISSUE TITLE
Blazor United feedback (it's good)

### ISSUE THREAD

**Issue by simonziegler** [dotnet/aspnetcore#46292]
@SteveSandersonMS [tweeted his Blazor United demonstration](https://twitter.com/stevensanderson/status/1617951942873088001?s=20&t=7FfsZ-8WFUPrGLS_4AopZQ), and he invited comment on GitHub.

My only comment is "yes please, in full".

In one stroke this demo answers a bunch of wish-list items I have for the future of how best to render my web app and to integrate it within a broader website. Achieving the results shown in the demo in that or a similar manner would be a wonderful result.

**Comment by syedqutub** [comment]
Loved the demo and got goose bumps when say how easy it was to switch the rendring modes without losing the component based design of blazor. But would it ve possible to dynamically switch from server to wasm mode as soon as wasm binaries all download in Auto mode?

**Comment by tstockwell** [comment]
Apologies in advance if adding to this issue is bad form, but here goes :-)....

First, Blazor is amazing and the ability to make Blazor pages routable is awesome!

However, as a developer that's done Razor Pages and Blazor I prefer creating templates with Razor Pages because I find them way more easy to maintain and create.  And that's mostly due to tag helpers.
For now, I prefer to stick to simpler Razor Pages with a small amount of client-side behavior, I avoid Blazor for larger apps because I find Blazor too difficult to create a lot of pages and too difficult to maintain.
From my perspective, it would be necessary for Razor Components to support tag helpers before I would consider Razor Pages and Razor Components to be integrated.
This is because I use tag helpers all the time to apply cross-cutting changes to my apps and to generate UI elements based on model attributes.

For example, here's the form from StarRatingReviews.razor (in the demo video around 3:48)...
```
<EditForm method="post" class="review-editor" EditContext="EditContext" enhance>
	<StarRating @bind-Value="EditContext.Model.Rating"/>
	<ValidationMessage For="@(() => EditContext.Model.Rating)"
	<InputTextArea rows="5" name="text" placeholder="Write a review" @bind-Value="EditContext.Model.Text"/>
	<ValidationMessage For="@(() => EditContext.Model.Text)"
	<button type="submit">Submit<button/>
<EditForm>
```
For the sake of argument let's say that I accept that I should rewrite everything in Razor Components, consider what happens down the road when I want to make a change to that <button>.
Let's suppose that I want to change all the submit buttons on all my forms in all my applications to be disabled until the form validates.
Using Blazor will force me to make these changes to all my templates myself.
However, I could theoretically do that with a tag helper that could render into a Razor Component, the tag helper could add the new behavior into the page, maybe something like this...
```
<MyButtonHelper Context='bhelper'>
<button type="submit" disabled="@bhelper.IsContainingFormValid"/>
</MyButtonHelper>
```
Adopting Blazor and Razor Components would force me to make these kinds of changes to templates myself, and I'd also have to give up my custom model attributes.

I really really really want to go all in on Blazor, but I'm concerned that doing so will make my life more difficult, so the lack of tag helper support will be a barrier to adoption for me.

**Comment by juepiezhongren** [comment]
hope that hybrid mode will be included

**Comment by Ponant** [comment]
Agreed this is a very nice way and intuitive way to go.

**Comment by snow-jallen** [comment]
Yes, yes, please! Htmx is probably the next best thing but I like this WAY more. Very much looking forward to future development along these lines.

**Comment by PeterDraex** [comment]
`WebComponentRenderMode.Auto` mode could significantly speed up first page load (time to interactive) of existing WebAssembly apps, as it would not be necessary to wait for all assemblies to download before interaction. That would be a relevant and significant improvement.

However, **if this disables prerendering and so makes the site not indexable, it can't be used on any site that requires SEO**. Therefore, if you can make it happen without breaking SEO, please, deliver it asap 💚! If not, rather focus on other improvements.

**Comment by juepiezhongren** [comment]
> Loved the demo and got goose bumps when say how easy it was to switch the rendring modes without losing the component based design of blazor. But would it ve possible to dynamically switch from server to wasm mode as soon as wasm binaries all download in Auto mode?

I think auto mode is only for page re entering. What we need is another mode, autoWithSwitch. Considering the cost for switch, wasm side data sync with server side needs a period, switch status and view options r required. I suggest auto and autoWithSwitch are 2 different modes.

**Comment by mammadkoma** [comment]
How to add RenderMode.Auto to our .net7 wasm projects?

**Comment by d3c0d3d** [comment]
@mammadkoma Wait for the next .NET Preview version, maybe there's something there.

**Comment by mammadkoma** [comment]
If we use MudBlazor components and then use RenderMode.Auto, it loads first the page server side then after download the MudBlazor components and other wasm dll load and work on client browser?

**Comment by d3c0d3d** [comment]
@mammadkoma Only the future will tell, wait for the next updates.
_Tip: Tomorrow, February 14th there will be a live on the dotnet channel on youtube with more information about the project who knows there you can ask more questions directly to the Blazor United developers._
