### ISSUE TITLE
OutputCacheMiddleware throws NullReferenceException when trying to serve requests from cache

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/aspnetcore#46333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I saw in our logs occasional `NullReferenceException`s being thrown by OutputCacheMiddleware but wasn't able to replicate that error locally until I also added the Rate Limiting feature. Now I'm able to consistently replicate the exception.

Just clone the sample project and hammer it with requests, and some of the queued requests will fail with a 500 error and a `NullReferenceException`. I have the queue set to 5, and some will fail and some will succeed. E.g. in the test I just did the first queued request failed failed, then the next two succeeded, then the last two also failed.

It seems to be specific to the case that the request is not able to be cached because cookies were set as part of the request.

I don't believe this error is unique to `RateLimitingMiddleware` because I did see this error in our logs before adding that. I'm not able to replicate it in the sample project below without using the RateLimitingMiddleware.

### Expected Behavior

`OutputCacheMiddleware` should never throw a `NullReferenceException`

### Steps To Reproduce

Sample project: https://github.com/DanielStout5/OutputCacheNullReferenceException

### Exceptions (if any)

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.TryServeCachedResponseAsync(OutputCacheContext context, OutputCacheEntry cacheEntry, IReadOnlyList`1 policies)
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.InvokeAwaited(HttpContext httpContext, IReadOnlyList`1 policies)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

7.0.101

### Anything else?

ASP.NET Core 7.0.2

Visual Studio 2022

**Comment by sebastienros** [comment]
I think I identified two bugs:

- First the body can be null (empty body) which is what the sample is showing. We need to handle that case for queries that could be cached. But this wouldn't be an issue in that sample without the next bug because the `Set-Cookie` header should prevent the entry from being cached in the first place.
- Second bug is related to Locking. We are not checking if the `AllowStorage` property is modified by the first request after the initial check:

Here we check if the current request can be cached: https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L120

Imagine this is the first request, it will be actually executed while others "in the queue" will wait for it to finish (this is why Rate Limiting is exacerbating this bug, it's easier to get requests all coming at the same time).
The `executed` boolean is `true` for the first request and will be returned to the http client, while the other awaiting requests will go to https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L136 to get served the same cached response entry. However, the first request might have been invalidated by a policy in the `ServeResponseAsync` event, so it shouldn't be cached. And it won't be cached, but the other requests awaiting are not going through the same re-validation. In the sample the response has a `Set-Cookie` so it should not be cached (`AllowCacheStorage` is set to `false` by the default policy). I believe we should check for `AllowCacheStorage` in `TryServeCachedResponseAsync`. It's also called when an entry is retrieved from cache, but I believe it should/may also be set to `true` anyhow.

@DanielStout5 best repro ever, thank you, it shows up because of two bugs that collide, and it would be hard to reproduce without rate limiting.

**Comment by sebastienros** [comment]
I spent some time trying to reproduce the issues in unit tests and after having a hard time getting in the same state, I now realize that the sample is actually not something that we would expect to see:
- The middleware setting a cookie is executed before rate limiting
- Rate limiting is executed before output caching

In a ideal scenario this should be the order:
- Output Cache
- Rate limiting
- Application middleware

@DanielStout5 Is there a reason you didn't setup the middleware in this order?

**Comment by DanielStout5** [comment]
@sebastienros it might work in that order. I did need output cache and rate limiting to be after UseAuthentication since they need to exclude users in certain roles, and I also wanted them to be after UseStaticFiles.

My rationale for having the cookie setting middleware be above the output cache was that I wanted to make sure it wouldn't serve a cached response to the requests that would normally be setting a cookie. I'll try moving it after UseOutputCache and see if that works

**Comment by DanielStout5** [comment]
@sebastienros I tested this and as I originally expected, I can't have my application middleware that sets the cookie **after** `UseOutputCache` because in that case, it serves up cached responses that don't set the cookie.


I did try this order:

- UseCustomCookieMiddleware
- UseOutputCache
- UseRateLimiter

And there are two issues with this ordering:

1. This doesn't fix the issue. I'm still able to replicate the NullReferenceException inside OutputCacheMiddleware with the above order. I believe the issue occurs at the time the cache entry expires.
2. Cached responses are not rate limited. This isn't the end of the world but my intent was for all requests to be rate limited, even ones that are being served from the cache.

**Comment by BrennanConroy** [comment]
Triage: Let's strongly consider backporting this

**Comment by sebastienros** [comment]
PR submitted, and found a simpler repro

```c#
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOutputCache(bld =>
{
    bld.AddBasePolicy(opt =>
    {
        opt.Expire(TimeSpan.FromSeconds(10)).SetLocking(true);
    });
});

var app = builder.Build();

app.Use((ctx, next) =>
{
    ctx.Response.Cookies.Append("Test", "Value");
    return next.Invoke();
});

app.UseOutputCache();

app.Use(async (HttpContext ctx, RequestDelegate next) =>
{
    await ctx.Response.WriteAsync("OK");
});

app.Run();

```
