### ISSUE TITLE
Security review for full stack web UI with Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46396]
This will include an analysis of all the threats that apply to full stack Blazor web apps, which include those that apply to Blazor Server applications + those that apply to server rendered applications.

**Comment by leastprivilege** [comment]
e.g. how this will integrate with the backend for frontend pattern (BFF) which is the recommended security pattern for web-frontends

**Comment by Ponant** [comment]
I am switch from `Lax` to `SameSite.Strict` for cookies in a razor pages web app in order to implement BFF with Azure B2C with some Blazor components. The oidc pipeline needed to be tweaked to allow for this scenario to work properly at the `/signin-oidc` url.

**Comment by brockallen** [comment]
> e.g. how this will co-exist with the backend for frontend pattern (BFF) which is the recommended security pattern for web-frontends

More concretely, how will you support session management over the web socket connections? Authentication session cookies often need to be updated and/or re-issued throughout the user's activity, and web sockets are not very friendly to such things.

Was there ever anything done in SignalR around this?

It would be easy to say that you just don't do anything or try to provide a solution, since over web sockets you can't issue HTTP response headers to the browser (such as Set-Cookie). But if you make the framework so easy to establish a web socket connection (without full understanding of the developer using said framework) this will potentially introduce problems in the app.

**Comment by javiercn** [comment]
> e.g. how this will co-exist with the backend for frontend pattern (BFF) which is the recommended security pattern for web-frontends

For context, this issue is not about auth specifically, but about other common threats we'll have to deal with (CSRF, etc.). Auth will get its own separate treatment which is outside of the scope of this issue.
