### ISSUE TITLE
Fix template tests to run in CI

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#46430]
Following tests are failing in the CI only (works fine locally), seems to be due to searching for the `StaticFiles` dependency. Unclear what exactly is pulling this dependency.

- [ ] `BlazorWasmHostedTemplate_Works`
- [ ] `BlazorServerTemplate_IdentityWeb_BuildAndPublish`
- [ ] `BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB`
- [ ] `BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB`

**Comment by TanayParikh** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=158385&view=results

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/45682

**Comment by halter73** [comment]
We missed one:

https://github.com/dotnet/aspnetcore/blob/f9121bc3e976ec40a959818451d126d5126ce868/src/ProjectTemplates/test/Templates.Blazor.Tests/BlazorWasmTemplateTest.cs#L62-L65

We also skip the only other Playwright test in the entire assembly:

https://github.com/dotnet/aspnetcore/blob/f9121bc3e976ec40a959818451d126d5126ce868/src/ProjectTemplates/test/Templates.Blazor.Tests/BlazorWasmTemplateTest.cs#L26-L28

That issue is at least open, but it says the test is "Quarantined" when in fact it's really skipped.

**Comment by MackinnonBuck** [comment]
Resolved by #54606
