### ISSUE TITLE
Generating new 2FA recovery codes fail when EFCore has QueryTrackingBehavior.NoTracking set globally

### ISSUE THREAD

**Issue by aha-tech** [dotnet/aspnetcore#46464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For efficiency, we have globally disabled change tracking for EF Core by setting 
```
builder.Services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseSqlServer(connectionString);
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
            });
```
In `Startup.cs`. This unfortunately prevents ASP.NET Identity from updating the database when generating new 2FA recovery codes. It does not seem to affect any other areas of ASP.NET Identity.

Temporarily turning on query tracking before generating the new recovery codes fixes the issue.

### Expected Behavior

ASP.NET Identity should override global query tracking behavior when performing operations that relies on query tracking.

### Steps To Reproduce

1. Create a new ASP.NET Core Web App project with Individual Accounts for Authentication type.
1. Add `options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);` to `Startup.cs`.
1. Run the application (remember to create the database first)
2. Register a user and log in
3. Enable 2FA, noting the Recovery codes
4. Generate new recovery codes
5. Log out
6. try to log in again using the second set of recovery codes -> failure (or have a look in the DB and see that the recovery codes are still just the originals)

Example project:
https://github.com/aha-tech/QueryTrackingTest

### .NET Version

6, 7

**Comment by captainsafia** [comment]
@aha-tech At the moment, identity only supports EFCore integration with `QueryTracking` turned on. The flag is only recommended for scenarios where the data is read-only. You can see this documented in the EFCore docs [here](https://learn.microsoft.com/en-us/ef/core/querying/tracking#no-tracking-queries)). Since identity requires writes to the DB, it's not advised to turn this on for these scenarios.

Why do you have this behavior enabled?
