### ISSUE TITLE
IdentityFramework:  VerifyUserTokenAsync() failed with purpose: "ResetPassword" for user.

### ISSUE THREAD

**Issue by prashantgham** [dotnet/aspnetcore#46467]
I am using  Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1. for authentication.  

Reset password is failing when there are more than one AKS pods running. I am getting above error while verifying the token generated with userManager.GeneratePasswordResetTokenAsync(), Reset token works properly in local and in azure when single container is running.  Even reset password succeed if I generate the token and reset it within same request.

Password reset failing when request goes to different pod (other than one which generates the token).  Is userManager uses the any of the pod specific key/data to validate token?  We have SecurityStamp, ConcurrencyStamp fields present in UserTable. 

We are using the default token provider: 
```csharp
  builder.Services.AddIdentity<UserEntity, IdentityRole>(options =>
    {
        options.Password.RequiredLength = 7;
        options.Password.RequireDigit = false;
        options.User.RequireUniqueEmail = true;
        options.Lockout.AllowedForNewUsers = true;
        options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(20);
        options.Lockout.MaxFailedAccessAttempts = 3;
    })
    .AddEntityFrameworkStores<MembershipContext>()
    .AddDefaultTokenProviders(); 
```

**Comment by captainsafia** [comment]
Triage: @prashantgham You are likely running into this issue because you data protection keys need to be shared across all the pods in your cluster. You can check out [these docs](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#persisting-keys-when-hosting-in-a-docker-container) for help on how to do this.
