### ISSUE TITLE
Set dynamically @page

### ISSUE THREAD

**Issue by hesolar** [dotnet/aspnetcore#46529]
## Summary

I want to develop a page that can be set dynamically , .

@page attribute only accepts hardcoded string like:
@page "hello"
@page "hola"

## Motivation and goals

Actually would be nice to do set dynamically @page tag without hardcoding url, i think parameters approach arent good solution.
Suppose i have a list of posible url pages in a list.
Why cant set dynamically url depending on that list ?

## In scope

1. Set dynamically @page tag not only using  @page "/hardcodedstring"
2. Allow @page directive passed as parameter, for example in a list 

## Risks / unknowns
Perhaps is dangerous to allow user set url with param maybe an object can be null or insecure.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).
I think this question is the best aproach right now to the problem
It uses parameters to get the efect of a dynamicall url.

https://stackoverflow.com/questions/65627464/how-to-use-dynamic-route-parts-in-blazor-wasm-app

**Comment by SteveSandersonMS** [comment]
> Allow @page directive passed as parameter, for example in a list

I'm not sure what that would mean. Why would the child pages be being rendered if they don't match the current URL? What does it mean to render a list of `@page` components? Something like the following?

```razor
@foreach (var product in Products)
{
    <ProductPage Product="@product" />
}
```

... but this would actually render all of them. Is you intent that we change the meaning of the `@page` directive so that it causes a component to skip rendering itself if the current URL doesn't match? Even if we did that it would be very inefficient because you might have a million products so this would be walking through that whole list and doing empty renders for everything except the one product matching the URL.

> Why cant set dynamically url depending on that list ?

I'm not sure where that list would be coming from, given that there isn't a parent component. And it means we can't have a fixed route table, which would destroy the efficiency of routing.

Altogether I think there is probably a different approach that would be more suitable for your scenario, which is if we changed `Router` to allow customizing the mapping from URL string to (component, parameters) selection. We could either allow subclassing `Router` and introduce a virtual method for it, or we could just have some new optional `Router` parameter called `Func<string, RouteData> PageMatcher` or similar. Then you could have arbitrary runtime logic for selecting which component acts as the page for a given URL, and still fall back on default matching in most cases.

**Comment by hesolar** [comment]
> I'm not sure what that would mean. Why would the child pages be being rendered if they don't match the current URL? What does it mean to render a list of @page components? Something like the following?

The idea of a list of parameters as you said with the products wasnt my idea exactly .
But as you said its a negative consequence.

I was thinking about render a url for example depending on language more like fixed for example in a resx file.

```
@inject IStringLocalizer<Resources> AllResourcesResolver
@page "/{Resources["WelcomePage"]}"
```
So this way i can have a fixed table route depending of a language.
I dont know if this is a bad idea but  i was thinking about this:

![image](https://user-images.githubusercontent.com/43806203/218555083-a6dd7735-15de-4f59-9190-31ed3552de88.png)

Anyway i think that any of the alternatives that you propose would be great since they would provide some flexibility to the @page directive 
Thanks for your time and congratulations for the work you do!
