### ISSUE TITLE
Kestrel gives 401 for large file uploads via POST request

### ISSUE THREAD

**Issue by Vivek-abstract** [dotnet/aspnetcore#46566]
Hi team, 

There's a weird error in Kestrel for the following scenario:
1. Windows authentication is enabled
2. Large file upload via HTTP post request 
3. Service is hosted as Kestrel windows service.

When I hit a POST endpoint with a large file, it initially sends a 401 status as the browser doesn't send the credentials in the first request. This is fine as it's how Kerberos works, but the issue is that Kestrel starts draining the request body as the browser is still uploading the file to it.
As Kestrel has a request drain timeout of 5 seconds, it is unable to do so within 5 seconds because of the large file. It closes the connection abruptly and the 401 status doesn't reach the browser. 
As a result, the browser doesn't send the consequent request with credentials.

For small files, it works fine as Kestrel is able to drain the request body within 5 seconds and the 401 status code reaches the browser.

The issue only occurs for large files (>30mb). I have the request limits etc configured so it's not failing due to the large file, it's failing because of the request drain timeout and Kestrel closing the connection.

Is there any way I can solve this issue? As a temporary fix we had to disable authentication for this method with AllowAnonymous.

I am not sure if this is the right forum to post this issue. If it's not, kindly let me know where should I post it.

**Comment by ShreyasJejurkar** [comment]
Hi Vivek, 
You can try applying `DisableRequestSizeLimit` attribute to your POST action method that accepts parameters. 

DisableRequestSizeLimitAttribute -> https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.disablerequestsizelimitattribute?view=aspnetcore-7.0

**Comment by Vivek-abstract** [comment]
I have tried this and the other RequestSizeLimit attribute, but it doesn't fix the issue.

**Comment by Tratcher** [comment]
> @Tratcher Chris Ross FTE isn't this what expect 100 continue is for?

Sortof. Windows auth sucks for uploads. The trouble here is that the client promised the server a certain Content-Length worth of request bytes so regardless of the status code it must send those bytes or close the connection. Enabling Expect 100-continue on the client can help because it gives the client ~600ms to observe the status code before it starts uploading. If the client gets a 401 fast enough it can choose to close the connection without starting the body. Once it's started uploading it usually won't check for a response until it's done. Kestrel's 5s drain timeout aggravates the situation and is not configurable. 

Mitigations:
- Enable Expect 100-continue on the client
- Try the same scenario with our Http.Sys server, it's drain behavior might be different enough to help.
- Send a GET or HEAD request first to authenticate the connection.
- Use windows auth to sign in, but then issue a cookie for future operations like the upload. Cookies are more predictable than connection state.
