### ISSUE TITLE
IWebHostBuilder.Build fails with System.InvalidOperationException: 'A public method named 'ConfigureAutomatedTesting' or 'Configure' could not be found in the 'Program' type.'

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/aspnetcore#46611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to start a Razor Pages project that uses top-level statements in program.cs in a in-memory IWebHost the following error occurs 

System.InvalidOperationException: 'A public method named 'ConfigureAutomatedTesting' or 'Configure' could not be found in the 'Program' type.'

![image](https://user-images.githubusercontent.com/18427214/218502956-69b65018-8e82-4b5e-a45e-c02b06707dfd.png)

### Expected Behavior

The in-memory web server should be started and playwright tests run

### Steps To Reproduce

I have added a failing example here https://github.com/carlblanchard/InMemoryPlaywrightDemo  run the test When_ClickEmployeeMenuOption_Then_EmployeesPageDisplayed_Chrome 

### .NET Version

.net 6

### Anything else?

Working version in net 3.1 https://github.com/JD-Innovensa/InMemoryPlaywrightDemo

**Comment by captainsafia** [comment]
If you're using top-level statements, you don't need to invoke `UseStartup` [here](https://github.com/carlblanchard/InMemoryPlaywrightDemo/blob/dc056ab6fae4691e575f7957278ca53e73969084/test/AutomatedTesting/Factory/AutomatedTestServerFactory.cs#LL79C10-L79C44) since there is no `Startup` class in the target application.

You'll also want to make sure you call the base `CreateWebHostBuilder` in your method like so:

```csharp
var builder = base.CreateWebHostBuilder();
 _webhostConfiguration?.Invoke(builder);
return builder;
```

As a general note, instead of `TStartup` you'll want to provide your `WebApplicationFactory` with the entrypoint which is your `Program`.
