### ISSUE TITLE
Memory leak in Blazor Server InputFile

### ISSUE THREAD

**Issue by bbalke** [dotnet/aspnetcore#46656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a Razor component that includes an <InputFile multiple OnChange="@OnImportFilesChanged"/>.

My code function contains the following which is similar to the code in [Learn](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=server).

    public async Task OnImportFilesChanged(InputFileChangeEventArgs e)
    {
        foreach (var file in e.GetMultipleFiles(8))
        {
            try
            {
                var stream = file.OpenReadStream(file.Size);
                byte[] buffer = new byte[1024 * 8];
                while (await stream.ReadAsync(buffer) > 0) ;
                stream.Close();
                stream.Dispose();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debugger.Break();
            }
        }
    }

I uploaded 8 files that were between 15MB and 48MB each. At the conclusion of the OnImportFilesChanged, my memory usage had increased by the size of the files.  I tried to force garbage collection but that did not change it.

This seems to be similar to [dotnet/aspnetcore#35540](https://github.com/dotnet/aspnetcore/issues/35540) but that issue was for WASM.

### Expected Behavior

I would have expected to memory usage to returned to about the same as it was before reading the files.

### Steps To Reproduce

1. Create Blazor Server project
2. Add page as Razor Component
3. Add <InputFile multiple OnChange="@OnImportFilesChanged"/> to page.
4. Add @code method with following     public async Task OnImportFilesChanged(InputFileChangeEventArgs e)
    {
        foreach (var file in e.GetMultipleFiles(8))
        {
            try
            {
                var stream = file.OpenReadStream(file.Size);
                byte[] buffer = new byte[1024 * 8];
                while (await stream.ReadAsync(buffer) > 0) ;
                stream.Close();
                stream.Dispose();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debugger.Break();
            }
        }
    }

### .NET Version

6.0.13

**Comment by javiercn** [comment]
@bbalke thanks for contacting us.

This is very likely not a memory leak unless:
* You are able to cause an OutOfMemoryException on the application.
* Proof that Blazor is holding on to the memory.
* Proof that your app is not holding on to the memory.

If you are able to provide a repro project and traces that proof the three things above, we will be happy to take a look at it. Otherwise, we have already tested these areas thoroughly and we have not found evidence of a leak, so it is very likely there is something your app is doing or there is a gap between the framework understanding of a memory leak and your definition for it.

A few important notes to take into consideration when measuring memory:
* Are you running the published version of the app?
* Has the app been published in Release mode?
* Have you made sure to not attach a debugger to the running app?
* Did triggering a Gen 2 forced, compacting collection `GC.Collect(2, GCCollectionMode.Aggressive | GCCollectionMode.Forced, blocking: true, compacting: true))` frees the memory?
* Is your app allocating objects on the large object heap?
* Did you test the memory growth after the app warmed up? Typically, there are caches that get populated when code executes for the first time that add a constant amount of memory to the footprint of the app.

Another key points of information that you might be missing are:
* Server GC will not trigger garbage collections until it determines it is absolutely necessary to do so, to avoid freezing your app, and considers that your app is the only thing running on the machine (so it can use all the memory in the system).
* Even when a GC is triggered, .NET will hold on to the memory instead of returning it to the OS immediately as it is very likely that it will reuse it the near future. This avoids committing and decommitting memory constantly, which is expensive.
* You'll see this reflected if you use dotnet-counters because you'll see the GCs happen and the amount of used memory go down to 0, but you will not see the working set counter decrease (that's the sign that .NET is holding on to the memory to reuse it).

You can see a lot of the statistics about how memory in your app is behaving using dotnet-counters. For more information see [here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#examples-1)

You can read more about it [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-7.0#blazor-server-memory-model)
