### ISSUE TITLE
blazor wasm duplicated requests when using individual account auth

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#46658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I did file new project and used the blazor wasm template, not asp hosted. After that, the only change I made was to plug in the authentication information. ln the network tab of chrome, I see two requests for several files and neither is cached: app.css, AuthenticationServices.js, blazor.webassembly.js, styles.css, bootstrap.min.css, etc. I want to understand why these duplicated requests are necessary. The initiator is `index` and `login-callback` for each of these. I have not been able to find anything through internet searching. I have included a screenshot

### Expected Behavior

I expected to not see duplicated requests.

### .NET Version

7.0.2

### Anything else?

![chrome-network](https://user-images.githubusercontent.com/32482832/218882085-f6a7935b-1c4c-4f95-9b35-8d56ff3271d9.png)

**Comment by javiercn** [comment]
@Krangth thanks for contacting us.

The auth system tries to automatically determine if there is an existing user session on the server and restore the authentication state on the app, for that it uses a silent sign in flow (that's part of OIDC) that uses an iframe to make that check in the background. The other requests that you are seeing are for the page temporarily loading inside a hidden iframe.

You are seeing multiple requests because you have disabled the browser cache on the network tab, if you don't disable it, you should either not see duplicate requests, see them come back as 304, or in the case that you have incorrectly configured the caching headers on the server, the requests duplicated.

**Comment by Krangth** [comment]
Thank you. I forgot I had disabled the cache while looking at app first load times.
