### ISSUE TITLE
Blazor component events not trigger in MVC partial view when calling via javascript

### ISSUE THREAD

**Issue by quocduong** [dotnet/aspnetcore#46663]
Dear guys,

I am facing with an issue Blazor component events when opening partial view on a modal.

The same question from here: https://github.com/dotnet/aspnetcore/issues/20332 but was not resolved.

It works correctly when I add the component or render partial in mvc pages.
There is my code: https://github.com/quocduong/BlazorEventDemo.git

EDITED 17/02/2023: Github minimal repo: https://github.com/quocduong/BlazorEventDemo.git

```


cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/17531

**Comment by quocduong** [comment]
I have implement a minimal repository to you guys can pull and reproduce the issue:
https://github.com/quocduong/BlazorEventDemo.git

Many thanks.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @quocduong.

Statically-rendered Blazor Server components only work correctly when added to the page before `blazor.sever.js` performs its startup sequence. However, it looks like your modal mechanism currently works by using the AJAX load() function to dynamically inject a partial view's contents directly onto the page _after_ the initial load. Because `blazor.server.js` has already scanned the document for statically-rendered components by that point, only the prerendered output from the Blazor component will exist on the page.

In order to dynamically render Blazor components to the page from JavaScript, you'll need to use the `Blazor.rootComponents` JavaScript API. See [this docs page](https://learn.microsoft.com/aspnet/core/blazor/components/?view=aspnetcore-7.0#render-razor-components-from-javascript) for more information.

Hope this helps!
