### ISSUE TITLE
Reduce the size cost of unused protocol support

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspnetcore#46681]
We know there are use cases for Kestrel where things like HTTP/2 or /3, or even HTTPS, aren't necessary. For instance, you may not want HTTPS for a server that's run behind a TLS-terminated proxy.

Today, a published app that doesn't use TLS still carries around some extra dependencies that are used only for TLS support. We should explore what we can do to minimize this cost.

**Comment by Tratcher** [comment]
Step 1: Measuring. Do we have a sense for how big each of these components might be?

**Comment by danmoseley** [comment]
I believe @eerhardt measured it for HTTPS

**Comment by eerhardt** [comment]
Here are the current published .exe size numbers for the `dotnet new api -aot` app using the Minimal API source generator:

**Windows** - `10.6 MB (11,178,496 bytes)`
**Linux** - `13.5 MB (14,204,768 bytes)`

Notice that Linux is ~30% bigger than Windows. This is because on Linux, in order to support HTTPS, we need to use `System.Security.Cryptography`. And in order for `System.Security.Cryptography` to validate certificates correctly, it needs to bring in the whole `System.Net.Http.HttpClient` stack. This isn't the case on Windows, because we use the OS crypto stack, and the .NET process doesn't need `HttpClient`.

Now, if I hack out HTTPS support using https://github.com/dotnet/aspnetcore/commit/bffa15c0f165b6530d56ebb77f8c839cbda203f0, and publish the same app, the numbers drop to:

**Windows** - `8.97 MB (9,406,464 bytes)`
**Linux** - `9.58 MB (10,049,136 bytes)`

Now the difference in size is much smaller, only ~7%. This is because all of `System.Security.Cryptography`, and thus `HttpClient` is able to be trimmed. You can see that by analyzing the `.mstat` file produced by NativeAOT (following [these instructions](https://github.com/dotnet/runtime/issues/78671#issuecomment-1370315695)). When comparing the "current" (left size of below image) vs. the hack commit (right side), see all the larger namespaces that are removed:

![image](https://user-images.githubusercontent.com/8291187/219822094-306e0ac0-876d-4b02-98c2-7960e83add72.png)

You can even tell from this picture that HTTP2 and 3 code is still in the hacked app. We could get even smaller if we removed those as well, if we felt necessary.
