### ISSUE TITLE
asp-route-{value} attributes do not work in anchor tags linking to Index pages

### ISSUE THREAD

**Issue by gabrielmaia2** [dotnet/aspnetcore#46748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using ASP.NET Core 7.0 and having the following file structure:
Pages/
    Page1.cshtml
    Page/
        Index.cshtml

When adding the an anchor tag in Page1.cshtml linking to Page/Index.cshtml, if you link to ./Page like this:
```razor
<a asp-page='./Page' asp-route-key="value">Anchor</a>
```
The "key" attribute will not be sent in the query string. For it to be sent, you must link to ./Page/Index:
```razor
<a asp-page='./Page/Index' asp-route-key="value">Anchor</a>
```

### Expected Behavior

When using the same anchor tag in the previously described situation:
```razor
<a asp-page='./Page' asp-route-key="value">Anchor</a>
```
The "key" attribute must be sent in the query string.

### Steps To Reproduce

Using ASP.NET Core 7.0, create a new project and create the following file structure inside of it:
Pages/
    Page1.cshtml
    Page/
        Index.cshtml

Add an anchor tag in Page1.cshtml linking to Page/Index.cshtml like this one:
```razor
<a asp-page='./Page' asp-route-key="value">Anchor</a>
```
Run the project and follow the anchor link in the browser.
The "key" attribute is not sent in the query string.

### .NET Version

7.0.102

### Anything else?

I dont know if this is by design, but if it is, I still didn't find it in the documentation.

**Comment by javiercn** [comment]
@gabrielmaia2 thanks for contacting us.

Is the link being correctly generated at all? I suspect it might not (it'll be an empty link) and that's why you don't see the `asp-route-key="value"` on the query string.

Since you are not using the default conventions (put everything in Pages) I suspect there are additional things that require configuration for pages inside the `Page` folder to be handled correctly according to conventions.
