### ISSUE TITLE
Blazor IJSRuntime.Invoke memory leak problem

### ISSUE THREAD

**Issue by optimit9266** [dotnet/aspnetcore#46761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in my project I use mass IJSRuntime.Invoke to draw canvans, the performance is good but will happen memory leak. I tracked memory change but memory occupy is not happen in my code. I really sure it's happened at lowaer layer. please solve this issue. thanks.

### .NET Version

dotnet --version 7

**Comment by MackinnonBuck** [comment]
It's possible that you're seeing an increase in memory use because of how much data is being JSON-serialized for JS interop. If this is a Blazor WebAssembly app, you might see performance improvements by using the new [`JSImport`](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0)-based interop. If this is a Blazor Server app, I would recommend taking a look at [this issue](https://github.com/dotnet/aspnetcore/issues/43513) to see if the insight there is useful.

We're going to close this out because we don't believe there is an issue in the framework. If you continue to experience the issue and believe it is indeed a framework bug, please submit another issue with a minimal repro project that demonstrates the issue, hosted as a public GitHub repository. Please also provide any diagnostic information you've collected that clearly shows the memory consumption problem you describe. Thanks!
