### ISSUE TITLE
Expose the SslStream and Cipher Suite on feature interfaces

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#46823]
## Background and Motivation

As was sensibly requested in #46442, we should expose these properties - their omission was likely an oversight.

Note that the issues to be discussed here are substantially similar to those in #46538.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+    #if NET7_0_OR_GREATER
+        TlsCipherSuite? NegotiatedCipherSuite { get => default; }
+    #endif
}

namespace Microsoft.AspNetCore.Server.Kestrel.Core.Features;

+ public interface ISslStreamFeature
+ {
+     SslStream SslStream { get; }
+ }
```

## Usage Examples

The cipher suite can be used to collect telemetry on the usage of outdated suites.

I'm not actually sure why you'd need the `SslStream` but everyone commenting on #46442 seemed to think it would be helpful.

## Alternative Designs

The properties could go on `ITlsConnectionFeature`, on `ITlsApplicationProtocolFeature`, or on an entirely new interface, but seemed at home on `ITlsHandshakeFeature`.

Parallelism suggests `ISslStreamFeature` should be called `ITlsSslStreamFeature`, but that seems silly.

## Risks

The if-def is kind of gross, but the API is also exposed in netstandard2.0.  We could use looser types (`int` and `object`?) and drop the default interface methods, but that would be a breaking change for anyone implementing the interface.

The new properties cannot feasibly be exposed for http.sys or IIS - the cipher suite isn't public and there's no SslStream.

**Comment by halter73** [comment]
API Review Notes:

- `ISslStreamFeature` is an escape hatch in case we miss a property.
  - Why is it in Microsoft.AspNetCore.Server.Kestrel.Core.Features? Only Kestrel will implement it. We do this for other features.
- Why the `#if`? Because netstandard2.0 doesn't support DIMs. We're doing `#if NETCOREAPP` now though. It shouldn't make a difference.
- Can `NegotiatedCipherSuite` be left non-nullable and have the DIM throw a `NotImplementedException`? No, because we cannot implement it for IIS/HTTP.Sys immediately, and throwing properties are annoying.
- `ISslStreamFeature`? More like `ITlsStreamFeature` 😆 . The property is of type `SslStream` though, so we're keeping the name.
- Are we going to stop putting the `SslStream` in the feature collection directly? Not where we currently put the stream in.
  - Adding a type we don't own to the feature collection is an anti-pattern, but we already do this. Not doing this would be breaking.
  - Should we always set `SslStream` directly as a feature? Yes.
  - Do we keep `ISslStreamFeature` as well since it's more standard like `IConnectionSocketFeature`? Even though it's completely redundant if we always add the `SslStream`? Sure.
  - Do we try to keep the direct `SslStream` and `ISslStreamFeature` in sync? No. If you want to set it, it's on you to manage this.
- `TlsCipherSuite` is only available in .NET 3 and above, so it won't be in netstandard2.1
  - Isn't it sad that Microsoft.AspNetCore.Connections.Abstractions 8.0 only ships net8.0/netstandard/netframework TFMs so it cannot add support for the `TlsCipherSuite` for libraries targeting lower .NET core versions.
  - If this type could be consumed by netstandard libraries, we would not use a DIM.
- SslStream supports System.Net.TransportContext, can we add support for this to HTTP.Sys? Not now.

API Approved!

```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+    #if NETCOREAPP
+        TlsCipherSuite? NegotiatedCipherSuite { get => default; }
+    #endif
}

namespace Microsoft.AspNetCore.Server.Kestrel.Core.Features;

+ public interface ISslStreamFeature
+ {
+     SslStream SslStream { get; }
+ }
```
