### ISSUE TITLE
Client result method accepting arguments that is unhandled by the client results in hanging until timeout

### ISSUE THREAD

**Issue by RedwoodForest** [dotnet/aspnetcore#46825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the server invokes a method that accepts parameters and returns a result such as `public Task<Object> UnhandledClientResultMethodWithArg(Object arg);` and the client has not implemented handling for this method the method call hangs until timeout occurs.

The same behavior is shown whether or not the client contract is provided to IHubContext as a generic parameter.

This behavior was discovered while testing a newer version of our client when we unintentionally called a new client method on an older version that did not implement it.

### Expected Behavior

I expected the call to immediately fail with an exception of some kind instead of hanging until timeout.

Note that if the called client method does not accept any arguments such as `public Task<Object> UnhandledClientResultMethod();` then an exception is thrown with the message `"Client didn't provide a result."` (which meets the above expectation), so it's surprising that the behavior is different when the method accepts an argument.

### Steps To Reproduce

I have created a minimal reproduction of this issue [here](https://github.com/RedwoodForest/signalr-client-result-method-not-implemented). DemonstrationTests.cs contains tests that verify the behavior I'd expect and comments noting which tests fail.

**Comment by BrennanConroy** [comment]
Does this still repro if you change from sending an `Object` to sending an `int` or simpler type?

**Comment by BrennanConroy** [comment]
Oh, I think I see the issue. If you changed your repro to have a method registered on the client that accepts Object then you'll see the expected results. But if you don't (it's commented out in your repro) it'll have this problem. What's happening is we try to deserialize the message but don't know the type being received from the server since the client doesn't have any registered methods, so the deserializer creates an `InvocationBinderFailureMessage` and logs the error and ignores the message.
https://github.com/dotnet/aspnetcore/blob/33e7a9a111742c8b06924383baba5c448d7f8af8/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1002
We should probably look at if the message expects a result and respond appropriately.

**Comment by RedwoodForest** [comment]
> We should probably look at if the message expects a result and respond appropriately.

Thanks for the quick analysis and response. That sounds like it would resolve this issue.
