### ISSUE TITLE
Error in WebAPI model validation with records

### ISSUE THREAD

**Issue by NikitaEgorov** [dotnet/aspnetcore#46831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I use record as webApi input parameters I have the issue with Model validation

```c#
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    [HttpPost]
    public Data Post(Data data)
    {
        return data;
    }
}

public record Data
{
    public NotRequired<string?>? ClientEmail { get; init; }
}

public record NotRequired<TType>(TType Value);
```

When I use request body
```json
{
  "clientEmail": {
    "value": null
  }
}
```
I got error 
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-9c38165191642ff7b3a585d4eb2036bf-be1d1eb195a5d0ab-00",
  "errors": {
    "ClientEmail.Value": [
      "The Value field is required."
    ]
  }
}
```

If I change NotRequired from record to class 

```c#
public class NotRequired<TType>
{
    public NotRequired(TType Value)
    {
        this.Value = Value;
    }

    public TType Value { get; init; }
}
```

everything fine

### Expected Behavior

No model validation errors

### .NET Version

7.0.101

**Comment by javiercn** [comment]
@NikitaEgorov thanks for contacting us.

This might be a limitation. Check https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#constructor-binding-and-record-types for more details.

You might need to attribute `TType`. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis

This is because the way records are compiled.

```csharp
public record NotRequired<TType>([AllowNull] TType Value);
```

might do the trick.
