### ISSUE TITLE
NavigationManager.NavigateTo: This throws an exception

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#46849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the .net8 version, NavigationManager.NavigateTo throws an exception if we use OnNavigateAsync in the router, example:

https://github.com/Alerinos/SQLError/blob/8e4cceec97e72138d26284793958debc66fa3565/SQLError/App.razor.cs#L10-L22

![image](https://user-images.githubusercontent.com/42449535/221047400-245d3f94-2b0b-4edd-b79e-5d7a98236981.png)

**Comment by Alerinos** [comment]
@mkArtakMSFT @msftdata 

https://github.com/Alerinos/NavigationException/

Just run the project and enter https://localhost:7212/discord

File:
https://github.com/Alerinos/NavigationException/blob/master/NavigationException/App.razor

**Comment by mkArtakMSFT** [comment]
Thanks for the repro.
Here what seems to be happening in your code.
Because you have [prerendering enabled](https://github.com/Alerinos/NavigationException/blob/65b9eeac168492f380fc22f9f6491d69c295cf06/NavigationException/Pages/_Host.cshtml#L19), the first time the `OnNavigateAsync` handler is called is during that prerendering, at which point the navigation is not yet available. That's because navigation relies on browser navigation APIs and prerendering is happening on the server, where there is no browser available.
You have two options to go from here:

1. Do not prerender the component from which you use Navigation by changing to.
```razor
<component type="typeof(App)" render-mode="Server" />
```
That, however, will turn off the prerendering for basically most of your app (except the HeadOutlet component)

2. Move your logic to `OnAfterRender` stage, where you know for certain that the browser is available, as the component has been rendered.

```razor
protected override void OnAfterRender(bool firstRender)
```

This is also documented [here](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#handle-asynchronous-navigation-events-with-onnavigateasync):

<img width="559" alt="image" src="https://user-images.githubusercontent.com/34246760/221312435-5f2ed822-22ee-4c0a-a09f-90876589d6fb.png">

**Comment by Alerinos** [comment]
Thanks for the detailed write-up.
I have now switched to a minimal interface which is better.
This code has been with me since .net 5 code, until .net 7 everything worked fine. After migrating to .net 8 it stopped working, probably something changed in the API or I just got lucky before :D
