### ISSUE TITLE
AppName.styles.css file has incorrect b- class identifiers

### ISSUE THREAD

**Issue by gjbundy** [dotnet/aspnetcore#46940]
I have a .NET 7.0 application that I am developing locally and then publishing it to an Azure App Service. While running locally the index page renders fine, showing the navbar and the top bar. As soon as I publish it to the App Service, I am no longer able to see any of the layout components. No NavBar and No top bar.

What I've Found:
with the CSS Isolation page, I realized that this appName.styles.css folder in the wwwroot location is generated dynamically. When this happens, for whatever reason, the [b-xxxxx] identifier that is present in the AppName.styles.css in the Azure App service does not match up with the correct identifiers. 

Workaround:
In order to fix this I've had to copy my AppName.styles.css from my development environment and then after I publish to the App Service, use the AppService Editor in the Azure Portal and replace the contents with my known working copy.

**Comment by gjbundy** [comment]
@javiercn  - Correct. I was using an ADO build pipeline, but with the latest updates the build is failing (incorrectly) so I have to push directly. Feel free to ping me on teams if you need more info!

**Comment by javiercn** [comment]
@gjbundy thanks for the additional details.

Could you file an issue through the report a problem dialog in Visual Studio with all the details and include a reference to this issue in it so that we can correlate them?

Start from a clean solution (physically remove the bin and obj folders from your projects/solution) and generate one or more MSBuild binlogs with VS as described https://msbuildlog.com/#MSBUILDDEBUGENGINE and attach them to the issue.

If you are able to reproduce the issue from the command-line, you can also generate the logs with `/bl`. Note that if you run multiple commands (dotnet build followed by dotnet publish) we need the binlogs for all the commands in order, so that we can investigate. Otherwise, if the issue is related to incrementalism, we won't be able to determine what is going on.

**Comment by gjbundy** [comment]
@javiercn Issue opened with VS now. and attaching the binlog files for you.
[VideoBINLOGS.zip](https://github.com/dotnet/aspnetcore/files/10867189/VideoBINLOGS.zip)
I suspect that you won't see anything in the logs now. After deleting the bin and obj folders manually and doing a rebuild I can confirm that the App service now renders properly after publish...Not sure how helpful this will be!

**Comment by javiercn** [comment]
@gjbundy I've deleted the comment. 

The reason we ask to file an issue through VS is because the logs can contain secrets and we do not want them exposed.
