### ISSUE TITLE
built-in Rate Limiting middleware in .Net 7

### ISSUE THREAD

**Issue by sxr1999** [dotnet/aspnetcore#46974]
I am using built in Rate limiting middleware in .Net 7. 

I use this code to configure a global rate limiter:

```
services.AddRateLimiter(options =>
        {
            options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(content =>
                RateLimitPartition.GetFixedWindowLimiter(
                    partitionKey: content.Request.Headers.Host.ToString(),
                    factory: partition => new FixedWindowRateLimiterOptions
                    {
                        AutoReplenishment = true,
                        PermitLimit = 5,
                        QueueLimit = 0,
                        Window = TimeSpan.FromSeconds(20)
                    }
                    ));
            options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
        });
```

The code works well, But when Rate limiter reaches the limit, It blocks all endpoints. How can Rate limiter only lock the endpoint that is currently accessed multiple times? If I use `AspNetCoreRateLimit` , I can set `EnableEndpointRateLimiting = true` to limit the rate for each endpoint individually, I don't find similar property in Built in Rate limiting middleware.

**Comment by adityamandaleeka** [comment]
The GlobalLimiter applies to all requests, by design, and if a GlobalLimiter is provided it will run before any policy specified on an endpoint: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.ratelimiting.ratelimiteroptions.globallimiter?view=aspnetcore-7.0

You can also define rate limiting policies and apply them to specific endpoints too, which sounds like what you're looking for. Here's some sample code that shows how that would look: https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0#rate-limiter-samples

**Comment by BrennanConroy** [comment]
Instead of partitioning by the Host, you can partition by something that is representative of the endpoint, like `content.Request.Path.ToString()` or `content.GetEndpoint()?.DisplayName`
