### ISSUE TITLE
Add Extensions to Http.TypedResults

### ISSUE THREAD

**Issue by dnperfors** [dotnet/aspnetcore#47050]
## Background and Motivation
`TypedResults` has a very similar api as `Results`, but it lacks an `Extensions` property.

This property would be useful for consistency, all endpoints can use `TypedResults` even when using customized results via an extension. Besides that there seem to be plans the recommend and add a codefixer for using `TypedResults` where possible. (#45217)

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public static class TypedResults
{
+    public static IResultExtensions Extensions { get; } = new ResultExtensions();
}
```

## Usage Examples

```csharp
app.MapGet("/",  () => TypedResults.Extensions.CustomResult());
```

## Alternative Designs

Alternatively a new specific interface could be used instead:

```diff
namespace Microsoft.AspNetCore.Http;

+ public interface ITypedResultExtensions { }

public static class TypedResults
{
+    public static ITypedResultExtensions Extensions { get; } = new ResultExtensions();
}
```

## Risks

When going for the proposed solution, existing extensions automatically become available, even if they are not 'Typed'.

**Comment by halter73** [comment]
API Review Notes:

- Why did we add `Results.Extensions` in the first place? Mostly discoverability of custom `IResult` types.
- The workaround is just continue using `Results.Extensions` and return strong types from custom `IResult` types.
- Is it confusing to include an `Extensions` in both places? It might less confusing because it's the only member of `Results` that's not in `TypedResults`.
- Do we like the alternative design? It provides more flexibility. You could have one `IResult`-returning method better for multiple return points in a lambda, and one that's type. It could be confusing if extensions that showed up on one didn't on the other though. And it's a lot more ceremony for custom `IResult` authors.

API Approved as proposed!

```diff
namespace Microsoft.AspNetCore.Http;

public static class TypedResults
{
+    public static IResultExtensions Extensions { get; } = new ResultExtensions();
}
```

**Comment by davidfowl** [comment]
We might be getting extension everything in C# 12, so hopefully, this will be obsolete in the future.

cc @jaredpar @MadsTorgersen

**Comment by dnperfors** [comment]
I can provide a PR with the implementation.
