### ISSUE TITLE
[Blazor] Router seems to be rendering twice

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47058]
From what I can tell, when there is no handler passed to the router, it will render the component twice:
https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L256-L259

Probably there should be an early return after the highlighted `Refresh`

**Comment by MarvinKlein1508** [comment]
Could this possibly has something todo with all those errors we see in our Eventviewer?

```
Category: Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager
EventId: 4
SpanId: f84e4ab5046d12a9
TraceId: f886dd67d7c1fa947063c8bd2e5152bc
ParentId: 0000000000000000
RequestId: 8000049b-0000-e400-b63f-84710c7967bb
RequestPath: /_blazor
TransportConnectionId: JNgCuYUT_el1KKsXUpt-cQ

Navigation failed when changing the location to https://besucherportal.scholzdom.local/Account/Login

Exception: 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
```

We get those all the time when someone switches from a razor component page to a razor page in our app. For example: from `Index.razor` to `/Account/Login.cshtml`

**Comment by surayya-MS** [comment]
I checked this in BlazorServerApp and found out that Router renders the component only once. This "return" happens [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L190) and the [comment](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L180-L183) explains it.

However when I worked on unified app model routing issue I also noticed that Router renders the component twice. I checked same thing in BlazorUnitedApp in my other branch with unified app model and found out that it is true. This happens inside `SetParametersAsync` [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L140) because previously the component was already rendered once [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L137). The fix is to put that `Refresh` inside else block.

The reason why this happened in BlazorUnitedApp and not in BlazorServerApp (turned out that it also happens but only once) is because BlazorUnitedApp renders `App.razor` every time and there is `Router` inside. `Router.SetParametersAsync` is called every time. Whereas in BlazorServerApp `Router` component is rendered once and `SetParametersAsync` is not called every time the page renders. Inerestingly in BlazorServerApp `SetParametersAsync` is called twice not once as in BlazorUnitedApp and the component was actually rendered 4 times on the start.
