### ISSUE TITLE
Generate self-signed certificate for local domain when debugging in Visual Studio

### ISSUE THREAD

**Issue by adcloeshelle** [dotnet/aspnetcore#47186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We would like clients on a different machine to hit a local instance of an ASP.NET Core Web API. The use case is a Mobile Developer is working with a Server developer and wants to test out an API change running on the server developers local instance. The Mobile Developer could be using a simulator or a physical mobile device (on the same network as the server developers machine). This all works well except we get SSL certificate errors - is it possible for Visual Studio to automatically install a self-signed certificate for the domain listed in launchSettings.json instead of localhost? Here is our launchSettings.json:

`{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://testmachine.example.domain.com:60418",
      "sslPort": 44317
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "TestDomainApplication": {
      "commandName": "Project",
      "commandLineArgs": "ContainerDeployment",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": "true",
      "applicationUrl": "https://testmachine.example.domain.com:44317;http://testmachine.example.domain.com:60418"
    }
  }
}`

### Expected Behavior

Visual Studio installs a self-signed certificate based on the domains listed in launchSettings.json, instead of localhost

### Steps To Reproduce

You can use the following launchSettings.json to reproduce. You will be able to hit the endpoint, but get ssl warnings:

`{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://testmachine.example.domain.com:60418",
      "sslPort": 44317
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "TestDomainApplication": {
      "commandName": "Project",
      "commandLineArgs": "ContainerDeployment",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": "true",
      "applicationUrl": "https://testmachine.example.domain.com:44317;http://testmachine.example.domain.com:60418"
    }
  }
}`

### .NET Version

7.0.201

**Comment by mitchdenny** [comment]
Thanks for reaching out @adcloeshelle. There will be two issues you are facing trying to communication with a HTTPS endpoint secured with a self signed certificate. The first is that the hostname you are using to reach the server won't be localhost so the browser/client software will rightly complain about that.

The second issue is the fact that as a self-signed certificate the browser/client cannot verify the server identity via a chain of trust to a root certificate that it trusts.

The second issue requires you to trust the certificate on the client device which is not something that our tooling can trigger.

Making our tooling create a self-signed certificate with a non-localhost domain is an interesting idea, but a better option for you that is likely to solve both problems would be to use a tunnelling solution.

If you are using Visual Studio for your .NET development you can make use of a feature called "dev tunnels". Dev tunnels run a reverse proxy on your local machine which then connects to a service hosted in the cloud which tunnels HTTPS requests from the cloud to your local machine. It is designed exactly for the scenario you are highlighting above because it does things like terminates the TLS connection using a public address with an automatically assigned certificate.

There are also other alternatives available such Ngrok, and CloudFlare Tunnel.
