### ISSUE TITLE
Honor default value provided in parameters for route handlers

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#47266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There are a number of ways to make it unnecessary to pass an argument corresponding to a given parameter.  We should think about what we want to do in these scenarios with RDG.

```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/{purple:int}", HandleRequest);

app.Run();

static string HandleRequest(int purple, int orange = 1) => "Hello World!";
static string HandleRequest(int purple, [System.Runtime.InteropServices.OptionalAttribute] int orange) => "Hello World!";
static string HandleRequest(int purple, params int[] orange) => "Hello World!";
```

### Describe the solution you'd like

I see that parameters can't already be flagged as optional:
```
// Endpoint Parameter: purple (Type = int, IsOptional = False, IsParsable = True, Source = RouteOrQuery)
```

Maybe we just need to recognize more forms of optionality?

**Comment by mitchdenny** [comment]
Thanks for bringing this up, it is something I hadn't considered. Just looking into the errors in the generated code now for these scenarios.

**Comment by mitchdenny** [comment]
OK for the `params` scenario I don't think we need to worry. The generated code is going to look at the signature for the method and identify that it is an array, and an array is always going to have a value, even if it is empty. I just tested it and the code it emits works fine (I will add some additional tests for it though!).

**Comment by mitchdenny** [comment]
In the case of this delegate signature:

```csharp
static string HandleRequest(int purple, [System.Runtime.InteropServices.OptionalAttribute] int orange) => "Hello World!";
```

Omitting the `orange` variable fails with a `400` (predictably). So, RDF doesn't appear to do anything special with the `[Optional]` attribute. 

The remaining case (`int orange = 1`) we don't handle at all - and the generator blows up (@captainsafia heads up that we'll need this captured in the known issues Gist). RDF works fine so its clearly some test cases we need to bring across ;)

**Comment by captainsafia** [comment]
> OK for the `params` scenario I don't think we need to worry. The generated code is going to look at the signature for the method and identify that it is an array, and an array is always going to have a value, even if it is empty. I just tested it and the code it emits works fine (I will add some additional tests for it though!).

@amcasey had brought up that it might make sense for `params` to treat the array parameter as optional since that matches the behavior for methods in general (zero, one, or many values are supported). `params` in inline lambdas was only recently added to C# (I believe it is part of C#12) and while both RDF and RDG respect the array type of the parameter, they don't set a `params` argument as optional in anyway.

> Omitting the orange variable fails with a 400 (predictably). So, RDF doesn't appear to do anything special with the [Optional] attribute.

Yep, don't think this is a scenario we'd support. If we did, it would be via the DataAnnotations attributes and the minimal validation support.

> The remaining case (int orange = 1) we don't handle at all - and the generator blows up (@captainsafia heads up that we'll need this captured in the known issues Gist). RDF works fine so its clearly some test cases we need to bring across ;)

Yeah, it looks like this is a result of the fact that code generated by RDF is oblivious to nullability while RDG code is not. I think we should create a separate issue for this to link in the doc. I dug into this a little bit further and it looks like for the given code:

```csharp
string HandleRequest(int purple, int orange = 1) => "Hello World!";
app.MapGet("/hello", HandleRequest);
```

We end up generating a parsing block that looks like this:

```csharp
if (GeneratedRouteBuilderExtensionsCore.TryParseExplicit<int>(orange_temp!, CultureInfo.InvariantCulture, out var orange_temp_parsed_non_nullable))
{
    orange_parsed_temp = orange_temp_parsed_non_nullable;
}
else if (string.IsNullOrEmpty(orange_temp))
{
    orange_parsed_temp = null;
}
else
{
    wasParamCheckFailure = true;
}
```

With the problematic code in question being:

```
else if (string.IsNullOrEmpty(orange_temp))
{
    orange_parsed_temp = null;
}
```

`orange_parsed_temp` is emitted as a non-nullable `int` to match the signature of the route handler delegate. I believe the fix is to change this line of code to emit a nullable type for the argument:

https://github.com/dotnet/aspnetcore/blob/7b619968eb26ff260ac7a8dc1fd3ae1cea2c38d2/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/EndpointParameter.cs#L232

using a strategy similar to what we do for the delegate cast:

https://github.com/dotnet/aspnetcore/blob/7b619968eb26ff260ac7a8dc1fd3ae1cea2c38d2/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/StaticRouteHandlerModel.Emitter.cs#L36-L37

**Comment by captainsafia** [comment]
I ended up addressing this in https://github.com/dotnet/aspnetcore/pull/47657 since I imported some tests from RDF that were failing because we didn't handle default values.

**Comment by mitchdenny** [comment]
Thanks @captainsafia

**Comment by captainsafia** [comment]
I'll keep this open until the PR is merged...

**Comment by eerhardt** [comment]
@captainsafia - can this be closed now? It is in the "Done" column for both projects, but this issue is still open.
