### ISSUE TITLE
Allow non-ASCII characters in response header values

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#4727]
Following up for https://github.com/aspnet/KestrelHttpServer/issues/1144. We may want to allow UTF-8 characters in response header values now to parallel our acceptance of UTF-8 characters in request header values. Note that the app has some degree of control over the response headers and their values.

**Comment by rickyburrell** [comment]
Any chance this can get some airtime? Not exactly conforming to HTTP spec. We have a load balancer running inside kestrel and are not exactly in control of response header creation. It's a bit unfortunate to have to alter non-ascii chars.

**Comment by dkonyayev** [comment]
We are having issues with this now. Our SSO provider inserts LDAP data into a header, and the LDAP data contains non-ASCII characters that are user's name (ex. Görkem)

It's hard to get resolution on this since only applications on Kestrel are having issues with these headers. All other applications are either processing it successfully or ignoring it.

**Comment by davidfowl** [comment]
We need an API proposal, this wouldn't be on by default. It's also up for grabs so can be implemented by anyone that needs it once the design and API are approved.

**Comment by Tratcher** [comment]
We expect this to be a problem for proxy scenarios. Bumping out of backlog for re-triage.
