### ISSUE TITLE
Add an option to disable DeveloperExceptionPageMiddleware with WebApplication / Minimal APIs

### ISSUE THREAD

**Issue by vchirikov** [dotnet/aspnetcore#47293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi, I want to have an option to disable preconfigured (implicit) middlewares and I can't remove `DeveloperExceptionPageMiddleware` / (`.UseDeveloperExceptionPage` call).

I don't want to use `WebHostBuilder` because according to the docs it's deprecated:

> This article covers the Web Host, which remains available only for backward compatibility. The ASP.NET Core templates create a [WebApplicationBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplicationbuilder) and [WebApplication](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication), which is recommended for web apps.

I don't want to wrap and catch with my middleware after the developer exception middleware, because it's an ugly workaround and produces unnecessary allocations and useless work per request.

[docs source](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-8.0)

### Describe the solution you'd like

Add an option to disable implicit middleware logic or at least have an option to disable `.UseDeveloperExceptionPage` in `Development` environment too.

### Additional context

Hardcoded part of `WebApplicationBuilder`:

https://github.com/dotnet/aspnetcore/blob/c52fd930f70e102d5e5c84e85180e451861eaf7e/src/DefaultBuilder/src/WebApplicationBuilder.cs#L313-L316

https://stackoverflow.com/questions/69982014/how-to-not-use-developerexceptionpagemiddleware

**Comment by davidfowl** [comment]
> I don't want to wrap and catch with my middleware after the developer exception middleware, because it's an ugly workaround and produces unnecessary allocations and useless work per request.

Can you make this more concrete for me (I'm not understanding why it's an ugly work aronud)? You're worried about extra allocations in development mode on the exceptional code path?  The stackoverflow question says that you want to create a consistent experience across all environments. Don't you need a middleware to do that?

**Comment by davidfowl** [comment]
I don’t have a problem with an flag but this is a developer purity thing. It seems like you’re saying that you don’t want any exception page, which is valid but I’d like to understand what you’re actually trying to do.

In .NET 8, there’s CreateSlimBuilder that you can use to get a minimal builder with no things in the pipeline.

**Comment by davidfowl** [comment]
> I just don't like implicit things in pipeline which I can't exclude.

There are other middleware in the pipeline that you can’t exclude (host filtering).

**Comment by davidfowl** [comment]
I don't see your request as anything to do with trimming (you can avoid the runtime behavior with a flag and that doesn't solve the trimming problem), the slim builder exists because of its dependency free nature. When we're done trimming it to bits for AOT scenarios then it's likely the thing you want to use.

**Comment by davidfowl** [comment]
> Good catch, it will be nice to have an option to remove it too, for example I don't want additional task + Host filtering middleware per request, because I have a reverse proxy on top of Kestrel (which do the same) or always use * as host (afaik for less allocations for middleware, we can implement IMiddleware + register it as a Singleton, why HostFilteringMiddleware doesn't do this? Am I wrong?)

I don't believe you're seeing any additional allocations from those middleware. At least, not in practice. If so, can you show them?

Your best bet here is to stick to the original claim, if you start throwing around things like trimming and performance without data then it takes away from your case.

**Comment by amcasey** [comment]
I understand that ASP.NET Core started out with everything being opt-in and it was borderline unusable because there's just _so much_ that goes into building a web app and most consumers don't need or want that level of control.  Since it is presently possible to have either nothing (don't call helpers like `CreateBuilder`) or everything (`CreateBuilder`) and it will soon be possible to have "less" (`CreateSlimBuilder`) I think we have pretty good coverage of the space.

You might find it interesting to look through some of the benchmarks [here](https://github.com/aspnet/Benchmarks/) to get ideas for how you can strip out as much default behavior as you want.

**Comment by amcasey** [comment]
@vchirikov Generally speaking, the docs aim to provide guidance for the most common use cases.  If you choose an atypical use case, you may find that you have to take a different approach.  I think we're unlikely to document a recommended way to opt out of features without more data showing that it's a common requirement.

**Comment by amcasey** [comment]
I believe the reason we didn't suggest using `WebHostBuilder` as a lower-level API for making custom configurations is that it's not _for_ that - that's simply a way that advanced users might choose to use it.

I'm not familiar with our plans for `WebHostBuilder`, so this shouldn't be read as a forecast about its future availability, but usually things retained for backward compatibility are not also scheduled for removal (at least, not without ample notice), since that would defeat the purpose.

**Comment by davidfowl** [comment]
The idea was to add CreateEmptyBuilder and that would replace the need for WebHostBuilder (we haven added that API yet)
