### ISSUE TITLE
API review: Razor MapRazorComponents

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47312]

**Comment by danroth27** [comment]
One item to discuss: We typically use methods starting with "Add" for configuring services, "Use" for configuring middleware, and "Map" for setting up routes. `MapRazorComponents` returns a builder that has a couple of "Add" methods on it: `AddWebAssemblyRenderMode()` and `AddServerRenderMode()`. Besides the "Add" prefix looking a little odd as part of setting up routes, I also initial though these methods did something completely different than what they actually do. I originally thought they applied the corresponding render mode to the entire app, but they actually enable the corresponding render modes to function.

**Comment by buvinghausen** [comment]
@danroth27 I started playing around with 8 recently since we are less than 60 days out from RC1 which is usually when I try to roll out the new features coming in the new release and have been playing around with Blazor in particular. First off big huge props on the Blazor united feature that solves my number one gripe with Blazor which is I want the server pre-rendered content pages for blogs and marketing content as well as on the main application the fast start from Blazor server but as the user stays on the app flip over to web assembly to reduce load it's perfect!

With that said here's my question for your team(s)... How do I map razor components from multiple razor class libraries?  In the old way I would pass in the assembly array to the router via the `AdditionaAssemblies` property and everything worked great.  When I do that now those assemblies seem to get ignored and the app returns the not found response when I hit any routes in an RCL.  I tried making multiple calls to `MapRazorComponents` and the routes do work and the component loads but it does so outside of the main layout.

Since this is an API review issue I figured this was the best place to ask my question if it is not I apologize but I didn't want to start a new issue for a simple question.  Thanks again for all your hard work on .NET 8 I'm excited that this much coolness was baked into an LTS release!

**Comment by buvinghausen** [comment]
^ sorry I just finally did an RTFM and saw your comment on your blog post...

> Note that there’s currently a [limitation](https://github.com/dotnet/aspnetcore/issues/49313) where components with routes must be defined in the same assembly as the App component passed to MapRazorComponents<App>(), so they cannot currently be defined in the client assembly. This will be addressed in a future update.
