### ISSUE TITLE
[Blazor] Base path validation

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/aspnetcore#47343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a site www.mysite.com and a Blazor WASM app under it, so www.mysite.com/myapp.  I have set the base path in index.html as `<base href="/MyApp/">` and in server program `app.UsePathBase("/MyApp")`.  This works fine except the base path validation seems to be case sensitive.

If the user enters https://www.mysite.com/MyApp, everything is fine, but if they enter https://www.mysite.com/myapp there is an error:  
**System.AggregateException: AggregateException_ctor_DefaultMessage (The URI 'https://www.mysite.com/myapp' is not contained by the base URI 'https://www.mysite.com/MyApp/'.)**  blazor.webassembly.js:1

If it is changed to https://www.mysite.com/MyApp then it works again.

Additional error  info:
```
at Microsoft.AspNetCore.Components.NavigationManager.Validate(Uri , String )
   at Microsoft.AspNetCore.Components.NavigationManager.set_Uri(String )
   at Microsoft.AspNetCore.Components.NavigationManager.Initialize(String , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyNavigationManager..ctor(String , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.InitializeNavigationManager(IJSUnmarshalledRuntime )
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder..ctor(IJSUnmarshalledRuntime , JsonSerializerOptions )
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.CreateDefault(String[] )
   at Program.<Main>$(String[] args)
   Exception_EndOfInnerExceptionStack
callEntryPoint @ blazor.webassembly.js:1
```

### Expected Behavior

The error should not occur because the base path validation should be case insensitive.

### Steps To Reproduce

As above.

### .NET Version

.NET 7

**Comment by javiercn** [comment]
@TonyLugg thanks for contacting us.

> The error should not occur because the base path validation should be case insensitive.

That's not the case, paths are case sensitive, only the host and scheme on a url are case-insensitive. Its only ASP.NET that decides to treat them as case insensitive.

Given that we don't know where you are going to deploy the app, we need to abide by the spec. Otherwise, we can create situations where someone can create an app on the hosting server with a path that uses a different casing and use that to load malicious code into the browser which can then be used to phish users, capture credentials, etc.

If you want to treat this case-insensitive and you are hosting webassembly, you could move the `index.html` into a razor page (like blazor server) and use `<base="~/" />` which should make sure your base path always matches the casing of your URL.

**Comment by TonyLugg** [comment]
@javiercn thank you for the explanation.  All our previous sites were ASP.NET so perhaps that is why I thought the sub paths were case sensitive.  I may look at moving index.html to a razor page.
