### ISSUE TITLE
IIS Express process memory size is not decreased.

### ISSUE THREAD

**Issue by KameshRajendran** [dotnet/aspnetcore#47351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a simple code that sends information to the client-side using an interop call triggered by a button click. We send base64-encoded data, but despite properly disposing of objects, the IIS Express process's memory size keeps increasing each time we execute the code.

![Call with Gokulprasath Venkatachalam-20230321_192108-Meeting Recording](https://user-images.githubusercontent.com/25635968/226630363-2b824207-0fad-4df7-9ea4-04aeef3b94e2.gif)

This makes the application unresponsive after multiple button click. 

**[index.razor]**

```razor
@page "/"
@implements IAsyncDisposable
@inject IJSRuntime Js

<h1>JavaScript Interop</h1>
<hr />
<button class="btn btn-primary" @onclick="@CallJSMethod">Call JS Method</button>
<br />
<div id="demop">
</div>
@code {
    private IJSObjectReference? JsModule;
    private int count = 0;
    public async void CallJSMethod()
    {
        MemoryStream memoryStream = new MemoryStream();
        using(FileStream fileStream = new FileStream("wwwroot/Data/pdf-succinctly.pdf", FileMode.Open, FileAccess.Read))
        {
            fileStream.CopyTo(memoryStream);
        }
        string base64 = Convert.ToBase64String(memoryStream.ToArray());
        memoryStream.Flush();
        memoryStream.Dispose();
        JsModule = await Js.InvokeAsync<IJSObjectReference>("import",
                "./script.js");
        await JsModule.InvokeAsync<string>("JSMethod", base64, count++);
        await JsModule.DisposeAsync();
    }
    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (JsModule is not null)
        {
            await JsModule.DisposeAsync();
        }
    }
}
```

**[script.js]**
 
```
export function JSMethod(str, count) {   
 document.getElementById('demop').innerText = "Javascript Method Invoked "+ count;
}
```

### Expected Behavior

The IIS Express process memory size should not be increased each time.

### Steps To Reproduce
1. Extract the below sample
2. Run the sample
3. Open the Task manager
4. Check the IIS Express process memory
5. Click the button multiple time
6. The IIS Express process memory size keep on increasing.

Sample project : 
 
[Sample (2).zip](https://github.com/dotnet/aspnetcore/files/11029133/Sample.2.zip)

### .NET Version

7.0.100

**Comment by adityamandaleeka** [comment]
A couple of observations:

I believe this growth is caused by the fact that you have a giant string being passed into your JS code. You can see this by replacing `base64` in this line with a smaller string:

```c#
 await JsModule.InvokeAsync<string>("JSMethod", base64, count++);
```

With that said, it appears the growth is also not unbounded. On my machine, I can see that it stabilizes at ~1 GB on .NET 7 (.NET 6 goes higher):

![image](https://user-images.githubusercontent.com/219224/226769440-51c672ec-7beb-41ed-b677-61b16ad26658.png)

Given the size of your objects, they must live in the LOH (large object heap) which doesn't get GC'd the same way as normal, smaller objects (for one thing, as you can imagine, compacting giant chunks of memory constantly would be inefficient).

@SteveSandersonMS, any suggestions? I'm rerouting this to blazor since I don't think this is an issue in my area.

**Comment by javiercn** [comment]
@KameshRajendran thanks for contacting us.

This is very likely not a memory leak unless:
* You are able to cause an OutOfMemoryException on the application.
* Proof that Blazor is holding on to the memory.
* Proof that your app is not holding on to the memory.

If you are able to provide a repro project and traces that proof the three things above, we will be happy to take a look at it. Otherwise, we have already tested these areas thoroughly and we have not found evidence of a leak, so it is very likely there is something your app is doing or there is a gap between the framework understanding of a memory leak and your definition for it.

A few important notes to take into consideration when measuring memory:
* Are you running the published version of the app?
* Has the app been published in Release mode?
* Have you made sure to not attach a debugger to the running app?
* Did triggering a Gen 2 forced, compacting collection `GC.Collect(2, GCCollectionMode.Aggressive | GCCollectionMode.Forced, blocking: true, compacting: true))` frees the memory?
* Is your app allocating objects on the large object heap?
* Did you test the memory growth after the app warmed up? Typically, there are caches that get populated when code executes for the first time that add a constant amount of memory to the footprint of the app.

Another key points of information that you might be missing are:
* Server GC will not trigger garbage collections until it determines it is absolutely necessary to do so, to avoid freezing your app, and considers that your app is the only thing running on the machine (so it can use all the memory in the system).
* Even when a GC is triggered, .NET will hold on to the memory instead of returning it to the OS immediately as it is very likely that it will reuse it the near future. This avoids committing and decommitting memory constantly, which is expensive.
* You'll see this reflected if you use dotnet-counters because you'll see the GCs happen and the amount of used memory go down to 0, but you will not see the working set counter decrease (that's the sign that .NET is holding on to the memory to reuse it).

You can see a lot of the statistics about how memory in your app is behaving using dotnet-counters. For more information see [here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#examples-1)

We have more details on how the Blazor memory model works [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-7.0#blazor-server-memory-model)
