### ISSUE TITLE
Onboard aspnetcore into the new TimeProvider type from runtime

### ISSUE THREAD

**Issue by joperezr** [dotnet/aspnetcore#47472]
Now that TimeProvider has been added to the platform in https://github.com/dotnet/runtime/pull/83604,  we should make the following changes in the aspnetcore layer for .NET 8:

- Remove all the copies of ISystemClock that exist in the repo (there are at least 6, with types that implement them), particularly all the ones that are not publicly exposed, and replace the places where they are used with TimeProvider.
- Two of these copies of ISystemClock are actually public and part of some of our API surface: Microsoft.AspNetCore.Authentication.ISystemClock, and Microsoft.AspNetCore.Server.kestrel.Core.Internal.Infrastructure.ISystemClock. We should consider deprecating those as well as the affected API that exposes them, and consider if there are new APIs/overloads that should be exposed that use TimeProvider as opposed to ISystemClock.

cc: @tarekgh @Tratcher @adityamandaleeka @davidfowl @mkArtakMSFT 

- [x] Authentication https://github.com/dotnet/aspnetcore/pull/47717
- [x] OutputCaching #47753
- [x] ResponseCaching #47753
- [x] YARP https://github.com/microsoft/reverse-proxy/pull/2108
- [x] SignalR Common - #47895
- [x] Kestrel - https://github.com/dotnet/aspnetcore/issues/13628 suggests using a monotonic value like SignalR.
- [x] Reconcile to a shared MockTimeProvider across AspNetCore. - https://github.com/dotnet/aspnetcore/issues/13628

**Comment by Tratcher** [comment]
@SebastianC was going to look at this.

**Comment by davidfowl** [comment]
I think you meant @sebastienros 😄

**Comment by BrennanConroy** [comment]
We should also be aware of https://github.com/dotnet/aspnetcore/issues/13628 when doing this. I don't know if this work will make it easier or harder to convert Kestrel to wall clock (except for the Date header obviously)

**Comment by Tratcher** [comment]
Follow up:
Microsoft.Extensions.Internal.ISystemClock used by MemoryCacheOptions.Clock, used in CertificateValidationCache.

**Comment by Tratcher** [comment]
- [ ] OutputCaching
- [ ] ResponseCaching
- [ ] Authentication https://github.com/dotnet/aspnetcore/pull/47717
- [ ] Kestrel
- [ ] SignalR Common

**Comment by halter73** [comment]
API Review Notes:

### Proposed API

--- 

- What do we think about the pattern of adding a new obsolete constructor?
  - `[EditorBrowsable(Never)]`? It could help with the `OAuthHandler` in particular when the derived types call `base`.
- What's the plan after .NET 8?
  - Remove default `ISystemClock` registration in `AddAuthentication`. Maybe keep the interface around for people who add it manually.
- Can we teach DI not to use `[Obsolete]` constructors
  - We'd have to change the contract for third-party DI containers to do the same. We cannot design an API expecting that feature right now.
- Can we add a `TimeProvider` property to `AuthenticationSchemeOptions` instead of adding the `TimeProvider` directly to DI?
  - This could make it harder to replace the `TimerProvider` globally for every scheme.

We'd prefer not to add new obsolete constructor to every auth handler if possible, but we don't like any of the other alternatives.

API Approved!

**Comment by davidfowl** [comment]
Why is the property and argument name "time" instead of "timeProvider"

**Comment by halter73** [comment]
API Review Notes:

- We removed the `TimeProvider` accepting constructors from auth and identity and use properties on options instead.
- What do we think about `TimeProvider` being nullable instead of preset to `TimeProvider.System`?
  - Nullable makes it more obvious if it's been overridden.
- Do we like `TimeProvider` over `Time` for the property names? Yes.
- No namespace were modified.

```diff
namespace Microsoft.AspNetCore.Authentication;

+ [Obsolete]
public interface ISystemClock
{
}

+ [Obsolete]
public class SystemClock : ISystemClock
{
}

public AuthenticationHandler<TOptions>
{
+ [Obsolete]
  protected AuthenticationHandler(IOptionsMonitor<TOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock)
+ protected AuthenticationHandler(IOptionsMonitor<TOptions> options, ILoggerFactory logger, UrlEncoder encoder)
+ [Obsolete]
  public ISystemClock Clock { get; }
+ public TimeProvider TimeProvider { get; }
}

public AuthenticaitonSchemeOptions
{
+ public TimeProvider? TimeProvider { get; set; }
}

public SecuirtyTokenValidator
{
+ [Obsolete]
  public SecurityStampValidator(IOptions<SecurityStampValidatorOptions> options, SignInManager<TUser> signInManager, ISystemClock clock, ILoggerFactory logger)
+ public SecurityStampValidator(IOptions<SecurityStampValidatorOptions> options, SignInManager<TUser> signInManager, ILoggerFactory logger)
+ [Obsolete]
  public ISystemClock Clock { get; }
+ public TimeProvider TimeProvider { get; }
}

public SecurityStampValidatorOptions
{
+ public TimeProvider? TimeProvider { get; set; }
}
```

API Approved as updated!
