### ISSUE TITLE
[Minimal API] IFormFile does not bind when using WithOpenApi extension method

### ISSUE THREAD

**Issue by marcominerva** [dotnet/aspnetcore#47526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using .NET 7.0.4. I have defined the following endpoints:

    app.MapPost("/api/upload", (IFormFile file) =>
    {
        return TypedResults.Ok(file.FileName);
    });
    
    app.MapPost("/api/upload_with_openapi", (IFormFile file) =>
    {
        return TypedResults.Ok(file.FileName);
    })
    .WithOpenApi();

When I invoke the first one, everything works as expected. However, when I call the endpoint that uses WithOpenApi, I get an exception:

    Microsoft.AspNetCore.Http.BadHttpRequestException: Required parameter "IFormFile file" was not provided from form file.
       at lambda_method3(Closure, Object, HttpContext, Object)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass92_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
    --- End of stack trace from previous location ---
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I have also tried adding the `[FromForm]` attribute to the `IFormFile` parameter, but with no luck.

### Expected Behavior

`IFormFile` should work even when using the `WithOpenApi` extension method.

### Steps To Reproduce

Minimal repro: https://github.com/marcominerva/FileUploadIssue

### .NET Version

7.0.202

**Comment by mitchdenny** [comment]
This does look like a bug. Thanks for reporting it!

**Comment by captainsafia** [comment]
Without the `WithOpenApi` call, the schema that is produced looks as follows:

```
schema": {
  "required": [
    "file"
  ],
  "type": "object",
  "properties": {
    "file": {
      "type": "string",
      "format": "binary"
    }
  }
},
```

With the call invoked, the schema looks as follows:

```
"schema": {
  "type": "string",
  "format": "binary"
},
```

Since we still rely on the schema generation logic in Swashbuckle ([ref](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L264-L274)), I suspect the bug is in the fact that we don't invoke the `GenerateSchemaFromFormParameters`  method in the schema override logic.

We'll have to fix this bug over on the Swashbuckle side for now.

@marcominerva Do you mind filing this issue in the Swashbuckle.AspNetCore repo?

**Comment by marcominerva** [comment]
Sure @captainsafia, done :) Thank you for your support!

**Comment by mitchdenny** [comment]
Closing this bug here now that there is one tracking it on the Swashbuckle side.
