### ISSUE TITLE
Example in section triggers an exception with the message 'For a dotnetjs resource, custom loaders must supply a URI string'

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/aspnetcore#47589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the `loadBootResource` API, and applying the source from the Microsoft documentation, produces an exception with Blazor. However, there is a workaround that is implied in the [change for documentation](https://github.com/dotnet/AspNetCore.Docs/issues/28903) request.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28903

### Expected Behavior

Using code from the official documentation is not supposed to produce exceptions. I wanted to add a custom header while loading Blazor resources in this instance. The expected behavior is for the code to run without exception and load the resources.

### Steps To Reproduce

Please [read](https://github.com/dotnet/AspNetCore.Docs/issues/28903) the documentation change request.

### Exceptions (if any)

blazor.webassembly.js:1 
        
Uncaught Error: For a dotnetjs resource, custom loaders must supply a URI string.
    at blazor.webassembly.js:1:43248
    at window.__wasmmodulecallback__ (blazor.webassembly.js:1:43352)
    at <anonymous>:1:20
    at blazor.webassembly.js:1:43463
    at blazor.webassembly.js:1:43478
    at new Promise (<anonymous>)
    at Object.start (blazor.webassembly.js:1:34639)
    at Object.At [as start] (blazor.webassembly.js:1:59571)

### .NET Version

7.0.202

**Comment by guardrex** [comment]
Thanks @jan-johansson-mr.

Javier ... The examples haven't changed since provided by the PU quite a while ago. I suspect that the 🧀 moved on some aspect(s). I'll work the docs issue that @jan-johansson-mr opened after I understand what changes we need to make.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @jan-johansson-mr.

It looks like the example in the docs is incorrect. The code involved in throwing this exception hasn't been changed in a few years, so it's probably best to update the docs rather than making a change to the product.

@guardrex, would you mind updating that example in the docs to work with the current version of the product? The example should check if the resource type is "dotnetjs", and if it is, it should either return a URL or `null`. Thanks!
