### ISSUE TITLE
Review whitespace handling for server-side rendered Blazor components

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#47609]
I tried out SSR with the following Blazor component in .NET 8 Preview 3:

```razor
@page "/"
@implements IRazorComponentApplication<MyComponent>

<!DOCTYPE html>
<html lang="en">
<body>
    <h1>Hello Blazor!</h1>
    <p>The time is @DateTime.Now.ToShortTimeString()</p>
</body>
</html>
```

Which rendered like this:

```html
<!DOCTYPE html>
<html lang="en"><body><h1>Hello Blazor!</h1>
    <p>The time is 1:05 PM</p></body></html>
```

The handling of the whitespace seems inconsistent. It's certainly been modified from what was originally authored in the component. In this case the changes seem purely aesthetic, but whitespace can be significant in HTML, so the user will need to control it. Do we need to clean up how we are handling whitespace in Blazor component rendering?

**Comment by javiercn** [comment]
@danroth27 this is by design.

We did a feature in early Blazor because having whitespace double the size of the render trees we generated, so we started trimming down insignificant whitespace where possible.

You can keep it with `@preservewhitespace true`, but the default is to remove it.

I do not think users need to do anything to control it. The change should not have any functional or visual impact in your app and there is a way for users to control it otherwise.

The default behavior makes things more efficient implementation wise, and more efficient on the wire too.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/blazor-components-trim-insignificant-whitespace

**Comment by danroth27** [comment]
@javiercn Cool, makes sense. 

In the case I reported above, is there a reason in the case above that the newline and indentation before the `<p>` tag is preserved?
