### ISSUE TITLE
DateOnly binding in minimal API is broken when using dd-MM-yyyy or dd/MM/yyyy

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/aspnetcore#47734]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

As the title says, I'm having an issue using minimal API in a es-ES locale (if that matters) while developing.
I'm trying in swagger some api entrypoints and when I use `DateOnly` and I put the date with european format it breaks.

### Expected Behavior

The binding should work using the machine (client) current locale.

### Steps To Reproduce

Entry point code 
```c#
app.MapGet("getAppointments", async (int? page, int? pageSize, DateOnly from, DateOnly to, IClinicProvider prov) =>
{
    var data = await prov.GetAppointmentsAsync(page, pageSize, null, null);

    return Results.Ok(data);
});
```

### Exceptions (if any)

Exception in response
```
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to bind parameter "DateOnly from" from "21/04/2023".
   at lambda_method305(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

7.0.203

**Comment by mitchdenny** [comment]
Thanks for reporting this. It does look like this could be a bug in ASP.NET to me. If I call ```DateOnly.Parse("17/04/2023")``` it succeeds in a console app due to the fact that my culture info is used (I am in a locale that uses european ordering on day/month). If I set the current culture to invariant it blows up (as expected).

**Comment by mitchdenny** [comment]
I finally got back to having a bit of a look at this. Turns out that this is by design. Because dates in the query string and path form part of a URL that are frequently shared we process them using the invariant culture to avoid issues where a URL works for one person. To illustrate the problem.

Let's say I sent you the following link:

http://myapp.com/booking/create?from=12/11/2023

If we processed dates using locales, someone in the US would be booking an appointment on the 11th of December, and someone who is in Australia would be booking on the 12th of November.

For this reason we process dates using invariant culture. As someone who is frequently caught out by date formatting because I work in Australia but interact with folks in the US, I strongly recommend using ISO-8601 format (`YYYY-MM-DD`) for dates.
