### ISSUE TITLE
Graceful handling of connection limits

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4777]
When maximum connection limits are reached, Kestrel closes the connection without a response. When attempting upgrade, Kestrel throws. We could make this behavior more graceful in the following ways

Ideas:
 - try to kill idle connections before rejecting or throwing (TBD: what counts as idle?)
 - send a HTTP 503 response when connection limits reached (TBD: what about TLS connections? Do we wait for a potentially expensive handshake? Is there a TLS equivalent to 503?)
 - allow connection adapters to participate in the 503 rejection (i.e. for logging or other reasons)

**Comment by abralock** [comment]
How can I force it to throw failure for maximum connection limits are reached -> MaxConcurrentConnections. I want to apply retry mechanism based on the exception throw.

**Comment by TwanVB** [comment]
Closing the connection is not an option for us while converting an old (custom socket based) self hosted service to use the kestrel webhost implementation. This is because we have other applications choosing how to proceed based on what HTTP error was returned, specifically if it is 503 we can retry after some time. 

We're working around this by creating middleware that tracks the number of calls being handled and return 503 if the limit is reached. We would prefer to set the KestrelServerLimits.MaxConcurrentConnections property.

I can also see advantages in just closing the connection, as is done now: Eventhough it is very minimal if you're sending a 503 response or doing something else to be more gracefull, you're still in a way handling the request. 
Therefor maybe it would be an option to add the ability to 
- either configure how to deal with this as a setting
- or expose a hook to do custom handling based on the limit that was exceeded (In our situation we would return 503 for MaxConcurrentConnections and in other situations fall back to the default)

**Comment by davidfowl** [comment]
Closing this out. Its not something we plan to tackle. We do plan to implement request and connection throttling that may cover this.
