### ISSUE TITLE
When [Authorize] is not written on method, Task.FromResult(AuthenticateResult.Fail is ignored

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#47846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a REST API with my custom `AuthenticationHandler` for HTTP Basic authentication.
It is registered as default scheme in startup.
When I put `[Authorize]` on method/controller, when the authentication fails, I return `Task.FromResult(AuthenticateResult.Fail(...)` and user receives 401 response.
When `[Authorize]` is not added on a method, the handler will run and enter the same branch **but the authentication and authorization pipeline (followed by casual processing of the request) will continue executing** and user does not receive 401 response. This results in some unexpected behavior such as Authorization middleware executing without user being authenticated and the function on the REST API itself being executed even though authentication check did not pass.

### Expected Behavior

Failed `AuthenticationHandler` isn't silently skipped (pretending that nothing has happened) when `[Authorize]` annotation is not added on method/controller.

### .NET Version

7.0.203

**Comment by Tratcher** [comment]
This is by design. Authentication only runs when `[Authorize]` is specified on a controller _or_ a default is set in `AddAuthentication`. Failed authentication just means that the request proceeds anonymously. `[Authorize]` disallows anonymous users from accessing that resource. To disallow all anonymous users you need to set your fallback authorization policy to require auth.

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-7.0
```
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = options.DefaultPolicy;
});
```

**Comment by janseris** [comment]
@Tratcher 
Is it possible to prevent the default scheme AuthenticationHandler to execute when default scheme is set but [Authorize] is not placed on method?

**Comment by Tratcher** [comment]
No, the default auth handler is always run by the auth middleware. You can remove the default and tell Authorize which scheme to use.
