### ISSUE TITLE
too many same/different aspnetcore templates

### ISSUE THREAD

**Issue by kasperk81** [dotnet/aspnetcore#47849]
tried explaining the difference between`dotnet new`'s `api`, `webapi`, `web`, `webapp` and `mvc` to someone and ended up confusing myself:

```
dotnet new --list

API Controller                                apicontroller               [C#]        Web/ASP.NET                     
ASP.NET Core API                              api                         [C#]        Web/API                         
ASP.NET Core Empty                            web                         [C#],F#     Web/Empty                       
ASP.NET Core gRPC Service                     grpc                        [C#]        Web/gRPC                        
ASP.NET Core Web API                          webapi                      [C#],F#     Web/WebAPI                      
ASP.NET Core Web App                          webapp,razor                [C#]        Web/MVC/Razor Pages             
ASP.NET Core Web App (Model-View-Controller)  mvc                         [C#],F#     Web/MVC                   
```

is it just me or does anyone else see redundancies?

**Comment by DamianEdwards** [comment]
There are legitimate (albeit some historical) reasons for each of these templates existing and being distinct. The code between them is quite different and represent different application types. ASP.NET Core is a very flexible framework rather than being focused on one particular app type like REST APIs, or server-side HTML rendering.

- `web`: This is the "empty" web project template. It has very little code and includes just a single "hello world" endpoint
- `webapp`: This is the project template for a web "app" that generates a UI from server-rendered HTML intended for browser clients. It uses Razor Pages and includes a home page, about page, error page, navigation, Bootstrap styling, etc.
- `webapi`: This is the project template for building RESTful HTTP APIs. But given the somewhat recent introduction of Minimal APIs, it supports two completely different implementations: MVC or Minimal APIs, controlled by the `minimal` argument.
- `grpc`: This is the project template for building gRPC APIs which are a very different pattern and implementation than RESTful HTTP APIs.
- `mvc`: This is the "traditional" ASP.NET Core MVC app project template, that's the equivalent of the `webapp` project template, but rather than using Razor Pages it uses Controllers and Views (hence MVC).
- `api`: This is the newest project template (introduced in .NET 8) that is intended to be a more modern, focused approach to building RESTful HTTP APIs that are intended for "cloud native" deployment. It uses Minimal APIs (no MVC option) and is native AOT friendly (controlled via the `-aot` option). The name being just "API" is in response to that being the more common way of referring to these kinds of apps across the industry, whereas we have traditionally used the term "Web API" (which now seems somewhat dated).

I hope that helps.
