### ISSUE TITLE
IDE0005 error when building with latest SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#47932]
When using the latest build of .NET 8 Preview 4 SDK to build the aspnetcore repo, it results in a bunch of errors like this for the projects in the repo:

```
CSC : error EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/vmr/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj]
```

This was caught by the Source-build bootstrapping build workflow which uses a source-built version of the latest SDK to build the product's repos.

**Comment by eerhardt** [comment]
This was fixed in https://github.com/dotnet/aspnetcore/pull/47540 with https://github.com/dotnet/aspnetcore/pull/47540/commits/20f174567bb40f1238fdc868e8541fca2887bbaa. https://github.com/dotnet/aspnetcore/issues/47912 is tracking a "real" fix here rather than just disabling this check.

Closing as this is fixed in the latest "main".
