### ISSUE TITLE
Make Microsoft.AspNetCore.Html.HtmlString implement System.Web.IHtmlString

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#48037]
## Background and Motivation

Given that `System.Web.IHtmlString` is being added to the runtime in .NET 8 without the corresponding System.Web.HtmlString implementation, we decided in runtime API review that it makes sense to have ASP.NET Core's `HtmlString` implement the interface. See https://github.com/dotnet/runtime/issues/83477.

## Proposed API

```diff
// Microsoft.AspNetCore.Html.Abstractions.dll
namespace Microsoft.AspNetCore.Html;

- public class HtmlString : IHtmlContent
+ public class HtmlString : IHtmlContent, System.Web.IHtmlString
{
+     string IHtmlString.ToHtmlString();
}
```

## Usage Examples

You can use code blocks like this:

```csharp
var myHtml = new HtmlString("<strong>My important safe HTML content!</strong>");
LegacyApiThatStillCallsHttpUtilityHtmlEncode(myHtml);
```

## Alternative Designs

We could add a default interface implementation to `IHtmlContent` as suggested by @twsouthwick [in the runtime issue](https://github.com/dotnet/runtime/issues/83477#issuecomment-1531988710). This might make it less clear to consumers of the interface that the `WriteTo` implementation is generally preferred.

```diff
- public interface IHtmlContent
+ public interface IHtmlContent : System.Web.IHtmlString
{
    void WriteTo(TextWriter writer, HtmlEncoder encoder);

+   string System.Web.IHtmlString.ToHtmlString()
+   {
+       using var writer = new StringWriter();
+       WriteTo(writer, HtmlEncoder.Default);
+       return writer.ToString();
+   }
}
```

We could consider making `ToHtmlString()` fully public. I decide against that in the primary proposal since `HtmlString.Value` provides an existing way to get the original string from an ASP.NET Core `HtmlString`.

```diff
- public class HtmlString : IHtmlContent
+ public class HtmlString : IHtmlContent, System.Web.IHtmlString
{
+     public string ToHtmlString();
}
```

We could also consider implementing `IHtmlString` on a few more specific types like `HtmlFormattableString` and `LocalizedHtmlString`. This could be either as an alternative or in addition to the default interface implementation. The original runtime proposal just suggested bringing over `HtmlString` though, so I think it's safest to start with that.

Or we could decide to not implement `IHtmlString` at all and say implement it yourself since it's so easy to do.

## Risks

- We unintentionally encourage more usage of `IHtmlString` instead of `IHtmlContent` or `IHtmlAsyncContent` which would generally be preferred in ASP.NET Core.
- People think that since one built-in `IHtmlContent` implementation implements `IHtmlString`, they all do.

@stephentoub @twsouthwick

**Comment by twsouthwick** [comment]
One of the main goals of the System.Web adapters project is to allow people to compile their libraries to .NET Standard without having to rewrite the world. In that direction, I'd like to implement the `System.Web.HtmlString` type in the adapters and have it follow the current pattern of type forward on .NET Framework, while providing a .NET Standard way of referencing it.

Since we want to push people to use the ASP.NET Core type, we can use the adapters to bridge the two worlds, including automatic conversion between the System.Web and the ASP.NET Core representation (this kind of conversion is a common pattern we've set up in the adapters to help people slowly migrate code):

```diff
namespace System.Web;

public class HtmlString : IHtmlString
#if NET6_0_OR_GREATER
+  , IHtmlContent
#endif
{
  public HtmlString(string value);

  public string ToHtmlString();

  public override string ToString();

#if NET6_0_OR_GREATER
+  public void WriteTo(TextWriter writer, HtmlEncoder encoder);

+  public static implicit operator HtmlString?(Microsoft.AspNetCore.Html.HtmlString? other};

+  public static implicit operator Microsoft.AspNetCore.Html.HtmlString?(HtmlString other};
#endif
}
```

See https://github.com/dotnet/systemweb-adapters/compare/main...tasou/htmlstring

@CZEMacLeod I know you've been interested in this feature - do you have an opinion here?

**Comment by CZEMacLeod** [comment]
@twsouthwick The implementation of System.Web.HtmlString looks good and the built in casts will help. The potential problem area is if we pass a Core HtmlString object (as object) to legacy code. It won't detect that it can be cast to an object that implements the interface.
Since default ctype operators can't be defined for interfaces (yet?) this could still break when mixing and matching legacy and new code while migrating.
The most obvious solution is to make IHtmlContent implement IHtmlString using a default implementation, and then use a better implementation for the Core HtmlString and related concrete types.
The issue of confusing consumers with ToHtmlString is a potential issue, however this could be mitigated with some decoration attributes to hide the member from intellisense, or even mark it as obsolete (although it won't be removed).
The alternative of implementing IHtmlString on Core HtmlString only is the simpler, and lower cost solution, especially if it is not public. This would hide the change from most users.
I think the question comes down to impact and mitigation.
For people migrating codebases, the interface implementation is best and most robust, but it is also easily documented what to look for and a simple cast can fix it in most cases.
To prevent confusion or potentially encouraging people to use the older technology, just privately implementing the interface on HtmlString will cover most problematic cases during migration.
I don't know if this adds anything or just reiterates the points already made, but either solution has pros and cons. I guess it is up to you guys to decide which has the best ratio.

**Comment by javiercn** [comment]
I'm a bit conflicted about having HtmlString implement a legacy interface. 

Can you provide a concrete scenario where this is useful? As in what code does a user need to write today vs what they will have to do without it, and where will that code be used.

**Comment by twsouthwick** [comment]
I'm fine with this for now. My main push for the `IHtmlString` was to enable *existing* patterns, not necessarily seeing a need to adapt it to newer ones. I've added support for this in the System.Web adapters which should handle most use cases for migration (i.e. using existing types and patterns). If we see evidence of people needing to call `HttpUtility.HtmlEncode` with an `IHtmlContent` we can readdress it then.
