### ISSUE TITLE
Dependency Injected pooled instances

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#48172]
## Background and Motivation

To provide a way to register object pools of scoped dependencies that will be created using DI resolution.
Pooled objects can then be reused across requests.

A custom option object provides a way to configure the pool size externally.

## Proposed API

```c#
namespace Microsoft.Extensions.DependencyInjection.Pools;

public static class DependencyInjectionExtensions
{
    public static IServiceCollection AddPool<TDefinition>(this IServiceCollection services, Action<PoolOptions>? configure = null) 
        where TDefinition : class

    public static IServiceCollection AddPool<TDefinition, TImplementation>(this IServiceCollection services, Action<PoolOptions>? configure = null)
        where TDefinition : class
        where TImplementation : class, TDefinition

    public static IServiceCollection ConfigurePools(this IServiceCollection services, IConfigurationSection section)
}

public sealed class PoolOptions
{
    public int Capacity { get; set; } = Environment.ProcessorCount * 2;
}
```

Internally an `ObjectPool<T>` is registered as a singleton and uses a custom `IPooledObjectPolicy` that uses the service provider to create new instances (referred as `DependencyInjectedPooledObjectPolicy` later in this document).

### Resolving the pool and using it directly

```c#
services
    .AddPool<MyService>()
    .AddScoped<Consumer>()
    ;
```

```c#
public class Consumer
{
    private readonly MyService _myService;
    
    public Consumer(ObjectPool<MyService> myServicePool)
    {
        var myService = myServicePool.Get();
        
        myService.DoSomething();

        myServicePool.Return(myService);
    }
}

public class MyService : IDisposable, IResettable
{
    // Lots of properties
    // ...

    private readonly ILogger _logger;

    public MyService(ILogger<MyService> logger)
    {
        _logger = logger;

        // Expensive initialization
        // ...
    }

    public void DoSomething()
    {
        // ...
        logger.Debug("Something was done");
    }

    public bool TryReset()
    {
        // ...
        return true;
    }
}
```

### Resolving a pooled instance without prior knowledge of pools:

```c#
services
    .AddPool<PooledFeature>()
    .AddScoped(provider => provider.GetRequiredService<ObjectPool<PooledFeature>>().Get())
    .AddScoped(provider => provider.GetRequiredService<PooledFeature>().Feature)
    ;
```

```c#
internal sealed class PooledFeature : IDisposable
{
    private readonly ObjectPool<PooledFeature> _pool;
    public Feature Feature { get; }
    
    public PoolHelper(ObjectPool<PooledFeature> pool, ILogger<CustomFeature> logger)
    {
        _pool = pool;
        Feature = new Feature(logger);
    }

    public void Dispose()
    {
        Feature.Reset();
        _pool.Return(this);
    }
}
```

### Expose the policy publicly only

[This article](https://learn.microsoft.com/en-us/aspnet/core/performance/objectpool?view=aspnetcore-7.0#objectpool-sample) describes how to use `ObjectPool<T>` with a `StringBuilder` like this: 

```c#
builder.Services.TryAddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();
builder.Services.TryAddSingleton<ObjectPool<StringBuilder>>(serviceProvider =>
{
    var provider = serviceProvider.GetRequiredService<ObjectPoolProvider>();
    var policy = new Microsoft.Extensions.ObjectPool.StringBuilderPooledObjectPolicy();
    return provider.Create(policy);
});
```

An alternative design to the proposal would be to only provide a custom `DependencyInjectedPooledObjectPolicy` as a public type to be used the same way for types that need to resolve dependencies from DI.

### Open generic

```c#
namespace Microsoft.Extensions.DependencyInjection.Pools;

public static class DependencyInjectionExtensions
{
    public static IServiceCollection AddObjectPools(this IServiceCollection services);
}

public sealed class PoolOptions
{
    public int Capacity { get; set; } = Environment.ProcessorCount * 2;
}

namespaceMicrosoft.Extensions.ObjectPool;

public interface IObjectPool<T> where T : class
{
    T Get();
    void Return(T obj);
}
```

#### Usage:

```c#
var services = new ServiceCollection()
    .AddSingleton<TestDependency>()
    .AddScoped<ITestClass, TestClass>()
    .AddObjectPools();
    

var pool = provider.GetRequiredService<IObjectPool<ITestClass>>();
var pooled = pool .Get();
pool.Return(pooled);
```

#### Automatic pooled dependency

Optionally we can implement a usage that allows to resolve scoped dependencies directly that would be returned when the scope expires.

```c#
var services = new ServiceCollection()
  .AddSingleton<TestDependency>()
  .AddObjectPools()
  .AddScoped<TestClass>()
  .AddTransient<Pooled<TestClass>>()
  .AddScoped<ITestClass>(provider =>
  {
    var pooled = provider.GetRequiredService<Pooled<TestClass>>();
    return pooled.Object;
  });
;

using (var scope = provider.CreateScope())
{
    resolved1 = scope.ServiceProvider.GetRequiredService<ITestClass>();
    resolved2 = scope.ServiceProvider.GetRequiredService<ITestClass>();
}

Assert.True(resolved1 == resolved2);
Assert.Equal(1, resolved1.DisposedCalled);
Assert.Equal(1, resolved1.ResetCalled);
```

## Risks

- Where should it go since it depends on M.E.ObjectPool and M.E.DependencyInjection ?
- Pooling objects with scoped/transient dependencies might leak services across requests that are not meant to be reused.
- As with any pooled objects, not returning instances correctly would invalidate the use of pools.

**Comment by davidfowl** [comment]
This looks like minimal DI support for adding a closed generic object pool. That seems fine. I would also remove the ConfigurePools overload that takes `IConfigurationSection`.

**Comment by sebastienros** [comment]
> adding a closed generic object pool

Do you think an open generic would make more sense? Are there inherent challenges?

**Comment by davidfowl** [comment]
I feel like the open generic makes more sense for this. 

```C#
services.AddObjectPools()
```

**Comment by sebastienros** [comment]
Updated with open generic design. Branch is here: https://github.com/dotnet/aspnetcore/compare/main...sebros/opengenerics

**Comment by halter73** [comment]
API Review Notes:

- What dll is this going into?
  - It will depend on both Microsoft.Extensions.DependencyInjection.Abstractions and Microsoft.Extensions.ObjectPool.
  - Microsoft.Extensions.ObjectPool has no dependency on M.E.DI. And there's no dependency in the other direction either.
  - The namespace is proposed as Microsoft.Extensions.DependencyInjection.Pools.
  - Can we add a M.E.DI dependency to Microsoft.Extensions.ObjectPool?
- Is this a new DI lifetime? Is "pooled" similar to singleton/scoped/transient?
  - We're considering core DI changes for named services.
- "Pooling objects with scoped/transient dependencies might leak services across requests that are not meant to be reused" seems like a serious risk.
  - Does making the pooled objects resettable mitigate this?
    - That wouldn't help if you pooled a DbContext which is then disposed.
  - In practice, the pooled resources can only depend on singletons and transient services.
- This could be useful for M.E.ML
- The open generic proposal is preferred by @sebastienros even though it's an "alternative"
  - The open generic proposal seems to make the risk of misusing the pool for scoped service worse. Now a caller can resolve any service from a pool.
  - Or you could say this is more like `IOptions<TOptions>` which people don't really seem to misuse.
    - But `IOptions<TOptions>` uses `new()` not `ActivatorUtilities`.
  - Let's leave it up to library authors and service registering code to say what is pooled.
- How are the types activated?
  - ActivatorUtilities. They can resolve services.
- Does `where TDefinition : IResettable` mitigate misusage?
  - Requiring `IResettable` is annoying? What if you just want to pool `StringBuilder`? 
- How do you use a custom `PooledObjectPolicy`?
  - You cannot, because DI is defining its own `PooledObjectPolicy`.
  - Why can't we add an overload that takes `IPooledObjectPolicy<TImplementation>`?
- `AddPool` -> `AddPooled`? Pro and con, sounds a lot like a new lifetime and it's not (e.g. `AddScoped`, `AddSingleton`, `AddTransient`).
  - We like it.
- What about `DependencyInjectionExtensions`? Maybe `ObjectPoolServiceCollectionExtensions`.

Here's what we're thinking so far.

```csharp
// Microsoft.Extensions.ObjectPool.dll
namespace Microsoft.Extensions.ObjectPool;

public static class ObjectPoolServiceCollectionExtensions
{
    public static IServiceCollection AddPooled<TDefinition>(this IServiceCollection services, Action<PoolOptions>? configure = null) 
        where TDefinition : class

    public static IServiceCollection AddPooled<TDefinition, TImplementation>(this IServiceCollection services, Action<PoolOptions>? configure = null)
        where TDefinition : class
        where TImplementation : class, TDefinition

    public static IServiceCollection AddPool<TDefinition, TImplementation>(this IServiceCollection services, IPooledObjectPolicy<TImplementation> pooledObjectPolicy, Action<PoolOptions>? configure = null)
        where TDefinition : class
        where TImplementation : class, TDefinition

    public static IServiceCollection ConfigurePools(this IServiceCollection services, IConfigurationSection section)
}

public sealed class PoolOptions
{
    public int Capacity { get; set; } = Environment.ProcessorCount * 2;
}
```

Note: M.E.DI = Microsoft.Extensions.DependencyInjection.Abstractions

**Comment by davidfowl** [comment]
New dll and add it to the shared framework. I'm not sure about the ConfigurePools (also why not IConfiguration vs IConfigurationSection). I think we need the ability to configure per pool type and for all pools so its possible pool options will need to be generic?

**Comment by adityamandaleeka** [comment]
cc @benjaminpetit for awareness

**Comment by sebastienros** [comment]
Updated proposal

```diff
```

**Comment by halter73** [comment]
API Review Notes:

- Should `TDefinition` be called `TService` to match DI?
  - It's not exactly a service, but it sounds better than `TDefinition` which sounds too similar to `TImplementation`.
  - `TPooled`? It's not obvious what it means.
- What happens if `builder.Services.Configure<PoolOptions>(() => ...)`? Do these configure methods get called before the specific `AddPooled`?
- Could we have a `ConfigurePools(IConfiguration)` that configures each pool independently keyed by fully qualified type name?
  - Can this use named options?
    - The per-type configuration already is.
  - Is there a similar API we've shipped that has cascading global, and per-type options? AuthenticationOptions don't work that way.
- Does it make sense to change a global default at all? Isn't it very specific to what is being pooled?
  - Maybe we can avoid doing this. It's something that could potentially added later if necessary.
  - For now at least.`builder.Services.Configure<PoolOptions>(() => ...)` does nothing.
- Is the `ConfigurePools<TDefinition>(this IServiceCollection services, Action<PoolOptions> configureOptions)` necessary? You can configure during the call to `AddPooled`.
  - Could be useful if an extension method added a pool internally you want to reconfigure.
  - Manually using named options is annoying.
  - Figuring out the right key could require looking at the docs or implementation.
  - We can also add the extra config methods later.
  - If you want to use the same internal `TImplementation` that a library added in an extension method but reconfigure the count using just the `TService`, it could be useful.
- Do we need an `AddPooled` overload that accepts a `IPooledObjectPolicy<TImplementation>`?
  - If you really want to do this, you can add the `ObjectPool<TImplementation>` to DI yourself.
- Should `ConfigurePools<TService>` be called `ConfigurePool<TService>` or `ConfigurePooled<TService>`?
  - Let's make it singular `ConfigurPool` instead
- Does `AddPooled` override previous calls with the same `TService` but a different `TImplementation`?
  - Yes. If it didn't, we should call it `TryAddPooled`.
- Would we consider `AddPool` or `AddObjectPool` over `AddPooled`?
  - Everyone like `AddPooled`.

API Approved!

```diff
// Microsoft.Extensions.ObjectPool.dll
namespace Microsoft.Extensions.ObjectPool;

+ public static class ObjectPoolServiceCollectionExtensions
+ {
+    public static IServiceCollection AddPooled<TService>(this IServiceCollection services, Action<PoolOptions>? configure = null) 
+        where TService : class
+
+   public static IServiceCollection AddPooled<TService, TImplementation>(this IServiceCollection services, Action<PoolOptions>? configureOptions = null)
+        where TService : class
+        where TImplementation : class, TService
+
+   public static IServiceCollection ConfigurePool<TService>(this IServiceCollection services, Action<PoolOptions> configureOptions)
+       where TService : class    
+ }

+ public sealed class PoolOptions
+ {
+    public int Capacity { get; set; } = Environment.ProcessorCount * 2;
+ }
```

**Comment by joperezr** [comment]
I'm assuming we can now close this one as no longer planned given that we've added [a library that does it in dotnet/extensions repo](https://github.com/dotnet/extensions/pull/4038)?

**Comment by joperezr** [comment]
Closing this for now due to the above. Feel free to reopen if needed.
