### ISSUE TITLE
Blazor server Cascading Value refreshed wrong

### ISSUE THREAD

**Issue by AlexNek** [dotnet/aspnetcore#48223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to search why OnParametersSetAsync() for component with CascadingValue/CascadingParameter called twice.
Here is the simple code for it
```
<button @onclick="OnRefresh">Refresh</button><br/>
<CascadingValue Value="@_forecasts" IsFixed="false">
    <TestComponent></TestComponent>
</CascadingValue>
@code {
    private WeatherForecast[]? _forecasts;

    protected override async Task OnInitializedAsync()
    {
        Console.WriteLine("---Main component loading shared data---");
        _forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }

    private async Task OnRefresh()
    {
        Console.WriteLine("---Pressed button Refresh---");
        await Task.Delay(200);
    }
```
I'm very curious why cascaded value refreshed? Complete project you can find in attachment

---Pressed button Refresh---
set:[Forecasts, BlazorTestCascadingValue.Data.WeatherForecast[]]
OnParametersSetAsync enter
set:[Forecasts, BlazorTestCascadingValue.Data.WeatherForecast[]]
OnParametersSetAsync enter
OnParametersSetAsync exit
OnParametersSetAsync exit

### Expected Behavior

In this case I expect no refresh for CascadingValue.
In case of refreshing the value I expected that refresh will be only once

### Steps To Reproduce

[Sample project](https://github.com/ANTestGit/BlazorTestCascadingValue/tree/main)

### .NET Version

7.0.203

**Comment by Flachdachs** [comment]
The Index component returns incomplete tasks, when the app starts in OnInitializedAsync and when refreshing in OnRefresh. A component is rendered after its lifecycle methods. If it has incomplete tasks it is rerendered when these incomplete tasks are completed. So you have immediate reaction on the screen, e.g. to show a spinner, and at the end to show the data after the time consuming work. That's how the lifecycle works.

**Comment by AlexNek** [comment]
Are you talking about some time interval?
How must I correct my code that it is working well?
Why I have the notification that _forecasts value changed?

**Comment by Flachdachs** [comment]
I'm talking about the [documented component lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle). Your code is not wrong. You don't get a notification for "_forecast has changed". SetParameterAsync() is called in general with all parameters that the parent component is giving you, but it doesn't make a statement about "has changed" or not. When you want to know if a value has changed, you have to compare the value in the ParameterView collection with the current value in your (Cascading)Parameter before calling `base.SetParametersAsync()`. But, do you really need to know this?

**Comment by AlexNek** [comment]
>Your code is not wrong
Then you want to tell that reaction is misunderstanding by me and other teammates?
Why then function named as 'Set Parameter'? Then I expected at least some note into documentation.
And why if I set` IsFixed='true'` then all working as expected? Why lifecycle related to it?

I more interested for [OnParametersSetAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onparameterssetasync?view=aspnetcore-6.0)
because we reread related data into this function.

>do you really need to know this
Yes of course, I want to know when my data is changed. What is bad in this Idea?

**Comment by Flachdachs** [comment]
It's not bad, but maybe the wrong question. What do you really want to achieve?

You may think that a lifecycle method is a good way to detect a change, but instead it could be better to have a service injected into the component. This service could fire an event when data have changed. So you can react exactly without writing workarounds for unwanted lifecycle behavior.

If you really need to know that Parameter data has changed, there is no other way than comparing it in SetParameterAsync. It is too late in OnParameterSet{Async}, because Parameters are already overriden. Or you need to store a copy of the data elsewhere. However, you can't change the behavior of the lifecycle. These methods will be called often and are not necessarily an indicator of a change.

**Comment by AlexNek** [comment]
> but instead it could be better to have a service injected into the component. 

Do you mean that scoped service solved data sync over different components in a better way?

>However, you can't change the behavior of the lifecycle. 

The big problem for me that the behavior is different in case of using CascadedValue(s). I created new log entry for rendering cycle and created new branch with "fixed" CascadingValue and there are big difference. ParametersSet is not called as expected.

From there
>https://learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-7.0
>[CascadingValue<TValue>.IsFixed](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.cascadingvalue-1.isfixed) can be used to indicate that a cascading parameter doesn't change after initialization.

I can understood that if `IsFixed == false` I must inform me every time when parameter is changed. And with 'normal' parameters all working fine with (On)ParametersSetAsync, so I expected the same behavior with cascading parameters.

**Comment by Flachdachs** [comment]
Whatever the reason is that the framework behavior is designed as is, it apparently doesn't fit your needs in this case, so you have to search for an alternative. To change the behavior in a way you want it, will break a lot of applications that are written for the current behavior. If at all, I can only imagine that such a breaking change comes in a major version, and surely not in 8.0 which is already in preview. So, in practical reasons for your app, it is better to search for a different solution than to wait a long time until a change is available. However, these are just my thoughts, not official statements of the framework developers.

Some rhetorical questions. Is there a reason why the parent component provides the data of the service to the client component? Why does the client component not query the service itself? Does the parent do something with it, that the client can't or shouldn't. If yes, why can't the service do this and cache the result? Does it need to be done every time a render cycle is started?

**Comment by AlexNek** [comment]
>Is there a reason why the parent component provides the data of the service to the client component?

What you can see is only behavior demo. In the real application there are more that one child (simple viewer, extended viewer, editors and so on). The application data is complex and I think nobody will read the same data parts again and again. In addition, it is existing project and nobody know today why some things implemented in this or different way.

For me personally, cascading values is a global variables for blazor parts and I will never use it. I already create (loader service)[https://github.com/ANTestGit/BlazorTestCascadingValue/blob/LoaderService/BlazorTestCascadingValue/Services/DataLoaderService.cs] but not sure if we want to have such big changes for the project. At least, we must pay attention to this issue somehow.

>Does it need to be done every time a render cycle is started?

No. That exactly was the error and why I try to understood the problem.
