### ISSUE TITLE
SystemTextJsonOutputFormatter cannot handle multiple encodings

### ISSUE THREAD

**Issue by i2um1** [dotnet/aspnetcore#48286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I have a simple ASP.NET Core Web API application on .NET 6:

Program.cs:
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers(options => options.RespectBrowserAcceptHeader = true);

var app = builder.Build();
app.UseAuthorization();
app.MapControllers();
app.Run();
```

TestController.cs:
```cs
using Microsoft.AspNetCore.Mvc;

[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{
    [HttpGet]
    public SomeClass Get() => new() { SomeProperty = "some text" };
}

public class SomeClass
{
    public string SomeProperty { get; set; }
}
```

My request:
```
GET http://localhost:5161/test
Content-Type: application/json;charset=utf-16
```

Actual response:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 17 May 2023 15:57:28 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "someProperty": "some text"
}
```

The API must return either UTF-8 or UTF-16 due to the Content-Type header from the request but it always returns UTF-8. After several tests, I found out that SystemTextJsonOutputFormatter has a bug in the base class on the following lines:
```cs
public virtual Encoding SelectCharacterEncoding(OutputFormatterWriteContext context)
{
    // ...
    var parsedContentType = new MediaType(context.ContentType);
    var contentTypeCharset = parsedContentType.Charset;
```

So, I have a few questions:
1. Why is `context.ContentType` always `"application/json;charset=utf-8"`?
2. Why does SystemTextJsonInputFormatter use `context.HttpContext.Request.ContentType` instead?

### Expected Behavior

Expected response:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-16
Date: Wed, 17 May 2023 15:57:28 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "someProperty": "some text"
}
```

Also, the body must be encoded in UTF-16. The old ASP.NET on .NET Framework 4.7.2 returns UTF-16.

### Steps To Reproduce

Just call the request.

### .NET Version

6.0.15

**Comment by halter73** [comment]
The output formatter uses the [Accept-Charset](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset) request header to determine the encoding for the response body. The [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) request header tells the server the content type and encoding of the request body but is not intended to affect the response body. Note that you set `RespectBrowserAcceptHeader` to true, not `RespectBrowserContentTypeHeader`. But as the mdn docs note, you're probably better off always responding with a utf-8 encoding particularly if the clients are browsers. That's why it's false by default.

If you really want to go a non-standard route, and use the `Content-Type` request header to determine the response encoding, you could create your own class that derives from `SystemTextJsonOutputFormatter`. I advise against doing this though.

```csharp
public class MyJsonOutputFormatter : SystemTextJsonOutputFormatter
{
    public MyJsonOutputFormatter (JsonSerializerOptions jsonSerializerOptions) : base(jsonSerializerOptions) { }

    public override Encoding SelectCharacterEncoding(OutputFormatterWriteContext context)
    {
        var contentTypeRequestHeader = context.HttpContext.Request.Headers.ContentType;

        if (!StringValues.IsNullOrEmpty(contentTypeRequestHeader)
        {
            context.ContentType = new StringSegment(contentTypeRequestHeader);
        }

        return base.SelectCharacterEncoding(context);
    }
}
````

https://learn.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-7.0

**Comment by i2um1** [comment]
@halter73, you are right, Accept-Charset works but Content-Type, Content-Enconding and Accept don't work. Is it a known breaking change of ASP.NET Core?

Request:
```
GET http://localhost:5161/test
Accept-Charset: utf-16
```

Response:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-16
Date: Wed, 17 May 2023 17:21:38 GMT
Server: Kestrel
Transfer-Encoding: chunked

笀∀匀漀洀攀倀爀漀瀀攀爀琀礀∀㨀∀猀漀洀攀 琀攀砀琀∀紀
```

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset, Accept-Charset is deprecated.
![image](https://github.com/dotnet/aspnetcore/assets/2651116/f8cb09b6-1b3d-4743-94fb-c1981ce0a9b8)

**Comment by i2um1** [comment]
Where did you find RespectBrowserContentTypeHeader?

**Comment by halter73** [comment]
`RespectBrowserContentTypeHeader` is not a real thing. Never was. That was my point. `Accept-Charset` is the request header that tells the server what charset to use for the response body. It's deprecated because the recommendation is to not use any request header to determine the charset of the response and instead always use UTF-8 no matter what.

The request `Content-Type` was never intended to change how the response is encoded. It only affects the request body decoding. As far as I know, neither ASP.NET, ASP.NET Core nor any other web framework has ever used the `Content-Type` request header to determine how to encode the response body. Why do you think this is a breaking change?

**Comment by i2um1** [comment]
@halter73 
>As far as I know, neither ASP.NET, ASP.NET Core nor any other web framework has ever used the Content-Type request header to determine how to encode the response body.

I created a new ASP.NET Web API on .NET Framework 4.8:

```cs
public class ValuesController : ApiController
{
    public SomeClass Get()
    {
        return new SomeClass() { SomeProperty = "some text" };
    }

    public class SomeClass
    {
        public string SomeProperty { get; set; }
    }
}
```

UTF-8 request:
```
GET http://localhost:53612/api/values
Content-Type: application/json;charset=utf-8
```

Response:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?RDpcUHJvamVjdHNcVGVzdFxDb25zb2xlQXBwMVxXZWJTaXRlMlxhcGlcdmFsdWVz?=
X-Powered-By: ASP.NET
Date: Wed, 17 May 2023 18:06:11 GMT
Content-Length: 28

{
  "SomeProperty": "some text"
}
```

UTF-16 request:
```
GET http://localhost:53612/api/values
Content-Type: application/json;charset=utf-16
```

Response:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-16
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?RDpcUHJvamVjdHNcVGVzdFxDb25zb2xlQXBwMVxXZWJTaXRlMlxhcGlcdmFsdWVz?=
X-Powered-By: ASP.NET
Date: Wed, 17 May 2023 18:23:09 GMT
Content-Length: 58

{
  "SomeProperty": "some text"
}
```

As you can see, the response length for UTF-16 is doubled and, of course, it's encoded in UTF-16.

**Comment by i2um1** [comment]
@halter73, anyway, thank you for the last version of MyJsonOutputFormatter.
