### ISSUE TITLE
Revisiting Blazor Multi-threading

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#48345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It has been brought up before
https://github.com/dotnet/aspnetcore/issues/33583#issuecomment-862415656
Today I am approaching from another angle

We can already write multi-threaded code easily in blazor projects, using async or other ways

We can call StateHasChanged from other threads using InvokeAsync of component base and it works

But it would be nice that when StateHasChanged is called, the component can use multiple threads to render itself too (for example if a for loop has many item inside that translates to many thing to compare the delta in the old tree and do some update) so perhaps the rendering process itself can use multiple threads, so if I have money I bought a better device I should see improvement on many items being rendered faster, because the TCU was faster

### Describe the solution you'd like

Use parallel processing inside blazor for anything you do that involves a list of objects
if you can

the overhead will be minimal, nobody cares about 4 bytes reduction in size of a frame in blazor, itself is a framework for rendering content so the reduction in complexity out weights the overhead as the number of element being rendered increases, this scales alright, because developing countries are getting devices with multiple cores too, people buying more expensive hardware expect a gain, making sure things loading blazing fast on single core is not impressive usually

If I am trying to make animation using blazor, I would just draw a canvas and use F# and fable to do it without leaving blazor or .NET (you can use keyboard and mouse to play pac man using a canvas rendered by F# and fable with 120hz while being accelerated by GPU)

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

I think you are making a lot of simplifications about what is involved in authoring a multi-threaded renderer. It's not just the renderer code that matters, but the user code that suddenly starts running concurrently.

Making the rendering process multi-threaded will add a lot of complexity, and very likely won't result in the types of gains that you expect. If you think we are wrong in our assessment, we are happy if you think you can prove us wrong with a demo/prototype and we would happily evaluate if it meets the constraints imposed by the rendering process, but otherwise, this is not a direction we plan to explore, as we already have enough evidence about the challenges in this space and we don't think is worth it.

**Comment by Xyncgas** [comment]
Thanks
