### ISSUE TITLE
[Question] .NET6 Minimal API model binding error handling and Environment.

### ISSUE THREAD

**Issue by chanos-dev** [dotnet/aspnetcore#48355]
Hello.

I have a question about the minimal api.

If you use the minimal api in .net6 and get a parameter binding error, the result depends on your environment.

For Development, I get 400 BadRequest - "BadHttpRequestException Failed to bind parameter Guid id from 1."

For Production it just returns a 400 BadRequest response code without any Exception.

So I did the processing in middleware with try, catch, but Development works, but Production doesn't.

For Production, does it work internally in a different process than Development?

I couldn't find the relevant document, so please share it if you have one.

Additionally, I'm wondering if there is a way to handle the error when a parameter binding error occurs in the Production environment as above.

---

### Here's an example.
```csharp
app.MapGet("/weatherforecast/{id}", (Guid id) =>
{
    return Results.Ok(id);
});
```

### Development
![image](https://github.com/dotnet/aspnetcore/assets/48897081/6633fb09-391e-4ceb-adc8-ceb1eb83cb90)

### Production
![image](https://github.com/dotnet/aspnetcore/assets/48897081/b7bd23a7-d294-48a1-9762-93bdd7343cd0)

**Comment by captainsafia** [comment]
@chanos-dev In minimal APIs, the default behavior is that exceptions are thrown when parameter binding fails (because a required parameter was not provided, a parameter failed to parse, etc.) in `Development` environments. This behavior does not happen in production environments. The behavior can be controlled by configuring the `RouteHandlerOptions.ThrowOnBadRequest` option in your configuration like so:

```csharp
var builder = WebApplication.CreateBuilder();

builder.Services.Configure<RouteHandlerOptions>(options => options => options.ThrowOnBadRequest = true));

var app = builder.Build();

// Will always throw exception for invalid `id`
app.MapGet("/weatherforecast/{id}", (Guid id) =>
{
    return Results.Ok(id);
});
```

You might also consider implementing the error handling in an endpoint filter like so:

```csharp
var app = WebApplication.Create();

app.MapGet("/weatherforecast/{id}", (Guid id) =>
{
    return Results.Ok(id);
})
.AddEndpointFilter(async (context, next) =>
{
  var result = await next(context);
  if (context.HttpContext.StatusCode == StatusCodes.Status400BadRequest)
  {
    return Results.ProblemDetails(..);
  }
  return result;
});
```

One thing to note about the approach above is that you won't be able to access the particulars of why the binding failed (required parameter not provided vs. not parsable). Those details will be logged in your application though.

**Comment by chanos-dev** [comment]
Thank you so much @captainsafia!

Handled with `RouteHandlerOptions.ThrowOnBadRequest` in Production!

It seems that the `AddEndpointFilter` method that you additionally informed has been supported since .NET 7.

It's a pity that I'm currently using .NET 6 and can't try that method. 😥
