### ISSUE TITLE
Introduce KestrelServerOptions.AllowUnsafeHostHeaderOverride

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#48461]
## Background and Motivation

At the request of an internal partner, #39334 introduced an internal API and corresponding appcontext switch that made it possible to overwrite an incorrect Host header with a value derived from an absolute-form request target to handle the surprisingly common client behavior of missing the line-break after the host header, as IIS/Http.Sys did. This PR upgrades it to a public API since those clients aren't going away. The behavior is the same, it just has a name and a doc comment intended for broader consumption.

Issue: #39335 
PR: #48460

## Proposed API

```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Core;

public class KestrelServerOptions
{
+    public bool AllowUnsafeHostHeaderOverride { get; set; }
}
```

## Usage Examples

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseKestrel(serverOptions => {
    serverOptions.AllowUnsafeHostHeaderOverride = true
});
```

## Alternative Designs

We could add a new configuration setting, but we don't really want this to be widely used (since it can hide security threats) and the only existing consumer configured it in code.

## Risks

Opting in to this setting makes it easier to write a less secure server.

**Comment by JamesNK** [comment]
IMO "Override" in the name is unnecessary.

**Comment by amcasey** [comment]
> IMO "Override" in the name is unnecessary.

Tell me more?  Without it, I have trouble reading the name as indicating that the original host header will be replaced.

**Comment by JamesNK** [comment]
Setting `AllowUnsafeHostHeader = true` to allow an unsafe host header doesn't seem confusing.

```cs
builder.WebHost.UseKestrel(serverOptions =>
{
    serverOptions.AllowUnsafeHostHeader = true
});
```

By default, Kestrel doesn't allow unsafe host headers, and you're changing that to true.

I don't think adding "Override" to each setting that changes how Kestrel works adds any value.

**Comment by amcasey** [comment]
To confirm, it's not the setting that's being overridden, it's the actual header.  When the setting is true,
```
GET http://www.foo.com/api/data
Host: http://www.bar.com
```
is rewritten to 
```
GET http://www.foo.com/api/data
Host: http://www.foo.com
```
What do you think would be a clear way to express that that will happen?

**Comment by halter73** [comment]
API Review Notes:

- https://datatracker.ietf.org/doc/html/rfc9112#section-3.2.2-8 says you MUST use the host from the absolute form start line rather than HOST header if they do not match, so that's what this does.

> When an origin server receives a request with an absolute-form of request-target, the origin server MUST ignore the received Host header field (if any) and instead use the host information of the request-target. Note that if the request-target does not have an authority component, an empty Host header field will be sent in this case.

- The host from the start line will be validated just like the HOST header would normally be validated when it's overridden.
- Should we just follow the RFC and override any time there's a disagreement by default?
  - Technically we're not complying with the RFC if we don't. Do we really need to opt-in to follow the spec and be less strict. 
  - That seems sketchy. They almost always match for any conforming client. Not many people have asked for this.
- If this is the default IIS behavior and "required" by RFC, do we need `Unsafe` in the name?
  - No.
- What about `PreferRequestTargetHost`?
  - This is more clear about what overrides what.
  - It's less clear overall that it's about the HostHeader.
- Note in doc comments. This only applies to HTTP/1, because there are no more absolute form request targets.

API Approved!

```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Core;

public class KestrelServerOptions
{
+    public bool AllowHostHeaderOverride { get; set; }
}
```

**Comment by amcasey** [comment]
Obviously, I have completely forgotten what we discussed.  If anyone remembers an action item beyond "rename the property", speak now.  (The notes seem pretty clear, but I'm not sure why I wouldn't have just done the rename during the meeting.)
