### ISSUE TITLE
Found a spelling mistake in visual studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#48693]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Found-a-spelling-mistake-in-visual-studi/1598031)._

---
The spelling in the highlighted area in the attached picture should be minimal instead of "mininmal".
! [image_2021_11_29T10_13_37_508Z.png] (https://aka.ms/dc/image?name=Ba4519afb399a450db770291f9cf7fcea637737776473276436_image_2021_11_29T10_13_37_508Z.png&tid=a4519afb399a450db770291f9cf7fcea637737776473276436)

---
#### Feedback Bot on 11/29/2021, 06:57 PM: 

(private comment, text removed)
#### Sara Liu [MSFT] on 11/29/2021, 10:15 PM: 

(private comment, text removed)
#### Feedback Bot on 3/1/2022, 11:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gfoidl** [comment]
The attached image above is 
![Ba4519afb399a450db770291f9cf7fcea637737776473276436_image_2021_11_29T10_13_37_508Z-1](https://github.com/dotnet/aspnetcore/assets/5755834/7753eef4-b025-4e7e-87e6-9fcc262620a2)

---

This typo got fixed with https://github.com/dotnet/aspnetcore/pull/37780

And recent versions of VS 2022 (e.g. 17.6.2) don't show that typo: 
![grafik](https://github.com/dotnet/aspnetcore/assets/5755834/8022e27c-df96-4853-a081-c9b6be819907)

So I'm closing that issue, as nothing needs to be done.
