### ISSUE TITLE
Redesign the ViewEngine to be async

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#4880]
* `IViewEngine` could be designed to be made without relying on HTTP. This may allow for not-HTTP scenarios such as email generation in background tasks. An alternative to this would be to recommend using components for this.
* Requirements for resdesign:
    - Existing scenarios must work
    - Have a package that does runtime compilation. Cannot be shipped with the shared fx, but can depend on it.

* `IViewEngine`    - `FindView` \ `GetView` could be merged if we can flow the `ExecutingFilePath` thru. 

```C#
interface IViewFactory
{
    IViewTemplatingSystem FindViewAsync(ViewFactoryContext); // This is the combined API
}

public readonly ViewFactoryContext
{
    public ActionContext ActionContext { get; set; }

    public string ExecutingFilePath { get; set; }

    public string Name { get; set; }

    public bool IsMainPage { get; set; }
}

IViewTemplatingSystem.ExecuteAsync(Options)
```

![20181116_224609997_ios](https://user-images.githubusercontent.com/174281/48652608-3d347300-e9b5-11e8-85dd-8e8229d22e90.jpg)

**Comment by mkArtakMSFT** [comment]
Reducing the priority, as this impacts only the non-default case, which is runtime-compilation scenario.

**Comment by effyteva** [comment]
Hi,
Any chance this will still make it to the 3.0.0 release?
There's a simple PR for that which I sent a few months ago: https://github.com/aspnet/Mvc/pull/8554

**Comment by pranavkm** [comment]
@effyteva I'd be happy to consider another PR if you send one. I did a fair bit of work to update the RazorViewEngine to be async here - https://github.com/aspnet/AspNetCore/commit/306c47f10004099200a92b148b9bc1e4704bfc77. You could consider using that as starting point.

**Comment by effyteva** [comment]
Thanks @pranavkm,
I believe you covered it on all https://github.com/aspnet/AspNetCore/commit/306c47f10004099200a92b148b9bc1e4704bfc77, as long as the EditorForAsync and the DisplayForAsync are there and working.
Was you change committed?

**Comment by pranavkm** [comment]
The changeset doesn't cover tests or code review, there's a fair bit of that. Since the sync version of some of the HtmlHelper methods would continue to exists, we want some coverage for those. This would be the stretch goal, but we would also want something like the [`Html.Partial` analyzer](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Analyzers/src/AvoidHtmlPartialAnalyzer.cs) for `DisplayFor` \ `EditorFor` methods

**Comment by effyteva** [comment]
I have to say that's very disappointing.
The ASP.NET Core Razor engine currently suffers from deadlocks (see this https://github.com/aspnet/AspNetCore/issues/4755) due to having sync-over-async code.
We've been using a custom build of the ViewEngine for more than a year, and we'll have to keep creating new customer builds for each ASP.NET core release.

**Comment by mkArtakMSFT** [comment]
Closing as this is not something we plan to do in the near future.
