### ISSUE TITLE
Blazor ErrorBoundary child component exception

### ISSUE THREAD

**Issue by accacc** [dotnet/aspnetcore#48828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have one custom ErrorBoundary component that I'm placing in MainLayout. If there is an error in any child component, it goes into an endless loop within the parent component. Thank you in advance for your help. I'm also including the link to the solution: 

https://github.com/accacc/EndlessLoop

### Expected Behavior

no recursive loop

### Steps To Reproduce

```razor
    @inherits ErrorBoundary
    @inject ISnackbar Snackbar
    @if (CurrentException is null)
    {
        @ChildContent
    }
    else if (ErrorContent is not null)
    {
        @ErrorContent(CurrentException)
    }
    else
    {
        @ChildContent
    
        @foreach (var exception in receivedExceptions)
        {
            Snackbar.Add(@exception.Message, Severity.Error);
            @exception.Message
        }
    
    
    
        Recover();
    }
    
    @code {
        List<Exception> receivedExceptions = new();
    
        protected override Task OnErrorAsync(Exception exception)
        {
            receivedExceptions.Add(exception);
            return  base.OnErrorAsync(exception);
        }
    
        public new void Recover()
        {
            receivedExceptions.Clear();
            base.Recover();
        }
    }

```

Parent Component

```razor
@page "/"

@inject ISnackbar Snackbar
@using System.Net;


<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

@error - @ex

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<MyComp></MyComp>


@code{
    public int error;
    public string ex;

    protected override Task OnInitializedAsync()
    {
        //Snackbar.Add("OK", Severity.Error);
        return base.OnInitializedAsync();
    }
}
```

Child component

```razor
<h3>MyComp</h3>

@error

@code {
    public int error;

    protected async override Task OnInitializedAsync()
    {
        await Task.Delay(5);

        error++;
        throw new Exception("aaa");

    }
}
```

### Exceptions (if any)

no

### .NET Version

6.0

**Comment by SteveSandersonMS** [comment]
The updated code has another problem that also creates an infinite loop. Inside your error boundary, when there's an exception, it also tries to render `MyComp` which will then throw again:

```razor
    else
    {
        @* This re-renders the child, which will then just throw again, hence the infinite loop *@
        @ChildContent
    
        @foreach (var exception in receivedExceptions)
        {
            Snackbar.Add(@exception.Message, Severity.Error);
            @exception.Message
        }  
    }
```

You'll need to not do that. Here's a version of your code that does not have this problem, since it doesn't keep re-rendering the content that always throws: https://blazorrepl.telerik.com/wHOKvKOX118Of8QW28

**Comment by accacc** [comment]
Only can i ask that,If any child component is already throwing an exception, shouldn't it not be rendered at all? I cannot control all child controllers as you mentioned. When rendering all child components under the parent in a tree-like structure, the ones that throw exceptions should not be rendered, meaning the OnInitializedAsync method should not be called for them.

**Comment by SteveSandersonMS** [comment]
I'm afraid that's not how it works. By putting an error boundary in a particular place, you're setting that as the granularity of your exception handling. It's like choosing where a try/catch block goes. If there's an exception within that block, that entire block is now in an undefined state and so Blazor has to remove it otherwise you would have undefined behavior. If you don't control the child content, you can't control whether or not they could tolerate running when some of their siblings or descendants are in an error state.

**Comment by accacc** [comment]
so that ErrorBoundary is not way handle of global exception.

**Comment by SteveSandersonMS** [comment]
Not if your goal is to have "on error continue next"-style semantics, no.

If your goal is to perform logging, consider implementing a custom logger provider (docs: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-7.0#custom-logger-provider-blazor-webassembly)
