### ISSUE TITLE
CreateSanitizedId should change to reflect HTML5 latest spec

### ISSUE THREAD

**Issue by doggy8088** [dotnet/aspnetcore#4894]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
Repo: https://github.com/doggy8088/ASPNETCORE_HTML5_Id

Steps:

1. `git clone https://github.com/doggy8088/ASPNETCORE_HTML5_Id.git`
2. `cd ASPNETCORE_HTML5_Id/ASPNETCORE_HTML5_Id`
3. `dotnet run`
4. Navigate to https://localhost:5001/Home/Test
5. Check the following `id` attribute:

  ![image](https://user-images.githubusercontent.com/88981/40888684-542339ca-678d-11e8-821f-bdb0c287b7bc.png)

#### Description of the problem:

Here is my model:
![image](https://user-images.githubusercontent.com/88981/40888682-4dd51f16-678d-11e8-8743-3dd13dc6ccfc.png)

The HTML output become:
![image](https://user-images.githubusercontent.com/88981/40888691-70149bba-678d-11e8-8c8e-6a7b79aee658.png)

There is a [`CreateSanitizedId` method](https://github.com/aspnet/Mvc/blob/9d38e2523c88b190e8df7665ad8cc1da06519a8f/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/TagBuilder.cs#L141-L144) in the `Microsoft.AspNetCore.Mvc.Rendering.TagBuilder` class.  In this method, it sanitized all the `id` attribute for all HTML tags to apply HTML4.01 spec for a long time which is no problem at all. 

The HTML 4.01 spec states that ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (-), underscores (_), colons (:), and periods (.).  HTML5 gets rid of that restrictions on the `id` attribute now. 

For a modern web framework, I think it should align with the HTML5 specification and deprecated the old behavior.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 
All of them.  All versions.

**Comment by javiercn** [comment]
I think this bug is simply about not sanitizing the id element (as HTML5 allows everything but spaces) so that it matches the property name when it contains non unicode characters and so that its exactly the same as the property name for purposes like interacting with the element through JavaScript.

I'm not sure what transformations we do when we find non-ascii characters on the id, but if its not obvious, it clearly posses an issue when interacting through JavaScript.

In theory we could do this, I don't think we need a compat switch for it, but just to announce the breaking change. We would have a switch to turn the old behavior back on, but you would be required to turn that on when you update (so as to not cause a big disruption for people using ids in their current javascript/css).

Any obscure transformation we can avoid is a good thing, but we need to preserve this behavior to not disrupt existing apps.

@rynowak Are you ok if we update here and provide a switch to go back to the old behavior? I think this leaves us in a better position moving forward.

**Comment by dougbu** [comment]
@javiercn 
> we would have a switch to turn the old behavior back on

That sounds like a compat switch because I'm not sure why we'd preserve it going forward.

I suspect we also need to change Microsoft.jQuery.Unobtrusive.Validation to support _not_ doing the same transformations we've been doing forever. The hardest part will likely be linking that JavaScript switch to the compat switch. In any case, the JavaScript switch needs to preserve the existing behaviour by default because users may update the package before they update anything from this repo.

**Comment by javiercn** [comment]
@dougbu We would like to support older browsers where we can and give people some room to update. You are right in that we would have to update the jquery bits.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
