### ISSUE TITLE
CompareAttribute not working properly with bound properties on the Razor Page's PageModel

### ISSUE THREAD

**Issue by RKDMax** [dotnet/aspnetcore#4895]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

See [This Repo](https://github.com/RKDMax/ReproduceCompareAttributeBug) to reproduce

#### Description of the problem:
When using a compare attribute on bound properties in the PageModel itself, the otherProperty parameter is not getting honoured and results in a "Could not find a property named &lt;otherProperty&gt;".

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.App 2.1.0

**Comment by poke** [comment]
I’m hitting this problem now too, with properties in my PageModel that are bound directly using `[BindProperty]`.

I do not like the workaround of having to create a sub-model for the form since this means that the form field names are unnecessarily nested. An easier workaround would be to simply implement the comparison check in code then since that means that you wouldn’t have to update your model.

I do consider this a bug since all validation attributes do work except for `[Compare]`. Combined with the error which isn’t clear on this restriction at all, this makes this also very difficult to discover. I would assume that most people would just expect this to work out of the box.

**Comment by CaCTuCaTu4ECKuu** [comment]
Microsoft.AspNetCore.App 2.2.0
Bug is presented

**Comment by steveofficer** [comment]
I have also just encountered this problem. To me the workaround kind of defeats one the purposes of having the PageModel i.e It is the page's model. I should not need a PageModel-model.
Additionally, the other validators work it is surprising to suddenly discover that `Compare` did not.

**Comment by johannsig** [comment]
In ASP.Net Core 2.2:

```
    public class RegisterModel : PageModel
	{
		public RegisterModel(UserManager<VocalsUser> userManager, ICaptchaService captchaService, IEmailSender emailSender)
		{
			UserManager = userManager;
			CaptchaService = captchaService;
			EmailSender = emailSender;
		}

		[Required]
		[BindProperty]
		[DataType(DataType.Text)]
		public string UserName { get; set; }

		[Required]
		[BindProperty]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }

		[Required]
		[BindProperty]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[Required]
		[BindProperty]
		[DataType(DataType.Password)]
		[Compare(nameof(Password))]
		public string PasswordRepeated { get; set; }
```

CompareAttribute works nicely in view (i.e. with unobtrusive validation) but causes invalid ModelState to occur in the OnPost method. This needs to be fixed.

**Comment by briman0094** [comment]
I'd have to agree with @JohannSig. I shouldn't need another model class inside my PageModel simply to use the `[Compare]` attribute functionality. One of the benefits of Razor Pages is combining the model and the controller for simple pages to reduce code size, but if I have to create another model for my PageModel to use, it negates this benefit and makes me wondering if I should just go back to MVC.

**Comment by cmoya212** [comment]
Just started out with Core and encountered this inexplicably dumb oversight. It makes absolutely no sense to respect some validation attributes and not others- especially IValidateableObject. In addition, I agree with others that the nested class solution is bonkers and defeats the purpose of PageModel.

**Comment by egbertn** [comment]
Totally agree! On .NET Core MVC it works, but not on Pagemodel! I had to change the code and implement IValidatableObject and validate it explicitly. Clumsy code :(

**Comment by cmoya212** [comment]
I think it would go a long way for the New Page template to automatically create the “InputModel” nested class inside of PageModel. You can always delete it if your page has no postbacks. Otherwise, this is highly unintuitive.

**Comment by Haukinger** [comment]
Unsure what being closed means here - will this ever be fixed?

**Comment by mkArtakMSFT** [comment]
Reopening as it seems there is enough involvement here to reconsider this.

**Comment by freeflying1222** [comment]
hope the issue be resolved as soon as possible!

**Comment by edgaras-civinskas** [comment]
Having same problem, shame it's not in 3.1.0-preview1.

**Comment by ctolkien** [comment]
Was just bitten by this, adding my +1

**Comment by jomeno** [comment]
@ctolkien Me too :(

**Comment by jfaquinojr** [comment]
Happy Holidays! #metoo

**Comment by lmalsch** [comment]
#metoo

**Comment by pranavkm** [comment]
Hi folks, we realize a lot of you are running in to this. Unfortunately the earliest we can do anything about this would be in the 5.0 milestone. In the meanwhile, a workaround is to use a wrapper type that contains properties with `[CompareAttribute]`.

**Comment by tjbarnes23** [comment]
Also ran into this and lost a few hours. Anyone implementing Password and Confirm Password fields without a nested input model class will likely run into it. Until it's fixed, I'd suggest adding comments in the empty razor pages project that explain the need for the nested input model. I removed the nested class thinking it was overkill. Thanks.

**Comment by redit0** [comment]
This is really frustrating, because it means it's impossible to use both the Compare attribute and a remote validation attribute together, since Compare ONLY works with a nested property, and for remove validation you need to include the __RequestVerificationToken, and that ONLY works when you DON'T use a nested property.  So for example on the default identity UI page for changing the email address, if you want to add a remote validation to use unobtrusive validation for making sure the email address is unique, you have to either remove the compare validation message on the post function, or disable the anti forgery token validation, which can't just be done for the remote validation post method, it has to be disabled for the entire page model.

**Comment by pranavkm** [comment]
For 5.0-preview7, we've addressed the issue described in the title. `CompareAttribute` applied to `PageModel` properties (as well as properties on `Controller`) should now work correctly. 

What remains unchanged is adding support for validation on the page model itself. MVC will not invoke the validation on PageModel if it implements `IValidatableObject`  or has custom validation attributes. This is in line with how validation works in the rest of the framework, only things that are bound are validated. Since a `PageModel` isn't a bound type, it does not get validated. If you feel this is important, please file a separate issue and we will consider it during triage.
