### ISSUE TITLE
Installation of ASP.NET Core Runtime 6.0.9 Hosting bundle fails when the system is already installed with 6.0.14

### ISSUE THREAD

**Issue by prasadmamidi7** [dotnet/aspnetcore#49116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As part of installation of our asp.net core application we are trying to install the asp.net core runtime 6.0.9 on a system which eventually fails installation with error "0x80070666 - Another version of this product is already installed , Installation of this version can not continue. To configure or remove the existing version of this product. use add and remove programs from control panel.

Up on investigation it was found that version 6.0.14 is causing this and also note the system has other versions already installed like 2.1.30,3.1.32,5.0.17,6.0.13,6.0.15,7.0.4. And if we un-install 6.0.14 our installation works.

the system where we install our software we do not have control and no knowledge what all software versions are installed.

Also note if the system is having 6.0.9  and if we try to install 6.0.14, it is silently uninstalling 6.0.9. which is strange and unintended behavior

### Expected Behavior

Installation of a version should not be blocked by another version , as it defeats the purpose of multiple side-by-side versions on the system.

Is this a know issue ? And any workaround to solve this problem is much appreciated (e.g. some flag during installation)

### Steps To Reproduce

Pre- Condition : 

- System is already  installed with ASP.NET Core Runtime 6.0.14 Hosting bundle

Steps

-  Try to install ASP.NET Core Runtime 6.0.9 Hosting bundle

### .NET Version

6.0.9

**Comment by davidfowl** [comment]
Is there any reason you need side by side patch versions?

**Comment by prasadmamidi7** [comment]
we have developed an asp.net core application with framework dependent model. And this application gets installed on the machines which we do not have any control and as part of our application installation we do install the dotnet 6.0.9 Hosting Bundle. 
Coming to side by side we need because of below reasons
-  We can not assume about existing versions of runtime on the machine
-  We can not uninstall any later versions and install the required version as we do not know which applications are using later versions
-  We can not simply skip required runtime version if we see later version as our application is tested and validated with particular version.

**Comment by wtgodbe** [comment]
This issue has 2 questions - the first is about why you get a downgrade failure when installing 6.0.9 while 6.0.14 is present on the machine - this is because up until 6.0.15, we would exit the installer with an error when the user tried to install a downgrade. This was fixed to exit with success & no-op in 6.0.15: https://github.com/dotnet/aspnetcore/pull/46844. So it's expected you'll have to manually uninstall any versions before 6.0.15 if you don't want to see this behavior on downgrade.

As for needing side-by-side, we currently do not support side-by-side installs within a specific Major version, as @davidfowl mentioned. You should not be depending on a specific patch of a Major version, as each patch only contains bug fixes, but not any API surface area changes. Your app should simply use `net6.0`, which means it will use the latest installed 6.0 patch on the machine.
