### ISSUE TITLE
WASM Cors fails despite allowing everything

### ISSUE THREAD

**Issue by wrharper-AASP** [dotnet/aspnetcore#49146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/issues/49094 This is not resolved, MSFTBot is closing things on the weekends.

**Comment by Markz878** [comment]
The issue was closed because what you are asking for is impossible. CORS is a browser standard that can't be bypassed. The reason why this works on a desktop application is because a desktop application doesn't have CORS enforcement like browsers. 

This github repo isn't meant for learning basics of the web, so please, stop harassing aspnetcore team, they have enough on their plate for .net 8 already. You should ask these kind of things on Stackoverflow.

**Comment by gfoidl** [comment]
As said by @Markz878 here and in https://github.com/dotnet/aspnetcore/issues/49094#issuecomment-1614185864 I'm closing this issue (side note: if the other issue is / was still actionable it would have been re-opened). Thanks.

**Comment by wrharper-AASP** [comment]
> The issue was closed because what you are asking for is impossible. CORS is a browser standard that can't be bypassed. The reason why this works on a desktop application is because a desktop application doesn't have CORS enforcement like browsers.
> 
> This github repo isn't meant for learning basics of the web, so please, stop harassing aspnetcore team, they have enough on their plate for .net 8 already. You should ask these kind of things on Stackoverflow.

stackexchange cannot fix a MSFT problem. The whole point is it isn't possible, and it should be. You are going about this in completely the wrong direction. Who owns the KeyVault? who owns ASP.Net? instead of dead ends, people need actual fixes and solutions. not a kickback saying no. The 2nd part of this is a cop out answer.

**Comment by Markz878** [comment]
I see, but you are talking to the wrong team, the CORS request belongs to Azure side. Allowing CORS has been suggested at least a few times to Key Vault team, but they seem to have declined it every time, see for example https://feedback.azure.com/d365community/idea/89085b38-f624-ec11-b6e6-000d3a4f0da0.
