### ISSUE TITLE
Winform & Blazor can't show image in local

### ISSUE THREAD

**Issue by bingoabs** [dotnet/aspnetcore#49202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .Net 7.0, Winform with Blazor, I can't show the local images.

I can save image into the `Environment.GetFolderPath(Environment.SpecialFolder.MyPictures)` folder, and get the paths, but when I render the paths like below, it can't work, only show `alt` text.

```c#
<div class="row">
    @foreach (var path in image_paths)
    {
        <div class="col-md-3">
            <img src="@path" class="img-fluid" alt="Responsive image">
        </div>
    }
</div>
```

### Expected Behavior

Does it the expected behaviour?

### Exceptions (if any)

It does not have any exception, just can't show the image successfully.

### .NET Version

7.0.304

### Anything else?

Using Visual Studio 2022

**Comment by surayya-MS** [comment]
@Eilon could you please look into this?

**Comment by Eilon** [comment]
Hi, this appears to be a limitation of the WebView2 control that is used by BlazorWebView. I tried to make it "just work" with `file://` URLs but couldn't get it to do so. After some research I found a fairly easy way to get it to work.

The WebView2 control has a feature to map a virtual hostname, such as `LocalImages`, to an arbitrary path, such as the local images folder on the computer. After performing the mapping you can reference content there using `http://LocalImages/some_image.jpg`.

Here's how to set it up in the program's startup code:

```c#
            _blazorWebView = new BlazorWebView()
            {
                // ... whatever settings you have...
            };
            // More _blazorWebView setup stuff for your app ...

            // For this issue, hook up the BlazorWebViewInitialized event
            _blazorWebView.BlazorWebViewInitialized += OnBlazorWebViewInitialized;

            Controls.Add(_blazorWebView);
```

And for the `BlazorWebViewInitialized` event handler you can set up virtual hostname mappings like this (set up as many as you want, to whatever locations you want):

```c#
        private void OnBlazorWebViewInitialized(object? sender, BlazorWebViewInitializedEventArgs e)
        {
            e.WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("LocalImages", Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures)), CoreWebView2HostResourceAccessKind.Allow);
        }
```

And finally, in the Razor code, I created the `image_paths` field like this:

```razor
@code
{
    string[] image_paths;

    protected override void OnInitialized()
    {
        image_paths = new[]
        {
            "http://LocalImages/nespresso-machine-1.jpg",
        };
    }
}
```

And when I run the app I can see my old coffee machine that I sold a couple years ago:

<img width="152" alt="image" src="https://github.com/dotnet/aspnetcore/assets/202643/94cc9822-5da5-4de3-a931-5c4cbf4c3626">

Given that I think this solves the problem, and it seems to be due to how WebView2 works, I'm closing this issue as I don't believe there is any further action required.

**Comment by bingoabs** [comment]
@Eilon Great! It is much better than mine, that I convert the image to base64 data, and embed it in image tag. Thanks very much.
