### ISSUE TITLE
[Blazor] Enhanced form navigation does not seem to handle collections correctly.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#49207]
* Checkout `javiercn/sample-editor-implementation`.
* Build the repo
* Run BlazorUnitedApp in samples.
* Navigate to `/Products-Binding-Context`

https://github.com/dotnet/aspnetcore/assets/6995051/13155355-2974-44f4-b026-c4c77812c973

* The elements are not correctly removed from the list, when the UI is updated.
* If enhanced navigation is disabled by commenting out the script, the app works as expected.

**Comment by SteveSandersonMS** [comment]
Looks like this is because the page is producing invalid markup:

![image](https://github.com/dotnet/aspnetcore/assets/1101362/67fdddce-ac62-4859-a91c-a0b575a8c8e4)

The interactive renderer would also fail in the same way if it was given an invalid attribute name, so it's probably correct for the enhanced navigation system to let this fail too.

**Comment by javiercn** [comment]
@SteveSandersonMS I've put a fix as part of https://github.com/dotnet/aspnetcore/pull/49224 to produce correct markup.

Is there a way to provide a better error in this case? I suspect this is not going to be the only instance where this can happen, for example, it could happen if for some reason the event handlers are not discovered for a razor file.
