### ISSUE TITLE
WebApi template remove UseMinimalAPIs option

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#49217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The UseMinimalAPI option is duplicated with the Api template

### Describe the solution you'd like

remove UseMinimalAPIs option

**Comment by mitchdenny** [comment]
What version of .NET are you using? Do you have a screenshot showing the issue?

**Comment by mitchdenny** [comment]
Ah I see what you mean. Note that the _ASP.NET Core API_ template is subtly different again from deselecting controllers in _ASP.NET Core Web API_ in that the former uses `WebApplication.CreateSlimBuilder(...)` which has a number of services/middleware absent by default (its more optimized for the AOT scenario).

Stepping back a bit though I can see that this is confusing and its feedback that we've recently received from others:

[#template](https://github.com/dotnet/aspnetcore/issues/49047)

Tagging @JeremyLikness and @DamianEdwards

**Comment by DamianEdwards** [comment]
Yeah we're in another situation where history and our current/future goals are creating tension (similar thing happened when we introduced Razor Pages). As @mitchdenny points out, the new "API" template is different in a few ways that aren't easy to compose with the existing "Web API" template, hence the new standalone template. Removing a parameter from an existing template is pretty impactful though.

That said, I'm open to doing something like the following, which would help address #49047 too:

- Hiding the option on the webapi template to use minimal APIs **in Visual Studio** (it would still be available at the command line via `dotnet new webapi` to avoid breaking any scripts or ppl used to creating minimal APIs this way where they aren't first presented with a list of templates to choose from)
- Rename the title of the webapi template to "ASP.NET Core Web API (Controllers)"
- Update the description of the api template to make clear it's intended for building RESTful HTTP services using minimal APIs (without saying "minimal APIs")
- Revisit this early in .NET 9 to consider dropping the minimal option from the webapi template completely

**Comment by mitchdenny** [comment]
I min did like the ASP.NET Core API option.

**Comment by DamianEdwards** [comment]
Thinking about this more overnight, merging the templates is more complicated due to the many other options supported by the webapi template that aren't compatible/supported with native AOT, e.g. OpenAPI, authentication, etc. The templating system doesn't yet support conditional parameters so there isn't currently a way to create a good VS experience for a template with mutually exclusive options.

For this reason, I'm inclined to revisit my [original proposal](https://github.com/dotnet/aspnetcore/issues/49217#issuecomment-1625672547) with some tweaks:

- Update the existing webapi template to be for creating controller-based APIs
- Rename the existing webapi template to "ASP.NET Core HTTP Service (Controllers)" (or a derivative of one of the other names from [above](https://github.com/dotnet/aspnetcore/issues/49217#issuecomment-1631424036))
- Hiding the option on the webapi template to use minimal APIs in Visual Studio (it would still be available at the command line via dotnet new webapi to avoid breaking any scripts or ppl used to creating minimal APIs this way where they aren't first presented with a list of templates to choose from)
- Rename the api template to "ASP.NET Core HTTP Service" (or a derivative of one of the other names from [above](https://github.com/dotnet/aspnetcore/issues/49217#issuecomment-1631424036))
- Update the description of the api template to make clear it's intended for building RESTful HTTP services using minimal APIs (without saying "minimal APIs") and that is has optional native AOT support
- Revisit this early in .NET 9 to consider dropping the minimal option from the webapi template completely

**Comment by DamianEdwards** [comment]
@Varorbc Visual Studio doesn't support conditional parameters AFAIK @phenning

**Comment by phenning** [comment]
Correct. Visual Studio does not support conditional parameters at this time it has not been prioritized and is non-trivial due to the way the template engine templates are integrated into the new project dialog.

**Comment by JeremyLikness** [comment]
I like this proposal and just have a few thoughts.

- Makes 100% sense to me to update the existing webapi template to be controllers-focused
- I like having controllers in the name. That's what it will use and that's how we talk about differences in how people build APIs with .NET. My only worry is people new to more recent versions may gravitate to this option because of its familiarity. I think the name as is works, with a caveat in a second...
- Hiding that option makes sense
- the caveat: I agree the new API name should not have "minimal API" but this is the template people starting should go with. Is there some phrase we can use to imply this is the way to go? Have we had "old vs new" templates in the past and come up with some way to highlight the difference, or is more of a "make sure it's earlier in the list" solution?
- Perhaps the description is where this is best addressed. "Build modern REST-based APIs on .NET using a simple, fluent API" ... just brainstorming here.

**Comment by bradygaster** [comment]
Pretty much agree with everything @JeremyLikness said. I'm not sure I'm a fan of the very-long name @DamianEdwards proposed "ASP.NET Core HTTP Services (Controllers)" seems long, but I'm already in a naming bikeshedding exercise and 2 is 2 much. :) I don't mind the inclusion of "API" in the name, but I do like "HTTP Service" a lot.

**Comment by DamianEdwards** [comment]
> Is there some phrase we can use to imply this is the way to go? Have we had "old vs new" templates in the past and come up with some way to highlight the difference, or is more of a "make sure it's earlier in the list" solution?

We had a very similar situation when we introduced Razor Pages in 2.x and for that we updated the existing "ASP.NET Core Web Application" template to use Razor Pages, and added a new "ASP.NET Core Web Application (Model-View-Controller)" template for the same content but using controllers and views. That remains to this day.

**Comment by DamianEdwards** [comment]
New proposal based on some more thinking and discussion:

- Update the Web API template to default to minimal APIs, i.e. `dotnet new webapi` will result in an app using minimal APIs
- Change the API template to be just for native AOT, e.g. `dotnet new webapiaot`

The reasoning for this is that the native AOT option is mutually exclusive with the other options in the Web API template, which currently makes it impractical to have them be in a single template. This new proposal delivers on the following goals:

- Make the API template users will most likely select when building an API default to using minimal
- Make it clear that a native AOT API does not support controllers, authentication, or OpenAPI in .NET 8

**Comment by DamianEdwards** [comment]
@Varorbc it's the model we wish to promote by default. Controllers is still selectable as an option.
