### ISSUE TITLE
Add warning that customizing data protection is non-trivial

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#49309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

See [this](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1843386) internal issue. Customer asserts that customizing data protection is non-trivial and thinks the templates that add auth should warn that customizing data protection is difficult.

### Describe the solution you'd like

When creating an ASP.NET Core web app with auth, warn user that customizing data protection is not easy.

### Additional context

Please close this issue if it's not actionable. I think most customers know that customizing data protection is non-trivial.

**Comment by mitchdenny** [comment]
I'm not sure a floating comment in the OOB templates which warns that data protection is hard would do much to help folks :)

**Comment by amcasey** [comment]
There's lots of room for improvement in the Data Protection docs and we hope to make progress in the 9.0 timeframe.  Since it sounds like the documentation required in this case is support for scaling an app across multiple instances, I'd follow https://github.com/dotnet/aspnetcore/issues/52916, which we hope will yield a new pattern for simplifying such apps.  You might also find this [existing doc](https://learn.microsoft.com/aspnet/core/host-and-deploy/web-farm) helpful.
