### ISSUE TITLE
[API Proposal]: SignOut overloads that take only one authentication scheme

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#49391]
## Background and Motivation

When multiple authentication schemes are registered, if we only want to sign out from a particular one it is necessary to allocate a collection. It is not the most efficient in terms of allocation.

https://github.com/dotnet/aspnetcore/blob/c343768fb12b048fe402999434ebf94bef2444af/src/Http/Http.Results/src/Results.cs#L80
https://github.com/dotnet/aspnetcore/blob/c343768fb12b048fe402999434ebf94bef2444af/src/Http/Http.Results/src/TypedResults.cs#L84
https://github.com/dotnet/aspnetcore/blob/c343768fb12b048fe402999434ebf94bef2444af/src/Mvc/Mvc.Core/src/ControllerBase.cs#L2459

## Proposed API

Add overloads that take a single authentication scheme.

```diff
namespace Microsoft.AspNetCore.Http;

public static partial class Results
{
+    public static IResult SignOut(AuthenticationProperties? properties = null, string? authenticationScheme = null)
}

public static partial class TypedResults
{
+    public static SignOutHttpResult SignOut(AuthenticationProperties? properties = null, string? authenticationScheme = null)
}
```

```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract partial class ControllerBase
{
+    public virtual SignOutResult SignOut(string authenticationScheme)
}
```

## Usage Examples

```csharp
app.MapGet("/signout", () =>
{
    return TypedResults.SignOut(authenticationScheme: "Cookies");
});
```

## Risks

Nothing I can see now

**Comment by Tratcher** [comment]
Another:
https://github.com/dotnet/aspnetcore/blob/c343768fb12b048fe402999434ebf94bef2444af/src/Mvc/Mvc.Core/src/SignOutResult.cs#L41-L42

**Comment by halter73** [comment]
> ```diff
> public static partial class TypedResults
> {
> +    public static SignOutHttpResult SignOut(AuthenticationProperties? properties = null, string? authenticationScheme = null)
> }
> ```

We have to be careful with default values. We do not to make `TypedResults.SignOut()` ambiguous between this and `SignOut(AuthenticationProperties? properties = null, IList<string>? authenticationSchemes = null)`. I would say we could just remove the default values from the existing overload to maintain both source and binary compatibility as recommended in [the rosly docs for adding optional parameters in public API](https://github.com/dotnet/roslyn/blob/91d6bfbcc57f1b355ad0d295d6d4b5b8f85bb1d5/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md#steps-for-adding-optional-parameters-to-an-existing-method), but that doesn't work when the new overload takes a different type `string?` instead of `IList<string>?` in the same position.

We'll probably just have to leave out the default values. Which makes me wonder, if we should add just `TypedResults.SignOut(params string[] authenticationScheme)` similar to [ControllerBase.SignOut()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.signout?view=aspnetcore-7.0)

> ```diff
> namespace Microsoft.AspNetCore.Mvc;
> 
> public abstract partial class ControllerBase
> {
> +    public virtual SignOutResult SignOut(string authenticationScheme)
> }
> ```

What's the motivation for this considering the `params` overload exists? Just to save an array allocation?

**Comment by joegoldman2** [comment]
> What's the motivation for this considering the `params` overload exists? Just to save an array allocation?

Yes, I think the main motivation is to avoid the array allocation as it's quite common to trigger the signout on a single scheme.

**Comment by halter73** [comment]
API Review Notes:
- We think that the updated code does look nicer than having to allocate an array:
	```csharp
	app.MapGet("/signout", () =>
	{
	    return TypedResults.SignOut(authenticationScheme: "Cookies");
	});
	```
    vs.
    - We think that the updated code does look nicer than having to allocate an array:
	```csharp
	app.MapGet("/signout", () =>
	{
	    return TypedResults.SignOut(authenticationScheme: new[] { "Cookies" });
	});
	```
- The API as proposed is a breaking change as noted in [my earlier comment](https://github.com/dotnet/aspnetcore/issues/49391#issuecomment-1846145149), so we cannot accept it as-is.
- We might consider an API proposal that adds `TypedResults.SignOut(params string[] authenticationScheme)` similar to [ControllerBase.SignOut()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.signout?view=aspnetcore-7.0), but that does not remove the array allocation.
  - However, https://github.com/dotnet/csharplang/issues/7700 may allow us to add non-allocation `params` overloads in the future.

We tried to come up with an API proposal that would be non breaking. Below is as far as we got, but even this would probably break given a call like `TypedResults.SignOut(authenticationScheme: new List<string> { "Cookies" })` as soon as we add a `params string[] authenticationSchemes` overload.

```diff
namespace Microsoft.AspNetCore.Http;

public static partial class Results
{
+    public static IResult SignOut()
-    public static IResult SignOut(AuthenticationProperties? properties = null, IList<string>? authenticationSchemes = null)
+   public static IResult SignOut(AuthenticationProperties? properties, IList<string>? authenticationSchemes = null)
+    public static IResult SignOut(params string[] authenticationSchemes)
}

public static partial class TypedResults
{
+    public static SignOutHttpResult SignOut()
-     public static SignOutHttpResult SignOut(AuthenticationProperties? properties = null, IList<string>? authenticationSchemes = null)
+    public static SignOutHttpResult SignOut(AuthenticationProperties? properties, IList<string>? authenticationSchemes = null)
+    public static SignOutHttpResult SignOut(params string[] authenticationSchemes)
}
```

Because of the difficulty in maintaining backward compatibility, we've decided to reject the API.

**Comment by martincostello** [comment]
I guess C# 12 at least makes it slightly less ugly (and then maybe the compiler can optimise it?):

```csharp
app.MapGet("/signout", () =>
 {
     return TypedResults.SignOut(authenticationScheme: ["Cookies"]);
 });
```

**Comment by halter73** [comment]
I agree it looks a bit better with the C# 12 syntax.

The final iteration at our attempt at a non-breaking change might work if we renamed `params string[] authenticationSchemes` to something like `params string[] authenticationSchemeParams`, and I'm sympathetic to wanting `TypedResults.SignOut("Cookies")` to just work, but I'm not sure it's worth it if we have to add a bunch of new overloads.
