### ISSUE TITLE
AddIdentityBearerToken should not be generic

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#49404]
After playing with the APIs introduced in https://github.com/dotnet/aspnetcore/issues/47228, I realized that making the API generic is pretty pointless. The TUser isn't used to discriminate any options so it seems superfluous.

**Comment by davidfowl** [comment]
I think we should remove it.

**Comment by halter73** [comment]
## Background and Motivation

Remove unnecessary code.

## Proposed API

```diff
// Microsoft.AspNetCore.Identity.dll

namespace Microsoft.AspNetCore.Identity;

- public static class IdentityAuthenticationBuilderExtensions
- {
-     public static AuthenticationBuilder AddIdentityBearerToken<TUser>(this AuthenticationBuilder builder)
-         where TUser : class, new()
-    public static AuthenticationBuilder AddIdentityBearerToken<TUser>(this AuthenticationBuilder builder, Action<BearerTokenOptions> configure)
-        where TUser : class, new()
- }
```

## Usage Examples

No instead of calling `AddIdentityBearerToken` to add bearer token auth for use with AddIdentityCore:

```csharp
// ...
builder.Services.AddAuthentication()
    .AddIdentityBearerToken<ApplicationUser>();
// ... 
```

You'd call the normal `AddBearerToken` method with the correct Identity Constant.

```
builder.Services.AddAuthentication()
    .AddBearerToken(IdentityConstants.BearerScheme)
```

## Alternative Designs

Just remove the generic parameter, but keep `AddIdentityBearerToken`.

## Risks

It's a breaking change, but the workaround is easy and it's in a preview.

**Comment by halter73** [comment]
API Review Notes:

- We are not deleting any public API that shipped in .NET 7. This was only in earlier previews.
- We think `AddIdentityBearerToken` without a generic parameter doesn't add much value when you can just call `.AddBearerToken(IdentityConstants.BearerScheme)`.

API Approved!
