### ISSUE TITLE
Expose AccessTokenResponse from the new BearerToken AuthenticatonHandler

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#49424]
## Background and Motivation

I'm trying to write a custom API that uses the new bearer token handler and I have to duplicate the AccessTokenResponse to use it in my API description. On top of that, leaving it internal also means that I can't add my own copy when I have my custom API *and* I use `MapIdentityApi<T>`, because they conflict.

The other benefit to making this public is that it becomes an easy way for .NET clients to consume the response type.

## Proposed API

```C#
using System.Text.Json.Serialization;
 
namespace Microsoft.AspNetCore.Authentication.BearerToken.DTO;
 
/// <summary>
/// The JSON data transfer object for the bearer token response.
/// </summary>
internal sealed class AccessTokenResponse
{
    /// <summary>
    /// The value is always "Bearer" which indicates this response provides a "Bearer" token
    /// in the form of an opaque <see cref="AccessToken"/>.
    /// </summary>
    /// <remarks>
    /// This is serialized as "token_type": "Bearer" using System.Text.Json.
    /// </remarks>
    [JsonPropertyName("token_type")]
    public string TokenType { get; } = "Bearer";
 
    /// <summary>
    /// The opaque bearer token to send as part of the Authorization request header.
    /// </summary>
    /// <remarks>
    /// This is serialized as "access_token": "{AccessToken}" using System.Text.Json.
    /// </remarks>
    [JsonPropertyName("access_token")]
    public required string AccessToken { get; init; }
 
    /// <summary>
    /// The number of seconds before the <see cref="AccessToken"/> expires.
    /// </summary>
    /// <remarks>
    /// This is serialized as "expires_in": "{ExpiresInSeconds}" using System.Text.Json.
    /// </remarks>
    [JsonPropertyName("expires_in")]
    public required long ExpiresInSeconds { get; init; }
 
    /// <summary>
    /// If set, this provides the ability to get a new access_token after it expires using a refresh endpoint.
    /// </summary>
    /// <remarks>
    /// This is serialized as "refresh_token": "{RefreshToken}" using System.Text.Json.
    /// </remarks>
    [JsonPropertyName("refresh_token")]
    public required string RefreshToken { get; init; }
}
```

## Alternative Designs

Do nothing

## Risks

Low

**Comment by halter73** [comment]
API Review Notes:

- This could be useful for endpoint filters, System.Text.Json customization, and client usage. 
- `AccessTokenResponse` is not returned from `/login` and `/refresh` is not a `Ok<AccessTokenResponse>` but really a `SignInHttpResult` that happens to write an `AccessTokenResponse` if doing bearer auth instead of cookie auth which could be confusing to someone trying to write an endpoint filter.
- If we make `AccessTokenResponse` public, all the DTOs listed in https://github.com/dotnet/aspnetcore/blob/2120c62f6b5c067523bf92f60818dfc7cef36dbf/src/Identity/Core/src/DTO/IdentityEndpointsJsonSerializerContext.cs should also be public.
- Is there any concern that exposing the internal representation will make it harder to change in the future?  Or is it already hard to change?
  - There's some concern that changing C# API might be a little more constraining that changing the HTTP API, but they're mostly the same, and we cannot break the HTTP API already.
- None of the DTOs have custom constructors or setters. They all use `init;` or `required` init.
- Why are none of the `InfoRequest` parameters required?
  - We treat a `/manage/info` POST with an empty JSON body (`{}`) the same as a GET. This is similar to `/manage/2fa` which only has a POST endpoint for security reasons.
- Do we want to make these structs instead of classes?
  -  These endpoints all hit the database in the normal case, so it's not super efficient to begin with.
  - The general guidelines is to default to class unless a struct is critical for performance.
  - The generic endpoint filter contexts avoid boxing in some cases, but in practice these DTOs will probably be boxed a lot anyway.
- If we make this public, would we put most of the DTOs in `Microsoft.AspNetCore.Identity.DTO` but leave the `AccessTokenResponse` in `Microsoft.AspNetCore.Authentication.BearerToken.DTO`?
  - This could hurt discoverability even though it might clarify that the `AccessTokenResponse` is written by the `BearerTokenHandler` and not the `MapIdentityApi` endpoints directly.
- What do we think about including `DTO` in a namespace?
  - We'd like to avoid it, but we don't want to drop all these types directly in `Microsoft.AspNetCore.Identity`
  - `Microsoft.AspNetCore.Identity.Objects`?
  - `Microsoft.AspNetCore.Identity.Data`? Let's do this!
  - Let's move `AccessTokenResponse` directly into `Microsoft.AspNetCore.Authentication.BearerToken`

API Approved! (TODO: Copy/Paste the approved API)

**Comment by halter73** [comment]
We need to update this API based on feedback in #50037 that the `/manage/info` endpoint throws an `ArgumentException` when a user has multiple roles.

## Background and Motivation

`InfoResponse.Claims` should support multiple values per claim type since this is commonly used. Roles are one extremely common use case where multiple claims will have the same `ClaimsIdentity.RoleClaimType`, but multiple claims with the same type

## Proposed API

```diff
// Microsoft.AspNetCore.Identity.dll
namespace Microsoft.AspNetCore.Identity.Data;

public sealed class InfoResponse
{
    public required string Email { get; init; }
    public required bool IsEmailConfirmed { get; init; }
-    public required IDictionary<string, string> Claims { get; init; }
+    public required IDictionary<string, string[]> Claims { get; init; }
}
```

#50953 targets release/8.0 and implements this updated API.

## Usage Examples

```csharp
    private static async Task<InfoResponse> CreateInfoResponseAsync<TUser>(TUser user, ClaimsPrincipal claimsPrincipal, UserManager<TUser> userManager)
        where TUser : class
    {
        return new()
        {
            Email = await userManager.GetEmailAsync(user) ?? throw new NotSupportedException("Users must have an email."),
            IsEmailConfirmed = await userManager.IsEmailConfirmedAsync(user),
            Claims = AggregateDictionary(claimsPrincipal.Claims.Select(claim => (claim.Type, claim.Value))),
        };
    }

    private static Dictionary<TKey, TValue[]> AggregateDictionary<TKey, TValue>(IEnumerable<(TKey, TValue)> pairs) where TKey : notnull
    {
        var dictionary = new Dictionary<TKey, TValue[]>(1);
        foreach (var (key, value) in pairs)
        {
            TValue[] newDescriptions;

            if (dictionary.TryGetValue(key, out var descriptions))
            {
                newDescriptions = new TValue[descriptions.Length + 1];
                Array.Copy(descriptions, newDescriptions, descriptions.Length);
                newDescriptions[descriptions.Length] = value;
            }
            else
            {
                newDescriptions = [value];
            }

            dictionary[key] = newDescriptions;
        }

        return dictionary;
    }
```

## Alternative Designs

We could also make the `Claims` an array rather than a dictionary/object which would be more similar to `ClaimsPrincipal.Claims`.

```diff
// Microsoft.AspNetCore.Identity.dll
namespace Microsoft.AspNetCore.Identity.Data;

public sealed class InfoResponse
{
    public required string Email { get; init; }
    public required bool IsEmailConfirmed { get; init; }
-    public required IDictionary<string, string> Claims { get; init; }
+    public required ClaimInfo[] Claims { get; init; }
}

+ public sealed class ClaimInfo
+ {
+    public required string Type { get; init; }
+    public required string Value { get; init; }
+ }
```

Or we could continue to use a dictionary, but use the concrete `Dictionary<string, string[]>` type instead of `IDictionary<string, string[]>` interface the implementation is probably always going to be a normal `Dictionary` going forward.

## Risks

The biggest risk is doing nothing and leaving the `/manage/info` completely broken for any user with multiple roles.

**Comment by halter73** [comment]
I'm closing this so we can track the API change in #50037 which is the issue where the bug was initially reported and which properly tracks the GA milestone.
