### ISSUE TITLE
Blazor Server with Microsoft Identity and Azure SignalR Using Multiple Hubs

### ISSUE THREAD

**Issue by dboyder222** [dotnet/aspnetcore#49425]
I hade contact with Cristos Matkas from Microsoft regarding this problem, this is what he said
It turns out that there is a known issue breaking SignalR Hubs with Blazor Server and Microsoft Identity. The main issue is that you have 2 SignalR connections and this doesn't work well at the moment. 

My recommendation (and that of the SignalR team) would be to split out the SignalR Hub on a separate API. That way, you'll have separation of concerns and will allow youto do proper authentication and authorization on both ends. This will also unblock you from the current issue you're facing.

_Originally posted by @csandoy in https://github.com/dotnet/aspnetcore/issues/34419#issuecomment-887263877_

**Comment by dboyder222** [comment]
Has there been any update on this? I'm building a Blazor application that uses a SignalR hub to update other user's screens when new data has been provided. I used the work around in this thread to get it working with SignalR, but when I go to use AzureSignalR I get a failure because context.HttpContext has a null value. We have the need to use Azure SignalR because we want to be able to scale out our Azure App Service if/when needed.

**Comment by davidfowl** [comment]
I don't understand this recommendation. From reading the linked issue, there's a general blazor server problem with auth because of the design of blazor server:

![image](https://github.com/dotnet/aspnetcore/assets/95136/533e283a-78c9-4428-9610-3f1b4326c93a)

The authentication information needs to flow from the client to the blazor server circuit, to *any* client API that gets used within a blazor circuit. 

That means if you try to connect to a hub from the server side, the auth headers or cookies need to flow from the client to the hub call. Same as if you wanted to call an API from a blazor server component. 

I'm not sure what :

> My recommendation (and that of the SignalR team) would be to split out the SignalR Hub on a separate API. That way, you'll have separation of concerns and will allow youto do proper authentication and authorization on both ends. This will also unblock you from the current issue you're facing.

I'm not sure what this means in the context of this issue. Can you clarify.

**Comment by dboyder222** [comment]
Hey David, 

I ended up finding this workaround that appears to be working with AzureSignalR()

[https://learn.microsoft.com/en-us/answers/questions/1160923/solution-custom-signalr-endpoints-(hubs)-in-a-blaz?cid=kerryherger](url)
