### ISSUE TITLE
Blazor 8: Blazor Web App router does not seem to see pages in an RCL

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#49432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to reference pages (@page directive) in an RCL from a Blazor Web App (new with Blazor .NET 8). The router does not seem to see the pages in the RCL? We have tried adding Additional Assemblies but with no luck. Wondering if we are missing something?

### Expected Behavior

We should be able to reference and run pages from and RCL. Is this maybe not ready yet?

### Steps To Reproduce

We have attached sample code.

### Exceptions (if any)

Error: 404

### .NET Version

.NET 8 Preview 6

### Anything else?

[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/12061218/BlazorApp1.zip)

**Comment by marinasundstrom** [comment]
If think this was mentioned in the blog post for Preview 6. Page components defined in an RCL can't be mapped to routes. The pages have to live in the main webapp project. So not even with AddionalAssemblies (as you would otherwise expect)

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-6/ 

> Note that there’s currently a [limitation](https://github.com/dotnet/aspnetcore/issues/49313) where components with routes must be defined in the same assembly as the App component passed to MapRazorComponents<App>(), so they cannot currently be defined in the client assembly. This will be addressed in a future update.

It is being tracked here: https://github.com/dotnet/aspnetcore/issues/49313

This will hopefully be fixed in the next preview when the Web Assembly bits are more complete. They did not have the time to finish that for this preview.

**Comment by chassq** [comment]
Thank you!
