### ISSUE TITLE
My Source Code Are Not Private In Webassembly Blazor

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#49726]
When I Maked App With Blazor And Run It Found That Source Code Can Be Deassebled
And When All Code Has To Be A Secret

The Webassembly Should Do Some Security Cause When Having Big App
And You Don't Want Anyone To See Source Code
This Comes

This In Visual Studio On Developer Computer
![Screenshot 2023-07-29 181138](https://github.com/dotnet/aspnetcore/assets/104096256/a89cf8a7-b3b2-43b2-99f3-1b77bccf471a)

And This In Hacker Window
![Screenshot 2023-07-29 181130](https://github.com/dotnet/aspnetcore/assets/104096256/1b366c01-0b5d-437f-99ab-5aeab2d5bf80)
![Screenshot 2023-07-29 181417](https://github.com/dotnet/aspnetcore/assets/104096256/e58b8ead-0edc-47b2-b548-41f158f2dd3c)

Are There Way To Make My Code Secure To Make Nobody To Get Source Code
Cause Someone Can Make Anathor App With Same Things I Have

**Comment by david-acker** [comment]
[It's recommend to place sensitive or business-related code behind APIs on the server, so the application can use the functionality without providing the client with the actual code.](https://github.com/dotnet/aspnetcore/issues/37799#issuecomment-950306882)

You could also use an existing .NET obfuscator tool if you were inclined, since Blazor apps use normal .NET DLLs, although someone could still de-obfuscate the code to gain access, if they were determined enough.
