### ISSUE TITLE
Two forms on same page results in null ref

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49821]
We did work in .NET 8 Preview 7 to try to [make it possible to use the `[SupplyParameterFromForm]` parameter as both the form model binding parameter and the form model](https://github.com/dotnet/aspnetcore/pull/49489). But when I try to set up two forms on the same page with two separate `[SupplyParameterFromForm]` parameters, I end up with null for one of them which causes a null ref when rendering the form.

Repro steps:
- Install .NET 8 Preview 7
- Create a new Blazor Web App
- Add the following two forms to Index.razor

```razor
<form method="post" @formname="contact" @onsubmit="AddContact">
    <div class="mb-3">
        <label class="form-label" for="name">Name</label>
        <InputText class="form-control" id="name" @bind-Value="NewContact.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label" for="email">Email</label>
        <InputText class="form-control" id="email" @bind-Value="NewContact.Email" />
    </div>
    <div class="form-check">
        <InputCheckbox class="form-check-input" id="send-me-deals" @bind-Value="NewContact.SendMeDeals" />
        <label class="form-check-label" for="send-me-deals">Send me deals</label>
    </div>
    <button class="btn btn-primary">Submit</button>
    <AntiforgeryToken />
</form>

<form method="post" @formname="contact2" @onsubmit="AddContact">
    <div class="mb-3">
        <label class="form-label" for="name">Name</label>
        <InputText class="form-control" id="name" @bind-Value="AnotherContact.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label" for="email">Email</label>
        <InputText class="form-control" id="email" @bind-Value="AnotherContact.Email" />
    </div>
    <div class="form-check">
        <InputCheckbox class="form-check-input" id="send-me-deals" @bind-Value="AnotherContact.SendMeDeals" />
        <label class="form-check-label" for="send-me-deals">Send me deals</label>
    </div>
    <button class="btn btn-primary">Submit</button>
    <AntiforgeryToken />
</form>

<ul>
    @foreach (var contact in contacts)
    {
        <li>@contact.Name @contact.Email @contact.SendMeDeals</li>
    }
</ul>

@code {
    static List<Contact> contacts = new();

    [SupplyParameterFromForm]
    public Contact NewContact { get; set; } = new();

    [SupplyParameterFromForm]
    public Contact AnotherContact { get; set; } = new();

    public class Contact
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public bool SendMeDeals { get; set; }
    }

    private async Task AddContact()
    {
        // Add contact...
        contacts.Add(NewContact);
        NewContact = new();
    }
}
```

- Run the app and try to submit the first form

You end up with a null ref when rendering the 2nd form because `AnotherContact` was set to null. I'm opening this issue to discuss if this is a scenario we should support.

**Comment by mkArtakMSFT** [comment]
Looks like this is due to the fact that `SupplyParameterFromForm` overrides the default value even if there is nothing (null) to set.

**Comment by SteveSandersonMS** [comment]
@javiercn Can you give an opinion on what's to be done here? I wonder if this will end up forcing us to change some API shape. 

Currently, `HttpContextFormValueMapper`'s `CanMap` returns a true/false value based only on the form name, scope name, and result type. It doesn't care whether there actually is a corresponding value in `Request.Form`. So it will return `true` for `CanMap` in both the above cases.

Then, `SupplyParameterFromFormValueProvider` will call `GetCurrentValue` and assign that to the result. If it receives the value `null`, it has no way to know that's meant to be ignored. There isn't any way of knowing that the form didn't actually contain a value at all, so we can't avoid overwriting the old property value.

Possible solutions:

 * Maybe if `GetCurrentValue` returns `null` that *always* means "I didn't have a value so leave the old one in place". Are there any cases where a mapped value can be supplied and is `null`?
 * Or should `GetCurrentValue` become `TryGetCurrentValue` so we know whether or not there is a result?
 * Or is your view that @danroth27's pattern above is invalid and cannot be expected to leave the old object in place?

**Comment by javiercn** [comment]
@SteveSandersonMS we have a couple of options here.

One choice is to say that the parameter should be initialized within `OnInitialized`, so changing the code for something like:
```csharp
public void OnInitialized()
{
    NewContact ??= new();
    AnotherContact ??= new();
}
```
The new syntax on the property is setting a "fallback" value before the parameters get bound, so then when binding happens it gets overridden, as opposed to the pattern above that sets the fallback/default after it has bound in all cases. We can choose to leave it as is and explain to people what is happening.

I realize that this is something that people will likely do in their code, as it's less verbose than the option above, and will only fail at the time we bind, not on first render, so another choice is to update the binding logic to account for whether a value was found or not through binding, and only override the value in that case.

What I don't like about that approach is that it will work in the case where the value is not found but will cause a failure in the case that we set the value to null when we fail to bind the top-level object, which might surprise people, and you end up with a null object instead of the default that you would have had otherwise. This can happen for example if your object has a constructor with parameters and throws when one of the required values is not present.

This option will make this scenario work with the mentioned cave heats, ultimately the correct way to do this is at the `OnInitialized`, but its a trade-off.

Another option would be introducing a feature where we initialize `[SupplyParameterFromForm]` by calling a parameterless constructor on them, but I don't think that solves anything, as that would have worked in the previous case and wouldn't work for types with constructor parameters.

Yet another option would be to capture the value from the property we are binding and preserving it in case we aren't able to bind a value for it. It might mean that the binding logic only provides a value when binding is at least minimally successful, and no-ops otherwise.

The challenge here is that it might cause the app to make decisions based on the default value instead of the bound value. For example, if they do work inside OnInvalidSubmit, they might be looking at the default value as opposed to the actual bound value.

Another aspect of it is consistency, if there is a parameter and a component higher up provides a value for it, that default set in the constructor would be overriden, so in this case, we could say that `SupplyFromFormParameter` always provide a value and you should only set defaults after parameters have been set.

What I am trying to get to this is:
* The correct way is to do this within OnInitialized to make sure you always end up with what you expect.
* I am ok if we decide to NOOP when the parameter is not part of the body, but we continue to set the value (whatever that value is) when that's not the case (for example, null if there are binding errors and we can't construct an instance).
* I think that in most cases people will still have to go through OnInitialized, as the typical pattern is more likely something like:
  ```
  Customer ??= await GoToDb(id);
  ```

So, the question here becomes, do we want to teach people the `OnInitialized` approach, or do we want to make the `= new()` approach work.

IMO, the pattern is convenient (and something that people is used to doing) even if it only works for a subset of cases (no async), but it can also be a pit of failure in more complex cases.

The other question is whether we could do nothing now and change this in the future, for which I think the answer is yes?

Any thoughts?

**Comment by javiercn** [comment]
@SteveSandersonMS cool, let's go with that then, as I agree is the most correct choice.
