### ISSUE TITLE
Blazor Web App is missing an error page

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49853]
When deployed to production a Blazor Web App will redirect server errors using `app.UseExceptionHandler("/Error");`. But there is nothing listening at /Error so you end up with a 404. Typically the error page is handled by a Razor Page, but in a Blazor Web App it should be a Blazor component page.

**Comment by danroth27** [comment]
A few things to note about the existing Razor Pages based error page:

- It uses `HttpContext` to get the trace identifier. With Blazor you currently need to set up and use `IHttpContextAccessor` to get this. See #48769.
- It uses the `[ResponseCache]` attribute to disable response caching, presumably so you get the right request ID. See #49130.
- It disables antiforgery

**Comment by SteveSandersonMS** [comment]
Making this work end-to-end will be nontrivial. I've filed an issue with details at https://github.com/dotnet/aspnetcore/issues/50287. We might decide it's unwise to rush that for .NET 8.

In the meantime, let's use this issue to track what we're doing for the error page in the project template in .NET 8, since that's literally what the issue title is about.

### Options for .NET 8

1. Don't have a custom error page in the project template
    * Why should the *default* project template contain a *custom* error page? "We've always done it this way" doesn't count :)
    * Consider another tech like Next.js 13. Its default projects do *not* include custom error pages. To add one, you would [follow docs](https://nextjs.org/docs/pages/building-your-application/routing/custom-error#500-page), and even then it's limited to a statically (build-time) rendered HTML file. Clearly this is not universal enough that they wanted to put it in the default project.
    * People who want to add one would follow our docs and add a `.cshtml` or `.html` file.
2. We could add `/Pages/Error.cshtml`. Note that it would not use the same layout, nor could it, since the Blazor layout will likely contain scripts for starting a circuit etc. As such it wouldn't accomplish much beyond the default built-in error output.

I'm changing the labels to make this reappear in triage.

**Comment by SteveSandersonMS** [comment]
also cc @danroth27
