### ISSUE TITLE
BUG on API Android API 16

### ISSUE THREAD

**Issue by sadegh-q** [dotnet/aspnetcore#49905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

crash at HubConnection.java:174 of version 7.0.0
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### .NET Version

version 7.0.0

**Comment by BrennanConroy** [comment]
Looks like we should update the docs to say 19+ then. It's also worth noting that in 8.0 the lowest Android API level will be 21+ due to OkHttp no longer supporting lower API levels.

It's also worth noting that Google Play doesn't even support anything below 19, and that vast majority of people are on 21+: https://apilevels.com/#:~:text=Android%20API%20Levels%20%20%20%20Version%20,%20%2037.9%25%20%2021%20more%20rows%20

**Comment by sadegh-q** [comment]
@BrennanConroy Thanks for your response,
Is any old version that supports .NET Core and API 16 together at the same time?

**Comment by BrennanConroy** [comment]
Any version before 5.0.0. But those are all unsupported versions.
