### ISSUE TITLE
New Identity login endpoint does not honor 'X-Requested-With: XMLHttpRequest' header

### ISSUE THREAD

**Issue by StevenRasmussen** [dotnet/aspnetcore#50010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am testing out the new Identity endpoints that are being exposed in asp.net Core 8.  When I attempt to hit the `/login` endpoint with invalid credentials, I am prompted by the browser for credentials even though I set the header `X-Requested-With: XMLHttpRequest`.  This is due to the endpoint setting the return header of `Www-Authenticate`.  I believe the generally accepted behavior is to not set that header if the request header has the `X-Requested-With: XMLHttpRequest` set.  See [here](https://stackoverflow.com/questions/86105/how-can-i-suppress-the-browsers-authentication-dialog)

![image](https://github.com/dotnet/aspnetcore/assets/11198735/09057b85-3cd6-46bb-a8b2-38d29e102da3)

### Expected Behavior

If a request to the `/login` endpoint has the `X-Requested-With: XMLHttpRequest` header set, and a `401` response is returned, it should not include the `Www-Authenticate` header which causes the browser to prompt the user for credentials.

### .NET Version

8.0.0-preview.7

### Anything else?

One thing to note is that I was not experiencing this when simply debugging in Visual Studio with Kestrel.  This behavior would only happen when I deploy to an IIS server.

**Comment by halter73** [comment]
Can you link to a GitHub repo that demonstrates this issue? The new [BearerTokenHandler does set the `www-authenticate` header](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/BearerToken/src/BearerTokenHandler.cs#L60), but it uses the "Bearer" rather than the "Basic" auth shown in the screen shot. I don't think this should cause the browser to prompt for credentials. I haven't seen it.
