### ISSUE TITLE
MapIdentityApi throws a System.ArgumentException when a user has multiple roles

### ISSUE THREAD

**Issue by KennethHoff** [dotnet/aspnetcore#50037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling the `account/info` endpoint when you have multiple roles throws a `System.ArgumentException` due to adding multiple values of the same key to a Dictionary.

### Expected Behavior

List all roles

### Steps To Reproduce

https://github.com/KennethHoff/Repros/tree/master/MapIdentityApiException

See Readme for steps

### Exceptions (if any)

```
System.ArgumentException: An item with the same key has already been added. Key: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Routing.IdentityApiEndpointRouteBuilderExtensions.CreateInfoResponseAsync[TUser](TUser user, ClaimsPrincipal claimsPrincipal, UserManager`1 userManager)
   at Microsoft.AspNetCore.Routing.IdentityApiEndpointRouteBuilderExtensions.<>c__1`1.<<MapIdentityApi>b__1_9>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>FB49A76E00958A78ED8A3DC031D4149080B37ED6EB129C512F9112A3DB80F087D__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass10_0.<<MapGet8>g__RequestHandler|4>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

**Comment by halter73** [comment]
We need to update the API that we [approved for RC2](https://github.com/dotnet/aspnetcore/issues/49424#issuecomment-1686799123) to make all the MapIdentityApi DTOs public in order to fix this bug.

## Background and Motivation

`InfoResponse.Claims` should support multiple values per claim type since this is commonly used. Roles are one extremely common use case where multiple claims will have the same `ClaimsIdentity.RoleClaimType`, but multiple claims with the same type

## Proposed API

```diff
// Microsoft.AspNetCore.Identity.dll
namespace Microsoft.AspNetCore.Identity.Data;

public sealed class InfoResponse
{
    public required string Email { get; init; }
    public required bool IsEmailConfirmed { get; init; }
-    public required IDictionary<string, string> Claims { get; init; }
+    public required IDictionary<string, string[]> Claims { get; init; }
}
```

#50953 targets release/8.0 and implements this updated API.

## Usage Examples

```csharp
    private static async Task<InfoResponse> CreateInfoResponseAsync<TUser>(TUser user, ClaimsPrincipal claimsPrincipal, UserManager<TUser> userManager)
        where TUser : class
    {
        return new()
        {
            Email = await userManager.GetEmailAsync(user) ?? throw new NotSupportedException("Users must have an email."),
            IsEmailConfirmed = await userManager.IsEmailConfirmedAsync(user),
            Claims = AggregateDictionary(claimsPrincipal.Claims.Select(claim => (claim.Type, claim.Value))),
        };
    }

    private static Dictionary<TKey, TValue[]> AggregateDictionary<TKey, TValue>(IEnumerable<(TKey, TValue)> pairs) where TKey : notnull
    {
        var dictionary = new Dictionary<TKey, TValue[]>(1);
        foreach (var (key, value) in pairs)
        {
            TValue[] newDescriptions;

            if (dictionary.TryGetValue(key, out var descriptions))
            {
                newDescriptions = new TValue[descriptions.Length + 1];
                Array.Copy(descriptions, newDescriptions, descriptions.Length);
                newDescriptions[descriptions.Length] = value;
            }
            else
            {
                newDescriptions = [value];
            }

            dictionary[key] = newDescriptions;
        }

        return dictionary;
    }
```

## Alternative Designs

We could also make the `Claims` an array rather than a dictionary/object which would be more similar to `ClaimsPrincipal.Claims`.

```diff
// Microsoft.AspNetCore.Identity.dll
namespace Microsoft.AspNetCore.Identity.Data;

public sealed class InfoResponse
{
    public required string Email { get; init; }
    public required bool IsEmailConfirmed { get; init; }
-    public required IDictionary<string, string> Claims { get; init; }
+    public required ClaimInfo[] Claims { get; init; }
}

+ public sealed class ClaimInfo
+ {
+    public required string Type { get; init; }
+    public required string Value { get; init; }
+ }
```

Or we could continue to use a dictionary, but use the concrete `Dictionary<string, string[]>` type instead of `IDictionary<string, string[]>` interface the implementation is probably always going to be a normal `Dictionary` going forward.

## Risks

The biggest risk is doing nothing and leaving the `/manage/info` completely broken for any user with multiple roles.

**Comment by KennethHoff** [comment]
I think the alternate design - the one mirroring ClaimsPrincipal - is cleaner and simpler to understand. 

Currently, I can see myself thinking - as someone whose entire knowledge (.. almost) of AspNetCore Identity comes from me testing out MapIdentityApi and practically immediately experiencing this exception -  "What is the string key representing? What is the string array value containing?"

**Comment by halter73** [comment]
API Review Notes:

- We discussed whether we'd prefer a flat list vs a dictionary as suggested in the PR, but decided that the dictionary is still better.
- We discussed the possibility of using `IReadOnlyDictionary` and/or `IEnumerable<string>`, but decided keeping it `IDictionary<string, string[]>` is better.
- Can we expose more information about each claim rather than just the type and value? If you were to JSON serialize `new Claim("Type", "Value")` gets serialized as S.T.J you'd get all of the following which includes "Subject" and "ValueType"
```json
{
  "Issuer": "LOCAL AUTHORITY",
  "OriginalIssuer": "LOCAL AUTHORITY",
  "Properties": {},
  "Subject": null,
  "Type": "Type",
  "Value": "Value",
  "ValueType": "http://www.w3.org/2001/XMLSchema#string"
}
```
- We could always add a `/manage/detailedClaims` endpoint in the future if we want, or a developer could write one themselves

```csharp
app.MapGet("/manage/detailedClaims", (ClaimsPrincipal user) => user.Claims);
```

- This is about giving the frontend enough information to display the right UI, and not for including enough information to recreate the `ClaimsPrincipal`.

After much discussion, we're not sure how necessary the `Claims` property is. We decided if someone wants more detail, they can add it themselves. For .NET 8, we'll just remove it.

The API proposal to remove the `Claims` property is approved.

```diff
// Microsoft.AspNetCore.Identity.dll
namespace Microsoft.AspNetCore.Identity.Data;

public sealed class InfoResponse
{
    public required string Email { get; init; }
    public required bool IsEmailConfirmed { get; init; }
-    public required IDictionary<string, string> Claims { get; init; }
}
```
