### ISSUE TITLE
query parameter does not work correctly in net 8 preview 7 under native aot

### ISSUE THREAD

**Issue by ivanjx** [dotnet/aspnetcore#50048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i cant have a route like this:
`/camera/archive/{cameraId}/chunk/{chunkName}`
to accept a request like this:
`/camera/archive/01870310-2e1e-428e-82fa-6bf15a74ecf0/chunk/4868579.ts`
because `chunkName` for some reason will always be null. this works fine if i do `dotnet run` but if i publish it with native aot, it does not work. see the attached file for the full bug repro.

i also believe this is a regression since it works fine with net 8.0 preview 6. you can try it by changing the versions in Dockerfile from 7 to 6.

### Expected Behavior

`chunkName` is not null or empty.

### Steps To Reproduce

[querybug.zip](https://github.com/dotnet/aspnetcore/files/12331399/querybug.zip)

### .NET Version

dotnet 8.0 preview 7

**Comment by captainsafia** [comment]
Thanks for this bug report, @ivanjx!

It looks like this is a bug related to the interceptors rewrite. Both of the route handlers in your application implement the exact same function signature (consume two strings and return a string) so we generate equivalent coegen for the both of them. I believe the issue here is that we should account for the parameter name in for methods that accept route parameters to account for the following codegen:

```csharp
var cameraId_RouteOrQueryResolver = GeneratedRouteBuilderExtensionsCore.ResolveFromRouteOrQuery("cameraId", options.RouteParameterNames);
var indexName_RouteOrQueryResolver = GeneratedRouteBuilderExtensionsCore.ResolveFromRouteOrQuery("indexName", options.RouteParameterNames);
```
