### ISSUE TITLE
Memory Leak on .Net 7 but not 6

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/aspnetcore#50097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a very simple API that was built targeting .Net 7. After a very long investigation[ available here](https://github.com/dotnet/diagnostics/issues/4139) we decided to try to revert the code back to .Net 6 and the leak was gone.

As explained, the leak could not be reproduced locally on either the VS debugger on Windows or Mac, nor using local docker. But we were able to reproduce on a clean AKS without any kind of monitoring, like Azure Monitor or datadog.

### Expected Behavior

Memory should stay constant while there's no users

### .NET Version

7.0.10

**Comment by adityamandaleeka** [comment]
Given that the original issue is at a point where there's unexplained native memory usage that needs to be investigated, I think it's best to keep the investigation in that issue for now. The folks you're talking to on that issue are also part of the .NET team and we can transfer the issue across repos when we know where the problem is. For now, having all the discussion in one issue is best.

**Comment by amcasey** [comment]
Agreed that we should track this investigation in a single issue (which can be moved between repos as needed).
