### ISSUE TITLE
WebApiAot ProjectTemplate add OpenAPI (Swagger) support

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#50134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

WebApiAot ProjectTemplate add swagger document

**Comment by captainsafia** [comment]
Thanks for filing this issue, @Varorbc! At the moment, it's not possible to introduce OpenAPI support using existing strategies for the native AOT template since they rely heavily on reflection APIs as part of their core functionality.

I'll close this issue for now but native AoT + OpenAPI is something we are reasoning through. I hope to track this with a more formal bug later.
