### ISSUE TITLE
Can we use Redis backplane to persist and read negotiate tokens to avoid sticky sessions in load balanced environment?

### ISSUE THREAD

**Issue by karthik-srivatsa** [dotnet/aspnetcore#50171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I recently encountered with an issue where the signalR connection was failing to establish intermittently with the status 404. Further reading about the same on internet forums made me realize that this is classic issue in load balanced environment where negotiate call is hitting one server and connection establishment call is hitting another server. 

### Describe the solution you'd like

The solution recommended from official MS documentation is to use sticky sessions or skip negotiation. Skipping negotiation will enforce the client to configure only WebSockets(which is fine, I guess). I tried looking for the implications of skipping negotiation but unfortunately, I didn't find concrete answer. If skipping negotiation is not completely recommended solution, **Can we make use of Redis backplane to persist token and validate it in next call?**

**Comment by BrennanConroy** [comment]
> If skipping negotiation is not completely recommended solution, Can we make use of Redis backplane to persist token and validate it in next call?

Short answer: No, use skip negotiation if you don't want sticky sessions.

Long answer:

SignalR is built on top of Connections.Abstractions. That layer is responsible for creating connections and handing them to the SignalR layer. The Redis backplane in SignalR is at the SignalR layer, meaning the connection creation has no concept of multi-server environments and no redis extensions.

So, let's imagine we do add Redis support at the Connections.Abstractions layer, and it puts IDs in Redis during /negotiate. Now the client can hit any server and use the ID from Redis, great! Except this immediately breaks if you don't use a persistent connection like WebSockets. e.g. LongPolling. Every request from LongPolling can hit a different server which means any state your application has for that connection would need to be synchronized in some database or shared memory. Additionally, any sends to the clients ID (`hubContext.Clients.Client("id").SendAsync(...)`) has to go to every server across the Redis Backplane which is a large waste of bandwidth and processing, today we only subscribe 1 server to listen to the connection ID specific messages which is much more efficient than every server needing to process the message.

To avoid this issue, we could restrict the Redis support to persistent connections only. So now clients using the WebSocket transport can negotiate with one server and connect to another without needing sticky sessions or session affinity. You would need to make sure you restrict your client code to WebSockets only, because other transports will break.

But at that point, just use skip negotiation which allows WebSockets to directly connect to a server without negotiating, avoiding all the added complexity described above.

**Comment by karthik-srivatsa** [comment]
Thanks for clarifying this :)
