### ISSUE TITLE
gRPC JSON transcoding documentation with Swagger / OpenAPI error

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#50177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I followed the [tutorial ](https://learn.microsoft.com/aspnet/core/grpc/json-transcoding-openapi)and enabled Aot, the program got an exception

![image](https://github.com/dotnet/aspnetcore/assets/5714438/403f8c2b-7527-4951-80ea-418b54fb75b4)

**Comment by adityamandaleeka** [comment]
This sounds a lot like what @captainsafia fixed in https://github.com/dotnet/aspnetcore/pull/49393

**Comment by adityamandaleeka** [comment]
@captainsafia can you take a look at this?

**Comment by captainsafia** [comment]
@Varorbc Are you able to share a repro for this issue?

From the original details in your report, this error is expected because it appears that you have enabled `PublishAoT` in an app that uses System.Text.Json to serialize types but did not configure the JSON source generator correctly by defining a JsonSerializerContext as outlined [here](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation).

**Comment by captainsafia** [comment]
> From the original details in your report, this error is expected because it appears that you have enabled `PublishAoT` in an app that uses System.Text.Json to serialize types but did not configure the JSON source generator correctly by defining a JsonSerializerContext as outlined [here](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation).

@Varorbc Do you repro the issue when you enable AoT _without_ configuring the Swagger?

FYI, although you see Swagger UI middleware in the stacktrace, this is an artifact of the way the Swashbuckle is configured in the middleware pipeline and not exactly related to it.

The exception message you've shared with me leads me to believe that it's related to enabling AoT in your application and not having the STJ generator enabled in your project per the instructions above.

If you're able to upload a repro of your project to GitHub, that might also help.

**Comment by adityamandaleeka** [comment]
@Varorbc Can you please share that as a public GitHub repo? Per policy we don't open zips.

**Comment by adityamandaleeka** [comment]
Thank you @Varorbc!

**Comment by captainsafia** [comment]
Thanks, @Varorbc! It looks like you are running into https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2550. The `Swashbuckle.AspNetCore` dependency doesn't support native AoT yet so you're running into issues with that.

Since this impacts the UI, you can try downloading the OpenAPI JSON definition and uploading it to a tool like [Postman](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/) to interact with it visually.
