### ISSUE TITLE
BLAZOR: Increase Debouce Time For Render

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#50494]
When I Maked A For Loop With 100 times and it Render One Time But When Delay Just 100 milliseconds it render 100 render

And here Other Example

```razor
<button @onclick="OnClickHandler">CLick Here</button>

@code {
    public int curruntCoutner = 0;
    [Parameter]
    public EventCallback<int> OnClickChanged { get; set; }
    [Parameter]
    public int OnClick { get; set; }
    [Parameter]
    public EventCallback<int> OnClick2Changed { get; set; }
    [Parameter]
    public int OnClick2 { get; set; }

    public async Task OnClickHandler()
    {
        curruntCoutner++;
        await OnClickChanged.InvokeAsync(curruntCoutner);
        await Task.Delay(100);
        await OnClick2Changed.InvokeAsync(curruntCoutner);
    }
}
```

Can I Edit The Debouce Of The Blazor Like

```c#
builder.Services.AddRazorComponents(e =>
{
       e.RenderDebouce = 500;
});
```

 Or I Think What Will Be Better Is

```c#
public class SomeComponent : ComponentBase
{
public override int DebouceOfTheRender() => 500;
}
```

And Thanks

**Comment by wisamidris7** [comment]
This Will Increase The Render Speed When Having Many Events From Everyplace Like

```c#
<button @onclick="OnClickHandler" @onfocus="OnFocusHandler">CLick Here</button>

@code {
    public int curruntCoutner = 0;
    [Parameter]
    public EventCallback<int> OnClickChanged { get; set; }
    [Parameter]
    public int OnClick { get; set; }
    [Parameter]
    public EventCallback<int> OnClick2Changed { get; set; }
    [Parameter]
    public int OnClick2 { get; set; }

    public async Task OnClickHandler()
    {
        curruntCoutner++;
        await OnClickChanged.InvokeAsync(curruntCoutner);
    }
    public async Task OnFocusHandler()
    {
        var someValue = HttpClient.Get...;
        await OnClick2Changed.InvokeAsync(someValue);
    }
}
```
This Will Render Two Times So This Will Be So Useful

**Comment by javiercn** [comment]
> When I Maked A For Loop With 100 times and it Render One Time But When Delay Just 100 milliseconds it render 100 render

It's not super clear what your ask here is. But likely the behavior you are seeing is by design. All renders that happen synchronously are batched on the same render batch, so calling render 100 times will be the same as calling it once.
There will only be 1 UI update.

If you are using `Task.Delay` or similar within your own loop (and calling StateHasChanged) then there will be 100 renders because there are 100 synchronous render batches in between your renders.

This behavior already exist on the framework and we don't plan to provide anything on ComponentBase to achieve it, since its trivial to do in your own code.

**Comment by wisamidris7** [comment]
thanks
