### ISSUE TITLE
[dotnet-sdk-8.0.100-rc.2.23451.1] SPOTClient reported Telerik.UI.for.Blazor package error on the login page. 

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#50525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When run the 3rd party application SPOTClient with the latest .NET 8 build, it failed on login page with Telerik.UI.for.Blazor package error.

**Application Name:** SPOTClient
**OS**： Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-8.0.100-rc.2.23451.1
**App, App Source and Repro environment checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1881082

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.2.23451.1: Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23423.3: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.414-win-x64: Pass

### Expected Behavior

launch successful.

### Steps To Reproduce

**Minimal repro steps:**  
Please refer to the demo attached [BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/12533953/BlazorApp1.zip)

1. Create Blazor Server App project(.net7.0)  
2. Install the nuget package : ```telerik.ui.for.blazor```
3. Add this code to _Host.cshtml
```<script src="_content/Telerik.UI.for.Blazor/js/telerik-blazor.js" defer></script>```
4. Add this code to Index.razor
```
<div class="mb-3">
    <Telerik.Blazor.Components.TelerikTextBox Id="@ID" Value="@Values" Label="@Labels" PlaceHolder="Enter your connected email address"></Telerik.Blazor.Components.TelerikTextBox>
</div>

@code
{
    string Values = "Values", Labels = "Labels", ID = "1";
}
```
5. Build and publish and run it with .net8 runtime
6. Go to : http://localhost:5000/

**App repro steps on repro machine:**
1.Execute “cd C:\SPOTClient\App\SPOTClient” in cmd.
2.Execute “dotnet SPOT.Platform.Client.Host.dll” in cmd.
3.Launch Server url: https://localhost:5005

### Exceptions (if any)

launch failed with below error:
```
blazor.server.js:1  [2023-09-05T08:32:55.677Z] Error: Microsoft.JSInterop.JSException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Function.assign (<anonymous>)
    at e.extend (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9184)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9537)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
    at t (https://localhost:5005/_content/Telerik.UI.for.Blazor/js/telerik-blazor.js:1:9523)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Telerik.Blazor.Components.Common.TextBoxBase.InitJsComponentAsync()
   at Telerik.Blazor.Components.Common.TextBoxBase.OnAfterRenderInternalAsync(Boolean firstRender)
   at Telerik.Blazor.Components.Common.TextBoxBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### .NET Version

 8.0.100-rc.2.23451.1

### Anything else?

dotnet info:
```
.NET SDK:
 Version:   8.0.100-rc.2.23451.1
 Commit:    dabc29073d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23451.1\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23431.9
  Architecture: x64
  Commit:       3c48925a6c
  RID:          win-x64

.NET SDKs installed:
  8.0.100-rc.2.23451.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.2.23431.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23431.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23430.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@mkArtak  This bug was found on the latest RC2 build and affect a very important app of our customer. Could you please check if this bug is a blocker?  Thank you.

**Comment by mkArtakMSFT** [comment]
@Junjun-zhao did work as is with the earlier version of the .NET 8 (RC1 as an example) or just .NET 7?

**Comment by PriyaPurkayastha** [comment]
> @Junjun-zhao did work as is with the earlier version of the .NET 8 (RC1 as an example) or just .NET 7?

Yes, it seems to have worked in RC1 based on the following at the top of the issue:
_Verify Scenarios:
_1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.2.23451.1: Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23423.3: **Pass**
3). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.414-win-x64: **Pass__**

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT Do you have any update for this bug? Is it a blocker for .NET 8 RC2 validation test?

**Comment by mkArtakMSFT** [comment]
Not a blocker for RC2 validation. We will address this in 8.0 GA.

**Comment by SteveSandersonMS** [comment]
I've been trying to investigate, which is tricky, because this issue happens inside `telerik-blazor.js` which is not included in the repro sources, and the only publicly available versions of it are minified.

However I do think I can see what's going on. `telerik-blazor.js` tries to do something similar to:

```js
deepExtend(options1, options2)
```

... where `options1` and `options2` are both JavaScript objects that have a property called `dotNetInstance` of type `DotNetObject`. The `deepExtend` logic presumably walks all the properties of `options2` recursively to apply them to `options1`.

In effect this means writing to the internals of a `DotNetObject` instance, which is definitely not supported. In .NET 7 and before, this happened to work, because both of the `dotNetInstance` objects happened to have the same `_id` value and no other properties. But in .NET 8, `DotNetObject` also has a new property `_callDispatcher` of type `CallDispatcher`, which on Blazor Server is actually the `CircuitManager`. This references a very wide range of things, and in particular, has a reference cycle so that if you naively try to walk its properties recursively, you'll get stuck in an infinite loop evaluating:

```js
_callDispatcher._dispatcher._dotNetCallDispatcher._dispatcher._dotNetCallDispatcher._dispatcher._dotNetCallDispatcher ... etc
```

### Fixing this

Developers and component library authors shouldn't be making the assumption that `DotNetObject` instances are safe to mutate internally (they are opaque handles, and mutating their internals is like private reflection or unsafe code in C#), nor should they assume it's possible to walk their properties recursively (again, it's exactly equivalent to using private reflection in C# to walk everything reachable from some framework primitive like `GCHandle`). It only worked by chance in earlier versions.

Blazor could be more defensive about this. For example, we could change `DotNetObject` (in `Microsoft.JSInterop.ts`) so that its properties are not enumerable or at least have symbol names. As per the [traversal rules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#traversing_object_properties), the options include:

 * Use symbol names to stop the properties showing up in `for (let propName in obj)` from seeing them. That's what `telerik-blazor.js` is doing to enumerate the properties.
 * Or, define the property as nonenumerable. That's a bit more robust but has a perf cost (and is still visible to `getOwnPropertyNames`/`getOwnPropertySymbols`)
 * Or even creating a special inheritance chain where `_callDispatcher` has a symbol name and is defined only on the prototype chain. That would give very high robustness against accidental discovery but is quite complex as we'd have to go outside the help that TypeScript offers natively for objects and inheritance.

If we did this, I don't know if `telerik-blazor.js` would start working. My guess is it probably would, at least in the common case where you only have either Server or WebAssembly in your app at a single time. If you have both platforms at once, or switch from one to the other, then it may be buggy since it appears to make the assumption it's allowed to track a single `DotNetObject` that refers to .NET as a whole. I can't confirm either way since I don't have access to its sources or design documents etc.

### Proposal

From the above list:

 * Use symbol names to stop the properties showing up in `for (let propName in obj)` from seeing them

That will make it hard for people to do the wrong things with `DotNetObject` naively. It's not our business to stop people from bypassing the safety rails with `getOwnPropertySymbols` etc any more than .NET should stop people from doing private reflection on framework types.

**Comment by PriyaPurkayastha** [comment]
Thank you @SteveSandersonMS for your thorough investigation. Was the _callDispatcher property added in .NET8 RC2? Any idea about usage of Telerik Blazor controls? For this particular customer app, it fails at login itself. Hence trying to understand how many apps out there will be broken by this when they move to RC2. At minimum, I think this should be documented as a Known Issue in .NET 8 RC2 so that customers are aware of it. cc @marklio

**Comment by SteveSandersonMS** [comment]
Another thought: this SPOT app is using Telerik for Blazor 2.22.0, released Feb 2021. The current version of Telerik for Blazor is 4.5.0.

If newer versions of Telerik for Blazor do work OK, then it would perhaps be reasonable to understand this as "very old versions of Telerik for Blazor are not compatible with .NET 8 and you should upgrade to a newer version".

@PriyaPurkayastha Would you be able to upgrade the SPOT app (or your minimal repro case) to use the current version of Telerik for Blazor to see if this resolves the issue?

**Comment by PriyaPurkayastha** [comment]
@Junjun-zhao will be able to try using the latest Telerik version 4.5.0 tonight (team is based in China) and report back.

**Comment by EduardoBocada** [comment]
> @Junjun-zhao will be able to try using the latest Telerik version 4.5.0 tonight (team is based in China) and report back.

Same thing for me here using latest Telerik UI for Blazor (4.5.0) and .NET 8 RC2.
It was working on .NET 7, .NET 8 Preview 7 and .NET 8 RC1

**Comment by Stamo-Gochev** [comment]
Hi all, 

My name is Stamo Gochev and I am one of the developers working on the Telerik UI for Blazor product.

I want to inform you that we are investigating the issue. If you have any further feedback or questions about the case, please reach out to us by opening a Telerik support ticket.

@SteveSandersonMS You can close the current issue as it is not related to the Blazor framework.

**Comment by Stamo-Gochev** [comment]
> Hi all,
> 
> My name is Stamo Gochev and I am one of the developers working on the Telerik UI for Blazor product.
> 
> I want to inform you that we are investigating the issue. Once we have more details, we will share our findings. If you have any further feedback or questions about the case, please reach out to us by opening a Telerik support ticket.
> 
> @SteveSandersonMS You can close the current issue as it is not related to the Blazor framework.

A quick update on this - we have a bug fix for the reported problem - if you are a Telerik customer and would like to test the fix, please open a Telerik support ticket and our team will help you.

**Comment by mkArtakMSFT** [comment]
Thanks @Stamo-Gochev.
Closing this as `external` at this point, given no action is pending from our end.

**Comment by iwhp** [comment]
There is an update from Telerik (v4.6.0) which solves this problem.
