### ISSUE TITLE
Microsoft.AspNetCore.Hosting.Abstractions and Microsoft.AspNetCore.App marked as deprecated

### ISSUE THREAD

**Issue by ctorresunimag95** [dotnet/aspnetcore#50641]
Hi all, I am currently working with some class libraries, I use the latest version of **Microsoft.AspNetCore.Http.Abstraction** available is 2.2.0 which is deprecated. Also, the **Microsoft.AspNetCore.App** that is recommended to be used as an alternative is marked as deprecated too.

Is there any plan to release those packages again or an alternative for them? Thanks!

**Comment by martincostello** [comment]
These packages are now part of the shared framework since ASP.NET Core 3.0, which are made available via à `FrameworkReference` rather than a `PackageReference`. This is why the packages are marked as deprecated and why there are no newer versions.

You can find more details about this here: https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework
