### ISSUE TITLE
RazorComponentResult returned component cannot execute clientside code

### ISSUE THREAD

**Issue by michaelongithub** [dotnet/aspnetcore#50762]
Hi 
I want to return a Razor Component from a controller. (.net 8 RC1, newest Blazor WebApp Template)
```
        public IResult CRT()
        {
            return new  RazorComponentResult<Components.Components.Counter>();
        }
```
I have a simple test component (the infamous Counter.razor) with @attribute [RenderModeServer]
Returns correct rendered component But counter event is not triggered:

- Not available for components returned with RazorComponentResult? Mere HTML rendering  as standard Blazor 8 SSR ?
- Will be available in RC2 / RTM
- if not, how to have a MVC Architecture with clientside code for Blazor 8 ?

BTW: The same behaviour if I use the component inside a Razor page (cshtml) with @await Component.InvokeAsync("Counter");
So has this maybe to do with that these calls cannot handle the new @attribute [RenderModeServer] ?

Thanks for information, Michael

**Comment by marinasundstrom** [comment]
You can't serve an interactive component without a static page in which to host it. That is why the new SSR model requires you to have the root ``App.razor`` (equivalent to index.html). It has to do with the Blazor JS script having to load once. 

And I'm not sure that interactive components are supported for component endpoints anyway.

You need to serve the ``blazor.web.js`` script, from the ``_framework`` path, and there is no easy way to expose that file without activating the entire thing by automatically mapping the components.

**Comment by michaelongithub** [comment]
Hi
thanks for reacting so quickly.
in .net 7 going via an enveloping .cshtml and having a layout file used in that view with <script src="_framework/blazor.server.js"></script> and 
    @(await Html.RenderComponentAsync<BlazorWebAppVS1782Empty.Components.Components.Counter>(RenderMode.Server)) 
 works with events. Haven't found out jet, how to make this work in .net 8 RC1.  But expect that to work again analogously somehow latest at RTM. Is not as ideal as it would be directy via RazorComponentResult.
My main motivation for that was to be able to have an MVC pattern style architecture again for may Blazor apps.

**Comment by marinasundstrom** [comment]
@michaelongithub I see. You try to create an MVC style app with Razor Components for views in custom endpoints.

I don't think that it is a supported case. Component endpoints are not meant to allow you do create MVC-style apps like with "Razor Views" in MVC.

Btw. Another thing to consider is the use of layouts for shared UI. They will not work unless you have the ``Router`` and the ``RouteView``. Because the latter applies that layout.

I do however agree that there are some things with component endpoints that aren't clear.

**Comment by michaelongithub** [comment]
Thanks again. So my understanding of the current situation is as follows:

- In its current inception for my motivation I don't see much use cases for RazorComponentResult.    While I understand your initial explanations for the limitation I wonder what the use case intentions of the Blazor team are with this method.
- Using Blazor Components with clientside code inside a Razor View was working in .net 7. I hope this will be available in .net 8 again or example / doc how this is working already with the new per component rendering mode.
- I still would like to have the option of organizing Blazor apps with an MVC pattern architecture. Anybody know how to to that in .net 8 ? (Without taking recourse to the "clumsy" detour with embedding components in razor views which I assume will be working again)

**Comment by marinasundstrom** [comment]
@michaelongithub Btw. I now see that you are using ``Component.InvokeAsync``. Isn't that just for Razor View components? (Not Razor/Blazor components)

Have you tried the ``component`` tag helper to render a Blazor component in a Razor View:

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-7.0

**Comment by marinasundstrom** [comment]
@danroth27 Are interactive components supported through Minimal API endpoints returning ComponentResult? (Apart from the limitation that you would have to render them in an SSR component)

**Comment by michaelongithub** [comment]
Thanks again for the hint
I had already tried 
`@(await Html.RenderComponentAsync<BlazorWebAppVS1782Empty.Components.Components.Counter>(RenderMode.Server))  `
And now per your advice
```

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<component type="typeof(Counter)" render-mode="Server" />
```
both make no clienside code running.

**Comment by marinasundstrom** [comment]
@michaelongithub 

Have you included the script? (Provided that you run .NET 8)

```js
<script src="_framework/blazor.web.js" suppress-error="BL9992"></script>
```

That is required to activate the interactivity. So it should be either directly in your view (.cshtml), or in a layout/master file.

**Comment by marinasundstrom** [comment]
@michaelongithub I have create a functioning MVC app that has a view that renders and interactive Razor component. To me it seem like it is working in .NET 8.

https://github.com/marinasundstrom/BlazorMvcViewTest

The route is ``/Test``.

**Comment by michaelongithub** [comment]
@marinasundstrom Tested Your Example:

- Yes clientside code works
- is as .net 8 Framework solution on the level of the project
- **but** as far as I can see is still the .net 7 template with old _hosts and app.razor file
- and uses    .net 7  <script src="_framework/blazor.server.js"></script> and not     <script src="_framework/blazor.web.js"></script> for .net 8.
- But thanks anyway.

**Comment by marinasundstrom** [comment]
@michaelongithub Yes. I created a Blazor Server .NET 7 project, and upgraded it. And true, I did not use the new script.

In the case of the ``TestController`` and its action and endpoint, I am not using ``_Host.cshtml`` at all. They are separate Razor views and Components.

The issue is that Blazor only exposes ``blazor.web.js`` when invoking the ``MapRazorComponents<TRootComponent>``. You only need to invoke those methods when you are using the stuff related to the integration with the router.

Because the script is not being expose, I asked @danroth27 for answers whether interactive components are supported in components from plain endpoints

I have update the sample and added a custom ``UseBlazorWebJS()`` method that maps the ``blazor.web.js`` file. It is based on [this](https://github.com/dotnet/aspnetcore/blob/57d703606439dccabec92c2a0d5e4fa618985cd8/src/Components/Endpoints/src/Builder/RazorComponentsEndpointRouteBuilderExtensions.cs#L57).

That way you can reference and use the newer script. But you will not be able to use Blazor WASM components without adding them to the container first - I think.

@SteveSandersonMS Perhaps you know the details of this? How to approach this scenario.

**Comment by marinasundstrom** [comment]
I have tested Minimal API endpoint with interactive components. It works.

https://github.com/marinasundstrom/BlazorMinimalApiTest

Created components:

* ``Counter`` - Interactive on the server.
* ``MyPage`` - equivalent to an ``index.html`` page (Server-side-rendered)

Register Razor component services:

```cs
builder.Services.AddRazorComponents()
    .AddServerComponents();
```

Serve the Blazor JS script:

```cs 
app.UseBlazorWebJS()
```

Map endpoint:

```cs
app.MapGet("/test", () => new RazorComponentResult<BlazorMinimalApi.Components.MyPage>());
```

Map Blazor Hub:

```cs
app.MapBlazorHub();
```

I don't know how well this is documented.

**Comment by michaelongithub** [comment]
@marinasundstrom Amazing. Admirable. Shows that it is basically possible in .net 8. 

- This is a minimal API scenario and built through the webapi template, not the cli dotnet new blazor (Blazor WebApp template in VS). I would have liked to have the team provide example / guidance / doc for an example based on that template with a programmatically returned Blazor component with clientside code. But maybe their moving the initial issue to Net 9 Planning means that it is not yet part of .net 8. ?
- How did you go about /what was your reasoning to find out about UseBlazorWebJS? Is this part of the official Blazor 8 RC ?
- Really don't want to keep you busy, not as tireless as you seem to be.

**Comment by marinasundstrom** [comment]
@michaelongithub I'm just a humble enthusiast and developer who is happy to help. And it was much needed distraction to me! 🙂 

I guess it is about priorities. Now when the final release is near.

When I started experimenting with this, a month ago, I noticed that the _blazor.web.js_ wasn't served unless you called MapRazorComponents<T>(). So I dug into the code and extracted that bit into my own extension method.

The key to make interactive server components work is the .MapBlazorHub(), as well as serving the script.

I think that the Blazor team needs time to think about how to design these APIs.

In the meantime, you have this workaround. Which I documented about in my repository for others to see.

But I have not tried out WebAssembly. I guess that I need to expose more static files. I will update once I have explored that.

**Comment by marinasundstrom** [comment]
FYI. I got WebAssembly working as well. So added endpoint for that.

**Comment by michaelongithub** [comment]
@marinasundstrom Indefatigable ! From the viewpoint of a wide perspective of a "Blazor Fullstack" I would expect the possibility to return a fully functional Blazor Component programmatically. My main argument being: You can return Razor Views and Pages. So please make that possible for Blazor Components.

**Comment by marinasundstrom** [comment]
@michaelongithub You have to know that endpoints that serve Razor Components aren't a replacement for Razor Views in MVC. You will not get the same but with Razor components.

You won't get things like layouts since they require you to have a ``Router`` component, and a ``RouteView`` component that applies the layout.

And I don't know if enhanced navigation, and such will work in your MVC case.

So in normal cases, when you are building full on interactive Blazor apps, you would rather use the other way of letting ASP.NET Core registering the pages to be used by the router.

But I think that since ASP.NET now supports rendering Blazor components through endpoints, and you can add interactivity, then it should be exposed for the developer to be used.

**Comment by marinasundstrom** [comment]
@mkArtakMSFT What should we do with this?

**Comment by javiercn** [comment]
I am going to clarify the state of things for .NET 8.0

* RazorComponentResult is designed to emit static HTML. There is no oficially supported way of achieving interactivity, although its technically possible to do so in several ways.
  * The reality is that when you try to do this at a "large scale", there are several things that you need to align to make things work (scripts, "special" framework endpoints, etc).

* If you want to enjoy all the available features, (enhanced navigation, streaming rendering, auto mode, etc.) you need to use Blazor Web.

* You can continue to use an MVC architecture with components via the component HTML helper or the tag helper. That will continue to work for the foreseable future, and its a perfectly valid alternative to have an island architecture.
  * The main missing features here are enhanced navigation, streaming rendering, and auto mode.

With this in mind, very likely our focus moving forward will be to continue expanding on the Blazor Web experience (MapRazorComponents), as that is the mainline scenario for us.

**Comment by michaelongithub** [comment]
@javiercn: Thanks a lot for this clarification
