### ISSUE TITLE
[8.0] RouteHandlerAnalyzer throws InvalidOperationException

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/aspnetcore#50836]
I've hit the following error while working on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2044.

```log
CSC : error AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Builde
r.EndpointRouteBuilderExtensions'.'. 
```

```cmd
PS D:\projects\forks\healthChecks> dotnet --info
.NET SDK:
 Version:   8.0.100-rc.2.23429.6
 Commit:    4bafa2271a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23429.6\
```

Repro:

```cmd
git clone https://github.com/adamsitnik/AspNetCore.Diagnostics.HealthChecks.git --branch reproBug reproBug
cd reproBug
dotnet build .\test\HealthChecks.UI.Tests\HealthChecks.UI.Tests.csproj
```

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @adamsitnik! We've gotten a few similar reports over the past few days including in https://github.com/dotnet/aspnetcore/issues/50868 and https://github.com/dotnet/aspnetcore/issues/50881. I'll close those in favor of using this one as the investigation.

https://github.com/dotnet/aspnetcore/issues/50868 highlights the framework reference being included as possibly related but I think that there might be a red herring considering the nature of the other bug reports. I'll dig in and see what I can find...I suspect upgrading runtime versions ithe more likely dilemma here...

**Comment by captainsafia** [comment]
OK, it turns out that this is related to the fact that the HealthChecks UI package uses the same type name in their sources as we do in ours:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/4607fc5b338388d3fcf302fc60fb004961825b9a/src/HealthChecks.UI/Extensions/EndpointRouteBuilderExtensions.cs#L9

Since we use `GetTypeByMetadataName`, it will return `null` if types by the same name are encountered in different assemblies. We can be more defensive here and use `GetTypesByMetadataName` then filter to the assemblies that we care about.

**Comment by glen-84** [comment]
This is also affecting [HotChocolate](https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/AspNetCore/src/AspNetCore/Extensions/EndpointRouteBuilderExtensions.cs).

**Comment by vip32** [comment]
package AspNetCore.HealthChecks.UI (7.0.2) is also causing this issue to appear

**Comment by michaelmcneilnet** [comment]
Is there any workaround for this? We're using HotChocolate and hitting this blocking issue on upgrading to DotNet8 today 😢

**Comment by glen-84** [comment]
@michaelmcneilnet

> Is there any workaround for this?

```xml
<PropertyGroup>
  <NoWarn>$(NoWarn);AD0001</NoWarn>
</PropertyGroup>
```

**Comment by tmitchel2** [comment]
I get 3 similar warnings in 3 different analyzers... (I'm using HotChocolate also)

warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.WebApplicationBuilder.WebApplicationBuilderAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions'

warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'.'

warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteEmbeddedLanguage.RoutePatternAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'

**Comment by jeremy-allocate** [comment]
I cannot believe this wasn't resolved before 8 went live to the world...

**Comment by captainsafia** [comment]
Thanks for the feedback here folks! The actual fix to this issue is in https://github.com/dotnet/aspnetcore/pull/50969. I'm bumped CI and request for reviews on this PR so that we can get it in the next servicing cycle.

In the meantime, the workarounds identified in [this comment](https://github.com/dotnet/aspnetcore/issues/50836#issuecomment-1812985321) should be sufficient for projects running into this with the dependencies at hand.

For context, this issue will manifest if any library references in your application are also declaring methods in the `Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions` static class. In this case, Roslyn's lookup will throw an exception when it discovers two types of the same name when resolving type symbols by name from metadata.

The fix here was to modify the behavior of our lookup to use alternative APIs that only checked for types based on name _and_ assembly.

**Comment by vipwan** [comment]
```bash
1>CSC : warning AD0001: 分析器“Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer”引发类型为“System.InvalidOperationException”的异常，并显示消息“Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'.”。
```
The compilation result is not affected, but the error message is annoying

**Comment by saddamhossain** [comment]
I am facing the same issues when I use **AspNetCore.HealthChecks.UI (version 7.0.2)**

**Comment by captainsafia** [comment]
To follow-up on this, the fix for this has been merged and is expected to be released in the next servicing release of .NET 8. In the meantime, recommend using the workarounds mentioned above.

**Comment by onionhammer** [comment]
Anyone else seeing this?

> Request textDocument/semanticTokens/range failed.
  Message: Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'.
  Code: -32000

**Comment by captainsafia** [comment]
@onionhammer I haven't seen that one before.

My hunch tells me that `textDocument/semanticTokens/range` is an operation that triggers an analyzer run, but the analyzers fails to load (because of the issue discussed here), and that triggers cascading failures in the extension.

Does using the workarounds mentioned above resolve the issue with the C# extension?

**Comment by onionhammer** [comment]
> Does using the workarounds mentioned above resolve the issue with the C# extension?

No, I already had that NoWarn set up ages ago

**Comment by captainsafia** [comment]
> > Does using the workarounds mentioned above resolve the issue with the C# extension?
> 
> No, I already had that NoWarn set up ages ago. This issue started happening more recently

@onionhammer OK, in that case. I'd recommend trying to see if updating to the upcoming .NET 8 release will resolve the issue. If not, I'd recommend filing an issue against the C# extension repo, especially if you are not seeing these exceptions in VS or when building from the commandline.

**Comment by onionhammer** [comment]
I only started seeing it after .net 8

**Comment by tmitchel2** [comment]
Great 👍🏻 thanks
