### ISSUE TITLE
Blazor Server authentication documentation is all over the place

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#50947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have used Blazor server authentication before the recent changes (azure AD).
With Microsoft Entra, one needs to make changes. 
The simple ask for a basic app with a single tenant is as follows:
1. Make the user login in case he is not logged in
2. Provide a logout button once he logs in

There is no documentation that addresses both.
The [link ](https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-blazor-server) on the app registration page has a 'tutorial' for Blazor server 
![image](https://github.com/dotnet/aspnetcore/assets/40038634/32082ec7-09b7-4dee-af81-da797b249fbf)

It is barely useful because it does not cover `CascadingAuthenticationState` or `AuthorizeRouteView`. Once it covers the "sync tool" it simply jumps to a generic tutorial that has nothing related to Blazor. It has only .net core, asp.core and other OSS platforms.

Then we also have the official documentation on Blazor. It is much more detailed. Yet even this does not have any mention of the process to be followed to implement a sign out button!

From [30000 ](https://github.com/dotnet/aspnetcore/issues/30000) I understand that Blazor documentation team wants to be platform agnostic and the azure team might be doing its own thing. But would it be possible to have one single document somewhere that has the entire login - logout flow for a single tenant in Azure?

**Comment by guardrex** [comment]
> Yet even this does not have any mention of the process to be followed to implement a sign out button!

Not directly ... that's true. The doc calls for the dev to ***scaffold*** their Identity needs into the app and cross-links to the *Scaffolding* document in the main doc set.

We don't document what a given SDK will provide in these scenarios as baseline code examples for any given release. This approach helps with churn in the recommendations that scaffolding templates make, but it's true that it hides a baseline idea/concept for how to accomplish Identity task implementations. In this case, it would be for `Account\Logout`, and you'd get the following Razor code for the current release ...

```cshtml
@{
    if (User.Identity?.IsAuthenticated ?? false)
    {
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
            <button type="submit" class="nav-link btn btn-link text-dark">Click here to Logout</button>
        </form>
    }
    else
    {
        <p>You have successfully logged out of the application.</p>
    }
}
```

... and the `Logout` model in code-behind is like this ...

```csharp
public class LogoutModel : PageModel
{
    private readonly SignInManager<IdentityUser> _signInManager;
    private readonly ILogger<LogoutModel> _logger;

    public LogoutModel(SignInManager<IdentityUser> signInManager, ILogger<LogoutModel> logger)
    {
        _signInManager = signInManager;
        _logger = logger;
    }

    public async Task<IActionResult> OnPost(string returnUrl = null)
    {
        await _signInManager.SignOutAsync();
        _logger.LogInformation("User logged out.");
        if (returnUrl != null)
        {
            return LocalRedirect(returnUrl);
        }
        else
        {
            // This needs to be a redirect so that the browser performs a new
            // request and the identity for the user gets updated.
            return RedirectToPage();
        }
    }
}
```

I think in ref source, it's over here ...

* https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.Logout.cshtml
* https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.Logout.cs.cshtml

We could document at least some of these in a more basic fashion ... or just continue to tell devs to use scaffolding to see what the template recommends.

> the entire login - logout flow for a single tenant in Azure

Thus far, we leave it to the Azure docs to cover. We've been more focused on what Blazor and Identity scaffolding do. However, we do continue to carry WASM-based Azure docs because I felt that our docs are better than their docs. 😜 Almost yearly, I try to shed our content for Azure to their resources, but I find each time I look that I like our WASM-Azure articles better.

@JeremyLikness ... You can email me if you want to discuss the history of the choices made, but I think you get the drift of it from that :point_up:.

**Comment by mayur-ekbote** [comment]
Thank you for your reply.

> ... and the LogoutModel in code-behind is like this ...

Actually, the signin/ signout Blazor code looks like this:

```
<AuthorizeView>
    <Authorized>
        Hello, @context.User.Identity.Name!
        <a href="MicrosoftIdentity/Account/SignOut">Sign Out</a>
    </Authorized>
    <NotAuthorized>
        <a href="MicrosoftIdentity/Account/SignIn">Sign In</a>
    </NotAuthorized>
</AuthorizeView>
```
That's it (at least I hope so, since it is part of the samples). As you can see, there is no explicit reference to asp.net style controllers or areas or anything. 
_However_ this is provided if you add the following to the startup class:


```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddMicrosoftIdentityWebAppAuthentication(builder.Configuration, "AzureAd");
builder.Services.AddControllersWithViews()
                .AddMicrosoftIdentityUI();

builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = options.DefaultPolicy;
});

// Add services to the container.

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor().AddMicrosoftIdentityConsentHandler(); 
// other stuff
app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
```

And of course, update the config file with the client and app IDs, along with updating the endpoint settings in Azure portal (that documentation is a little vague - it doesn't specify exactly how exactly the callback URLs work.)

But I hope you see the source of frustration - one needs to google and stitch the pieces together and then do some trial and error to figure out how these things work ( `AzureAD` related stuff is now in `Microsoft.Identity.Web`)

At least for Microsoft technologies (Blazor+Azure) it is only reasonable to expect a cohesive document. At least an official blog post, if not an official doc?

**Comment by guardrex** [comment]
You're right, @mayur-ekbote ... I forgot that scaffolded code for Identity won't target Microsoft Identity Platform endpoints. I think Jeremy's plans are to sort out better Blazor Server coverage.

**Comment by mkArtakMSFT** [comment]
Thank you for your patience.
Given the number of issues that we have to deal with, we're aggressively closing those that we haven't been able to get to in a reasonable time. This will help us focus on the issues which are more impactful.
