### ISSUE TITLE
source-building: restore.cmd not working properly (Microsoft.DotNet.Arcade.Sdk not found)

### ISSUE THREAD

**Issue by trynn** [dotnet/aspnetcore#50950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While trying to write a pull request, run into following issue:

Clean/New clone of repository.

```
PS S:\github\aspnetcore> git clone git@github.com:trynn/aspnetcore.git
```

The Restore Script fails. 
```
PS S:\github\aspnetcore> .\restore.cmd
```
See attached Exception-Log.

# fix
Issue here is, the `NuGet.confg` from the repository is not used. Therefore the Nuget sources point to my private setup.
To fix this, a rename to `NuGet.Config` (note the casing) is required.
(credits to from https://github.com/dotnet/sdk/issues/7875)

No idea, why i'm the only one running into this issue? 
Maybe some1 can verify and reproduce the behaviour.

### Expected Behavior

I expect that the Nuget-Sources from /NuGet.config are used in the restore script.
Since it's clearly `NuGet.config` in the repository, the casing has either to be fixed or the resolver for the config needs to handle this differently?

### Steps To Reproduce

1. Clone Repo
2. make sure you have custom `%AppData%\NuGet\NuGet.Config` you can identify later.
3. execute restore.cmd

### Exceptions (if any)

```
PS S:\github\aspnetcore> .\restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error : Could not resolve SDK "Microsoft.DotNet.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve
 that message to correctly specify the SDK.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): internal, Microsoft Visual Studio Offline Packages, nuget.org
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.DotNet.Arcade.Sdk" because directory "S:\github\aspnetcore\.dotnet\sdk\9.0.100-alpha.1.23464.
17\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk" did not exist.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error : You are running the 'restore' operation with an 'HTTP' source, 'http://nuget.internal.synesc.net/nuget'. Non-HTTPS access will be removed in a future version. Con
sider migrating to an 'HTTPS' source.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
Build failed with exit code 1. Check errors above.
```

### .NET Version

7.0.401 / 9.0.100-alpha.1.23464.17

### Anything else?

Executed on Windows 22H2 19045.3448
Powershell 7.3.7
Visual Studio Community 2022, 17.7.4
git version 2.42.0.windows.2

**Comment by wtgodbe** [comment]
@emgarten according to https://github.com/NuGet/Home/issues/4785#issuecomment-285817274, `NuGet.config` is supported, which is how we case our file: https://github.com/dotnet/aspnetcore/blob/main/NuGet.config. Is the behavior the author is seeing expected?

**Comment by wtgodbe** [comment]
Looks like Justin has moved teams, @nkolev92 any thoughts on the above?

**Comment by nkolev92** [comment]
Didn't arcade have an issue with casing at some point? Is maybe that the problem? 
NuGet should be supporting all casings.

**Comment by wtgodbe** [comment]
Do you have any more details on that casing bug? I'm not sure how to track it down. Maybe someone from @dotnet/dnceng remembers?

**Comment by trynn** [comment]
Just re-tested with the same result on my maschine.

```
PS S:\github\aspnetcore> .\restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
GET https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
  Attempting to install 'sdk v9.0.100-alpha.1.23524.8' from public location.
dotnet-install: Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
dotnet-install: Downloaded file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "S:\github\aspnetcore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 9.0.100-alpha.1.23524.8
dotnet-install: Installation finished

Welcome to .NET 9.0!
---------------------
SDK Version: 9.0.100-alpha.1.23524.8

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
S:\github\aspnetcore\artifacts\toolset\restore.proj : error : Could not resolve SDK "Microsoft.DotNet.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): internal, Microsoft Visual Studio Offline Packages, nuget.org
S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.DotNet.Arcade.Sdk" because directory "S:\github\aspnetcore\.dotnet\sdk\9.0.100-alpha.1.23524.8\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk" did n
ot exist.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error : You are running the 'restore' operation with an 'HTTP' source, 'http://nuget.internal.synesc.net/nuget'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
S:\github\aspnetcore\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
Build failed with exit code 1. Check errors above.
```
Renaming the `nuget.config` still works so solve it for me.

I'll happily provide everything needed, but some1 will need to tell me what's needed.
If it's not reproducable by others, it's most likley some problem with my maschine (which is a dev-machine since win10 release)
Maybe it's not even worth it chasing the ghost.

If i had to guess, i would first check the involded executable versions. primarily the one that's used / is accessing the nuget.config file. I dont have the insight who's doing that tho

**Comment by wtgodbe** [comment]
I agree that it's likely an issue with your local set-up, given that we haven't been able to track down any likely causes & I haven't seen other reports of this happening for devs. Given that you have a workaround, I'm going to close this issue.

**Comment by amuagarwal** [comment]
> Just re-tested with the same result on my maschine.
> 
> ```
> PS S:\github\aspnetcore> .\restore.cmd
> Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
> GET https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
>   Attempting to install 'sdk v9.0.100-alpha.1.23524.8' from public location.
> dotnet-install: Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
> dotnet-install: Downloaded file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
> dotnet-install: The remote and local file sizes are equal.
> dotnet-install: Extracting the archive.
> dotnet-install: Adding to current process PATH: "S:\github\aspnetcore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
> dotnet-install: Note that the script does not resolve dependencies during installation.
> dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
> dotnet-install: Installed version is 9.0.100-alpha.1.23524.8
> dotnet-install: Installation finished
> 
> Welcome to .NET 9.0!
> ---------------------
> SDK Version: 9.0.100-alpha.1.23524.8
> 
> ----------------
> Installed an ASP.NET Core HTTPS development certificate.
> To trust the certificate, run 'dotnet dev-certs https --trust'
> Learn about HTTPS: https://aka.ms/dotnet-https
> 
> ----------------
> Write your first app: https://aka.ms/dotnet-hello-world
> Find out what's new: https://aka.ms/dotnet-whats-new
> Explore documentation: https://aka.ms/dotnet-docs
> Report issues and find source on GitHub: https://github.com/dotnet/core
> Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
> --------------------------------------------------------------------------------------
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error : Could not resolve SDK "Microsoft.DotNet.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): internal, Microsoft Visual Studio Offline Packages, nuget.org
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.DotNet.Arcade.Sdk" because directory "S:\github\aspnetcore\.dotnet\sdk\9.0.100-alpha.1.23524.8\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk" did n
> ot exist.
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error : You are running the 'restore' operation with an 'HTTP' source, 'http://nuget.internal.synesc.net/nuget'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> S:\github\aspnetcore\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
> Build failed with exit code 1. Check errors above.
> ```
> 
> Renaming the `nuget.config` still works so solve it for me.
> 
> I'll happily provide everything needed, but some1 will need to tell me what's needed. If it's not reproducable by others, it's most likley some problem with my maschine (which is a dev-machine since win10 release) Maybe it's not even worth it chasing the ghost.
> 
> If i had to guess, i would first check the involded executable versions. primarily the one that's used / is accessing the nuget.config file. I dont have the insight who's doing that tho

Even i am not able to setup local env as per the document and getting the exactly same error.

**Comment by wtgodbe** [comment]
> Even i am not able to setup local env as per the document and getting the exactly same error.

Can you paste your error here? I'm curious if you're seeing the same list of sources as @trynn. Does renaming nuget.config fix it for you as well?

**Comment by amuagarwal** [comment]
> > Even i am not able to setup local env as per the document and getting the exactly same error.
> 
> Can you paste your error here? I'm curious if you're seeing the same list of sources as @trynn. Does renaming nuget.config fix it for you as well?

Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in E:\DevelopersParadise\Servers.
GET https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
  Attempting to install 'sdk v9.0.100-alpha.1.23524.8' from public location.
dotnet-install: Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
dotnet-install: Downloaded file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23524.8/dotnet-sdk-9.0.100-alpha.1.23524.8-win-x64.zip size is 270484037 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "E:\CodeSpace\Online Repos\Git\aspnetcore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 9.0.100-alpha.1.23524.8
dotnet-install: Installation finished
E:\CodeSpace\Online Repos\Git\aspnetcore\artifacts\toolset\restore.proj : error : Could not resolve SDK "Microsoft.DotN
et.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and r
esolve that message to correctly specify the SDK.
E:\CodeSpace\Online Repos\Git\aspnetcore\artifacts\toolset\restore.proj : error :   SDK resolver "Microsoft.DotNet.MSBu
ildWorkloadSdkResolver" returned null.
E:\CodeSpace\Online Repos\Git\aspnetcore\artifacts\toolset\restore.proj : error :   Unable to resolve 'Microsoft.DotNet
.Arcade.Sdk (= 9.0.0-beta.23518.2)' for '.NETStandard,Version=v0.0'. PackageSourceMapping is enabled, the following sou
rce(s) were not considered: dotnet-eng, dotnet-public, dotnet-tools, dotnet31-transport, dotnet5-transport, dotnet6-tra
nsport, dotnet7, dotnet7-transport, dotnet8, dotnet8-transport, dotnet9, dotnet9-transport, richnav.
E:\CodeSpace\Online Repos\Git\aspnetcore\artifacts\toolset\restore.proj : error :   MSB4276: The default SDK resolver f
ailed to resolve SDK "Microsoft.DotNet.Arcade.Sdk" because directory "E:\CodeSpace\Online Repos\Git\aspnetcore\.dotnet\
sdk\9.0.100-alpha.1.23524.8\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk" did not exist.
E:\CodeSpace\Online Repos\Git\aspnetcore\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arca
de.Sdk' specified could not be found.
Build failed with exit code 1. Check errors above.

I followed all the setps as define at docs/BuildFromSource.md

**Comment by wtgodbe** [comment]
I see, your problem is that `PackageSourceMapping` is enabled:

> PackageSourceMapping is enabled, the following sou
rce(s) were not considered: dotnet-eng, dotnet-public, dotnet-tools, dotnet31-transport, dotnet5-transport, dotnet6-tra
nsport, dotnet7, dotnet7-transport, dotnet8, dotnet8-transport, dotnet9, dotnet9-transport, richnav.

You'll need to disable or reconfigure that in order to restore from our feeds. You can read more here: https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping.

This is a different issue than the one described by the original post in this issue, so I'm going to close this again.
