### ISSUE TITLE
When Calling Methods From JS To DotNet

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#51100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

```js
DotNet.invokeMethodAsync("BlazorLargeSample1", "CallSomthing");
```
This Is Takes Too Many Time When My App Contains 400 classes And Many Extension Methods

### Describe the solution you'd like

```js
DotNet.invokeMethodAsync("BlazorLargeSample1", "Class1.CallSomthing");
```
Here The Time Well Be Freed To Search First For Class And Method After It
No Checking For Every Class State Methods

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what are you trying to achieve? What is taking too long in your example?
And how do you propose to speed it up?

**Comment by marinasundstrom** [comment]
@wisamidris7 I see what you mean. You would like to specify the fully-qualified name (ex. ``Class1.CallSomthing``) of the method as the argument, instead of just the method name. (?)

The method name specified in ``DotNet.invokeMethodAsync("AssemblyName", "MethodName");`` is the name of a method marked with attribute ``[JSInvokable]``. The "MethodName" argument is actually an identifier, which defaults to the method name.

The ``[JSInvokable]`` does have a constructor that allows you to specify an alternate identifier.

**Comment by wisamidris7** [comment]
no i mean why in the app scan all methods in every class contains JSInvokable

When I Count All Files That Without Counting Classes It Was 394 File
