### ISSUE TITLE
NavigationLock not working with enhanced navigation in an interactive server page component

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#51436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NavigationLock doesn't activate when navigation away using link that triggers enhanced navigation in an interactive server page component. (For instance a link in the navbar)

Only works on page refresh.

### Expected Behavior

The ``OnBeforeInternalNavigation`` should be triggered on enhanced navigation to another page.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by MackinnonBuck** [comment]
Thanks for reporting this, @marinasundstrom. To clarify, is the scenario that you have an interactive component on the page trying to block enhanced navigation? Or does your scenario only involve statically-rendered components?

**Comment by marinasundstrom** [comment]
@MackinnonBuck Ah. Forgot. It's when I'm on a page which is an interactive component. The only time the handler is being called is when doing a hard navigation, like a refresh.

**Comment by MackinnonBuck** [comment]
> It doesn't block enhanced navigations.

This is expected and by-design (since there is no interactive router), but I can see how this might not be intuitive.

We did just make a change recently that makes enhanced navigations invoke the `LocationChanged` event, though. I wonder if it would be worth extending this to also invoke location changing handlers and allow for the cancellation of enhanced navigations. This would be theoretically possible, but opens up some other questions too. For example, if an interactive runtime initiates a programmatic navigation using `NavigationManager.NavigateTo()`, should location changing handlers be invoked in all other interactive runtimes? If so, this would require updating the implementation to perform multiple extra .NET<-->JS interop calls to coordinate the cancellation of the navigation.

> The only time the handler is being called is when doing a hard navigation, like a refresh.

I'm surprised that the location changing handler runs at all in this case. Or are you referring to the `ConfirmExternalNavigation` parameter on `NavigationLock`? That actually uses the `beforeunload` event to prompt the user and doesn't rely on registering a location changing handler.

Here's the behavior of navigation events when using server-side routing today (assuming internal navigations if possible):

| Navigation type | Location changed | Location changing | Explanation/justification |
| --------------- | ---------------- | ----------------- | ------------------------- |
| `NavigationManager.NavigateTo()` (interactive) | ✅ | ✅<sup>1</sup> | Navigation is completely controlled by the interactive runtime |
| `NavigationManager.Refresh()` (interactive) | ✅ | ❌ | Causes an enhanced navigation, so is consistent with other enhanced navigation triggers |
| Browser link click | ✅ | ❌ | Causes an enhanced navigation, so is consistent with other enhanced navigation triggers |
| `NavigationManager.NavigateTo()` (SSR) | ❌ | ❌ | Navigations during SSR are treated as redirects and don't go through the normal Blazor navigation code path |
| `NavigationManager.Refresh(forceReload: true)` (interactive) | ❌ | ❌ | Consistent with clicking the "refresh" button on the browser |

And here's the behavior when using client-side routing:

| Navigation type | Location changed | Location changing | Explanation/justification |
| --------------- | ---------------- | ----------------- | ------------------------- |
| `NavigationManager.NavigateTo()` (interactive) | ✅ | ✅ | Navigation is completely controlled by the interactive runtime |
| `NavigationManager.Refresh()` (interactive) | ❌ | ❌ | Enhanced navigation cannot be performed, so this is treated the same as `NavigationManager.Refresh(forceReload: true)` |
| Browser link click | ✅ | ✅ | Navigation is handled by the interactive router |
| `NavigationManager.NavigateTo()` (SSR) | ❌ | ❌ | Navigations during SSR are treated as redirects and don't go through the normal Blazor navigation code path |
| `NavigationManager.Refresh(forceReload: true)` (interactive) | ❌ | ❌ | Consistent with clicking the "refresh" button on the browser |

I think the things here that are candidates for reconsideration are:
* Enhanced navigations invoke location changing handlers in all interactive runtimes
  * If we did this, we would need to think about whether `NavigationManager.NavigateTo()` should also allow other interactive runtimes to cancel the navigation
* To be consistent with location changing handlers not being invoked for enhanced navigations, `NavigationManager.NavigateTo()` also does _not_ invoke location changing handlers if there is no client-side router

I think if we were going to make one of the two above changes, we should make the second one. This would turn ✅<sup>1</sup> into an ❌.
That way, the rules are super clear and predictable:
* When interactive routing is used, location changing handlers always get invoked for internal navigations
* When server-side routing is used, location changing handlers are never invoked

What you think? @marinasundstrom @danroth27 @javiercn @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck Your proposal sounds good to me. I agree it makes the rules simpler. However I've no idea if it would meet the bar for something we'd do before GA, or even if we could plan to bring this as an obscure breaking change into an 8.0.x servicing release based on the idea that we're denoting it as a bug. @mkArtakMSFT

**Comment by marinasundstrom** [comment]
@MackinnonBuck Yes, it was the ``ConfirmExternalNavigation`` that was executed. But the in app navigating didn't trigger. Which is an odd behavior for an interactive page, at least. 

I assume that the ``NavigationLock`` can be implemented to work in SSR pages as well. But that is not anything I suggest as urgent for GA.

**Comment by MackinnonBuck** [comment]
@guardrex could we add some content to the "Blazor routing and navigation" docs about how the `LocationChanged` event and "location changing" handlers interact with enhanced navigation?

The table above shows the cases where each event gets called, but we probably don't need a table like that in the docs. We could summarize the behavior as:

_"When an enhanced navigation occurs, `LocationChanged` event handlers registered in interactive runtimes (i.e., Blazor Server/WebAssembly) get invoked. However, location changing handlers may or may not intercept enhanced navigations, so it's important that app logic not rely on location changing handlers being invoked reliably. For example, the user might switch to another page before an interactive runtime becomes available. In .NET 8, if server-side routing and enhanced navigation are enabled, location changing handlers will only get invoked for programmatic navigations initiated from an interactive runtime. In future .NET versions, more types of navigations (e.g., link clicks) may also invoke location changing handlers"._
