### ISSUE TITLE
NavigationManager.NavigateTo makes a GET request when navigating between server interactive pages.

### ISSUE THREAD

**Issue by XorZy** [dotnet/aspnetcore#51465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using NavigationManager.NavigateTo to navigate between two Blazor pages which both have the RenderModeInteractiveServer attribute, the browser makes a GET request to fetch the page instead of using the existing SignalR connection.

### Expected Behavior

This seems like a very inefficient approach. Indeed this will force every single page to render twice when pre-rendering is enabled. It also negatively impacts responsiveness by having to establish a new connection rather than using the existing websocket to handle routing.

It is to be expected that the first interactive page the user lands on will be rendered twice, but subsequent navigations should not make HTTP requests and trigger pre-rendering, and should instead rely on the existing SignalR connection.

This was in fact the  behavior on NET7 and below when using Blazor Server. 
The only way that  I have found to replicate this behavior on NET8 is to set the @rendermode of the Route component to InteractiveServer.

However, if my understanding is correct, by doing so you lose the ability to serve static Blazor pages, which Blazor Identity Components require.

Is this a bug or a new behavior?
If so, how to keep the ability to navigate using the SignalR connection and still be able to serve static pages?
 

### Steps To Reproduce

Use NavigationManager.NavigateTo to navigate between two pages with the RenderModeInteractiveServer attribute

### .NET Version

8.0.100-rc.2.23502.2

**Comment by javiercn** [comment]
@XorZy thanks for contacting us.

This happens because the app is using server-side routing as opposed to client-side routing, so the navigation happens via enhanced navigation.

In this model the router is not interactive and routing happens through the ASP.NET routing system. Trying to bypass that for "performance" reasons is not worth the complexity it would add to the system. If this is important to you, then use "global interactivity" (there is an option for it on the template) that will setup the app to behave in the exact same way as a Blazor Server app.

> This seems like a very inefficient approach. Indeed this will force every single page to render twice when pre-rendering is enabled. It also negatively impacts responsiveness by having to establish a new connection rather than using the existing websocket to handle routing.

For the record, this doesn't matter the vast majority of time and can be optimized away easily. The cost of the extra connection is negligible if not "free", and 2 renders aren't a problem either as 1, it is a constant factor, and 2, can be optimized away by persisting the state after the first render using persisted component state.
