### ISSUE TITLE
In Dmain Driven Design (DDD) , Should be use the IRepository contract in the application layer or in the domain layer? 

### ISSUE THREAD

**Issue by akbaramd** [dotnet/aspnetcore#51511]
I have been involved for a while now in which layer should the repository contract be, the domain or the application?

I know that the repository contract in DDD is defined inside the domain layer, but when the application layer needs a method that is not in the repository, it must tell the domain layer to add it.

And this is **against the principle of dependency inversion**, in my opinion, because **changing the logic at the level of the higher layer should not effect the lower layer**.

Because the Domain layer at the lower level does not know what the application layer needs to provide.

(If we do not consider the Generic repository).

And we have the principle that **"contracts has owned by the client side"** that the existence of a repository in the domain violates this principle because we do not use contracts in the domain layer

**Comment by martincostello** [comment]
This looks more like a general question about software engineering, rather than anything specific to ASP.NET Core.

Have you considered asking this question over at https://softwareengineering.stackexchange.com/ instead?

**Comment by akbaramd** [comment]
> This looks more like a general question about software engineering, rather than anything specific to ASP.NET Core.
> 
> Have you considered asking this question over at https://softwareengineering.stackexchange.com/ instead?

For me, this issue is more relevant at the Net Core level. And I would like to know the opinion of programmers who are in this field

**Comment by Rzassar** [comment]
I couldn't be more agree. I always put the Repository contracts in the application layer.
In other words:

Although DDD states that repository interfaces should be declared in the Domain layer, I see no benefit in declaring IRepository there:
o	As the main consumer of the repositories is the Application layer and the implementation is in the “Infrastructure” layer. Hence, the Domain layer has nothing to do with the repositories. 
o	On the other hand, I think it is far better to define them in the “Application” layer, as they may emit some business logic with it (e.g., consider ICustomerRepository has a GetTopTenCustomers(); method means that the customer repository emits some meaningful business logics, while, the business logic has nothing to do with the “Domain” layer.

BTW, I also think you should ask it in a broader area. This problem is an architectural design matter and should be asked in a more general group that encompasses all the software engineers.

**Comment by akbaramd** [comment]
> I couldn't agree more. I always put the Repository contracts in the application layer. In other words:
> 
> Although DDD states that repository interfaces should be declared in the Domain layer, I see no benefit in declaring IRepository there: o As the main consumer of the repositories is the Application layer and the implementation is in the “Infrastructure” layer. Hence, the Domain layer has nothing to do with the repositories. o On the other hand, I think it is far better to define them in the “Application” layer, as they may emit some business logic with it (e.g., consider ICustomerRepository has a GetTopTenCustomers(); method means that the customer repository emits some meaningful business logics, while, the business logic has nothing to do with the “Domain” layer.
> 
> BTW, I also think you should ask it in a broader area. This problem is an architectural design matter and should be asked in a more general group that encompasses all the software engineers.

I agree with your opinion; in fact, that was the reason for my question. But isn't this GetTop10Customer domain logic? In DDD, we have to separate the domain logic from the application. But the same example that you mentioned, in my opinion, is domain logic and no application logic is involved in it.
