### ISSUE TITLE
In Blazor WebApp with auto render mode, how to resolve the pages or routeData from wasm?

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#51518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying the web app with auto mode. I need two part of layout, one is ssr mode, the other is auto.

The ssr party is alright, but I meeting some issue with the auto party.

I need a inactive layout componet. I know the issue that the Body of layout can't be passed to auto compontents so I want to rebuild the Body with route data. However I can't find the way to achieve this. Are there anyone could help?

Thank you for the great work.

### .NET Version

8.0.0 rc2

**Comment by javiercn** [comment]
@ElderJames thanks for contacting us.

Could you clarify a bit more what you are trying to achieve? Maybe with an example?

**Comment by ElderJames** [comment]
Hello @javiercn , here is my example https://github.com/ElderJames/BlazorAutoLayout , you can click the `Admin`  link in the upper right corner to connect. 

Here are my implementation steps:

- I create a wrapper component to achieve the [auto rendered layout componet](https://github.com/ElderJames/BlazorAutoLayout/blob/master/LayoutDemo/LayoutDemo.Client/Pages/WrapperComponent.razor) 
- Get the [RouteData from cascading value](https://github.com/ElderJames/BlazorAutoLayout/blob/master/LayoutDemo/LayoutDemo/Components/Routes.razor#L3C27-L3C27) which I pass in the router component.
- Transfer to a Dto [`RouteDataInfo`](https://github.com/ElderJames/BlazorAutoLayout/blob/master/LayoutDemo/LayoutDemo.Client/Pages/WrapperComponent.razor#L71C2-L72C53) because the `PageType` property is `Type` type and can't be serialized.
- Pass the RouteDataInfo to the wrapper component and [rebuild the RouteData by reflection](https://github.com/ElderJames/BlazorAutoLayout/blob/master/LayoutDemo/LayoutDemo.Client/RouteDataInfo.cs#L20C1-L37C10), and render the page component.

This is a very tortuous process, I want to ask is there a more elegant and direct way for me to present the page in an interactive layout?

**Comment by javiercn** [comment]
@ElderJames Am I correct in understanding that the challenge you are facing here is with the `@Body`, since your client layout doesn't invoke `@body`.

You might be able to do this a bit differently. If in your app component, you resolve `https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/IRoutingStateProvider.cs` you get access the to the page type, and can look up the layout, and then set the render mode for the `<Routes>` component instead.

Having different layouts and those layouts requiring different render modes, is not something we've anticipated. Support for that might be something that we need to build within the router itself.

Otherwise, your solution is the best approach possible right now. The router in that case would need to persist the route data to the client, retrieve it, and essentially do Assembly.Load("Assembly").GetType("TypeName") and build the render fragment passed to `@body` with that.

**Comment by ElderJames** [comment]
Thanks for your reply @javiercn

Could we inject the `IRoutingStateProvider` and get the current PageType currently?

**Comment by ElderJames** [comment]
I have tried and it can't resolve in wasm.

```
Error: One or more errors occurred. (Cannot provide a value for property 'RoutingState' on type 'BlazorApp.Client.LayoutWarpper'. There is no registered service of type 'Microsoft.AspNetCore.Components.Routing.IRoutingStateProvider'.)
```

**Comment by javiercn** [comment]
@ElderJames You can't use EndpointRoutingStateProvider directly, but you can create your own service on the server that wraps it (inject it in the constructor) and serializes the information to make it available later on in the client. Note that RouteData is not directly serializable, as we don't support serializing the type (It is the same for any piece of data that crosses boundaries).
