### ISSUE TITLE
AllowAnonymous should be explicitly defined on Blazor Identity pages

### ISSUE THREAD

**Issue by los93sol** [dotnet/aspnetcore#51592]
I routinely put an _Imports.razor at the root of my projects with @attribute [Authorize] to enforce authorization on all pages, but because @attribute [AllowAnonymous] is not explicitly defined on the razor pages in Pages/Account that ends up breaking the pages and requires me to go specify it manually.  If AllowAnonymous was defined on those pages explicitly it would not be an issue.  Interestingly, creating Pages/Account/_Imports.razor with @attribute [AllowAnonymous] breaks the pages in Pages/Account/Manage because the @attribute [Authorize] there ends up not being applied at all.  Even manually defining it on individual pages does not work there.  I'm unclear if that's by design or a bug in the framework, but it is definitely unexpected as it appears to conflict with how MVC behaves when doing similar on a controller vs an action within that controller

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. While your point is valid, we haven't seen many customers express concerns regarding the current structure of these pages. It is our goal to keep the templates as clean as possible, and that's why we didn't include any of these attributes, given that they would be redundant in current structure of the template.
