### ISSUE TITLE
AuthorizeRouteView not showing Authorizing child content

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#51642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
In .net 8 blazor Web App, when you set Authorizing on AuthorizeRouteView showing some text, loading, for example, this text will not be seen on screen at any time

### Expected Behavior

Child content must be shown when authentication is in progress. Now you just can see the page youhad requested.

### Steps To Reproduce

Just insert this on the RC2 Routes.razor

```csharp
<Authorizing>
    <span>--- Loading ---</span>
</Authorizing>
```

### .NET Version

8.0.100-rc.2.23502.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
If you happen to use server side rendering, then the user is already authorized before the component is being rendered, when the page has `AuthorizedAttribute`.
If this is not the scenario you experience, please provide a minimal repro project so that we can investigate this further.

**Comment by CrahunGit** [comment]
Yes, It works like this. But If I take the [Authorize] attribute off the child content will not be shown anyway. Even If I put prerender to false.

**Comment by mkArtakMSFT** [comment]
Thanks for additional details. This comes down to the fact that by the time the request hits the server, it is already authorized, and there is no need for the `Authorizing` content to be shown.
