### ISSUE TITLE
ASP .NET 8 RC2 Routing & UseStaticFiles

### ISSUE THREAD

**Issue by 1619digital** [dotnet/aspnetcore#51677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is the same bug as #50707 , except when using an Additional Assembly. That is, with an optional parameter in the route, the app is unusable, because all requests to static assets get routed the to the blazor page, not the static asset.

Changing the page directive from `@page "/{PageName?}"` to `@page "/"` fixes the issue.

I have tried this on rc2 and nightly.

### Steps To Reproduce

repository here - [https://github.com/OpenEnergyGroup/BlazorApp4](https://github.com/OpenEnergyGroup/BlazorApp4)

### .NET Version

8.0.100-rtm.23526.1

**Comment by javiercn** [comment]
@1619digital thanks for contacting us.

The behavior you are observing is by design. `/{PageName?}` will match the root `/` and any other URL that has a single segment since you have an unconstrained parameter on it, and at that point static files will not do anything.

You need to use the `{page:nonfile?}` constraint if you want to avoid matching URLs that look like a file.

**Comment by 1619digital** [comment]
Hi - thanks very much - is it the expected design that static files are lower down in priority than optional routes? That's not be behaviour we see with our 7.0 app, where all static files are matched before trying to match a route.

You're fix does work though (although wouldn't, I think, if you had an extensionless file) - I suggest this issue could be added to breaking changes.

**Comment by mkArtakMSFT** [comment]
We don't plan to document this as a breaking-change, as Blazor Web is a somewhat new model, and this behavior is unique to Blazor Web.
