### ISSUE TITLE
Different scoped services lifetime in Blazor Web App with Server render mode

### ISSUE THREAD

**Issue by christophe-mommer** [dotnet/aspnetcore#51768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Scoped services in Blazor Web App with rendermode server behave differently if interactivity is global or not

Before .NET 8, with Blazor Server, a scoped service was a kind of singleton for an user session. We have the same behavior for Blazor Web App with Server render mode and global interactivity (meaning, the websocket bridge is open at the beginning of the app and never closed)

But, when switching to Blazor Web App with per components interactivity, even if I set both my components as interactive on server, a service declared as scoped is recreated on navigating, BUT the websocket bridge remains open, since I navigate from ComponentA to ComponentB and both are set as interactive.

It might be more a question than a bug, but is this the expected behavior when both components are interactive?
Shouldn't they share the same scoped service instance?

It's ok that the service is recreated if components are server "static" (no interactivity) or when navigating from an interactive component to a "static" component, since it's a kind of new request (no WS bridge involved).

### Steps To Reproduce

Create two Blazor Web App with Server rendermode: one with global interactivity and the other one with component interactivity. 
Create a service and register it as scoped in both apps.
Create two components that uses the service. On the "per component interactivity" app, mark both component as InteractiveServer
Inject the service in both components and navigate. If you put a breakpoint (or a console.writeline) in the service ctor, you can see that it's recreated in the per-component interactivity app

### .NET Version

8.0 rc2

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @christophe-mommer.

The behavior you're experiencing is by design. When you enable "per-component" interactivity, server-side routing gets used. This means that the router still has a static server render mode, so each navigation causes a prerender to occur. In turn, this causes the interactive component to be rendered twice - once during prerendering and once after getting enabled for interactivity. The prerendered version of the component uses the request's DI scope, but the interactive component uses the circuit's, hence the behavior you're observing. If you disable prerendering for the component by giving it a `new InteractiveServerRenderMode(prerender: false)` render mode, you'll notice that the component only get created once.

Hope this helps!

**Comment by christophe-mommer** [comment]
Thank you for the valuable information @MackinnonBuck!
Since I'm currently recording a course on Blazor with .NET 8, I wanna be sure I didn't told bad informations.
So indeed, when disabling prereding, scoped service is created only once.
What I don't get however is: why, if prerendering is enabled, in the second lifecycle of the component (the interactive one), I don't get the scoped service instance like it was in Blazor Server before.

I created a small sample here: https://github.com/christophe-mommer/BlazorScopedServices_Demo

When I set the rendermode with prerender, I still have the console trace of service created when switching component. Shouldn't I only have it one for the circuit, since it's not closed?
