### ISSUE TITLE
CodeSpace fails to build Dotnet

### ISSUE THREAD

**Issue by danirzv** [dotnet/aspnetcore#51848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've forked from dotnet/aspnetcore then made a branch of main and opened it in Github-Codespace, i did nothing more but `dotnet build` and `dotnet test` failing by message as blow:

> /workspaces/aspnetcore/AspNetCore.sln(11360): Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{1542DC58-1836-4191-A9C5-51D1716D2543}" is listed as being nested under project "{05A169C7-4F20-4516-B10A-B13C5649D346}", but does not exist in the solution.

### Expected Behavior

I've expected Build and test work fine

### Steps To Reproduce

1. Fork from dotnet/aspnetcore
2. Create a branch
3. Open in codespaces
4. run `dotnet build` or `dotnet test`

### Exceptions (if any)

MSB5023

### .NET Version

9.0.100-alpha.1.23530.11

**Comment by mitchdenny** [comment]
What happens if you follow the building from source instructions: 

https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md

There is no expectation that our repository will build using just ```dotnet build```.

**Comment by danirzv** [comment]
> What happens if you follow the building from source instructions:
> 
> https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md
> 
> There is no expectation that our repository will build using just `dotnet build`.

it's just exactly same instruction the page you have mentioned has on `codespaces-on-github` section
https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#codespaces-on-github

**Comment by danirzv** [comment]
Any updates?

**Comment by captainsafia** [comment]
@danirzv As @mitchdenny mentioned, we don't generally recommend running a `dotnet build` at the **root** of the repo when working with the codebase. The instructions in the section that you referenced should be a little bit clearer that `dotnet build` and `dotnet test` can only be used within _specific projects_.

That aside, it does look like our top-level `AspNetCore.sln` file has become inconsistent with the repo since we rely more heavily on the individual `.slnf` files within the repo.

**Comment by mitchdenny** [comment]
Thanks Sofia

**Comment by danirzv** [comment]
@captainsafia thank you for your PR and description
