### ISSUE TITLE
CreateInboundActivityHandler override in .net 8 RC2 not being called

### ISSUE THREAD

**Issue by Thomas-Explc** [dotnet/aspnetcore#51934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CreateInboundActivityHandler introduced in .net 8 preview 3, as seen in the dotnet blog post linked below, does not appear to work in .net 8 release candidate 2.

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/#monitor-blazor-server-circuit-activity

Within the same circuit handler the overrides for circuit open, circuit closed, connection up and connection down work as expected.

Are there any situations which would cause the CreateInboundActivityHandler to not be called when UI events fire in an interactive server component that is functioning as expected?

### Expected Behavior

The CreateInboundActivityHandler is called when any user interface events within a blazor component are activated, e.g. the changing of text, the click of a button.

### Steps To Reproduce

Repo: https://github.com/Thomas-Explc/CreateInboundActivityHandler_Bug_Example

Go to counter page, use the button and enter test in the input field, no UI events cause function to fire.

Logger in CreateInboundActivityHandler is not hit, no breakpoints within that function are reached.

### Exceptions (if any)

None, issue is logical.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Visual Studio 2022, 17.8.0 Preview 6.0.

**Comment by MackinnonBuck** [comment]
Confirmed this is a bug, specifically for Blazor Web Apps. It's caused by the fact that in Blazor Web, the initial circuit handlers array is empty [by the time the inbound activity dispatcher gets built](https://github.com/dotnet/aspnetcore/blob/099783acba672ad980b3907f84799ec03a159cb2/src/Components/Server/src/Circuits/CircuitHost.cs#L73). However, even after the Blazor Web circuit handlers are [retrieved later from DI](https://github.com/dotnet/aspnetcore/blob/099783acba672ad980b3907f84799ec03a159cb2/src/Components/Server/src/Circuits/CircuitHost.cs#L765), we don't build the inbound activity handler.

The easy fix would be to call `BuildInboundActivityDispatcher` after the `_circuitHandlers` are retrieved for Blazor Web.

**Comment by hulkbulgur** [comment]
This works now, but when deploying the app to IIS, the CreateInboundActivityHandler method still does not seem to be executed. Is it possible that the implemented fix doesn't help when hosting on IIS?
