### ISSUE TITLE
NavigationManager.NavigateTo("urlInOtherDomain") causes Uncaught (in promise) WebSocket is not in the OPEN state in Firefox

### ISSUE THREAD

**Issue by bc3** [dotnet/aspnetcore#51936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

existing item: #19050

let this simple piece of code in a blazor server app

```
@page "/"
@inject NavigationManager NavManager

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<button onclick="@navigate">direct with js NavigationManager</button>

@code{
    public void navigate() {
        NavManager.NavigateTo("https://www.google.com");
    }
}

```

it runs fine in chrome, when you run it in firefox, you get exception: Uncaught (in promise) WebSocket is not in the OPEN state

https://github.com/dotnet/aspnetcore/assets/2547576/58f6118d-f070-479f-b294-2dfc9f969f24

it is already described in https://github.com/dotnet/aspnetcore/issues/19050 and closed  in https://github.com/dotnet/aspnetcore/pull/23224, but the problem still remains

### Expected Behavior

it just goes to google without the socketexception, this is a simple version of our code. In our main project it is used to downlad a CSV file, and now the user always sees blazor disconnect.

### Steps To Reproduce

use code snippet

### Exceptions (if any)

Uncaught (in promise) WebSocket is not in the OPEN state

### .NET Version

7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is because the `onBeforeUnload` event is not reliable. The framework listens to that event and uses that as a signal to disconnect the circuit. However, because of the unreliability nature of that event, sometimes it doesn't fire and you end up seeing the exception that you've observed.
That said, it's safe to ignore that exception. We're closing this as the framework has no control over that event and it's a browser behavior: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#usage_notes
