### ISSUE TITLE
CascadingParameter  set in MainLayout.razor doesn't work as expected in .NET 8

### ISSUE THREAD

**Issue by ruikaifeng** [dotnet/aspnetcore#51955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The the cascading parameters work properly only during  prerender:
![11 9 1](https://github.com/dotnet/aspnetcore/assets/100664890/8a1c75dc-fb2d-4d54-bb89-521ba397ea84)

I found a workaround that set rendermode to InteractiveServer gobally in app.razor

<Routes @rendermode="RenderMode.InteractiveServer" />

![11 9 2](https://github.com/dotnet/aspnetcore/assets/100664890/1e83b867-846d-4763-b720-83ac4f7b59f6)

### Expected Behavior

The the cascading parameters work properly without setting rendermode to InteractiveServer gobally

### Steps To Reproduce

codes in Razor Components:
```
@attribute [RenderModeInteractiveServer]

<h1>Themed Counter</h1>
<p>Current count: @currentCount</p>
<p>
    <button class="btn @(ThemeInfo is not null ? ThemeInfo.ButtonClass : string.Empty)"
            @onclick="IncrementCount">
        Increment Counter (Themed)
    </button>
</p>

@code {
    private int currentCount = 0;       

    [CascadingParameter]
    // this themeinfo is only cascaded properly during prerender
    protected ThemeInfo? ThemeInfo { get; set; } 

    private void IncrementCount()
    {
        currentCount++;
    }
    protected override void OnInitialized()
    {
        base.OnInitialized();
    }
}
```

mainlayout:
```
@inherits LayoutComponentBase


<div class="page">
    <div class="sidebar">
        <NavMenu />
    </div>

    <main>
        <div class="top-row px-4">
            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
        </div>

        <CascadingValue Value="@theme" >
            <article class="content px-4">
                @Body
            </article>
        </CascadingValue>
    </main>
</div>

@code {
    private ThemeInfo theme = new ThemeInfo { ButtonClass = "btn-success" };
}
```

### .NET Version

8.0.100-rc.2.23502.2

**Comment by SteveSandersonMS** [comment]
Cascading parameters don't cross rendermode boundaries. This is because:

1. It would break most existing apps if the framework tried to serialize them, because in general one should not expect their values to be serializable.
2. Top-level cascading parameters are often used as a DI alternative, and so you should expect to have different data on different hosting platforms. For example, in static SSR there's a cascading `HttpContext`. It would not make sense to serialize that out and rehydrate it for interactive rendering, since at that time there's either a different HTTP context or even no HTTP context at all.

Of course, this will be covered in the .NET 8 docs when they are published.

As a solution, you should use `builder.Services.AddCascadingParameter` (including in your `.Client` project if you're also using WebAssembly) to register cascading values, so your app supplies a value for each hosting platform. Then a value will always be available, and it's your responsibility as the app developer to determine that value for each hosting platform.

**Comment by guardrex** [comment]
Just to let you know, @ruikaifeng, docs will cover this after https://github.com/dotnet/AspNetCore.Docs/pull/30958 merges, which will be later this afternoon.
