### ISSUE TITLE
Blazor Web app with RenderMode.InteractiveWebAssembly requires services to be registered in App in addition to App.Client

### ISSUE THREAD

**Issue by bradbrowne** [dotnet/aspnetcore#52155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the first page that is loaded by the .NET 8 Blazor Web app requires a service to be registered, then it needs to be registered in the App and App.Client projects, as follows:

```
builder.Services.AddSingleton<TestViewModel>();
```

If it is not in the first page that is loaded then it will work on subsequent pages, but the initial page needs to have services in both App and App.Client projects.

If it does not, then you will get this error:

```
Cannot provide a value for property 'TestViewModel' on type 'Test.App.Client.Views.TestView'. 
There is no registered service of type 'Test.App.Client.ViewModels.TestViewModel'.
```

### Expected Behavior

I expect that I should only be required to register the services that are required by my WebAssembly components in the App.Client project.

I would also expect that I could successfully load initial pages that contain WebAssembly components that are not registered in the App, and would only require them to be registered in the App.Client project.

### Steps To Reproduce

I have created a minimal repo at the following location so that you can reproduce the behaviour:

https://github.com/mapdojo/Test.App

The `Test.App` project has the following line commented out that is required for the application to work:

```
// FIXME: Why is this required?
// builder.Services.AddSingleton<TestViewModel>();
```

Running the application with `dotnet watch` and then navigating to the http://localhost:5001/ page will show the error.  Uncommenting the above line will make the app work, and you can also make it work by starting on a different page.

### Exceptions (if any)

If you start the application on a different page e.g., http://localhost:5001/counter, then the application will work and you can navigate to the http://localhost:5001/ page in that session and it will work ... but if you refresh on that page it will give you the following error as before:

```
Cannot provide a value for property 'TestViewModel' on type 'Test.App.Client.Views.TestView'. 
There is no registered service of type 'Test.App.Client.ViewModels.TestViewModel'.
```

### .NET Version

8.0.100

**Comment by Andrzej-W** [comment]
Hello @bradbrowne this is expected behaviour in .NET 8. In .NET 7 Balzor WASM application was downloaded to the browser without any prerendering on the server. In .NET 8 it is prerendered by default. To prerender this page server has to run code located in App.Client project.

If you're in a hurry, read this:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#client-side-services-fail-to-resolve-during-prerendering

However, to really understand the entire process, I suggest reading these two articles from start to finish:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0

If you think your problem has been solved, remember to close this issue.

**Comment by bradbrowne** [comment]
Hi @Andrzej-W, thank you for providing the explanation and relevant documentation, I can see that I was making some assumptions about how this works that I will need to modify!  I will need to figure out a way to register dummy services on the Server that are not required for pre-rendering but will be required by the Client ... or stick with the existing .NET 7 non-pre-rendered approach for the time being.

Thank you again for your swift and informative reply!
