### ISSUE TITLE
dotnet new webapi template : package reference Swashbuckle.AspNetCore version isn't the last one

### ISSUE THREAD

**Issue by diplomegalo** [dotnet/aspnetcore#52246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Project created with dotnet new cli reference an old version of Swashbuckle.AspNetCore. 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0,net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>web_8</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

</Project>
```

### Expected Behavior

The csproj should reference the version 6.5.0 : 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0,net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>web_8</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" /><!-- should reference the 6.5.0 version -->
  </ItemGroup>

</Project>
```

### Steps To Reproduce

dotnet new webapi

### .NET Version

8.0.100

### Anything else?

I suggest you to change the [SwashbuckleAspNetCoreVersion](https://github.com/dotnet/aspnetcore/blob/5fa9760a727556292ae2b43880e30a24c872c140/eng/Versions.props#L326) value to 6.5.0.

**Comment by captainsafia** [comment]
@diplomegalo Thanks for opening this issue!

We typically upgrade the Swashbuckle.AspNetCore version after we've had the chance to test with the new iteration. We weren't able to get to this the last time Swashbuckle.AspNetCore was updated.

Updating the version will only affect .NET 9 and beyond at this point, so we'll wait to here more feedback on the value of this before we do so. Outside that, it's fairly easy for developers to upgrade the version themselves so this is low-pri.

**Comment by RandomBuffer** [comment]
Just noting this here that I tried upgrading to **Swashbuckle.AspNetCore** 6.5.0 to fix **DateOnly** serialisation fixed in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2319 but the Swagger schema broke (notice in WUI) so I had to revert back to **Swashbuckle.AspNetCore** 6.4.0.

**Test**
1. Create a new Controller API project using the default template.
2. Upgrade to **Swashbuckle.AspNetCore** 6.5.0.
3. Enable **IncludeXmlComments**.
4. Run and notice **WeatherForecast** no longer shows up in the Swagger schema section.

dotnet --version
`8.0.200`

**Comment by RandomBuffer** [comment]
As an experiment tried upgrading to **Swashbuckle.AspNetCore** 6.5.0 to fix **DateOnly** serialisation which was fixed in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2319 but the **Swagger.json** broke with missing elements so had to revert back to **Swashbuckle.AspNetCore** 6.4.0.

**Test**
1. Create a new Controller API project using the default template.
2. Upgrade to **Swashbuckle.AspNetCore** 6.5.0.
3. Enable **IncludeXmlComments**.
4. Run project and notice **WeatherForecast** no longer shows up in the SwaggerUI schema section.

**dotnet --version**
`8.0.200`

**Comment by RandomBuffer** [comment]
Tried upgrading to  **Swashbuckle.AspNetCore** 6.5.0 to fix DateOnly serialisation but it breaks **Swagger.json** as mentioned in this [Swashbuckle comment](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2771#issuecomment-2008967940)

**dotnet --version**
`8.0.200`

**Comment by captainsafia** [comment]
@RandomBuffer Take a look at https://github.com/dotnet/aspnetcore/issues/54599 for our future plans in the OpenAPI effort.

I'm going to close this issue as we plan on removing Swashbuckle.AspNetCore from the templates.

As for the immediate problem you are running into with `DateOnly`, perhaps you can use a custom `SchemaFilter` to override the schema generated for `DateOnly` types?

**Comment by RandomBuffer** [comment]
thanks @captainsafia yeah have read that plan, super exciting.
