### ISSUE TITLE
Signing keys not retrieved from authority when using AddJwtBearer

### ISSUE THREAD

**Issue by hughnatt** [dotnet/aspnetcore#52296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In NET 7, specifying the `JwtBearerOptions.Authority`  in `AddJwtBearer` would query the configuration (issuer and signing keys) from the `.well-known/openid-configuration` endpoint of the authority server.

```csharp
builder.Services
    .AddAuthentication()
    .AddJwtBearer(options => 
    {
        options.Authority = "<AUTHORITY_URL>";
    });
```

This is not the case anymore in NET 8.

I believe the issue comes from those lines in `JwtBearerHandler.cs` introduced in this [PR](https://github.com/dotnet/aspnetcore/pull/49541) https://github.com/dotnet/aspnetcore/blob/c187bb1dc18de5b5b0afcfef0c7c14dd67415c61/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L244-L260

We basically never get into the else, as the default `ConfigurationManager<...>` inherits  `BaseConfigurationManager`

### Expected Behavior

Issuer and public signing keys should be retrieved from the Authority server discovery endpoint, allowing for minimal configuration on the client side.

### Steps To Reproduce

Minimal repro here: https://github.com/hughnatt/aspnetcore-issue-jwtbearer-configuration

### .NET Version

8.0.100

**Comment by eirikurharaldsson** [comment]
Same issue here: https://github.com/dotnet/aspnetcore/issues/52330
We are unable to upgrade solutions to .NET 8 because of this.

**Comment by hughnatt** [comment]
In our case, I've created a temporary work-around using a custom _somewhat hardcoded_ ConfigurationManager https://gist.github.com/hughnatt/116059eeff449657d614f24967aff9a9

You can specify this custom configuration manager in the options when adding your authentication scheme.

`options.ConfigurationManager = new CustomConfigurationManager(authorityUrl)`

**Comment by hughnatt** [comment]
@keegan-caruso Can you maybe give us some feedback on this ? That would be very much appreciated 😃

**Comment by LarsWesselius** [comment]
Related, probably same root cause is https://github.com/dotnet/aspnetcore/issues/52388 where the token will be considered invalid at all times. Unrelated possibly to the ConfigurationManager but I suspect the OpenIdConnect package is causing this too. This is causing my company to have to revert to .NET 7 (where it works just fine)

**Comment by kieranbenton** [comment]
Getting the same here, this is a proper footgun when upgrading - its taken 2 days to figure it out. 

I recognise the hard work that goes into .NET in general, but given the highlighted focus on .NET 8 an the authentication/authorisation story how has this possibly made its way though testing? We're literally just authenticating a JWT token against IdentityServer4 - not a weird configuration at all. Is there a gap we can help with on improving the test coverage on upgrades of these packages?

Going to try the workaround for now to get us moving.

**Comment by hesham-amer** [comment]
Has there been an update or a fix on this topic?  Is this a confired general .NET8 Issue? We're running into the same issue and unsure if there's a fix

**Comment by halter73** [comment]
Signing keys and issuer is downloaded from the authority, but the way it works by default changed in .NET 8 as part of switching from using `JwtSecurityToken` to using `JsonWebToken` by default. https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events

`JwtBearerOptions.Configuration` is initialized using the configured `Authority` [by JwtBearerPostConfigureOptions.cs](https://github.com/dotnet/aspnetcore/blob/3e168fe85e2330621ed12d9c9524c80e0f743dc6/src/Security/Authentication/JwtBearer/src/JwtBearerPostConfigureOptions.cs). The call to `ConfigurationManager.GetConfigurationMangerAsync` has simply moved [into JsonWebTokenHandler here.](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/131d476988d2367a44724516e32e9fdc49521f6a/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L646)

I tried out the repro app at [hughnatt/aspnetcore-issue-jwtbearer-configuration](https://github.com/hughnatt/aspnetcore-issue-jwtbearer-configuration), and sure enough I see `"/.well-known/openid-configuration endpoint called."` written to stdout from the `DiscoveryController`. I did have to send a valid JWT token though since the metadata is grabbed lazily.

```
> curl "http://localhost:5104/" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
```
