### ISSUE TITLE
[.NET 8] Using attribute [Authorize] is bugged when refreshing page (shows HTTP ERROR 401 despite being logged in)

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#52317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using Blazor RenderMode InteractiveServer globally and Prerender turned off. I also use JWT authentication (not sure how it behaves with other authentication methods).

When navigating with a href clicks it works fine authenticating the user and showing authorized page. But when the same user refreshes the page with F5, it shows HTTP ERROR 401, like this:

![71f6a2805720bc6e30fd8bc27805812a](https://github.com/dotnet/aspnetcore/assets/10290906/8dc35fab-1f6b-4fe2-8ac5-bc31e0d57819)

A **minimal reproducable project** is made for you to see the issue.

### Expected Behavior

I expect the authenticated & authorized user to keep seeing the Authorized content inside the blazor page component after a F5 page refresh.

### Steps To Reproduce

1. Download the repo: [Minimalistic project - Github](https://github.com/DM-98/BlazorApp2-AuthorizationIssueRepro)
   or quickly Git Bash this:
   `git clone https://github.com/DM-98/BlazorApp2-AuthorizationIssueRepro`
3. Open Package Manager Console and run "Update-Database" 
   _(which makes a new database called BlazorApp2-AuthorizationBugRepro)_
5. Start with(out) debugging
6. Register a user and then Login
7. Navigate to [Authorize]'d page only and press F5

### .NET Version

8.0.100

**Comment by surayya-MS** [comment]
Thanks for contacting us, @DM-98 !
The authentication state provider the app defined is only used within Blazor and is not integrated with the ASP.NET Core authentication system. During prerendering, Blazor Web respects the metadata defined on the page and uses the ASP.NET Core authentication system to determine if the user is authenticated. Since you haven't integrated your custom AuthenticationStateProvider with the built-in authentication system, when you navigate from one page to the other, only your auth provider is used, (which works), but when you refresh the page, your provider is not involved in the auth decision, and thats why the page doesn't get rendered.
 
To address this, it's better if you perform the authentication within the ASP.NET Core auth system and your authentication state provider only takes care of reflecting that state. For an example on how to do this, check the authentication state provider in the Blazor Web template with individual user accounts.

**Comment by rezamohammad** [comment]
Hello,
 if possible, write a sample code for example
Thankful

**Comment by rezamohammad** [comment]
Hello, @surayya-MS
if possible, write a sample code for example
Thankful

**Comment by rezamohammad** [comment]
hi @DM-98 
    https://github.com/dotnet/aspnetcore/issues/52063#issuecomment-1817420640


Well, I found a workaround by:
define following class and register it where server initializes

```
public class BlazorAuthorizationMiddlewareResultHandler : IAuthorizationMiddlewareResultHandler
{
    public Task HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
    {
        return next(context);
    }
}
```
and handler:

`services.AddSingleton<IAuthorizationMiddlewareResultHandler, BlazorAuthorizationMiddlewareResultHandler>();`
This class will prevent redirection from the new .net 8 authorization middleware response.
The problem still exists, but we can at least we can use .NET 8 new feature the way we used to in Blazor and .NET 7.

You may need to separate endpoint routing other than blazor routes since it basically renders serverside authorization (via .AddAuthentication(...).AddJwtBearer(...)) ineffective.

hope this helps, enjoy .net 8. while the team fixes the problem.

**Comment by dmm-l-mediehus** [comment]
@rezamohammad The workaround works flawlessly, thanks.

**Comment by sh-jthorpe** [comment]
> Thanks for contacting us, @DM-98 ! The authentication state provider the app defined is only used within Blazor and is not integrated with the ASP.NET Core authentication system. During prerendering, Blazor Web respects the metadata defined on the page and uses the ASP.NET Core authentication system to determine if the user is authenticated. Since you haven't integrated your custom AuthenticationStateProvider with the built-in authentication system, when you navigate from one page to the other, only your auth provider is used, (which works), but when you refresh the page, your provider is not involved in the auth decision, and thats why the page doesn't get rendered.
> 
> To address this, it's better if you perform the authentication within the ASP.NET Core auth system and your authentication state provider only takes care of reflecting that state. For an example on how to do this, check the authentication state provider in the Blazor Web template with individual user accounts.

Hi @surayya-MS, i've logged https://github.com/dotnet/aspnetcore/issues/52586 as this issue applies to MS Entra ID auth as well, and in that scenario there's no authentication state provider for us to configure.

**Comment by Stefan13-13** [comment]
@rezamohammad Thank you, I have the same issue.
How do I register the class you shared?
Thanks!

**Comment by Stefan13-13** [comment]
For me the workaround by @rezamohammad  does not work.
The error goes away, but now I can view my page with the `@attribute [Authorize(Policy = MyPolicy)]` while I'm not autorized.
