### ISSUE TITLE
Static files can't be served from the root when a Razor page component matches that route with param

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#52320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

**TL;DR;** Static files can't be served from the root when a Razor page component matches that route.

Consider that you are building a CMS. You have Page component that is supposed to display page content, so you want to catch the "permalink" like so:

``@page "/{permalink}"``

That is all fine so far. The component gets hit upon navigating to: http://localhost:5000/this-is-a-test.

The problem with this path seems to have precedence over static file. So it catches all routes and paths, including static files.

Because of this static files can't be served from the root.

### Describe the solution you'd like

Guidance in how to solve such a situation. Since I imagine this is a common case for larger sites to want to use not only simple parameters, but also for wildcards.

As a solution in my case, I guess that I could put resources in sub-folders in the wwwroot-folder. That would work in this instance, but not for wildcards params.

**Comment by javiercn** [comment]
@marinasundstrom thanks for contacting us.

This is by design; the route is capturing any path with one segment. The same behavior happens on Razor pages or controllers, it didn't happen in old Blazor Server because there was a catch-all route with. There's a `:nonfile` constraint for it. 

The reason this didn't happen in previous versions of Blazor is because MapFallback* use a route `{**path:nonfile}` in their default overloads

**Comment by marinasundstrom** [comment]
@javiercn OK. Good to know! I will try the constraint. 

Thank you so much!
