### ISSUE TITLE
net8 packages (e.g. Microsoft.Extensions.Http.Polly 8.0.0) target netstandard2.0 (and other various frameworks), but according to Microsoft they can only be used on net8

### ISSUE THREAD

**Issue by jjanuszkiewicz** [dotnet/aspnetcore#52332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Package `Microsoft.Extensions.Http.Polly`, version 8.0.0, targets `netstandard2.0`. However, Microsoft has stated multiple times ([example1](https://github.com/dotnet/aspnetcore/issues/45278#issuecomment-1327903662), [example2](https://github.com/dotnet/aspnetcore/issues/45149#issuecomment-1320517662), [example3](https://github.com/NLog/NLog.Extensions.Logging/issues/642#issuecomment-1322460925)) that MS package versions must match the app runtime version where they are used.

As is, this package can be installed in apps targeting any framework and may result in an invalid runtime behaviour, but based on the above linked comments I think it should target `net8` (and 9.* should target `net9` and so on).

Is this something that can be done for this and other similar packages? Right now all the burden of ensuring correct dependency versions is shifted onto app developers, but it seems it could be solved with a stricter framework targeting.

**Comment by wtgodbe** [comment]
@joperezr @eerhardt who owns Polly these days? Can you please move it to the appropriate area path?

**Comment by eerhardt** [comment]
> However, Microsoft has stated multiple times (https://github.com/dotnet/aspnetcore/issues/45278#issuecomment-1327903662, https://github.com/dotnet/aspnetcore/issues/45149#issuecomment-1320517662, https://github.com/NLog/NLog.Extensions.Logging/issues/642#issuecomment-1322460925) that MS package versions must match the app runtime version where they are used.

I believe this only applies to `Microsoft.AspNetCore.*` packages, and not to `Microsoft.Extensions.*` packages. `Microsoft.Extensions` packages are intended to support `netstandard2.0`.

See https://github.com/aspnet/Announcements/issues/324. I don't believe our stance has changed on that.

As for the HealthChecks package ([example1](https://github.com/dotnet/aspnetcore/issues/45278#issuecomment-1327903662), I think that is a bug (note the issue is still open). If HealthChecks supports netstandard2.0, it should work on any platform that supports netstandard2.0.
