### ISSUE TITLE
Implement JavaScript click event functions for easy use in Blazor

### ISSUE THREAD

**Issue by AmirMahdyJebreily** [dotnet/aspnetcore#52349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

it is currently not possible to create a modal in Blazor without using pure vanilla JavaScript methods that the parent element of the modal is created in the display mode and disappears in the hidden mode!
Unfortunately.

### Describe the solution you'd like

Direct support for JavaScript click event functions like `event.preventDefault();` and `event.stopImmediatePropagation()` from libraries like alpine.js and vue.js.

### Additional context

As someone who has been working on the front end for many years, I say that Blazer has performed weaker than other js libraries in event handling...

**Comment by javiercn** [comment]
@AmirMahdyJebreily thanks for contacting us.

You can use `@onevent:preventDefault` and `@onevent:stopPropagation` to achieve that.

Given the constraints Blazor operates in (it renders remotely on server mode) it can't offer an imperative API to achieve these tasks, since by the time the event is received in the .NET side for handling, it has already executed on the JS side.

**Comment by AmirMahdyJebreily** [comment]
thanks for your response.  
can blazer wasm have this api specifically?
