### ISSUE TITLE
.NET8 Not respecting @layout

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/aspnetcore#52367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using @layout directives on a Razor page, it is not being respected. I have an app which AddsRazorComponents() and MapsRazorComponents() in the Program.cs.

I have two components, Home and RandomNumber. Home component has @layout MainLayout and RandomNumber uses @layout EmptyLayout. Neither of them are respected when the application is run.
### Expected Behavior

@layout is respected for each @page i define in my application.

### Steps To Reproduce

https://github.com/garrettlondon1/HtmxBlazor

### .NET Version

8.0.1

**Comment by garrettlondon1** [comment]
I know this app is not using Routing, Blazor at all, but we should be able to take advantage of the Routing middleware and @page directives, without having to define minimal API endpoints and return RazorComponentResult.

**Comment by SteveSandersonMS** [comment]
I'm a bit confused about what your sample is trying to do.

Your sample app calls `app.MapRazorComponents<Home>()`, which means you are defining `Home` as your root component which is responsible for hosting all your `@page` components. But then `Home` itself is also a `@page` component.

What did you mean when you defined `Home` as the root component? How could `RandomNumber` then ever get rendered? My best guess is that you don't really want to have any specific root component at all, but instead want to map endpoints for all the `@page` components, as if they are all separate root components. Is that right?

If you want things to work in a more normal way, you should define a root component (e.g., call it `App.razor` and then use that as the generic type parameter to `MapRazorComponents`). Inside that, have a `<Router>` component, so it will render whatever `@page` component corresponds to the current URL, inside any nominated layout.

> I know this app is not using Routing, Blazor at all, but we should be able to take advantage of the Routing middleware and @page directives

You are using ASP.NET Core's server-side routing (as you mention, the Routing middleware). And that wouldn't be any different if you had a `<Router>` component - during SSR it's not going through a separate route matching process, it's simply using whatever route data was already computed by the Routing middleware. So AFAIK there's no reason to be trying to avoid having a `<Router>` component.

Does this make sense? If I've misunderstood your goals please clarify.

**Comment by garrettlondon1** [comment]
@SteveSandersonMS Yes, trying to avoid a root component and have all pages rendered independently.

Let me try the generic type solution you’ve recommended. Much appreciated..

I was trying to boil down a solution to the simplest  it could possibly get, to try and create a more beginner friendly template. I think it’s close, hopefully I can abstract the routing away from the user to keep it simple.

Thanks very much for your response.

**Comment by garrettlondon1** [comment]
@SteveSandersonMS Yup, I added App.razor. Added a simple <Router tag, and it worked like a charm. Whenever I want to render a partial, I can just specify EmptyLayout. And specifying the DefaultLayout on the RouteView eliminates the need for @layout on the page.

Question: Why do we need a base component in the generic type of MapRazorComponents<>(). Is there any way to say.. without RazorComponentResult and Minimal API, maybe through Program.cs.. that I want to just map every @page directive in the assembly, to return plain HTML once OnInitialized is complete?

BTW: I pushed the latest to that same repo.. It's an incredibly clean developer experience, curious what you think about it.

**Comment by SteveSandersonMS** [comment]
> Question: Why do we need a base component in the generic type of MapRazorComponents<>()

It's to do with how the system discovers the `@page` component types. On principle we don't scan every type in every assembly you reference, as it would harm startup time. By specifying a root component type, you're also specifying which assembly should be scanned.

Secondly, there's a requirement that the root component not have an interactive rendermode, because the transition from prerendered to interactive would re-evaluate any `<script>` tags, which would normally cause you an error. So it's helpful to have an explicit notion of a root component that will always be static, and then layouts can be interactive if you want. I know this paragraph isn't applicable to your scenario since you're only doing static SSR anyway, but it is applicable to most other apps.

> BTW: I pushed the latest to that same repo.. It's an incredibly clean developer experience, curious what you think about it.

Yes, this is cool! HTMX forces a very different approach to achieving interactivity (compared with either the streaming SSR + enhanced nav approach or the interactive rendermode approach - a different set of tradeoffs) but is clearly popular and effective in many cases. I'm glad to see this example of how it can be integrated and am sure many other developers would like to do this.
