### ISSUE TITLE
Static file and routing with asterisk template conflict

### ISSUE THREAD

**Issue by daping123** [dotnet/aspnetcore#52420]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I want to to serve static files with the following minimal api:
```
app.MapGet("{*UrlParts}", (string? UrlParts) =>
{
    return Results.Content($"<h1>Hello World</h1>", "text/html");
});
```
I put the static file middleware before the minimal api, but it always return the result: Hellow World.
After researching, it works if I add the `app.UseRouting()` middleware.
We know that before .NET 6, we use `app.UseRouting()` and `app.UseEndpoints(endpoints =>{endpoints.MapControllers();});`. But beyond .NET 6, we only use `app.MapControllers();`.
I want to know why it works when I add the `app.UseRouting()` middleware

### Steps To Reproduce

Reproduce the issue:
```
app.UseStaticFiles();

app.MapControllers();
app.MapGet("{*UrlParts}", (string? UrlParts) =>
{
    return Results.Content($"<h1>Hello World</h1>", "text/html");
});
```

Workaround:
```
app.UseStaticFiles();
app.UseRouting();  //add this middleware..

app.MapControllers();
app.MapGet("{*UrlParts}", (string? UrlParts) =>
{
    return Results.Content($"<h1>Hello World</h1>", "text/html");

});
```

### .NET Version

.NET 8.0

**Comment by captainsafia** [comment]
This happens because starting in .NET 6, we automatically register the routing middleware via the `WebApplication` if it hasn't already been registered. That means that routing will run _before_ any middlewares that you register in your application.

```
var app = WebApplication.Create();

app.UseRouting(); // Implicitly done for you, runs first
app.UseStaticFiles(); // Explicitly done by you, runs after routing

app.Run();
```

When you explicitly call `UseRouting` yourself, the framework will no longer register it first and instead follow the ordering that is defined by you.

Let me know if you have any follow-up questions.
