### ISSUE TITLE
Constant loop in scaffolded Login.razor: OnInitializedAsync when using rendermode InteractiveServer at <Routes> level

### ISSUE THREAD

**Issue by eptgrant** [dotnet/aspnetcore#52481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using InteractiveServer render mode at the <Route> level, the Login.razor page scaffolded in from the template is dysfunctional. 

### Expected Behavior

No refresh loop, ability to login

### Steps To Reproduce

Create a new .net 8 Blazor web app with the below configuration:
<img width="602" alt="image" src="https://github.com/dotnet/aspnetcore/assets/2383857/4132165d-0e88-4ef9-b093-bedbef5f39dd">

Modify App.razor so that:
<Routes  />
becomes
<Routes @rendermode="InteractiveServer" />

Launch the application and visit the Login page, It will constantly refresh. Setting a breakpoint inside the OnInitializedAsync method shows this is what is getting hit repeatedly.

### .NET Version

8.0.100

### Anything else?

VS2022

**Comment by gslf** [comment]
Same issue here

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

This is a limitation that gets worked around if you create a project with global interactivity enabled (rather than creating a project with per-page interactivity and then switching to global interactivity).

You could create a project with global interactivity and see what it does, then copy that into your project.

We also have https://github.com/dotnet/aspnetcore/issues/51046 to track making this scenario better long-term.
