### ISSUE TITLE
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear() no longer effective in .NET 8

### ISSUE THREAD

**Issue by chrisdrobison** [dotnet/aspnetcore#52615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We execute 

```
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
```

at the beginning of our Program.cs file to prevent JWT claim keys getting mapped to the XML soap scheme URLs. We just upgraded to .NET 8 along with `Microsoft.AspNetCore.Authentication.JwtBearer` to 8.0.0. It appears that clearing the default claim type map is no longer effective. All claims coming through the JWT bearer middleware still retain the default mapped claims that were supposedly cleared at the very beginning of the program. The only workaround I've been able to find is 

```
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
```

I added that at the beginning of the Program.cs file and claims came back as expected.

### .NET Version

8.0.0

**Comment by fredericDelaporte** [comment]
I had almost the same trouble. The application was re-mapping `sub` to `ClaimTypes.Name` instead of the default `ClaimTypes.NameIdentifier`. The aim was to get Principal.Identity.Name reflecting the `sub` claim.

```c#
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap[JwtRegisteredClaimNames.Sub] = ClaimTypes.Name;
```

After migration to .Net 8, this was not working anymore (`Name` being `null`).

It took my way too long to find out that the handler had changed and that we should change the code to:

```c#
JsonWebTokenHandler.DefaultMapInboundClaims = true;
JsonWebTokenHandler.DefaultInboundClaimTypeMap[JwtRegisteredClaimNames.Sub] = ClaimTypes.Name;
```

And remove `using System.IdentityModel.Tokens.Jwt;`.

Another solution is to revert to the old handler by setting to `true` the `UseSecurityTokenValidators` option on `JwtBearerOptions`, but [it is not recommended](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.securitytokenvalidators).

So, I do not think this is an issue in the new implementation, rather a lack of guidance or ease of finding that guidance on how to migrate. (In other words this issue should be closed here, and maybe another one should be opened on the [.Net 8 breaking change page](https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0).)

**Comment by halter73** [comment]
It looks like you've found the breaking change announcement. If there's anything specific we should change to make migrating easier, please file a separate issue.
