### ISSUE TITLE
blazor WebAssembly does not run normally

### ISSUE THREAD

**Issue by aidenwlf** [dotnet/aspnetcore#52721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/101579695/a3667152-7f34-4da9-867b-0d21dd134ad5)
blazor WebAssembly does not run normally and keeps reporting errors, whether it is Auto or WebAssembly as soon as it is refreshed, only the server mode can run normally

### Expected Behavior

Normal should be switched automatically

### Steps To Reproduce

The official template project generated directly can't be used, and I've reinstalled Visual Studio 2022 and it still doesn't work
[BlazorApp11.zip](https://github.com/dotnet/aspnetcore/files/13634944/BlazorApp11.zip)

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@aidenwlf thanks for contacting us.

Could you please create the repro as a public github repository instead of a zip file? Thanks.

**Comment by aidenwlf** [comment]
@javiercn https://github.com/aidenwlf/blazorbug

**Comment by javiercn** [comment]
@aidenwlf thanks for the additional details.

The first thing I noticed is that you are using an RC release, instead of the final RTM, could you please upgrade to the RTM (the final 8.0 version) and try with that version?

https://github.com/aidenwlf/blazorbug/blob/main/BlazorApp11.Client/BlazorApp11.Client.csproj#L12
