### ISSUE TITLE
How to use Razor library with "Blazor Web App project template" server+client .NET 8.0?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#52752]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-to-use-Razor-library-with-Blazor-We/10524728)._

---
I want to use Blazor pages with JSInterop that are shared between different projects.
It works fine when I use "Blazor WebAssembly project templates". 
But I cannot get it to work with "Blazor Web App project template". Prerendering part works fine but client rendering is not working as pages are missing in *.Client project.
Error message: Error deserializing root component operations: System.InvalidOperationException: Root component type 'MyProject.AppShared.Pages.MyPage' could not be found in the assembly 'MyProject.AppShared'
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.DeserializeOperations(String operationsJson)
...

As long as I copy all the pages into the *.Client project, everything works fine. (Server rendering and Client rendering)
How can I tell the *.Client project that all pages are stored in a different project? Is there anything like this AdditionalAssemblies="new[] { typeof(MyPage).Assembly}"?
Or is it not possible at the moment?

---
#### Feedback Bot on 11/23/2023, 06:21 PM: 

(private comment, text removed)
#### Adil Ansari on 11/26/2023, 07:36 PM: 

(private comment, text removed)
#### Alex Nek on 11/27/2023, 03:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Your Client project must reference the Razor Class Library, otherwise it won't be able to find any of the types. You might also be running into a bug in this area that we've recently patched, where the RCL assembly might not be loaded when the app starts.

You can workaround it by making an explicit reference to a type inside that assembly, for example, with `GC.KeepAlive(typeof(MyRclType)` within the Program.cs of your client app.
