### ISSUE TITLE
Terminate SignalR connections when the corresponding token expires

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#5283]
Originally asked in: https://github.com/aspnet/SignalR/issues/1155#issuecomment-347287019

**Comment by alexb5dh** [comment]
Any up-to-date workarounds at the moment?

I'm thinking about implementing custom `TimedPrincipal` that will throw on all methods after token expires and assigning it to `HttpContext.User`. Exception handler in that case will force a client to disconnect.

Global handling is limited until #5353 is done but that can be fixed by temporarily adding try/catch in all methods involved.

Would be great if anyone could propose any simpler idea.

**Comment by davidfowl** [comment]
The core idea here is solid https://github.com/dotnet/aspnetcore/issues/5283#issuecomment-368864944. The only change would be to stash the AuthenticationResult in HttpContext.Items after the authentication middleware runs then write the same logic in OnConnectedAsync but instead of calling AuthenticateAsync just grab the AuthenticationResult and use it to implement the same logic (aborts the connection after it times out).

**Comment by philip-reed** [comment]
Is there an updated workaround for this in 3.1?

**Comment by netbidev** [comment]
Is there any news about this feature?

**Comment by warappa** [comment]
#### Using the workaround in .NET 5
The provided workaround above (https://github.com/dotnet/aspnetcore/issues/5283#issuecomment-368864944) doesn't work anymore in .NET 5, as `Abort` now sets `allowReconnect` to `false` which tells the client to not reconnect anymore.
You need to use `HubCallerContext` instead of `HubConnectionContext`, as `HubConnectionContext` isn't exposed anymore.

It's now required to directly abort the _underlying_ connection to enable a client-reconnect.
Use the code of the above workaround and replace the `OnHeartbeat` code with this:

```csharp
feature.OnHeartbeat(state =>
{
    var (ticket, context) = ((AuthenticationTicket, HubCallerContext))state;
                
    // Ensure the access token token is still valid.
    // If it's not, abort the connection immediately.
    if (ticket.Properties.ExpiresUtc < DateTimeOffset.UtcNow)
    {
         context.GetHttpContext().Abort(); // abort hard - not gracefully (connection.Abort()) - to ensure reconnect
    }
}, (result.Ticket, Context));
```

PS: ExpiresUtc
I also needed to manually set `tokenValidatedContext.Properties.ExpiresUtc` in `OnTokenValidated` in `Startup.cs`.
```csharp
services.AddAuthentication("CustomAuthenticationScheme")
.AddCustomAuthentication(configure =>
{
    ...
    configure.Events.OnTokenValidated = async context =>
    {
        var token = context.SecurityToken;
        context.Properties.ExpiresUtc = token.ValidTo;
    };
    ...
});

**Comment by alinflorin** [comment]
> #### Using the workaround in .NET 5
> The provided workaround above ([#5283 (comment)](https://github.com/dotnet/aspnetcore/issues/5283#issuecomment-368864944)) doesn't work anymore in .NET 5, as `Abort` now sets `allowReconnect` to `false` which tells the client to not reconnect anymore (see #25693).
> You need to use `HubCallerContext` instead of `HubConnectionContext`, as `HubConnectionContext` isn't exposed anymore.
> 
> It's now required to directly abort the _underlying_ connection to enable a client-reconnect.
> Use the code of the above workaround and replace the `OnHeartbeat` code with this:
> 
> ```cs
> feature.OnHeartbeat(state =>
> {
>     var (ticket, context) = ((AuthenticationTicket, HubCallerContext))state;
>                 
>     // Ensure the access token token is still valid.
>     // If it's not, abort the connection immediately.
>     if (ticket.Properties.ExpiresUtc < DateTimeOffset.UtcNow)
>     {
>          context.GetHttpContext().Abort(); // abort hard - not gracefully (context.Abort()) - to ensure reconnect
>     }
> }, (result.Ticket, Context));
> ```
> 
> PS: ExpiresUtc
> I also needed to manually set `tokenValidatedContext.Properties.ExpiresUtc` in `OnTokenValidated` in `Startup.cs`.
> 
> ```cs
> services.AddAuthentication("CustomAuthenticationScheme")
> .AddCustomAuthentication(configure =>
> {
>     ...
>     configure.Events.OnTokenValidated = async context =>
>     {
>         var token = context.SecurityToken;
>         context.Properties.ExpiresUtc = token.ValidTo;
>     };
>     ...
> });
> ```

Hello,

Trying this out right now, it seems that the OnHeartbeat function is executed every second or so (not sure why). This is a bit too often I'd say, especially if there are lots of connected users. Is there a workaround? I would say executing this every time the client sends a "ping" - 15s by default I think - would be perfect. Is that possible?

**Comment by davidfowl** [comment]
@BrennanConroy is going to be looking at this with https://github.com/dotnet/aspnetcore/issues/5297
