### ISSUE TITLE
Does [AsParameters] properly propagate documentation via ApiExplorer?

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#52931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure if this is the case, but there are some issues in [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2658) with `[AsParameters]` usage, and I'd thought it'd be worth to investigate.

### .NET Version

.NET 8

**Comment by captainsafia** [comment]
@kikaragyozov I suspect not. In order to bind information from the `AsParameters` attribute correctly, the type of the parameter annotated with `AsParameters` must be reflected on to discover it's properties and generate schemas for those. This functionality is not present in Swashbuckle at the moment.
