### ISSUE TITLE
Blazor 8 Render mode breaks migrations over 3rd party components. 

### ISSUE THREAD

**Issue by the-black-wolf** [dotnet/aspnetcore#53008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

New render-mode approach in Blazor 8 breaks 3rd party component libraries (like IgniteUI for Blazor) that depend on initializer scripts (what you referred to in another issue as "classic" initializers).

I end up with the following warning in the devtools console and app is broken. 

`Initializer '<IgniteUI path>' will be ignored because multiple runtimes are available. use 'before(Web|WebAssembly|Server)Start' and 'after(Web|WebAssembly|Server)Started?' instead.)`

Modifying our own components is fine, but we have zero to no control over 3rd party components. So this is a pretty big breaking change that prevents migration. Staying on net7 is not really an option because other components, including desktop and business logic libraries migrate to 8. 

### Expected Behavior

A way to force Blazor 8 to behave in net7 compatible way for Server or WASM modes, which will load appropriate initializers. 

### Steps To Reproduce

Start Blazor 8 app, any mode, add Infragistics IgniteUI for Blazor and try to do anything with initializers (chart for example). Nothing will work because initializers will be ignored. 

### Exceptions (if any)

n/a

### .NET Version

8.0.100

### Anything else?

n/a

**Comment by javiercn** [comment]
@the-black-wolf thanks for contacting us.

This is a requirement Blazor web imposes on `initializers` and it's by design, since there might be multiple components rendering in different contexts.

There's already an option `enableClassicInitializers` that you can pass to `Blazor.start` to turn on classic initializers for Blazor Web.

Alternatively, you can write an initializer in the app, import the `classic` initializer and invoke the appropriate method calls in the right contexts

```js
import { beforeStarts, afterStarted } from `./classic-initalizer.js`

export function beforeWebStarts(options) {
  beforeStarts(options);
...
```

> So this is a pretty big breaking change that prevents migration. Staying on net7 is not really an option because other components, including desktop and business logic libraries migrate to 8.

It's not a breaking change because you need to migrate from Blazor Server/WebAssembly to Blazor web (which is a new scenario) for this to be a problem. 

You can still upgrade from 7.0 and 8.0 and keep using blazor.server.js and blazor.webassembly.js without changes.

**Comment by the-black-wolf** [comment]
@javiercn thanks for the tip on classic initializers. I did it, but unfortunately it did not fix the problem. However, I now think that Ignite itself is not compatible with net80, so its not really solvable by you. Their classic initializers do get called, but rendering produces no output (but it does in net70). I'll escalate this to their support. Again, thanks for your quick response.
