### ISSUE TITLE
Razor compiler emits neither warning nor error when binding against non-existent property.

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#53020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Here's the example:
```
<InputText @bind-SomethingNonExistent="Value"></InputText>
```

### Expected Behavior

I'd expect that Razor emits a warning or an error as it does when binding against a property which does not have a corresponding callback parameter.

**Comment by javiercn** [comment]
@voroninp thanks for contacting us.

This is by design. `@bind` is just syntactic sugar over `attribute=Value` and `attributechanged="(value => _attribute = value)"`. In the case of `ComponentBase`, attributes are represented as Properties, but this is not true in the general case, which would make throwing an error/warning incorrect in these situations.

**Comment by voroninp** [comment]
@javiercn So, for the components which inherit from `ComponentBase` it's still reasonable to have a warning, isn't it?
