### ISSUE TITLE
Routing issues or just by design?

### ISSUE THREAD

**Issue by code-dispenser** [dotnet/aspnetcore#53130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not able to use client side webassembly interactive pages with server side static SSR pages without some sort of nuance and/or show stopper.

### Expected Behavior

Be able to use client side webassembly interactive pages with static SSR pages on the server but without either having to reload the program.cs file (each time when navigating from SSR to WASM), lose the ability to navigate/display cached client side pages during a connection issue and (nice to have) not have fetches made to the server for no apparent reason (although I am sure there is good reason for this).

### Steps To Reproduce

Using the new DotNet 8 Blazor Web App template, selecting Auto (Server and WebAssembly) with the location of per page/component.

1. Navigating between components/pages marked as InteractiveAuto (irrespective of prerender settings) that have been downloaded and running correctly on the client side (as WASM). The browser devtools are showing fetches being made to the server when navigating between these cached client side pages/components. 

2. Navigating between components/pages marked as InteractiveWebAssembly (irrespective of prerender settings) that have been downloaded and running correctly on the client side (as WASM). The browser devtools are showing fetches being made to the server when navigating between these cached client side pages/components.

3. With both 1 & 2 if you lose your internet connection you are stuck on the page i.e you cannot navigate/use the browser back button to display and use any cached client side WASM pages.

Using the new DotNet 8 Blazor Web App template, selecting WebAssembly, Local Accounts with the location of Global.
This template gives static SSR pages on the server and WASM pages on the client. It appears that the template achieves this (mixed SSR and WASM mode) by setting the rendermode to null (in the server side App.razor file) when routing to certain server (project) side pages.

4. You can now navigate between client side pages with or without an internet connection (with no fetches to the server). With a connection, if you navigate from a cached WASM page to the server SSR page and then back to the WASM page, the client side program.cs file code is run again before you get back to the WASM page.

5. If you navigate to the SSR page (without an internet connection) you get stuck on the "You're not connected page. Losing the connection whilst on the SSR page, you're stuck on that page. Navigation/Browser back button will not display your cached WASM pages for either case.

### .NET Version

8.0.100

**Comment by SteveSandersonMS** [comment]
> If you navigate to the SSR page (without an internet connection) you get stuck on the "You're not connected page. Losing the connection whilst on the SSR page, you're stuck on that page. Navigation/Browser back button will not display your cached WASM pages for either case.

Based on this, it sounds like what you want is something like an offline-enabled PWA. That's the minimum requirement for being able to load a WebAssembly page without currently having an internet connection.

We don't currently have a template option that generates an ASP.NET Core-hosted PWA for you (tracked as https://github.com/dotnet/aspnetcore/issues/48935), but it is possible to set one up manually, for example as done at https://github.com/SteveSandersonMS/MyDotNet8PWA (note: offline support is only enabled once the app is published).

The remaining thing I think you'll find difficult is hosting SSR pages in the same app. It's hard to make this work alongside a PWA because a PWA really wants to handle all incoming page loads. If you're very experienced with both PWAs and ASP.NET Core, it's possible you'll find a way to make the two know about each other and not interfere, but if not I'd recommend trying to avoid the requirement. That is, either use a full-fledged offline-enabled PWA and not SSR pages, or don't rely on the site working offline.

**Comment by javiercn** [comment]
@code-dispenser thanks for the additional details.

It seems that what you want is global interactivity, per page interactivity (as Steve mentioned) relies exclusively on SSR, which won't work offline.

**Comment by code-dispenser** [comment]
@javiercn I had been evaluating the different rendermodes/project selections to understand what I could do out of the box with the new project template/render modes.

I was just a little surpised, especially at No. 3 as I had assumed given that the pages had downloaded and were running clientside that I could navigate to and use them if the connection dropped (as they work offline) etc.

As long as I know what is possible, not possible and/or by design then I can plan accordingly and make the appropriate selections for the tasks at hand.  

Thank you for explaining that this is by design.
