### ISSUE TITLE
ForbidResult results 200 status code instead of 403

### ISSUE THREAD

**Issue by 9percent** [dotnet/aspnetcore#53244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While I'm trying to set the `AuthorizationFilterContext.Result` to `new ForbidResult()` in my custom AuthorizationFilter, the response status is 200 OK instead of 403 forbidden.
Sample code:
```
internal class MyAuthFilterAttribute : Attribute, IAuthorizationFilter
{
    public void OnAuthorization(AuthorizationFilterContext context)
    {
        context.Result = new ForbidResult();
    }
}
```
The response code is `200`.

Contrast that with other result types:

`context.Result = new UnauthorizedResult();`
Response status is `401`.

`context.Result = new NotFoundResult();`
Response status is `404`.

### Expected Behavior

`ForbidResult` response status code sould be `403`.

### Steps To Reproduce

1. Implement a custom `IAuthorizationFilter` attribute like the sample code in the description.
2. Use as controller attribute.
3. Observer the response status code.

### .NET Version

8.0.100

**Comment by captainsafia** [comment]
@9percent Thanks for reporting this issue.

It looks like the `ForbidResult` type does not implement the `StatusCodeResult` interface which explains why the status code isn't configured.

I'm not entirely sure why the `ForbidResult` doesn't implement a `StatusCode` like other types too. This has been the case for a while and it's unclear if that was an intentional choice or an oversight in this case. In either case, changing the behavior at this time will prove to be disruptive to people who are already relying on it.

The best path forward might be to use the `HttpContext` on `AuthorizationFilterContext` to explicitly set the status code in your `IAuthorizationFilter` implementation.
