### ISSUE TITLE
SDK 8.0.101 - Endpoint Filters and Output Caching - endpoint filters do not run prior to the cache hit

### ISSUE THREAD

**Issue by HummingMind** [dotnet/aspnetcore#53460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
I am using both Output Caching and an Endpoint Filter on my minimal API.

The endpoint filter runs on the first request, when there is no cache. However, it does not run again if there is a cache hit. Is this by design? For example, my endpoint filter checks for a custom X-Api-Key header and returns a certain status code if the value does not match. This works fine when the result is not cached, but then the filter does not run again on the next request (that can come from any other source) if there is a cache hit.

Is this by design? Is there a way to make sure the Endpoint Filter runs first, before the cache is checked?

Thank you!

### Expected Behavior

I was hoping the endpoint filter would be executed prior to the cache being checked.

PS: I understand I can use SetVaryByHeader in this particular example. But my question still applies.

**Comment by captainsafia** [comment]
Catching up on some triage here. It's likely that my response might be too late to solve the original issue reported but I'm hoping this answer will be helpful to someone who runs into the issue in the future.

Yes, the behavior that you are seeing is expected behavior. Endpoint filters and the output caching middleware run at different layers of the stack.

Endpoint filters are invoked by the endpoint middleware, which will typically run after the output caching middleware in your application. If you're looking to invoke some behavior that should run regardless of the status of the output caching middleware, you should implement this logic in a middleware that runs _before_ the output caching middleware.

For more information on middleware ordering, see [this doc](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0) and [this doc specifically for minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-8.0).
