### ISSUE TITLE
[Routing] Should we decode `2FA` into `/` before running constraints

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#53480]
This has been an existing behavior in routing for a long time, but it can be surprising.

We will URL decode the path, but for security reasons we don't decode any `%2F (/)` encoded segment. If you are receiving a parameter that contains `%2F` and has a constraint in it, the value will be encoded, and your constraint might not match.

For example, if you are using a regex to validate that a parameter is a URL or similar.

Currently your parameter needs to account for the existence of the encoded value and use `%2F` instead of `/` in the regex. We might want to detect this situation and decode into `/` for the purpose of evaluating the constraint.

**Comment by Tratcher** [comment]
This is another case of https://github.com/dotnet/aspnetcore/issues/30655. Trying to special case %2F is all of these little places can lead to incorrect and inconsistent results like double decoding.

The proposal to fix this everywhere is a new PathSegements property that splits the path into segments and _then_ fully decodes them, without special casing %2F. Up stack components will then need to operate on the segments rather than the path. I don't think there's any other way to properly fix these issues.

**Comment by javiercn** [comment]
Closing this in favor of #30655.

If we ever decide to do #30655, we'll also have to replicate that behavior within Blazor.
