### ISSUE TITLE
Blazor Web app mapfallback failing with 401

### ISSUE THREAD

**Issue by sukanzubair** [dotnet/aspnetcore#53547]
Whenever I reload my blazor webapp it fails with status code 401, however I would like it to go to the root page and reload the app, 

![image](https://github.com/dotnet/aspnetcore/assets/38372897/120617dd-ae38-4891-a144-35642d16591b)

**Comment by javiercn** [comment]
@sukanzubair thanks for contacting us.

This is typically because your page has `[Authorize]` on it and you are not authenticated. If you are using cookies, it should trigger a Challenge resulting in a 302 to the login endpoint. If you are using a different auth scheme, you need to configure this behavior for your particular auth scheme.

**Comment by sukanzubair** [comment]
Thank you for the feedback @javiercn 
I am using JWT so went with the option of using app.UseStatusCodePagesWithRedirects.

I am hoping this does not cause other issues but for now It is working
