### ISSUE TITLE
SpaProxyLaunchManager should use job objects on Windows to kill orphened child processes

### ISSUE THREAD

**Issue by AustinWise** [dotnet/aspnetcore#53546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

`SpaProxyLaunchManager` launches a process in `LaunchDevelopmentProxy`. It wants this process to be killed when the parent process exits. Currently it accomplishes this on Windows by launching a PowerShell script that [polls for the exit of the process](https://github.com/dotnet/aspnetcore/blob/afb5f4dfc3d0ad59d0b2d0ed82a2faa2c7dc5487/src/Middleware/Spa/SpaProxy/src/SpaProxyLaunchManager.cs#L218-L244).

This works, but there are some downsides:

* It uses a whole separate process (two counting `conhost.exe`) and polls once second. This has a small impact on system resources and battery life.
* It uses process ids (PID) to refer to both the parent and child process. While it is unlikely, it is possible for one process to exit and another to be spawned that uses the same id. This could confuse the script the script and cause it to extend the lifetime of the child process for longer than expected.
* If the monitoring PowerShell script is somehow killed, the proxy process will live longer than expected.

### Describe the solution you'd like

There is a feature in Windows that is explcitly designed for this situtation: Job Objets. Specifically, the [`JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE` flag](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_basic_limit_information) can be used to implement the "kill specific child processes when I exit" functionally.

The main downside is increase implementation complexity. Specifically you will need to add some P/Invokes for the job object functionality and a couple of structure definitions. This can be automated with CsWin32.

### Additional context

It is probably possible to implement similar behavior on Linux using cgroups. Off the top of my head, I don't know of a similar macOS facility.

**Comment by javiercn** [comment]
@AustinWise thanks for contacting us.

While all that you mention is true, we don't think that the benefits are a good trade-off compared to the complexity it adds.
* We don't think the impact on resources/batery is significant (if you want/can prove otherwise, we are happy to be wrong).
* Having a separate process take the same process ID in between polls, is also something we considered and deemed very unlikely.
* We also are aware that if the script that watches the other processes gets killed it won't do its job, but that's somewhat generally expected and something we are willing to live with. Previously the proxy would be launched directly by the .NET process and stay alive when some tooling killed it aggressively, so we think this is in general (even if not perfect) an improvement.

Given that this is exclusively used during development, we think our trade-offs in this area are reasonable, if someone comes up with a simple enough solution that has additional benefits, we might consider accepting a contribution to change it.

However, we are trying to get out of the business of launching the process ourselves and have some centralized way in the future where we can describe what needs to run and each tool / IDE can take care of launch each individual process.

**Comment by AustinWise** [comment]
Thanks for the explanation. I agree that since this is exclusively used during development, this is mostly a matter of aesthetics.

While the amount of code for using job objects is [relatively small at less than 70 lines](https://github.com/AustinWise/KillMyChildren/blob/5355219b89a6ec44d7f594fe7494231b1582404c/KillMyChildren/ProcessManager.cs), I'm guessing these are the reasons it would more trouble than its worth to use in Spa Proxy:

* It appears that using `Microsoft.Windows.CsWin32` to generate the P/Invokes would be complicated by the fact that it is not currently support in source builds.
* If you don't use `Microsoft.Windows.CsWin32`, you have to check in several P/Invoke definitions. Currently this is not really done in this repo outside of the IIS code.

I agree with your final statement that some sort of tool like Foreman or Docker Compose is probably a better way to address this than in Spa Proxy.
