### ISSUE TITLE
Optional work on assignment for custom events added through `blazor.registerCustomEventType`

### ISSUE THREAD

**Issue by a-scollin** [dotnet/aspnetcore#53759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to register a custom event on an element that requires setting up an observer on said element. 

Currently this looks something like this :  

```
@inject IJSRuntime JsRuntime

<div @ref="_eleRef" @mycustomevent="CustomEventHandler"/> 

@code { 

   ElementReference _eleRef = default!; 

   public override void OnAfterRender(bool firstRender){
       if(firstRender){
          await JsRuntime.InvokeVoidAsync("setupCustomEventDispatcher", _eleRef);
       }
    }
}
```

### Describe the solution you'd like

I'm wondering if instead of requiring another interop call, the options passed to `blazor.registerCustomEventType` could also accept some optional work to execute on the element in question when we are assigning the event listener. 

```
    blazorInstance.registerCustomEventType('mycustomevent', {
            onAssignment : ele => // ...  
            createEventArgs: event => {
            return {
                elapsedTime: event.elapsedTime,
                animationName: event.animationName,
                pseudoElement: event.pseudoElement
            };
        }
    });

```

**Comment by javiercn** [comment]
@a-scollin thanks for contacting us.

It's unclear to us what you are trying to achieve, can you provide some more details on how the new callback would be used?

**Comment by a-scollin** [comment]
> @a-scollin thanks for contacting us.
> 
> It's unclear to us what you are trying to achieve, can you provide some more details on how the new callback would be used?

Hi Javier, thanks for the reply. This would be an improvement to event binding in Blazor.
 
When assigning event handlers to an element in Blazor AFAIK the only way to reference the virtual elements respective element in the DOM is through `ElementReference` as shown. 

This is cumbersome and it also somewhat requires keying all associated elements to ensure their DOM elements persist. In the example provided, we're setting up a custom event dispatcher on an element, however, if the renderer later replaces this element (as it's unkeyed) we wouldn't be able to tell the old one doesn't exist anymore and would need to setup the dispatcher again. 

For these reasons, it would be great to have a place where we can declare some JS so we can act upon elements that are bound to  events from Blazor.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. While this is something we could do, it's the first time it's been asked for, so we'd probably need to collect more evidence that others are looking for this functionality too, to avoid the risk that we ship something too specific.

An alternative solution that might be almost as convenient for you is, instead of using a `<div>` here, use a [custom element](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements). That can still have the same visible appearance as a div, but allows you to register some JavaScript that runs whenever the element is added to the DOM and can initialize it. Or another approach is to use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to run some code whenever an element with a particular characteristic (e.g., a CSS class) is added to the DOM.

**Comment by a-scollin** [comment]
Using a custom element here is a good solution. Thank you Steve.
