### ISSUE TITLE
Blazor SSR Forms Submit Method Data Binding

### ISSUE THREAD

**Issue by kijanawoodard** [dotnet/aspnetcore#53768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The other day I posted a blazor ssr form directly to a minimal api. Worked fine.

But it got me wondering, why can't we declare the model for the target method as a parameter of the method instead of separately as [SupplyParameterFromForm]?

I did see this thread https://github.com/dotnet/aspnetcore/issues/46688 which seems to have examples of what I'm thinking of, but I can't see where along the design process it stopped being possible to declare the model in the method.

### Describe the solution you'd like

(warning: live coding in github)

<form @onsubmit="OnPost" @formname="some_form">
  <input type="text" name="someInput" /> 
</form>

@code {
   
   public void OnPost(FormInput input)
   {
      ...
      Save(input.SomeInput);
      ...
   }
   record FormInput(string SomeInput);
}

**Comment by javiercn** [comment]
@kijanawoodard thanks for contacting us.

It can't be done because the page needs to render so that the form gets rendered and we can identify what event handler needs to be called. We want the data from the form to be available on that first render so that we can have logic that for example, avoids querying the database for that data. E.g

```
protected override Task OnInitializedAsync() => FormData ??= await QueryDbForData()
```

If we didn't bind the data to form data, there's no easy way to avoid having to go to the database (another abstraction would be needed) and even after that, you'll want to display the page, so if you take the data in the form, you'll have to always asign it to a property/field, which is problematic if you forget.

In essence, it sounds neat when you just care about the event handler, but it becomes more complicated when you start considering other aspects.

**Comment by kijanawoodard** [comment]
Hmm. In the use case I was thinking of, the form wasn't bound to the Model at all. It just used hard coded name attributes. The idea is a very simple "empty form" that gets submitted. A simple example might be "an email newsletter sign up form".

In that way of thinking, if you need some more complex, you can fall back to the current way. But if you need something simple, it looks/behaves just as if it was a minimal api endpoint.

Strange, I would have sworn I typed in an html form above, but I don't see it now. Maybe it was stripped.
