### ISSUE TITLE
[Blazor] Public API changes to enable compression on Interactive components for Blazor Web

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#53821]
## Background and Motivation

We've enabled websocket compression on interactive server components in Blazor web. As part of that, we needed new public APIs to configure some of the settings and disable them if needed.

Compression is enabled by default and we don't expect the majority of our customers to change any of the settings.

## Proposed API

```diff
+ namespace Microsoft.AspNetCore.Components.Server;

+ public class ServerComponentsEndpointOptions()
{
+  public Func<HttpContext!, WebSocketAcceptContext!>? ConfigureWebsocketOptions { get; set; }
+  public ContentSecurityFrameAncestorPolicy { get; set; }
}

+ name Microsoft.AspNetCore.Builder;

+static class ServerRazorComponentsEndpointConventionBuilderExtensions
{
+  RazorComponentsEndpointConventionBuilder .AddInteractiveServerRenderMode(this RazorComponentsEndpointConventionBuilder! builder, Action<ServerComponentsEndpointOptions!>? callback = null) 
```

### Disable compression
```csharp
builder.MapRazorComponents<App>().AddServerRenderMode(o => o.ConfigureWebSocketOptions = null)
```

### Configure a more strict frame-ancestors directive policy.
```csharp
builder.MapRazorComponents<App>().AddServerRenderMode(o => o.ContentSecurityFrameAncestorsPolicy = "'none'")
```

### Disable compression

We discarded this approach because we still want to support configuring the parameters for the websocket, and we don't want to introduce two settings (CompressionEnabled and the callback). And given that this is going to be extremely rare, the callback we think is good enough.

```csharp
builder.MapRazorComponents<App>().AddServerRenderMode(o => o.CompressionEnabled = false)
```

**Comment by halter73** [comment]
API Review Notes:

- Setting the `ConfigureWebsocketOptions` to null disables compression. ~This is the only way to disable compression.~
  - The default is non-null which is unusual. And it's not obvious that the nullness of the callback disables compression.
  - There is a second way. Setting `WebSocketAcceptContext.DangerousEnableCompression = false` in `ConfigureWebsocketOptions`. If you override the Func, you need to manually set it to true again.
  - Can `ConfigureWebsocketOptions` be an `Action` rather than a `Func`?
  - Does `ConfigureWebsocketOptions` need to return a `Task`?
- `WebSocket` should have a capital "S".
- `"'self'"` is the default value for `ContentSecurityFrameAncestorsPolicy` and maps to a `Content-Security-Policy: frame-ancestors {ContentSecurityFrameAncestorsPolicy};` header.
- We have "FrameAncestors" in the property name to indicate you can set other CSP headers manually for other things.

API Approved!

```diff
+ namespace Microsoft.AspNetCore.Components.Server;

+ public class ServerComponentsEndpointOptions()
+ {
+  public Func<HttpContext, WebSocketAcceptContext, Task> ConfigureWebSocketOptions { get; set; }
+  public string? ContentSecurityFrameAncestorPolicy { get; set; }
+  public bool DisableWebSocketCompression { get; set; }
+ }

+ name Microsoft.AspNetCore.Builder;

+ public static class ServerRazorComponentsEndpointConventionBuilderExtensions
+ {
+  RazorComponentsEndpointConventionBuilder AddInteractiveServerRenderMode(this RazorComponentsEndpointConventionBuilder builder, Action<ServerComponentsEndpointOptions>? callback = null);
+ }
```
