### ISSUE TITLE
Can I use the new razor Identity UI from .NET8 in Blazor Server Side?

### ISSUE THREAD

**Issue by twojnarowski** [dotnet/aspnetcore#53893]
## Summary

In this article [What’s new with identity in .NET 8
](https://devblogs.microsoft.com/dotnet/whats-new-with-identity-in-dotnet-8/) it is stated that:

> The new version is built with Razor components and works with both server-side and WebAssembly Blazor apps.

However here [In SSR, supply HttpContext as cascading value #50253](https://github.com/dotnet/aspnetcore/pull/50253) it is stated that:
> In SSR, this will receive the HttpContext. In other rendering modes where there is no HTTP context, no value will be supplied so the property will remain null.

So these two statements conflict with each other, because in the new .NET8 Blazor template for example the Login.razor page needs the HttpContext:
```csharp
[CascadingParameter] private HttpContext HttpContext { get; set; } = default!;
```
Other pages also use the `RedirectManager.RedirectToCurrentPageWithStatus` method which needs `HttpContext` as a parameter.

I have created a new project using this template:
![image](https://github.com/dotnet/aspnetcore/assets/13180578/835c5d14-d2c0-4319-995d-c1b9576cff03)
And selected the Interactive render mode "Server"
And now when I start this application, I can see during debugging that the HttpContext from Cascading Parameter is not actually null:
![image](https://github.com/dotnet/aspnetcore/assets/13180578/258305d1-974e-4c50-8dfe-c50dee91c138)

In this template, the Program.cs has these lines:
```csharp
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();
```
Am I correct to assume that means I am using what used to be Blazor Server Side nad now Interactive Server Side Rendering? And if yes, then why in such case the HttpContext is not null?

## Motivation and goals

I would like to use the new Blazor Identity UI in the application which I updated from .NET7 to .NET8

## In scope

Clarification as to how can I use Identity in Blazor SS. 
Do I still need _Host.cshtml to extract authentication information from HttpContext during application load?
Can I use new Identity razor components in Blazor SS-only application?
Can I access HttpContext in a Blazor SS-only application?
Is Blazor Server Side now renamed "interactive SSR" in the documentation?

**Comment by javiercn** [comment]
@twojnarowski thanks for contacting us.

I think the terminology here is a bit confusing:
Blazor SSR = Static Server Rendering (Equivalent to MVC/Razor pages).
Interactive Server = Component running on the server interactively (Blazor Server + static server prerendering by default).
Interactive Client = Component running on the browser (Blazor Webassembly + static server prerendering by default).

App.razor <~> _Host.cshtml
MainLayout.razor <~> _Layout.cshtml
Routes.razor <~> (old App.razor, interactivity root)

With this in mind, the new identity support only works in Static Server Rendering (SSR) as it requires the HttpContext to be available. 
* When you navigate to one of the identity pages, it first **prerenders statically** on the server as a result of an HTTP request, which is why HttpContext is available.
* Forms and other aspects of the Identity UI only work in SSR mode, as they require an HttpContext instance, so they won't work if the component becomes interactive (the HttpContext in the cascading value is not provided there).

**Comment by twojnarowski** [comment]
So, I can use the new .NET8 template to create a Blazor Web App with Interactive Server, and with Individual Accounts Identity, but to make it work I need to copy things that I need from HttpContext in App.razor to memory and then change all of the generated UI to use data from memory, not from HttpContext, and it should work correctly?

**Comment by twojnarowski** [comment]
@javiercn is it possible to get a clarification on my last question, can I copy user claims from HttpContext to memory in App.razor and just modify the new UI to use user data from memory and not from HTTPContext and everything should work?
