### ISSUE TITLE
PageTitle does not work with disabled prerendering and render mode InteractiveWebAssembly

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#53917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you disable pre-rendering the PageTitle stops working for that page. See the movie below where first the Counter title works with prerendering and then not when prerendering is disabled.

https://github.com/dotnet/aspnetcore/assets/4984486/6122a0b1-2395-49cf-8fe3-66265865565f

### Expected Behavior

PageTitle component sets the document title regardless of the render mode and/or enabling of prerendering.

### Steps To Reproduce

1. File new Project -> Blazor Web App
2. Choose "Interactive render mode" -> WebAssembly and tick "Include sample page"
3. Go Counter.razor in the Client project and replace
`@rendermode InteractiveWebAssembly`
for
`@rendermode @(new InteractiveWebAssemblyRenderMode(false))`
5. Run the application (F5) and navigate to the Counter page and observe that the title is empty, which should be "Counter"

### .NET Version

8.0.101

**Comment by javiercn** [comment]
@rogihee thanks for contacting us.

Suspect that this is by design, in your `App.razor` your `HeadOutlet` is not rendered as interactive, so during prerendering, only `HeadOutlet` is populated (without title content because the page doesn't prerender and doesn't run) and non-interactively when the page renders, so at no point both components are rendered on the same environment.

You need to adjust `HeadOutlet` to render in the same mode as your page, if your page is not prerendering.

I believe we have a separate issue to try and improve the experience here in the future (with a warning or an error)

**Comment by javiercn** [comment]
Apply @rendermode to `HeadOutlet` and let us know if you still have issues.

**Comment by rogihee** [comment]
@javiercn thank you for your answer.

I resolved it by using the `RenderModeForPage` in the App.razor solution as documented here - after loading webassembly it sets the correct title:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#fine-control-of-render-modes
