### ISSUE TITLE
Expose JavaScript interoperability Initialization Status in Blazor

### ISSUE THREAD

**Issue by sherviniv** [dotnet/aspnetcore#53995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Currently, in Blazor, there is no direct way to determine when the JavaScript interop has been initialized. There is a private field, "IsInitialized" in IJSRuntime, which holds this information internally, developers do not have direct access to it. As a result, we are forced to rely on workarounds, such as using reflection
`
if (((bool)jSRuntime.GetType().GetProperty("IsInitialized")!.GetValue(jSRuntime)!) == true) {
    // JavaScript interop is initialized
}
`
I'm curious about why this field is private and what alternative methods exist to determine whether jSRuntime is initialized. I understand that we can address this issue by using OnAfterRender(bool firstRender). However, in certain cases, such as when implementing extension methods that receive jSRuntime as a parameter, we lack access to component lifecycles. Therefore, I'm wondering if there is a way to obtain this information through a property.
Thanks!

**Comment by javiercn** [comment]
@sherviniv thanks for contacting us.

> However, in certain cases, such as when implementing extension methods that receive jSRuntime as a parameter, we lack access to component lifecycles

You can write your own helper method `TryInvokeAsync<TResult>(string name, ...)` that wraps InvokeAsync and catches the exception.

The reason we don't provide an API to check is that it will not be correct, for example we could have an IsAvailable property or method that can be used to check, but in a Blazor server context, it can happen that you check, and just at that point the connection breaks and results in an error, which is misleading.

The only accurate way to do JS interop is to try and perform it and catch any exception that might occur.

There is an API planned for 9.0 that simplifies determining the render mode the component is currently running, and we'll likely provide something like `IsInteractive` that will help a lot along those lines, but beyond that, we are unlikely to provide such api directly inside JSRuntime because we can't guarantee its available without trying to actually invoke the method.

> `if (((bool)jSRuntime.GetType().GetProperty("IsInitialized")!.GetValue(jSRuntime)!) == true) { // JavaScript interop is initialized }`

This is completely unsupported and not something we recommend.

**Comment by sherviniv** [comment]
I appreciate your fast response @javiercn!

> There is an API planned for 9.0 that simplifies determining the render mode the component is currently running, and we'll likely provide something like IsInteractive that will help a lot along those lines,

Cool,  seems like there are lots of cool features in .Net 9! This stuff may help other folks migrate from other frameworks like Angular and React to Blazor much more conveniently. As a simple example, In this case, in Angular is it possible to define an interceptor and handle requests based on status for example(showing an error message in a toast when there is status 400).
