### ISSUE TITLE
[9.0-preview.1] Request Delegate Generator emits nullable annotations when Nullable Reference Types not enabled

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#54020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If an application does not use nullable reference types but does use the request delegate generator, the application fails to compile due to RDG emitting code with nullable annotations.

### Expected Behavior

RDG does not emit nullable annotations if the project does not use nullable reference types.

### Steps To Reproduce

- Clone the [martincostello/SignInWithAppleSample](https://github.com/martincostello/SignInWithAppleSample) repository.
- Checkout the https://github.com/martincostello/SignInWithAppleSample/commit/4c6ea88a1d6e8f79a63685cbfc4678994c902796 commit.
- Run `dotnet build` from the root of the repository.

### Exceptions (if any)

Example error:

```console
❯ dotnet build
MSBuild version 17.10.0-preview-24101-01+07fd5d51f for .NET
Restore complete (1.0s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  SignInWithApple failed with errors (1.3s)
    C:\Coding\martincostello\SignInWithAppleSample\src\SignInWithApple\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(281,32): error CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source. [C:\Coding\martincostello\SignInWithAppleSample\src\SignInWithApple\SignInWithApple.csproj]
```

### .NET Version

9.0.100-preview.1.24101.2

**Comment by captainsafia** [comment]
@martincostello Thanks for reporting this issue!

RDG enables the nullability context for generated files by adding `#nullable enable` in the file preamble. From my understanding, all source generated code needs to enable this since generated files don't implicitly carry the nullability context of the project.

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
```

There's definitely something going on here since I'm able to repro the issue but I think the generator is emitting the right code here.

**Comment by captainsafia** [comment]
@chsienki Was just taking a look at this issue again. Any thoughts on why we might be seeing this even with nullability enabled via the pragma in generated source files?

**Comment by chsienki** [comment]
@captainsafia Oh huh, I see what the issue is, although I don't know if it's a bug in Roslyn or By Design.

The `#nullable` context is reset by the nature of these being `file` scoped classes. Effectively each `file` class is treated as if its in its own file and so the top-level `#nullable enable` isn't applied. If you add a `#nullable enable` at the start of each `file` class then it works as expected.

Like I said, not sure if that's by design or a bug caused by how `file` classes are handled internally. I would suspect its actually a bug, but @RikkiGibson or @jaredpar can weigh in on that's expected for the feature.

**Comment by chsienki** [comment]
@captainsafia Ignore that last comment. 

It's this line that's causing the issue:

```csharp
           var jsonBodyOrServiceTypeTuples = new (bool, Type)[] {
               #nullable disable
               (false, typeof(global::Microsoft.AspNetCore.Antiforgery.IAntiforgery)),
               #nullable restore
           };
```

The `#nullable restore` is resetting the context back to 'off', so everything below it is in a non-enabled context. Given that the generators owns the code below the line you should just change it to a `#nullable enable` to get the correct context back.

**Comment by RikkiGibson** [comment]
Chris beat me to it :)

**Comment by chsienki** [comment]
As an aside if this `(false, typeof(global::Microsoft.AspNetCore.Antiforgery.IAntiforgery)),` is user code then the `disable` should be a `restore` so that it matches the context it was written for.

**Comment by captainsafia** [comment]
@chsienki Oof! Good spot. Thanks.

@martincostello I should be able to fix this.
