### ISSUE TITLE
Restarting browser windows doesn't resolve CERT_INVALID error

### ISSUE THREAD

**Issue by marknoble** [dotnet/aspnetcore#54026]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Ran into the issue described here - but closing all Edge windows didn't resolve the issue:
```
Got an error?
If you receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID, try to restart all browser windows so the new certificate can be picked up by the browser and run the application again.
```

Opening the application in an in-private window resolved the issue temporarily, but I'm submitting feedback to try to get it documented how to resolve this when closing and re-opening the browser windows is insufficient.

**Comment by mairaw** [comment]
@danroth27 moved to the aspnetcore repo since closing all browser windows didn't solve the cert issue

**Comment by halter73** [comment]
@marknoble Did you try regenerating and trusting the developer certificate as described here? https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0#troubleshoot-certificate-problems-such-as-certificate-not-trusted

You could also try using the "http" instead of the "https" launch profile.
