### ISSUE TITLE
Improve server addresses collection debugging

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#54030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

.NET 8 improved debugging of server addresses collection:

https://github.com/dotnet/aspnetcore/blob/d93b8e28b53f7c5d5cf6722facaef6012efa32b2/src/Servers/Kestrel/Core/src/Internal/ServerAddressesCollection.cs#L11-L13

This collection is used internally. However, the value returned from the `IServerAddressesFeature` interface is the nested type:

![image](https://github.com/dotnet/aspnetcore/assets/303201/5d71e826-8e76-4d8b-a701-2e5574704408)

### Describe the solution you'd like

Also add debugging to the nested type:

https://github.com/dotnet/aspnetcore/blob/d93b8e28b53f7c5d5cf6722facaef6012efa32b2/src/Servers/Kestrel/Core/src/Internal/ServerAddressesCollection.cs#L100

### Additional context

You can see what the value returned is from a started WebApplication with this code:

```cs
var addresses = _app.Services
    .GetRequiredService<IServer>().Features
    .GetRequiredFeature<IServerAddressesFeature>().Addresses;
```

**Comment by MythoclastBM** [comment]
Before changes: 
![before](https://github.com/dotnet/aspnetcore/assets/160416277/f5ed7a53-760d-4d69-b32d-ee1c7eb28ea4)

After changes: 
![after](https://github.com/dotnet/aspnetcore/assets/160416277/82f22fc3-45f3-4a10-8ca8-6ce7c503753a)

I also modified the solution file because I was getting this error 
![before](https://github.com/dotnet/aspnetcore/assets/160416277/29d6fd6f-05f4-479b-b4ba-48474e06cc98)

or basically all projects in the Kestrel/samples folder and adding references to the projects was the only way to get it to work. I assume it breaks for everyone that tries to use them, but I easily could've done something wrong setting up my repo. 

I also accidentally committed a modified version of the KestrelSampleStartup by accident, will revert to the main version. Apologies.

**Comment by JamesNK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/issues/54030
