### ISSUE TITLE
Enable docker feature for SPA templates

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5417]
Currently when you create a new Angular/React project, the *Enable Docker support* option is disabled because the template config doesn't declare support for that.

We should implement support for this. AFAIK it should be able to work the same way as other ASP.NET templates.

**Comment by NotMyself** [comment]
Looks like I ran into this today. Using `dotnet new react` and attempting to use the following Dockerfile fails with no support for NPM.

```Dockerfile
FROM microsoft/dotnet:2.2-sdk-alpine AS build
WORKDIR /app

COPY . .
RUN dotnet restore
RUN dotnet build
RUN dotnet publish -c Release -o /app/deploy

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine AS runtime
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
WORKDIR /app
EXPOSE 80
COPY --from=build /app/deploy ./
ENTRYPOINT ["dotnet", "api.dll"]
```

**Comment by glennc** [comment]
There are a few ways a customer could do something the most likely 2 are:

1. Use multi-stage build so that actions requiring node happen in their own image, separate to the .NET compilation process. This assumes you don't need node at runtime and mostly need npm restore and trans-pile steps.
2. Create your own build possibly runtime image that adds the version of node and other tools that you need.

Depending on your build pipeline and lots of other details there might be other options. But those 2 are the pure Docker way of doing it.

For us the only real option is to generate a multi-stage Dockerfile that uses the Node images when node is required. However, the Dockerfile contents are not currently owned by us. They are generated by the Docker tooling team. We could probably add Dockerfiles that you could get on the commandline, and then use right-click to add support later. But getting the VS checkbox for Docker support to work requires more work with a different team.

Either way, we don't currently have time for this in the 3.0 milestone so I am moving the issue out. However, we could do a blog post explaining to everyone how they can get this working today without template support. @danroth27 do you want to work on that with me?

**Comment by danroth27** [comment]
> However, we could do a blog post explaining to everyone how they can get this working today without template support. @danroth27 do you want to work on that with me?

@glennc Sure

**Comment by ricardoasilva92** [comment]
> > However, we could do a blog post explaining to everyone how they can get this working today without template support. @danroth27 do you want to work on that with me?
> 
> @glennc Sure

any news on this?

**Comment by tiagomelobr** [comment]
Anyone else found a solution for this?

**Comment by mkArtakMSFT** [comment]
Closing as there are no plans to do this in the near future.
