### ISSUE TITLE
Cannot get routeData in IExceptionHandler.TryHandleAsync() for ASP.NET Core 8 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54192]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-get-routeData-in-IExceptionHandle/10586875)._

---
I have the following code, and the context. GetRouteData() always return null.
I want to log the controller name and action name when exception occurs.
How can I fix it? 

Thank you,

## GlobalExceptionHandler.cs

```
public async ValueTask<bool> TryHandleAsync(
	HttpContext context,
	Exception exception,
	CancellationToken cancellationToken)
{

// STEP 0: Get controller name / action name
	var routeData = context. GetRouteData();
	var controllerName = routeData?. Values["controller"]?. ToString();
	var actionName = routeData?. Values["action"]?. ToString();
}
```

## Program.cs

```
app. UseHttpsRedirection();
app. UseStaticFiles();

app. UseRouting();

#region Use build-in ExceptionHandler
app. UseExceptionHandler();
#endregion

app. UseAuthorization();

app. MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app. Run();
```

---
#### Feedback Bot on 2/18/2024, 03:05 AM: 

(private comment, text removed)
#### jasper.lai on 2/18/2024, 08:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment]
Since you're using `MapControllerRoute()` rather than `UseMvc()` (which is good since `MapControllerRoute()` is the more modern API that utilized [endpoint routing](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#aspnet-core-endpoint-definition), you need to update your call from `GetRouteData()` to call `GetEndpoint() as RouteEndpoint` as follows:

```csharp
var routeEndpoint = context.GetEndpoint() as RouteEndpoint;
var routePattern = routeEndpoint?.RoutePattern;
var controllerName = routePattern?.RequiredValues["controller"]?.ToString();
var actionName = routePattern?.RequiredValues["action"]?. ToString();
```

**Comment by halter73** [comment]
The problem is that the exception handler middleware clears the path and other routed data from the HttpContext before running any custom handlers. This is to protect against any attempt to re-execute the middleware pipeline accidently resulting in the same endpoint that just threw the exception getting hit again.

https://github.com/dotnet/aspnetcore/blob/87c039723f99b92a84d65cd823c8e6b44450784e/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L156-L169

The good news is that all the old route data is stored in the [ExceptionHandlerFeature](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.diagnostics.iexceptionhandlerfeature?view=aspnetcore-8.0) as you can see in the middleware implementation above. You can get access to the route data from the feature as follows:

```csharp
var routeValues = httpContext.Features.Get<IExceptionHandlerFeature>()?.RouteValues;
var controllerName = routeValues?["controller"]?.ToString();
var actionName = routeValues?["action"]?.ToString();
```
