### ISSUE TITLE
Identity functions not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54248]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Identity-functions-not-working/10577468)._

---
[severity:It bothers me. A fix would be nice]
The function in the user manager, findbyemailasync fails completely.  The function in the sign in manager PasswordSignInAsync fails completly as well.  Ive used these functions for years and there is no reason I see that they should fail.

---
#### Feedback Bot on 2/6/2024, 00:12 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment]
Removing "Needs: Author Feedback", because the author is @vsfeedback who is not going to reply meaning the label will not get labeled automatically. By removing the label now, we should continue to see this issue in our triage queries. But if [Valley of the Kings](https://developercommunity.visualstudio.com/user/1293157) doesn't turn up on this issue with a repro in the next few weeks, we will have to close the issue.
