### ISSUE TITLE
Disposing disposable transient services in Blazor

### ISSUE THREAD

**Issue by AntMaster7** [dotnet/aspnetcore#54376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Someone opened this [same issue](https://github.com/dotnet/aspnetcore/issues/20755) some years ago. However, it was closed and the answer given in that issue appears to be wrong.

In the section [Disposal of services](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#disposal-of-services) in the ASP.NET Core documentation it states: "The container calls [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) for the [IDisposable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable) types it creates. Services resolved from the container should never be disposed by the developer.".

However, this appears to be not the case with Blazor. Whereas the Dispose method of components is called if they implement the IDisposable interface, the injected services (given they are transient) are not disposed. I do believe one of the reasons for a DI container is lifetime management. A component should not be aware of the lifetime of a service it consumes.

### Describe the solution you'd like

Injected transient services get disposed once a component gets disposed.

### Additional context

I'm not sure if this might even be considered a bug because it contradicts the documentation.

**Comment by SteveSandersonMS** [comment]
> In the section [Disposal of services](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#disposal-of-services) in the ASP.NET Core documentation it states: "The container calls [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) for the [IDisposable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable) types it creates. Services resolved from the container should never be disposed by the developer.".

In Blazor the DI container *does* dispose transient services at the end of the lifetime of the DI container (e.g., the end of a Blazor Server circuit). It can't dispose them any earlier because there's nothing to define a shorter lifetime. As such, the doc is correct (and the comment you linked to is incorrect, since the DI container *does* track even transient instances).

This isn't very useful, because of course you probably do want them to be disposed earlier. Unfortunately this is a design limitation with DI that applies to all long-lived app contexts (Blazor Server, Console apps, WinForms, etc.).

We have an issue tracking the desire to improve how the DI container works to handle these long-lived app scope scenarios: https://github.com/dotnet/aspnetcore/issues/26676.

Mainly, for now, we recommend not using transient services in long-lived DI scopes such as Blazor Server circuits. Or if you must do, then create and dispose your own DI scope for a shorter unit of work, or use the `OwningComponentBase` base class to simplify this pattern.

**Comment by AntMaster7** [comment]
Thank you so much @SteveSandersonMS for taking the time to look into this. I have no idea how you guys are able to manage so many requests.
