### ISSUE TITLE
Blazor SSR: Partially invalid UI Refresh after submitting EditForm

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/aspnetcore#54432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a form with multiple input boxes (bool, text, select multiple), a submit without any changes changes the output to be invald:
1. Initially it looks like this:

<img width="197" alt="Initial" src="https://github.com/dotnet/aspnetcore/assets/7989549/87c5bb42-ec1f-428b-bc2d-f49ae77a406b">

2. After clicking the Save button (which does not do anything) it looks like this

<img width="193" alt="SaveWithoutChanges" src="https://github.com/dotnet/aspnetcore/assets/7989549/4b390d25-bc69-4dd3-9c8b-edaef914b1c3">

For some reason one of the checkboxes is now not checked anymore (the disabled one) and the input select is empty

Repo see below, the interesting markup is here:
https://github.com/Tornhoof/InputMultiSelectRepro/blob/main/Components/Pages/Home.razor

### Expected Behavior

Ui is not broken.
I noticed it does not call OnInitializedAsync again after the post callback is finished.
Workaround: Call NavigationManager.Refresh

### Steps To Reproduce

1. Checkout https://github.com/Tornhoof/InputMultiSelectRepro
2. Make sure NavigationManager.Refresh(); in line 85 in Home.razor is commented
4. Run in browser
5. Press Save

### .NET Version

8.0.200

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please try removing the explicitly-specified `selected` attribute [here](https://github.com/Tornhoof/InputMultiSelectRepro/blob/8cec59b435495508f93e4489be0c171e60b04c6a/Components/Pages/Home.razor#L39)? This attribute gets inferred by the value bound to the `<InputSelect>`.

Also, it looks like the roles specified [here](https://github.com/Tornhoof/InputMultiSelectRepro/blob/8cec59b435495508f93e4489be0c171e60b04c6a/Components/Pages/Home.razor#L67-L70) aren't populated when it's not the first render of the form, which is why you're seeing those values disappear after form submission. To fix this, you could always render each option in the form rather than dynamically reading from the model to determine which options to render. Alternatively, you could populate the roles in the "else" branch in your code.

Could you please let us know if these suggestions solve the problems you're seeing?

**Comment by Tornhoof** [comment]
> Could you please try removing the explicitly-specified selected attribute [here](https://github.com/Tornhoof/InputMultiSelectRepro/blob/8cec59b435495508f93e4489be0c171e60b04c6a/Components/Pages/Home.razor#L39)

I tried that, but how do I select anything in OnInitializedAsync then? Looking at https://github.com/dotnet/aspnetcore/blob/d4d6468c669d03c4e4daaea20c913b22dba636e2/src/Components/Web/src/Forms/InputSelect.cs#L47-L52 there is no code which does anything w.r.t to selection in SSR mode?
The only code I found is in the appropriate javascript/typescript code in the PR you wrote a few years ago, which isn't used/loaded in SSR mode and if I set the rendermode to InteractiveServer, everything works as expected, but not in SSR.


> Also, it looks like the roles specified [here](https://github.com/Tornhoof/InputMultiSelectRepro/blob/8cec59b435495508f93e4489be0c171e60b04c6a/Components/Pages/Home.razor#L67-L70) aren't populated when it's not the first render of the form, which is why you're seeing those values disappear after form submission.

Ah thank you, this was indeed the reason, the breakpoint in OnInitializedAsync was never hit after Callback, so I never thought about that weird multiple render topic.

**Comment by Tornhoof** [comment]
@mkArtakMSFT any objections, if I open a docs PR stating that InputSelect (multiple) works only for interactive rendermodes?
