### ISSUE TITLE
enhancedload in Blazor Hybrid/MAUI and WebAssembly Hosted

### ISSUE THREAD

**Issue by c0g1t8** [dotnet/aspnetcore#54463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**enhancedload** event should not occur in Blazor Hybrid/MAUI and WebAssembly hosted applications. 

In Blazor components that have been enhanced to support static SSR, this event triggers the addtion of javascript when the component is first rendered in **Blazor Web Apps** as [documented](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0). This additional script allows interactive functionality till component is ready to render. On this render, the addtional javascript is not added.

The issue appears when the same component is used in a Blazor Hybrid/MAUI or WebAssembly hosted application. The javasript that was intended to be used only for static SSR is added. In this particular case, an interactive component, written entirely in Blazor/C#, needed to be support the same interactivity when statically rendered.  Javascript was added as per the documentation. This worked as expected in Blazor Web Apps. But when the same componenet was used in a Blazor Hybrid/MAUI or WebAssembly hosted application, it did not.

The interactivity is based on handling the click event on a specific element. On the Blazor side, an event handler was added for the click event. A similiar event handler was added in JavaScript for static SSR support. In Blazor Web App there is no issue since the JavaScript is only used in for static SSR. But when Blazor Hybrid/MAUI or WebAssembly hosted, both handlers are in play where the Blazor handler is always superceded by the JavaScript handler.

### Expected Behavior

**enhancedload** event should not occur in Blazor Hybrid/MAUI and WebAssembly hosted.

The behaviour of a Blazor component when interactive in Blazor Web App and non Blazor Web App should be the same.

### Steps To Reproduce

See [1560 ](https://github.com/microsoft/fluentui-blazor/pull/1560)and [1633](https://github.com/microsoft/fluentui-blazor/pull/1633).

### .NET Version

8.0.200

### Anything else?

I'm assuming this was just an edge case that was not covered and the intent of the **enhancedload** event is specifically to enable support of static SSR for Blazor Web Apps.

**Comment by MackinnonBuck** [comment]
> enhancedload event should not occur in Blazor Hybrid/MAUI and WebAssembly hosted applications.

To clarify, is the issue that the `enhancedload` event currently _does_ get invoked in Blazor Hybrid and WebAssembly applications, and it should not? Or that it currently _does not_ get invoked, and it should? I'm going to assume the latter, because I'm fairly certain the `enhancedload` event never gets invoked in Hybrid or WebAssembly standalone scenarios. If that's the case, it's unlikely that we would expand the `enhancedload` event to also get triggered by anything that isn't an enhanced page load.

If my assumption is wrong and you're saying that there are cases when `enhancedload` gets invoked when it shouldn't, could you please provide a minimal repro project that shows this, hosted as a public GitHub repository? Thanks!

**Comment by c0g1t8** [comment]
Hi @MackinnonBuck,

> To clarify, is the issue that the enhancedload event currently does get invoked in Blazor Hybrid and WebAssembly applications, and it should not? Or that it currently does not get invoked, and it should? I'm going to assume the latter, because I'm fairly certain the enhancedload event never gets invoked in Hybrid or WebAssembly standalone scenarios. If that's the case, it's unlikely that we would expand the enhancedload event to also get triggered by anything that isn't an enhanced page load.

The **enhancedload event** is being invoked in Hybrid and WebAssembly standalone scenarios. From reading in-between the lines in the documentation, it appears it's use is only for supporting static SSR. I could not find any documentation on it's intent in Hybrid or WebAssembly scenarios.

From your comments, it sounds like the intent was to **_not to invoke the enhancedload event_** which is the what I would expect in non-static SSR scenarios.

I can provide a minimum repro in a public Github repository.

**Comment by c0g1t8** [comment]
@MackinnonBuck 

I think I found my problem. I took a deep dive into your [BlazorPageScript](https://github.com/MackinnonBuck/blazor-page-script) library and [found](https://github.com/MackinnonBuck/blazor-page-script/blob/599c37c8f5f85c79e1e845b8b18ea5d4406c85c6/src/wwwroot/BlazorPageScript.lib.module.js#L67C1-L90C2)

```javasript
export function afterWebStarted(blazor) {
    customElements.define('page-script', class extends HTMLElement {
        static observedAttributes = ['src'];


        // We use attributeChangedCallback instead of connectedCallback
        // because a page-script element might get reused between enhanced
        // navigations.
        attributeChangedCallback(name, oldValue, newValue) {
            if (name !== 'src') {
                return;
            }


            this.src = newValue;
            unregisterPageScriptElement(oldValue);
            registerPageScriptElement(newValue);
        }


        disconnectedCallback() {
            unregisterPageScriptElement(this.src);
        }
    });

    blazor.addEventListener('enhancedload', onEnhancedLoad);
}
```

The Javascript listener is attached to the **enhancedload** event only **afterWebStarted**.  That's not what's happening my case. This could be the cause of the behaviour I'm seeing.

**Comment by MackinnonBuck** [comment]
@c0g1t8 The `BlazorPageScript` library is meant to be used exclusively in Blazor Web Apps, especially in cases where JS interop may not be an option (i.e., no interactivity). It was designed to be used in `@page` components (hence the name), so I would recommend that component libraries not take a dependency on that package, instead using its code as a reference when implenting their own solution.

I could update the library to also register the custom element even in non-web cases, but it's not clear to me how useful that would be. If an app is completely interactive (e.g., WebAssembly standalone or Blazor Hybrid), JS interop can be used in place of `PageScript`. The main case this helps with is using `PageScript` in a component library, but again that's not something I would recommend.

Am I correct in understanding that the `enhancedload` event is not getting invoked in Blazor WebAssembly standalone scenarios, and the issue was actually due to a characteristic of `PageScript`?

**Comment by c0g1t8** [comment]
@MackinnonBuck 

FYI, I found the cause of the issue in the FluentUI Blazor library.  See [this](https://github.com/microsoft/fluentui-blazor/pull/1633#issuecomment-2002552015). 

My mistake was thinking the **onLoad** was being triggered by the **enhancedload** event which sent me down the wrong path. It was only when I started digging further into the source code PageScript that I realized how things actually worked. 

I appreciate the time you spent providing me the feedback that allowed me to resolve my issue. 🙏
