### ISSUE TITLE
builder.Services.AddDataProtection().PersistKeysToFileSystem() how to ensure 100% availability when a web farm of servers are using a single file share to decrypt and validate an AntiForgeryToken

### ISSUE THREAD

**Issue by whitcsharp** [dotnet/aspnetcore#54561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have been using Machine Keys to provide AntiForgery token support for our .NET framework apps. This has worked well as the machines are independent of each other and if one goes down the others will remain up and running.
PersistKeysToFileSystem() seems to take away that 100% availability. If all servers in a farm rely on one servers file share to be up and availability it seems risky to do this.
What are my options to alleviate concerns about availability?
Thank you.

**Comment by amcasey** [comment]
I don't have a detailed understanding of Machine Keys, but it seems like that would only be possible if the keys never changed?  Since Data Protection rotates keys regularly, you can't completely eliminate the possibility of different machines having different states.

As for where to locate shared storage, there are a number of [options](https://learn.microsoft.com/aspnet/core/security/data-protection/implementation/key-storage-providers), but [Azure blob storage](https://learn.microsoft.com/aspnet/core/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps) is probably the most straightforward.  If you prefer to keep everything within the farm, you could use EF Core or Redis (with careful configuration to avoid data loss), but you'd still need to manage keeping your database/cache available.  The system is also pluggable, if you have a different preferred storage location.

**Comment by amcasey** [comment]
I regret not being able to provide an answer that guarantees 100% availability, but I think I covered the available options.  Please let us know if you have more questions.
