### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5462]
Make Blazor DLLs available from a CDN

**Comment by Lupusa87** [comment]
Is anything happening here?

I try to load blazor app from azure CDN linked to azure storage but no success yet.

Blazor is working well as static website from azure storage.

I want to enable it from CDN because of load speed and also CDN compression support.

I put whole (not only dlls) blazor app to CDN and when calling index.html it give this error:
`WASM: System.InvalidOperationException: 'Router' cannot find any component with a route for '/index.html', and no fallback is defined.`

**Comment by ghidello** [comment]
Hi! 
I have been happily hosting my blazor apps on github pages with a custom domain. A few days ago I tried a default Blazor Hosted application on Azure Websites and my Avast antivirus was blocking my specific application dll (not the ones from the framework) saying that it didn't have enough positive feedback on that dll. The funny thing is that Avast complains about the ddl if I load the site from app-name.azurewebsites.net but not from localhost or one of my "real" domains: weird.

On the topic of the dll extension replacement i would like to push for the wasm extension (even if not tecnically correct) because github pages and cloudflare are already handling the compression for "application/wasm" but not for "application/octet-stream" so a default Blazor app weights about 3.2 MB having only mono.wasm compressed with brotli.

(Sorry @Lupusa87 , I never tried tha Azure cdn so I have no suggestions on that)

**Comment by danroth27** [comment]
@Lupusa87 Since this issue is tracking something different (hosting the Blazor runtime on a common CDN), could you please open a new issue with more details on how to reproduce the problem you are seeing? We need to know what version of Blazor you are using, what does the app code look like, how did you publish it to the CDN, etc.
