### ISSUE TITLE
[Blazor]: Why enhance naviagation would clear the <head> element?

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#54658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We found that when the page jumped, the head element was modified, causing the style and JS to reload.

https://github.com/ant-design-blazor/ant-design-blazor/issues/3747

**Comment by ElderJames** [comment]
Here is the repro repo https://github.com/ElderJames/NavigateIssue

You can submit the form in Home page then can see the style was loss in a moment.
I used js initializers to insert the style. https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/wwwroot/AntDesign.lib.module.js

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. This happens because enhanced navigation removes any content from the page that does not match what the server rendered. The exception to this is the children of any elements with the `data-permanent` attribute.

Putting the `data-permanent` attribute on the `<head>` may not be desirable, though, because then _all_ head content gets preserved and ignores whatever the server renders.

To work around this (although it's a bit weird), you could have two `<head>` elements, one with the dynamically-added styles and a `data-preserve` attribute, and another with the rest of the head content. According to [this](https://stackoverflow.com/a/33110559), this approach should work with modern browsers even though it's not technically valid HTML.

A less weird solution might be to register a listener for Blazor's `enhancedload` event, and re-add the styles in that event if they've been removed. Something like:
```javascript
Blazor.addEventListener('enhancedload', () => { ... });
```

We also have an [issue](https://github.com/dotnet/aspnetcore/issues/51021) tracking updating `data-permanent` to also apply to the element with the attribute (not just its children), which would make this scenario not require any of these hacks.

Could you please let us know if any of these approaches work for you? Thanks!

**Comment by ElderJames** [comment]
I tried to add the head dynamically with a data-permanent attribute, but the head element was still removed after the form was submitted.
![image](https://github.com/dotnet/aspnetcore/assets/7550366/ede298ac-247c-4b5f-aa2c-7fee90346904)
![image](https://github.com/dotnet/aspnetcore/assets/7550366/693fcb69-5b10-4756-9347-8186ca89e5b6)
