### ISSUE TITLE
Blazor streaming rendering without JavaScript

### ISSUE THREAD

**Issue by flixcor** [dotnet/aspnetcore#54724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It is currently not possible to use streaming render mode without JavaScript 

### Describe the solution you'd like

Blazor streaming render mode is very interesting, but requires JavaScript. Html is inherently stream-friendly, so it would be great if there would be a mechanism to flush the response stream early, like in Razor Pages. This way, you could for example render the static content on a page - such as a header - early, before any database calls are made, improving time to first byte. Another opportunity could be rendering the first few items of an IAsyncEnumerable early. To allow doing this without JavaScript, rendering would have to be done in order, so a child component in this scenario cannot trigger a re-render higher up in the component hierarchy. This rules out a lot of functionality that is currently possible with different render modes, so it would definitely have to be something you opt-in to.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Streaming rendering in Blazor requires JavaScript because partial-content is being streamed most of the time (like a single-component is being rendered out of many) and that content will need to be merged with the rest of the existing content, and that's what JavaScript code helps with.

Hence, supporting what you're asking for would involve completely changing the Blazor component programming model, which is not something we plan to do.
