### ISSUE TITLE
Blazor DynamicComponent is reusing old instances and their states

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54727]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-DynamicComponent-is-reusing-old-i/10620301)._

---
[severity:I'm unable to use this version]
The code (Sample Blazor project attached):

```
@page "/"

<PageTitle>Home</PageTitle>

<p>
  <button @onclick=OnClick3>Show 3 buttons</button>
  <button @onclick=OnClick5>Show 5 buttons</button>
</p>

@for (int i = 0; i < count; ++i)
{
  <DynamicComponent Type=typeof(MyButton) />
}

@code {
  int count = 3;

void OnClick3() => count = 3;
  void OnClick5() => count = 5;
}
```

1. You can see three buttons with text "False". Each was rendered using DynamicComponent and Type=typeof(MyButton).
2. Clicking on one of them changes the text to "True"
3. Clicking on "Show 5 buttons", two new buttons are rendered with "False" but the existing ones with "True" are not recreated and still show "True".

I would expect that all buttons show "False" after rerendering.

---
#### Feedback Bot on 3/20/2024, 08:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is due the DOM preservation mechanism that Blazor uses internally. It tries to preserve as much of the DOM as possible, if new content is being rendered. You can control the DOM preservation logic by explicitly specifying unique keys to elements. The DOM merging logic will look for this information on elements when applying the new changes. If it happens to see the an element with the same key both in new and existing DOM then it will preserve the content. Otherwise, the content will be overwritten with the new content.
When not specified explicitly, the framework tries to "figure out" the mapping on its own. If that behavior is not what you want (which seems to be the case here), you should define the mappings explicitly using the `@key` directive. You can read more about this in our documentation here: https://learn.microsoft.com/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-8.0

**Comment by bitrott** [comment]
Honestly, @key is really powerful, but the documentation is terrible. The example it gives is too simplistic on its own. The reasons given when to use it and when not to don't encompass much of the real scope of the issue. This ticket makes a case for reviewing it I think.
