### ISSUE TITLE
Virtualize component doesn't work with hidden elements

### ISSUE THREAD

**Issue by carlbm** [dotnet/aspnetcore#54741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using blazor (.net7) and the virtualize component and setting the height as a parameter to the component (in my case 95). In the CSS I have both width: 95 and max-width:95 for the parent element of each 'cell'. This works perfectly. 

I've recently added a tooltip to the element (I started with matblazor MatTooltip component - which uses opacity:0 - and once I saw this issue tried manual CSS - using display: hidden - same result for both) and this has caused .. the best word I can think of is chaos. Before it reloads it scrolls okay, but as soon as it fetches the next set of data something happens; Either all of the cells go blank and the scroll bar thumb shrinks. In this state further scrolling down shrinks the thumb further, but everything is still blank. Scrolling up *sometimes* shows the top page.
The other alternative state is that it oscillates between different pages approx every second. Sometimes some of these pages have blank cells, sometimes there are no blanks, but the contents change each time it updates.

The following video has no input - this is happening on it's own

https://github.com/dotnet/aspnetcore/assets/2923969/ecdf946e-0417-4cc7-a394-0bf074e64322

### Expected Behavior

The Virtualize component should respect the 95 height and scroll as expected, no matter what I put in each element

### Steps To Reproduce

Minimal project. Go to the 'Fetch data' page and scroll down in the virtualize component 

https://github.com/carlbm/virtualize-issue

https://github.com/dotnet/aspnetcore/assets/2923969/0991e76a-c72b-445f-8d84-45c3cb5a34a5

### .NET Version

targetframework net7, built with 8.0.2000

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please provide a repro that doesn't use any third-party components, so that we can scope down the problem to Blazor only.
Note, that the Virtualize component utilizes logic to calculate the height for each element, and assumes that all the elements have the same height. If any of these requirements is not met, then you may run into unexpected behaviors: https://learn.microsoft.com/aspnet/core/blazor/components/virtualization#advanced-styles-and-scroll-detection
