### ISSUE TITLE
Programmatically set preventDefault and stopPropagation

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/aspnetcore#54782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

> We already have a way of preventing events in Blazor, but the problem is that it is very limited. The prevention only works after the event handler is over and the component rendering cycle is finished. This way it is really hard to do any advanced handling on input, like input masking for example. The existing behavior can be seen in the next example.

We need some way of setting `preventDefault` and `stopPropagation` in the event handler because falling back to javascript to write an entire function is not sufficient.

### Describe the solution you'd like

Including it in the EventArgs was rejected:

```cs
    private void onKeydown( KeyboardEventArgs args )
    {
        if ( args.Key == "a"  )
        {
            args.PreventDefault();
        }
    }
```

but some kind method call could be an alternative:

```cs
    private void onKeydown( KeyboardEventArgs args )
    {
            this.PreventDefault();
    }
```

Regardless, this has been brought up several times and is a popular issue. I believe it was closed to due the specific EventArgs implementation and not the general idea, but it wasn't clear.

This is a sorely missed for things like: making a right click menu that hands the default context menu depending on a condition, or an analog clock component in a popover that will preventDefault if you are performing a touch move event.

Even if it's not feasible to implement right now, please keep the issue open for discussion.

### Additional context

#45949 #52544 #48113 #33422 #30460 #28119 #16611

![image](https://github.com/dotnet/aspnetcore/assets/7112040/0555fde8-64ac-4783-84c2-23214f4078be)

https://github.com/dotnet/aspnetcore/issues?q=PreventDefault

**Comment by MackinnonBuck** [comment]
> I believe it was closed to due the specific EventArgs implementation and not the general idea, but it wasn't clear.

These other issues were closed because it's just _not possible_ to implement this feature in a way that will work for all of Blazor's supported execution models.

The `preventDefault` JavaScript method only has any effect when it's called synchronously, i.e., before the JavaScript event handler returns. Because Blazor supports execution models that communicate with the browser asynchronously (Blazor Server and Blazor Hybrid), the JavaScript event handler will have already completed by the time the .NET event handler runs. So, there's no possible way the .NET event handler can then travel back in time to call `preventDefault` on the original JS event.

This is why we have the `@preventDefault` directive attribute - it doesn't have the same problem as a `KeyboardEventArgs.PreventDefault()` API because it requires specifying _beforehand_ whether `preventDefault` should be called on a future JS event.

If you don't know whether you want to call `preventDefault` until you have the event data (e.g., which key was pressed), then you need to use a JavaScript event handler.

Hope this helps.

**Comment by danielchalmers** [comment]
Really a big shame but thanks for the explanation @MackinnonBuck to help me understand the situation better
