### ISSUE TITLE
Newly created page immediately switches to "Not found" page

### ISSUE THREAD

**Issue by RamType0** [dotnet/aspnetcore#54795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Newly created page immediately switches to "Not found" page

### Expected Behavior

Never switches to "Not found" page

### Steps To Reproduce

1. Open Solution at https://github.com/RamType0/BlazorSwitchesToNotFoundIssue and run it
2. Select "IssuePage" 
3. Its contents shown for very short time
4. The page switches to "Not found" page

### .NET Version

.NET 8.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will need a public repository as a minimal repro.
What we guess is happening, though is that you're missing to specify the `AdditionalAssemblies` on your Router. Let us know if that helps: https://learn.microsoft.com/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#interactive-routing

**Comment by RamType0** [comment]
> Thanks for contacting us. We will need a public repository as a minimal repro.

Sorry,I just make public the posted repository.

**Comment by MackinnonBuck** [comment]
Thanks for getting back to us. The problem is that the page gets correctly rendered statically from the server, but after interactivity starts, the client doesn't know about the existence of the page, so it displays the "not found" page. To resolve this, you could move the `IssuePage` component to the `.Client` project. Alternatively, you could update the logic [here](https://github.com/RamType0/BlazorSwitchesToNotFoundIssue/blob/f6f029ed964f8c58c8c93a410866dbfe62869431/BlazorApp1/BlazorApp1/Components/App.razor#L26) to not render the `IssuePage` with WebAssembly interactivity.

**Comment by RamType0** [comment]
> Thanks for getting back to us. The problem is that the page gets correctly rendered statically from the server, but after interactivity starts, the client doesn't know about the existence of the page, so it displays the "not found" page. To resolve this, you could move the `IssuePage` component to the `.Client` project. Alternatively, you could update the logic [here](https://github.com/RamType0/BlazorSwitchesToNotFoundIssue/blob/f6f029ed964f8c58c8c93a410866dbfe62869431/BlazorApp1/BlazorApp1/Components/App.razor#L26) to not render the `IssuePage` with WebAssembly interactivity.

Thanks, but what does `RenderModeForPage = null` mean?
