### ISSUE TITLE
PWA template

### ISSUE THREAD

**Issue by xamlsharp** [dotnet/aspnetcore#5479]
I'm extremely excited about this project, but even more so if Blazor could be integrated with the principles behind creating "Progressive Web Apps". Of course, this would mean that interop with the Service Worker would be required (among other things).

With the recent beta release of Google's Flutter, can Microsoft one-up them by using a better language with better tooling in order to create apps with an even better reach? Blazor PWA's just might be the answer...

**Comment by roboriaan** [comment]
For those who might be interested in a Blazor starter template that is cached for an offline scenario using 'Service Workers' :
[https://github.com/roboriaan/BlazorServiceWorker](url)

**Comment by danroth27** [comment]
@roboriaan Nice! Have you considered making this template available as a NuGet package so it can be installed and used from the .NET Core CLI?

**Comment by roboriaan** [comment]
@danroth27 Sure thing. I'll get cracking on it. Keep you guys posted.

**Comment by roboriaan** [comment]
@danroth27 @xamlsharp 

I've made this template available as a NuGet package :

```
dotnet new -i RC.Blazor.Hosted.Service.Worker
dotnet new blazorserviceworker
```

**Comment by roboriaan** [comment]
@danroth27 I've updated the readme. To be honest, I'm a bit unfamiliar with pull requests. I did create one. Do I just send the link?

**Comment by danroth27** [comment]
@roboriaan I meant send a PR to the https://github.com/aspnet/blazor.docs repo to update the community page with a link to your project. Once you've finished updating your readme I'm happy to help you out with that.

**Comment by roboriaan** [comment]
@danroth27. Ah I see. Awesome! That would be great if you could help me out on that. The readme file is updated.

**Comment by AngelMunoz** [comment]
Hello everyone, to add my two cents
it would be intresting to see guidance on how to tailor Blazor baset PWA's with the WinRT API.
I know in javascript if I'm running on a C#'s WebView or the visual studio 2017's pwa templates I can do the following and boom, we've got native stuff showing around:
```js
if(window.Windows) {
  const msg = new Windows.UI.Popups.MessageDialog("Hello World!");
  msg.showAsync();
}
```
I'm not sure Blazor can do this right now perhaps it can but via js interop but I bet writing full C# PWA tailoring would be nice.

Anyways if we had a PWA Template that had this kind of tailoring it could enable some future scenarios for different businesses/individual devs .

(btw, not sure if this can fit better on a different issue or this is fine)

**Comment by Difference** [comment]
Could PWA be made to have a shared cache,  "a cross domain service worker resource"?, hosted by Microsoft for the Blazor dotnet runtime?

**Comment by danroth27** [comment]
@Difference This might be just due to my ignorance about service workers, but I'mun clear what you're asking for. A shared cache for what? Hosted by Microsoft where?

**Comment by Difference** [comment]
Please let me hurry up and grab that ignoramus hat back to somebody who actually deserves it, and sorry for not explaining better.

Quick answers : 
_A shared cache_ for the Blazor.Browser.dll ,  mono.js , mono.wasm etc. files.

_Hosted by Microsoft_ at some sensible url, in the same way we can use resources such as bootstrap: 
 href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"

I had the thought, that since all Blazor Client side apps will be using the same Runtime, it could save a lot of bandwidth and cut down time where the user has to wait, if the runtime files was not downloaded once per app, but rather once per browser.

This might be achieved if the common shared Runtime, where builtin to the browser ( a possibility for Edge? ) or if the Runtime files where only downloaded if not already present in a shared browser cache, - a cache that  was not sandboxed to the individual app.

As I read the service worker documentation, it is possible to store files, fetched from a cross domain origin, so in theory, these common files could be hosted at a central location, and fetched from there.
( https://asp.net/dotnet/blazorruntime/Microsoft.AspNetCore.Blazor.Browser.dll ,  mono.js , mono.wasm etc.) **BUT** the spec does not seem to allow apps to share files cached.

I think that this idea might be very close to the thoughts behind, "foreign-fetch"
https://developers.google.com/web/updates/2016/09/foreign-fetch 
A concept that seems to have been removed from the w3c Service Worker specs ( https://github.com/w3c/ServiceWorker/issues/1188 )

Getting the files from a common MS location, would allow bugfixes, performance enhancements and general updates to the runtime to be rolled out, without the need to update the individual web apps.

There may very well be other and better schemes for solving this, but the ambition seems good to me.

**Comment by ScottRFrost** [comment]
Blazor seems to be approaching 1.0. Any word on if we're going to have an official PWA template ship with it?

**Comment by danroth27** [comment]
We expect to shift our focus from Blazor Server to Blazor WebAssembly after shipping .NET Core 3.1 later this year. As part of the Blazor WebAssembly work we expect to look at addressing PWA scenarios.

**Comment by JeroMiya** [comment]
Sounds like this is gaining traction, which is great. Might be a good time to flesh out some Blazor PWA requirements now. PWA caching is more complex than it seems, as you have to think about application and cache integrity. These are some common features provided by other front-end-frameworks with official PWA/service-worker support:

- The whole application must be cached together, and updated as one unit not individual files. For example, you never want to have a more up-to-date version of index.html but an out of date version of the mono wasm runtime. Other PWA implementations implement this with a sort of autogenerated secondary manifest file, which hashes every file in the application together to form a version hash.
- Individual file integrity: The same secondary manifest file that stores a hash of the application as a whole also needs to store the hashes of each individual file. When downloading and caching these files, the service worker needs to validate the file contents against the hash to ensure individual file integrity.
- For unhashed content, such as files from a CDN that are not available at build time, the service worker still needs to download and cache these files, but it should respect the http caching headers for those resources, for instance downloading new copies of the files when the http caching headers indicates that the cache has expired.
- The service worker should not update resources of an app that is currently running, including resources that are lazy loaded after the initial app loads (if you use a pre-fetch caching strategy). This means that the service worker may need to maintain multiple versions of the app and all resources while those tabs are open, and clean up old versions of the app when tabs are closed and no longer running.
- Error recovery on failed file hashes (plus possibly retry behavior), and other safe mode errors.
- Fail safe logic - example: deleting the secondary manifest file from the server side (thus resulting in a 404 for the secondary manifest file), should result in fail safe behavior by the service worker such as clearing all caches and de-registering itself. Additionally, a special service worker that simply unregisters itself and any other service workers that you can serve at the old service worker URL.
- Configurability to e.g. bypass the service worker caching mechanisms or change the caching policy on a file-by-file and file-globbing basis, or configuring groups of resources at once with different caching policies.

**Comment by lertoo** [comment]
The major problem is that blazor.webassembly.js loads *.DLL using xhr but not fetch API.

**Comment by SteveSandersonMS** [comment]
Done in  https://github.com/dotnet/aspnetcore/pull/18878

**Comment by vanderstack** [comment]
Any advice on how to create a new project using the template? I've downloaded Visual Studio 2019 Preview 16.6 [as advised](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-1/) however I only have options for a Blazor Server App regardless of choosing .Net Core 3.0, 3.1, or 5.0. When I click the link for 'Get additional project templates' I am taken to [the marketplace](https://marketplace.visualstudio.com/search?target=VS&category=Templates&vsVersion=&subCategory=ASP.NET&sortBy=Relevance) and searching by relevance for the term blazor doesn't return any useful suggestions.

**Comment by danroth27** [comment]
@vanderstack To use Blazor WebAssembly you need to first install the Blazor WebAssembly template from the command line, which will then get picked up by VS. See https://docs.microsoft.com/aspnet/core/blazor/get-started for the exact steps. The recent announcement blog post also covers this and creating PWA apps in more detail: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/.

**Comment by vanderstack** [comment]
Thanks for the guidance. Also, I'm amazed I heard back in under 5 minutes, you rock, and thank you for the wonderful work you are doing on this project, I've been loving development with Blazor since the 0.6 days and am so glad to hear the latest announcements that Blazor will provide a cross-platform development model in .NET 5. Go Team!
