### ISSUE TITLE
.net core 是否在Aot支持反射功能这一块

### ISSUE THREAD

**Issue by codevist-pixt** [dotnet/aspnetcore#54817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

,net core 8.0在Aot不支持使用反射这一块 希望在 .net croe 9 使用Aot的反射功能 个人觉得在.net core 6的版本的aot的反射蛮好用的

### Describe the solution you'd like

无

**Comment by martincostello** [comment]
Reflection is typically not supported in native AoT because it is fundamentally incompatible with the goals of trimming away functionality that isn't used, as the trimmer will remove things because it doesn't know they are used. This is one of the reasons why, for instance, the JSON source generator was created for (de)serialization.

I'm not aware of any plans to change this in .NET 9.

If you have further questions about native AoT and reflection you should file a new issue, in English, in the dotnet/runtime repo.
