### ISSUE TITLE
Blazor Web App - AuthorizationPolicy not found when using Global WebAssembly

### ISSUE THREAD

**Issue by forashm** [dotnet/aspnetcore#55028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to migrate to a new .net 8 blazor project and am having an issue where if I add a policy in Program.cs to check if a user is logged in with mfa, the policy cannot be found on the .razor page

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The AuthorizationPolicy named: 'MFARequired' was not found.
System.InvalidOperationException: The AuthorizationPolicy named: 'MFARequired' was not found.

If I do the exact same thing to a Blazor Web App where interactivity is set to Per Page/Component with WebAssembly, the policy works as intended. Maybe I am missing something with the new blazor types.

### Expected Behavior

The policy should exist and either allow the user entry to the page or deny access.

### Steps To Reproduce

[This repo](https://github.com/forashm/Blazor-Web-App-GlobalWebAssemblyWithIdentity ) contains a minimal project of a Blazor Web App with Global WebAssembly where Policy isn't working (My intended project type).

[This other repo](https://github.com/forashm/Blazor-Web-App-IndividualWebAssemblyWithIdentity ) contains a project where policy is working but on a per page/component interactivity type using WebAssembly 

### Exceptions (if any)

>Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The AuthorizationPolicy named: 'MFARequired' was not found.
System.InvalidOperationException: The AuthorizationPolicy named: 'MFARequired' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData, IEnumerable`1 policies)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

### .NET Version

8.0.202

### Anything else?

I used VS 2022 17.9.5 to create both projects

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're observing is by design.

What's happening in your first example, you're setting up the policy on the `server`, yet you expect the policy to be evaluated on the client, as you're trying to get it to apply in a WebAssembly interactivity mode.  In this case, once the page is loaded in the browser, the client-side router handles the requests and there is no knowledge about the policy anymore.

As for your second example, you've setup per-page interactivity mode, which forces the server router to be used, which means that the evaluation is going to happen on the server on each request. Hence, it's working.

If you call `AddAuthorizationCore` in the client project's Program.cs file, you can **also** configure the same policy and then it will work. This is important, as it will get both your server and client to be protected the same way. You can learn more about this from our docs here: https://learn.microsoft.com/aspnet/core/blazor/security/?view=aspnetcore-8.0#resource-authorization

**Comment by forashm** [comment]
This makes sense, thanks. I remember in .net 6 this was different which is why I assumed it'd be similar. Now I just need to figure out why the amr mfa claim isn't working as I have implemented the above on the client side and I get a redirect to the login page as I am assuming the policy isn't met.

**Comment by halter73** [comment]
> Now I just need to figure out why the amr mfa claim isn't working

You might need to update the [PersistingServerAuthenticationStateProvider](https://github.com/forashm/Blazor-Web-App-GlobalWebAssemblyWithIdentity/blob/74b0bc030d483d2560e8763402cefc99de652eb8/GlobalWebAssemblyWithIdentity/Components/Account/PersistingServerAuthenticationStateProvider.cs#L51-L52) in the server project and the [PersistentAuthenticationStateProvider](https://github.com/forashm/Blazor-Web-App-GlobalWebAssemblyWithIdentity/blob/74b0bc030d483d2560e8763402cefc99de652eb8/GlobalWebAssemblyWithIdentity.Client/PersistentAuthenticationStateProvider.cs#L29-L32) in the client project to serialize/deserialize the amr claim. The claims that get sent to the client using `PersistentComponentState` are opt-in since they are unencrypted unlike the claims in the authentication cookie.

**Comment by forashm** [comment]
That solved my issues. Thank you both, it is much appreciated!
