### ISSUE TITLE
Google OAuth Handler > Support full list of URI parameters

### ISSUE THREAD

**Issue by olivierboucher** [dotnet/aspnetcore#55058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The GoogleHandler doesn't support the full list of URI parameters [1].

This is inconvenient because we have to override the class if we wish to add additional parameters like `hd` for example.

[1]: https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters

### Describe the solution you'd like

Add the missing properties to src/Security/Authentication/Google/src/GoogleChallengeProperties.cs and supply them in https://github.com/dotnet/aspnetcore/blob/79ef5e329b1e31c3775a1977798253cc8f7da6cc/src/Security/Authentication/Google/src/GoogleHandler.cs#L66

Full list: https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters

**Comment by martincostello** [comment]
A new property, [`OAuthOptions.AdditionalAuthorizationParameters`](https://github.com/dotnet/aspnetcore/blob/79ef5e329b1e31c3775a1977798253cc8f7da6cc/src/Security/Authentication/OAuth/src/OAuthOptions.cs#L94), was added in .NET 9 preview 2 that allows you to add arbitrary additional parameters to the challenge URL, removing the need to override `BuildChallengeUrl()` yourself. `GoogleOptions` derives from `OAuthOptions`, so it also inherits this property.

You can see the code for how this works below:

https://github.com/dotnet/aspnetcore/blob/79ef5e329b1e31c3775a1977798253cc8f7da6cc/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L300-L337

The Google handler automatically benefits from this change because it calls its base class' implementation here:

https://github.com/dotnet/aspnetcore/blob/79ef5e329b1e31c3775a1977798253cc8f7da6cc/src/Security/Authentication/Google/src/GoogleHandler.cs#L72

**Comment by olivierboucher** [comment]
Great, thanks for the detailed answer Martin !
