### ISSUE TITLE
Captured Component reference is not set on a Component when using a Parameter

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#55317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have 2 instances of AutoCompleteDDL component on my page that uses "InteractiveServer" render mode. When I try to pass a reference of type AutoCompleteDDL to the other component via "FilterComponent" parameter, the reference is always null when I reference it in the OnAfterInputChangedAsync method, inside the AutoCompleteDDL.

Interestingly, if you create an onclick event handler on the page where the 2 components are and click the button, it will capture the components in local variables and immediately the 2nd AutoCompleteDDL FilterComponent property will be updated. If it only works this way, is there a way for me to reference one component from another?

DropDownTest1 page:

```razor
@rendermode InteractiveServer

<h3>DropDown Test1</h3>

<AutoCompleteDDL @rendermode="InteractiveServer" @ref="parent"></AutoCompleteDDL>
<AutoCompleteDDL FilterComponent="parent" @rendermode="InteractiveServer" @ref="child"></AutoCompleteDDL>

@code {
	private AutoCompleteDDL parent;
	private AutoCompleteDDL child;

}
```

AutoCompleteDDL component:

```razor
[Parameter]
public AutoCompleteDDL FilterComponent { get; set; }

<input @bind:after="OnAfterInputChangedAsync"/>

async Task OnAfterInputChangedAsync()
{
	if (FilterComponent is { })
		{
                       // reference is null, always
			Console.WriteLine($"we have a reference to the parent component");
		}
}
```

### .NET Version

.net 8 Blazor

**Comment by SteveSandersonMS** [comment]
The `@ref="parent"` directive attribute will cause `parent` to be populated with the component instance **when the child component is created** but not before (naturally, the value cannot be set before the value is instantiated).

Since child components are instantated after the parent has rendered, they are not available until the parent has rendered. The code sample you give is trying to read the reference before the parent has finished its first render, which cannot work.

What I would recommend is not trying to pass a reference to a sibling component, but instead have your component pass itself to the child, e.g.:

```razor
<AutoCompleteDDL FilterComponent="@this" />
```

Then the child component can access whatever it needs on the parent. The parent can even expose properties that give access to other child components of the same parent.

**Comment by SteveSandersonMS** [comment]
Additionally, you should remove `@rendermode="InteractiveServer"` from the child component declaration since the parent is already using this rendermode.
