### ISSUE TITLE
Security Claims not Identifying Expiration Time.

### ISSUE THREAD

**Issue by gentcod** [dotnet/aspnetcore#55333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created this claim: `var claims = new List<Claim>
{
    new(ClaimTypes.Name, user.Name),
    new(ClaimTypes.Email, user.Email),
    new(ClaimTypes.Expiration, JsonSerializer.Serialize(DateTime.Now.AddHours(12)), ClaimValueTypes.Date),
    new("userId", user.UserId),
};`

I noticed I was getting this error.

Also want to point out that I added extra validation using this: `var token = new JwtSecurityToken(
    issuer: null,
    audience: null,
    claims,
    expires: DateTime.Now.AddHours(12),
    signingCredentials: creds
);`

### Exceptions (if any)

Microsoft.IdentityModel.Tokens.SecurityTokenNoExpirationException: 'IDX10225: Lifetime validation failed. The token is missing an Expiration Time. Tokentype

### .NET Version

8.0

**Comment by martincostello** [comment]
It _might_ be that the IdentityModel library validating the generated token is expecting the Expiration claim to be Unix-epoch seconds/milliseconds, rather than a string/Date.

**Comment by gentcod** [comment]
So it has a funny behavior, when I remove the last claim, it works but when I make any other changes it doesn't. So my assumption is that it is not specifically identifying the expiration claim

I also have to specify the expiration in the claim as well as in the token for it to work.

**Comment by halter73** [comment]
The string produced by `JsonSerializer.Serialize(datetime)` is invalid for the `exp` claim, but `ClaimTypes.Expiration` is `http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration` rather than `exp`, and I think only `exp` matters, so the bad serialization might not matter.

I found a similar problem on StackOverflow at https://stackoverflow.com/questions/78189589/asp-net-core-8-0-jwt-validation-issue-securitytokennoexpirationexception-despit where the resolution was to remove the explicit Microsoft.IdentityModel.Tokens 7.4.1 reference fixed it. I'm not sure why that would be, but I know mixing versions of Microsoft.IdentityModel... packages can lead to problems in some cases.

I know that `JsonWebToken` is the newer, better version of `JwtSecurityToken`, so maybe switching the token creation logic to use `JsonWebToken` would help. See https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events. To get a full understanding of what's going on, we'll need a full repro project hosted on GitHub to look at.

@jennyf19 Do you have any idea what's going on here?

**Comment by gentcod** [comment]
@halter73 this is the link to the [repo](https://github.com/gentcod/Foodie). Kindly reference the token generator [tokenGenerator](https://github.com/gentcod/Foodie/blob/review/API/Token/JwtTokenGenerator.cs) and the middleware that handles authentication [authMiddleware](https://github.com/gentcod/Foodie/blob/review/API/Middleware/AuthMiddleware.cs).

NB: The code might burn your eyes, but it's alright 😅

**Comment by halter73** [comment]
@gentcod Thanks for linking to repro, but it is not minimal for us to take a look at. It requires configuring DB connection strings, issuer keys, and registering a user with Identity even though the `UserController` only exposes a login endpoint with no registration.

A minimal repro shouldn't need Identity, a database, or any outside configuration even for something like the `IssuerSigningKey`. A random value could be used for the key. Ideally, the app should `Console.WriteLine(new JwtSecurityTokenHandler().WriteToken(token));` just before starting the `WebApplication`, and expose a single endpoint that requires auth to test the JWT against.
