### ISSUE TITLE
net8 Razor Pages Web App with Blazor Component. Component not working from csthml page 

### ISSUE THREAD

**Issue by igsuffolk** [dotnet/aspnetcore#55415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Component not rendering when render-mode="Server"
Does render with render-mode="ServerPrerendered" but no  interaction as expected.

New Asp Net Core App with Razor pages.
Add Blazor functionality as per
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0

This functionality was working before .net8

If I browse route directly to /BlazorTest it works as expected.

### Expected Behavior

Server Interaction expected.

### Steps To Reproduce

index.cshtml
```
@page
@using TestApp.Components.Pages

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <component type="typeof(BlazorTest)" render-mode="Server" />
</div>
```
Component BlazorTest
```
@page "/BlazorTest"
@rendermode InteractiveServer

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<input id="input1" class="form-control" @bind="input1"/>
<button class="btn btn-primary" @onclick="Save">Save</button>
<label class="form-label">@stringInput</label>

@code {
    private string input1;
    int currentCount = 0;
    string stringInput = "";

    void IncrementCount()
    {
        currentCount++;
    }
    void Save()
    {
        stringInput = input1.ToString();
    }
}
```

### .NET Version

8.0.4

**Comment by guardrex** [comment]
👁️ on this in case an article update is in order after investigation.

**Comment by igsuffolk** [comment]
Git Repo created at https://github.com/igsuffolk/WebApplication1

**Comment by igsuffolk** [comment]
Simple project as asked for. Created new from VS2022 template.

Index.csthml has the component added.

Components/Pages/BlaxorTest is the Blazor component

Blazor component is not rendered on index page.

If browsed directly (/BlazorTest) it works as expected.

**Comment by javiercn** [comment]
@igsuffolk Your project is not correctly configured.

https://github.com/igsuffolk/WebApplication1/blob/main/Program.cs#L28-L29

You only call `MapRazorComponents` when your entire app is component based (Blazor Web). In your case, you need to keep using `MapBlazorHub` directly and add the Blazor Server script to your `_Layout.cshtml` as done in previous versions or migrate from controllers/mvc to Blazor web if you want to take advantage of specific new features.

**Comment by guardrex** [comment]
Sorry to comment on a closed issue, ***but*** ....... I can't repro a problem with our guidance on this ...

![image](https://github.com/dotnet/aspnetcore/assets/1622880/4c649683-5432-4481-ab0b-65e280204f5b)

@MackinnonBuck and I chatted about the section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#use-non-routable-components-in-pages-or-views

... briefly at that time (specifically about the need for a no-op `App` component to make it work), and I think (along with @danroth27 looking :eyes:) that it was approved for publication in the form that you see it in the article. The guidance doesn't match what you just said, @javiercn. The approach doesn't rely on `MapBlazorHub`, nor does it use the Blazor Server script (it uses the BWA script).

Perhaps only temporarily, I've closed the docs issue because I don't have actionable changes to make at this time. 

@igsuffolk ... I took a peek at your repro app. That doesn't match our guidance. For example, we require a no-op `App` component, but you have an `App` component that looks like you are trying to (or starting to) perform a full conversion from an RP app over to a BWA app (i.e., your `App` component file isn't empty). See the section that I linked for details :point_up:.

**Comment by igsuffolk** [comment]
Thanks,
I did read the guidance
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0

However if you read logically from the top then get to the section which is the solution I was looking for (Enable interactive server-side rendering (interactive SSR). In my way of thinking, that was the solution.
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#enable-interactive-server-side-rendering-interactive-ssr

**Comment by guardrex** [comment]
It ***tries*** to avoid that problem in the article's opening section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#razor-component-integration

... which is meant to get the reader to the section that covers their scenario by stating (emphasis added) ...

> Use the guidance in the following sections ***depending on the project's requirements***:

The plan was for you to see that bullet 2 matches your scenario, and then you'd click the link in bullet 2 to jump down to that section. Well ... *that didn't work* 😢😄.

Besides further changes to the opening remarks, this article could be split into four articles, which would be an overview to orient the reader to one of the three scenarios (one of three other articles in a sub-node).

I'll re-open your docs issue with a new title to take a look either way: Either I'll make further modifications to the lead-in section to make it clear that the reader should go to ***one*** of the cross-linked sections, or I'll see about splitting up the article into a node of articles.

It seems like the guidance is OK 🤞🍀 at this time. You can try to follow that section as it's described, ignoring the rest of the article, to see if you can update your app and get it running. If it doesn't work, I recommend that we take it up again on a new docs issue that you should open from the bottom of that article. Your current issue over there that I'm about to re-open will be set up to only focus on the article layout/sections, so we'd work from a new issue. The reason that I threw you over here to the product unit was that I thought that you did follow the guidance in that section and something more sinister was going on in the framework 😈. As it turns out, the wrong guidance was in play.

**Comment by igsuffolk** [comment]
This title "Add Blazor support to an ASP.NET Core app" threw me then, since that was what I was looking for initially. 

I have followed the section you reference and the app is working as expected.👍

**Comment by guardrex** [comment]
🎉 Great! I'm glad that aspect on the app failing is resolved.

Yes, I think work should be done to at least clarify the remarks of the opening section. Breaking out the sections into articles is on the table tho. I'll chat with Dan about it when I reach that issue, which should be within a week or two.

**Comment by MatrixRonny** [comment]
> Git Repo created at https://github.com/igsuffolk/WebApplication1

Here is the code after applying the changes mentioned in this thread:
https://github.com/MatrixRonny/RazorPagesWithComponents

I would like to note that the documentation fails to mention that the following code must be present:
```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

This code, usually found in `_ViewImports.cshtml`, effectively enables use of `<component>` tag in Razor Pages.
