### ISSUE TITLE
Deprecation notice for Microsoft.AspNetCore.Http package, provider of IFormFile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55430]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Deprecation-notice-for-MicrosoftAspNetC/10559521)._

---
[regression] [worked-in:17.8.4]
I created a recent project and Visual Studio 2022 reported that the Microsoft.AspNetCore.Http package, which has the IFormFile Interface, is deprecated. Is there any new way to represent a file sent with HttpRequest? If so, is it documented?

---
#### Feedback Bot on 1/11/2024, 07:02 PM: 

(private comment, text removed)

**Comment by martincostello** [comment]
These types are now included in the [ASP.NET Core Shared Framework](https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework) since .NET Core 3.0.

You should remove the package reference and use `<FrameworkReference Include="Microsoft.AspNetCore.App"/>` instead.
