### ISSUE TITLE
Server-side: handle reconnection to different server

### ISSUE THREAD

**Issue by chris-ray** [dotnet/aspnetcore#5562]
If after a delay, or a lost network connection the websocket disconnects. It seems it will never reconnect.

![image](https://user-images.githubusercontent.com/4673182/43357925-3038f85a-924f-11e8-981f-1b5cc50086c1.png)

**Comment by Brunni** [comment]
Perhaps I missed it, but is there at least a way to show the user, that he is disconnected from the server? Perhaps with the possibility to reload the page (with loosing the state)?

**Comment by JohnKiller** [comment]
Since #8177 has been closed and this issue is now in the backlog, if I want to start using Blazor, how should I prepare for this feature when it will be available? Because if the user state needs to be serializable, this must be a key  decision during initial application design.

My concern is that if I implement blazor right now, when this issue gets fixed it will be implemented in a way that is incompatible with whatever I came up with. How should one proceed? Load balancing is a very critical scenario for any decent sized application, so it's my primary concern

**Comment by mv10-work** [comment]
An `IDistributedCache` implementation makes state-persistence a fairly trivial problem to solve, as long as the application is designed for it up front. In our case, we set up a request-scoped abstract class keyed on a user identifier (OIDC subject ID, since we have no anonymous-access users), then the apps derive from this to manage various bits of app-specific `<TState>` data (high-level, like navigation location), which is restored upon the initial connection (driven by persistent OIDC login, but any cookie-stored unique ID would work -- check it in an `OnGet` for `_Host` where you still have `HttpContext` and go from there). Caching is handled automatically by that base class.

Business-level data is persisted directly to the `IDistributedCache` (optionally DPAPI-protected) instead of being stored in `<TState>`. We have a rule that no sensitive data can be persisted as app state which eliminates encryption overhead.

We're hoping this type of implementation will make it easier to switch to whatever solution eventually becomes the official answer. Of course, having access to the Blazor client internals would allow such a system to explicitly identify "reconnect" versus "quit and restart" restoration behavior, but we apply an arbitrary expiration policy (ex. 5 minutes) to the startup state-restoration decision.

I like most of the ideas from @TheFanatr but I'd rather see a new API have a name other than `Session` simply because ASP.NET session-state has such a long history of being discouraged for many good reasons, whereas any non-trivial Blazor SS app virtually _requires_ this for entirely different reasons unrelated to session-style convenience.

**Comment by fiha8** [comment]
I hope I haven't miss something, but I was searching a lot, still haven't found a solution for this issue. 
Is there already any decent solution? 

This is an serious thing, I guess no one can release the app where user is getting such an error and have to refresh the page to continue working with the app.

**Comment by mkArtakMSFT** [comment]
This is going to be addressed as part of https://github.com/dotnet/aspnetcore/issues/30344
