### ISSUE TITLE
Explicitly calling `context.Fail(....)` in authorization policy requirement handler results in empty `policyAuthorizationResult.AuthorizationFailure.FailedRequirements`

### ISSUE THREAD

**Issue by Xor-el** [dotnet/aspnetcore#55673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling _`context.Fail(....)`_ in our _`Authorization`_ policy requirement handler causes _`policyAuthorizationResult.AuthorizationFailure.FailedRequirements`_ to be **empty** when our _`Authorization`_ fails.

### Expected Behavior

_`policyAuthorizationResult.AuthorizationFailure.FailedRequirements`_ should not be **empty** when _`Authorization`_ fails regardless of whether we call _`context.Fail(....)`_ in our policy requirement handler or not.

### Steps To Reproduce

1. Clone this [repo](https://github.com/Xor-el/AuthBugDemo), build and run.

2. Initiate the request below using _`cURL`_, notice we get a _`401 Unauthorized`_ response.

```curl
curl --location 'https://localhost:7244/authbugdemo/implicit-fail' \
--header 'Content-Type: application/json' \
--header 'X-API-Key: BadAPIKey' \
--data '{
    "name": "Chucky",
    "description": "Child'\''s Play is an American slasher media franchise created by Don Mancini."
}'
```

3. Initiate the request below using _`cURL`_, notice we get a _`403 Forbidden`_ response.

```curl
curl --location 'https://localhost:7244/authbugdemo/explicit-fail' \
--header 'Content-Type: application/json' \
--header 'X-API-Key: BadAPIKey' \
--data '{
    "name": "Chucky",
    "description": "Child'\''s Play is an American slasher media franchise created by Don Mancini."
}'
```

4. the difference between the two endpoints are their _`Authorization`_ policy requirement [handlers](https://github.com/Xor-el/AuthBugDemo/tree/main/Authorization/Policy/RequirementHandlers/ApiKey).

    The [_`implicit-fail`_](https://github.com/Xor-el/AuthBugDemo/blob/main/Authorization/Policy/RequirementHandlers/ApiKey/ApiKeyImplicitFailRequirementHandler.cs) endpoint policy requirement handler doesn't call _`context.Fail`_ if authorization fails. however, the [_`explicit-fail`_](https://github.com/Xor-el/AuthBugDemo/blob/main/Authorization/Policy/RequirementHandlers/ApiKey/ApiKeyExplicitFailRequirementHandler.cs) endpoint policy requirement handler calls _`context.Fail("....")`_ when authorization fails.

5. I have an [_`IAuthorizationMiddlewareResultHandler`_](https://github.com/Xor-el/AuthBugDemo/blob/main/Authorization/AuthorizationResultTransformer.cs) implementation that checks if the failed requirement is of a particular type using _`policyAuthorizationResult.AuthorizationFailure.FailedRequirements`_ and modifies the response status code appropriately.

unfortunately, _`policyAuthorizationResult.AuthorizationFailure.FailedRequirements`_ is always empty when we use the [_`explicit-fail`_](https://github.com/Xor-el/AuthBugDemo/blob/main/Authorization/Policy/RequirementHandlers/ApiKey/ApiKeyExplicitFailRequirementHandler.cs) policy requirement handler that calls _`context.Fail("....")`_.

I don't see this behaviour documented anywhere so I assume it's a bug.
If it is an expected behaviour (this would be strange :confused:), then how do we propagate the failure reason from the various policy requirement handlers to my [_`IAuthorizationMiddlewareResultHandler`_](https://github.com/Xor-el/AuthBugDemo/blob/main/Authorization/AuthorizationResultTransformer.cs) without calling _`context.Fail("....")`_?

### .NET Version

8.0.200

**Comment by juchom** [comment]
I'm just hitting the same issue.

There is nothing in the doc about this behavior : https://learn.microsoft.com/en-us/aspnet/core/security/authorization/customizingauthorizationmiddlewareresponse?view=aspnetcore-8.0

**Comment by juchom** [comment]
Ok, so after digging a bit more I found this :

When we call Fail, the authContext properties are `HasSucceeded` is `false` and `HasFailed` is `true`
When we don't call Fail, the authContext properties are `HasSucceeded` is `false` and `HasFailed` is `false`

In the first case we go to line 20
In the second case we go to line 21

https://github.com/dotnet/aspnetcore/blob/e47c15abd3ae87aff8e04af5dac44847844460b9/src/Security/Authorization/Core/src/DefaultAuthorizationEvaluator.cs#L16-L21

Line 20 goes to this

https://github.com/dotnet/aspnetcore/blob/e47c15abd3ae87aff8e04af5dac44847844460b9/src/Security/Authorization/Core/src/AuthorizationFailure.cs#L44-L49

Line 21 goes to this

https://github.com/dotnet/aspnetcore/blob/e47c15abd3ae87aff8e04af5dac44847844460b9/src/Security/Authorization/Core/src/AuthorizationFailure.cs#L56-L57

So the question is why in case 1 static AuthorizationFailure.Failed is not taking a second argument with the failed requirements ?

**Comment by halter73** [comment]
`AuthorizationHandlerContext.Success(IAuthorizationRequirement requirement)` takes a requirement while `AuthorizationHandlerContext.Fail(AuthorizationFailureReason reason)` takes a reason (or nothing if you call `Fail()`). 

`PolicyAuthorizationResult.AuthorizationFailure.FailedRequirements` returns an `IEnumerable<IAuthorizationRequirement>`, but you did not provide any `IAuthorizationRequirement` when you called `Fail(AuthorizationFailureReason reason)`, and there's no special stateful logic in `AuthorizationHandlerContext` to keep track of what requirement is being checked when `Fail(AuthorizationFailureReason reason)` or `Fail()` is called. These methods have no idea if any requirement is being checked at all when they get called.

You might think that `FailedRequirements` should include any requirement that didn't explicitly succeed (i.e. `AuthorizationHandlerContext.PendingRequirements`) like it does in the case when fail wasn't explicitly called, but this could easily be incorrect. It's very likely that whatever cased fail to be called made it impossible to check whether the pending requirements were actually checked or not. This is particularly true if `AuthorizationOptions.InvokeHandlersAfterFailure` is set to `false`, but that's not the only way this could happen.

By calling `AuthorizationHandlerContext.Fail` without any `IAuthorizationRequirement`, you're telling the `DefaultAuthorizationEvaluator` that the authorization failure was unrelated to the requirements. That's why the [doc comments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationhandlercontext.fail?view=aspnetcore-8.0) tell you that it is "Called to indicate [HasSucceeded](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationhandlercontext.hassucceeded?view=aspnetcore-8.0#microsoft-aspnetcore-authorization-authorizationhandlercontext-hassucceeded) will never return true, *even if all requirements are met*." (emphasis mine). So, you're telling the system whether or not the `ApiKeyExplicitFailRequirement` succeeded is irrelevant to the failure.

You'll notice that we never call `AuthorizationHandlerContext.Fail` in our [conceptual authorization docs](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0). We also don't call it internally anywhere in our framework either because the only reason a built-in `AuthorizationHandler` can fail is because a requirement wasn't met. It might make sense to call `Fail` if the reason authorization failed is something more than simply not meeting a requirement like a backend identity provider going down, but that's not a concern for any of the built-in `AuthorizationHandler`'s that only need to verify data already contained within the `ClaimsPrincipal` meets the expected requirements.

Why do you need to call `AuthorizationHandlerContext.Fail`? If you need to communicate details to the `IAuthorizationMiddlewareResultHandler` why authorization failed beyond the requirement simply not being met, why not check `PolicyAuthorizationResult.AuthorizationFailure.FailureReasons` instead?

The example given of an API key being invalid seems more like an authentication failure than an authorization failure anyway. I'd expect that to be reported by an API key `IAuthenticationHandler` in `AuthenticateAsync()` using `AuthenticationResult.Fail(string failureMessage)`.

**Comment by juchom** [comment]
Thanks @halter73, 

If I understand it correctly, when we write an AuthorizationHandler we have to follow this rules :

Succeed : means "Ok, this handler has met the required condition"

No call : means "This handler has not met the required condition"

Fail : means "An error has happened that prevent the handler to conclude if it succeeded or not"

**Comment by halter73** [comment]
No problem. Your understanding looks correct to me.

**Comment by Xor-el** [comment]
Thanks @halter73 for the clarification. 
Apologies for the late response.

**Comment by Pilchard123** [comment]
@halter73 Would it be worth uipdating the docs to be a little clearer, maybe with something like @juchom 's text? I've just been trying to work out exactly what this issue is about; I called `context.Fail()` becuase I wanted to be certain that, no matter what, if a particular branch in the handler was hit then the requirement would never be satisfied. I'm not unable to tell if it has or not, I _know_ at this point that it must not be satisfied some other way.

In fact should there be a `.Fail()` (that acts like what people in this thread thought it did) and `Error` for cases that the current `Fail` covers? For the sake of not breaking compatibility, maybe they could be called `Fail` - which behaves as it currently does - and something like `NeverSatisfy`, for "this requirement should not be satisfied, even if another handler thinks it should be".

For a possible use-case - consider [the example in the docs](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0#why-would-i-want-multiple-handlers-for-a-requirement). But imagine there was a reason a certain group wasn't allowed into a building at all, even as a guest (maybe for clean-room reimplementation reasons - the group writing the new code cannot be allowed in the same building as the group reverse engineering). The BadgeEntryHandler could check "is the bearer of this badge barred from entering", and force a fail even if they have a guest badge that would otherwise let them through.
