### ISSUE TITLE
UseRateLimiter() does not work when called after UseMvc()

### ISSUE THREAD

**Issue by Blackbaud-NickGlyder** [dotnet/aspnetcore#55826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding the new dotnet 8 rate limiting middleware to an application, the rate limiting policies are not applied if the middleware is registered after calling `.UseMvc()`.

Example configuration of an `IApplicationBuilder`

```csharp
        public static IApplicationBuilder ConfigureBuilder(this IApplicationBuilder builder)
        {
            builder
                .UseRouting()
                .UseMvc()
                .UseRateLimiter()  // <== Rate limit policies not applied
                .UseEndpoints(app => app.MapControllers());

            return builder;
        }
```

Moving the call to `.UseRateLimiter()` to before `.UseMvc()` applies rate limiting policies as expected. 

### Expected Behavior

I would expect the rate limiting middleware to be run in this scenario, or if not, an explanation of why this ordering matters would be helpful. 

### .NET Version

8.0.205

**Comment by martincostello** [comment]
Middlewares execute in the order are defined in the application's pipeline.

By putting rate limiting after MVC, requests to controllers will never reach the rate limiting middleware because MVC will have already written to the HTTP response and end the request pipeline. Effectively, it's too late to rate limit because the processing has already happened.

You should register the rate limiting middleware before the middlewares you wish to protect with it.
