### ISSUE TITLE
Microsoft.AspNetCore.Components.NavigationException:“Exception_WasThrown”

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/aspnetcore#55831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Microsoft.AspNetCore.Components.NavigationException:“Exception_WasThrown”
[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/15400593/BlazorApp1.zip)
Can you tell me if this is the right way to write? How to solve the login jump exception， Thank you
![image](https://github.com/dotnet/aspnetcore/assets/30250585/98c12286-5be7-4a99-90b3-f9985fd4a1da)
![image](https://github.com/dotnet/aspnetcore/assets/30250585/98a4c056-c3cc-4e4c-9fb3-e1126b08aacd)

### .NET Version

8.0.300

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. `NavigationException` does not indicate an error, but instead signals to the framework that a redirect should occur. Are you seeing this error because it's being caught in your own code?

Also, if you think this is a bug in the framework, please provide us a minimal repro project, hosted on GitHub as a public GitHub repository. We're not able to download zip files from issues. Thanks!

**Comment by HuaFangYun** [comment]
https://github.com/HuaFangYun/Blazor-Navigation-Bug    @MackinnonBuck  Thanks!

**Comment by HuaFangYun** [comment]
At present, I see that there is no problem with a template to write in this way, but there is a problem when I use this way. Can you help me point out how to correct the writing method? can the program run normally? Thank you very much

**Comment by halter73** [comment]
> but there is a problem when I use this way. Can you help me point out how to correct the writing method? can the program run normally? Thank you very much

Sorry, this got lost. The "Resolution: Answered" removes it from our triage queries, but our bot did not auto close this for some reason.

To answer your question, you cannot navigate to another page during static rendering without redirecting and loading the page from scratch, so there's no way the program to continue to "run normally". You need to design your app to work even when the page you're navigating to is loaded from scratch. This is important even without a call to `NavigationManager.NavigateTo` during static rendering in case someone manually (re)loads address.

If you change [`<Routes @rendermode="@RenderModeForPage" />`](https://github.com/HuaFangYun/Blazor-Navigation-Bug/blob/4bb2a4e699df7d87c6a9d903d402de1fcd733e23/Components/App.razor#L16) to just `<Routes @rendermode="@InteractiveServer" />`, the login page will render interactively rather than statically and `NavigationManager.NavigateTo` will not throw an exception or load the new page from scratch, but you will not be able to set cookies which is probably something you'd want a login page to do.
