### ISSUE TITLE
OpenIdConnectAuthenticationHandler: message.State is null or empty

### ISSUE THREAD

**Issue by merijndejonge** [dotnet/aspnetcore#55910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using Microsoft Identity and and Microsoft Entra as external identity server. I'm using AddOpenIdConnect to set it all up. Everything works perfectly fine except when Microsoft is making a callback as a result of granting tenant-wide admin consent for my app.
This callback is not handled correctly and issues the following Exception:
[2024-05-25` 22:22:08 ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
```
 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
````
Tenant-wide admin consent is granted using the URL https://login.microsoftonline.com/{organization}/adminconsent?client_id={client-id} as documented at https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent?pivots=portal#construct-the-url-for-granting-tenant-wide-admin-consent.

It triggers the following callback to my identity server:

````
https://<my-server>/signin-microsoft?admin_consent=True&tenant=<teant-id>
````
The path `/signin-microsoft` is correct and according to my setup.

As a result the sysadmin who want to give tenant-wide consent to my app will get an error from my backend as a result. Obviously, this is not desired.

### Expected Behavior

The expected  behaviour is that the sys admin will get as normal HTTP 200 response to indicate success.
Or else, there should be an option that my backend can handle the request and returns a HTML result page or something. 

### Steps To Reproduce

Open the URL `https://<my-server>/signin-microsoft?admin_consent=True&tenant=<teant-id>` in a browser to trigger the exception.

### Exceptions (if any)

---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

net8.0

**Comment by merijndejonge** [comment]
You can use the blazor sample 
- https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc

Which is recommended by MS (https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern)

- In the folder `blazor-samples-main/8.0/BlazorWebAppOidc/BlazorWebAppOidc`, run `dotnet run`
- Then, in a web browser, open the URL `https://localhost:5001/signin-oidc?admin_consent=True&tenant=some-tenant-id`

This will trigger the following log:
````
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
       ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: OpenIdConnectAuthenticationHandler: message.State is null or empty.
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by halter73** [comment]
I'll see what we can do to improve OpenIdConnectAuthenticationHandler and/or our Blazor documentation to avoid this issue with tenant-wide admin consent.

It's a little surprising that it's reusing the signin redirect URI (e.g. `/signin-microsoft` or `/signin-oidc`) URL when redirecting after admin consent rather than a URL that's unique from signin designed to handle admin consent completing for that application. I wonder if it's because you aren't specifying a `redirect_uri` and you only have the signin redirect URI registered in the app registration portal, so Entra just uses that.

Looking at the documentation from https://learn.microsoft.com/en-us/entra/identity-platform/v2-admin-consent#request-the-permissions-from-a-directory-admin, it seems like they show it redirecting back to a unique `/permissions` endpoint which is specified via a`&redirect_uri` query param in the original `https://login.microsoftonline.com/{tenant}/v2.0/adminconsent?client_id=...` URL. The docs claim you can use any `redirect_uri` registered in the app registration portal, so your best bet might just be able to fix your issue by registering a new `/permissions` URI in the portal, specifying that as your `redirect_uri`, and writing a custom endpoint to handle the `/permissions` request.

Another thing to consider is to try using [`AddMicrosoftIdentityWebApp`](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-app-sign-user-app-configuration?tabs=aspnetcore#initialization-code) instead of using `AddOpenIdConnect` and `AddCookie` directly. It adds a bunch of [customizations on top of AddOpenIdConnect and AddCookie](https://github.com/AzureAD/microsoft-identity-web/blob/3e682e9a1111232deb476f87dfd1b369af651d59/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L295) that would probably provide better integration to non-standard features provided by Entra, although I'm not sure if it specifically accounts for this.

If you have to use the signin redirect URI to handle this the admin consent redirect, you can set [OpenIdConnectOptions.SkipUnrecognizedRequests](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions.skipunrecognizedrequests?view=aspnetcore-8.0) which should avoid this error. If you want to redirect back to a specific page in this case, you can configure an [OpenIdConnectOptions.Events.OnMessageReceived](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents.onmessagereceived?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-openidconnect-openidconnectevents-onmessagereceived) callback that calls `messageReceivedContext.SkipHandler()` after calling `httpContext.Response.Redirect(wherever)` itself.

You can find the relevant code in the handler that's throwing the `AuthenticationFailureException`. You can see 

https://github.com/dotnet/aspnetcore/blob/0ffc29649a8047ad969445fd185450892b3fc75b/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L579-L602

**Comment by merijndejonge** [comment]
Thanks for the clear explanation.
I wasn't aware of the redirect_uri because it wasn't mentioned in the example thatI referred to (https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent?pivots=portal#construct-the-url-for-granting-tenant-wide-admin-consent)

Since the grant-admin-consent URL is the be used by my clients it is pretty fragile to also request them to use the redirect_uri. My proposal therefore would be to make redirect_uri optional and do nothing in case this parameter is absent in the grant-admin-consent request. This, in my view, is the most robust and best way.

To make the current approach robust and customer-friendly I must make available an open endpoint just for the redirect_url. This is not only inconvenient and undesired, opening an unauthenticated endpoint is also not optimal from a security point of view because anyone can use this unnecessary endpoint.

I've also tried the SkipUnrecognizedRequests approach. This, indeed, prevents the exception but it gives a general 404 error, which is also not a customer-friendly solution.

In order to combine it with the OnMessageReceived  suggestion, I need a bit more help. Do you suggest to check in the OnMessageReceived  handler wether the request URL contains something like "signin-oidc?admin_consent=True" and then change this URL to public accessible page, like /permissions as in the example?

**Comment by merijndejonge** [comment]
any news/updates on this?

**Comment by halter73** [comment]
Sorry for the delay. I still haven't personally tried granting tenant-wide admin consent, but the issues you've run into don't seem like show stoppers.

> Since the grant-admin-consent URL is the be used by my clients it is pretty fragile to also request them to use the redirect_uri. My proposal therefore would be to make redirect_uri optional and do nothing in case this parameter is absent in the grant-admin-consent request. This, in my view, is the most robust and best way.

I don't understand this. You must be generating a link for clients to click on, right? Wouldn't they run into bigger issues if there was a typo in the `client_id`? I don't see how making sure the link has the right `redirect_uri` is any more fragile. They're both query string parameters.

> In order to combine it with the OnMessageReceived suggestion, I need a bit more help. Do you suggest to check in the OnMessageReceived handler wether the request URL contains something like "signin-oidc?admin_consent=True" and then change this URL to public accessible page, like /permissions as in the example?

On further thought, if I really couldn't specify a `redirect_uri`, I would probably just do this in middleware that I put in front of `UseAuthentication()`. You could simply rewrite `HttpContext.Request.Path` to point to `/permisions` if you see a request to `signin-oidc?admin_consent=True` if you put your middleware before `UseRouting()` too. Otherwise, you could just redirect.

You could do this in `OnMessageReceived` instead. I don't see any real problems with it. Is there some reason you didn't want to do this?

**Comment by merijndejonge** [comment]
Thanks for the detailed remarks.

The approaches you propose do work, but don't make a lot of sense in my opinion:
- Using a consent link for customers with a redirect_url
   - makes the link more complicated than necessary for my customers. Please understand that using a consent link is already something many of them are not familiar with and triggers concerns. That there will be a callback from there environment to mine, will make matters worse. In particular, since there is no clear need for this call back.
   - as explained earlier, the redirect url adds more room for making mistakes. This doesn't add tp customer satisfaction.
   - In my case, I don't generate the link. Customers must construct the link themselves and fill in their own {organization}. 
   - as also explained earlier, the redirect url requires that I add an unauthenticated endpoint to my system. This is undesirable. In particular since there is no need for it.
- Handling the callback url in middleware or in OnMessageReceived etc. adds complexity to my backend. In particular since the callback doesn't serve a clear purpose, this is undesirable.

What would greatly help is to make the following changes:
- Make the redirect url optional. If it isn't used, then do nothing
- Create a dedicated input field in the Entra portal where app builders can specify a valid redirect url for admin consents

**Comment by halter73** [comment]
> What would greatly help is to make the following changes:
> 
> * Make the redirect url optional. If it isn't used, then do nothing
> * Create a dedicated input field in the Entra portal where app builders can specify a valid redirect url for admin consents

Thanks for the detailed bug report and recommendations. Unfortunately, these two changes would need to be made to the Entra backend and not the aspnetcore libraries we ship out of this repo. I recommend submitting this feedback to https://feedback.azure.com/d365community/forum/22920db1-ad25-ec11-b6e6-000d3a4f0789

I wonder if you would have gotten better behavior if you used `AddMicrosoftIdentityWebApp` instead of `AddOpenIdConnect`. I considered keeping this issue open to track looking for `admin_consent` in the query string and giving a better error about needing to write code to handle the tenant-wide admin consent redirect, but this does not appear to be part of any OIDC or OAuth standard, and I don't want to special-case logic like that specifically just for Entra in the standard `OpenIdConnectAuthenticationHandler`.

If using `AddMicrosoftIdentityWebApp` still has the same issues (and I suspect it probably will since it does rely on the `OpenIdConnectAuthenticationHandler`), https://github.com/AzureAD/microsoft-identity-web would be a better place to file this issue.
