### ISSUE TITLE
Lazy Loading separate Razor Class Library project in Blazor Web App

### ISSUE THREAD

**Issue by LEXEnprise** [dotnet/aspnetcore#55985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

For bigger solutions, it is really impotant to separate or modulazired your UI. It is something like supporting Micro FrontEnds wherein you can create separate RCL project/s but load it on request basis not included during building of the application.

**Comment by ElderJames** [comment]
I also want it to be able to automatically chunk every page and components at compile time, which makes the first load faster.

**Comment by javiercn** [comment]
@LEXEnprise thanks for contacting us.

We already have a feature for that called Lazy loading, where you can mark dlls as lazy and won't get downloaded until you request them.

If you are talking about having some sort of dynamic dependency where your app doesn't even reference the library, that will never work because of trimming. The app needs to see the transitive closure of its entire dependency graph to trim correctly, so this is not something a direction we plan to go.

@ElderJames this won't help, the cost is mostly on having to bring the .NET runtime, not on your component/libraries.
