### ISSUE TITLE
blazor.web.js is deprecated for pagespeed Lighthouse

### ISSUE THREAD

**Issue by GajaLab** [dotnet/aspnetcore#56081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Lighthouse pagespeed analyses, considered by Google in SEO positioning, the blazor.web.js file is deprecated

### .NET Version

8

### Anything else?

https://go.screenpal.com/watch/cZ1h1uVNbY2

**Comment by javiercn** [comment]
@GajaLab thanks for contacting us.

This is likely a report on the `window.unload` event handler (your image doesn't include anything else). 

While browsers intend to deprecate that API, there are not great alternatives to it and will continue to work for the foreseeable future (and even if it stops working, Blazor uses it as a performance optimization).

**Comment by richardaubin** [comment]
Deprecation of unload api is due to happen by end of Q1 2025 from what the docs say here 
https://developer.chrome.com/docs/web-platform/deprecating-unload#deprecation_timeline

**Comment by GoldSucc** [comment]
@javiercn I tested replacing unload event with pagehide for my projects in Blazor.web.js script (high lighthouse score is one of my selling points) and it worked, performance is fine and deprecation warning disappeared. Pagehide is different from unload but generally it should work similarly in many cases. Unload is not guaranteed to work at all according to docs, it is inconsistent, so even if pagehide is slightly different IMHO it is better at least because it is consistent and not deprecated. Have you considered to use pagehide or there is a reason I don't know why it is a bad idea?

**Comment by Kalle-kula** [comment]
Why is this closed when people keep reporting it?
