### ISSUE TITLE
Visual Studio - Remove compilation errors in .g.cs files 

### ISSUE THREAD

**Issue by vertonghenb** [dotnet/aspnetcore#5614]
When a component fails to compile, the error list shows the {componentname}.g.cs files, which are not clickable in VS. Is it possible to hide these files?

**Comment by ArvindRSingh** [comment]
Is there any possible workaround?

**Comment by katiep23** [comment]
I just started getting these types of errors after I upgraded to .NET Core 3.0 Preview 7.

**Comment by neilRGS** [comment]
Hi.
I am getting the same thing just running the getting started Blazor tutorial on the [Micorosoft site](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-J7MA57grRnwaU5b9tFcbjQ&epi=je6NUbpObpQ-J7MA57grRnwaU5b9tFcbjQ&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__ciwkx9fiq0kfrxt2kk0sohz30m2xjdvv9fu2nhmu00)(7593)(1243925)(je6NUbpObpQ-J7MA57grRnwaU5b9tFcbjQ)()&irclickid=_ciwkx9fiq0kfrxt2kk0sohz30m2xjdvv9fu2nhmu00&view=aspnetcore-3.0&tabs=netcore-cli):
Here's the cli output:
```$ dotnet run
obj\Debug\netstandard2.0\RazorDeclaration\App.razor.g.cs(54,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(55,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Shared\MainLayout.razor.g.cs(54,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(55,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Shared\NavMenu.razor.g.cs(54,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Shared\SurveyPrompt.razor.g.cs(54,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(55,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [R:\Dev\Blazor\blazordemo\blazordemo.csproj]

The build failed. Fix the build errors and run again.
```

Any ideas as to how to fix the build errors?

**Comment by elementalpete** [comment]
This seems to be a general Razor issue - I run into frequently in standard Asp.Net Core MVC projects.  In the case of Asp.Net Core MVC, these errors correspond to errors in the .cshtml file.  The solution is to find and fix the error in the .cshtml and do a rebuild or clean and build.  Usually, I find that when I open the .cshtml file, there is a red squiggly line showing me where the error is, but it never gets populated to the Error List.  So in neilRGS's case, I am guessing that @using Microsoft.AspNetCore.Components (or using a fully-qualified class name for Microsoft.AspNetCore.Components.RenderTree) in the Razor file would fix it, although I don't have an easy way to verify.

The main time that this causes me issues is if I am refactoring code, say by deleting a model file and then deleting the corresponding view, and then attempting to build and run.  Even though the .cshtml file has been deleted, and the .cshtml.g.cs file wouldn't have to be recreated, I have run into instances where the .cshtml.g.cs file already exists, it can't find the model file, and so it throws a missing reference error and compilation fails before VS realizes that the .cshtml.g.cs file is no longer relevant.  It can be tricky to fix at that point - I've had to cut and paste in old versions of the .cshtml file, "fix the error" by deleting all or most of the file contents, rebuild, and then redelete the .cshtml file to clear the error.

**Comment by asad-c** [comment]
@elementalpete Check the .cshtml and fix the error, so simple it's embarrassing I didn't think to do it before reading your post :-).

**Comment by mkArtakMSFT** [comment]
Closing as we haven't received any recent customer reports in this area. Presumably this is fixed already.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen let me know if this shouldn't be closed yet.

**Comment by terrenceferguson** [comment]
@mkArtakMSFT I am also experiencing this issue.

I changed the name of a class used in the Razor page, and it is now throwing this exception on build. If I manually change the class name in those files, it seems to build correctly.

**Comment by terrenceferguson** [comment]
@mkArtakMSFT 

While I think some semblance of the issue might still be present, what I noticed is that the references to class names in .cshtml files (e.g. @model Namespace.Models.EditProfile) are not being refactored when they are changed globally. I'm not sure if that's intentional, or if it's a bug. Nevertheless, I wanted to reply that it doesn't seem to be an issue for me at the moment, before you go down any unnecessary rabbit holes. Thanks.

**Comment by irdublu** [comment]
I've just hit this error - again.  A 'solution' I have used before is to close the solution, delete the bin and obj folders and the vs file then reload.  This time VS is refusing to clear down 5 errors that are all in one line in a component called Schedule.razor.g.cs.  Nothing I do clears this.
Anyone any ideas please?

**Comment by beccahammond** [comment]
I am hitting this same issue.  I have tried deleting the bin and object folders and reloading the project and still get the same errors in my cshtml.g.cs files.

**Comment by lukemason76** [comment]
Error occurred today using VS 16.7.5. Renamed a data class due to a warning about it clashing with an area name. Clean. Build. Errors in *.g.cs   Clean, build, same.  Googling found this page. It’s not fixed, please don’t close.

**Comment by vashov** [comment]
I create blazor project with BlazorApp.Client, BlazorApp.Server and BlazorApp.Shared inside.
Also i add IS4 with individual user accounts.

When I rename namespace of BlazorApp.Server.Models => BlazorApp.Server.Entities with Ctrl+R+R, then it shows, that all files (where this namespace used) are changed.

But when i try rebuild error of *.g.cs occures.
Clean, deleting bin/obj, rebuilding didn't help.

The fact is that namespaces in files _ViewImports.cshtml (BlazorApp.Server => Pages => _ViewImports.cshtml) and _ViewImports.cshtml *specific for IS4* (BlazorApp.Server => Areas => Identity => Pages => _ViewImports.cshtml) were auto-changed incorrect.
This files have
```
@using TestHackBlazor.Server.Areas.Identity
...
@using TestHackBlazor.Server.Areas.Identity
```
Instead of 
```
@using TestHackBlazor.Server.Areas.Identity
...
@using TestHackBlazor.Server.Entities 
```
After had corrected this, error of *.g.cs disappeared.

**Comment by RDavis3000** [comment]
VS 16.7.7 renamed a class being used as the model for a MVC view, got errors in the* .g.cs files. Clean. Build. Errors in *.g.cs Clean, build, same, found my way here

**Comment by corneliusroemer** [comment]
Got the same error. No idea how it happened. I deleted the delinquent file (something in debug with .g.cs ending) and rebuilt. That worked.

**Comment by redoc209** [comment]
VS 2019
I just ran into this error and this is what I tried.
Quit VS. Deleted bin/obj folder. reopened project and the error is still there.
With VS open, deleted the razor.g.cs file.  Recompiled and did not work.

Error is pointing to a line in the razor.g.cs file.  Error message is "the left-hand side of an assignment must be a variable, property or indexer"  There is no error on this line in the code. It occurred after adding an onchange event to the input it is referencing and then removing it.  Even though it was removed and code reverted back to last working version, an error is thrown.  

This issue is not fixed.  Please do not close.

**Comment by mofolom** [comment]
I'm getting these issues.

![image](https://user-images.githubusercontent.com/4580013/106360601-fd51d000-6321-11eb-95b1-6695ec0de242.png)

**Comment by alexwhite68** [comment]
I get these errors often on Visual Studio for Mac (Community Edition), current version 8.9 Preview build 1451, these all seem to happen when I rename classes or move classes from one folder to another (drag and drop), what works most of the time if it's one file is to open it select all the text delete it, save etc (same as deleting the file).

Sometimes I cannot clear the error and that is game over for those classes that are affected, the workaround that works for me is to create new classes from scratch copy/paste the contents from the old classes then delete the old files.

**Comment by H230** [comment]
This may be a possible solution.  When using the rename feature. it  appears to not automatically rename the class referenced in the view, please check all views manually to see if you are still referencing the old class somewhere.  this fixed it for me.

**Comment by mofolom** [comment]
I downgraded from dotnet 5 to dotnet core 3.1. I don't have the issues any
longer.

**Comment by alexwhite68** [comment]
> This may be a possible solution. When using the rename feature. it appears to not automatically rename the class referenced in the view, please check all views manually to see if you are still referencing the old class somewhere. this fixed it for me.

I spent many hours on this, deleting files, cache, reboots etc, nothing cleared my issues until I set a @using path to the new location of the files which in my case was the layout files so a @using Blazor.Client.Shared and changed that in the _Imports.razor file, somewhere in the files where we cannot see them that namespace is being used by the compiler, because it's not listed anywhere in the actual layout files, all of my .razor files are standalone.

So if you create a new folder structure for your files and drag and drop the files, you need to mirror the folder structure in namespace names and make sure they are being used.

**Comment by pranavkm** [comment]
This is being resolved as part of switching Razor to use a source generator as part of .NET 6.
