### ISSUE TITLE
Blazor server closes when downloading a file with Libre Wolf browser exited with code 4294967295 (0xffffffff).

### ISSUE THREAD

**Issue by asieradzk** [dotnet/aspnetcore#56596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to download a file from Blazor Server application when using libre wolf browser the application closes with code exited with code 4294967295 (0xffffffff). regardless if download succeeded or canceled by user. Application closes in both debug and build. No exceptions are thrown, no errors are logged to console in browser or asp.net core console.

For extra clarity:
-IT IS NOT THE BROWSER THAT CRASHES (it causes the crash to happen somehow)
-The server process crashes when launched from visual studio (debug or release both), does not happen when running executable directly. 

Project that caused this to happen:
https://github.com/asieradzk/RL_Matrix/tree/2dda076391066292bf184b126237f8717aa87a22/src/RLMatrix.Dashboard

Steps to reproduce:
-Fresh empty blazor server application targeting net7.0
-Create a button that triggers a download of file. I am generating file on the fly so I'm using something like this:

```js

<script>
    window.saveAsFile = (fileName, contentType, content) => {
        const link = document.createElement("a");
        const file = new Blob([atob(content)], { type: contentType });
        link.href = URL.createObjectURL(file);
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
</script>
```

And interop with that js.

-Dialog opens, either save file or close dialogue - the application will crash.

This happened when using LibreWolf browser 124.0.1-1, no issue with other browsers.

I will soon post link to entire application that causes this. 

### Expected Behavior

Blazor server application should not close/exit/crash

**Comment by javiercn** [comment]
@asieradzk thanks for contacting us.

.NET 7.0 is out of support, as a first step, upgrade to .NET 8.0 and check if the issue still occurs.

**Comment by asieradzk** [comment]
> @asieradzk thanks for contacting us.
> 
> .NET 7.0 is out of support, as a first step, upgrade to .NET 8.0 and check if the issue still occurs.

Still occurs in .NET 8.0.
I've added a link in the OP to repository containing code with issue. I've found that any kind of download on LibreWolf would make this weird crash happen so its quite concerning and might point to serious security issue.

**Comment by javiercn** [comment]
@asieradzk thanks for the additional details.

Do you mean the browser crashes? Not the Server process, isn't it?

**Comment by asieradzk** [comment]
> @asieradzk thanks for the additional details.
> 
> Do you mean the browser crashes? Not the Server process, isn't it?

No, the Blazor Server application crashes with code 4294967295 (0xffffffff).
There are no exceptions thrown and nothing else is logged in output window or console window. Thats the only message I get.

**Comment by javiercn** [comment]
@asieradzk thanks for the additional details.

Are you running the application from Visual Studio or the Command Line?

**Comment by asieradzk** [comment]
> @asieradzk thanks for the additional details.
> 
> Are you running the application from Visual Studio or the Command Line? Are you debugging the application while this happens?

Visual Studio 22

**Comment by javiercn** [comment]
@asieradzk thanks for the additional details.

I suspect this is a problem with the browser you are using `LibreWolf` that's crashing in some way for reasons that are not obvious to us. The code snippet that you reference seems completely client-side based and unrelated to Blazor at all.

The reason you are seeing the app being closed is likely because you are running under the debugger and when VS sees the original browser window close (because of a crash) it automatically stops the server app from running. You'll likely won't see this behavior if you don't run under the debugger (CTRL+F5) or if you run from the command line and visit the page manually.

As to what's happening in this particular instance, we would suggest you file an issue with the folks that develop `LibreWolf` as it seems unlikely this is caused by Blazor.

> Should be easy to reproduce just clone the project in link and run it, no extra setup required,.

Unfortunately, this requires us to install untrusted software, which we don't do unless we absolutely need to.

**Comment by asieradzk** [comment]
> @asieradzk thanks for the additional details.
> 
> > Should be easy to reproduce just clone the project in link and run it, no extra setup required,.
> 
> Unfortunately, this requires us to install untrusted software, which we don't do unless we absolutely need to.
> 
> I suspect this is a problem with the browser you are using `LibreWolf` that's crashing in some way for reasons that are not obvious to us. The code snippet that you reference seems completely client-side based and unrelated to Blazor at all.
> 
> The reason you are seeing the app being closed is likely because you are running under the debugger and when VS sees the original browser window close (because of a crash) it automatically stops the server app from running. You'll likely won't see this behavior if you don't run under the debugger (CTRL+F5) or if you run from the command line and visit the page manually.
> 
> As to what's happening in this particular instance, we would suggest you file an issue with the folks that develop `LibreWolf` as it seems unlikely this is caused by Blazor.
> 
> To summarize: Run the app from the command line with `dotnet run` from the CLI and try the same steps. The app should keep running.

The crash does not happen when running executable directly but its still worrying that LibreWolf just by improperly interacting with SignalR (my guess) manages to crash process..

Again its NOT the browser thats crashing, its the process inside visual studio.

**Comment by javiercn** [comment]
> The crash does not happen when running executable directly but its still worrying that LibreWolf just by improperly interacting with SignalR (my guess) manages to crash process..

> Again its NOT the browser thats crashing, its the blazor server process managed by visual studio.

> Clearly this is something that should not happen and lack of descriptive error message is also an issue.

> One more time: It is NOT THE BROWSER that crashes, its the server process. The browser causes the crash.

Thanks for the additional details and sorry for the confusion. 

There's likely no error message because VS is likely killing the debugged app process.

In order for us to try and narrow down this further, could you try a couple of things?
* Does it happen in Visual Studio if you run without debugging? (CTRL+F5)
* If you put this snippet on a static HTML file or just an SSR rendered page without Blazor Server being involved, do you also see the issue happen?

```js
<script>
    window.saveAsFile = (fileName, contentType, content) => {
        const link = document.createElement("a");
        const file = new Blob([atob(content)], { type: contentType });
        link.href = URL.createObjectURL(file);
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
</script>
```

I suspect given what you mentioned that this is likely something to do with either the JS debugger or the .NET debugger crashing and VS terminating the process as a result.

Given that this doesn't happen from the command line, it's very likely a development time issue, it'll be better if you file this issue through the [report a problem](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) dialog in Visual Studio as that will make sure important information for troubleshooting this problem is captured so that folks in the VS and debugger team can analyze the problem.

**Comment by Mahamadou-Nouridine** [comment]
I'm experiencing the exact same issue with a different browser in a Blazor Hybrid app (Razor pages rendered in asp.net core mvc). Anytime I download a file using the same approach (Create a button that triggers a download of file) the app shuts down whether in debug or release mode.
I have a logic that generate an excel file that will be later on be downloaded. At the first time I thought that the issue is with the package I'm using for generating the excel file (closedXML), I then instead of generating the file, I directly provide a contant generated base64 excel data and still the same issue.
My .net version is 8.0

**Comment by tratak** [comment]
I have the same issue with Vivaldi browser (Chromium one). Changing the browser to Chrome resolved the problem. Then, I return to Vivaldi, I remove all extensions and, it works on Vivaldi, too. Then, I added extensions one by one and finally, after all extensions were added again, the Vivaldi browser still works. So the problem was an extension, that have to be reloaded.
Hope that this will hep someone!
