### ISSUE TITLE
Blazor QuickGrid not displaying correctly

### ISSUE THREAD

**Issue by jfgreco** [dotnet/aspnetcore#56636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the Blazor QuickGrid, the column titles that are marked as sortable, are showing up as gray buttons instead of text that is clikable. Any ideas on what might be going wrong? [screenshot](https://i.sstatic.net/53KAxzbH.png)

I tried removing the CSS from the pages to see if there was some kind of issue rendering.

![Screenshot 2024-07-04 at 7 48 06 PM](https://github.com/dotnet/aspnetcore/assets/2632693/87234258-d8c8-46bc-81e8-b0ea274c5d53)

### Steps To Reproduce

Setting the Sortable property to true

### Exceptions (if any)

Display a proper column header and not a button

### .NET Version

8.0.6

**Comment by tipr-external** [comment]
@jfgreco did you solve the issue? If so, could you state how as I have the same issue!

**Comment by robert-shattock** [comment]
@tipr-external for me I had to do Cntrl-F5 ... obviously the css and images hadn't loaded for some reason.  Hope it helps.

**Comment by jbennink** [comment]
I had this issue today and after a long time I managed to figure out that I had the wrong filename for the generated css styles. My project was names "Company.Project" but I have a line 
```html
    <link rel="stylesheet" href="@Assets["Project.styles.css"]" />
```

in my App.razor. I got this wrong because I changes the `rootnamespace` in the csproj and figured that was the name, but it takes the `assemblyname`, which is also the file on disk ie Company.Project.dll
