### ISSUE TITLE
OpenAPI Vs Swashbuckle

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#56711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
public class WeatherForecast
{
    public DateOnly Date { get; set; }

    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

    [DefaultValue("123")]
    public string? Summary { get; set; }

    public DateOnly? Date1 { get; set; }

    public int? TemperatureC1 { get; set; }

    [Required]
    public DateOnly? Date2 { get; set; }

    [Required]
    public int? TemperatureC2 { get; set; }
}
```
### OpenAPI
![image](https://github.com/dotnet/aspnetcore/assets/5714438/1e5d0768-6531-49f0-83d2-980c643f4b21)

### Swashbuckle
![image](https://github.com/dotnet/aspnetcore/assets/5714438/3c62cd92-acf9-4e1d-b7a5-61746e24bb80)

@captainsafia
- `TemperatureF `has no method set, and should not appear in the model
- `TemperatureC2` is a nullable attribute, but it adds a required attribute and should no longer appear nullable

**Comment by KennethHoff** [comment]
> TemperatureC2 is a nullable attribute, but it adds a required attribute and should no longer appear nullable

Requiredness and nullability are two orthogonal concepts. Required means you have to set it. Nullable means it can be set to the value `NULL`.

```
// Required, nullable
{ age: null } // Valid 
{ age: 10 } // Valid
{ } // Invalid

// Required, non-nullable
{ age: null } // Invalid 
{ age: 10 } // Valid
{ } // Invalid

// Non-required, nullable
{ age: null } // Valid
{ age: 10 } // Valid
{ } // Valid

// Non-required, non-nullable 
{ age: null } // Invalid 
{ age: 10 } // Valid
{ } // Not sure what happens.
```

**Comment by captainsafia** [comment]
Thanks for chiming in @KennethHoff! Your response around required vs. nullable is correct.

With regard to the other comment:

> TemperatureF has no method set, and should not appear in the model

There's a bit of subtlety to reason through with this one. `TemperatureF` has no `set` method but it does have a `get` method. That means that it is totally valid for it to appear in the schema for responses, but not necessarily in the schema for request bodies.

The "correct" way to model this in OpenAPI is using the `readOnly` property to indicate that the property is not settable but _does_ exist on the schema. OpenAPI will use `readOnly` as a clue for whether a property should be validated as present when it is in the response (and vice versa for `writeOnly`). https://github.com/dotnet/aspnetcore/issues/56353 is tracking modeling this correctly. This isn't currently in yet because we're working through how to handle `readOnly` correctly with an eye for the long-term direction of OpenAPI (see https://github.com/dotnet/aspnetcore/pull/56470#issuecomment-2201299656 for more info).

I'm gonna mark this issue as "resolved" for now given we're tracking the feedback presented here elsewhere. If you have any other questions, feel free to comment before the bot autoresolves or open another issue.

**Comment by martincostello** [comment]
Specified but null is useful for scenarios such as an HTTP PATCH where you want to explicitly clear a value of an object, where as not providing the property at all would mean "don't edit it at all, leave it with whatever value it may already have".
