### ISSUE TITLE
Regression: HTTP 401 using Microsoft.AspNetCore.Authentication.JwtBearer 8.0.7

### ISSUE THREAD

**Issue by nwoolls** [dotnet/aspnetcore#56727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Accessing an ASP.NET protected Web API using a valid JWT bearer token returns an HTTP 401 using Microsoft.AspNetCore.Authentication.JwtBearer 8.0.7. Downgrading to 8.0.6 resolves the issue. 

### Expected Behavior

Accessing an ASP.NET protected Web API using a valid JWT bearer token should return a successful status code (200, 201, etc) along with the expected body.

### Steps To Reproduce

From the command line:

```bash
mkdir spl-dotnet-8.0.7-web-api-401
cd spl-dotnet-8.0.7-web-api-401
dotnet new webapi
dotnet add package Microsoft.AspNetCore.Authentication.JwtBearer
```

Edit the `Program.cs`:

```csharp
builder.Services
    .AddAuthentication()
    .AddJwtBearer();
builder.Services.AddAuthorization();
```

```csharp
...
.WithName("GetWeatherForecast")
.WithOpenApi()
.RequireAuthorization();
...
```

Edit `secrets.json`:

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "Audience": "api://<Client ID>"
  }
}
```

Run the project and attempt to retrieve the sample weather forecast using a valid JWT bearer token. The result is an HTTP 401.

Next, edit the `.csproj` file and downgrade `Microsoft.AspNetCore.Authentication.JwtBearer` to 8.0.6.

Rerun the project and attempt to retrieve the sample weather forecast using a valid JWT bearer token. The request succeeds.

### .NET Version

8.0.303

**Comment by halter73** [comment]
This regression was likely caused by [this commit](https://github.com/dotnet/aspnetcore/commit/67761b3c1df88c462f1451fea3a3d500d5bc1344) which was made to address https://github.com/dotnet/aspnetcore/issues/53423.

Previously, if the "Authentication:Schemes:Bearer" configuration was used but no "ValidIssuer" or "ValidAudience" (not just "Audience") was specified, [TokenValidationParameters.ValidateIssuer](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuer?view=msal-web-dotnet-latest#microsoft-identitymodel-tokens-tokenvalidationparameters-validateissuer) and [TokenValidationParameters.ValidateAudience](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateaudience?view=msal-web-dotnet-latest) would be set to false respectively. This disabled issuer validation even if the authority's `.well-known/openid-configuration` provided an "issuer" to validate against. Likewise, audience validation would be disabled even if an "Audience" configured since it was not a "ValidAudience" or part of "ValidAudiences".

You might be able to fix you issue just by changing "Audience" to "ValidAudience":

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "ValidAudience": "api://<Client ID>"
  }
}
```

If this still doesn't help diagnose your issue, I recommend [enabling trace level logs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#configure-logging) to see if that includes any details about why the JWT was rejected.

You could also take a look at the "iss" and "aud" claims on the valid-but-rejected JWT and see how it compares to the "issuer" specified at `https://login.microsoftonline.com/<Tenant ID>/v2.0/.well-known/openid-configuration` and the "ValidAudience" specified by your app's configuration. It's possible you're using the wrong "\<Tenant ID\>", and you can just change the "Authority" to use the right one. You can also add "ValidIssuer" or "ValidIssuers" manually similar to "ValidAudience" or "ValidAudiences":

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "ValidAudiences": [ "api://<Client ID>" ],
    "ValidIssuers": [ "<Issuer from valid-but-rejected JWT's 'iss' claim>" ]
  }
}
```

To just get the old behavior, you can explicitly set "ValidateIssuer" and "ValidateAudience" to false as follows:

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "ValidateIssuer": false,
    "ValidateAudience": false
  }

```

However, you probably do want to validate both to prevent the type of forwarding attacks described in [TokenValidationParameters.ValidateIssuer](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuer?view=msal-web-dotnet-latest#microsoft-identitymodel-tokens-tokenvalidationparameters-validateissuer) and [TokenValidationParameters.ValidateAudience](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateaudience?view=msal-web-dotnet-latest) documentation.

**Comment by nwoolls** [comment]
Your assessment seems spot on. The following configuration resolves (works around?) this issue:

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "ValidAudience": "api://<Client ID>",
    "ValidIssuer": "https://sts.windows.net/<Tenant ID>/"
  }
}
```

Can you say whether the above configuration is recommended going forward, or if, in the future, the `Audience` value will be used in absence of `ValidAudience` and the issuer from `.well-known/openid-configuration` will be used in the absence of `ValidIssuer`. Just trying to suss out if this is a long-term or short-term change.

Thanks for the direction and speedy response!

**Comment by halter73** [comment]
> Can you say whether the above configuration is recommended going forward, or if — in the future — the `Audience` value will be used in absence of `ValidAudience` and the issuer from `.well-known/openid-configuration` will be used in the absence of `ValidIssuer`? Just trying to suss out if this is a long-term or short-term change.

That looks good to me. This is a long-term change that we also just [merged it into main](https://github.com/dotnet/aspnetcore/pull/56702) for 9.0-preview7. There is no current plan to ever read the "Audience" value. But if we did, we would still fall back to the "ValidAudience" in order not to break existing code that's doing proper validation.

As of 8.0.7, you should already be able to omit the "ValidIssuer" because it can be obtained from `.well-known/openid-configuration`. I don't see much harm in specifying it, but it ends up being redundant because the default validator will succeed if the correct issuer is specified [via either the authority's `.well-known/openid-configuration` or `TokenValidationParameters.ValidIssuer` (which is what your app's configuration controls)](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/3b3d3ec6417885b686625004adfd8fb7dc3442a2/src/Microsoft.IdentityModel.Tokens/Validation/Validators.Issuer.cs#L123-L140), so I'd just go with my first suggestion if it works:

```json
{
  "Authentication:Schemes:Bearer":
  {
    "Authority": "https://login.microsoftonline.com/<Tenant ID>/v2.0",
    "ValidAudience": "api://<Client ID>"
  }
}
```

**Comment by nwoolls** [comment]
Unfortunately I cannot omit `ValidIssuer`; I'm not sure if that's a library issue or an Azure issue or something I'm not understanding fully.

The issuer in the token received from Azure is `https://sts.windows.net/<Tenant ID>/` as seen by decoding the JWT. However, the issuer found at https://login.microsoftonline.com/<Tenant ID>/v2.0/.well-known/openid-configuration is:

```json
"issuer": "https://login.microsoftonline.com/7ac08305-d802-4bb9-ac0b-32f9ea2a1282/v2.0",
```

**Comment by halter73** [comment]
I think what you have is fine then. I forgot you were using Entra ID rather than Azure AD. This is the well-known behavior (see https://github.com/dotnet/blazor-samples/issues/251). Stuff like that is part of the reason you can specify "ValidIssuer" independently of the "Authority". At least it won't accept any issuer now.

You might be even better of using Microsoft.Identity.Web's `AddMicrosoftIdentityWebApi` instead of AddJwtBearer. It just [calls AddJwtBearer](https://github.com/AzureAD/microsoft-identity-web/blob/a6cdceb5ffd3b9518d35c3046b7117b4b4844ec5/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L142) under the covers but should make configuration a little more straight forward. Just be aware the configuration is different. It uses the "AzureAd" config section (even if using Entra ID instead Azure AD) and actually does use "Audience" instead of "ValidAudience".

https://learn.microsoft.com/entra/identity-platform/scenario-protected-web-api-app-configuration
https://learn.microsoft.com/entra/identity-platform/scenario-web-api-call-api-app-configuration
