### ISSUE TITLE
API description provider not lifting Container type of properties 

### ISSUE THREAD

**Issue by jgarciadelanoceda** [dotnet/aspnetcore#56764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This bug comes from an issue we face using Swashbuckle. Analyzing the issue domaindrivendev/Swashbuckle.AspNetCore#2658, Swashbuckle is not capable of documenting the properties of a class that is used with AsParameters, because when checking the documentation Swashbuckle looks for the Container type and is not present in the documentation of the MetadataType

Expected behavior
To have documentation about the ContainerType to be able to set this documentation with Swashbuckle.

More info in microsoft/OpenAPI.NET#1712

cc:@captainsafia

### Expected Behavior

Provide the ContainerType of the properties that come from a AsParameters class

### Steps To Reproduce

Create an endpoint with AsParameter class and check if the ContainerType is present 

### .NET Version

Dotnet8

**Comment by captainsafia** [comment]
@jgarciadelanoceda Thanks for filing this issue!

It appears that the issue is due to the fact that the `ApiParameterDescription.ModelMetadata.ContainerType` property isn't configued for `ApiParameterDescription`s that are dervied from `[AsParameters]` types. The problem is with this method:

https://github.com/dotnet/aspnetcore/blob/e31445e897e416b743f436b27cb81f3c87c56d27/src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs#L436-L437

Which only passes information about the type, and not the property info when constructing model metadata. To fix this, we'd want to call the correct [ModelMetadataIdentity](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Abstractions/src/ModelBinding/Metadata/ModelMetadataIdentity.cs) API to get all the of the information funneled through.

If this is enough information to help you open a PR, I'd be glad to review it. Otherwise, I can share more pointers on how we might go about fixing this.

For now, sticking this in the backlog.

**Comment by jgarciadelanoceda** [comment]
Thank you @captainsafia.
I have been able to compile aspnetcore and I will try to handle the issue

**Comment by jgarciadelanoceda** [comment]
I did not close it because I thought that this was going to net9 or net8, if it's planned to net10, then you can close this issue :)

**Comment by captainsafia** [comment]
Yes, this will go into .NET 10. I don't think it's super urgent that we need to backport but if that is not the case let me know.
