### ISSUE TITLE
dotnet restore >NU1301> Interruption in project build due to external dependency failure 

### ISSUE THREAD

**Issue by ravindra-aditya** [dotnet/aspnetcore#56873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Suddenly, project build / restore stopped working while building dotnet projects in visual studio 2022

Relevantly,  getting feed interference issues whenever other services are interrupted or not working.
Error: NU1301 Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

Related created issue update: https://github.com/NuGet/NuGetGallery/issues/10074 

### Expected Behavior

If services are having issue either due to downtime or dependencies broken, we need to have a fix which can help to do alternatively.

### Steps To Reproduce

Create an aspnetcore web api application and try to build, immediately the reported error is getting inferred.

### Exceptions (if any)

Error: NU1301 Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

### .NET Version

8.0

### Anything else?

![image](https://github.com/user-attachments/assets/6b150251-d92c-4782-8945-88ad10dcf137)

**Comment by martincostello** [comment]
If I go to `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json` I get an HTTPS warning:

![image](https://github.com/user-attachments/assets/ebd0acc0-592e-4562-9531-d0c6e0632218)

I guess there's an outage on that MyGet feed? I'm not sure if it's even used/supported anymore.

**Comment by martincostello** [comment]
Have you identified _why_ you need to use `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json` at all?

- Where is that package source configured to be used?
- What packages are stored in it that you need?
- Do you actually need them?

All I personally can do is give you the hint above as you might find you don't actually need it, and can just remove it.

Otherwise, _someone_ somewhere at Microsoft will need to fix the certificate.

**Comment by ravindra-aditya** [comment]
@martincostello I just tried reviewing dotnet repos from github, then happened to build the solution and finally landed in to the following with VS 2022 Enterprise error.

I even tried this but it didn't work to confirm. 
https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source

Sometimes, been in tensed to see myself in chaos hence, waiting for the issue to get fixed.

**Comment by martincostello** [comment]
Which repos?

Why is whatever you're building trying to use this broken feed?

**Comment by ravindra-aditya** [comment]
I tried to explore https://github.com/aspnet/AspLabs 

I'm afraid, there is no solution open except **aspnetcore 8.0** web api new vanilla project being attempted to build in latest windows 11 and visual studio 2022 enterprise with all are up to date.

**Comment by martincostello** [comment]
- [aspnet/WebHooks](https://github.com/aspnet/WebHooks) is a deprecated and archived repo
- [aspnet/AspLabs](https://github.com/aspnet/AspLabs) - I find any references to MyGet in this repo

**Comment by ravindra-aditya** [comment]
This is what my concern as well, I don't see any direct dependency with myget however, visual studio is making calls it seems.

**Comment by martincostello** [comment]
What does `dotnet nuget list source` that I suggested you run output?

**Comment by ravindra-aditya** [comment]
I have followed these documentations but nothing helped.

https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source

**Comment by martincostello** [comment]
In that case, I'm out of ideas as to what is telling that feed to be used, and I can't do anything about making the MyGet feed to work.

You'll have to investigate on your computer further to find where its usage is coming from.

**Comment by ravindra-aditya** [comment]
Issue seems to be resolved. I'm able to see build getting succeeded.

**Comment by ravindra-aditya** [comment]
Issue still exists, hence reopened the issue. worried who is the best point of contact.

![image](https://github.com/user-attachments/assets/31f79997-b4a5-4f6b-9368-a32fcab129b3)

**Comment by martincostello** [comment]
- What package sources are configured in Visual Studio?
- What is the contents of your `NuGet.config` file in the solution directory, if any?
- What packages are you trying to get from the MyGet feed?

I still think the most likely cause here is that your computer is mis-configured and you don't actually need to use this feed, so removing it from wherever it is configured will solve your problem.

If you do actually need to use it, then it depends on whether it being shut down/broken is intentional.

- If it wasn't intentional and it's an outage, then a team _somewhere_ at Microsoft needs to fix it. I have no idea who such a team would be or how to escalate anything to them.
- It if was intentional and it was shutdown due to it being old and deprecated/obsolete, then you'll have to replace everything that needed it with something else.

**Comment by martincostello** [comment]
I'm going to close this issue as it's nothing to do with the ASP.NET Core (or NuGet) teams, and I've given you plenty of hints to try and help you avoid this issue entirely by encouraging you to investigate where the package source is being configured and investigating why you even need it.

**Comment by ravindra-aditya** [comment]
Always multiple repos in a nightmare, if they have vulnerabilities. The issue got resolved when we split the repos in to separate directories rather than hierarchical.
