### ISSUE TITLE
Routes component is not found in assembly when render mode is set to InteractiveAuto

### ISSUE THREAD

**Issue by yandoldonov** [dotnet/aspnetcore#57007]
When instantiating the latest default BlazorWebApp template and setting RenderMode to InteractiveAuto - blazor.web.js runtime spits an error complaining that 

Root component type '%ProjectName%.Components.Routes' could not be found in the assembly 'ProjectName'.

Steps to re-produce:

1) Start Visual Studio and chose to create new project of type Blazor Web App. Continue the process with all the defaults.
2) Once the project is created - in App.razor component - set RenderMode in HeadOutlet and Routes to InteractiveAuto, like so:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="BlazrWebApp.styles.css" />
    <HeadOutlet @rendermode="@RenderMode.InteractiveAuto" />
</head>

<body>
<Routes @rendermode="@RenderMode.InteractiveAuto" />
    <script src="_framework/blazor.web.js"></script>
</body>

</html>
```

Expected result: no issues/errors in browser console when executing/running the project. 
Actual result: Error: One or more errors occurred. (Root component type '%ProjectName%.Components.Routes' could not be found in the assembly '%ProjectName%'.)

![error](https://github.com/user-attachments/assets/60924898-b9dd-4b0b-a695-69020b016fcb)

**Comment by javiercn** [comment]
@yandoldonov thanks for contacting us.

> Start Visual Studio and chose to create new project of type Blazor Web App. Continue the process with all the defaults.

We can't do anything with this, since the "defaults" are sticky and might have changed for you. Unless you are able to tell us exactly what combination of (Interactivity (per page or global) and render modes (webassembly, server)) you are using when you are creating the template, there's nothing that we can do.

I would also include that depending on the render mode you start with, when you switch to `Auto` you likely need to adjust the location of files in your app (mainly move almost all the `.razor` files to the client project) since they need to be available when running in webassembly.

**Comment by yandoldonov** [comment]
Hi there! thank you for looking into this issue for me. 

i hope this help - these are the parameters i have selected when creating the project:

![image](https://github.com/user-attachments/assets/953e891f-6c5a-42ee-b268-dcff02d2473f)

so its - start new project - select Blazor Web App - then ge through the step as per screenshot above - this results in a created default settings project.

from that point i made 2 changes.

1) add Components folder BlazorWebAppDefault.Client folder and create a sample ClientSideComponent.razor - to trigger the framework to include components from the Client project.

2) adjust contents of App.razor component to those as per screenshot below - basically adjusting render mode of HeadOutlet and Routes. no other changes.
 
![image](https://github.com/user-attachments/assets/5fd98f8f-e98e-4b10-b349-dec895fad0df)

when attempting to run the app - i end up with the following error in browser run-time:

![image](https://github.com/user-attachments/assets/a7b4c937-1705-4a4f-bac8-90977d2dbddb)

while investigating the issue i have come across posts on Stackoverflow and on github suggesting that Routes.razor be placed into the Client project. this however puzzles me as - if i do so - Routes.razor has then no way of referencing root project and any razor components defined there. so if i intend to run the app in a mixed Auto mode - i imagine that it would include both components placed in the main project (too be rendered in server mode) as well as those placed in the Client project. how would Route.razor be expected to cover those components/routes?

thank you.

**Comment by javiercn** [comment]
@yandoldonov thanks for the additional details.

![image](https://github.com/user-attachments/assets/bf4f3685-3b04-400a-bb30-5bf74266f986)

The problem is here. When you select per page/component interactivity, the `Routes` component is defined on the server project. If you apply `rendermode` Auto in the `Routes` component you need to do additional work to move that component to the client project.

It seems that in your case you want to have global interactivity as opposed to per-page interactivity.
