### ISSUE TITLE
[Blazor] negotiateVersion (SignalR) best practice in regards to XSS

### ISSUE THREAD

**Issue by Welchen** [dotnet/aspnetcore#57091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During a security scan we got a report that negotiateVersion response value format could leave to a XSS attack.   I searched and found the ticket #32771 and where this was talked about once before. The ticket was resolved stating that only integers would be returned.  That is not the case and the audit showed that.

**Request**

> POST /ContentServer/_blazor/negotiate?negotiateVersion=1u9gdh%3cscript%3ealert(1)%3c%2fscript%3ekwhcrq8u1z8 HTTP/1.1

**Response**

> 
> HTTP/1.1 200 OK
> Date: Mon, 15 Jul 2024 23:14:44 GMT
> Content-Type: application/json
> Content-Length: 105
> Connection: close
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> X-Frame-Options: SAMEORIGIN
> Server: MTIWebServer
> Strict-Transport-Security: max-age=31536000
> X-XSS-Protection: 1; mode=block
> 
> {"error":"The client requested an invalid protocol version '1u9gdh<script>alert(1)</script>kwhcrq8u1z8'"}

**Details from the audit** 

> The value of the negotiateVersion request parameter is copied into the HTML document as plain text between tags. The payload u9gdh<script>alert(1)</script>kwhcrq8u1z8 was submitted in the negotiateVersion parameter. This input was echoed unmodified in the application's response.
> 
> This proof-of-concept attack demonstrates that it is possible to inject arbitrary JavaScript into the application's response.
> 
> The original request used a Content-type header which it is not possible to generate using a standard HTML form. It was possible to replace this header with a standard value, to facilitate cross-domain delivery of an exploit.
> 
> The response does not state that the content type is HTML. The issue is only directly exploitable if a browser can be made to interpret the response as HTML. No modern browser will interpret the response as HTML. However, the issue might be indirectly exploitable if a client-side script processes the response and embeds it into an HTML context.

### Expected Behavior

The response would either not echo the value or the value would be encoded in case the value is not an integer.

### Steps To Reproduce

Inject an illegal value into the request for the negotiateVersion.

### .NET Version

8.0.303

**Comment by javiercn** [comment]
@Welchen thanks for contacting us.

We'll have the `Signalr` folks take a look at it, since this is not really Blazor specific.

**Comment by blowdart** [comment]
If I look at the results you can see `Content-Type: application/json`. 

Your scanner is not sort of, but not really in the one key way, correct in this bit

> The value of the negotiateVersion request parameter is copied into the HTML document as plain text between tags. The payload u9gdh<script>alert(1)</script>kwhcrq8u1z8 was submitted in the negotiateVersion parameter. This input was echoed unmodified in the application's response.

There is no HTML document here.

Certainly, if an application written atop SignalR took that json, and then inserted it into an HTML document in a naive way, by appending, or not using innerText then that could lead to XSS and the scan results call this out

> The response does not state that the content type is HTML. The issue is only directly exploitable if a browser can be made to interpret the response as HTML. No modern browser will interpret the response as HTML. However, the issue might be indirectly exploitable if a client-side script processes the response and embeds it into an HTML context.

So, XSS would come from your client-side code.

Thus our response is still the same as in #32771

**Comment by Welchen** [comment]
> If I look at the results you can see `Content-Type: application/json`.
> 
> Your scanner is not sort of, but not really in the one key way, correct in this bit
> 
> > The value of the negotiateVersion request parameter is copied into the HTML document as plain text between tags. The payload u9gdh<script>alert(1)</script>kwhcrq8u1z8 was submitted in the negotiateVersion parameter. This input was echoed unmodified in the application's response.
> 
> There is no HTML document here.
> 
> Certainly, if an application written atop SignalR took that json, and then inserted it into an HTML document in a naive way, by appending, or not using innerText then that could lead to XSS and the scan results call this out
> 
> > The response does not state that the content type is HTML. The issue is only directly exploitable if a browser can be made to interpret the response as HTML. No modern browser will interpret the response as HTML. However, the issue might be indirectly exploitable if a client-side script processes the response and embeds it into an HTML context.
> 
> So, XSS would come from your client-side code.
> 
> Thus our response is still the same as in #32771

What's the value of it being returned if it could be mishandled by the client? Wouldn't the want to help avoid that from happening? 

The want to keep those things from happening and the savings of time from being pinned by security audits seems worth the change/update, right?

**Comment by blowdart** [comment]
It isn't mishandled by our clients.

In order for this to be exploitable a few things would have to happen.

1. An app would have to be written atop SignalR which takes that error json and displays it to the user, without following best practice against XSS.
2. In order for the attack to work the attacker would have to have a way to send an invalid version to the backend to trigger the error message.
3. The attack would only affect the current session.
4. In order to make the attack affect the current session the attacker would have to have the ability to send a malformed request from within the client web application. Our SDK & libraries don't have the ability to send such a request, so in order for that to happen, the attacker would need a way to inject javascript into the client app.
5. And if the attacker has the ability to inject javascript into the client app they have the ability to do everything a reflected XSS would do anyway, so there's no point in making an extra hop to a SignalR backend to get XSS, they're already executing in the context of the client app.

So, it is not a security vulnerability, and your scanner already knows and tells you about the nuance here, when it says

> The response does not state that the content type is HTML. The issue is only directly exploitable if a browser can be made to interpret the response as HTML. No modern browser will interpret the response as HTML. However, the issue might be indirectly exploitable if a client-side script processes the response and embeds it into an HTML context.

So, any fix would be "cosmetic", not security related, and as your scanner already tells you the nuance, which should be enough for you to realise it's a false positive, I, as the security PM for .NET have no reason to say this is a must fix. If the SignalR team want to "fix" this, they're free to, but it would be a "fix" in V.next and wouldn't be considered for backporting as it's not a security bug.
