### ISSUE TITLE
RequestDelegateGenerator generates invalid code for optional array parameters

### ISSUE THREAD

**Issue by ithline** [dotnet/aspnetcore#57175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`RequestDelegateGenerator` in a project targetting `net9.0` generates invalid code for array parameters.

The generator tries to assign single parsed value to an array parameter.

Snipped from the generated code
```csharp
global::System.Int32[]? ids_local = new global::System.Int32[ids_temp.Length];
for (var i = 0; i < ids_temp.Length; i++)
{
    var element = ids_temp[i];
    global::System.Int32[]? parsed_element = default;
    if (GeneratedRouteBuilderExtensionsCore.TryParseExplicit<int>(element!, CultureInfo.InvariantCulture, out var element_parsed_non_nullable))
    {
        parsed_element = element_parsed_non_nullable; // THIS LINE IS NOT VALID, element_parse_non_nullable is int, not an int[]
    }
    else if (string.IsNullOrEmpty(element))
    {
        parsed_element = default;
    }
    else
    {
        wasParamCheckFailure = true;
    }
    ids_local[i] = parsed_element!;
}
```

I think the issue is at this [line](https://github.com/dotnet/aspnetcore/blob/b41e166aac4746253b541ce512eaeff8dbf73112/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/EndpointParameter.cs#L382), where instead of `typeSymbol`, there should be a `parameterType` variable written into the output.

### Steps To Reproduce

```csharp
var builder = WebApplication.CreateSlimBuilder(args);
var app = builder.Build();

app.MapGet("/", (int[]? ids = null) =>
{
    return TypedResults.Ok(ids);
});

app.Run();
```

### .NET Version

9.0.100-preview.6.24328.19

**Comment by captainsafia** [comment]
@ithline Thanks for filing this issue!

It looks like we didn't catch this bug because there is a gap in our testing. We've got pretty extensive tests for our array-binding logic for RDG [in this test file](https://github.com/dotnet/aspnetcore/blob/08b60af1bca8cffff8ba0a72164fb7505ffe114d/src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Arrays.cs) but the coverage tends to be around the arrays of nullable values, as opposed to nullable arrays.

After some debugging, it looks like the issue here is actually with the default null value that the array is set to `= null` because nullable annotations for arrays are handled in [the fallback case](https://github.com/dotnet/aspnetcore/blob/b41e166aac4746253b541ce512eaeff8dbf73112/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/EndpointParameter.cs#L401). As a workaround, if you'd just like the argument to be optional you can do so with the nullability annotation (and no default value). 

With regard to a fix for this, I believe your hunch about changing the `typeSymbol` to `parameterSymbol` is one the right track although I think we'll have to condition it to only emit when the type being bound is an array (to distinguish between `int?` and `int[]?`).

Are you interested in submitting a PR with a bug fix for this? I can provide more pointers if that would be helpful.

In the meantime, I'll stick this in the backlog given the scope of impact and feasibility of a workaround.

**Comment by ithline** [comment]
Hello @captainsafia!

I can give it a try. Did some digging in the code today, but will certainly need some pointers on how to set up and author generator tests.

**Comment by captainsafia** [comment]
@ithline Sure -- the first step would be to clone the repo and set it up for building locally using [the instructions here](https://github.com/dotnet/aspnetcore/blob/a3608826a0cf20a1be4a80945c353bfaf6b425e9/docs/BuildFromSource.md). You might run into issues depending on what OS and/or editor you are using and what dependencies are installed.

Assuming that works out for you, you should be able to author a test like the one below in [this file](https://github.com/dotnet/aspnetcore/blob/a3608826a0cf20a1be4a80945c353bfaf6b425e9/src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Arrays.cs).

```diff
+    [Fact]
+    public async Task NewTest()
+    {
+        var (_, compilation) = await RunGeneratorAsync("""
+app.MapGet("/hello", (int[]? p) => p?.Length);
+""");
+        var endpoint = GetEndpointFromCompilation(compilation);
+
+        var httpContext = CreateHttpContext();
+
+        await endpoint.RequestDelegate(httpContext);
+        // Verify result here
+    }
```

Our generator test infrastructure is set up to run each test case twice, once with the compile-time generator and once with the dynamic run-time code gen so that we can validate the behavior is consistent between the two. Debugging the test should allow you to step through the source generators code and use that to guide dev.
