### ISSUE TITLE
"Bearer" scheme is hard-coded despite the actual scheme being available in a property

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspnetcore#57174]
In [JwtBearerHandler](https://github.com/dotnet/aspnetcore/blob/b41e166aac4746253b541ce512eaeff8dbf73112/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L84) the scheme is being hard-coded as a string literal rather than using the scheme that was defined in its configuration. 

The `Scheme` property is available on the base class https://github.com/dotnet/aspnetcore/blob/b41e166aac4746253b541ce512eaeff8dbf73112/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L23C12-L23C40

I think it would make sense to use the `Scheme` property here instead of hard-coding "Bearer" - otherwise you can't define authentication like this:

```csharp
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, cfg =>
{
    cfg.Audience = options.Audience;
    cfg.Authority = options.Authority;

    if (options.MetadataAddress is not null)
        cfg.MetadataAddress = options.MetadataAddress;

    cfg.RequireHttpsMetadata = options.RequireHttpsMetadata;

    cfg.TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = "sub",
        RoleClaimType = ClaimTypes.Role,
        ValidateAudience = true,
        ValidateIssuer = true,
        ValidIssuer = options.Authority,
        ClockSkew = TimeSpan.FromSeconds(5),
        ValidAudience = options.Audience
    };
})
// In my use-case, this second scheme is used by my Blazor app to get the current user
// during token construction (in an `IClaimsTransformation` so that custom, app specific 
// roles and permissions can be added to the token to be used with `[Authorize(Roles = "")]`
// in my Blazor components.
.AddJwtBearer("Service", cfg =>
{
    var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("my-key"));
    cfg.TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = ClaimTypes.NameIdentifier,
        RoleClaimType = ClaimTypes.Role,
        
        IssuerSigningKey = key,
        ValidateIssuer = true,
        ValidIssuer = "MyCustomIssuer",
        ValidateAudience = true,
        ValidAudience = "https://TemplateProject.api",
        ClockSkew = TimeSpan.FromSeconds(5)
    };
});
```

**Comment by MackinnonBuck** [comment]
We would recommend using [`OnMessageReceived`](https://learn.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0#built-in-jwt-authentication) to handle this scenario. Setting the `Scheme` property does not change what authentication headers are used. Or, please take a look at #56834 because that shows the supported way of doing what you're trying to achieve.

**Comment by hades200082** [comment]
@martincostello - @MackinnonBuck gave the usual work around that we're currently using, but surely given that we set the scheme in the `.AddJwtBearer()` call, it should honour the scheme we set?

If I call `.AddJwtBearer("Foo", cfg => {});` then is it unreasonable to expect it to look for `Authorization: Foo <token>` instead of `Authorization: Bearer <token>`?

**Comment by hades200082** [comment]
This has been closed as "by design" - Can we get a real answer as to why this isn't a bug? @martincostello or @MackinnonBuck ?

**Comment by chrisoverzero** [comment]
It's by design because the "scheme" here isn't the same as the "scheme" in an "authorization" header. In the [code snippet you've linked](https://github.com/dotnet/aspnetcore/blob/b41e166aac4746253b541ce512eaeff8dbf73112/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L23C12-L23C40), the property `Scheme` is a value of type `AuthenticationScheme`. From [the documentation](https://github.com/dotnet/aspnetcore/blob/e048f3048fc04b12298d68ad47c1b3d676542e64/src/Http/Authentication.Abstractions/src/AuthenticationScheme.cs#L9) for that type:

```csharp
/// <summary>
/// AuthenticationSchemes assign a name to a specific <see cref="IAuthenticationHandler"/>
/// handlerType.
/// </summary>
```

The JWT Bearer authentication handler is meant to be used _with JWT Bearer authentication_ – that defines an authentication scheme of "Bearer". It's only a coincidence that it's the same as the default name associated with that handler type. For comparison, the `AddCookie` method uses a default scheme name of "Cookies" (not "Cookie"), and changing that doesn't change the value of the "cookie" header.

**Comment by Coder3333** [comment]
@chrisoverzero, does anyone know how to set the Scheme of an authentication header to a different value from the authentication scheme using the .Net HttpClient, as you are describing?  If I set the scheme of AuthenticationHeaderValue, that impacts both the context's scheme, as well as setting the header value to the same scheme.  We wouldn't need to re-interpret the header value on the server if the request had a custom scheme for the context, but the actual header value was still "Bearer ".

` 
request.AuthorizationHeader = new AuthenticationHeaderValue("CustomScheme", tokenValue);
`
This produces -
Context: "CustomScheme"
Header Value: "CustomScheme tokenValue"

We want -
Context: "CustomScheme"
Header Value: "Bearer tokenValue"
