### ISSUE TITLE
Paginator renders extra empty rows when page isn't full of items

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#57199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With .NET 9 Preview 6 it looks like the Paginator is now rendering empty rows when the page isn't full of items:

![image](https://github.com/user-attachments/assets/bd9af345-676e-458f-89db-76fc50032db0)

### Expected Behavior

If the page isn't full, only the rows with items should be rendered.

### Steps To Reproduce

Create a Blazor Web App
Scaffold some CRUD pages
Wire up the Paginator to the QuickGrid
Add a couple of items to the table, fewer than the page size

### .NET Version

9.0.100-preview.6.24328.19

**Comment by MackinnonBuck** [comment]
> With .NET 9 Preview 6 it looks like the Paginator is now

Did this not happen prior to preview 6?

It looks like this would be a template change rather than a product change. We should update the styling in the template to make the table look nicer (not just fixing those extra lines, but also the weird wrapping, etc.).

**Comment by SteveSandersonMS** [comment]
> If the page isn't full, only the rows with items should be rendered.

Just to clarify, that's something the app developer needs to do with CSS if they want. It's by design.

The framework needs to render all the rows because otherwise the page links will jump up and down by default as you navigate. The expectation is the developer sets a fixed height in CSS, or if they really want blank ones to be gone, add CSS that sets display:none for rows that lack specific child elements.

**Comment by danroth27** [comment]
> Did this not happen prior to preview 6?

This doesn't happen with .NET 8:

![image](https://github.com/user-attachments/assets/6d3271c7-1ecf-4bcd-814c-a12c0669c440)

> The framework needs to render all the rows...

It does look like the rows are rendered in the DOM even on .NET 8. You just don't see the horizontal lines.

> ...because otherwise the page links will jump up and down by default as you navigate.

It looks like the paginator links will still jump on .NET 8 & 9 because the extra empty rows aren't rendered with the same height as the rest of the content. I'm not sure I agree this should be the default UX, but assuming it is, can we render the empty rows with the same fixed height? What if the other rows don't all have the same height?

**Comment by javiercn** [comment]
Is the markup different in any way?

**Comment by SteveSandersonMS** [comment]
Perhaps we changed the CSS and regressed this.

**Comment by guardrex** [comment]
Hit this as I was making the 9.0 [Blazor movie dB tutorial](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-8?view=aspnetcore-9.0&pivots=vs) updates.

@danroth27 ... I'd like to try to avoid readers opening doc issues on this. However, I'm not sure that it can be avoided because I'd need to call it out in the text, which doesn't seem ideal. I guess I can just have a GH saved reply on this if a lot of readers ping me on it.

![Image](https://github.com/user-attachments/assets/f5e1e85c-1b21-4163-b576-81c5f6f746d9)

**Comment by guardrex** [comment]
BTW ... It's not the `Paginator` component, as the issue title states, right? It's doing this even if the `Paginator` component is removed ...

![Image](https://github.com/user-attachments/assets/0122c44d-c456-487d-a2d1-e9dfad249800)

**Comment by htmlsplash** [comment]
The reason you don't see gridlines in the .net 8 version because only empty tr elements are rendered. In the .net 9 version the code was modified to include colurms (td elements) that render between the tr elements (source, RenderNonVirtualizedRows method).

This creates UI that looks terrible. At the minimum if you have to render empty rows, don't include styles, or have another set of styles for empty rows. 

Currently, I am employing a hack around this by settings the paginations state, ItemsPerPage property to zero if there are no records and page size if there are records. This code executes after I fetched the dataset. It works, but you have to do in for every page.

What's ETA on fixing this?

.net 8 version:

` if (Pagination is not null)
 {
     while (rowIndex++ < initialRowIndex + Pagination.ItemsPerPage)
     {
         <tr></tr>
     }
 }`

.net 9 version:

`if (Pagination is not null)
        {
            while (rowIndex++ < initialRowIndex + Pagination.ItemsPerPage)
            {
                <tr>
                    @foreach (var col in _columns)
                    {
                        <td class="@ColumnClass(col)" @key="@col"></td>
                    }
                </tr>
            }
        }`

**Comment by danroth27** [comment]
Thanks for researching this, @htmlsplash!

> In the .net 9 version the code was modified to include colurms (td elements) that render between the tr elements (source, RenderNonVirtualizedRows method).

For reference, here's the PR that made this change: https://github.com/dotnet/aspnetcore/pull/53473. It was done to simplify styling of the rows.

> if you have to render empty rows, don't include styles

It's actually Bootstrap that adds the styling for the empty `td` elements.

> I prefer to see empty data template so I can put my markup there if there's no data present.

Do you want to open a separate GitHub issue to suggest this feature?

> What's ETA on fixing this?

It seems like the right fix is to style the rows to all be the same height when using a `Paginator`, which I think needs to happen in the app since Blazor doesn't know what the expected line height is. @SteveSandersonMS Thoughts?

**Comment by htmlsplash** [comment]
"Do you want to open a separate GitHub issue to suggest this feature?" - I'll do that sometime tomorrow.

"It's actually Bootstrap that adds the styling for the empty td elements." - What I meant to say is, you can render placeholder rows/tds, just when rendering them don't call class="@ColumnClass(col), because the ColumnClass is that class to use when the rows are visible, not empty place holders, or better yet, use separate class, so we can specify place holder classes.

**Comment by htmlsplash** [comment]
Requested fix to this problem here: #59078

**Comment by danroth27** [comment]
I've opened https://github.com/dotnet/aspnetcore/issues/59096 to track documenting our guidance on styling the additional empty rows when using a paginator with QuickGrid.
