### ISSUE TITLE
OpenAPI activates transformers too many times

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#57211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm doing so work comparing the performance of M.A.OpenApi with NSwag and Swashbuckle, and based on my current numbers, M.A.OpenApi is coming out as the slowest.

As part of looking into that I noticed that using `AddSchemaTransformer<T>()` seemed to be significantly slower (~20ms: https://github.com/martincostello/aspnetcore-openapi/pull/23#issuecomment-2273228860) than `AddSchemaTransformer(IOpenApiSchemaTransformer)`. It makes sense that the former is slower as it's DI-activated vs. a singleton, but I was surprised at how much slower.

Doing some further digging with trying to make the service a singleton, I noticed that the transformer instance was being activated 15 times per HTTP request to get the OpenAPI document - I would expect only one for the lifetime of the application.

### Expected Behavior

Document/operation/schema transformers are only activated as many times as their associated service registration requires (singleton vs. scoped vs. transient etc.).

### Steps To Reproduce

1. Clone https://github.com/martincostello/aspnetcore-openapi/commit/8805a51f3cb68444177a47f1112b4f630cd0cfe5
2. Launch the application in a debugger
3. Navigate to the `https://localhost:50001/swagger-ui/index.html` URL
4. Observe the following debug output:

```
Activations: 1
Activations: 2
Activations: 3
Activations: 4
Activations: 5
Activations: 6
Activations: 7
Activations: 8
Activations: 9
Activations: 10
Activations: 11
Activations: 12
Activations: 13
Activations: 14
Activations: 15
```

### .NET Version

9.0.100-preview.7.24406.8

**Comment by captainsafia** [comment]
@martincostello Thanks for filing this issue!

I suspect what's happening here is that the transformer is being activated once for each top-level schema in the document as a result of [this logic](https://github.com/dotnet/aspnetcore/blob/257d69079e0f7fc84e3f6cd5047272d7f79b4d66/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs#L162-L176) that supports activating/disposing type-based schema transformers once for each top-level schema. We probably actually want to move this logic up higher in the stack and do it once for each request.

Our perf benchmarks missed this because they test multiple transformers against a single schema instead of a single schema transformer against multiple schemas.

> Document/operation/schema transformers are only activated as many times as their associated service registration requires (singleton vs. scoped vs. transient etc.).

I expect this issue to only be happening to schema transformers, and not document/operation transformers but I'll have to write a benchmark to verify. Document/operation transformers are both modeled as document transformers that get instantiated once per document (and each document is instantiated once per request by extensions).

I'll take a deeper look tomorrow to verify my intuition here but I think we can land a fix for this in RC1.

**Comment by martincostello** [comment]
Something to check for as well is if the lifetimes are working correctly. With the repro, I currently get 15, 30, 45 etc as the document is requested.

For a singleton I would just expect 1 and then no further output (like with a manually created singleton transformer), but the "once per request" resolution change sounds like it would yield 1, 2, 3 etc.

**Comment by martincostello** [comment]
> I'm doing so work comparing the performance of M.A.OpenApi with NSwag and Swashbuckle, and based on my current numbers, M.A.OpenApi is coming out as the slowest.

FYI with the fix for #56990 these are the latest numbers I get, and now you're second 😎:

```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.22621.3880/22H2/2022Update/SunValley2)
12th Gen Intel Core i7-1270P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 9.0.100-rc.1.24408.25
  [Host]     : .NET 9.0.0 (9.0.24.40709), X64 RyuJIT AVX2
  DefaultJob : .NET 9.0.0 (9.0.24.40709), X64 RyuJIT AVX2
```
| Method      | Mean       | Error     | StdDev    | Gen0     | Gen1    | Allocated |
|------------ |-----------:|----------:|----------:|---------:|--------:|----------:|
| AspNetCore  | 1,223.9 μs |  27.37 μs |  79.84 μs |  46.8750 |  7.8125 | 428.96 KB |
| NSwag       |   219.4 μs |   5.74 μs |  16.10 μs |   2.9297 |       - |  26.54 KB |
| Swashbuckle | 2,535.0 μs | 107.42 μs | 304.75 μs | 156.2500 | 31.2500 | 1452.2 KB |

**Comment by martincostello** [comment]
If I "level" the playing field by disabling the [caching that NSwag does by the host name](https://github.com/RicoSuter/NSwag/blob/7d6df3af95081f3f0ed6dee04be8d27faa86f91a/src/NSwag.AspNetCore/OpenApiDocumentMiddlewareSettings.cs#L43), then you move into first place:

```

BenchmarkDotNet v0.14.0, Windows 11 (10.0.22621.3880/22H2/2022Update/SunValley2)
12th Gen Intel Core i7-1270P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 9.0.100-rc.1.24408.25
  [Host]     : .NET 9.0.0 (9.0.24.40709), X64 RyuJIT AVX2
  DefaultJob : .NET 9.0.0 (9.0.24.40709), X64 RyuJIT AVX2


```
| Method      | Mean     | Error     | StdDev    | Median   | Gen0     | Gen1    | Allocated  |
|------------ |---------:|----------:|----------:|---------:|---------:|--------:|-----------:|
| AspNetCore  | 1.022 ms | 0.0290 ms | 0.0832 ms | 1.013 ms |  42.9688 |  7.8125 |  428.87 KB |
| NSwag       | 5.524 ms | 0.2430 ms | 0.6933 ms | 5.266 ms | 171.8750 | 31.2500 |  1590.7 KB |
| Swashbuckle | 2.683 ms | 0.0823 ms | 0.2400 ms | 2.633 ms | 156.2500 | 31.2500 | 1452.16 KB |

**Comment by captainsafia** [comment]
> For a singleton I would just expect 1 and then no further output (like with a manually created singleton transformer), but the "once per request" resolution change sounds like it would yield 1, 2, 3 etc.

Hmmm, the way I was seeing it, type-based transformers always have a scoped lifetime when they are registered ([similar to middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-8.0), for example) since there is no way to explicitly associate a lifetime with a registered transformer.

The current bug is that schema/operation transformers violate this expectation because they end up being called once for each operation or schema respectively.

However, I would expect that singleton dependencies resolved within a transformer respect that lifetime.

```
var builder = WebApplication.CreateBuilder();

builder.Services.AddSingleton<Dependency>();
builder.Services.AddOpenApi(options =>
{
	options.AddSchemaTransformer<SchemaTransformerWithDependency>();
});

// Instanitated for each request to the document service
public class SchemaTransformerWithDependency(Dependency dependency) : IOpenApiSchemaTransformer
{
	// ..
}

// Instantiated once for the lifetime of the application, regardless of how many times the
// Open API document is generated
public class Dependency { }
```

The transformer itself has a scoped, not singleton, lifetime. If we take a bit more inspiration from `IMiddlewareFactory`, it _does_ allow you to register middleware as either scoped or transient. So we could look into transformers with a transient scope but I dunno how valuable that would be.

Another gotcha here is the resolution of transient services in the middleware. Because we resolve the transformer once-per-request, transient services effectively have a scoped lifetime. Middlware works around this by allowing you to inject transient services into the `InvokeAsync` call so that you get a new instance every time the middleware is applied, or in our case every time `TransformAsync` is invoked.

So, there's a spectrum for how sophistcated we want to get with managing scopes in the factory-actived transformers here. We can go as far as replicating what we do with middleware or stick with the currrent convention which is:

- Transformers always have a scoped lifetime where the "unit-of-work" is a single request to generate the OpenAPI document.
- Transformers respect the singleton lifetime of dependencies they take with that lifetime.
- Transformers respect the scoped lifetime of dependencies they take with that lifetime.
- Transformers do not respect the transient lifetime of dependencies they take on (those are always effectively scoped).

**Comment by martincostello** [comment]
That sounds reasonable to me - I guess I'm just used to the way "normal" services behave. Scoped behaviour should be fine 👍
