### ISSUE TITLE
Add a new parameter to the ImportMap component that allows to specify a Nonce for the importmap html script

### ISSUE THREAD

**Issue by ghidello** [dotnet/aspnetcore#57277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I created a new .Net 9.0 preview 6 Blazor Web App with the global Auto interactivity mode.
I applied the content security policies from the [documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-9.0#client-side-blazor-apps) adding what's needed for local development:

```html
    <meta http-equiv="Content-Security-Policy"
          content="base-uri 'self';
                default-src 'self';
                img-src data: https:;
                object-src 'none';
                script-src 'self' 'wasm-unsafe-eval';
                style-src 'self';
                upgrade-insecure-requests;
                connect-src 'self' ws://localhost:* http://localhost:* "> <!-- For local development -->
```

Chrome and Firefox refuse to execute the importmap inline script because it is not allowed by the content security policy.

### Describe the solution you'd like

Add a new nullable string parameter to the ImportMap componet for specifying a Nonce and use it to create a nonce attribute on the importmap script tag:

```csharp
public sealed class ImportMap : IComponent
{
	\\...
	
	[Parameter] public string? Nonce { get; set; }
	
	\\...

	private void RenderImportMap(RenderTreeBuilder builder)
	{
		builder.OpenElement(0, "script");
		builder.AddAttribute(1, "type", "importmap");

		if (!string.IsNullOrWhiteSpace(Nonce))
		{
			builder.AddAttribute(2, "nonce", Nonce);
		}

		builder.AddMarkupContent(3, _computedImportMapDefinition!.ToJson());
		builder.CloseElement();
	}
}
```

### Additional context

Browser error example:

![importmap_csp_error](https://github.com/user-attachments/assets/c5f53f54-8151-4b71-ba53-b0c93a8c062a)

Possible fix in action (in this example the CSP are in an header):

![importmap_csp_error_possible_fix](https://github.com/user-attachments/assets/1ead84c0-b0aa-4a7e-a15e-eb5a946d1118)

![importmap_csp_error_possible_fix_headers](https://github.com/user-attachments/assets/4bd2cf7f-0f79-4871-8399-b1a60c6216d9)

**Comment by javiercn** [comment]
@ghidello thanks for contacting us.

I've created a PR with a fix https://github.com/dotnet/aspnetcore/pull/57282 so that the additional parameters can be passed down to the script tag.

That said, there's (in my opinion) a better alternative. You can grab the `ImportMapDefinition` from endpoint metadata, compute the sha256 hash and add that to the CSP policy instead of using the nonce.

**Comment by ghidello** [comment]
Wow, that was fast! Thanks.

I'm using [NetEscapades.AspNetCore.SecurityHeaders](https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders) so I thought to simply apply the Nonce created by the library. 
I like your approach better though, I'll see if I can integrate it with the library.

Thanks again!

**Comment by ghidello** [comment]
I got a working hack but I had to steal the internal [ToJson](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Endpoints/src/Assets/ImportMapDefinition.cs#L206) method code and change the [JsonSerializerOptions](https://github.com/dotnet/aspnetcore/blob/1df67c0c8bf3e31ea6fc25308c40cb76367ba8a1/src/Components/Endpoints/src/Assets/ImportMapSerializerContext.cs#L15) adding `NewLine = "\n"` in order to have a valid sha (I'm on Windows).

I'm a bit on the fence about asking, because probably using a Nonce is simply easier, but do you think it could be doable to expose the JsonSerializerOptions so I could simply clone them adding the NewLine specification?

**Comment by javiercn** [comment]
@ghidello you can call `ToString` https://github.com/dotnet/aspnetcore/blob/main/src/Components/Endpoints/src/Assets/ImportMapDefinition.cs#L213 as a proxy and you avoid calling ToJson.

I'm not opposed to changing our internal options to use a different line ending, but I have to think for a split second about it, since I don't like the idea of potentially mixing line endings on a page.

In any case, you can handle the serialization yourself if you want to have full control over it, it's like 3 lines of code.

Finally, IMO using a hash with CSP is better because it offers a stronger guarantee that the content is what you expected. I only recommend using nonce as a last resort and author/architect your app to avoid it where possible (for example no "dynamic" inline scripts)

**Comment by ghidello** [comment]
I don't know how I missed the `ToString` method. Sorry! Thanks again.
