### ISSUE TITLE
Use case support for Blazor Web App in Interactive Auto mode

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspnetcore#57327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have an existing external API that is built in .NET 8 using controllers and authenticated using a JwtBearer provided by our Single Sign On OIDC server.

In Blazor, running in InteractiveAuto rendering mode, I want to be able to have the user log in via OIDC.

I then want to have access to the ClaimsPrincipal and the access_token in my components regardless of whether they are being rendered on the server or in the wasm client.

This doesn't seem possible currently, but I think Blazor should be handling this case. If Blazor is being split into two applications, then it should handle authentication like this seamlessly.

### Describe the solution you'd like

My current thinking would be to be able to use Blazor something like this...

```cs
// In Blazor/Program.css
builder.Services.AddOidcAuthentication(options => {
  // ... snip config ...
});

// `AddOidcAuthentication` could just be a convenience method that adds everything needed 
// for authentication against OIDC providers, including the cookies

var apiBaseUrl = builder.Configuration["ApiBaseUrl"];
builder.Services.AddHttpClient("my-api-client", client => {
  client.BaseAddress = new Uri(apiBaseUrl, UriKind.Absolute);
}).AddAuthenticationHeaders();
```

```cs
// In Blazor.Client/Program.cs
builder.Services.AddServerAuthetnication();

// The idea here is that AddServerAuthentication handles setting up
// everything needed for the client to have access to the authentication state,
// ClaimsPrincipal and access_token from the server's authentication

var apiBaseUrl = builder.Configuration["ApiBaseUrl"];
builder.Services.AddHttpClient("my-api-client", client => {
  client.BaseAddress = new Uri(apiBaseUrl, UriKind.Absolute);
}).AddAuthenticationHeaders();
```

Then, in my components (in the WASM Blazor.Client project) I should be able to do this:

```cs
@inject IHttpClientFactory Factory

@* ... snip markup ... *@

@code
{
  protected override async Task OnInitializedAsync()
  {
    var client = Factory.CreateClient("my-named-client");
   // Now I can use `client` to make authenticated requests to my API
  }
}
```

This way, it wouldn't matter if the components were being pre-rendered, SSR or Client rendered - it should just work.

Additionally, if I use the CascadingAuthenticationState in my components/pages I should be able to get the `ClaimsPrincipal` from it regardless of where it's being rendered. The same goes for the access token...

```cs
@inject IHttpClientFactory Factory

@* ... snip markup ... *@

@code
{
  [CascadingParameter]
  public Task<AuthenticationState>? AuthState { get; set; }

  protected override async Task OnInitializedAsync()
  {
    var user = (await AuthState)?.User;
    var accessToken = user.GetAccessToken(); // or similar
  }
}
```

### Additional context

I've spent months trying to get the InteractiveAuto rendering mode working in my scenario but have ultimately given up as I was spending more time trying to figure this out than actually building my application.

Every tutorial, course, etc. that I've seen that attempts to touch on Blazor authentication in .NET 8 is either focussed entirely on the server, uses EF Core and Identity that way or just completely glosses over it without giving any useful information on how to use it in this (what should be) relatively simple and common scenario.

Asking for help on forums and Discord has equally yielded no tangible results.

It seems that this is a gap in the design of Blazor currently.

**Comment by javiercn** [comment]
@hades200082 thanks for contacting us.

This is already possible, however, if you are using Blazor with auto mode, the way to go is to use BFF (Backend For Frontend). Your server (not the browser) initiates the auth request, captures the tokens and stamps a cookie containing the results.

When your page renders on the server, you flow the tokens to interactive modes (server or webassembly) using persistent component state.

This is what our template with auth does (- the tokens part).

**Comment by javiercn** [comment]
@halter73 can you point people to your sample?

**Comment by hades200082** [comment]
@javiercn i literally spent months trying to get this to work with my API and OIDC provider following the samples I could find, trying to get help on Discord and it just never worked. 

In my use case the users roles and permissions are retrieved from the API as part of their app user profile. 

Nothing I tried would let me get custom claims into the Blazor claims principle for both server and client AND still have the access token available for both as well.

**Comment by halter73** [comment]
@hades200082 Have you looked at https://learn.microsoft.com/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=with-bff-pattern? It uses the server-side `AddOpenIdConnect` and `AddCookie` methods which configure OIDC sign in and store the access and refresh token in an encrypted cookie rather than use `AddOidcAuthentication` which is a WebAssembly-only API based on oidc-client-js.

Using the access token you acquired from WebAssembly during prerendering before the WebAssembly runtime loads is definitely going off the beaten path. It would likely require custom cookie-based logic. And even then, are you going to write your own logic to do a server-side refresh during prerendering when the access token expires? Why not just make it all server-side then? I doubt any OIDC provider would consider using a token acquired from WebAssembly/JS in the browser during server prerendering a supported scenario.

We recommend using the BFF pattern for this type of use case, because you want to be able to make authenticated requests from both the server and WebAssembly with the auto render mode, and you typically do not want to expose access and refresh tokens to the browser when they're acquired with a secret on the server. SPA access more susceptible to being stolen by malicious JS which is why Entra gives SPA refresh tokens a much shorter lifetime than server-side ones.

https://learn.microsoft.com/en-us/entra/identity-platform/refresh-tokens#token-lifetime

BFF here basically means the WebAssembly client first makes a request to the host server using cookie authentication, and then the host proxies the request without the cookie but with the JWT access token to the ultimate backend. The sample uses [YARP](https://github.com/microsoft/reverse-proxy/) via [MapForwarder](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs#L209-L216) in the Blazor server project to attach the access token stored in the encrypted authentication cookie to the ultimate backend which is protected by JWT bearer authentication using the JwtBearerHandler. It also [transparently refreshes the access token](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidc/BlazorWebAppOidc/CookieOidcServiceCollectionExtensions.cs#L15) if it's nearing expiration or already expired (so long as the refresh token isn't also expired ofc).

It also uses persistent component state to serialize any claims that you might need from the server on the client. [`UserInfo`](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/UserInfo.cs) is the `ClaimsPrincipal` DTO used for [serialization](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/PersistingAuthenticationStateProvider.cs)/[deserialization](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/PersistentAuthenticationStateProvider.cs) in the sample, and it only reads the sub and name claims currently.

It could be updated to serialize anything including the access token if you want to make request directly to the backend from the client instead of following the BFF pattern. However, the BFF pattern is likely more secure, since it avoids using the same tokens on multiple devices and avoids exposing any tokens directly to JS.

**Comment by MackinnonBuck** [comment]
Thanks, @hades200082.

It seems that what you're trying to do isn't currently supported by the framework. We will take into account this feedback when considering how we can improve things in the future. The framework doesn't have a built-in mechanism to share an access token between the client and the server.

We think your alternative of using WebAssembly interactivity (not Auto) is a good choice if you don't want to use BFF or implement your own token sharing logic.

**Comment by hades200082** [comment]
@MackinnonBuck You should take a look at how NextJS, React Server Components and next-auth work from a DX perspective. 

So much simpler and they abstract away from the developer the complexity so the developer can focus on building their app rather than scaffolding.

**Comment by halter73** [comment]
Are you talking about [this](https://github.com/nextauthjs/next-auth/issues/7913#issuecomment-1614987449)? Can you point more specifically to the design you would like us to emulate?

**Comment by hades200082** [comment]
@halter73 

First, let me say that I've been working with .NET since Framework 2.2. Before that I worked mostly with PHP, but dabbled with ASP Classic. I only started working with JS frameworks like NextJS about 3 years ago. I say this so that it's clear that I am primarily a .NET developer. 

There are a number of areas where I feel Blazor, and in particular the "InteractiveAuto" rendering mode, could benefit from taking a leaf out of the playbook of other front-end frameworks such as NextJS.

1. **Server vs Client rendering**
  In NextJS, the default for "pages" is for them to be server-rendered (using React Server Components). However, interactive components on those pages (or indeed the pages themselves) may be marked as "use client". This doesn't mean that those components are entirely client-rendered - NextJS will still server-render as much of them as it can. It means that the interactive aspects of them (e.g. useEffect and other React hooks) execute in the browser. No separate "client" project is needed.
  
    The server-rendered page can make HTTP requests to fetch content from anywhere. Likewise, the "use client" components can also make HTTP requests as needed. Both utilise the JavaScript `fetch` API to make these requests, NextJS just wraps this with its own version on the server side to aid with caching, etc.
  
2.  **Authentication**
  Authentication with Blazor, especially in relation to basic, provider-agnostic OIDC, is woefully under-documented. Even course creators and YouTubers ignore or gloss over this area which tells me it is simply not well enough understood in the Blazor community.
  
    In NextJS with Next-Auth we can use `getServerSession()` for retrieving the user and tokens if the code is in the server context (which is most places by default), or simply `getSession()` if it's inside a hook which runs in the browser. 
  
    It can even be wrapped up into a single utility function for ease: `return typeof window === "undefined" ? getServerSession() : getSession();`
  
    The "session" is a JavaScript object that is created/defined in the callbacks of the authentication process. These would be analogous to the `OpenIdConnectEvents` and the `ClaimsPrincipal` in .NET. In Next-Auth we can have our user session object contain the information we need (e.g. claims, permissions, etc.) and even store the access_token on it. This is stored in an encrypted cookie, which handles expiry, and next-auth takes care of deleting the cookie when the user logs out.
  
    Since we have access to the access_token within some of the callbacks, we can even make an authenticated call to our API to get the roles and permissions - which we can then use in the pages & routing to control access/visibility of pages or individual components.
  
    Since we can get the access_token on either client or server the components can make authenticated requests from either. Next-auth takes care of refreshing the token when needed.
    
    The bottom line here is that Blazor needs to make authentication far simpler to implement, especially in the InteractiveAuto scenarios. It needs to be simple to configure (ideally in one place) and then just needs to work, including the ability to use the access_token in HTTP requests. If that means BFF then Blazor should handle that proxying without needing custom setup.
  
3. **Overall developer experience**
  This one is a little harder to articulate. 
  
     NextJS when I create a new project, I can install next-auth, add the OIDC configuration and callbacks to create the session object and can be getting on with building my application within 30m-1h.
  
    In Blazor, all I've been able to do so far _in 3 months_ is scaffolding. Copy/pasting code from examples trying to get the ability to make authenticated API requests on both client and server to allow pre-rendering to work for client components.
    
    Part of this has to do with the ecosystem. NextJS developers have access to a massive ecosystem of npm packages, React libraries, etc. There's very little out there for Blazor in comparison. 
    
    Additionally, many front-end tools are much harder to implement for Blazor (Tailwind CSS for example) owing to the absence of a traditional front-end build process (npm/yarn/webpack/etc.)
    
    There is also a lot of confusion, outdated information, etc. out there on sites like Stack Overflow, YouTube and various online training sites owing to the multiple versions and multiple render modes within Blazor. (more on that below)
      
4. **Better documentation**
  If I need to look up how to do something for NextJS, all the documentation is in one place: https://nextjs.org/docs

    The documentation for Blazor is fragmented, spread across many sections of https://learn.microsoft.com/, https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor and https://blazor-university.com/
    
    In my opinion (pun intended), this fragmentation of documentation is party due to the attempt by Blazor to remain "unopinionated" - relying on the core .NET documentation to tell people how to do things, while branching off to other categories or sites for the things that are very Blazor specific. This increases the learning curve for Blazor.
    
    Another thing contributing to the confusion and fragmented documentation is the different render modes and project types. Again, in my opinion, there should be one single Blazor project type - Blazor - and the handling of wasm vs server vs pre-render ... etc. should be handled as invisibly as possible by the framework.

**Comment by veikkoeeva** [comment]
For what its worth @hades200082, I think if Blazor were to embrace more web components, also declarative ones in this context, it would perhaps be easier to tap into those processes and bring other tooling and libraries to the fold. So, improve developer experience and by extension authentication experience. Some of that may go to the router experience (with cookies), which may be one struggle as far as I've seen in projects.

For that piece in particular, I may be in minority, but the "black box experience" that "do this" is more difficult than have a documentation of copy-paste and a clear sequence diagram on what are the sequences in various flows.

All that being noted, just to ensure that you've seen https://damienbod.com/2022/01/03/secure-a-blazor-wasm-asp-net-core-hosted-app-using-bff-and-openiddict/ amongst other samples there. You probably have, but even in that case it may help others looking for a BFF like experience and rendering something on the server.

**Comment by AmirAmeri** [comment]
you can used :
    private IComponentRenderMode? RenderModeForPage
      => HttpContext.GetEndpoint().Metadata.GetMetadata<RenderModeAttribute>()?.Mode;

instead :
 => HttpContext.Request.Path.StartsWithSegments("/Account")
     ? null
     : InteractiveWebAssembly;

in App.razor in server side . Complete Code is :

App.razor :

<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="custom.css" />
    <link rel="stylesheet" href="FarbuildFluent.Wasm.styles.css" />
    <script src="js/anchorLink.js"></script>
    <link rel="icon" type="image/x-icon" href="favicon.ico" />


    <HeadOutlet @rendermode="RenderModeForPage" />
</head>

<body>
    <Routes @rendermode="RenderModeForPage" />

    <script src="_framework/blazor.web.js"></script>
</body>

</html>

@code {
    [CascadingParameter]
    private HttpContext HttpContext { get; set; } = default!;


    private IComponentRenderMode? RenderModeForPage
      => HttpContext.GetEndpoint().Metadata.GetMetadata<RenderModeAttribute>()?.Mode;
}

this parameter resolve your cascading role and you can used for client and server side .
