### ISSUE TITLE
AuthorizationHandler called twice when using a global filter

### ISSUE THREAD

**Issue by lukos** [dotnet/aspnetcore#57348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is already a bug reported a few years back here: https://github.com/dotnet/aspnetcore/issues/32518 which says that if you apply a global `AuthorizeFilter` but add a more specific `AuthorizeAttribute` to an action, then the auth handler is invoked twice, which is both unexpected and potentially poor performance.

The original comment was that this was "by design" but I am not sure they meant that they wanted it to do this, just that a change to the architecture had this as a side effect because it doesn't make sense to me and won't allow us to create a more specific policy over the gobal filter. To be clear, I don't have a problem with the fact that the global filter will perform a simple authenticated check before then calling my specific authorization policy, the issue is that the exact same handler is called twice as if the global filter sees the attribute, runs its policy and then the attribute does the same thing again.

### Expected Behavior

Preferred behaviour would be that either the `AuthorizeAttribute` overrides the global `AuthorizeFilter` OR the global filter does a simple authentication check and the specific auth handler is *only* called as a result of the policy in the attribute.

### Steps To Reproduce

Create a .Net 8 API application and add a global auth filter:

```c#
builder.Services.AddControllers(options => options.Filters.Add(new AuthorizeFilter()));
```

Create an action that has a specific policy:

```c#
[Authorize("My policy")]
public IActionResult MyAction()
{
    return Ok();
}
```

Configure that policy to call a handler e.g.

```c#
builder.Services.AddAuthorizationCore(options => options.AddPolicy("My policy", policy => policy.Requirements.Add(new MyHandlerRequirement()));
```

In order to workaround this weird behaviour, the original bug said to add a specific controller route, which disables the global filter like this (it does disable the global filter for sure):

```c#
app.MapControllerRoute(name: "test_route",
        pattern: "test",
        constraints: new { httpMethod = new HttpMethodRouteConstraint("POST") },
        defaults: new { controller = "Home", action = "MyAction" })
        .RequireAuthorization("My Policy");
```

BUT, the attribute routing from the controller takes precedence over this conventional routing configuration, so this still won't work for my project that uses attribute routing. It might have been an OK workaround when everyone was using conventional routing but the attribute routing is really valuable for APIs.

### .NET Version

8.0.304

**Comment by halter73** [comment]
> The original comment was that this was "by design" but I am not sure they meant that they wanted it to do this, just that a change to the architecture had this as a side effect because it doesn't make sense to me and won't allow us to create a more specific policy over the gobal filter.

MVC's `AuthorizeFilter` is supported for backwards compatibility, but the recommendation since ASP.NET Core 3 has been to use Authorization middleware instead which supports all ASP.NET Core endpoints instead of just MVC. So our recommendation would be to remove `options.Filters.Add(new AuthorizeFilter())` and instead call `app.MapControllers().RequireAuthorization()`.

> When using endpoint routing, we recommend against configuring [AuthorizeFilter](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.authorization.authorizefilter) and instead relying on the Authorization middleware. If the app uses an AuthorizeFilter as a global filter in MVC, we recommend refactoring the code to provide a policy in the call to AddAuthorization.

https://learn.microsoft.com/aspnet/core/migration/22-to-30#authorization

Nothing prevents you from MVC's `AuthorizeFilter` and Authorization middleware together, but they weren't designed to be used together, so you might run into issues like your auth handler being invoked twice.

> BUT, the attribute routing from the controller takes precedence over this conventional routing configuration, so this still won't work for my project that uses attribute routing. It might have been an OK workaround when everyone was using conventional routing but the attribute routing is really valuable for APIs.

Were you not calling `MapControllerRoute` before? It does support attribute routing. The conventional routing configuration would only apply to controller actions that do not use attribute routing. For actions that do use attribute routing, `MapControllerRoute` and `MapControllers` do the exact same things. And any call to `RequireAuthorization()` on the returned builder will apply equally to endpoints using conventional and attribute routing.

If you know all your actions use attribute routing, you can call `MapControllers` instead though.

```csharp
app.MapControllers().RequireAuthorization();
```

If you were call `UseMvc()` instead, we recommend upgrading it to call `MapControllerRoute` or `MapControllers` instead in order to take full advantage of [Endpoint Routing](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0).

https://learn.microsoft.com/aspnet/core/migration/22-to-30?#routing-startup-code

**Comment by MackinnonBuck** [comment]
Closing this as by design. We don't think there's a framework issue here. If you disagree, please file a new issue describing the bug. Thanks!
