### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24379.15] Fail to load page in nopCommerceNetCore app after retargeting it to .NET 9.0 with error: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#57493]
### Description

When retarget the 3rd party application to net9.0, build and run with the latest .NET 9 build, it failed to load page with error:
```System.NullReferenceException: Object reference not set to an instance of an object```.  When retargeting it to net9.0 using dotnet-sdk-9.0.100-preview.5.24307.3, this issue does not reproduce.

**Findings:**
After debugging into the source code of application, we found the exception is thrown from [NUglify ](https://github.com/trullock/NUglify)nuget package, which is referenced by [WebMarkupMin.NUglify](https://github.com/Taritsyn/WebMarkupMin) nuget package.
And if we reference the NUglify and WebMarkupMin.NUglify nuget packages source code into application source code directly, we found the exception is thrown at ```JSParser.ParseUnaryExpression()``` method in JSParser.cs file (line 3665) from NUglify package. 
The expr variable in line 3664 returns a null object, which result to the line 3665 get "```Object reference not set to an instance of an object```" exception: 
```
expr = ParseUnaryExpression(out dummy, false); //It returns null
ast = new UnaryExpression(exprCtx.CombineWith(expr.Context)) //The null expr causes the error
    {
        Operand = expr,
        OperatorContext = exprCtx,
        OperatorToken = opToken
    };

```

### Reproduction Steps

**Please get the repro machine information from** [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455)
1.Open "...\Source\nopCommerce\src\Presentation\Nop.Web\Nop.Web.csproj" with Visual Studio.
2. Retarget Nop.Web to net9.0.
```<TargetFramework>net9.0</TargetFramework>```
3. Build the app with dotnet-sdk-9.0.100-preview.7.24379.15.
4. Run the app.
5. Go to "https://localhost:56111/Admin/Order/List" on browser.(If need login, account and password refer to [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455))
6. Click "View" in order list.

### Expected behavior

Page loading successfully 

### Actual behavior

Page loaded failed with errors:
```System.NullReferenceException: Object reference not set to an instance of an object.```

StackTrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at WebMarkupMin.NUglify.NUglifyJsMinifier.Minify(String content, Boolean isInlineCode, Encoding encoding)
   at WebMarkupMin.NUglify.NUglifyJsMinifier.Minify(String content, Boolean isInlineCode)
   at WebMarkupMin.Core.GenericHtmlMinifier.ProcessEmbeddedScriptContent(MarkupParsingContext context, String content, String contentType)
   at WebMarkupMin.Core.GenericHtmlMinifier.EmbeddedCodeHandler(MarkupParsingContext context, String code)
   at WebMarkupMin.Core.Parsers.HtmlParser.ProcessEmbeddedCode()
   at WebMarkupMin.Core.Parsers.HtmlParser.Parse(String content)
   at WebMarkupMin.Core.GenericHtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.Core.HtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.AspNetCore8.BodyWrapperStreamBase.<InternalFinishAsync>d__24.MoveNext()
   at WebMarkupMin.AspNetCore8.BodyWrapperStreamWithResponseBodyFeature.<FinishAsync>d__5.MoveNext()
   at WebMarkupMin.AspNetCore8.WebMarkupMinMiddleware.<InvokeCore>d__2.MoveNext()
   at WebMarkupMin.AspNetCore8.WebMarkupMinMiddleware.<InvokeCore>d__2.MoveNext()
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__5.MoveNext()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
   at Nop.Services.Installation.InstallUrlMiddleware.<InvokeAsync>d__2.MoveNext() in C:\Users\test01\Desktop\Source\nopCommerce\src\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 50
```

### Regression?

Yes

Verify Scenarios:
1). Windows 10 21H2 AMD64 + default target net8.0 + default dotnet-sdk-8.0.300: Pass
2). Windows 10 21H2 AMD64 + default target net8.0 + dotnet-sdk-9.0.100-preview.7.24379.15: Pass
3). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.5.24307.3: Pass
4). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.6.24328.19: Fail
5). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.7.24375.12: Fail
6). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.7.24379.15: Fail

### Configuration

**Application Name**: nopCommerceNetCore
**OS**：Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-preview.7.24379.15
**App Source or Repro machine checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455
**GitHub Link**:
https://github.com/nopSolutions/nopCommerce

**Dotnet Info:**
```
.NET SDK:
 Version:           9.0.100-preview.7.24379.15
 Commit:            812e813ae9
 Workload version:  9.0.100-manifests.28aae763
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24379.15\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.7.24376.15
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.7.24379.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24379.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24376.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24379.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Other information

@dotnet-actwx-bot @dotnet/compat

**Comment by javiercn** [comment]
I've moved this to a milestone and put it in our project board. It was incorrectly labeled so we lost track of it.

I've also taken a quick look at the issue, but the Visual Studio instance on the repro machine has an expired license.

**Comment by javiercn** [comment]
@Junjun-zhao can you make sure visual studio is up to date on the repro machine and usable?

**Comment by javiercn** [comment]
@Junjun-zhao this appears to be fixed.

![image](https://github.com/user-attachments/assets/48fb8ee6-5e7f-43f1-a359-c852b3064a8d)

![image](https://github.com/user-attachments/assets/635e7619-2be1-4d82-9fcc-9d8de0e374f1)

**Comment by javiercn** [comment]
And this is the same running with RC2
![image](https://github.com/user-attachments/assets/55467622-5d33-4783-978b-e47abbff9121)

![image](https://github.com/user-attachments/assets/3b474e78-8e5a-42b4-aa41-e02d6185a569)

**Comment by javiercn** [comment]
Wrong screenshot, but still works
![image](https://github.com/user-attachments/assets/c991e507-b427-436d-b9de-9dfe33bcbf47)

**Comment by Junjun-zhao** [comment]
Hi @javiercn，

We verified with RC1 and RC2 build, this issue still reproduces.
1). Windows 10 21H2 AMD64 + target net9.0 +dotnet-sdk-9.0.100-preview.7.24407.12: Fail
2). Windows 10 21H2 AMD64 + target net9.0 +dotnet-sdk-9.0.100-rc.1.24422.10: Fail
3). Windows 10 21H2 AMD64 + target net9.0 +dotnet-sdk-9.0.100-rc.2.24425.2: Fail

Here is a video recorded for your reference： 
The Visual Studio on repro machine has been activated and updated to the latest version.
![ReproSteps (1)](https://github.com/user-attachments/assets/ec8be5ba-2338-4b2b-8c6a-7bd1856b1640)

**Comment by javiercn** [comment]
@AndyAyersMS we took a look.

We can only repro with the exact steps provided here. And when we look at the call stack, the markup throwing the exception is identical between 8.0 and 9.0.

Here is the markup from the callsite:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <title>Edit order details / nopCommerce administration</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    



<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" />








    
    



<link rel="stylesheet" type="text/css" href="/css/ay9_xl4b4hochtdfvoclsa.styles.css?v=Da65r2jowUqk07cscI7WfcqWWIQ" />

<script type="text/javascript" src="/lib_npm/jquery/jquery.min.js?v=ETctd0sWu37HRGyGqGIsZu5ju2A"></script>
```

And as I mentioned, is identical between 8.0 and 9.0.

In addition to that, it seems to be machine/environment specific? I can't reproduce the issue on my own machine.

**Comment by AndyAyersMS** [comment]
Is there any appreciable difference you can spot between the machines where you have a repro and the ones where you don't (different OS/CPU etc)?

Possibly this is a different problem with similar manifestation?

I would appreciate it if you could dig a little deeper on the machines where you have a repro. As this is all debug code it is unlikely an issue in the jit or runtime layers. I think it is more likely something upstack. If you run into a dead-end, then let me know.

**Comment by javiercn** [comment]
@AndyAyersMS I'm trying to dig into this. 

Unfortunately, I was trying to get more confirmation, and I suspect the reason I can't reproduce it on my box is that I don't seem to be hitting the same code path.

I've taken a look at the machine and the solution seems to have lots of changes applied to them (in my case I cloned and simply switched .net 8.0 to .net 9.0).

I'm somewhat at a loss here because when I hit
```
		public MarkupMinificationResult Minify(string content, string fileContext, Encoding encoding,
			bool generateStatistics)
		{
			return _genericHtmlMinifier.Minify(content, fileContext, encoding, generateStatistics);
		}
```

In the repro machine, the values are exactly the same for .NET 8.0 and .NET 9.0. I don't really know where else to look as from the callstack below, the same function is called with the same parameters. In my book that should produce the same result in the absence of any weird side-effect, which I think would be library specific.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at WebMarkupMin.NUglify.NUglifyJsMinifier.Minify(String content, Boolean isInlineCode, Encoding encoding)
   at WebMarkupMin.NUglify.NUglifyJsMinifier.Minify(String content, Boolean isInlineCode)
   at WebMarkupMin.Core.GenericHtmlMinifier.ProcessEmbeddedScriptContent(MarkupParsingContext context, String content, String contentType)
   at WebMarkupMin.Core.GenericHtmlMinifier.EmbeddedCodeHandler(MarkupParsingContext context, String code)
   at WebMarkupMin.Core.Parsers.HtmlParser.ProcessEmbeddedCode()
   at WebMarkupMin.Core.Parsers.HtmlParser.Parse(String content)
   at WebMarkupMin.Core.GenericHtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.Core.HtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
```

@Junjun-zhao I see a lot of files modified on that solution. Can we park this machine and try the scenario from scratch on a clean machine?

**Comment by Junjun-zhao** [comment]
@javiercn 
We may find the difference between us. We tried with the latest version of source code from Github, this issue does not reproduce (even on dotnet-sdk-9.0.100-preview.7.24379.15 which we filed this issue). 
 
The source code in our lab was downloaded in May, we have copied the source code in our lab to the new repro machine. The only changes we made on this machine is global.json file and retarget …\src\Presentation\Nop.Web\Nop.Web.csproj from net8.0 to net9.0. 
Please get the repro machine information from [Internal bug]（https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455）.  

The source code of our apps on GitHub may be a little different from the versions in our lab, as they are refreshed on a schedule according to our strategy in our lab.

**Comment by AndyAyersMS** [comment]
Yeah you need to be on a somewhat older release of nop commerce. The `qq-template` text and such I saw [here](https://github.com/dotnet/aspnetcore/issues/57493#issuecomment-2307881686) was removed in https://github.com/nopSolutions/nopCommerce/issues/6977.

@Junjun-zhao do you know the version number where you see the failure?

**Comment by Junjun-zhao** [comment]
@AndyAyersMS 
This issue reproduces on the latest release version 4.70.4, 
https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.70.4 

The latest code is 4.80.0 (Not released) which does not reproduce the issue.

**Comment by Junjun-zhao** [comment]
@AndyAyersMS Is there any update for this issue? Thanks for looking into this issue.

**Comment by AndyAyersMS** [comment]
I am hoping @javiercn can look once more now that we know what version of nop Commerce to use. If that's not possible I can look later this week, but it's likely outside my area of expertise.

**Comment by Junjun-zhao** [comment]
@javiercn Could you please help take look at this bug again?

This issue reproduces on the latest release version [4.70.4](https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.70.4), the latest code is 4.80.0 (Not released) which does not reproduce the issue.

Please get the repro machine information from [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455) if needed.

**Comment by Junjun-zhao** [comment]
@javiercn  Any update about this issue? We verified it with latest build dotnet-sdk-9.0.100-rc.2.24470.13, this issue still reproduces.  Will this be fixed on RC2 milestone?

**Comment by Junjun-zhao** [comment]
Hi @mkArtakMSFT @javiercn,  thanks for taking look at this issue.   Is there any update or plan for this issue? Will it be fixed into the .NET 9.0 GA build?

**Comment by javiercn** [comment]
@Junjun-zhao the credentials to access the machine are wrong.

**Comment by javiercn** [comment]
I did further investigation. The main delta that I see is

```
<script id="download381026284-qq-template" type="text/template">
```
gets transformed to
```
<script id="download1424106890-qq-template" type="text/javascript">
```
in the switch from 8.0 to 9.0.

I did try to reproduce this behavior on a recent enough release by spinning up a container with `9.0.200-preview.0.24527.8`, which in turn contains the runtimes below.

```console
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [/.dotnet/shared/Microsoft.NETCore.App]
```

Using these runtimes I was unable to reproduce this issue.

**Comment by javiercn** [comment]
Can we try with a newer build? (RTM)

**Comment by Junjun-zhao** [comment]
@javiercn We tried the issue with the latest RTM build dotnet-sdk-9.0.100-rtm.24523.42, it still reproduces.  
We have installed the RTM build on the repro machine.  We recorded a video for the repro steps, the file path is Desktop\Repro.gif on the repro machine. Or you also could get it from the attachment of [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2187455).

**Comment by javiercn** [comment]
Took another look.

The issue is on the library code.

![Image](https://github.com/user-attachments/assets/321dde02-3d39-4677-a6e3-01c8b8709eb3)

C:\SourceCode\nopCommerce\nopCommerce\src\Presentation\Nop.Web.Framework\TagHelpers\Shared\NopScriptTagHelper.cs

`NopScriptTagHelper` incorrectly checks on the output for the presence of a `type` attribute instead of checking the context and as a result, overrides the output type as `text/javascript` instead of leaving it as `text/template`.

```csharp
    {
        ArgumentNullException.ThrowIfNull(context);

        ArgumentNullException.ThrowIfNull(output);

        if (_webHelper.IsAjaxRequest(ViewContext.HttpContext?.Request))
            return;

        output.TagMode = TagMode.StartTagAndEndTag;

        if (!output.Attributes.ContainsName("type")) // we don't touch other types e.g. text/template
            output.Attributes.SetAttribute("type", MimeTypes.TextJavascript);
```

**Comment by PriyaPurkayastha** [comment]
@javiercn do we know what has changed in .NET 9 Preview 6 that is surfacing this issue in the library? Trying to understand why this works with .NET 9 Preview 5.

**Comment by javiercn** [comment]
@PriyaPurkayastha we updated the `script` tag helper to support `importmap` which needs to look at the `type` attribute.

I believe what happened is that in 8.0 the built-in `ScriptTagHelper` didn't process the `type` attribute, so the runtime/compiler copied that attribute directly to the output

Since on 9.0 we added support for `importmap` we started handling the `type` attribute and at that point didn't get automatically copied into the output.

This is a library issue because the library should not be checking the output for the presence of the `type` attribute, but it should check the `context` instead. It happened to work in 8.0 because our tag helper (or any other tag helper) wasn't processing the `type` attribute so it got automatically copied to the output.

Our change simply caused the underlying bug in the library implementation to surface. It's also the reason why it was "so hard" to find, this didn't repro without the `NopScriptTagHelper` being active to override the script `type`.

The behavior on the framework is considered by design, so this is something that they'll have to fix in their codebase.

**Comment by PriyaPurkayastha** [comment]
Thanks @javiercn for the details about what changed in .NET 9. I am not very familiar with this space, hence have a couple of additional questions: 
•Do we have any documentation published about the updates that have been made to script tag helper in .NET 9 where we have started handling type attribute because of which it doesn’t get included in the output? Is that considered a breaking change and if not, do we have any documentation that explains why this change is “allowed” and not considered breaking. For example something similar to [.NET API changes that affect compatibility - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules) 
•You mentioned that the library should be checking for the context instead of looking for the type attribute. Is this best practice or usage documented?
•I am not pushing back on the resolution that the library owners need to make a change at their end. I am trying to find out if you can publish a breaking change announcement for this so that other customers that might be having similar code pattern/usage and run into this hard to diagnose issue, can easily find out what they need to do.

**Comment by javiercn** [comment]
@PriyaPurkayastha we have docs for tag helpers here

•Do we have any documentation published about the updates that have been made to script tag helper in .NET 9 where we have started handling type attribute because of which it doesn’t get included in the output? Is that considered a breaking change and if not, do we have any documentation that explains why this change is “allowed” and not considered breaking. For example something similar to [.NET API changes that affect compatibility - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules)
•You mentioned that the library should be checking for the context instead of looking for the type attribute. Is this best practice or usage documented?

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-8.0

> I am trying to find out if you can publish a breaking change announcement for this so that other customers that might be having similar code pattern/usage and run into this hard to diagnose issue, can easily find out what they need to do.

I don't think this is a common scenario, if we get reports on GH we'll make an announcement, but at the time we don't believe this is common or worth documenting any further, the XML docs are already clear on this aspect 
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.taghelpers.taghelpercontext.allattributes?view=aspnetcore-8.0#microsoft-aspnetcore-razor-taghelpers-taghelpercontext-allattributes
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.taghelpers.taghelper.process?view=aspnetcore-8.0#microsoft-aspnetcore-razor-taghelpers-taghelper-process(microsoft-aspnetcore-razor-taghelpers-taghelpercontext-microsoft-aspnetcore-razor-taghelpers-taghelperoutput)

**Comment by AndyAyersMS** [comment]
Or was that for an older version...?

**Comment by Junjun-zhao** [comment]
> Or was that for an older version...?

It reproduces on the latest release version v4.70.5, does not reproduce on the latest code of nopCommerceNetCore app.
