### ISSUE TITLE
Route constraints invoked for paths which do not use the route constraint

### ISSUE THREAD

**Issue by onionhammer** [dotnet/aspnetcore#57572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using a {parameter} in one route and a {*catchall} in another route causes a RouteHandlers to be invoked unrelated requests

Example:

```
/tiles/{**path} 
/{partner:my_route_constraint}/{form}.js
```

the `my_route_constraint` will be invoked with "tiles" as the routeKey value of `partner` even though the path is not using that constraint, and is more specific (starts with /tiles/) for **certain** requests

example:

```
GET /tiles/one_segment <-- this hits the route constraint
GET /tiles/one_segment/two_second <-- this does not hit the route constraint
```

### Expected Behavior

If you specify a prefixed route, it should not hit a route constraint? 

### Steps To Reproduce

Here is a repo that reproduces the issue:

https://github.com/onionhammer/repro-routing-issue/blob/master/Program.cs

Reference test.http for example requests

### .NET Version

8.0.401

**Comment by javiercn** [comment]
@onionhammer thanks for contacting us.

This is by design. Routing evaluates the current path against all potential matches as a first step and then applies matcher policies and ordering to get a final result.
`/tiles/{**path}` might not match because it has an HTTP POST constraint and, in that case, `/tiles/sample.js` will still match and can't be discarded.

**Comment by onionhammer** [comment]
Why was the choice made to not just route to a more specific path?
