### ISSUE TITLE
I'm stuck in "Interact with data in Blazor web apps" learning path.

### ISSUE THREAD

**Issue by EkiciFurkan** [dotnet/aspnetcore#57675]
I want to finish this course and i wanna understund everyting about this course but i stock in this "dotnet new blazorserver -o BlazingPizzaSite -f net6.0" clı command ıt's not working

What ı can do for this situation ?

**Comment by EkiciFurkan** [comment]
> @EkiciFurkan can you post a link to the tutorial you are following?
> 
> Very likely needs an update for the 8.0 SDK and onwards, since that template got removed.

https://learn.microsoft.com/tr-tr/training/modules/interact-with-data-blazor-web-apps/3-exercise-create-user-interfaces-with-blazor-components

This page, yes it may have been removed

**Comment by javiercn** [comment]
@guardrex can you take a look at it?

We should get this updated to use `dotnet new blazor -ai -int Server` as that would be the closest equivalent. We'll likely also need to do updates to the docs.

/cc: @mkArtak @danroth27

**Comment by guardrex** [comment]
@javiercn ... @danroth27 manages the Blazor Learn Module coverage via Azure Training documentation authors. I only occasionally provide feedback on them and don't work on them directly.

**Comment by danroth27** [comment]
We're working on a major update to the Blazor learning path to update it to the latest .NET version and to revise the content, but it's going to take some time.

@jongalloway @CamSoper Any thoughts on how we might mitigate the current situation? The problem here is that the current Blazor learning path uses the old Blazor Server template which was removed in .NET 8.

Some options:

1. Add some text warning the learner that the template has not yet been updated to .NET 8 and they need to use an older .NET SDK version (only .NET 6 is currently still supported)
1. Try to make some minimal updates to switch the current content to use .NET 8 and the Blazor Web App template.

**Comment by CamSoper** [comment]
> 1. Add some text warning the learner that the template has not yet been updated to .NET 8 and they need to use an older .NET SDK version (only .NET 6 is currently still supported)

That's a good option. We already have boilerplate includes for "This module relies on .NET 6" and walks them through verifying they have it.

Also, I'd be remiss not to point out that this is one of those scenarios that can be avoided by pointing learners to a Codespace. As we've discussed, I'm a huge fan of shipping the environment I want my learners to use, because it's the only way I can guarantee they have the environment I intend for them to learn in (and that I've used to verify my content).

> 2. Try to make some minimal updates to switch the current content to use .NET 8 and the Blazor Web App template.

This isn't a bad option, either. If you make me a list of the changes and any required text changes, I can make them for you.

**Comment by danroth27** [comment]
> That's a good option. We already have boilerplate includes for "This module relies on .NET 6" and walks them through verifying they have it.

Ah, cool, the [current text](https://learn.microsoft.com/training/modules/interact-with-data-blazor-web-apps/3-exercise-create-user-interfaces-with-blazor-components) is already pretty clear that the tutorial uses the .NET 6 SDK, although the install link just points to the [Download .NET](https://dotnet.microsoft.com/download) page, which installs .NET 8. @CamSoper Can we point this link to https://dotnet.microsoft.com/download/dotnet/6.0 instead?

@EkiciFurkan Can you please try installing the .NET 6 SDK from https://dotnet.microsoft.com/download/dotnet/6.0 and see if that resolves your issue while we work on getting the learn module updated to .NET 8?

**Comment by CamSoper** [comment]
@danroth27 I updated the .NET 6 and 7 includes so they link directly to the correct version of the download. Should go out with the next publish.

**Comment by EkiciFurkan** [comment]
> > That's a good option. We already have boilerplate includes for "This module relies on .NET 6" and walks them through verifying they have it.
> 
> Ah, cool, the [current text](https://learn.microsoft.com/training/modules/interact-with-data-blazor-web-apps/3-exercise-create-user-interfaces-with-blazor-components) is already pretty clear that the tutorial uses the .NET 6 SDK, although the install link just points to the [Download .NET](https://dotnet.microsoft.com/download) page, which installs .NET 8. @CamSoper Can we point this link to https://dotnet.microsoft.com/download/dotnet/6.0 instead?
> 
> @EkiciFurkan Can you please try installing the .NET 6 SDK from https://dotnet.microsoft.com/download/dotnet/6.0 and see if that resolves your issue while we work on getting the learn module updated to .NET 8?

Yes .NET 6 SDK works very well in. I will be really looking forward to the training documentation for .NET 8 and new expected versions!

**Comment by CamSoper** [comment]
I'm closing this since we seem to have figured it out, @EkiciFurkan. Please feel free to let me know if you need more help!
