### ISSUE TITLE
Page calls dispose immediately after first render

### ISSUE THREAD

**Issue by rbuergi** [dotnet/aspnetcore#57681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dispose is called immediately after first render.

### Expected Behavior

I expect the page not to be disposed as long as it is displayed.

### Steps To Reproduce

The bug can be reproduced with the blazor project template: Go to Home.razor, implement IDisposable and set a breakpoint. Start in debug. The breakpoint will be hit.

### .NET Version

8

**Comment by rbuergi** [comment]
Have added a repo here: https://github.com/rbuergi/blazor-debug Set breakpoint in Home.razor and start in debug

**Comment by javiercn** [comment]
@rbuergi thanks for contacting us.

This behavior is by design.

There are two renders that happen when you prerender.
* When you first visit the page, the server prerenders it (that's the disposal you are seeing).
* When the page becomes interactive.

**Comment by rbuergi** [comment]
@javiercn thanks a lot for the hint. yes, have understood. When I have the scenario that I need to fetch data and I am displaying a spinner while it is loading, what is the best practice? Turn off prerendering? How can I distinguish in the OnParametersSet() whether I am in prerender mode or not?

**Comment by gavinltomra** [comment]
@javiercn I've just hit the same problem, and I think this is genuinely a bug, although perhaps in the project templates rather than in Blazor itself (though I wonder if the Blazor defaults are also unintuitive).

I created a new project, selected "Interactive Server" in the wizard, and it generated the `AddInteractiveServerRenderMode()` etc calls in Program.cs.  However, it did **not** set the `@rendermode` in App.razor.

The default behaviour in this case appears to be to prerender *only*: `OnInitialized` is called and then `Dispose` is called, exactly once.  The application is then not actually interactive.

After explicitly adding the missing `@rendermode="@InteractiveServer"` attributes to both `HeadOutlet` and `Routes` in App.razor, I now get `OnInitialized`+`Dispose` (for prerender), and then `OnInitialized` again (for interactive), and now my logic works as expected.

I think this is very unintuitive, and either (probably better) the default render mode should automatically be set when `AddInteractiveServerRenderMode()` is called, or at the very least the template should set these attributes.  (Or the equivalent if there's a better way.)

This is especially unintuitive for people coming from previous versions of .NET Blazor, where Blazor Server was interactive by default.

**Comment by gavinltomra** [comment]
Ok, it looks like in a later version of VS than I was initially using, an option has been added to the wizard for "Interactivity Location" -- setting this to Global does add the rendermode attributes as expected.

No idea why this isn't the default; what's the point in having a non-interactive application?
