### ISSUE TITLE
Consider Reducing Ceremony for `EventCallback` Creation

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#57726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This is inspired by this finding:
https://github.com/dotnet/aspnetcore/blob/f22b35078a992e4bff2429f517e28a30907689cb/src/Components/Web/src/Forms/EditForm.cs#L15

I am having to do the same for my own code whenever I create Razor files. It would be ideal to have this taken care of automatically so that denoted inline Razor is rendered _once and only once_ per component instantiation (like `OnInitialized` is) to reduce the amount of work to both create EventCallbacks and to reduce the associated allocations in doing so.

### Describe the solution you'd like

Currently I have to do this:

```
<EditForm OnSubmit="@_success">
</EditForm>

@code {
    EventCallback<EditContext> _success;

    protected override void OnInitialized()
    {
        _success = EventCallback.Factory.Create<EditContext>(this, Success);
        base.OnInitialized();
    }

    Task Success(EditContext parameter) => Task.CompletedTask;
}
```

Maybe something like this (note the proposed `+` but it can be another token of course):
```
<EditForm OnSubmit="@+(Success)">
</EditForm>

@code {
    Task Success(EditContext parameter) => Task.CompletedTask;
}
```
Then the `Success` delegate allocation is only created/allocated _once and only once_ no matter how many redraws occur.

### Additional context

I first created a discussion about this:
https://github.com/dotnet/aspnetcore/discussions/54771

But since there were no replies I have created an issue here to foster further communication.

Thank you for any consideration and all your efforts out there. 🙏

**Comment by javiercn** [comment]
@Mike-E-angelo thanks for contacting us.

I don't think we would introduce a special syntax for something like that. I'm also not sure that it actually helps, and that the allocation doesn't show up elsewhere. I believe it's unavoidable since EventCallback is a struct and will eventually be boxed, negating any saving that you could have using your caching strategy.

That said, I'm willing to be proven wrong, if you can provide two traces that show a meaningful difference, we might reconsider.

**Comment by Mike-E-angelo** [comment]
Hi @javiercn I would be interested in getting you these traces.  What is the best way to do this?

**Comment by javiercn** [comment]
@Mike-E-angelo file an issue through Visual Studio user voice and attach them there. Link the issue here.

That said, what we are asking is not for the traces, but for the investigation that led you to the conclusion that the approach you are using avoids allocations and reduces memory usage alltogether.

My understanding is (and it's been a while) that doing something like what you propose won't reduce the total memory usage or the allocations in general, as the allocation that's potentially saved there, would be introduced elsewhere.

I would also say that I don't think we would need a special syntax for this, if this proved to be beneficial, I don't know why the compiler couldn't do it automatically without any new syntax.

**Comment by javiercn** [comment]
@SteveSandersonMS do you remember the details about this?

**Comment by Mike-E-angelo** [comment]
Thank you @javiercn for your conversation and for pointing me in the right direction. 👍

> My understanding is (and it's been a while) that doing something like what you propose won't reduce the total memory usage or the allocations in general, as the allocation that's potentially saved there, would be introduced elsewhere.

Indeed, this exercise is also for me, as I have been thinking the opposite this entire time. 😅  Every time I put a delegate in my Razor that isn't created in `OnInitialized()` makes me wonder/cringe on the memory impact.  So it will be valuable to know if this is a legitimate concern.

I will see if I can get a good recording for you and update here when I have it.

**Comment by SteveSandersonMS** [comment]
@javiercn I think you're right based on the fact that, when a value type is used as a component parameter, it gets stored on `RenderTreeFrame.AttributeValueField` which is typed as `object`, and hence that value will get boxed during each render. This is unavoidable unless we had a special field on `RenderTreeFrame` of type `EventCallback` and hence paid the memory cost of that on every rendertree frame, even ones that don't have any event callback.

As such, creating the `EventCallback` struct on demand during rendering has no extra memory or allocation cost - for the `EventCallback` itself.

The ways it might be beneficial to cache them are:

 * The `EventCallback`'s `Delegate` instance would be preserved. It's not easy to know whether or not this gets preserved automatically as it depends on the exact syntax you use to initialize it, and this can change over time as the C# compiler gets smarter about caching method-to-delegate conversions.
 * If the `Delegate` is preserved, this will also allow `AttributeEventHandlerId` to remain constant across diffs, and hence the rendering system does less work to unregister old events and register new ones.

So ultimately I think it comes down to whether the `Delegate` is getting preserved. It's worth checking using Ilspy or similar whether, in your particular case, the simple syntax `OnSubmit="@Success"` already results in the delegate getting cached. If it does the code is already optimal (and if not, you could cache the delegate manually instead of the `EventCallback`).

**Comment by Mike-E-angelo** [comment]
Thank you very much for that valuable insight @SteveSandersonMS and all your efforts out there. 🙏  

> It's worth checking using Ilspy or similar whether, in your particular case, the simple syntax OnSubmit="@Success" already results in the delegate getting cached

You got me thinking about this and if I understand correctly, we have this exact scenario in the default template of a new Blazor Web App in the `Counter.razor` file via `IncrementCount`:

```
@page "/counter"
@rendermode InteractiveServer

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
}
```

Compiling this and reviewing the decompiled code reveals the following `BuildRenderTree`:

```
#pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Web.PageTitle>(0);
            __builder.AddAttribute(1, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddContent(2, "Counter");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\r\n\r\n");
            __builder.AddMarkupContent(4, "<h1>Counter</h1>\r\n\r\n");
            __builder.OpenElement(5, "p");
            __builder.AddAttribute(6, "role", "status");
            __builder.AddContent(7, "Current count: ");
            __builder.AddContent(8, 
#nullable restore
#line (8,34)-(8,46) "...\BlazorApp1\Components\Pages\Counter.razor"
currentCount

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\r\n\r\n");
            __builder.OpenElement(10, "button");
            __builder.AddAttribute(11, "class", "btn btn-primary");
            __builder.AddAttribute(12, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (10,43)-(10,57) "...\BlazorApp1\Components\Pages\Counter.razor"
IncrementCount

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(13, "Click me");
            __builder.CloseElement();
        }
        #pragma warning restore 1998
```

So if I understand your request (and performed it correctly), from what I can see the `IncrementCount` delegate reference is created each time, adding a new allocation each time this method calls from a `StateHasChanged` call.

Please let me know if there is something fundamentally misunderstood on my part and I will further assist to correct it.

**Comment by SteveSandersonMS** [comment]
@Mike-E-angelo You might be right but it's quite difficult to tell from the C# disassembly where it shows up as a lambda in the code. It's a lot more objective if you look at the IL disassembly because then you can see for sure if it's emitting a `newobj` instruction (or whatever it is) to produce a `Delegate` instance, without any syntax sugar to hide what's going on.

**Comment by SteveSandersonMS** [comment]
I should also clarify we've known about this since the beginning of Blazor.

We've even talked in detail with the C# team on more than one occasion about changing compilation output to improve this specific thing, and at another time there was a huge community PR we worked on for weeks to cache delegates in Blazor code, but neither of them worked out. So please don't expect there to be a simple solution!

In practice it's very rarely a real perf issue, and in those rare cases it is already possible to cache the delegates manually.

**Comment by Mike-E-angelo** [comment]
> It's a lot more objective if you look at the IL disassembly because then you can see for sure if it's emitting a newobj instruction (or whatever it is) to produce a Delegate instance, without any syntax sugar to hide what's going on

Ah yes, of course!  We're dealing with an area I don't spend a lot of time in, but familiar enough to get what you are looking for, for your review (it looks like it makes use of the `newobj` you referenced):

```
IL_00ca: nop
    IL_00cb: ldarg.1      // __builder
    IL_00cc: ldc.i4.s     12 // 0x0c
    IL_00ce: ldstr        "onclick"
    IL_00d3: ldsfld       class [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.EventCallbackFactory [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.EventCallback::Factory
    IL_00d8: ldarg.0      // this
    IL_00d9: ldarg.0      // this
    IL_00da: ldftn        instance void BlazorApp1.Components.Pages.Counter::IncrementCount()
    IL_00e0: newobj       instance void [System.Runtime]System.Action::.ctor(object, native int)
    IL_00e5: callvirt     instance valuetype [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.EventCallback`1<!!0/*class [Microsoft.AspNetCore.Components.Web]Microsoft.AspNetCore.Components.Web.MouseEventArgs*/> [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.EventCallbackFactory::Create<class [Microsoft.AspNetCore.Components.Web]Microsoft.AspNetCore.Components.Web.MouseEventArgs>(object, class [System.Runtime]System.Action)
    IL_00ea: callvirt     instance void [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder::AddAttribute<class [Microsoft.AspNetCore.Components.Web]Microsoft.AspNetCore.Components.Web.MouseEventArgs>(int32, string, valuetype [Microsoft.AspNetCore.Components]Microsoft.AspNetCore.Components.EventCallback`1<!!0/*class [Microsoft.AspNetCore.Components.Web]Microsoft.AspNetCore.Components.Web.MouseEventArgs*/>)
    IL_00ef: nop
```

> In practice it's very rarely a real perf issue, and in those rare cases it is already possible to cache the delegates manually

Thank you for the additional context and history @SteveSandersonMS I do appreciate it.  It's not _too_ surprising to hear that I am not bringing up anything new. 😁  I am glad you are aware of it.  It would of course be ideal to have an auto-baked solution around this but if it's been looked into and was not viable that is understandable.  Maybe in some future version of .NET/Blazor. :)

As it sounds like you have already tried to address this I will close this issue for now.  Thank you again for all your effort and diligence toward building something truly valuable and incredible for us developers.  🤓👍
