### ISSUE TITLE
Provision to handle Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] error

### ISSUE THREAD

**Issue by aravinda-sn** [dotnet/aspnetcore#57724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are currently unable to gracefully handle Blazor component rendering errors, such as Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]. Here is the desired behavior and challenges we face:

1. Desired Behavior: We want to log these rendering errors to Azure App Insights or Serilog without disrupting the user experience. These errors are not critical and should not stop the application from rendering components as usual.
2. Issues with ErrorBoundary: Using ErrorBoundary results in rendering an ErrorComponent once an exception occurs. This is not the desired outcome, as we want to continue rendering the original component.
3. Lack of Customization Options: Although Blazor is open source, classes like ErrorBoundaryBase and ComponentBase are not easily customizable, limiting our ability to handle errors as needed.
4. Looking for a Solution: We need a way to log errors such as Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] without altering the rendering behavior of components. Any suggestions or guidance on achieving this would be greatly appreciated.

Thank you,
Aravinda

### Expected Behavior

Be able to log error Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] and prevent this from displaying in console.

### .NET Version

8

**Comment by javiercn** [comment]
@aravinda-sn thanks for contacting us.

You can create your own base class and mimic the behavior of [`ComponentBase`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs) and perform any addition you want.

If you want all your components to use it, you can add and `@inherits` directive on an `_Imports.razor` file to apply it to all your components in a single line of code.

You can use this to guard your rendering function as well as other lifecycle methods with a `try..catch` where you can handle things however you see fit.

That said, this is a pit of failure. If you have logic that might fail but might not be critical, you should try to handle that within your component, as opposed to relying on exceptions for these situations.

I also believe you can extend `ErrorBoundaryBase` to provide your own logic for handling exceptions. See the implementation for [`ErrorBoundary`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Web/ErrorBoundary.cs)

**Comment by aravinda-sn** [comment]
Hi Javiercn,
Thank you for the helpful insights and for sharing the link to ComponentBase. While ErrorBoundaryBase can theoretically be extended, the CurrentException attribute is read-only, and the Recover method is not designed for extensibility. Access to the ErrorBoundaryBase source code would be very helpful to understand and work around these limitations.
Thanks,
Aravinda

**Comment by javiercn** [comment]
@aravinda-sn you can access the code for `ErrorBoundaryBase` [here](https://github.com/dotnet/aspnetcore/blob/4bc867dee200dffb10c9e3693b875311407bdfc6/src/Components/Components/src/ErrorBoundaryBase.cs#L11)

It doesn't matter that `CurrentException` is not writeable. You can call `Recover` to reset its value and it will be automatically populated when an exception happens.

By implementing `BuildRenderTree`, in your own component you get to decide what fragment to render, which allows you to re-render the original fragment instead of the ErrorFragment as ComponentBase does.

For everything that you describe (logging errors and re-displaying the original fragment) you can extend `ErrorBoundary` and extend `OnErrorAsync` to do your own logging, and call `Recover()` if that's what you want to do to trigger the re-render of the original fragment.

If that for some reason is not enough for you, you can override `BuildRenderTree` and provide your own logic of what to render when.

**Comment by aravinda-sn** [comment]
@javiercn, thank you!

**Comment by aravinda-sn** [comment]
@javiercn the ComponentBase.cs in the above link is not compiling with dotnet version 8.0.202. Please advise.
