### ISSUE TITLE
.NET9: Microsoft.AspNetCore.OpenApi.OpenApiSchemaService should not be internal 

### ISSUE THREAD

**Issue by jornhd** [dotnet/aspnetcore#57798]
## Background and Motivation

As Swashbuckle is no longer supported in .NET 9, we've started migrating our operation filters to operation transformers to prepare for the .NET 9 release.

In some of our current Swashbuckle filters, we need to add types to the schema that isn't described in the ApiDescription, in order to reference these types in eg. operation.Responses.

We do this today with the following line:
`var schema = context.SchemaGenerator.GenerateSchema(myType, context.SchemaRepository);`

We tried to do the same in our IOpenApiOperationTransformer implementation:
```
var componentService = context.ApplicationServices.GetRequiredKeyedService<OpenApiSchemaService>(context.DocumentName);
var schema = await componentService.GetOrCreateSchemaAsync(myType, null, true, cancellationToken);
```

The problem is that OpenApiSchemaService is internal, not public, so it's impossible to add schema for additional types.

## Proposed API

Make OpenApiSchemaService public, or provide GetOrCreateSchemaAsync in a public api, preferable the OpenApiOperationTransformerContext.

**Comment by martincostello** [comment]
> As Swashbuckle is no longer supported in .NET 9

I assume you mean _"not included in the ASP.NET Core 9 templates"_? Swashbuckle.AspNetCore itself is still supported by its maintainers (of which I'm one), and there's support for .NET 9 in progress: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3007

> it's impossible to add schema for additional types

You should be able to add additional schema components using `IOpenApiOperationTransformer` (via adding additional requests/responses) or via `IOpenApiDocumentTransformer` by adding components to the `OpenApiDocument`. You shouldn't need to have access to the internal implementation details to change the OpenAPI document like that.

**Comment by jornhd** [comment]
> You should be able to add additional schema components using IOpenApiOperationTransformer (via adding additional requests/responses)

That's exactly what I'm trying to do! The problem is how do we create the schema for a type?

One example: The API is set up to handle and return exceptions as a custom type ErrorResponse.
Instead of setting this response type with attribute on every single method, we do this today in an OperationFilter.

Migrating this filter to an IOpenApiOperationTransformer implementation, we have this code:

```csharp
public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
{
    if (operation.Responses.ContainsKey("500"))
    {
        return Task.CompletedTask;
    }
    
    // Next line is old Swashbuckle code - How can we do convert the type ErrorResponse to OpenApiSchema using IOpenApiOperationTransformer?
    // var schema = context.SchemaGenerator.GenerateSchema(typeof(ErrorResponse), context.SchemaRepository);

    var serverError = new OpenApiResponse
    {
        Description = "Server Error",
        Content =
        {
            { "application/json", new OpenApiMediaType { Schema = schema } }
        }
    };
    operation.Responses.Add("500", serverError);

    return Task.CompletedTask;
}
```
So the problem is, when we can't access the OpenApiSchemaService.GetOrCreateSchemaAsync, how are we supposed to get the schema for the custom type ErrorRespose?

**Comment by martincostello** [comment]
My understanding is that, given a type, you can use the new [`JsonSchemaExporter.GetJsonSchemaAsNode()`](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview6/libraries.md#jsonschemaexporter) method, like the service does [here](https://github.com/dotnet/aspnetcore/blob/3b4e92a6975816bf107e34b02a6d4d0cd2da5589/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs#L215) to create a schema.

```csharp
var schemaObject = JsonSchemaExporter.GetJsonSchemaAsNode(jsonSerializerOptions, typeof(ErrorResponse), jsonSchemaExporterOptions);
// Create an OpenApiSchema from the JsonNode returned above
```

That's not something I've done myself though. Rather than get into adding a schema directly, I've instead added metadata to the API endpoints to add additional produces metadata (e.g. [`ProducesProblem()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.openapiroutehandlerbuilderextensions.producesproblem)), and then the internals add it to the schema automatically.

**Comment by jornhd** [comment]
Ok, so we basically need to copy most of the service (the jsonSchemaExporterOptions is huge, and we still need to deserialize JsonNode). It would have been nice to have this in a public method like Swashbuckle has.

**Comment by captainsafia** [comment]
@jornhd Thanks for filing this issue and trying out the new APIs.

The choice to make the `OpenApiSchemaService` internal as part of this release was intentional. As mentioned in this thread, the current `OpenApiSchemaService` implementation depends on the new `JsonSchemaExporter` APIs in STJ for generating schemas. There are some OpenAPI-specific mappings in our options object that are required when targeting Open API v3.0. We're hoping to add support for OpenAPI v3.1 in the future, which will change the shape and requirements of the schema service. So the choice to not make the APIs public at the moment is to give us the flexibility to design the right API in the future.

I do have one curious question about your scenario though. Where is the `ErrorResponse` type that you're returning manifesting in your API? Are you using middleware or filters to generate the response type?

I'd +1 @martincostello's recommendation above: if you can you should use `ProducesProblem` (there are ways to only call it once) to convey to the application that it returns that type. That way, that behavior is codified in the metadata of the APIs and isn't just superficially in the OpenAPI document. It also means you don't have to author transformers/filters for each OpenAPI package to configure this behavior.

**Comment by jornhd** [comment]
> I do have one curious question about your scenario though. Where is the ErrorResponse type that you're returning manifesting in your API? Are you using middleware or filters to generate the response type?

We do this using middleware.

I've learned now that we can add the response type to all methods by adding a custom convention with `AddControllers` option action. I guess we can do something similar in MinimalApi.

@martincostello @captainsafia Thanks for your inputs. You can close this issue.

**Comment by Brads3290** [comment]
@martincostello @captainsafia I understand this issue is closed, but I don't think this answers @jornhd's question:
> when we can't access the OpenApiSchemaService.GetOrCreateSchemaAsync, how are we supposed to get the schema for the custom type ...

In their specific case the type they wanted to generate a schema for was an error response and there was a better way to do it, but what about when we do need to generate a schema for an arbitrary type?

Surely, manually copying the internal implementation of `OpenApiSchemaService` is not the answer.. - and we can't simply use `JsonSchemaExporter.GetJsonSchemaAsNode` in isolation because `GetOrCreateSchemaAsync` does other things (applying schema transformers, caching), which we would then miss out on.

**Comment by Meigs2** [comment]
> > I do have one curious question about your scenario though. Where is the ErrorResponse type that you're returning manifesting in your API? Are you using middleware or filters to generate the response type?
> 
> We do this using middleware.
> 
> I've learned now that we can add the response type to all methods by adding a custom convention with `AddControllers` option action. I guess we can do something similar in MinimalApi.
> 
> [@martincostello](https://github.com/martincostello) [@captainsafia](https://github.com/captainsafia) Thanks for your inputs. You can close this issue.

I know this is slightly old, but I wish some extra details were added here for others (like myself) needing to do this.

In my case, I have an `ApiResult<T>` helper type that wraps `IResult` results and essentially flags that an endpoint returns a standard set of responses, like ProblemDetails for 400 and 500, etc.

For those looking to see how to do something like this and get extra metadata added to controllers, this is my quick-and-dirty solution:

```csharp
public class ApiResultConvention : IApplicationModelConvention
{
    public void Apply(ApplicationModel application)
    {
        var controllers = application.Controllers;

        foreach (var controller in controllers)
        {
            foreach (var action in controller.Actions)
            {
                var resultTypeOption = IsApiResultType(action.ActionMethod.ReturnType);

                if (resultTypeOption.IsNone)
                {
                    continue;
                }

                var apiResultAttributes = new Dictionary<int, ProducesResponseTypeAttribute>()
                {
                    { StatusCodes.Status400BadRequest, new ProducesResponseTypeAttribute<ProblemDetails>(StatusCodes.Status400BadRequest) },
                    { StatusCodes.Status500InternalServerError, new ProducesResponseTypeAttribute<ProblemDetails>(StatusCodes.Status500InternalServerError) },
                    { StatusCodes.Status200OK, new ProducesResponseTypeAttribute(resultTypeOption.Value.GetGenericArguments().First(), StatusCodes.Status200OK) }
                };

                var attributesToAdd = apiResultAttributes
                    .Where(x => action.Filters
                        .OfType<ProducesResponseTypeAttribute>()
                        .All(attr => attr.StatusCode != x.Key))
                    .Select(x => x.Value)
                    .ToList();

                foreach (var attributeToAdd in attributesToAdd)
                {
                    action.Filters.Add(attributeToAdd);
                }
            }
        }
    }

    private static Option<Type> IsApiResultType(Type type)
    {
        if (type.IsGenericType)
        {
            var outerType = type.GetGenericTypeDefinition();
            if (outerType == typeof(Task<>))
            {
                return IsApiResultType(type.GetGenericArguments()[0]);
            }

            if (outerType == typeof(ApiResult<>))
            {
                return Option.Some(type);
            }
        }

        return Option.None;
    }
}
```

Then you just add it to the list of conventions when calling `AddControllers`:

```csharp
builder.Services.AddControllers(options =>
{
    options.Conventions.Add(new ApiResultConvention());
});
```

Hope this saves someone some time until we get to generate schemas using the OpenApi package.

**Comment by captainsafia** [comment]
@Meigs2 Thanks for sharing your workaround! I like the use of `IApplicationModelConvention` here. Since it's a more low-level abstraction you'll get a more consistent representation of the type across all OpenAPI generators.

As far as long-term thoughts on on-demand schema generation, the adoption of the new Microsoft.OpenAPI package and official support for true JSON schema in Microsoft.OpenAPI means that we can move to more consistent representations of schemes between what is produced by STJ and what the `OpenApiSchema` supports.

That hopefully moves us to a future where there is a smaller delta between what OpenApiSchemaService and STJ do and helps us land an API for this in .NET 10.
