### ISSUE TITLE
Q: Is WebAuthn planned to be implemented by aspnet.identity?

### ISSUE THREAD

**Issue by Guymestef** [dotnet/aspnetcore#5780]
Hello,

The API should be available in Chrome and Firefox May release.
Starting to look at it and be ready for it could be a good idea?

[webauthn specs](https://www.w3.org/TR/webauthn/)

(Question initially posted on [aspnet/Security here](https://github.com/aspnet/Security/issues/1725#issuecomment-380487325))

**Comment by mguinness** [comment]
The World Wide Web Consortium (W3C) [announced](https://www.w3.org/2019/03/pressrelease-webauthn-rec.html) today that the Web Authentication API (WebAuthn) is now an official web standard.  Are there any plans to integrate this into ASP.NET Identity Core?

**Comment by BuairtRi** [comment]
I’d like to add my voice to this as well, now that the standard is approved.

**Comment by StillLearnin** [comment]
Same question here.  We're coding our own handling of this since it isn't already implemented, but it would be great to see it supported by aspnet.identity out of the box.

**Comment by DerHulk** [comment]
It would be nice to have nativ support from ms for webauth. I think this will also help to get more people interesset in this.

**Comment by 6Hat** [comment]
Yes Please! Think about it... Passwordless Authentication is much more secure, not to mention a kick butt layer that provides a nice feel and flow with things like biometric authentication for web apps. The increased security alone should put this at the top of the list!

**Comment by wsy** [comment]
It's almost 5 years since this issue been raised.
FIDO2 is now getting more and more popular.
So, I think it's time we move this issue out of Backlog milestone.

Some 'beoming-popular' evidence:
- [Microsoft, Apple and Google is all pushing FIDO2.](https://www.apple.com/newsroom/2022/05/apple-google-and-microsoft-commit-to-expanded-support-for-fido-standard/)
- [Apple supports FIDO2 since iOS 16 / iPadOS 16.](https://www.apple.com/ios/ios-16/)
- [Android supported FIDO2 since 2019.](https://fidoalliance.org/news-your-google-android-7-phone-is-now-a-fido2-security-key/)
- [Microsoft Account now supports FIDO2](https://support.microsoft.com/en-us/windows/sign-in-to-your-microsoft-account-with-windows-hello-or-a-security-key-800a8c01-6b61-49f5-0660-c2159bea4d84)
- Among all these major websites, GitHub's user experience is the best one. It supports Windows Hello with Edge browser and it supports iCloud Key Chain with Safari on iOS16 / iPadOS16. On all major OSes, GitHub has amazing FIDO2 login experience.

**Comment by codemonkey85** [comment]
I really think this library by @KristofferStrube is worth a look: [https://github.com/KristofferStrube/Blazor.WebAuthentication](https://github.com/KristofferStrube/Blazor.WebAuthentication)

**Comment by mguinness** [comment]
There's also a good example written by Damien Bod (well known in application security circles) at [ASP.NET Core Identity with FIDO2 WebAuthn, MFA and Passwordless](https://github.com/damienbod/AspNetCoreIdentityFido2Mfa) that uses the [Passwordless - FIDO2 for .NET](https://fido2-net-lib.passwordless.dev/) library developed by Anders Åberg.

**Comment by mikekistler** [comment]
I think this will be covered by #53467.
