### ISSUE TITLE
JsonOptions Microsoft.AspNetCore.OpenApi formatting

### ISSUE THREAD

**Issue by JTeeuwissen** [dotnet/aspnetcore#57891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to migrate from NSwag to m.a.OpenApi. NSwag used the configuration via `AddJsonOptions`/`AddNewtonsoftJson` to modify the resulting openapi specification. Using `AddJsonOptions` in combination with `MapOpenApi`/`AddOpenApi` does not seem to affect the specification.

For example:
services
```cs
services.AddRouting();
services
    .AddControllers()
    .AddJsonOptions(options =>
    {
      options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
    });

services.AddOpenApi();
```

controllers
```cs
[ApiController]
[Route("api/v1/[controller]")]
public class ExampleController : ControllerBase
{
  [HttpGet("{id}")]
  public ExampleResult Get(int id)
  {
    return new ExampleResult { ExampleId = id };
  }
}

public class ExampleResult
{
  public int ExampleId { get; set; }
}
```

results in
```json
{
      "openapi": "3.0.1",
      "info": {
        "title": "Example | v1",
        "version": "1.0.0"
      },
      "paths": {
        "/api/v1/Example/{id}": {
          "get": {
            "tags": [
              "Example"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "OK",
                "content": {
                  "text/plain": {
                    "schema": {
                      "$ref": "#/components/schemas/ExampleResult"
                    }
                  },
                  "application/json": {
                    "schema": {
                      "$ref": "#/components/schemas/ExampleResult"
                    }
                  },
                  "text/json": {
                    "schema": {
                      "$ref": "#/components/schemas/ExampleResult"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {
          "ExampleResult": {
            "type": "object",
            "properties": {
              "exampleId": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        }
      },
      "tags": [
        {
          "name": "Example"
        }
      ]
    }
```

while `exampleId` should be `example_id`

### Describe the solution you'd like

I'd like m.a.OpenApi to automatically pick up on json configurations, to have the openapi spec match the expected json.

**Comment by martincostello** [comment]
Looks like the OpenAPI schema service resolves the JSON options from the HTTP version of `JsonOptions`:

https://github.com/dotnet/aspnetcore/blob/b6b29ca3c2cdc316e8eb20cb4077ea81f21340c4/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs#L30

I don't think it would be able to depend on the other version for controllers as it would otherwise need to take a dependency on MVC.

I think you'll need to configure the HTTP JSON options with [`ConfigureHttpJsonOptions()`](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.httpjsonserviceextensions.configurehttpjsonoptions) to match the configuration you use for your controllers:

```csharp
services.ConfigureHttpJsonOptions((options)
{
    options.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
    // other settings to make them functionally match
});
```

**Comment by JTeeuwissen** [comment]
That indeed does seem to do the trick. Would it be possible to create a separate package (e.g. `Microsoft.AspNetCore.OpenApi.Mvc`) to avoid having to rely on configuring two separate json options. Two options (not to speak of newtonsoft) would make it easy to have subtle differences between the api and its spec.

**Comment by captainsafia** [comment]
@JTeeuwissen Thanks for filing this issue! This is a good one to cover in our docs write-ups as well.

> I don't think it would be able to depend on the other version for controllers as it would otherwise need to take a dependency on MVC.

I think the best pattern here would probably be to require something like this:

```csharp
builder.Services.ConfigureHttpJsonOptions((options) => ConfigureJsonSerializerOptions(options.SerializerOptions));
builder.Services.AddControllers().AddJsonOptions((options) => ConfigureJsonSerializerOptions(options.SerializerOptions))

// In some helper library
void ConfigureJsonSerializerOptions(JsonSerializerOptions jsonSerializerOptions) { }
```

That should keep things a bit more DRY with regards to where the configuration with the JSON options happens.

IMO, creating a new package is bit of a heavy solution for this. The current stance is that the `Microsoft.AspNetCore.Http.JsonOptions` object is the defacto one that we'll extend upon in other implementations (e.g. `ProblemDetailsWriter`, `DeveloperExceptionPage`, `JwtBearerToken` config) since it lives lower in the stack compared to the older `JsonOptions` type in MVC.

> not to speak of newtonsoft

With regard to usage of Newtonsoft.Json, I doubt that we'll ever be able to land on a particularly clean solution here. The core logic for generating schemas in our implementation takes a dependency on System.Text.Json's `JsonSchemaExporter` APIs which map to STJ's binding behavior. You could get the desired result if you constructed an STJ JsonSerializerOptions object that matched the semantics of Newtonsoft.Json's configuration but it's still STJ determine how the schemas get generated (which might have subtle differences with Newtonsoft.Json's binding rules).
