### ISSUE TITLE
Server-side Blazor Disable IUserIdProvider ？

### ISSUE THREAD

**Issue by 17723010593** [dotnet/aspnetcore#58112]
I enabled Server-side Blazor on my aspnetcore Server,
I injected `GameRoleIdProvider`

`builder.Services.AddSingleton<IUserIdProvider, GameRoleIdProvider>();`   However, blazor also calls `GameRoleIdProvider`, there is no way to disable blazor from calling `GameRoleIdProvider`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Blazor Server resolves that service because it utilizes SignalR internally. That said, it's not going to interfere with Blazor as it's only calling the `GetUserId` method.
That said, we'll let the SignalR team know about this as a feature request to allow registering independent IUserIdProvider instances in the future.

Having said this, can you also share more about why this is a problem for you?
