### ISSUE TITLE
blazor.server.js SyntaxError: Unexpected token '{' in  Safari Version 16.3. with a Mac Studio using Ventura 13.2

### ISSUE THREAD

**Issue by julianadormon** [dotnet/aspnetcore#58212]
### URL(s)

https://jbordeauxphotography.proofpix.com/roseville-high-2024/

### Description

Long story short, I went into production with .net9 RC1 after much testing (I know, I know).

I then started getting complaints from a few Safari users that their websites were not loading all the content. Upon reviewing their site on their system, there was no WebSocket connection being opened. We run blazor server for them.

The console reports: blazor.server.js SyntaxError: Unexpected token '{' 

They were not having any problems until I upgraded from .net 8.

I have no problems on Safari running on MacOS Version 14(sonoma) or 15(sequioa).

Something about the javascript engine in the older version of Safari does not like what's going on now, methinks.

<img width="800" alt="screenshot-2024-10-02-at-94643_1n8ute9" src="https://github.com/user-attachments/assets/f2ae2f49-8673-479a-8f9b-56e12e9e787f">

I hope this is helpful. Thanks for all you do!

**Comment by danroth27** [comment]
@julianadormon Thank you for testing with .NET 9 RC1! We want to make sure upgrading to .NET 9 is easy and seamless, so this sort of early feedback is super valuable.

> The console reports: blazor.server.js SyntaxError: Unexpected token '{'

Can you please verify that the blazor.server.js file is being correctly downloaded on these devices?

> I have no problems on Safari running on MacOS Version 14(sonoma) or 15(sequioa).

For what versions of Safari seem to have the issue?

**Comment by julianadormon** [comment]
Hi Dan! Thank you.
Safari Version 16.3. with a Mac Studio using Ventura 13.2 for sure and also Safari: Version 16.1 (18614.2.9.1.12)
Mac: 13.0 (22A380). Two different customers.

The same site works fine in newer versions, so I have to assume the file is downloading. But if you really need me to check, I will ask the client to fire up their console again.

**Comment by julianadormon** [comment]
FYI: 
I'm simply using:  <script src="/_framework/blazor.server.js"></script>

**Comment by MackinnonBuck** [comment]
@julianadormon, it would be great if we could get a line number that the error is happening on.

Would it be possible for you to deploy a version of the site using an unminified version of `blazor.server.js` and have the customer screenshot the error message again, including the line number? Per our [official support policy](https://learn.microsoft.com/aspnet/core/blazor/supported-platforms), we only support the latest version of each browser.

Also, could you please have the customer click on the error message and view the `blazor.server.js` file itself? Maybe invalid JS is being returned by the server.

**Comment by dany28** [comment]
I have diagnosed problem, there is code in `blazor.web.js` like this:
```JS
class A {
   static {
        this.B = "Ok";
   }     
}
```
wchich is not working od old devices (i.e. IOS 16)

replace with
```JS
class A {
    static B = "Ok";
}
```

start working great, right now I'm using fixed copy of `blazor.web.js` on my project and it's working great

**Comment by julianadormon** [comment]
@dany28 Thank you! Is this something I can fix because I cannot seem to find /src/Components/Web.JS/tsconfig.json 
Any chance you can provide a link to your JS file? Thanks again :)

**Comment by dany28** [comment]
> @dany28 Thank you! Is this something I can fix because I cannot seem to find /src/Components/Web.JS/tsconfig.json Any chance you can provide a link to your JS file? Thanks again :)
> 
> Actually I am using blazor.server.js not blazor.web.js

I don't have fixed version od blazor.server.js, You can do it by yourself
1. in browser developer mode find blazor.server.js, copy content
2. create file blazorfixed.server.js in your application folder `wwwroot` favorite editor (i.e. VS Code), paste content
3. find all places with `static {...}` code, replace it to code like `static variableName = variableValue`;
4. replace in `App.razor`  code `<script src="_framework/blazor.server.js"></script>` to `<script src="blazorfixed.server.js"></script>`

**Comment by julianadormon** [comment]
Thank you @dany28

**Comment by julianadormon** [comment]
@MackinnonBuck do you still require more information from me or is the above enough to go on, thanks?

**Comment by MackinnonBuck** [comment]
Thanks for figuring this out, @julianadormon!

Per our [official support policy](https://learn.microsoft.com/aspnet/core/blazor/supported-platforms), only the latest version of each browser is supported. We do consider high-impact scenarios on a case-by-case basis, but since the latest version of Safari is supported on macOS Ventura, we would suggest that customers update to the latest browser version. If you need to build a version of `blazor.server.js` that works on older browsers, you're free to do so (see @dany28's suggestion).

**Comment by dany28** [comment]
Right now 99% of Blazor developers have two choices:
1. Don't go with Blazor NET 9.0, stay with 8.0
2. Produce own JS scripts

and that's only because the creator of Blazor decided to change the default behavior of the `useDefineForClassFields` flag for ES2022 in `tsconfig.json` (default value is `true` but in Blazor project configuration is manually set to false)

**Comment by julianadormon** [comment]
@MackinnonBuck All the credit goes to @dany28. I will try modifying the js files. Thanks.

**Comment by LuohuaRain** [comment]
@julianadormon Hi, after modifying these JS files (blazor.web.js), does every blazor function run normally?

**Comment by Theoistic** [comment]
got the same, a simple blazor website breaks on iPhone 7 (iOS 15.8) because Unexpected token '{' in blazor.web.js ..

_I can't come to terms with iPhone 7 already being too old for a website._

**Comment by Ed156** [comment]
This now makes Maui Hybrid apps with net9 not working anymore below iOS 17 ...

**Comment by giovanni-a** [comment]
Hi. I’m using an iPhone 12 Mini with iOS 16. Blazor websites built with .NET 9 don’t load in any browser, and there’s no fallback to a compatibility mode. I believe this is a serious issue that needs to be addressed.

**Comment by DanielJMHoffman** [comment]
Just to emphasise the need for support on older iOS devices: Our Blazor web app is mostly used by airlines across Africa, and our one client has older iPads across their entire fleet of aircraft, which allows max. iOS 15. Unfortunately we cannot ask them to get new iPads across the company - however @dany28 's suggestion, to create our own blazorfixed.web.js has worked for us. We really appreciate the work by the Blazor Team - the .NET 9 updates are amazing!!

**Comment by e0548965** [comment]
Any news about this? Encountering the same issue.

**Comment by MikhailKrasnobaev** [comment]
Good day, can confirm the issue on .NET 9 on iPhone 7 (iOS 15.8).
Solved by manually editing  blazor.web.js and disabling SIMD.

**Comment by LuohuaRain** [comment]
@MikhailKrasnobaev why and how to disable SIMD?

**Comment by MikhailKrasnobaev** [comment]
> [@MikhailKrasnobaev](https://github.com/MikhailKrasnobaev) why and how to disable SIMD?

SIMD also doesn't work on iPhone 7 (iOS 15.8), so it needs to be disable, more info https://github.com/LostBeard/BlazorWASMSIMDDetectExample?tab=readme-ov-file

**Comment by drma-tech** [comment]
How do I detect that the browser does not support running this version of Blazor? I have tested several things, but it always validates as supported and still gives this error.

**Comment by drma-tech** [comment]
I generated this script (with the help of AI), and it appears to be working.
Note: I don't want to change Blazor to make it worse. I prefer the user to update the browser.

```
<script>
    const isModernBrowser = (() => {
        try {
            // Test basic required APIs
            if (typeof WebAssembly !== "object") return false;
            if (typeof WebAssembly.instantiate !== "function") return false;
            if (typeof BigInt !== "function") return false;
            if (typeof fetch !== "function") return false;
            if (typeof Promise !== "function") return false;

            // Safely test modern syntax using Function (optional chaining / nullish coalescing)
            new Function("const obj = { foo: null }; const x = obj && obj.foo !== undefined ? obj.foo : 'ok';");

            return true;
        } catch (e) {
            console.error("Browser not supported:", e);
            return false;
        }
    })();

    if (!isModernBrowser) {
        showBrowserWarning();
    }

    window.addEventListener('error', function (e) {
        if (e.filename && e.filename.includes('blazor.webassembly.js')) {
            showBrowserWarning();
        }
    });

    function showBrowserWarning() {
        document.body.innerHTML = `
            <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;text-align:center;padding:20px;font-family:sans-serif;">
                <h1>Unsupported Browser</h1>
                <p>Your browser is too old to run this application.</p>
                <p>Use the latest version of your browser (Chrome, Edge, Firefox, Safari, etc).</p>
            </div>
        `;
    }
</script>
```

**Comment by khalil2099** [comment]
my app is blazor .net 9.0.3 and it looks like i only need to change this code in blazor.webassembly.js:

`static {
            this.nextEventDelegatorId = 0
        }`

to

`static nextEventDelegatorId = 0;`

dont need to change anything else. tested on iphone 7 (ios 15.8.4) safari.

so everytime i publish my app, i will need to replace this file again.

**Comment by giovanni-a** [comment]
As the maintainers of the OpenSilver framework, we are currently unable to upgrade beyond .NET 8 for many of our applications—including our new [OpenSilverShowcase.com](https://OpenSilverShowcase.com) app—because of this issue.

It’s difficult to justify deploying a web application that cannot support a Safari browser that is only two years old.

Resolving this would have a significant positive impact, not just for us, but for the wider community relying on OpenSilver.

We would greatly appreciate any update or prioritization on this issue.

**Comment by drma-tech** [comment]
@giovanni-a  
hard to justify? browser, softwares or OS with two years without update, this user should not even be accessing the internet. you are doing them a favor. you have to force everyone to stay updated. I don't feel any weight on my conscience about this.

**Comment by giovanni-a** [comment]
Thanks for your input, @drma-tech. I understand the reasoning behind encouraging users to stay updated, but in practice, the situation is not so simple. On Apple devices, browser versions are tied to OS versions, which are in turn tied to hardware. For example, Blazor WebAssembly sites don’t show up at all on iOS 16.3 or macOS Monterey. Many older MacBook Pros, as well as iPhones 6s, 7, 8, and X are still running perfectly well—I personally know people who use and are happy with these devices.

Regardless of individual motivations, current [stats](https://iosref.com/ios-usage) show that as many as 7% of iOS users are still on iOS 16 or below. Given over a billion active iPhone users, this translates to tens of millions of people. Realistically, these users aren’t going to buy new hardware just because our site won’t load. So it’s not really “doing them a favor”—we’re more likely just shooting ourselves in the foot by excluding them.

While it’s theoretically possible to patch that one line in WebAssembly.js with each deployment, it’s not practical for most teams, and it makes more sense to just stick with .NET 8. My bigger concern is for the broader OpenSilver and Blazor WebAssembly community. We’ve worked hard for years to promote .NET as a great platform for web development, competing with frameworks like React and Angular. We want .NET to succeed—that’s what we work on every day.

It’s understandable if an advanced feature doesn’t work on an older device, like the latest CSS effects. But here, we’re talking about a basic “Hello World” site that doesn’t load at all: the entire website is just blank, with no errors or explanation. Previous comments suggest it’s just a single line that needs changing. It’s not reasonable to expect every developer to manually patch this for every release. A change this minor in the official distribution could make .NET sites accessible to tens of millions more users.

**Could we please reconsider making this small but important fix to WebAssembly.js in the official distribution? It would have a huge positive impact on the entire .NET web community.**

**Comment by drma-tech** [comment]
You have two options:

1 - Accept losing part of your audience. From the moment we decided to work with Blazor, we already knew that we wouldn't be able to reach 100% of our potential audience. Even if Microsoft fixes this problem, there will still be users who won't be able to run WebAssembly at all.

2 - You can create two versions of your site and redirect the user to the Net 8 version if the browser is too old. This is the script I currently use to alert the user. You can use the same one to redirect.

```
<script src="https://unpkg.com/wasm-feature-detect/dist/umd/index.js"></script>
<script type="text/javascript">
    // check is browser is compatible with blazor
    detectBrowserFeatures()
        .then((ok) => {
            if (!ok) {
                showBrowserWarning();
            }
        })
        .catch((error) => {
            showError(`Browser not supported: ${error.message}`);
        });
</script>
```
```
async function detectBrowserFeatures() {
    const [simd, bulkMemory, bigInt] = await Promise.all([
        wasmFeatureDetect.simd(),
        wasmFeatureDetect.bulkMemory(),
        wasmFeatureDetect.bigInt()
    ]);

    if (!simd || !bulkMemory || !bigInt) {
        showBrowserWarning();
        return false;
    }

    return true;
}

function showBrowserWarning() {
    document.body.innerHTML = `
        <div style="display: flex; align-items: center; justify-content: center; min-height: 100vh; background: #f0f2f5; font-family: 'Segoe UI', Roboto, sans-serif; padding: 1rem;">
            <div style="background: #fff; padding: 0.6rem; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); max-width: 460px; text-align: center; color: #333;">
                <div style="font-size: 2rem; margin-bottom: 0.5rem;">⚠️</div>
                <h2 style="font-size: 1.5rem; margin-bottom: 0.5rem;">Your browser needs an update</h2>
                <p style="font-size: 1rem; line-height: 1.6; margin-bottom: 0.5rem; text-align: justify;">
                    This app uses modern browser features. Your current browser version isn’t compatible. Even when installed from a store, this app runs inside your device’s built-in browser.
                </p>
                <ul style="list-style: none; padding: 0; margin: 0; font-size: 0.95rem; color: #555; text-align: left; padding-top: 0.5rem;">
                    <li style="margin: 0.5rem 0; text-align: center;">
                        <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/googleplay.svg" alt="Play Store" width="20" style="margin-right: 4px;" />
                        <strong>Android</strong>: uses <strong>Chrome</strong>
                    </li>
                    <li style="margin: 0.5rem 0; text-align: center;">
                        <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apple.svg" alt="App Store" width="20" style="margin-right: 4px;" />
                        <strong>iOS/macOS</strong>: uses <strong>Safari</strong>
                    </li>
                    <li style="margin: 0.5rem 0; text-align: center;">
                        <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/microsoftstore.svg" alt="Microsoft Store" width="20" style="margin-right: 4px;" />
                        <strong>Windows</strong>: uses <strong>Edge</strong>
                    </li>
                </ul>
            </div>
        </div>
    `;
}
```

![Image](https://github.com/user-attachments/assets/fafccfaf-228a-4c90-a01b-733e2f750dee)

**Comment by gerneio** [comment]
For those of you like me who don't like doing one-off code static asset changes and storing on disk, here's another approach for how to make this change dynamically at runtime. Note that depending on your application architecture and deployment target, your results may vary.

## MAUI Blazor Hybrid

My main use case was for using Blazor Hybrid within a MAUI mobile app. The below solution worked for iOS, Android, and Windows (tested under .NET 9):

#### Create a Custom `BlazorWebView` and override/provide a custom `IFileProvider`
```csharp
class CustomBlazorWebView : BlazorWebView
{
    public override IFileProvider CreateFileProvider(string contentRootDir)
    {
        var p = base.CreateFileProvider(contentRootDir);

        return new WrappedFileProvider(p);
    }

    class WrappedFileProvider(IFileProvider defaultProvider) : IFileProvider
    {
        private static readonly ManifestEmbeddedFileProvider _manifestProvider = new(typeof(WebViewManager).Assembly);

        public IDirectoryContents GetDirectoryContents(string subpath) => defaultProvider.GetDirectoryContents(subpath);

        public IChangeToken Watch(string filter) => defaultProvider.Watch(filter);

        public IFileInfo GetFileInfo(string subpath)
        {
            if ("blazor.webview.custom.js".Equals(subpath, StringComparison.OrdinalIgnoreCase))
            {
                var fi = _manifestProvider.GetFileInfo("_framework/blazor.webview.js");

                static string ModifyFileContent(IFileInfo f, string contents)
                {
                    return contents.Replace("static{this.nextEventDelegatorId=0}", "static nextEventDelegatorId=0;");
                }

                return new ModifiedFileInfo(fi, ModifyFileContent);
            }
            else
                return defaultProvider.GetFileInfo(subpath);
        }

        // See: Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo
        class ModifiedFileInfo(IFileInfo f, Func<IFileInfo, string, string> modifyContentsFn) : IFileInfo
        {
            public bool Exists => f.Exists;

            private long? _length;
            public long Length => EnsureLength();

            public string PhysicalPath => f.PhysicalPath;

            public string Name => f.Name;

            public DateTimeOffset LastModified => f.LastModified;

            public bool IsDirectory => f.IsDirectory;

            private long EnsureLength()
            {
                if (_length is null)
                {
                    using var stream = GetModifiedStream();
                    _length = stream.Length;
                }

                return _length.Value;
            }

            public Stream CreateReadStream()
            {
                var stream = GetModifiedStream();

                if (!_length.HasValue)
                    _length = stream.Length;

                return stream;
            }

            private string? _content;

            public Stream GetModifiedStream()
            {
                if (_content is null)
                {
                    using var strm = f.CreateReadStream();

                    using var reader = new StreamReader(strm);

                    _content = modifyContentsFn(f, reader.ReadToEnd());
                }

                return new MemoryStream(System.Text.Encoding.Default.GetBytes(_content));
            }
        }
    }
}
```

Then make sure to update XAML markup to point to your `CustomBlazorWebView`:
#### MainPage.xaml
```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:BlazorWebViewDemo"
             x:Class="BlazorWebViewDemo.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">
    <CustomBlazorWebView HostPage="wwwroot/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </CustomBlazorWebView>
</ContentPage>
```

And finally update your `index.html` to point to the new dynamic resource:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    ...
</head>
<body>
    ....
    <script src="blazor.webview.custom.js" autostart="false" defer></script>
    ...
</body>
</html>
```

Note that it's feasible for you to just hotswap replace the contents of the current `_framework/blazor.webview.js`, but I prefer to make it a specific opt-in so that downstream consumers understand the risk (if any).

Credit [here](https://github.com/dotnet/maui/blob/c4fc50730d512e3dc4b7e0756bb575f8602bebb4/src/BlazorWebView/samples/BlazorWinFormsApp/CustomFilesBlazorWebView.cs#L15) for showing how to hook up a custom file provider for the `BlazorWebView`. After that it was just a matter of tracing the source code until I found how to resolve the current content of the `blazor.webview.js` file, which ultimately turns out to be stored as an embedded Assembly manifest resource (see `Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider`)

## ASP.NET Core Hosted - WASM

For this scenario, this is mostly untested, however I had do something similar for a completely different use case (under .NET 8), but with the same goal of changing the contents of the default blazor loader script at runtime. The below example was specific for an ASP.NET Core hosted WASM solution, but I have a feeling it can easily be adapted to work with Blazor server (or other render-modes).

#### Program.cs
```C#
app.MapGet("/blazor.webassembly.custom.js", (IWebHostEnvironment hostingEnv) =>
{
    var f = hostingEnv.WebRootFileProvider.GetFileInfo("/_framework/blazor.webassembly.js");
    using var strm = f.CreateReadStream();
    using var reader = new StreamReader(strm);

    var contents = reader.ReadToEnd();
    contents = contents.Replace("static{this.nextEventDelegatorId=0}", "static nextEventDelegatorId=0;");

    return Results.Content(contents, "text/javascript");
});
```

Afterwards, just make sure to update your `index.html` to point to the new dynamic resource (same as above).

---

Kind of annoying that we had to go this far to address a one-liner fix, especially since it seems like after that one fix the Blazor app seems to work as intended. This seems to be one of the continuous pain points that keeps developers/teams from upgrading their apps to the latest .NET, since not much thought (or concern) is given for backwards compatibility. I get the idea of just saying "client devices need to just update to latest supported OS", but when you're dealing with a massive fleet of devices where you don't control/manage those devices in anyway, and your goal is to make your app as accessible as possible to all users, sometimes you got to pivot and make these kinds of adjustments. If it wasn't for the fact that pushing a new update to the various mobile app stores typically requires that you target their latest SDK, and therefore translates to us needing to then upgrade and use the latest .NET, I would have happily kept our app on the older frameworks in order to keep device compatibility for our end users, but alas, that was not an option here (when targeting .NET MAUI specifically that is)...

**Comment by gerneio** [comment]
Adding additional notes to my last reply regarding working with the new Blazor Web render-modes (i.e. using `blazor.web.js`).

Looks like what I did previously for my WASM project doesn't quite work in .NET 9 since all Blazor framework resources are embedded within the Assembly (similar to the MAUI project). Doesn't change a whole lot since we just swap out the `WebRootFileProvider` with the `ManifestEmbeddedFileProvider`, so no biggy there really.

However the bigger pain point is that `nextEventDelegatorId` is not the only static reference that needs updated now. There are **several** `static { this...` instances that now need to be replaced. The `static { this.Css...` one in particular was a pain since it contains embedded ending curly braces, making it a little more difficult to replace with Regex. However, I came up with the below solution that seems to work well enough:

```csharp
app.MapGet("/blazor.web.custom.js", () =>
{
    var manifestProvider = new(typeof(RazorComponentsEndpointRouteBuilderExtensions).Assembly);
    var f = manifestProvider.GetFileInfo("/_framework/blazor.web.js");

    if (!f.Exists) return Results.NotFound();

    using var strm = f.CreateReadStream();
    using var reader = new StreamReader(strm);

    var contents = reader.ReadToEnd();

    // Special cases where contents might contain an ending curly brace (i.e. `Hello ${name}`)
    contents = Regex.Replace(contents, @"static{this\.(\w+=`.*?`)}", @"static $1;");
    contents = Regex.Replace(contents, @"static{this\.(.*?)}", @"static $1;");

    // TODO: cache modified contents?

    return Results.Content(contents, "text/javascript");
});
```

Of course I wouldn't consider this bulletproof, as it would be quite easy for a change to happen to the underlying file that would break this Regex pattern, but at least we can say for a given .NET version (or `Microsoft.AspNetCore.Components.*` package rather), we can be sure that the script adjustments will continue to work. We'd just need to revalidate once updating to the latest package. My test was against .NET 9.0.7 btw.

I would imagine that a more elegant solution would be to pass the current script through some sort of JS transpiler and request that it transforms the script with older browser support in mind, but I didn't feel the need to take this extra step since the source script is static (again, given a certain package version).

Hope this helps someone else...

**Comment by jacob-l** [comment]
@gerneio Thanks for sharing your approach.

I agree that transpiling JS files is the most robust and “correct” solution, and doing it at build time makes sense. If Node.js is available on the build machine, it’s pretty straightforward.

I also looked into cross-platform transpilation with .NET. The best I managed so far is something like this: https://github.com/jacob-l/Babel.Net. Maybe this could be useful in some way.

It works (although I’ve only tested it on Windows so far).

Performance isn’t great, so it might make sense to cache the results and transpile only once per file.

P.S. I’m not sure that the ‘Replace("static{this.nextEventDelegatorId=0}", "static nextEventDelegatorId=0;")’ approach produces exactly the same code. Is the output really equivalent?
With the replace approach, I’d expect something like this:
Replace(
  "class T{static{this.nextEventDelegatorId=0}constructor(e){this.browserRendererId=e,this.afterClickCallbacks=[];const t=++T.nextEventDelegatorId;",
  "var nextEventDelegatorId=0;class T{constructor(e){this.browserRendererId=e,this.afterClickCallbacks=[];const t=++nextEventDelegatorId;"
)

**Comment by gerneio** [comment]
@jacob-l 

I also agree that doing this at build time and using a transpiler is the ultimate solution to guarantee near 100% correctness and browser compatibility.

As for my replace logic, I can confirm that it does work as intended. Your last example actually ends up putting the static class property outside the class itself, which I would suspect would break some of the code. 

So to make it a little more clear, the goal would be to take the following class definition:

```js
class T {
  static{this.nextEventDelegatorId=0;}
  constructor(e) { 
    // ...
  }
  // ...
}
```

and replace it with the functional equivalent of:

```js
class T {
  static nextEventDelegatorId=0;
  constructor(e) { 
    // ...
  }
  // ...
}
```

You can see that these are equivalent by evaluating [this JSFiddle](https://jsfiddle.net/uz83wkhv/).

Note that the `blazor.web.js` has some classes with multiple static properties, but whatever transpiler they are using is actually breaking them out into their own individual static blocks, which makes our replace logic relatively simple (compared to the alternative at least).

**Example:**
```js
class $o {
	static{this.ReconnectOverlayClassName = "components-reconnect-overlay";}
	static{this.ReconnectDialogClassName = "components-reconnect-dialog";}
	static{this.ReconnectVisibleClassName = "components-reconnect-visible";}
	static{this.RejoiningAnimationClassName = "components-rejoining-animation";}
	static{this.AnimationRippleCount = 2;}
	constructor(e, t, n) {
		// ...
	}
	// ...
}
```

[This MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks) describes the `Static initialization blocks` and how they can be used. Note that my replace approach only works because the Blazor framework is really only using the simple approach of setting static class properties and no other logic (as shown in the MDN doc).

**Comment by artarya** [comment]
There is such an error in old browsers.
I had exactly the same problem on the server. When I published the program on the server, I got an error, but it worked fine on my system.
Then I realized that the server browser was old, that's why I had such an error.

**Comment by arika0093** [comment]
Hello!

I've prepared a project that provides a blazor.server.js build to solve this problem. Simply install the package or load the JS file directly.
It works with .NET 9 and later.

https://github.com/arika0093/LegacyBlazorJs
