### ISSUE TITLE
Component/partial static generation

### ISSUE THREAD

**Issue by Atulin** [dotnet/aspnetcore#58384]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to create a single component/tag helper/partial/anything of the sort that would encompass all SVG icons I'd like to use. That is, instead of using

```html
<icon-menu></icon-menu>
```

I'd like to use it as

```html
<icon name="menu"></icon>
```

The component would read the appropriate file from the directory that contains icons and display it. That, however, would mean that every page load would cause as many IO reads as there are icons on the page, which is not great for many reasons. As a workaround, the file could be loaded once, and then stored in `IMemoryCache`, but I'm not a fan of this solution either.

### Describe the solution you'd like

I'd like the ability to create components/etc. that would run during **build time**. For example, a tag helper like

```cs
public sealed class IconTagHelper : StaticTagHelper
{
	public required string Name { get; set; }

	public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
	{
		var file = await File.ReadAllTextAsync(Path.Join("icons", $"{Name}.svg"));
		output.TagName = "i";
		output.Content.SetHtmlContent(file);
	}
}
```

that when used

```html
@page "product/{id}"
<h1><icon name="info"></icon> Learn more</h1>
```

would run **once** on build time, and during runtime would be equivalent to

```html
@page "product/{id}"
<h1><i><svg>...</svg></i> Learn more</h1>
```

so, ideally, it would be converted to a `WriteLiteral("<i><svg>...</svg></i>");` in the final compilation.

**Comment by javiercn** [comment]
@Atulin thanks for contacting us.

This is not something that we are planning to do. What you seem to be asking is running components at compile time rather than at build time, and that would require running the application inside the compiler to run the code and resolve icons.

We already support statically rendering components, but I don't think that's what you are looking for.

What you seem to be describing is some sort of macro that transforms your input into a specific output at compile time, which is something we don't have plans for.
