### ISSUE TITLE
[Blazor] Behavioral breaking change in .NET 8.0 component re-rendering

### ISSUE THREAD

**Issue by S-Luiten** [dotnet/aspnetcore#58417]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After updating a blazor server project from .NET 7.0 to .NET 8.0, I noticed that components no longer re-render when needed.
The issue appears to be related to having global state passed through a cascading parameter, where the component/page containing the cascading value component is not involved with a state change, and `StateHasChanged` is not invoked directly on the component that needs to be re-rendered.

### Steps To Reproduce

https://github.com/S-Luiten/TestBlazorRerenderIssue

The project has .NET 7.0 and .NET 8.0 target frameworks. The issue can only be reproduced when the target framework is .NET 8.0. Additionally, there is a second page (Home2.razor, `/2`) where this issue is not present on both .NET 7.0 and .NET 8.0 (so this page shows the expected behavior). The only different between Home.razor and Home2.razor is that Home2.razor handles both the event callback / statehaschanged and the cascading value, whereas Home.razor only has the cascading value, and leaves the rest to a child component.

On .NET 7.0, after clicking the 'Refresh page' button, an async task is simulated, and one second later the page shows the new data:
Before:
![Image](https://github.com/user-attachments/assets/d51ec32d-cea5-4f17-8572-9f4b56183475)
After:
![Image](https://github.com/user-attachments/assets/7f27c009-2659-4417-893d-fed4a60e79d7)

On .NET 8.0, only the listener child component is updated, the invoker child component and the listener's sub-child components do not update:
![Image](https://github.com/user-attachments/assets/701cc03e-bab6-4e5c-891c-dd2125e2b6f0)

Note that on Home2.razor, the page rerenders immediately after clicking the button (which is why the value is incremented after the simulated task, so you can see the second time it rerenders):
![Image](https://github.com/user-attachments/assets/e69b09c3-616d-4e52-852b-781d2976d206)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @S-Luiten, and thanks for providing a repro.

It looks like the behavioral change was intentionally introduced here: https://github.com/dotnet/aspnetcore/pull/42901.

**Here's what's going on:**

If Blazor knows for sure that no parameters have changed, a component won't re-render, _even if its parent does_.

Over time, the parameter change detection logic has become more accurate, and the PR linked above added support for enums. Because the `EventListenerGrandChild` component in your repro only accepts a single `enum` parameter (`ChildType`), and this value doesn't change between renders, the component doesn't re-render in .NET 8.

This isn't something we're going to revert, because in most cases it's good to avoid unnecessary re-renders.

If you absolutely need the component to re-render, you can do so explicitly. For example, you can re-render the `EventListenerGrandChild` component in the same way you re-render `EventListener`.

Hope this helps. Closing this out as by-design.
