### ISSUE TITLE
How do you increase the startup time on IIS

### ISSUE THREAD

**Issue by Layfully** [dotnet/aspnetcore#58628]
We have a .net 7 web service hosted on Kestrel. It takes a long time, to load up all the data into memory (financial data). It can't be avoided and is already part of an async method. We already set the startupTimeLimit to 3600 (maximum) in the web.config. Our application restarts during startup and the process runs again.

HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit

Would it be possible to set the time limit higher (for example 1 hour 30 minutes) Alternatively, how do I instruct the IIS not to timeout when starting up?

**Comment by martincostello** [comment]
> We have a .net 7 web service hosted on Kestrel

.NET 7 has been [out of support since May 2024](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support) - the first thing you could try is upgrading to .NET 8. As well as meaning you'll be in support and get security fixes, performance improvements might make you app start faster (even if it's not fast _enough_).

Secondly, I would suggest moving your data load out of the start-up path, and doing it in the background, and using something like a [health ready probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) to use to poll for when when application is ready to serve traffic, and then rotate it into service when it considers itself ready.

**Comment by Layfully** [comment]
We are already migrating to .NET 9 and plan to merge it in November. We also tried moving data load out of the startup path into separate thread but this extended the load of the data since the app was running at the same time and doing it properly would require to rewrite some bigger parts of the app. Is it possible to increase the iis time higher than 3600?

**Comment by martincostello** [comment]
> Is it possible to increase the iis time higher than 3600?

Not that I'm aware of - [the docs](https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/web-config) say 3600 is the maximum.

**Comment by Layfully** [comment]
Okay, closing the issue
