### ISSUE TITLE
Renenable .tt generated code for RequestHeaders.Generated.tt

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#5869]
When we converted from project.json to csproj the .tt code generation stopped working. Figure out how to hook it back up in the csproj world.

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
