### ISSUE TITLE
Correlation failure

### ISSUE THREAD

**Issue by asos-jasperdeluna** [dotnet/aspnetcore#58780]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Authentication failure occurs during external provider (Facebook/Google) sign-in process with a "Correlation failed" error. The authentication middleware is unable to validate the correlation ID between the initial authentication request and the provider's callback. This is an existing issue but its not clear what the resolution is here https://github.com/dotnet/aspnetcore/pull/47873

### Expected Behavior

We expect there to be some way to catch that exception

### Steps To Reproduce

Uncertain, we suspect users are waiting for >10 mins on login page, then trying to log in which causes the "Correlation failed." exception.

### Exceptions (if any)

Exception: Microsoft.AspNetCore.Authentication.AuthenticationFailureException
Message: "Correlation failed."
Location: Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper

Stack Details:
- OuterId: "8299279"
- Component: Duende.IdentityServer, Version=7.0.6.0
- Error ID: 40001287
- Severity: Error

Full Exception Chain:
1. Primary Exception:
   - Type: Microsoft.AspNetCore.Authentication.AuthenticationFailureException
   - Message: "An error was encountered while handling the remote login."
   - ID: 8299279

2. Inner Exception:
   - Type: Microsoft.AspNetCore.Authentication.AuthenticationFailureException
   - Message: "Correlation failed."
   - ID: 40001287
   - SeverityLevel: Error

### .NET Version

net. 8

**Comment by mkArtakMSFT** [comment]
@halter73 @javiercn suggested that there is probably a setting which will allow to configure the cookie timeout. Do you know how to set that setting?

**Comment by javiercn** [comment]
Assuming you are using openid connect you can use `AddOpenIdConnect(o => o.NonceCookie.Expiration = ...)` to set a longer expiration time for the nonce.

**Comment by asos-jasperdeluna** [comment]
@mkArtakMSFT  @javiercn Thanks for the quick response. As I understand it the issue is around the correlation between the start of the external provider interaction and the callback at the end. Extending the cookie would allow us to give the user longer on the external provider login page. But this wouldn't solve other scenarios i.e. clicking back from the external provider login etc. Is there a way to catch this error so we can handle it properly? Thanks

**Comment by halter73** [comment]
> Uncertain, we suspect users are waiting for >10 mins on login page, then trying to log in which causes the "Correlation failed." exception.

This is probably the root cause of the issue.  If users wait > 15 minutes on the login page, correlation failures are expected. If you want to make this less common, you can increase the [RemoteAuthenticationTimeout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.remoteauthenticationoptions.remoteauthenticationtimeout?view=aspnetcore-9.0) from its default of 15 minutes.

> We expect there to be some way to catch that exception

There is a way. You can configure the [`OnRemoteFailure`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.remoteauthenticationevents.onremotefailure?view=aspnetcore-9.0) event. If you call [`HandleResponse()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.handlerequestcontext-1.handleresponse?view=aspnetcore-9.0) or [`SkipHandler()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.handlerequestcontext-1.skiphandler?view=aspnetcore-9.0), the exception will not be thrown.

Please feel free to reopen this issue if this doesn't answer your question or open a new one.
