### ISSUE TITLE
OAuth RedirectUri is not being applied

### ISSUE THREAD

**Issue by ckcks12** [dotnet/aspnetcore#58855]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/5278d28ab78b13a69c468939fff1968ca935ee5a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L263-L277

properties.RedirectUri is not being used at all.

https://github.com/dotnet/aspnetcore/blob/5278d28ab78b13a69c468939fff1968ca935ee5a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L273-L277

RedirectContext sets its RedirectUri property with the last argument which  from `BuildChallengeUrl()`.

https://github.com/dotnet/aspnetcore/blob/5278d28ab78b13a69c468939fff1968ca935ee5a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L300-L310

and `BuildChallengeUrl()` uses second argument, not the first one - `properties.RedirectUri`. This maybe the bug.

https://github.com/dotnet/aspnetcore/blob/5278d28ab78b13a69c468939fff1968ca935ee5a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L273
```c#
    protected string BuildRedirectUri(string targetPath)
        => Request.Scheme + Uri.SchemeDelimiter + Request.Host + OriginalPathBase + targetPath;
```
the second argument is built from httpcontext.

# suggestions
use BuildChallengeUrl as fallback of properties.RedirectUri

### Expected Behavior

# what I expected is:

```c#
        await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new GoogleChallengeProperties
        {
            Prompt = "consent",
            RedirectUri = "https://webdonalds.io/signin-google",
        });
```
this redirect uri must be passed to oauth.

(but currently, it's ignored)

### Steps To Reproduce

set redirect uri to https://github.com . 
redirect_uri parameter won't be changed.

### .NET Version

8.0.201

**Comment by ckcks12** [comment]
It's funny (and kinda scary) that it's quite easy to patch.

```
app.Use(
    async (ctx, next) =>
    {
        var path = ctx.Request.Path.ToString();
        if (path.Contains("/login") || path.Contains("/signin-"))
            ctx.Request.Scheme = "https";
        await next(ctx);
    }
);

```
Where /login is with google oauth entrypoint.

Since the redirect uri check are happening in both side: clinet(us) server(google)
so each path check is for them.

honestly, I thought it's quite annoying bug so others might have an interest on it but apparently not.

It's useful(more like necessary) in this env. reverse proxy (with https cert) and http plain server.

I know there's Forwarding-aware middleware in asp.net built-ins but oauth handler, remote auth handler they don't use it 🙂‍↔️

Until this bug be fixed, this workaround works. 

and i for sure can make a pull request, just wanna know it's a bug or need-to-improve stuff. just let me know.

**Comment by halter73** [comment]
When doing an OAuth flow, the first redirect back to your application needs to be handled by `OAuthHandler.HandleRemoteAuthenticateAsync` so it can verify the authorization code and exchange it with the token and userinfo endpoints to ensure the login really succeeded and figure out what should go into the `ClaimsPrincipal`. That's why the `redirect_uri` must be `RemoteAuthenticationOptions.CallbackPath` which gets handled by the `OAuthHandler` first.

After the redirected request to `Options.CallbackPath` gets validated, and any necessary cookies are set to preserve the `ClaimsPrincipal` for future request, the `OAuthHandler` then redirects again back to the URL specified by `AuthenticationProperties.RedirectUri`. It first gets serialized into encrypted state here:

https://github.com/dotnet/aspnetcore/blob/9ab6570011b03f287b21dfe7235460b27780794a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L329

And then gets decrypted, deserialized and used for the final redirect here:

https://github.com/dotnet/aspnetcore/blob/9ab6570011b03f287b21dfe7235460b27780794a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L68-L69

https://github.com/dotnet/aspnetcore/blob/9ab6570011b03f287b21dfe7235460b27780794a/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L180

> It's funny (and kinda scary) that it's quite easy to patch.

I'm not sure why it's scary that you can do powerful things in middleware like change things like `HttpContext.Request.Scheme` so following middleware handles the request differently. That's one of the primary purposes of middleware.

The fact that changing the request scheme to "https" fixes your issue implies that there is some sort of [TLS termination](https://en.wikipedia.org/wiki/TLS_termination_proxy) happening in front of your app. If you have TLS termination in front of your app, and you don't have some sort of middleware in front of the authentication middleware informing it that the original request scheme really was "https" and not "http", then `BuildRedirectUri` will generate an "http" URL which is likely being rejected by the OAuth provider.

Your custom middleware is a reasonable solution if you know that requests cannot reach your app without TLS. If that's true, HttpContext.Request.Scheme` really should be "https" for all requests, not just the ones containing "/signin-" on the path. This affects more than just the `OAuthHandler`, it can also affect things like link generation in Blazor and MVC.

The more standard way to do this is using the [forwarded headers middleware](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0#forwarded-headers-middleware-order). Most proxies that do TLS termination will add an `X-Forwarded-Proto: https` header to the request. The code would look something like this:

```csharp
var builder = WebApplication.CreateBuilder(args);

// ...

builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedProto;
});

// ...

var app = builder.Build();

// Make sure to call UseForwardedHeaders() before UseAuthentication()
app.UseForwardedHeaders();

app.UseRouting();
app.UseAuthentication()
app.UseAuthorization();

// ...
```

, and we have built in middleware that does exactly this called the `ForwardedHeadersMiddleware`

**Comment by halter73** [comment]
Please feel free to reopen the issue, or if you cannot do that, file a new one, if this doesn't in fact answer your question.
