### ISSUE TITLE
Blazor solution to loading data twice due to Prerender

### ISSUE THREAD

**Issue by Terrence77** [dotnet/aspnetcore#58854]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blazor Server Prerender:

Rendering calls OnInitializedAsync twice and data is loaded from db twice.

### Describe the solution you'd like

Simply supply a boolien parameter to 

OnInitializedAsync(bool firstRender)

```
protected override async Task OnInitializedAsync(bool firstRender)
{
	if(firstRender)
		await LoadData();
}
```

I have read all the instructions for dealing with this and they are all too complex compared to reacting to bool parameter.

OnAfterRenderAsync is obviously too late in the lifecycle to populate controls with data.

Is there some technical reason why you can't pass this bool to OnInitializedAsync?

Thank you.

**Comment by javiercn** [comment]
@Terrence77 thanks for contacting us.

The behavior is by design, the app renders once, gets tore down after prerendering and re-renders interactively when the circuit is connected. 

The parameter you are referring to (isFirstRender) doesn't make sense in this context. OnInitialized(async) already represents the first time the component receives parameters.

The component instance during prerendering is not the same instance after the circuit starts in interactive mode, hence you need a way to "restore" the state.

You can re-issue the query, use a cache, detect that you are prerendering and avoid loading the data in that scenario or use persistent component state to restore the state from the original render.

**Comment by Terrence77** [comment]
@javiercn thank you for that explanation.  I barely understand it, but it is sinking in slowly.

Terrence
