### ISSUE TITLE
Blazor web app with Fallback authentication and disabled prerendering doesn't load content of anonymous pages

### ISSUE THREAD

**Issue by pilarodriguez** [dotnet/aspnetcore#58978]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a .Net 8 Blazor web app with server side rendering. I have configured Entra ID authentication with a fallback policy.

I have a home page that allows anonymous authentication (to make it easier to test authentication, it is not the intention to keep it). And an "Access denied" page also with anonymous authentication. Once you try to Access any of the other pages you are redirected to Microsoft authentication. If the user is not valid, it should be redirected to the "Acess denied" page, which will show an error message (that's why this page should allow anonymous)

If I configure globally interactive render mode with the prerendering disabled in the App.razor page (`<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />`), I don't get an error when I access to the Home or Access denied pages, but the content is not loaded. 

![Image](https://github.com/user-attachments/assets/8a0479b9-7097-475f-aba1-387dbe292132)

If I allow prerendering or if instead of configuring the global render mode in the App.razor page, I just use ` <Routes/>` and then in the page where I need it I add the attribute (`@rendermode @(new InteractiveServerRenderMode(prerender: false))`), the content is loaded. 

The workaround is obviously to set the attribute where needed instead of globally. But for big applications with many components, it is not acceptable.

### Expected Behavior

I should be able to globally disable prerendering

![Image](https://github.com/user-attachments/assets/7f15f4f9-1052-4cd7-9dfe-eb361f0d5b1e)

### Steps To Reproduce

This is a minimal repo to reproduce it https://github.com/pilarodriguez/quick-grid-test/tree/main
It is missing the Entra ID secrets from the config file. I don't want those secrets to be public

### .NET Version

.Net 8

**Comment by danroth27** [comment]
A fallback authentication policy is going to require authentication for anything, even your anonymous pages. As an alternative, could you use an *_Imports.razor* file to apply an `[Authorize]` attribute to just the desired pages?

**Comment by pilarodriguez** [comment]
> A fallback authentication policy is going to require authentication for anything, even your anonymous pages

Doesn't it defeat the whole propose of an anonymous page? If the anonymous pages require authentication, what is the purpose of anonymous pages then? 


> As an alternative, could you use an __Imports.razor_ file to apply an `[Authorize]` attribute to just the desired pages?

That is not secure. In the future new pages might be added and the attribute could be missed. We want the whole application to be secure and always use a default authentication

Instead of using the fallback authentication, I've also tried adding the (`@attribute [Authorize(Roles = "Admin")]`) attribute to the `_Imports.razor` file, and `[AllowAnonymous]` at the top of the `App.razor` file (not sure if that is correct). And I get a similar behavior. It works if I don't configure globally the render mode (without the `<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />`), and if I do, the pages requires authentication if I access them from a direct link, but not if I click in the navigation bar.

**Comment by halter73** [comment]
> Doesn't it defeat the whole propose of an anonymous page? If the anonymous pages require authentication, what is the purpose of anonymous pages then?

The issue is that the fallback policy applies to everything including static assets that are necessary for anonymous pages.

> Instead of using the fallback authentication, I've also tried adding the (`@attribute [Authorize(Roles = "Admin")]`) attribute to the `_Imports.razor` file, and `[AllowAnonymous]` at the top of the `App.razor` file (not sure if that is correct). 

The `[AllowAnonymous]` and `[Authorize]` attributes only work when they are in a page component (meaning there's a `@page` directive which makes it routable) or inside of `_Imports.razor` since that gets included in page components.

Is there a reason that putting `[Authorize(...)]` in `_Imports.razor` and `[AllowAnonymous]` on the page components is insufficient?

**Comment by pilarodriguez** [comment]
> Is there a reason that putting `[Authorize(...)]` in `_Imports.razor` and `[AllowAnonymous]` on the page components is insufficient?

That would indeed be a good solution. The problem is that it doesn't work when configuring the global render mode. I want to use server side rendering and disable prerendering on all pages. I do it by adding this in the App.razor page
```

    <Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
```
But with this, the authentication doesn't work properly. Authentication is requested if I directly access the page with the link, which is correct. But if I click on the navigation bar to be redirected to the page, then I get access even if I'm not authorized

In this gif you can see how Home page is allowed (which is correct), but then when I navigate to Resource overview, which is not anonymous, the page is also shown (which is not correct because my user is not authorized for that page). If I use directly the link to the resource overview page, then I'm redirected to Microsoft Entra to add my credentials and then I get the Access denied page (which is correct because my user doesn't have permission)

![Image](https://github.com/user-attachments/assets/7d3c8f91-f9f4-4d4b-b6a9-5a0bc4ec6f40)



It works fine if I just have `<Routes/>`  in the App.razor page and then add the attribute `@rendermode @(new InteractiveServerRenderMode(prerender: false))` to every page. But we don't want to add the attribute to all pages, we want to configure a default render mode

**Comment by halter73** [comment]
> But with this, the authentication doesn't work properly. Authentication is requested if I directly access the page with the link, which is correct. But if I click on the navigation bar to be redirected to the page, then I get access even if I'm not authorized

This appears to be because you're using `<RouteView>` instead of `<AuthorizeRouteView>` [inside of `Routes.razor`](https://github.com/pilarodriguez/quick-grid-test/blob/57071d8faa4fa23dbee3387b572976a1e3432bb4/QuickGridTestProj/Components/Routes.razor#L3). You should be using `<AuthorizeRouteView>`. I recommend taking a look at [the ASP.NET Core Blazor authentication and authorization docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-9.0&tabs=visual-studio#resource-authorization). The "Resource authorization" section covers `<AuthorizeRouteView>`, but the whole document is worth a read. 

New requests still require authorization even without `<AuthorizeRouteView>` is because the routing and auth middleware get a chance to handle new requests, but when there is globally interactive internal navigation, there is no new request and the Blazor router is the last line of defense.

Once you update to `<AuthorizeRouteView>`, you'll probably want to include a `<NotAuthorized>` element that redirects to the login page. There's an example of something like this in the [blazor-samples repo here](https://github.com/dotnet/blazor-samples/blob/28d960afb5ff659ed05aa9a5a929c696afc9d694/9.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Routes.razor#L3-L7).

#### Routes.razor

```razor
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <AuthorizeRouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)">
            <NotAuthorized>
                <RedirectToLogin />
            </NotAuthorized>
        </AuthorizeRouteView>
    </Found>
</Router>
```

#### RedirectToLogin.razor
```razor
@inject NavigationManager Navigation

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateTo($"authentication/login", forceLoad: true);
    }
}
```

#### Program.cs

```csharp
app.MapGet("/authentication/login", () => TypedResults.Challenge()).AllowAnonymous();
```

Does this fix your issue?

**Comment by pilarodriguez** [comment]
Sorry for the late reply. Yes, that solution works. Thanks
