### ISSUE TITLE
-BuildManaged -BuildInstallers doesn't work as installer build too early

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/aspnetcore#58984]
When building installers without first building the rest of the repository (managed + native) in a previous build execution, the build fails as the installer build runs too early. This is probably not a problem as that's not a common workflow but with the VMR we need to be able to build the entire repository in one go.

Blocks https://github.com/dotnet/sdk/pull/44828?new_mergebox=true

The solution that I'm thinking of is adding a Traversal project that builds the installer projects and adding that to eng/Build.props at the very end with a `BuildInParallel=false` metadata so that it runs after everything else. The installer project will still build in parallel.

**Comment by ViktorHofer** [comment]
cc @wtgodbe

**Comment by wtgodbe** [comment]
Yeah, our workflow for installers has always been to build them in a separate invocation of `build.cmd`, after the main repo build. This isn't great, but has never really been a problem since almost nobody ever needs to build the installers locally. I'd be happy to change it in the repo if the VMR solution works, it would simplify our CI/logical model
