### ISSUE TITLE
nuget package 'Microsoft.AspNetCore.SignalR.Client' is not compatible with Blazor server webassembly using .NET 8.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59085]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/nuget-package-MicrosoftAspNetCoreSign/10790621)._

---
[severity:It's more difficult to complete my work]
When adding the package Microsoft.AspNetCore.SignalR.Client to a Blazor server webassembly project that uses the target framework .NET 8.0 the project will load and appear but functionality ceases to work.

Even if you create a brand new project, add the SignalR.Client assembly,... since the project defaults to .NET6.0 it will work... when you switch to .NET 8.0, it will not. 
![Screenshot 2024-11-14 145814.png](https://aka.ms/dc/image?name=B56ade73a3529497286f0cb919c7b7e64638672111155999893_Screenshot_2024-11-14_145814.png&tid=56ade73a3529497286f0cb919c7b7e64638672111155999893)

---
#### Feedback Bot on 11/14/2024, 05:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### peckler on 11/15/2024, 00:38 PM: 

<p>This issue was introduced in the latest Microsoft.AspNetCore.SignalR.Client version 9. The previous version 8.0.11 seems to be ok.</p>

**Comment by aholland1973** [comment]
I have experienced the same issue today. 

If you create a brand new .NET 8.0 Blazor Server application using the "Blazor Web App" VS2022 template, and then add the Microsoft.AspNetCore.SignalR.Client package, _anything_ SignalR breaks immediately, even the demo "Counter.razor" page. This is clearly because while version 9.0.2 of the package is (currently) added, this isn't forward-compatible in a .NET 8.0 app. 

The solution therefore is to downgrade the package to 8.0.13 and then everything works correctly again. 

Does NuGet not have any mechanism for only getting the latest version of a package that actually works with a given .NET release?
