### ISSUE TITLE
Cascading Parameter is null with SSR /interactive Server

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#59109]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Seems to be a 9 issue

` <CascadingValue Name="Hannes" Value="11">  
     <Routes />
 </CascadingValue>`

Set home.razor to 

@rendermode InteractiveServer

`  [CascadingParameter (Name="Hannes")]
  public int hannes { get; set; }`

Parameter @Hannes is 0

### Expected Behavior

should be 11

### Steps To Reproduce

https://github.com/hannespreishuber/cascadingtestcase

### .NET Version

9

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

This is by design. Your cascading parameter value is crossing render boundaries, which is not supported.
https://github.com/hannespreishuber/CascadingTestCase/blob/master/CascadingTestCase/Components/Pages/Home.razor#L2

See https://github.com/dotnet/aspnetcore/issues/51969

**Comment by hannespreishuber** [comment]
> [@hannespreishuber](https://github.com/hannespreishuber) thanks for contacting us.
> 
> This is by design. Your cascading parameter value is crossing render boundaries, which is not supported. https://github.com/hannespreishuber/CascadingTestCase/blob/master/CascadingTestCase/Components/Pages/Home.razor#L2
> 
> See [#51969](https://github.com/dotnet/aspnetcore/issues/51969)

. unexpexted behavior
- no warning - just empty, when switiching Render mode. 
- nearly impossible to find and fix by dev

sum: ugly by design
