### ISSUE TITLE
Preventing Default Behavior for Events Directive Lifecycle

### ISSUE THREAD

**Issue by connorbowlan** [dotnet/aspnetcore#59142]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

**Framework:** .NET 8
**Render Mode:** Interactive Server

**Issue**

With this code sample, using any given Blazor directive to prevent an event's default behavior, the lifecycle falls one step behind:

![Image](https://github.com/user-attachments/assets/3ae389b1-eed4-4a81-b2d1-f57925a75112)

If you press either the arrow down or arrow up keys, the next key may not be populated into the field as `_preventKeyDownDefault` will be false for that call to `HandleKeyDown()`.

**Reproduction**

1. Type a word into the field.
2. Press either the arrow down or arrow up key.
3. Press any other alphabet key.
4. Note that your pressed key is not populated into the input field.
5. Press any other alphabet key.
6. Note that because `HandleKeyDown()` has been called again `_preventKeyDownDefault` is now `false` the pressed key is populated into the input field.

https://github.com/user-attachments/assets/d2f476a0-997b-47bd-9aa4-893c3834a003

### Describe the solution you'd like

Create an override for the `@event:preventDefault` Blazor directive that passes an object of type `KeyBoardEventArgs`, but still expects a `bool` as the returned type.

![Image](https://github.com/user-attachments/assets/c184ae62-8208-4490-ae13-8e98a3e43062)

`HandleKeyDownPreventDefault()` will accept `KeyboardEventArgs` as a parameter and conditionally return whether to prevent the default behavior.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The issue you're observing here is that you can only call the preventDefault synchronously, and it has to be called before the event handler completes. In the Blazor Server case it's impossible to make that decision in the C# code, because the C# handler will be invoked asynchronously. You can work around this by implementing this in JS.

The following issue has more details about this problem: https://github.com/dotnet/aspnetcore/issues/45949

**Comment by connorbowlan** [comment]
Ah. Dang it. That makes sense. I wish I had seen that thread before posting. Thanks anyway!
