### ISSUE TITLE
Static web assets blazor, ability to exclude appsettings (or other files)

### ISSUE THREAD

**Issue by Nickztar** [dotnet/aspnetcore#59163]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We currently replace some settings on deployment in the appsettings.json files. But due to them being compressed and served as static assets we are unable to get the settings.

I feel like this already exists but I am unable to find anything or get anything to work. Found a way to exlude them from compression but they are still served as a static asset and thus they are sent incomplete (file is larger now...)

### Describe the solution you'd like

Some way to, in csproj, set that a file should be excluded from static assets.

**Comment by javiercn** [comment]
@Nickztar thanks for the additional details.

The current approach is mainly geared towards creating a "final" deployment during build/publish. Modifying files after that becomes more challenging, and generally not recommended compared to working within the build to get the files updated at that time.

With that said, there are a couple of ways to go about it:
* You can modify the `<<project>>.endpoints.json` file to update the content length as well as the ETag for the file.
  * The ETag is the Base64 encoded SHA256 value of the file contents.
  * You might also have to update the `integrity` property of the endpoint, which matches the ETag value.
  * Note that the format of this file is considered an implementation detail that might change in future versions as needed.
  * This, along with disabling compression should be good enough for the original file to get served correctly without compression.
  * If the file also has a fingerprinted endpoint, (which I believe it does) you'll have to also update the ETag for that endpoint as well as well as the fingerprint value (Which you can compute as the Base36 of the SHA256 hash)
  * In general, you can find the relevant code https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Tasks/Utils/FileHasher.cs
* You can remove `appSettings` from the `Content` item group and add it to the `ContentWithTargetPath`, specifying the appropriate target path so that it gets copied to the right output location.
  * You'll have to wire-up `app.UseStaticFiles` to serve this file, since it won't be part of the list of endpoints.
* You can integrate the changes at the time you are publishing by adding your target to `<PrepareForBuildDependsOn>Your-Target;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>` and doing your modifications there.
  * The advantage of this approach is that you work with the system vs against it.

**Comment by Nickztar** [comment]
Thanks for the response. Appsettings sadly cannot be excluded from Content since then it won't be recognized in blazor.boot.json so the runtime won't resolve it.

My solution was something like your first example but instead of changing it I just removed all endpoints that matched appsettings and then serve them via UseStaticAssets.
