### ISSUE TITLE
JwtBearer middleware silently fails without Microsoft.IdentityModel.Tokens.JsonWebTokens dependency

### ISSUE THREAD

**Issue by DennisBaekgaard** [dotnet/aspnetcore#59210]
## Summary
The `Microsoft.AspNetCore.Authentication.JwtBearer` middleware silently fails token validation when the `Microsoft.IdentityModel.Tokens.JsonWebTokens` package is not installed, despite valid tokens being passed. Seeing there's no warning or error suggestion the JsonWebTokens package is required to correctly validate a JWT, a developers first thoughts are to debug the actual pipeline/tokens it self, and not the packages required. 

## Motivation and goals

When using JWT Bearer authentication in .NET applications, the `Microsoft.IdentityModel.Tokens.JsonWebTokens` package is required to properly validate tokens with the JsonWebTokenHandler. Without this package, the middleware silently falls back to the older` JwtSecurityTokenHandler`. This can in some cases cause the pipeline to fail token validation, without informing the cause of it. When inspecting the context at run time, logging more extensively etc. no information is provided as to the actual issue.

## In scope

Ensure that the JwtBearer middleware logs warnings when `JsonWebTokenHandler` is unavailable, and (to the best of my knowledge) fallback to `JwtSecurityTokenHandler` occurs. Maybe make it conditional based on `.AddJwtBearer()`.

## Examples

1. Set up JWT Bearer authentication in a .NET app, e.g. Minimal API
2. Pass a valid JWT signed with RS256 to an endpoint with `.RequireAuthorization()`
3. Without the `Microsoft.IdentityModel.Tokens.JsonWebTokens` package, the middleware falls back to `JwtSecurityTokenHandler`.

Observe the The token is rejected with a generic "invalid token" error.

##Proposed behaviour
The middleware logs a warning: `JsonWebTokenHandler is not available. Falling back to JwtSecurityTokenHandler, which may fail on certain tokens. Install Microsoft.IdentityModel.Tokens.JsonWebTokens to resolve this.`

**Comment by mkArtakMSFT** [comment]
@halter73 can you please look into this?
For the `no logs` concern I think we should consider improving that as part of https://github.com/dotnet/aspnetcore/issues/54424

**Comment by halter73** [comment]
I see this has a number of reactions, so I must be missing something, but I don't think it's possible to reference the `Microsoft.AspNetCore.Authentication.JwtBearer` without also referencing `JsonWebTokenHandler` unless you're doing something really unusual.

First off, [Microsoft.IdentityModel.Tokens.JsonWebTokens](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens.JsonWebTokens) is not a NuGet package, but I assume you mean [Microsoft.IdentityModel.JsonWebTokens](https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens) which does contain [`JsonWebTokenHandler`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2ecd35bba7059e354df0d8a346526a499a8f0e30/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs). However, this package is brought in transitively through `JwtBearer`'s `Microsoft.IdentityModel.Protocols.OpenIdConnect` dependency.

```cli
PS C:\dev\temp> mkdir issue-59210
PS C:\dev\temp\issue-58996> cd issue-59210
PS C:\dev\temp\issue-59210> dotnet new web
The template "ASP.NET Core Empty" was created successfully.

Processing post-creation actions...
Restoring C:\dev\temp\issue-59210\issue-59210.csproj:
Restore succeeded.

PS C:\dev\temp\issue-59210> dotnet add package Microsoft.AspNetCore.Authentication.JwtBearer
PS C:\dev\temp\issue-59210> dotnet nuget why .\issue-59210.csproj Microsoft.IdentityModel.JsonWebTokens
Project 'issue-59210' has the following dependency graph(s) for 'Microsoft.IdentityModel.JsonWebTokens':

  [net9.0]
   │
   └─ Microsoft.AspNetCore.Authentication.JwtBearer (v9.0.0)
      └─ Microsoft.IdentityModel.Protocols.OpenIdConnect (v8.0.1)
         └─ System.IdentityModel.Tokens.Jwt (v8.0.1)
            └─ Microsoft.IdentityModel.JsonWebTokens (v8.0.1)
```

The only reason I know of that `JwtBearer` would use `JwtSecurityTokenHandler` over `JsonWebTokenHandler` in .NET 8 and alter is if you set `JwtBearerOptions.UseSecurityTokenValidators = true` which is one of the workarounds suggested in the [.NET 8 Breaking change announcement](https://github.com/aspnet/Announcements/issues/508) that accompanied the breaking change to use `JsonWebTokenHandler` instead of `JwtSecurityTokenHandler` by default.

If this is not what's going on, can someone please provide a complete repro project, host it on github, and link to it here?

Artak is correct that #54424 should improve the logging around `JwtBearer` authentication failures in general, and make issues like this easier to diagnose.
