### ISSUE TITLE
Microsoft.AspNetCore.OpenApi. How can I detect when dotnet watch has hot reloaded?

### ISSUE THREAD

**Issue by nielsbosma** [dotnet/aspnetcore#59258]
I'm working on an ASP.NET Core application and using dotnet watch for development. When dotnet watch performs a hot reload, the application doesn't restart, and lifecycle events like ApplicationStarted or ApplicationStopped are not triggered.

I would like to detect when a hot reload occurs (e.g., when a file change triggers the reload). Ideally, I want to log or execute some custom logic whenever hot reload happens.

I've tried monitoring lifecycle events like IHostApplicationLifetime.ApplicationStarted, but these don't get triggered during hot reloads. I've also looked into using middleware, but that only captures incoming requests.

How can I reliably detect and respond to hot reload events in an ASP.NET Core application without having to watch for file changes?

**Comment by captainsafia** [comment]
@nielsbosma I believe that you can implement a `MetadataUpdateHandler` in order to solve this. See [these docs](https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload-metadataupdatehandler?view=vs-2022) for more information.

Your issue title indicates something related to OpenAPI. What are you trying to do with OpenAPI and hot reload?
