### ISSUE TITLE
host.RunAsService() throws PlatformNotSupportedException on Windows

### ISSUE THREAD

**Issue by cheesi** [dotnet/aspnetcore#5934]
Hello!

I'm facing a very strange issue. Currently I'm porting our .Net Framework windows service to ASP.NET Core. For the windows service part, i have been following this tutorial: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

However the `host.RunAsService()` throws a `PlatformNotSupportedException `on my windows dev machine (i didn't had the time to test it somewhere else).

```c#
System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceBase..ctor()
   at Microsoft.AspNetCore.Hosting.WindowsServices.WebHostService..ctor(IWebHost host)
   at Project.TerminalServer.Program.Main(String[] args) in C:\Users\user\source\repos\Project\src\Project.Server\Program.cs:line 63
```

The code isn't very spectacular:
```c#
IsService = args.Contains(RUN_AS_SERVICE);
ContentRoot = IsService ? Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName) : Directory.GetCurrentDirectory();
Logger = NLogBuilder.ConfigureNLog(Path.Combine(ContentRoot, NLOG_CONFIG)).GetCurrentClassLogger();
var host = CreateWebHostBuilder(args.Where(x => x != RUN_AS_SERVICE).ToArray()).Build();
                
if (IsService)
{
    Logger.Info("Starting as a service.");
    host.RunAsService();
}
else
{
    Logger.Info("Starting in console mode.");
    host.Run();
}
```

Info:
```
ASP.NET Core 2.1.2 with Microsoft.AspNetCore.Hosting.WindowsServices 2.1.1.
Windows 10.0.17134 
C:\Users\user>dotnet --version
2.1.400
```

**Comment by achikhv** [comment]
Got this error on .NET Core 2.2 after including package reference
`<PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.1" />`

When I remove it, service runs successfully.

Hope that helps.

**Comment by romain78** [comment]
I had the same issue, the problem was the namespace :
the name of the .exe file generated contained a dot :
MySolution.Test.exe (won't work) => MySolutionTest.exe (works)

**Comment by cphillips83** [comment]
Just to add what solved the issue for me. I have a project like dotnet thats a CLI tool for in house devops related things. This tool uses chocolatey to install individual commands in to their own folder. It then uses some reflection and command line parsing to call in to these commands.

Since the commands are in their own folders outside of the main exe, I have used the assembly event to look for DLLs that can't be found in the main exe path. For some reason the main exe path already has a stubbed out version of System.ServiceProcess when doing a self containied deploy/publish even though it was not used anywhere. This was leading to reflection load that DLL instead of the real one in the command's folder.

Once I added the nuget for System.ServiceProcess to the main project that handles command delegation the error went away and started properly. I only came to try this based on what @Tratcher  said above.

My suggestion is to provide a better error message. Prior to saying "OS not supported", perhaps it should check to see if you are on windows or a supported OS and report that this is some sort of stub library and to add the nuget reference?

**Comment by lothrop** [comment]
I got this error message on Windows Server 2019 with .NET Core 3.1 when I failed to copy the runtimes folder along with the executable and DLLs.

**Comment by Larry57** [comment]
I forgot to copy the xxx.deps.json file and it also leads to this issue. (.NET Core 3.1)

**Comment by KalibGao** [comment]
@Larry57 
https://github.com/dotnet/aspnetcore/issues/5934#issuecomment-644003133
This works for me.

**Comment by davidfowl** [comment]
If this still repros using the generic host, file an issue on dotnet/runtime. I believe I saw a similar issue related to nuget packages and files being overwritten on publish (I can't find it right now).
