### ISSUE TITLE
OpenApi will use System.ComponentModel.Attributes changed to Fluent mode.

### ISSUE THREAD

**Issue by YataoFeng** [dotnet/aspnetcore#59393]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Suppose I have 20 parameters in a class, and each parameter requires many `System Components.Model.Attributes`, this will look confusing.

description、required、defaultValue、range、minLength、maxLength、regularExpression...

emailAddress、phone... and other custom validation.

### Describe the solution you'd like

Can OpenApi support it will use `System.ComponentModel.Attributes` changed to Fluent mode.
EntityFramework provides two options, Fluent and Attributes.

**Comment by captainsafia** [comment]
@YataoFeng Thanks for filing this issue!

I don't think we'd add support for fluent-style attributes on parameters in the current implementation. However, it should be possible to achieve this behavior by using schema transformers. See [the docs here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/customize-openapi?view=aspnetcore-9.0#use-schema-transformers).

For context as to why, most things in ASP.NET Core, like MVC's model validation, take a dependency on the System.ComponentModel attributes which is why we've adopted them as the min-bar for support in this implementation. The schema transformers API does provide an opportunity to add this support independently in a third party library.
