### ISSUE TITLE
Blazor Scaffolding is broken due to regression

### ISSUE THREAD

**Issue by coderdnewbie** [dotnet/aspnetcore#59491]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

1) I created a brand new Blazor App with Identity and Interactive Auto, using the Web App template.

2) I added the movie.cs file from Microsoft learning https://www.youtube.com/watch?v=ZN-CcfEY3Z8 and added scaffolding.

3) I did migrations and and update database using connected services

4) Fixed some scaffolding errors. Tried to go to localhost movies page. Got the following Exception:

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppId.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppId.Data.ApplicationDbContext]'.

The fix in program.cs, is to change builder.Services.AddDbContext<...>to builder.Services.AddDbContextFactory<...>and then it works as expected.

The issue is that the scaffolding pages are injecting:

@inject IDbContextFactory<BlazorAppId.Data.ApplicationDbContext> DbFactory

but the program.cs is set as builder.Services.AddDbContext<...>

This is a regression as this used to work in .Net 8.0.

@Danoth, Please can you test https://www.youtube.com/watch?v=ZN-CcfEY3Z8 scaffolding again? I suspect it will not work with dotnet 9.0 and be a source of frustration to people trying to learn Blazor.

### Expected Behavior

The regression is fixed so scaffolding works like .Net 8.0 where builder.Services.AddDbContextFactory<...> was used.

### Steps To Reproduce

1) I created a brand new Blazor App with Identity and Interactive Auto, using the Web App template.

2) I added the movie.cs file from Microsoft learning https://www.youtube.com/watch?v=ZN-CcfEY3Z8 and added scaffolding.

3) I did migrations and and update database using connected services

4) Fixed some scaffolding errors. Tried to go to localhost movies page. Got the following Exception:

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppId.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppId.Data.ApplicationDbContext]'.

The fix in program.cs, is to change builder.Services.AddDbContext<...>to builder.Services.AddDbContextFactory<...>and then it works as expected.

### Exceptions (if any)

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppId.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppId.Data.ApplicationDbContext]'.

### .NET Version

.Net 9.0

**Comment by javiercn** [comment]
@coderdnewbie thanks for contacting us.

@danroth27 can you follow up?

**Comment by coderdnewbie** [comment]
I am a bit confused. The issue I am reporting is that the latest scaffolding has a bug where it injects IDbContextFactory but registers with AddDbContext instead of AddDbContextFactory. Please can the scaffolding be fixed to register using AddDbContextFactory.

The youtube video from @danroth27 is the training for beginners and is still applicable (i.e. not out of date) and fine to use if the bug in the scaffolding was not there. Please can it be fixed.

**Comment by coderdnewbie** [comment]
Thanks, if you can not recreate then let me know and I can give you exact steps.

**Comment by guardrex** [comment]
I believe I see where things went sideways.

When you were scaffolding, you probably selected the existing dB context ... the one that Identity placed ... instead of creating a new context for the scaffolding operation. If you select the plus sign next to **DbContext class** to add a new one (e.g., with the Blazor movie dB tutorial, we recommend `BlazorWebAppMovies.Data.BlazorWebAppMoviesContext`), then it creates the context for the added Razor components with `AddDbContextFactory` ...

```csharp
builder.Services.AddDbContextFactory<BlazorWebAppMoviesContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("BlazorWebAppMoviesContext") ?? 
    throw new InvalidOperationException("Connection string 'BlazorWebAppMoviesContext' not found.")));
```

... which is the one that the components will use ...

```razor
@inject IDbContextFactory<BlazorWebAppMovies.Data.BlazorWebAppMoviesContext> DbFactory
```

It creates that in addition to the one that's already there for Identity ...

```csharp
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
```

Two things come to mind on addressing this ...

Given that Dan's YT tutorial (and the written tutorial) don't get into adding Identity, it doesn't surprise me that his scaffolding step doesn't broach the subject of what to do if you're creating the app with Identity. I don't think that he (or I for the written tutorial) necessarily need to make a change to these tutorial experiences. Adding Identity is out of scope for these tutorials.

However for the scaffolder, it does lead to a poor user experience if the dev is scaffolding the components and the tooling suggests the existing dB context and does nothing to indicate that using it is going to 💥 on them. Perhaps, the scaffolder can be programmed to suggest a new context, which will lead to getting one based on `AddDbContextFactory`. I agree with you that the scaffolder can probably address this situation.

It's best if you close this issue and open a new one over on the scaffolding repo at ...

https://github.com/dotnet/Scaffolding/issues

... where you can describe this to them. Please feel free to cut-'n-paste as much of my remarks into it as you want. They'll work it forward from there. Otherwise, you'll need to wait until Dan gets back to have him move this issue over there. With the holidays ⛄ here, that could take a few weeks.

**Comment by coderdnewbie** [comment]
I have raised issue: https://github.com/dotnet/Scaffolding/issues/3131 and am closing this as requested by https://github.com/guardrex
