### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#6000]
_From @rosieks on January 8, 2015 17:19_

ASP.NET WebAPI 2 introduced support for batching. There was issue for batch implementation in Mvc but it was closed: https://github.com/aspnet/Mvc/issues/508

Despite that it would be great to have this usefull feature.

_Copied from original issue: aspnet/Home#262_

**Comment by GiancarloLelli** [comment]
Hi all,
I've implemented a sample client/server project for this. It uses a standard middleware and a few other things. The code is available here https://github.com/GiancarloLelli/aspnetbatchingmiddleware happy to discuss and answer questions

**Comment by vkras** [comment]
@GiancarloLelli , in my opinion, using HttpClient internally to make loopback requests sort of defeats the purpose of the batch mode from the performance point of view. Each connect will take time and resources to perform.

**Comment by ibasin** [comment]
I want to add my 2 cents and state that batch support is really important for us as well. Would love to see it implemented soon.

**Comment by fiksen99** [comment]
Any progress on official support for a batch apis?

**Comment by Tratcher** [comment]
Has anyone done an updated analysis on the usefulness of batching, especially now that HTTP/2 is achieving broad adoption? Batching in HTTP/1.1 seems to get you two things: 1) Maximum TCP packet density, and 2) fewer round trips to mitigate high latency connections.

For 1, HTTP/2 has a number of request compression techniques to reduce the number of bytes sent on the wire. While not a direct replacement for batching's packet density, it should offset those savings.

Case 2 is where it gets really interesting. HTTP/1.1 suffered over high latency connections because connections were poorly utilized. In most scenarios the client sends one request at a time, waits for the response, and then sends the next request. On high latency connections this multiplies the cost of every request. HTTP pipelining addressed this using an approach similar to batching, but was not widely adopted.

HTTP/2 addresses connection utilization via multiplexing. It allows hundreds of requests to be sent before you have to stop and wait for responses, and those responses can come as soon as they're ready, they don't have to wait for in-order delivery. This avoids the HTTP/1.1 latency issues by parallelizing transmission and processing, and the out of order responses can give you a big performance boost over pipelining or batching.

HTTP/2 is enabled by default in all modern browsers, in IIS and HttpSys (Win10), and Kestrel (3.0).

**Comment by gregFDS** [comment]
@Tratcher - I think Batch Support would still be useful because one could treat the entire batch as a single transaction, committing or rolling back related changes together.

**Comment by Lonli-Lokli** [comment]
For us Batch is a way how we can process long requests which might fail otherwise with Url too long exception, caused by spec limitation for GET requests.

**Comment by Tratcher** [comment]
> For us Batch is a way how we can process long requests which might fail otherwise with Url too long exception, caused by spec limitation for GET requests.

A batch implementation should enforce similar restrictions as a server or risk introducing exploits. Batching should not be used to bypass server restrictions.

**Comment by Lonli-Lokli** [comment]
@Tratcher not sure I get your point. It's similar to the way how OData Batch supposed to be used by official spec.

**Comment by Tratcher** [comment]
@Lonli-Lokli restrictions on fields like url lengths are implemented to ensure that components in the stack don't spend an arbitrary amount of time and resources processing the url. Data structures and algorithms designed for 1kb urls, or for 0-100 query key-value pairs are not going to hold up if the url is suddenly 32kb or there are 1000 query key-value pairs. This can result in performance, reliability, and security issues in your site.

**Comment by Lonli-Lokli** [comment]
Is there any spec for Batch to see how it supposed to work ?

**Comment by CRuppert** [comment]
This is a big deal for us too. We had rolled our own batch stuff at one point, but there was a fundamental change to how things are working under the hood here. Our batch stuff used to be able to parallelize the batch calls, but can no longer because of fundamental state changes under the hood to asp.net core. :/

**Comment by davidfowl** [comment]
This isn't something we plan to build an support natively in ASP.NET Core (at least not at the moment). I'm sure there are 3rd party middleware implementations that could be used.

**Comment by walunjsachin** [comment]
> This isn't something we plan to build an support natively in ASP.NET Core (at least not at the moment). I'm sure there are 3rd party middleware implementations that could be used.

Is there any recommendation from them?  I have seen Azure Portal using batch calls not sure if that is exposed via some nuget.
Also browser connection limitations (6 connections per domain) make bulk requests necessary.
