### ISSUE TITLE
Consider using ActivatorUtilities.CreateFactory in CompressionProviderFactory

### ISSUE THREAD

**Issue by pakrym** [dotnet/aspnetcore#6007]
`ActivatorUtilities.CreateInstance` is 30x slower than invoking factory delegate.

**Comment by adityamandaleeka** [comment]
I looked into how much of an impact this would have by using a modified version of https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/ResponseCompression/perf/Microbenchmarks/ResponseCompressionProviderBenchmark.cs where the setup (which exercises the `CreateInstance` codepath) is the benchmark.

With that test, I couldn't see a measurable improvement when switching to a cached `ObjectFactory` that we invoke each time instead of the current `CreateInstance` call.

Based on that, I'm closing this issue unless/until we discover another reason for doing this.
