### ISSUE TITLE
Enable MVC Views/Pages to invoke a Component as a TAG

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#6348]
We want to support views/pages using components using the normal element syntax. This is an upgrade over the current support for using HtmlHelper to invoke a component.

We need to do significant design and scoping work here to figure out the limitations and caveats of enabling this.

**Comment by javiercn** [comment]
Not sure why this is still open.
@rynowak is this not the `HtmlHelper extensions` or is this meant to be deeper integration, like calling a component as a tag from a view/page.

**Comment by rynowak** [comment]
This should track using components **AS TAGS** from views. Updating the main post.

**Comment by LorenDorez** [comment]
@rynowak I managed to get RC working in MVC Views but had to update the `components.server.js` file a bit. [repo here](https://github.com/LorenDorez/EatSleepBlazorRepeat/tree/master/MVCApp)

I cant wait for this to be fully integrated into MVC so i dont have to map RC components to random HTML tags. Might need to do a Prefix though since you could have a Component named to a current standard html tag like `button`

**Comment by SteveSandersonMS** [comment]
We do now support the `<component>` tag helper (both for rendering server-executed and client-executed components as of .NET 5).

If the original suggestion was to support using components directly (e.g., `<MyComponent />` inside a `.cshtml` file), it's not something on the roadmap currently due to high cost (e.g., with nested child content, it completely changes the meaning of `.cshtml` syntax) and the fact that it won't make a huge difference over `<component>`.

**Comment by HybridSolutions** [comment]
How is this progressing? We're using .NET 6 and still the following will not work in a View Component (Razor Pages):

```
@model ProgressBarViewModel
@{
}

DOES NOT WORK
<component type="typeof(eCM.Web.Components.Counter)" render-mode="ServerPrerendered" />

WORKS
@(await Html.RenderComponentAsync<eCM.Web.Components.Counter>(RenderMode.ServerPrerendered))
```

**Comment by MarcSchluperAtIntel** [comment]
> How is this progressing? We're using .NET 6 and still the following will not work in a View Component (Razor Pages):
> 
> ```
> @model ProgressBarViewModel
> @{
> }
> 
> DOES NOT WORK
> <component type="typeof(eCM.Web.Components.Counter)" render-mode="ServerPrerendered" />
> 
> WORKS
> @(await Html.RenderComponentAsync<eCM.Web.Components.Counter>(RenderMode.ServerPrerendered))
> ```

Yet https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-6.0 claims it does work. It also shows how to use parameters.

**Comment by mkArtakMSFT** [comment]
@danroth27 any objections against closing this?

**Comment by danroth27** [comment]
> @danroth27 any objections against closing this?

No objections from me. We have the component tag helper for rendering components from MVC views and Razor Pages. If you want Blazor component syntax end-to-end you can create a Blazor Web App.
