### ISSUE TITLE
asp.net core WebSocket behide IIS  won't  throw WebSocketException when “unsafe” close

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#6475]
### Describe the bug
I'm using websocket without SignalR, and I have a `ConcurrentDictionary<Guid,WebSocket>`  that count the coming connection.
and when I run the app use kestrel , and  kill the browser use TaskManager， the `WebsocketException` can successfully throw, but when I run the app behide IIS/ IIS-Express  , there  no Exception be throw

### Expected behavior
Throw WebsocketExceptin when the websocket connection "unsafe" close on both kestrel and IIS/IIS-Express

### Additional context
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.502
 Commit:    c74ce8f29f

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by John0King** [comment]
I'll try the new ANCM next week , I add a 2 minutes timeout for now

**Comment by John0King** [comment]
I try this today ,and it fix for IIS (dotnet hosting bundle) , but not for IIS-Express(dotnet SDK)
I look the aspnetcore.dll

server type  | runtime type | ancm info
|-----------|-------------|------------|
dev server|  dotnet hosting |  ancm v12.218346.1 (in `inetsrv` and `program file/iis` )
local pc    | dotnet sdk    | ancm v12.2.18192.0 (in `program file/iis express`)

## here's  the `dotnet --info`

### for dotnet sdk 
```
.NET Core SDK（反映任何 global.json）:
 Version:   2.2.102
 Commit:    96ff75a873

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### for hosting bundle

```

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by John0King** [comment]
@jkotalik @Eilon  Is it safe to rely on the websocket connection lifetime( eg. Throw `WebSocketException` ), Or It's better to do the server timeout and the client ping/pong.

**Comment by anurse** [comment]
@John0King in general, the only way to be sure to catch network disconnects is through timeouts and ping messages. There are many scenarios where a client/server will simply disappear and stop responding to messages and you won't get any response. This is true for any socket, including WebSockets :).

@jkotalik Is 2.1.7 available for IIS Express now?

**Comment by John0King** [comment]
@anurse 
>the only way to be sure to catch network disconnects is through timeouts and ping messages

I'm not familiar with the low level socket, but I have been hear of `TCP` connection is reliable， and `WebSocket` is build on that. and since we can catch the `WebSocketExpception` disconnect immediately after the client been killed and there is a `KeepAliveInterval` configuration of `WebSocket` , I think the ping/pong message is used in a low level socket (maybe in `TCP` connection level).
Is my understand right ?

```C#
        //
        // 摘要:
        //     Gets or sets the frequency at which to send Ping/Pong keep-alive control frames.
        //     The default is two minutes.
        public TimeSpan KeepAliveInterval { get; set; }

```

**Comment by anurse** [comment]
> I'm not familiar with the low level socket, but I have been hear of `TCP` connection is reliable

It's "reliable" but that doesn't mean you're guaranteed to see a disconnect (see this [blog post](https://www.joyent.com/blog/tcp-puzzlers) for some examples that illustrate many scenarios where a client "disconnects" but the server does not respond to that disconnection).

The ping/pong behavior of WebSockets does provide the opportunity to do this, but the `WebSocket` APIs .NET Core provides don't allow you to observe these ping/pong messages. It's important to note that the ping/pong messages serve two purposes (according to the [WebSocket spec](https://tools.ietf.org/html/rfc6455#section-5.5.2)):

1. Ensuring that intermediate proxies don't terminate the connection, seeing it as an idle HTTP connection
1. Allowing either party (client or server) to check if the other party (server or client) is still there.

Browsers don't expose ping/pong messages to clients, and the .NET APIs don't expose them to servers, so it's difficult to use the built-in ping/pong messages for detecting disconnection. As a result, most applications built on WebSockets (SignalR, for example) ignore these keep-alive messages and send their own ping/pong messages.

If you're concerned about sending too many messages, because your app is sending your own "pings" and the WebSocket is sending **it's** "pings", you probably don't have to worry. Most WebSocket implementations don't try to send a ping if another message is already being sent, since it's not necessary (as the purpose of the ping is to keep the connection "active", and if a message is being sent, it's already active).

**Comment by John0King** [comment]
@anurse  
>  so it's difficult to use the built-in ping/pong messages for detecting disconnection

but since they do send  the ping/pong message, Won't it throw `WebSocketException` when remote side  disconnect?

and if I'm going to use my own ping message , is there any examples of how to handle both custom message and the ping/pong message

**Comment by anurse** [comment]
> Won't it throw `WebSocketException` when remote side disconnect?

The .NET WebSocket APIs will not throw an exception solely because it hasn't received a frame from the client. Your OS TCP stack may close the connection when a client goes silent for a while (i.e. because TCP packets go unacknowledged), but that's beyond the control of the WebSocket APIs and varies by OS. Windows tends to do this quickly (within ~30 seconds) but I've observed Linux distros take upwards of 10 minutes. If the OS terminates the connection, it will indeed manifest as a `WebSocketException`.

> is there any examples of how to handle both custom message and the ping/pong message

I don't have a specific example, no. You'd need to encode a "message type" into your messages and parse that out in order to determine if the message is a normal data message or a ping message. We do this with SignalR in our [Hub Protocol](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md). SignalR has many different message types, just one of which is a "Ping". The specific example would depend on how your normal messages are structured.
