### ISSUE TITLE
Inconsistent IPNetwork.Contains behavior for prefixes which are not at start of subnet range.

### ISSUE THREAD

**Issue by pavel12345** [dotnet/aspnetcore#6674]
### Describe the bug

In AspNetCore/src/Middleware/HttpOverrides/src/IPNetwork.cs

The code below assumes that the prefix will have all bits in position > mask length set to 0. I do not believe that this a requirement for CIDR notation. If it is, it is not applied consistently since the routine will break if the mask is == 0 at a given byte.

            for (int i = 0; i < PrefixBytes.Length && Mask[i] != 0; i++)
            {
                if (PrefixBytes[i] != (addressBytes[i] & Mask[i]))
                {
                    return false;
                }
            }

### To Reproduce
Create instance with Prefix/Prefix Length 192.168.0.1/31.
Contains returns false for 192.168.0.0.

### Expected behavior
Expectation is that 192.168.0.1/31 would match 192.168.0.0

**Comment by Tratcher** [comment]
Hmm, CreateMask should already be dealing with this:
https://github.com/aspnet/AspNetCore/blob/402394347d5a9b3add7decf52af85cbb4e7866b3/src/Middleware/HttpOverrides/src/IPNetwork.cs#L48

**Comment by fvoronin** [comment]
The problem that, because here https://github.com/dotnet/aspnetcore/blob/ce2e3bc723a1265fdd5e40481237bb97719df76d/src/Middleware/HttpOverrides/src/IPNetwork.cs#L45-L62 does not correctly determine if the host address is in the same subnet:
```cs
if (PrefixBytes[i] != (addressBytes[i] & Mask[i])) 
```

We need to get a subnet address for both addresses (for initial address - `PrefixBytes`, and for the address to be checked - `addressBytes`) and compare the octets of those subnet addresses.

Also I think it would be nice to add a check for the `prefixLength` parameter in the constructor for going beyond the range 0-32 for IPv4 and 0-128 for IPv6.
