### ISSUE TITLE
Update Razor Components template to use C# 8 language features

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#6888]
Ex ranges for the weather forecast data.

**Comment by davidfowl** [comment]
I don’t think we should do this. We want to use language features in other templates as well but the plan was to wait on c# 8 to be the default

**Comment by danroth27** [comment]
> We want to use language features in other templates as well but the plan was to wait on c# 8 to be the default

@davidfowl Agreed, is that not happening for .NET Core 3.0?

**Comment by davidfowl** [comment]
It is but I believe it'll just be the default and templates won't have to explicitly specify it.

**Comment by javiercn** [comment]
I'm a bit confused by this and I also think that our templates are not the right place to teach users new language features. It is ok to use new features if they improve a given scenario and make sense, but i'm not a fan of changing some code just because there is a new feature if there is no clear benefit for using the new feature; It actually makes the template harder to understand for existing users.

This bug is very generic and not actionable in this form. If you want action to be taken on it, please go through the template and create a list of places where we want to change the existing template to showcase new language features so that we can have a discussion about it.

**Comment by pranavkm** [comment]
> This bug is very generic and not actionable in this form.

👍 Closing this. We have issues that track specific improvements to our templates
