### ISSUE TITLE
Can Azure App service Metrics be trusted when using Kestrel + AspNet Core Module?

### ISSUE THREAD

**Issue by joshmouch** [dotnet/aspnetcore#7064]
I've been trying to figure out Azure metrics since day one, as either they are badly labelled, incorrect, or something is going on with the IIS+Module+Kestrel pipeline that is making them inaccurate.

The problem I have is that I want to autoscale my app service whenever either the "AppPlan\HTTP Queue Length" gets too large or else the "App\Requests in Queue" gets too large, meaning that the server can't keep up with the load.  However, these values are always 0.  So something isn't adding up.

I tried making a test harness to hit the app as hard as I possibly could.  To the point there it could no longer make TCP connections to the app service, however, these values never went up.

**Comment by anurse** [comment]
I believe this is a limitation of the out-of-process hosting model. Since Kestrel isn't running as part of IIS (but rather IIS is proxying requests to Kestrel), it doesn't participate in these metrics. The [in-process hosting model](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#in-process-hosting-model) (supported in 2.2 and the 3.0 preview releases) integrates ASP.NET Core directly within IIS and may produce better results here.

@shirhatti do you have any thoughts on using App Service autoscaling with ASP.NET Core?
