### ISSUE TITLE
Blazor default templates have nav render issues

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/aspnetcore#7206]
The default templates for Blazor have several issues with the CSS that breaks rendering in the following situations: 

- when the Navigation list contains more than approximately 12 items on either Desktop or Mobile
- the browser is full screen on a 4K monitor

In these cases, you will experience one or more of the following issues:

- The background gradient will cut off at the end of the list, leaving a different color background in the rest of the column.
- At all resolutions, the nav will not scroll properly if there are more items than there is vertical height.
- If the text any nav item is too long, it will overlap the items around it.

My company has fixed these issues in our apps, and my colleague will be making a pull request to submit our changes so that the community can leverage the improved rendering in their apps.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @robertmclaws.
Sure, we would happily consider your PRs.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, assigned to you to review the PR, when it'll be available.

**Comment by adrianwright109** [comment]
@robertmclaws has the PR been submitted yet?

**Comment by robertmclaws** [comment]
My bad, I got sidetracked by another project. Will attempt to push one this evening. Thanks for the reminder!

**Comment by peterblazejewicz** [comment]
@robertmclaws 
Robert, can you attach the screenshots if that is still a problem? I could have a look into this,
Thx!

**Comment by chrissainty** [comment]
I'll have a go at this one if that's ok @SteveSandersonMS? Looks like a bit of CSS needed. I can't find the templates in the repo, could you point me in the right direction?

**Comment by SteveSandersonMS** [comment]
Awesome, thanks! I think the two you want are:

 * https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp
 * https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp

Running the templates from these directories is difficult, so what I'd recommend is simply figure out what `.css` contents you want using a separate normal project, then just copy in the resulting `.css` file here.

Final point, we'd probably only want to take *reasonably* simple CSS changes. If a fix would require something super complicated, or especially if it requires extra boilerplate HTML, then we may prefer not to change it. That's because the templates serve their main purpose in helping people get started and make sense of how things work.

**Comment by chrissainty** [comment]
A really simple solution to this is to add `overflow-y: auto` to the `.sidebar` class. This will allow it scroll independently of the main content. Would you be happy with this as a solution? Or would you prefer a solution which scrolls the entire page as one?

**Comment by robertmclaws** [comment]
I don't think scrolling the whole page is the right approach under this design. I personally think the sidebar should be 100vh and let content inside be scrollable as necessary.

I also think that the icon should be centered because it doesn't throw off the balance between the other lines. Example:

![image](https://user-images.githubusercontent.com/1657085/87748957-5793a500-c7c5-11ea-8cfb-1c692003d5a0.png)

Just my $0.02.

**Comment by TanayParikh** [comment]
Scrolling functionality has been added via https://github.com/dotnet/aspnetcore/pull/41062. 

Is anyone still having issues with high resolution monitors and the gradient being cut off?

**Comment by robertmclaws** [comment]
I'll check it out in the next release. If it's fixed and everyone is ok with it, I'm fine closing out the issue.
