### ISSUE TITLE
Incorrect empty prefix during validation (Razor Pages with IFormFiles)

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet/aspnetcore#7238]
I'm trying to troubleshoot an issue reported in the [FluentValidation](https://github.com/JeremySkinner/FluentValidation/issues/1029) repo, where sometimes during validation the model `prefix` incorrectly is passed to the ValidationVisitor as an empty string. This seems to be specifically related to binding `IFormFiles` within Razor Pages apps. 

This seems to be something that @dougbu was working on in https://github.com/aspnet/mvc/issues/7562 but it doesn't look like it's fixed in all cases.

### To Reproduce
A full repro can be found at https://github.com/vrao1020/FluentValidationTest, but essentially the following is required:

```csharp
// Razor page model
public class IndexModel : PageModel
{
    [BindProperty]
    public ObjectB ObjB { get; set; }
    public IActionResult OnGet()
    {
        return Page();
    }

    public IActionResult OnPost()
    {          
        if (!ModelState.IsValid)
        {
            return Page();
        }
    
        return Page();
    }
}

// Model
public class ObjectB
{
    public IFormFile FileToUpload { get; set; }
}

// Form
@page
@model IndexModel
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="ObjB.FileToUpload"></label><br />
        <input asp-for="ObjB.FileToUpload" type="file" accept=".png,.jpg,.bmp" /><br />
        <span asp-validation-for="ObjB.FileToUpload" class="text-danger"></span>
    </div>
    <input type="submit" value="Submit"/>
</form>
```

- In the case where *no file is specified* when the form is submitted, the prefix passed to the `ValidationVisitor` for the `ObjectB` property is correctly `ObjB`.
- In the case where a file *is uploaded* with the form, the prefix passed to the ValidationVisitor is incorrectly an empty string. 

@rynowak @dougbu could either of you help me understand what's going on here and whether this behaviour is correct (it doesn't seem like it is)?

I can see that in `ParameterBinder.EnforceBindRequiredAndValidate`, some code has specifically been added to handle empty prefixes (https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L322-L340) Is this related to handling this situation? If so, should this code also be present in the other case in the case above in that method? (https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L313) ? 

Thanks!

**Comment by dougbu** [comment]
After debugging a bit, I suspect our `ValidationStateDictionary` needs an entry to pass the correct `ModelState` key along to the validation system when `FormFileModelBinder` does its fallback.

Oddly, I expected the error to be consistently added to a `FileToUpload` entry in `ModelState` as-is (never `ObjB.FileToUpload` as the form expects). Need to debug more with a repro in this repo because some classes are too optimized for the debug symbols to be useful&hellip;

**Comment by JeremySkinner** [comment]
Thanks - I figured it'd be something related to that but I felt like I was starting to go down the rabbit hole trying to debug the model binding process. For now I've asked the user to work around the problem by explictly specifying `[BindProperty(Name = "ObjB")]`. Let me know if there's any more info you need from me.

**Comment by lakeman** [comment]
Are you hitting this condition in [ParameterBinder](https://github.com/aspnet/AspNetCore/blob/14b7184c09ac715348e556df7706ea7647cfae42/src/Mvc/Mvc.Core/src/ModelBinding/ParameterBinder.cs#L140)?

This behaviour of changing model binding based on the existence of values seems problematic. There are a number of edge cases that can cause surprising behaviour (hence why I'm commenting here instead of creating a new issue).

IMHO the names of bound fields should be determined only from compile time information. We should remove this test and always use the parameter name.

My own motivating reduced case;

```C#
class Model {
    [BindProperty]
    public Dictionary<int, ...> Dict { get; set; }
    [BindProperty]
    public string Value { get; set; }
}
```
If the dictionary is empty, this leads to `"Value"` being converted to a key value for the dictionary, which fails;
```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper.ConvertSimpleType(Object value, Type destinationType, CultureInfo culture)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
...
```

However if the dictionary had a compatible key type, this would lead to other surprising behaviour.

To work around this issue I have to plaster `BindProperty(Name = nameof(Property))` everywhere I'm using a collection that might be empty. 

I believe it would be more appropriate to force people to explicitly use `BindProperty(Name = "")`, if that is the behaviour they want. Otherwise they could also be surprised if the name of one of their keys is the same as their property name.

**Comment by pranavkm** [comment]
Moving this out to a later milestone.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by lakeman** [comment]
I finally got around to writing a workaround for my specific case, that ensures no collections with `[BindProperty]` and no explicit name can bind against an empty prefix;

```c#
    public class BindMetadataProvider : IBindingMetadataProvider
    {
        private bool IsImplementation(Type type, Type interfaceType) =>
            type.GetInterfaces().Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == interfaceType).Any();

        public void CreateBindingMetadata(BindingMetadataProviderContext context)
        {
            IModelNameProvider nameAttrib = null;
            if (context.BindingMetadata.BinderModelName == null 
                && context.Key.MetadataKind == ModelMetadataKind.Property
                && context.BindingMetadata.IsBindingAllowed
                && (nameAttrib = context.Attributes.OfType<IModelNameProvider>().FirstOrDefault())!=null
                && nameAttrib.Name == null
                && IsImplementation(context.Key.ModelType, typeof(ICollection<>)))
                context.BindingMetadata.BinderModelName = context.Key.PropertyInfo.Name;
        }
    }

   mvcOptions.ModelMetadataDetailsProviders.Add(new BindMetadataProvider());
```
