### ISSUE TITLE
[Announcement] IHostingEnvironment's and IApplicationLifetime's marked obsolete and replaced

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#7749]
When Microsoft.Extensions.Hosting was introduced in 2.1 some types like `IHostingEnvironment` and `IApplicationLifetime` were copied from **Microsoft.AspNetCore.Hosting**. Some 3.0 changes cause apps to include both the **Microsoft.Extensions.Hosting** and **Microsoft.AspNetCore.Hosting** namespaces. Any use of those duplicate types causes an "ambiguous reference" compiler error when both namespaces are referenced.

This error has been addressed in **3.0.0-preview3** by marking the following types obsolete and replacing them with new types. There have not been any behavioral changes made for the new types, only naming.

Obsolete types (warning):
```
Microsoft.Extensions.Hosting.IHostingEnvironment
Microsoft.AspNetCore.Hosting.IHostingEnvironment
Microsoft.Extensions.Hosting.IApplicationLifetime
Microsoft.AspNetCore.Hosting.IApplicationLifetime
Microsoft.Extensions.Hosting.EnvironmentName
Microsoft.AspNetCore.Hosting.EnvironmentName
```

New types:
```
Microsoft.Extensions.Hosting.IHostEnvironment
Microsoft.AspNetCore.Hosting.IWebHostEnvironment : IHostEnvironment
Microsoft.Extensions.Hosting.IHostApplicationLifetime
Microsoft.Extensions.Hosting.Environments
```

Note the new `IHostEnvironment` `IsDevelopment`, `IsProduction`, etc. extension methods are in the **Microsoft.Extensions.Hosting** namespace which may need to be added to your app.

For 3.0 both the old and new types will be available from HostBulder's and WebHostBuilder's dependency injection containers. The old types will be removed in 4.0.

**Comment by Tratcher** [comment]
Updated to include EnvironmentName -> Environments.

**Comment by jwbats** [comment]
I am trying to access IWebHostEnvironment in a class library, referenced by my web project. It contains my business logic.

Despite having installed Nuget packages:

- Microsoft.AspNetCore.Hosting
- Microsoft.AspNetCore.Hosting.Abstractions
- Microsoft.Extensions.Hosting

And having using clause:

`using Microsoft.AspNetCore.Hosting`

The type 'IWebHostEnvironment' isn't known in that very same code file.

When pressing F12 on IWebHostEnvironment in my Startup.cs (which does know it), I end up in a file that says it's in assembly Microsoft.AspNetCore.Hosting.Abstractions.

So why can't I access it in another project that has the Abstractions Nuget package?

I'm at a loss. How do I access IWebHostEnvironment in my non-web project?

**Comment by davidfowl** [comment]
> I am trying to access IWebHostEnvironment in a class library, referenced by my web project. It contains my business logic.

Do you need access to the WebRoot? If yes, then your class library needs to target netcoreapp3.0 (see https://github.com/aspnet/Announcements/issues/324) and it needs a `<FrameworkReference Include="Microsoft.AspNetCore.App" />`

**Comment by jwbats** [comment]
@davidfowl, that's exactly what I needed. Problem solved. Tnx.

And on a sidenote, I believe you're the same guy who provided some BackgroundService example code a long time ago on some other site. My project makes ample use of it and it works very well.

So that for that, too!

**Comment by voloda** [comment]
> > I am trying to access IWebHostEnvironment in a class library, referenced by my web project. It contains my business logic.
> 
> Do you need access to the WebRoot? If yes, then your class library needs to target netcoreapp3.0 (see [aspnet/Announcements#324](https://github.com/aspnet/Announcements/issues/324)) and it needs a `<FrameworkReference Include="Microsoft.AspNetCore.App" />`

So you are actually asking to switch from .NET Standard library to .NET Core specific one? This is a major step back IMHO.

**Comment by davidfowl** [comment]
> So you are actually asking to switch from .NET Standard library to .NET Core specific one? This is a major step back IMHO.

Why do you say that?

**Comment by voloda** [comment]
> > So you are actually asking to switch from .NET Standard library to .NET Core specific one? This is a major step back IMHO.
> 
> Why do you say that?

Well - with .net standard targeting I can move things around easily. We developed bunch of stuff using it. I can simply use such interface and perform own implementation if needed.

Unless .netcoreapp3.0 is alias for netstandard2.1 (which IMHO it is not) then you are asking us to re-target all our libraries which is a major deal then.

This will make them .NET Core specific and those will stop working with regular framework. At minimum it will require to do something regarding multi-targeting.

I love the concept of netstandard since it was much more understandable than whatever targeting before - thus IMHO step back to history :-1:.

**Comment by davidfowl** [comment]
Not all of your libraries but the ones that use ASP.NET Core.

**Comment by davidfowl** [comment]
> This will make them .NET Core specific and those will stop working with regular framework. At minimum it will require to do something regarding multi-targeting.

That's the case no matter what. NET Standard 2.1 is never coming to .NET Framework.

**Comment by bruno-garcia** [comment]
I'm assuming libraries target `netstandard2.0` which today work with ASP.NET Core 2.0 (on .NET Core 2.x and .NET Framework 4.6.1+) would require an new target to `netcoreapp3.0` and some `#ifdef` to work around the breaking changes and msbuild `Condition=` to either import the nuget packages or add the framework reference.

If my understanding is correct, I hope I'm on the right track here:

https://github.com/getsentry/sentry-dotnet/pull/308/files#diff-d22b9fb3093ec3cec416174443361588R4-R26

**Comment by voloda** [comment]
> > This will make them .NET Core specific and those will stop working with regular framework. At minimum it will require to do something regarding multi-targeting.
> 
> That's the case no matter what. NET Standard 2.1 is never coming to .NET Framework.

Yep - that is what I understand, 

The thing here is that either the .NET Standard 2.0 promise to work with .NET Core 3.0 is broken or that ASP.NET Core is not actually part of .NET Standard.

I am not sure which of above is worse.

Let me explain:

I recently migrated one small project to .NET Core 3.0 - this was kind of OK...

* Now I am migrating larger one and finding that I cannot rely on consuming .NET Standard 2.0 SDK we built around the ASP.NET Core 2.2
* Everything compiles but starts throwing missing method exceptions in runtime
* So without having all the internal references targeted either to .NET Standard 2.1 or switching them to NETCoreApp3.0 I cannot reliably say that it will work - simply the .NETCoreApp3.0 consumes netstandard2.0 references which contain calls which are no longer available.
* Now I need to keep support for both - .NETStandard2.0 and .NET Core 3.1 aka framework supposedly implementing .NET Standard 2.1

I am commenting here since that was the first step I came thru - but there are others regarding logging (and I guess more will come once I go thru it).

Obviously I understand that you need flexibility etc. and perhaps stuff will converge once .NET 5 will be here but in meanwhile it is going to be just a mess.

**Comment by davidfowl** [comment]
> The thing here is that either the .NET Standard 2.0 promise to work with .NET Core 3.0 is broken or that ASP.NET Core is not actually part of .NET Standard.

ASP.NET Core was never *part* of .NET Standard, but it *targeted* .NET Standard. Those 2 things are completely different and it's important to understand the implications. It's correct to say that some ASP.NET Core packages are incompatible between 2.x and 3.x, it's incorrect to say that .NET Standard (all version) is incompatible with .NET Core 3, it is compatible.

ASP.NET Core made several breaking change in this release that may or may not affect your libraries. We also made ASP.NET Core 3.0 target .NET Core only.

> Everything compiles but starts throwing missing method exceptions in runtime

What throws method missing exception? Do you have an example?

> So without having all the internal references targeted either to .NET Standard 2.1 or switching them to NETCoreApp3.0 I cannot reliably say that it will work - simply the .NETCoreApp3.0 consumes netstandard2.0 references which contain calls which are no longer available.

It doesn't. See my comment above about *specific* ASP.NET Core 2.x packages, not .NET Standard.
