### ISSUE TITLE
@aspnet/signalr@1.1.2 hubConnection.on with `this` points to HubConnection

### ISSUE THREAD

**Issue by ibraheemalkilanny** [dotnet/aspnetcore#8279]
### Describe the bug
For example:

```
export class SignalRService {

  constructor(
    @Inject('BASE_URL') private baseUrl: string
  ) {
  }

  startConnection(): Promise<void> {
    this.hubConnection = new HubConnectionBuilder()
      .withUrl(`${this.baseUrl}notification`)
      .build();

    return this.hubConnection.start()
      .then(() => {
        console.log('Connection started');
        this.hubConnection.on("onEvt", this.onEvt);
      })
      .catch(err => console.log('Error while starting connection: ' + err));
  }

  private onEvt(json: string) {
   console.log(this); // prints HubConnection !!
  }
}
```
### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code (angular 7.2.7)

### Expected behavior
`this` should point to object of type `SignalRService` but `HubConnection` is received

**Comment by anurse** [comment]
This is expected behavior because of how `this` works in JavaScript. It's *entirely controlled* by the **caller** of the function instead of being defined by where the function is defined (like in C# or other languages). See the [documentation on `this` on Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) for more detail.

Since `HubConnection` is calling your function, it ends up being assigned as `this` by default. This is how JavaScript works, and it is unfortunately quite different from other languages that use `this`. You can use `.bind` or an arrow function to force a specific value for `this`. My suggestion would be to change the following code:

```javascript
       this.hubConnection.on("onEvt", this.onEvt);
```

To something like this:

```javascript
       this.hubConnection.on("onEvt", (json) => this.onEvt(json));
```

It looks the same but because you are using an arrow function (`() =>` syntax) the `this` value inside your arrow function is guaranteed to be the same as the `this` value outside the function (i.e. the `SignalRService` instance), so the call should succeed.
