### ISSUE TITLE
Consider adding IPNetwork.Parse

### ISSUE THREAD

**Issue by svick** [dotnet/aspnetcore#8606]
### Is your feature request related to a problem? Please describe.

I've been reading [a blog post by Jon Skeet](https://codeblog.jonskeet.uk/2019/03/17/hosting-asp-net-core-behind-https-in-google-kubernetes-engine/) and noticed this code in it:

```c#
options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("130.211.0.0"), 22));
```

I think that this code is quite verbose and it would be easier to understand if it would be possible to use IP subnet syntax here.

### Describe the solution you'd like

A new method:

```c#
public class IPNetwork
{
    public static IPNetwork Parse(string subnetString);
}
```

It could be used like this:

```c#
options.KnownNetworks.Add(IPNetwork.Parse("130.211.0.0/22")));
```

If this method was added, it would probably also make sense to add a `Try` version of it:

```c#
public static bool TryParse(string subnetString, out IPNetwork network);
```

What do you think?

**Comment by blowdart** [comment]
This would probably fit better in .NET Core, along with the rest of the IPAddress classes. Might I suggest asking [there](https://github.com/dotnet/corefx/issues)?

**Comment by svick** [comment]
@blowdart [The `IPNetwork` class is already part of ASP.NET Core](https://github.com/aspnet/AspNetCore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Middleware/HttpOverrides/src/IPNetwork.cs), I'm just suggesting adding few methods to it.

Or are you saying the whole class should be moved to .Net Core?

**Comment by blowdart** [comment]
In my opinion, yes. Of course other may disagree :) Feels weird it's in ASP.NET when it could be used elsewhere

**Comment by khellang** [comment]
There's already [a corefx issue](https://github.com/dotnet/corefx/issues/36030) that's related to this.

**Comment by halter73** [comment]
API Review Notes.

1. Do. we want to support `IParsable<TSelf>`? No. This isn't even implemented by `IPAddress`.
2. In the PR, the input is `ROS<char>` instead of string. `IPAddress` takes both, but the `string` overloads are probably legacy. An implicit conversion exists. I think this will prevent discovering the `TryParse` method in `RequestDelegateFactory` (RDF), but we should probably fix RDF to find the `ROS<char>` version.
3. Do we like `networkSpan` as the parameter name? `subnetSpan`? Let's stick with "network" since the type name is `IPNetwork`

```diff
namespace Microsoft.AspNetCore.HttpOverrides;

public class IPNetwork
{
+    public static IPNetwork Parse(ReadOnlySpan<char> networkSpan);
+    public static bool TryParse(ReadOnlySpan<char> networkSpan, IPNetwork? network);
}
```

API Approved! We think this matches the current PR.
