### ISSUE TITLE
Add Pipelines-related http features in TestServer

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#8660]
Epic https://github.com/aspnet/AspNetCore/issues/8829
Split from https://github.com/aspnet/AspNetCore/issues/7815

We should support the Pipe Goodness on TestServer.

We'd remove the stream-based implementation and use pipes. Stream-based implementation would then be a wrapper around the pipes.

**Comment by JamesNK** [comment]
Something to test/implement with this issue: ensure that `Response.StartAsync` correctly sets `Response.HasStarted` to true in TestServer.

**Comment by anurse** [comment]
Bumping out of preview4. I don't think this is a critical thing for preview 4, but feel free to debate :).

**Comment by JamesNK** [comment]
I would like it. Does that make it critical? 🙃

Seriously though, I was looking into https://github.com/grpc/grpc-dotnet/issues/144 yesterday and TestServer never sets Response.HasStarted when the response content is flushed, and that makes our functional tests a little less trustworthy. For example, it is not an error to send headers after writing content. I'm considering moving some of the functional tests to use a spun up Kestrel instance because I don't trust how accurate TestServer is.

But I understand there is higher priority work.

**Comment by anurse** [comment]
We just don't have the capacity for this in 3.0. I'll put this in 3.1 for now, and if someone feels so inspired, we can review a PR :)

**Comment by anurse** [comment]
@JamesNK does your PR satisfy this need? Are we ready to close this?

**Comment by JamesNK** [comment]
My PR satisfies my need to have StartAsync work correctly.

TestServer still needs to be refactored to use pipes.

**Comment by anurse** [comment]
Ok, we'll keep this around. There may be capacity later when the unknown unknowns become known knowns.

**Comment by anurse** [comment]
We don't expect to have the capacity in 3.0. Lots on the queue. This is a good candidate for 3.1 though.

**Comment by alefranz** [comment]
I had a look at this and I believe that most of work has been done as part of https://github.com/dotnet/aspnetcore/issues/11598.

**Comment by anurse** [comment]
Looks like you're correct and #11598 has a better listing of what is done and not yet done. I'm going to close this as a duplicate of it.
