### ISSUE TITLE
Papercuts with GenerateReferenceAssemblies.ps1

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#8680]
Misc potential papercuts to consider improving:
- Is there any way to automatically do this instead of detecting/failing PRs via code check and needing manual script run + update
- After running the script recently it checked out every ref file with whitespace changes
- Add a way to target a specific project instead of running it on everything?

**Comment by JunTaoLuo** [comment]
To follow up on this issue:
1. By design, I think we'll keep this step manual. We should be aware of all the API breaking changes we're making.
2. This should be a non-issue if autocrlf is configured locally. Even if there's a warning `warning: LF will be replaced by CRLF`, the file will be ignored when you execute `git add`. There is a case to be made for ignoring whitespace changes during CodeCheck so I'll make a PR for this.
3. This is documented at https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md

**Comment by JunTaoLuo** [comment]
Actually for 1. we have some ideas to run parts of reference assembly verification locally. cc @Tratcher

**Comment by Tratcher** [comment]
E.g. After a local build you can diff the built dll against the current ref assembly and warn if they don't match. This should be compatible with incremental build (e.g. skipped if an assembly is not re-built).

We could take this a step further and automatically update the ref assemblies if there are differences. The review for breaking changes will happen when you go to commit the change, and again as part of the PR.

**Comment by JunTaoLuo** [comment]
FYI I did some preliminary investigation and it seems like it's quite feasible to generate ref assemblies on build. in AspNetCore, it increased by ~10 seconds: Time Elapsed 00:04:01.99 to Time Elapsed 00:04:10.44. However, I ran into some concurrency issues which I don't have time to resolve right now. We will consider this in the future.

**Comment by dougbu** [comment]
Will go away mostly in 'release/3.1' when I update the Arcade 'release/3.x' code to support better GenAPI and remove the need for hundreds of *.manual.cs files. Will also go away in 'master' when we complete #14801.
