### ISSUE TITLE
Add support for pinging and timeouts to C++ client

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#8721]
Epic #8720 

* Sending pings from the client
* Timing out the server connection based on server activity (pings, etc.)

**Comment by grahambunce** [comment]
@BrennanConroy Can I ask what this refers to? The .NET client sends a hearbeat that can be intercepted on the server so that the client can be indicated as "alive" by server side logic.

Does this suggest that this feature does not exist in the C++ client (i.e. it will not send the keep alive for a WebSocket connection?)

**Comment by grahambunce** [comment]
Thanks. Can I ask why this has been bumped to .net 7? It seems pretty important for any client to keep the connection alive. One of the benefits of the .net client is that it does this automatically, indicates via events when connections are dropped and has automatic reconnection logic.

**Comment by BrennanConroy** [comment]
> Can I ask why this has been bumped to .net 7?

Because the client is still a work in progress.

**Comment by grahambunce** [comment]
Understood. I know the client is still alpha (beta?) but we’re looking to use it right now in an IOT environment instead of wrapping the .net client itself (main app is C++/QT). It is likely that missing parity features (such as this) will be added outside the .net release cycle?

Just trying to decide on the best options for us.

**Comment by BrennanConroy** [comment]
> It is likely that missing parity features (such as this) will be added outside the .net release cycle?

Yes, the project "ships" from a different repo. You can either consume it from source (so get changes as they come in or whenever you want them), or wait for us to update vcpkg with a newer commit (happens occasionally after a batch of changes go in). .NET 7 doesn't really have a meaning to the C++ client, it's just how we track things in this repo.

**Comment by grahambunce** [comment]
Ok, thank you

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/SignalR-Client-Cpp/pull/77
